### ISSUE TITLE
Notification mail + v0.85 : demandeur non renseigné

### ISSUE THREAD

**Issue by Boris31** [pluginsGLPI/formcreator#100]
Bonjour,

Sur GLPI 0.85.3 avec FormCreator 0.85-1.2.3, lorsqu'un ticket est créé par l'intermédiaire d'un formulaire, dans la notification mail reçue le champ demandeur est vide or il est bien renseigné dans le ticket créé et apparait ensuite dans les notifications lors de la création de suivi, tâche,...
Ce problème n'est pas présent avec une version GLPI 0.84 et FormCreator 0.84-2.1.4

**Comment by Boris31** [comment]
Pour info, après recherche j'ai trouvé la solution.
Dans le fichier targetticket.class.php, à la ligne 719 : 
- -       $datas['_users_id_requester']   = 0;
- +      $datas['_users_id_requester']   = $_SESSION['glpiID'];

**Comment by neeftarah** [comment]
La version 0.85-1.2.3 de Formcreator apporte une nouvelle fonctionnalité permettant de choisir les personnes ou groupes ajouter en tant que demandeur / observateur / attribuer à.

Il est possible qu'une migration depuis une ancienne version de Formcreator n'ai pas récupéré les valeurs par défaut (demandeur = personne répondant au formulaire et observateur = valideur).
(NB : La ligne dont vous proposez la modification à d'ailleurs été modifiée comme tel pour cette évolution)

Pouvez-vous me confirmer que dans la configuration de votre formulaire, dans destination > votre ticket, les acteurs sont bien définit ?

Si non, avez-vous fait une migration depuis une ancienne version ? Si oui, laquelle ?

**Comment by Boris31** [comment]
Bonjour,

Merci pour votre retour et votre travail.
La version 0.85-1.2.3 est la première que j'installe, aucune mise à jour donc.
Je vous confirme que les acteurs sont bien définis dans la destination.

En re-téléchargeant les dernière releases des version 0.84 et 0.85, je vois bien la récupération du "requester" dans la 0.84 mais j'ai bien un "requester" à 0 dans la 0.85...
