### ISSUE TITLE
Problem with field visibility upon validation error

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/formcreator#1000]
**Describe the bug**
If you create a form with a select field containing accents, another field which visibility depends upon the first field and a third field which you set a validation rule (for example, a text field with a max length of 5). If you set the value of the selectbox so that your key field will appear and subsequently enter a string too long for the third textbox, when you come back, the second field will be hidden even though the selectbox has the correct value.

**To Reproduce**
1) Create a first field with two values containing accents (ex: école, hòpital)
2) Create a second field that should appear only if "école" is selected
3) Create a third text field with a max length of 5
4) Make sure "école" is selected in the first field and enter a string too long in the third field
5) Submit the form

**Expected behavior**
I would expected to be taken back to the form and have all three fields visible. Instead, the second field is hidden despite the selectbox actually being on the correct value for it to appear.

**Additional context**
I've located the problem in file selectfield.class.php and the method getAnswer(). The function does 

`$value = $this->getValue()`

The problem is that when you're coming back from a validation error, every accented character is actually an html entity. So this means that the condition

`in_array($value, $values)`

fails and what's returned is not the actual value, but the default value. I've temporarily fixed this changing the above line to 

`$value = html_entity_decode($this->getValue())`

On the other hand, I have no idea why the list's value contains html entities ONLY when you're coming back from a validation error. I'll leave that up to you guys.

**Comment by Synairgis** [comment]
Ok, so my previous patch only fixed part of the problem mentioned above. Namely, I did not check apostrophes. So to be thorough, I recommend altering my list of proposed values by the following:

L'école
L'hôpital

Then, make sure you do not allow empty values and that there are no default values defined for the selection list. Then, link the visibility of the second question to the first value of the list (basically, visible only when "L'école" is selected). With all this set into place, visualize the form.

1) Is the field that should be visible actually visible?
2) Enter a text too long in question 3 and submit the form. When you return, is the field still visible?
3) Change the value of the selectbox.
4) Enter a text too long in question 3 and submit the form. When you return, did the list keep its value and is the visibility of the field still correct? 

Now here's the thing that's important. You also need to make the above verifications when the question's been modified. So basically, just open up the edit question window and click save. That'll do the trick. Then just redo steps 1-4 to check everything's still working.

My previous patch did not handle all those special cases. I ended up having to modify the code yet again. Here's my new "getAnswer" function for selectfield.class.php:

```PHP
public function getAnswer() {
      $values = $this->getAvailableValues();
      $value  = stripslashes( html_entity_decode($this->getValue(), ENT_QUOTES, 'UTF-8'));

      foreach($values as $index => $val)
         $values[$index] = stripslashes( html_entity_decode($val, ENT_QUOTES, 'UTF-8'));
      
      return in_array($value, $values) ? $value : $this->fields['default_values'];
}
```

**Comment by btry** [comment]
Hi

For your information I began today the PR #1007 where I want to remove all encoding problems in questions. I plan to extend it to handle encodings in form answers in the hope to not need html decoding. 

Will you agree to test it soon ? Your feedback will be really appreciated.

**Comment by btry** [comment]
Hi

This issue should be solved now. I close.
