### ISSUE TITLE
Bug with select in formcreator

### ISSUE THREAD

**Issue by bubulutin** [pluginsGLPI/formcreator#1001]
**Describe the bug**
In formcreator with  glpi 9.2.1 and plugin formcreator 2.6.3 wehnyou choose "select" for a field 
in the description you have blank 

**To Reproduce**
1. Go to 'form...'
2. Click on '.add a question...'
3. select title "localisatiion" puis select Type = "select"
4-default value 2 puis value 1 2 3 4 5 
5- save the question

**Expected behavior**
When we fill in  the form, we scrolled
we select 3 and we saved 
We expected to see in the description of ticket localisarion : 3 
but i see localisation : 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 
 - Browser [e.g. chrome, safari] firefos esr 45.1.1
*
You have to know that it is ok with checkboxes and radio button
Coul you pleased help me to find a solution ?
thank you

**Comment by btry** [comment]
Hi

I'm sorry I could not handle this issue in time. As there are new versions of the plugin released, and incoming, this issue is obsolete. Please open a new ticket if needed.
