### ISSUE TITLE
Problem with radio button value upon validation failure

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/formcreator#1006]
**Describe the bug**

When you create radio buttons with apostrophes in the label and then hit a validation error, upon returning to the form, your radio button selection is gone.

**To Reproduce**

1. Create a form with two fields, one radio with apostrophes in the label (ex. it's good, it's awesome) and a second text field where you'll put a validation rule (ex. max length = 5).
2. Click on one of the two radios and then enter a text too long so that the validation fails
3. Click submit. When you get taken back to the page, the radio button is no longer checked

**Expected behavior**

When the validation fails, I would expect the radio button to keep the value I previously selected. Instead, either I get the default value or nothing at all.

**Additional context**

I've located the problem inside the radiosfield.class.php. Inside the displayField() method, there's this line:

`$checked = ($this->getValue() == $value) ? ' checked' : '';`

The problem here is twofolds. You see, `$this->getValue()` returns apostrophes that are both escaped with a backslash AND in html entity form while `$value` returns the normal string with every character plainly as it is. Therefore, the "checked" condition is never true.

**Comment by btry** [comment]
Hi

With the development version if the plugin I don't reproduce.

Can you tell your current version of Formcreator ?

![image](https://user-images.githubusercontent.com/14139801/40485403-b38399c8-5f5e-11e8-835a-94388beffbc7.png)

**Comment by Synairgis** [comment]
As mentioned over the phone, the bug actually happens when you correct the question, because apostrophes are initially encoded as html entities... but when you correct the question, they're reverted back to normal apostrophes. For the moment, here's the patch that I applied:

`$val = stripslashes(html_entity_decode($this->getValue(), ENT_QUOTES | ENT_XML1, 'UTF-8'));`
`$checked = ($val == html_entity_decode($value, ENT_QUOTES | ENT_XML1, 'UTF-8')) ? ' checked' : '';`

**Comment by btry** [comment]
Hi 

I think this issue is solved with versions 2.7 and later

**Comment by btry** [comment]
Hi

I close this issue, it should  be solved now.
