### ISSUE TITLE
2 problems in one : errors in class files and forms are not filled with input values

### ISSUE THREAD

**Issue by Kailin69** [pluginsGLPI/formcreator#1009]
A strange behavior appears few days ago.

We only have one form for new collaborators in our company.

Now, when someone is using the form, the input values are not the one the user wrote, but some random values.

And when checking the form, I get errors in form.class.php and question.class.php

1. Go to forms
2. Click on a question
3. See error

**Screenshots**
I made a screenshot because it's really odd that the whole thing went wrong just a few days ago.

**Desktop**
 - OS: WIN 8.1
 - Browser : Firefox
 - Version: latest

![erreur-glpi-formcreator](https://user-images.githubusercontent.com/39730295/40654816-a5e3cc68-633f-11e8-88fe-20bf2adc0968.jpg)

**Comment by btry** [comment]
Hi

This ticket is very old. I think the problem is solved now as I don't had any similar feedback. I close. If you still have problems, please open a new ticket with up to date inforamtion.
