### ISSUE TITLE
Question movement not registered

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/formcreator#1010]
**Describe the bug**
When you create a form with various questions visualize the form, then move questions around, the change won't be registered until you actually refresh the page.

**To Reproduce**
1) Create a form with two questions
2) Visualize the form
3) Go back to the question tab and swap the question's order
4) Visualize the form again and the question's order will remain the same

**Expected behavior**
I would expect that moving questions around would be immediately noticed by GLPI and not have to actually refresh the page manually for things to be detected.

**Additional context**
The problem here is rather simple (though the fix might not be, I don't really know). Usually, when you apply a modification to a question, it reloads the entire page when you save. This, in turn has the side-effect of removing the "Visualize" tab from memory and forcing GLPI to reload it from scratch when you go to it again. Moving questions around, on the other hand does NOT reload the page. So if you've been to the "Visualize" tab before moving your questions around, GLPI will display what it already has... in this case, an outdated version of the form with questions in the wrong order.

**Comment by btry** [comment]
Hi

This happens because when a tab was loaded by GLPI, it is added to the DOM. Going back to the tab simply un-hides it. I'm not sure there is something to do. 

I'll focus on more impacting issues and keep this one for a period of time where I'll  be more available.

**Comment by btry** [comment]
I investigated and for now I don't have a reliable solution to force refresh of a tab when something happens in an other tab. The issue is that GLPI does not provide a reliable way to find the content of a tab with an ID. 

We need an improvement in GLPI first.

**Comment by btry** [comment]
Hi

This problem should be solved since version 2.11.x

If you still observe such behavior, please open a new ticket wuth up to date information.
