### ISSUE TITLE
Restricted access doesn't work when it has sub-category

### ISSUE THREAD

**Issue by kedson42** [pluginsGLPI/formcreator#1012]
Hello guys.
I’ve found a very specific problem. 
I want to create a form with restricted access. It works fine most of the time, except when I have sub-categories.
For some reason, when I have a form with a category that is a child of another category, GLPI ignores the restricted access and let any user see the father category. Users cannot see the form itself, just the father category. It’s very strange. Since here we created a catalog for self-service users and another for IT-users, we don't want self-service users seeing IT-related categories.

![3](https://user-images.githubusercontent.com/34751754/40843052-1f3a1ea8-6586-11e8-81c5-4101193b4075.PNG)

![345](https://user-images.githubusercontent.com/34751754/40843060-2872bfc0-6586-11e8-8f1c-b8c67b51f220.PNG)

![4353454](https://user-images.githubusercontent.com/34751754/40843142-6e493dc6-6586-11e8-8a69-71e83eed1831.PNG)

![1](https://user-images.githubusercontent.com/34751754/40843080-3979da7e-6586-11e8-8c42-070cd5e7ee3e.PNG)

![fdfd](https://user-images.githubusercontent.com/34751754/40843226-ab6ae7d6-6586-11e8-9bac-687513f7676b.PNG)

![6](https://user-images.githubusercontent.com/34751754/40843263-c5e1427c-6586-11e8-9967-5378447ab95d.PNG)

Here a GIF to help understand the behavior.

![pqp](https://user-images.githubusercontent.com/34751754/40843530-a7c5463e-6587-11e8-92ca-e9f63a5aae35.gif)

**Comment by kedson42** [comment]
Anyone?

**Comment by kedson42** [comment]
Hi
Indeed it has little impact. Some users are seeing useless categories, but not the form itself.

But I'm reporting this bug anyway, so the fix can be added in future releases.

**Comment by btry** [comment]
I'll investigate after the release 2.6.4. I hope to have enough time to find a fix for 2.7.0

**Comment by kedson42** [comment]
Thank you!

**Comment by btry** [comment]
Hi 

This issue is a false positive : when a user is on the service catalog, the user uses a self-service profile, and in your example the form is restricted to super admins. The restrition applies to the current profile of the user, not all profiles the user is granted to use.
