### ISSUE TITLE
Actor type question incorrectly setting one of the people as first follow up actor

### ISSUE THREAD

**Issue by kedson42** [pluginsGLPI/formcreator#1013]
Hello guys.

When I create a form with an actor type question, one of the users is randomly chosen to be set as the first follow up actor.
This behavior makes whoever will answer the ticket confused, since the person may not be sure of who really opened the ticket.

![hhhhh](https://user-images.githubusercontent.com/34751754/40844715-0e7518c0-658b-11e8-917e-f4e6b6cc49ac.PNG)

![rrrrr](https://user-images.githubusercontent.com/34751754/40844735-188d4274-658b-11e8-8250-04733500fbe0.PNG)

![lococolo](https://user-images.githubusercontent.com/34751754/40844796-3f8403fe-658b-11e8-8c05-2998ddf3df4c.PNG)

![kkkkkk](https://user-images.githubusercontent.com/34751754/40844761-285a863a-658b-11e8-812b-95da9c3173a8.PNG)

**Comment by btry** [comment]
Hi

I know this is an old ticket. If you're still following its progress, please give a try with the develop branch (incoming 2.7.0)

**Comment by btry** [comment]
This might be related to #1381. PR in progress #1391

**Comment by btry** [comment]
Hi

This ticket is too old. I close. If the problem persists with the latest version, please open a new ticket.
