### ISSUE TITLE
[glpi 9.3 forms 2.6.4] ticket associated item /form is missing

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#1014]
**To Reproduce**
Accept a form with ticket creation.

**Expected behavior**
In the ticket section "items" the forms is displayed.

**Screenshots**
http://forum.glpi-project.org/viewtopic.php?pid=348685#p348685

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox
 - Version newest

**Additional context**
the ticket title is "list view problems" you can see it in ticket list view but in the main view of the ticket the associated object are not even more displayed with 9.3.
**In my test system it is not viewed in items section.**

**Comment by Armin83** [comment]
FYI 9.3 nightly tarball today works. I don't know why. (2.6.3)

![2018-06-14 20_54_56-window](https://user-images.githubusercontent.com/19192087/41432132-639e32a2-7015-11e8-8d09-0375b70ad70b.png)

**Comment by Armin83** [comment]
I can see this with super-admin rights but it is not enough to have read and update rights on entity!
I think something is missing in my profile-rights for this or bug / wrong check.

**Comment by Armin83** [comment]
I have a profile xyz this profile have update rights on entity but this don't work. i will provide your screenshot from my testsystem but at the moment it's little broken.

**Comment by Armin83** [comment]
Ok right problem is gone but i can't see it anymore in ticket view. I can only see it in forms window or list view. (tested with requester, approver, super-admin and profile with update rights)

![2018-09-07 19_06_26-window](https://user-images.githubusercontent.com/19192087/45232853-3dd3cd80-b2d1-11e8-8019-08eafb04601f.png)

**Comment by Armin83** [comment]
Right here on the next bug ;)
There is a view change on 9.3 (9.3.x) and so we cannot see the linked items in ticket "main" view.  Items tab don't really correct. I will update you next days.

**Comment by btry** [comment]
OK, thank you foebyour feedback. I'll merge the current fix for upgrade.

Latest versions of formcreator  have additional checks preventing access to form answers. This solves some security problems.

An example is a form generating several tickets for different technicians. Some informations are confidential and shall not disclose to some  technicians. This can be solved at ticket level, because the ticket may contain a subset of answers. However, without security, viewing the answers will disclose all of them. 

There is an other issue opened by other users about that. I'll make a reference to this one.

**Comment by btry** [comment]
Hi

While developong for 2.7.0 I thi,k I found your issue

Look in this screenshot you shared : https://github.com/pluginsGLPI/formcreator/issues/1014#issuecomment-419504985

This view is handled by GLPI. Formcreator correctly adds a relation between the generated ticket and the answers, but GLPI may filter out the relation if your profile does not has **Form Answer** in helpdesk types 


![image](https://user-images.githubusercontent.com/14139801/45742597-ab99c680-bbfa-11e8-82e9-3bfa1c45114b.png)

Please check this setting for all profiles needing to see the relation. However, for security reasons, form answers may be still not readable.

**Comment by Armin83** [comment]
Yes, thats it. Maybe i changed this on dev system so i got the other screenshot. (On my productionssystem 9.2.2 i see them also not in this view now it works.)

THANKS
