### ISSUE TITLE
associate form to existing ticket

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#1015]
Hello

I would to know if it is possible to link a form to a ticket during form creation

Case :
I have created a computer installation check list 
the request is firstly created by the user to have a new computer
I take the ticket and go to prepare the computer
I use my form check list computer and select the ticket to associate my check list.

Thank you for your answer

**Comment by mauriciolamego** [comment]
I believe I have the same need and intention. In fact, it is suggested that when a user / technician completes a form, it is possible for him / herself to enter an already open call linking to what is being created, offering the options whether it is parent, child, or related.
Sincerely,

**Comment by btry** [comment]
Hi

I guess the need would be satisfied if the link between tickets allows to link a target ticket to a ticket choosen from a question.

**Comment by btry** [comment]
Hi

Having no feedback, I close.
