### ISSUE TITLE
incohérence champ acteur : valeur selectionnée / valeur inscrite dans le ticket

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1016]
Bonjour,

Je vous fait remonter un comportement qui n'est pas bloquant mais peut être gênant.
Lorsqu'on crée une question de type "acteur", on interroge bien la base et on peut le sélectionner une personne présente dans GLPI identifiée par Nom + prénom. Cependant, dans le formulaire généré je récupère le champs "identifiant" de la personne, ce qui est beaucoup moins parlant pour nos gestionnaires.
Est-ce qu'il existe une solution permettant d'afficher Nom + Prénom dans le formulaire généré plutôt que l'identifiant?

D'avance merci

**Comment by btry** [comment]
Je pense qu'il y a eu un petit souci à la création du ticket :)

**Comment by btry** [comment]
Bonjour

Avec quelle version de GLPI et du plugin ?

**Comment by btry** [comment]
Précision, le plugin est supposé présenter le login des utilsiateurs, pas le nom + prénom (risque d'homonyme, alors que le login est forcément unique)

**Comment by eckorion** [comment]
J'ai testé en 2.5.2 avec GLPI 9.1.3 et en 2.6.2 avec GLPI 9.2.2

**Comment by eckorion** [comment]
Je viens de vérifier, c'est identique en 2.6.3.
Merci d'avance pour ce que vous pourrez faire.
Bonne journée

**Comment by btry** [comment]
Bonjour

Pouvez-vous tester le patch ci dessus ?
