### ISSUE TITLE
Ticket Categories Filter

### ISSUE THREAD

**Issue by wfilho** [pluginsGLPI/formcreator#1018]
I'be been talking with some people on forums and one of the problems IMO of GLPI is that ticket categories in the same dropdown is a big problem when you have more than 200 categories to incident or request. The first thing we try in these cases are installing formcreator to make it easy for our users to deal with it. 

**Describe the solution you'd like**
We think that if you put a type question  where we can choose a main category and the user, in the form, can choose only the subcategories of this main category we selected it would resolve this big issue.

Cenario:
Service Catalog
Service Catalog -> Equipment
Service Catalog -> Equipment -> Desktop
Service Catalog -> Equipment -> Desktop -> Install
Service Catalog -> Equipment -> Desktop -> Format
Service Catalog -> Equipment -> Desktop -> Repair Hardware

We would like to have a type of question (ex. Category Filter) where we choose a main category (ex. Service Catalog -> Equipment -> Desktop) and then a sublevel number (as in the field Dropdown List -> Assistance - Ticket Category) and it will filter only the subcategories of the main category choosen.

**Describe alternatives you've considered**
I couldn't think in an alternative. I think we could ask you to implement a new feature on FormCreator or ask for the feature to GLPI core team, but I think it would be more interesting this feature in formcreator as we already try formcreator when facing with "one dropdown list for all categories" problem.

Thanks in advance !
Regards

**Comment by btry** [comment]
Hi

This idea is interesting. If you want to be a sponsor to develop this feature, contact us : contact@teclib.com 

You have an opportynity to have the feature for the release 2.7.0. I will continue its development very soon, and I wish to release it in the last 3 months of 2018.

**Comment by pedroluisvsousa** [comment]
A simple solution would be to show only the categories configured as "Visible in the simplified interface".

**Comment by btry** [comment]
hi 

Recent versions of Formcreator provide new options to select ovisible categories in a question:

- you can select catetgories for incident or request, categories for changes
- you can select a subtree from the categories tree you designed
- you can set a deep limit from the root of your subtree (or the whole tree if not subtree is not set)

![image](https://user-images.githubusercontent.com/14139801/76415434-7b6b5800-6399-11ea-8765-2a37751e180c.png)

![image](https://user-images.githubusercontent.com/14139801/76415455-8625ed00-6399-11ea-869b-45c088b46271.png)

**Comment by pedroluisvsousa** [comment]
Hi,
I leave the suggestion, for the next version, the addition of the option "Simplified interface" in Subtree root. This option would be useful to delimit the end user's catalog view.

Thank's.

**Comment by btry** [comment]
Hi

I checked the code : when the user runs the simplified interface or the service catalog, the dropdown shall show only the catgories having the simplified interface set to "yes"

![image](https://user-images.githubusercontent.com/14139801/76600114-96a7a600-6506-11ea-94de-330187b26cf7.png)

Formcreator shall follow the rules given by GLPI, then there should not be any option to show ticket categories of the normal interface when the user is in simplified interface.

Actually, I think this ticket is solved.

**Comment by pedroluisvsousa** [comment]
ok. I tested. Perfect.

**Comment by btry** [comment]
Great, then I close this ticket (lately).

Thank you for your feedback.
