### ISSUE TITLE
It does not hide question descrition type.

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#1019]
It does not hide question descrition type.
Following examples screens.

![screenshot-2018-6-19 chamado nti - forms - 5](https://user-images.githubusercontent.com/26510405/41600233-b450624e-73ab-11e8-898e-6c3d23ff828d.png)

![screenshot-2018-6-19 chamado nti - forms - 5 1](https://user-images.githubusercontent.com/26510405/41600244-bcc5a97a-73ab-11e8-8045-59d60c91f69f.png)

**Comment by btry** [comment]
Hi

Please specify the version of GLPI and the version of Formcreator

**Comment by pedroluisvsousa** [comment]
GLPI 9.2.3 and Formcreator v2.6.3.

**Comment by btry** [comment]
Hi

I'm currently working on an other project until July 9th. Please be patient.

**Comment by tlombardini** [comment]
Same problem, Thanks for your help ;)

**Comment by btry** [comment]
Hi

Please use a testing environment to test this branch: https://github.com/pluginsGLPI/formcreator/pull/1007

It should help to solve conditions issues. This branch needs some more tests to ensure  there are no regressions (its purpose is to remove all quotes and characters encoding issues).

**Comment by pedroluisvsousa** [comment]
Hi,
I tested it and it's ok.
Thanks a lot!

**Comment by btry** [comment]
Thank you for your feedback. I'll close t his issue when the PR will merge.

**Comment by btry** [comment]
fix merged. closing the issue.
