### ISSUE TITLE
Recherche catalogue de service

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1020]
Bonjour,
Lorsqu'on fait une recherche de formulaire depuis le catalogue de service, j'ai l'impression que les accents sont mal gérés. Par exemple en saisissant Téléphonie, le formulaire n'est pas retrouvé alors que bien présent (ex ci-dessous) : 
![image](https://user-images.githubusercontent.com/25478777/41643049-7c67d960-746a-11e8-8843-c0a20e137c53.png)
Est-ce qu'il ne serait pas possible de s'affranchir de ce problème en ne tenant pas compte des accents?
Cordialement

**Comment by btry** [comment]
Bonjour

Le moteur de recherche est basé sur les fonctions offertes par le SGBDS (Mysql / PariaDB). Essayez de faire une recherche avec 2 mots clés. Malheureusement le formulaire "Téléphonie" ne contient qu'un seul mot. Etoffez sa description et voyez ce qu'il se passe en faisant une recherche avec 2 mots minimum. Le formulaire devrait être trouvé.

**Comment by eckorion** [comment]
En saisissant 2 termes, ce n'est pas mieux, 
![image](https://user-images.githubusercontent.com/25478777/41646632-a0ce5ff4-7474-11e8-9e20-6430e7f51760.png)
Je suis obligé de saisir l’intégralité du titre alors que si le mot ne contient pas d'accent je le trouve directement 
![image](https://user-images.githubusercontent.com/25478777/41646706-ce4a9420-7474-11e8-8787-6d6d8baeb285.png)
Il me semblait que si la base est en UTF8 general-CI on ne tient pas compte des accents, majuscules...

**Comment by eckorion** [comment]
![image](https://user-images.githubusercontent.com/25478777/41646816-065c5e16-7475-11e8-9ec7-b1f827ac903a.png)

**Comment by btry** [comment]
Je dois attendre juillet pour m'occuper ce cela. 

Je proposerai un patch qui convertira les caractères accentués en caractères non-accentués avant de lancer la recherche. 

Note: il faut aussi faire attention aux mots courts comme "de", "le", "la", etc. Ils peuvent être ignorés par le moteur de recherche (il faut que je relise la documentation de MySQL sur ce point).

**Comment by eckorion** [comment]
Pas de souci, merci pour tout.
Bonne journée

**Comment by eckorion** [comment]
Bonjour,
Juste pour information, est-ce que vous avez eu le temps de regarder ce problème?
Je me demandais s'il était envisageable de proposer une auto-complétion ou un filtrage des formulaires au fur et à mesure de la saisie? un peu comme sur GLPI.
Merci

**Comment by eckorion** [comment]
Bonjour, 
Je peux également vous proposer de jeter un œil, est-ce que vous auriez une indication où regarder?
Cdlt

**Comment by btry** [comment]
Bonjour

La recherche de formulaires est dans la méthode PluginFormcreator::showFormList()

**Comment by eckorion** [comment]
Bonjour,
en fait la recherche a l'air de fonctionner correctement, le problème vient du stockage du nom et de la description du formulaire dans la base de données.
Par exemple "éléphant" est stocké comme ça : 
"&eacute;l&eacute;phant" 
Ce sont les fonctions prepareInputForAdd() dans form.class.php et plugin_formcreator_encode() dans setup.php qui semblent en être responsable mais on n'est pas allé plus loin.
Cdlt

**Comment by btry** [comment]
Bonjour

Tout à fait, et je nettoie ça progressivement depuis très longtemps. Je compte purger l'usage de plugin_formcreator_encode() dans la version 2.7.0 car cela est aussi inutile que source de bug.

La version 2.6.4 a un peu progressé sur le sujet. Je vous invite à l'essayer en environnement de test, et envisager une migration de votre production. 

Si vous voulez essayer en laboratoire la branche develop, (upgrade epuis une ancienne version et utilisation) cela me serait très utile pour avancer.

**Comment by eckorion** [comment]
Pour info, j'ai le même problème avec la branche develop avec un GLPI 9.3 dev, mais je n'ai pas poussé plus loin (je manque un peu de temps pour l'instant). Les tests précédents étaient faits à partir d'une version 2.6.4.

**Comment by btry** [comment]
avez vous bien exécuté l'outil de mise à jour ? Il doit modifier les champs contenant ces entités html dans les données existantes.

Pouvez-vous aussi observer si cela fonctionne bien avec un formulaire créé avec la version develop ?

**Comment by eckorion** [comment]
Voici une modification qui semble fonctionner sur ma version de prod (à vérifier quand même) si jamais quelqu'un a besoin de régler ce problème en attendant la maj:
dans form.class.php
J'ai complété la regex 
``$keywords = preg_replace("/[^A-Za-z0-9 ]/", '', $keywords);
remplacer par  
$keywords = preg_replace("/[^A-Za-z0-9ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ ]/", '', $keywords);

et ajouté une condition à la fonction prepareInputForAdd()

   public function prepareInputForAdd($input) {
      // Decode (if already encoded) and encode strings to avoid problems with quotes

       foreach ($input as $key => $value) {
         if (!is_array($value)) {
             if($key=='name' || $key=='description')
                 $input[$key] = plugin_formcreator_encode($value,false);
             else
                $input[$key] = plugin_formcreator_encode($value,true);
         }
      }

**Comment by eckorion** [comment]
Concernant la mise à jour, j'ai copié les fichiers dans le répertoire, mais l'outil plugin ne m'a pas proposé de mise à jour, comme si j'étais toujours en 2.6.4. Par contre j'ai bien créé un nouveau formulaire. Je vais refaire les tests en partant d'une autre version

**Comment by btry** [comment]
comment dire... ce que vous avez trouvé est intéressant : à ce jour je me demande ce qui m'est pasé par la tête pour effacer  les caractères accentués d'une expressions recherchée.

En gros si vous tapez éléphant dans la zone de recherche, le plugin va chercher des formulaires avec le mot **lphant** (les é ont été supprimés par le preg_replace).

Il faut absolument que je résolve cela en remplaçant les caractères accentués par leur équivalent sans accent. Cela vaut aussi le coup de re-vrifier si il est vraiment requis de faire ce remplacement.

**Comment by eckorion** [comment]
Bonjour,
Désolé, je vous harcèle ce matin :/
Est-ce que vous pensez que ça sera intégré dans la prochaine version 2.7?
D'avance merci

**Comment by btry** [comment]
Bonjour

j'ai trouvé un correctif. Il résout le problème pour la version 2.6.5. Veuillez tester rapidement car je compte releaser sous quelques jours.

**Comment by eckorion** [comment]
Bonjour,
J'ai installé la release 2.6.5 (qui apparait comme une 2.6.4) en upgrade et en primo install, mais le problème est toujours identique.
J'ai fait l'installation sur une 9.3.1

**Comment by btry** [comment]
le correctif n'est pas dans la future 2.6.5. Le flot de travail réclame qu'il y ait une validation (relecture du code et/ou validation fonctionnelle) d'abord. 

Il faut que vous téléchargiez la version depuis mon fork, pas la branche release/2.6.5. Je fusionne de préférence quand le fix est validé par le demandeur.

**Comment by eckorion** [comment]
Ok, j'ai effectué les modifications, mais il y a toujours un problème.
J'ai l'impression qu'il recherche les mots avec accent maintenant 
![image](https://user-images.githubusercontent.com/25478777/47431680-bf59bf00-d79c-11e8-8f35-955c2e10e26f.png)
![image](https://user-images.githubusercontent.com/25478777/47431694-c84a9080-d79c-11e8-8233-8ea5b792b59d.png)

**Comment by btry** [comment]
Oui, je confirme. Faire uen recherche ignorant ls accents va ête un peu compliquée car la fiabilité des focntions disponibles en php n'est pas parfaite. Sur certains systèmes, c'est officiellement dit que ça peut ne pas fonctionner. J'ai repéré du code que je peux reprendre de wordpress, mais il faut faire de même côté SQL. De ce côté là, c'est plus compliqué, je n'ai pas encore trouvé de solution convenable.

Il faudrait compter sur le fait que le concepteur de formulaires et le demandeur savent tous les deux écrire sans faute d'accent (ou alors fassent les mêmes erreurs :) ).

**Comment by eckorion** [comment]
Ce que je voulais dire c'est qu'en fait si je tape éléphant il trouve création. J'ai l'impression qu'il me propose tous les mots avec accent si j'ai mis un accent dans la recherche.

**Comment by btry** [comment]
La recherche porte sur plusieurs champs : 
- nom des formulaires
- description des formulaires
- nom des questions
- description des questions

Il y a peut être le mot "de" dans un des champs rattaché au formulaire éléphant ou ses questions

**Comment by eckorion** [comment]
Ca se pourrait, mais si je tape juste éléphant il me propose le formulaire "création de pages web" et je suis certain de ne pas avoir le mot éléphant dans ce formulaire :D

**Comment by btry** [comment]
Ca se tient comme raisonnement. 

Pour creuser il faut que je sache si vos tables sont en myisam ou innodb (ça impacte les résultats de recherche), ainsi que le nombre total de formulaires dans la bdd.

**Comment by btry** [comment]
Bonjour

Je reproduis le même souci. Apparemment du moment qu'il y a un accent dans un mot, des faux résultats apparaissent, à partir du moment où le même caractère existe dans un autre mot.

Il est très probable que cela se recoupe avec les soucis d'enregistrement des caractères acentués dans la BDD. Ils sont convertis en entités HTML, car je supprime le bug quand je supprime cet encodage dans la table.

Il est très compliqué de modifier l'encodage des textes partout dans le plugin sans risquer des régressions. Je l'ai fait progressivement depuis la série 2.5.x, et la future 2.7.0 n'a plus que quelques résidus. Je vais donc repousser le correctif pour ce ticket à 2.7.0.

Je vous invite à  tester en labo la version 2.7.0 avec ce patch et remonter tout bug wue vous pouvez rencontrer. Au vu des résultats que j'obtiens, je pense qu'elle est proche du statut de release candidate.

**Comment by eckorion** [comment]
Bonjour,
Je veux bien, mais comment je peux la récupérer?
Merci

**Comment by btry** [comment]
Bonjour,

il suffit de se positionner dans la branche develop et de télécharger le ZIP.

lien direct: https://github.com/pluginsGLPI/formcreator/archive/develop.zip

**Comment by btry** [comment]
Bonjour

je fusionne le correctif dans la versin 2.7.0. Je tente de dégager un peu de temps un peu plus tard pour vérifier et éventuellemetn améliorer le moteur de recherche.

**Comment by btry** [comment]
Bonjour

Je ferme ce ticket car il est très ancien . Il pourrait être résolu grâce à un changement récent dans le moteur de recherche. Si le problème persiste avec uen version 2.10 ou supérieur, merci d'ouvrir un nouveau ticket.
