### ISSUE TITLE
Balises de notifications non fonctionnelles

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/formcreator#1023]
Hello,
Certaines balises dans les notifications ne sont pas prises en compte.
Il s'agit des balise de type lang. et la balise ##formcreator.form_full_answers##

Voici le contenu de la notif:

![image](https://user-images.githubusercontent.com/6872020/42025559-20909742-7ac5-11e8-8610-e8aa0b7dbadd.png)

Et le mail reçu:
![image](https://user-images.githubusercontent.com/6872020/42025451-dfd1bc9a-7ac4-11e8-98c6-576ce5c5adc2.png)

Merci.

**Comment by lquenta** [comment]
Sorry, but we had some workaround for this?
Thanks!

**Comment by btry** [comment]
Hi

Well, after checking the source code it appeared to me that this feature does not exists, that's why it is broken :D, and why I labelled this issue as feature.

If someone proves me that this worked before, this may be a proof I broke the feature (long long ago).

**Comment by josemalena** [comment]
I have the same issue... This feature will increase a lot the productivity of this plugin. And if we can create the notification with the approve and reject buttons, will be much more better.

**Comment by eckorion** [comment]
Bonjour,
Je souhaiterai savoir s'il y a du nouveau concernant ces balises?
Est-ce qu'il existe une solution pour pouvoir joindre dans la notification le contenu du formulaire.
Merci

**Comment by eckorion** [comment]
Pour rappel on a les balises suivantes à disposition dans la notification "Un formulaire est en attente de validation" 
![image](https://user-images.githubusercontent.com/25478777/85512924-bae14b80-b5fa-11ea-9241-3e1ed68734c9.png)
Mais seules les balises en vert fonctionnent.
