### ISSUE TITLE
Non réception de mail lorsque le destinataire est Auteur

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/formcreator#1024]
Bonjour,

Les notifications sur l'évènement "Formulaire sauvegardé" dont le destinataire est "Auteur" ne sont pas envoyées.
Par contre si on met par exemple Administrateur, elles sont bien envoyées.

Il n'y a rien dans la file d'attente des courriels ni dans la corbeille de la file d'attente.

Merci

**Comment by ladenree76000** [comment]
est ce que l'auteur a sélectionné dans ses préférences "ne pas me notifier pour mes changements " ?

**Comment by btry** [comment]
Too old, closing.
