### ISSUE TITLE
antislashes removed in description field

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#103]

**Comment by neeftarah** [comment]
Je ne voit aucune solution avec PHP 5.3 et le framework de GLPI. Si tu en voit une, n'hésite pas...

**Comment by orthagh** [comment]
et en 5.4 ? Franchement je pense qu'on peux se mettre cette contrainte.

**Comment by neeftarah** [comment]
Il faut voir, le problème vient du "Magic quote" appliqué par GLPI qui ajoute des antislashes sur toutes les variables et qu'il faut que je retire.
Si on oublie PHP 5.3, je peut peu être forcer l'encodage de tout les caractères et évité ainsi les addslashes et donc supprimer les stripslashes qui ne seraient plus nécessaires.

Après il faut savoir ce qui est le plus important :
- Être compatible PHP 5.3 comme GLPI ?
- Ou pouvoir mettre des antislashes dans les descriptions ?

**Comment by coni83210** [comment]
Bonjour,
je rencontre exactement le même problème.
Avez-vous trouvé une solution ?

**Comment by Fabzed** [comment]
Bonjour bonjour,
Pti' up !
Même soucis ;)

**Comment by btry** [comment]
Bonjour,

C'est en file d'attente, pas d'inquiétude. J'ai donné priorité au bug de lenteur du service catalogue (réclamant un patch structurel). Il est tout juste résolu. Je peux revenir sur les bugs un peu moins impactant.

**Comment by btry** [comment]
Bonjour 

Je viens de faire un essai avec la version 2.4.1, et je ne reproduis pas (ou plus). 

@coni83210, @Fabzed avez vous possibilité de faire un retour ?

**Comment by Fabzed** [comment]
Oui pardon, bonjour ! :)

J'ai tous mis à jour sur un GLPI de test et c'est ok pour moi.
(Debian 8.7, GLPI 9.1.2, plugin 2.4.0)

Merci ;)

**Comment by btry** [comment]
Bonjour

Merc pour le retour. 

J'attends un peu pour avoir le retour de @coni83210 si il est toujours à l'écoute. Si pas de réponse ou retour positif, je ferme.

En passant, notez que la version 2.4.2 est sortie et corrige quelques bugs, notamment sur le type de champ acteur.

**Comment by coni83210** [comment]
Bonjour
je confirme que le bug est corrigé.
Merci beaucoup !!!!


-------- Message d'origine --------
De : btry <notifications@github.com>
Date : 30/04/2017 14:44 (GMT+01:00)
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : coni83210 <nicolasweil@hotmail.com>, Mention <mention@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] antislashes removed in description field (#103)


Bonjour

Merc pour le retour.

J'attends un peu pour avoir le retour de @coni83210<https://github.com/coni83210> si il est toujours à l'écoute. Si pas de réponse ou retour positif, je ferme.

En passant, notez que la version 2.4.2 est sortie et corrige quelques bugs, notamment sur le type de champ acteur.

**Comment by btry** [comment]
Merci; donc je ferme.
