### ISSUE TITLE
Pas d'envoi de mail d'enquete de satisfaction avec ticket générés via Formulaire

### ISSUE THREAD

**Issue by bouboufatal** [pluginsGLPI/formcreator#1032]
Bonjour,

Je rencontre un comportement que je n'explique pas, peut etre que j'oublie qq chose...!

Sur notre GLPI V9.2 avec plugin Formulaire v2.6, les enquêtes de satisfaction fonctionnent très bien SAUF pour les tickets générés via les formulaires.

En effet, dès la clôture d'un ticket généré par l'ouverture d'un formulaire, aucun mail concernant l’enquête de satisfaction n'est envoyé. Le fonctionnement est OK avec les tickets ouvert "normalement".

Auriez vous une idée ?

Merci par avance

**Comment by btry** [comment]
Hi

Adding link to the forum: http://forum.glpi-project.org/viewtopic.php?id=163850

As I told in the forum, please, try the release 2.6.3 and feedback

**Comment by bouboufatal** [comment]
Désolé je n'avais pas vu. Croyez vous que la MAJ puisse mettre en péril mes formulaires actuels ?
Nous en avons un certains nombre en production...

Merci !

**Comment by btry** [comment]
Bonjour

L'upgrade du plugin n'est pas supposé faire perdre les formulaires. Si  tel était le cas, ce serait un bug.

Upgrader de 2.6.x vers 2.6.y ne posera pas de souci. Les changements en base de données sont mineurs. 

Cependant, faites systématiquement un test d'upgrade avec un serveur de test, et avant d'upgrader la production, faites toujours une sauvegarde des fichiers et de la BDD.

**Comment by bouboufatal** [comment]
ça marche merci, je vais tenter de tester cela ce jour.

**Comment by bouboufatal** [comment]
Arf, il me faut GLPI v9.2.1 pour passer la version 2.6.3 du plugin
Je suis en GLPI v9.2
Bon...
Me voila un peu coincé tout de suite...!

**Comment by btry** [comment]
Il va falloir songer à passer en version 9.3 car les bugfixes et les développements en cours risque de me faire renoncer à la version 2.6.4 que je voulais pourtant réaliser ce mois ci. 

Si tel est le cas je devrai passer directement à la version 2.7.0 qui ne prendra plus en charge GLPI 9.2. Entretenir la compatibilité avec GLPI 9.2.x et GLPI 9.3 m'oblige à rendre le code moins maintenable.

**Comment by bouboufatal** [comment]
Ok, merci pour votre retour...
Nous utilisons aussi pas mal de plugin, et certains ne seront pas compatible avec la 9.3 avant qq temps, voila qui m’embête donc un peu..

Au dela de ces problemes de version, est ce que le probleme sité dans ce sujet (l'envoi de mail pour enquete qui ne fonctionne pas avec les tickets générés par la saisie d'un formulaire) est un probleme que vous aviez identifié ou pourrions nous penser que cela n'est pas lié et qu'il faut que je cherche une autre piste ? Si oui, auriez vous une idée de l'investigation à mener ?

Merci beaucoup !

**Comment by btry** [comment]
Avant de monter GLPI en 9.3 vous ferez sans doute un ceratin nombre de tests. Cela prendra un peu de temps, que je mets à profit pour résoudre quelques soucis de compatibilité. C'est le but de la release 2.6.4.

A propos des enquêtes de satisfaction, je n'ai aucun retour de bug jusqu'à maintenant, au point que je ne sais pas si cela a déjà été utilisé avec le plugin. Etant donné que les enquêtes de satisfaction sotn en lien avec le ticket et son cycle de vie, je pense que Formcreator ne peut pas impacter la fonctionnalité, positivement ou négativement. 

Pour vérifier, j'aurai besoin que vous donniez la marche à suivre pour reproduire le souci. Sans cela je risque de chercher à reproduire selon une mauvaise démarche (qui ne déclencherait pas le bug) et passer beaucoup de temps à trouver.

**Comment by bouboufatal** [comment]
Bonjour,

Merci pour vos échanges, j'ai trouvé cela venait d'une mauvaise configuration de ma part, pas d'héritage sur les entités..

Donc rien à voir.

Merci !

**Comment by btry** [comment]
Bonne nouvelle: un bug de moins à traiter :)

Merci pour le retour; je ferme le ticket.
