### ISSUE TITLE
Title of the form with seized items

### ISSUE THREAD

**Issue by typtop21** [pluginsGLPI/formcreator#1045]
Hi,
Would it be possible to include in the title of the form that is included in the ticket created elements of the form.
I have created a physical access request form for newcomers not yet present in our IS.
I wish that in the title of the form -the same during the creation of ticket request- can take again the name and the first name of the person asked during the filling of the form.
Best regard

**Comment by btry** [comment]
Hi

![image](https://user-images.githubusercontent.com/14139801/43010288-54c6b12c-8c40-11e8-82fb-24d495e2495c.png)

You can add tags in the field **Ticket title**. They will be replaced by the content if the fields when generating the title of the target ticket.

**Comment by typtop21** [comment]
Yes OK
I found and it works perfectly.
Thank you

**Comment by btry** [comment]
Thank you for your feedback, I close this issue.
