### ISSUE TITLE
 Show empty / object / Entity - Not working

### ISSUE THREAD

**Issue by niloultimate** [pluginsGLPI/formcreator#1054]
**Describe the bug**

The object - / object / Entity - does not show empty.

**To Reproduce**
1 - Create question
2 - Select "Object GLPI" in type.
3 - Select "Administration - entity" on "Object GLPI".
4 - ADD question.

Prit the my screean
![image](https://user-images.githubusercontent.com/24455891/43209737-c32b22da-9003-11e8-84ef-40337715a40b.png)

Ok now go to test:

1 - Go to preview

Observer that does not come empty.

![image](https://user-images.githubusercontent.com/24455891/43210153-ba36546e-9004-11e8-8aa2-4d2cde884e75.png)

System info:

GLPI version: 9.1.3
Plugin formcreator version: 2.5.2

Thank you for your attention.

**Comment by btry** [comment]
Hi

Having no feedback, I close
