### ISSUE TITLE
Ticket creation condition

### ISSUE THREAD

**Issue by Semprus** [pluginsGLPI/formcreator#1064]
Hello,

I would like to know if it's possible to create ticket creation condition on destinations.
For example, I'm working for a Helpdesk and we are working on "New arrivals". 
The form is requesting about material, account, and other things. The material is managed by a group and account by an other one.
If the user don't need material, there is no need to create a ticket for the specific group.
The creation of the ticket depend on user's answer.

Is it possible ?

**Comment by btry** [comment]
Hi

there is currently no condition for ticket / change creation.

I mark your ticket a feature request, unplanned.

If you want to sponsor the feature, please contact us: contact@teclib.com

**Comment by btry** [comment]
Hi

The feature is implemented.
