### ISSUE TITLE
formulaire en attente de validation

### ISSUE THREAD

**Issue by anouhi** [pluginsGLPI/formcreator#1069]
Bonjour, 

Ma version de glpi = 9.2.3
Maversion form creator = 2.6.3

Mes questions sont les suivantes 

- j'ai un message a chaque fois que je valide un formulaire (impossible de généré les destinataires) 
j'ai dans le formulaire un groupe active directory qui contien des utilisateur avec un mail de tager sur ad

quelqu'un a t'il une idée

Ensuite

- Mes formulaires semble etre en attente de validation, sauf que j'ai mi non lors de la creation de mon formulaire... 
Sur la page central de glpi lorsque je valide un formulaire ce dernier ne semble pas basculer vers la personne qui doit le prendre en charge.

Une idée?

merci de votre aide

**Comment by btry** [comment]
Bonjour

Veuillez préciser le message car sans lui je n'aurai aucune idée de ce qu'il se passe. Voyez aussi les logs de glpi : glpi/files/_logs/php-errors.log et glpi/files/_logs/sql-errors.log

Si il y  a quelque chose semblant en rapport avec votre souci, copiez le ici que je puisse l'analyser.

**Comment by anouhi** [comment]
![capture](https://user-images.githubusercontent.com/10148388/43843361-aae04ac8-9b27-11e8-919c-d07bdfb5b298.PNG)

**Comment by anouhi** [comment]
J'ai ceci a chaque fois que je valide un formulaire, pour les log je vous les fourni demain, car nous sommes plusieurs a bosser sur le sujet et je n'est pas la main sur les log aujourd'hui, je vous remercie de votre aide. 

sinon la notification fonctionne pour le demandeur, mais pour pour la cible... le demandeur recoit un mail qui dit que sont ticket et pris en charge, mais la cible ne recoit rien (ni ticket ni mail)

**Comment by btry** [comment]
Merci

La cible ? Il s'agit d'un technicien assigné au ticket, je suppose ? Vérifiez la configuration des notifications dans GLPI. Le plugin transmet toutes les informations à GLPI pour créer les tickets. C'est donc GLPI qui produit les notifications qui sont en lien avec les tickets.

Cela dit si les tickets ne sont aps générés à cause d'un souci, il est normal qu'aucune notifications ne soit créée.

**Comment by anouhi** [comment]
C'est bien ca, la cible est le ou les technicien, car je passe par un groupe recupéré par ldap.

Par contre quand vous dite vérifier la configuration des notifications de quoi parlez vous? car pour la parti notification mail elle fonctionne.

**Comment by anouhi** [comment]
lorsque je rempli mon formulaire je n'est rien ici et pourtemps je suis en super admin
![capture](https://user-images.githubusercontent.com/10148388/43844251-8e9c1228-9b29-11e8-9098-905747ebf5e7.PNG)

Pourtemps le formulaire est bien saisi, mais il ne genere pas de ticket... 
![capture1](https://user-images.githubusercontent.com/10148388/43844405-e90e44ce-9b29-11e8-9539-bafbb41bba05.PNG)

encore merci pour votre aide, je m'occupe des log rapidement pour vous les founirs

**Comment by btry** [comment]
L'erreur que vous avez reporté est un echec de créatio ndes tickets. Il me semble clair qu'il faut d'abord résoudre ce souci avant de vérifier notifications et décompte des tickets.

Quand un formulaire est sauvegardé, il s'agit d'erengistrer en BDD les réponses faites par le demandeur. La création des tickets a lieu après.

**Comment by anouhi** [comment]
la création d'un ticket manuel fonctionne correctement, c'est vraiment lors de l'utilisation de formulaire que je rencontre un souci. Et je n'est pas d'explication. Le souci serrais donc au niveau de la base de donnée?

**Comment by btry** [comment]
Non, le souci pourrait être lié aux informations saisies, il reste peut être quelques cas où une apostrophe peut générer une mauvaise requête SQL. J'ai un patch en cours qui sera versé dans la prochaine version 2.6.4 si des testeurs veulent bien la valider, ou bien dans la version 2.7.0 qui est en cours de dév (pour que j'aie le temps de la mettre à l'épreuve moi-même).

Cela ntétant qu'une hypothèse, j'attends vos logs pour confirmer. Je les lirai début de semaine prochaine.

**Comment by anouhi** [comment]
Bonjour, 
voici les deux fichiers de log que vous m'avez demandé hier.
Sinon j'avais autre question ainsi qu'une proposition.

Ma question (complementaire), actuellement la base de donnée est déporté (dans un environnement propice au coupure de courant), perso je pense qu'il vaudrait mieux avoir la base de donnée de GLPI et Form creator en local sur le serveur qui hébergé glpi plutôt que déporté, mais je me permet de vous demandé votre avis. (car si pour d'autre produit je conseille une DB déporté, dans ce cas present je ne suis pas convaincu)

Ensuite ma proposition, j'ai un environement de pre-pro sur un synology ou je fais tout mes tests, et si il y as besoin d'un beta testeur, je veux bien donnée un coup de main. échange de bon procédé.

Et encore merci de votre aide, car vraiment je tourne en rond sur mes deux pannes 

voici les logs

**Comment by anouhi** [comment]
php-errors.log

[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/2273133/php-errors.log)

**Comment by anouhi** [comment]
sql-erros.log
[sql-errors.log](https://github.com/pluginsGLPI/formcreator/files/2273135/sql-errors.log)

**Comment by btry** [comment]
Bonjour

> Ma question (complementaire), actuellement la base de donnée est déporté (dans un environnement propice au coupure de courant), perso je pense qu'il vaudrait mieux avoir la base de donnée de GLPI et Form creator en local sur le serveur qui hébergé glpi plutôt que déporté, mais je me permet de vous demandé votre avis. (car si pour d'autre produit je conseille une DB déporté, dans ce cas present je ne suis pas convaincu)

Vous pouvez utiliser une base de données sur le même hôte que GLPI aussi bien qu'utilsier deux hôtes séparés. C'est un choix de sysadmin qui dépend de votre architecture et de votre PRA. Je vous invite à en discuter sur le forum communautaire car c'est hors sujet ici. https://forum.glpi-project.org/

> Ensuite ma proposition, j'ai un environement de pre-pro sur un synology ou je fais tout mes tests, et si il y as besoin d'un beta testeur, je veux bien donnée un coup de main. échange de bon procédé.

D'une manière générale ayez toujorus une instance de GLPI pour tests d'upgrade de GLPI et ses plugins, ou tests d'un nouveau plugin que vous envisagez d'ajouter à la production. Si vous souhaitez contribuer en faisant des tests, je serai heureux d'avoir vos retours sur la version 2.6.4 en développement (branche develop). Par rapport à la version 2.6.3 il y a beaucoup de corrections faites, ainsi que le rétablissement de compatibilité aec GLPI 9.3.0

Si vous trouvez des bugs, créez un ticket par bug.

**Comment by btry** [comment]
Vos journaux montrent que vous rencontrez un souci d'échappement d'une apostrophe. Mal échappée, la requête SQL pour enregistrer les données est incorrecte et fait échouer la créatio ndes tickets.

```
2018-08-08 15:57:59 [14@CISYS-V08L-GLPI.linux.local]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_tickets` (`name`,`content`,`itilcategories_id`,`urgency`,`impact`,`priority`,`requesttypes_id`,`actiontime`,`date`,`entities_id`,`status`,`locations_id`,`global_validation`,`time_to_resolve`,`time_to_own`,`slas_tto_id`,`slas_ttr_id`,`internal_time_to_resolve`,`internal_time_to_own`,`olas_tto_id`,`olas_ttr_id`,`type`,`users_id_lastupdater`,`users_id_recipient`,`date_creation`,`date_mod`) VALUES ('CREDIM - I2S','DonnÃ©es du formulaire\n=================\n\n\nCompte bloquÃ© concernÃ©\n---------------------------------\n1) Nom et prÃ©nom de l'utilisateur concernÃ© : : sm10_1\n\n2) Equipe de rattachement : : BPH - EMOS\n\n3) Login de l'utilisateur concernÃ© : : sss\n\n4) NumÃ©ro de tÃ©lÃ©phone de la personne concernÃ©e : 0630770134\n\n5) Type de blocage : Verrouillage aprÃẀs 3 essais infructueux\n\n','0','3','3','3','7','0','2018-08-08 15:57:59','0','2','0','1',NULL,NULL,'0','0',NULL,NULL,'0','0','1','14','14','2018-08-08 15:57:59','2018-08-08 15:57:59')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'utilisateur concernÃ© : : sm10_1\n\n2) Equipe de rattachement : : BPH - EMOS\n\n' at line 2
  Backtrace :
  inc/commondbtm.class.php:504                       
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  ...ins/formcreator/inc/targetticket.class.php:1262 CommonDBTM->add()
  plugins/formcreator/inc/form_answer.class.php:1023 PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/form_answer.class.php:741  PluginFormcreatorForm_Answer->generateTarget()
  plugins/formcreator/inc/form.class.php:1207        PluginFormcreatorForm_Answer->saveAnswers()
  plugins/formcreator/front/form.form.php:124        PluginFormcreatorForm->saveForm()
```

**Comment by btry** [comment]
Il est probable que la version de développement corrige déjà le souci. Essayez la avec le même formulaire et en le remplissant de la même manière.

**Comment by anouhi** [comment]
Merci de votre aide.
Donc mes deux erreurs (impossible de générer les destinataires et les ticket qui n'apparaisse pas serrait lié 

ou puis-je trouver la version 2.6.4 ?? je vais la tester chez moi dans un premier temps

Et encore merci de m’accordé votre temps. Je ne manquerai pas de faire un retour

**Comment by anouhi** [comment]
merci je fais un retour à mon responsable et je vous tien au courant de la suite, pour ma part je vais mettre en place la solution dans mon environement de pre-prod perso.

**Comment by anouhi** [comment]
Bonjour, effectivement lorsque j'enleve les apostrophe, le ticket et bien généré. (pour le demandeur, mais pas pour l'équipe a qui j'attribue (un groupe) se ticket)

Me reste un probleme, je notifie normalement un groupe (que j'importe d'active directory)

Sauf que mes utilisateurs (membre de se groupe) ne reçoivent pas de notification, avez vous une idée?

**Comment by btry** [comment]
Bonjour

Si votre problème d'accès touche les tickets, et pas les réponses aux formulaires alors vous avez peut être fait un mauvais choix sur l'entité destination des tickets générés par le formulaire.

Vérifiez le profil de vos techniciens et l'entité où se trouve le ticket. 

Encore une fois, distinguez bien le ticket et les réponses au formulaire. Ce sont des objets différents.

**Comment by anouhi** [comment]
merci pour l'info, je pense que c'est bien configuré mais peut etre ne suis pas au bon endroit.

**Comment by btry** [comment]
Bonjour,

Vous pouvez définir l'entité dans la configuration de chaque ticket ou changement cible.

**Comment by btry** [comment]
Bonjour 

Je pense que ce ticket n'est plus  d'actualité. Je ferme.
