### ISSUE TITLE
"Leave request" form not working with accented characters in name

### ISSUE THREAD

**Issue by petrasteri** [pluginsGLPI/formcreator#1070]
This is a bug already reported three times in GLPI's forum at
https://forum.glpi-project.org/viewtopic.php?pid=351620

Do I still have to write everything once again?

**Comment by btry** [comment]
Hi

You said on the forum :
>  Under the "Setup" menu, I only have
Dropdowns
Components
External links

> I suppose I'm stuck.

You don't have enough rights to check the version of Formcreator. Get in touch with the administrators of your GLPI instance, and ask if they can test the develop branch of the plugin and feedback in this ticket..

**Comment by btry** [comment]
Hi

Assuming you have rights to edit the forms, please go to Administration > Forms

Find the form "leave request" (I assume this is its name), or move the mouse on  the name of each form until you find the one having id=4 in its URL (based on the information you shared in the forum)). Click it.

Click on the tab "Questions" to view all sections and questions in the form. I guess that a question is used to ask for a user. Click on it to edit it and view the type of question. You should have a display like  this

![image](https://user-images.githubusercontent.com/14139801/44022772-e6126300-9ee8-11e8-801e-c4376a84d236.png)

**Comment by petrasteri** [comment]
@btry  Thanks for your replies.  Unfortunately, in my "Administration" drop-down menu, I don't have "Form".

I suppose I have to wait my colleague to come back from vacations.  But I'm going on vacations too and will be back on mid-September, so this bug has to wait till then.

**Comment by btry** [comment]
OK, then I plan this bugfix for 2.7.0.

**Comment by btry** [comment]
Hi

Any feedback ?

I released the version 2.6.4 and the develop branch is now for the future 2.7.0. I update my request : 
> ask if they can test the develop branch of the plugin and feedback in this ticket

now you should try the release 2.6.4.

I don't plan a new version 2.6.x and focus on 2.7.0 now.

**Comment by petrasteri** [comment]
I'm just back from vacations.

Just talked to my colleague.  He said he's going to update everything - GLPI and the plugins.  I don't know when he'll do so.  So this issue has to be put in pending.

**Comment by btry** [comment]
Hi

This issue should not exist anymore. I close.

**Comment by petrasteri** [comment]
Sorry for not writing back.
My colleague, who has all the admin credentials to update the server and knows all the ins and outs of GLPI, said we would move to Jira.  So he won't spend time on this again.  Sorry.

**Comment by btry** [comment]
Hi

OK, I don't get issues with accented chars or single quotes, then the plugin should be OK now.
