### ISSUE TITLE
Pas de génération de ticket après validation de formulaire

### ISSUE THREAD

**Issue by LNAQUAO** [pluginsGLPI/formcreator#108]
Bonjour,

(Version GLPI : 0.85.4, version FormCreator : 0.85-1.2.4).
 Voici le souci : 
1) le demandeur crée un formulaire avec validation requise. Il obtient le message : " le formulaire a été sauvegardé avec succès "
2) le formulaire est envoyé automatiquement au validateur
3) le validateur accepte les données du formulaire. Après avoir cliqué sur le bouton " Accepter " et avoir saisi un commentaire, le message suivant s'affiche en rouge "Demandeur est obligatoire ", puis en dessous : " le formulaire a été sauvegardé avec succès !". Je ne comprends pas le message affiché en rouge car dans la liste des formulaires, le nom du demandeur s'affiche bien ! Et le demandeur est bien configuré dans la rubrique 'Ticket cible' dans Administration/Formulaire (demandeur = demandeur du formulaire)
4) A la suite de la validation : AUCUN ticket n'est crée.

Pourriez-vous me dire d'où vient le problème ???
Pourquoi aucun ticket n'est crée après validation par le validateur ?

Merci

**Comment by neeftarah** [comment]
Bonjour,

GLPI n'accepte, à la création qu'un seul demandeur/observateur/technicien.

Afin de pouvoir associer plusieurs demandeurs / observateurs / techniciens à un ticket générer par formcreator, le plugin crée un ticket sans acteurs puis les rajoute après.

Le problème dans votre cas, c'est que le demandeur est rendu obligatoire (sans doute via un gabarit ou via le plugin comportement). La création du ticket échoue donc.

C'est également un problème pour les notifications à la création du ticket car il n'y a pas de destinataire à ce moment.

Nous réfléchissons donc au problème. en attendant, essayer de retirer la configuration du champs "Demandeur" comme obligatoire, au moins pour les formulaires si vous utilisez un gabarit.


En revanche, un autre problème, sans doute plus simple à résoudre, est que le formulaire devrais sans doute échoué à la validation si la création des tickets  échoue.
Je me penche donc sur ce dernier point.

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
La validation ne sera maintenant plus possible si les destinations (Tickets) ne peuvent être créé.

**Comment by neeftarah** [comment]
Pour la suite, en attente de la demande https://github.com/glpi-project/glpi/issues/56

**Comment by orthagh** [comment]
sera ajouté dans 0.90.1

**Comment by blerohellec** [comment]
Je confirme. Pourrait être clôturé
