### ISSUE TITLE
FormCreator 2.6.4 : SQL Error table does not exist

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#1090]
**Describe the bug**

SQL error after answer a form. 

It's an error on sql request construction. The table name which is build with the code seems to be incorrect. "glpidev" is the name of the apache instance. SQL Tables names starts with "glpi.xxxx".

How to investigate ?

Mysql Version : mysql Ver 15.1 Distrib 10.0.31-MariaDB

SQL Debug :

```Error: Table 'glpidev.glpi_' doesn't exist
  Backtrace :
  inc/dropdown.class.php:333
  inc/item_ticket.class.php:1263                     Dropdown::getDropdownName()
  inc/commondbtm.class.php:4374                      Item_Ticket::getSpecificValueToDisplay()
  inc/tickettemplatepredefinedfield.class.php:349    CommonDBTM->getValueToDisplay()
  inc/tickettemplatepredefinedfield.class.php:145    TicketTemplatePredefinedField::showForTicketTemplate()
  inc/commonglpi.class.php:478                       TicketTemplatePredefinedField::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
```

**Comment by btry** [comment]
Hi

If there is no entry in the backtrace related to the plugin it will be hard to reproduce as is. I need more information. Can you create and share a simple form which reproduces the issue ?

**Comment by btry** [comment]
After reformatting it, your backtrace is more readable. Maybe there is an inconsistency in the table glpi_items_tickets, Please have a look in this table, focusing on the rows having a foreign key to the generated tickets.

**Comment by SylvainGuibert** [comment]
they are a missing line in my backtrace...the most important i think : 
` Error: Table 'glpidev.glpi_' doesn't exist`

**Comment by btry** [comment]
This line is for sure a problem when finding the table for an itemtype.

I believe that a variable containing the name of an itemtype is empty when computing the table if this itemtype. If this actually happens, then the error is in an previous method in the backtrace.

That's why i suggest that you check the table glpi_items_tickets which t(contains a column populated with names of itemtypes. I expect you find an empty string in the rows related to the generated ticket.

**Comment by SylvainGuibert** [comment]
That's Ok, i can't reproduce again....
Thanks for your help.
