### ISSUE TITLE
Question - Description on title hovering mouse

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1099]
Hello @btry  Can u help?

Natively, when hovering the mouse by the Title (Standart Interface) of a called the GLPI demonstrates the description field.

Using the Formscreator, when passing the mouse this behavior does not occur. Is there any way to do that?

Example

Standard interface

![visao ti](https://user-images.githubusercontent.com/35368369/45097246-c0edfb80-b0f8-11e8-87ea-645fcc89307d.PNG)

Simplified interface

![visao user](https://user-images.githubusercontent.com/35368369/45097316-e844c880-b0f8-11e8-8252-778473931f62.PNG)

**Comment by btry** [comment]
Hi

this is not implemented in the plugin. There is no workaround yet.

**Comment by phamorais** [comment]
Thank u @btry

**Comment by btry** [comment]
If you want to sponsor this development, feel free to contact us at contact@teclib.com . 

We are defining the roadmap for the next version 2.7.0, this is a good opportunity for you to have the feature in an acceptable delay.

**Comment by phamorais** [comment]
Thanks @btry .

Do you already have a forecast for the release of the new version?

**Comment by btry** [comment]
Hi

I want to release the version 2.7.0 before the end of the year. 2 months and a half to finish a big code refactor, then implement features requested by customers. I expect to wait 2 or 3 weeks maximum before freezing the roadmap of new features. After this deadline, extra features will wait 2.8.0.

**Comment by humbertocruz** [comment]
I created a merge request, https://github.com/pluginsGLPI/formcreator/pull/1267 - needing help for tests and docs update.

**Comment by phamorais** [comment]
@btry Can u Help @humbertocruz ?

**Comment by btry** [comment]
hi @phamorais Code review done. 

@humbertocruz can you do some improvements ?

If you need to test, I suggest you generate form answers for various cases
a form which generates 1 ticket
a form which generates nothing
a form which generates 2 tickets

Run them at least once, and see how your code behaves.

Also, your code fails with rich text mode. Use Toolbox::getHtmlToDispplay()

```php
        case "glpi_plugin_formcreator_issues.name":
            $ticket = new Ticket();
            $name = $data[$num][0]['name'];
            $ticket->getFromDB($data[$num][0]['id']);
            $richText = version_compare(PluginFormcreatorCommon::getGlpiVersion(), 9.4) >= 0 || $CFG_GLPI['use_rich_text'];
            $content = $ticket->getField('content');
            if ($richText) {
               $content = Toolbox::getHtmlToDisplay($content);
            }
```

This method wlll also do a nl2br for you.

**Comment by phamorais** [comment]
@btry this allready funcional in GLPI
