### ISSUE TITLE
Headers dropdown missing

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/formcreator#1100]
**Describe the bug**
There is no headers dropdown menu.

![image](https://user-images.githubusercontent.com/23405363/45103517-58227580-b130-11e8-8ecb-4835add593bd.png)
![image](https://user-images.githubusercontent.com/23405363/45103631-a2a3f200-b130-11e8-8186-12348da3387c.png)

GLPI 9.3.0
FromCreator v2.6.4
IIS 2012 R2
PHP 7.0
MYSQL 5.6

**Comment by btry** [comment]
Hi 

I don't get the point. 

Do you expect an extra dropdown called "Headers" ? What would be the purpose of those headers ?

**Comment by titidelaff** [comment]
Configuration and usage
Headers
Menu : Setup > Dropdowns : Forms > Headers

Headers are rich texts _(text with presentation: bold, italic, titles, colors, etc.)_ which are defined per entities. They can be translated since GLPI 0.85 like all other dropdowns _(Dropdowns translation must be enabled on GLPI general configuration page: Setup > General : General setup > Translate dropdowns = Yes)_.

These texts are shown on the users forms list, over the forms. It can be used to indicate some general advertisement over all the forms below.

Configuration
![image](https://user-images.githubusercontent.com/23405363/45145748-ab90d400-b1c1-11e8-9df8-f14c71dd05a6.png)


I'm just trying to add a header on the form creation interface as shown in the doc

**Comment by btry** [comment]
Hi

The headers feature was removed long ago. How can you still access it ? There was a class in inc/header.class.php that you probably still have in the plugin (https://github.com/pluginsGLPI/formcreator/blob/2.4.2/inc/header.class.php). 

I'm wondering how you still access it.

**Comment by btry** [comment]
Hi,

no feedback. I close this issue. Feel free to re-open if needed.
