### ISSUE TITLE
Actor question type doesn't work

### ISSUE THREAD

**Issue by KallistiMan** [pluginsGLPI/formcreator#1107]
GLPI 9.3.0, FormCreator 2.6.4
Steps to reproduce:
* A form is created with one section, one question of type Actor.
* Destination is of type ticket, ticket actor Requester + Watcher + Assigned to are all set to Actors from question.
* The form is used, I select an actor in the question.

Expected behaviour:
* Requester, Watcher and Assigned to are set to the Actor selected when using the form.

Actual behaviour:
* Requestor is set to the From requester, Watcher and Assigned to are unset.

I have tried to set the ticket actors to specific users/groups and to form requester (in for example assigned to) and that works.

**Comment by btry** [comment]
Hi

I will try with the version 2.7.0 in development

**Comment by KallistiMan** [comment]
Let me know if I can do anything more to help

**Comment by btry** [comment]
You may test yourself the version 2.7.0 and feedback if the issue still occurs.

Warning: use it only on a testing environment.

**Comment by KallistiMan** [comment]
Sorry, how do I download 2.7.0? I downloaded the development branch but couldn't upgrade.

**Comment by btry** [comment]
From github. Viee the source code, select the branch develop and download a zip with the big green button.

Feel free to feedback any bug you find (I'm a new issue) if any

**Comment by KallistiMan** [comment]
Tested with the current dev version. The previous forms didn't work (complained about a field: The text is too short (minimum 0 characters): <Field title>) but I will see when I have time to create another issue.

Created a new form with just one actor field. Created a target using that actor for requester. Created a ticket using the form. My user is still requester, not the user selected in the form.

**Comment by btry** [comment]
Hi i need to come back on this issue. I'll qualify it if I reproduce.

**Comment by nuria2c** [comment]
We have the same problem. We've update formcreator plugin to 2.6.5 (GLPI 9.2.4) and some forms doesn't work maintenant. With the previous version.

**Comment by nuria2c** [comment]
The problem is that the actor is not saved in the form
![image](https://user-images.githubusercontent.com/5544480/48260134-a3038680-e41a-11e8-9c2e-824c23226dbe.png)

![image](https://user-images.githubusercontent.com/5544480/48260166-bb73a100-e41a-11e8-9ce6-5929e8239974.png)

![image](https://user-images.githubusercontent.com/5544480/48260264-1a391a80-e41b-11e8-8d6d-7d54d7525ffd.png)

**Comment by btry** [comment]
Hi @nuria2c

 if some forms don't work, please create an issue per identified bug, and describe how to reproduce.

**Comment by btry** [comment]
OK, then the problem is not in the target ticket, it is in the display of a saved form. Thanks, this helps me for the tests.

**Comment by nuria2c** [comment]
Sorry. The form work's. the problem in a requester assignment when the source is a field actor type.

**Comment by btry** [comment]
Hi

As I could work on this issue for 2.6.5 I moved it to milestone 2.7.0. I did a test, and it worked:

Note: I also tested 2 actors, and results are ok as well.

Please try it and feedback.

### answers
![image](https://user-images.githubusercontent.com/14139801/48265589-2c23b900-e42d-11e8-89c9-5135ba86e39d.png)


### view the answers
![image](https://user-images.githubusercontent.com/14139801/48265552-0e565400-e42d-11e8-9583-5225d3a7499e.png)

### generated ticket
![image](https://user-images.githubusercontent.com/14139801/48265562-18785280-e42d-11e8-9f54-eca43eb7a0b1.png)

**Comment by nuria2c** [comment]
It works. But now the problem is that the anonymous users (like introduce a genric email in the actors field) now doesn't work...
Is it necessary change some parameter?
We test is GLPI 9.3.2

**Comment by nuria2c** [comment]
Any idea?

**Comment by btry** [comment]
Hi,

Please be patient : i'm very busy with many projects, and a lot of structural improvements in this plugin. The issue is queued and will be analyzed in deep soon

**Comment by btry** [comment]
Hi

I did a test with the versioin 2.7.0-beta.3; the email aded in an actor field is correctly added to the requesters.

I think this issue can be closed.

**Comment by nuria2c** [comment]
Hi, we don't try it yet. As soon as we can try it in the development server i'll feedback.

**Comment by btry** [comment]
Hi 

any news with this issue ? Can you check if the issue still occurs with the latest release or the develop branch ?

**Comment by btry** [comment]
Hi 

having no feedback, I close
