### ISSUE TITLE
PHP errors when moving up/down a question

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#1110]
GLPI 9.2.4, FormCreation version 2.6.4

In Administration > Forms, in the Questions tab of the form, everytime I move up/down a question, I get a pair of PHP errors (in php_errors.log), as follow.
Nevertheless, the result is correct and the question is moved

2018-09-13 16:53:15 [2@ULYSSE]
  *** PHP Notice(8): Undefined index: fieldtype
  Backtrace :
  plugins\formcreator\inc\question.class.php:291     
  plugins\formcreator\inc\question.class.php:386     PluginFormcreatorQuestion->checkBeforeSave()
  inc\commondbtm.class.php:1150                      PluginFormcreatorQuestion->prepareInputForUpdate()
  plugins\formcreator\inc\question.class.php:499     CommonDBTM->update()
  plugins\formcreator\front\question.form.php:89     PluginFormcreatorQuestion->moveUp()
2018-09-13 16:53:15 [2@ULYSSE]
  *** PHP Notice(8): Undefined index: fieldtype
  Backtrace :
  plugins\formcreator\inc\question.class.php:291     
  plugins\formcreator\inc\question.class.php:386     PluginFormcreatorQuestion->checkBeforeSave()
  inc\commondbtm.class.php:1150                      PluginFormcreatorQuestion->prepareInputForUpdate()
  plugins\formcreator\inc\question.class.php:503     CommonDBTM->update()
  plugins\formcreator\front\question.form.php:89     PluginFormcreatorQuestion->moveUp()

**Comment by btry** [comment]
Hi

I reproduce on  the 2.6.x series, including the incoming version. 

I don't reproduce on the future version 2.7.0. 

As the issue has no more impact than a warning and is fixed on the next major version, I won't fix it for 2.6.5.
