### ISSUE TITLE
Problème d'affichage formulaire

### ISSUE THREAD

**Issue by nikopole** [pluginsGLPI/formcreator#1118]
Bonjour,
quand je crée un formulaire, le visu est propre dans la prévisualisation.
![2018-09-19 12_20_49-glpi - formulaires - 5 - internet explorer](https://user-images.githubusercontent.com/43406689/45747564-7a26f800-bc06-11e8-88f3-c8471c55b4ad.png)

Mais quand j'ouvre le formulaire directement de l'accueil, il y a des questions que je ne vois pas
![2018-09-19 12_18_28-glpi - formcreator - 5 - internet explorer](https://user-images.githubusercontent.com/43406689/45747585-8f038b80-bc06-11e8-9fda-a1a65084c9a4.png)

pourriez vous m'aider ?

Merci,
Cordialement,
Nicolas

GLPI 9.3.0, FormCreator 2.6.4

**Comment by nikopole** [comment]
Bon je pense avoir trouvé le problème.
il se situe dans le type de question j'ai choisi "Auteur" pour avoir la liste des utilisateurs.

Quand je choisi "Selection LDAP" je n'ai pas le problème d'affichage.

**Comment by btry** [comment]
Bonjour

J'ai trouvé la semaine dernière une erreur dans le champ de type "Acteur" (Auteur n'existant pas, je pense que c'est Acteur que vous avez utilisé).

Essayez de patcher le plugin avec ce commit: https://github.com/pluginsGLPI/formcreator/commit/9d38a45fb765b80ef80988d20dfee30f3161783f

Ca doit résoudre votre souci.

**Comment by btry** [comment]
Bonjour

Je ferme le ticket faute de retour.
