### ISSUE TITLE
 public form does not have responsive design

### ISSUE THREAD

**Issue by rodrigomoiseis** [pluginsGLPI/formcreator#1119]
** Describe the bug **
When you leave the forms in public visibility, the form link does not open responsive to all devices.

**Reproduce**
1. Go to administration
2. Click Forms
3. Click any form
4. Target option
5. Leave public access
6. Copy the public link and paste it into another browser.
7. You can verify that you are not responsive.

**Expected behavior**
I expected that when I entered the public link, the form opened reponsivo for all the device and not only the computer

** Screenshots **
![capturar](https://user-images.githubusercontent.com/43414261/45761914-95443880-bc03-11e8-93b4-6f3fe174fb64.PNG)

** Desktop (fill in the following information): **
- O: any mobile operating system

** Smartphone (please fill in the following information): **
- Device: All smartphone devices

**Comment by btry** [comment]
Hi

I think this issue is solved with latest versions

![image](https://user-images.githubusercontent.com/14139801/57537010-ae8e2680-7345-11e9-9664-9787ebc55fcd.png)
