### ISSUE TITLE
Upgrade of formcreator-develop fails

### ISSUE THREAD

**Issue by KallistiMan** [pluginsGLPI/formcreator#1120]
Trying to upgrade formcreator from 2.6.4 to current development version fails: Unknown column 'validator_id' in 'field list'/Please, check migration log

**Comment by btry** [comment]
Please provide the migration log in glpi/files/_log/migration_to_develop.log

You should find a backtrace. I recently fixed an issue with 2.6.4. Maybe this issue is related (#997 #1059). Waiting for your backtrace to confirm.

**Comment by KallistiMan** [comment]
Backtrace:
plugins/formcreator/install/update_2.5_2.6.php:77  plugin_formcreator_upgrade_error()
plugins/formcreator/install/install.php:84  plugin_formcreator_update_2_6()
plugins/formcreator/hook.php:84  PluginFormcreatorInstall->upgrade()
inc/plugin.class.php:701  plugin_formcreator_install()
:   Plugin->install()
front/plugin.form.php:47  call_user_func()

**Comment by KallistiMan** [comment]
If I'm upgrading from 2.6.4, why is it trying to drop this key and field?

**Comment by btry** [comment]
I need to check the source to retrieve the context. In previous versions of the plugin I found that a column storing a validator ID contains either a user ID or a group ID,depending on the value of an other column. This is a bad design I wanted to change. To fix that the plugin needs 2 other columns : one for user ID an otrher for group ID. 

Nex the upgrade code copies the content (one row at a time) to the user ID column if this is a user ID, or Group ID column if this is a group ID. Finally the old column is dropped.

I think this is in here your issue occured. I must plan investigation on this issue starting from October 8th.

**Comment by KallistiMan** [comment]
I understand.

My thought was just that, as the upgrade is from 2.6.4, it should be able to assume that the migration away from validator ID has already been done. In other words, why is it running 2.5 -> 2.6 migration when upgrading 2.6.4 -> 2.7.0/develop.

**Comment by btry** [comment]
I agree,

This may happen if the plugin does not find his clue to determine the previous version. If you check the database before then upgrade you should find a row in the table glpi_configs containing the schema version of the plugin.

Select * from glpi_configs where context='formcreator';

**Comment by KallistiMan** [comment]
schema_version 2.6

**Comment by btry** [comment]
Then the plugin shall start from 2.6.

I refactored a bit the code in 2.7.0 maybe I left an error. I'll try to reproduce and fix in a few days, and enhance the tests on this

**Comment by btry** [comment]
see #1124 : i updated the upgrade logic to a smarter design. I think this patch is the part I missed.

**Comment by btry** [comment]
Hi @KallistiMan 

I got one positive feedbach for the patch, and it was merged. However I would appreciate you feedback too. Did you test it ?

**Comment by KallistiMan** [comment]
Hi, I've tested the upgrade now and it seems to work well. No visible issues during the run and nothing in the backtrace.

**Comment by btry** [comment]
Hi

Great ! Thank you for your feedback, I think we may close the issue
