### ISSUE TITLE
Pas de recalcul du formulaire avec champ Objet GLPI

### ISSUE THREAD

**Issue by mkael29** [pluginsGLPI/formcreator#1121]
Bonjour,

j'ai un formulaire avec une question Object GLPI positionné à Entités.
Ensuite j'ai d'autres questions dont l'affichage est conditionné à la valeur de l'Entité sélectionnée.
Ces question restent désespérément invisibles!
Actuellement je suis en GLPI 9.3.1 et Plugin 2.6.4
Avant j'étais en GLPI 9.2 et il n'y avait pas de problème.

Cordialement.

**Comment by mkael29** [comment]
Plugin 2.6.3

**Comment by btry** [comment]
Ouvrez les outils de développement de votre navigateur, puis modifiez la question permettant de choisir une entité.

Quand vous modifiez laquestion le navigateur va lancer une requête. Le navigateur vous permettra de voir le code de réponse HTTP du serveur, mais aussi le contenu qu'il renvoie au navigateur. L'URL se termine par showfields.php . 

Vérifiez que le serveur répond HTTP 200 OK, et montrez le texte retourné. C'est du texte au format JSON (accolades, crochets, et un schéma de clés / valeurs séparés par le caractère deux-points).

Il faut voir si le JSON n'est pas pollué par du code HTML et un warning PHP, notamment en mode DEBUG de GLPI).

Vérifiez aussi si les outils de développeur de votre navigateur reourne des erreurs Javascript, les logs sql-errors.log et php-errors.log de GLPI.

Reportez ici tout ce que vous trouvez, en filtrant à ce qui concerne le bug.

**Comment by mkael29** [comment]
Résultats:
- showfields.php : {"formcreator_field_41":true,"formcreator_field_1":true,"formcreator_field_2":false,"formcreator_field_45":false,"formcreator_field_46":false,"formcreator_field_47":false,"formcreator_field_48":false,"formcreator_field_49":false,"formcreator_field_50":false,"formcreator_field_62":false,"formcreator_field_4":false,"formcreator_field_66":false,"formcreator_field_21":false,"formcreator_field_24":false,"formcreator_field_10":false,"formcreator_field_11":false,"formcreator_field_70":false,"formcreator_field_22":false,"formcreator_field_12":false,"formcreator_field_23":true,"formcreator_field_40":false,"formcreator_field_42":false,"formcreator_field_43":false,"formcreator_field_44":false,"formcreator_field_51":false,"formcreator_field_57":false,"formcreator_field_63":false,"formcreator_field_60":false,"formcreator_field_53":false,"formcreator_field_54":false,"formcreator_field_55":false,"formcreator_field_56":false,"formcreator_field_59":false,"formcreator_field_64":false,"formcreator_field_61":false,"formcreator_field_65":false,"formcreator_field_67":true,"formcreator_field_68":false,"formcreator_field_69":true}

- Console JS : 
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[En savoir plus] jquery-1.10.2.min.js:1
Logging system initialised at Fri Sep 21 2018 16:24:46 GMT+0200 common.js:206:17
Erreur dans les liens source : request failed with status 404
URL de la ressource : http://glpi.sofimat.fr:81/lib/jqueryplugins/qtip2/jquery.qtip.min.js?v=9.3.1
URL du lien source : jquery.qtip.min.map[En savoir plus]
Logging system initialised at Fri Sep 21 2018 16:24:47 GMT+0200

Pour le mode DEBUG: pas d'erreur.

La question Objet GLPI est le field41 et la question avec une condition est le field49.

Lors d'un clic sur la question Objet GLPI, il y a une requête getDropdownValue.php qui permet de remplir la liste déroulante. Par contre pas d'autre requête après une sélection.

**Comment by btry** [comment]
Apparement tout est bon. Il semble donc qu'il y a un problème au moment de comparer la valeur de la question avec celle de la condition.

Il va falloir que je reproduise. Dans la conditions vous avez renseigné un ID d'entité ou un nom ? Il faut également vérifier si vous testez l'entité racine (ID = 0) il y a un cas particulier où le plugin pourrait mal se comporter.

la requete getDropdownValue est normale. Elle va chercher les valeurs à afficher dans la dropdown affichée à l'écran.

**Comment by mkael29** [comment]
Il semblerait que le script suivant ne soit pas exécuté:

jQuery(document).ready(function($) { jQuery("#dropdown_formcreator_field_411908526926").on("select2-selecting", function(e) { formcreatorChangeValueOf (41, e.val); }); })

**Comment by mkael29** [comment]
Si je modifie le fichier inc/field/dropdownfield.inc.php pour ajouter un alert(e.val) avant formcreatorChangeValueOf, je n'ai pas d'affichage à l'écran.

jQuery(document).ready(function($) { jQuery("#dropdown_formcreator_field_41405922027").on("select2-selecting", function(e) { alert(e.val); formcreatorChangeValueOf (41, e.val); }); });

**Comment by btry** [comment]
Intéressant.

GLPI 9.3 a une nouvelle version de select2. Cela a eu un impact sur le fonctiohnnement du plugin; la versin 2.6.4 vise entres autres à corriger ces soucis. 

Pourriez vous vérifier si le bug persiste avec Formcreator 2.6.4 exécuté sur GLPI 9.2.x ?

**Comment by mkael29** [comment]
Je n'ai plus de GLPI 9.2 de disponible.

**Comment by btry** [comment]
Alors il va falloir que je teste moi même, mais je ne peux pas le faire avant quelques jours.

**Comment by mkael29** [comment]
Par contre j'ai d'autres questions en liste déroulante mais avec des valeurs fixes, et là pas de problème, le formulaire est bien actualisé lors de la sélection d'une valeur. J'ai l'impression que le problème n'est qu'avec les Objets GLPI.

**Comment by btry** [comment]
C'est fort possible. C'est le genre de problème que je veux définitivement éliminer en 2.7.0 (voir #1106).

Pour m'aider à reproduire dites moi si des noms d'entités contiennent des caractères accentués ou spéciaux. Ca peut être déterminant. J'ai aussi besoin de savoir si votre condition contient l'ID de l'entité ou un nom.

**Comment by mkael29** [comment]
A part l'Entité racine pas d'accent dans les noms sauf une un é.
Le résultat est le même que se soit avec l'ID ou le nom.

**Comment by btry** [comment]
Et initialement, la condition contenait un nom ?

**Comment by mkael29** [comment]
Actuellement, la condition contient le nom.
Je viens de supprimer l'accent mais toujours le problème.

**Comment by btry** [comment]
C'est noté. Patientez quelques jours, je reviens avec un fix ou avec d'autres questions si je n'arrive pas à reproduire.

**Comment by mkael29** [comment]
Pas de souci.

**Comment by btry** [comment]
Bonjour

J'ai reproduit le bug, et effectivement il y a du code JS qui n'est pas exécuté. C'est lié à l'upgrade du composant Select2 entre GLPI 9.2 et 9.3.

De plus, il faut utiliser l'ID de l'entité dans l'expression de condition, comme il faut le faire pour comparer la valeur d'un champ de type intitulé (lieu est connu pour avoir cette contrainte).

Pour résoudre le souci patchez selon cette PR https://github.com/pluginsGLPI/formcreator/pull/1131

**Comment by btry** [comment]
Bonjour,

Merci pour le retour. Notez qu'en version 2.7.0 je résoudrai le problème imposant l'usage d'un ID à la place du libellé de l'entité. Je pense pouvoir faire la mise à jour des conditions automatiquement
