### ISSUE TITLE
Status and log update for form

### ISSUE THREAD

**Issue by lquenta** [pluginsGLPI/formcreator#1123]
Hi.
I was successfully created a form that creates automatically a Ticket, since it's created from the data of a form, i had two issues:
1) The user that filled the form has no way to know which form corresponds to a ticket in an easy way (a link)
2) In the log section of the created form, it just notifies the creation of a petition, but nothing else, the newly created Ticket, has reassigned, closed, but the user has no way (other than notification from emails) that know the exact history of the ticket.
There is a way to show to the user all the history of the ticket (reassignation, status) in the web interface?

Thanks for your help

**Comment by btry** [comment]
Hi

Can you tell which version of Formcreator ?

## 1
In your generated ticket the requester should see hos answer as associated element, like a user could associate a computer in a regular ticket. If he does not see it, then the profile of your requester misses the itemtype Form Answer.
![image](https://user-images.githubusercontent.com/14139801/46003420-cb286780-c0b0-11e8-8573-7452b1448649.png)

## 2

Once a form is flled and a ticket is generated you should use  the histotry of the ticket to followup related events. What prevents the user to read this history ?

**Comment by lquenta** [comment]
Hi Thanks for your answer, i just solved it by giving the proper profile assignement to displayvall the tickets created by the form and now the user can check all the history, your indications worked great! , 

Thanks, btw i'm using the 2.6.3 version.
