### ISSUE TITLE
You usually forget to write GLPI compatibility in the release. It is very frustrating!

### ISSUE THREAD

**Issue by valentindragan** [pluginsGLPI/formcreator#1126]
You usually forget to write GLPI compatibility in the release. It is very frustrating!

**Comment by btry** [comment]
Hi,

The compatibility data are in the file plugin.xml which feeds this page: http://plugins.glpi-project.org/#/plugin/formcreator

I'll add compatibility information in the recent releases.

**Comment by btry** [comment]
Added compatibility for all 2.6.x releases.
