### ISSUE TITLE
Separate form by default

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#1130]
Hello,

For users portal, I would like to put incident form highlighted.

Would it be possible to change the color or put this form a the top ?

Thank you for your job and your reply

**Comment by btry** [comment]
Hi

You may sponsor the feature by contacting us at contact@teclib.com .

**Comment by btry** [comment]
Hi It is now possible to change the background color of forms, and set them a custom icon.

I guess this ticket can be closed now.
