### ISSUE TITLE
Use GenericObject plugin objects in the Glpi objects fields

### ISSUE THREAD

**Issue by mohierf** [pluginsGLPI/formcreator#1133]
**Is your feature request related to a problem? Please describe.**
I created some objects types with the Generic Object plugin but I cannot create a field that is relating to my new objects.

**Describe the solution you'd like**
Simply have the Generic Object plugin new types in the GLPI objects list

**Comment by btry** [comment]
Hi

I think your issue duplicates #660

**Comment by mohierf** [comment]
For sure ... sorry but I did not saw the former issue.
