### ISSUE TITLE
View the tickets on a map

### ISSUE THREAD

**Issue by mohierf** [pluginsGLPI/formcreator#1134]
As of now, the user can only see its tickets in a search engine and table. It does not llok possible to view the tickets on a map

I would like Something like this:
![image](https://user-images.githubusercontent.com/2932687/46668515-ea54e800-cbcc-11e8-8446-451fa0a28652.png)

**Comment by btry** [comment]
Hi

In which view do you want to get a map ? in the service catalog ?

**Comment by btry** [comment]
Hi

map viex for  tickets is implemented in GLPI. Closing.
