### ISSUE TITLE
Evolution ?

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1138]
Est-ce possible d'exporter les données formulaire du plugin afin de les importer sur une autre instance ?

**Comment by btry** [comment]
Bonjour,

Oui. Allez dans la liste de vos formulaires (partie administration), et cochez le ou les formulmaire(s) à exporter. Cliquez sur le bouton "Action" en haut ou en base de la liste. Vous aurez une fenêtre proposant diverses actions. L'une d'elle permet d'exporter au format JSON les formulaires sélectionnés.

Pour importer, vous avez un icône en haut de la liste des formulaires représentant un disque support de stockage avec une flèche (près du fil d'Ariane). 

Il y a une limitation à la fonctionnalité. Les formulaires peuvent être paramétrés pour avoir des relations avec des objets de GLPI (utilisateurs, gabarits, ...) Certaines relations ne seront pas réimportées, il faut les rétablir manuellement.

**Comment by EC2311** [comment]
ok !
Merci

**Comment by btry** [comment]
Réponse approuvée, je clos ! 

Pensez au forum GLPI si vous avez des questions : https://forum.glpi-project.org/ . Cet espace est plutôt dédié aux bugs et demandes de fonctionnalités.
