### ISSUE TITLE
Line wrap error with rich text

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#1139]
Line wrap error with rich text.

**To Reproduce**
1. Enable the option:
General > Assistance > Use rich text for helpdesk -> Yes
2. Create a form with a textarea fild e destination for a change. At the destination of the form (change), the "List field" answer is assigned to the field impacts.
3. Fill out the form with a list.

**Expected behavior**
In the impacts field the list is expected:
1. one
2. two
3. three

**Actual result**
```<p><p>1. one</p><p>2. two</p><p>3. three</p></p>```

**Screenshots**
![image](https://user-images.githubusercontent.com/26510405/46915531-5f387100-cf83-11e8-8b08-cf244104542d.png)
![image](https://user-images.githubusercontent.com/26510405/46915523-3617e080-cf83-11e8-931a-f6d3db027a80.png)
![image](https://user-images.githubusercontent.com/26510405/46915556-9c046800-cf83-11e8-830b-8f311eea2879.png)

**Desktop (please complete the following information):**
 - OS: Mint Linux 19
 - Browser firefox 62.0.3, 

I'm using 2.6.5-bugfix version.

**Comment by btry** [comment]
Hi

Please test this fix and feedback.

![image](https://user-images.githubusercontent.com/14139801/46939384-6f754c80-d066-11e8-8c1e-a6ebef61a966.png)

**Comment by pedroluisvsousa** [comment]
That's ok.

**Comment by btry** [comment]
Hi

Thank you for your feedback. The fix is ready for the next reelase.

**Comment by btry** [comment]
Hi

please try this fix and feedback quickly. Release is imminent.

https://github.com/pluginsGLPI/formcreator/pull/1178/files

**Comment by pedroluisvsousa** [comment]
Hi,
the problem with the characters was resolved.
![screenshot_2018-11-02 glpi - changes - 30 1](https://user-images.githubusercontent.com/26510405/47908133-61e40300-de6b-11e8-974f-ef1a0fd34626.png)


However there is a formatting problem in the Description field.
![screenshot_2018-11-02 glpi - changes - 30](https://user-images.githubusercontent.com/26510405/47908149-67414d80-de6b-11e8-8937-2e4d2223a040.png)

**Comment by pedroluisvsousa** [comment]
When you set "Use rich text for helpdesk = yes", the problem persists.
![screenshot_2018-11-02 glpi - changes - 4](https://user-images.githubusercontent.com/26510405/47910342-51368b80-de71-11e8-8617-a22fb82b7708.png)
![screenshot_2018-11-02 glpi - changes - 4 1](https://user-images.githubusercontent.com/26510405/47910341-51368b80-de71-11e8-915c-51719e9d24fb.png)

**Comment by btry** [comment]
i reproduce with  rich text mode. and added a fix.

In this comment https://github.com/pluginsGLPI/formcreator/issues/1139#issuecomment-435326125, you was with rich text disabled ?

**Comment by btry** [comment]
Ok, I reproduced also without rich text. 

An other update to the fix is online.I'm waiting for your feedback. Few hours left before the release due to the week end.

**Comment by btry** [comment]
Hi, 

I figured it out. Please download the new changes and try again.

**Comment by pedroluisvsousa** [comment]
Hi,
It has been tested in both modes. That's OK. Thank you very much.

**Comment by btry** [comment]
great ! I merge,  thank you for your feedback !
