### ISSUE TITLE
Liste des issues ne contient pas celles des sous entités

### ISSUE THREAD

**Issue by mohierf** [pluginsGLPI/formcreator#1146]
La liste des issues présentées pour un utilisateur ne contient pas les issues qui ont été ouvertes dans les sous entités auxquelles cet utilisateur a accès.

Exemple:
 L'utilisateur A a accès aux entités 1, 1.1 et 1.2. Si un utilisateur B ouvre un ticket dans l'entité 1.1, l'utilisateur A ne voit pas ce ticket dans sa liste des demandes d'assistance. Est-ce parce que ce n'est pas lui qui l'a ouvert ? ou est-ce parce que c'est dans une sous entité ?

Je suppose que ce comportement n'est pas forcément lié aux entités mais peut être plutot car un utilisateur ne peut voir que les demandes qu'il a lui même émises ?

Ce comportement est-il configurable d'une façon ou d'une autre ? Je n'ai rien vu dans ce sens ...

**Comment by btry** [comment]
Bonjour

J'ai besoin de précision. Dans quelle partie de l'interface avez vous ce comportement ?

**Comment by mohierf** [comment]
C'est dans la liste des issues, l'onglet "Mes demandes d'assistance" de l'interface Helpdesk (http://127.0.0.1/glpi/plugins/formcreator/front/issue.php?reset=reset)

**Comment by mohierf** [comment]
@btry: any news about this ?

**Comment by btry** [comment]
Hi,

Not yet. Stay tuned.

**Comment by btry** [comment]
Hi,

In your example, is user A an actor of the ticket ?

**Comment by mohierf** [comment]
No. User A is not concerned by the ticket.

Indeed I would like that user A is able to see all the tickets of his entoty and sub-entities ... whether it is an actor or not for the tickets

**Comment by mohierf** [comment]
I just tried with the same user (A) and a different profile and I get all the tickets in my list ... it looks like the prolem is because of the Self Servce user profile ...

**Comment by btry** [comment]
Your user A must be a requester or a watcher of the generated ticket to have access to it from the service catalog.

Why your user A needs to access all tickets for his entity from the service catalog ? As the item on the left panel says, you should see your requests : those you're involved as a requester or an observer (but not asignee).

**Comment by btry** [comment]
An addition: the request generating the list of requests is partially generated by the plugin. 

Have a loon on this request 

```sql
SELECT DISTINCT `glpi_plugin_formcreator_issues`.`id` AS id, 'glpi' AS currentuser, `glpi_plugin_formcreator_issues`.`sub_itemtype`, `glpi_plugin_formcreator_issues`.`entities_id`, `glpi_plugin_formcreator_issues`.`is_recursive`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_plugin_formcreator_issues`.`name`, '$#$' , `glpi_plugin_formcreator_issues`.`id`) SEPARATOR '$$##$$') AS `ITEM_0`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_formcreator_issues`.`display_id`, '__NULL__'), '$#$', `glpi_plugin_formcreator_issues`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_0_display_id`, `glpi_plugin_formcreator_issues`.`display_id` AS `ITEM_1`, `glpi_plugin_formcreator_issues`.`status` AS `ITEM_2`, `glpi_plugin_formcreator_issues`.`date_creation` AS `ITEM_3`, `glpi_plugin_formcreator_issues`.`date_mod` AS `ITEM_4`, `glpi_entities`.`completename` AS `ITEM_5`, `glpi_users_requester_id`.`name` AS `ITEM_6`, `glpi_users_requester_id`.`realname` AS `ITEM_6_realname`, `glpi_users_requester_id`.`id` AS `ITEM_6_id`, `glpi_users_requester_id`.`firstname` AS `ITEM_6_firstname`
FROM `glpi_plugin_formcreator_issues`
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 )
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b` ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )
LEFT JOIN `glpi_entities` ON (`glpi_plugin_formcreator_issues`.`entities_id` = `glpi_entities`.`id` )
LEFT JOIN `glpi_users` AS `glpi_users_requester_id` ON (`glpi_plugin_formcreator_issues`.`requester_id` = `glpi_users_requester_id`.`id` )
WHERE 
( `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.users_id = '2' 
 OR `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.users_id = '2' 
 OR `glpi_plugin_formcreator_issues`.`requester_id` = '2'
) AND ( 
 `glpi_plugin_formcreator_issues`.`entities_id` IN ('5') 
 OR (`glpi_plugin_formcreator_issues`.`is_recursive`='1' 
  AND `glpi_plugin_formcreator_issues`.`entities_id` IN ('0','2')
 )
) AND 
( 
 `glpi_plugin_formcreator_issues`.`status` IN ('1','2','3','4','waiting','accepted') 
) 
GROUP BY `glpi_plugin_formcreator_issues`.`id`
ORDER BY ITEM_0 ASC 
```

especially this part which filters the result
```sql
WHERE 
( `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.users_id = '2' 
 OR `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.users_id = '2' 
 OR `glpi_plugin_formcreator_issues`.`requester_id` = '2'
)
```
which references these JOINs 
```sql
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 )
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b` ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )

```

**Comment by mohierf** [comment]
Got it. I did more tests and I understand the logic behind this ... and I think that it may be interesting for a user to have a view of all the tickets of an entity. Let me explain ...

Let's say I am the boss of an entity having sub-entities. Neither am I the requester nor the observer of the tickets opened for my Entity ... but I am simply interested in the tickets list and counts !

**Comment by btry** [comment]
In such case, I would recommend you use the helpdesk, not  the simplified interface. The task you're describing is near to a reporting task.

**Comment by mohierf** [comment]
Ok, but in the same entity, I have some users using the Services catalog and one user that need the legacy Helpdesk interface ... how should I configure this ?

**Comment by btry** [comment]
I  guess that the user who needs the helpdesk already has access to the simplified interface. Give him the right to use the same entity (with recursion in your case) with a profile configured with the helpdesk. He will be able to change his profile to switch between the simplified interface or the helpdesk.

An exemple:

![image](https://user-images.githubusercontent.com/14139801/47504349-5ccff400-d86c-11e8-82a5-3f65de5c6ba0.png)

![image](https://user-images.githubusercontent.com/14139801/47504419-82f59400-d86c-11e8-90af-e26c8a6ed5e8.png)

![image](https://user-images.githubusercontent.com/14139801/47504442-8d179280-d86c-11e8-8e6e-05ca69b07072.png)

**Comment by mohierf** [comment]
Ok, so it will be able to switch between the profiles ... hmmm, I will have some remarks about the UI being more complex than needed 😉 

I did some more tests: 
- add my Boss user in a *Bosses users* group
- make this group as an observer for the tickets created from the forms

And then my Boss user is seeing the tickets created by some other users in the sub entities of his entoty ... and that's almost what I wanted !

**Comment by btry** [comment]
Well, the simplified interface alreay gives the ability to switch between profiles or entities. If you are an admin a,d want to try a profile for other types of users, thisz is convenient. And the ability to quite the service catalog or the simplified interface is necessary; or you would lock yourself for the lifetime of a session :D 

Your solution will do the trick too, but beware : he may receive a lot of notifications.

So can we close this issue ?

**Comment by mohierf** [comment]
If you set the user as an observer without mail notifications ... it does the trick 😉
