### ISSUE TITLE
"Objet-GLPI" de type "Catégorie" : prendre en compte les paramètres de visibilité

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/formcreator#115]
Hello,

Dans la configuration d'une catégorie (intitulé) on peut lui indiquer "Visible pour XXX" (XXX pouvant être interface simplifiée/incident/demande/problème/changement) à "Non".

Cette configuration ne semble pas reprise lorsqu'on ajoute l'objet Catégorie sur un formulaire : on voit l'ensemble des catégories de l'entité.

Il faudrait trouver une solution pour que ces paramètres (ou un autre) soient pris en compte.

++
François.

**Comment by neeftarah** [comment]
Salut,

GLPI ne semble pas gérer ces choses automatiquement en natif mis à part via l'attribut "condition" à passer manuellement à la fonction Dropdown::show().

Gérer ce genre de cas dans Formcreator reviendrais sans doute à faire un sélecteur par intitulé. Difficile, d'autant que n'importe qui peut rajouter des intitulés.

Une solution possible serait de rajouter, pour les questions de type intitulé, un champ texte permettant de saisir pour chaque question ce champs "condition" (un peu comme les regex des questions de type "text" et "textarea").

Dit moi si cette solution semble te convenir ou si tu a d'autres idées.

Cordialement,
Jérémy.

**Comment by dgsn** [comment]
Bonjour,
Je commence à utiliser les formulaires et effectivement il serait pratique de pouvoir ajouter un paramètre supplémentaire au niveau des champs de type intitulé ou Objet GLPI.
Ce paramètre pourrait être un zone de texte reportée tel que dans une clause de type like '%xxx%' de la requête SQL récupérant la liste des intitulés ou des Objets GLPI ciblés.
On peut même ajouter un sélecteur transformant la clause LIKE en NOT LIKE.
Ce mécanisme est déjà utilisé dans la sélection standard des liste déroulante dans GLPI.
Qu'en pensez-vous ?
Bien cordialement.
David
