### ISSUE TITLE
Base de connaissance

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1150]
Bonjour,
Est-ce qu'il est envisagé de pouvoir accéder à la base de connaissance depuis la page d'accueil "catalogue de service" simplifié ou pas?
Merci

**Comment by btry** [comment]
Bonjour, c'est implémenté edpuis al création du catalogue de service.

Vous devez relier les catégories de formulaires aux catégories de la KB. Une fois fait la navigation dans les catégories afichera les éléments de KB avec les formulaires. Le moteur de recherche porte sur les 2 types de ressources.
