### ISSUE TITLE
Not create a tiquet when some sections o question title have some characters

### ISSUE THREAD

**Issue by nuria2c** [pluginsGLPI/formcreator#1158]
We can't use in the title of the sections and in the select options the character ' (apostrophe) 

We can use it the title field of the question and secttion and in the form the title appears correctly. 

The problem is: when the user sends the form data, the form is created but not the ticket to manage it.
We doesn't have validated forms, therefore, when sending the form, the ticket is automatically created.

We have GLPI 9.2.4 and Form creator 2.6.0
We have Catalan language as default language but the error also is reproduced when change to English language default.

**To Reproduce**
Example 1
1. Create a form and select "All languages" in the language option
2. Create a section with question with title "Dades de l'usuari"
3. create a question with title "Usuari"
4. Define a Destination and a Target

**Expected behavior**
Ticket and form created succefully

**Screenshots**
![image](https://user-images.githubusercontent.com/5544480/47495854-8af60980-d855-11e8-9261-bb6837f3e708.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: 

**Smartphone (please complete the following information):**
 - Version: 66.0

**Comment by btry** [comment]
Hi

Several fixes related to an apostrophe were fixed since 2.6.0. Please upgrade to the version 2.6.4 and try again. Notice I'm nearly ready to release 2.6.5, which is the last version compatible with GLPI >= 9.2.1 and < 9.3 .

**Comment by btry** [comment]
Hi

Any feedback @nuria2c ? I'm planning to produce the release 2.6.5 next monday. If the fix is easy for 2.6.x you have a chance to have the fix in the incoming release.

**Comment by nuria2c** [comment]
Hi,
We can’t answer you yet. We have to test the new version of plugin in a test environment.


De: btry <notifications@github.com>
Enviat: dimarts, 30 d’octubre de 2018 16:20
Per a: pluginsGLPI/formcreator <formcreator@noreply.github.com>
A/c: Núria Costa Casas <nuria.costa@uvic.cat>; Mention <mention@noreply.github.com>
Tema: Re: [pluginsGLPI/formcreator] Not create a tiquet when some sections o question title have some characters (#1158)


Hi

Any feedback @nuria2c<https://github.com/nuria2c> ? I'm planning to produce the release 2.6.5 next monday. If the fix is easy for 2.6.x you have a chance to have the fix in the incoming release.

**Comment by btry** [comment]
Hi

You can update the locales yourself to have the latest updates. 

I'll investigate for this quote problem with 2.7.0

**Comment by btry** [comment]
hi

https://user-images.githubusercontent.com/5544480/48259308-dd1f5900-e417-11e8-97ec-537d7b7afd47.png

The JS error in this above picture was identified here : https://github.com/glpi-project/glpi/issues/5321 and has a fix. Could you check the fix works for you ?

**Comment by btry** [comment]
Hi,

Closing due to lack of feedback.
