### ISSUE TITLE
TTR not populated in Change Request

### ISSUE THREAD

**Issue by xmprx** [pluginsGLPI/formcreator#1161]
GLPI 9.3.2, formcreator 2.6.4

TTR (Time to Resolve) attribute from the answer in a form is not populated in the resulting Change Request.

**Steps to reproduce**
1. Create a form with a question using a Date & Time field as the answer.
2. Use Change Request as Destination, set Time To Resolve to "equals to the answer to the question" and pick the question/answer created in the first step.
3. Fill out the form as a user would.
4. Check the resulting change request, the TTR field won´t be populated.

**Expected behavior**
TTR field is populated from the answer.

**Additional context**
This very scenario works correctly when a Ticket is used as a Destination (appears to be Change Request related).

**Comment by btry** [comment]
Hi

Please test this fix and fedbaack.
