### ISSUE TITLE
Change title overwritten by name when saving

### ISSUE THREAD

**Issue by xmprx** [pluginsGLPI/formcreator#1162]
GLPI 9.3.2, formcreator 2.6.4

Change title field is overwritten by name field when saving a Destination.

**Steps to reproduce**
1. Create a form with a Change Request as a Destination.
2. Edit this Destination in any way, or just open it and click save.
3. After the page reloads, the second field - Change title will be overwritten by the first field - Name.

**Expected behavior**
Change title field shall be left intact after saving a Destination.

**Additional context**
This very scenario works correctly when a Ticket is used as a Destination (appears to be Change Request related).
Also, as a workaround, you can just use the same value for both fields to prevent a visible change of a Change title field.

**Comment by btry** [comment]
Hi,

please test the above patch and feedback.

**Comment by xmprx** [comment]
Hi,

the fix fixes the issue, fields are no longer being overwritten.

Thank you!
