### ISSUE TITLE
PHP Error in issue.php after form answers deletion

### ISSUE THREAD

**Issue by mohierf** [pluginsGLPI/formcreator#1177]
```
[2018-10-31 09:19:52] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/formcreator/inc/issue.class.php:479        
  plugins/formcreator/hook.php:256                   PluginFormcreatorIssue::giveItem()
  inc/search.class.php:5090                          plugin_formcreator_giveItem()
  inc/search.class.php:1384                          Search::giveItem()
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  plugins/formcreator/front/issue.php:61             Search::show()
  {"user":"664@glpi-VirtualBox","mem_usage":"0.000\", 2.85Mio)"} 
```

This error happens very frequently after I deleted some form answers. 

I had several form answers, then I deleted permanently some of them and deleted some others (still in the trash). Since the deletion, I have a lot of PHP errors like the log upper

**Comment by btry** [comment]
Hi

I think you have one error per deleted form answer. Please can you describe the targets of the form which  generated those answers ? Can I reproduce with one target ticket or several target tickets ?

Also, I guess this happens with develop branch,  right ?

**Comment by btry** [comment]
Hi

Having no feedback, I close
