### ISSUE TITLE
données saisies non insérées en table

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1179]
Bonjour,
je me trouve devant un problème similaire avec un autre plug-in (surveyticket) où lorsque je renseigne le champ "comment" afin de rediriger certaines parties du questionnaire vers tel ou tel groupe, les données saisies ne sont pas enregistrées.
J'ai tenté un import d'une autre base où le plug-in a fonctionné ...
Les données sont alors bien visibles en table, mais rien n'apparait dans l'applicatif !!!!

En mode debug, j'ai le message d'erreur suivant 👍 

  | PHP Notice: Undefined index: comment in C:\wamp\www\glpi_test\plugins\formcreator\inc\targetticket.class.php at line 119
-- | --

Je suis sur GLPI 9.3.2, avec la dernière version du plug-in, PHP 7.2.10, mysql 5.7.23 ; les table sont toutes migrées en innoDB.

Merci pour votre aide :)

**Comment by btry** [comment]
Bonjour

Quelle est la version de Formcreator ?

**Comment by btry** [comment]
Bonjour

Pouvez-vous montrer la structure de la table glpi_plugin_formcreator_targettickets ?

**Comment by Sicoval31** [comment]
Bonjour,
nous avons la version 2.6.5.
Voici la structure de la table 👍 
![image](https://user-images.githubusercontent.com/42040529/48539422-56ef9080-e8b7-11e8-8d6f-03dcc52d665a.png)

Merci à vous :)

**Comment by btry** [comment]
Bonjour,

J'ai l'impression que vous avez upgadé vers la version 2.7.0 en cours de développment puis êtes revenu à une version 2.6.x. La colonne **content** portera ce nom à partir de la version 2.7.0 pour des raisons de cohérence. Dans les versions 2.6.x elle doit s'appeler **comment**.

Renommez cette colonne et voyez si votre problème persiste.
