### ISSUE TITLE
Choose the follow-up email address from an answer 

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/formcreator#1190]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
provide a new field for actors added in the target settings
use a question to set the email address of a user defined in the target or a question, the user being used as an actor.
![image](https://user-images.githubusercontent.com/23405363/48193447-c7902d80-e34a-11e8-9298-6693283fda65.png)

**Describe alternatives you've considered**
All other solution

**Additional context**

**Comment by btry** [comment]
![image](https://user-images.githubusercontent.com/14139801/52260745-59e2a600-2927-11e9-93e5-8bf5ad0a96cf.png)


![image](https://user-images.githubusercontent.com/14139801/52260765-68c95880-2927-11e9-84c0-ea7632a4c8cd.png)


![image](https://user-images.githubusercontent.com/14139801/52260732-4df6e400-2927-11e9-9b01-7cea49e4c23c.png)

**Comment by titidelaff** [comment]
Works for me

**Comment by btry** [comment]
Great, then I close.
