### ISSUE TITLE
problème de condition d'affichage des champs

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#1192]
**Describe the bug**
lorsque l'affichage d'un champ est conditionné par un autre champ qui a une valeur de type "GLPI object", cela ne fonctionne pas. Testé avec la version 2.6.5 de formcreator

**To Reproduce**
1 - Créer une question "A" de type "Objet GLPI"
2 - Créer une seconde question "B" configuré avec "Masqué par défaut sauf si" "A" "=" valeur
3 - Malgrè les changements de valeur de la question "A", la question "B" n’apparaît jamais.

Il est possible que celà soit du à un TRIM sur la valeur.
Pour pousser l'analyse, j'ai créé un consommable "test".
Lorsqu'il est sélectionné, la valeur qui est affichée dans le code de la page est "test - "
Lorsque je mets cette valeur dans la condition et que j'enregistre, l'espace à la fin disparaît.
Je ne sais pas si c'est le même fonctionnement avec les autre objets.

Testé avec Utilisateurs, Ordinateur et Consommables

**Expected behavior**

Il faut que la valeur soit reconnue. L'idéal, serait que la valeur corresponde au champ "Nom", Identifiant,.. exactement.
**Screenshots**

**Desktop (please complete the following information):**
Chrome 70.0.3538.77 + IE 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment]
Bonjour,

Il faudrait vérifier si ça persiste avec la version 2.7.0; la quasi totalité des champs et leurs interactions a été réécrite.

**Comment by tdelaux** [comment]
Bonjour,

Afin d'effectuer les test en 2.7.0, existe-t-il une documentation sur l'installation d'une version en cours de développement ?

Merci

**Comment by btry** [comment]
Bonjour

Il n'y a rien de particulier à faire : prenez un GLPI de test; idéalement avec uen copie de la BDD de production pur avoir vos formulaires. Ensuite faites un upgrade du plugin vers la branche develop.

Si vous connaissez les bases de git je vous conseille de l'utiliser pour installer les fichiers du plugin. Ca vous permettra de récupérer facilement les corrections versées ou à tester. Sinon, téléchargez le zip ici : https://github.com/pluginsGLPI/formcreator/archive/develop.zip

**Comment by tdelaux** [comment]
La version en cours de développement corrige bien ce bug.
Par contre, un nouveau bug est introduit pour le type "boite à cocher". Ce type de champ n'est plus masqué lorsqu'il est conditionné par un "masquer par défaut sauf si"

Cordialement,

**Comment by btry** [comment]
Bonjour, 

J'ouvre #1197 pour ce souci. Pensez à faire un ticket par bug ou feature pour un meilleur suivi.

**Comment by btry** [comment]
J'ai trouvé le souci. Voyez la PR associée #1197. Le bug devait toucher tous les types de champs, donc je pense que ça fermera tous les autres tickets similaire que vous avez créé.

**Comment by btry** [comment]
Bonjour,

Avez-vous pu tester le correctif ? A défaut je le considèrerai comme valide (vu que j'ai pu reproduire et coriger le bug de mon côté).

**Comment by btry** [comment]
bonjour,

pas de retour, je ferme.
