### ISSUE TITLE
Problème de génération des tickets \r\n

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#1193]
**Describe the bug**
Bonjour,
depuis la version 2.6.5, les tickets générés comportent les caractères "\r\n" à la place de retour à la ligne dans la description du ticket lorsque le contenu de la destination est créé spécifiquement.

Exemple de Description dans le ticket de destination :

---

Demandes pour les applications suivantes : ##answer_8##

Pour l'utilisateur : ##answer_7##
Profil identique à l'utilisateur : ##answer_11##

Commentaire : ##answer_14##

---

ce qui donne comme description du ticket : 

---

Demandes pour les applications suivantes : \r\nMOVEX\r\n\r\nPour l'utilisateur : tech\r\nProfil identique à l'utilisateur : post-only\r\n\r\nCommentaire : ryèu

---

Cordialement,

**Comment by btry** [comment]
Bonjour

Le mode texte riche est il activé dans votre GLPI ?

**Comment by SylvainGuibert** [comment]
Bonjour,

Le problème est similaire pour nous depuis le passage en 2.6.5.
Concernant le mode texte riche , il est désactivé de notre coté : 

![2018-11-15_11h00_35](https://user-images.githubusercontent.com/16323410/48545236-bce31480-e8c5-11e8-8ba8-813747b8c9c7.png)

Je rajouterais en plus des carctères \r\n, le \ qui apparaît devait les simple quote.

ex : 

S\'agit-il d\'un remplacement de matériel ou d\'une demande ? : Demande
Téléphonie / Lecteur / Douchette : \r\nLecteur CAB

**Comment by tdelaux** [comment]
Le mode texte riche est désactivé de mon coté aussi.

**Comment by btry** [comment]
Bonjour,

Pour faire court, je suis au bout de ce que je peux faire dans la série 2.6.x et sa dette technique. La version 2.7.0 contient des changements majeurs pour s'en débarrasser et éviter les effets de bord qu'on me rapporte après chaque correction liée au rendu des objets cible (ticket, changements).

@SylvainGuibert Pouvez-vous également mener une campagne de tests de la branche develop ? Avoir de nombreux testeurs accélèrera significativement la release 2.7.0.

**Comment by SylvainGuibert** [comment]
@btry : Il faut me tutoyer. Oui, je vais prendre le temps de tester sur la branche develop.

**Comment by SylvainGuibert** [comment]
@btry  : Avec la branche Develop : 
Test unitaire sur un formulaire crée dans une version antérieure :

-> Lorsqu'il il y'a une simple ou double quotte (',") le caractères d'échappement '\' apparaît. Nous avons donc par exemple : S\'agit-il ou \"

-> Lorsque le type de question est "boite à cocher", la réponse dans l'élément de destination (ticket) parfait avec les caractères \r\n devant la réponse.
Exemple : 4) Validation responsable : \r\nOui

-> Pas de problème avec les réponses sur des questions de type "boutons radios", "champ libre" ou bien 
-> Les caractères type @, # , ! , ? ne semblent pas poser de problème.

**Comment by SylvainGuibert** [comment]
Bonjour,

Je viens de faire quelques tests (sur le même formulaire que le premier test). Les tests me paraissent également bon. Plus de caractères type \r\n . En revanche, j'ai testé avec quelques caractères spéciaux et les \\ ne passent pas correctement. Un des deux est supprimé systématiquement. 

Exemple : 

Données dans le formulaire : 

![2018-11-20_09h38_06](https://user-images.githubusercontent.com/16323410/48761179-4c167080-eca8-11e8-9e3c-41d69420d84b.png)

Données dans le ticket : 

![2018-11-20_09h38_21](https://user-images.githubusercontent.com/16323410/48761194-56386f00-eca8-11e8-9601-7c7d731dd187.png)

**Comment by btry** [comment]
Bonjour

J'ai entamé hier un refactorage afin de mieux gérer la production de contenu selon qu'il faille ou non utiliser le texte riche. Je pense que ce refactorage m'aidera à résoudre ce souci. Je prévois la publication du code courant de la semaine prochaine.

**Comment by btry** [comment]
Bonjour @SylvainGuibert 

J'ai fusionné le refactorage dont j'ai parlé. Il semble qu'il a effectivement contribué à résoudre ce problème de double anti-slash. Pouvez-vous mettre à jour votre copie du plugin et voir si le correctif focntionne pour vous également ?
