### ISSUE TITLE
Statut demande vs Statut tickets

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#1194]
**Describe the bug**
Dans l'interface simplifiée, le statut de la demande (qui comporte le formulaire et les tickets associés) n'évolue pas en fonction du statut des tickets.
Ceci est le cas uniquement avec les demandes qui ont données lieux à plusieurs tickets.
Pour l'utilisateur qui se connecte sur son interface GLPI, cela affiche donc de faussent informations (1 demande en cours alors que tous les tickets liés sont clos)

![02](https://user-images.githubusercontent.com/44919953/48349583-ed883b80-e684-11e8-9a92-618c54218c86.jpg)

![03](https://user-images.githubusercontent.com/44919953/48349889-ce3dde00-e685-11e8-9a1d-0a614aa00d09.jpg)

Il faudrait faire évoluer le statut de la demande en suivant le statut des tickets liés. Idéalement, la demande devrait prendre le statut du ticket ayant le statut le plus bas.

Cordialement,
Thomas Delaux

**Comment by btry** [comment]
Bonjour

Je  ferme ce ticket car il est trop ancien. Il y a eu des améliorations sur la gestion des statuts encore très récemment; il est possible que le problème soit résolu. Si des problèmes persistent avec la dernière version, merci d'ouvrir un nouveau ticket.
