### ISSUE TITLE
"show unless" fails on Actor

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#1198]
**Describe the bug**
Formcreator version : development
when a Actor is displayed by a condition "show unless", the field is not hidden when the condition is not met.

**Comment by btry** [comment]
Hi @tdelaux 

i merged the fix for this issue and all other similar ones you created. Can you validate that the development version is fixed ?

**Comment by tdelaux** [comment]
Bonjour,
je me suis bloqué lundi après midi pour effectuer les tests.

Cordialement,

**Comment by btry** [comment]
Bonjour @tdelaux 

Avez vous ds retours sur vos tests ?

Je vais bientôt geler les fonctionnalités pour livrer une version beta.

**Comment by btry** [comment]
Bonjour 

le correctif est fusionné puisqu'il résout le problème (au moins pour moi).  A défaut de retour, je clos ce ticket et les autres qui sont en rapport avec celui-ci.
