### ISSUE TITLE
Modifications de quelques paramétrages

### ISSUE THREAD

**Issue by MaxG89** [pluginsGLPI/formcreator#120]
Bonjour,

Merci pour ce plugin qui permet vraiment de dépasser les limites de GLPI en terme d'ouverture de tickets personnalisés.

Afin de mieux coller à l'activité de mon entreprise j'aurai, de mon coté, souhaité modifier quelques points du plugin afin de répondre aux attentes de nos utilisateurs. J'ai eu beau chercher dans tous les fichiers de ce dernier je n'arrive malheureusement par à trouver ceux me permettant d'avoir la finalité souhaitée. Je me permet donc de venir chercher un peu d'aide ici.

1/J'aurais dans un premier voulu modifier le nom et la destination du bouton Formulaires sous Assistance afin que celui-ci ne renvoi pas sur le répertoire formlist mais directement sur showform.

2/Lors de l'envoi d'un formulaire j'aimerai également que l'utilisateur ne soit plus renvoyé sur formlist mais directement dans le tableau des tickets en cours.

J'ai bien l'impression que les fichiers homepage_forms et homepage_link seraient ceux que j'ai besoin de modifier, mais lorsque je fais les changements (je bidouille et ne suis pas du tout spécialiste) cela ne modifie rien sur mon affichage.

A notre niveau, Formcreator étant utilisé afin de permettre à l'utilisateur de créer des tickets avec des variables conditionnées, j'aimerai lui éviter de jongler entre le menu tickets et le menu formulaires pour ne pas le perdre.

Dans tous les cas je vous remercie par avance pour votre réponse et tient encore une fois à vous féliciter pour le travail accompli.

Cordialement.

MaxG89

**Comment by neeftarah** [comment]
Bonjour,

* Les liens des fils d'ariannes sont dans inc/form.class.php : PluginFormcreatorForm::getMenuContent();
* Les liens du menu dans setup.php : plugin_init_formcreator ()
* Les liens de redirection (pour les formulaires) dans front/form.form.php

Si vous avez besoin de plus d'aide et d'assistance personnalisé, vous pouvez nous contacter par mail à contact@teclib.com.

Cordialement,
Jérémy

**Comment by MaxG89** [comment]
Bonjour Jérémy,

Merci pour votre retour. Je vais regarder tout ça pour tenter d'arriver à ce que je recherche.

Bien cordialement.

Maxime
