### ISSUE TITLE
ticket is empty

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#1205]
**Describe the bug**

Formcreator version : development

generated ticket description is empty

**Comment by btry** [comment]
Hi

Can you describe or provide a screenshot of the configuration of the target ticket, and the answers you gave to the form ?

**Comment by btry** [comment]
Hi

It seems that a fix added for 2.6.5 broke the develop branch, despite a successful cherry-pick.

I took the opportunity of #1207 to search a fix. This pr should fix the issue. Waiting for feedback.

**Comment by btry** [comment]
Hi @tdelaux 

Can you update your copy of the development version and check if the fix works for you ?

**Comment by btry** [comment]
no feedback.. closing.
