### ISSUE TITLE
Ajouter une gestion de profil

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/formcreator#121]
Hello,

Il faudrait pouvoir configurer dans les profils plusieurs droits : 
- droit de créer des formulaires
- droit de supprimer des formulaires
- droit de lire les config des formulaires
  etc...

Actuellement les droits d'accès à la gestion des formulaires sont positionnés sur le droit "UPDATE" d'une "entity" : ce n'est pas du tout logique.

++

**Comment by SylvainGuibert** [comment]
Je suis également intéressé par cette fonctionnalité. La possibilité de laisser à certain profils le droit de créer / modifier des formulaires.

**Comment by nqb** [comment]
+1 pour cette fonctionnalité

**Comment by btry** [comment]
Bonjour

Je garde cela sous le coude pour un développement communautaire. Et appel à contribution, sait on jamais :)

**Comment by Guanymede** [comment]
+1 cette fonctionnalité serait très appréciable. Déjà simplement la possibilité de choisir quels profils peuvent créer des formulaires et quels profils peuvent les utiliser serait une avancée très précieuse !

**Comment by btry** [comment]
Bonjour

@Guanymede : vous pouvez déjà limiter l'acès à un formulaire par profil. Ouvrez un fomulaire, onglet **Cibles**. Choisissez **Droits restreints (profils)**, sauvegardez. Vous pourez ensuite choisir les profils autorisés parmi ceux qui existent.

**Comment by Guanymede** [comment]
Oui, merci beaucoup! Je n’avais pas encore exploré cette possibilité.

Ma difficulté principale par contre, c’est surtout de pouvoir déléguer la création de formulaires à un grand nombre de personnes (via profils) car il n est pas souhaitable de diffuser le compte super admin qui est aujourd’hui le seul disposant des droits de créations/modification de formulaire. 
En tous cas ce plugin est vraiment très pratique et propose une interface idéale entre les utilisateurs et les services support !!

**Comment by MichelKarwatka** [comment]
Je suis également fortement intéressé par la possibilité de déléguer le droit de créer des formulaires via Form Creator à d'autres profils que le profil super admin.
La gestion du GLPI de l'entreprise dans laquelle je travaille est assurée par une équipe limitée en ressources. Tous les sites sont très intéressés par l'outil Form Creator ce qui fait que l'équipe centrale n'est pas en mesure de répondre à toutes les demandes.
Déléguer la gestion des formulaires à un responsable IT des sous-entités est donc primordial pour nous.

**Comment by btry** [comment]
Bonjour

La partie administration (ou si on peut dire "back office") est ouverte à tout utilisateur autorisé à modifier les entités. L'objectif est de limiter les les paramétrages du plugin en s'appuyant au maximum sur ceux que GLPI propose déjà.

Peut être qu'il est envisageable pour vous d'attribuer le droit en modification des entités à vos responsables IT ?

Si cela ne suffit pas, vous pouvez sponsoriser la fonctionnalité en nous contactant à contact@teclib.com .

**Comment by MichelKarwatka** [comment]
Bonjour, 
cette solution me convient tout à fait.
Merci pour votre réponse rapide.
