### ISSUE TITLE
formcreator section no <br> lines in email notification message

### ISSUE THREAD

**Issue by abeulink** [pluginsGLPI/formcreator#1214]
Hello guys,

We use:
Windows 10 Enterprise, version 1803.
GLPI version 9.3.1
Plugin formcreator version 2.6.4
Browsers Firefox version 63.0.1
Chrome version 70.0.3538.102

I have created a form about data leak. 
I have tested it with fake info. Data leak form registered in GLPI no problem, the fields correctly displayed in ticket. 
But there is one problem: e-mail I received, field beschrijving (discription)) is messed by formcreator I think Check below:

> URL : htt ps://help.xxxxxxxx.nl/glpi/index.php?redirect=ticket_1068 
> Ticket: Beschrijving
> Titel :datalek of beveiligingsincident gemeld 
> Requesters : Arno Beulink 
> Begindatum :20-11-2018 12:19 
> Afsluitdatum : 
> Request source :Formcreator
> 
> Associated item : 
> Formulieren antwoorden - Meldingsformulier datalek of beveiligingsincident 
> 
> 
> Status  : Nieuw
> 
> Urgentie : Zeer hoog
> Impact : Gemiddeld
> Prioriteit : Gemiddeld 
> 
> Categorie  :Datalek of beveiligingsincident 
> Beschrijving : Formulier data ================= 0. Over deze melding --------------------------------- 1) Gaat het om een nieuwe of bestaande melding? : Nieuwe melding 2) Als het bestaande melding is, welke nummer? : 1. Contactgegevens en overige algemene informatie --------------------------------- 3) Naam van de organisatie of het bedijf : Test school 4) Adres : fakeadres 127, 5555 NL 5) Naam : testdocent02 6) Functie : testdocent 7) E-mail adres : testdocent02 @test.nl 8) Telefoonnummer : 061234567890 fake phone number 9) De melder is contactpersoon : Ja 10) Naam contactpersoon : 11) Functie contactpersoon : 12) E-mail adres contactpersoon : 13) Telefoonnummer contactpersoon : 14) Was er een andere organisatie betrokken bij de inbreuk? : Nee 15) Naam van de andere organisatie die betrokken was bij de inbreuk : 16) In welke hoedanigheid was de andere organisatie betrokken bij de inbreuk? : 2. Tijdlijn --------------------------------- 17) Extacte datum waarop de inbreuk, indien bekend : 2018-11-20 18) Startdatum van de periode waarbinnen de inbreuk was : 2018-11-19 19) Einddatum van de periode waarbinnen de inbreuk was : 2018-11-20 20) Duurt de inbreuk nog voort? : Ja 21) Wanneer werd de inbreuk ontdekt? : 2018-11-20 22) Als u de inbreuk later meldt dan 72 uur na de ontdekking, wat is daarvan dan de reden? : 3. Gegevens over het datalek --------------------------------- 23) Aard van de inbreuk : Inbreuk op de vertrouwelijkheid van de gegegevens Inbreuk op de beschikbaarheid van de gegevens 24) Wat is de aard van het incident waarbij er een inbreuk op de beveiliging van persoonsgegevens is geweest? : Apparaat, gegevensdrager (bijv. USB-stick) en/of papier met persoonsgegevens kwijtgeraakt of gestolen 25) Geef een samenvatting van het incident waarbij er een inbreuk op de beveiliging van persoonsgegevens is geweest : usb stick lag op tafel, was even weg geweest, daarna lag het niet meer op tafel, overal gezocht, enzovoort 4. Persoonsgegevens die betrokken zijn bij het datalek --------------------------------- 26) Persoongegevens in het algemeen : Naam Geslacht, geboortedatum en/of leeftijd Contactgegevens Locatiegegevens 27) Onbekend / anders, namelijk: : 28) Bijzondere categorieën van persoonsgegevens : Onbekend / anders, namelijk: (hieronder invullen) 29) Onbekend / anders, namelijk: : NAW 30) Geef (eventueel bij benadering) aan hoeveel gegevensrecords ("gegevensregisters") zijn getroffen door de inbreuk : 450 5. De groep mensen van wie persoonsgegevens betrokken zijn bij het datalek --------------------------------- 31) De groep mensen van wie persoonsgegevens betrokken zijn bij het datalek : Leerlingen of studenten Minderjarigen 32) Omschrijf de groep mensen van wie persoonsgegevens zijn betrokken bij de inbreuk : leerlingen test school 33) Van minimaal hoeveel personen zijn persoonsgegevens betrokken bij de inbreuk? : 0 ??? 34) Van maximaal hoeveel personen zijn persoonsgegevens betrokken bij de inbreuk? : 450 ??? 6. Maatregelen die zijn getroffen voordat het datalek plaatsvond --------------------------------- 35) Waren de persoonsgegevens op het moment dat de inbreuk zich voordeed versleuteld, gehasht of op een andere manier onbegrijpelijk of ontoegankelijk voor onbevoegden? : Nee 36) Als de persoonsgegevens deels onbegrijpelijk of ontoegankelijk waren, om welk deel gaat dat dan? : 37) Als de persoonsgegevens geheel of deels onbegrijpelijk of ontoegankelijk waren gemaakt, op welke manier is dit dan gebeurd? : 7. Gevolgen van het datalek --------------------------------- 38) Gevolgen van de inbreuk op de vertrouwelijkheid, de integriteit en/of beschikbaarheid van de gegevens : Onbevoegden hebben kennis kunnen nemen van de gegevens De gegevens kunnen op een onbehoorlijke of onrechtmatige manier worden gebruikt Er worden binnen uw eigen organisatie mogelijk onjuiste, onvolledige of achterhaalde persoonsgegevens gebruikt Er worden mogelijk onjuiste, onvolledige of achterhaalde persoonsgegevens hergebruikt voor andere doeleinden of doorgegeven aan andere organisaties 39) Anders, namelijk: : 40) Lichamelijk, materiële en immateriële schade voor de betrokkenen, welke gevolgen kan de inbreuk hebben voor de persoonlijke levenssfeer van de betrokkenen? : Identiteitsdiefstal of -fraude Reputatieschade Verlies van vertrouwelijkheid van door het beroepsgeheim beschermde persoonsgegevens 41) Andere gevolgen, namelijk: : 42) Geef een inschatting van de ernst van de mogelijke gevolgen voor de betrokkenen : Aanzienlijk 8. Vervolgacties naar aanleiding van het datalek --------------------------------- 43) Heeft u het datalek gemeld aan de betrokenen of bent u van plan dat te gaan doen? : Ja 44) Wanneer heeft u het datalek gemeld aan de betrokkenen? : 45) Wanneer gaat u het datalek melden aan de betrokkenen? : 46) Wat is de inhoud van de melding aan de betrokkenen? : er is beveiligingslek geweest, usb stick van onze docent met adressen is ontvreemd, enzovoort 47) Hoeveel betrokkenen heeft u geïnformeerd of gaat u informeren? : 450 48) Welk communicatiemiddel of welke communicatiemiddelen gebruikt u of gaat u gebruiken om de betrokkenen te informeren? : brief (per post) 49) Waarom ziet u af van het melden van het datalek aan de betrokkenen? : 50) Als het informeren van alle betrokkenen een onevenredige inspanning zou vergen, licht dan toe hoe u door een openbare mededeling of een soortgelijke maatregel de betrokkenen gaat informeren. : 51) Welke maatregelen heeft u getroffen waardoor het niet nodig is om de betrokkenen te informeren? : 52) Welke andere redenen heeft u om de betrokkenen niet te informeren? : 53) Welke technische en organisatorische maatregelen heeft uw organisatie getroffen om de inbreuk aan te pakken en om verdere inbreuken te voorkomen? : usb stick gebruik wordt verboden, usb stick data krijgt geen toegang meer op pc's 54) Heeft de inbreuk zich voorgedaan in een grensoverschrijdende gegevensverwerking, en is de Autoriteit Persoonsgegevens voor deze verwerking de leidende toezichthouder? : Nee 55) Als er sprake is van een grensoverschrijdende gegevensverwerking, om welke EU-landen gaat het dan? : 56) Heeft uw organisatie of bedrijf, het datalek gemeld bij privacytoezichthouders in een of meer andere EU-landen, of gaat u dat nog doen? : Nee 57) Ja, namelijk: : 58) Heeft uw organisatie of bedrijf, het datalek gemeld bij Europese toezichthouders op andere meldplichten, of gaat u dat nog doen? : Nee 59) Ja, namelijk: : 9. Overig --------------------------------- 60) Is naar uw mening deze melding compleet? : Ja, de vereiste informatie is verstrekt en er is geen vervolgmelding nodig 61) Ondertekening : Door dit vakje aan te vinken verklaart u bevoegd te zijn deze melding te doen en dat de in de melding verstrekte informatie juist is. 
> 
> Aantal vervolgacties : 0
> Aantal taken : 0
> 
> 
> -- 
> xxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxx
> Automatically generated by GLPI

How can I solve it?

There is something I want to tell you:
In Notification queue (Administration) I saw something weird, left side is messed, right side is not messed. Please check below pic:
![form problem - fields messed in html](https://user-images.githubusercontent.com/26407519/48775827-7aa74200-ecce-11e8-8e8a-cea30caf6533.jpg)

So HTML code caused this problem.

**Comment by abeulink** [comment]
found bug, formcreator didn't add <br> lines in email notification message.

**Comment by btry** [comment]
Hi did you tried the version 2.7.0 ? this kind of problem should be solved and if not it should be easy to fix (a lot of code rewritten to handle these bugs efficiently).

**Comment by btry** [comment]
Hi

The problem is silved in the current revision of the incomong 2.7.0 . Closing. 

Feel free to request again if the issue still occurs for you.

**Comment by btry** [comment]
hi @abeulink 

While writing unit tests in a r elated part of the plugin , I found that the issue occurs on GLPI 9.3 without rich t ext mode only.


The PR #1293 should solve the issue. I will merge when the (new) unit tests validate the changes.
