### ISSUE TITLE
Probleme caractere 'spécial' 

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1217]
Champ de type texte.
Ce champ est rempli avec une phrase comme "l'arbre est penché"

dans le mail généré et dans le contenu du champs, le texte est renseigné : 
l\'arbre est penché -> antislash avant l'apostrophe

**Comment by imanou10** [comment]
bonjour 
Je rencontre le même problème.
Cordialement

**Comment by btry** [comment]
Bonjour @EC2311 @imanou10 quelle version du plugin SVP ? 

Si vous êtes sur une version 2.6.x ou inférieur, veuillez tester la 2.7.

**Comment by EC2311** [comment]
Bonjour

Comment telecharge t-on le code de la 2.7 ?

**Comment by btry** [comment]
Bonjour

Je pense fusionner bientot ce travail là; autant directment l'essayer: 

https://github.com/btry/formcreator/tree/feature/1216_remove_commondbchild

cliquez sur le bouton vert de téléchargement.  Si vous upgradez à partir d'une révision plus ancienne il faudra upgrader.

- si vous upgradez à partir d'une autre révision de 2.7.0, ```php scripts/cliinstall.php --force-upgrade```
- si vous upgradez à partir d'uen version < 2.7.0 : ```php scripts/cliinstall.php```

Dans les 2 cas, la base de données sera modifiée d'uen façon un peu compliquée à annuler. Donc sauvegardez la BDD avant l'upgrade et utiliser evidemment une version de test.

**Comment by EC2311** [comment]
Si je comprends bien : si on a deja installé une 2.7.0 -> cliinstall Force upgrade, sinon cliinstall uniquement ?

(J'ai la 2.6.5)

**Comment by btry** [comment]
oui, c'est ça !

**Comment by EC2311** [comment]
resultat ligne commande : Please run composer install --no-dev in the plugin directory

**Comment by btry** [comment]
@EC2311 suivez simplement la consigne.

rendez vous dans le dossier du plugin et exécutez la commande, tout simplement. 

composer : http://getcomposer.org

**Comment by EC2311** [comment]
composer est passé...
mais ensuite ?
le plugin affiche 'mettre à jour' et 'nest pas visible dans les menus

**Comment by btry** [comment]
i lfaut mettre à jour le plugin depuis la ligne de commande comme je l'ai indiqué plus haut

depuis le dossier du plugin:
- si vous upgradez à partir d'une autre révision de 2.7.0, ```php scripts/cliinstall.php --force-upgrade```
- si vous upgradez à partir d'uen version < 2.7.0 : ```php scripts/cliinstall.php```

**Comment by EC2311** [comment]
**Premiere commande :** 
...\plugins\formcreator>php scripts/cliinstall.php
Please run composer install --no-dev in the plugin directory

**Seconde Commande :** 
...\plugins\formcreator>composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing docopt/docopt (1.0.2): Loading from cache
Generating optimized autoload files

...\plugins\formcreator>

**Comment by btry** [comment]
La première commande dépend de la seconde.

Maintenant que vous avez exécuté la seconde, vous pouvez retenter la première. L'upgrade devrait s'exécuter.

**Comment by EC2311** [comment]
toujours identique
-> information : 
fallait il dezipper dans le repertoire (comme un plugin classique) ?

**Comment by btry** [comment]
Il faudrait que je vérifie si je n'ai pas laissé une coquille dans le code d'upgrade (peu de tests donc les changements que j'ai fait sont un peu risqués).


Je vosu conseille de dézipper hors de GLPI car le zip doit contenur un dossier avec un nom arbitraire, contenant lui-même les fichiers.

- dézippez hors de GLPI
- renommez le dossier contenant le plugin en "formcreator"
- déplacez la version de formcreator dans glpi à un autre endroit (votre dossier personnel par exemple)
- déplacez la version dézipée (le dossier formcreator) dans le dossier plugins de glpi.
- vérifiez que GLPI détecte Formcreator
- lancez composer install --no-dev
- upgradez en ligne de commande comme j'ai décrit plus haut.

**Comment by btry** [comment]
@nbriche Try this fix please, and feedback 

https://github.com/pluginsGLPI/formcreator/pull/1231

**Comment by nbriche** [comment]
Seems to work for me

**Comment by btry** [comment]
As you can see it is much easier to fix those problems now. I merge. Thanks for your feedback.

**Comment by btry** [comment]
I got a positive feedback, then I close. @EC2311 If you still have an issue, please leave a message here.
