### ISSUE TITLE
tinymce wrongly included

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/formcreator#1218]
**Describe the bug**

As mentioned in the title, I noticed a problem when creating a textarea field using the latest version of GLPI and the plugin (9.3.2 and 2.6.5). The thing is that the tinymce editor does not appear as it should. Instead, I get a bunch of javascript errors telling me it cannot find it.

**To Reproduce**
1. Create a form using the formcreator plugin
2. Add a textarea field ("zone de texte" in french)
3. Save everything
4. Preview the form

**Expected behavior**

Normally, you'd see your field with a tinymce editor appear. Instead, you get a text field and the editor doesn't appear. You also get a bunch of javascript errors in the console.

**Additional context**

Okay, so I reported the issue [here](https://github.com/glpi-project/glpi/issues/4955). However, this apparently is not a core, but a plugin issue... so I'm moving it here. The thing is that the plugin calls the `html::requireJS()` function that takes care of including the tinymce plugin. The problem is that the include statement inside the `html.class.php` file is made for the file `tinymce.js` which doesn't exist. Instead, what we have is the `tinymce.min.js`. So, of course, when you try to include it, you get a bunch of javascript errors.

Anyway, I found that correcting the line inside html.class.php actually solves the problem... however, given that my report in the main GLPI github was closed less than five minutes after I opened it, I guess I'll report it here in hope that it'll get properly resolved.

**Comment by btry** [comment]
Hi, let's check if the issue persists with the develop branch (incoming version 2.7.0)

**Comment by btry** [comment]
Hi

I don't reproduce with version 2.7.0-beta.1 + current bugfixes un develop branch).

**Comment by btry** [comment]
Hi, @Synairgis  

any news about this issue ?

**Comment by Synairgis** [comment]
You can close this issue. After trying five times to reproduce my own issue without success, I think it might have been some weird cache issue. Anyway, everything works correctly.

**Comment by btry** [comment]
Great ! Thank you for your feedback.
