### ISSUE TITLE
Données du Formulaire

### ISSUE THREAD

**Issue by chappat** [pluginsGLPI/formcreator#1226]
Bonjour, jr n'arrive pas à afficher le résultat de mes questions sur mon ticket.
Lorsque je fais un ##FULLFORM##
Il me renvoi mes questions suivi de L'ID de la réponse mais pas la réponse quelque soit le type utilisé (Intitulé ou Objets GLPI).
Auriez vous une idée?
Merci.

GLPI 9.1.2 et Form Creator 2.5.1

**Comment by btry** [comment]
Bonjour 

Je vous invite à demander de l'aide sur le forum de GLPI car vous avez un problème sur l'utilsiation du plugin. 

https://forum.glpi-project.org/
