### ISSUE TITLE
Link a field (Plugin Field)  in glpi_objects dropdown

### ISSUE THREAD

**Issue by bacus99** [pluginsGLPI/formcreator#1228]
Hi

I want to add to visual at right of the computername the age of the computer.  I create a additionnal field with FIELD addon and update it with a script

for exemple Can I see the AGE on the right of the computername
![image](https://user-images.githubusercontent.com/11425241/49468374-b82dc400-f7d2-11e8-9c21-764e41d81ca6.png)

![image](https://user-images.githubusercontent.com/11425241/49468484-00e57d00-f7d3-11e8-81e9-8ad3654139fd.png)

I think I have to modify glpiselectfield.class.php to call the new table glpi_plugins_field_computerage
and add the $input to name under 'age' but don't know how

![image](https://user-images.githubusercontent.com/11425241/49468564-3c804700-f7d3-11e8-8542-d0de68e716f0.png)

Any clue?

**Comment by btry** [comment]
Hi

To customize the field you should work in the method displayField().

You may need to reimplement it in the class as it currently uses the parent implementation.

**Comment by btry** [comment]
Hi,

Having no feedback, I close.
