### ISSUE TITLE
bug in migration script

### ISSUE THREAD

**Issue by Stoatwblr** [pluginsGLPI/formcreator#1229]
2.7.0b1: install script:  glpi_plugin_formcreator_questionregexes doesn't exist in previous versions of formcreator (therefore "INSERT INTO" breaks)

 
        $uuid = plugin_formcreator_getUuid();
            $DB->query("INSERT INTO `glpi_plugin_formcreator_questionregexes`
                              SET `plugin_formcreator_questions_id`='$id', `fieldname`='regex', `regex`='$regex', `uuid`='$uuid'"
            ) or plugin_formcreator_upgrade_error($migration);

**Comment by ladenree76000** [comment]
i also had this message :
 Table 'glpi93.glpi_plugin_formcreator_questionregexes' doesn't exist
upgrading from previous version

**Comment by btry** [comment]
Hi,

please try to upgrade with this fix and feedback.

**Comment by btry** [comment]
hi @Stoatwblr and @ladenree76000 

Did you test the fix ?

**Comment by Stoatwblr** [comment]
I didn't have a chance yet. 
The formcreator was totally borked and I had to remove the plugin. I haven't restored it from a backup yet.

**Comment by btry** [comment]
I'm interested about how it broke to make the upgrade more  resilient.
