### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by vlegros** [pluginsGLPI/formcreator#123]
Hello
The labels of the form should be translated based on user entity / location

**Comment by neeftarah** [comment]
Hi,
Can you explain your needs? I don't understand why form's label should be translated based on user entity / location.

Forms are created and assigned to an entity and a langage. Users locations are not linked to forms and should not give informations about users langage or rights.

regards,
Jérémy

**Comment by vlegros** [comment]
Hello

For example, when we do a form for User Management (creation of a new user), we should be about to make a single form, make it visible for ALL ENTITIES recursively, and based on the requester language, the questions may be translated


Ex : Last Name / Nom de Famille / Nachname  / 姓


The form should be displayed in the language of the requester.

Regards

vincent

**Comment by neeftarah** [comment]
HI,

OK. Currently, you need to create one form per language.
You also can duplicate a form to make it easy to rebuild a form.

Translations may be interesting.
However, mosts of peoples use only one language and don't have this problem, so this feature won't be develop soon. Moreover, I know it should be cumbersome for you if you have 4 languages or more to manage and lots of forms, but it isn't blocking and does not prevent you from doing all your translations.

Best regards,
Jérémy

**Comment by btry** [comment]
Hi

Formcreator 2.12.0 (currently beta) supports translations on all items composing a form. The best language is selected depending on the user preferences or the browser's language (anonymous access).

The feature is implemented, then I close this ticket.
