### ISSUE TITLE
V2.7.0 Beta 1 - HostName  return the IP 

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1230]
**Describe the bug**
HostName  return the IP

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser  chrome
 - Version 70.0.3538.110 64 bits

**Comment by btry** [comment]
Hi

This field relies on the function gethostbyaddr(). Here is its documentation: http://php.net/manual/en/function.gethostbyaddr.php

You can read taht if the resolution fails it returns the IP of the host. Please check that the computer of the requester can be solved by your DNS server.

**Comment by btry** [comment]
As I don"t have any feedback, and the issue is very likely in the networking context, I close.
