### ISSUE TITLE
"Urgency" has no default anymore

### ISSUE THREAD

**Issue by nbriche** [pluginsGLPI/formcreator#1232]
With v2.7.0-beta, GLPI 9.3.3:

- Create an "Urgency" question
- Go to preview
- "Urgency" is set to Very High, or High, or whatever is the highest urgency enabled in GLPI.

**Expected behavior**
"Urgency" should be "Medium"

In [urgencyfield.class.php:48](https://github.com/pluginsGLPI/formcreator/blob/54595150aead69d341f5ecd067d252c6f2293d17/inc/fields/urgencyfield.class.php#L48), replacing `$this->value` by `3` seems to resolve the issue, so I guess it's because there's nowhere in 2.7.0 equivalent to [2.6.5's default setting](https://github.com/pluginsGLPI/formcreator/blob/dfc4a5aff41ad1b6b2905590e5040fcaeba739bb/inc/fields/urgencyfield.class.php#L107).

**Comment by btry** [comment]
Hi

I did not reproduced your issue, but i found something slightly different about the defaut value of this type of field.

Please use this fix and check / update the default value of your urgency field. It must be a number with 3 = medium.

**Comment by nbriche** [comment]
It's now _so close_ to working as intended. Your change made me go back to the question's default value, and before I tried your fix (on a fresh GIT checkout of release/2.7.0-beta.1) I could not save any default value: the field blanked out every time I went back to it after saving. Now I can set the default value to 3... but I can't set it to anything else (can't even blank it).

It's really weird. I thought at first that the DB just wasn't queried properly and the default value was just whatever the serializeValue() returned as default, but not _quite_:

- Start with current state: `return '';`
- Open the question: the default value is blank. Save.
- Make the code change `return '3';`
- Open the question: default value's still blank. Set it to 3, save, go back: it's still there. OK so far.
- Blank the value, save, go back: Still 3. Put 4, save, go back: still 3.
- Change the code back to `return '';`
- Open the question: default value _is still 3_. Don't change, save, reopen: _default value is blank_.

I can't really go further down that rabbit hole right now, but I'm currently in a state of mild WTF.

**Comment by btry** [comment]
Hi

Indeed, i still missed a line of code. I updated the fix. Try it and feedback again. 

Now I can set / update the default value.

**Comment by nbriche** [comment]
Yes, the default now saves, and the value is correctly saved in the form.

There's still no hard default on the field creation though: when you create the question, you still have to explicitly specify what the default will be. Although maybe that's on purpose? In which case maybe there should be a line somewhere to explain what values to put (I wouldn't have immediately guessed I had to put '3' for 'Medium').

**Comment by btry** [comment]
If i remember well, if the default value is not set, the field should show "medium" by default, right ?

**Comment by btry** [comment]
An other note : I have ideas to improve the questions designer, to avoid use of an integer for questions like urgency. But first : we need stabilization of the plugin v2.7 then refactor + unit tests for future releases.

**Comment by nbriche** [comment]
No; I just deleted and recreated my question (by just setting its name and type), and the dropbox shows "Very high". When I go back to my question, the default value sets itself to '0'. From there I can modify it though.

**Comment by btry** [comment]
OK, then I'll search how to set 3 by default.

**Comment by btry** [comment]
Fix updated. I think we are now in the final version

**Comment by nbriche** [comment]
Agreed, I'm now seeing the correct behavior.
