### ISSUE TITLE
liste et Champ obligatoire dependant si liste non renseignée

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1233]
Bonjour

Je réalise un formulaire avec une liste (basé sur objet GLPI/Utilisateur) afin de selectionner une personne : ok.
Si ce champ n'est pas renseigné (parce que la personne n'est pas présente dans la DB) alors on peut la saisir sur un champ de type texte.
Voici le formulaire : certes avec 2 champs utilisateurs, mais c'est le meme principe.

Ma question : 
pourquoi le champ texte(renseigné obligatoire) peut ne pas être renseigné ?
En effet, si je ne selectionne pas un utilisateur, alors mon champ texte resite bien affiché, mais n'est pas obligatoire. Pourtant j'ai ajouté une longueur minimale de saisie...

{"forms":[{"is_recursive":0,"access_rights":1,"requesttype":7,"name":"test","description":"test","content":"","is_active":1,"language":"fr_FR","helpdesk_home":0,"is_deleted":0,"validation_required":0,"is_default":0,"uuid":"8ce5b539-2d1ee5ce-5c09615a0ac4c6.37405463","_sections":[{"name":"Garants","order":1,"uuid":"8ce5b539-2d1ee5ce-5c09616c4026d7.46682013","_questions":[{"fieldtype":"glpiselect","name":"Garant 1","required":0,"show_empty":1,"default_values":0,"values":"User","range_min":"","range_max":"","description":"","regex":"","order":1,"show_rule":"always","uuid":"8ce5b539-2d1ee5ce-5c0961978334a6.60881677","_conditions":[]},{"fieldtype":"glpiselect","name":"Garant 2","required":0,"show_empty":1,"default_values":0,"values":"User","range_min":"","range_max":"","description":"","regex":"","order":3,"show_rule":"always","uuid":"8ce5b539-2d1ee5ce-5c09635400b659.67262294","_conditions":[]},{"fieldtype":"text","name":"Garant 1 Non trouvé","required":1,"show_empty":0,"default_values":"","values":"","range_min":1,"range_max":80,"description":"","regex":"","order":2,"show_rule":"shown","uuid":"8ce5b539-2d1ee5ce-5c096353e98615.17494168","_conditions":[{"show_field":"8ce5b539-2d1ee5ce-5c0961978334a6.60881677","show_condition":">","show_value":"","show_logic":"AND","order":1,"uuid":"8ce5b539-2d1ee5ce-5c0964385386a8.77426398"}]},{"fieldtype":"text","name":"Garant 2 non trouvé","required":1,"show_empty":0,"default_values":"","values":"","range_min":1,"range_max":80,"description":"","regex":"","order":4,"show_rule":"shown","uuid":"8ce5b539-2d1ee5ce-5c09634063aa44.03355202","_conditions":[{"show_field":"8ce5b539-2d1ee5ce-5c09635400b659.67262294","show_condition":">","show_value":"","show_logic":"AND","order":1,"uuid":"8ce5b539-2d1ee5ce-5c09644365fd42.11859324"}]}]}],"_validators":[],"_targets":[{"itemtype":"PluginFormcreatorTargetTicket","name":"Creation groupe","uuid":"8ce5b539-2d1ee5ce-5c09639e24a621.64993978","_data":{"comment":"##FULLFORM##","due_date_rule":null,"due_date_question":null,"due_date_value":null,"due_date_period":null,"urgency_rule":"none","urgency_question":0,"location_rule":"none","location_question":0,"validation_followup":1,"destination_entity":"current","destination_entity_value":null,"tag_type":"none","tag_questions":"","tag_specifics":"","category_rule":"none","category_question":0,"_ticket_relations":[],"title":"Creation groupe","_actors":[{"actor_role":"requester","actor_type":"creator","actor_value":null,"use_notification":1,"uuid":"8ce5b539-2d1ee5ce-5c09639e23b195.72383769"},{"actor_role":"observer","actor_type":"validator","actor_value":null,"use_notification":1,"uuid":"8ce5b539-2d1ee5ce-5c09639e246858.11311773"}]}}],"_profiles":[]}]}

le but etant de ne pas 'bloquer' si la personne n'est pas trouvée dans la liste, mais de pouvoir/devoir la renseigner à la main via le champ texte.

D'avance merci

**Comment by EC2311** [comment]
la version 2.7.0 permet de bien tester le champ vide : ok
par contre la notion de champ obligatoire n'apparait pas sur le champs "secondaire" (qui doit s'afficher si le champ parent est vide)

**Comment by btry** [comment]
Bonjour

Désolé pour le délai.

Je fais un test avec la version courante du plugin (branche develop) et ça semble fonctionner comme attendu:
![image](https://user-images.githubusercontent.com/14139801/50839481-b1a9e380-1360-11e9-85ce-1826a638876e.png)

**Comment by btry** [comment]
Bonjour @EC2311 

Avez-vous pu faire un essai avec la dernière version de développement ?

**Comment by EC2311** [comment]
Je viens de telecharger la version 2.7.0 beta 3.

Je n'arrive pas à faire fonctionner le test suivant : 
Si le garant 1 est vide (car on ne le trouve pas dans la base), le champ saisi libre ne s'affiche pas.
Quel test faut-il mettre ?
![image](https://user-images.githubusercontent.com/42341169/52110043-b419f900-25ff-11e9-9192-c094513e0bc1.png)

**Comment by btry** [comment]
Bonjour

Il y a une contrainte sur l'implémentation actuelle d'un champ de type sélection. la valeur vide représentée par **------** correspond à la valeur 0. C'est à dire que ne rien sélectionner renvoie au serveur la valeur 0. A la place d'une chaine vide, essayez la valeur 0, et ça devrait fonctionner (c'est le cas pour moi).

**Comment by btry** [comment]
![image](https://user-images.githubusercontent.com/14139801/52220061-44756980-289e-11e9-9dea-39bf43890575.png)

A représentant chez moi votre champ sélection.

**Comment by EC2311** [comment]
Bonjour
Resultat : 
![image](https://user-images.githubusercontent.com/42341169/52269876-94f0d380-293f-11e9-83f3-15bba70f930f.png)

Zone secondaire (qui devrait s'afficher) : j'ai bien rempli avec '0'
![image](https://user-images.githubusercontent.com/42341169/52269900-a2a65900-293f-11e9-9f0b-f067250e4dd7.png)
![image](https://user-images.githubusercontent.com/42341169/52269920-b18d0b80-293f-11e9-8ebf-e81a685d655a.png)
Zone Garant 1 (issue LDAP)
![image](https://user-images.githubusercontent.com/42341169/52269944-c36eae80-293f-11e9-9637-73f23201dea3.png)

**Comment by btry** [comment]
Bonjour

Je reviens sur le dernier point qui était non résolu. Après revue de code ed la versio ned développement (future 2.8.0) vous pouvez exprimer la condition avec uen chaine vide. Inutile de mettre un zéro.

Je crois que le souci vient que votre condition est mal exprimée (je viens de le réaliser).

Si vous voulez que Garant 2 s'affiche si garant 1 n'est **pas** vide, alors la condition que vous utilisez est la négation de ce que vous voulez obtenir.

Essayez plutot une condition comme ci-dessous:
![image](https://user-images.githubusercontent.com/14139801/53872492-ac82b100-3ffe-11e9-92dc-170af3a0a5f6.png)

**Comment by EC2311** [comment]
Bonjour
je suis en beta 3
image du champ en saisie manuelle, si garant 1 non saisie
![image](https://user-images.githubusercontent.com/42341169/53960296-35284c80-40e6-11e9-8d48-e454dacd0c20.png)

Image du garant 
![image](https://user-images.githubusercontent.com/42341169/53960387-7882bb00-40e6-11e9-8e61-7443911634e9.png)

en previsualisation : 
on voit le garant 1, mais pas la saisie 'manuelle'
![image](https://user-images.githubusercontent.com/42341169/53960447-a36d0f00-40e6-11e9-8461-96ebd0b9b8f7.png)
Si je selectionne un utilisateur (garant1) puis je remet à vide le champ garant 1, la zone de saisie manuelle n'apparait pas :(

**Comment by btry** [comment]
La beta 3 est obsolète : la version 2.7.0 est sortie depuis plusieurs semaines, et lundi je devrai publier la  version 2.8.0.

Avec le code de la future 2.8.0, j'ai eu un résultat cohérent, avec prise en compte ed ma reparque sur l'opérateur **=** qui devrait être **!=** .

**Comment by btry** [comment]
Pour la saisie manuelle du  garant 1, je pense que vous devriez utiliser l'opérateur de comparaison **=** à la place de **!=**

**Comment by EC2311** [comment]
Désolé, en 2.7.0 toujours meme souci... sur question initiale..
MAIS 
en recreant la question (saisie manuelle) et en mettant le filtre sur garant 1 = '' alors cela fonctionne...
comme si dans la base (?) il y aurait un mauvais renseignement ?

**Comment by btry** [comment]
C'est le symptôme d'un problème à l'upgrade : peut être un changement de format en BDD pour lequel je n'ai pas fait de conversion dans l'upgrade.

La beta 3 étant assez proche de la version finale, le bug devrait être reproductible en partant d'une  release inférieure à 2.7.0 (beté exclues). L'idéal serait que vous vous souveniez avec quelle version vos questions ont été créées. Ensuite, voir si on arrive à reproduire, pour enfin corriger le code d'upgrade.

**Comment by EC2311** [comment]
je devais initialement en 2.6.5 (au tout debut du probleme)

**Comment by btry** [comment]
Bonjour

Avez vous encore une copie de votre DB avant upgrade ? Il faudrait visualiser les conditions en lien avec le problème dans la table des conditions. Cela dit, je ne m'attends à ne rien trouver car le souci porte sur des chaines vides (ou d'apparence vides).

**Comment by btry** [comment]
Bonjour

Ce ticket est obsolète, je ferme.
