### ISSUE TITLE
"show unless" fails on Common - Locations

### ISSUE THREAD

**Issue by Konatus** [pluginsGLPI/formcreator#1235]
Test case 
 - User select a Location in a dropdown with all the locations
 - the hidden field configured in "show unless" doesn't appear when the good value is selected in the previous field

**Comment by Dayflare** [comment]
@btry i updated to develop branch (to fix the migration issue) and tested again. Show unless and hidden unless works now as expected, but only if the element is not a description. If it's a description then the field is always shown and u cannot hide it.

**Comment by btry** [comment]
Hi

I found the issue. Please try this fix and feedback.

**Comment by Dayflare** [comment]
with this fix it works like a charm. thank you!

**Comment by btry** [comment]
Thank you for your feedback. I think the issue can be closed now.
