### ISSUE TITLE
[2.7.0] : Installation

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1236]
Erreur lors de l'installation : 
Done (0 seconde)
Done (0 seconde)
Traitement en cours...
Table 'web-projets-dev.glpi_plugin_formcreator_questionregexes' doesn't exist
Please, check migration log

log : 
Table '...plugin_formcreator_questionregexes' doesn't exist
  Backtrace :
  plugins\formcreator\install\upgrade_to_2.7.php:129 plugin_formcreator_upgrade_error()
  plugins\formcreator\install\install.php:135        PluginFormcreatorUpgradeTo2_7->upgrade()
  plugins\formcreator\install\install.php:103        PluginFormcreatorInstall->upgradeOneStep()
  plugins\formcreator\hook.php:50                    PluginFormcreatorInstall->upgrade()
  inc\plugin.class.php:707                           plugin_formcreator_install()
  front\plugin.form.php:47                           Plugin->install()

**Comment by btry** [comment]
Bonjour, ce bug est un doublon de #1229. Essayez le fix proposé svp. Je ferme ce ticket au profit de l'autre.
