### ISSUE TITLE
Liste catégorie de ticket vide depuis le formulaire

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/formcreator#1237]
**Describe the bug**
Sur la maj v2.7.0-beta.1, la question intitulé de catégorie de ticket ne fonctionne plus.
Depuis le formulaire la liste est vide et n'affiche aucune catégorie.
En revanche on peut toujours mettre une catégorie par défaut.

**To Reproduce**
1. Ajouter une question de type intitulé de catégorie de ticket
2. Remplir un formulaire

**Expected behavior**
Afficher la liste des catégories

**Screenshots**
![image](https://user-images.githubusercontent.com/23405363/49727603-f44ca300-fc70-11e8-9c09-9649a1109b70.png)

**Comment by btry** [comment]
Bonjour

A ce jour ça fonctionne correctement; je ne me souviens pas avoir eu un tel bug. Pouvez-vous retester avec la branche develop à jour et faire un retour ?

![image](https://user-images.githubusercontent.com/14139801/50838249-dfd9f400-135d-11e9-821d-b82cbef1254e.png)

**Comment by btry** [comment]
Bonjour @titidelaff 

Avez vous possibilité de tester la version 2.7.0 beta 3 ?

**Comment by titidelaff** [comment]
Fonctionne sur la version 2.7.0 beta 3.
Merci

**Comment by btry** [comment]
Merci, je ferme le ticket
