### ISSUE TITLE
Validation par un groupe

### ISSUE THREAD

**Issue by Max6Devil** [pluginsGLPI/formcreator#124]
Bonjour,

Est-il possible de faire valider un groupe sur un formulaire et non des personnes spécifiques?

Merci 

Cdlt

**Comment by neeftarah** [comment]
Bonjour,

Actuellement non. Les fonctions de validations sont effectivement limité mais nous n'avons pas prévus dans l'immédiat de les complétés.

Nous restons toutefois ouvert à toute proposition de fonctionnalités ou propositions de code.

Si votre besoin est urgent ou spécifique, vous pouvez également contacté Teclib, contact@teclib.com, pour une proposition commerciale.

Cordialement,
Jérémy
