### ISSUE TITLE
How to change background color of section

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#1241]
Hello,

Could you tell me how to change the color please

I tried with C:\inetpub\wwwroot\plugins\formcreator\css\style.css

line 217 .formcreator_form > .form_section > h2 {
   background: #2bb4dc;

but color does not change

Thank you for your help

**Comment by btry** [comment]
Hi

You should also check if the CSS from GLPI affects this color. Use the developer tools of your browser to find all styles applied and how they take precedence. 

This kind of question should be posted on the forum of GLPI : https://forum.glpi-project.org/
