### ISSUE TITLE
Consultation des formulaires saisies

### ISSUE THREAD

**Issue by Steven-91** [pluginsGLPI/formcreator#1242]
Bonjour,

J'ai mis en place sans mon organisation un formulaire pour des demande Informatique avec validation par un directeur qui ensuite génére un ticket.

En tant qu'administrateurs, moi et mon équipe souhaiterions pouvoir visualiser les formulaires saisies. Or quand nous allons dans les formulaires saisies et que nous cliquons sur un formulaire, nous avons un message comme quoi nous n'avons pas les droits requis.

![image](https://user-images.githubusercontent.com/45817605/49863702-25f47400-fe01-11e8-90b2-1ead8f51921f.png)

![image](https://user-images.githubusercontent.com/45817605/49863745-3b699e00-fe01-11e8-9dd9-aa70c4814333.png)

Nous avons un profil "Super-Admin".

J'aimerais sonc pouvoir consulter les formulaires saisies pour pouvoir les traitées.

Merci d'avance pour votre aide.

GLPI Version 9.2.2
Formcreator Version 2.6.2

**Comment by btry** [comment]
Bonjour

Pouvez-vous utiliser un environnement de test pour essayer la  version 2.6.4 ?

En version 2.6.2 seul le demandeur ou le valideur peuvent voir les demandes saisies (par souci de sécurité). 

Un problème d'accès pour les administrateurs a éé résolu en version 2.6.4. Cette correction dervait répondre à votre besoin.

**Comment by Steven-91** [comment]
Bonjour,

Merci pour ce retour. J'ai donc rétrogradé en 2.6.4.
Je vais voir pour passé la 2.7.0 sur une pré prod.
