### ISSUE TITLE
Date format indication

### ISSUE THREAD

**Issue by Cecilka** [pluginsGLPI/formcreator#1243]
**Is your feature request related to a problem? Please describe.**
In the form I created, I have quite a few date fields. When the user fills a date field, he has a choice either to pick a date with the date picker (in which case the format is OK) or to type it directly. In the second case, there's a control so that the user can only type a digit or the symbol '-'. The use of the the symbol '-' as a separator is mandatory, otherwise there's an error message when the user saves the form.
However, in some countries (France for example), the symbol '/' (slash) is more current when it comes to date formatting. If the user types the date quickly with slashes and doesn't realize that the symbol has not been taken into account, the error message is ill adapted. Indeed, it indicates that the date field is empty (since Form Creator did not recognize the date, it emptied the field). However, in the eyes of the user, it's disturbing, since he has indeed entered a date, and it can be puzzling and a bit difficult for him to understand why dates are erased.

**Describe the solution you'd like**
Quick fix : improve the error message (Something like : Date format must be jj-mm-aaaa).
Other quick fix : force the use of the date picker ; you shouldn't be able to type a date directly into the field
Maybe a bit more complicated : allow the typing of the date, but in three fields (one for the day, one for the month, one for the year) separated by dashes

**Describe alternatives you've considered**

**Additional context**

**Comment by btry** [comment]
Hi

The date field is provided by GLPI. Can you check if the issue occurs in a date field of GLPI ? (financial and administrative information of a computer is a good place).

**Comment by btry** [comment]
Hi

This issue is very old and I had no feedback. I close.
