### ISSUE TITLE
drag&drop in file fields - 2.7.0 beta

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/formcreator#1244]
*Bonjour 
Nous n'avons plus la possibilité de formater notre texte dans la destination dans le champs description.
![image](https://user-images.githubusercontent.com/36695393/49999711-cbd9e700-ff97-11e8-85d6-1da4af3272a0.png)
De plus le formatage du champs description lors de la création du formulaire ne reste pas il transforme le code formatage en des slashs.
cordialement

**Comment by btry** [comment]
Bonjour

Pouvez vous préciser la version de GLPI et l'état du mode texte riche (si GLPI < 9.4) ?

**Comment by imanou10** [comment]
Bonjour je suis en version 9.3.3 et oui l'etat est desactivé.
Je viens de l'activer et du coup je peux formater mon texte dans la destination cependant je rencontre toujours le probleme avec le champ description dans la création du formulaire.
Merci

**Comment by btry** [comment]
Bonjour

J'ai besoin d'in éclaircissement : qu'appelez vous "la création d'un formulaire" ?

En effet quand un demandeur remplit un formulaire, les réponses sont enregistrées, et elles servent à ré-afficher le formulaire (rempl), et ces mêmes réponses servent à générer les tickets / changemetns cibles.

Il ya donc deux endroits où vous pourriez avoir un problème de rendu, et il me faut éclaircir ce point pour tenter de reproduire.

**Comment by imanou10** [comment]
Je rencontre ce probleme lors du rendu suite à la configuration de formulaire; Autrement dit quand un demande affiche un questionnaire il voit mon texte sans couleur ni forme 
![image](https://user-images.githubusercontent.com/36695393/50104185-b4b22800-0229-11e9-9a35-3d0499c81be8.png)
Lorsque je sauvegarde mon champ il est de ce format 
![image](https://user-images.githubusercontent.com/36695393/50104322-f9d65a00-0229-11e9-8fad-7dcfe8a53f76.png)
Puis quand je retourne dedans je vois qu'il n' a rien gardé.

**Comment by btry** [comment]
Bonjour

Une petite vérification ave la future version 2.9 montre que le problème est résolu. Si le problème persiste avec ladernière ersion, merci d'ouvrir un nouveau ticket.
