### ISSUE TITLE
add logo on user form 

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#1252]
Hello

Could you tell me how to add our logo on form page for users.

Thank you

**Comment by yalgva** [comment]
Hello

I mean the logo on form home user page

![image](https://user-images.githubusercontent.com/30655170/50641990-1e406f00-0f6a-11e9-8536-8baa85d97fac.png)

**Comment by btry** [comment]
Hi

There is no feature in the plugin to change this logo. You may do this by replacing the image file in GLPI : glpi/pics/fd_logo.png . Of course this change will be lost each time you will upgrade GLPI.
