### ISSUE TITLE
Bug Affichage du champ  lié a une question de type "Intitulé -> catégorie de ticket"

### ISSUE THREAD

**Issue by nmoussay** [pluginsGLPI/formcreator#1255]
Bonjour,
Nous sommes dans la version 9.3.1 de GLPI et 2.6.4 de formcreator.

Nous rencontrons un problème lorsque nous créons une question de type Intitulé = Catégories de tickets. Voici notre création de question : 

![question categorie](https://user-images.githubusercontent.com/46283477/50563503-aa118b80-0d1d-11e9-8976-23974cf52afb.PNG)

Dans la Prévisulisation, aucun problème.

![previsualisation categorie](https://user-images.githubusercontent.com/46283477/50563535-f8bf2580-0d1d-11e9-9fb6-d135425aa99d.PNG)

Cependant, lorsque que nous créons une autre question avec dans "L'affichage de champ = Masqué par défaut, sauf si..." = X (X correspond à une valeur de catégorie de ticket, dans le cas ci-dessous X =  Audio)".

![question 2 lie](https://user-images.githubusercontent.com/46283477/50563605-83a02000-0d1e-11e9-89c7-b00fe0d637fe.PNG)

Dans la prévisualisation, si Audio est sélectionné dans la question 1, la question devrait apparaitre. Malencontreusement, non.

![resultat](https://user-images.githubusercontent.com/46283477/50563675-29ec2580-0d1f-11e9-8d5d-5f90f2d4cd4e.PNG)

Nous investiguons de notre côté.

Merci de votre aide.

Cordialement,

**Comment by btry** [comment]
Bonjour

Pour faire fonctioinner la condition sur un champ de type dropdown vous devez utiliser l'ID de l'intitulé.

C'est résolu dans la version 2.7.0 à venir. Pouvez vous tester la branche develop et faire un retour  ?

**Comment by btry** [comment]
je me fixais initialement l'objectif de fin 2018. Donc ça ne devrait pas tarder. Les problèmes principaux de la version 2.6 semblent résolus au vu des retours qu'on me fait; il ne reste plus que des problèmes mineurs ou marginaux. Il y aura donc une 2.7.0 avec une ou 2 releases correctives. 

Je passerai à Formcreator 2.8 pour la sortie de GLPI 9.3 (fin de support de GLPI 9.2 et éventuellement de nouvelles fonctionnalités si besoin)

**Comment by btry** [comment]
le bug étant résolu, je ferme.
