### ISSUE TITLE
does not record or become disorganized

### ISSUE THREAD

**Issue by flaviodiego31** [pluginsGLPI/formcreator#1258]
I was with the version of glpi 9.2.1 and FORMCREATOr version 2.4.1 and it was working perfectly. But I updated the GLPI and when I opened a form after registering the call in the description paste was unorganized so I activated the rich text and even then it continued Similarly.
So decide to upgrade formcreator to version 2.6.5. After updating when I try to register the form after clicking send the screen goes blank and the call is not registered

**Comment by btry** [comment]
Hi

If you have a blank screen, then you have a fatal error. You can find the backtrace in your HTTP server's errors log. Share it here

**Comment by btry** [comment]
hi @flaviodiego31 

did you find something in the logs ? I cannot investigate without any backtrace.

**Comment by btry** [comment]
Hi

Having no feedback, I close.
