### ISSUE TITLE
PAS de creation de ticket à la validation du formulaire

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1259]
GLPI 9.3.2 - Formcreator 2.6.5, 2.7.0, 2.6.4

bonjour,
suite à nos différentes échanges, et à votre demande, je réouvre un nouveau topic sur ce bug.

Lorsque je rentre les infos du formulaire et que je valide celui-ci, aucun ticket ne se crée !
J'étais alors en v2.6.5, je suis passé à votre demande en 2.7 puis en 2.6.4 sans aucun résultat probant.
Finalement, j'ai sauvegardé mes formulaires, supprimer le plug-in et les tables et tout réinstallé en 2.7.
L'import des formulaires s'est presque bien passé (ajout de valideur dans le formulaire et perte des destinataires ....). 
et toujours pas de création de ticket :(
reinstall de la 2.6.4 : pareil

J'ai bien un message comme quoi le formulaire est bien enregistré, pas d'alertes sur la création/non création de ticket.
Le mode debug ne remonte pas d'alerte non plus

**Comment by btry** [comment]
Bonjour

La fonction d'export / import a ses limites : si il y a un bug, vous pouvez ouvrir un ticket également ici.

Votre formulaire contient-il au moins une cible de type ticket ? Sans cela le formulaire j(n'en génèrera pas.

**Comment by Sicoval31** [comment]
Oui, il y a bien une cible, MAIS les données entrées pour le contenu (descriptif) du ticket refusent de s'enregistrer (pb déja soulevé), d'où très certainement la non création du ticket ?!

**Comment by Sicoval31** [comment]
Install complète de la 2.6.4 (après suppression des tables en base).
import des formulaires et test : creation de ticket OK

Ps : attention avec l'import de formulaires json depuis une ancienne version du plugin lors de modif de nom de champs dans les tables ...

**Comment by btry** [comment]
Bonjour

Donc à priori vous avez upgradé en 2.7 puis regressé vers une vesion plus ancienne.

Il n'y a rien qui permette de regresser la base de données. C'est donc normal que le plugin ne fonctionne plus dans un tel scénario.

L'export / import n'est ps prévu pour fonctinner entre différentes  versions du plugin. Exporter dans une version X et importer dans une version Y peut ne pas fonctinnner. 

Merci pour le retour
