### ISSUE TITLE
Validation du formulaire et statut

### ISSUE THREAD

**Issue by babalou** [pluginsGLPI/formcreator#126]
Bonjour,

J'avais créé des formulaires avec les versions 0.84.x de GLPI et la version 0.84-2.1.5 du plugin Formcreator. La validation fonctionnait correctement.
- Lorsqu'un valideur refusait la demande, le statut passait à "Refusé" et l'icône du statut du formulaire devenait une croix rouge.
- Lorsqu'un valideur acceptait la demande, le statut passait à "Accepté" et l'icône du statut du formulaire devenait une marque "check" verte. Un ticket correspondant était créé.

J'ai mis à jour GLPI en version 0.85.4 avec la version 0.90-1.2.5 de Formcreator, et maintenant : 
- Lorsqu'un valideur refuse la demande, le statut passe à "Refusé" et l'icône du statut du formulaire devient la croix rouge. Pas de problèmes, donc.
- En revanche, lorsqu'un valideur accepte la demande, j'obtiens le message suivant : "Votre ticket a bien été enregistré, son traitement est en cours... Impossible de générer les destinations !". De plus, le statut ne semble pas changer (l'icône du statut reste sur l'horloge) et le valideur a la possibilité de valider plusieurs fois la demande. Du côté des tickets, pas de problèmes, le ticket correspondant est bien créé.

Est-ce une mauvaise configuration de ma part ? 

Cordialement.

**Comment by neeftarah** [comment]
Bonjour,

La version 0.90-1.2.5 de formcreator ne présente normalement pas de problème sur la validation.

Entre la version 0.84 et 0.85, des modifications ont été faites sur les destinataires des tickets.
Pouvez-vous vérifier que les destinataires (demandeur, observateur(s) et assignés) sont correcte sur votre ticket de destination.

Utilisez-vous d'autres plugins (Comportement, escalade, etc.) ?

Le message "Impossible de générer les destinations !" s'affiche normalement si une des destinations au moins (ticket) ne peuvent être créés. (Un problème peut empêcher la création des tickets si le demandeur est obligatoire (gabarits ou plugin comportements)).
Dans ce cas, le formulaire ne peut être validé et reste donc en attente afin de vous permettre de vérifier la configuration de vos formulaires pour éviter les erreur d'enregistrement, puis de relancer la validation suivit de la création des tickets.

Dans votre cas, si le ticket est bien créer, je ne voit pas de raison pour que vous ayez ces erreurs. A moins que vous ayez plusieurs destinations ?

Cordialement,
Jérémy

**Comment by babalou** [comment]
Bonjour,

Merci pour votre réponse.

Dans la page du ticket de destination :
- le demandeur à la valeur "Demandeur du formulaire"
- l'observateur a la valeur "Valideur du formulaire"
- le destinataire est un groupe que j'ai créé. Actuellement, ce groupe est composé d'une seule personne qui reçoit bien un email de création de nouveau ticket, après la validation.

J'ai vérifié le gabarit associé et je n'ai aucun champ obligatoire.

Est-ce que le problème vient du fait que le destinataire est un groupe et pas un utilisateur ?

Cordialement.

**Comment by babalou** [comment]
Les autres plugins installés sont :
- Adressage IP
- Comptes
- Customfields
- Gestion d'objets
- Gestion de baies
- Imports fabricants
- Injection de fichiers
- Rapports

**Comment by babalou** [comment]
Je vous confirme également qu'il n'y a qu'une seule destination pour le formulaire en question.

**Comment by babalou** [comment]
Pour tester, j'ai enlevé la validation sur ce formulaire. 

A la validitation du formulaire par un demandeur, j'obtiens également le message : "Votre ticket a bien été enregistré, son traitement est en cours... Impossible de générer les destinations !". Ensuite, le ticket est créé et l'utilisateur assigné reçoit bien l'email annonçant la création d'un nouveau ticket.

**Comment by babalou** [comment]
Bonjour,

Je viens de télécharger et d'installer la dernière version Master de genericform et les problèmes décrits précédemment ont disparu. 

Je vous remercie pour cette mise à jour !

Très cordialement.
