### ISSUE TITLE
Update category ticket from form

### ISSUE THREAD

**Issue by jeckilles** [pluginsGLPI/formcreator#1262]
**Describe the bug**
No way to update target category ( change ) from fromcreator. 

**To Reproduce**

**Expected behavior**
I want to update the change ticket from a form. But it doesn't update.

**Screenshots**

Questions: 
![image](https://user-images.githubusercontent.com/46598616/51035726-35efa700-15ab-11e9-87e6-f062b79df4a4.png)
Target:
![image](https://user-images.githubusercontent.com/46598616/51035689-16f11500-15ab-11e9-85d5-e6052156c574.png)

**Additional context**
FormCreator V2.6.5

**Comment by btry** [comment]
Hi I don't reproduce with the incoming release.

I close. Feel free to test the version 2.7.0-beta.3, and prepare yourself to upgrade.
