### ISSUE TITLE
Problem with ldap question type

### ISSUE THREAD

**Issue by klodnitsky** [pluginsGLPI/formcreator#1263]
Hi.

Using v2.7.0.-beta3, problem with ldap question type, when i'm trying to add question:
![image](https://user-images.githubusercontent.com/7794575/51299015-880f4d00-1a2f-11e9-88fd-fedce7724c9a.png)

After adding, can't edit it:
![image](https://user-images.githubusercontent.com/7794575/51299034-a2e1c180-1a2f-11e9-884e-a8db9e62430e.png)

**Comment by btry** [comment]
Hi

Having no feedback, I close this issue.
