### ISSUE TITLE
Impossible to empty recycle bin of deleted forms

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/formcreator#1265]
**Describe the bug**
If create a form and then answer your questions a couple of times, you'll start to see a list of your answers build up in the "form answer" tab. Then, if you want to subsequently delete some of the answers present, the procedure seems to be to check the ones you want and then open the "action" menu which then offers you to put them in the trashcan. The problem is that once they're there, they become completely inaccessible as there is no way to access the formcreator trashcan.

**To Reproduce**
1. Create a form with a single question
2. Fill your form and answer it a couple of times
3. Go to the "Form answers tab"
4. Select a couple of the forms you want to delete
5. Click on the "Action" button and select "Put in trashcan"

**Expected behavior**
While the forms are correctly put in the trashcan, I would expect to have, like on the ticket forms, an actual icon that allow me to access said trashcan to complete the deletion process or revert it. However, since the icon is not there, then forms in the trashcan become stuck in a completely inaccessible state barring me from actually deleting any form that has answers associated with it short of manually deleting records in the database.

**Comment by btry** [comment]
Hi

I already noticed  that 1 or 2 weeks ago. As there are beta versions of 2.7.0 I must wait until the versin 2.8.0 to fix that: I must remove the column is_deleted from the FormAnswers table.

I think this issue should be linked to : https://github.com/pluginsGLPI/formcreator/issues/861

**Comment by btry** [comment]
Hi

as this issue is blocking form deletion with answers I think it is better to provide a fix for 2.7.0.  The above PR should fix the issue.
