### ISSUE TITLE
Question : changement du statut de validation en base

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1268]
Bonjour,
si je demande la validation du formulaire, est-il possible lorsque la validation a été refusée, de modifier ce statut (en base) afin de le mettre de nouveau dans l'état : en attente de validation.
J'ai bien tenté une modif sur la table glpi_plugin_formcreator_issues en modifiant la valeur du champ status de refused en waiting. Mais cela ne change rien au final :(

Au passage, dans cette table, je retrouve l'ensemble des tickets créés avec ou sans le formulaire !
Et l'intitulé (name) du formulaire que j'aurai pu changer pour qu'il apparaisse différemment dans la liste des formulaires créés (mais ça ne marche pas non plus).

Features : 
- Tant que le formulaire n'est pas validé, pouvoir revenir sur les infos saisies dans le formulaire pour modifications.
- pouvoir déterminer un valideur en fonction de la réponse à une question (plus complexe, car il faut faire les questions AVANT de choisir le valideur ...)

**Comment by Sicoval31** [comment]
Super, on peut ainsi repasser du statut refusé au statut en attente de validation en modifiant le champ dans la table form_answers. Je pensais aussi pouvoir modifier l'intitulé du formulaire, mais non :(

**Comment by btry** [comment]
Oui, vous pouvez, mais je n'ai pas mesuré les éventuels effets de bord que ça peut avoir (notification mail, impact sur l'UI).

Pour modifier l'intitulé de formulaire, il y a des demandes pour une fonctinnalité permetant de le rendre plus "dynamique", je pense qu'i lfaut prendre en compte des balises comme c'est fait pour les tickets cibles. Je ne sais pas encore quand j'implémenterai la fonctionnalité.

**Comment by btry** [comment]
Bonjour

Des améliorations ont été faites régulièrement pour calculer le statut des demandes d'assistance. Ce ticket est devenu obsolète, et probablement résolu.
