### ISSUE TITLE
Question de type LDAP impossible à créer

### ISSUE THREAD

**Issue by AdAugustaPerAngusta** [pluginsGLPI/formcreator#127]
ma version de glpi est la 0.85.4, ma version du plugin est la : 0.90-1.2.5
mais la création d'une question de type LDAP est impossible malgré le fait que ce bug doit être couvert dans cette version.
La validation de la création de la question ne se fait pas et la page web devient vide !(glpi/plugins/formcreator/front/question.form.php)
Merci de votre aide.

**Comment by neeftarah** [comment]
Bonjour,

Pouvez-vous passer GLPI en "mode debug" si possible (Compte Super-Admin : Préférences) et me transmettre les erreurs qui pourrais s'afficher ?

De même s'il y a des erreurs, elles devraient être enregistrer dans le fichier files/_logs/php-errors.log ou files/_logs/sql-errors.log

Pouvez-vous également me joindre une capture d'écran de la configuration de votre question ?

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
Bonjour,

N'ayant pas  de nouvelle de votre part, je vais clôturer cette issue et déployer la version 0.90-1.3.

Si vous rencontrez à nouveau ce problème, n'hésitez pas à réouvrir l'issue avec plus de détails.

Cordialement,
Jérémy
