### ISSUE TITLE
Caractères spéciaux champs conditionnels

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/formcreator#1270]
Lorsque que je créer un champ conditionnel avec une apostrophe ou une parenthése, la vérification du = sur la condition ne fonctionne pas.

**Comment by btry** [comment]
Bonjour

Il n'y aura plus de version corrective pour la série 2.6.x. Il est fort possible que le problème soit résolu avec la version 2.7.0 à venir. Je vous invite à essayer la beta 3 pour voir si le problème persiste.

**Comment by btry** [comment]
Bonjour

J'ai créé un formulaire avec 2 questions de type texte, la seconde étant affichée si la première contient "test =". Avec la version de développemetn actuelle (eta 3 + quelques correctifs) je n'ai eu aucun souci.

**Comment by btry** [comment]
![image](https://user-images.githubusercontent.com/14139801/51524747-11a78c00-1e2f-11e9-8d75-68d5cb3857ab.png)

![image](https://user-images.githubusercontent.com/14139801/51524757-1704d680-1e2f-11e9-9703-3ba5f71781c3.png)

![image](https://user-images.githubusercontent.com/14139801/51524774-1ff5a800-1e2f-11e9-9806-d8a4d9cf3c8c.png)

### sane signe =
![image](https://user-images.githubusercontent.com/14139801/51524788-27b54c80-1e2f-11e9-94d1-f192541c8fb9.png)

### avec signe =
![image](https://user-images.githubusercontent.com/14139801/51524799-2dab2d80-1e2f-11e9-933b-dd97ca3949bd.png)

**Comment by titidelaff** [comment]
Ma faute,

C'est les caractères ' et ( qui me posent problèmes.

Question de type boutons radio
![image](https://user-images.githubusercontent.com/23405363/51542647-06b72080-1e5c-11e9-9678-cf861de42396.png)

Question de type boutons radio avec la condition
![image](https://user-images.githubusercontent.com/23405363/51542734-39611900-1e5c-11e9-9efe-221514c7a11d.png)

Résultat
![image](https://user-images.githubusercontent.com/23405363/51542759-4847cb80-1e5c-11e9-8f60-ecc1382b377a.png)

En attendant j'enlève les apostrophes et les parenthèses et ça marche.

**Comment by titidelaff** [comment]
Sans le '
![image](https://user-images.githubusercontent.com/23405363/51542844-7af1c400-1e5c-11e9-8739-2867d4a7d305.png)

**Comment by btry** [comment]
Hi

I found several issues when investigating. Please test the latest revision of the develop branch with the above patch and feedback

**Comment by titidelaff** [comment]
It still does not work with the patch on the latest version of the develop branch.

**Comment by btry** [comment]
Indeed, I updated the PR, please try again and feeback

**Comment by titidelaff** [comment]
With the last modification it works.
Thank you

**Comment by titidelaff** [comment]
I just did some tests, I think there is a problem to recover the answer and for showing entered form.
I created a destination for a ticket.
Inside I put an answer from a question with radio button and '
Once the ticket is created, the answers do not appear in my ticket.
When i want to show entered form, in debug mode I have an error in the fields.class.php file:
PHP Notice: Undefined offset: 254 in C:\glpi\plugins\formcreator\inc\fields.class.php at line 186

Fatal error: Uncaught Error: Call to a member function isPrerequisites() on null in C:\glpi\plugins\formcreator\inc\fields.class.php:201 Stack trace: #0 C:\glpi\plugins\formcreator\inc\formanswer.class.php(574): PluginFormcreatorFields::isVisible('260', Array) #1 C:\glpi\inc\commonglpi.class.php(475): PluginFormcreatorFormAnswer->showForm('193', Array) #2 C:\glpi\ajax\common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFormcreatorFormAnswer), 'PluginFormcreat...', '', Array) #3 {main} thrown in C:\glpi\plugins\formcreator\inc\fields.class.php on line 201

**Comment by btry** [comment]
Hi

This error looks like an inconsistency in your DB. Let's assume you have a form with two fields A and B

B is hidden unless A matches some expression, but A does not exists (it may be deleted after confuring B)

In such case, the code will instanciate an object representing the field A to do the comparison defined in the field B. This instanciation probably failed. 

Please have a look in your database: check if this A field is in the DB. If the inconsistency is confirmed, then I need to find what did you do with this A field. Maybe a cascaded deletion is missing in the plugin (i'm checking right now)

**Comment by btry** [comment]
Update

 the cascaded deletion of the A field works as expected: deleting A will also delete the condition in the field B.

**Comment by btry** [comment]
I'll try to reproduce with your exact description. Stay tuned

**Comment by titidelaff** [comment]
Another problem with the patch.
When someone populates a question in a form with a **'** I have a http 500 error.

**Comment by btry** [comment]
tests with **it's ok** and **it's not ok** => success. I don't reproduce any bug

![image](https://user-images.githubusercontent.com/14139801/51991639-d0a51c80-24ab-11e9-99c8-34af44b79e9d.png)

![image](https://user-images.githubusercontent.com/14139801/51991655-d69afd80-24ab-11e9-8429-8c8a7887add6.png)

**Comment by btry** [comment]
> When someone populates a question in a form with a ' I have a http 500 error.

Please tell me which types or fields are impacted. Text, textarea ?

**Comment by titidelaff** [comment]
text

**Comment by btry** [comment]
The patch is yupdated, now you should be able to have a single quote in text and radio answers.

**Comment by titidelaff** [comment]
Ok for single quote in text filed

**Comment by btry** [comment]
OK, 

now the conditions issue remains to be fixed.

You have a condition in your question B. This contition has a the ID of the question A in a foreign key column. Checl that the ID of the question A matches the value in the condition.

If not, try to delete questions A and B then recreate them (with the condition).

**Comment by titidelaff** [comment]
Looks like it's working properly now.
I will still do some testing and make a comeback.
Thank you for the time spent on this problem.

**Comment by titidelaff** [comment]
Hello,
When I create a destination for a ticket, if I put an single quote in the title field, the ticket does not generate on the other hand the form yes and I get a 500 error or a blank page

**Comment by titidelaff** [comment]
I understand that it is easier to handle errors by making several requests but the error here is always related to the single quote.
Moreover if in a field description there is a single quote the form does not record the field and I end up with tickets without description

**Comment by titidelaff** [comment]
You'r right.
Thank you

**Comment by titidelaff** [comment]
Ok, so last information with a - '- it works
With a - '- it does not work.
I did not see the difference at the beginning but by making a copy paste of the single quote we see the difference

**Comment by btry** [comment]
for the HTTP 500 error : 
https://github.com/pluginsGLPI/formcreator/pull/1285

please test and feedback.

> Moreover if in a field description (textaerafield) there is a single quote the form does not record the field and I end up with tickets without description

Are you  talking about a question of type description ?
![image](https://user-images.githubusercontent.com/14139801/52137104-14358d00-264a-11e9-974a-477cff4b67d1.png)

**Comment by titidelaff** [comment]
Yes question of type description.
I try this:
line 80 add return Toolbox::addslashes_deep($this->value);
line 127 & 135 replace by return Toolbox::addslashes_deep($this->value);
With this no problem.

**Comment by btry** [comment]
Hi

I get a different result because it is better to not save a **\'** litterally in the DB. I took time to check other fields and noticed similar issues.

Please feedback with fixes #1285 and #1286 .

**Comment by btry** [comment]
Hi

No feedback, then I assume  the bug is solved. Feel free to open a new ticket if issue still occurs.
