### ISSUE TITLE
Acteur (observateur) depuis une question

### ISSUE THREAD

**Issue by kurgans0** [pluginsGLPI/formcreator#1274]
Il est pratique d'ajouter des acteurs à un ticket, particulièrement les observateurs depuis une liste définie à l'aide d'une question de type Objet GLPI.

Mais dans la question, on n'a pas d'option pour limiter le retour de choix donner par l'objet GLPI, particulièrement quand ce sont des Utilisateurs.

Serait-il possible d'ajouter un filtre sur les différents champs de l'objet GLPI pour limiter la liste, un peu comme on peut le faire pour une requête LDAP?

(À noter au passage que l'utilisation d'Objet LDAP n'est pas possible avec les Acteurs ce qui serait également pratique)

Bravo pour votre travail.

**Comment by btry** [comment]
Bonjour

Il me semble qu'il y a déjà des demandes communautaires de ce type en attente. Si vous voulez avoir la fonctinalité plus rapidement vous pouvez envisager de souscrire à GLPI Network: https://glpi-project.org/glpi-network/ .

En ce qui concerne les objets LDAP, je ne vois pas vraiment l'intérêt : les utilisateurs de l'annuaire devraient être importés dans GLPI. Une fois fait, ils seront disponibles avec le champ Acteurs ou Objet GLPI / Utilsiateur.

![image](https://user-images.githubusercontent.com/14139801/51828904-e02a3700-22ec-11e9-9e38-d29c25b75c7f.png)

**Comment by btry** [comment]
Duplicate of #591

**Comment by btry** [comment]
In progress: https://github.com/pluginsGLPI/formcreator/pull/2978

big up to the sponsor

**Comment by btry** [comment]
Bonjour

La fonctionnalité de filtrage sur Objets GLPI et intitulés sera disponible dans Formcreator 2.14.0
