### ISSUE TITLE
Liste déroulante entité non fonctionnelle

### ISSUE THREAD

**Issue by sonbinome** [pluginsGLPI/formcreator#1276]
**Describe the bug**
La liste déroulante des entités ne fonctionne pas.

**To Reproduce**
Créer une question, sélectionner le type "Objet GLPI" et choisir l'objet GLPI "Administration - Entités"
![image](https://user-images.githubusercontent.com/30912487/51734054-a7d3f000-2083-11e9-8dc0-c1bc25654169.png)

**Expected behavior**
Quand on prévisualise le questionnaire, la liste déroulante pour sélectionner l'entité est vide (elle ne fait apparaitre que l'entité active). Cela est pareil si on lance le formulaire de façon classique

**Screenshots**

![image](https://user-images.githubusercontent.com/30912487/51734142-ef5a7c00-2083-11e9-9985-dd381a50833e.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser [Chrome, Firefox]
 - Version GLPI: 9.3.3
 - Version Plugin : 2.7.0 Beta3

**Comment by btry** [comment]
Hi

Please test this fix and feedback : https://github.com/pluginsGLPI/formcreator/pull/1278

**Comment by sonbinome** [comment]
Hello,

I've just remplaced my file inc/fields/dropdownfield.class.php with your's new file and apparently it works for me.
Thanks a lot for your help.

Have a good day :-)

**Comment by btry** [comment]
Great ! thank you for hunting the bug !
