### ISSUE TITLE
Error "Class 'PluginFormcreatorForm' not found" on public forms

### ISSUE THREAD

**Issue by pafnow** [pluginsGLPI/formcreator#1277]
When I try to open a public form with an incognito browser window, I get this error

URL: https://****/plugins/formcreator/front/formdisplay.php?id=1
Error:
Fatal error: Uncaught Error: Class 'PluginFormcreatorForm' not found in /var/www/glpi/plugins/formcreator/front/formdisplay.php:43 Stack trace: #0 {main} thrown in /var/www/glpi/plugins/formcreator/front/formdisplay.php on line 43

The form is properly set as public:
![image](https://user-images.githubusercontent.com/8747037/51741874-a974d680-20ca-11e9-9f90-496eb8dfcd30.png)

It works properly when logged in...

GLPI 9.3.1
Forms 2.6.5

**Comment by btry** [comment]
Hi

Can you check if this still occurs with 2.7.0-beta.3 (on a testing envitronment) ?

**Comment by pafnow** [comment]
Yes, same issue

**Comment by btry** [comment]
Can you try to reset all cookies related to glpi in the browser, or try with a private browsing window ? Maybe there is a session problem.

**Comment by btry** [comment]
Hi 

No feedback; I assume you found a solution. If not, feel free to request to reopen.
