### ISSUE TITLE
Pas de ticket généré après saisie formulaire sans validation

### ISSUE THREAD

**Issue by ThedarksideoftheForce** [pluginsGLPI/formcreator#128]
Bonjour,

GLPI 0.84.3  -  Formcreator 0.84-2.1.5

Je rencontre un problème sur la génération automatique de ticket après la saisie d'un formulaire sans validation.
Je viens d'installer Formcreator 0.84-2.1.5
J'ai créé une catégorie de formulaires 'Categorie test'
J'ai créé un nouveau formulaire : 
Nom : Formulaire test numéro 1
Actif : Oui
Catégorie : Categorie test
Accès direct depuis la page d'accueil : Oui
Description du formulaire : Formulaire de test
Mangue : Français
Entete : Ce formulaire est le formulaire de test numero 1
Validation requise : Non

J'ai créé une section : Section 1
 J'ai créé une question : 
Titre : Quelle est la couleur du cheval blanc d'Henry IV ?
Type : Liste déroulante
Section : Section 1
Affichage du champ : Toujours
Champ obligatoire : Oui
Afficher une valeur vide : Non
Valeur par défaut : Rouge
Valeurs : Rouge;Bleu;orange;Blanc;Vert;Marron
Description : Merci de donner votre avis

J'ai défini la cible : Utilisateurs GLPI authentifiés

J'ai défini la Destination : 
Nom : Ticket généné par Formulaire test numero 1
Titre du ticket : Ticket genene par Formulaire test numero 1
Description : ##FULLFORM##
Gabarit de tickets : -----

J'ouvre le formulaire, j'y répond (la bonne réponse est Blanc), je clique sur Envoyer.

Je vois que le formulaire est validé, mais je n'ai pas de ticket généré ;-(

Avez-vous une idée de l'origine de ce problème ? Ai-je oublié quelque chose quelque part ?

Merci de votre aide.

Cordialement,

**Comment by neeftarah** [comment]
Bonjour,

Merci de votre retour, la correction sera incluse dans la prochaine version. Pous pouvez également voir les corrections apportées dans le commit ci-dessus.

Cordialement,
Jérémy

**Comment by ThedarksideoftheForce** [comment]
Bonjour, 

Super ! J'ai hâte de pouvoir l'installer. Un grand merci pour votre travail. Malgré ce bug, nous avons mis en place les formulaires qui nous aident énormément dans la quête d'informations auprès de nos utilisateurs pour la génération des tickets. 

Cordialement, 

Olivier Lecomte 
ThedarksideoftheForce 

----- Mail original -----

De: "Jérémy MOREAU" <notifications@github.com> 
À: "pluginsGLPI/formcreator" <formcreator@noreply.github.com> 
Cc: "ThedarksideoftheForce" <olivier.lecomte@free.fr> 
Envoyé: Mardi 27 Octobre 2015 17:04:59 
Objet: Re: [formcreator] Pas de ticket généré après saisie formulaire sans validation (#128) 


Bonjour, 
Merci de votre retour, la correction sera incluse dans la prochaine version. Pous pouvez également voir les corrections apportées dans le commit ci-dessus. 
Cordialement, 
Jérémy

**Comment by Raphael19** [comment]
Bonjour,
Est ce que vous avez une date pour la correction de ce bug?

Merci
Cordialement

Raphaël
