### ISSUE TITLE
Lien dans une question 

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1281]
Dans une question, je souhaite indiquer un lien internet "exterieur" à l'instance de GLPI.
Par defaut le lien de l'instance est ajouté au lien cible : 
http:\\siteGlpi\ http\\lienexterne

comment faire pour n'avoir que 
http:\\lienexterne 

Merci

**Comment by btry** [comment]
Bonjour

Pouvez vous montrer le détail de votre question dans l'interface de conception de votre formulaire ?

**Comment by EC2311** [comment]
Bonjour

Vous souhaitez voir le code source de la question ? ou un screenshot de la question?

**Comment by btry** [comment]
J'ai besoin d'un screenshot pour reproduire exactement comme vous l'avez fait

**Comment by EC2311** [comment]
Bonjour
En re-modifiant, l'ajout du lien cfg du site n'est plus ajouté.
Donc je ne sais pas si c'est un bug ou lors de la copie du lien dans la case ? (peut etre en collant http:\\ ou sans justement ?)
Toujours est-il : la ca fonctionne.

si j'arrive à reproduire je mets un screenshot

**Comment by btry** [comment]
Bonjour

J'attends quelques jours, et si vous ne reproduisez pas, je pense qu'on pourra fermer le ticket. 

A tout hasard, la question n'aurait-elle pas été créée avec une version précédente du plugin ?

**Comment by EC2311** [comment]
Bonjour

Je suis en version 2.7.0 beta 1

**Comment by EC2311** [comment]
J'etais en 2.7.0 beta 1
mais néanmoins je viens juste de passer en beta 3 ce matin.

**Comment by EC2311** [comment]
Je pense que l'on va fermer ce topic.
Je ne reussis pas à reproduire.
Merci Bien.
