### ISSUE TITLE
[2.7.0-beta.3 ] Not saving the "Specific selection" in change destination

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#1282]
**Describe the bug**
In Change destination:
I'm selecting "ticket category" ->> "specific category" and then selecting the category
but after "save" (->> Item successfully updated ) the "Ticket category" returns to "Specific category" and the category is not saved.

**To Reproduce**
1. Create a simple form.
2. Add a destination, choosing change type.
3. In the destination setting page, in the "Ticket category" field select "Specific category". Select the category and save the destination settings.
4. Note that the selected category is not saved.

**Expected behavior**
The selected category is save.

**Comment by btry** [comment]
Hi

I don't reproduce. Maybe your tables are slightly out of date. Did you do a fresh installation of the plugin or did you upgrade from a previous beta ?

**Comment by pedroluisvsousa** [comment]
Hi,
I installed the last development version and the problem persists. Note: The problem is present only in the change destination. In destination ticket is ok.

- Ticket destination - ok!

![captura de tela de 2019-01-31 05-37-01](https://user-images.githubusercontent.com/26510405/52041930-8e66f400-251a-11e9-8a2d-3531459d660d.png)

- Change destination - no saving specific category
![captura de tela de 2019-01-31 05-37-50](https://user-images.githubusercontent.com/26510405/52041928-8e66f400-251a-11e9-8433-c672db3c6102.png)

**Comment by btry** [comment]
Please share the result of this SQL query

```sql SHOW CREATE table glpi_plugin_formcreator_targetchanges```

**Comment by pedroluisvsousa** [comment]
mysql> SHOW CREATE TABLE glpi_plugin_formcreator_targetchanges;
+---------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                                 | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+---------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| glpi_plugin_formcreator_targetchanges | CREATE TABLE `glpi_plugin_formcreator_targetchanges` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `content` longtext COLLATE utf8_unicode_ci,
  `impactcontent` longtext COLLATE utf8_unicode_ci,
  `controlistcontent` longtext COLLATE utf8_unicode_ci,
  `rolloutplancontent` longtext COLLATE utf8_unicode_ci,
  `backoutplancontent` longtext COLLATE utf8_unicode_ci,
  `checklistcontent` longtext COLLATE utf8_unicode_ci,
  `due_date_rule` enum('answer','change','calcul') COLLATE utf8_unicode_ci DEFAULT NULL,
  `due_date_question` int(11) DEFAULT NULL,
  `due_date_value` tinyint(4) DEFAULT NULL,
  `due_date_period` enum('minute','hour','day','month') COLLATE utf8_unicode_ci DEFAULT NULL,
  `urgency_rule` enum('none','specific','answer') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'none',
  `urgency_question` int(11) NOT NULL DEFAULT '0',
  `validation_followup` tinyint(1) NOT NULL DEFAULT '1',
  `destination_entity` enum('current','requester','requester_dynamic_first','requester_dynamic_last','form','validator','specific','user','entity') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'requester',
  `destination_entity_value` int(11) DEFAULT NULL,
  `tag_type` enum('none','questions','specifics','questions_and_specific','questions_or_specific') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'none',
  `tag_questions` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `tag_specifics` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `category_rule` enum('none','specific','answer') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'none',
  `category_question` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+---------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0,00 sec)

**Comment by pompzer** [comment]
Hello,

I have the exact same issue. These fields are not saved : 
![image](https://user-images.githubusercontent.com/41009559/52558276-2c4ba000-2df2-11e9-8ca4-6ba01edb84e8.png)

No SQL errors, but I have PHP notices : 

```
2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: destination_entity
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:349
  plugins/formcreator/inc/targetticket.class.php:127 PluginFormcreatorTargetBase->showDestinationEntitySetings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: destination_entity_value
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:394
  plugins/formcreator/inc/targetticket.class.php:127 PluginFormcreatorTargetBase->showDestinationEntitySetings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: destination_entity_value
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:415
  plugins/formcreator/inc/targetticket.class.php:127 PluginFormcreatorTargetBase->showDestinationEntitySetings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: destination_entity_value
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:436
  plugins/formcreator/inc/targetticket.class.php:127 PluginFormcreatorTargetBase->showDestinationEntitySetings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: category_rule
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:538
  plugins/formcreator/inc/targetticket.class.php:137 PluginFormcreatorTargetBase->showCategorySettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: category_question
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:588
  plugins/formcreator/inc/targetticket.class.php:137 PluginFormcreatorTargetBase->showCategorySettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: category_question
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:594
  plugins/formcreator/inc/targetticket.class.php:137 PluginFormcreatorTargetBase->showCategorySettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: urgency_rule
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:609
  plugins/formcreator/inc/targetticket.class.php:142 PluginFormcreatorTargetBase->showUrgencySettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: urgency_question
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:644
  plugins/formcreator/inc/targetticket.class.php:142 PluginFormcreatorTargetBase->showUrgencySettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: urgency_question
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:663
  plugins/formcreator/inc/targetticket.class.php:142 PluginFormcreatorTargetBase->showUrgencySettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: location_rule
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:842
  plugins/formcreator/inc/targetticket.class.php:147 PluginFormcreatorTargetBase->showLocationSettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: location_question
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:877
  plugins/formcreator/inc/targetticket.class.php:147 PluginFormcreatorTargetBase->showLocationSettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: location_question
  Backtrace :
  plugins/formcreator/inc/targetbase.class.php:899
  plugins/formcreator/inc/targetticket.class.php:147 PluginFormcreatorTargetBase->showLocationSettings()
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

2019-02-11 11:43:41 [xxx]
  *** PHP Notice(8): Undefined index: uuid
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:353
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
```


GLPI : 9.2.3
Plugin ver : 2.6.5

Maybe the issue seems obvious but I'm not a developper at all, for me it is chinese... (Chinese is easier in fact)

Thanks for your help.

**Comment by btry** [comment]
Hi

@pompzer I checked the code and i think that some code in GLPI fails to load data from the DB before displaying the page.

Unfortunately the backtrace you found don't help me to find how this may happen. I need to see what happens in your server. To do that you heed professional support. Contact us at contact@teclib.com .

**Comment by pompzer** [comment]
Hi @btry 

Thanks for your help, I finally solved it, but I am not sure about what did the trick, here is all I did in chronological order : 

1. I ran glpi/scripts/check_db.php
2. Corrected all tables that has errors (a lot !)
3. Tried again the plugin, issue not fixed
4. I uninstalled the plugin, made sure that no tables from the plugin were left, then reinstalled the plugin
5. Now it works !

Find attached my SQL requests to solve my tables issues, maybe you will notice smthg.

Thanks a lot
[check_db.txt](https://github.com/pluginsGLPI/formcreator/files/2851585/check_db.txt)

**Comment by btry** [comment]
Hi

This seems strange... I guess that you were running a recent version of GLPI with a older database version. Maybe this was the same for the plugin. 

You should carefully read about how to upgrade GLPI (I'm suspecting that upgrades are not done as they should be), and evaluate the risk about a damaged database. As this is out of the scope of development, feel free to get community support from the forum, or get professional support.

I'm still waiting from feedback from @pedroluisvsousa

**Comment by pompzer** [comment]
Hi @btry 

Yes you are right, my predecessor had a lot of issue with upgrading GLPI, especially from 0.X.X versions to 9.2.3. I'm sure he did not upgrade correctly, I fix what I found piece by piece... I will think about professionnal support, you are right.

Thank you.

**Comment by pedroluisvsousa** [comment]
Hi,

I tested it on a new installation and it worked.
The problem remains in a migrated instance. Errors were not listed in the php-errors.log and sql-errors.log files.
I will make another migration and return the test results.

Greetings.

**Comment by btry** [comment]
I remove the bug label, as feedbacks shows the problem might be something else.

**Comment by pedroluisvsousa** [comment]
Hi,

I made a new GLPI migration and installation of Formcreator plugin (development version) and this problem  was fixed.
However, the category assigned at the change destination was not assigned to the change ticket as shown in the screens below.

![rect1426](https://user-images.githubusercontent.com/26510405/52642035-f9b8aa80-2eb8-11e9-9900-b23d8788f2d7.png)
![rect817](https://user-images.githubusercontent.com/26510405/52642037-f9b8aa80-2eb8-11e9-91c6-e101117cb7e8.png)

Regards.

**Comment by btry** [comment]
> However, the category assigned at the change destination was not assigned to the change ticket as shown in the screens below.

I released 2.7.0 right now... then you were probably running nearly the same. A quick check with  GLPI 9.4 was successful 

![image](https://user-images.githubusercontent.com/14139801/52642960-4bbef780-2edc-11e9-9a4c-fb56d3f03ea2.png)

![image](https://user-images.githubusercontent.com/14139801/52642984-5c6f6d80-2edc-11e9-8544-83decec02425.png)

**Comment by btry** [comment]
I reproduced. Code to assign category for changes was missing. 

@pedroluisvsousa  Try release 2.7.0 + patch #1300 and feedback

**Comment by pedroluisvsousa** [comment]
Hi,
Great!! It's ok!

Thanks a lot.
