### ISSUE TITLE
absence table glpi_plugin_formcreator_matching_questions

### ISSUE THREAD

**Issue by dgsn** [pluginsGLPI/formcreator#130]
Bonjour,
je n'arrive pas à valider une question avec un affichage conditionnel.
J'obtiens le message : 
"L'action que vous avez réalisée n'est pas autorisée."
et dans la log SQL il y a : 
'2015-10-07 12:49:57
*** MySQL query error: 
*** _
SQL: SELECT m.`targets_id`, q.`name`, `fields`
                          FROM `glpi_plugin_formcreator_matching_questions` m
                          LEFT JOIN `glpi_plugin_formcreator_questions` q ON m.`targets_id` = q.`id`
                          WHERE `questions_id` = 24
Error: Table 'glpi2.glpi_plugin_formcreator_matching_questions' doesn't exist'

Effectivement cette table n'existe pas.

Informations : 
formcreator          Name: Formulaires                    Version: 0.84-2.1.5
GLPI  0.84.8 

Bien cordialement

**Comment by neeftarah** [comment]
Bonjour,

Le code pour créer cette table est le suivant : 
```SQL
CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_matching_questions` (
    `questions_id` int(11) NOT NULL,
    `targets_id` int(11) NOT NULL,
    `fields` int(11) NOT NULL,
    CONSTRAINT pk_questions_targets PRIMARY KEY (questions_id, targets_id)
)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
```

il a été ajouté dans le code de la prochaine version.

Cordialement,
Jérémy
