### ISSUE TITLE
Icone manquant depuis la version 9.4 de GLPI

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#1302]
Il manque des icônes sur l'interface utilisateur depuis la mise a jour en 9.4 de GLPI.
![image](https://user-images.githubusercontent.com/47602797/52789867-607ac700-3065-11e9-9154-e1263a4a40b8.png)

Version 9.4.0 de GLPI et 2.7.0 de Formcreator.
J'ai essayer depuis chrome et firefox, même résultat.
J'ai désactivé les autres plugin, même résultat
.

**Comment by toinoubm** [comment]
J'ai le même problème. 
Plus l'onglet de réservation qui ne s'affiche pas alors que le profil possède les droits. J'ai essayé de fouiller un peu dans les fichier mais je ne trouve pas les images même celle qui s'affiche correctement.

**Comment by tguichard25** [comment]
Tu as vérifié que tu avais bien un équipement autorisé pour la réservation.

**Comment by toinoubm** [comment]
En regardant le code j'ai compris que c’était ça. Du coup effectivement cela marche mieux avec des réservations autorisé. Par contre impossible de trouver les images de l'interface utilisateur dans les dossiers. Je vais approfondir ma recherche. De toute façon je suis en train de recoder certain truc pour l'interface utilisateur, pour pouvoir combler les besoins de mon entreprise. Donc je vais peut être trouver ce qui cloche.

**Comment by tguichard25** [comment]
Il me semble que depuis la 9.4 font awesome est utilisé de base par GLPI , formcreator l'utilisait avant cela.

**Comment by toinoubm** [comment]
j'ai trouvé la solution. Effectivement c'est font awesome qui est utilisé.  Dans le fichier inc/wizard.class.php ligne 100 ils suffit de remplacer `echo '<span class="fa fa-paper-plane-o fc_list_icon" title="'.__('Seek assistance', 'formcreator').'"></span>';` par `echo '<span class="fa fa-paper-plane fc_list_icon" title="'.__('Seek assistance', 'formcreator').'"></span>';`

**Comment by toinoubm** [comment]
cela doit être une erreur similaire pour la réservation.

**Comment by btry** [comment]
Bonjour

Effectivement il semble que la version de font awesome dans GLPI 9.4 ne reconnait plus ```fa-paper-plane-o```. Vérification faite avec GLPI 9.3, je valode votre changement @toinoubm . Le commit est dans la branche develop.

**Comment by btry** [comment]
correction faite aussi pour les réservations.

![image](https://user-images.githubusercontent.com/14139801/52942259-f2871600-336a-11e9-9960-7984b8745c0c.png)
