### ISSUE TITLE
Objet GLPI - Projet

### ISSUE THREAD

**Issue by Kiks67** [pluginsGLPI/formcreator#1303]
Bonjour

Est-il prévu/possible de rajouter les projets dans les objets GLPI ?
A cet jour, dans "Outils", il y a uniquement "Notes" et "Flux RSS".

![image](https://user-images.githubusercontent.com/44313220/52793680-86589980-306e-11e9-9ada-438666846506.png)

**Comment by toinoubm** [comment]
J'ai besoin de rajouter cette option pour entreprise, je suis en train de voir comment l'implémenter.

**Comment by btry** [comment]
Bonjour

essayez ce patch, ça devrait satisfaire votre besoin.

**Comment by Kiks67** [comment]
Nickel 👍  ça marche très bien
Ne reste plus que la possibilité de lier les tickets aux objets en question lors de la création du ticket

**Comment by btry** [comment]
Bonjour

Si vous voulez accélérer l'implémentatin de la liaison d'objets aux tickets, vous pouvez nous contacter ici : contact@teclib.com
