### ISSUE TITLE
Champs conditionnés non affiché dans le ticket

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#1304]
**Describe the bug**
Les champs conditionnés par "Masqué par défaut sauf si" n'apparaissent pas dans le ticket généré.

**To Reproduce**
Formcreator : 2.7.0
GLPI : 9.3.1

Création d'un formulaire avec 2 champs : 
  - Q1 case à cocher avec 2 valeurs "C1" et "C2"
  - Q2 bouton radio avec 2 valeurs "R1" et "R2" avec la condition "Masqué par défaut sauf si Q1 = C1"
![image](https://user-images.githubusercontent.com/44919953/52961255-d3a07800-339a-11e9-82b3-c4c894d35892.png)

On coche C1 et on sélectionne R1 : 
![image](https://user-images.githubusercontent.com/44919953/52961392-20844e80-339b-11e9-8f9e-e72451c49f1b.png)

Configuration de la destination par défaut : 
![image](https://user-images.githubusercontent.com/44919953/52961348-02b6e980-339b-11e9-8635-5cffe3b70f42.png)

Le ticket généré ne contient pas Q2 et sa réponse : 
![image](https://user-images.githubusercontent.com/44919953/52961463-46115800-339b-11e9-83c1-416712354b80.png)

**Expected behavior**
Lorsque la condition est respectée, le champ doit être renseigné dans le ticket

**Comment by jvergacas** [comment]
I have had the same problem with GLPI 9.4 and Forcreator 2.7.0

**Comment by msizec** [comment]
I did not face this problem with 9.4 and 2.7

**Comment by btry** [comment]
Hi

I reproduce the issue

**Comment by btry** [comment]
Can you try the patch #1331 and feedback ?

The issue seems to occur when you tick only one option of the checkboxes question

**Comment by jvergacas** [comment]
thanks, now it's working fine.

**Comment by btry** [comment]
thank you for your feedback, the patch is ready for the next release. I close this issue.
