### ISSUE TITLE
Validator don't recive email when I need an aceptation request.

### ISSUE THREAD

**Issue by Nestmojo** [pluginsGLPI/formcreator#1307]
Hello, I'm using GLPI 9.1.6. 

I created a form and colocate an user as validation form. 

When I create a new form as self service user I expect the validator that I chose recieve an email indicating they have to responds a request. 

![image](https://user-images.githubusercontent.com/33136858/53048350-2725cb00-345a-11e9-806b-026f12a4b86c.png)

The problem is the validator don't receive the notification in his email. 

The Ticket objetive was created this form 

![image](https://user-images.githubusercontent.com/33136858/53048462-6d7b2a00-345a-11e9-8d3c-de88373bd8d4.png)

And when the validator confirms the request, is in this moment when he receiv the email. 

**What I Want?**

i want when a user send a form requesting the validation the validator receive a email.
![image](https://user-images.githubusercontent.com/33136858/53048990-ac5daf80-345b-11e9-9feb-5a63d6a8f54d.png)

Please, can you help me

Sorry for my english, My native leguage is Spanish.

**Comment by btry** [comment]
Hi

Can you check if the problem persists with the latest release of Formcreator and GLPI 9.3.3 or GLPI 9.4 ? Based on the version of GLPI, I think you're not using the latest release of the product.

**Comment by btry** [comment]
Hi,

No feedback, then I close

**Comment by Sophal-IT** [comment]
Dear btry,
Currently I am using latest version of GLPI also Form creator plugin. But the problem is the same to @Nestmojo.
Please help

**Comment by btry** [comment]
Hi

Check that you have configured the cron job to run the GLPI's automatic actions scheduler. This is the most common mistake for this kind of issues.

Next check glpi/files/_logs/cron.log . It should contain an entry every minute.

Finally check the notification queue in GLPI and see if it contains notrifications related to Formcreator. Don't forget to check the deleted notifications. A deleted notification is a sent notrification.
