### ISSUE TITLE
[2.7.0] The change ticket fields are not saved

### ISSUE THREAD

**Issue by luisjosemachado** [pluginsGLPI/formcreator#1309]
Hi,

I am running tests to migrate my current server with GLPI 9.1.7.1 and Formcreator 2.5.2.

On a test environment, the server was migrated to GLPI 9.3.3 and Formcreator 2.7.

I get the following error. When a target change is setting in a form, the change ticket fields are not saved: Destination entity, Time to resolve, Ticket category and Urgency (See screnshots and logs below).

**Before saving**
![screenshot_2019-02-20 glpi - form creator - 1](https://user-images.githubusercontent.com/30940056/53116114-9d8fff00-3526-11e9-8c5a-dbae13212087.png)

**After saving**
![screenshot_2019-02-20 glpi - form creator - 1 1](https://user-images.githubusercontent.com/30940056/53116112-9d8fff00-3526-11e9-9552-d6b8f97a2c2c.png)

**sql-errors.log**

_[2019-02-20 15:37:56] glpisqllog.ERROR: DBmysql::query() in /var/www/html/nti933_1/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_plugin_formcreator_formanswers` WHERE `plugin_formcreator_forms_id` = '1' AND `is_deleted` = '0'
  Error: Unknown column 'is_deleted' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/dbutils.class.php:329                          DBmysql->request()
  inc/dbutils.class.php:380                          DbUtils->countElementsInTable()
  plugins/formcreator/inc/formanswer.class.php:367   DbUtils->countElementsInTableForMyEntities()
  inc/commonglpi.class.php:210                       PluginFormcreatorFormAnswer->getTabNameForItem()
  plugins/formcreator/inc/form.class.php:584         CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:165                       PluginFormcreatorForm->defineTabs()
  inc/commonglpi.class.php:707                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1005                      CommonGLPI->showTabsContent()
  plugins/formcreator/front/form.form.php:155        CommonGLPI->display()
  {"user":"2@localhost.localdomain","mem_usage":"0.163\", 11.43Mio)"} 
[2019-02-20 15:37:56] glpisqllog.ERROR: DBmysql::query() in /var/www/html/nti933_1/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_plugin_formcreator_formanswers` WHERE `plugin_formcreator_forms_id` = '1' AND `is_deleted` = '0'
  Error: Unknown column 'is_deleted' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/dbutils.class.php:329                          DBmysql->request()
  inc/dbutils.class.php:380                          DbUtils->countElementsInTable()
  plugins/formcreator/inc/formanswer.class.php:367   DbUtils->countElementsInTableForMyEntities()
  inc/commonglpi.class.php:210                       PluginFormcreatorFormAnswer->getTabNameForItem()
  plugins/formcreator/inc/form.class.php:584         CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:165                       PluginFormcreatorForm->defineTabs()
  ajax/updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()
  {"user":"2@localhost.localdomain"}_ 

**Some observations:**
1. This problem is also present in the production system (GLPI 9.171 + Form 2.5.2);
2. There is no this problem when I do a clean install with GLPI 9.3.3 + Form 2.7. But the bug is present in a clean install with GLPI 9.171 + Form 2.5.2;
3. I tried uninstalling the form, migrating the system and then installing the plugins (version 2.7). However, the problem persists.

Regards.

**Comment by btry** [comment]
Hi

I think the best would be to create manually the missing column in the table. It looks like a bug in the upgrade code somewhere between 2..x and 2.7.0

**Comment by btry** [comment]
Hi

I found the cause of your SQL errors : is_deleted is a column removed from the table but a query was not updated. The fix is ready for  the next release.

However his bug is not related to your problem while editing a target.

**Comment by btry** [comment]
If I edit a target ticket and set time to resolve , urgency or location, this works fine. Could you try the develop branch on a testing environment ? Maybe the the latest fixes will help you.

**Comment by luisjosemachado** [comment]
Hi,

I tested develop branch and the bug is still present. As I said in the first post, this bug is only in the migrated base of Form 2.5.2 and editing the target change.

Regards.

**Comment by btry** [comment]
Can you check if you see an SQL error diferent from the ones you gave earlier ?

**Comment by pedroluisvsousa** [comment]
Hi, 

I run form 2.8 with GLPI 9.3.3 and 9.4.1.1. 
The problem continues with a migrated base and no error log is logged.

Regards.

**Comment by btry** [comment]
Is is a fresh install of the plugin or an upgraded one ?

If you upgraded the plugin, please tell me how you update the files of the plugin.

**Comment by pedroluisvsousa** [comment]
Hi,

It's an upgraded one.

The form upgrade steps (Linux CentOS 7), after upgrade GLPI:

1. Unzip the file *glpi-formcreator-2.8.0.tar.bz2* in <glpi_root>/plugins;
2. Change owner permission: chown apache.apache /var/www/html/glpi/plugins -R;
3. Login in GLPI web interface.
4. Go to menu Administrator>>Plugins and install and enable the Form plugin.

Thanks.

**Comment by pedroluisvsousa** [comment]
I also tried uninstalling the form plugin before the GLPI upgrade.

**Comment by btry** [comment]
Then you overwrite older files. A file in 2.6.x was renamed in 2.7.0. Then your plugin contains 2 versions of the same thing, under 2 different filename. Thius should not impact the behabiour of the plugin, but it is better to move the old version away from GLPI then put the newer version in the plugins/ folder.

Could you reproduce the issue and check if you have an SQL error in GLPI's logs ?

**Comment by pedroluisvsousa** [comment]
I upgraded GLPI by creating a new root directory and the new plugin folder was empty. So I do not override old files.

**Comment by btry** [comment]
ok,

Could you try 3 things ?
- create a new form with a target ticket and edit this target ticket. Try to edit the fields where you encouteer bugs, and feedback
- find in the table glpi_plugin_formcreator_targettickets the rows of belonging to your faulty form, and the test form. Show them here.

**Comment by btry** [comment]
hi @pedroluisvsousa 

Do you have news about your issue ?

**Comment by pedroluisvsousa** [comment]
I tested GLPI 9.4.2 and Form 2.8.1 with the migrated database and the problem persists.

Regards.

**Comment by btry** [comment]
Can you show a screenshot of the values before saving the changes, after saving the changes and show the row in the DB ?

Also, please check the logs of GLPI and report PHP errors or SQL errors.

**Comment by lgardre-ocea** [comment]
Hi,

Same issue here, with GLPI 9.4.2 and Form Creator 2.8.2. The location does not link with the form response in the ticket.

Question :
![1](https://user-images.githubusercontent.com/51413452/59288015-17cdc600-8c73-11e9-9af7-b65f4431f896.png)

Question Configuration :
![2](https://user-images.githubusercontent.com/51413452/59288091-3fbd2980-8c73-11e9-939b-e33023b26a2c.png)

Destination Ticket (see "Lieu" should link to "Agence" field) :
![3](https://user-images.githubusercontent.com/51413452/59288146-5fece880-8c73-11e9-9754-1d910004268e.png)

Final Ticket after completing a test form (see that "Lieu" field is empty, thought "Agence" in the form is mandatory and was not empty when sending the form) :
![4](https://user-images.githubusercontent.com/51413452/59288174-6f6c3180-8c73-11e9-937a-fefabb59b4f4.png)

**Comment by btry** [comment]
Hi @lgardre-ocea 

Please check the logs in glpi/file/_logs : php-errors.log and sql-errors.log . Are there some relevant errors ?

**Comment by lgardre-ocea** [comment]
Hi @btry,

Actually, I can't really say if the errors are relevant or not, but here they are:

1. In php-errors.log, there are two recurring errors: "Trying to get property of non-object" and "Undefined index: user_id_validator"

Example below:
```
[2019-06-12 10:53:04] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  inc/dbmysql.class.php:285
  plugins/formcreator/inc/form.class.php:872         DBmysql->numrows()
  plugins/formcreator/inc/form.class.php:600         PluginFormcreatorForm->showMyLastForms()
  plugins/formcreator/front/formlist.php:62          PluginFormcreatorForm->showList()
  {"user":"192@GLPI-PROD-02","mem_usage":"0.000\", 5.48Mio)"}
[2019-06-12 10:56:45] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: users_id_validator
  Backtrace :
  ...r/inc/notificationtargetformanswer.class.php:65
  inc/notificationtarget.class.php:1236              PluginFormcreatorNotificationTargetFormAnswer->addDataForTemplate()
  inc/notificationtemplate.class.php:253             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:108        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:164                NotificationEventAbstract::raise()
  plugins/formcreator/inc/formanswer.class.php:820   NotificationEvent::raiseEvent()
  plugins/formcreator/inc/form.class.php:1220        PluginFormcreatorFormAnswer->saveAnswers()
  plugins/formcreator/front/form.form.php:123        PluginFormcreatorForm->saveForm()
  {"user":"192@GLPI-PROD-02"}
```



2. In sql-errors.log, there also are two recurring errors: "Unknown column 'fa.users_id_validator' in 'where clause'", "Unknown column 'fanswer.users_id_validator' in 'field list'"

Example below:
```
[2019-06-12 10:48:54] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT count(id) AS quant
        FROM glpi_problems
        WHERE is_deleted = 0

        AND glpi_tickets.entities_id IN (0,1)
  Error: Unknown column 'glpi_tickets.entities_id' in 'where clause'
  Backtrace :
  ...ins/dashboard/front/metrics/metrics.inc.php:390
  plugins/dashboard/front/metrics/index.php:21       include()
  {"user":"1243@GLPI-PROD-02"}
[2019-06-12 10:53:04] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT fa.`id`, f.`name`, fa.`status`, fa.`request_date`
                FROM glpi_plugin_formcreator_forms f
                INNER JOIN glpi_plugin_formcreator_forms_validators fv ON fv.`plugin_formcreator_forms_id`=f.`id`
                INNER JOIN glpi_plugin_formcreator_formanswers fa ON f.`id` = fa.`plugin_formcreator_forms_id`
                WHERE (f.`validation_required` = 1 AND fv.`items_id` = '192' AND fv.`itemtype` = 'User' AND `fa`.`users_id_validator` = '192'
                   OR f.`validation_required` = 2 AND fv.`items_id` IN ('8') AND fv.`itemtype` = 'Group' AND `fa`.`groups_id_validator` IN ('8')
                )
                AND f.is_deleted = 0
                ORDER BY fa.`status` ASC, fa.`request_date` DESC
                LIMIT 0, 5
  Error: Unknown column 'fa.users_id_validator' in 'where clause'
  Backtrace :
  plugins/formcreator/inc/form.class.php:871
  plugins/formcreator/inc/form.class.php:600         PluginFormcreatorForm->showMyLastForms()
  plugins/formcreator/front/formlist.php:62          PluginFormcreatorForm->showList()
  {"user":"192@GLPI-PROD-02"}

[2019-06-12 12:46:01] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS `cpt` FROM (SELECT DISTINCT
                  NULL                           AS `id`,
                  `f`.`name`                     AS `name`,
                  CONCAT('f_',`fanswer`.`id`)    AS `display_id`,
                  `fanswer`.`id`                 AS `original_id`,
                  'PluginFormcreatorFormAnswer'  AS `sub_itemtype`,
                  `fanswer`.`status`             AS `status`,
                  `fanswer`.`request_date`       AS `date_creation`,
                  `fanswer`.`request_date`       AS `date_mod`,
                  `fanswer`.`entities_id`        AS `entities_id`,
                  `fanswer`.`is_recursive`       AS `is_recursive`,
                  `fanswer`.`requester_id`       AS `requester_id`,
                  `fanswer`.`users_id_validator` AS `validator_id`,
                  `fanswer`.`comment`            AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  `tic`.`name`                  AS `name`,
                  CONCAT('t_',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  'Ticket'                      AS `sub_itemtype`,
                  `tic`.`status`                AS `status`,
                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tic`.`users_id_recipient`    AS `requester_id`,
                  0                             AS `validator_id`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
  Error: Unknown column 'fanswer.users_id_validator' in 'field list'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:124
:                                                  PluginFormcreatorIssue::cronSyncIssues()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:83                                  CronTask::launch()
```

**Comment by btry** [comment]
It seems that your database was not properly upgraded in the past. The missing column users_id_validator was introduced 2 years ago.

You should fix the structure of your tables. This is very likely not related to your issue, but this is more urgent. Once it is fixed then you may come back on this issue. Compare the structure of the table glpi_plugin_formcreator_formanswers against the structure described in install/mysql/plugin_formcreator_empty.sql.

**Comment by lgardre-ocea** [comment]
Thanks for the quick answer.

Why am I not surprised?... ^^
Allright, I'll do that first and update the ticket later.


Regards,
Ludo

**Comment by btry** [comment]
Hi 

This issue is talled for long, and new versions of the plugin are out now. It is obsolete. If the issue still ocurs with the latest version or the 2.9.0-beta branch, then feel free to open a new issue with a link to this one.
