### ISSUE TITLE
 field text area in form

### ISSUE THREAD

**Issue by claudiatobarrodriguez** [pluginsGLPI/formcreator#1318]
It would be great if the field text area were enriched that can include tables, graphics or text with special format

Thank you,

Your Wonderful project, helps a lot to the management of IT services

**Comment by btry** [comment]
Hi

If you enable rich text mode in GLPI 9.3 you will have access to HTML tables.

In GLPI 9.4 the rich text mode setting does not longer exists, it is always enabled.

### GLPI 9.3
![image](https://user-images.githubusercontent.com/14139801/53514186-69d54c00-3ac7-11e9-8cbe-2333a0d5bf67.png)

### GLPI 9.4
![image](https://user-images.githubusercontent.com/14139801/53514201-79ed2b80-3ac7-11e9-821c-cc43f1c7c612.png)

**Comment by claudiatobarrodriguez** [comment]
Hi, thanks for your response.
I wanted to confirm that I refer to the formcreator plugin, it only allows me to add a text area.
It would be great if you could edit it in rich text

view image.

Greetings

Claudia.

![captura](https://user-images.githubusercontent.com/44502507/53518125-5b266f00-3a9e-11e9-92ad-e0514001c47b.PNG)

**Comment by btry** [comment]
Yes, this makes sense to have rich text here. However I need to refactor some parts of the plugin to enable rich text in the predefined value. 

I began this code refactor, and the release target is 2.9.0.

**Comment by NeyRamon** [comment]
It would be nice if you could insert image into the text area and get saved in glpi.

**Comment by btry** [comment]
Hi

Insert of images in the textarea was fixed recently. See #1455.

**Comment by btry** [comment]
Hi 

In the latest release the rich text is enabled for the default value. I think I can close this thread.
