### ISSUE TITLE
Changement de cible KO pour les changements

### ISSUE THREAD

**Issue by KaiserTroll** [pluginsGLPI/formcreator#1319]
Bonjour à tous,

Je voulais savoir s'il existait une subtilité qui expliquerait pourquoi lors d'un "changement de cible", je ne peux pas affecter mon **Changement** à une catégorie, alors que dans le cas d'un **Incident** aucun soucis, tout se passe bien ? (la config que j'ai faite est identique)

Idem, je ne peux pas **Attribué à** automatiquement un **Changement** à l'**"Acteur depuis la question"**, alors que depuis un **Incident** c'est possible. (la config que j'ai faite est là aussi identique)

Merci pour vos retours :) 

GLPI 9.3.3
Formulaire 2.7.0

**Comment by btry** [comment]
Bonjour

1 - Essayez le patch #1300 

2 - je tente de reproduire...

**Comment by btry** [comment]
Pour le 2e problème, il y a une anomalie dans le schéma des tables du plugin. Je dois produire une version 2.8.0 pour ce correctif.

Une fois prêt, je vous demanderai de faire un test d'upgtrade (prévoyez un environnement de test), puis de vérifier que vous pouvez assigner des acteurs depuis une question de type acteurs.

**Comment by btry** [comment]
Bonjour

Voilà un correctif. 

https://github.com/pluginsGLPI/formcreator/pull/1324

Si vous prenez le correctif tel quel, il faudra l'essayer en environnement de test car il faut upgrader le plugin (passage de la version 2.7 à 2.8).

Sinon, modifiez directement la  table glpi_plugin_formcreator_targetchange : il manque dans la colonne  **actor_type**, la valeur **question_actors** dans le type ENUM.

**Comment by KaiserTroll** [comment]
J'ai installé la nouvelle version... mais impossible d'acceder aux formulaires, 
j'ai l'erreur suivante : **Une erreur est survenue au chargement des contenus !**
et quand je repasse sur le 2.7.0, j'ai de nouveau accès et plus de soucis


Je suis passé en version GLPI 9.4.0 (pour les besoins du nouveau pluging)

**Comment by btry** [comment]
Je n'en suis pas certain, mais je pense que vous n'avez pas exécuté l'upgrade du plugin. Il en faut pas sseulement mettre à jour les fichiers, mais aussi utiliser l'outil en lign de commande pour upgrader, ou aller dans al liste des plugins de GLPI pour lancer la procédure d'upgrade. Sinon le plugin se désactive (à cause de la différence de version entre les tables du plugin et la version du code).

**Comment by KaiserTroll** [comment]
Non non, j'ai bien mis à jour le plugin (j'avais fais des captures pour être certain)

<img width="825" alt="form" src="https://user-images.githubusercontent.com/46817165/53567179-b1f37d80-3b5e-11e9-8466-1e8b6c683b6e.PNG">

Et là encore, même en revennant en version 2.7, ils réapparaissent, et sont de nouveau indisponible dès que je refais la montée de version

**Comment by btry** [comment]
Je ne reproduis pas ce problème.

Pouvez vous donner l'URL où apparait le souci, pour que j'aille au bon endroit ?

Je pense que vous avez l'affichage de GLPI et que l'erreur est dans  la partie centrale (le contenu des onglets). Si oui, alors vous avez peut être une erreur HTTP 500 au chargement de l'onglet, donc vous devriez avoir un backtrace dans les logs du serveur HTTP. Avec  ce backtrace je pense que je pourrai trouver ce qu'il se passe.

**Comment by KaiserTroll** [comment]
J'ai l'erreur à la connexion de l'utilisateur (et ce n'est pas un soucis de droits, un compte self-service ou super-admin ont le même soucis).
Dans la capture ci-dessous, je n'ai pas le bouton **Formulaire** qui apparait dans le menu du haut (alors que dans la version précédente si)

<img width="626" alt="form2" src="https://user-images.githubusercontent.com/46817165/53568635-d94c4980-3b62-11e9-926c-d09ad8353b34.PNG">

Et l'erreur s'affiche comme il suit lorsque je click sur le bouton formulaire du menu plus bas.
<img width="635" alt="form3" src="https://user-images.githubusercontent.com/46817165/53568639-d9e4e000-3b62-11e9-84d2-eb2d5aea9d2c.PNG">

Pouvez-vous me dire où trouver les logs GLPI ? Car pas de logs sur le serveur lui même.

**Comment by btry** [comment]
Je viens de  tester, ça fonctionne toujours  pour moi; et je ne vois pas comment le patch peut influer sur cette vue.

Vous avez trouvé le backtrace dans votre serveur HTTP ? Si je ne reproduis pas c'est mon seul espoir d'avoir un indice sur pourquoi ça plante.

**Comment by btry** [comment]
Je pense que vous avez pris la branche support/2.9.0 pour vos tests. Prenez la branche develop et appliquez le patch #1324 . 

Dans la branche support/2.9.0 j'ai corrigé un problème qui pourrait corespondre à votre souci. Cette version n'est pas à utiliser car elle est l'objet de refactorages de code importants.

**Comment by KaiserTroll** [comment]
Alors, effectivement à la vue du répertoire install il semblerait bien que ce soit une version 2.9.0 que j'ai...

<img width="516" alt="form4" src="https://user-images.githubusercontent.com/46817165/53628080-5d0d4100-3c0a-11e9-8066-60d9be9a9a00.PNG">

Cependant, c'est bien la version 2.8.0 que j'ai téléchargé (je l'ai reprise ce matin dans le doute).
Je pense que du coup c'est le lien de téléchargement qui pointe sur la version 2.9.0.

Et donc avec cette "**pseudo**" version 2.8.0 (qui semble être la 2.9.0 en réalité) en modifiant les valeurs selon le patch #1324, toujours la même erreur.
(Pseudo n'est en rien péjoratif ;) juste pas la version qu'on attend) 

Dans tous les cas, merci pour l'aide apportée

**Comment by btry** [comment]
Apperemment vous avez téléchargé la branche support/2.8.0 . Ne prenez pas celle là, ell a été renommée en 2.9.0 à cause du patch.

prenez plutot directement cette archive : https://github.com/btry/formcreator/archive/1319.zip

**Comment by KaiserTroll** [comment]
Je pense que là encore il semble y avoir un soucis... (ou alors c'est moi le soucis, possible aussi)

Dès que je mets le plugin, mon site devient indisponible 

<img width="276" alt="form5" src="https://user-images.githubusercontent.com/46817165/53633401-a617c200-3c17-11e9-9f4a-cb9b4fb2f292.PNG">

Et dès que je supprime le plugin, de nouveau dispo (j'ai testé plusieurs fois pour être sur de la corrélation

**Comment by btry** [comment]
C'est une erreur HTTP 500. Il faut que vous donniez le backtrace enregistré dans les logs du serveur HTTP pour avoir du détail sur ce qu'il se passe.

**Comment by KaiserTroll** [comment]
Après quelques recherches dans les méandres de l'hébergeur, voilà la seule chose que j'ai : 

**XX.XX.XX.XX monurl.web.ovh** - [01/Mar/2019:14:33:25 +0100] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"

**Comment by btry** [comment]
Cette ligne provient de access.log. Le backtrace sera dans error.log . Vous ne devriez pas ête loin.

Voilà un exemple de backtrace provenant d'un serveur Apache 2

```
[Fri Mar 01 14:22:57.435023 2019] [php7:notice] [pid 31389] [client ::1:47208] 
PHP Fatal error:  Uncaught Error: Cannot use object of type PluginFormcreatorSection as array in /var/www/html/glpi-94/plugins/formcreator/inc/question.class.php:175
Stack trace:
#0 /homevar/www/html/glpi-94/plugins/formcreator/inc/question.class.php(137): PluginFormcreatorQuestion::showForForm(Object(PluginFormcreatorForm), '')
#1 /var/www/html/glpi-94/inc/commonglpi.class.php(485): PluginFormcreatorQuestion::displayTabContentForItem(Object(PluginFormcreatorForm), '1', '')
#2 /var/www/html/glpi-94/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFormcreatorForm), 'PluginFormcreat...', '', Array)
#3 {main}
thrown in /var/www/html/glpi-94/plugins/formcreator/inc/question.class.php on line 175, referer: http://server/glpi-94/plugins/formcreator/front/form.form.php?id=5
```

**Comment by KaiserTroll** [comment]
Je suis désolé, je n'ai pas accès à autre chose...

**Comment by btry** [comment]
Alors je ne pourrai pas trouver ce qu'il se passe dans votre instance. Pour ma part, j'ai fait des essais et n'ai pas eu de problème. 

Est il possible de faire un essai avec un serveur où vous avez la pleine maîtrise (une VM par exemple) ?

**Comment by KaiserTroll** [comment]
Depuis une version avec Wamp, j'ai l'erreur suivante lors de l'installation du plugin : (est-ce que ça peut expliquer)

`2.4.1 multiple alter in glpi_plugin_formcreator_answers - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_answers` ADD INDEX `plugin_formcreator_forms_answers_id` (`plugin_formcreator_forms_answers_id`) , ADD INDEX `plugin_formcreator_question_id` (`plugin_formcreator_question_id`) - L'erreur est La clé 'plugin_formcreator_forms_answers_id' n'existe pas dans la table`

**Comment by btry** [comment]
Ce genre d'erreur peut arriver pendant un upgrade, pas une installation.

Si vous avez cette erreur après une tentative d'upgrade précédente qui a échoué, il faut restaurer la BDD avant de faire un upgrade (pour éviter un état imprévu des tables).

J'ai besoin de savoir quelle est la version du plugin avant l'upgrade.

**Comment by KaiserTroll** [comment]
Bonjour,
J'étais en version 2.7.0.

**Comment by btry** [comment]
J'ai beau réessayer un upgrade avec mon environnement de développement, je n'ai aucun souci.


A propos de votre erreur d'upgrade sur votre environnemetn de test
``
`2.4.1 multiple alter in glpi_plugin_formcreator_answers - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_answers` ADD INDEX `plugin_formcreator_forms_answers_id` (`plugin_formcreator_forms_answers_id`) , ADD INDEX `plugin_formcreator_question_id` (`plugin_formcreator_question_id`) - L'erreur est La clé 'plugin_formcreator_forms_answers_id' n'existe pas dans la table`
``

cela ne peut pas être le fait d'un upgrade de 2.7.0 vers 2.8.0 (le patch), car aucune modification sur cette table n'a lieu.

**Comment by btry** [comment]
Vérification faite, l'index sur ```plugin_formcreator_forms_answers_id``` est ajouté pendant l'upgrade vers 2.5.0 et vers 2.7.0 . Pour une raison ou une autre, l'upgrade s'effectue donc à partir df'une version antérieure à 2.7.0

**Comment by KaiserTroll** [comment]
Modop que j'ai fait : 
- Depuis la version 2.8.0 non fonctionnelle : Downgrade en version 2.7.0
- Désintallation et nettoyage de la version 2.7.0
- Installation de la version 2.7.0
- Upgrade de la version 2.8.0

Maintenant, ca semble fonctionner (sur mon serveur).
Et le soucis d'affectation initial a bien été corrigé ! 

Merci pour le temps et les réponses !!
