### ISSUE TITLE
Pas de boutons dans modifier une destination

### ISSUE THREAD

**Issue by blienard** [pluginsGLPI/formcreator#132]
Bonjour,

Les boutons de validation et d'annulation (ainsi que les champs qui devraient figurer sous _Gabarit de ticket_ et _Date d'échéance_) n'apparaissent pas dans le formulaire de modification d'une destination.

GLPI v0.90

Plugins :
* Formulaires	0.90-1.2.5
* Comportements	0.90
* OCS Inventory NG	1.2.0
* Plus de rapports	0.90+1.0
* Tableau de bord	0.6.8

La désactivation des plugins ne change rien.

Cordialement

**Comment by blienard** [comment]
Copie écran
![bug_formulaire](https://cloud.githubusercontent.com/assets/4600782/10511175/c6be79ec-7337-11e5-84a2-7becd4a16be8.JPG)

**Comment by tamtamaouy** [comment]
Bonjour, J'ai le meme probleme que vous avec la meme version. Je ne sais pas si quelqu'un peut nous donner un retour par rapport a ce point.
Bien cordialement.

**Comment by jpmba** [comment]
Même problème sur une installation debian PHP 5.6 (ok sur windows php 5.4)
Peut être un problème avec la traduction 
Solution temporaire:
dans plugins/formcreator/inc/targetticket.class.php
REMPLACER (ligne 150)

 Dropdown::showFromArray('due_date_period', array(
         'minute' => _n('Minute', 'Minutes', 2),
         'hour'   => _n('Hour', 'Hours', 2),
         'day'    => _n('Day', 'Days', 2),
         'month'  => _n('Month', 'Month', 2),
      ), array(
         'value' => $this->fields['due_date_period']
      ));      

PAR
Dropdown::showFromArray("due_date_period", array(
         'minute' => 'Minute',
         'hour'   => 'Hours',
         'day'    => 'Days',
         'month'  => 'Month'
      ), array(
         'value' => $this->fields['due_date_period']
      ));

**Comment by blienard** [comment]
Merci.
J'ai testé et cela fonctionne parfaitement.

**Comment by tamtamaouy** [comment]
Bonsoir,
j'ai appliqué la solution proposée. tout est OK maintenant.
Merci bcp.

**Comment by blienard** [comment]
Il reste un petit bug : lorsqu'on veut définir une date d'échance dans Ticket cible, le nombre de jours (ou minutes, ou heures, ou mois) reste à 1 quelque soit le nombre choisi.

**Comment by neeftarah** [comment]
Bonjour,

Merci pour vos retours. Le problème est due à une absence de traduction dans GLPI.
La solution proposée ci-dessus fonctionne, mais ne tient pas compte des traductions souhaité par l'utilisateur.

Une correction est apporté et sera disponible sur la prochaine version (Cf. commit ci-dessous)

Cordialement,
Jérémy
