### ISSUE TITLE
Affectation automatique à la Catégorie de ticket

### ISSUE THREAD

**Issue by KaiserTroll** [pluginsGLPI/formcreator#1321]
Bonsoir, 

Je voulais savoir en quel type de question, je devais déclarer mon choix afin de pouvoir affecter directement à la **Catégorie de ticket**, dont le résultat serait **Egale à la réponse à la question**

![image](https://user-images.githubusercontent.com/46817165/53360227-4bd7e200-3935-11e9-9fc0-b2dfbf413614.png)

J'ai essayé en déclarant en **Boutons radio**, et en **Séléction**. Pour le moment je n'arrive pas à le faire fonctionner

Merci pour vos retours :)

GLPI 9.3.3
Formulaire 2.7.0

**Comment by btry** [comment]
Bonjour

Vous avez besoin que le formulaire contienne uen question de type Intitulé, catégorie de ticket

![image](https://user-images.githubusercontent.com/14139801/53510172-a603af00-3abd-11e9-92e9-732332f10097.png)

Les questions apparaitront ensuite dans la liste 

![image](https://user-images.githubusercontent.com/14139801/53510283-e19e7900-3abd-11e9-9bea-d7e8738b4ff6.png)

**Comment by KaiserTroll** [comment]
Suite à la nouvelle version, cela fonctionne, merci !
