### ISSUE TITLE
 Impossible de sélectionner un objet dans Formulaire

### ISSUE THREAD

**Issue by DooBio** [pluginsGLPI/formcreator#1323]
Bonjour

Suite à la mise à jour de GLPI 9.4 et Formcreator 2.7. les utilisateurs ne peuvent plus sélectionner d'objet dans les formulaires :  la combo est vide

Voici l’écran de configuration de la question : 

![image](https://user-images.githubusercontent.com/32511461/53429740-7e451600-39ed-11e9-9d30-1612a6717ff8.png)

Et voici l'affichage avec un Utilisateur Profil Self-Service 
![image](https://user-images.githubusercontent.com/32511461/53430008-f7446d80-39ed-11e9-8f0a-998e0252d2e4.png)

Je précise qu'avec un utilisateur admin ça fonctionne

**Comment by btry** [comment]
Bonjour

Je pense que votre profil self-service n'est habilité à montrer que les équipements de l'utilsiateur. C'est une restriction implémentée assez récemment pour respecter les restrictions configurées au niveau des profils.

![image](https://user-images.githubusercontent.com/14139801/53485601-ea278d00-3a86-11e9-9134-e7b0c025c4c1.png)

**Comment by DooBio** [comment]
Merci 

c'est exactement ça merci j'ai décoché la case et la visualisation est revenu

Désolé pour le dérangement

A+

**Comment by btry** [comment]
Bonjour

Merci pour le retour. Pas de mal, j'ai aussi cru à un bug sur le coup ;)
