### ISSUE TITLE
Hidden submit button

### ISSUE THREAD

**Issue by nichollasrennah** [pluginsGLPI/formcreator#1329]
Is it possible to implement a check condition for submitting the form? 

For example, the option to hide the "Submit button" if a field does not match a certain condition.

It would prevent the form from being sent if a specific field does not meet a certain condition.

**Comment by btry** [comment]
Hi, 

No, this is not possible for now. The form is validated after submission.

**Comment by btry** [comment]
Hi

The feature is implemented.
