### ISSUE TITLE
 The problem with a link in an email

### ISSUE THREAD

**Issue by Ruiseart** [pluginsGLPI/formcreator#133]
The variable "## formcreator.validation link ##" is always filled with "http://..." even though GLPI is available only on encrypted connection.

**Comment by neeftarah** [comment]
Hi,

Thanks for your help!

The value was fixed.
It now take the value defined in "Setup > General" : Field "URL of the application" in the "General setup" tab. So it let you define an HTTPS value or whatever you want.

Regards.
