### ISSUE TITLE
Objects are not listed in version 2.7.0

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1332]
I have some users who have access to more than one entity, but version 2.7.0 only shows the objects of the main entity of the user (even selecting to show everything in the entity selection), those of the other entities do not appear in the list.
This problem occurs only on the form, when editing the question, in default value they are shown.

Previous versions worked correctly.

**Comment by btry** [comment]
Hi
Can you give an example of impacted objects ? Computers for example ?

Also, if the form is used with the service catalog, is the profile restricted to "my assets" ? 

If you can read french, please check #1323, especially this comment: https://github.com/pluginsGLPI/formcreator/issues/1323#issuecomment-467818636

**Comment by btry** [comment]
Might be related to this question in the forum: https://forum.glpi-project.org/viewtopic.php?id=167894

**Comment by btry** [comment]
Please, try this fix and feedback: 

https://github.com/pluginsGLPI/formcreator/pull/1333

**Comment by btry** [comment]
No fedback, fix merged. Closing.

**Comment by jvergacas** [comment]
I'm sorry for the delay in answering, we're on the carnival holiday here in Brazil.
I tested it and it is now working properly.
Thank you very much.

**Comment by btry** [comment]
Hi 

> we're on the carnival holiday here in Brazil 

nice ! have fun !

I closed the issue because my tests were successful and there are very few risks it would not run for you, don't worry. Thank you for your feedback.
