### ISSUE TITLE
Erreur 500 lors de l'import de formulaire (Undefined variable)

### ISSUE THREAD

**Issue by touxe** [pluginsGLPI/formcreator#1335]
Bonjour,

J'ai voulu modifier en masse des formulaires. J'ai pour cela exporter l'ensemble de mes formulaires en JSON pour les modifier et les importer par la suite. J'ai une erreur 500 lors de l'import.

Voici un exemple de formulaire que je ne peux pas importer après export (même sans aucune modification) : 
`{
    "forms": [
        {
            "name": "Messagerie - Demander un service",
            "is_recursive": 1,
            "access_rights": 1,
            "requesttype": 7,
            "description": "",
            "content": "",
            "is_active": 1,
            "language": "fr_FR",
            "helpdesk_home": 1,
            "is_deleted": 0,
            "validation_required": 0,
            "is_default": 1,
            "uuid": "7e1dcac4-91f5039d-5c7ae2702397b9.37253392",
            "_plugin_formcreator_category": "Messagerie",
            "_entity": "Root entity > Service Informatique",
            "_sections": [
                {
                    "name": "Informations sur le demandeur (vous ou une autre personne)",
                    "order": 1,
                    "uuid": "7e1dcac4-91f5039d-5c658eeb21fb70.75385139",
                    "_questions": [
                        {
                            "name": "Nom du demandeur",
                            "fieldtype": "glpiselect",
                            "required": 1,
                            "show_empty": 1,
                            "default_values": 0,
                            "values": "User",
                            "range_min": null,
                            "range_max": null,
                            "description": "",
                            "order": 1,
                            "show_rule": "always",
                            "uuid": "7e1dcac4-91f5039d-5c658f0d7dd790.09564768",
                            "_conditions": [],
                            "_parameters": []
                        },
                        {
                            "name": "Téléphone ou joindre le demandeur",
                            "fieldtype": "text",
                            "required": 1,
                            "show_empty": 0,
                            "default_values": "",
                            "values": "",
                            "range_min": null,
                            "range_max": null,
                            "description": "",
                            "order": 2,
                            "show_rule": "always",
                            "uuid": "7e1dcac4-91f5039d-5c6590456255e9.19291007",
                            "_conditions": [],
                            "_parameters": {
                                "text": {
                                    "regex": {
                                        "regex": "",
                                        "fieldname": "regex",
                                        "uuid": "7e1dcac4-91f5039d-5c659045668f01.28540947"
                                    },
                                    "range": {
                                        "range_min": "",
                                        "range_max": "",
                                        "fieldname": "range",
                                        "uuid": "7e1dcac4-91f5039d-5c6590456762c3.62010395"
                                    }
                                }
                            }
                        },
                        {
                            "name": "Localisation du bénéficiaire",
                            "fieldtype": "dropdown",
                            "required": 1,
                            "show_empty": 0,
                            "default_values": 0,
                            "values": "{\"itemtype\":\"Location\"}",
                            "range_min": null,
                            "range_max": null,
                            "description": "",
                            "order": 3,
                            "show_rule": "always",
                            "uuid": "7e1dcac4-91f5039d-5c65907809e266.77840324",
                            "_conditions": [],
                            "_parameters": []
                        },
                        {
                            "name": "Observateur souhaité",
                            "fieldtype": "glpiselect",
                            "required": 0,
                            "show_empty": 1,
                            "default_values": 0,
                            "values": "User",
                            "range_min": null,
                            "range_max": null,
                            "description": "",
                            "order": 4,
                            "show_rule": "always",
                            "uuid": "7e1dcac4-91f5039d-5c6590a1961d89.41982932",
                            "_conditions": [],
                            "_parameters": []
                        }
                    ]
                },
                {
                    "name": "Déposer une demande (J’ai besoin d’un service, d’un accès, d’une information …)",
                    "order": 2,
                    "uuid": "7e1dcac4-91f5039d-5c6593eb6419d0.05176240",
                    "_questions": [
                        {
                            "name": "Veuillez préciser le périmètre de votre demande",
                            "fieldtype": "radios",
                            "required": 1,
                            "show_empty": 0,
                            "default_values": "",
                            "values": "Création d'une BAL\r\nCréation d'une liste de diffusion\r\nCréation de BAL de service\r\nArchivage boite mail\r\nConfiguration d'un smartphone\r\nCréation d'agenda de salle de réunion\r\nAjout/suppression/modification Liste Distribution\r\nAccès Boite mail d'une autre personne\r\nAccès Boite mail Générique\r\nRécupération de messages supprimés\r\nDemande d'information\r\nAutre",
                            "range_min": null,
                            "range_max": null,
                            "description": "",
                            "order": 1,
                            "show_rule": "always",
                            "uuid": "7e1dcac4-91f5039d-5c6594439aa407.62454287",
                            "_conditions": [],
                            "_parameters": []
                        },
                        {
                            "name": "Informations complémentaires",
                            "fieldtype": "textarea",
                            "required": 0,
                            "show_empty": 0,
                            "default_values": "",
                            "values": "",
                            "range_min": null,
                            "range_max": null,
                            "description": "",
                            "order": 2,
                            "show_rule": "always",
                            "uuid": "7e1dcac4-91f5039d-5c6594aea001b3.40706273",
                            "_conditions": [],
                            "_parameters": {
                                "textarea": {
                                    "regex": {
                                        "regex": "",
                                        "fieldname": "regex",
                                        "uuid": "7e1dcac4-91f5039d-5c6594aea40797.25341092"
                                    },
                                    "range": {
                                        "range_min": "",
                                        "range_max": "",
                                        "fieldname": "range",
                                        "uuid": "7e1dcac4-91f5039d-5c6594aea4e995.44544867"
                                    }
                                }
                            }
                        }
                    ]
                }
            ],
            "_validators": [],
            "_targets": [
                {
                    "itemtype": "PluginFormcreatorTargetTicket",
                    "name": "Messagerie- Demander un service",
                    "uuid": "7e1dcac4-91f5039d-5c751c6af2f0c8.93430619",
                    "_data": {
                        "content": "##FULLFORM##",
                        "due_date_rule": "",
                        "due_date_question": 0,
                        "due_date_value": -30,
                        "due_date_period": "minute",
                        "urgency_rule": "none",
                        "urgency_question": 0,
                        "location_rule": "answer",
                        "location_question": 5,
                        "validation_followup": 1,
                        "destination_entity": "current",
                        "destination_entity_value": null,
                        "tag_type": "none",
                        "tag_questions": "",
                        "tag_specifics": "",
                        "category_rule": "specific",
                        "category_question": 308,
                        "_tickettemplate": "Demande",
                        "_ticket_relations": [],
                        "title": "Messagerie- Demander un service",
                        "_actors": [
                            {
                                "actor_role": "requester",
                                "actor_type": "question_person",
                                "use_notification": 1,
                                "uuid": "7e1dcac4-91f5039d-5c6eaa63719ff7.53767462",
                                "_question": "7e1dcac4-91f5039d-5c658f0d7dd790.09564768"
                            },
                            {
                                "actor_role": "observer",
                                "actor_type": "question_person",
                                "use_notification": 1,
                                "uuid": "7e1dcac4-91f5039d-5c6eaa6da81e74.13525687",
                                "_question": "7e1dcac4-91f5039d-5c6590a1961d89.41982932"
                            }
                        ]
                    }
                }
            ],
            "_profiles": []
        }
    ]
}`

Lors de l'import, j'ai l'erreur suivante (mode debug de GLPI)

`PHP Notice: Undefined variable: question_id in /var/www/html/glpi/plugins/formcreator/inc/questionregex.class.php at line 119
PHP Notice: Undefined variable: fieldname in /var/www/html/glpi/plugins/formcreator/inc/questionregex.class.php at line 119

Fatal error: Uncaught Error: Call to a member function getEmptyParameters() on null in /var/www/html/glpi/plugins/formcreator/inc/questionparameter.class.php:113 Stack trace: 
#0 /var/www/html/glpi/plugins/formcreator/inc/questionregex.class.php(119): PluginFormcreatorQuestionParameter::import(Object(PluginFormcreatorImportLinker), NULL, NULL, Array) 
#1 /var/www/html/glpi/plugins/formcreator/inc/question.class.php(1440): PluginFormcreatorQuestionRegex::import(Object(PluginFormcreatorImportLinker), '4', 'regex', Array) 
#2 /var/www/html/glpi/plugins/formcreator/inc/section.class.php(378): PluginFormcreatorQuestion::import(Object(PluginFormcreatorImportLinker), '3', Array)
#3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2098): PluginFormcreatorSection::import(Object(PluginFormcreatorImportLinker), '3', Array) 
#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1922): PluginFormcreatorForm::import(Object(PluginFormcreatorImportLinker), Array) 
#5 /var/www/html/glpi/plugins/formcreator/front/form.form.php(1 in /var/www/html/glpi/plugins/formcreator/inc/questionparameter.class.php on line 113`

Les deux premieres questions semblent être importée, mais pas le reste ...

Cela n'est peut etre pas lié, mais j'ai cette erreur SQL dans les log : 
` Error: Table 'glpi.glpi_plugin_formcreator_forms_answers' doesn't exist`

Voici les tables existantes : 
`| glpi_plugin_formcreator_answers                            |
| glpi_plugin_formcreator_categories                         |
| glpi_plugin_formcreator_entityconfigs                      |
| glpi_plugin_formcreator_formanswers                        |
| glpi_plugin_formcreator_forms                              |
| glpi_plugin_formcreator_forms_profiles                     |
| glpi_plugin_formcreator_forms_validators                   |
| glpi_plugin_formcreator_issues                             |
| glpi_plugin_formcreator_items_targettickets                |
| glpi_plugin_formcreator_questiondependencies               |
| glpi_plugin_formcreator_questionranges                     |
| glpi_plugin_formcreator_questionregexes                    |
| glpi_plugin_formcreator_questions                          |
| glpi_plugin_formcreator_questions_conditions               |
| glpi_plugin_formcreator_sections                           |
| glpi_plugin_formcreator_targetchanges                      |
| glpi_plugin_formcreator_targetchanges_actors               |
| glpi_plugin_formcreator_targets                            |
| glpi_plugin_formcreator_targettickets                      |
| glpi_plugin_formcreator_targettickets_actors  `

MariaDB [glpi]> select * from glpi_configs where context='formcreator';
+-----+-------------+----------------+-------+
| id  | context     | name           | value |
+-----+-------------+----------------+-------+
| 210 | formcreator | schema_version | 2.7   |
+-----+-------------+----------------+-------+
1 row in set (0.000 sec)

GLPI version 9.3.3
Plugin formcreator v 2.7.0

Merci pour votre aide.

**Comment by btry** [comment]
Bonjour

Veuillez essayer le patch ci dessus et me faire un retour.

**Comment by btry** [comment]
Une précision : si une erreur survient pendant l'import, le restant d'un formulaire ne sera pas importé. Il n'est pour le moment pas possible (o extrêmement compliqué) d'annuler l'import d'un formulaire si un souci survient. Il faut attendre la prise en charge de transactions au niveau de la BDD dans GLPI.

A propos de l'erreur ```Error: Table 'glpi.glpi_plugin_formcreator_forms_answers' doesn't exist```, vous devriez avoir un backtrace. pour trouver comment cela se produit. Je voudrais voir si ça correspond au correctif #1314 en attente de validation.

**Comment by touxe** [comment]
Bonjour,

OK pour l'import avec le patch, par contre toute mes catégories de formulaire disparaissent.
C'est comme ci il ne prenait pas en compte le "_plugin_formcreator_category" dans le json

Pour la table manquante, voic ce que j'ai : 
`[2019-03-04 09:01:01] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS 'cpt' FROM (SELECT DISTINCT
                  NULL                           AS 'id',
                  CONCAT('f_','fanswer'.'id')    AS 'display_id',
                  'fanswer'.'id'                 AS 'original_id',
                  'PluginFormcreatorFormAnswer' AS 'sub_itemtype',
                  'f'.'name'                     AS 'name',
                  'fanswer'.'status'             AS 'status',
                  'fanswer'.'request_date'       AS 'date_creation',
                  'fanswer'.'request_date'       AS 'date_mod',
                  'fanswer'.'entities_id'        AS 'entities_id',
                  'fanswer'.'is_recursive'       AS 'is_recursive',
                  'fanswer'.'requester_id'       AS 'requester_id',
                  'fanswer'.'users_id_validator' AS 'validator_id',
                  'fanswer'.'comment'            AS 'comment'
               FROM 'glpi_plugin_formcreator_forms_answers' AS 'fanswer'
               LEFT JOIN 'glpi_plugin_formcreator_forms' AS 'f'
                  ON'f'.'id' = 'fanswer'.'plugin_formcreator_forms_id'
               LEFT JOIN 'glpi_items_tickets' AS 'itic'
                  ON 'itic'.'items_id' = 'fanswer'.'id'
                  AND 'itic'.'itemtype' = 'PluginFormcreatorFormAnswer'
               WHERE 'fanswer'.'is_deleted' = '0'
               GROUP BY 'original_id'
               HAVING COUNT('itic'.'tickets_id') != 1
               UNION
               SELECT DISTINCT
                  NULL                          AS 'id',
                  CONCAT('t_','tic'.'id')       AS 'display_id',
                  'tic'.'id'                    AS 'original_id',
                  'Ticket'                      AS 'sub_itemtype',
                  'tic'.'name'                  AS 'name',
                  'tic'.'status'                AS 'status',
                  'tic'.'date'                  AS 'date_creation',
                  'tic'.'date_mod'              AS 'date_mod',
                  'tic'.'entities_id'           AS 'entities_id',
                  0                             AS 'is_recursive',
                  'tic'.'users_id_recipient'    AS 'requester_id',
                  0                             AS 'validator_id',
                  'tic'.'content'               AS 'comment'
               FROM 'glpi_tickets' AS 'tic'
               LEFT JOIN 'glpi_items_tickets' AS 'itic'
                  ON 'itic'.'tickets_id' = 'tic'.'id'
                  AND 'itic'.'itemtype' = 'PluginFormcreatorFormAnswer'
               WHERE 'tic'.'is_deleted' = 0
               GROUP BY 'original_id'
               HAVING COUNT('itic'.'items_id') <= 1) AS 'issues'
  Error: Table 'glpi.glpi_plugin_formcreator_forms_answers' doesn't exist
  Backtrace :
  plugins/formcreator/inc/issue.class.php:125
  inc/crontask.class.php:832                         PluginFormcreatorIssue::cronSyncIssues()
  front/cron.php:83                                  CronTask::launch()
`

**Comment by btry** [comment]
Le système d'export / import concerne les formulaires uniquement, pas les catégories de formulaire.

La fonctionnalité a été développée pour metre au point des formulaires (et les tester) sur une instance de tests utilisant une copie d'une instance de production). Une fois au point, les formulaires sont exportés de l'instance de test et importés dans l'isntance de production. Du coup les catégories de formulaire sont supposées exister, idem pour tous les objets de GLPI (utilsiateurs, groupes nottament).

**Comment by btry** [comment]
Pour l'erreur SQL, vous confirmez mon hypothèse. Essayez le patch #1314 .

**Comment by touxe** [comment]
> Le système d'export / import concerne les formulaires uniquement, pas les catégories de formulaire.
> 
> La fonctionnalité a été développée pour metre au point des formulaires (et les tester) sur une instance de tests utilisant une copie d'une instance de production). Une fois au point, les formulaires sont exportés de l'instance de test et importés dans l'isntance de production. Du coup les catégories de formulaire sont supposées exister, idem pour tous les objets de GLPI (utilsiateurs, groupes nottament).

Pas certain d'avoir compris. J'exporte et j'importe depuis le même serveur. Du coup les catégories existent bien. Elles sont par ailleurs bien exportées dans le JSON.

**Comment by btry** [comment]
Voilà un correctif pour le problème d'import des catégories de formulaire.

J'y corrige aussi un problème sur les entités, où on peut mettre à jour un formulaire dans uen entité sans qu'on n'ait le droit de le faire.

Essayez le patch #1337

**Comment by btry** [comment]
#1337 merged; closing.
