### ISSUE TITLE
Page "ticket cible" (destination)

### ISSUE THREAD

**Issue by babalou** [pluginsGLPI/formcreator#134]
Bonjour,

J'utilise actuellement GLPI 0.90 et la version master du plugin formcreator.

Lorsque je suis sur la page de configuration d'un ticket cible (destination), je ne vois plus ni le champ pour définir le demandeur, ni le champ pour définir l'observateur, ni le champ pour définir le destinataire, ni le récapitulatif de tous les id des questions du formulaire.

Est-ce simplement un changement lié au passage en version 0.90 ?

**Comment by blienard** [comment]
Bonjour,
Cela ressemble au problème que j'ai rencontré auquel une réponse m'a été apportée hier.
https://github.com/pluginsGLPI/formcreator/issues/132

**Comment by babalou** [comment]
Merci Bruno. Oui, il s'agissait bien du même problème. Je viens d'appliquer le correctif du post #132 et la page de configuration d'un ticket cible fonctionne à nouveau correctement.

**Comment by neeftarah** [comment]
Bonjour,

Le problème est corrigé (voir 08ebeee)

Cordialement,
Jérémy
