### ISSUE TITLE
upgrade error - Version 2.6.5

### ISSUE THREAD

**Issue by spinaldf** [pluginsGLPI/formcreator#1343]
Hi, I try upgrade GLPI + Plugins, but show this errors on upgrade. How can I fix this problem?

Enviroment detais:
GLPI 9.2.2 + Forms 2.6.5 (Last version to GLPI 9.2.2)

Erros:
Mariadb:

 HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
  Error: Unknown column 'fanswer.users_id_validator' in 'field list'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:125        
  plugins/formcreator/install/update_0.0_2.5.php:418 PluginFormcreatorIssue::cronSyncIssues()
  plugins/formcreator/install/update_0.0_2.5.php:50  plugin_formcreator_updateIssue_2_5()
  plugins/formcreator/install/install.php:77         plugin_formcreator_update_2_5()
  plugins/formcreator/hook.php:48                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:731                           plugin_formcreator_install()
  front/plugin.form.php:48                           Plugin->install()

PHP:
  *** PHP Notice(8): Undefined index: title
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:937 
  inc/commondbtm.class.php:1150                      PluginFormcreatorTargetTicket->prepareInputForUpdate()
  plugins/formcreator/install/update_2.5_2.6.php:138 CommonDBTM->update()
  plugins/formcreator/install/install.php:81         plugin_formcreator_update_2_6()
  plugins/formcreator/hook.php:48                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:731                           plugin_formcreator_install()
  front/plugin.form.php:48                           Plugin->install()

**Comment by btry** [comment]
Hi

The column **users_id_validator** was added in the version 2.6.0. Did you upgraded from a version < 2.6.0 to 2.6.x in the past ?

Please use the backup of your DB before the upgrade and compare the output of

```sql
SHOW CREATE TABLE glpi_plugin_formcreator_forms_answers;
```

and the creation of the table located here
https://github.com/pluginsGLPI/formcreator/blob/v2.6.5/install/mysql/plugin_formcreator_empty.sql#L60

**Comment by btry** [comment]
I also notice that the upgrade was running from a version lower than 2.5.0.

In the snapshot of your database before  the upgrade, show the output of the following

```sql
SELECT * FROM glpi_configs WHERE context='formcreator';
```

**Comment by spinaldf** [comment]
Well, my last version was 2.4.2, I Upgrade my GLPI and Plugins

Database changed
MariaDB [glpi]> SELECT * FROM glpi_configs WHERE context='formcreator';
+-------+----------------+-------------+-----+
| value | name           | context     | id  |
+-------+----------------+-------------+-----+
| 2.6   | schema_version | formcreator | 197 |
+-------+----------------+-------------+-----+
1 row in set (0.00 sec)

**Comment by btry** [comment]
Hi

Can you compare the table **glpi_plugin_formcreator_forms_answers** in the backup of your DB before the upgrade against the following CREATE TABLE statement ? 
https://github.com/pluginsGLPI/formcreator/blob/v2.6.5/install/mysql/plugin_formcreator_empty.sql#L60

**Comment by btry** [comment]
Hi

Having no feedback, I close
