### ISSUE TITLE
Open ticket with "new" status with group selected

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1346]
Open ticket with "new" status

When creating a form and informing that it should go to the XPTO group, the ticket is opened with the status "Processing Assigned". However, I need the ticket to be changed to "processed assigned" only when a technician assigns it.

Is it possible for a ticket to go to a group with the status of "new" and only change to "processing attributed" only in the technician assignment?

@btry can u help?

**Comment by phamorais** [comment]
any ?

**Comment by phamorais** [comment]
I Will Publishing this em Pull Requests.

**Comment by btry** [comment]
Hi

When you fill the foem and submitit, do your account has the ability to own a ticket ? (see the rights of your profile)

**Comment by phamorais** [comment]
Hello @btry 

I created two profiles. One for the customer and one for my analyst, and only the Analyst can get a ticket. But when opening a call as a client, the call enters the status of "processing assigned". I would like it to come in as "new", given that no analyst has taken the call yet.


![Teste](https://user-images.githubusercontent.com/35368369/54848384-e5d64480-4cbf-11e9-994a-dfd16532c2f4.gif)

**Comment by phamorais** [comment]
Can u understand?

**Comment by msizec** [comment]
+1, could be an option

**Comment by phamorais** [comment]
@btry 
Is there any possibility for this feature to be realized?

**Comment by btry** [comment]
Hi

I'm not sure about that. I investigated but was interrupted by my workload. If I remember well, this is GLPI which sets the state of the ticket, when the logged in user at time of creation has Own right.

If this is indeed the case, then the plugin might reset the state, but notifications will trigger and this is not a satisfying process IMHO.

I need to see if some special property may be passed ti Ticket::add() to force the state if the ticket. If not, I will consider a PR for GLPI. Remains to be accepted by the team.

If someone needs a quick resolution of this issue, please consider to support the required development : contact@teclib.com.

**Comment by mab18** [comment]
Hi, 
Why not create a rule that would set the status according to certain criteria. I tested on my test environment, we can actually force a status "new", even if with assigned groups .

**Comment by phamorais** [comment]
Hello,

when I posted this issue the most stable version used was 9.3.3

I did the test in 9.3.3 and the rule doesn't work, it keeps going in as Assigned Processing.

However, in version 9.4.4 the rule worked, but I didn't see anything in the rule fix releases.

**Comment by phamorais** [comment]
No longer needed
