### ISSUE TITLE
Enquetes satisfaction

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/formcreator#1348]
bonjour 
Les enquêtes de satisfactions ne fonctionnent pas.
en effet l'utilisateur reçoit son mail de d'invitation d’enquêtes mais lorsqu'il clique sur le lien cela lui renvoie sur le ticket sans l’enquête.
Voici la page sur laquelle j'arrive
![image](https://user-images.githubusercontent.com/36695393/54263024-1277b700-4570-11e9-80a9-5d5a89394d73.png)
Cordialement

**Comment by imanou10** [comment]
Bonjour
Pour information je suis passé en version 7.8

**Comment by btry** [comment]
Bonjour

Il faudra attendre quelques semaines avant que je fasse un test. Qeu vous utilisez la dernière version est déjà une information utile.

**Comment by imanou10** [comment]
Je vous remercie bonne journée

**Comment by btry** [comment]
Une idée : vous utilisez probablement le catalogue de service simplifié. Si vous passez en catalogue de service étendu, est ce que cela résout votre problème ?

**Comment by imanou10** [comment]
Pourriez vous me dire comment le faire j'ai chercher dans tous les menus en vain .
Merci par avance

**Comment by imanou10** [comment]
Cela fonctionne super merci beaucoup.
👍
