### ISSUE TITLE
E-mail notification issue

### ISSUE THREAD

**Issue by Ruiseart** [pluginsGLPI/formcreator#135]
If a ticket is created from a form I get e-mail with: 
...
Requesters : --
...
So is empty. But when I open the ticket I see a name for author and requester. If the ticket is created directly by user everything is OK.

**Comment by neeftarah** [comment]
Hi,

See #100 (In French created on 21 Apr) and https://github.com/glpi-project/glpi/issues/56 (On GLPI).

In short word, Formcreator let you add several requester but GLPI not!
So Formcreator create ticket without requesters and add them later.

This feature may be added to version GLPI 0.91, so we will be able to fixed that problem without remove feature from formcreator as soon as GLPI 0.91 will be released.

Maybe a quick fix may be find with the particular (but must common) case of only one requester. I look at this.

Regards.

**Comment by neeftarah** [comment]
Fixed for one requester. See 9a01239.
