### ISSUE TITLE
Création d'un ticket suivant les réponses du formulaires

### ISSUE THREAD

**Issue by ThomasRavail** [pluginsGLPI/formcreator#1352]
Bonjour

Est-il possible de gérer la création des tickets en fonction des réponses de l'utilisateur ? Actuellement, nous avons un formulaire dynamique en fonction du type de la demande de l'utilisateur :

![image](https://user-images.githubusercontent.com/14281452/54370386-cf087000-4677-11e9-8ab6-cbdd7fa9f843.png)

Dans l'onglet Destination, nous séparons les différentes demandes en incluant les réponses des utilisateurs. Cependant, si un utilisateur sélectionne uniquement le type Compte Utilisateur par exemple, cela crée tout de même 3 autres tickets vides (contenant un espace simplement) :

![image](https://user-images.githubusercontent.com/14281452/54370672-535af300-4678-11e9-92ca-f77a0c2f026a.png)

Y a t-il un moyen pour ne pas créer de ticket si les réponses ne sont pas renseignées ?

En vous remerciant par avance.

Cordialement,
Thomas.

**Comment by btry** [comment]
Bonjour

Pour le moment le plugin ne prend pas en charge la génération de ticket ou changments en fonction de conditions.

C'est une fonctionnalité envisageable; vous pouvez étudier le développement de la fonctionnalité avec notre service commercial : contact@teclib.com

**Comment by btry** [comment]
Bonjour

Les conditions sont implémentées sur les cibles. Sujet résolu.
