### ISSUE TITLE
FormCreator 2.8 : Unable to set a Form Category 

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#1356]
**Describe the bug**
When you create a forms, and you want to affect a category on it, you can see all categories, but when you choose one, field stay blank.

**To Reproduce**
1. Create a form
2. Click on 'Drowp down category list"
3. Select a category

**Expected behavior**
Normally the category name should be displayed

**Screenshots**
Screen before category select : 

![image](https://user-images.githubusercontent.com/16323410/54536654-63811400-4991-11e9-989b-d6973dbc6086.png)

List of available category : 

![2019-03-18_15h17_58](https://user-images.githubusercontent.com/16323410/54536490-1a30c480-4991-11e9-9ad5-302d56c9d525.png)

ScreenShot after select a category : 

![image](https://user-images.githubusercontent.com/16323410/54536581-40566480-4991-11e9-9b49-2863221db338.png)

**Additional context**
GLPI 9.4.1.1

**Comment by btry** [comment]
Hi

Do you have a JS error in the console of your browser ?

**Comment by SylvainGuibert** [comment]
Hi,
Please find the JS errors bellow

![2019-03-26_07h08_23](https://user-images.githubusercontent.com/16323410/54974946-f7f10500-4f95-11e9-8ad8-b8d358e08468.png)
