### ISSUE TITLE
2.8.0 - Balise html <p> dans la description du ticket

### ISSUE THREAD

**Issue by Lau65rent** [pluginsGLPI/formcreator#1357]
Bonjour,

Version Glpi 9.4.0,

lors de la création d'un ticket à partir d'un formulaire, uniquement sur les champs zone texte
il y a la balise html <p> </p> qui apparait dans la description du ticket.
![Capture](https://user-images.githubusercontent.com/31002694/54536650-60862380-4991-11e9-85c7-9e195e2f124a.JPG)

j'ai essayé de suivre la procédure de la version précédente mais il n'y a plus de Text enrichie sur la 9.4

Comment faire?

**Comment by btry** [comment]
Bonjour,

Avec quelle version du plugin ?

**Comment by Lau65rent** [comment]
2.7.0 pardon

**Comment by btry** [comment]
Je viens de tester je ne reproduis pas . 
![image](https://user-images.githubusercontent.com/14139801/54541499-5ae10b80-499a-11e9-8ed7-c4a0fed4cd32.png)

Pouvez-vous monter le texte qui décrit la génération du ticket ? Utilsiez vous la balise ##FULLFORM## ?

Le formulaire a t il été créé dans uen  version préédente du plugin (< 2.7.0) ?

Note : dans GLPI version 9.4 le texte est toujours enrichi.

**Comment by Lau65rent** [comment]
Le formulaire a été crée avec la version 2.7.0
Voici la génération du ticket à la place du ##FULLFORM##
![Capture](https://user-images.githubusercontent.com/31002694/54541841-f7a3a900-499a-11e9-9d4b-69337ef5cc6d.JPG)

**Comment by btry** [comment]
je vais essayer avec un modèlede ce  genre, et peut être faire tuer le lapin par le chasseur (on ne sait jamais)

**Comment by Lau65rent** [comment]
J'ai suivi ce topic
https://github.com/pluginsGLPI/formcreator/issues/1139

puis la solution
https://github.com/pluginsGLPI/formcreator/pull/1178/files

mais je trouve pas aucun des fichiers dans les répertoires...

**Comment by btry** [comment]
le patch a été fusioinné pour la version 2.6.5 du plugin, mais à aprtir de la version 2.7.0, j'ai complètment réécrit le code gérant le rendu des tickets car c'était source de problèmes permanents. Ce patch est donc obsolète et non applicable de nouveau à cause des changments importants dans le code.

**Comment by Lau65rent** [comment]
Ha ok (je venais de trouver les fichiers...)

**Comment by Lau65rent** [comment]
Bonjour,

Vous avez pu reproduire le problème?

**Comment by btry** [comment]
Bonjour

Avec un ticket spécifiant explicitement la réponse de la question zone de texte, je reproduis.

**Comment by btry** [comment]
Bonjour

J'ai compris le problème.

Dans votre modèle de ticket vous avez certainement le tag ##answer_xx## entouré par des balises <code> et </code>

Ca peut arriver si vous coipiez / collez la balise à partir de la liste présentée en bas des paramètres du ticket cible. Enlevez ces  balises et le rendu sera correct.

**Comment by Lau65rent** [comment]
Je viens de faire un test vous avez raison

il aime pas mon code html pour le ##anwser_80##

<span style="color: #ff9900; line-height: small; font-size: small;"> ##answer_80##</span>

Par contre lors de la validation du code il rajoute automatiquement <p> </p>

**Comment by btry** [comment]
oui, mais les balises P que vous voyez proviennent des retours à la ligne dans le texte saisi. et ce sont ces balises qui deviennent visibles.

**Comment by Lau65rent** [comment]
OK.
Du coup pas de mise en forme possible pour les réponses du champs Zone de Texte.

Je crois bien que le chasseur vient de tuer le lapin ;)

**Comment by btry** [comment]
J'ai édité mon commentaire p récédent car il était mal interprété par github. e ce que j'ai observé, le souci venait d'une balise CODE. et le texte était à l'intérieur d'une TABLE. Essayez de mettre de la mise en forme, mais attention à bien relire le HTML généré pour éviter la présence de ces balises CODE. Ce sont elles qui désactivent l'interprétation des autrs balises imbriquées dedans.

**Comment by Lau65rent** [comment]
Le problème c'est qu'il rajoute systématiquement les <p> et </p> automatiquement dès que l'on clique sur OK dans le code source

**Comment by btry** [comment]
Je fais un essai, les balises P apparaisent bien dans le template (car elles matérialisent les paragraphes)

mais ces balises n'apparaissent pas dans le ticket généré

![image](https://user-images.githubusercontent.com/14139801/55557799-effa3900-56ea-11e9-811c-63ee4df29433.png)

le chasseur s'est tiré une balle dans le pied !
![image](https://user-images.githubusercontent.com/14139801/55557773-dfe25980-56ea-11e9-9325-822106da7c49.png)

**Comment by Lau65rent** [comment]
Ok pour ça, j'ai le même résultat.
Mais si vous mettez en forme le ##answer_XX## juste vous changer la couleur d'écriture, dans le ticket généré il va mettre les balises

**Comment by btry** [comment]
Pouvez-vous comparer cet afichage avec l'onglet principal du ticket ? 

J'ai remarqué que les balises P n'apparaissent pas quand on lit le texte vie l'onglet principal.

Je soupçonne un bug côté GLPI

**Comment by Lau65rent** [comment]
Bonjour,

Sur l'onglet principal, les balises P n'apparaissent pas.

**Comment by btry** [comment]
Le souci se situe dans le code de nettoyage du HTML côté GLPI, via une livrairie tierce. 

Je pense que l'imbrication de balises P dans des balisesSPAN (ou P) est détecté et ces balises sont converties en texte. Je ne vois pas trop ce que je peux faire sans me lancer dans des traitements lourds sur le code HTML généré par le plugin. 

En effet,  le code HTML du ticket cible (texte riche) et le code HTML de la réponse saisie dans une zone de texte  sont automatiquement imbriqués. Et comme une nouvelle ligne génère une balise P on se retrouve avec des imbrications inutiles de balises de type bloc (P dans P par exemple).

Je pense que pour le moment, il vaut mieux chercher à contourner cette contrainte, peut être qu'en éditant le code HTML au noveau de l'objet cible on peut éviter ces imbrications indésirables.

**Comment by Lau65rent** [comment]
Merci  pour le retour,

Je fais voir comment faire.

**Comment by btry** [comment]
Bonjour

Ce ticket est obsolète (et devrait avoir été résolu). Je ferme.
