### ISSUE TITLE
 Attached Documents

### ISSUE THREAD

**Issue by tlsz1** [pluginsGLPI/formcreator#1358]
bonjour,
quand sur mon formulaire j'upload un document (souvent un csv), et à la génération du ticket je ne le vois pas (normalement il devrait être dans traitement du ticket) mais ce csv est bien présent dans "gestion" "document"

ce bug est venu post migration (9.11 => 9.4) j'ai testé avec formC 2.7 et 2.8 meme bug.

une idée?

merci beaucoup!

**Comment by btry** [comment]
Pouvez vous essayer d'uploader 2 fois le même document dans le même champ fichier ?

**Comment by tlsz1** [comment]
non, toujours rien.

**Comment by btry** [comment]
Voyez si vous avez des erreurs php et sql dans les logs de GLPI

**Comment by tlsz1** [comment]
[2019-03-13 15:19:50] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\glpi\inc\dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS `cpt` FROM (SELECT DISTINCT
                  NULL                           AS `id`,
                  CONCAT('f_',`fanswer`.`id`)    AS `display_id`,
                  `fanswer`.`id`                 AS `original_id`,
                  'PluginFormcreatorFormAnswer'  AS `sub_itemtype`,
                  `f`.`name`                     AS `name`,
                  `fanswer`.`status`             AS `status`,
                  `fanswer`.`request_date`       AS `date_creation`,
                  `fanswer`.`request_date`       AS `date_mod`,
                  `fanswer`.`entities_id`        AS `entities_id`,
                  `fanswer`.`is_recursive`       AS `is_recursive`,
                  `fanswer`.`requester_id`       AS `requester_id`,
                  `fanswer`.`users_id_validator` AS `validator_id`,
                  `fanswer`.`comment`            AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `fanswer`.`is_deleted` = '0'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  CONCAT('t_',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  'Ticket'                      AS `sub_itemtype`,
                  `tic`.`name`                  AS `name`,
                  `tic`.`status`                AS `status`,
                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tic`.`users_id_recipient`    AS `requester_id`,
                  0                             AS `validator_id`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
  Error: Champ 'fanswer.is_deleted' inconnu dans where clause
  Backtrace :
  plugins\formcreator\inc\issue.class.php:125        
  :                                                  PluginFormcreatorIssue::cronSyncIssues()
  inc\crontask.class.php:829                         call_user_func()
  front\cron.php:83                                  CronTask::launch()
  {"user":"@SOM"} 
[2019-03-14 17:15:26] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\glpi\inc\dbmysql.class.php line 177
  *** MySQL query error:
  SQL: INSERT INTO `glpi_groups_tickets` (`groups_id`, `type`, `tickets_id`) VALUES ('199', '2', '8249')
  Error: Duplicata du champ '8249-2-199' pour la clef 'unicity'
  Backtrace :
  inc\dbmysql.class.php:821                          
  inc\commondbtm.class.php:658                       DBmysql->insert()
  inc\commondbtm.class.php:1140                      CommonDBTM->addToDB()
  inc\commonitilobject.class.php:842                 CommonDBTM->add()
  inc\ticket.class.php:1316                          CommonITILObject->prepareInputForUpdate()
  inc\commondbtm.class.php:1362                      Ticket->prepareInputForUpdate()
  front\ticket.form.php:72                           CommonDBTM->update()
  {"user":"6@SOM"}

**Comment by btry** [comment]
Non, cette erreur est un autre souci (le patch attend la prochaine release d'ailleurs).

Je n'ai pas reproduit jusqu'à maintenant. Vosu reproduisez systématiquement ou cela arrive-t-il de temps en temps ?

Autre chose, l'utilisateur qui remplit la demande a-t-il l'habitude de travailler avec plusieurs onglets du navitageur ouverts sur GLPI ?

**Comment by tlsz1** [comment]
-une date pour la prochaine release?
-cela arrive à chaque fois.
-non, j'ai un intranet, avec des liens, l'utilisateur clic sur le lien et arrive direct sur le formulaire.
http://glpi.x.x/glpi/plugins/formcreator/front/formdisplay.php?id=6

**Comment by btry** [comment]
la prochaine release sera livrée ... quand elle sera prête :) 

Ce bug étant très impactant, je compte l'inclure.

**Comment by btry** [comment]
Votre formulaire est il soumis à validation ?

**Comment by tlsz1** [comment]
vivement qu'elle soit dispo :)
non, aucune validation.

**Comment by btry** [comment]
possible duplicate witrh #1367

**Comment by btry** [comment]
Hi

Please test the above patch and feedback. Files should no longer be lost now.

The loss occurs un the following scenario
- requester opens a form
- requester uploads a file in a file field
- requester clicks or edits an other field
- the update triggers request to the server for visibility update of each field
- file field processes the uploaded file, converts it into a Document in GLPI. The uploaded file is moved
- the requester validates the form
- the file field does not finds any file and considers there are no file to convert into Document

**Comment by btry** [comment]
Hi

I received today a positive feedback for the patch. Closing. The patch will be included in the version 2.8.2.
