### ISSUE TITLE
[2.8] Html tags inserted in change destination fields

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#1359]
Hi,

**To reproduce**
1. Create a form with a textarea field;
2. Add a change destination;
3. Configure impact field to sign the form answer. Save the form destination.
4. Run the form inserting multiples lines. 
5. In the change ticket, the impact field shows some html tags.

**Screenshot**

1. Form
![Captura de tela de 2019-03-18 13-50-49](https://user-images.githubusercontent.com/26510405/54548464-be613e00-4986-11e9-85c0-53a68582572c.png)

2. Destination field
![Captura de tela de 2019-03-18 13-52-43](https://user-images.githubusercontent.com/26510405/54548461-be613e00-4986-11e9-9b8e-d7f85d8a7026.png)

3. Impact field (change ticket)
![Captura de tela de 2019-03-18 13-51-55](https://user-images.githubusercontent.com/26510405/54548462-be613e00-4986-11e9-9189-07aa3b48d8f7.png)

Regards.

**Comment by btry** [comment]
Hi

Please try the latest version 2.8.2. With it, I don't reproduce. Don't forget to feedback.

**Comment by pedroluisvsousa** [comment]
Hi,
I tested versions 2.8.2 and 2.8.3. There is the same problem. Pleaser, see below.

![Screenshot_2019-08-10 GLPI - Changes - 3](https://user-images.githubusercontent.com/26510405/62820922-31d83780-bb42-11e9-912f-735ba3c09941.png)

**Comment by btry** [comment]
Hi

In my investigations I found the bug occurs with 2.8.x and future 2.9 versions.

In this case there is a rich contect which must be converted back to simple text. I think I'll need to add a new dependency to do the job properly. I selected the following library: https://github.com/mtibben/html2text .

I need to verify if GLPI does provide an equivalent feature before starting a fix.

**Comment by btry** [comment]
- GLPI has a method to convert from HTML to text... but it does not handle UL and OL tags.

- The library I selected seems no longer actively maintanied, then I need to find a viable alternative.

- maybe this issue may be properly fixed in a future version of GLPI by adding support for rich text in all fields of changes (it seems to me simpler and more consistent way to solve the issue). I need to submit the idea to the GLPI team.

**Comment by btry** [comment]
Hi

I close this issue as it is obsolete. Feel free to open a new one if this still ocurs with Formcreator 2.10.1 or later
