### ISSUE TITLE
Form appear on home page even I select "no" in Direct access on homepage field

### ISSUE THREAD

**Issue by jotafe** [pluginsGLPI/formcreator#136]
Form appear on home page even I select **No** in Direct access on homepage menu.
They only not apper if I select one profile in **Target > Restrict Access**.

**Comment by neeftarah** [comment]
Hi,

This should not be the case. I re-tested this and don't find your error.

Can you give me more details please (glpi version, formcreator version, example of configuration,etc.)?

Regards.

**Comment by neeftarah** [comment]
NB : tested and not reproduced on GLPI 0.90 + Formcreator 0.90-1.2.5

**Comment by jotafe** [comment]
Hello Jérémy, 
GLPI 0.85.4 and 0.90
Formcreator 0.90-1.2.5
Server Debian

**Comment by neeftarah** [comment]
OK,

Can you confirm you still have the bug ?
And if yes, can you join screenshot of your homepage and the configuration page of forms that should not be on homepage ?

**Comment by jotafe** [comment]
![form2](https://cloud.githubusercontent.com/assets/15238629/10756871/f8752d3c-7c8d-11e5-9e75-8a8895dbef56.png)
![form1](https://cloud.githubusercontent.com/assets/15238629/10756870/f871d5d8-7c8d-11e5-9b97-3207e0e99f3c.png)

**Comment by neeftarah** [comment]
OK, I'm sorry I didn't remember, but it has already been fixed in master branch and for next release (Issue #125 in French).

You can see the solution commit here : 42f6501

Best regards,
Jérémy MOREAU

**Comment by jotafe** [comment]
Thank you for your quicly support.
And congrats for your idea, its a great plugin,
Have a nice week
