### ISSUE TITLE
Fresh Install error "Multiple primary key defined"

### ISSUE THREAD

**Issue by GitDer** [pluginsGLPI/formcreator#1360]
I'm trying to install version 2.8.0 of Form Creator on GLPI 9.3.3 and get the following error : 

`Changement de la structure de la base de données - glpi_plugin_formcreator_forms_profiles (1 seconde)

2.8.0 multiple alter in glpi_plugin_formcreator_forms_profiles - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_forms_profiles` CHANGE `plugin_formcreator_profiles_id` `profiles_id` INT(11) NOT NULL DEFAULT '0' , ADD `id` INT(11) NOT NULL AUTO_INCREMENT , ADD PRIMARY KEY `id` (`id`) , ADD UNIQUE KEY `unicity` (`plugin_formcreator_forms_id`, `profiles_id`) , ADD `uuid` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL - L'erreur est Multiple primary key defined`

**Comment by btry** [comment]
Bonjour,

Vous dites que vous faites une installation, mais l'erreur indique qu'il s'agit d'un upgrade. Pouvez vous éclaricir la situation ?

Il devrait y avoir un backtrace dans glpi/files/_logs/migratoin_to_2.8.0.log. Pouvez-vous le partager ?

**Comment by GitDer** [comment]
Bonjour,

Effectivement je n'avais pas suffisamment prêté attention...
Je viens de contrôler la base SQL avant ajout du module et il y'a déjà des tables glpi_plugin_formcreator_* existante.
Donc ce module avait déjà du être installé puis supprimé par le passés (sans doute incorrectement).
Je viens de faire un drop manuel des tables et de relancer l'installation du module qui c'est déroulée sans problème.
Navré pour le dérangement et merci du retour rapide.
