### ISSUE TITLE
Perda de formatação de texto quando aberto um formulario

### ISSUE THREAD

**Issue by dboscaini** [pluginsGLPI/formcreator#1361]
Quando abro um chamado via formcreator com formatação rich text o mesmo não é replicado no chamado aberto

Exemplo
Criação do chamado
![image](https://user-images.githubusercontent.com/35369423/54689672-bf1ce000-4afe-11e9-8a10-864e395d0ff7.png)

Chamado aberto
![image](https://user-images.githubusercontent.com/35369423/54689542-8250e900-4afe-11e9-9db8-472700e328f1.png)

GLPI Versão 9.1.2
formcreator 2.5.2

**Comment by btry** [comment]
Hi

Please translate your request into english : I don't understand Portuguese.

**Comment by dboscaini** [comment]
When I open a call via formcreator with rich text formatting it is not replicated in the open ticket

Example
Creation of the ticket
![image](https://user-images.githubusercontent.com/35369423/54692428-ca263f00-4b03-11e9-8e1e-012f28f88564.png)

Open ticket
![image](https://user-images.githubusercontent.com/35369423/54692459-d5796a80-4b03-11e9-9c92-84b04f6a76e1.png)

GLPI Version 9.1.2
formcreator version 2.5.2

**Comment by btry** [comment]
Can you consider upgrading GLPI and Formcreator to the latests versions ? Formcreator 2.5.2 is old and no longer maintained. Theire are chances that your issue is already fixed in the recent releases.

**Comment by dboscaini** [comment]
Unfortunately I can not update because it was customized, it would have several problems, I found a similar problem, I just could not apply it to my version.
https://github.com/pluginsGLPI/formcreator/pull/730

**Comment by btry** [comment]
You should try on a testing environment to upgrade GLPI to at least 9.3.3 and Formcreator 2.8.0.

I worked a lot to fix recurrent problems with ticket rendering (backslashes, new lines, html vs plain text...)

The result is very satisfying : nearly all issue are solved, ant the few we found so far are easily solved without risk of regression. I think that your patches are now obsolete.

**Comment by dboscaini** [comment]
I upgrade the version and solved this problem
