### ISSUE TITLE
Specification / Documentation file format (JSON)

### ISSUE THREAD

**Issue by ajsb85** [pluginsGLPI/formcreator#1362]
Hi, @btry 

I want to help with the documentation of the specification for the file format in JSON.

Regards.

**Comment by btry** [comment]
Hi

You can use a JSON sample, and see how it is organized. The keys use the usual GLPI convention : 
key beginning with an underscore is somewhat virtual and is most often an object contained in the parent object in the JSON. Other keys match columns in the table of the object in DB. 

Other questions ? just ask.
