### ISSUE TITLE
BUG - Cache Browser

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1363]
He was in a strange situation.

When checking "remember password", quit the browser and open again, the glpi takes about 4 minutes to load the home screen. If I access in an anonymous tab access is normally done. I think you're saving some cache. Does anyone know what can it be?

It follows the error log from the first access (where the bug occurs) to the correct access.

this situation occurs in any browser

1 STEP - Open Browser , login in GLPI and mark "Remender password"
2 STEP - Close Brownser
3 STEP - Open Brownser
4 STEP - Access GLPI

My GLPI version: 9.3.3
formcreator version: 2.8.0 (and 2.6.5)
PHP 7.3.3

Log: 

![erro](https://user-images.githubusercontent.com/35368369/54712856-1c7b5600-4b2c-11e9-9d2a-0f5fb8bd8ab1.PNG)

**Comment by btry** [comment]
Hi

Can you disable the plugin then try to reproduce again ?

**Comment by phamorais** [comment]
Hi @btry 

with it disabled, also happens. I believe, maybe it's in GLPI and not in the correct plugin?

**Comment by btry** [comment]
Hi,

Yes, it seems that it is relatés to GLPI only. But the issue light come from your mysal server. Try to restart it and see if the problem persists. 

Also, check if you have crashed tables.

**Comment by btry** [comment]
As the issue is not repated to Formcreator, I close. 

You may consider getting help from the community https://forum.glpi-project.org/
 or get professional support : https://services.glpi-network.com/#offers

**Comment by phamorais** [comment]
OK.
