### ISSUE TITLE
server refused to connect

### ISSUE THREAD

**Issue by kiayunan** [pluginsGLPI/formcreator#1365]
![image](https://user-images.githubusercontent.com/42923102/54730752-27ca9200-4bbd-11e9-923c-9fca4c5a0f77.png)

![Screenshot_1](https://user-images.githubusercontent.com/42923102/54731720-6e6ebb00-4bc2-11e9-973a-d4ee6dc5a744.png)

![image](https://user-images.githubusercontent.com/42923102/54732626-5fd6d280-4bc7-11e9-8ec5-6faedcf08797.png)

why i can't add the default value, it tells refused to connect?

here's my sql-errors.log

[2019-03-20 18:02:58] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 180
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS `cpt` FROM (SELECT DISTINCT
                  NULL                           AS `id`,
                  CONCAT('f_',`fanswer`.`id`)    AS `display_id`,
                  `fanswer`.`id`                 AS `original_id`,
                  'PluginFormcreatorFormAnswer'  AS `sub_itemtype`,
                  `f`.`name`                     AS `name`,
                  `fanswer`.`status`             AS `status`,
                  `fanswer`.`request_date`       AS `date_creation`,
                  `fanswer`.`request_date`       AS `date_mod`,
                  `fanswer`.`entities_id`        AS `entities_id`,
                  `fanswer`.`is_recursive`       AS `is_recursive`,
                  `fanswer`.`requester_id`       AS `requester_id`,
                  `fanswer`.`users_id_validator` AS `validator_id`,
                  `fanswer`.`comment`            AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `fanswer`.`is_deleted` = '0'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  CONCAT('t_',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  'Ticket'                      AS `sub_itemtype`,
                  `tic`.`name`                  AS `name`,
                  `tic`.`status`                AS `status`,
                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tic`.`users_id_recipient`    AS `requester_id`,
                  0                             AS `validator_id`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
  Error: Unknown column 'fanswer.is_deleted' in 'where clause'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:125        
  plugins/formcreator/install/install.php:86         PluginFormcreatorIssue::cronSyncIssues()
  plugins/formcreator/hook.php:48                    PluginFormcreatorInstall->install()
  inc/plugin.class.php:701                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"2@glpi-virtual-machine"}

**Comment by btry** [comment]
Hi

the SQL error has a PR #1355, waiting for feedback before merge. Try it, and feel free to feedback.

Your errors in the browser are more likely related to yout browser. Maybe this link will help https://stackoverflow.com/questions/29855651/alternate-stylesheets-not-working-in-chrome

**Comment by kiayunan** [comment]
can you give another solution, it doesn't work, I,ve try with another browser too and it doesn't work either, thank you

**Comment by btry** [comment]
The solution I gave was about the SQL error, which is not related to the issue you described. 

Can you tell the version of your browsers ?

**Comment by kiayunan** [comment]
Google Chrome

Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by kiayunan** [comment]
i'm finally fix it, https://serverfault.com/questions/611285/x-frame-options 

thank you for your support
