### ISSUE TITLE
Form does not insert attachments in ticket

### ISSUE THREAD

**Issue by dboscaini** [pluginsGLPI/formcreator#1367]
I have GLPI 9.4.4.1 and formcreator 2.80 and when I try to open a ticket through the form the attachment is not included, I ran some tests and the attachment is included only when there is only the files field, if any other add the ticket is opened without the file.

example dont attach
![image](https://user-images.githubusercontent.com/35369423/54838258-e4e4e900-4ca6-11e9-95bf-c29a261af367.png)
![image](https://user-images.githubusercontent.com/35369423/54838211-d39bdc80-4ca6-11e9-9be4-1cde3c5ec9cc.png)

example attach
![image](https://user-images.githubusercontent.com/35369423/54838275-f3330500-4ca6-11e9-91aa-b4181e4ab99f.png)
![image](https://user-images.githubusercontent.com/35369423/54838356-2c6b7500-4ca7-11e9-9785-58f4be67924b.png)

**Comment by btry** [comment]
Hi 

I have several reports about this issue. Your observation is interestiing, this might help me to solve it. Please stay tuned next week.

**Comment by btry** [comment]
Hi

I created 2 forms : one with a file field and an other with a textarea and a file field. Both wotks for me.

Could you export the 2 forms and send them to me ? Maybe there is an other difference which is important to trigger the bug.

**Comment by dboscaini** [comment]
I discovered another detail, the error occurs only when I move the field ... for example ... if I just create the attachment field it works, if I move it to another position it stops working ... it follows export from the pre and after move

[erro anexo.zip](https://github.com/pluginsGLPI/formcreator/files/3003035/erro.anexo.zip)

**Comment by btry** [comment]
Where do you do this move : in the target ticket, or when you reorder the questions of the form ?

**Comment by dboscaini** [comment]
when I reorder the questions of the form

![image](https://user-images.githubusercontent.com/35369423/54919591-f49b4200-4edf-11e9-8da1-63a029a9328b.png)

**Comment by btry** [comment]
I still don't reproduce : I imported the version of your form before the move, tested it, then moved the file field before the urgency question, and tested it again. I still have the uploaded file in the generated ticket.

**Comment by btry** [comment]
If you have a testing instance of GLPI, could you try the current develop branch of  the plugin and feedback if the bug still occurs ?

**Comment by dboscaini** [comment]
Unfortunately I do not currently have a testing GLPI, by the time I resolved not moving the field. One more information that might help is that I'm coming from another version, it was in GLPI 9.2.1 and I went to 9.4.4.1, and the formcreator was in 2.5.2 and I went to 2.8.0. I got many bugs in this migration, it could have been caused by this.

**Comment by btry** [comment]
By checking the source code or trying to reproduce in various ways, there is nothing obvious yet.

Could you identify 2 answers for the form 
- one which worked fine,
- another which failed to add the uploaded tile in the target ticket
Lets call them **faID1** and **faID2**

Take note of  the ID of both.

Next, in the table glpi_plugin_formcreator_form_questions, find the row matching the file question of the form, and take note if its ID. Lets call it **qID**

In the table  glpi_plugin_formcreator_answers you whould find 2 rows : 
- one for the working form answer
- an other for the failed one

select * from glpi_plugin_formcreator_answers where plugin_formcreator_formanswers_id in ( faID1, faID2 ) AND plugin_formcreator_questions_id = qid

I want to compare the value of the column **answer** for the returned rows.

**Comment by dboscaini** [comment]
The form ID OK (faID1) is 13
The question file of faID1 is 169
The answer OK is 47

![image](https://user-images.githubusercontent.com/35369423/54934225-e7408080-4efc-11e9-8252-560ec25484cf.png)

The form ID NotOK (faID2) is 25
The question file of faID2 is 181
The anwser nOK is 47

![image](https://user-images.githubusercontent.com/35369423/54934280-ff180480-4efc-11e9-9f48-8c7657ae2d39.png)

If i run de query selecting only the questions 169 exist, 181 dont exist
![image](https://user-images.githubusercontent.com/35369423/54935225-a0ec2100-4efe-11e9-80cc-7fd24fedf539.png)

**Comment by btry** [comment]
Hi

The row with the foreign key = 181 exists in your screenshot. It is the 3rd line starting from the bottom. However, the column "answer" contains [] which means that no document was taken into account while saving answers. I think the issue is here : the document is uploaded but ignored by the plugin for some reason.

**Comment by dboscaini** [comment]
Sorry, I had not seen the 181, I believe it is uploaded, because at the opening of the call it is shown that the file has been moved successfully.

![image](https://user-images.githubusercontent.com/35369423/54991531-eca0d800-4f9b-11e9-8929-0034150fda23.png)

**Comment by btry** [comment]
Hi

when you reproduce the bug, do you confirm t hat the file is added in the documents of GLPI and you can download it ? (in Management > Documents)

**Comment by btry** [comment]
Hi

Please test the above patch and feedback. Files should no longer be lost now.

The loss occurs in the following scenario
- requester opens a form
- requester uploads a file in a file field
- requester clicks or edits an other field
- the update triggers request to the server for visibility update of each field
- file field processes the uploaded file, converts it into a Document in GLPI. The uploaded file is moved
- the requester validates the form
- the file field does not finds any file and considers there are no file to convert into Document
