### ISSUE TITLE
simple service catalog dont show old tickets

### ISSUE THREAD

**Issue by dboscaini** [pluginsGLPI/formcreator#1369]
When I enable the simple service catalog the old tickets donts show.. how repair?

![image](https://user-images.githubusercontent.com/35369423/54846870-9d1c8c80-4cbb-11e9-963a-6964e2c1081a.png)

![image](https://user-images.githubusercontent.com/35369423/54846890-aad21200-4cbb-11e9-9daa-6443deae8f51.png)

**Comment by dboscaini** [comment]
Other exemple
![image](https://user-images.githubusercontent.com/35369423/54848972-84af7080-4cc1-11e9-9d10-9ca56fb89b69.png)


![image](https://user-images.githubusercontent.com/35369423/54848736-e7543c80-4cc0-11e9-8891-b4957813e937.png)

**Comment by dboscaini** [comment]
i reinstall de plugin and works, this occour because the older version.

**Comment by btry** [comment]
Hi 

The issue is probably caused by a SQL error, fixed with this patch: https://github.com/pluginsGLPI/formcreator/pull/1355

Can you check in your sql-errors.logs ?
