### ISSUE TITLE
Pas d'affichage du nombre de traitement du ticket sous Firefox V0.90-1.2.5

### ISSUE THREAD

**Issue by CHCI74** [pluginsGLPI/formcreator#137]
Bonjour,
Sur firefox v38.2.1 dnas l'onglet "Traitement du ticket", le nombre d'actions n'apparaît pas alors qu'il apparaît sur IE11.
Voir pièces joints
![affichage firefox](https://cloud.githubusercontent.com/assets/12545704/10790917/4107629c-7d86-11e5-80ee-227be64ce3ba.JPG)
![affichage ie](https://cloud.githubusercontent.com/assets/12545704/10790916/41029442-7d86-11e5-8756-c378aa237f00.JPG)

**Comment by neeftarah** [comment]
Bonjour,

Ce bug ne semble pas venir spécifiquement de Formcreator mais plutôt de GLPI.
Je vous suggère de faire votre demande sur le forum de GLPI : http://forum.glpi-project.org/

Cordialement,
Jérémy
