### ISSUE TITLE
Mixed default value on dropdown

### ISSUE THREAD

**Issue by kiayunan** [pluginsGLPI/formcreator#1372]
I want to make a questions with dropdown, i'm using form categories's dropdown, then i'm adding the default value. when i'm review my form at preview my default value on question 1 it shows too on question 2, how can i make the default value on question 1 and question 2 separated?

**Comment by btry** [comment]
Hi

Are you using the last release 2.8.0 ? Can you show the settings of your 2 dropdowns questions ?

**Comment by kiayunan** [comment]
yes i'm using release 2.8.0 and i'm using glpi 9.3.0

here's my settings for my drop downs questions

![Screenshot_6](https://user-images.githubusercontent.com/42923102/55316353-65220000-5498-11e9-9466-70610f33afd4.png)

at question 1 i just need _kebersihan_and the child's of _kebersihan_

![Screenshot_7](https://user-images.githubusercontent.com/42923102/55316381-7703a300-5498-11e9-99fe-054cda79aac5.png)

at question 2 i just need toilet

![Screenshot_8](https://user-images.githubusercontent.com/42923102/55316383-779c3980-5498-11e9-8418-f8b5bddbe1b1.png)

![Screenshot_10](https://user-images.githubusercontent.com/42923102/55316534-d366c280-5498-11e9-86f1-c191982485a7.png)
![Screenshot_11](https://user-images.githubusercontent.com/42923102/55316535-d3ff5900-5498-11e9-893d-b4a1ee5cd15d.png)

here's my preview, that my dropdown isn't seperated

![Screenshot_12](https://user-images.githubusercontent.com/42923102/55316568-e4173880-5498-11e9-9ecc-dad834457d4c.png)
![Screenshot_13](https://user-images.githubusercontent.com/42923102/55316570-e4173880-5498-11e9-8a56-95797deea9a9.png)

here's my form creator's dropdowns looks like 
![Screenshot_14](https://user-images.githubusercontent.com/42923102/55316648-132daa00-5499-11e9-8fe2-f8d242f2ec7c.png)

I hope you can help me, thank you

**Comment by btry** [comment]
OK, I understand your question now.

The default value is a value pre-selected when the plugin displays a form to a requester. It will not restrict the available values.

Currently there is no feature to restrict the values avaialble for a dropdown, Development is needed to add the feature. 

If you need it quickly you may consider to contact us : contac@teclib.com

**Comment by kiayunan** [comment]
But, I've tried with another glpi and it works, it can separate my drop-down in the form creator's dropdowns but when i tried in my production's server in won't work

**Comment by btry** [comment]
How did you duplicate the form from the other GLPI to the production server ?

**Comment by kiayunan** [comment]
That's the problem when i export my form from another glpi and try it on production server i the drop-down is still mixed

**Comment by btry** [comment]
Both questions use Form categories dropdown as their source. This is normal that they show the same set of options.

If there is a bug, it is not on your production but on the other GLPI instance.

**Comment by kiayunan** [comment]
Thank you for your information its very helpful

**Comment by btry** [comment]
Did you find the cause of the difference of behaviour ? What was it ?

**Comment by kiayunan** [comment]
I don't know what makes the different, when I try in my server for trial it works, it can separate form creator's dropdown, maybe you can make feature like that?

**Comment by btry** [comment]
The best would be to add options similar to ticket categories.

Have a look on a test form : you should be able to choose a subtree root, and a maximum depth. Generalizing this feature to all tree dropdowns should be nice, and should satisfy your need.
