### ISSUE TITLE
Plusieur valideur requise 

### ISSUE THREAD

**Issue by ykasdi** [pluginsGLPI/formcreator#1375]
Bonjour, 
est ce qu'il y a la possibilité de mettre plusieurs valideurs dans un formulaire 
par exemple : il faut valider le formulaire par plusieurs personnes avant de créer un ticket) 
Merci

**Comment by btry** [comment]
Bonjour

A ce jour, il suffit qu'un valudeur valide les réponses pour que la génération des tickets / changment se lance. La  validation multiple n'est pas possible.

**Comment by btry** [comment]
Bonjour,

Sans réaction de votre part je suppose que la question est close.
