### ISSUE TITLE
duplication de formulaire

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1377]
Bonjour,
en voulant dupliquer un formulaire via les actions en masse, si mon formulaire est bien dupliqué (Formulaires, cibles), une seule question (la première) est dupliquée ; les autres ne le sont pas.

N'ayant pas de destinations configurées pour le moment, je ne sais pas si cette partie est dupliquée ou pas.

**Comment by Sicoval31** [comment]
problème existant sur glpi 9.3.1 et plugin 2.6.4
inexistant en glpi 9.4.1 et plugin 2.8

**Comment by btry** [comment]
Si un formulaire n'est pas entièrement dupliqué c'eest qu'il y a une erreur pendant la duplication. Malheureusement il n'y a aps encore de transaction possible au niveau de la BDD, ce qui fait que le plugin ne peut pas annuler le début d'une duplication échouée.

Si le bug n'apaprait plus en 2.8.0, on peut clore. La version 2.6 n'est plus maintenue.

**Comment by btry** [comment]
Bonjour

Sans retour de votre part, je sppose que le sujet peut être clos.
