### ISSUE TITLE
Change the default language issue

### ISSUE THREAD

**Issue by salgueirosa** [pluginsGLPI/formcreator#138]
Dear,

I´m trying to change de default language from formcreator to pt_BR.
Already try to translate the mail confirmations also for request / deny, also for other mail informations, without sucess.
The procedure was:

- Write the texts directly to locales/pt_BR.po;
- Write the texts directly to locales/en_GB.po;
- Write the texts directly to inc/notificationtargetformanswer.class.php
Without sucess.
Can you please help me in inform the correct procedure to change the langs?

Thanks in advance,

**Comment by neeftarah** [comment]
Hi,

The ".po" files are just "source code" files witch needs to be compiled into ".mo" files (directly in command line or with a tool like PoEdit).

However, for notifications, these files are only needed on plugin installation. You can translate your e-mails directly from GLPI's interface : Setup > Notification > Notification templates.
Each template may have several languages : One default translation with is used for every non-translated languages, and one translation per language.

Best regards,
Jérémy
