### ISSUE TITLE
Set icon for form

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#1380]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We would like to be able to set the icon or upload that will be visible in the user interface for forms.
Example: A form for filing an incident on a computer.

![example](https://user-images.githubusercontent.com/47602797/55786753-27832f80-5ab5-11e9-88bc-85dc859cced8.png)

**Describe alternatives you've considered**
Maybe use font-awesome

**Comment by btry** [comment]
Hi

Similar feature implemented in the future 2.9.0. You may select a font awesome pictogram, and set its color. You cal also set the background color of the tile.
