### ISSUE TITLE
Mes demandes d'assistance : listing des demandes où l'on est demandeur (et non rédacteur)

### ISSUE THREAD

**Issue by cmonnet76** [pluginsGLPI/formcreator#1381]
Bonjour,

Nous utilisons GLPI 9.4.1.1 avec FormCreator 2.8.0.
Nous forçons l'usage du "Catalogue de service simplifié" pour nos "clients", mais nos techniciens eux, pour créer un ticket, utilisent les forms GLPI classiques pour avoir accès à tous les champs des tickets.

Le problème que l'on rencontre se produit quand un technicien fait un ticket "à la place" d'un client. Le technicien est donc le rédacteur du ticket, mais il indique comme demandeur : le client.

Or, ce ticket n'apparait pas dans la liste "Mes demandes d'assistance" du client.
En effet, dans cette liste, on voit les tickets pour lesquels on est rédacteur (et non pas demandeur).
NB: D'ailleurs la colonne "Demandeur" n'affiche pas le nom du demandeur, mais celui du rédacteur.

Serait-il possible que la partie "Mes demandes d'assistance" liste bien les tickets pour lesquels on est demandeur (et non rédacteur) ?
Ou, du moins, qu'on ait la possibilité de choisir entre l'un ou l'autre affichage ?

Merci d'avance.
Christine

**Comment by btry** [comment]
Bonjour

Le patch ci dessus devrait résoudre le problème. Utilisez un environnement de test pour vérifier qu'il fonctionne bien, et n'oubliez pas de vider la table issues du plugin et lancer son action automatique  pour rafraichir la table avec les données corrigées.

**Comment by btry** [comment]
Bonjout @cmonnet76 

Avez vous pu essayer le patch ?

**Comment by cmonnet76** [comment]
Bonjour,

Désolée, j'étais en congé jusqu'à hier.
Merci pour vos réponses. 
Je viens de tester le patch, mais désormais ma colonne "Demandeur" est vide (dans la table "glpi_plugin_formcreator_issues" pratiquement toutes mes valeurs "requester_id" sont à 0).

Peut-être m'y suis-je mal pris ?
Ce que j'ai fait :
`wget https://github.com/pluginsGLPI/formcreator/commit/26a898d66092e601426b9032e3aefdfcf0d52773.patch`
`cd <glpi-directory>/plugins/formcreator`
`patch -p1 < ../../../26a898d66092e601426b9032e3aefdfcf0d52773.patch`

Ensuite j'ai vidé la table 'glpi_plugin_formcreator_issues' et j'ai lancé l'action automatique 'SyncIssues'.

Je suis avec GLPI v9.4.2 et FormCreator 2.8.1.

Cordialement,

**Comment by btry** [comment]
Bonjour,

Votre procédure est bonne.

Je ne suis pas étonné que le patch ne fonctinne pas encore bien, car c'est un point assez délicat. Je cherche une mise à jour du patch...

**Comment by btry** [comment]
Bonjour

Je viens de faire des essais et le requsters_id est bien défini à l'id de l'utilsaiteur remplissant le formulaire.

Sur quelle version avez vous appliqué le patch ?

**Comment by btry** [comment]
J'ai amélioré le patch. En effet si on remplit un ticket GLPI (donc sans passer par un formulaire du plugin), la demande créée contient l'auteur du ticket, mais pas le demandeur.

Ca pourrait résoudre le souci, mais je me demande comment vous pouvez avoir 0 dans la colonne requester_id.

**Comment by cmonnet76** [comment]
Bonjour,
Nous utilisons désormais FormCreator 2.8.2.
Je viens de re-tester en procédant comme suit : 
```
cd <glpi-directory>/plugins/
rm -rf formcreator/
git clone -b develop https://github.com/pluginsGLPI/formcreator.git
```
Ensuite j'ai vidé la table 'glpi_plugin_formcreator_issues' et j'ai lancé l'action automatique 'SyncIssues'.
Résultat : 
1) Dans l'interface web, GLPI me propose de "nettoyer" le plugin, puis de le ré-activer (ce que je fais).
2) Dans la partie "Mes demandes d'assistance", je constate que dans la colonne "Demandeur" s'affiche toujours le nom du rédacteur et non pas celui du demandeur.

Je n'ai donc plus ce problème de "0" pour le requesters_id. Mais, ce n'est toujours pas la bonne valeur qui apparaît dans la colonne "Demandeur" du tableau.

Cordialement,

**Comment by btry** [comment]
Bonjour 

c'est normal : vous utilisez la branche develop du plugin et le patch est dans une branche sur mon fork. Le patch sera versé dans develop quand il sera satisfaisant.

Comme vous avez l'air de savoir utilsier git, ajoutez un remote à votre clone local vers mon fork https://github.com/btry/formcreator et faites un checkout de la branche contenant le patch. Vous trouverez son nom en consultant la page de sa PR.

**Comment by cmonnet76** [comment]
Merci pour votre aide.
J'ai donc fait : 
```
git remote add btry https://github.com/btry/formcreator
git fetch btry
git checkout btry/feature/1381_diff_requester_author
```
Puis, j'ai recommencé la procédure de nettoyage de la table 'glpi_plugin_formcreator_issues' + relance de 'SyncIssues'.
Du coup, je confirme que j'ai toujours le même soucis : tous mes requester_id sont mis à 0.

**Comment by btry** [comment]
Seules les demandes efectué&es avec le patch actif devraient être cocnernées. 

Il est peut être possible de corriger les anciennes demandes. Si le patch actuel donne de bons résultats alors je pourrai faire le nécessaire dans une phase d'upgrade du plugin.

**Comment by cmonnet76** [comment]
En faisant une demande, après avoir installé le patch, le champ requester_id n'est certes pas égal à 0 (mais semble contenir l'id du createur).
Via le web, je peux voir qu'il y a toujours un décalage entre : créateur et demandeur.
Voir captures d'écran ci-après : 
- https://framapic.org/IxBxoshjmLfr/Kn8N09btVpAb.png
- https://framapic.org/aTZjGwdmkrg2/HCC7nUhJzVKf.png
Cordialement,

**Comment by btry** [comment]
Pouvez vous exporter le formulaire pour que je fasse fonctionner sur mon environnement ?

**Comment by cmonnet76** [comment]
J'ai exporté mon formulaire : 
[export_formcreator_20190522_0740.zip](https://github.com/pluginsGLPI/formcreator/files/3206213/export_formcreator_20190522_0740.zip)
Est-ce bien ce fichier json que vous souhaitez tester ?

**Comment by btry** [comment]
Bonjour, 

Oui, ça semble correspondre, vu le nom du fichier dans le ZIP.

**Comment by willmx31** [comment]
Bonjour,
Je me permet de relancer ce sujet. Je constate aussi que le demandeur du ticket est en fait le créateur/rédacteur du ticket. Du coup le nombre de tickets n'est pas incrémenté.
Merci.

Version du plugin 2.8.3
Version GLPI : 9.4.3

**Comment by btry** [comment]
Bonjour

@cmonnet76 : en analysant le code et votre dernier retour, ile apparait que l'inchoérence réside dans le libellé.

Dans la capture ci dessous, le demandeur est en fait l'auteur de la demande. 

![image](https://user-images.githubusercontent.com/14139801/67109211-4edb5780-f1d0-11e9-9618-4c6943bab2cf.png)

Ce champ est assez important car il déternime les listes de demandes dans le catalogue de service. Je pense que le patch (que j'ai réactualisé pour la versin 2.9 en développement)^est au point, et que le souci restant est à traiter séparément.

**Comment by btry** [comment]
Bonjour

Le problème devrait être résolu avec cette version du correctif. Il a été validé par un autre utilsiateur.

https://github.com/btry/formcreator/tree/feature/1381_diff_requester_author
