### ISSUE TITLE
Menu fonts are too large

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1383]
I verify that the class used in the menu is not present in the styles file (styles.css) and this is causing a problem with the font size.
To fix the problem, I added the field below in the styles file (styles.css):

.label {
  display: inline;
  padding: .2em .6em .3em;
  font-size: 75%;
  font-weight: bold;
  line-height: 1;
  color: #fff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
}

**Comment by btry** [comment]
Hi @jvergacas 

Could you show a screenshot of the problem ? I'm not sure I get the point.

**Comment by jvergacas** [comment]
Hi @btry

I use GLPI 9.4.2

This is the screen without the inclusion of the style:
![2019-02-19 10_34_44-Window](https://user-images.githubusercontent.com/43650152/56809943-6fbb8500-680b-11e9-9c8c-05b469512c41.png)


This is with the style:
![2019-02-19 10_35_49-Window](https://user-images.githubusercontent.com/43650152/56809958-7c3fdd80-680b-11e9-9f47-5a4cbd35b0e9.png)

**Comment by btry** [comment]
Hi

Thank you for your feedback.

Indeed, there are some languages where the text is too long. Either we reduce the fond, either we increase width of the left area.

**Comment by jvergacas** [comment]
Hi,

Debugging the screen I realized that the HTML calls the ".label" style, but it is not in the style file and so I created it.

**Comment by btry** [comment]
We took a different approach because we don't wqant to reduce the font size.

I added a patch in the develop branch, but you can pick it for your copy of the plugin

https://github.com/pluginsGLPI/formcreator/commit/f1bc3907dd072709a2aca28b1ead5ea9a56f903b

**Comment by jvergacas** [comment]
This is also a good solution, in the next updates I can keep it.
Thank you.
