### ISSUE TITLE
Migration 2.8.0 -> 2.8.1 : Perte des valeurs d'affichage conditionnel ?

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1384]
Suite à migration de 2.8.0 vers 2.8.1, les valeurs d'affichage conditionnel ont disparu.
Voici comment se presente un champs : 
![image](https://user-images.githubusercontent.com/42341169/55945038-436c0a00-5c4a-11e9-9edd-63a419056110.png)

on a bien le type de conditionnement, mais pas la valeur.

Je l'ai refait sur une autre instance... et cela semble correct.

-> y aurait il une table à vérifier (sauvegarder) afin d'etre sûr de ne pas perdre les valeurs ?

**Comment by btry** [comment]
Bonjour

La migration 2.8.0 vers 2.8.1 ne fait aucun changement dans le schéma de la BDD, ni même ses  données. Je pense que votre souci n'est pas lié à l'upgrade.

Avez vous le moyen de vérifier l'état de votre question avant upgrade (a l'aide d'un backup), puis après uprgade ?

Les conditions sont dans la table glpi_plugin_formcreator_questoins_conditions.

**Comment by btry** [comment]
Bonjour @EC2311 

Avez vous pu vérifier le contenu de la table ?

**Comment by EC2311** [comment]
bonjour,
Non désolé je n'ai pas eu la possibiltié de vérifier le contenu de la table.

par contre sur la derniere instance (Prod) je sauvegarderai le contenu de la table en prevision

**Comment by EC2311** [comment]
J'ai migré de 2.6.5 en 2.8.5, pas eu de souci : je pense que ce la devait etre lié à la beta test ?
Je clos l'incident
