### ISSUE TITLE
Bug avec les apostrophes

### ISSUE THREAD

**Issue by bbouillonmons** [pluginsGLPI/formcreator#1385]
Bonjour,

GLPI 9.4.1.1 - FormCreator v 2.8.0

Nous avons connu un petit problème hier dans le plugin FormCreator.
Nos formulaires étaient créés depuis un bon moment, et nous testions la mise à disposition pour notamment les utilisateurs.
D'un seul coup, les questions de deux de nos formulaires ont complètement disparu, et aucun solution ne pouvait être trouvée, excepté un imort d'une sauvegarde des formulaires que nous avions fait précédemment.

En examinant de plus près, voilà l'erreur que nous avons découvert :

[2019-04-10 14:49:04] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
   MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `values` = 'L'imprimante ne s'allume pas
L'imprimante n'imprime rien
Bourrage papier
Traces noires ou grises lors de l'impression
Traces blanches lors de l'impression
' WHERE `id` = '222'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'imprimante ne s'allume pas
L'imprimante n'imprime rien
Bourrage papier

Il semble qu'il y ait des problèmes pour l'interprétation de l'apostrophe dans le plugin, et cela cause la suppression des questions dans les formulaires et dans la DB.

Bien à vous,

**Comment by btry** [comment]
Bonjour

Il manque le backtrace qui accompagne la requête. Pouvez-vous l'ajouter ?

**Comment by bbouillonmons** [comment]
Bonjour,

Qu'appellez-vous le Backtrace ? 
Merci

**Comment by btry** [comment]
Vous avez dû trouver la requête SQL dans le fichier glpi/files/_logs/sql-errors.log. Le backtrace est l'état de la pile d'appels de fonctions au moment de l'erreur. J'en ai besoin pour trouver le code fautif. Il est situé juste en dessous de la requête SQL.

Un exemple d'entrée de log complète

```
[2019-01-28 22:17:24] glpisqllog.ERROR: DBmysql::query() in /home/dethegeek/public_html/glpi-93/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE `glpi_displaypreferences` SET `itemtype` = 'PluginFormcreatorFormAnswer' WHERE `itemtype` = 'PluginFormcreatorForm_Answer'
  Error: Duplicate entry '0-PluginFormcreatorFormAnswer-2' for key 'unicity'
  Backtrace :
  inc/dbmysql.class.php:1029                         
  plugins/formcreator/install/upgrade_to_2.7.php:45  DBmysql->update()
  plugins/formcreator/install/install.php:135        PluginFormcreatorUpgradeTo2_7->upgrade()
  plugins/formcreator/install/install.php:103        PluginFormcreatorInstall->upgradeOneStep()
  plugins/formcreator/hook.php:50                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:707                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"2@l-w510","mem_usage":"0.004\", 1.98Mio)"} 
```

**Comment by bbouillonmons** [comment]
Voilà les infos : 

Voici quelques exemples complets : 

[2019-04-10 14:49:04] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `values` = 'PC ne s'allume pas
PC reboot
PC n'a plus accÃ¨s au rÃ©seau
PC bloquÃ© sur les mises Ã  jour (au dÃ©marrage)
' WHERE `id` = '220'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'allume pas
PC reboot
PC n'a plus accÃ¨s au rÃ©seau
PC bloquÃ© sur les mises ' at line 1
  Backtrace :
  inc/dbmysql.class.php:937                          
  inc/commondbtm.class.php:615                       DBmysql->update()
  inc/commondbtm.class.php:1446                      CommonDBTM->updateInDB()
  plugins/formcreator/inc/question.class.php:1424    CommonDBTM->update()
  plugins/formcreator/inc/section.class.php:390      PluginFormcreatorQuestion::import()
  plugins/formcreator/inc/form.class.php:2121        PluginFormcreatorSection::import()
  plugins/formcreator/inc/form.class.php:1922        PluginFormcreatorForm::import()
  plugins/formcreator/front/form.form.php:110        PluginFormcreatorForm->importJson()
  {"user":"354@demeter","mem_usage":"0.804\", 6.33Mio)"} 
[2019-04-10 14:49:04] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `values` = 'L'Ã©cran ne s'allume pas
Ã‰cran allumÃ© mais rien n'apparaÃ®t

' WHERE `id` = '221'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Ã©cran ne s'allume pas
Ã‰cran allumÃ© mais rien n'apparaÃ®t

' WHERE `id` = '' at line 1
  Backtrace :
  inc/dbmysql.class.php:937                          
  inc/commondbtm.class.php:615                       DBmysql->update()
  inc/commondbtm.class.php:1446                      CommonDBTM->updateInDB()
  plugins/formcreator/inc/question.class.php:1424    CommonDBTM->update()
  plugins/formcreator/inc/section.class.php:390      PluginFormcreatorQuestion::import()
  plugins/formcreator/inc/form.class.php:2121        PluginFormcreatorSection::import()
  plugins/formcreator/inc/form.class.php:1922        PluginFormcreatorForm::import()
  plugins/formcreator/front/form.form.php:110        PluginFormcreatorForm->importJson()
  {"user":"354@demeter","mem_usage":"0.041\", 6.34Mio)"} 
[2019-04-10 14:49:04] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `values` = 'L'imprimante ne s'allume pas
L'imprimante n'imprime rien
Bourrage papier
Traces noires ou grises lors de l'impression
Traces blanches lors de l'impression
' WHERE `id` = '222'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'imprimante ne s'allume pas
L'imprimante n'imprime rien
Bourrage papier
Traces' at line 1
  Backtrace :
  inc/dbmysql.class.php:937                          
  inc/commondbtm.class.php:615                       DBmysql->update()
  inc/commondbtm.class.php:1446                      CommonDBTM->updateInDB()
  plugins/formcreator/inc/question.class.php:1424    CommonDBTM->update()
  plugins/formcreator/inc/section.class.php:390      PluginFormcreatorQuestion::import()
  plugins/formcreator/inc/form.class.php:2121        PluginFormcreatorSection::import()
  plugins/formcreator/inc/form.class.php:1922        PluginFormcreatorForm::import()
  plugins/formcreator/front/form.form.php:110        PluginFormcreatorForm->importJson()
  {"user":"354@demeter","mem_usage":"0.083\", 6.36Mio)"}

**Comment by btry** [comment]
De ce que je vois les questions n'ont pas disparu. Je pense que vous avez tenté d'importer un formulaire précédemment exporté en JSON.

Le formulaire n'existait pas au moment de l'import et certaines questions contenant une apostrophe n'ont pas pu être créées pour les raisons que vous avez identifié.

**Comment by btry** [comment]
Veuillez tester ce patch et me faire un retour.

https://git<hub.com/pluginsGLPI/formcreator/pull/1386/files

**Comment by bbouillonmons** [comment]
Merci. Nous testons et nous vous revenons avec les résultats.

**Comment by btry** [comment]
Bonjour @bbouillonmons 

avez vous pu tester le patch ? Il est probable que je fasse une release la semaine prochainr, je souhaite fusionner un maximum de correctifs.
