### ISSUE TITLE
Affichage des formulaires lents 30 secondes

### ISSUE THREAD

**Issue by jeromemartignagocdg47** [pluginsGLPI/formcreator#1389]
Depuis mise à jour et passage en version 2.8.1 l'affichage des formulaires est très long, environ 30s

En cliquant sur Assistance - Formulaire, il faut attendre 30 secondes pour que les formulaires apparaissent.
Version de GLPI 9.4.2
Version de Fusion 9.4+1.1
Version de Form Creator	2.8.1

OS 
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

Erreur trouvée 
![image](https://user-images.githubusercontent.com/49755079/56362251-b0067c00-61e9-11e9-8e14-a7b7c9983958.png)

**Comment by btry** [comment]
Bonjour,

Vous utilisez le catalogue de services ? 

Avez vous vérifié si il ya des tables corrompues ?

Pouvez-vous compter le nombre de lignes dans les tables suivantes ?
- glpi_tickets
- glpi_plugin_formcreator_issues
- glpi_plugin_formcreator_formanswers
- glpi_plugin_formcreator_answers

Quelle est la dernière version du plugin où vous n'avez pas observé ces lenteurs ?

**Comment by jeromemartignagocdg47** [comment]
Taille des tables 
glpi_tickets : 13 134
glpi_plugin_formcreator_issues : 12 970	
glpi_plugin_formcreator_formanswers : 3 439	
glpi_plugin_formcreator_answers : 25 457

**Comment by btry** [comment]
Le catalogue de services ressemble à ceci:

https://github.com/pluginsGLPI/formcreator/blob/develop/screenshot_2.png

il est activé dans l'onglet Formulaires dans les entités, et est accessible aux utilsiateurs de l'interface simplifiée.

Il peut arriver qu'une table soit endommagée. Vous devriez les trouver avec la requete suivante

```sql
show table status where comment like '%crash%';

```

**Comment by btry** [comment]
Le plugin est utilisé sur des instances avec des tables de l'ordre de 10 à 15 fois plus grosses, sans qu'on me rapporte un souci.

Il faudrait vérifier les ressources utilisées de votre serveur, et activer la journalisation des requêtes lentes (slow queries) avec un seuil de déclenchement de 5 à 10 secondes. Ca pourrait être une piste.

**Comment by CDG47** [comment]
Un contrôle a été fait sur les tables, aucun soucis.
Le problème est sur l'affichage via le menu Tickets > Formulaires ou en interface simplifié.
![image](https://user-images.githubusercontent.com/11661365/56587077-31db1880-65e1-11e9-9f95-d80b40a4e0ab.png)
Nous n'avions pas de soucis avec la version 2.6.5.
Nous avons rencontré ce problème avec la 2.7, 2.8 et 2.8.1.
L'erreur renvoie à [la ligne 279 du fichier simplecache.class.php de GLPI](https://github.com/glpi-project/glpi/blob/2176db2af6cec976af871d78abaf22ff88cfbc93/inc/cache/simplecache.class.php#L279)

**Comment by btry** [comment]
L'endroit où se produit l'erreur n'a pas de signification car cela n'indique pas quel est le code responsable de la lenteur que vous observez, mais l'endroit où les 30 secondes allouées se sont écoulées.

Pour résoudre un problème de ce type, il faut soit reproduire sur un environnement de développeur (ce que je n'ai pas réussi à faire jusque là), soit chercher des indices permettant de cerner plus ou moins précisément le code responsable de la lenteur. Cela peut aussi être un problème de dimensioinnement du serveur, une anomalie matérielle, peut être aussi une anomalie dans la BDD (bien que je pense que le bug serait un peu différent dans ce dernier cas).

Etant donné que je ne n'ai aucun autre cas similaire pour faciliter les recherches, il se peut que le problème soit lié à votre instance. Cela pourrait nécessiter d'intervenir dessus, ce qui n'est pas envisageable sans contrat de support. Je vous invite à considérer la souscription au support professionnel pour trouver une solution rapidement.

https://services.glpi-network.com/#offers

En parallèle, essayez quand même d'activer la fonction de journalisation des requêtes lentes sur le serveur SQL. 

Autre piste de recherche : vérifiez que votre serveur MySQL est paramétré correctement pour gérer votre base de données.

https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html

**Comment by CDG47** [comment]
Apparemment le problème de lenteur est lié au profil. En super-admin, nous avons un meilleur temps d'affichage par rapport au post-only. Il semblerait que le même problème est été posté sur le [github de GLPI](https://github.com/glpi-project/glpi/issues/5806)

**Comment by btry** [comment]
En effet il pourrait y avoir un lien entre les deux car le plugin s'appuie sur les entités pour les formulaires. des requêtes SQL assez complexezs sont faites pour afficher les formulaires dans le catalogue de services, ce qui pourrait amplifier la lenteur observée dans GLPI.

Suivez l'autre ticket, pour surveiller sa progression. Mais je vous conseille toujours d'activer les slow queries pour voir si ça le problème provient de requêtes.

**Comment by CDG47** [comment]
Nous avons mis les slow queries mais les temps sont plutôt rapides:
# Query_time: 0.000010  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0
# Query_time: 0.000010  Lock_time: 0.000000  Rows_sent: 0  Rows_examined: 0
# Query_time: 0.001084  Lock_time: 0.000034  Rows_sent: 1  Rows_examined: 1
# Query_time: 0.000009  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0
# Query_time: 0.000008  Lock_time: 0.000000  Rows_sent: 0  Rows_examined: 0
# Query_time: 0.000009  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0
# Query_time: 0.000008  Lock_time: 0.000000  Rows_sent: 2  Rows_examined: 0
# Query_time: 0.000008  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0
# Query_time: 0.001079  Lock_time: 0.000038  Rows_sent: 2  Rows_examined: 2

Le temps le plus lent (0.001084) correspond à la requête suivante:
SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_formcreator_forms_profiles%';

**Comment by btry** [comment]
donc il est clair qu'aucune requête ne pose souci

**Comment by btry** [comment]
Bonjour

Il me semble que votre problème nécessite de procéder à un profilage des pages où vous rencontrez des lenteurs.

**Comment by btry** [comment]
Bonjout

Il semble que le plugin n'est pas la cause du problème.
