### ISSUE TITLE
Créateur d'une demande de validation d'un formulaire à mettre comme observateur dans le ticket

### ISSUE THREAD

**Issue by CHCI74** [pluginsGLPI/formcreator#139]
Bonjour,
Serait-il possible d'offrir la possibilité de mettre leréateur d'une demande de validation d'un formulaire comme observateur dans le ticket afin qu'il puisse suivre l'évolution de sa demande ?
Merci.

**Comment by neeftarah** [comment]
Bonjour,

Cette fonctionnalité est déjà disponible depuis la version 0.85-1.2.
Vous pouvez, dans la définition des tickets "Destinations", définir qui vous voulez en tant que demandeur, observateur ou technicien du ticket qui sera créer.

Cordialement,
Jérémy
