### ISSUE TITLE
Question : Traduction / utilisation Langue

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1393]
Bonjour

Nous avons créé des formulaires langues "Francaise" choisie dans l'entete formulaire : OK

Quel est le processus pour que les memes formulaires soient disponibles dans d'autres langues ? faut-il recreer un autre formulaire (donc dupliquer ?) 

L'idéal serait meme de récuperer la langue de l'utilisateur afin de présenter les formulaires dans les langues de l'utilisateur et à defaut celle d'origine ?

Ex : utilisateur a choisi "anglais". Les formulaires presents sont proposées dans sa langue (anglais) et si la traduction n'existe pas alors la langue de creation du formulaire (ici francais) est affiché ?

Peut etre que cela fonctionne ainsi... mais... 

en tout cas un sacré boulot ! super

**Comment by btry** [comment]
Bonjour

Pour avoir le même formulaire en plusieurs langues, il faut créer un formulaire pour chacune de ces langues. Vous pouvez dupliquer le premier formulaire pour reproduire les conditions ets tickets cibles, ...

Du point de vue du demandeur, les formulaires affichés sont ceux qui sont pour toutes les langues et ceux qui correspondent à la langue courante du demandeur. Les autres ne sont pas afichés.

**Comment by EC2311** [comment]
_"Du point de vue du demandeur, les formulaires affichés sont ceux qui sont **pour toutes les langues** et ceux qui correspondent à la langue courante du demandeur. Les autres ne sont pas afichés."_

ok, donc en fait si on veut que le formulaire s'affiche quelque soit les langues utilisateurs, il faut alors ne spécifier aucune langue dans le formulaire ?
