### ISSUE TITLE
Capture d'écran dans formulaire ne sont pas transformer en ticket

### ISSUE THREAD

**Issue by neus670** [pluginsGLPI/formcreator#1395]
**Describe the bug**
Lorsque l'on remplis un formulaire avec une zone de texte et que l'on copie colle une capture d'écran, celle ci n'est pas transmise en clair au ticket créer.

Alors que cela fonctionne si je fais la même chose sur une nouvelle création de ticket directement depuis Glpi.

Cela fonctionnait jusqu'à la mise à jour en 2.7.

Dans le ticket l'image apparait du style :
* <img id=";197e8a9e-d9d62df8-5c763f3a685cb4.69777496" src="http://kesglpi/front/';https:/nagios.fromi.com/front/';data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAkAAAL9CAYAAABJ1D+0AAAAAXNSR0IArs4c6QAAAARn
(snip)
sxJruGoTxylp6BcltFCAlVNp3AD1sZcoMUo2jfPKhFUbX/sdkPlWKjaekVKC2M7ARHT6PZScvxNGBOptuRr"

*

**Comment by btry** [comment]
Bonjour,

L'upload de documents par la zone de texte des formulaires n'est pas pris en charge pour le moment.

**Comment by neus670** [comment]
Elle fonctionnait pourtant avant.?

**Comment by btry** [comment]
Pas à ma connaissance. Si ça fonctionnait avec une ancienne version, mercide préciser laquelle, pour que je puisse faire une rechercne.

**Comment by btry** [comment]
Ah, c'est dit dans la 1er post. 

Je vais y jeter un oeil. Je vais sortir bientot une 2.8.2. Il ya fort à parier que je n'aurai pas trouvé de correctif pour cette release.

**Comment by neus670** [comment]
Merci encore

**Comment by btry** [comment]
Bonjour

Suite aux derniers développements, les images collées dans une zone de texte dont prises en charge (version 2.9.1 prévue dans les jours à venir).

Voir #1573 

Etant donné que la situation a évolué, je ferme ce ticket. Si vous trouvez un bug avec la versin 2.9.1 ou supérieur, veuillez ouvrir un nouveau ticket.
