### ISSUE TITLE
Form answers name 

### ISSUE THREAD

**Issue by tomSDL** [pluginsGLPI/formcreator#1396]
Hi,

Thanks for a great plugin. Is it possible to dynamically change the name of the form in form answers? 

**RFC: Request for change form ##answer_2##**

![image](https://user-images.githubusercontent.com/32687810/56905550-554a0b80-6a98-11e9-960b-59c83fe60340.png)

**Comment by btry** [comment]
Hi, 

Not at the moment. I think there is already an issue here for that feature.

**Comment by tomSDL** [comment]
Thanks. I tried looking but couldn't find.

Look forward to that feature.

**Comment by btry** [comment]
Hi

The feature is implemented. Form answer are customizable and support answer tags.
