### ISSUE TITLE
2.8.1 : no categorie = no ticket

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1397]
Avec la version 2.8.1, si, dans la destination d'un formulaire je ne spécifié pas une catégorie de ticket, en choisissant "depuis gabarit ou aucune" le ticket n'est pas créé.

**Comment by btry** [comment]
Bonjour

Avez vous trouvé une erreur dans php-errorslog oou sql-errors.log ?

Je viens de faire un essai avec la version 2.8.2 (en attente de publication) et ça fonctionne bien. Comme elle contient peu de correctifs, ça doit être bon aussi pour la 2.8.1.

**Comment by btry** [comment]
Bonjour

Il y a eu beaucoup de releases depuis la v2.8.1, je pense que ce ticket n'est plus d'actualité. N'hsitez pas à signaler si vous reproduisez sur la version 2.9.1
