### ISSUE TITLE
Affichage d'une section sous condition

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1399]
Bonjour,
serait-il possible d'envisager qu'une section (et donc les questions qu'elle contient) puisse être affichée sous condition de réponse à une question précédente ?
Ainsi, cela éviterai de paramétrer cet affichage pour plusieurs questions qui vont dépendre de la réponse à une seule question. 
Dans la section affichée, on peut aussi avoir un champ dont l'affichage dépend de la réponse à une autre question de la même section

Exple : demande de matériel téléphonique : choix sur mobile ou fixe.
On affiche selon la réponse la section des questions pour les téléphones mobiles ou la section pour les téléphones fixes.

**Comment by msizec** [comment]
je pense que c'est possible désormais, ne sais depuis quand mais cest intégré ! merci !
