### ISSUE TITLE
Top lists on forms

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1400]
when we use the type of question "Suspended List" and we use the "ITIL category", the "completename" is displayed. It is possible to display only the "name". This way the user would only have access to the last name, making it not a very large list.

![Captura de tela em 2019-05-08 13-35-38](https://user-images.githubusercontent.com/35368369/57392119-4ea54d80-7196-11e9-9759-b47aa08efad4.png)
![Completename](https://user-images.githubusercontent.com/35368369/57392122-4ea54d80-7196-11e9-93ce-e0d39d99fb21.png)

**Comment by btry** [comment]
Hi,

currently the code does not allows to show the name instead of the complete name. This is technically possible.

Showing the complete name allows to avoid ambiguous cases when the name is the same for entries with different ancestors.

**Comment by phamorais** [comment]
@btry 

I agree.

In my case, I offer the list just on the form. In my company, the form is already categorized, so the user does not need to view the ancestors.

Example:

Form: Alpha System
Question: Select the system module
List: Ticket Category

My Ticket Category is as follows:

1 - Alpha System
2 - Alpha System> Financial
3 - Alpha System> Customer
4 - Alpha System> Product

When my client selects my form, it will only see the "Financial, Customer and Product" modules in the list, and the "name" is displayed only on the form, and all ancestors are listed in all GLPI lists.

In my company we did however changed the file "dropdown.class.php" and it worked. But I believe this should be done in the plugin if the project is approved.

Example

list in form

![formulário](https://user-images.githubusercontent.com/35368369/57541209-e042c580-7324-11e9-94de-04c414aac024.png)

List in GLPI

![lista](https://user-images.githubusercontent.com/35368369/57541223-e769d380-7324-11e9-9193-694ba1df3acf.png)

**Comment by btry** [comment]
dropdown.class.php is a file belonging to GLPI, not the plugin. Your change might affect all dropdowns in GLPI and plugins.

**Comment by phamorais** [comment]
exactly!

So I posted here in the plugin, I believe this can be handled in Formcreator and not in GLPI.

For my working process changing the file "dropdown.class.php" had no impact, but it might have to the community. So I did not suggest it on the GLPI page.

**Comment by btry** [comment]
If I have enough time I may implement a setting in version 2.9.0

**Comment by phamorais** [comment]
@btry thx!

**Comment by phamorais** [comment]
Hi @btry 
is there any chance of this being implemented?

**Comment by phamorais** [comment]
Hi @btry Any chance this in form v10.2?

**Comment by btry** [comment]
Hi

It is too late, v2.10.2 is already out. I'm focusing on stabilization of 2.11 and performance optimization for now.

**Comment by phamorais** [comment]
@btry Thx! I will wating!

**Comment by phamorais** [comment]
@btry Hi!

Don't forget about us haha!

**Comment by phamorais** [comment]
@btry  Any chance this in form v2.11.3?

**Comment by btry** [comment]
Hi

I'm busy with tasks for customers. Consider subscribing support and request for a quote. This way you can get better delays.
