### ISSUE TITLE
URL Enquête de Satisfaction

### ISSUE THREAD

**Issue by Leiilow** [pluginsGLPI/formcreator#1401]
Bonjour,

Mon entreprise débute dans GLPI et nous avons mis en place les enquêtes de satisfaction après clôture d'un ticket. La personne mis en demandeur du ticket reçois donc un mail avec l'invitation à remplir l'enquête de satisfaction ainsi que l'URL du ticket dans l'onglet satisfaction.

Ma question est la suivante : est-il possible de changer l'URL mis dans le mail en un nom du genre "enquête de satisfaction" style DNS ? Car je trouve l'URL très longue, mais bon c'est juste une histoire de customisation.

Vous remerciant,
Bonne journée.

**Comment by btry** [comment]
Bonjour

Formcreator n'est pas impliqué dans le système d'enquêtes de satisfaction. je vous invite à poser la question sur le forum communautaire : https://forum.glpi-project.org/

Vous pouvez aussi souscrire à un contrat de support pour vous accompagner dans la configuration et utilisation de GLPI : https://glpi-project.org/subscriptions/
