### ISSUE TITLE
mise à jour

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1402]
bonjour,
je vois qu'il y a une mise à jour de sécurité, comment faire cette mise à jour sachant que j'ai des formulaires en production ?

bien cordialement
Alain

**Comment by btry** [comment]
Bonjour

Après avoir remplacé l'ancienne version du plugin par la dernière, upgradez le plugin comme n'importe quel autre. Vous pouvez aussi upgrader avec la ligne de commande : https://github.com/pluginsGLPI/formcreator/tree/develop/scripts

**Comment by btry** [comment]
Bien sûr toujours sauvegarder GLPI et sa BDD avant d'upgrader, et idéalement validez vote procédure avec un GLPI de  test contenant uen copie de votre BDD.

**Comment by defaliz** [comment]
Très bien,
je vous remercie
Alain
