### ISSUE TITLE
erreur sur installation

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1403]
rebonjour,
j'ai corrigé mon erreur sur le plugin,
dans la base j'ai bien les tables et les champs de mes formulaires
côté glpi le plugin formcreator est indiqué comme non activé... 
si je l'active est-ce mes formulaires précédents seront conservés ?

je vous remercie
Alain

**Comment by btry** [comment]
Si aucun bug ne se manifeste, oui.

**Comment by defaliz** [comment]
ça a fonctionné
merci pour votre aide
Alain
