### ISSUE TITLE
Gamme de caractères ne fonctionne pas

### ISSUE THREAD

**Issue by jorgecamargosdb** [pluginsGLPI/formcreator#1404]
**Describe the bug**
Après avoir défini les caractères minimum ou maximum à saisir par le demandeur, dans un champ de texte ou int, je vérifierai que cette fonction ne fonctionne pas, permettant ainsi l’insertion de caractères inférieurs ou supérieurs.

**To Reproduce**
1. Go to 'Formcreator'
2. Click on 'Questions'
3. Create a question type "Entier"
4. Insert a range caracter
5. See the error. If you enter fewer characters than the minimum or more characters than the maximum, it returns no error and allows the opening of the call

**Expected behavior**
a return on the required characters.

**Desktop (please complete the following information):**
 - OS.: CentOS 7
 - Browser.: chrome, safari
 - GLPI Version.: 9.4.1
 - Formcreator Verson.: 2.8.0

![Formcreator Error](https://user-images.githubusercontent.com/23311692/57638165-94418c00-7583-11e9-96e2-1df9bd760d4c.JPG)

**Comment by btry** [comment]
Hi

For integer, the min and max fields don't set the number of characters but the minimum and maximum values of the integer.

The same applies to float type.

min <= X <= max , not min <= len(X) <= max

**Comment by jorgecamargosdb** [comment]
Hi

Good morning, thank you for your explanation.
I did with "regex" because I want to validate this field.
