### ISSUE TITLE
interface simplifée pour le ticket lié au formulaire 

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1406]
bonjour
problème simple je pense, mon glpi utilise l'interface simplifiée mais le ticket lié au formulaire est au format standard, comment le mettre ne interface simplifiée ?

merci à tous

**Comment by btry** [comment]
Un ticket n'est pas associé à un type d'interface. C'est le type d'interface qui définit comment le ticket est présenté. Vérifiez votre profil utilsiateur. Si besoin, rendez-vous sur le forum communautaire https://forum.glpi-project.org/
