### ISSUE TITLE
Conditional display with checkboxes

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#1408]
Hi !

**Is your feature request related to a problem? Please describe.**

Actually we use formcreator conditional question with text field. Text filed is case sensitive and some users have big fingers and type one char in uppercase, one in lowercase, or all in uppercase....
So the next question is not displayed to the form, and we does not have all informations that we need !

**Describe the solution you'd like**

The idea is to use checkboxes instead of text field. Actually nothing happens, when we make a conditional question with this type of field.

**Describe alternatives you've considered**

We use text field, but it's a good solution when you haven't human users ;) !

Thanks !

**Comment by btry** [comment]
Hi

Please build an test form where you reproduce the issue and share it here. This will help to check and fix faster.

**Comment by SylvainGuibert** [comment]
Please find the configuration of the test form : 
![image](https://user-images.githubusercontent.com/16323410/58170997-36a0f400-7c95-11e9-80f8-138da9990cf4.png)


The second question is conditional. If answer = "oui" then display "question masquée"

![image](https://user-images.githubusercontent.com/16323410/58171014-40c2f280-7c95-11e9-9dec-9c19d9a34cb3.png)


This is the form without any answer : 

![image](https://user-images.githubusercontent.com/16323410/58171039-50dad200-7c95-11e9-97b4-1245cd92b334.png)

This the form after tick the check boxes for answer yes

![image](https://user-images.githubusercontent.com/16323410/58171059-5cc69400-7c95-11e9-9dbc-a5728fc8a4bf.png)

**Comment by btry** [comment]
I assume you're running the latest release ?

**Comment by btry** [comment]
Je viens de tester, il semble que ça affecte les questions de type Adresse IP (un champ texte fonctionne bien)

**Comment by btry** [comment]
En fait c'est tout à fait normal : le champ adresse IP est un champ invisible. Il collecte l'IP de l'ordinateur où est soumis le formulaire.

Il est donc inutile de placer une condition d'affichage sur ce champ.

**Comment by SylvainGuibert** [comment]
Je viens de faire le test en modifiant le type de champ et effectivement ça fonctionne. Merci pour l'aide !
