### ISSUE TITLE
Bouton annuler,sauvegarder et d'autres options pas affichés dans la destination du formulaire

### ISSUE THREAD

**Issue by nblaisonneau** [pluginsGLPI/formcreator#141]
Bonjour,

Tout d'abord un grand merci à l'équipe de dev pour ce travail, le plugin est top.
Je rencontre cependant un petit problème à moitié résolu :)
Dans la partie destination de nombreuses options sont masquées car il y a (je crois, je ne suis pas dev, juste sysadmin) une erreur de code dans la page inc/targetticket.class.php
J'ai retiré la section "due_date" est tout réapparait.
Voici les lignes que j'ai supprimé:
De 90 : echo '<td width="15%">' . __('Due date') . '</td>';
à 160: echo '</tr>';
Pourriez-vous me dire ce qui bloque? Pour que je puisse remettre en place cette partie du code.

Version Glpi: 0.90
Version formcreator: 0.90-1.2.5

Je joins des captures d'écrans, on peut y voir sur la première qu'il n'est pas possible de faire de sauvegarde des modifications et les autres options n'apparaissent pas.

Avant:
![helpdesk - formcreator - mozilla firefox_2](https://cloud.githubusercontent.com/assets/15675840/10977220/1c7d58a8-83f0-11e5-9e2c-366bc4cdec44.jpg)

Après:
![helpdesk - formcreator - mozilla firefox](https://cloud.githubusercontent.com/assets/15675840/10977223/21e78a02-83f0-11e5-860f-252035a33e48.jpg)

J'espère que cela pourra aider.

Merci d'avance.
Cdt,
N1c0

**Comment by Gilmor49** [comment]
Bonjour,
j'ai le même phénomène.
Après suppression de la partie de code, ça refontionne!
Merci pour votre super boulot.

Cdt, Gilles

**Comment by neeftarah** [comment]
Bonjour,

Le problème avait déjà été remonté dans l'issue #132 et à été corrigé par le commit 08ebeee.
La correction sera disponible dans la nouvelle version 0.90-1.3.

Cordialement,
Jérémy
