### ISSUE TITLE
BUG - Dropdown filter fail : Target ticket? 

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1412]
The drop down list for creating a form is not filtering when typing.

1 - In creating the form:
2 - Taget ticket

When we select "ticket category"> "Specific category", the "Category" list and enter a word, the list is not filtere

![lista](https://user-images.githubusercontent.com/35368369/58475179-a135b200-8123-11e9-88d3-b776797825ca.png)

PLugin Version : 2.8.1
GLPI version: 9.3.3.

**Comment by resplandeluiz** [comment]
I have a solution.

In file  inc/targetticket.class.php, 
Find the function 

`protected function getCategoryFilter()`

**Change this**

`return [`
           ` 'OR' => [`
            ` 'is_request'  => 1,`
            `'is_incident' => 1 `  
         `]`
` ];`
`}`
` return "is_request = '1' OR is_incident = '1'";`


**For**

`return [`
            `'OR' => [`            
              ` 'is_incident' => 1`              
           ` ]`
        ` ];`
   `   }`
     ` return "is_request = '1';   `

![pic-filter](https://user-images.githubusercontent.com/31370242/58476402-07700400-8127-11e9-94ed-83e7fe97f360.png)



Works! I will create one Merge Request.

**Comment by btry** [comment]
Hi @resplandeluiz 

the chenge you might not be good. I notice 2 things

1 - the method returns a raw SQL snippet or an array for the query builder, depending on the version of GLPI. Both expressions should be changed.

2 - the dropdown might not work if the SQL snippet is badly included in the remaining of the query and causes an invalod query.

@phamorais can check in sql-errors.log if there are relevant errors ?

**Comment by phamorais** [comment]
@btry 
Sorry for the delay in replying

There are no relevant logs. But it is easy to reproduce, just create a list and try to search this field

**Comment by phamorais** [comment]
@resplandeluiz can u help ?

**Comment by phamorais** [comment]
@btry 

This bug does not occur in version 2.8.6. We can close this issue
