### ISSUE TITLE
PB tests conditionnels

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1414]
Bonjour,
J'ai un souci avec les tests conditionnels autres que égal.
Lorsque je fais un test sur une valeur "supérieure ou égale" par exemple le test ne se valide pas.
Lorsque j'enregistre et que je reviens sur la question le test a été enregistré en =
![image](https://user-images.githubusercontent.com/25478777/58802920-9d67cb00-860e-11e9-87ed-48072b4442ec.png)
Lorsque je vérifie dans la table `glpi_plugin_formcreator_questions_conditions` le test n'existe tout simplement pas:
![image](https://user-images.githubusercontent.com/25478777/58803092-f46da000-860e-11e9-8455-b606c8ee9198.png)
Je suis en GLPI 9.3.3 et formcreator 2.8.2
Merci d'avance

**Comment by btry** [comment]
Bonjour

Ce bug m'a été signalé la semaine dernièer et un patch a été fait. Il est dans ce commit

https://github.com/pluginsGLPI/formcreator/commit/fad48aa8df79e3aca5b30f51a862c5559023e345

**Comment by eckorion** [comment]
Désolé, j'avais cherché, mais pas trouvé.
Je viens de tester ça fonctionne.
Merci

**Comment by btry** [comment]
C'est normal : le bug n'a pas été reporté via github
