### ISSUE TITLE
Evolution ? Lister les intitulés

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1418]
Bonjour

Comment peut-on lister les intitulés (Type de serveur, par exemple) mais aussi les intitulés des autres plugin (database etc?) 
Apres tout c'est un objet GLPI non? ;)

**Comment by EC2311** [comment]
Oups

pas vu dans Intitulé : j'avais recherché dans objet glpi 
Désolé
donc résolu sans probleme

**Comment by btry** [comment]
Bonjour

Fausse alerte donc je ferme :)
