### ISSUE TITLE
Incorrect category view

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1419]
Hi,

**Describe the bug**
When I create subcategories for a category, and the user does not have entity access to the subcategory forms, the home page shows the category in the MENU, even without forms (empty category)

**To Reproduce**
Create sub-categories and add forms to an entity that the user does not have access to.

**Expected behavior**
Do not show the empty category.

**Comment by btry** [comment]
Hi your report is taken into account, but I cannot investigate for now. Please be patient.

**Comment by jvergacas** [comment]
Thanks for the help, it was resolved with the fix: 	

fix(wizard): form categories may show when they are empty
