### ISSUE TITLE
Erreur accès détail de la cible

### ISSUE THREAD

**Issue by Gilmor49** [pluginsGLPI/formcreator#142]
Bonjour,

Suite mise à jour Ubuntu server 14 et GLPI 0.90 le plugin Formcreator n'affiche plus le détail d'une cible. 

Ubuntu server 14
GLPI 0.90 / Plugin Formcreator dernière version
EN mode Debug j'ai une partie de la cible!

A priori idem case #141 

Pb affichage?
Cdt, Gilles

![erreur_glpi](https://cloud.githubusercontent.com/assets/15018195/11020579/a166a1fc-8623-11e5-9c7e-d98ac0b24306.jpg)

**Comment by neeftarah** [comment]
Bonjour,

Effectivement idem #141, idem #132 et donc déjà corrigé dans la version 0.90-1.3.

Cordialement,
Jérémy
