### ISSUE TITLE
Erreur accès aux formulaires saisis - Issue #869

### ISSUE THREAD

**Issue by githublivier** [pluginsGLPI/formcreator#1421]
Bonjour,

Avant toute chose, je tenais à vous remercier pour le travail effectué pour ce plugin qui est fort utile.

Je me permets d'ouvrir cette demande car, je suis confronté au problème décrit dans l'issue #869 mais je ne peux pas mettre en place le fix bug.
En effet, mon hébergeur ne me permet pas d'évoluer ma version php. Je suis donc toujours en 5.4.
De ce fait, j'utilise le plugin en v2.5.2 pour une version glpi en 9.1.3

Si j'essaie d'ajouter directement les lignes de codes je rencontre le message d'erreur suivant : 

`Parse error: syntax error, unexpected 'class' (T_CLASS)...`

Qui semble être liée à ma version php.

Je sais que je n'utilise pas une version très récente du plugin mais si ce n'est pas trop long et compliqué à mettre en oeuvre, est il possible de proposer un fix bug compatible avec la V2.5.2 du plugin svp ?

Vous remerciant par avance

**Comment by btry** [comment]
Bonjour

en PHP 5.4 il n'est pas possible d'utiliser la syntaxe Foo::class (Foo étant pour l'exemple une classe).

Il faut chercher dans tout le code les occurences de cete syntaxe et les remplacer par le nom de la classe entre simples quotes.

Je ne peux pas  passer du temps à faire des correctifs pour des versions obsolètes du plugin de manière communautaire. Vous devriez envisager un contrat de support pour cela.

Je vous invite à prendre contact pour étudier nos offres d'hébergement pour GLPI à contac@teclib.com . Cela vous permettrait de résoudre tous les problèmes de sécurité liés à l'usage de versions obsolètes de PHP, GLPI et du plugin.

**Comment by githublivier** [comment]
Bonjour,

Je comprends parfaitement et vous remercie d'avoir pris le temps de me répondre.
Encore merci pour votre travail.
