### ISSUE TITLE
Formcreator 2.8.1 : mise en forme différente entre cible et ticket

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1424]
Bonjour,
après avoir travaillé la mise en forme du corps du ticket lors de la validation du formulaire (zone description de l'onglet cible du formulaire), je me suis rendu compte que la mise en forme du ticket n'a rien à voir ... perte des couleurs, des alignements, polices différentes, etc ...
Je me retrouve en fait à l'inverse de l'effet recherché : avoir un ticket lisible et agréable à lire avec les infos essentielles ...
J'ai nettoyé les balises superflues ou en double du code html généré, en vain.
Sur quel CSS les formulaires s'appuient-ils ?

**Comment by btry** [comment]
Bonjour

GLPI utilsie la librairie HTMLawed. Elle nettoie certaines imbrications de balises absurdes comme ds balises P imbriquées. Du côté de Formcreator, il y a certaines contraintes techniques qui aboutissent à de telles imbrications. Par conséquent, le code HTML enregistré dans les tickets générés peut être très différent de ce que vous avez conçu et vous perdrez probablement des styles dans des balises supprimées.

Tant que GLPI utilise cette librairie, je ne peux pas contourner cette contrainte.

Vous devriez plutôt rester sur quelque chose de simple. La situation évoluera certainement mais à une date indéterminée.

**Comment by Sicoval31** [comment]
Pour ne pas dupliquer les sujets ... ref au post https://forum.glpi-project.org/viewtopic.php?id=171374 sur ke forum GLPI
Le code HTML généré lors de la création du ticket rajoute des ";" dans les balises, ce qui perturbe donc la lecture du code HTML et ne rend plus la mise ne forme voulue.
Et parfois ajout de balise <code></code> au milieu du code ...
![image](https://user-images.githubusercontent.com/42040529/62694828-5fec3900-b9d5-11e9-941f-6dc7cfc70bf8.png)

Le code en base est bon.
Dans le formulaire aussi :
![image](https://user-images.githubusercontent.com/42040529/62694914-8ca05080-b9d5-11e9-8758-7f7528b532ce.png)

**Comment by btry** [comment]
Bonjour

L'ajout de balises CODE doit provenir d'opérations de copier coller entre la liste des tags disponibles pour le formulaire et le modèle de ticket cible. En effet la liste est affichée avec cette balise. Cela a été enlevé récemment, mais pas encore livré. Il faut attendre la 2.8.4. 

Pour le souci de point virgule je n'ai pas encore eu de temps pour chercher. Il est probable que je livre la version 2.8.4 avant de chercher une solution.

**Comment by Sicoval31** [comment]
la balise code seule n'est pas gênante en soit et ne modifie pas l'apparence du ticket.
quant à l'ajout du ";", est-ce formcreator ou plutôt GLPI qui interprète mal quelque chose ? et comme je n'ai pas d'autres plugin qui permettent de créer directement un ticket, je n'ai pas pu comparer.
Je suis le seul à avoir remonté cela ?
Ou personne ne touche à la mise en forme du ticket dans le bloc destinataire ?
bon courage pour la suite

**Comment by btry** [comment]
Je n'ai pas conaissance ou souvenir d'un problème similaire, mais la gestion du code HTML est assez compliquée pour des raisons historiques coté plugin, et à cause d'une librairie tierce utiliée côté GLPI. 

Il serait intéressnt de svoir avec quelle  version du plugin a été créé le formulaire imapcté, avec quelel version le ticket cible a été modifié pour la dernière fois, et comparer l'allure du texte directmetn dans la BDD avec un formulaire "frais".

**Comment by Sicoval31** [comment]
Ces formulaires sont récents, créés courant juin avec les versions actuelles en PROD (glpi 9.4.2 et FC 2.8.1).
la mise en forme du bloc destinataire à été faite hier pour vérifier ce problème, il ne contenait avant que la balise ##fullform##.

**Comment by btry** [comment]
Bonjour

Je ferme ce ticket car des changements dans la gestion des zones de texte ont eu lieu dans le plugin depuis l'ouverture de ce ticket.

Le plugin est toujours assujetti à la librairie HTMLawed dans GLPI.

En ce qui concerne les balises CODE, elles ne sont plus utilisées pour afficher la liste des tags disponibles, permettant de résoudre d'éventuels problèmes de copier / coller.
