### ISSUE TITLE
Checkbox or multselect are not going to the ticket screen.

### ISSUE THREAD

**Issue by vinilamelas** [pluginsGLPI/formcreator#1426]
Checkbox or multselect are not going to the ticket screen.

When selecting a checkbox that is hidden the same as another checkbox the information is not going to the description of the called.

**To Reproduce**

1 - I open the form
2- Answer a checkbox or multiselect question.
3 - This question opens another question with the same field type, I answer this question by selecting several items.
4 - I open the call
5 - In the ticket screen does not appear the information of the 2 answer, but in the answer screen of the form appears.

**Expected behavior**

**Screenshots**

 
![image](https://user-images.githubusercontent.com/51828518/59518481-18957080-8e9c-11e9-9ffa-512664fd04db.png)

![image](https://user-images.githubusercontent.com/51828518/59518641-6b6f2800-8e9c-11e9-8a2a-4be718d7f0f4.png)

 - Browser [chrome, safari]

Formcreator 2.8.3
GLPI 9.3.3

**Comment by vinilamelas** [comment]
follow video : 
![ABERTURA](https://user-images.githubusercontent.com/51828518/59519261-d8cf8880-8e9d-11e9-8bb6-aa554273579c.gif)


follow form : 
[export_formcreator_20190614_1215.zip(https://github.com/pluginsGLPI/formcreator/files/3291205/export_formcreator_20190614_1215.zip)

complete form response : 
[Form Response.pdf](https://github.com/pluginsGLPI/formcreator/files/3291213/Form.Response.pdf)

**Comment by phamorais** [comment]
Hi

I have the same problem in version 2.8.3.

**Comment by vinilamelas** [comment]
Hello Phamorais

Follows the correction passed by Teclib


diff --git a/inc/formanswer.class.php b/inc/formanswer.class.php
index 977129ae..503a9fa6 100644
--- a/inc/formanswer.class.php
+++ b/inc/formanswer.class.php
@@ -1155,12 +1155,13 @@ class PluginFormcreatorFormAnswer extends CommonDBTM
       $question = new PluginFormcreatorQuestion();
 
       $found_questions = $question->getQuestionsFromForm($this->fields['plugin_formcreator_forms_id']);
-      foreach ($found_questions as $id => $question) {
-         $fields[$id] = PluginFormcreatorFields::getFieldInstance(
+      foreach ($found_questions as $questionId => $question) {
+         $answer = $answers_values['formcreator_field_' . $questionId];
+         $fields[$questionId] = PluginFormcreatorFields::getFieldInstance(
             $question->fields['fieldtype'],
             $question
          );
-         $fields[$id]->parseAnswerValues($answers_values);
+         $fields[$questionId]->deserializeValue($answer);
       }
 
       // TODO: code very close to PluginFormcreatorTargetBase::parseTags() (factorizable ?)

**Comment by phamorais** [comment]
@vinilamelas 

Thank you very much

Will this solution apply to new versions? I ask this is because the topic is not marked here in git that informs the validation of the code.

**Comment by btry** [comment]
Hi,

@phamorais this fix will be included on the next version. Sorry to not inform you about this fix. I found it while searching an other problem a month ago without noticing that this issue is related.

**Comment by btry** [comment]
Fixed with https://github.com/pluginsGLPI/formcreator/commit/fd25d4efebbe391edfb1de815a820f6612303b40
