### ISSUE TITLE
extration des valeur des champs du formulaire

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1429]
bonjour,
je voudrais extraire les valeurs des champs d'un formulaire pour alimenter un annuaire ldap
question : 
les questions sont dans les champs plugin_formcreator_questions_id 
les numéros sont-ils toujours les mêmes pour un même id de formulaire
par exemple : 
64 contient le prénom
65 contient le nom
...

merci

**Comment by btry** [comment]
Bonjour

Un formulaire est cec que vous concevez en tant qu'administrateur. Vous définissez les questions, les setions les tickets ou changement cibles.

Qaund un demandeur soumet sa saisie, il crée une réponse à un formulaire.

A partir de ces définitions je vais pouvoir répondre.

la table formanswers matérialise la réponse au formulaire, et la table answers contient dans une ligne la réponse à une question du formulaire. Vous avez autant de lignes que de questions dans le formulaire.

C'est donc dans la table answers que vous aurez les doonnées saisies par le demandeur. De mémoire vous avez une clé étrangère vers la table questions qui vous sera nécessaire pour savoir à quelle question correspond une donnée saisie.

Du coup l'id d'une question est fixe pour toutes les réponses à un formulaire, tant que la conception du formulaire n'évolue pas.

**Comment by defaliz** [comment]
parfait, 
merci pour la réponse rapide....
