### ISSUE TITLE
Impossible de scroll dans un formulaire

### ISSUE THREAD

**Issue by Kahalisto** [pluginsGLPI/formcreator#143]
Bonjour,

Si un formulaire possède un certain nombre de question, il est impossible de scroll si la disposition Séparation Verticale est utilisée.
Du coup il est également impossible d'envoyer le formulaire :(

**Comment by Kahalisto** [comment]
J'ai remarqué que l'ascenseur vertical permettant le scroll ne s'affiche pas lorsque le navigateur est en plein écran (Chrome et Firefox) et résolution de 1920*1080.
En revanche si je réduis la largeur de la fenêtre, l’ascenseur fini par s'afficher.

**Comment by neeftarah** [comment]
Bonjour,

Ce bug est effectivement due au nouveau fonctionnement de GLPI et pas directement à FormCreator.

Je regarde ce soucis avec un des développeur cœur s'il y à des modification à faire au niveau de Formcreator ou de GLPI.

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
Bonjour,

Le problème est bien introduit par GLPI qui applique une classe CSS rendant le scroll impossible sur tout les fichier se terminant pas "form.php".

Ce comportement est voulu pour GLPI pour les fichier "xxx.form.php" mais le fichier d'affichage des formulaire "showform.php" posait problème.

J'ai résolu ce bug sur Formcreator en changeant le nom du fichier "showform.php => formdisplay.php",  et vais rapporter le bug au niveau de GLPI pour inclure le point manquant ".form.php".

Cordialement,
Jérémy

**Comment by Kahalisto** [comment]
Bonjour,

J'ai appliqué la correction.
Ça fonctionne impeccablement
merci beaucoup !
