### ISSUE TITLE
filtrage des notifications 

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1435]
bonjour,
je voudrais notifier mes techniciens en fonction de la source de la demande
pour un formulaire --> notification à un groupe de techniciens
pour le courriel --> notification à un autre groupe...

comment faire ça ? avec une règle métier ?

merci pour vos réponses
Alain

**Comment by btry** [comment]
Bonjour

Cet espace devrait être reservé aux rapprots de bugs / nouvelles fonctionnalité. Je vous renvoie vers le forum de GLPI, où vous aurez plus de chances d'avoir une réponse de la communauté.

https://forum.glpi-project.org/

**Comment by defaliz** [comment]
oups, désolé
