### ISSUE TITLE
Problème d'affichage des menu 

### ISSUE THREAD

**Issue by reg25** [pluginsGLPI/formcreator#144]
Bonjour, depuis peu j'ai vu la disparition des menus en mode helpdesk et j'ai remarqué des caractères illégaux sur le javascript généré par scripts.js.php, ce qui me semble être la cause du bug. Voici un exemple : 
![scripts js php](https://cloud.githubusercontent.com/assets/15835790/11150798/196c2e10-8a2a-11e5-9ee9-e81bd92bf156.jpeg)

Mon environnement : Debian Wheezy, Apache 2.2.22, Php 5.4.45, GLPI 0.85.4, Formcreator 0.85-1.2.4 (testé aussi avec 0.90-1.3)

**Comment by neeftarah** [comment]
Bonjour,

Je suis désolé mais les caractères que vous avez ne devrais clairement pas y être.
Le fichier doit se terminé à la ligne juste au dessus. (https://github.com/pluginsGLPI/formcreator/blob/master/scripts/scripts.js.php)

Je vous suggère de tenté sur un "GLPI neuf" avec les dernières versions.
Si vous étiez sous Windows, il peut arriver que certains caractères soit insérés ou mal interprété. Mais étant sous Debian, il n'y a aucune raison que vous ayez ce genre de chose.

Je vous suggère également (on ne sait jamais) de vérifié l'ensemble des fichiers à la recherche de code non désiré et de vérifier la sécurité de vos serveur / postes / navigateurs / Anti-Virus.

Cordialement,
Jérémy

**Comment by reg25** [comment]
Bonjour, merci d'avoir pris du temps pour répondre. J'ai suivi vos suggestions, avec un glpi "neuf" sans succès. Ensuite je suis passé au serveur "neuf" et là j'ai identifié le problème de ma config actuelle. Je ne sais pas pourquoi, le module apache-php habituel est devenu libapache2-mod-php5filter lors d'une update. Visiblement, celui ci pose problème avec les fichiers js.php. Je suis revenu au module habituel libapache2-mod-php5 et tout est revenu dans l'ordre.
Merci pour votre support.
