### ISSUE TITLE
Captcha sur formulaire anonyme

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1440]
Bonjour,
Je me demande s'il est envisagé de mettre en place un système de captcha sur les formulaires anonymes/publics?
Du fait qu'ils deviennent accessibles à tous le monde ce serait bien d'avoir une sécurité de ce type, mais que sur ceux-là.
Cordialement

**Comment by btry** [comment]
Bonjour

La question ne s'est pas pose jusqu'à aujourd'hui. C'est techniquement faisable, mais ca va consommer quelques ressources du serveur malgré tout (voir l'implémentation équivalente dans flyve MDM, plugin auxiliaire pour l'ancienne démo)

**Comment by eckorion** [comment]
Bonjour, je n'ai pas trouvé l'implémentation dont vous parlez, mais je ne vois pas trop la consommation de ressources avec un reCaptcha par exemple.
Mais merci quand même de votre réponse.
Cordialement

**Comment by btry** [comment]
Bonjour

J'ai raisonné par rapport à un risque d'attaque par déni de service ou la pollution de la BDD par un apport massif de données (inutiles).
