### ISSUE TITLE
Impossible de voir certain ticket dans l'interface simplifiée

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#1441]
Dans l'interface simplifié, nous avons un problème sur certain ticket qui sont mal affiché dans la section "Mes demandes d'assistance".
Nous avons des tickets dont le nom est à la place de l'ID et les titres des tickets sont tous "Ticket".
Lorsque l'on clique sur "Ticket" impossible d'ouvrir le ticket (problème de droit)

Les liens sont différents:
http://glpi/plugins/formcreator/front/issue.form.php?id=&sub_itemtype=3048
Au lieu de:
http://glpi/plugins/formcreator/front/issue.form.php?id=3483&sub_itemtype=Ticket

![image](https://user-images.githubusercontent.com/47602797/60433627-8fa16780-9c05-11e9-844a-d081dc87015c.png)

GLPI 9.4.2
Formcreator 2.8.3

J'ai trouvé une erreur dans le fichier php.log sans savoir si ça a un rapport
`[2019-07-01 13:25:51] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\glpi\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins\formcreator\inc\issue.class.php:522        
  plugins\formcreator\hook.php:278                   PluginFormcreatorIssue::giveItem()
  inc\search.class.php:5271                          plugin_formcreator_giveItem()
  inc\search.class.php:1444                          Search::giveItem()
  inc\search.class.php:314                           Search::constructData()
  plugins\formcreator\inc\issue.class.php:685        Search::getDatas()
  plugins\formcreator\inc\wizard.class.php:243       PluginFormcreatorIssue::getTicketSummary()
  plugins\formcreator\inc\wizard.class.php:86        PluginFormcreatorWizard::showTicketSummary()
  plugins\formcreator\front\issue.form.php:59        PluginFormcreatorWizard::header()
  {"user":"59@","mem_usage":"0.001\", 2.49Mio)"} `

**Comment by btry** [comment]
Bonjour

C'est un bug d'upgrade que j'ai mis un certain temps à trouver.

Vous devez modifier la structure de la table glpi_plugin_formcreator_issues : ses colonnes ne sont pas dans le bon ordre, et une requête SQL dépend du respect de cet ordre.

Pour Réarrangez l'ordre des colonnes pour qu'il respecte la structure de la téble telle qu'elle est définie dans le fichier .sql dans le dossier install du plugin.

Ensuite videz la table de son contenu, mais ne la supprimez pas. 

Enfin, allez dans les actions automatiques de GLPI, faite une recherche avec le mot formcreator. Vous aurez 1 action automatique affichée : syncissues. Forcez son exécution.

Le problème sera résolu.

Dans la foulée, vérifiez aussi la structure de la table glpi_plugin_formcreator_formanswers. Il se peut qu'elle diffère de la structure fixée dans le fichier .sql. Si il y a une différence, veuillez ouvrir un autre ticket pour aborder ce problème.

**Comment by btry** [comment]
Note : le bug d'upgrade a été corrigé, mais ceux qui ont déjà upgradé au dela d'une certaine version (2.8.0 de mémoire) resteront impactés tant qu'ils n'auront pas exécuté la procédure manuelle ci dessus.

Les autres (install fraiche ou upgrade à partir de versions plus anciennes que <2.8 vers 2.8.4) ne seront pas impactés. (la 2.8.4 n'est pas encore releasée)

**Comment by tguichard25** [comment]
Merci,

Tout fonctionne parfaitement maintenant.

Cordialement,

Tristan GUICHARD
MUTUALITE FRANCAISE COMTOISE
Technicien spécialiste infrastructure
Système d'information
67 rue des Cras
25041 BESANCON CEDEX
Tél : 03 81 65 80 32
Mobile : 06 78 70 01 24
www.mutualite-comtoise.fr<http://www.mutualite-comtoise.fr>

[FB-f-Logo__blue_1024]<https://fr-fr.facebook.com/mutualite.comtoise>[TwitterLogo_#55acee]<https://twitter.com/mutcomtoise> [In-2C-115px-R] <https://www.linkedin.com/company/mutualite-comtoise>

De : btry <notifications@github.com>
Envoyé : lundi 1 juillet 2019 14:01
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : Tristan GUICHARD <t.guichard@mut25.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Impossible de voir certain ticket dans l'interface simplifiée (#1441)


Bonjour

C'est un bug d'upgrade que j'ai mis un certain temps à trouver.

Vous devez modifier la structure de la table glpi_plugin_formcreator_issues : ses colonnes ne sont pas dans le bon ordre, et une requête SQL dépend du respect de cet ordre.

Pour Réarrangez l'ordre des colonnes pour qu'il respecte la structure de la téble telle qu'elle est définie dans le fichier .sql dans le dossier install du plugin.

Ensuite videz la table de son contenu, mais ne la supprimez pas.

Enfin, allez dans les actions automatiques de GLPI, faite une recherche avec le mot formcreator. Vous aurez 1 action automatique affichée : syncissues. Forcez son exécution.

Le problème sera résolu.

Dans la foulée, vérifiez aussi la structure de la table glpi_plugin_formcreator_formanswers. Il se peut qu'elle diffère de la structure fixée dans le fichier .sql. Si il y a une différence, veuillez ouvrir un autre ticket pour aborder ce problème.
