### ISSUE TITLE
V2.8.1 - groupe valideur de la sous entité non disponible

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1444]
Bonjour,
Afin de clarifier l'usage de certains formulaires, nous avons créé une entité fille et dans cette entité, les formulaires et les groupes (demandeurs et valideurs).
Ces groupes ont des utilisateurs.
Les formulaires sont uniquement accessibles à ces groupes (ça fonctionne)

si je veux que mon formulaire puisse être validé par le groupe demandeur de cette entité fille, lorsque je choisis "valideur : groupe" et que je déroule la liste des groupes, je n'ai que les groupes de l'entité racine et aucun de l'entité fille pour laquelle les formulaires sont créés (ils sont bien sur l'entité racine>fille et j'ai rajouté la récursivité même si en principe il n'y a pas lieu n'ayant pas d'entité fille-fille).
Je suis bien placé dans l'entité fille pour faire mes changements.

De plus, je ne peux pas changer l'entité du formulaire, il m'est indiqué que je n'ai pas suffisamment de droits ... en SuperAdmin :D

Merci pour votre aide et corrections

**Comment by btry** [comment]
Bonjour

Pouvez vous utilsier une instance de test et utilsier la branche develop du plugin pour vérifier que le souci existe toujours ?

**Comment by Sicoval31** [comment]
sur une base de test glpi 9.4.2
avec formcreator en 2.8.2 : même problème
avec FC develop (2.8.3) : même problème

j'ai cru voir une version taguée 2.9.0 ...

**Comment by btry** [comment]
Bonjour


La version 2.9.0 est sur les rails. Il faudrait tester celle ci, car je ne pense pas faire de nouvelle release pour la série 2.8.x.

**Comment by btry** [comment]
J'ai fait un  test de transfert de formulaire d'une entité vers une autre, ça a fonctionné (version 2.9.0 en cours de développement). Je pense que le souci sera résolu avec cette future version.

**Comment by btry** [comment]
Bonjour

A défaut de retour de votre part, je ferme ce ticket. Vous pouvez en ouvrir un autre si le problème persiste.
