### ISSUE TITLE
Ticket destination selon valeur d'un champ

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1445]
Bonjour,
est-il possible, sinon serait-il possible, de pouvoir générer un ticket selon la réponse à une question ?

Par exple, j'ai une question sur la téléphonie. Je souhaite que le groupe responsable ne recoive un ticket QUE si une réponse est apportée à la question.
si je défini un destinatiare précis mais que la réponse est vide, le groupe va recevoir un ticket ... vide.
Je souhaiterai éviter cela. Le ticket ne serait donc créé QUE s'il y a une réponse à la question.
Le TOP serait de pouvoir envoyer un ticket(1 seule destination configurée) à tel ou tel groupe selon la réponse à une question ...

**Comment by btry** [comment]
Bonjour

Il s'agit de générer une cible quand une condition est remplie. Ce n'est pas encore implémenté.

En revanche on pourrait peut être classer la génération de cible vide comme étant un bug.

J'imagine que vérifier que les questions remplissant une cible sont visibles ET contiennent quelque chose pourrait résoudre le souci.

**Comment by detruxdeveloper** [comment]
Hello btry,

Is there any way I can help (financially or by developing)? Form Creator has helped me immensely but this is the only feature that is missing for my business.

**Comment by btry** [comment]
Hi

Your contribution is welcome, either by developing yourself the feature, either by sponsoring it.

### sponsoring

contact us at contact@teclib.com

### development

at time of writing this message, new features must be based on the **support/2.9.0 branch** . Fork the project, and begin to hack. If you have questions, feel free to ask. I cal already tell you how I see the general direction of the development.

Do not forget to follow conventional commits and add unit tests with atoum. I worked a lot to improve and complete them, and there is still a lot to do. I wish to not reduce the coverage at least.

**Comment by msizec** [comment]
+1 pour cette feature
Cest plutot meme un manque actuellement 

En tout cas +1 pour formcreator quoiqu'il en soit et aux dév & users derrière !

**Comment by btry** [comment]
Bonjour

La focntionalité est désormais implémentée. Il est possible de définir des conditions sur les objets cible (ticket ou changement) comme on le ferait pour afficher / cacher des questions ou des sections. Quand la condition est évaluée à vrai, alors la cible est générée, sinon elle est ignorée.
