### ISSUE TITLE
Problème d'affichage pour TextArea

### ISSUE THREAD

**Issue by Laurette57** [pluginsGLPI/formcreator#1448]
Bonjour, 

J'ai remarqué un petit soucis d'affichage pour le champ TextArea. Dans la partie ticketing, les balises html p et /p apparaissent. 

Edit: Ce n'est pas le cas pour les notifications par mail

![image](https://user-images.githubusercontent.com/48410676/60731804-c69ab480-9f48-11e9-8612-19b42128be33.png)

J'ai un peu cherché pour corriger le problème mais j'ai pas pu trouver la classe correspondante, et mon niveau en php n'est pas fameux.

Version de GLPI 9.4
Version de formcreator : 2.8.3

Merci pour votre temps.
Laura

**Comment by btry** [comment]
Bonjour

Une librairie utilisée par GLPI peut impacter cet affichage. Vous utilisez probablement un modèle personalisé pour le ticket cible (sans le tag ##FULLFORM##) et avec du code HTML. 

Dans ce cas il est facile de se retrouver avec du code HTML non valide à cause d'imbrications de balises (P imbriqué dans P par exemple). Votre problème semble bien correspondre à ce scénario.

Vous arriverez peut être à contourner en éditant le code HTML du modèle de ticket cible, à l'aide de l'éditeur riche. Enlevez les balises P qui pourraient entourer le tag de la question "description".

**Comment by Laurette57** [comment]
Bonjour,

Effectivement je n'utilise pas le tag  ##FULLFORM##, mais les tags personalisés. 
J'ai complètement réécrit le forumaire en HTML sur un éditeur et le problème d'affichage s'est résolu.

Merci pour votre réponse rapide :)
Laura
