### ISSUE TITLE
 Validation error for integer field

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/formcreator#1449]
In an integer field, inserting points or bars does not report the error.

![Erro Validator](https://user-images.githubusercontent.com/30185683/60748654-7d595d80-9f66-11e9-9908-040f90520084.png)

**Comment by btry** [comment]
Hi

The checks of the inputs occur when the user submits the form, not before.

Creating the feature to check in real time all inputs is quite complex because the plugin should check all constraints (regex, min / max values,...)

**Comment by mrcssilvasouza** [comment]
Hi Btry

You did not understand When I click Send, it does not display the error. Nothing happens.

**Comment by btry** [comment]
Hi

Are the answers rejected anyway ?

**Comment by mrcssilvasouza** [comment]
The form is not created. If you have an attachment, the document is inserted into the Documents module, and the form remains open with all fields filled in and the fields integer empty. This is bad for the user, it is important that the popup appears with the error.

**Comment by btry** [comment]
Hi

I'm trying with a simple form : only 1 integer question. If I type an invalid integer, I actually get the error message.

I tried with the release 2.8.3 and the develop branch, both on GLPI 9.4.3.


![image](https://user-images.githubusercontent.com/14139801/60867140-6e0a3680-a22a-11e9-9a20-4774b4af2802.png)

**Comment by btry** [comment]
Please disable all other plugins and see if the bug persists.

**Comment by mrcssilvasouza** [comment]
That's how it works. But put numbers with points, there will be no error. Point is not integer!

**Comment by btry** [comment]
Hi

Well.. I got the point.. litterally :)

Can you try the above fix and feedback ?

**Comment by mrcssilvasouza** [comment]
Thank you

After change, it works perfectly.
