### ISSUE TITLE
User response type default entity

### ISSUE THREAD

**Issue by Alysson-san** [pluginsGLPI/formcreator#1451]
Good morning, dear, if you can help me with the formcretor I thank you very much, the situation is this, I have a public form where I put a question with type "Select" and I put some options, when I go to Destination> Call opening has an option of "User response type default entity", when I put this option "User type question" appears but only the message "no results found" appears.

Glpi 9.4.3
FormCreator 2.8.3

![formcreator](https://user-images.githubusercontent.com/52745694/60972949-9d3da800-a2fd-11e9-8dfa-0c2725361ae0.JPG)

**Comment by btry** [comment]
Hi

The dropdown shows the questions of type GLPI Object, itemtype User. If no such question exist in your form, then the list is empty.
