### ISSUE TITLE
2 questions à propos de formcreator

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1452]
bonjour
est-il possible de : 

choisir dans un champ du formulaire un observateur spécifique (qui sera donc observateur du ticket généré par le formulaire)
caché sur la page d'accueil certains formulaire en fonction du login ou du groupe d'appartenance
merci et bravo pour ce plugin que nous utilisons énormément

**Comment by btry** [comment]
Bonjour 

1 - il vous faut au moins une question de type GLPI Object / User ou Acteur. Dans le ticket cible, ajoutez un observateur à partir de la réponse à une question, et choisissez la question précédement créée.

2 - pour le moment l'accès aux formulaires peut être restreint en fonction des profils utilsiateur. La prise en charge d'autres critères requiert un développement.

**Comment by btry** [comment]
Bonjour

A défaut de retour, je suppose que les questions sont  résolues.
