### ISSUE TITLE
hidden unless does not work if condition is other question with LDAP Select 2.8.3

### ISSUE THREAD

**Issue by achekmez** [pluginsGLPI/formcreator#1454]
hidden unless does not work if condition is other question with LDAP Select with plugin version 2.8.3 glpi version 9.4.3

**To Reproduce**
1. make question 
type = LDAP Select, 
filter = (& (samaccountname=*) (& (displayName=*) (&(objectCategory=person)(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:= cn=DG MP All Staff, OU=SharedMailboxes,OU=Moscow, DC=mpmsk, DC=corp)(givenName=*)(sn=*))))
Attribute = (LDAP) City
2. make second question
show field = hidden unless
1st question = (in my case for ex) Moscow
3. try the form

expecting when in 1st question choose Moscow 2nd question should appear - but it does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/21035924/61704787-2ff23400-ad4d-11e9-8ec3-52666b55a86b.png)
![image](https://user-images.githubusercontent.com/21035924/61704829-49937b80-ad4d-11e9-88a0-a4508d448751.png)
![image](https://user-images.githubusercontent.com/21035924/61704861-5b751e80-ad4d-11e9-855a-484ed35ddb5b.png)
![image](https://user-images.githubusercontent.com/21035924/61704880-6760e080-ad4d-11e9-9741-f524b90434ae.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome

it workes in plugin version 2.5.2 glpi ver 9.2.2

**Comment by btry** [comment]
Hi

Comparisons are unsupported for this type of questions. It is unexpected that someone used them. 

Please test this fix and feedback. I believe this should be sufficient to make it work.

https://github.com/pluginsGLPI/formcreator/pull/1457

**Comment by btry** [comment]
Patch successfully tested
