### ISSUE TITLE
Problem pasting images into tickets

### ISSUE THREAD

**Issue by victorgrechi** [pluginsGLPI/formcreator#1455]
We're having a problem when someone tries to paste a image at the description of a ticket. When they save the ticket, we don't receive the image correctly.

1 - Opening the ticket:

![image](https://user-images.githubusercontent.com/47543344/61814929-88920180-ae1f-11e9-9e0a-ad796b83ff6e.png)
![image](https://user-images.githubusercontent.com/47543344/61814943-8e87e280-ae1f-11e9-827a-8a3bee110538.png)

2 - We receive her like this:

![image](https://user-images.githubusercontent.com/47543344/61814991-a6f7fd00-ae1f-11e9-9277-e98af6144496.png)

We've noticed that this only happens when the image is too big.

We're using the version 2.8.3 of FormCreator.

**Comment by ddurieux** [comment]
It's a problem with size of field, must define the field `glpi_plugin_formcreator_answers.answer` in `longtext` instead `text`

**Comment by btry** [comment]
Hi, 

thanks @ddurieux a quick check shows you're right, this is only a truncated string problem.

**Comment by btry** [comment]
Due to schema change, the fix will be available in 2.9. Not earlier.

**Comment by btry** [comment]
fix: 71284f6ad8cbdba221f54633459598c2f53cdf90

**Comment by ddurieux** [comment]
;)
