### ISSUE TITLE
disabling validation option

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1459]
**Is your feature request related to a problem? Please describe.**
Is there any way to disable that feature from user bar?
**Describe the solution you'd like**
![111111](https://user-images.githubusercontent.com/35932698/62244253-b52db680-b3e7-11e9-80af-fd4d9efd1bcc.PNG)
I want to disable validate counter.

**Comment by btry** [comment]
Hi

Currently there is no way to hide this counter. You may consider to comment the related code, but be careful when you upgrade the plugin.

**Comment by reinethernal** [comment]
Could you tell me please where can i find it?

**Comment by btry** [comment]
Hi

Check in PluginFormcreatorWizard::showTicketSummary()

**Comment by vincentdeniau** [comment]
Hello @reinethernal ,

You can juste hide the button by adding this to your entity UI customization :

`#formcreator_servicecatalogue_ticket_summary .status_validate{
    display: none;
}`

**Comment by btry** [comment]
Hi

This is a good idea, and not too much invasibe making the patch maintainable for a while.

I think I can close this question now.
