### ISSUE TITLE
Problème de remontés de données dans un formulaire anonyme.

### ISSUE THREAD

**Issue by biet-j** [pluginsGLPI/formcreator#146]
Bonjour,

Je rencontre un problème avec un formulaire anonyme avec des champs pointants dans la base de donnée de GLPI
Si je suis connecté et que j'accède au formulaire tout marche bien.
Si je suis non connecté, j'obtiens une erreur "Loading Failed"
![bug_formulaire anonyme](https://cloud.githubusercontent.com/assets/14232775/11370545/92410ade-92c4-11e5-8933-6a4848bcc3ed.png)

Il est vrai que l'accès anonyme qui permet de selectionner parmis des données de la BDD est un peu contracditoire, mais peut etre une option de sécurité que chaque utilisateur pourrait ou non valider ?

Cordialement.

**Comment by neeftarah** [comment]
Bonjour,

C'est effectivement un point que nous n'avions pas re-tester après le portage en 0.85 et suites aux modifications sur la gestion des droits sur cette version de GLPI.

Cette remonté de données fonctionnais en 0.84, mais en 0.85 un grand nombre de contrôles de sécurité ont été ajouté sur chaque éléments de GLPI. Toutefois avec le nouveau fonctionnement des droits sur GLPI ça risque d'être compliqué.

Je vait voir si je peut réactivé cette fonctionnalité.
Si c'est effectivement un peut douteux au niveau sécurité, ça reste de l'affichage et c'est vous en tant qu'administrateur qui prenais la décision d'afficher ou non ces données dans votre formulaire de façon anonyme.

Cordialement,
Jérémy

**Comment by biet-j** [comment]
Merci, à vous
