### ISSUE TITLE
Assign ticket from form to pc

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1462]
**Is your feature request related to a problem? Please describe.**
The ability to link ticket created from a form to a computer stored in glpi
**Describe the solution you'd like**
When creating a ticket from the form, the ticket is not attached to the computer or any other device, although the owner is appointed and the specialist responsible for the equipment is also
**Additional context**

![image](https://user-images.githubusercontent.com/35932698/62369862-a820dc80-b539-11e9-93b2-38a873992a1d.png)
![image](https://user-images.githubusercontent.com/35932698/62369937-dc949880-b539-11e9-8b53-bf2d39569a38.png)

**Comment by reinethernal** [comment]
I can re-send images in english if this could help)

**Comment by btry** [comment]
Hi,

Yes, please. I'm not able to read Russian.

**Comment by reinethernal** [comment]
![image](https://user-images.githubusercontent.com/35932698/62371785-5c246680-b53e-11e9-8236-eeccb42c9ef4.png)


Sorry, but for the second screenshot there;s no english translation. I can do it manually.
![image](https://user-images.githubusercontent.com/35932698/62371984-e66cca80-b53e-11e9-855a-5ca7d69f784f.png)

First field marked by * is: Room nubmer
The second field is the list of available pc's (there's pc already chosen)
Third is with the list of displays available for user to choose
Fourth is for comments.

**Comment by reinethernal** [comment]
User than pc is assigned to is my user. Profile which i try create ticket from has the same rights as post-only.

**Comment by reinethernal** [comment]
Is there any chance that i can solve my problem?)

**Comment by btry** [comment]
Hi

Please be patient, your issue is in the queue, community support is at best effort. If you need urgent support, please consider subscribing a support plan here: https://glpi-project.org/subscriptions/ or contact us at contact@teclib.com

**Comment by reinethernal** [comment]
> Hi
> 
> Please be patient, your issue is in the queue, community support is at best effort. If you need urgent support, please consider subscribing a support plan here: https://glpi-project.org/subscriptions/ or contact us at [contact@teclib.com](mailto:contact@teclib.com)

I understand, but that would be nice to have any feedback)

**Comment by reinethernal** [comment]
Hi! Any news?

**Comment by btry** [comment]
Hi

No news for now. 

Again, of you need this feature un a short delay, consider to sponsor it. This is still possible for the version 2.9. I wish to release it before end of 2019.

**Comment by btry** [comment]
Hi

I think that the version 2.9 (branch support/2.9.0) contains the feature you need. 

With this version you can assign an asset from a question to the target ticket. The asset will be associated to the generated ticket and will be visible in the **Items** tab of this ticket.

:warning: the version 2.9.0 is still in development. It is not ready for production. You're welcome to test it and feedback bugs you may find.

**Comment by reinethernal** [comment]
Thx, will try in test installation) thank you)

**Comment by reinethernal** [comment]
Yep, that works!

**Comment by btry** [comment]
Hi

Thanks for your feedback.
