### ISSUE TITLE
add a question that only accepts a valid ip address

### ISSUE THREAD

**Issue by marty1027** [pluginsGLPI/formcreator#1466]
Good evening,

I´m trying to create a question where the field only accepts valid ip address. 

I have created a integer field with this regular expression:

#^((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))*$#

but not only the field still accepts ip address like 256.256.256.256 

but prints only the first 3 numbers.

please help me kkkkk. I´m knew at this and trying to put this to work.

**Comment by btry** [comment]
Hi

For community support, please go to the forum dedicated to GLPI : https://forum.glpi-project.org/

You may also search on internet for such regex. This is a common need.
