### ISSUE TITLE
Search by tags

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1469]
That would be nice to have an option to search forms by list of tags. i.e. we have form named "computer malfunction". User enters in search such tags like computer/pc/error/mouse/keyboard etc, and a form "computer malfunction" appears in list.

**Comment by btry** [comment]
Hi

Where ? 
- in the form designer (for admins) 
- in the service catalog for requesters with simplifid interface
- or in the helpdesk  (requesters with normal interface)

**Comment by reinethernal** [comment]
> Hi
> 
> Where ?
> 
> * in the form designer (for admins)
> * in the service catalog for requesters with simplifid interface
> * or in the helpdesk  (requesters with normal interface)

Hi, in the service catalog for requesters with simplifid interface provided by your plugin

**Comment by btry** [comment]
There is the search engine, but unfortunately it does not works as good as expected, due to constraints in Mysql's search features. Why not use the form categories ?

**Comment by reinethernal** [comment]
Because according to my experience, users try to search anything but not that they need.

**Comment by btry** [comment]
Well... This was an unexpected answer :rofl: 

The feature you describe should be satisfiled by the search engine. Searches are done in form name, description, question names and, if I remember well, section names.

As I said, the search engine has some issues, and I did not foud yet an acceptable solution. For now it seems I cannot rely on something else than some search engine written in PHP, with the performance hit this may introduce.

**Comment by reinethernal** [comment]
So anything i type in description will help to search form needed?

**Comment by btry** [comment]
yes

**Comment by reinethernal** [comment]
Thank you! Creating invisible field filling with needed words really works.

**Comment by btry** [comment]
:+1: 

Then I guess your problem i adresses ?

**Comment by reinethernal** [comment]
Yes, thank you again)
