### ISSUE TITLE
Multi-Column Form

### ISSUE THREAD

**Issue by v2ip** [pluginsGLPI/formcreator#1470]
Form sections to be optionally organized in columns on the form.  A check mark can be used in the edit section screen to make the section appear next to instead of below the previous section. 

E.g...

Form Title 1 
Section 1
Question 1
Section 2
Question2 

Would become with Section 2 Check marked...
          Form Title 1
---------------------------
|Section1    |     Section2    |
|Question1 |     Question2 |
---------------------------

**Comment by sebastianSanchez23** [comment]
Hi,
Any updates on this feature, I just started using the plugin and would lik eto know if it's possible to change the layout of the questions?

**Comment by btry** [comment]
Hi

You may configure the content of the target by replacing the tag ##FULLFORM## with the content of your choice. Just ensure you insert the tags of the question which shall show in the generated target.

**Comment by sebastianSanchez23** [comment]
Thanks will do that !
