### ISSUE TITLE
BUG - Put "RN" in Questions with type "Text Area"

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1474]
Hello

I use a form with a "Text Area" question and some required fields.
I noticed that when the user doesn't respond to a required field and is alerted by GLPI, the "Text Area" question includes an "RN" in the text if it has an Enter.

Reproduce
1 - Go to the forms
2 - Fill in the fields and do not mark a required field
3 - Check if the Text Area field included "RN" in place of Enter

GLPI Version: 9.3.3
Formcreator: 2.8.3

![Test Field](https://user-images.githubusercontent.com/35368369/63356370-09202100-c33e-11e9-9fcc-c162f3fb8d3a.gif)

**Comment by btry** [comment]
Hi

Please add the version of GLPI and the version of the plugin.

**Comment by phamorais** [comment]
Hi @btry 

Done!

**Comment by Kelvin-Pereira** [comment]
Hello there are some solutions for this:

GLPI from what I could see it creates form inputs by calling methods by pulling parameters from the database input.
In the root folder of GLPI plug-ins / formcreator / inc / Field you will find the files responsible for passing the parameters to the method responsible for assembling the input Html :: inputName and returning to view, eg:
![Screenshot_1](https://user-images.githubusercontent.com/42652204/63427372-5d350f00-c3eb-11e9-9c0b-81d03a365b70.png)

We may notice that it does not pass the required parameter, but we can get it.
  The left Array is in a form view that has a textarea as required, we can note that the Array Field has the information we need to mount the input as a requider.
![true](https://user-images.githubusercontent.com/42652204/63427427-7ccc3780-c3eb-11e9-8f36-3d19b7aac042.png)

So we just need to assemble a simple logic and pass this true case information to the method responsible for creating the input.
![logica simples](https://user-images.githubusercontent.com/42652204/63427479-953c5200-c3eb-11e9-8bde-f8c8e24ad26e.png)

Ok now let's enter the Html :: textarea method to put the required if condition is true
![metodo](https://user-images.githubusercontent.com/42652204/63427572-d2a0df80-c3eb-11e9-8513-43c0ab1ca3c9.png)

Ok here we are right we can see that the method is expecting an Array $ options [] which below is merged with the Array $ p [], ok in $ display and mounted the input and there we will put the required if it be true and we can do this:
![input](https://user-images.githubusercontent.com/42652204/63427649-024fe780-c3ec-11e9-8ea4-7fb643f8f08b.png)

Now let's enter the form and try to submit it with the empty field.
![Screenshot_2](https://user-images.githubusercontent.com/42652204/63427698-23183d00-c3ec-11e9-8127-61743b805707.png)

Ready the form is now submitted only if the capo is filled, now this input does not risk getting the rnrn
: remarks now repeat this for all inputs

Now let's see the simplest form and I found no problem:
  Let's go to the inc / form.class.php file and look for the saveForm method
Now look for Toobox :: stripslashes_deep ($ input);
![Screenshot_3](https://user-images.githubusercontent.com/42652204/63427776-53f87200-c3ec-11e9-9428-11b8fb59e623.png)

Let's leave it like this
![Screenshot_4](https://user-images.githubusercontent.com/42652204/63427831-7be7d580-c3ec-11e9-8b03-b29f13aa962a.png)

Ready now when you submit a form with an unfilled required field it will return as you left it

sorry about my English XD.

**Comment by btry** [comment]
Hi 

Thank you for your invesstigation.

We need to check if the bug occurs with both GLPI 9.3 and GLPI 9.4. If not, there is need to check the version of GLPI with the constant GLPI_VERSION
 and the php function version_compare().

I cannot read in deep your post @Kelvin-Pereira but if your fix requires a fix in the code of the plugin, please consider to fork it and create a PR. I'm for now too busy to handle this bug quickly.

**Comment by phamorais** [comment]
@btry @Kelvin-Pereira 

Hello

Apply a suggested fix to and it worked perfectly

**Comment by btry** [comment]
Hi

I did a check with GLPI 9.4. The bug does not reproduces for me.

As GLPI 9.3 is no longer maintained and the bug seems to occur when rich tect mode is disabled, I thihnk I won't search a fix for this issue. In GLPI 9.4 and later, the rich text mode is always enabled, it is no longer optional, and this solves many problems like this.

I recommend users to consider upgrade to the latest release of GLPI.

**Comment by Kelvin-Pereira** [comment]
muito bom, @btry   obrigado pelo feedback.

**Comment by Kelvin-Pereira** [comment]
Very good, @btry thanks for the feedback.

**Comment by phamorais** [comment]
Thx!
