### ISSUE TITLE
Acteur depuis la question ?

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1475]
bonjour,
dans un formulaire j'essaie d'utiliser un observateur avec le choix :
"acteur depuis la question" mais je ne peux pas choisir dans la liste des questions, j'ai uniquement la section que je ne peux même pas utiliser,
pareil pour "groupe depuis la question" ou "personne depuis la question"

est-ce un bug ou une mauvaise utilisation ?
je vous remercie

**Comment by btry** [comment]
Bonjour

Pour utiliser **Acteurs depuis la question** vous devez avoir une question de type **acteurs** dans le formulaire. Sinon la liste des questions possibles sera vide.

Pour **Groupes depuis la question** c'est sans doute le même problème. Vous n'avez pas de question de type Objet GLPI / Groupe

Enfin, pour **Personne depuis la question** vous devez avoir une question de type Objet GLPI / Utilsiateur.

**Comment by defaliz** [comment]
j'ai trouvé un poste qui expliquait l'utilisation..
je ferme donc le post
Alain

**Comment by defaliz** [comment]
parfait 
merci pour cette réponse 

Alain Defrance 
Chef de service des systèmes d'informations 
01 47 03 89 11 
alain.defrance@inha.fr 



De: "notifications" <notifications@github.com> 
À: "pluginsGLPI" <formcreator@noreply.github.com> 
Cc: "Alain Defrance" <alain.defrance@inha.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 20 Août 2019 17:05:30 
Objet: Re: [pluginsGLPI/formcreator] Acteur depuis la question ? (#1475) 



Bonjour 

Pour utiliser Acteurs depuis la question vous devez avoir une question de type acteurs dans le formulaire. Sinon la liste des questions possibles sera vide. 

Pour Groupes depuis la question c'est sans doute le même problème. Vous n'avez pas de question de type Objet GLPI / Groupe 

Enfin, pour Personne depuis la question vous devez avoir une question de type Objet GLPI / Utilsiateur.
