### ISSUE TITLE
Version 2.8.4 : Menu dupliqué avec compte post-only

### ISSUE THREAD

**Issue by Maximumi** [pluginsGLPI/formcreator#1480]
**Description du bug :**
Le menu "Formulaires" situé dans la barre est dupliqué

**Pour reproduire :**
1. Suppression ancien dossier plugin version 2.8.2
2. Décompression de la nouvelle version 2.8.4 
3. Procédure de mise à jour du plugin via GLPI
4. Vider la cache du navigateur client
5. Connexion avec un utilisateur post-only
4. Menu dupliqué

**Capture :**
![image](https://user-images.githubusercontent.com/18038061/63574953-3d3b5200-c589-11e9-9216-f0ffa519c961.png)

**Client / Navigateur :**
 - Chrome Version 76.0.3809.100 (Build officiel) (64 bits)
 - Firefox 60.8

**Serveur :**
 - GLPI 9.4.2
 - Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
 - Debian 9.9
 - Apache 2.4.25-3+deb9u7
 - PHP 7.0.33-0+deb9u3

**Comment by btry** [comment]
Bonjour

le code qui affiche cette entrée de menu n'a pas changé depuis un grand nombre de releases .... Comment ça peut arriver ? Je vais tenter de reproduire

**Comment by prohand** [comment]
Bonjour,

Je confirme avoir le même problème.

Merci

**Comment by tsmr** [comment]
$PLUGIN_HOOKS['add_javascript']['formcreator'][] = 'js/scripts.js.php'; appelé 2 fois dans le setup..

https://github.com/pluginsGLPI/formcreator/blob/develop/setup.php#L209

https://github.com/pluginsGLPI/formcreator/blob/develop/setup.php#L243

**Comment by prohand** [comment]
Effectivement quand j'enlève celui de la ligne 243 par exemple, j'en ai plus qu'un seul affiché

**Comment by btry** [comment]
Bonjour,

Je ferai une release  2.8.5 lundi pour corriger ce souci. Merci @tsmr d'avoir pris le temps de chercher la cause du bug.

**Comment by btry** [comment]
fix: https://github.com/pluginsglpi/formcreator/commit/4075b1e

Une release 2.8.5 va être publiée dans quelques minutes avec ce fix.
