### ISSUE TITLE
Validation du formulaire par un groupe

### ISSUE THREAD

**Issue by amorice95000** [pluginsGLPI/formcreator#1482]
Bonjour,
La validation d'un formulaire par un groupe semble dysfonctionner.
L'utilisateur (membre du groupe valideur) voit bien la demande à valider mais lorsqu'il clique sur la demande, il obtient le message "Vous n'avez pas les droits requis pour réaliser cette action". 
Il a bien le profil "Observateur".
Cela fonctionne sans soucis lorsque le formulaire est paramétré avec une validation du type "Utilisateur".
Nous sommes en version GLPI 9.4.3, version du plugin FormCreator 2.8.4
Cordialement,
[20190827_BugFormulaire-validationGroupe.pdf](https://github.com/pluginsGLPI/formcreator/files/3546351/20190827_BugFormulaire-validationGroupe.pdf)

**Comment by Belface** [comment]
Bonjour
je constate le même problème qu'**amorice95000**

Pour reproduire :
- Création de 3 utilisateurs (profil self-service, même entité)
- J'ajoute User1 et User2 dans un groupe
- Je paramètre ce groupe comme valideur d'un formulaire
- Je me connecte à GLPI avec le compte User3, renseigne et envoie le formulaire
- Lorsque je me connecte à GLPI avec User1 (ou User2), je vois un formulaire à valider ; lorsque j'essaye d'y accéder :

![Capture](https://user-images.githubusercontent.com/55400519/65222081-a184ff00-dabe-11e9-85a5-ee67adb7ed25.JPG)

Mes versions : GLPI 9.4.2 / FormCreator 2.8.5

Merci par avance

**Comment by btry** [comment]
Bonjour

Je suis en train de chercher, et j'arrive à un point important à vérifier. User1 et USer2 ont ils le droit dz valider des incidents ou des demandes ?

Quand on est membre d'un groupe validateur, il y a cette vérification en plus, par rapport à un utilsiateur validateur. Je pense qu'il faut harmoniser les 2 cas d'ailleurs.

**Comment by btry** [comment]
Au vu de l'historique des changements, la vérification du droit de validation pour valider une réponse devrait toujorus être faite. Du coup, je dois faire une correction qui va (je pense) "amplifier" votre problème. 

J'attends la réponse à ma question (post précédent). Je m'attends à ce que votre souci soit simplement l'absence de ce droit de validation dans le profil de User1 et User2.

**Comment by Belface** [comment]
Bonjour et merci de votre réponse

Voici les informations demandées ::

![Capture](https://user-images.githubusercontent.com/55400519/66900669-8c3bbb80-effd-11e9-9613-8b204308baf6.JPG)

![Capture2](https://user-images.githubusercontent.com/55400519/66900677-8e057f00-effd-11e9-9b7f-95ddb3fb045e.JPG)

D'après la deuxième capture, les droits ont bien l'air d'être en place

**Comment by btry** [comment]
En effet, je continue de cherche.

**Comment by Belface** [comment]
Autres tests effectués à l'instant ::
- J'ajoute le profil **Admin** à User1 (ou User2) et me connecte avec ce profil : même résultat (Pas les droits requis...)
- J'ajoute le profil **Super-Admin** à User1 (ou User2) et me connecte avec ce profil : ça marche (j'ai le droit d'accepter ou refuser la demande en attente de validation)

**Comment by amorice95000** [comment]
Bonjour,
Même chose chez moi :
- les users 1 et 2 sont bien dans la même entité
- ils ont bien les droits de valider
- le user 1 a le profil Self Service
- le user 2 le profil Observateur

**Comment by btry** [comment]
@Belface : Avoir plusieurs profils pour un même utilisateur n'a pas d'importance. Un seul profil n'est actif à un instant T, ils ne se cumulent pas.Si vous ne saviez pas cela, je vous invite à vérifier le profil actif au moment où vous reproduisez le bug. Sinon, je risque de chercher un bug qui n'existe pas :)

**Comment by Belface** [comment]
Je le savais merci.
Mon explication n'était peut être pas assez clair :: Je me connecte avec le compte User1 ::
- Je sélectionne le profil Self_Service -> Erreur de droits
- Je sélectionne le profil Admin -> Erreur de droits
- Je sélectionne le profil Super-Admin -> Ca marche

**Comment by btry** [comment]
d'accord. Je prends en compte ces résultats

**Comment by Belface** [comment]
Rebonjour
voici un avancement sur les tests (qui j'espère vous donnera une piste)
J'ai réussi à corriger le problème avec l'utilisation du profil **Admin** en activant l'option "mettre à jour entités" (dans la configuration de ce même profil). Je ne peux malheureusement pas faire le test sur le profile **Self_Service**, celui-ci étant en interface simplifié.

![Capture](https://user-images.githubusercontent.com/55400519/66908445-63222780-f00b-11e9-9f30-34acca2e89a0.JPG)

**Comment by btry** [comment]
Je pense avoir trouvé. Pouvez vous tester ce correctif ?

https://github.com/pluginsGLPI/formcreator/pull/1541

**Comment by amorice95000** [comment]
Bonjour,
TEST fait à l'instant, cela fonctionne.
Merci pour le correctif.
Bonne journée

**Comment by btry** [comment]
Merci pour le retour.

**Comment by Belface** [comment]
Désolé pour le délai
Je confirme que le correctif a corrigé le pb

Merci
