### ISSUE TITLE
Get QuestionRegex from API

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#1483]
**Describe the bug**
`GET /apirest.php/PluginFormcreatorQuestionRegex` fail with  `500 Internal Server Error`.

Server logs:
```
2019/08/28 15:02:43 [error] 1206#1206: *1278 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PluginFormcreatorQuestionParameter::__construct(), 0 passed in /home/teclib/Main/html/glpi-fusion-94/inc/api.class.php on line 1139 and exactly 2 expected in /home/teclib/Main/html/glpi-fusion-94/plugins/formcreator/inc/questionparameter.class.php:59
Stack trace:
#0 /home/teclib/Main/html/glpi-fusion-94/inc/api.class.php(1139): PluginFormcreatorQuestionParameter->__construct()
#1 /home/teclib/Main/html/glpi-fusion-94/inc/apirest.class.php(237): API->getItems('PluginFormcreat...', Array, 0)
#2 /home/teclib/Main/html/glpi-fusion-94/apirest.php(48): APIRest->call()
#3 {main}
  thrown in /home/teclib/Main/html/glpi-fusion-94/plugins/formcreator/inc/questionparameter.class.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: *.glpi-fusion-94.local, request: "GET /apirest.php/PluginFormcreatorQuestion/4/PluginFormcreatorQuestionRegex HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "72.glpi-fusion-94.local"
```

**To Reproduce**
Make a `GET` request on `/apirest.php/PluginFormcreatorQuestionRegex`

**Expected behavior**
Response: Collection of PluginFormcreatorQuestionRegex

**Additional context**
I'm trying to use formcreator through the API as a self-service user.
I've already fixed some rights issues (will do a PR later) but this problem seems a bit more complex.

**Comment by btry** [comment]
Hi

This is vert likely causes by a HTTP PUT or POST with inconsistent data. I'll change this to have a more friendly HTTP error code

**Comment by btry** [comment]
Hi

You may implment  PluginFormcreatorQuestion::post_getItem() to automatically add some properties when the object is retrieved from he DB

I would suggest a new key _parameters containing nested arrays, the same way as when an admin saves a question in the form designer. Create a text question and have a breakpoint in PluginFormcreatorQuestion::updateParameters() to see how the arrays is built. The argument is $_POST.

**Comment by AdrienClairembault** [comment]
As `post_getItem` doesn't exit I assumed you meant `post_getFromDB`, however it is not called by the API so it wont work.

I've go the same error for `PluginFormcreatorQuestionRange`.

(Also, why are these two classes necessary ? As far as I can see a question can only have one range and one regex ?).

**Comment by btry** [comment]
Hi

Yes, you're right. this is post_getFromDB() instead of post_getItem().

The api calls getFromDB() to get an item, then post_getFromDB will be called. However if you get items via the Search endpoint, I guess the post_getFromDB is not called.

**Comment by btry** [comment]
Range and regex were columns of the question table but I began to migrate those data in dedicated classes because those constraints must not be handled in the question class (for example : range min / max for integer and float means minimum and maximum accepted values, whereas fir a text field the min and max define the acceptable length of the accepted answer.

**Comment by btry** [comment]
Hi,

I guess the PR #1503 makes this issue obsolete ?

**Comment by AdrienClairembault** [comment]
Indeed, let's close this.
