### ISSUE TITLE
Submit form through API

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#1486]
Unless I'm mistaken, it is not possible to submit a form through the API.

What would be the best way to allow this ?

A quick solution would be to create a new `PluginFormcreatorFormSubmit` object that would call `$form->saveForm($_POST)` inside it's `add` method but this feels a bit hacky.

Do you have any better idea ?

**Comment by btry** [comment]
Hi

The plugin needs some code refactor :
when a user submits a form, we enter in PluginFormcreatorForm::saveForm() where the inputs from the user are validated before calling PluginFormcreatorFormAnswer::saveAnswers()

PluginFormcreatorForm::saveForm() should be (roughly) migrated and refactored in PluginFormcreatorFormAnswer, maybe in PrepareInputrForAdd().

**Comment by AdrienClairembault** [comment]
Closing this as this is now working after your latest changes.
