### ISSUE TITLE
[2.8.4] Default form in service catalog is duplicate

### ISSUE THREAD

**Issue by robsonjorgefernandez** [pluginsGLPI/formcreator#1487]
**Describe the bug**
Default form in service catalog is duplicate when the language is the same of form.

**To Reproduce**
1. Create a form and define a language. E.g _Português do Brasil_
2. Change your language in perfil to _Português do Brasil_

**Expected behavior**
Show only one service form in catalog

**Screenshots**
1. Form in Português do Brasil
![image](https://user-images.githubusercontent.com/16673533/64048093-1a8bd900-cb47-11e9-8c19-14f3a3b8d863.png)
1.1 Service Catalog in Português do Brasil
![image](https://user-images.githubusercontent.com/16673533/64048109-24add780-cb47-11e9-9446-4e0e8d37f3b1.png)
1.2. HTML in Português do Brasil
![image](https://user-images.githubusercontent.com/16673533/64048201-75bdcb80-cb47-11e9-8fc4-4e0a358f75e9.png)

This happen on English language too.
2. Form in English
![image](https://user-images.githubusercontent.com/16673533/64047810-3773dc80-cb46-11e9-8314-e6bd3dcd8d56.png)
2.2 Service Catalog in English
![image](https://user-images.githubusercontent.com/16673533/64047829-43f83500-cb46-11e9-83e8-0229cc6368f9.png)
2.3 HTML in English
![image](https://user-images.githubusercontent.com/16673533/64047892-73a73d00-cb46-11e9-9b92-49a22181636b.png)

**Desktop (please complete the following information):**
 - OS: [Fedora 30 (Workstation Edition)
 - Browser: Chrome
 - Version: 76.0.3809.132 (Official Build) (64-bit)

and

 - OS: Fedora 30 (Workstation Edition)
 - Browser: Firefox
 - Version: 68.0.2 (64-bit)

**Additional context**
<details><summary>My system:</summary>
<p>
<pre>
{
    "glpi": {
        "uuid": "MRaizpbTXfhzZ2L5TTF3oGh69uCqutZNvF2NY6tR",
        "version": "9.4.3",
        "plugins": [
            {
                "key": "formcreator",
                "version": "2.8.4"
            },
            {
                "key": "fusioninventory",
                "version": "9.4+1.1"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "0-500",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "500-1000",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MariaDB Server",
            "version": "10.3.17-MariaDB-log",
            "size": "3815.6",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "Apache",
            "version": "2.4.34"
        },
        "php": {
            "version": "7.1.30",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqlnd",
                "PDO",
                "Phar",
                "posix",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sqlite3",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "xml",
                "xmlwriter",
                "xsl",
                "zip",
                "mysqli",
                "pdo_mysql",
                "pdo_sqlite",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "apcu",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "256M",
                "post_max_size": "20M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "5M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "Red Hat Enterprise Linux Server release 7.7 (Maipo)",
            "version": "3.10.0-1062.el7.x86_64"
        }
    }
}
</pre>

**Comment by btry** [comment]
Hi

The issue is not language dépendant. It was already reported in french (see the issues reported these last few days). I'll release a special 2.8.5 version monday to fix this issue.

**Comment by btry** [comment]
fixed : https://github.com/pluginsglpi/formcreator/commit/4075b1e
