### ISSUE TITLE
Rules are broken because of html tags inserted

### ISSUE THREAD

**Issue by sebelk** [pluginsGLPI/formcreator#1491]
We have a lot of rules based on text patterns in the ticket description that perform tasks such as: assign to group of thecnicians, users, set a category, raise the urgency, etc.

For example:

    `"Area solicitada : Infraestructura"`

In the case of earlier versions (forms 2.6.2)  it has not that issue:

![imagen](https://user-images.githubusercontent.com/4109256/64203085-1de5d400-ce69-11e9-8c46-6100780747be.png)

But now on GLPI 9.4.3 and forms 2.8.3 you can see that some html tags was inserted and hence rules were broken.

![imagen](https://user-images.githubusercontent.com/4109256/64203159-3e159300-ce69-11e9-9ca9-c865f0adac04.png)

![imagen](https://user-images.githubusercontent.com/4109256/64203172-47066480-ce69-11e9-8ea8-caa5ba05f00d.png)

Is it a bug?

**Comment by btry** [comment]
Hi

I guess that with Formcreator 2.6.2 you used GLPI with rich text mode disabled. Please have a look on this setting to ensure I'm right. (you probably used GLPI 9.2 or 9.3)

In glpi you had a setting to enable or disable rich text mode. This setting does not exists anymore and GLPI always runs in rich text mode. Therefore you must now take this into account. This is quite hard to tune business rules as Formcreator adds a layer of complexity with the generated HTML.

Please show your business rule.

**Comment by sebelk** [comment]
Thanks @btry we've found that the field content of table glpi_tickets is parsed. Bases on that we've created regexps and now rules and working fine.

For example creating pattern as:

`/Datos.*Sub Categoria \(SAP - SD\).*Premios.*TITULO/`

HTH

**Comment by btry** [comment]
Hi

Great ! Then I can close this issue.
