### ISSUE TITLE
 Submit a question straight to the top

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1499]
HI
Is it possible to add a button, which allows you to send a question straight to the top? No need to select one by one?

![image](https://user-images.githubusercontent.com/35368369/64789678-32059180-d54b-11e9-82a3-04f46c7934e1.png)

My GLPI Version: 9.3.3
My Formcreator version: 2.8.3

**Comment by resplandeluiz** [comment]
I did like this

add new button in list, 

![image](https://user-images.githubusercontent.com/31370242/66220925-5238f400-e6a4-11e9-9ac8-c06b0ffa9c04.png)

add in rule to new funcionality,

![image](https://user-images.githubusercontent.com/31370242/66221252-00dd3480-e6a5-11e9-9e8a-f6afa64cd673.png)

and logic,

![image](https://user-images.githubusercontent.com/31370242/66221361-341fc380-e6a5-11e9-8d99-604d597ef401.png)

**Comment by btry** [comment]
Hi

Your changes are in a screenshot. Could you fork the project and create a PR ? This is way more efficient to manage contributions.

**Comment by phamorais** [comment]
@resplandeluiz Thaks for u contribuition!

**Comment by btry** [comment]
Hi

The submitted PR was reworked and merged in the incoming 2.9.0. I close this issue. Thank you for your contribution @resplandeluiz
