### ISSUE TITLE
Allow ticket field targeting for answer

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/formcreator#15]
In target destination "ticket", add the possibility to target a specific field to fill with the answer of a specific question.

**Comment by neeftarah** [comment]
Obsolete

**Comment by neeftarah** [comment]
Finaly should be usefull for several fields :

* linked objects (computer, softwares, etc.) from a GLPI Object question
* Category
* Type
* Urgency
* Impact
* Etc.

**Comment by btry** [comment]
done
