### ISSUE TITLE
Masquer barre de recherche

### ISSUE THREAD

**Issue by Aurel2312** [pluginsGLPI/formcreator#1502]
Bonjour,

Est-il possible par défaut de masquer la barre de recherche "Merci de décrire votre besoin ici" qui perturbe nos utilisateurs.
En effet, nous leur mettons à dispositions deux formulaires (un pour les incidents et un pour les demandes), mais ne les voient pas immédiatement car cette barre est entourée de rouge et interpelle plus que les formulaires mis à disposition dessous.

Je vous remercie par avance pour votre retour.

Bonne journée

Aurélien

**Comment by mab18** [comment]
Bonjour,
J'ai exactement la même demande ! et pour aller plus loin : pouvoir activer un formulaire par défaut.
Merci de votre dévouement,
Mab18

**Comment by mab18** [comment]
Hi,
This feature is not requested for me for now. I had only one form, and I have many other now ;-)
Maybe some people need only one form (or two as described by @Aurel2312  : I solve it to send to users the direct URL to this form, it's sufficient and convenient.

**Comment by btry** [comment]
Bonjour

Une option existe désormais pour cacher la barre de recherche.
