### ISSUE TITLE
notifications différentes suivant formulaire saisi

### ISSUE THREAD

**Issue by defaliz** [pluginsGLPI/formcreator#1504]
bonjour
j'ai un formulaire A je voudrais qu'une fois saisi l'auteur seul soit notifié
et un formulaire B je voudrais que pour ce formulaire l'auteur et d'autres personnes soit notifiées...

je sais faire un modèle de notification en indiquant les bonnes personnes mais je ne sais pas relier le formulaire A au modèle de notification A et le form B au modèle de notification B
pouvez-vous m'aider ?
merci 
Alain

**Comment by btry** [comment]
Bonjour

Il n'y a pas de fonctionnalité permettant de définir un comportement de notification en fonction du formulaire manipulé.

Dans GLPI la configuration des notifications est également en fonction des entités. (par défaut elles sont toutes dans l'entité racine, et s'applique à leur sous-arbre.) Ca pourait vous aider à résoudre votre question.

**Comment by defaliz** [comment]
merci btry,
peut-être une fonctionnalité à ajouter..
du coup je fait différemment, 
pas de notification pour la validation du form (sauf pour l'auteur) 
notification uniquement pour le ticket produit par le form (différents groupes notifiés en fonction des tickets associés au form)
bonne journée
