### ISSUE TITLE
[2.8.5] Form with date & time picker field is not saved

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#1508]
**Describe the bug**
I can't create a form with date and time field with the latest version. (formcreator 2.8.5 glpi 9.4.4 imho it should be compatible or is **9.4.*f*** to new ?

**To Reproduce**
1. new form with only date & time (the original bigger one also don't work ;)
2. target ticket
3. (no validation)
4. send form
(get no error message after send and no confirmation!)

**Expected behavior**
- I should have a saved form but there is nothing.
- A ticket should be created.
- a Mesage should apear: Form is saved

**Screenshots**
On monday if you need

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1903 (Build 18262.356)
 - Browser Google Chrome 77.0.3865.90 (64-bit)

**Additional context**
_If i change the field to date it works. If i change it back tothe field date & time it doesn't work._

i tried also 
uninstalled plugin in glpi web + clean up + deinstalled also two old tables form other problems glpi_formcreator_formvalidators_backup, glpi_plugin_formcreator_formprofiles
( i did imho a fresh forms install with this procedure)
At the moment we have 2.6.5 and we plan to upgrade the production system. Other bugs we had on several earlier upgrade process trys seemed to be fixed with our other cases :)

**Comment by btry** [comment]
Hi

Thank you for your contribution in #1509 . I added some changes and updated the unit tests. Could you check that it still works ? Once done, I'll squash the 2 commits and merge it.

**Comment by Armin83** [comment]
LGTM. I already did a small test and deployed the changes to the production system
