### ISSUE TITLE
Bugs v2.9.0-beta.1

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#1515]
Bonjour,

J'ai un problème d'affichage sur la v2.9.0-beta.1.
![image](https://user-images.githubusercontent.com/47602797/66135791-b99a6980-e5fa-11e9-9e25-a329407d9a1b.png)

PHP Warning: require_once(C:\glpi_qualif\plugins\formcreator\inc/../data/font-awesome_9.4.php): failed to open stream: No such file or directory in C:\glpi_qualif\plugins\formcreator\inc\common.class.php at line 184

Il manque la traduction pour "Access types"

**Comment by btry** [comment]
Bonjour

Les traductions ne sont pas encore mises à jour, en effet. Je tâcherai d'y consacrer du temps pour la beta 2.

Comment avez vous installé cette version du plugin ? depuis GIT ou depuis l'archive fournie dans la release ?

**Comment by tguichard25** [comment]
Depuis la release

**Comment by btry** [comment]
Bonjour

J'ai trouvé un oubli dans le processus de constrction de l'archive. Ce sera corigé pour la prochaine release (certainement la beta 2). En attendant j'ai mis à jour l'archive de la beta 1. Si vous re-téléchargez l'archive le problème doit disparaitre.

**Comment by tguichard25** [comment]
Super merci

**Comment by tguichard25** [comment]
Fonctionne parfaitement maintenant.
Un gros merci pour ce super travail.
Le rendu des icônes fait vraiment la différence.

**Comment by btry** [comment]
Merci :)

N'oubliez pas de soutenir le projet si vous le pouvez !
