### ISSUE TITLE
Subtree depth on v2.9.0-beta.1

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/formcreator#1521]
**Describe the bug**
When selecting Type = "Intitulé" and sub-type = "General - Locations" and choosing a Subtree root that is not top-level, the "Limit subtree depth" doesn't work.

In this example, I've selected Subtree root = CSCV->E007 and Unlimited "Subtree depth" but in the form visualisation, it doesn't list the E007 sub-locations...
Even if I change "Limit Subtree depth" to let's say 1 or 2, the same happens...

If I select a top-level location as "Subtree root", it works as expected.
![Bug001](https://user-images.githubusercontent.com/38400135/66320745-63c10c80-e8ed-11e9-8a7b-44059868a5bf.png)
![Bug001_2](https://user-images.githubusercontent.com/38400135/66320746-63c10c80-e8ed-11e9-8694-dc81b6e47785.png)
![Bug001_3](https://user-images.githubusercontent.com/38400135/66320747-63c10c80-e8ed-11e9-9a66-69f21c269d82.png)
![Bug001_4](https://user-images.githubusercontent.com/38400135/66320748-6459a300-e8ed-11e9-8acf-7396a2fe2ee1.png)
![Bug001_5](https://user-images.githubusercontent.com/38400135/66320749-6459a300-e8ed-11e9-9a19-57f6c373776e.png)
![Bug001_6](https://user-images.githubusercontent.com/38400135/66320750-6459a300-e8ed-11e9-898f-c318c21306fd.png)

**Desktop (please complete the following information):**
OS = Windows 10
Google Chrome Version 77.0.3865.90 (Build officiel) (64 bits)

**Comment by btry** [comment]
Hi

Could you validate this fix ?

**Comment by fralla2** [comment]
Don't seems to work.... 

If I look quickly on the database, the data looks to be correct : 
**Table: glpi_plugin_formcreator_questions**
**values  = ** {"itemtype":"Location","show_ticket_categories_depth":"0","show_ticket_categories_root":"23"}

The problem seems to lies with one of the following files (probably **/inc/fields/dropdownfield.class.php**) that don't compute the "locations_id" and "level" correctly when searching inside the "glpi_locations" tab...

![Bug001_7](https://user-images.githubusercontent.com/38400135/66482956-18843680-ea72-11e9-9ca9-30c146f489d6.png)

Note : I haven't looked really into how the plugins works yet but the "glpi_plugin_formcreator_issues" tab only seems to contains "sub_itemtype" = Ticket, so no locations in there....

Thanks
Francois

**Comment by btry** [comment]
The error seems to be introduced when the feature for tickets categories was generalized to other tree-ish dropdowns.

And some other inconsistencies. The tests I did were satisfying... and I just merged the change...

The code I see in your screenshot is not up to date with the fix. Try to download the file /inc/fields/dropdownfield.class.php from the support/2.9.0 branch. It should be better with that. Warning : do that only on a testing environment !

**Comment by fralla2** [comment]
Should I drop all the tables related to the plugins first or will tables like glpi_plugin_formcreator_issues will be repopulated automatically upon using the new plugins files?

**Comment by btry** [comment]
don't touch your tables. No need to change anything because the bug is related to the code only. 

Just apply the up to date file, and try.

**Comment by fralla2** [comment]
Confirmer working. Thanks :)

**Comment by btry** [comment]
great !

thanks for your feedback.
