### ISSUE TITLE
2.9.0-Beta-1 - Does not work with GLPI in Portuguese

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1522]
**Describe the bug**
If GLPI is set to Portuguese or Spanish, the plugin does not work properly as in the images below:
![portugues-1](https://user-images.githubusercontent.com/43650152/66428230-0fe91d00-e9ec-11e9-8391-00dba176b418.jpg)
![portugues-2](https://user-images.githubusercontent.com/43650152/66428232-11b2e080-e9ec-11e9-8905-0bd1276a1333.jpg)

In English and French, it works correctly:
![Ingles-1](https://user-images.githubusercontent.com/43650152/66428323-37d88080-e9ec-11e9-812f-aeff1d78b478.jpg)
![Ingles-2](https://user-images.githubusercontent.com/43650152/66428328-39a24400-e9ec-11e9-91a0-a46c0050a5e7.jpg)

**Comment by btry** [comment]
Hi

- Could you tell if the issue occurs with version 2.8.5 
- Can you check in the developer tools of your browser if you get an Javascript error ?

**Comment by btry** [comment]
Hi

There is probably something specific cin your data (form names ?) : i don'r reproduce. I'm wating for feedback related to my previous post.

**Comment by jvergacas** [comment]
Hy @btry 

Version 2.8.5 does not display the error.

Following is the print with the browser error message:
![portugues-3](https://user-images.githubusercontent.com/43650152/66487679-27271980-ea83-11e9-9819-f1c90c2ae8e4.jpg)

**Comment by TR0LLL** [comment]
Good Morning,

I have the same problem described above, when starting the test with the plugin I can not edit the properties of the forms, whether they are imported or new.
If I change the language to English it enables it.

**Comment by btry** [comment]
Hi

I think that there is a problem with translations of Spanish and Brazilian, but I'm not 100% sure this is the cause of your issue.

If I switch to those languages I get a fatal error in PHP, when translating the name of a tab used on the left of the page. I believe this may interrupt loading of the page when displaying the tabs on tne left.

Translations need an update. I updateds the string which seems to cause the bug, but I don't speak your languagaes. This need verification.

Once done I used the tool to update the locales  and erase the cache for translations in GLPI

- stop the HTTP sevrver
- php vendor/bin/robo locales:pull 
- rm files/_cache/cache_trans/*
- start the HTP server

This would be nice to update both languages because they're not fully  translated and still inherit from data of previous versions. Now some strings require plurals and this breaks the translation engine if the plural is missing.

**Comment by jvergacas** [comment]
Hi @btry 

My Spanish is very bad, so I only worked in Brazilian.

I reviewed the whole translation but some were missing:
![Erro-1](https://user-images.githubusercontent.com/43650152/70535870-8d402380-1b3c-11ea-882e-45086360772d.png)
![Erro-2](https://user-images.githubusercontent.com/43650152/70535874-8fa27d80-1b3c-11ea-9120-24c6abcedc3a.png)

So I started a translation from the POT file and had the same problem, anyway, attached is the full translation from the POT file.
[pt_BR.zip](https://github.com/pluginsGLPI/formcreator/files/3945179/pt_BR.zip)

**Comment by btry** [comment]
Hi

Ok, Thanks, I'll import your translations in the project and check again the fatal error.

I guess you're not aware about transifex. This is an online service for translations. Assuming you have an account and are added as a translator of the project, you can review / update translations online without having to edit the files.

https://www.transifex.com/teclib/glpi-project-plugin-formcreator

**Comment by btry** [comment]
Hi @jvergacas 

I'm a bit confused : I see you were added in the contributors list of the locale if I update from transifex (our name was added in the contributors). You contributed this year, I don't know if you did before or after my last comment in this issue.

Anyway, the translation is 100% complete, then I updated from here. I'll probably check next week how the plugin behaves with this revision of locales.

**Comment by jvergacas** [comment]
Hi @btry 

I'm sorry, I forgot to let you know, but as you submitted the LINK, I signed up and completed the translations there.

Now, I want to see other plugins, and I can start with BEHAVES

Thank you.

**Comment by btry** [comment]
Thank you very much for your contribution !

**Comment by btry** [comment]
Hi

I updated the translations of  the plugin : there are some new strings to be transalted. n the mean time, I found an issue which was probably similar to this issue.

After updating the branch support/2.9.0, reseting the translation cache in GLPI and restarting the server the translation issue I encountered vanished. I expect the problem will be solved for you as well. 

Please confirm.

About the JS error, I found nothing wrong so far.

**Comment by jvergacas** [comment]
Hi @btry 

I completed te translation today.

Thank you

**Comment by btry** [comment]
Thank you. I'll very likely release a bugfix release in january.

**Comment by btry** [comment]
Hi

Release 2.9.2 done recently, this issue should be solved now.
