### ISSUE TITLE
When Form disabled, it is no longer in the list but remains accessible.

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1524]
**Describe the bug**
When a form is disabled, it's remains accessible. I think it's a functionnality :
- remains accessible AND not in the list is good, BUT the field it not well labelled.
- maybe a new field "not in the list" should be a good new functionnality.

**To Reproduce**
Create a Form, disable it : go to http://(nameofserver)/glpi/plugins/formcreator/front/formdisplay.php?id=(number of form)

**Expected behavior**
A message should indicates this form is not enabled

**Comment by btry** [comment]
Hi

This commit should fix the problem. This is not a feature, this is a missing check before displaying the form.

https://github.com/pluginsGLPI/formcreator/commit/0290a97985db92ab2253e6b0602e6507d725a459

**Comment by mab18** [comment]
Hi !
Corrected
