### ISSUE TITLE
A form deleted and enabled is usable

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1525]
**Describe the bug**
When a form is deleted (in trash) AND enabled, the form is usable when direct access in URL. (an old link may use this form by error).

**To Reproduce**
create a form, enable it and delete it, but leave it int the trash.
go to the url with this form, it is fully functionnal although deleted !

**Expected behavior**
With a direct URL, should have an error "form doesn't exist"

**Comment by btry** [comment]
Hi

Nice report ;)

Here is the fix : 6169412d

**Comment by mab18** [comment]
fix correct ;-)
