### ISSUE TITLE
Search options : Avoir le nom (ou l'image) du 'Statut' dans l'export de Formanswer

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/formcreator#153]
1/ Aller dans la liste des formanswer
2/ La liste des formanswer s'affiche avec leurs statuts (une image est affichée dans la première colonne)
3/ Mais dans l'export PDF (par exemple) cette colonne reste vide

**Comment by neeftarah** [comment]
Bonjour,

Ce bug doit être rapporter et corriger dans GLPI.
Formcreator affiche correctement des images comme plusieurs pages et/ou plugins. Ces images comportent un texte alternatif qui doit être repris dans les exports CSV (ce n'est actuellement pas le cas) et, à défaut de l'image, dans les exports PDF.

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
PS : Le lien des issues GLPI ;)
https://github.com/glpi-project/glpi/issues/new
