### ISSUE TITLE
500 error when creating new ticket -2.9.0-beta.1

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1532]
Glpi 9.4.4 plugin 2.9.0-beta.1 receive 500 error
here's php-fpm log
[11-Oct-2019 15:52:53 Europe/Moscow] PHP Fatal error:  Uncaught Error: Undefined class constant 'ACTOR_ROLE_REQUESTER' in /data/www/helpdesk-gumrf/glpi/plugins/formcreator/inc/targetbase.
Stack trace:
#0 /data/www/helpdesk-gumrf/glpi/plugins/formcreator/inc/targetbase.class.php(512): PluginFormcreatorTargetBase->addGroupActor('3', '6')
#1 /data/www/helpdesk-gumrf/glpi/plugins/formcreator/inc/targetticket.class.php(625): PluginFormcreatorTargetBase->prepareActors(Object(PluginFormcreatorForm), Object(PluginFormcreatorFor
#2 /data/www/helpdesk-gumrf/glpi/plugins/formcreator/inc/formanswer.class.php(843): PluginFormcreatorTargetTicket->save(Object(PluginFormcreatorFormAnswer))
#3 /data/www/helpdesk-gumrf/glpi/plugins/formcreator/inc/formanswer.class.php(1026): PluginFormcreatorFormAnswer->generateTarget()
#4 /data/www/helpdesk-gumrf/glpi/inc/commondbtm.class.php(1142): PluginFormcreatorFormAnswer->post_addItem()
#5 /data/www/helpdesk-gumrf/glpi/plugins/formcreator/front/form.form.php(132): CommonDBTM->add(Array)
#6 {main}
  thrown in /data/www/helpdesk-gumrf/glpi/plugins/formcreator/inc/targetbase.class.php on line 595

**Comment by btry** [comment]
Hi

The commit 78c12a81 should fix the problem. Please update the file and feedback.

**Comment by reinethernal** [comment]
Yep this helped. That's funny, but my colleague helped me to fix this issue for about 5 minutes ago)
