### ISSUE TITLE
browser go back when correcting a actor in a list on IE

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1533]
**Describe the bug**
When you enter the beginning of the name of a person on a user list field, on IE, and we press backspace to correct a letter, it makes the browser go back one page, canceling all the input .

**To Reproduce**
In a form, use a Actor list. 
Go to the form with IE, type the beginning of somebody and correct with backspace : on Firefox and EDGE, the backspace corrects the lasts letters, on IE, the browser go back one page.

**Expected behavior**
The backspace on IE should have the same function as Firefox and EDGE.

**Desktop (please complete the following information):**
 - OS: Windows
 - IE
 - 11

**Comment by btry** [comment]
Hi

I guess the same issue will occur in a similar field in GLPI. Could you check, please ?

**Comment by mab18** [comment]
I try immediately ;-)

**Comment by mab18** [comment]
A similar field is the problem... The bug is not present on user selection (4 example a user list on a ticket).
Curiously, the problem is not the same on form lists with IE 11.0.960.19507 (w7) = bug as defined. While IE 11.737.17763.0 (W10) we can't type more than 2 characters and selection/filter is not made !

**Comment by mab18** [comment]
I can't reproduce the problem in GLPI parts.
Curiously, filters are ok with IE, on user selections, but not all fields in Firefox in GLPI.
(eg resp technique : user is not selectable on firefox but ok in IE even if it's curiously displayed. But User is ok in twice browsers.... I never seen this problem before. But it's not formcreator problem.

**Comment by btry** [comment]
It might worth to disable all plugins an see if the bug persists in GLPI, before opening a ticket in https://github.com/glpi-project/glpi/issues .

If you need to open a ticket in the GLPI repo, please add the URL of this ticket in the description.

**Comment by mab18** [comment]
The problem is very real, in near future and because of that, we will stop IE in favor of Edge. 
It's a big project to change that here.

**Comment by btry** [comment]
I think this is better than fixing the plugin to make a very old browser work.

**Comment by btry** [comment]
Hi

2 years elapsed. I guess you seeded to switch to Edge. I close this issue as we cannot continue to support IE
