### ISSUE TITLE
Propose new functionality - DRAFT

### ISSUE THREAD

**Issue by mauriciolamego** [pluginsGLPI/formcreator#1534]
Hello, I would like to propose a feature where the user can fill out the form and have the option to save draft to continue at a later time. The system would save drafts where the user could continue to fill in by clicking.

Here's the tip! :)

**Comment by btry** [comment]
Hi

This is very kind you annouce your feature before coding it :)

Do you have an idea on how you would implement it ?

Also, this development shall be based on the support/2.9.0 branch (lot of refactored code compared to develop which is EOL soon).

**Comment by mauriciolamego** [comment]
I'm sorry, but I have no programming experience and knowledge, just an effective user of your plugin.
Thanks for the solution you have available to us, it is very useful.
I look forward to the improvements.
A hug.

**Comment by btry** [comment]
Ah, sorry ! I thought you wanted to develop it. I cannot tell when the feature will be implemented. This is a matter of availability of a community contribution or a sponsored need.

If you want to sponsor this feature feel free to contact us : contact@teclib.com
