### ISSUE TITLE
EVO ? : Ticket : incident ou Demande

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1540]
Un formulaire cree un ticket, mais un ticket peut etre un incident, ou une demande.

Comment peut-on choisir le type du ticket créé via le formulaire ?

Merci

**Comment by btry** [comment]
Bonjour

Pour le moment vous devez utilsier un gabarit de ticket et l'associer au ticket à générer.

Dans la prochaine versin vous pourrez définir le type sans passer par un gabarit.
