### ISSUE TITLE
Piece Jointe vide 

### ISSUE THREAD

**Issue by Gwenounours** [pluginsGLPI/formcreator#1543]
Bonjour,

Je crée une question de type fichier (non obligatoire)
Sur le moment, le formulaire indique que la piece est telechargée.
Si je valide et que je retourne sur mon ticket pour verifier ma PJ, cela montre qu'il y une PJ mais impossible d'y acceder, elle ne semble pas exister. (voir image)
![image](https://user-images.githubusercontent.com/14139801/67004807-6556b580-f0e1-11e9-9f5a-d6d79aaa2191.png)

Cela se produit sur tout mes formulaire, meme ceux qui sont sur l'entité principale.
Pour mes test j'utilise des comptes authentifiés.

Je ne sais pas si c'est un bug ou une erreur de ma part.

Merci d'avance si vous prenez le temps de répondre.

**Comment by btry** [comment]
Bonjour

Quelle version de GLPI et de Formcreator ? Il me semble que ce souci a été remonté et résolu. JE vous invite à upgrader en Formcreator 2.8.5 si vous n'y êtes pas déjà, et voir si le bug persiste.

**Comment by Gwenounours** [comment]
re,
Merci d'abord de votre réponse.
Je suis en 2.8.5 et en 9.4.2 pour GLPI.

**Comment by btry** [comment]
Pouvez vous trouver le fichier dzns les documents de glpi, et voir si vous trouvez son ID dans la table glpi_items_documents ?

**Comment by Gwenounours** [comment]
Dans les documents les lignes de documents apparaissent mais cela apparait vide (surligné en jaune dans l'image) , contrairement aux pieces jointe ajoutées manuellement dans un ticket.
https://ibb.co/pzpmxwB
Dans la base de données il semble que tout soit correct aussi.
https://ibb.co/GH3Tg8t

**Comment by btry** [comment]
Pouvez vous montrer le gabarit du ticket cible ? Je veux voir si le tag de la question de type fichier est présent.

**Comment by btry** [comment]
De mon côté, avec la version de développement (2.8.5 + bugfixes) ou la version 2.9 en dévelopement, je ne reproduis pas

**Comment by Gwenounours** [comment]
Je n'ai pas mis de gabarit pour le ticket cible.
![image](https://i.ibb.co/Q8GwDPG/Capture.png)

**Comment by btry** [comment]
Bonjour

Est ce que le problème persiste avec la version 2.9.0 ?

**Comment by Gwenounours** [comment]
Bonjour,

Je vais tester ☺


De : btry <notifications@github.com>
Envoyé : mardi 17 décembre 2019 15:30
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : PIEL Gwen <gpiel@ville-pontoise.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Piece Jointe vide (#1543)


Bonjour

Est ce que le problème persiste avec la version 2.9.0 ?

**Comment by Gwenounours** [comment]
Je viens de tester ,
Oui j’ai toujours le problème. Tristesse.


De : btry <notifications@github.com>
Envoyé : mardi 17 décembre 2019 15:30
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : PIEL Gwen <gpiel@ville-pontoise.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Piece Jointe vide (#1543)


Bonjour

Est ce que le problème persiste avec la version 2.9.0 ?

**Comment by btry** [comment]
Non, pas tristesse : ce sera plus facile de travailler sur cette version que la précédente :).

**Comment by Gwenounours** [comment]
C’est vrai que c’est beaucoup plus ergonomique ☺


De : btry <notifications@github.com>
Envoyé : mardi 17 décembre 2019 16:54
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : PIEL Gwen <gpiel@ville-pontoise.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Piece Jointe vide (#1543)


Non, pas tristesse : ce sera plus facile de travailler sur cette version que la précédente :).

**Comment by btry** [comment]
Dans le code, oui. 

Pour les admins et utilisateurs finaux, il va y avoir des choses sympa bientôt.

**Comment by Gwenounours** [comment]
En tous cas sous Firefox, il n’y plus le bouton « sauvegarder » lors de l’edition d’un question.
Cela fonctionne sous IE
[cid:image001.png@01D5B4FF.5A10FAA0]


De : btry <notifications@github.com>
Envoyé : mardi 17 décembre 2019 17:06
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : PIEL Gwen <gpiel@ville-pontoise.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Piece Jointe vide (#1543)


Dans le code, oui.

Pour les admins et utilisateurs finaux, il va y avoir des choses sympa bientôt.

**Comment by btry** [comment]
je suis sous firefox, et j'ai bien le bouton

![image](https://user-images.githubusercontent.com/14139801/71014923-04ecf000-20f3-11ea-9b6e-c1cd5fa33972.png)

A tout hasard, vous avez des erreurs dans les logs sql, php ou du serveur http ?

**Comment by Gwenounours** [comment]
Bonjour,

D’accord, problème de version Firefox pour ma part.
Je vais regarder cela pour les logs.


De : btry <notifications@github.com>
Envoyé : mardi 17 décembre 2019 17:32
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : PIEL Gwen <gpiel@ville-pontoise.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Piece Jointe vide (#1543)


je suis sous firefox, et j'ai bien le bouton

[image]<https://user-images.githubusercontent.com/14139801/71014923-04ecf000-20f3-11ea-9b6e-c1cd5fa33972.png>

A tout hasard, vous avez des erreurs dans les logs sql, php ou du serveur http ?

**Comment by btry** [comment]
Bonjour

Ca fonctionne avec une version plus récente ? Quelle était la version utilisée ?

**Comment by btry** [comment]
Bonjour

Cette version étant obsolète et n'ayant pas eu de réponse, je ferme.
