### ISSUE TITLE
Duplication of tickets after validating form plugin 2.9.0

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1544]
**Describe the bug**
After validating of a form, two tickets created.

**To Reproduce**
1. Go to forms waiting for approval
2. Click on validate button
3. Go to tickets

**Expected behavior**
Only one ticket created 

**Screenshots**
Duplicated tickets
![image](https://user-images.githubusercontent.com/35932698/67013953-a7412500-f0fc-11e9-8b78-268b3870c48d.png)

Only one target associated with form
![image](https://user-images.githubusercontent.com/35932698/67013800-5df0d580-f0fc-11e9-8522-473c71c2545d.png)

**Additional context**

**Comment by reinethernal** [comment]
Thank you. I Confirm that updated version helped.

**Comment by btry** [comment]
Hi

Great, I close. Thank you for the feedback.
