### ISSUE TITLE
Validator is now a requester plugin 2.9

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1545]
**Describe the bug**
After validating a form validator became a requester.

**To Reproduce**
1. Validate form
2. Click on new ticket
3. See error

**Expected behavior**
Validator must not be a requester

**Screenshots**
![image](https://user-images.githubusercontent.com/35932698/67014769-12d7c200-f0fe-11e9-923b-729c1318ac63.png)

![image](https://user-images.githubusercontent.com/35932698/67015624-76162400-f0ff-11e9-9459-2d661561f43a.png)

**Comment by btry** [comment]
Hi
Did you observed the same in earlier versions (2.8.x) ?

**Comment by reinethernal** [comment]
No, only at that version

**Comment by btry** [comment]
I'm comapring bersion 2.8.5 and 2.9.0-beta

I don't see any difference. When a form answer is valodated, the validator is logged, then he is the author of the ticket (un the top right corner of the form). Despite this may require an enhancement, both version currently behave the same .


In the following screenshots, "glpi" filled a form, and the answer is validated by "normal"

### 2.8.5

![image](https://user-images.githubusercontent.com/14139801/67025721-ccd32c00-f106-11e9-8790-a66e5dfe5e0d.png)

### 2.9.0 beta

![image](https://user-images.githubusercontent.com/14139801/67025753-d9f01b00-f106-11e9-8959-8e5aeaec7c3f.png)

**Comment by reinethernal** [comment]
Ok. Thank you) Maybe that's not a 'bug' but a 'feature', but how for me, that's confusing

**Comment by btry** [comment]
I think it is possible to have a better management of the author, but I don"t know how yet. If I need a new column un a table I'll have to do that for the next minor version (2.10)

**Comment by btry** [comment]
Link with #50 
Better behavior witrh #1391, but still WIP

**Comment by btry** [comment]
Hi @reinethernal 

Could you try this fix and feedback ?

**Comment by btry** [comment]
The fix worked for me. Having no feedback, I guess it will work for you as werll. If not, please open a new issue.
