### ISSUE TITLE
PluginFormcreatorAnswer API response - question

### ISSUE THREAD

**Issue by rodrigo-ferreira** [pluginsGLPI/formcreator#1548]
**Describe the bug**
I'm try to get FormCreatorAnswer by apirest.php from GLPI API.

I requet soething like this:
`https://chamadost.trf2.jus.br/apirest.php/PluginFormcreatorForm_Answer/48/PluginFormcreatorAnswer`

And i receive something like this:
`"\u001F\x8B\b\u0000\u0000\u0000\u0000\u0000\u0004\u0003\u0000\u0000\u0000\xFF\xFF\xE5\x94MN\xC30\u0010F\xAF\x82f\x9D\xFA'J \xF6\u000E!\xB1\x86u\u001AE\xA6u\x88!\xB5\x8D\xED\x88E\xD5\xC3p\u0016.\x86\x93\x80\xDAJ\x85\u0005\xCA.\xBB\xB1\xFCy\xDE\xE8i\xE4r\u000Fj\v<%\xD7\t\u062E\u007FV\xBAn\x8C\xDBm\x9C\u0014\xC1\xB8\xB1\xF6\xB5\xD0\xFE]:_\u000F\u025C^\f\xBE\xF5\xD2\ae\xF4\u0014*\u0012\x98\xDE\u0000\x87\u0002\u0011d\u0018\x83\u0004:\xA5_=\xF0r\u000FNv\xF1\xE6a\xE4\xDD\u001FqCY\u07CE\xB0\u0018o\x9Dlb\xAA\r\xC1z\x8E\xF1\xA6\u0015;\xB15>\xA0\xE0\x9A\u0014\xBD\xF4\u001E=9,\xACr\x91\x8Clk\xF1_\xFDpN\xE1\x90\xFCJ~\xFC\u001E\u007F\u0016\xECO3\\\xC0\xA1\u001A\xA0\x93\u16CB\xE2\u0006\xDB\xFF0\xCCN\f\x97k\xB8\u0013\xFA\xF3\xC3)\xB3\x86j\x89\xA2\u0659\xE8\xB8}\xF3\xAD2%'\xA6SB\u064A\x92\u0015-\xAE\b\xE1\x84,\xD15%g\xB2\xE3\"\xCE(;;\u02A6Y\x9E\xC5\xE3\xE2>\r\x9A\r~\xAB/l=\xB6\n\x99\u0005\u0000\u0000"`

What i have to do to get a readble information?

Sorry my english.
:-)

**Comment by btry** [comment]
Hi

Your URL is incomplete. Could you edit your message to add the missing part ?

**Comment by rodrigo-ferreira** [comment]
I updated the URL

**Comment by btry** [comment]
Hi

Thank you. I tried a similar request with a real life form, and the result is consistent : I get a JSON string, as expected.

Do you have such content with any endpoint ?

**Comment by rodrigo-ferreira** [comment]
Thank you, 

Yes any endpoint like: `https://chamadost.trf2.jus.br/apirest.php/PluginFormcreatorForm_Answer/<any number>/PluginFormcreatorAnswer`

My enviroment is:
GLPI v.9.2.4
Plugin Formcreator v.2.6.5

**Comment by rodrigo-ferreira** [comment]
We can close this issue. It's not a bug.

Thanks the suport.
