### ISSUE TITLE
La liste des formulaires est vide

### ISSUE THREAD

**Issue by Belface** [pluginsGLPI/formcreator#1549]
Bonjour

Lorsque mon utilisateur clique sur "Tous mes formulaires" (Demandeurs ou validateurs), rien ne s'affiche. Pour reproduire, mon utilisateur a un profile **Self_Service**

![Capture1](https://user-images.githubusercontent.com/55400519/67082179-e624b880-f198-11e9-870b-f8d1a499afaa.JPG)

![Capture2](https://user-images.githubusercontent.com/55400519/67082187-e9b83f80-f198-11e9-9be3-31df62d8c993.JPG)

Comme pour le ticket 1482, lorsque j'applique le profile **Admin** ou **Super-Admin**, les tickets apparaissent

![Capture4](https://user-images.githubusercontent.com/55400519/67082518-9c889d80-f199-11e9-8a3f-5e99a61765cb.JPG)

Pour corriger avec le profile **Self_Service**, je dois repasser le profil en "Interface Standard", puis ajouter l'option de configuration "Mettre à jour" la "Configuration générale"

![Capture](https://user-images.githubusercontent.com/55400519/67083696-e8d4dd00-f19b-11e9-88f5-69ff03be0643.JPG)

**Comment by btry** [comment]
Bonjour

Tout d'abord, quelle version du plugin utilisez vous ?

#1482 a été résolu cette semaine. Aucune release valide pour la production ne contient le correctif. Du coup, si vous ne l'avez pas appliqué manuellement, il serait intéressant que vous le fassiez pour voir si il résout votre souci.

**Comment by btry** [comment]
> Pour corriger avec le profile Self_Service, je dois repasser le profil en "Interface Standard", puis ajouter l'option de configuration "Mettre à jour" la "Configuration générale"

juste pour être exhaustif : si vous n'activez pas le droit "mettre à jour", la liste reste donc vide ?

**Comment by Belface** [comment]
Exactement

**Comment by Belface** [comment]
Bonjour btry
je viens d'installer la version **2.8.6**, et le pb semble résolu. Vous avez apporté une correction ?
Merci

**Comment by btry** [comment]
Bonjour

Je vois 2 correctifs susceptibles d'avoir impacté poositivement votre souci, au vu de leur commit, mais ils étaient destinés à résoudre d'autres problèmes.

023a60e3dd0136c2670b5a88f2f4e8c535ff3327 et (moins probable) 4c2260034f274335cc962fe21e4bee8938149695

Si le souci est résolu, c'est qu'il y avait un lien avec un autre bug.

**Comment by Belface** [comment]
Je refais des tests et vous tiens au courant

**Comment by btry** [comment]
Merci

**Comment by Belface** [comment]
Bonjour,
je confirme que le problème a été corrigé
Merci, vous pouvez fermer le case

**Comment by btry** [comment]
Bonjour

Merci pour votre retour.
