### ISSUE TITLE
Question : acteurs / envoi de mails

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#1550]
Bonjour,

Preambule : 
Soit un formulaire avec 'n' questions pouvant affecter jusque 'n' acteurs.
Un acteur finalement n'est pas impliqué (reponse à non, par exemple) : donc 'n-1' acteurs doivent recevoir un mail pour le (ou les ?) tickets

Ainsi, tous les acteurs peuvent ne pas devoir recevoir ces tickets : Comment faites vous ? generez vous 'n-1 ' tickets ou 1 seul ticket envoyé au 'n-1' acteurs , comment cela est il mis en oeuvre dans form-creator ? 

En effet, le concepteur du formulaire connait l'ensemble des acteurs, donc on pourrait imaginer de renseigner tous les acteurs en envoi de mail... 

Si on met acteur = reponse à question du formulaire... le demandeur lui ne connait pas forcement l'acteur... 

Du mal à trouver la méthode de 'codification'

**Comment by btry** [comment]
Bonjour

Le champ detype acteurs permet d'entrer autant d'actreurs qu'on le veut. JE ne comprends pas l'intéret d'avoir plusieurs champs de ce type si les acteurs saisis sont tous du même type (observateur par exemple).

Si vous avez 2 tickets géénrés par un formulaire, et qu'i lcontient 3 questions de type acteurs, peu importe que toutes soient remplies ou non, les 2 tickets seront générés.

Si un acteur est défini à partir de la réponse à uen questoin, le demandeur sait forcément quel acteur sera concerné, puisque c'est lui qui le saisit.

**Comment by btry** [comment]
Bonjour

A défaut d'évolution sur ce ticket, je suppose qu'il est résolu. Je ferme.
