### ISSUE TITLE
Names and description of forms are not fully displayed plugin 2.9

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1551]
**Describe the bug**
Headers and description of forms are not fully displayed. Plugin 2.9.0. GLPI 9.4.4
**To Reproduce**
Just enter a title of form more than 30 chsracters and see.
**Expected behavior**
All forms are displayed correctly increasing in size regardless of the number of characters in the name and header fields
**Screenshots**

![image](https://user-images.githubusercontent.com/35932698/67102037-7a0f7800-f1cb-11e9-982a-6f8e2572fe20.png)

**Additional context**
There was no such problem in the previous version (2.8.5)

**Comment by btry** [comment]
Hi

There a missing patch in 2.9. It was asked to have a fixed height for tiles, but long form titles are truuncated. I'll have to restore a variable height. The fix is already done but not merged yet.

**Comment by reinethernal** [comment]
Thx, i'll wait)

**Comment by btry** [comment]
Hi

The fix is done: bfb273fe

**Comment by reinethernal** [comment]
That helped, thx)
