### ISSUE TITLE
I can't create a regex with '/' 

### ISSUE THREAD

**Issue by robsonjorgefernandez** [pluginsGLPI/formcreator#1552]
**Describe the bug**
It's not possible to escape `/` in regex.

**To Reproduce**
1. Create a form 
2. Go to `Questions` 
3. Try to create a `question` with a `regex` that have a `/`

**Expected behavior**
Possible to create a regex like this: `/[0-9]{2}\.[0-9]{3}\.[0-9]{3}\/[0-9]{4}-[0-9]{2}/`

**Screenshots**
![regex](https://user-images.githubusercontent.com/16673533/67123611-3286ed00-f1c7-11e9-853e-52bc904198aa.png)

**Log**
<pre>
==> /var/www/glpi/glpi_files/_log/php-errors.log <==
[2019-10-18 17:02:26] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/glpi-9.4.4/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: plugin_formcreator_sections_id
  Backtrace :
  plugins/formcreator/inc/question.class.php:406     
  inc/commondbtm.class.php:1101                      PluginFormcreatorQuestion->prepareInputForAdd()
  plugins/formcreator/front/question.form.php:51     CommonDBTM->add()
  {"user":"13@glpi"} 
</pre>

**Additional context**

<details><summary>System Config</summary>
<pre>
{
    "glpi": {
        "uuid": "MRaizpbTXfhzZ2L5TTF3oGh69uCqutZNvF2NY6tR",
        "version": "9.4.4",
        "plugins": [
            {
                "key": "formcreator",
                "version": "2.8.5"
            },
            {
                "key": "fusioninventory",
                "version": "9.4+1.1"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "0-500",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "500-1000",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MariaDB Server",
            "version": "10.3.18-MariaDB-log",
            "size": "6867.8",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "Apache",
            "version": "2.4.34"
        },
        "php": {
            "version": "7.1.30",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqlnd",
                "PDO",
                "Phar",
                "posix",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sqlite3",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "xml",
                "xmlwriter",
                "xsl",
                "zip",
                "mysqli",
                "pdo_mysql",
                "pdo_sqlite",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "apcu",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "256M",
                "post_max_size": "20M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "5M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "Red Hat Enterprise Linux Server release 7.7 (Maipo)",
            "version": "3.10.0-1062.1.2.el7.x86_64"
        }
    }
}
</pre>
</details>

**Comment by btry** [comment]
Hi

Can you test the fix above ?

**Comment by robsonjorgefernandez** [comment]
It works!
Thank you @btry!

**Comment by btry** [comment]
Hi

Thank you for your feedback
