### ISSUE TITLE
2.9.0-Beta-1 - Groups do not appear as validators

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#1553]
**Describe the bug**

When I choose to validate by a group combobox does not load the groups.

**To Reproduce**
1. Go to '...' create a new form
2. Click on '....' Need to be validate?
4. See error created groups do not appear

**Expected behavior**
existing groups should appear

**Screenshots**
![glpi erro groups](https://user-images.githubusercontent.com/42414051/67230512-cd740700-f413-11e9-80cb-52bbeb2223f2.png)
![glpi groups](https://user-images.githubusercontent.com/42414051/67230539-d2d15180-f413-11e9-90cd-05f8dc13c1fa.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Versão 77.0.3865.120

**Additional context**

**Comment by btry** [comment]
Hi

Please check that there is at least one user in your groups with the rights to validate request or incident tickets. Groups without such users are filtered out.

**Comment by TR0LLL** [comment]
That's right, thank you very much, I will proceed with the tests!

**Comment by TR0LLL** [comment]
Solved
