### ISSUE TITLE
[QUESTION] Lien entre Awnsers et Tickets

### ISSUE THREAD

**Issue by naurel06** [pluginsGLPI/formcreator#1554]
Bonjour,

N'ayant pas pour l'instant la fonctionnalité d'API REST je me penche sur le cas des Query en base pour réaliser un robot qui à la création d'un formulaire complètera automatiquement le ticket créé.
Pour se faire je veux query la liste des tickets non clos à partir de la liste des formulaires correspondant à mon modèle. Le robot doit pouvoir extraire les jeux de réponses pour chaque ticket non clos.

Dans les tables suivantes j'ai les informations qui m’intéressent : 
glpi_plugin_formcreator_forms_answers => filtrage sur plugin_formcreator_forms_id pour extraire chaque ID
glpi_plugin_formcreator_answers => filtrage pour chaque ID précédemment récupéré sur le champ plugin_formcreator_forms_answers_id pour avoir l'ensemble des réponses

glpi_plugin_formcreator_issues => contient l'ID des tickets qui m'interessent

Le soucis c'est que je n'arrive pas à faire le lien entre un jeu de réponse et un ticket. Je ne sais pas comment cela fonctionne. Pouvez-vous m'aider ?

**Comment by btry** [comment]
Bonjour

Vous pouvez vous appuyer sur la table glpi_plugin_formcreator_issues pour trouver les tickets non clos.

Il y a une relation entre la table glpi_tickets et la table glpi_plugin_formcreator_form_answer via la table glpi_items_tickets

Les tickets générés par formcreator sont partiellement recopiés dans glpi_plugin_formceator_issues . Leur corespondance est dans les colonnes original_id et itemtype (qui doit être égal à "Ticket").

**Comment by naurel06** [comment]
Merci c'est exactement ce que je recherchais.
