### ISSUE TITLE
Modification ticket

### ISSUE THREAD

**Issue by orderman** [pluginsGLPI/formcreator#1557]
GLPI 9.4.2 / FormCreator 2.8.5

Bonjour,

Je teste FormCreator afin de mettre en place un catalogue de service
j'ai créé un formulaire et je me logue avec un utilisateur dont le profil est PostOnly
Une fois le ticket généré lorsque je veux modifier l'urgence ou la catégorie ou ajouter un fichier avec cet utilisateur post only (c'est son ticket)  et que je sauvegarde ma modification

Un ticket Vide  (en mode création) apparait et le ticket que j'ai voulu modifier n'a pas pris en compte les modifications lorsque je le sélectionne 

Je ne comprends pas . Ou c'est un mauvais paramétrage de ma part , ou la modification ,n'est pas possible en PostOnly en interface simplifiée ou un bug.
A quoi sert le bouton sauvegarder dans ce cas . L'urgence devrait être modifiable par  le demandeur
c'est le cas lorsque j'utilise en interface standard mais dans ce cas plus cde catalogue de service

En tout cas le fait qu'un ticket en création  apparaisse sans autre indication est curieuse et anormal lorsque l'on veut modifier un ticket existant

Merci pour votre travail et vos réponses

Cordialement

**Comment by btry** [comment]
Bonjour

Essayez ce fix; il devrait résoudre le souci. Pensez à me faire un retour.

**Comment by orderman** [comment]
Bonjour,

Le fix ne change rien
J'ai toujours le même problème
si je clique sur Sauvegarder dans un ticket existant  un nouveau ticket vierge se créé 

Cdt

Hello,
The fix does not change anything
I still have the same problem

Thanks for your answer

**Comment by orderman** [comment]
Bonjour,

Le problème est toujours présent malgré le Fix

Cdt


Philippe LAFOREST

De : btry <notifications@github.com>
Envoyé : jeudi 31 octobre 2019 09:53
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Modification ticket (#1557)


Bonjour

Essayez ce fix; il devrait résoudre le souci. Pensez à me faire un retour.

**Comment by orderman** [comment]
Désole je suis un boulet ...
je n'avais pas fait le bon changement
Le fix fonctionne donc

Merci pour tout

cdt

**Comment by btry** [comment]
Merci pour votre retour. Le fix est prêt pour la prochaine version.
