### ISSUE TITLE
Missing translation for From Categories

### ISSUE THREAD

**Issue by SilentBob999** [pluginsGLPI/formcreator#1559]
**Describe the bug**
Translate some form and most importantly, translate some form categories.
Go to /plugins/formcreator/front/formlist.php.
Form categories on the left pane do not use translation.

**To Reproduce**
1. Translate some form.
2. Most importantly, translate some form categories.
3. Go to /plugins/formcreator/front/formlist.php.
4. Form categories on the left pane do not use translation.
5. Switch langague to confirm.

**Expected behavior**
A correct translation as configure.

**Screenshots**
 v2.8.5 EN
![2019-10-31 15_21_16-GLPI](https://user-images.githubusercontent.com/4992105/67979550-e7bb9b00-fbf2-11e9-8447-44cf1684efc7.png)

 v2.8.5 FR
![2019-10-31 15_20_54-GLPI](https://user-images.githubusercontent.com/4992105/67979551-e8543180-fbf2-11e9-9301-11744311a79c.png)

 v2.8.5 config
![2019-10-31 15_28_44-(GLPI) WNETVMTEST16 (GLPI windows) (WNETVMTEST16) - Remote Desktop Connection Ma](https://user-images.githubusercontent.com/4992105/67979712-38cb8f00-fbf3-11e9-9f43-1f644e55ba28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Tested : GLPI 9.4.4
Form creator v2.8.2,  v2.8.5 & 2.9.0 beta1 (2.9.0 beta 1 screenshot below [it as more problem])

 v2.9.0 beta1 
![2019-10-31 15_35_36-(GLPI) WNETVMTEST16 (GLPI windows) (WNETVMTEST16) - Remote Desktop Connection Ma](https://user-images.githubusercontent.com/4992105/67980232-5fd69080-fbf4-11e9-8881-3d7a127ce42d.png)

Thank you

**Comment by btry** [comment]
Hi

In your last picture the mess pay be caused by a cached CSS. Please refresh the page in the browser to refresh it, and tell me the result.

Translation issue solved with 495c8dc5

**Comment by SilentBob999** [comment]
Thank you for the fix, This work perfectly.

Regarding the display mess... If you mean the cache on the client, it is not that, a clear my browser and got the same result on different browser/pc (tested IE & Chrome on W2k12r2 and Windows10).

The problem is with the long title; the word wrap spacing is very large.

v2.9.0-beta1
![2019-11-01 09_38_22-GLPI - Liste des formulaires - Internet Explorer](https://user-images.githubusercontent.com/4992105/68028522-08e0c200-fcad-11e9-9383-b6f955145e29.png)

v2.8.5
![2019-11-01 09_39_59-GLPI - Liste des formulaires](https://user-images.githubusercontent.com/4992105/68028609-32015280-fcad-11e9-9aed-c72f1c4a61f2.png)

I also notice another bug that I am not able to reproduce for some reason. I got categories that got created when I did add a translation. I added two translations to the categories ID 4, and at the same time, that create the categories ID 10 & 11.  It is possible that I was on 2.8.5 or something or that I switch between version right before or after... I am not quite sure of sequence of events.  Now if I add a translation, there is no problem. I can only confirm by the time of creation of category id 10 & 11, it matches the time when I create the translation. (sure it will be more clear if there was also an history for when a translation is added…)

![2019-11-01 09_43_13-GLPI - Form categories](https://user-images.githubusercontent.com/4992105/68030722-07fe5f00-fcb2-11e9-9a1b-0ff9fb5dfba5.png)

Thank you again for the translation fix.

**Comment by btry** [comment]
Hi

In the branch support/2.9.0 there are some fixes for too long titles done after the build of 2.9.0-beta.1 .You may want to try it. 

About the categories issue, please create a new ticket. It is needed to have a better handling of bug reports

**Comment by SilentBob999** [comment]
I copy a few files over from support/2.9.0 and indeed it work ;)  Thank you

**Comment by btry** [comment]
Thank you for your feed back.
