### ISSUE TITLE
Search options of Formanswer : delete number of problems

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/formcreator#156]
No have any "problems" in Formanswer

**Comment by Manu1400** [comment]
But keep "Number of tickets"

**Comment by neeftarah** [comment]
Wont be fixed because it is automatically done in search.class.php of GLPI and cannot associate tickets without problems.

report this problem in GLPI if you want :
inc/search.class.php line 5305 => search options for problems are added if ticket can be associated.

**Comment by neeftarah** [comment]
NB : Search.class is based on tickets, because there is no link with problems in GLPI
