### ISSUE TITLE
avoir les groupes comme cibles de formulaires

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1560]
Bonjour,
a ce jour, l'accès aux formulaires n'est possibles qu'aux anonymes, aux utilisateurs authentifiés (sans distinction aucune) ou aux profils.
Mais PAS a des groupes d'utilisateurs ! Mais pourquoi alors que la gestion des groupes d'utilisateurs est une des bases d'utilisation de GLPI.
Cela oblige à des contorsions de création de profils/droits et à des changements de profils aux utilisateurs pour avoir accès à certains formulaires.

Merci de rajouter l'accès aux formulaires selon les groupes :)

C'est plus simple de gérer un groupe VIP ou directeur que de créer un profil particulier ! non ?

Merci et bravo pour le travail déjà réalisé

**Comment by tguichard25** [comment]
Bonjour,

Je suis entièrement d'accord avec ce que demande Sicoval31.
Chez nous aussi, la gestion d'accès par groupe serait grandement apprécié.

**Comment by btry** [comment]
Bonjour

C'est une fonctionnalité souhaitable, mais je ne suis pas assez disponible pour cela actuellement.

Un contributeur ou un sponsor sont les bienvenus.

**Comment by ladenree76000** [comment]
doublon avec #811

**Comment by rpauleau** [comment]
Bonjour,

Je suis très intéressé par cette fonctionnalité aussi

Cordialement

**Comment by btry** [comment]
Bonjour

Vous pouvez sponsoriser la fonctionnalité en nous contactant a l'adresse contact@teclib.com .

**Comment by rpauleau** [comment]
Sponsoriser ?

J'envoie un mail à cette adresse pour expliquer mon besoin c'est ça ?

Cordialement

**Comment by btry** [comment]
Bonjour

C'est pour obtenir une proposition commerciale si vous êtes prêts à financer le développement de la fonctionnalité. Cela permet de répondre rapidement à votre besoin. Sinon vous pouvez faire le développement vous même si vous avez les compétences, ou attendre que la communauté implémente la fonctionnalité.

**Comment by btry** [comment]
Bonjour

C'est implémenté dans Formcreator 2.13
