### ISSUE TITLE
see ticket ID in dropdown and allow to link ticket from answer

### ISSUE THREAD

**Issue by SilentBob999** [pluginsGLPI/formcreator#1561]
Hi,
We would like the ID to show in the dropdown like elsewhere in GLPI. Actually We would prefer the ID first "ID - ticket title".  The main point is to be able to search/filter with the ticket ID.

![2019-11-05 09_48_57-Clipboard](https://user-images.githubusercontent.com/4992105/68225574-a2b2b280-ffbe-11e9-81f3-b5e7fd5eeb42.png)

![2019-11-05 09_48_50-Clipboard](https://user-images.githubusercontent.com/4992105/68225575-a2b2b280-ffbe-11e9-86f5-38124773774e.png)

![2019-11-05 11_25_08-Window](https://user-images.githubusercontent.com/4992105/68225851-0fc64800-ffbf-11e9-9738-72c7d184917b.png)

It would also be awesome to be able to link the ticket created to a ticket from an answer in the form.
![2019-11-05 11_42_13-Window](https://user-images.githubusercontent.com/4992105/68227727-376adf80-ffc2-11e9-8e76-0859adee0d77.png)

Thank you,

**Comment by btry** [comment]
Hi

In cases like yours, well, ID is necessary :)

I'll do a change for the 2.9.0-beta.2

**Comment by SilentBob999** [comment]
thank you very much :)

**Comment by btry** [comment]
The version 2.9.0 in development should now solve the issue. Feel free to try it, but on testing environement only ! (branch support/2.9.0)

**Comment by SilentBob999** [comment]
Hi,
I copy a few files over and see that we can now see the ID if the user is set to see ID's everywhere. See picture below.

**user setting : ID On**
FormCreator
![2019-11-06 08_53_09-Window](https://user-images.githubusercontent.com/4992105/68304226-56757a00-0073-11ea-99d1-590754c2c879.png)
Ticket form
![2019-11-06 08_54_03-Window](https://user-images.githubusercontent.com/4992105/68304223-56757a00-0073-11ea-9a78-5b75ba1fe763.png)

**user setting : ID Off**
FormCreator
![2019-11-06 08_51_12-Window](https://user-images.githubusercontent.com/4992105/68304224-56757a00-0073-11ea-92c5-a8015ad6e56a.png)
Ticket form
![2019-11-06 08_52_05-Window](https://user-images.githubusercontent.com/4992105/68304228-570e1080-0073-11ea-8aff-f3c95ead0d5a.png)

Is it possible to have the ID display for this dropdown regardless of the user setting?

Thank you for your support

**Comment by btry** [comment]
Hi

This would require I rewrite methods belonging to GLPI core to change a few lines. This is a bad idea : 
- this would make the plugin behave in a less standard way compared to GLPI
- this would introduce delays if a bug in GLPI is fixed in the code of GLPI and not fixed also in the plugin.

If you need to show the IDs of objects in the plugin, it might be relevant to allow the same in GLPI ?

**Comment by SilentBob999** [comment]
Hi,
I got confuse, as you can see, the screenshot show that in “/ticket.form.php” it does show the Ticket ID, no matter if the ID's are display at large or not.  But I notice that in the Knowledgebase it does act the same way it does now in FormCreator.
I am trying to find where this is programmed but I really have a hard time to follow all those class and method.  I saw the ForceID of the GetLink method for the display of already linked ticket, and I saw the dropdown for the link type, but I don’t even see in which file the dropdown for the ticket list his...
The point is, that specific dropdown has the desired behavior.

**Comment by SilentBob999** [comment]
The main point is that the ID for Ticket is as important as the Serial and Tag Number for a computer.  That’s the element use by the users and technician to identify it.

**Comment by SilentBob999** [comment]
Also, as it is now, we cannot search with the id, even if it is display.

**Comment by SilentBob999** [comment]
submitted an issue for GLPI too
https://github.com/glpi-project/glpi/issues/6557

**Comment by SilentBob999** [comment]
My idea is that if someone fix the KnowledgeBase we will know what to do ;)

**Comment by btry** [comment]
Hi

I don't reproduce

### my setting

![image](https://user-images.githubusercontent.com/14139801/69435601-26e79280-0d40-11ea-9346-25e5be99927d.png)

### in a ticket
![image](https://user-images.githubusercontent.com/14139801/69435655-3ff04380-0d40-11ea-8095-00918d3b0f52.png)

### in a Formcreator's target ticket

![image](https://user-images.githubusercontent.com/14139801/69435686-51395000-0d40-11ea-8a2b-21bdf322ade0.png)

The ID is displayed in GLPI and Formcreator, no matter is the show ID setting in the user preference. Then consistency between both places is ok for me.

**Comment by SilentBob999** [comment]
Hi btry,
Yes, the dropdown in target ticket is alright for me too.
Where we would like the same thing to display, is if we create a question of type "GLPI Object" -> "Assistance -> Tickets".

![image](https://user-images.githubusercontent.com/4992105/69971486-f6e18180-14ed-11ea-9e62-db507944d357.png)

We want this field for a form that would be used to create a sub request sent to external supplier.  The communication with them is by email and we do not want all the communication to be available to the user who create the original request.

So this are the two thing we trying to add:
- We want the ID to always show if we create a question asking for a Ticket.
- get the "Formcreator's target ticket" to be able to link to the "answer of the question".


Sorry for the confusion and thank you for your help

**Comment by btry** [comment]
Hi 

Could you try #1616 and feedback ?

**Comment by btry** [comment]
Hi

The Fix I submitted is obsoleted by an other change. Having no feedback, I close.

**Comment by KorvinEC** [comment]
Hello! I have a problem with target Ticket. For some reason, I am not able to link it to already existing ticket, based on user input. Is it possible?

I have a similar task as @SilentBob999. I need to be able to make form ticket a son (or be linked to) other, already created ticket.

**Comment by btry** [comment]
Hi

Please open a new issue : your question is not related to this issue (based in the title), and it is also so old it is obsolete.
