### ISSUE TITLE
Form error using hour, minute and second

### ISSUE THREAD

**Issue by geanferrani123** [pluginsGLPI/formcreator#1562]
Dear, good afternoon!

When the file below has the ": ss" inserted in the highlighted line, the form does not allow saving the information entered in it, can you help me? It only accepts when we move the ticketrecurrent.class.php file and remove the ": ss"

![image](https://user-images.githubusercontent.com/55212206/68242953-46688680-fff0-11e9-9c83-70ba8b0f65af.png)

![image](https://user-images.githubusercontent.com/55212206/68243107-95aeb700-fff0-11e9-9898-c615f903cf17.png)

**Comment by btry** [comment]
Hi

Which  version of GLPI, of Formcreator ?

Also, I guess  the issue is related to a question of type Date time ?

Could you share a simple form to reproduce the issue ?

**Comment by geanferrani123** [comment]
My GLPI is in version 9.4.4

![image](https://user-images.githubusercontent.com/55212206/68326267-d74f6880-00a9-11ea-9f1e-d467494f5c24.png)

**Comment by btry** [comment]
Hi

The release 2.8.6 of Formcreator contains a fix for date time fields. The bug was anwsers are rejected without any error message when a datetime field contains something. As you did not tell the version of the plugin, I expect you have a version < 2.8.6. Please test the latest release on a testing environment and feedback.

**Comment by geanferrani123** [comment]
> Oi
> 
> A versão 2.8.6 do Formcreator contém uma correção para os campos de data e hora. O erro foi que as respostas são rejeitadas sem nenhuma mensagem de erro quando um campo datetime contém algo. Como você não informou a versão do plugin, espero que você tenha uma versão <2.8.6. Teste a versão mais recente em um ambiente de teste e feedback.

Ok, I'll test and give you a feedback.

**Comment by btry** [comment]
Hi

I assume the bug is solved for you. If not, please leave a comment here.
