### ISSUE TITLE
Insertion capture d'écran dans formulaire

### ISSUE THREAD

**Issue by moccino** [pluginsGLPI/formcreator#1568]
FormCreator 2.8.5 + GLPI 9.4.2 + Mozilla FireFox

Bonjour, j'ai créé des formulaires de support utilisateur mais lorsque l'utilisateur insert une capture écran de son problème, celle ci n'est pas visible dans le formulaire, ni pas dans le ticket généré...

![image](https://user-images.githubusercontent.com/50907789/68852008-4d218880-06d7-11ea-9e3b-a436c168192b.png)

![image](https://user-images.githubusercontent.com/50907789/68851496-5bbb7000-06d6-11ea-87ec-2c8526b6ef17.png)

![image](https://user-images.githubusercontent.com/50907789/68851821-e69c6a80-06d6-11ea-87ce-e4fbc3f902da.png)

**Comment by btry** [comment]
Bonjour

Avez vous essayé la version 2.8.6 ?

**Comment by mab18** [comment]
De mon côté, en 2.8.6, le copier/coller d'image de capture d'écran donne ça :
![plugin Formcreator - problème de pièce jointe en copier-coller - 01](https://user-images.githubusercontent.com/55535560/68940804-6d6b4900-07a4-11ea-99ed-043280f1653d.png)
Bien que l'image est dans le champ de la table au vu du contenu.
Aurais-je un problème d'install ? Que dois-je vérifier (quelles est la chaine d'objets PHP GLPI utilisés pour traiter ces images) ? J'ai l'impression d'être le seul à avoir ce problème.

**Comment by btry** [comment]
Bonjour

Il peut y avoir un lien avec la taille de l'image par rapport au champ prévu en BDD.

Dans la table glpi_plugin_formcreator_issues changez le champ comment en LONGTEXT.

Ce changement sera fait en 2.9.0.

Lien probable: https://github.com/pluginsGLPI/formcreator/issues/1455

**Comment by mab18** [comment]
Bonjour,
J'ai déjà mis cette colonne en LONGTEXT depuis mes tests de l'autre fois.
Je viens de revérifier : cette colonne est bien en LONGTEXT dans mon environnement.

**Comment by CGFLmlm** [comment]
Merci pour vos réponse. Pour ma part, j'ai essayer la 2.8.6 et mis LONGTEXT mais rien ne change... :(
Une autre piste pour mon problème ?

Merci de votre aide car cela devient pénalisant...

**Comment by btry** [comment]
@mab18 

Pouvez vous vérifier le code ML représentant le texte de votre ticket ?

Je reproduis votre cas et je remarque ceci

![image](https://user-images.githubusercontent.com/14139801/68955727-f72c0e00-07c6-11ea-807f-33e3d72080dc.png)

Si je supprime **denied:** le code HTML devient correct et l'image apparait.

**Comment by btry** [comment]
@moccino : je ne reproduis pas encore votre cas

**Comment by btry** [comment]
le **denied** est ajouté par HTMLawed utilsié dans GLPI.

**Comment by mab18** [comment]
@btry : 
Pour ma part, les images insérées parr copier-coller ont ce contenu : 
(...)img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABVYAAAMACAYAAADPPjzCAAAgAElEQVR4nOy9eVRU16Lu(...)

**Comment by btry** [comment]
ça doit être avant de valider le formulaire. De ce que j'observe, dans le ticket généré, le mot **denied** est ajouté. C'est lui qui "casse" l'affichage de l'image.

**Comment by moccino** [comment]
J'ai 2 srv GLPI - un de prod et un de test et j'ai mon problème d'image sur les 2 - j'ai mis mon svr de test en glpi 9.4.4 mais idem... j'ai essayé la Beta de FormCreator mais cette fois si pas d'image et seulement un texte 'image' d'indiqué... Mes srv sont sous centos si besoin.
Je peux vous envoyer toute info utile qui vous permettrait de debugger.
Merci de votre aide.

**Comment by mab18** [comment]
@moccino > ...mais cette fois si pas d'image et seulement un texte 'image' d'indiqué...

Tiens, je n'ai pas la Beta et j'ai ça aussi... Est-ce le même "image" que mon post du 15 à 12:39 ?

**Comment by mab18** [comment]
@btry : 
Je confirme que dans le navigateur, si on retire "denied", l'image s'affiche correctement.
Et aussi que "denied" ne se trouve pas dans la colonne, il est forcément ajouté lors de l'envoi de la page vers le navigateur.

**Comment by mab18** [comment]
@btry > le denied est ajouté par HTMLawed utilsié dans GLPI.

Effectivement, en ligne 340, si on remplace 
static $d = 'denied:';
par 
static $d = '';
l'image s'affiche alors sans aucun problème et dans le plugin FormCreator _ET_ dans GLPI.

Question : comment faire en sorte que HtmlLawed n'ajoute pas "denied" ? On est presque à trouver le problème une fois ça résolu. Je n'arrive pas à comprendre le code de cet outil.

**Comment by btry** [comment]
Bonjour

HTMLawed est là pour des raisons de sécurité. Sans toucher à GLPI, il n'y a qu'une seule solution : convertir les images uploadées en documents, en faisant en sorte qu'un textarea se comporte comme dans GLPI, par exemple la saisie d'un ticket. Je me souviens avoir exploré cela, mais il y a 3 problèmes à résoudre : 
- je me souviens que quelque chose m'empêche de réutilsier la fonctionnalité de GLPI
- comment conserver le lien entre les documents uploadés si le formulaire est soumis avec des erreurs (comme un champ obligatoire non rempli)
- comment mémoriser qu'un document appartient à un champ de texte, et le distinguer d'un document envoyé par un champ de type fichier ? Le même souci devrait apparaitre au moment de générer un ticket en différé, après une validation.

**Comment by mab18** [comment]
@btry @moccino : 
J'ai trouvé de mon côté comment faire fonctionner ces @#& images ;-)
dans ./inc/html.class.php, ligne 94 : 
'schemes' => '*: aim, app ...'
ajouter "data"
'schemes' => '*: aim, data, app ...'

L'inclusion des images ne peut donc pas fonctionner dans GLPI sans ce paramétrage, dans aucun endroit, même dans les plugins.

**Comment by moccino** [comment]
Oui problème identique à Paste from clipboard picture does not works #1514
De mon coté, j'ai essayé de modifier le fichier ./inc/html.class.php mais cela persiste... j'ai supprimer et réinstallé formcreator - puis réimporté mes formulaires ---> Les images ont fonctionnés sur 3 tickets puis de nouveau le problème ....
c'est très bizarre :(
Une autre piste svp ? merci

**Comment by mab18** [comment]
Pour ma part, le problème est corrigé avec la modification telle que je l'ai décrite.
Je peine à croire que ça fonctionne "un peu" puis ça "s'arrête" au bout de 3 tickets.
J'ai tracé le code, le "deny" se met à cet endroit car il manque "data". Donc si vous avez encore le problème, c'est que vous n'êtes plus dans le contexte énoncé ou que "data" n'est pas dans ./inc/html.class.php comme décrit ou bien il existe un autre problème ailleurs.
Voyez aussi, vu que vous avez réinstallé le plugin complètement, que le format de la colonne tel que l'a proposé @btry à propos du problème #1455 ("Dans la table glpi_plugin_formcreator_issues changez le champ comment en LONGTEXT") et aussi la colonne "contents" de la table glpi_tickets.
Voici ma ligne 94 de ./inc/html.class.php, au cas où :
'schemes'          => '*: data, aim, app, feed, file, ftp, gopher, http, https, irc, mailto, news, nntp, sftp, ssh, tel, telnet'

**Comment by btry** [comment]
Bonjour
Après une revue des PR en attente et de quelques bugs, j'ai remarqué que le changement de colonne décrit dans #1455 n'a pas été fusionné (j'en avais pourtant la certitude). C'est chose faite.

J'ai fait une tentative de conversion des images copiées / collées en document dns un champ zone de text, comme c'est fait dns GLPI au niveau des tickets. Très bonne surprise, je pensais être confronté à des problèmes de gestion des uploads en tous genre, et il se trouve que non.

Vous serez peut être intéressés d'esssayer cette PR basée sur 2.9.0-beta (avec les derniers correctifs en attentent de release)

**Comment by orderman** [comment]
Bonjour,
Je suis en GLPI 9.4.4 Formcreator 2.8.6 
Je cherche un moyen d'insérer des captures écran dans un formulaire
Mais je ne sais pas quel item prendre dans la liste  déroulante type 
Et d'après ce que je viens de lire ca n'est peut être pas encore au point
ou compliqué a mettre en œuvre...je ne suis pas un codeur HTML ou PHP...
Si je peux avoir déjà le type a choisir...ou s'il faut attendre..

Merci

Philippe LAFOREST

**Comment by btry** [comment]
Bonjour

Prenez le type ed question "zone de texte". 

Je vous invite à essayer le patch cité un peu plus haut pour résoudre les problèmes avec ce cas d'utilisation et me faire un retour.

**Comment by btry** [comment]
Bonjour

L'un de vous a t il pu essayer le patch #1573  ? Je pense pouvoir faire une beta 2 bientôt, et j'aimerais savoir si il résout le souci pour l'inclure.

**Comment by orderman** [comment]
Bonjour,

J’ai installé la version 2.9.0 beta1
Je n’ai même plus l’affichage de l’entête du ticket   une fois celui-ci créé  mais seulement suivi et Document
Je suis en PostOnly

[cid:image002.jpg@01D5AA9A.300A13F0]


D’autre part l’insertion d’image ne fonctionne et je ne peux même pas utiliser les menus contextuels
Copier-Coller et le crtlC/CrtlV ne fonctionne pas non plus

[cid:image005.jpg@01D5AA9A.300A13F0]


Cordialement






[image006 (3)]

Philippe LAFOREST
Technicien
05 34 61 50 81

12, rue Michel Labrousse
31036 Toulouse


[logoeco1]
Avant d'imprimer cet e-mail, pensons à l'environnement


De : btry <notifications@github.com>
Envoyé : mercredi 4 décembre 2019 10:38
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Comment <comment@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Insertion capture d'écran dans formulaire (#1568)


Bonjour

L'un de vous a t il pu essayer le patch #1573<https://github.com/pluginsGLPI/formcreator/pull/1573> ? Je pense pouvoir faire une beta 2 bientôt, et j'aimerais savoir si il résout le souci pour l'inclure.

**Comment by btry** [comment]
Bonjour

Je n'ai pas les images que vous avez voulu joindre. Editez votre post directement. Il semble que les réponses par email ne focntionnent pas très bien.

Pour tester le patch il faut prendre directement la branche support/2.9.0, faire un build des dépendances avec composer, et appliquer le patch sus mentionné. Il y a eu beaucoup de patches depuis la beta1. Je compte faire une beta2 bientôt, avec des features que je n'avais pas prévu au programme de cette release ;)

**Comment by orderman** [comment]
GLPI 9.4.4 / Formcreator 2.9.0-beta1
Bonjour,

Suite a MAJ en 2.9.0 beta 1 
Je n’ai plus l’affichage de l’entête du ticket   une fois celui-ci créé  mais seulement suivi et Document
Je suis en PostOnly

![tktform1](https://user-images.githubusercontent.com/49547111/70139685-47deaa80-1693-11ea-81b8-2a8a71070270.JPG)

D’autre part l’insertion d’image ne fonctionne et je ne peux même pas utiliser les menus contextuels 
Copier-Coller et le crtlC/CrtlV ne fonctionne pas non plus

![CopyPastedNOK](https://user-images.githubusercontent.com/49547111/70139695-4ca35e80-1693-11ea-8128-83eaf9c5b101.JPG)

Cordialement

Philippe

**Comment by btry** [comment]
Bonjour

Ce tickez devient assez long : si vous trouvez des problèmes différents, veuillez faire un fil distinct pour chacun. Sans cela, je serai vite moins efficace pour apporter les corrections.

De ce que je vois, je peux coller une image par arccourci clavier, mais pas par menu contextuel. Cela doit être lié à la librairie tierce partie utilisée pour gérer le txt area en mode texte riche. Test effectué avec Firefox, sous linux. @orderman Quel est votre environnement  ?

**Comment by orderman** [comment]
Bonjour,

Non je ne peux pas coller d’image
Même avec les raccourcis clavier
Et je en peux plus utiliser les menus contextuels souris Copier-Coller
Si je fais clic droit coller j’ai une pop-up m’indiquant d’utiliser les raccourcis clavier
Qui ne fonctionnent pas

Voulez vous que je supprime le post et que j’en ouvre un nouveau tkt

Cdt


PHLIPPE LAFOREST

De : btry <notifications@github.com>
Envoyé : mercredi 4 décembre 2019 12:52
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Insertion capture d'écran dans formulaire (#1568)


Bonjour

Ce tickez devient assez long : si vous trouvez des problèmes différents, veuillez faire un fil distinct pour chacun. Sans cela, je serai vite moins efficace pour apporter les corrections.

De ce que je vois, je peux coller une image par arccourci clavier, mais pas par menu contextuel. Cela doit être lié à la librairie tierce partie utilisée pour gérer le txt area en mode texte riche. Test effectué avec Firefox, sous linux. @orderman<https://github.com/orderman> Quel est votre environnement ?

**Comment by moccino** [comment]
Pour ma part avec l'ancien patch, les capture d'écran sont bien en visu dans le ticket, par contre lorsque sur le même ticket je vais dans le suivi, l'image ne s'affiche pas lorsque la capture est volumineuse .... le même affichage que le problème initiale (par contre cela le fait uniquement pour les capture écran volumineuse)

Est ce que le nouveau patch est bien celui-ci afin que je test ?
![image](https://user-images.githubusercontent.com/50907789/70142656-0a315000-169a-11ea-9428-fce1ee748ad6.png)


Merci

**Comment by orderman** [comment]
Bonjour,
Le test initial était sous Edge
Sous Firefox je n’ai pas le pop-up indiquant d’utiliser les raccourcis clavier mais  l’insertion image ne fonctionne pas. Je vais patienter et attendre la prochaine version stable


Philippe

**Comment by btry** [comment]
Oui, SVP créez bien un ticket par problème; c'est important quand je dosi reprends quelque chose après quelques semaines d'interruption.

**Comment by mab18** [comment]
Bonjour,
J'avais posté un message qui peut-être correspond au problème de grosses images tronquées :
https://github.com/pluginsGLPI/formcreator/issues/1514#issuecomment-538296731

**Comment by btry** [comment]
Bonjour

Ce fil devient compliqué à suivre ...

Je ne sais pas encore quand, il faut que je vérifie si les problèmes de copier / coller avec ou sans raccourcis sont liés au patch #1573 . Je ne vois pas comment il peut y avoir un lien entre les deux.

Pour ceux qui veulent tester ce patch #1573, veuillez l'appliquer sur la dernière révisin de la branche support/2.9.0 . Depuis 2.9.0.beta-1 il y a eu pas mal de correctifs (merci à la communauté).

Je voudrais résoudre ce fil avant de sortir une beta-2, voire même uen version définitive.

**Comment by orderman** [comment]
Bonjour,

Je viens de tester cette modification
https://github.com/pluginsGLPI/formcreator/pull/1573/files#diff-ae547a6dc41e555c9540773728b2a2f9R93
Le copier-coller fonctionne dans le formulaire
Mais je ne vois pas l’image copiée dans la description  une fois le ticket créé

Cdt

PHILIPPE




De : btry <notifications@github.com>
Envoyé : jeudi 12 décembre 2019 09:57
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Insertion capture d'écran dans formulaire (#1568)


Bonjour

Ce fil devient compliqué à suivre ...

Je ne sais pas encore quand, il faut que je vérifie si les problèmes de copier / coller avec ou sans raccourcis sont liés au patch #1573<https://github.com/pluginsGLPI/formcreator/pull/1573> . Je ne vois pas comment il peut y avoir un lien entre les deux.

Pour ceux qui veulent tester ce patch #1573<https://github.com/pluginsGLPI/formcreator/pull/1573>, veuillez l'appliquer sur la dernière révisin de la branche support/2.9.0 . Depuis 2.9.0.beta-1 il y a eu pas mal de correctifs (merci à la communauté).

Je voudrais résoudre ce fil avant de sortir une beta-2, voire même uen version définitive.

**Comment by btry** [comment]
Bonjour

@orderman votre version du plugin est bien la branche support/2.9.0 ? et est-elle à jour ? (au moins datée de la semaine dernière)

**Comment by orderman** [comment]
Bonjour,

Il s’agit de la 2.9.0 beta 1 installé le 04/12/2019

Cdt

Philippe

De : btry <notifications@github.com>
Envoyé : vendredi 13 décembre 2019 09:17
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Insertion capture d'écran dans formulaire (#1568)


Bonjour

@orderman<https://github.com/orderman> votre version du plugin est bien la branche support/2.9.0 ? et est-elle à jour ? (au moins datée de la semaine dernière)

**Comment by btry** [comment]
c'est la version affichée dans GLPI, ce n'est pas assez précis quand on est sur une version en cours de développement.

Depuis la publication de release 2.0.9.beta-1 j'ai fait beaucoup de corrections, et certaines peuvent influer sur ce bug. Il faut donc utilsier la toute dernière révision de la branche support/2.9.0.

**Comment by orderman** [comment]
Bonjour,
J’ai omis de dire GLPI 9.4.4
La copie écran fonctionne sous Edge et Firefox
Sinon c’est bien 2.9.0-beta1 qui est affiché dans les plugins GLPI
J’ai carrément installé cette beta le 4/12
Elle pose d’ailleurs des soucis que j’avais remonté mais
J’ai préféré attendre quelque choise de plus stable et créer
Une nouvelle demande comme vous l’avez conseillé
car il est vrai qu’on ne s’y retrouve plus
Je dois donc installer la 2.9.0 si je comprends bien  et vous faire un retour ?

Cdt

Philippe




De : btry <notifications@github.com>
Envoyé : vendredi 13 décembre 2019 09:44
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Insertion capture d'écran dans formulaire (#1568)


c'est la version affichée dans GLPI, ce n'est pas assez précis quand on est sur une version en cours de développement.

Depuis la publication de release 2.0.9.beta-1 j'ai fait beaucoup de corrections, et certaines peuvent influer sur ce bug. Il faut donc utilsier la toute dernière révision de la branche support/2.9.0.

**Comment by btry** [comment]
Pour prendre la dernière révision, vous avez besoin de l'archive du code source téléchargeable sur github, branche support2.9.0

Vous aurez besoin d'avoir composer (http://getcomposer.org) sur le sysème.
Ensuite dans le dossier du plugin lancez les commandes suivantes. Elles sont obligatoires pour que le plugin fonctionne.

* composer install
* php vendor/bin/robo build:fa-data

Ensuite, vous pourrez faire la procédure d'installation ou d'upgrade habituelle.

**Comment by mab18** [comment]
Hi !
nota : 
    composer install +     php vendor/bin/robo build:fa-data = doesnt work out of the box, I put archive in the directory and run this to lines = ok
Well...
The update to "support 2.9" breaks all criteria of forms already made. 
The criteria is here, but contraints is disapeared, need to redo them :-// I'll do a ticket for that

Picture is in the webmail, but not in outlook (see https://github.com/glpi-project/glpi/issues/6721 ) I don't know why. I think it's a Outlook problem or conjunction of 2 (formcreator/outlook). Why not create picture as GLPI : create a file rather than inserting it into the text. Because it seems painful.

**Comment by btry** [comment]
Hi

I did some fixes in the upgrade process a few hours ago. As I plan to releaase  the final  version tomorrow, I'm very interested about your problem of criterias. Please open an issue and put all details you know.

If a specific web client (or webmail) fails to show the picture, you need to find how to get the "source" of the email to manually check if the picture is actually missing.

**Comment by mab18** [comment]
Issue is made ;-)
Source of the email seem to be correct, I don't know why there is a problem in outlook. I think I am not alone in this case.
The problem is not the same as the beginning : I have a red cross in the picture placement. It's ok in Webmail, the "source" in outlook can be open in a browser successfully with pictures.
What I have in Outlook. 
![image](https://user-images.githubusercontent.com/55535560/70919272-dbfc2a80-2020-11ea-8566-80c3e0c20a67.png)
Curiously, last week, that's was ok in my only test I made... I have no Idea for that. And more curiously, the email I copy for proof of pictures are not ok today in the same email today.

**Comment by btry** [comment]
If you reproduce this with tickets generated by glpi without using Formcreator, then this problem is specific to GLPI, and not Formcreator, and continue to feed your report in https://github.com/glpi-project/glpi/issues/6721

**Comment by mab18** [comment]
See below : 
2 first pictures are inserted with formcretor with copy/paste.
third one is inserted directly in GLPI AFTER formcreator create it, with a copy/paste too.
![image](https://user-images.githubusercontent.com/55535560/70920152-609b7880-2022-11ea-935c-278b4c5299b0.png)
In the source, I can see a very different way in creation : 
Formcreator insert the picture in base64 in the text, while GLPI create a file, and in the description, this is manifest.
I use only formcreator for creating tickets.

**Comment by FreddyCeralis** [comment]
Bonjour

Je confirme que tout fonctionne parfaitement dans GLPI, c'est vraiment Formcreator qui ne gère pas correctement le copier coller
GLPI 9.4.5 + Formcreator 2.9.0

**Comment by btry** [comment]
Hi

I coming back on this issue.

I updated the patch #1573 with all other commited fixes and ran it. I can paste a picture in teh clipboard (taken from a screen capture tol), then submit the answers. A ticket is generated and contains the image  as expeected. 

No issue with Ctrl+V with Firefox or Chromium.

**Comment by btry** [comment]
I wish to distinguish 2 issues decribed here

- the images are missing in the generated ticket, should be fixed with the above mentionned patch
- the copy / paste issue.

I think there is no direct / obvious relation between them. Can someone test the branch support 2.9.0 (now marked 2.9.1-dev) with the patch #1573 and validate if the images are visible in the generated tickets ?

For those who have copy / paste issues, please, let's open an other thread.

**Comment by orderman** [comment]
Bonjour,
J'ai testé GLPI 9.4.5 / Formcreator 2.9.1
insertion Copie d'écran sur formulaire fonctionne sous Edge et Firefox
mais le tickets généré ne contient pas d'image

Dois appliquer le fix #1573 bien que je sois avec la dernière version de FORMCREATOR

*****

Hello,
I tested GLPI 9.4.5 / Formcreator 2.9.1
insertion Screen copy on form works with Edge and Firefox
but the generated ticket does not contain any pictures

Do I apply fix # 1573 even if I work with the latest version of FORMCREATOR

Best regards


Philippe

**Comment by mab18** [comment]
Bonjour, 
Pourriez-vous retester avec le correctif de https://github.com/pluginsGLPI/formcreator/issues/1514 ?
-
Could you try with th fix https://github.com/pluginsGLPI/formcreator/issues/1514 ?

**Comment by btry** [comment]
Bonjour

Les problèmes de capture d'écran devraient être résolus avec GLPI 9.5 et les dernières releases de Formcreator. 

Si le problème persiste, merci d'ouvrir un nouveau ticket.
