### ISSUE TITLE
Duplicate a Form change the recipient name

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1571]
**Describe the bug**
When a form is duplicated, the name of recipient is changed.

**To Reproduce**
Duplicate a Form, go to recipient tab, the recipent has changed to a curious name, generally, last value of the list of questions.

**Expected behavior**
The name should not changed.

**Screenshots**
Original :
![image](https://user-images.githubusercontent.com/55535560/69244145-b9ebc580-0ba4-11ea-9807-c0198d655a02.png)
Duplicate form :
![image](https://user-images.githubusercontent.com/55535560/69244168-c6701e00-0ba4-11ea-98f6-1963a23bf62a.png)

**Context**
GLPI 9.4.4/Formcreator 2.8.6

**Comment by btry** [comment]
Hi

Do you have the opportunity to check if the bug persists with 2.9.0 beta ?

**Comment by mab18** [comment]
I can do a snapshot of my test environment without problem.
But, please, can you help me to apply correctly the 2.9.0 beta ?

**Comment by btry** [comment]
to install beta, download the snapshot of the branch support/2.9.0

- backup your DB, even if it is a testing one (to have an easy rollback to 2.8.x)

then assuming you have composer, 
- run composer install in the folder of formcreator (available in http://getcomposer.org or your distribution)
- run php vendor/bin/robo build:fadata (requires an internet connection)
- upgrade the plugin with the CLI tool or from glpi, as usual

**Comment by mab18** [comment]
@btry : I have too much job this week, I'll do this next week ;-)

**Comment by mab18** [comment]
This problem is still present.

**Comment by btry** [comment]
Can you show the name and the title of the target on the original form ?

**Comment by btry** [comment]
Hi

Here is a fix: 897c564f
