### ISSUE TITLE
Non-admin can't edit/add forms

### ISSUE THREAD

**Issue by boscorelly** [pluginsGLPI/formcreator#1574]
Hi,

we want to enable forms edition/creation for non-admin profiles.

But i see nowhere the option in profile configuration or somewhere else.

Is it a bug ? ou is it not implemented ?

**Comment by btry** [comment]
Hi

Creation / edition of forms is allowed for profiles having the right to update entities. That's why you don't find any specific right .

**Comment by boscorelly** [comment]
hi,

where can i set it up ?

i haven't found :/

**Comment by btry** [comment]
Configure the profile of your users to have UPDATE right on entities.

![image](https://user-images.githubusercontent.com/14139801/69541138-c13a1700-0f88-11ea-92c4-b9c99e5606f8.png)

**Comment by mab18** [comment]
Hi !

@btry : Thanks for this information ;-) VERY useful !! @boscorelly : thanks for this question !
