### ISSUE TITLE
Question : Is it possible to create Problems ?

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1578]
Hi to all !

I see we can create Changes and Tickets, but I don't see Problems :-/

Is it however possible ? Is it planned to develop it?

Thanks to those answers.

**Comment by btry** [comment]
Hi

This is possible, but not planned yet. You may consider to spnsor this development by contacting us : contact@teclib.com

**Comment by mab18** [comment]
Thanks for your answer ;-)

**Comment by btry** [comment]
Hi

Target Problems are implemented.
