### ISSUE TITLE
Compteur ticket reste à 0

### ISSUE THREAD

**Issue by orderman** [pluginsGLPI/formcreator#1579]
GLPI 9.4.4 / Formcreator 2.8.6

Bonjour,
Les compteurs (indicateurs de situation des ticket situés en haut de la fenêtre) reste à 0 malgré que des tickets soient attribués a un groupe technique ou en attente…

Il me semble qu'une demande existe déjà mais je ne l'ai pas retrouvé  

Cdt

Philippe LAFOREST

**Comment by btry** [comment]
Bonjour

Voyez #1575

**Comment by orderman** [comment]
Vu #1575 ca fonctionne

Merci
