### ISSUE TITLE
The user list also includes non-enabled ones

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1582]
**Describe the bug**
To reproduce :
Disable some users, note them.
In "post-only", 
(fast way) : click on numbers at left upper, (in progress, waiting, to be validated, closed), you see a filter corresponding with your user préselected. Click on the user list : you see the disabled users. 
(slow way) : click on (mes demandes d'assistance) my requests of assistance (don't know the real term in GLPI english), add a rule with requester, choose "IS", click on user list : same thing.

I think it's not normal in post-only. Users could be lost in the so long list.

**Expected behavior**
The user list should not let seeing the non-enabled users.

**Additional context**
GLPI 9.4.4+formcreator 2.8.6

**Comment by btry** [comment]
Hi

Please use a testing environment to check if this still happens with the future version 2.9.0 (use branch support/2.9.0)

I think the 1st case will not reproduce and the 2nd will reproduce.

**Comment by mab18** [comment]
Hi,
Deactivated still in the list in 2 cases
![image](https://user-images.githubusercontent.com/55535560/70922350-3ea3f500-2026-11ea-8d46-07d9ac076eee.png)
![image](https://user-images.githubusercontent.com/55535560/70922356-44013f80-2026-11ea-8dff-84b1b463aa73.png)

**Comment by mab18** [comment]
Hi,
I confirm deactivated users still in list.

**Comment by mab18** [comment]
Hi,
2.9.2 ? Est-ce compliqué de corriger ? Je ne me rends pas compte.

**Comment by btry** [comment]
Oui c'est compliqué : en interface simplifiée une dropdown pour choisir un utilsiateur est limitée à l'user actuellement connecté. Formcreator passe outre cette limitation. Il se passe 2 chose
- 1 pourquoi limiter uniqueemnt à l'user connecté ?
- 2 est il pertinent d'appliquer cette restriction au plugin ? (il y a les pour et les contre)

Enfin, la dropdown est affichée par le moteur de recherche et le plugin a peu de moyens pour ajouter des contraintes sur cette dropdown qui appartient à GLPI, pas à lui. Même appliquer la restriction que GLPI applique ailleurs rquiert une jointure entre 2 tables, et dans le contexte actuel, il n'y a pas de jointure permettant de  placer la condition.

Donc besoin d'étudier la question. De plus, d'autres bugs sont plus impacatants, plus urgents, donc peuvent mériter qu'une release soit faite même quand d'autres soucis ne sont pas résolus.

**Comment by mab18** [comment]
Merci pour cette réponse ;-)

**Comment by mab18** [comment]
Bonjour,
Je reviens sur cette lecture : 
Je ne comprends pas le problème de "la limite à l'utilisateur connecté". 
Utilisateur post-only ou pas, on ne devrait pas, dans le cadre de l'usage des utilisateurs pour destinataire, voir les désactivés dans une liste. Je ne comprend pas ce qui ne va pas avec ça. Je ne vois que de ma porte, sans doute y a-t-il d'autres contraintes que je ne connais pas.

Hi,
I come back to this reading:
I do not understand the problem of "limit to the logged in user".
Post-only user or not, we should not, in the context, see disabled ones. I don't understand what's wrong with that, Probably other constraints that I don't know are around this.

**Comment by btry** [comment]
Oui, je comprends votre point de vue. Initialement j'ai commencé à chercher comment filtrer les utilsiateurs inactifs, et j'ai eu l'idée de vérifier une partie de l'interface simplifiée de GLPI pour voir si cette restriction s'appliquait, et j'ai vu que GLPI n'affiche que l'utilsiateur actuellement connecté (ce qui va plus loin que filtrer les utilisateurs inactifs).

Du coup j'estime que le plugin devrait appliquer la même restriction, car si GLPI fait ainsi, c'est qu'il y a  une raison qui serait peut être valable également pour le plugin.

**Comment by mab18** [comment]
Mince, j'avais supprimé mon message pour ne pas vous polluer,  désolé pour ça :-/ .
Vous avez raison, il se peut que les utilisateurs inactifs puissent être nécessaires à sélectionner. Il faudrait pouvoir ajouter un critère "actif", qui n'est pas dans la liste des critères actuellement.
Un cas pour illustrer : des tickets créés par un utilisateur qui est parti et donc désactivé.
Avec votre réponse, et en relisant plusieurs fois, j'ai fini par voir autrement, grâce à vous.

Merci pour ces éclairages.

**Comment by btry** [comment]
Bonjour

Pas tant que ça : si GLPI limite la liste en interface simplifiée, Formcreator doit en faire de même, à moins qu'on identifie une raison valable.

Je mets en suspens car il y a d'autres tâches importantes sur le plugin à mener.

**Comment by btry** [comment]
Bonjour

Ce problème a été résolu il ya quelques mois partiellement, ce fix permet de restreindre tous les champs sur lesquels uen recherche est possible et cocnernant les utilsiateurs

https://github.com/pluginsGLPI/formcreator/pull/2214

**Comment by btry** [comment]
Hi

I the latest version of Formcreator all search criterias related to users are restricted as done in #2214. 

I think we can consider this issue solved as this prevents to show disabled users.
