### ISSUE TITLE
support 2.9.0 - breaks all criteria of forms already made

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1583]
Hi,
After upgrade to test support 2.9.0 : 
The update to "support 2.9" breaks all criteria of forms already made. 
The criteria are here, but contraints are disapeared, need to redo them :-//

I don't know what to log or send
![image](https://user-images.githubusercontent.com/55535560/70918060-c128b680-201e-11ea-9592-03fd236a2305.png)

**Comment by btry** [comment]
Hi

I found an error in the upgrade code.

Please run this query to fix your DB. You should recover your conditions

```sql
UPDATE `glpi_plugin_formcreator_conditions` SET `itemtype` = 'PluginFormcreatorQuestion' WHERE `itemtype` = 'plugin_formcreator_question'
```

A fix was uploaded. Thank you for this report.

**Comment by mab18** [comment]
This correction seem ok. it add duplicate tests (I kept the tests I had for correcting) = same criterias.
