### ISSUE TITLE
support 2.9.0 - duplicate form crash - fatal error

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1585]
**Describe the bug**
Fatal error: Uncaught Error: Class 'ImportFailureException' not found in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php:133 
Stack trace: #0 /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php(942): PluginFormcreatorTarget_Actor::import(Object(PluginFormcreatorLinker), Array, 12) 
1 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2033): PluginFormcreatorTargetTicket::import(Object(PluginFormcreatorLinker), Array, 24) 
2 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1502): PluginFormcreatorForm::import(Object(PluginFormcreatorLinker), Array) 
3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1567): PluginFormcreatorForm->duplicate() 
4 /var/www/html/glpi/inc/massiveaction.class.php(990): PluginFormcreatorForm::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginFormcreatorForm), Array) 
5 /var/www/html/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes() 
6 /var/www/html/glpi/front/massiveaction.php(59): Massiv in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php on line 133

**To Reproduce**
Try to duplicate a form see below : 

**Additional context**
[export_formcreator_20191217_105300.json.txt](https://github.com/pluginsGLPI/formcreator/files/3972672/export_formcreator_20191217_105300.json.txt)

**Comment by btry** [comment]
This commit should solve this issue ddbc5b23ea84c7431150d40f96479a5b41055c3c 

As i'm curently worling on the release of 2.9.0, this commit will go in 2.9.1.

**Comment by mab18** [comment]
With thix fix, it send the same error : 
PHP Notice: Undefined index: _group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php at line 133

Fatal error: Uncaught GlpiPlugin\Formcreator\Exception\ImportFailureException: failed to find a group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php:135 Stack trace: 
0 /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php(942): PluginFormcreatorTarget_Actor::import(Object(PluginFormcreatorLinker), Array, 10) 
1 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2033): PluginFormcreatorTargetTicket::import(Object(PluginFormcreatorLinker), Array, 13) 
2 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1502): PluginFormcreatorForm::import(Object(PluginFormcreatorLinker), Array) 
3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1567): PluginFormcreatorForm->duplicate() 
4 /var/www/html/glpi/inc/massiveaction.class.php(990): PluginFormcreatorForm::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginFormcreatorForm), Array) 
5 /var/www/html/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes() 
6 /var/www/html/glpi/fro in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php on line 135

**Comment by btry** [comment]
The patch above should fix the duplication issue on target_actors. Waiting for your feedback.

**Comment by mab18** [comment]
Hi !
Thanks for your job. ;-)

I applied the patch and when I try to duplicate a form, I have a blanck screen.
No error in php.log but sql.log reveals a problem: in my labels, I have quotes:

last error in sql.log (anonymized)
  SQL: INSERT INTO `glpi_plugin_formcreator_questions` (`name`, `fieldtype`, `required`, `show_empty`, `default_values`, `values`, `description`, `order`, `show_rule`, `plugin_formcreator_sections_id`, `uuid`) VALUES ('Motif 1', 'select', '1', '1', '', 'Application 1 (logiciel d'échange ou d'assistance d'un truc.)
Domaine 1, 2 et 3', '&lt;p&gt;Motif de la demande&lt;/p&gt;', '3', '1', '20', '7855e0f5-91f5039d-5dfb36c65b9f51.93753950')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'échange ou d'assistance d'un truc.)
Domaine 1, 2' at line 1
  Backtrace :
  inc/dbmysql.class.php:832
  inc/commondbtm.class.php:659                       DBmysql->insert()
  inc/commondbtm.class.php:1141                      CommonDBTM->addToDB()
  plugins/formcreator/inc/question.class.php:971     CommonDBTM->add()
  plugins/formcreator/inc/section.class.php:272      PluginFormcreatorQuestion::import()
  plugins/formcreator/inc/form.class.php:2007        PluginFormcreatorSection::import()
  plugins/formcreator/inc/form.class.php:1502        PluginFormcreatorForm::import()
  plugins/formcreator/inc/form.class.php:1567        PluginFormcreatorForm->duplicate()
  inc/massiveaction.class.php:990                    PluginFormcreatorForm::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:969                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()
  {"user":"123@srv-glpi"}

We can see a mixing between my (quotes, parentheses) and (quotes, parentheses) of sql syntax.

I think 

> '

 have to be preceded with a 

> \
so insert with ' have to transform to \'

**Comment by btry** [comment]
Hi
Thank you for the feedback.

If you have a blank screen then you have a PHP fatal error, resulting in a HTTP 500 response code. You will find a backtrace in your HTTP server log.

**Comment by btry** [comment]
It seems  that there is an escaping issue with a content containing a single quote.

**Comment by btry** [comment]
I added a commit to the PR. Please apply the patch again and feedback

https://github.com/pluginsGLPI/formcreator/pull/1586/commits

**Comment by mab18** [comment]
Excellent ! ;-)
Duplication works fine with this patch.

**Comment by btry** [comment]
OK, I merge it.

Thank you
