### ISSUE TITLE
[2.9.0] Users can view all forms

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1587]
**Describe the bug**
With the Self-Service profile, users can access all forms including those from entities that do not have access.

**Comment by btry** [comment]
Hi

And with an other profile, is the issue occurs as well ?

**Comment by btry** [comment]
I'm suspecting that your form has anonymous acces. Do you confirm ?

**Comment by jvergacas** [comment]
Taking a closer look at the problem, it is showing the categories but not the forms.
The 3 categories circled in red should not be displayed in the logged in profile. By selecting one of them, the forms shown are not the ones that should be in the category.
![Plugin-Fusion-2 9 0](https://user-images.githubusercontent.com/43650152/71017893-2e4b5300-20d6-11ea-93eb-bc824d63d106.png)

**Comment by btry** [comment]
Can you check if he bug occured in 2.8.x ?

**Comment by jvergacas** [comment]
This problem occurred in an older version, but in later versions (2.8.5 and 2.8.6) it does not occur.

**Comment by jvergacas** [comment]
Hi @btry 

I googled and found the problem in versions 2.8.0 and 2.8.1, being fixed with  [fix(wizard): form categories may show when they are empty](https://github.com/pluginsGLPI/formcreator/commit/d3182ac4519e1e62373f57d2fa6ebc2fb1ed7932)

**Comment by btry** [comment]
Thank you

this is exactly hat I need to find. I guess I did a mistake while I updated this code to the new coding standards.

Please be patient : i'm on an other task right now.

If you're in a hurry, you might use this PR to do a quick fix.

**Comment by btry** [comment]
Hi

I'm investigating your issue. The commit you shared was merged in the version 2.9.0 then you're probably not in the scenario of the fix, or there is a regression.

I need to reproduce with a simple data set. Could you use an empty GLPI to build a set of categories, forms (and maybe entities) where the bug occurs ?

**Comment by jvergacas** [comment]
Hi

I tested on a clean GLPI and the problem is only in the forms category.
It is showing all categories, including those that the user does not have access to, forms that the user does not have access to are not shown.
When the user clicks on a category they do not have access to, they are shown category forms that the user has access to.

In the previous version (2.8.6) the categories of forms it does not have access to are not shown.

Thanks.

**Comment by mab18** [comment]
Hi !
@jvergacas : I'am seeing this issue and I have a question : How do you setting rights about categories forms ?

**Comment by jvergacas** [comment]
Hi @mab18 

I set entity access permissions and transfer forms to these entities, and if the user does not have entity access, the category is empty and not shown in the category menu.

This works until version 2.8.6, as of 2.9.0, the category is displayed but with other forms that should not be in this category.

I haven't had time to properly parse the category.class.php file so I replaced this file with plugin version 2.8.6

Thanks.
Jean

**Comment by btry** [comment]
Hi

There is no relation between form categories and entities. A category is displayed only if there are forms or FAQ in its subtree.

Then the regression occurs when counting items in a category.

**Comment by jvergacas** [comment]
Hi @btry 

Exactly. If the user does not have access to the entity, the forms and the category will not be displayed.
The problem is that, in this case, it shows categories with forms that do not belong to the category but belong to the user entity.

Thanks.

**Comment by mab18** [comment]
Thanks for explains @jvergacas ;-)

**Comment by btry** [comment]
Hi @jvergacas 

I found 2 issues related to a bad entity restriction, leading to SQL errors. I'm suspecting your issue has the same cause. Could you try the following fix and fedback ?

https://github.com/pluginsGLPI/formcreator/pull/1851

**Comment by btry** [comment]
hi @jvergacas @mab18 

Can one of you test the above patch and feedbaack ?

**Comment by jvergacas** [comment]
Hi @btry 

Now, it is working fine.

**Comment by btry** [comment]
Thank you, i'll merge the fix.
