### ISSUE TITLE
Unable to delete a form (v 2.8.6)

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1589]
**Describe the bug**
I want to delete a form that is in the trash and I have a blocking error message. I cannot delete this form. I am super-user other old forms are abble to supress without problem.
Message in red at lower right :
Erreur
Opération échouée
(1 problèmes de droits, 0 échecs)
Saisie de formulaire xxxx - test (1) : Erreur d'habilitation

v2.8.6

**Comment by btry** [comment]
Hi

Are you using a mass action to delete the form ?

**Comment by mab18** [comment]
Hi,
I have no other choice, because Suppress definitively is not present !
![image](https://user-images.githubusercontent.com/55535560/71245629-73a99380-2315-11ea-8f2f-7356a048a20b.png)

**Comment by btry** [comment]
Hi 

you have at least one answer for this form, and purge is forbiden because of that. you muse first check that all answers can be deleted and delete them.

The fix above adds a message to warn the admin.

**Comment by mab18** [comment]
Hi !
Happy new year ;-)
It's a good option : we know why it's not working. I tested it ok.
What to do to translate the text ?
