### ISSUE TITLE
Duplicate form - error message in one line and furtively v2.8.6

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1590]
**Describe the bug**
When I duplicate a form, it's seems to work ok, but I have a message that appears furtively : 
![image](https://user-images.githubusercontent.com/55535560/71189501-3694c100-2283-11ea-9868-7fba06864d1b.png)
On one form.
![image](https://user-images.githubusercontent.com/55535560/71189655-75c31200-2283-11ea-97cc-e22afaf53359.png)
On 2 forms differents.
in my forms, I have those 2 sorts of problem. I just realize that problem, it's so fast...
I don't know if this problem is on2.9.0/1 too, I'll try tomorrow

**To Reproduce**
Just duplicate the form, not all forms. 

**Screenshots**
See above

v2.8.6

**Comment by btry** [comment]
Ok, I'm not surprised, the fix will be probably similar to groups. Please wait until I find time to build the patch

**Comment by btry** [comment]
Hi

The issue should be fixed in version 2.9.0 because duplication was rewritten. If it still occurs, please leave a comment here.
