### ISSUE TITLE
Forms are not displayed correctly v.2.9.0

### ISSUE THREAD

**Issue by jonaigringo** [pluginsGLPI/formcreator#1594]
**Describe the bug**
Forms that require group validation are not displayed correctly. Fields do not carry information

**To Reproduce**
1. Go to home page
2. Click on any form
4. fields do not carry information

**Expected behavior**
Fields on forms that need validation should load fields correctly

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome and Opera
 - Version 79.0.3945.88 and 65.0.3467.78 

**Additional context**
The problem only happens with formcreator version 2.9.0

**Comment by btry** [comment]
Hi

please test this fix and feedback

**Comment by jonaigringo** [comment]
Solved! Thanks

**Comment by btry** [comment]
Please check the logs of your http server for an error 500 (you might check for its existence in the developper tools of your browser).

Which version of GLPI are you using ?

**Comment by jonaigringo** [comment]
v9.4.4

![image](https://user-images.githubusercontent.com/59033130/71887221-6dd8ee00-311c-11ea-866c-36004fa7dd68.png)

**Comment by btry** [comment]
Hi

Ok, You have a fatal error. Please check the logs of your http server. You should find the a backtrace for this error.

I'm not sure yet, but you may be impacted by a bug in GLPI 9.4.4 in the search engine.

Have a look here : https://github.com/pluginsGLPI/formcreator/issues/1575

**Comment by jansenarruda** [comment]
Hi
I´m facing same error @jonaigringo jonaigringo facing when viewing form answers. Here my http server log:

2020/01/09 11:34:15 [error] 1845#1845: *304 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PluginFormcreatorFields::isVisible() must implement interface PluginFormcreatorConditionnableInterface, instance of PluginFormcreatorTextField given, called in /var/www/glpi/plugins/formcreator/inc/formanswer.class.php on line 587 and defined in /var/www/glpi/plugins/formcreator/inc/fields.class.php:113
Stack trace:
#0 /var/www/glpi/plugins/formcreator/inc/formanswer.class.php(587): PluginFormcreatorFields::isVisible(Object(PluginFormcreatorTextField), Array)
#1 /var/www/glpi/inc/commonglpi.class.php(475): PluginFormcreatorFormAnswer->showForm('3', Array)
#2 /var/www/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFormcreatorFormAnswer), 'PluginFormcreat...', '', Array)
#3 {main}
  thrown in /var/www/glpi/plugins/formcreator/inc/fields.class.php on line 113" while reading response header from upstream, client: 172.30.6.216, server: GLPI_Server, request: "GET /ajax/common.tabs.php?_target=/plugins/formcreator/front/formanswer.form.php&_itemtype=PluginFormcreatorFormAnswer&_glpi_tab=PluginFormcreatorFormAnswer$main&id=3& HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "GLPI_Server", referrer: "http://GLPI_Server/plugins/formcreator/front/formanswer.form.php?id=3"

**Comment by btry** [comment]
Thank you @jansenarruda With this backtrace i could fond what happened

Please try this fix 5453a927

**Comment by jansenarruda** [comment]
Hi @btry 

Works like a charm here!!!!

Thank you!!!!!

Only a detail: In 'Print this form', don´t show the icon ...

![image](https://user-images.githubusercontent.com/17916404/72075887-5a23b800-32d3-11ea-9be1-17de31f8495d.png)

**Comment by btry** [comment]
Thanks, the print button should be fixed now:

2d871a38b55e17cc491df772bdb4cee143a85643

**Comment by jansenarruda** [comment]
@btry working now!!!!

thanks!!!
