### ISSUE TITLE
Formulaires saisis vide

### ISSUE THREAD

**Issue by tzoub** [pluginsGLPI/formcreator#1596]
Bonjour,
Depuis la mise à jour de GLPI de 0.85.5 à 9.4.1.1 l'onglet "Formulaires saisis" de tous mes formulaires est vide. J'ai lu un post à ce sujet mais cela n'a pas réglé mon problème. Le puglin est actuellement en version 2.8.6
![formulaire_vide](https://user-images.githubusercontent.com/59441767/71668420-20016600-2d69-11ea-84ba-1917c2ad8abd.png)

**Comment by btry** [comment]
Bonjour

Vous avez peut ête une erreur HTTP 500. Pour vous en assurer, utiliser les outils développeur de votre navigateur pour vérifier les réponses des requêtes HTTP. Si vous trovez une erreur HTTP 500, merci de partager le log de cette erreur enregistré dans le serveur HTTP. J'ai besoin du backtrace PHP.

**Comment by tzoub** [comment]
Bonjour,
Merci pour votre réponse. Je ne vois pas d'erreur HTTP 500 dans les différentes logs que j'ai à ma disposition. Par contre, j'ai des erreurs dans l'onglet console : 
![erreur_console](https://user-images.githubusercontent.com/59441767/71896923-51a57300-3155-11ea-833e-9f6bbf5373fd.png)

**Comment by btry** [comment]
Bonjour 

Les erreurs dans la console sont à priori un autre problème.

Sans backtrace je ne peux pas aller plus loin. Envisagez d'utiliser un environnement de test pour voir si le souci persiste avec la version 2.9.0. La série 2.8 est en fin de vie.

**Comment by tzoub** [comment]
Bonjour,
Comment vous fournir le backtrace php?
![console](https://user-images.githubusercontent.com/59441767/71990277-62c4b180-3233-11ea-983c-c27bca428696.png)
?

**Comment by btry** [comment]
Tout dépend de l'OS du serveur (Windows, Linux) et du logiciel servant votre GLPI (IIS, apache, NGINX, ...)

Consultez sa documentation pour trouvver les journaux contenant les erreurs du logiciel utilisé. Je ne peux pas m'étendre sur ce sujet car cela sort du contexte du plugin.

**Comment by tzoub** [comment]
Voici des logs PHP, en espérant que cela convienne
![backtrace](https://user-images.githubusercontent.com/59441767/71994422-fd73bf00-3238-11ea-982a-dbfdf07c5e31.png)

**Comment by btry** [comment]
Bonjour
C'est un backtrace, mais je pense qu'il provient de php-errors.log de votre GLPI.

Ce log est généré par du code PHP de GLPI et il ne peut pas contenir les erreurs fatales (car php va s'arrêter immédiatement).

Référez vous à la documentation de votre  serveur HTTP pour savoir où il stocke ses propres logs. Si vous ne savez pas où ils sont, je vous invite à prendre du support professionnel : https://glpi-project.org/fr/support/

**Comment by tzoub** [comment]
Bonjour,
En regardant le sql-error.log, je me suis rendu compte que la table glpi_plugin_formcreator_formanswers n'était pas correcte, j'ai ajouté la colonne groups_id_validator  et modifié la colonne validator_id par users_id_validator.
J'ai désormais un tableau avec les différents formulaire saisis, mais je devrais pouvoir les visualiser?
![formulaires_saisis](https://user-images.githubusercontent.com/59441767/72061783-d5d33400-32d6-11ea-8bd0-f31553c75345.png)
![formulaires_saisis-2](https://user-images.githubusercontent.com/59441767/72061787-d8358e00-32d6-11ea-9177-d277486e5299.png)

**Comment by btry** [comment]
Il y a peut être d'autres erreurs dans php-errors.log en lien avec cette nouvelle situation ?

La première chose à faire quand il y a une anomalie est de vérifier php-errors.log, sql-errors.log et si page blanche, onglet vierge, chercher une erreur 500 avec son backtrace les logs du serveur HTTP. LA plupart du temps le backtrace est indispensable ou permet d'accélérer la recherche d'un correctif.

**Comment by tzoub** [comment]
Non je ne vois rien en lien avec cette nouvelle situation. Peut-être est-ce du au trop grand ecart de version? A des informations non présente en BDD?

**Comment by btry** [comment]
Si vous avez eu une anomalie de structure d'une table, cela signifie qu'il y a eu un problème pendant un précédent upgrade du plugin. Vous devriez vérifier chaque table en BDD avec la structure décrite dans le fichier install/mysql/plugin_formcreator_empty.sql

**Comment by btry** [comment]
Bonjour

Pouvez-vous essayer la branche support/2.9.0 avec les correctifs faits jusqu'à maintenant ?

Il se pourrait que le souci soit résolu.

**Comment by tzoub** [comment]
Merci pour les réponses, j'ai comparé la structures des tables avec le fichier et mise à part deux format de colonnes, tout était OK.
Bien que maintenant la liste des formulaires saisi s'affiche, je n'ai pas le contenu des formulaires.

**Comment by btry** [comment]
Bonjour

Ce ticket est obsolète, je ferme.
