### ISSUE TITLE
Unable to add a second criteria to the "display field" section in a question

### ISSUE THREAD

**Issue by jnfohr** [pluginsGLPI/formcreator#1597]
Hi,

Since the update to v2.9.0 I cannot add a secondary criteria to the "display field" (affichage du champ)section in a question.

The server returns a 400 error, it seems some fields are missing in the ajax request.

When I hit the '+' the request is:
GET /plugins/formcreator/ajax/condition.php?items_id=X

whereas when I insert a first criteria I get:
GET /plugins/formcreator/ajax/condition.php?itemtype=PluginFormcreatorQuestion&items_id=X&plugin_formcreator_sections_id=Y

**Comment by btry** [comment]
Hi

Can you try the above patch and feedback ?

**Comment by jnfohr** [comment]
Hi

Thanks, it's fine now, I can add a second condition.

Regards,

Jean-Noel
