### ISSUE TITLE
Add the possibility to create several tasks in destination tickets

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/formcreator#16]
In the des tination "ticket" add the possibility to ad one or more tasks with specific title, description, categories, status, private or no, and assigned to fields.

The title and description must be parsed to replace TAGS by questions answers like in ticket.

**Comment by flegastelois** [comment]
Will be directed by the ability to add tasks in templates tickets GLPi.
So it's a GLPi-Core enhancement.
