### ISSUE TITLE
Forms is not in assistance menu anymore

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#160]
Forms is not in assistance menu anymore and administration neither

**Comment by neeftarah** [comment]
Hi,

In administration => Is the plugin activated (You always need to reactivate a plugin after update) ?
In assistance => Have you forms activated that you have access to ?

**Comment by satyan01** [comment]
Hello

It comes back to administration, my forms are activated but forms is not in assistance menu

**Comment by satyan01** [comment]
If  I switch to english, it disappears from administration

**Comment by neeftarah** [comment]
hi,

the commit above should fix your problem for administration menu.
In addition, assistance menu now appear only if their is some forms available.
Moreover a form is defined by language. So, for example, if they are defined in "French", they didn't appears in English.

**Comment by satyan01** [comment]
Hello,

Thank you, it works perfectly.
