### ISSUE TITLE
error call to a member function count() on array

### ISSUE THREAD

**Issue by ludovicbernard** [pluginsGLPI/formcreator#1601]
bonjour,
Après avoir crée près de 100 demandes d'un  même formulaires ( Assistance\formulaire) celui-ci plante avec comme message d'erreur 
error call to a member function count() on array in c:\wamp64\www\glpi\plugins\formcreator\inc\form.class.php on line 1284
lorsque je passe par (Administration\formulaire\ monformulaire\Prévisualisation ) celui fonctionne bien .

formcreator 2.9.0
glpi 9.4.5
wampserver : 3.1.3 64bit
Apache : 2.4.33 - PHP 5.6.35
MySQL 5.7.21
MariaDB 10.2.14

merci de votre aide.

**Comment by btry** [comment]
Bonjour

Essayez d'appliquer  ce correctif : https://github.com/pluginsGLPI/formcreator/commit/e6f4bc8e9a0527570c289579208d77910ce18aed

**Comment by ludovicbernard** [comment]
résolu merci. et vive formcreator
