### ISSUE TITLE
Ticket title not truncated

### ISSUE THREAD

**Issue by KMSRA** [pluginsGLPI/formcreator#1602]
**Describe the bug**
Ticket title is not truncated to 70 char as in classical ticket creation.

**To Reproduce**
1. a form is created with a ticket as target
2. target ticket title contains anwser of a text field
3. when this form is tested, generated ticket title is not truncated

See screenshots, same text issued with formcreator and classical ticket creation form.

![2020-01-10 14_56_56-GLPI - Formcreator - 1](https://user-images.githubusercontent.com/59735811/72158445-8a925180-33ba-11ea-9ca1-4dc613cfb14c.png)

![2020-01-10 15_02_53-GLPI - Tickets](https://user-images.githubusercontent.com/59735811/72158457-95e57d00-33ba-11ea-8928-0685e999a7cf.png)

**Expected behavior**
The ticket text title must be truncate to 70 chars.

**Desktop (please complete the following information):**
 - OS: Windowns 10
 - Browser firefox and chrome

**Additional context**
GLPI version 9.4.5
Tested on v2.9.0 and v2.9.0-beta.1 with same behaviour

**Comment by btry** [comment]
Hi

It seems that the limit is 250 chars, coded as a length in the input field in the TML code of the page (creation of a ticket).

I found a limit to 70 in the php code here

https://github.com/glpi-project/glpi/blob/99afae96ccfdf7d97415af4423a5698c84bb3225/inc/commonitilobject.class.php#L1391

It is applied when there is no title set to truncate the description.

In conclusion : 
the field is truncated if it exceeds 250 chars when the title is set.
The field is limited to 255 chars in the databaase, making the title be truncated to 255 chars if the title of a ticket is generated by formcreator.
it is truncated to the 70 first chars of the description if the title is not set.

I think there is nothing to fix here, or maybe to limit to 250 chars if we want to be very picky.

**Comment by KMSRA** [comment]
Great it works 👍  thanks for your rapid answer.
I set no title and put answer in description :
![2020-01-10 15_29_15-GLPI - Formcreator - 1](https://user-images.githubusercontent.com/59735811/72160532-c5968400-33be-11ea-8a91-0bf3598b60a5.png)
Howerver, the red star is confusing because title seems mandatory.

**Comment by btry** [comment]
You're right, this red mark is obsolete now. Here is a fix: 45ae5c11
