### ISSUE TITLE
Can't access to my forms - fatal error

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1604]
When I create a new form, or when accessing to older ones, I have this errror (debug) :
Fatal error: Uncaught TypeError: Argument 1 passed to PluginFormcreatorFields::isVisible() must implement interface PluginFormcreatorConditionnableInterface, instance of PluginFormcreatorTextField given, called in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php on line 587 and defined in /var/www/html/glpi/plugins/formcreator/inc/fields.class.php:113 Stack trace: #0 /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php(587): PluginFormcreatorFields::isVisible(Object(PluginFormcreatorTextField), Array) #1 /var/www/html/glpi/inc/commonglpi.class.php(475): PluginFormcreatorFormAnswer->showForm('240', Array) #2 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFormcreatorFormAnswer), 'PluginFormcreat...', '', Array) #3 {main} thrown in /var/www/html/glpi/plugins/formcreator/inc/fields.class.php on line 113

**To Reproduce**
Click on "reponse au formulaire" on a form.

**Expected behavior**
The link to the ticket

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/72247817-075d3f80-35f6-11ea-9c44-d403e5b66f3c.png)

**Additional context**
GLPI 9.4.5+Formcreator 2.9.0

**Comment by btry** [comment]
Hi

Please try the branch release/2.9.1 . I think it is already fixed. The version 2.9.1 will be released soon.

**Comment by mab18** [comment]
Does I have to download all the 2.9.1 ?

**Comment by btry** [comment]
You have 2 choices : 
- download the whole project from github, but you will need to build the plugin yourself
- patch your copy 

This commit is the fix you need: https://github.com/pluginsglpi/formcreator/commit/5453a92

**Comment by mab18** [comment]
I choose patch : excellent ! 
It work again :-)

THANKS

**Comment by btry** [comment]
Thank you for your feedback.
