### ISSUE TITLE
Bouton + sur les conditions d'affichage

### ISSUE THREAD

**Issue by benshoes** [pluginsGLPI/formcreator#1605]
**Describe the bug**
Le bouton + pour ajouter des conditions ne fonctionne pas. (chrome et IE)
Le - fonctionne

**Screenshots**
![image](https://user-images.githubusercontent.com/53210764/72249414-a3d51100-35f9-11ea-88e7-a3b8d2b5d8c6.png)

**Comment by btry** [comment]
Bonjour 

LE fix sera dans la release 2.9.1 : https://github.com/pluginsGLPI/formcreator/pull/1598

**Comment by benshoes** [comment]
Merci beaucoup ;)
Bonne journée et super boulot
