### ISSUE TITLE
unable to delete the actors targeted in the change section

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1607]
**Describe the bug**
In a form of change, actors cannot be deleted, none of Applicant / Observer / Attributed to
If I add one, I can't delete it, persone, group, or every thing else.

**To Reproduce**
Try to delete actor in a form of change type.
[Edit : ] press the X icon does nothing and noting in the logs.

**Expected behavior**
Should be deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/72332494-6d12ff80-36ba-11ea-93fc-a2f93cc5ae72.png)

GLPI 9.4.5+formcreator 2.9.1

**Comment by btry** [comment]
Hi

Try this patch, it should solve your issue: 62e0de19

**Comment by mab18** [comment]
Excellent ! :-)

This patch corrects the problem !
