### ISSUE TITLE
Validation ne fonctionne plus

### ISSUE THREAD

**Issue by Belface** [pluginsGLPI/formcreator#1608]
GLPI 9.4.5 / FormCreator 2.9.0

Bonjour
depuis la mise vers le plugin 2.9.0, la validation des formulaires ne fonctionne plus.
Voici des captures réalisées avec le compte Super-Admin

**Formulaire sans validation**

![Capture](https://user-images.githubusercontent.com/55400519/72338951-c46a9d00-36c5-11ea-97d3-e67e6b6b8d2e.JPG)

**Le même formulaire avec validation (utilisateur ou groupe)**

![Capture2](https://user-images.githubusercontent.com/55400519/72338971-d0eef580-36c5-11ea-870c-103a44d121f6.JPG)

Comme vous pouvez le voir, le bouton envoyer disparait, et la zone de validation (en bas) n’apparaît plus.

Merci par avance

**Comment by btry** [comment]
Bonjour

J'ai eu effectivement une remontée que je parviens pas à reproduire.

Pouvez-vous exporter le formulaire en format JSON et le déposer ici ?

**Comment by Belface** [comment]
Merci de votre réponse ; le voici 

[export_formcreator_20200114_1341.zip](https://github.com/pluginsGLPI/formcreator/files/4059159/export_formcreator_20200114_1341.zip)

**Comment by Belface** [comment]
Je viens d'installer la version FormCreator 2.9.1. Voici le changement

![Capture](https://user-images.githubusercontent.com/55400519/72346193-b9b80400-36d5-11ea-876d-9a5c9ae12dc4.JPG)

**Comment by Belface** [comment]
J'aurai une question : dans la version antérieure à Formcreator 2.9, en bas du formulaire, apparaissait la liste déroulante des groupes (ou utilisateurs) qui valident. Dans cette nouvelle version, cette liste n'apparait pas. En validant, la demande apparait directement dans la liste des réponses aux formulaires.

Est-ce un fonctionnement normal ?

**Comment by btry** [comment]
Bonjour

Si il n'y a qu'un seul validateur possible, la dropdown est désormais cachée et le validateur sélectionné automatiquement. C'est une feature qui a été demandée il y a longtemps par la communauté.

Si vous n'avez qu'un seul validateur possible, alors c 'est normal.

**Comment by Belface** [comment]
Super, donc ok pour ce point la... merci
J'ai repéré 2 dysfonctionnements : 
- Le ticket n'est pas créé une fois le formulaire validé
- La demande n’apparaît pas dans la liste de **"Mes derniers formulaires (Valideur)"**

![Capture](https://user-images.githubusercontent.com/55400519/72348037-c5a5c500-36d9-11ea-9e8a-a06a281a6d9f.JPG)

Alors qu'en regardant dans **"Tous mes formulaires (Valideur)"**, je retrouve mes dernières demandes

![Capture2](https://user-images.githubusercontent.com/55400519/72348090-e241fd00-36d9-11ea-97bb-87c20bd8a87d.JPG)

Souhaitez vous que je déclare des incidents différents dans Git ?
Merci

**Comment by btry** [comment]
Oui : i lfaut faire 1 ticket par problème, sinon, c'est compliqué traiter le fil de discussion. 

Une fois fait, vous devriez pouvoir effacer votre message ici (sinon, je m'en occupe) pour nettoyer le fil.

**Comment by Belface** [comment]
Donc tout est ok
Merci

**Comment by btry** [comment]
Le souci de bouton a donc disparu avec la version 2.9.1 ?

**Comment by Belface** [comment]
Oui, désolé, j'ai oublié de le préciser... la mise à jour à corriger le problème

Merci

**Comment by btry** [comment]
Ok, donc souci résolu, merci pour le retour
