### ISSUE TITLE
In a change, urgency is inverted between question and specific

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1609]
**Describe the bug**
In a form to make changes, when selecting urgency specific formcreator search about values in questions in the form and when selecting urgency from question, it search in GLPI values. ;-)

**To Reproduce**
see screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/72339790-3becfc00-36c7-11ea-9d95-37112a08f818.png)
![image](https://user-images.githubusercontent.com/55535560/72339844-5d4de800-36c7-11ea-90b6-46da353662b5.png)

**Additional context**
GLPI 9.4.5 + formcreator 2.9.1 (plus some patchs)

**Comment by mab18** [comment]
Add : I think it's the same thing with resolution time : 3 choices seems shifted.

**Comment by btry** [comment]
Hi

Indeed, there is a mistake in the JS code. Here is the fix for urgency: 9be5e3aa

**Comment by btry** [comment]
2nd fix for due date resolution: 4ddb6e8f

**Comment by mab18** [comment]
Hi !
It's ok for the 2 patchs ;-)

**Comment by btry** [comment]
Great ! Then I close. Thanks for your feedback

**Comment by Sicoval31** [comment]
Bonjour,
ticket fermé mais un bug reste présent car si le choix est désormais correctement possible concernant le temps de résolution ; à l'enregistrement, la sélection choisie est pas conservée mais pas les paramètres.

**exple** : 3eme choix :  calculée à partir de la question ; je choisis la question et le paramétrage.
Quand j'enregistre les modifications, le choix reste, les paramètres ne s'affichent plus.
De plus, si la question est renseignée, le ticket ne se crée pas ...

GLPI 9.4.2 - FC 2.9.1

**Comment by btry** [comment]
OK je réouvre, et je regarde bientôt.

**Comment by btry** [comment]
Bonjour

Si le bug n'existe qu'avec le champ Date & heure, c'est peut être en lien avec un changement qui a eu lieu autour de GLPI 9.4.3. J'ai dû ajouter la prise en charge des secondes, ce qui case le fonctionnement de ce type de chanmp avec GLPI 9.4 de révision inférieure. 

Essayez d'upgrader GLPI à la dernière version 9.4.6, et voyez si le problème persiste.

**Comment by mab18** [comment]
Bonjour,
Je n'arrive pas à reproduire ce cas... contexte GLPI 9.4.6+correctifs / FC 2.10.1

**Comment by btry** [comment]
Bonjour @mab18 

si vous êtes en GLPI 9.4.6, je pense que le bug ne se reproduira plus. Du coup, votre retour d'expérience me confirme que le bug n'existe qu'avec les premiers GLPI 9.4.x et comme il vaut mieux upgrader vers 9.4.6 voire 9.5, j'estime que ce problème est obsolète.

**Comment by mab18** [comment]
Je propose de clore ce ticket : je n'arrive pas à reproduire ni les priorités, ni les dates, effectivement, il a dû être corrigé avec les montées de version.

Merci de votre réponse.

**Comment by btry** [comment]
J'approuve également. Je ferme.
