### ISSUE TITLE
Ticket non créé après validation

### ISSUE THREAD

**Issue by Belface** [pluginsGLPI/formcreator#1610]
GLPI 9.4.5 / FormCreator 2.9.1

Bonjour
depuis la mise à jour vers le plugin 2.9.1, les tickets ne sont plus créés après validation.

Merci

**Comment by btry** [comment]
Bonjour

Je ne reproduis pas. J'ai essayé avec cun utilsiateur validateur.

Combien de validateurs avez vous dans svotre formulaire, et de quel type (utilsiateur ou groupe) ?

**Comment by Belface** [comment]
Bonjour Btry
erreur de ma part... mon formulaire n'avait plus de cible.
Tout fonctionne.
Le ticket peut être cloturé

**Comment by btry** [comment]
Bonjour

Ca me rassure :)

Merci pour le retour
