### ISSUE TITLE
Demande en attente de validation n'apparaissent plus

### ISSUE THREAD

**Issue by Belface** [pluginsGLPI/formcreator#1611]
GLPI 9.4.5 / FormCreator 2.9.1

Bonjour
depuis la mise à jour vers le plugin 2.9.1, la demande n’apparaît plus dans la liste de **"Mes derniers formulaires (Valideur)"**

![Capture](https://user-images.githubusercontent.com/55400519/72349350-a8bec100-36dc-11ea-859f-70ef644c3ed2.JPG)

Alors qu'en regardant dans **"Tous mes formulaires (Valideur)"**, je retrouve mes dernières demandes

![Capture2](https://user-images.githubusercontent.com/55400519/72349361-aeb4a200-36dc-11ea-9853-4e014089e578.JPG)

Merci

**Comment by btry** [comment]
Bonjour

J'ai trouvé une anomalie récemment sur la liste. Elle devrait être triée par ordre décroissant de date.

Essayez ce commit : 9ed9e871032f338c450ee6d98935e6c25b064eda

**Comment by Belface** [comment]
Le correctif corrige bien le pb pour les demandes dans la liste **"Mes derniers formulaires (Valideur)"**
Merci
 
Par contre, je me pose une question ; dans la liste **"Mes derniers formulaires (Demandeur)"**, j'y vois bien les demandes refusées ainsi que celles en attente : 

![Capture](https://user-images.githubusercontent.com/55400519/72351400-8fb80f00-36e0-11ea-8d62-c1ae5e4c2ad8.JPG)

Mais lorsque je valide la demande, celle-ci n’apparaît pas en validée dans cette même liste

![Capture2](https://user-images.githubusercontent.com/55400519/72351449-a9595680-36e0-11ea-93c4-534e4dccd9cd.JPG)

Il s'agit peut être d'un fonctionnement normal ?
Merci par avance

**Comment by btry** [comment]
Les deux listes (avec le patch ci dessus) affichent au maximum 5 demandes, triées avec 2 critères
- le statut par ordre croissant
- la date par ordre décroissant

Le statut validé est la valeur la plus élevée, et vous avec déjà 5 demandes avec un statut différent. Du  coup elle n'apparait pas dans la liste.

Si vous cliquez sur le lien en bas de la liste vous devriez retrouver votre demande validée.

**Comment by btry** [comment]
Je vais modifier le libellé des 2 zones pour p réciser la limite à 5 éléments.

**Comment by Belface** [comment]
Si je comprend bien, le tri se fait d'abord par le statut du ticket (refusé, validé, en attente, ...) , puis par la date ?
Si oui, est-ce qu'un classement par la date (uniquement) ne serait pas plus judicieux ? (les statuts seraient ainsi mélangés)

**Comment by Belface** [comment]
...et les 5 demandes affichées seraient bien les 5 les plus récentes

**Comment by btry** [comment]
Bonjour

Oui c'est bien cela. Le but de ces 2 critères de tri est de montrer les demandes non validées (en attente ou refusées) en priorité. Celles qui sont validées devraient avoir moins d'intérêt dans ces listes. Les utilisateurs qui ne sont pas restreints au catalogue de services ont accès aux tickets et peuvent suivre leurs demandes via la lite des tickets.

**Comment by btry** [comment]
Expliciter la taille de la liste dans l'UI 4f7cf5dc53538e9f78b1178fc3ff81b04360ef2c

Pour ne pas modifier les chaines localisables dans une version corrective, je place ce changement dans la version 2.10, sinon la traduction connue sera perdue le temps que la communauté fasse les mises à jour.

**Comment by Belface** [comment]
C'est noté pour le comportement de l'affichage.
Vous pouvez donc clôturer ce ticket

Merci

**Comment by btry** [comment]
Merci pour le retour. Vous devriez pouvoir appliquer le correctif sur la 2.9 et mettre à jour les traductions localement.
