### ISSUE TITLE
[2.9.x] Accueil / Formulaires : Arborescence disparu

### ISSUE THREAD

**Issue by maravtdm** [pluginsGLPI/formcreator#1612]
Depuis la version 2.9.x l'arborescence des formulaires a disparu de la page d'accueil (Accueil/Formulaires)
On ne voit plus que les catégories (qui ne sont pas "cliquables") et les formulaires sont disponibles qu'en cliquant sur le menu-parent "Formulaires" en haut des menu-enfants.
Aucun formulaires des menu-enfants n'apparait

Avant (en v2.8.5)
![GLPI - Interface standard-forms-v2 8 5](https://user-images.githubusercontent.com/11086888/72363482-34444c00-36f5-11ea-9cf0-658b5900de49.png)

Après (en v2.9.1)
![GLPI - Interface standard-forms-v2 9 1](https://user-images.githubusercontent.com/11086888/72363498-3d351d80-36f5-11ea-9685-f3b07affc9c5.png)

Je précise que , mettre oui/non à l'option "Accès direct depuis la page d'accueil" ne change rien

**Comment by maravtdm** [comment]
De plus j'ai été obligé de renommé les menus, car le menu "Bureautique" bien que commencant par "2" figurait systématiquement en premier ...

**Comment by btry** [comment]
Bonjour

Commencez par rafraichir le cache du navigateur. Ensuite ouvrez les le options pour développeur du navitgateur et voyez si vous avez des erreurs 500. Si oui, vous trouverez des backtraces dans les logs du serveur HTTP. Si non, voyez si il y a des erreurs dans php-erros.log et sql-errors.log de GLPI

**Comment by maravtdm** [comment]
Re
Alors, aucune erreur 500, que du 200, tout va bien de ce coté la 
Rien non plus, malheureusement du côté php ou sql ...

**Comment by jvergacas** [comment]
https://github.com/pluginsGLPI/formcreator/issues/1606
