### ISSUE TITLE
[2.9.x] Text area type question

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1613]
Hi

When we include a conditional display text area type problem, it prevents the next item from being displayed if the condition is not met.

thanks

**Comment by btry** [comment]
Hi

It looks like the bug is in GLPI; a closing HTML tag is missing when generating the textarea with the file drop area.

**Comment by btry** [comment]
Pleaase try this fix 8de43588

It expects the issue will be fixed in GLPI 9.4.6 or later

https://github.com/glpi-project/glpi/pull/6811

**Comment by btry** [comment]
Hi

The fix for GLPI was merged. You may choose the fix for GLPI or the workaround above. When GLPI 9.4.6 will be available, the workaround will be useless.

**Comment by jvergacas** [comment]
Hi @btry 

Now it is working fine.

Thanks
