### ISSUE TITLE
Heure bug le formulaire

### ISSUE THREAD

**Issue by tzoub** [pluginsGLPI/formcreator#1614]
Bonjour,
J'ai un formulaire dans lequel j'ai un champs date & heure obligatoire. Or, lorsque ce champ est renseigné, mon formulaire ne s'enregistre pas.
Si je modifie le type de ce champ en Date uniquement, le formulaire fonctionne.
Comment faire pour intégrer l'heure en plus de la date?

**Comment by btry** [comment]
Bonjour

il me semble qu'il y a eu un rapport de bug identique dans une version précédente de Formccreator (2.8.5 je crois). 

Celui ci devrait correspondre : https://github.com/pluginsGLPI/formcreator/issues/1562

Quelles versions de GLPI et de formcreator ?

**Comment by tzoub** [comment]
Bonjour,
Merci pour la réponse, je regarde le post ASAP.
Version de GLPI 9.4.1.1
Version du plugin 2.8.6

**Comment by tzoub** [comment]
Bonjour,
J'ai parcouru le post et, malgré que je sois en version 2.8.6 du plugin, j'ai tout de même le problème.
Est-ce que cela ne pourrais pas venir d'un update qui se serait mal passé?

**Comment by btry** [comment]
Bonjour

Non, je pense que c'est un autre souci. Je n'ai pas pu vérifier, mais je soupçonne un changement dans GLPI entre les version 9.4.x et 9.4.y (x étant à déterminer et y valant 3 ou 4). 

Quelle est votre version de GLPI ?

**Comment by tzoub** [comment]
Je suis en 9.4.1.1 de GLPI

**Comment by btry** [comment]
Utilisez un environnement de test pour vérifier si le bug persiste en 9.4.4 ou 9.4.5.

**Comment by btry** [comment]
Bonjour

Ce  ticket est obsolète.
