### ISSUE TITLE
[2.9.1] Mise en page

### ISSUE THREAD

**Issue by moccino** [pluginsGLPI/formcreator#1615]
GLPI 9.4.2
Formcreator 2.9.1

Bonjour, depuis le mise à jour en 2.9.1, la mise en page de GLPI avec les formulaires n'est pas correct.
Ci joint une capture d'écran.
la ligne du bas copyright GLPI vient chevaucher les formulaire…

Pouvez vous m'aider ?
merci

![FormCreator](https://user-images.githubusercontent.com/50907789/72443533-b2b0f480-37ae-11ea-9ed8-d83ec27e6d95.PNG)

**Comment by btry** [comment]
Bonjour

Voyez si ce patch pour GLPI arrange les choses

https://github.com/glpi-project/glpi/pull/6811

**Comment by moccino** [comment]
Tout fonctionne avec le patch. merci pour votre réactivité :)
