### ISSUE TITLE
[2.9.1] Capture d'écran volumineuse

### ISSUE THREAD

**Issue by moccino** [pluginsGLPI/formcreator#1617]
Bonjour,
Lors de l'ajout dans un ticket de d'une capture d’écran volumineuse, exemple: "imp écran" depuis un ecran 4K, le ticket est totalement vide, il n’ insert ni l'image ni le texte dans la description.

Merci de votre aide.

![image](https://user-images.githubusercontent.com/50907789/72516551-25bf7700-3852-11ea-805e-e72e88bca5fb.png)

**Comment by btry** [comment]
Bonjour

- Veuillez préciser la version du plugin, la version de GLPI.


- Vérifiez que la table glpi_plugin_formcreator_answers utilise un champ de tyle longtext pour stocker les valeurs : 

![image](https://user-images.githubusercontent.com/14139801/72517442-af237900-3853-11ea-8d14-39f452f150fb.png)

- Vérifiez les logs de glpi : sql-errors.log et php-errors.log.

- Enfin, vérifiez dans la BDD le contenu de la colonne content pour le ticket créé.

**Comment by moccino** [comment]
Les valeur BDD sont ok:

![image](https://user-images.githubusercontent.com/50907789/72519866-8487ef00-3858-11ea-8a79-af2596e12437.png)

![image](https://user-images.githubusercontent.com/50907789/72520001-ce70d500-3858-11ea-826e-c89ca9b5f544.png)

J'ai refait un test et l'image s'affice dans le ticket mais pas dans la descruption du ticket
Je rappel que se problème se pose uniquement avec des capture volumineuse...

![image](https://user-images.githubusercontent.com/50907789/72526713-53fb8180-3867-11ea-9ab4-391c37dba9dd.png)

php-errors.log:
[2020-01-16 13:50:26] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): Missing argument 1 for Auth::redirectIfAuthenticated(), called in /var/www/html/glpi/index.php on line 66 and defined
  Backtrace :
  inc/auth.class.php:1209                            
  index.php:66                                       Auth::redirectIfAuthenticated()
  {"user":"@sv-glpi01.dijon.fnclcc.fr"} 
[2020-01-16 13:50:35] glpiphplog.WARNING: Html::loadJavascript() in /var/www/html/glpi/inc/html.class.php line 6047
scripts/ind.js file not found from plugin mod!  {"user":"2078@sv-glpi01.dijon.fnclcc.fr"} 
[2020-01-16 13:50:35] glpiphplog.WARNING: Html::loadJavascript() in /var/www/html/glpi/inc/html.class.php line 6047
scripts/ind.js file not found from plugin mod!  {"user":"2078@sv-glpi01.dijon.fnclcc.fr"} 
[2020-01-16 13:50:35] glpiphplog.WARNING: Html::loadJavascript() in /var/www/html/glpi/inc/html.class.php line 6047
scripts/ind.js file not found from plugin mod!  {"user":"2078@sv-glpi01.dijon.fnclcc.fr"} 

sql-errors.log: Pas d'erreur

**Comment by btry** [comment]
L'erreur dans les logs php semble être un aute souci. 

Vous avez vérifié la table glpi_tickets, or c'est la table glpi_plugin_formcreator_answers qu'il faut vérifier. Cela dit, si l'image est intègre un des affichages, je pense que la colonne est correctement définie.

Vous n'avez pas précisé les  versions de GLPI et du plugin. Si vous êtes en version inférieure à 2.9.1, utilisez un environnement de test pour tester la dernière version. Il y a un changement qui pourrait résoudre votre souci.

**Comment by moccino** [comment]
le premier screen est celui de la table glpi_plugin_formcreator_answers et le deuxième screen est bien celui de la table glpi_tickets.

GLPI version 9.4.2
FormCreator 2.9.1

**Comment by mauriciolamego** [comment]
With me it mainly occurs when attaching copied images from whatsapp. Here's information if it serves as a parameter for improvement!

**Comment by btry** [comment]
Hi

The behavior described in https://github.com/pluginsGLPI/formcreator/issues/1617#issuecomment-575139126 might be solved in Formcreator 2.10 installed in GLPI 9.5. With GLPI 9.4, the problem may persist.

I'm interested if you can test GLPI 9.5 release candidate with Formcreator 2.10.0 . I expect the bug is solved as I contributed to GLPI to sove several problems with textareas.

**Comment by btry** [comment]
Hi

Can you check if the problem persists with the latest release of Formcreator and GLPI 9.5 ?

**Comment by btry** [comment]
Hi

Having no feedback, I close this ticket. Feel free to open a new one if this still occurs with the latest version. Using GLPI 9.5 is preferred as GLPI has been improved to solve issues related to Formcreator.
