### ISSUE TITLE
[2.9.1] Wrong assingned technician

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#1618]
The ticket is created with the status "Processing (assigned)" and the requester is defined as the assigned technician.

**Bug Description**
The ticket is created with the status "Processing (assigned)" and the requester is defined as the assigned technician.

**To Reproduce**
1. Create a simple form with the fields: title and descrition.
2. Define a target ticket with the assigned field empty.
3. Loging with a technician profile (Assistance - Beeing in charge).
4. Fill the form and send.
5. The ticket is created with status "Processing (assigned) and the requester is defined as the assigned technician.

**Expected behavior**
The ticket is created with status "New" and assigned field is empty. 

**Screenshots**
![filled_form](https://user-images.githubusercontent.com/26510405/72547334-36c8b200-386b-11ea-8656-5ffd9a13d0f4.png)

![target_ticket](https://user-images.githubusercontent.com/26510405/72547402-59f36180-386b-11ea-860e-72ac52de8d78.png)

![ticket_opened](https://user-images.githubusercontent.com/26510405/72547371-4cd67280-386b-11ea-8c9b-42197cfc7791.png)

![techprofile](https://user-images.githubusercontent.com/26510405/72547456-72fc1280-386b-11ea-9eb5-11aa91a0457f.png)

**Additional context**
This problem only appears when the user profile is setting with Assistance - Beeing in charge.

This bug is present in previous versions of the Formcreator.

**Comment by btry** [comment]
Hi

The behavior you described is normal. This behavior is implemented in GLPI and occurs because Formcreator builds data of the ticket then sends the data to GLPI for creation.

If you use GLPI without Formcreator to create a ticket (with an empty lis of assigned) when you're logged in as a technician + the right you pointed, the ticket will  have the status processing and the ticket is automatically assigned to the user.

**Comment by pedroluisvsousa** [comment]
Great! When I set up "Pre-select me as a technician when creating a ticket=No" (Personalization) works as expected.

![setup_no](https://user-images.githubusercontent.com/26510405/72727525-ddfa6180-3b69-11ea-8297-c63cae0a37aa.png)


Thanks a lot.
