### ISSUE TITLE
Forms menu is displayed two times

### ISSUE THREAD

**Issue by Kahalisto** [pluginsGLPI/formcreator#162]
Hello !

The Forms menu is displayed two times with the post-only profil

as you can see below
![image](https://cloud.githubusercontent.com/assets/14975836/11535134/c4d154f0-9912-11e5-96ba-1b5ce7b59473.png)

Version : 0.90-1.3.2

**Comment by vlegros** [comment]
Je confirme. J'ai le meme phénomene (idem en Anglais)
Vincent

**Comment by neeftarah** [comment]
Hi,

This bug is llinked to an HTML bug into GLPI. I modified Formcreator (see following commit) to fixed it, but the initial bug in GLPI will be corrected in next GLPI version.
