### ISSUE TITLE
[2.9.1] Problème affichage créateur du ticket

### ISSUE THREAD

**Issue by benshoes** [pluginsGLPI/formcreator#1622]
Lors de la création du ticket, le créateur n’apparaît pas.
Peut-être en lien avec l'issue #1621 car le créateur n'est pas dans l'entité du ticket

**Screenshots**
![image](https://user-images.githubusercontent.com/53210764/72820405-323b3980-3c6f-11ea-8e91-f41d72845f5e.png)

**Comment by mab18** [comment]
Hi, I see the same problem : ticket don't have the creator.

**Comment by btry** [comment]
Hi,

Do the form require a validation step ? Which version of the plugin ?

**Comment by benshoes** [comment]
No validation and 2.9.1 version

**Comment by btry** [comment]
Please show the actors of the target ticket which generated this ticket.

**Comment by benshoes** [comment]
are we obliged to put actors in the target or that is enough by the rules ?

**Comment by mab18** [comment]
Yessss...
![image](https://user-images.githubusercontent.com/55535560/74038455-83ae2d00-49c0-11ea-8d83-909baab60b6b.png)
Was missing !
Sorry for the noise ;-)
Thanks

**Comment by benshoes** [comment]
Yessss !!!!! :-D

**Comment by btry** [comment]
Probably : This actor is created automatically when you create the target ticket

**Comment by benshoes** [comment]
I try and I will give you feedback

**Comment by benshoes** [comment]
It's OK now.
Thx a lot
