### ISSUE TITLE
Update 2.8 > 2.9 perte destination formulaire

### ISSUE THREAD

**Issue by Blank-Vcf** [pluginsGLPI/formcreator#1623]
en prod glpi 9.3.2 avec plugin 2.8.5
les formulaires ont:
une Cibles > droit des profil
une Destinations > création ticket dans la bonne entité

dump de la base et bascule dans une base de test avec glpi en 9.4.5 et le plugin en 2.8.6
maj base glpi > ok
maj et activation du plugin > ok
cible et destination sont toujours ok

migration 2.8 > 2.9.1
suppression dossier plugin et recopie du nouveau
maj et activation plugin > ok

la table glpi_plugin_formcreator_targets est supprimés
dans le formulaire, les nom des champs changent:
cible est remplacé par Type d'accès > ok
destination par cible > tout est vide
tous les formulaires ont perdu leur cible

**Comment by btry** [comment]
Bonjour

Dans la version 2.9.0 la table la table glpi_plugin_formcreator_targets n'est plus utilisée. Il est normal qu'elle disparaisse.

Il y a un souci de migration autour de ce changemnt de structure.

**Comment by Blank-Vcf** [comment]
j'ai vu l'update dans le dossier d'install, mais pas de script sql pour le passer juste a la main et voir si j'ai des erreurs.

**Comment by btry** [comment]
Il y a pourtant bien du code d'upgrade pour mettre à jour les données

https://github.com/pluginsGLPI/formcreator/blob/v2.9.0/install/upgrade_to_2.9.php#L43

Je vais le revérifier. Si une correction est nécessaire, elle sera dans la prochaine releaase.

**Comment by btry** [comment]
Je viens de tester un upgrade d'un formulaire depuis 2.8.0 vers 2.9.1, les cibles sont upgradées correctement.

- Vérifiez que vous avez une table backup_glpi_plugin_formcreator_targets : c'est un renommage de la table glpi_plugin_formcreator_targets.

- Trouvez l'id d'un formulaire et voyez si ses cibles existent dans glpi_plugin_formcreator_targettickets et glpi_plugin_formcreator_targetchanges

**Comment by Blank-Vcf** [comment]
j'ai des erreur dans le log sql de glpi

> [2020-01-22 11:39:02] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
>   *** MySQL query error:
>   SQL: UPDATE `glpi_plugin_formcreator_targettickets` SET `plugin_formcreator_forms_id` = '20', `uuid` = '1fcdff7a-6dfcc468-5dcc12dc68b976.56758102', `name` = 'Demande d'accès ou de création d'un dossier réseau' WHERE `id` = '19'
>   Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'accès ou de création d'un dossier réseau' WHERE `id` = '19'' at line 1
>   Backtrace :
>   inc/dbmysql.class.php:948                          
>   plugins/formcreator/install/upgrade_to_2.9.php:83  DBmysql->update()
>   plugins/formcreator/install/install.php:135        PluginFormcreatorUpgradeTo2_9->upgrade()
>   plugins/formcreator/install/install.php:103        PluginFormcreatorInstall->upgradeOneStep()
>   plugins/formcreator/hook.php:48                    PluginFormcreatorInstall->upgrade()
>   inc/plugin.class.php:521                           plugin_formcreator_install()
>   front/plugin.form.php:47                           Plugin->install()
> 

les quote dans les titres des formulaires....

**Comment by btry** [comment]
Oik, c'est un souci d'échappement d'apostrophes.

**Comment by btry** [comment]
essayez ce patch 
```diff
diff --git a/install/upgrade_to_2.9.php b/install/upgrade_to_2.9.php
index 2afda11f..f8e42cfb 100644
--- a/install/upgrade_to_2.9.php
+++ b/install/upgrade_to_2.9.php
@@ -77,7 +77,7 @@ class PluginFormcreatorUpgradeTo2_9 {
                [
                   $formFk => $target[$formFk],
                   'uuid'  => $target['uuid'],
-                  'name'  => $target['name'],
+                  'name'  => Toolbox::addslashes_deep($target['name']),
                ],
                [
                   'id' => $target['items_id'],
tb
```

**Comment by Blank-Vcf** [comment]
La migration se fait ce coup sans erreur, par contre dans la table glpi_plugin_formcreator_targettickets , le colonne plugin_formcreator_forms_id est pas remplie.
Si je remet les bons ids, j'ai tout dans glpi.

**Comment by btry** [comment]
C'est peut être parce que bous n'avez pas restauré votre BDD avant de relancer la migration.

**Comment by Blank-Vcf** [comment]
C'est tout ok avec une base propre.
Merci bien

**Comment by btry** [comment]
Merci pour le retour; je ferme.
