### ISSUE TITLE
Add request/issue field

### ISSUE THREAD

**Issue by boscorelly** [pluginsGLPI/formcreator#1624]
I need the possibility to set if the form will create a ticket with an issue or a request type.

For now, it only create an issue.

**Comment by btry** [comment]
Hi

Create a ticket template with a predefined request type then assign this template to the  target ticket. In a future version you will be able to set the request type from Formcreator.

**Comment by boscorelly** [comment]
an empty template ?

my ticket is populated directly from informations from the answers

**Comment by btry** [comment]
No : create a new template, then link the target ticket of your form to this template. 
![image](https://user-images.githubusercontent.com/14139801/72905307-a4c01e00-3d30-11ea-9159-5b63ca318089.png)

![image](https://user-images.githubusercontent.com/14139801/72905374-bc97a200-3d30-11ea-8725-da06c3e5c290.png)

**Comment by boscorelly** [comment]
Thanks !

**Comment by btry** [comment]
Hi

FYI : 2.10.0-beta.1 is imminent.  In this release you will be able to set the type of the target ticket without using a template. A fixed one or from a question : Request Type.

![image](https://user-images.githubusercontent.com/14139801/73373880-98503e00-42b9-11ea-892c-215e2be96a28.png)
