### ISSUE TITLE
upgrade plugin : You must run vendor/bin/robo build:fa-data in the directory of the plugin

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1625]
Bonjour,
en voulant faire un update de la version de FC de la 2.8.3 à la 2.9 ou 2.9.1, j'ai ce message d'erreur :
You must run vendor/bin/robo build:fa-data in the directory of the plugin

Que faire exactement ?
Merci

**Comment by btry** [comment]
Bonjour
Installez composer à partir des dépôts de votre distribution linux. Si vous n'utilsiez pas linux, vous avez fait un mauvais choix :laughing: vous devrez télécharger composer sur https://getcomposer.org et bidouiller votre PATH.

Ensuite, dans le dossier du plugin exécutez 
- composer install
- vendor/bin/robo build:fa-data comme indiqué dans l'UI de GLPI.

Pour éviter tout cela, je vous conseille d'utilsier le build du plugin disponible dans les releases au lieu d'utilsier les sources (qui est plutôt à réserver pour le développement)

**Comment by yalgva** [comment]
thx
