### ISSUE TITLE
2.9.1 - destination : choix de l'urgence 

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1626]
Merci pour les modifications apportées par rapport à la 2.8.3 (et qui répondent à quelques une de mes demandes).
Un petit bug relevé dans la partie destination du formulaire sur le choix de l'urgence.
Si je choisis 
- urgence spécifique : il me demande à quelle question
- Réponse à une question : il me liste les urgences spécifiques

**Comment by btry** [comment]
Bonjour

Oui, il y a eu une inversion ici et sur 1 autre champ. La correction est faite, mais pas encore livrée.

Cherchez dans les tickets fermés, de mémoire j'ai précisé les commits contenant les corrections.

**Comment by btry** [comment]
Bonjour,

le cas étant traité (voir l'autre ticket), je ferme.
