### ISSUE TITLE
No form Is displayed on homepage when access type is Restricted access

### ISSUE THREAD

**Issue by kabassanov** [pluginsGLPI/formcreator#1627]
**Describe the bug**
Since version 2.9.0, when a form is created and its access type is defined as Restricted access (by profiles*), even if the form is configured with Direct access on homepage set to Yes, it is not visible. 

**To Reproduce**
1. Go to Home/Administration/Forms
2. Click on '+'
3. Fill Form Name
4. Set Sub-entities to Yes
5. Set Active to Yes
6. Set Directed access on homepage to Yes
7. Click on Add
8. Go into the freshly created form
9. Choose Access types, then Restricted access, then a profile and Save.
10. Login to GLPI with an user from the selected profile.
11. Look for the form on the homepage.
12. Cry...

**Expected behavior**
Display the form table on homepage

**Additional context**
It still works in 2.8.6

**Comment by btry** [comment]
Hi

This fix should solve your issue. Please apply it and feedback

https://github.com/pluginsGLPI/formcreator/commit/841d459bdedc26596d8eaedc5cfd213982c1e9d8

**Comment by kabassanov** [comment]
Is getFormRestrictionCriterias a new function? In 2.9.1, I have showForCentral with this:

 $formProfileFk    = Profile::getForeignKeyField();

**Comment by kabassanov** [comment]
Anyway, applying these two modifications to showForCentral in 2.9.1 doesn't seem to be enough...

**Comment by btry** [comment]
Ok, then revert this patch and try this one. While searching for a fix, I found necessary to factorize some code, and it successfully fixed the bug on my instance.

41152255a776ce3c0c6c1fdace2f3549b1cc3992

**Comment by kabassanov** [comment]
This one is ok for me. Thanks.

**Comment by btry** [comment]
Great, thank you for your feedback.
