### ISSUE TITLE
2.9.1 : affichage section sous condition

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1630]
Je viens de tester l'affichage d'une section sous condition : ça ne fonctionne pas que la question soit une liste déroulante (choix multiples ou pas), une case à cocher ou un bouton radio.
Pas de message d'erreur
FC 2.9.1 et glpi 9.4.2

**Comment by Sicoval31** [comment]
bon ben ... tout fonctionne. j'comprends pas ?!

**Comment by btry** [comment]
Il peut y avoir des soucis si on crée des conditions sur une section qui n'existe pas encore. Je suis en train de corriger ce genre de souci.
