### ISSUE TITLE
2.9.1- bouton "bring top" ne fonctionne pas

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1631]
Le nouveau bouton permettant de bouger une question en tête de section ne fonctionne pas. 
Rien ne se produit.

FC 2.9.1 et glpi 9.4.2

**Comment by btry** [comment]
Bonjour

Le bug a été corrigé, il faut attendre la prochaine release

**Comment by btry** [comment]
Bonjour 

le bug étant corrigé, et à défaut de vor epart, je ferme le ticket.
