### ISSUE TITLE
Liste des questions : affichage de plus d'infos

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1632]
C'est la journée bug/features ! désolé
Est-il possible d'ajouter des colonnes sur l'affichage des questions de façon à avoir les questions sur lesquelles un affichage conditionnel est mis (pas la condition, mais juste le fait qu'il y ait une condition), une regex, un controle de saisie, etc ...

PS : si l'affichage des questions 2,3,4 est soumis à la réponse de la question 1 ; la suppression de la Q1 ne supprime pas la condition des Q2,3 et 4 ; d'où ma demande de pouvoir afficher si une question est soumise à condition pour faire les modifs plus facilement

**Comment by btry** [comment]
Normalement, la suppressuin d'une question doit entrainer la suppression des conditions la concernant. Il y a donc bug.

**Comment by btry** [comment]
Bonjour,

Je pense que ce correctif devrait résoudre votre souci: f3f4899ef8ed107eb9d7d2e9f0e7a57f7bf065a9

**Comment by btry** [comment]
Bonjour,

A défaut de etour de votre part, je ferme ce ticket.
