### ISSUE TITLE
Create New Question Error

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1635]
**Describe the bug**
When creating a new question for newly created form, it throws an error which is "form is not defined".

**To Reproduce**
1. Go to newly created form on Forms tab.
2. Click on questions tab.
3. Add new question.
4. Click save.
4. See error on web console.

**Expected behavior**
It should save the created question by the user.

**Screenshots**
<img width="1439" alt="Screen Shot 2020-01-28 at 16 11 07" src="https://user-images.githubusercontent.com/60381082/73246211-ffea8880-41e8-11ea-9aaf-4e846831f36b.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [79.0.3945.130]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment]
Hi

i tried the release 2.9.& and the version 2.10 to be released soon. I don't reproduce.

Can you tell your version of the plugin ?

**Comment by btry** [comment]
humm, Ok, I just saw your PR, then you're probably running the develop version.

**Comment by leecheromerevilit** [comment]
> humm, Ok, I just saw your PR, then you're probably running the develop version.

Yes I'm running the develop version.

**Comment by btry** [comment]
I edited the commit message and merged it. Thank you for your contribution.
