### ISSUE TITLE
Question "textbox" encapsulates the items underneath

### ISSUE THREAD

**Issue by R00t3n3d** [pluginsGLPI/formcreator#1638]
**Describe the bug**
Since the upgrade to Formcreator 2.9.1 since 2.9.0, When I create a question in a form with the "Textbox" type, all other objects below the question are encapsulated in the HTML by the textbox. Therefore, when I try to hide the section in which this question is located, it hides the whole rest of the form.

**To Reproduce**
1. Go to "Administration > Forms" 
2. Chose or create one
3. Create a question with the type "textbox".
4. Create another question with any of the types below
5. Hide only the question with the type "textbox" (With, for example, hide by default unless).
6. The other questions below are also hidden

**Expected behavior**
If I hide the question with a "Textbox" type, I want this question only to be hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/46027518/73354873-08010180-4297-11ea-9670-99dc91fd552a.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Brave, Firefox, Chrome
 - Version Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
GLPI version : 9.4.3

**Comment by btry** [comment]
Hi

You're  right; this is a bug in GLPI. There is a patch  ready for the version 9.4.6: https://github.com/glpi-project/glpi/pull/6811

The next version of Formcreator will include a workaround.

**Comment by R00t3n3d** [comment]
Thanks for your answer, I will see to update my GLPI

**Comment by btry** [comment]
Hi 

Your bug should be solved if you upgrade to Formcreator 2.9.2+ with GLPI 9.4.6+ . Can you test and feedback ?

**Comment by btry** [comment]
Hi

HAving no feedback, I close this issue. Feel free to create a new one if the problem persists with the latest release.
