### ISSUE TITLE
After last update some fields are missing in the form

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#164]
I have a form with 20 questions, after migration to last master the form displays 9 fields on 20.

**Comment by neeftarah** [comment]
Hi,

Formcreator don't limit the number of questions and I also have some forms with more than 10 questions without problems.
So I will need more informations.

Maybe an issue on a particular field and / or value?
Can you give me the questions configurations and values?
Do you use conditional display? Maybe with some values with quotes?

**Comment by neeftarah** [comment]
Hi,

Do you still have this problem?
If yes, can you give me more details?

Best regards,
Jérémy

**Comment by satyan01** [comment]
the issue is fixed. thx

**Comment by satyan01** [comment]
Sorry but the issue is not fixed, I have the same issue. last version of form creator and last master glpi.

Maybe an issue on a particular field and / or value? it stops at job function field but without condition and not mandatory
Can you give me the questions configurations and values?

 Last Name *    *  *  *  
 First Name *  *    *  *  
+ Add a question  

Company Information

 Same Access As *    *  *  *  
 Entry Date *  *  *  *  *  
 Official Start Date *  *  *  *  *  
 Company  *  *  *  *  *  
 Department *  *  *  *  *  
 Title ID *  *  *  *  *  
 Job Function *  *  *  *  *  
 Internal *  *  *  *  *  
 Temporary *  *  *  *  *  
 End Date *  *  *  *  *  
 Manager *  *  *  *  *  
 Comments *  *    *  *  
+ Add a question  

IT Materials

 Computer / Igel *    *  *  *  
 Blackberry *  *  *  *  *  
 Blackberry Phone Number *  *  *  *  *  
 Visit Card *  *  *  *  *  
 Specific Software Needs *  *  *  *  *  
 Nice Recording 

Do you use conditional display? Maybe with some values with quotes?

Conditional display on temporary /end date / without quotes

**Comment by neeftarah** [comment]
Hi,

I try to reproduce your form but I can't reproduce your issue.

What is the type of question "job function" and its parameters ?

Have you some errors related to this on your logs files (glpi/files/_log/sql-errors.log and glpi/files/_log/php-errors.log) ?

Witch browser do you use ? And do you reproduce your issue on all browser (Firefox, Chrome...) ?

**Comment by satyan01** [comment]
Hello

Happy new year !


What is the type of question "job function" and its parameters ? ldap select / paremeter : (& (samaccountname=*) (&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))

Attribute ldap title

Show empty yes

Required no

Have you some errors related to this on your logs files (glpi/files/_log/sql-errors.log and glpi/files/_log/php-errors.log) ? no

Witch browser do you use ? And do you reproduce your issue on all browser (Firefox, Chrome...) ? chrome does not work and IE works



Thank you for your excellent work



Yannick



[Unigestion's logo]<http://www.unigestion.com/>



Yannick Labbé
IT Service Desk & IT Training
IT

Unigestion SA
8c, avenue de Champel CP 387
CH 1211 Genève 12



Dir.  +41 (0) 22 704 44 46

Tel.  +41 (0) 22 704 41 11



Fax. +41 (0) 22 704 43 84

Fax. +41 (0) 22 704 42 11



ylabbe@unigestion.com<mailto:ylabbe@unigestion.com>

www.unigestion.com<http://www.unigestion.com>







[LinkedIn logo]  Follow Unigestion on LinkedIn.<http://www.linkedin.com/company/unigestion>







[Awards]<http://www.unigestion.com/awards>



Funds Europe Awards 2015 Winner
Asset Management Firm of the Year (under €20bn) <http://www.unigestion.com/awards>

**Comment by neeftarah** [comment]
Hi,

Sorry but still cannot reproduce your bug :'(

If it work on IE, maybe a javascript error ?

Can you give me more detail : OS of your server, PHP version and the lists of the values of the "job function" question (in your LDAP) ?

Best regards,
Jérémy

**Comment by satyan01** [comment]
no more issue after glpi 9.2 upgrade
