### ISSUE TITLE
pied de page GLPI apparait en permanene sur le formulaire

### ISSUE THREAD

**Issue by orderman** [pluginsGLPI/formcreator#1640]
![piedpageGLPIsurformcreator](https://user-images.githubusercontent.com/49547111/73363798-b2822000-42a9-11ea-9097-2f4663dc4b38.JPG)

GLPI 9.4.5 / Formcreator  2.9

Bonjour,

sur ma plateforme de test
lorsque j'ai un formulaire qui occupe plus que la hauteur de page  et nécessite un scroll
le pied de page indiquant la version GLPI reste accroché au milieu du formulaire même si je scroll
Sur des formulaire plus petit je n'ai pas ce pb
pb apparait sur Edge et Mozilla (je n'ai pas testé chrome)

A noter que sur la version précédente de GLPI j'avais aussi le problème

Cdt

Philippe

**Comment by btry** [comment]
Bonjour

Avez vous un champ de type textarea dans le formulaire ? Est ce que le bug persiste sur un formulaire sans ce type de champ ?

**Comment by orderman** [comment]
Bonjour,

Tout a fait
Sans le champ de type textarea dans le formulaire
Je n’ai plus le soucis

Cdt

Philippe



De : btry <notifications@github.com>
Envoyé : mercredi 29 janvier 2020 15:34
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] pied de page GLPI apparait en permanene sur le formulaire (#1640)


Bonjour

Avez vous un champ de type textarea dans le formulaire ? Est ce que le bug persiste sur un formulaire sans ce type de champ ?

**Comment by btry** [comment]
Ok, donc voyez le patch pour GLPI mentinné dans cet autre ticket: 

https://github.com/pluginsGLPI/formcreator/issues/1638

**Comment by orderman** [comment]
Bonjour,

Application du fix Ok
Le problème n'est plus présent
Vous pouvez clôturer ce post
Merci pour tout
Cdt

Philippe

**Comment by btry** [comment]
Bonjour

J'ai reçu une notification où vous dites que le souci est résolu. Le mesage a apparemment été effacé. J'ai donc un doute. Problème résolu ou pas ?

**Comment by orderman** [comment]
Oui en effet j’ai répondu au mail et alors que je venais d’ajouter un post en direct (que j’ai voulu effacer) pour ne pas faire doublons
Désolé
Mais oui le soucis est résolu

Cdt

**Comment by btry** [comment]
Ok, merci por le retour.
