### ISSUE TITLE
[2.9.1] Form Formcreator assignment to a group since a question

### ISSUE THREAD

**Issue by Nitro76210** [pluginsGLPI/formcreator#1642]
Hi all and thank you very much to btry for the plugin,

**Environment :**
I'm using GLPI version GLPI 9.4.5 (PHP 7.2.10)
with plugin Formcreator : 2.9.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [IE, Firefox]

**To Reproduce**
I created a new form where a question look for GLPI group (Internal group of GLPI, not LDAP).
So, In the targuet of my form, I need to automatically assign my ticket to the group I selected in the form question "Service Destinataire".
In "Assign to" field, I selected "Group since question" and I selected the question "Service Destinataire".

**Expected behavior**
When I validate and click "Add" button, He said "Group since the question "N/A"".  Normaly, it must said  "Group since the question Service Destinataire"
When i create a new ticket, automatic assign don't work.

**ScreenShoots**
![image](https://martincalais-my.sharepoint.com/:f:/g/personal/fdepreux_martincalais_fr/EhiEA_3jc1pGlLYxLc-e7qwBAsfbuoxiUPtt7f2Xsx1vVA?e=ogp4n8)
![image](https://user-images.githubusercontent.com/14139801/73438299-1cec9c00-434e-11ea-84b9-ef2351118ff6.png)

Do you have an idea ? 

Thank you in advance,

**Comment by btry** [comment]
Hi

This issue may be already fixed in  the version 2.10. Could you try the branch support 2.10.0 on a testing environment and feedback ?

**Comment by Nitro76210** [comment]
I'm sorry but I don't found the testing version in https://github.com/pluginsGLPI/formcreator/tree/develop
Can you say me where i can download the tests version ?

**Comment by btry** [comment]
Here is the good link: https://github.com/pluginsGLPI/formcreator/tree/support/2.10.0

You will need to build an archive yourself with Composer and Robo. If you don't have those skills, please wait a few days : i will release a beta version very soon., with a pre-built archive.

**Comment by Nitro76210** [comment]
Ah ok thank you very much.
I don't know to build the archive. I can wait few days the beta version.

**Comment by Nitro76210** [comment]
Problem solved by 2.10 beta version. Thank you a lot
