### ISSUE TITLE
2.9.1 : bouton envoyer, champs et section masqués sans condition

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#1644]
Bonjour, 
suite au passage de la 2.8.3 en 2.9.1, j'ai sur certain formulaire des sections et champs qui disparaissent lors de la saisie du formulaire.
Pire, j'ai en même temps le bouton "envoyer" qui n'apparait pas.
a noter que ni ces champs, ni ces sections n'ont de conditions d'apparition mise en place.

en revanche, j'ai dans le formulaire certains champs qui en ont.
Si j'active la réponse faisant apparaitre ces champs, j'ai alors les champs et sections anormalement masqués qui apparaissent.

Merci pour votre aide
Cdlt

**Comment by btry** [comment]
Bonjour Vous êtes probablemetn en GLPI 9.4.x avec x <= 5. 

Essayez ce patch : 

https://github.com/glpi-project/glpi/pull/6811

**Comment by Sicoval31** [comment]
effectivement, j'allai envoyer l'export des formulaires.
en revanche, je n'ai pas de champs type fichier, mais textarea.
il faut que je passe en 9.4.5 ? (très frileux vu les remontées négatives des ralentissements constaté à priori !)
[export_form_sico31.zip](https://github.com/pluginsGLPI/formcreator/files/4134930/export_form_sico31.zip)

**Comment by btry** [comment]
La  version 9.4.5 de GLPI contient encore le bug. LE patch n'est inclus dans aucune release à ce jour, il faut attendre la version 9.4.6.

D'ici là, Formcreator incluera un contournement. Si vous le pouvez, patchez vote GLPI avec le corretif ci dessus. Quand vous passerez à Formcreator 2.10 (j'espère la livrer bientôt) vous devrez supprimer le correctif. 

Enfin, avec GLPI 9.4.6 il n'y aura plus rien à gérer.

**Comment by Sicoval31** [comment]
Merci beaucoup, 
correction apportées dans le fichier html.class.php de glpi ; ça semble être bon.
pour info V9.4.2 de glpi

**Comment by btry** [comment]
Merci pour le retour. Je ferme.
