### ISSUE TITLE
Microsoft icon doesn't works

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#1645]
When we choose the Microsoft icon for the form. This icon is not displayed correctly :

![image](https://user-images.githubusercontent.com/2960490/73519652-f2f4b180-4401-11ea-89ff-260a677a29b1.png)

We use GLPI 9.4.5 and FormCreator 2.9.1.
Others icons work correctly.

Tested on Google Chrome and Firefox.

**Comment by btry** [comment]
Hi

Please try this fix: 69786c67bfb5eff71ded4fa33bf45535a7af52e2

**Comment by lolokai** [comment]
It works perflectly : thank you
