### ISSUE TITLE
[2.9.1] attachment in the text area, not present in the ticket

### ISSUE THREAD

**Issue by TOH2F** [pluginsGLPI/formcreator#1646]
![image](https://user-images.githubusercontent.com/60504041/73526450-8d102600-4411-11ea-9591-f7435acb66a0.png)

is it possible to separate the upload from the text area?

In the target it is also impossible to make a link on the document.

Thank you for your help

**Comment by btry** [comment]
Hi

I will rework this part to see if I can drop this upload area. I'm not sure this is possible. If I find a solution I expect to deliver the change in version 2.11. I expect to deliver this version before the summer 2020.

**Comment by TOH2F** [comment]
the upload in itself is not annoying, but it does not appear void in the ticket is it possible?

**Comment by btry** [comment]
Hi
I reproduce only if I select a file fron the file area you highlighted (I think that dropping a file here will also trigger the bug)

**Comment by btry** [comment]
Hi

I found how to handsle the uplaods in textarea without having the file dorp zone.

Please try this fix and see if you still have images in the target ticket and form answer (worked fine for me)

https://github.com/pluginsGLPI/formcreator/pull/1653

**Comment by TOH2F** [comment]
Thank you very much for your work !

**Comment by btry** [comment]
I guess it worls as expected ?
