### ISSUE TITLE
Problem with section hidden by conditions

### ISSUE THREAD

**Issue by brtok** [pluginsGLPI/formcreator#1652]
I created 3 sections with questions type text area, that are shown if a value is selected in the radio option.
It happens that when selecting one of the options, the corresponding section appears:
![form1](https://user-images.githubusercontent.com/11841638/73580609-ea819280-4464-11ea-8da1-6dfdaff9b720.png)

But when selecting the second or third option, the corresponding sections are not shown.
![form2](https://user-images.githubusercontent.com/11841638/73580618-eeadb000-4464-11ea-82c4-4b30bb7e2922.png)

GLPI: 9.4.5
Form Creator: 2.9.1
Browser: Google Chrome

Recreate:
1 - Create a form, insert 4 sections.
2 - Insert 1 radio question with 3 options on the first section
3 - Insert 1 text area question on the 3 other sections below
3 - Make every section with the text areas "hidden unless" equals one of the radio options

**Comment by btry** [comment]
Hi

https://github.com/glpi-project/glpi/pull/6811

**Comment by brtok** [comment]
Perfect @btry !
Thanks for help!
