### ISSUE TITLE
New functionality - Question

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1654]
New functionality

When using the question "GLPI Object" and "Tickets", it is possible to select only by the Ticket Title.

Is it possible to select by ID? It would be a great way to use the "Related tickets" option when opening the ticcket.

**Comment by mab18** [comment]
Hi, 
Lol, I write the same thing in #1669 ;-) 
The title was not clear.

**Comment by phamorais** [comment]
@btry 

Up! :)

**Comment by mab18** [comment]
Hi @phamorais , please see https://github.com/pluginsGLPI/formcreator/issues/1669

**Comment by btry** [comment]
Hi

Thanks @mab18 for the link with your own issue. I close this one as the you reported the patch worked for you.
