### ISSUE TITLE
invalid character for change type forms

### ISSUE THREAD

**Issue by mauriciolamego** [pluginsGLPI/formcreator#1656]
**Describe the bug**
as can be seen in the image when filling out a change form, the fields are receiving invalid characters, making it difficult to read.

**To Reproduce**
1. when filling the form with the destination "type" change

**Expected behavior**
we hope that there are no invalid characters, and that paragraphs and spaces are presented correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/40633272/73665910-b2569b80-4680-11ea-9638-eb002ae36467.png)

**Desktop (please complete the following information):**
 - OS: [WINDOWS 10 1903]
 - Browser [CHROME]
 - Version [Versão 79.0.3945.130 (Versão oficial) 64 bits]

**Comment by btry** [comment]
Hi

Please tell the version of GLPI and the plugin.

**Comment by mauriciolamego** [comment]
FORMCREATOR 2.8.6 and GLPI 9.4.4

**Comment by mrcssilvasouza** [comment]
It also occurs in version 2.9.1 with GLPI 9.4.5

**Comment by mrcssilvasouza** [comment]
It is also not allowing to pre-define the checklist.

![image](https://user-images.githubusercontent.com/30185683/80529115-58a6fa00-896d-11ea-9b8b-ba448a95f779.png)

**Comment by btry** [comment]
Hi

@mrcssilvasouza : please create a distinct ticket for your issue. 

I'll focus on the release 2.9.2 with a last fix and then I'll look at this one.

**Comment by mrcssilvasouza** [comment]
ok thanks
