### ISSUE TITLE
[INTERNAL] can't save field type email

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/formcreator#1657]
**Describe the bug**

**To Reproduce**
1. create field type email
![image](https://user-images.githubusercontent.com/7335054/73726623-2bf99280-4730-11ea-8006-979fe84dbfaf.png)

2. on save formcreator display this 
![image](https://user-images.githubusercontent.com/7335054/73726663-3b78db80-4730-11ea-9126-db29b42dfd9a.png)

3. Same result if y provide default email

No error log

**Expected behavior**
Can save field type email

**Additional context**
GLPI 9.4.5
FormCreator : develop branch

**Comment by btry** [comment]
fixed in 2ee1bd5a
