### ISSUE TITLE
[INTERNAL] textarea field unexpected behavior

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/formcreator#1660]
**Describe the bug**

**To Reproduce**
1. create form with textarea
2. Try to fill form
3. plugin ask if i want to leave or stay

![image](https://user-images.githubusercontent.com/7335054/73731442-cb228800-4738-11ea-9312-a5a7bf3f8625.png)

Export of my form
[export_formcreator_20200204_1027.zip](https://github.com/pluginsGLPI/formcreator/files/4152413/export_formcreator_20200204_1027.zip)

**Expected behavior**
Save target like other form

**Additional context**
GLPI 9.4.5
Formcreator : develop branch

**Comment by btry** [comment]
I have a PR pending for this field type

https://github.com/pluginsGLPI/formcreator/pull/1653

Do the issue still occurs with it ?

**Comment by stonebuzz** [comment]
Hi @btry 

its caused by -> https://github.com/glpi-project/glpi/pull/6433
