### ISSUE TITLE
[Question] How to export form answers

### ISSUE THREAD

**Issue by iPaulis** [pluginsGLPI/formcreator#1666]
**Is your feature request related to a problem? Please describe.**
I am trying to find a way to export form answers, for example, in a CSV, but I cannot find any. Is there anything I am missing? how can I export one or many form answers in CSV or something similar? I am using v2.8.5 of the plugin in GLPI v9.3.2

If I remember correctly, I would say there was a table view with all the answers in an earlier version of the plugin, so then we could use filters and export in different formats. It could get a bit messy visually, but it worked. 
However, at some point it stopped showing answers directly and started showing just the basic info as an index, and after clicking one form it shows the answers inside.
There is the option to print that, to create a PDF for example, but only one by one, so it makes it more difficult to check and compare answers between several forms, and impossible to filter data depending on an answer.

With an export to CSV all of that would be solved.

**Describe the solution you'd like**
I would like to have the option to export the answers and work and curate that data outside GLPI. Excel, CSV or any other way to check all the answers in a table view would really help. 
Also an option to download all documents linked with those form answers, with the form ID in their name, or organized in subfolders by ID,... some way not to mix all documents of different forms between them.

**Describe alternatives you've considered**
-To display all answers in a table view and export them with another plugin.
-To access the database directly, select and export the data, but it is not user friendly and I would like non sysadmin GLPI users (with the appropriate role and permissions) to have the option to export form answers themselves to work with that data.

Thank you in advance for all your help and for this wonderful plugin, it really makes my work easier.

**Comment by btry** [comment]
Hi

The answers should be available in the answers list for a form. After a code reviex and a test I noticed the feature is broken.

Could you try this patch ? If you use a version 2.8 or 2.9, the patch may need slight changes for backport.

https://github.com/pluginsGLPI/formcreator/pull/1667/files

**Comment by iPaulis** [comment]
Hi, I am using v2.8.5, I would like to update it to the latest version eventually, but I cannot at the moment because we are using GLPI v9.3.2 for now, so we would have to update GLPI first to support the latest versions of the plugin, and we are not going to update GLPI yet.

Version 2.8.6 is the latest one that supports GLPI v9.3.x, right?
I could try the patch if it supports GLPI v9.3.x.

P.S.: This is my view of the form answers. As you see, answers are not shown directly, only the list of submitted forms. Then, answers are shown inside, but are not exportable.
![Screenshot from 2020-02-06 13-02-05](https://user-images.githubusercontent.com/11468889/73936161-7d498380-48e2-11ea-9df3-9b4154e0f25d.png)
![Screenshot from 2020-02-06 13-35-18](https://user-images.githubusercontent.com/11468889/73937559-99025900-48e5-11ea-8801-8b838b69ae31.png)

**Comment by btry** [comment]
Hi

I regularly rewrite parts of the plugin to raise code quality. This makes many patches complicated or impossible to backport. I won't backport patches to versions reaching end of life (or the plugin will not evolve anymore).

You should consider to upgrade to GLPI 9.4.5 as GLPI 9.3.x also reached end of life.

About your issue, it seems the feature broke long ago. The fix is quite big already, and still growing. This patch cannot be backported to your version : some code refactor are required to make it work properly.

**Comment by btry** [comment]
The PR is ready for tests;  but it cannot be backported.

**Comment by btry** [comment]
#1667

**Comment by iPaulis** [comment]
Hi, I completely understand. I will upgrade to newer versions of GLPI as soon as I possibly can.
I hope this patch solves the exporting issue and you can include it in a newer version release. I will try it when I upgrade everything else.

Thank you for your help.

**Comment by btry** [comment]
I think the feature you need is provided by GLPI, in the red rectangle.

the fields of the answers were not displayed, I fixed this and did some improvements. However some fields won't show here (file and description for example). No search for now : i'm unsure this is possible due to some field types like checkboxes and multiselect.

![image](https://user-images.githubusercontent.com/14139801/74031511-f6fc7280-49b1-11ea-8b04-5a7102ded564.png)

**Comment by btry** [comment]
Hi @iPaulis 

Do you have feedback ? I want to know if I should merge the fix.

**Comment by btry** [comment]
Hi

Having no feedback I close this issue.

**Comment by iPaulis** [comment]
Hi, sorry for not replying earlier.

We finally were able to move on to GLPI v9.4.6 a while ago, and recently updated the formcreator plugin from v2.8.5 to v2.9.2 and now to v2.10.4, which is the latest one supported by GLPI v9.4.6.

I was checking if you finally were able to implement the fix, but I see that the problem still remains; form answers are not shown.
I could not give you feedback because the plugin and GLPI versions that we had were not compatible.

If you already managed to fix the issue, as shown in the screenshot, did you implement it in a release later than v2.10.4? or are you planning on implementing it in a later release?
I mean, I won't be able to test it now if it is not backported, because I am still in GLPI v9.4.6, but I would like to be able to see the form answers eventually when I am able to update to GLPI v9.5.5 or later.

Could anyone else with compatible versions check the fix? is everybody else also not being able to see form answers? or am I the only one having this problem?

Sorry for the inconveniences and thank you for your time.

**Comment by btry** [comment]
Hi

It appears that very few people want this feature. You're maybe alone with this need. Without feedback, I did not merged the patch and is not maintained. I remember that this pr might break a few things in the plugin. Since then, Formcreator evolved, and I expect some work to update it. 

No recent version can export form data so far. 

Maybe could you consider to export data from the rest API of GLPI ?

**Comment by iPaulis** [comment]
Hi,

If I knew how I could export the data from the rest API I would, but I don't have any experience in that. Could you point out some guide I could follow? or any specific recommendation or steps to export this data using the API?

Anyway, that would only partially solve my problem, as my intention was to not have to be involved in the data export if it was user friendly enough for some non IT users at work to do it by themselves. 
Unfortunately, I don't have the time nor the resources to build a customized tool for an easy workflow of non tech savy users, that is why I was hoping this feature to be fixed eventually. 

Thank you for your help.

**Comment by btry** [comment]
Hi

GLPI provides in its root directory a file named apirest.md. It provides documentation about endpoints.

You need to know the concepts of itemtypes, search options (available in the developer documentation), and also know how the database is designed.


https://glpi-developer-documentation.readthedocs.io/en/master/devapi/search.html

https://github.com/glpi-project/glpi/blob/9.5/bugfixes/apirest.md
