### ISSUE TITLE
 sha1_file($path): failed to open stream: No such file or directory : no picture in ticket

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1668]
Hi,
**Describe the bug**
Unable to add picture in a ticket

**To Reproduce**
Create a form with ability to drag/drop picture or select one with the "choice file..."
click on send form : the picture in not in ticket. 
Add the same picture in GLPI directly works fine.

**Expected behavior**
Adding file as in GLPI in a ticket.

**logs**
In ./_log/php-errors.log : 
```
[2020-02-06 14:25:17] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): sha1_file($path): failed to open stream: No such file or directory
  Backtrace :
  :
  inc/document.class.php:562                         sha1_file()
  inc/commondbtm.class.php:5084                      Document->getFromDBbyContent()
  ...mcreator/inc/fields/textareafield.class.php:157 CommonDBTM->addFiles()
  plugins/formcreator/inc/formanswer.class.php:1247  PluginFormcreatorTextareaField->parseAnswerValues()
  plugins/formcreator/inc/formanswer.class.php:678   PluginFormcreatorFormAnswer->validateFormAnswer()
  inc/commondbtm.class.php:1098                      PluginFormcreatorFormAnswer->prepareInputForAdd()
  plugins/formcreator/front/form.form.php:132        CommonDBTM->add()
```
I have the file uploaded in /var/www/html/glpi/files/_tmp/auto_orient/ : 
`-rw-r--r-- 1 www-data www-data 2,5M févr.  6 14:26 5e3c13ff6d9be1.53245498IMG_20200204_190544.jpg
`
But the plugin seems to not seeing it !

**Desktop (please complete the following information):**
 - OS: Windows and Android
 - Firefox

**Additional context**
GLPI 9.4.5 + formcreator 2.9.1

**Comment by btry** [comment]
Hi

I assume you used a textarea field and you dropped the picture un the file area under the rich text input.

I found a fix to no longer need this drop zone. Maybe it will fix your issue. Could you test it and fedback ?

 https://github.com/pluginsGLPI/formcreator/pull/1653

**Comment by mab18** [comment]
I used the same function in the same block "in GLPI" and "in formcreator".
Please, I see the pull and I am a little bit lost in which files to update, could you help me ? 
I'll try a separate add file, just to see...

**Comment by mab18** [comment]
In a separate file add, it works well !
Is it possible to remove the part who add file in rich text ? 'Maybe the pull is the answer...

**Comment by btry** [comment]
yes : find the line ```'enable_fileupload' => true, ``` in the same file and switch it to false.

This change was done in an other commit, that's why there is no change in the diff of this PR.

**Comment by mab18** [comment]
other commit : okkkkk, I understand now ;-)

Why it works in GLPI and not in formcreator ? (It's ok for me to add a field to insert files, it's for understand the problem, and maybe somebody will have problems with the suppress of that function. I used it before, and it worked..)

**Comment by btry** [comment]
I added the file drop zone to fix the file upload issues in 2.9.1, to fix problems with file uploads. I did not found a smarter way at this time but a fix was really required. I finally found this way, which provides a metter UI for requesters. People wanting to upload files out of a textarea can user the file field.

**Comment by mab18** [comment]
It's correct : the functionality works in add a separate file zone, it's the essential ;-)
I also test the drag&drop: it works too with 'enable_fileupload' => false.

Thanks

**Comment by btry** [comment]
Great. I think the file upload issues are definitely fixed now. 

Thanks for your feedbback.

FYI  a release 2.9.2 will be released soon with a lot of bugfixes. This is the branch support/2.9.0

**Comment by mab18** [comment]
See too #1671 and patch [https://github.com/pluginsGLPI/formcreator/commit/4e5ed459d6ba95a08c9306828024a27fd5bed7d3]
