### ISSUE TITLE
Question type liste LDAP

### ISSUE THREAD

**Issue by clementodot** [pluginsGLPI/formcreator#167]
Bonjour,

En GLPI v. 0.90.1, une source d'authentification "Annuaire LDAP" a été créée vers un AD Windows 2012 R2. Dans GLPI, cela marche correctement (utilisateurs et groupes importés avec succès, capacité à trouver de nouveaux utilisateurs et groupes, etc.).

Dans "Formulaires" en revanche, une question de type "Liste LDAP" pointant vers le bon annuaire ne retourne aucun résultat (testé avec plusieurs attributs).

Comment puis-je troubleshooter ce problème ?

Merci.

**Comment by neeftarah** [comment]
Bonjour,

Formcreator se base sur la connexion GLPI pour la connexion à l'annuaire LDAP. Il n'y a donc aucune raison, à priori, pour que la connexion ne fonctionne pas.
En revanche, Formcreator à besoin, outre l'attribut, d'un filtre de connexion. Ce filtre est repris par défaut de la connexion LDAP, mais il est possible, selon votre configuration, que ce filtre ne soit pas bon.

Avez-vous des erreurs PHP lors de l'affichage d'un formulaire contenant ce type de question ?
(activez le "mode DEBUG" dans vos préférences ou consultez le fichier glpi/files/_logs/php-errors.log)

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
See #172

**Comment by neeftarah** [comment]
Bonjour,

N'ayant pas de retour de votre part depuis un bon moment, je ferme le sujet.

N'hésitez pas à le rouvrir avec plus d'informations si votre problème persiste.

Cordialement,
Jérémy
