### ISSUE TITLE
Form malfunction with sections

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1671]
**Describe the bug**
A form with many sections doesn't work correctly.

**To Reproduce**
See file 
[export_formcreator_20200207_1733-changement-test.zip](https://github.com/pluginsGLPI/formcreator/files/4171940/export_formcreator_20200207_1733-changement-test.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/74047198-3e91f700-49d0-11ea-923e-dec23750dac7.png)

**Additional context**
GLPI 9.4.5+Formcreator 2.9.1

**Comment by CDG47** [comment]
We have the same problem, the submit button disappear under the footer 
GLPI 9.4.5+Formcreator 2.9.1
![firefox_2020-02-13_09-58-59](https://user-images.githubusercontent.com/11661365/74417949-e2075f80-4e47-11ea-8c86-1a22a6190ca8.png)

**Comment by btry** [comment]
Hi

This occurs when the form contains a textarea. There is a HTML tag imbrication problem.

The issue should be solved with this patch for GLPI: https://github.com/pluginsGLPI/formcreator/commit/4e5ed459d6ba95a08c9306828024a27fd5bed7d3 

Also take note that the file zone under the textarea will be removed in 2.9.2. This is this zone which triggers the issue.

**Comment by CDG47** [comment]
Thanks, it's ok with this patch.

**Comment by btry** [comment]
Thank you for your feedback.

@mab18 : is the patch working for you as well ?

**Comment by mab18** [comment]
Hi, 
sry for delay
@btry  : It's perfect with the patch !!!
TY !!
