### ISSUE TITLE
[2.9.1] + GLPI 9.4.4 - Tickets Summary not counting and/or Working on Simplified Interface

### ISSUE THREAD

**Issue by gabrielpetrone** [pluginsGLPI/formcreator#1678]
**Describe the bug**
In user simplified interface, the ticket count its always 0 (zero) and when click on it, not works as expected listing my opened/pending/peding approval/closed tickets.

**To Reproduce**
1. Go to 'Forms' with an Simplified Interface profile
2. Click on closed tickets on ticket summary (top-left)

**Expected behavior**
Show the number of each summary itens and when click, list my closed tickets,

**Screenshots**
Now counting the number of tickets:
![image](https://user-images.githubusercontent.com/11214455/74277986-33eca000-4cf7-11ea-8d68-4090216685c0.png)
When clicked on 'closed' tickets:
![image](https://user-images.githubusercontent.com/11214455/74278070-5da5c700-4cf7-11ea-85c0-df19123678e4.png)
In Standard interface and same criteria:
![image](https://user-images.githubusercontent.com/11214455/74278415-f1779300-4cf7-11ea-8a7f-b484293bad21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 72.0.2

**Smartphone (please complete the following information):**
 - Device: Motorola G6
 - OS: Android 9
 - Browser: Firefox
 - Version: 68.4.2

**Additional context**
GLPI Version: 9.4.4
Formcreator Version: 2.9.1

**Comment by btry** [comment]
Hi

Please check the file glpi/files/_logs/sql-errors.log. Maybe there are some failing request.

It might be interesting also to check php-errors.log in the same director.

**Comment by gabrielpetrone** [comment]
In sql-errors.log is occurring this error with formcreator:

> [2020-02-12 07:50:16] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 188
>   *** MySQL query error:
>   SQL: SELECT DISTINCT `glpi_plugin_formcreator_issues`.`id` AS id, 'csc.dashfiscal' AS currentuser,
>                         `glpi_plugin_formcreator_issues`.`sub_itemtype`, `glpi_plugin_formcreator_issues`.`entities_id`, `glpi_plugin_formcreator_issues`.`is_recursive`,  GROUP_CONCAT(DISTINCT CONCAT(`glpi_plugin_formcreator_issues`.`name`, '$#$' ,
>                                                         `glpi_plugin_formcreator_issues`.`id`) ORDER BY `glpi_plugin_formcreator_issues`.`id`
>                                         SEPARATOR '$$##$$') AS `ITEM_PluginFormcreatorIssue_1`,    
>                             IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_formcreator_issues`.`display_id`,
>                                                                          '__NULL__'),
>                                                    '$#$', `glpi_plugin_formcreator_issues`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$')
>                                     AS `ITEM_PluginFormcreatorIssue_1_display_id`, `glpi_plugin_formcreator_issues`.`display_id` AS `ITEM_PluginFormcreatorIssue_2`,  `glpi_plugin_formcreator_issues`.`status` AS `ITEM_PluginFormcreatorIssue_4`,  `glpi_plugin_formcreator_issues`.`date_creation` AS `ITEM_PluginFormcreatorIssue_5`,  `glpi_plugin_formcreator_issues`.`date_mod` AS `ITEM_PluginFormcreatorIssue_6`,  `glpi_entities`.`completename` AS `ITEM_PluginFormcreatorIssue_7`,   `glpi_users_requester_id`.`name` AS `ITEM_PluginFormcreatorIssue_8`,
>                         `glpi_users_requester_id`.`realname` AS `ITEM_PluginFormcreatorIssue_8_realname`,
>                         `glpi_users_requester_id`.`id`  AS `ITEM_PluginFormcreatorIssue_8_id`,
>                         `glpi_users_requester_id`.`firstname` AS `ITEM_PluginFormcreatorIssue_8_firstname` FROM `glpi_plugin_formcreator_issues` LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id`
>                                                  AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id`
>                                                  AND `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id`
>                                                  AND `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id`
>                                                  AND `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id`
>                                                  AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`tickets_id`
>                                                  AND `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`type` = 2 ) LEFT JOIN `glpi_ticketvalidations` 
>                                              ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_ticketvalidations`.`tickets_id`
>                                                  )LEFT JOIN `glpi_entities` 
>                                           ON (`glpi_plugin_formcreator_issues`.`entities_id` = `glpi_entities`.`id`
>                                               )LEFT JOIN `glpi_users`  AS `glpi_users_requester_id`
>                                           ON (`glpi_plugin_formcreator_issues`.`requester_id` = `glpi_users_requester_id`.`id`
>                                               ) WHERE (( `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.users_id = '319'
>                                     OR `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.users_id = '319'
>                                     OR `glpi_plugin_formcreator_issues`.`requester_id` = '319' OR `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`.`groups_id`
>                                              IN (1) OR `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`groups_id`
>                                              IN (1) OR `glpi_ticketvalidations`.`users_id_validate`
>                                           = '319')  OR `glpi_plugin_formcreator_issues`.`validator_id` = '319') AND  ( `glpi_plugin_formcreator_issues`.`entities_id` IN ('309', '316')  OR (`glpi_plugin_formcreator_issues`.`is_recursive`='1' AND `glpi_plugin_formcreator_issues`.`entities_id` IN ('0','90','300')) )  AND (   `glpi_plugin_formcreator_issues`.`status` IN ('2','3')  AND  (`glpi_users`.`id` = '319')  ) GROUP BY `glpi_plugin_formcreator_issues`.`id` ORDER BY ITEM_PluginFormcreatorIssue_1 ASC 
>   Error: Unknown column 'glpi_users.id' in 'where clause'
>   Backtrace :
>   inc/search.class.php:1246                          
>   inc/search.class.php:314                           Search::constructData()
>   plugins/formcreator/inc/issue.class.php:675        Search::getDatas()
>   plugins/formcreator/inc/wizard.class.php:241       PluginFormcreatorIssue::getTicketSummary()
>   plugins/formcreator/inc/wizard.class.php:84        PluginFormcreatorWizard::showTicketSummary()
>   plugins/formcreator/front/wizard.php:45            PluginFormcreatorWizard::header()
>   {"user":"some_id@some_ip_from_some_website"} 

in php-errors.log:
> [2020-02-12 07:50:16] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 658
>   *** PHP Notice(8): Undefined index: totalcount
>   Backtrace :
>   plugins/formcreator/inc/issue.class.php:676        
>   plugins/formcreator/inc/wizard.class.php:241       PluginFormcreatorIssue::getTicketSummary()
>   plugins/formcreator/inc/wizard.class.php:84        PluginFormcreatorWizard::showTicketSummary()
>   plugins/formcreator/front/wizard.php:45            PluginFormcreatorWizard::header()
>   {"user":"some_id@some_ip_from_some_website","mem_usage":"0.001\", 3.38Mio)"} 

idk what to do... can you help me ?

**Comment by btry** [comment]
Hi,

Stay tuned, until I analyses these logs

**Comment by Dayflare** [comment]
i have a similar issue. It doesn't count tickets to be validated. There is a ticket for validation but the user sees a count of 0 tickets to be validated.
![image](https://user-images.githubusercontent.com/42730126/74842358-90b90d80-532a-11ea-8411-8d161cf4a9ec.png)

then if i change the search filter to "not solved" or "processing" it shows the ticket, but the count stays at 0. 
![image](https://user-images.githubusercontent.com/42730126/74842492-cbbb4100-532a-11ea-8d7e-94bf672e943b.png)

a solution for this: the default search filter should be set to "not solved" and then count the values.

SQL Error:
```
[2020-02-19 14:32:02] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS `cpt` FROM (SELECT DISTINCT
                  NULL                           AS `id`,
                  `f`.`name`                     AS `name`,
                  CONCAT('f_',`fanswer`.`id`)    AS `display_id`,
                  `fanswer`.`id`                 AS `original_id`,
                  'PluginFormcreatorFormAnswer'  AS `sub_itemtype`,
                  `fanswer`.`status`             AS `status`,
                  `fanswer`.`request_date`       AS `date_creation`,
                  `fanswer`.`request_date`       AS `date_mod`,
                  `fanswer`.`entities_id`        AS `entities_id`,
                  `fanswer`.`is_recursive`       AS `is_recursive`,
                  `fanswer`.`requester_id`       AS `requester_id`,
                  `fanswer`.`users_id_validator` AS `validator_id`,
                  `fanswer`.`comment`            AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  `tic`.`name`                  AS `name`,
                  CONCAT('t_',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  'Ticket'                      AS `sub_itemtype`,
                  `tic`.`status`                AS `status`,
                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tic`.`users_id_recipient`    AS `requester_id`,
                  0                             AS `validator_id`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
  Error: Illegal mix of collations for operation 'UNION'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:122        
  inc/crontask.class.php:829                         PluginFormcreatorIssue::cronSyncIssues()
  front/cron.php:83                                  CronTask::launch()
  {"user":"1103@glpi"} 
```

**Comment by btry** [comment]
Hi @Dayflare 

you problem is probably related to the structure of the tables involved in the query. I'm not sure, but a similar issue occured mayve 1 or 2 years ago. You should search for it. 

Check that the collation of all tables is correct by comparing  them with tne empty.sql file of the plugin. You may also want to check the tables of GLPI core as well.

**Comment by btry** [comment]
Hi 
@gabrielpetrone I tried with the release 2.9.1 and  the latest revision of 2.9.X and I don't reproduce.

Near the end of your request I read AND  (`glpi_users`.`id` = '319') . In my instance I see the following: glpi_users_requester_id`.`id` = '2'). Is your plugin the tagged version 2.9.1 and without any change ?

**Comment by Dayflare** [comment]
my error persists with version 2.9.2
the ticket validation only shows 0

**Comment by btry** [comment]
Hi

I think this issue is obsolete, then I close.

Users of GLPI  9.4.5  shall check if they have the following fix : https://github.com/glpi-project/glpi/pull/6365

Others shall open a new issue if the problem persists with 2.10.1
