### ISSUE TITLE
Official documentation

### ISSUE THREAD

**Issue by scorpio94260** [pluginsGLPI/formcreator#168]
Bonjour, 
Je ne trouve aucun lien pour avoir un bon tutoriel pour mettre en place ce plugin.
Merci d'assister
Scorpio

**Comment by neeftarah** [comment]
Bonjour,

J'ai initier un [Wiki](https://github.com/pluginsGLPI/formcreator/wiki) pour formcreator.
Je n'ai cependant que peu de temps a y consacré.

Chacun est libre d'y participer et toute aide est la bienvenue.

Cordialement,
Jérémy

**Comment by flegastelois** [comment]
Nous avons planifié la mise à jour de la documentation officielle du plugin Formcreator.

Elle sortira avec une des prochaines versions majeures 1.4.X ou 1.5.X.

**Comment by btry** [comment]
Documentation done : 

http://glpi-plugins.readthedocs.io/fr/latest/formcreator/index.html
