### ISSUE TITLE
Change questions order : unable to go down a question

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1683]
**Describe the bug**
When composing a Form, we can't go down a question, up is ok.

**To Reproduce**
Add 2 questions in a form, in the same section. The type does not matter.
Try to go up the second : no way
Try to go down the first : ok.

**Expected behavior**
Questions should go up and down.

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/74526988-ebb2c500-4f24-11ea-9942-6dee8991ce5f.png)

**workaround**
up all the questions to let this one go down...

**Comment by btry** [comment]
Hi 

there is a fix in the branch support : 3a191ebd417623e98d05d608f48e39cd54815f75

**Comment by mab18** [comment]
Excellent !
It corrects.
Thanks

**Comment by btry** [comment]
thank you for your feedback

**Comment by mab18** [comment]
I note a little esthetic thing : 
![image](https://user-images.githubusercontent.com/55535560/74540364-efa01080-4f3f-11ea-87df-e4da88b2315f.png)
It's not really a problem but is not linear. 
;-)

**Comment by mab18** [comment]
@btry sorry, refresh wasn't done, I didn't saw that the ticket was closed.
