### ISSUE TITLE
Problem on the redaction field

### ISSUE THREAD

**Issue by CIVIER-C** [pluginsGLPI/formcreator#1686]
**Describe the bug**
When the requestor field is filled in from the answer to a question, the name of the editor is not the one who entered the form but that of the requester

**To Reproduce**
Demandeur  
Utilisateur Personne depuis la question "Agent concerné par la demande : " 
When the ticket is created the writer field = requester field

**Expected behavior**
writer field = name of the person who entered the form

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version GLPI 9.4.5 formcreator 2.9.1
![1 formulaire](https://user-images.githubusercontent.com/39520590/74668432-7bff3d00-51a5-11ea-9f70-5e8f672633db.jpg)
![2 cible](https://user-images.githubusercontent.com/39520590/74668435-7c97d380-51a5-11ea-9f3b-bdc602157914.jpg)
![3 ticket](https://user-images.githubusercontent.com/39520590/74668437-7d306a00-51a5-11ea-98fe-2eda1bbb7426.jpg)

**Additional context**

**Comment by btry** [comment]
Hi

Please  try this patch and feedback

https://github.com/pluginsGLPI/formcreator/pull/1529/

**Comment by btry** [comment]
Hi

This bug should be fixed now in versions 2.9.2 (not released yet) and later.
