### ISSUE TITLE
Problème enquête de satisfaction

### ISSUE THREAD

**Issue by Izanagi52** [pluginsGLPI/formcreator#1687]
Bonjour,
Je suis en version 2.9.1 du plugin, et 9.4.4 de GLPI.

Lorsqu'un utilisateur qui utilise le catalogue de service simplifié reçoit clic sur un lien pour répondre a une enquête de satisfaction, ça lui ouvre la page du ticket sans aucun accès a l'enquête.
Est-ce que c'est un fonctionnement normal ?

Et si l'utilisateur utilise le catalogue de service étendue, et qu'il clic sur le lien de l'enquête, il n'arrive pas directement sur l'onglet "Satisfaction".

**Comment by btry** [comment]
Bonjour

Efectivement ce cas d'utilsiation n'a pas été considéré. Il se trouve que j'ai une solution assez simple à mettre en oeuvre. Pouvez vous tester le patch et me faire un retour ?

**Comment by Izanagi52** [comment]
J'ai tester les deux modification du patch, et les deux on l'air de fonctionner parfaitement !
L'enquête apparait bien en catalogue simplifié, et l'onglet et bien forcé en étendu. Merci !
Ça répond parfaitement à ce que je voulais !

PS : Juste un petit détail, moi ça ne me dérange pas dans mon cas, mais avec le catalogue simplifié, on voit quand même l'enquête et on peux y répondre, même après qu'elle soit expirée.

**Comment by btry** [comment]
J'ai mis à jour la PR pour gérer l'expiration de l'enquete de satisfaction. Si vous pouvez valider que ça fonctinne pour vous, je pense que la PR sera prête.

**Comment by Izanagi52** [comment]
Ça fonctionne très bien !
J'ai juste changé "Satisfaction survey expired" par l'équivalent français !
Merci !

**Comment by btry** [comment]
Normalement le message devrait être automatiquement traduit en français, via la localisation de GLPI. Si ce n'est pas le cas, ce n'est pas normal. 

Jee fusionne le patch. Merci pour votre retour.

**Comment by Izanagi52** [comment]
Ah oui c'est vrai, j'avais même pas vérifier...
Du coup j'ai rien dit ! C'est parfait !
