### ISSUE TITLE
Ticket destination non formaté

### ISSUE THREAD

**Issue by Gilmor49** [pluginsGLPI/formcreator#169]
Bonjour,

suite à la dernière mise à jour, le commentaire du ticket de destination n'est plus formaté.

Plus de section, tout est dans le même bloc.

Cdt, Gilles

Données du formulaireIdentification du demandeur 1) Le demandeur est l'usager : Non 2) Nom de l'usager : Cailleau GerardDétail de la demande. 3) Type : Poste 4) Choix PC : Fixe 5) Affectation : Remplacement 6) Matériel remplacé : vieux portable FRLONDFAB021Informations supplémentaires et justification du besoin 7) Lieu d'installation : Atelier Montage 1 Bureau chef 8) Date d'installation souhaitée : 2015-12-23 9) Informations supplémentaires et justification du besoin :
Test
10) Demande liée à un projet : Oui 11) Projet : Projet KlineValidation / Signature 12) Validation / Signature : Acceptation des conditions d'utilisation.

**Comment by neeftarah** [comment]
Bonjour,

Merci d'avoir remonté ce problème.
Il semblerais effectivement que GLPI 0.91 retire l'ensemble des balises HTML lors de la création d'un ticket si ce code HTML n'est pas encodé.

Cordialement,
Jérémy

**Comment by Gilmor49** [comment]
Bonjour,

Merci de votre réponse.

 

Je suis en version 0.90.1

A priori le phénomène est apparu après la dernière màj de pluggin.

 

Cdt, Gilles

 

De : Jérémy MOREAU [mailto:notifications@github.com] 
Envoyé : jeudi 17 décembre 2015 13:07
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : Gilmor49 <gilles.moreau90@sfr.fr>
Objet : Re: [formcreator] Ticket destination non formaté (#169)

 

Bonjour,

Merci d'avoir remonté ce problème.
Il semblerais effectivement que GLPI 0.91 retire l'ensemble des balises HTML lors de la création d'un ticket si ce code HTML n'est pas encodé.

Cordialement,
Jérémy
