### ISSUE TITLE
php vendor/bin/robo build:fa-data` issue

### ISSUE THREAD

**Issue by phillf** [pluginsGLPI/formcreator#1691]
**Describe the bug**
Error occurs when executing ```php vendor/bin/robo build:fa-data``` results in the following PHP error:

`PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/vhosts/servicedesk.twhcompanies.com/public_html/plugins/formcreator/vendor/consolidation/robo/src/Collection/loadTasks.php on line 15`

**To Reproduce**
Clone the plugin in the GLPI folder and execute the commands as indicated in the README.md.

**Comment by btry** [comment]
Hi,

Which branch ?

**Comment by phillf** [comment]
Support/2.9.0 and I even tried tags for v2.9.0 and v2.9.1.

**Comment by btry** [comment]
The error seems located in a 3rd party library. As there is few probability that a syntax error appears in the Robo.li project, I would suggest you delete the vendor directory, then recreate it with **composer install**, and try again

**Comment by phillf** [comment]
@btry, sadly it's the same result.

**Comment by btry** [comment]
Compare the file against the copy on github https://github.com/consolidation/Robo/blob/master/src/Collection/loadTasks.php

Also tell your php version

**Comment by phillf** [comment]
This getting more interesting. Different library generates an error when running cron.php.

```PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/vhosts/servicedesk.twhcompanies.com/public_html/vendor/zendframework/zend-cache/autoload/patternPluginManagerPolyfill.php on line 12```

Version is GLPI 9.4.5 with FusionInventory 9.4+2.4 on PHP 7.3.

**Comment by btry** [comment]
I believe there is a problem both the version of PHP, but 7.3 should not produce such error. Check the version in GLPI's settings. Maybe you checked the version from CLI and have an other version enabled in your http server

**Comment by phillf** [comment]
Operating system: Linux 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
PHP 7.3.14 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube
	Loader, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix,
	pspell, redis, session, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, xsl, zip, zlib)

**Comment by phillf** [comment]
What should I do?

**Comment by btry** [comment]
Hi

I just tried to run Robo build:fa-data :
- deleted my vendor directory
- ran composer install
- ran vendor/bin/robo build:fa-data

It is OK for me, but I have php 7.2 on my computer. Note also that my version of PHP is lower than yours, then it should be OK with PHP 7.3. If I can, I'll try with the same version (I'm busy with others tasks right now).

Then there is no syntax error on the 3rd party libraries. The parse error is similar in your GLPI and Robo, then there is probably something wrong in your PHP installation. I think this is not a bug in GLPI or Formcreator. You may check in the GLPI forum if someone had a similar issue and found a solution.

**Comment by btry** [comment]
Hi

Having no feedback, I guess your problem is solved.
