### ISSUE TITLE
[2.9.1 + GLPI 9.4.5] Problem if validator

### ISSUE THREAD

**Issue by benshoes** [pluginsGLPI/formcreator#1692]
Hello,
If the "validation required" is configured, the ticket creation is not done.
![image](https://user-images.githubusercontent.com/53210764/75235802-1cb0b680-57bd-11ea-8739-cf9e3a4fd6fd.png)

**Comment by btry** [comment]
Hi

This is the expeted behavior. a user must forst validate the answers to the form. Once done, the plugin will generate the targets.

**Comment by benshoes** [comment]
OK thx, i understoud now ;-)
I close this bad issue
