### ISSUE TITLE
Show form title and first answer

### ISSUE THREAD

**Issue by MigueFM93** [pluginsGLPI/formcreator#1693]
Hello,

I want to make a change customized for my company. When showing the answered forms, we see how information about it is displayed. My intention is that instead of showing the name of the form, the first answer of the form is also shown (i.e. a field whose answer is the name of the person we want to unsubscribe).  I'd like it to look like this: "Solicitud Alta - Pepe Perez".

![Captura33](https://user-images.githubusercontent.com/19668117/75268368-b301ce00-57f7-11ea-9af6-a87192c441af.JPG)

"Pepe Perez" is the answer to the question called "Last Name" on the form.

Is there any way to concatenate this in the code? Could you help me, any ideas?

Thank you so much.

PD:
The code that shows this information from the resulting forms is the following within GLPI:

![Captura44](https://user-images.githubusercontent.com/19668117/75268389-b8f7af00-57f7-11ea-8ece-a242f6581593.JPG)

**Comment by btry** [comment]
Hi 

The plugin currently does not support this feature.

To properly implement this, I think the object PluginFormcreatorForm needs a new field (with a new column in its table) to save the template of the form answer title. This template may be retrieved in PluginFormcreatorFormAnswer::prepareInputForAdd(), analyzed with the method PluginFormcreatorFormAnswer::parseTags(). However this methods calls PluginFormcreatorTargetBase::addAttachedDocument() which will cause a bug. There is a need to move this call out of the method.

Note : The analysis is based on the branch develop. If you want to implement this, please fork the project and create a branch based on develop, and submit your PR. Contributing is the best option to not need to maintain yourself a patch on the middle / long term.

**Comment by MigueFM93** [comment]
Thank you very much for your answer. If I can go ahead with the development I will create a new branch, as you say.

Regards
