### ISSUE TITLE
Quotation marks parsing in source code editor

### ISSUE THREAD

**Issue by djehutyy** [pluginsGLPI/formcreator#1696]
**Describe the bug**
In the "edit a question" section within Forms editor, using the source code, the quotation marks are changed with `&quot;` after saving and reopen.

**To Reproduce**
1. Go to 'Forms'
2. Click on 'questions'
3. Add a textarea question
4. In source code add `<input type="checkbox" />`
5. After saving  and reopen the form (in source code), it changes  in `<input type="\&quot;checkbox\&quot;" />`

**Expected behavior**
It should stay `<input type="checkbox" />`

![source_editor](https://user-images.githubusercontent.com/45942012/75899540-f41f6100-5e3b-11ea-914c-38b51954cf1a.PNG)
![after_save](https://user-images.githubusercontent.com/45942012/75899538-f386ca80-5e3b-11ea-9737-5c319995d24a.PNG)

Operating system: Linux itk-svil-glpi 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64
PHP 7.3.15 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/7.3.15 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.1.44-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

formcreator          Name: Form Creator                   Version: 2.9.1

**Comment by btry** [comment]
Hi

I'm not sure I will care this issue : you're not supposed to create HTML inputs in a textarea.

I guess you want to create a checklist for a task, and the user who completes the list should report his progress by checking the boxes ?

**Comment by djehutyy** [comment]
My need is to use more options in a question. So add more Type*'s  in the text area:
Example:
Checkboxes `<input type="checkbox" />`
 Date `<input type="date" id="birthday" name="birthday">`
 etc..

![after_save](https://user-images.githubusercontent.com/45942012/75902365-2fbc2a00-5e40-11ea-80a0-4ca1e5362b55.PNG)
![before_save](https://user-images.githubusercontent.com/45942012/75902373-32b71a80-5e40-11ea-9910-426b5aa4a880.PNG)

**Comment by btry** [comment]
Well... this use case is completely unsupported. I'm even not sure that GLPI sanitization will allow HTML inputs when creating the targets (if any).

textarea question is for rich text only. Wht is the problem with the checkboxes and date question types ? How they don't fit your need ?

**Comment by djehutyy** [comment]
First of all, thanks for the fast replays :)

- So, i'll try to explain better. In the form i put a lot of questions. The first is the one with more different informations (informations in different forms but basically inherent only about the first one).

- I prefer add mixed forms in the question to avoid confusion.

![questions](https://user-images.githubusercontent.com/45942012/75904380-6778a100-5e43-11ea-923b-2eaed56185db.PNG)

**Comment by btry** [comment]
Hi

You cannot use conditions on questions to hide some of them depending on the answer filled in others ? It does not fill your need ?

>  In the form i put a lot of questions. The first is the one with more different informations (informations in different forms but basically inherent only about the first one).

I don't understand this : one question should contain one information because the inputs from the requester are used to build a target (ticket or change).

> I prefer add mixed forms in the question to avoid confusion.

Sections are made for that. An example : a section for question about a user, then a section about his type of request, then a section about attachments

**Comment by btry** [comment]
Hi

Having no feedback about this I close. Feel free to request for reopen if you want to resume.
