### ISSUE TITLE
Error displaying completed forms

### ISSUE THREAD

**Issue by jopehi** [pluginsGLPI/formcreator#1697]
Hello everyone.

I have installed glpi version 9.4.5 and the FormCreator version 2.9.0 plugin, and when I go to see the answers of the forms that have been filled in, it presents me with an error and cannot visualize the content of the completed form.

I have activated debug mode, and it shows me the following message:

PHP Catchable Fatal Error: Argument 1 passed to PluginFormcreatorFields :: isVisible () must implement interface PluginFormcreatorConditionnableInterface, instance of PluginFormcreatorTextField given, called in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php on 587.php and defined in /var/www/html/glpi/plugins/formcreator/inc/fields.class.php at line 113

Fatal error: Call to undefined method PluginFormcreatorTextField :: getID () in /var/www/html/glpi/plugins/formcreator/inc/fields.class.php on line 123

What I can do? Or how can I solve this error?

Thank you

Joseph

**Comment by btry** [comment]
Hi

How dod you install this version of the plugin ? It is strange that PluginFormcreatorTextField does not inherits from  PluginFormcreatorConditionnableInterface

**Comment by jopehi** [comment]
Hi,
I have reviewed the issues, and found this fix: #5453a92, I have applied it and it worked correctly.

Thank you
