### ISSUE TITLE
[9.2.1] Url does not open in the corresponding tab

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#1699]
**The bug**
When in Service catalog extended mode, the URL does not open on the corresponding tab

**Screenshots**
For this url: https://glpihomologa.jfce.jus.br/index.php?redirect=ticket_2020030013_Ticket$3

1. Helpdesk mode: GLPI's helpdesk
![Screenshot](https://user-images.githubusercontent.com/26510405/76160486-59f43d00-6109-11ea-9890-e1e4a4022b1f.png)

2. Helpdesk mode: Service catalog extended
![Screenshot (1)](https://user-images.githubusercontent.com/26510405/76160485-58c31000-6109-11ea-8812-7d94d9efe8ae.png)

**Server**
- Formcreator 2.9.1
- GLPI 9.4.5

**Desktop**
 - Linux
 - Chrome 79.0

**Comment by btry** [comment]
Hi

Try this fix and feedback: #1701

**Comment by pedroluisvsousa** [comment]
It worked!
Thank's.

**Comment by btry** [comment]
Thann you for your feedback. It is already merged and ready for 2.9.2
