### ISSUE TITLE
Adding inventory number in the GLPI object

### ISSUE THREAD

**Issue by Ruiseart** [pluginsGLPI/formcreator#170]
GLPI object in a question shows only the name of the computer, monitor, printer or device. Could you also add inventory number?

**Comment by sidneim** [comment]
Hi,

I have this difficulty at the time too, just can filter the name of the machines. It would be a very nice improvement and apparently is "simple".

**Comment by nqb** [comment]
+1 for this feature. It will be great to add inventory number and serial number (same behavior for ticket creation).

**Comment by nqb** [comment]
For information, if you let mouse on the name, you can see content of "Comments" field. In this fact, adding serial number and inventory number could be easy.

**Comment by btry** [comment]
Hi

Serial and inventory number are now available in the drpodown.
