### ISSUE TITLE
In the simplified view, the ticket title is displayed instead of the number

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1700]
Hello people

In one environment, I have GLPI in version 9.3.4 and formcreator in 2.8.6. In the simplified view, the ticket title is displayed instead of the number in column "ID".

Can someone help me?
![duvida](https://user-images.githubusercontent.com/35368369/76253856-2fe66c00-622a-11ea-9891-bb67ddf1f180.png)

**Comment by btry** [comment]
Hi 

This bug should be fixed in version 2.9.x. Please check on a testing environment that the version 2.9.1 or the branch support/2.9.0 fixes it. 

i'm waiting for your feedback.

**Comment by phamorais** [comment]
@btry 


I am starting a test environment today. I will test and give you feedback

**Comment by phamorais** [comment]
@btry Hi!


Upgrade to version 9.4.5 and Formcreator to version 2.9.1 as attached images.


![imagem 1](https://user-images.githubusercontent.com/35368369/76895066-0ce13b00-686e-11ea-9463-e105df950072.png)

Plugin Version

![image](https://user-images.githubusercontent.com/35368369/76895277-7103ff00-686e-11ea-8500-e245ffb94f8a.png)

**I realized that the error only happens for the Simplified Interface**

**Comment by btry** [comment]
The problem should be related to the table glpi_plugin_formcreator_issues. 

Check the table in the DB and  adjust the order of the columns to match the following (picked from the SQL script to initialize a fresh DB for the plugin).

```sql
CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_issues` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `display_id` varchar(255) NOT NULL,
  `original_id` int(11) NOT NULL DEFAULT '0',
  `sub_itemtype` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(255) NOT NULL DEFAULT '',
  `date_creation` datetime NOT NULL,
  `date_mod` datetime NOT NULL,
  `entities_id` int(11) NOT NULL DEFAULT '0',
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
   `requester_id` int(11) NOT NULL DEFAULT '0',
  `validator_id` int(11) NOT NULL DEFAULT '0',
  `comment` longtext,
  PRIMARY KEY (`id`),
  INDEX `original_id_sub_itemtype` (`original_id`, `sub_itemtype`),
  INDEX `entities_id` (`entities_id`),
  INDEX `requester_id` (`requester_id`),
  INDEX `validator_id` (`validator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by phamorais** [comment]
@btry 


Hello

The order of my columns is like this. It's wrong?

![image](https://user-images.githubusercontent.com/35368369/78780874-b0a59e80-7975-11ea-9e1f-e59108620bd4.png)

**Comment by phamorais** [comment]
@btry 


I found that in my Production environment, for some tickets the information is inserted incorrectly by the plugin. In this case it was expected to have ticket_id

![image](https://user-images.githubusercontent.com/35368369/78781513-c6679380-7976-11ea-885b-f450ea94652a.png)

In homologation the error does not happen (yet). Can you tell me how I correct? These prints used another environment (Formcreator 2.8.5). But in the previous post, I was using v2.9.1 and the error persists. This means that just updating the plugin will not solve the problem.

Columns in the approval environment

![image](https://user-images.githubusercontent.com/35368369/78781823-50176100-7977-11ea-9e0b-365fab817c79.png)

**Comment by phamorais** [comment]
@btry 

Running "desc" in the table that there were errors, the parameters are correct according to the script

![image](https://user-images.githubusercontent.com/35368369/78897987-6d1c6480-7a49-11ea-8f14-a5daaee3495b.png)

**Comment by btry** [comment]
Hi

Move the column "name" after the column "id".

It will do the trick for the rows created after this fix.

**Comment by phamorais** [comment]
@btry 

Understand.

I have 2 environments with the same behavior, but one is with version 2.8.5 and the other with 2.9.1.

If I move the column, will it only work for the newer version? Or will it work for both environments?

**Comment by btry** [comment]
It should work for both. Check the PR I did this week in the PR list. This is an upgrade fix. You will find easily from which version the bug occurs. Double check with the big SQL (containing union keyword) request in issue.class.php

The issue comes from a change in this request, sensitive to the order of the columns.

**Comment by phamorais** [comment]
@btry 

OK understood.

in this case I can apply regardless of the itilized version, or wait for the next plugin relaease with your PR right?

**Comment by btry** [comment]
The patch will apply for those who will upgrade from a version prior to 2.6.0 to the release containing it.

For other cases including you, people need to reorder the columns of the table by hands

**Comment by phamorais** [comment]
@btry Hi!


First of all I would like to thank you for your support. All the times I needed you were cordial and thoughtful, and not everyone here at git works that way, so thank you very much.

I did it as requested by you and really corrected it, for the new tickets.

However, for the ancients is there any way to readjust? Because in the tickets that have the information in the incorrect columns, I cannot know the correct ticket ID number.


Example of incorrect tickets but without the ticket Id information. So how do I apply the fix to the old ones?

![image](https://user-images.githubusercontent.com/35368369/79249759-1d2c0c00-7e54-11ea-9f46-d32a51ad073d.png)

**Comment by btry** [comment]
Hi 

Thank you for your comment, I'm glad getting such feedback.

I dont have any known solution, but I think this possible to build a tiny PHP script or maybe a SQL query.

The bug began when you began to use an impacted version of the plugin, and stopped to occur when you applied the patch. Then you have a range of IDs  to fix in the table glpi_plugin_form creator_issues. Assuming that it is possible to run a SQL query which moves the column's contents in the good one, with a where statement to limit the rows to the impacted range.

**Comment by phamorais** [comment]
@btry 

They are already finalizing the script to correct the old tickets. However, all that is missing is information that is wrong in the bank and I do not understand where the data came from. In the screen below there is the column "Status". What is this information?
È approval of the ticket before opening?

I say this because in my base that is defective, there are some records with the number "6". And I would like to know where it came from.


![image](https://user-images.githubusercontent.com/35368369/79378090-1b854580-7f33-11ea-82ef-ab64c700b0df.png)

**Comment by phamorais** [comment]
@btry 
This issue can be closed
