### ISSUE TITLE
Show/Hide criteria includes Status 

### ISSUE THREAD

**Issue by GeneralVini** [pluginsGLPI/formcreator#1706]
The possibility of control of sections besides category, title, description and file are welcome.

I want to place a satisfaction section after the ticket´s solution, in other words, status=solucinated

**Comment by btry** [comment]
Hi

A form is not modifiable after it was accepted (automatically or after validation.

Then I don't see how you could create your own satisfaction survey.

You may try the latest revision of support/2.9.0: it contains fixes to properly handle ticket survey from email and service catalog.

**Comment by GeneralVini** [comment]
Thanks a lot! It's worked like a charm!

**Comment by GeneralVini** [comment]
Does this issue will be available in the next versions?

**Comment by btry** [comment]
Hi

Yes, it will be included in the version 2.9.2 and later. Do not use the branch support/2.9.0 in production. You may instead pick the patch and apply it on the release 2.9.0 or 2.9.1

https://github.com/pluginsGLPI/formcreator/pull/1701

**Comment by btry** [comment]
Hi the fix is in the release 2.9.2. Closing.
