### ISSUE TITLE
Bug d'envoie de pièce jointe en Self-service

### ISSUE THREAD

**Issue by Clecle87** [pluginsGLPI/formcreator#1709]
**Describe the bug**
Bonjour, 
Nous mettons en place GLPI dans notre entreprise et nous souhaitons utiliser FormCreator pour les utilisateurs parce que l’interface est facile de compréhension.

Cependant, durant mes tests, j'ai pu remarquer que les utilisateurs (donc en Profil Self-Service), ne peuvent pas ajouter des pièces jointes dans les "Zone de texte". On peut les séléctionner mais rien ne se passe lors de l'envoie. Le corps du message se transforme bien en ticket mais la pièce jointe se perd.

Avez-vous une solution au problème ?

J'ai essayé d'ajouter "Editer le suivi" au profil Self-service pour que celui-ci ajoute les pièce jointes directement sur le ticket mais il y a une restriction de droit de ce côté aussi.

J'utilise GLPI 9.4.5 et FormCreator 2.9.1

**Comment by btry** [comment]
Bonjour

Un correctif est en cours pour résoudre les soucis avec les envois de documents dans les zones de texte et les questions de type fichier.  Veuillez patienter jusqu'à la version 2.9.2 du plugin.

**Comment by btry** [comment]
Bonjour

La version 2.9.2 corrige une partie des problèmes liés à l'upload et les zones de texte. Les soucis persistants devraient ẑetre résolus dans GLPI 9.5 grâce à un patch qui a été versé dans cette branche.
