### ISSUE TITLE
Problème d'affichage lors de l'ajout d'une destination en mode séparation verticale

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#171]
La séparation verticale est activée.
Version de GLPI : 0.90.1
Version du Plugin : 0.90-1.3.3

Lors de l'ajout d'une destination à un formulaire, le bas de page (en dessous "attribuer à") n'est pas visible, et aucun "ascenseur" n'est disponible pour y accéder, ce qui a pour effet de ne pas pouvoir valider l'utilisateur à ajouter.

Pour contourner le problème, je passe le zoom de la page à 70 %, je peux ensuite voir le bouton "ajouter" ainsi qu'une partie des balises disponible. Quand il y'a de nombreuses sections / questions dans le formulaire, la visibilité des dernières balises est impossible, il faut dézoomer à 10 %.

Le zoom par défaut du navigateur est configuré à 100%.

Problème constaté avec les navigateurs suivants : 
-> Google Chrome 41.0.2272.87 m
-> Microsoft Edge
-> Internet Explorer 11.0.10240.16603

**Comment by neeftarah** [comment]
Bonjour,

Le problème ne vient pas d'un navigateur précis mais d'une implémentation mal réfléchie de séparation verticale de GLPI. Et nous avons du passer à coté.

Je vais voir ce que je peut faire pour corrigé le problème sur Formcreator.

NB : Le problème est normalement déjà corrigé sur GLPI 0.91 (branche de développement)

**Comment by SylvainGuibert** [comment]
Merci pour cette réponse claire, et précise. En attente de la mise à jour. :+1:
