### ISSUE TITLE
Answers to json in text

### ISSUE THREAD

**Issue by itmicus** [pluginsGLPI/formcreator#1715]
**Is your feature request related to a problem? Please describe.**
I The responses from the form serve as input for automation, such as providing access. It is convenient to work with answers in JSON format

**Describe the solution you'd like**
Formcreate save answers to text ticket in JSON format

**Comment by btry** [comment]
Hi

Do you want to have tickets containing JSON ?

**Comment by itmicus** [comment]
> Hi
> 
> Do you want to have tickets containing JSON ?

yes

**Comment by btry** [comment]
Hi

I think this is a bad idea. Ticket's content targets humans. It is better to make your tool an API consumer (rest or xmlrpc).

**Comment by itmicus** [comment]
> Hi
> 
> I think this is a bad idea. Ticket's content targets humans. It is better to make your tool an API consumer (rest or xmlrpc).

People using formcreator to make request with usefull form, but next, the form is processed through the API by script

**Comment by btry** [comment]
If you already use the API, you should improve your tool to read data from the PluginFormcreatorAnswer itemtype. From the ticket item you can find the PluginFormcreatorFormAnswer : there is a relation in the DB. Next you can read all PluginFormcreatorAnswer items related to the form answer.

The plugin is not officially compatible with the API, but I'm improving it over time.

**Comment by btry** [comment]
having no feedvack, and the need being solvable via the API, I close.
