### ISSUE TITLE
Validation dropdown (when using entities)

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/formcreator#1717]
**Describe the bug**

Hi there, 
We are using different entities in GLPI to separate our staff and groups. 
My admin user is the only one in the root entiry, all other users are under sub-entities. 
When creating a form (inside a sub-entity) and activation the validation, the form only list my user for validation and no groups.

It looks like the form-creator dropdown only search for user who has a profile inside the root entity or maybe it's something related to profile rights?

**To Reproduce**
- Create different sub-entities in glpi
- Assign users and group to sub-entities
- Assign one profile to the root entity
- Create a new form (from inside a sub-entity)
- Activate form-validation
- Select "Users" : Only the user inside the root entity is listed
- Select "Groups" : No group is listed

**Expected behavior**
- Should list all the users (inside this entity) in the dropdown so I can choose a user to validate the form
- Should list all the groups containing users (inside this entity) so I can select a group to validate this form

**Screenshots**
![form-creator-validation-001](https://user-images.githubusercontent.com/38400135/77935062-f203c300-727e-11ea-91d1-29d581a8ad3a.png)
![form-creator-validation-002](https://user-images.githubusercontent.com/38400135/77935067-f4661d00-727e-11ea-8db4-83fbba8ffffd.png)
![form-creator-validation-003](https://user-images.githubusercontent.com/38400135/77935072-f62fe080-727e-11ea-94ea-f0ade0b6d2d3.png)

**Desktop (please complete the following information):**
 - Windows 10 x64 1903
 - Google Chrome 80.0.3987.149
- FormCreator version 2.10.0-beta.1
- GLPI Version 9.4.5

Notes : This behavior vas happening on formCreator version 2.9.1 too, so I've upgraded to 2.10.0-beta.1 this morning to see it it was fixed but still does the same

Thanks
Francois

**Comment by sidgaabriel** [comment]
I'm having the same issue here but I was wondering if its possible to user choose a validator in a dropdown list, I saw this feature on previous versions but its not enable on this one. I have one form which is fulfilled by users but needs to be approved by sector management, not a group or a single approver like image bellow:
![38423314-de16fbde-39ad-11e8-83b6-2fa3eec5e1d1](https://user-images.githubusercontent.com/45013403/77942977-db676700-7292-11ea-886e-e65d691a61ef.jpg)

**Comment by btry** [comment]
Hi

Can you check that at least one group contains at least one user having the at least one of the following rights ?

- ticket validation for incidents
- ticket validation for requests

**Comment by fralla2** [comment]
OMG sorry for that. This option completely slipped my mind... 
For whatever reason I thought that it was missing the plugins' common tab inside the profiles (like some others plugins uses) and didn't realize it used the Assistance (Tickets) tab from GLPI itself.

Thanks again for pointing it to me.

Can I ask you another unrelated question/suggestion? Or should I open a new issue/question in gitHub?

Thanks
Francois

**Comment by btry** [comment]
If you have an other question or bug report, it is  better to open a dedicated ticket.

**Comment by fralla2** [comment]
Ok perfect. 

Yes you can close it. Addind ticket validation rights to the profiles added both the user and his groups to the dropdown menu ;)

Thanks
