### ISSUE TITLE
Choose Approver inside the Form

### ISSUE THREAD

**Issue by sidgaabriel** [pluginsGLPI/formcreator#1718]
It's possible to user choose a validator in a dropdown list, I saw this feature on previous versions but it's not enable on this one. I have some forms which are fulfilled by users but needs to be approved by management, not a group or a single approver like, each department has his own manager responsible to approve a new requested ticket to IT team, I saw this on a 2019 posts if I'm not incorrect but wasn't able to reproduce at 2.9.1 version that I'm currently using right now.
![77942977-db676700-7292-11ea-886e-e65d691a61ef](https://user-images.githubusercontent.com/45013403/78027240-6e57de00-7333-11ea-8552-72e53f5f0ee0.jpg)

**Comment by btry** [comment]
Hi

Log ago a user suggested to disable choosing a validator when there is only one in the dropdown, and select it automatically. Maybe you have only one choice, which hides the dropdown.

**Comment by sidgaabriel** [comment]
But I have at least 15 approvers, thats why I wanted to enable this for one specific form, so after the user fulfill the form he chooses the approver currently managing his sector. I created 2 test users and enable it on a test form but when I save an try to subject a form a Pop-Up message appears to me requesting to select a validator (please check pints bellow).
![1](https://user-images.githubusercontent.com/45013403/78029873-a3fec600-7337-11ea-8b66-e641a1bf410b.jpg)
![2](https://user-images.githubusercontent.com/45013403/78029876-a5c88980-7337-11ea-8780-fd7ac7383ed8.jpg)
![3](https://user-images.githubusercontent.com/45013403/78029878-a6f9b680-7337-11ea-831a-353f6285b33c.jpg)

**Comment by sidgaabriel** [comment]
Any news?

**Comment by btry** [comment]
Hi

In your 2nd screenshot, it appears that no users in the list is selected. Is it what you want ?

**Comment by sidgaabriel** [comment]
No, I want the user to select who is gonna approve the form, is a all-company form so a user select an approver to the form.

**Comment by sidgaabriel** [comment]
In a nutshell, I need this approver field available at form field so user can choose who will approve the selected form.

**Comment by btry** [comment]
Hi

I guess you misunderstood the implementation of the feature. You must select at least 2 users in the form designer to define a subset of validators. Those users will be available for validation in the requester point of view. Non selected users in the form designer will not be available.


Try to select 2 users, then try to fill the form as a requester. The validators field shall show.

**Comment by sidgaabriel** [comment]
Please, how can I select 2 users if the dropdown menu only allows me to choose one? Can you show me an example how to do a form like this?

**Comment by sidgaabriel** [comment]
I really tried but can't select 2 users, it only allows me one. Could be browser issue? I'm using new Edge and Firefox with both presenting the same behavior.

**Comment by btry** [comment]
Hi

Sorry for the late reply. I reproduce the issue. Please try the PR #1723

**Comment by sidgaabriel** [comment]
Thanks for the reply, now it's working!

**Comment by sidgaabriel** [comment]
Please, I notice that when I choose all the form validator field does not appear at form but when I choose more the one but not all the field appear:
![image](https://user-images.githubusercontent.com/45013403/80252061-01431a00-864d-11ea-978a-5d82504460f3.png)
![image](https://user-images.githubusercontent.com/45013403/80252086-0b651880-864d-11ea-9006-c47305339fce.png)
![image](https://user-images.githubusercontent.com/45013403/80252111-17e97100-864d-11ea-84a6-1bea67015f17.png)
![image](https://user-images.githubusercontent.com/45013403/80252196-3cdde400-864d-11ea-935c-fc64979dee5b.png)
Please, could you help me?

**Comment by btry** [comment]
Hi
Can you test this fix and feedback ?

https://github.com/pluginsGLPI/formcreator/pull/1743

**Comment by sidgaabriel** [comment]
> Hi
> Can you test this fix and feedback ?
> 
> #1743

Fixed again, thanks for the quick reply.
