### ISSUE TITLE
Question type liste LDAP : Problème sur les filtres

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#172]
Glpi Version : 0.90.1
PLugins Version : 0.90-1.3.3

Lors de l'ajout d'une liste de type LDAP, avec l'attribut "(LDAP) Common Name" et le filtre "(objectClass=user)", le filtre n'est pas pris en compte. L'ensemble des utilisateurs et ordinateurs de l'active directory sont remontés.

En mode debug, je n'ai aucune erreur, dans les fichiers de logs /var/www/glpi/_log/php-errors.log, je n'ai pas d'erreur non plus.

Les utilisateurs GLPI sont synchronisés avec un annuaire LDAP. Le filtre est fonctionnel pour la partie "Authentification", "Filtre de connexion" dans GLPI.

**Comment by neeftarah** [comment]
Bonjour,

Je ne suis pas expert en LDAP, mais êtes-vous sûr de votre filtre ?
Le filtre par défaut de GLPI pour les Active Directory et légèrement plus complexe : 
(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))

**Comment by SylvainGuibert** [comment]
Effectivement...le filtre était un peu léger..... Avec le filtre que tu as fournis...le résultat est celui attendu  (La liste des utilisateurs) !!

Merci !
