### ISSUE TITLE
PB bouton radio à l'impression

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1720]
Bonjour,
J'ai constaté un petit souci lors de l'impression des formulaires j'utilise l'impression PDF pour récupérer le formulaire au format pdf et j'ai un souci avec les questions avec bouton radio.
En fait la réponse cochée n'apparait pas correctement par exemple ci-dessous: 
![image](https://user-images.githubusercontent.com/25478777/78502081-7d89c200-775f-11ea-8f67-c7bc75a100ba.png)
J'ai essayé avec plusieurs formats de PDF avec adobe et Windows et c'est toujours le même résultat.
Pour info, je suis en glpi 9.4.4 et formcreator 2.9.1 (testé en 2.8.6 également)
Merci d'avance

**Comment by btry** [comment]
Hi

Please try the fix #1722

**Comment by eckorion** [comment]
Hello,

C'est pareil, 
![image](https://user-images.githubusercontent.com/25478777/79242023-11504200-7e74-11ea-9892-cebd817b3d79.png)

Cdlt

**Comment by btry** [comment]
Le changement est principalement dans le CSS, rafraichissez la page avec F5 et réessayez. Je pense que le navigateur utilise l'ancienne version des styles.

**Comment by eckorion** [comment]
Oui j'avais fait, le problème est sur Firefox. Ça fonctionne correctement avec chrome.

**Comment by btry** [comment]
Bonjour

Ca fonctionne correctement avec Firefox pour moi. De toute façon, j'e trouve que le rendu sur PDF d'un bouton radio n'est pas cohérent avec un checkbox (d'un point de vue purement esthetique). J'ai donc fait cette autre solution. Elle pourait être plus satisfaisante.

https://github.com/pluginsGLPI/formcreator/pull/1732

**Comment by eckorion** [comment]
Bonjour,

Ça a l'air de fonctionner, j'ai tester avec Chrome et Firefox c'est beaucoup mieux :)
Merci beaucoup

**Comment by btry** [comment]
Ok, je vais merger cette version. Merci pour le retour

**Comment by btry** [comment]
#1732 merged
