### ISSUE TITLE
champs de formulaire obligatoire

### ISSUE THREAD

**Issue by radiaips** [pluginsGLPI/formcreator#1725]
Bonjour, 

Je souhaite rendre quelque champs de formulaire représentés sous des dropDown obligatoires, d'une façon que le formulaire ne se valide pas si l'une des liste est vide !

Y'a til une solution pour ça sans avoir à modifier tout les fichiers qui génèrent ces listes ?

**Comment by btry** [comment]
Bonjour

C'est ici (l'allure de l'éditeur de questions diffère un peu en 2.8 et 2.9 : la capture vient de la branche develop): 
![image](https://user-images.githubusercontent.com/14139801/79436225-e29bae00-7fd0-11ea-8760-1b643c366629.png)

**Comment by radiaips** [comment]
Bonjour, 
Je vous remercie pour votre retour. est-il possible d'avoir le cheminement pour accéder à cette fenêtre? je me connais pas trop en interface glpi, je travaille plutôt le code source  php  sous la version 9.3.3.
je vous remercie d'avance .

**Comment by btry** [comment]
C'est dans le menu Administration > formulaires. Ensuite ouvrez un formulaire de la liste, puis éditez une question de type sélecvtion ou intitulé.

**Comment by radiaips** [comment]
Et si l'onglet formulaire n'existe pas dans Administration ?  c'est pas relié à un plugin precis ? 

 mon menu administration contient :  users , profiles , groups , notification , entities , maintenance , rules , logs et dictionaries .

**Comment by btry** [comment]
Cela existe forcément, du moment que vous avez le droit pour créer et modifier des formulaires (équivalent au droit de modifier les entités) et sue le plugin est actif.

**Comment by btry** [comment]
Bonjour

Avez vous toutes les réponses à vos questions ? Si oui, vous pouvez fermer ce ticket.

**Comment by radiaips** [comment]
Bonjour, 
je m'excuse de ne pas vous avoir répondu avant aujourd’hui.
pour avoir formulaire dans le menu administration il faudra bien ajouter le plugin Formcreator, j'ai essayé de voir de plus prés ce plugin et j'ai constaté qu'il repond pas à mon besoin d'ajouter des champs obligatoire sur les formulaires de Assets=>computers par exemple, mais uniquement sur les tickets !
Si je me trompe dites moi.

**Comment by btry** [comment]
Bonjour

Ce plugin sert à concevoir des formulaires pour pour générer des tickets ou des changements de manière adaptée à certaines problématiques (exemple, un formulaire dédié aux problèmes de VPN, un autre dédié aux problèmes de réseau, etc)

Il n'ajoute rien sur les formulaires de GLPI lui même. Si cela est votre besoin allez voir le plugin Fields : https://github.com/pluginsGLPI/fields

**Comment by radiaips** [comment]
Bonjour, 

Je vous remercie pour votre  retour et réactivité.
