### ISSUE TITLE
Modification impossible des formulaires apres migration vers 2.9.1

### ISSUE THREAD

**Issue by Ricou11** [pluginsGLPI/formcreator#1729]
**Describe the bug**

Bonjour,
GLPI = 9.4.1.1
FORMCREATOR = 2.8.0

migration vers FORMCREATOR 2.9.1 sans aucun message = OK !

Mais impossible a présent de modifier les formulaires. Ils sont bien la et apparaissent dans la liste des formulaires. Lorsque l'on rentre pour modifier un formulaire, l'écran contient juste le titre du formulaire ! il n'y a plus les onglets à gauche, plus de détail -> plus rien !!! 
Il faut noter par ailleurs, qu'ils fonctionnent toujours et créent des tickets sans problèmes.

Avez-vous une solution a mon problème SVP ?

Je vois rien au niveau des droits ou autre 

Merci

**Comment by btry** [comment]
Bonjour

Ca ressemble à une erreur HTTP 500. Vérifiez les logs du serveur HTTP et les fichiers php-errors.log / sql-errors.log.

 Est ce que vous avez un environnement de test pour essayer avec GLPI 9.4.5 ?

Si il y a effectivement une perte de compatibiltié avec GLPI 9.4.1, je vais voir si je peux résoudre le souci.

**Comment by Ricou11** [comment]
Bonjour,
Non DSL pas de serveur de test pour l'instant !

Rien de spécial dans le php-errors.
Dans le sql-errors je vois :

[2020-04-16 10:26:35] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `formcreator_field_13` = '' WHERE `id` = '13'
  Error: Unknown column 'formcreator_field_13' in 'field list'
  Backtrace :
  inc/dbmysql.class.php:936                          
  inc/commondbtm.class.php:616                       DBmysql->update()
  inc/commondbtm.class.php:5170                      CommonDBTM->updateInDB()
  ...mcreator/inc/fields/textareafield.class.php:155 CommonDBTM->addFiles()
  plugins/formcreator/inc/fields.class.php:331       PluginFormcreatorTextareaField->parseAnswerValues()
  plugins/formcreator/ajax/showfields.php:35         PluginFormcreatorFields::updateVisibility()
  {"user":"216@HSP-GLPI-REC"} 

[2020-04-16 10:26:42] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `formcreator_field_13` = '&lt;p&gt;blabla&lt;/p&gt;' WHERE `id` = '13'
  Error: Unknown column 'formcreator_field_13' in 'field list'
  Backtrace :
  inc/dbmysql.class.php:936                          
  inc/commondbtm.class.php:616                       DBmysql->update()
  inc/commondbtm.class.php:5170                      CommonDBTM->updateInDB()
  ...mcreator/inc/fields/textareafield.class.php:155 CommonDBTM->addFiles()
  plugins/formcreator/inc/formanswer.class.php:1247  PluginFormcreatorTextareaField->parseAnswerValues()
  plugins/formcreator/inc/formanswer.class.php:678   PluginFormcreatorFormAnswer->validateFormAnswer()
  inc/commondbtm.class.php:1100                      PluginFormcreatorFormAnswer->prepareInputForAdd()
  plugins/formcreator/front/form.form.php:132        CommonDBTM->add()
  {"user":"216@HSP-GLPI-REC","mem_usage":"0.000\", 5.29Mio)"}

**Comment by btry** [comment]
Bonjour 

Votre erreur SQL ne me semble pas liée à votre problème, en plus d'être surprenante. C'est comme si quelque chose devait générer dynamiqueemtn des colonnes dans une table, ce qui est exclu dans la conception du plugin.

Vous n'avez rien trouvé dans les logs du serveur HTTP  (/var/www/apache2/errors/errors.log ou assimilé)  ?

**Comment by Ricou11** [comment]
Bonjour

Dans le "ssl_error_log" ...

[Thu Apr 16 11:46:18.547656 2020] [:error] [pid 3944] [client
82.234.156.207:53466] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415
[Thu Apr 16 11:47:32.494775 2020] [:error] [pid 9885] [client
82.234.156.207:53563] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.form.php?id=1
[Thu Apr 16 11:47:36.786307 2020] [:error] [pid 9885] [client
82.234.156.207:53563] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.form.php?id=17&
[Thu Apr 16 11:48:34.043221 2020] [:error] [pid 11129] [client
82.234.156.207:53621] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 11:51:15.662603 2020] [:error] [pid 9885] [client
82.234.156.207:53735] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 11:51:38.052918 2020] [:error] [pid 11147] [client
82.234.156.207:53739] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 11:55:54.737528 2020] [:error] [pid 3966] [client
82.234.156.207:53773] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 11:56:04.158262 2020] [:error] [pid 11665] [client
82.234.156.207:53774] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 11:56:11.671363 2020] [:error] [pid 3944] [client
82.234.156.207:53775] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 14:34:34.174242 2020] [:error] [pid 11129] [client
82.234.156.207:54917] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 14:37:34.006646 2020] [:error] [pid 9885] [client
82.234.156.207:54973] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 14:38:28.199922 2020] [:error] [pid 3944] [client
82.234.156.207:54991] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 15:31:55.665753 2020] [:error] [pid 9887] [client
82.234.156.207:55424] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 17:03:59.526844 2020] [:error] [pid 11608] [client
82.234.156.207:56406] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415
[Thu Apr 16 17:05:21.592033 2020] [:error] [pid 6403] [client
82.234.156.207:56409] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415, referer:
https://support-rec.hesperia.fr:43443/glpi/plugins/formcreator/front/form.php
[Thu Apr 16 17:50:17.723796 2020] [:error] [pid 9887] [client
82.234.156.207:56702] PHP Fatal error:  Uncaught exception
'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index
1 does not exist in plural array' in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php:415\nStack
trace:\n#0 /var/www/html/glpi/inc/autoload.function.php(172):
Zend\\I18n\\Translator\\Translator->translatePlural('Access type', 'Access
types', 2, 'formcreator')\n#1
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(45):
_n('Access type', 'Access types', 2, 'formcreator')\n#2
/var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(49):
PluginFormcreatorForm_Profile::getTypeName(2)\n#3
/var/www/html/glpi/inc/commonglpi.class.php(210):
PluginFormcreatorForm_Profile->getTabNameForItem(Object(PluginFormcreatorForm),
0)\n#4 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(729):
CommonGLPI->addStandardTab('PluginFormcreat...', Array, Array)\n#5
/var/www/html/glpi/inc/commonglpi.class.php(165):
PluginFormcreatorForm->defineTabs(Array)\n#6
/var/www/html/glpi/inc/commonglpi.clas in
/var/www/html/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php
on line 415

**Comment by btry** [comment]
Bonjour

C'est un problème dans le cache des traductions du plugin.
Vous devez planifier une maintenance pour faire ce qui suit

- Stopper Apache ou le service php-fpm (selon votre setup)
- effacer le cache de glpi (glpi/files/_cache/locales); attention, je donne le chemin de mémoire, je peux me tromper
- redémarrer Apache ou php-fpm
- tester si le bug persiste.

Il me semble qu'il y a un autre ticket (fermé) pour ce problème. Une recherche devrait permettre de le retrouver.

**Comment by Ricou11** [comment]
Bonjour,
Effectivement, après "suppression" du cache, je peux accéder en modification aux formulaires !
Bravo et merci à vous.
