### ISSUE TITLE
In the field description, accented characters are not correctly displayed

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#173]
See the original report here : http://forum.glpi-project.org/viewtopic.php?id=143972

**Comment by neeftarah** [comment]
This problem seems to be due to lacks in PHP <= 5.3
GLPI 0.90 (and Formcreator 0.90) support only PHP >= 5.4

If PHP is the problem, we wont correct this.
Please test this and tell me.

(I develop on PHP 5.6 and GLPI 0.90+ and doesn't have any problem)

**Comment by dethegeek** [comment]
so let's see if the user can upgrade and report. As I told him, this may be related to the other issue I mentioned on the forum.

**Comment by btry** [comment]
so let's see if the user can upgrade and report. As I told him, this may be related to the other issue I mentioned on the forum.
