### ISSUE TITLE
Impression PDF en interface simplifiée

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1735]
Bonjour,
Je m'aperçois que l'impression est décalée si on imprime un formulaire depuis l'interface simplifiée
![image](https://user-images.githubusercontent.com/25478777/80074941-374ba580-854a-11ea-8d54-60b8f62c559f.png)
En mode interface standard ça fonctionne correctement. 
GLPI 9.4.4 et Formcreator 2.9.1 avec la modification pour les boutons radio.
Identique avec Chrome et Firefox

Cordialement

**Comment by btry** [comment]
Bonjour

Pouvez vous vérifier si cela persiste avec la version 2.9.2 en dev (branch support/2.9.2) ?

**Comment by eckorion** [comment]
Bonjour,
Ça m'indique que j'ai la version 2.11.0 d'installée mais c'est pareil.

**Comment by btry** [comment]
Bonjour

Effectivement, support/2.9.2 n'existe pas. Je voulais dire support/2.9.0. A priori vous avez pris la branche develop. Ca devrait suffire pour valider que le souci est toujours d'actualité.

**Comment by btry** [comment]
Bonjour

Je fais un test, et ne constate pas d'anomalie (branche support/2.9.0). Essayez en vidant le cache du navigateur.

**Comment by eckorion** [comment]
Bonjour,
C'est peut être dû au fait que je faisais un upgrade, par contre j'ai voulu refaire une installation de zéro, j'ai le message suivant après l'installation de formcreator :
You must run vendor/bin/robo build:fa-data in the directory of the plugin
Mais je n'ai pas ça, où puis-je le trouver?
Merci

**Comment by btry** [comment]
Bonjour

Vous devez installer composer puis l'exécuter comme mentionné après vous être positionné dans le dossier de formcreator.

Vous trouverez plus de détails dans d'autres tickets (fermés).

**Comment by eckorion** [comment]
Bon j'ai installé composer et du coup la version 2.9.2, mais c'est toujours pareil
![image](https://user-images.githubusercontent.com/25478777/80586064-a9bdf900-8a14-11ea-8417-d7c21dc3505f.png)
Je précise que c'est uniquement depuis l’interface simplifiée que ça le fait et l'impression d'une manière générale, PDF ou pas.

**Comment by btry** [comment]
Bonjour

On peut conclure que le comportment est le même entre les 2 versions. Cependant je ne reproduis toujours pas.

L'utilsiateur est en interface simplifiée. Le catalogue de services est-il activé ?

Sur votre capture d'écran, il y a des aprties qui ne devraient pas apparaitre sur la version imprimée. Il y a peut être un lien avec le souci

![image](https://user-images.githubusercontent.com/14139801/80684536-1ba24b00-8ac6-11ea-9a20-8955ac1dde64.png)

**Comment by eckorion** [comment]
Oui effectivement, c'est depuis le catalogue de service (étendu ou simplifié). Si je désactive le catalogue de service même en self service c'est correct.

**Comment by eckorion** [comment]
voici l'aperçu avant impression:
![image](https://user-images.githubusercontent.com/25478777/80807687-2213ee00-8bbe-11ea-8f7d-38c530457fea.png)

**Comment by btry** [comment]
Hi

Could you test the patch above and feedback ?

**Comment by eckorion** [comment]
Bonjour, désolé pour le délai, j'étais passé à côté de la notif.
Oui c'est bon, ça a l'air de fonctionner
![image](https://user-images.githubusercontent.com/25478777/83733976-a12d9380-a64e-11ea-9b91-375bf45aa52c.png)

**Comment by btry** [comment]
Bonjour

Merci pour le retour. Je correctif sera dispo dans la version 2.10.0-rc.1 à venir dans quelques jours. N'hésitez pas à la tester et remonter les éventuels bugs.
