### ISSUE TITLE
Formcreator 2.9.1  More than one validator

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/formcreator#1737]
Formcreator no longer allows you to add another approver to the form, as it did in previous versions.

![Error Formcreator](https://user-images.githubusercontent.com/30185683/80232689-b06ef980-862b-11ea-9115-fd1d043cbee1.png)

**Comment by sidgaabriel** [comment]
Dear friend, please check the [#1718](https://github.com/pluginsGLPI/formcreator/issues/1718) thread.

**Comment by mrcssilvasouza** [comment]
thanks
