### ISSUE TITLE
[2.9.1] Champs "Par" et "Demandeur" égaux

### ISSUE THREAD

**Issue by 666dsa666** [pluginsGLPI/formcreator#1739]
Bonjour,

Nous venons de remarquer que suite au passage sur la version 2.9.1 les champs tickets Par et Demandeur sont remplacés par le champ demandeur.

Le champ demandeur doit être égal à la réponse à une question, cependant le champ "Par" était jusqu'à présent égal à : utilisateur ayant rempli le formulaire

Cela permettait de suivre qui avait créé le ticket en séparant cette information de pour qui il avait été créé.

Il est uniquement possible de configurer le champ demandeur, ce qui ne permet plus ce suivi.

**Comment by btry** [comment]
Bonjour

Il y a eu des modifications sur la gestion de ces champs récemment. Ces modifications visent à mieux gérer la distinction entre l'auteur et le demandeur d'un ticket.

Pouvez vous tester la version de la branche support/2.9.0 ? Cette branche représente à ce jour la versin 2.9.2, qui la prochaine release.

**Comment by btry** [comment]
Bonjour

A défaut de réponse je ferme ce ticket. La version 2.9.2 devrait résoudre le souci.
