### ISSUE TITLE
Validation - Groupe - Liste incomplete

### ISSUE THREAD

**Issue by blienard** [pluginsGLPI/formcreator#174]
La liste des groupes valideurs est incomplète, seulement 34 groupes affichés sur 67 disponibles.

GLPI 0.90.1
Plugin Formulaires 0.90-1.3.3

**Comment by neeftarah** [comment]
Bonjour,

Pour des raisons à la fois de droits, de sécurités et de simplicité, seuls les groupes contenant des utilisateurs ayant eux-même les droits de validation sur les tickets (dans leurs profils) sont affichés dans la liste des groupes valideurs.

Est-ce bien le cas des 33 groupes manquants ?

Cordialement,
Jérémy

**Comment by blienard** [comment]
Parmi les 33 manquants, j'ai un groupe avec 2 personnes ayant des droits de validation.

J'ai créé un nouveau groupe avec des utilisateurs ayant des droits de validation (en tout point similaire à un groupe existant apparaissant dans la liste des groupes valideurs), celui n'apparait toujours pas dans la liste.
A noter que j'ai un groupe sans nom dans la liste déroulante.
