### ISSUE TITLE
problème affichage question après zone texte conditionnée

### ISSUE THREAD

**Issue by sbea17** [pluginsGLPI/formcreator#1745]
**Describe the bug**
Bonjour
je crée des formulaires qui utilisent des questions conditionnées à certaine réponses faites précédemment en utilisant 'Masqué par défaut, sauf si'
Cela fonctionne très bien pour la plupart des types de questions que j'utilise sauf pour les zones de texte.
Visuellement les questions placées derrière une zone de texte sont incluses dans le bloc zone de texte au lieu d'être dans un bloc séparé en-dessous comme c'est le cas pour tous les autres types de questions. 
Si je remplace le type 'zone de texte' par 'texte', j'obtiens le comportement attendu pour toutes les questions conditionnées ou pas.
En résumé, dès qu'on utilise une zone texte conditionnée, toutes les questions et sections suivantes sont imbriquées sous la zone texte, au lieu d'être indépendantes.

Ci-dessous des exemples pour reproduire les cas.
J'espère être assez claire.
Merci pour votre aide.
Cordialement

**To Reproduce**
1. **Exemple1**
- Formulaire:
question1: sélection xxx ou yyy
question2: zone de texte sans condition
question3: radio bouton sans condition
question4: zone texte masqué sauf si réponse1 = xxx
question5: radio bouton sans condition

- Résultats - scenario 1:
question1: réponse yyy
question2 affichée même niveau que question1
question3 affichée même niveau que question2
question4 non affichée
question5 non affichée _**-> comme elle n'a pas de condition je m'attends à ce qu'elle s'affiche**_

- Résultats - scenario 2:
question1: réponse xxx
question2 affichée même niveau que question1
question3 affichée même niveau que question2
question4 affichée même niveau que question 3
question5 affichée **_mais au même niveau que la zone de texte et non au même niveau que les autres questions_**

2. **Exemple2**
- Formulaire:
question1: sélection xxx ou yyy
question2: zone texte masqué sauf si réponse1 = xxx
question3: radio bouton sans condition
question4: zone de texte sans condition
question5: radio bouton sans condition

- Résultats - scenario 1:
question1: réponse yyy
question2 non affichée
question3 non affichée **_-> je m'attends à ce que ce soit affiché_**
question4 non affichée **_-> je m'attends à ce que ce soit affiché_**
question5 non affichée **_-> je m'attends à ce que ce soit affiché_**
_**et même la section suivante non conditionnée ne s'affiche pas**_

- Résultats - scenario 2:
question1: réponse xxx
question2 affichée même niveau que question1
question3 affichée **_mais au même niveau que la zone de texte précédente et non au même niveau que la question2_**
question4 **_affichée mais imbriquée sous question3_**
question5 **_affichée mais imbriquée sous question4_**
la section suivante non conditionnée s'affiche

**Desktop (please complete the following information):**
FormCreator 2.9.1
GLPI 9.4.5

**Comment by btry** [comment]
Bonjour

Le  bug devrait être résolu avec la version 2.9.2. Pouvez-vous l'essayer et rapporter si le souci est résolu ?

**Comment by sbea17** [comment]
Bonjour
Effectivement, mes différents tests sont concluants.
Merci pour ces corrections.
