### ISSUE TITLE
default ticket form

### ISSUE THREAD

**Issue by boscorelly** [pluginsGLPI/formcreator#1746]
Hi,

is there a way to replace the default ticket form with a catalog/list of forms ?

**Comment by btry** [comment]
Hi

Sorry for the delay...

If the default ticket form is the new ticket form of the simplified interface (self service profile), then Formcreator completely replaces the self service interface with its own design. Just enable service catalog (simplified or extended)  in an entity and Formcretor will provide your own forms in this entity and its subtree.

**Comment by boscorelly** [comment]
hi,

i will check if i can activte it :)

Le 06/01/2021 à 20:53, btry a écrit :
