### ISSUE TITLE
Probleme niveau urgence entre le formulaire et le ticket

### ISSUE THREAD

**Issue by chumbert39** [pluginsGLPI/formcreator#1747]
GLPI 9.4.5 FormCreator 2.9.1 
 
Bonjour,

j'ai remarqué un problème lors de la génération du ticket via un formulaire.
En effet, le degré d'urgence est demandé à l'utilisateur via une question de type Urgence.
Dans la cible de celui-ci, j'ai bien indiqué Urgence spécifique / question mais le ticket généré ne correspond pas au niveau de l'urgence.

Étant novice dans l'utilisation de GLPI pouvez-vous m'indiquer s'il s'agit d'un bug ou si cela est dû à une mauvaise utilisation ?

Vous remerciant par avance.

![1](https://user-images.githubusercontent.com/63642754/80609951-04694c00-8a39-11ea-8a19-5ad8389cc93f.png)
![2](https://user-images.githubusercontent.com/63642754/80609968-0a5f2d00-8a39-11ea-9337-d15743109382.png)

**Comment by msizec** [comment]
Je peux te dire ce que j'ai vu a ce sujet : il y a un bug tout con, quand on sélectionne "Urgence spécifique", il propose de sélectionner une question, alors qu'il devrait lister les urgences.
Et si tu choisis urgence liée à une question, il propose la liste des urgences.

**Comment by btry** [comment]
Bonjour

La branche supportL2.9.0 doit contenir des fix correspondant à ce problème. Vendredi sortira la version 2.9.2, basée dessus.

**Comment by btry** [comment]
Bonjour

Je suppose que le problème a été résolu.
