### ISSUE TITLE
Formcreator 2.9.1 does not allow you to pre-define the checklist.

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/formcreator#1748]
Formcreator 2.9.1 does not allow you to pre-define the checklist.

![image](https://user-images.githubusercontent.com/30185683/80767829-3523b100-8b1f-11ea-8e03-445803229912.png)

**Comment by btry** [comment]
Hi

There was a typo in the coede. Fixed with 0ed7cf32
