### ISSUE TITLE
Missing variable declaration on js/script.js.php

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1749]
**Describe the bug**
Missing declaration of variable html on js script.

**To Reproduce**
1. Update query to break list of forms display.
2. Open browser console.

**Expected behavior**
If there's an error to the query for display form list, it should display "An error occured while querying forms" but since there's a missing declaration of variable html on [line](https://github.com/pluginsGLPI/formcreator/blob/3ee813f1217fae49bf60701181be4ae718c237d6/js/scripts.js.php#L324) , user cannot view the error message.

**Comment by btry** [comment]
Hi please create a PR to fix this. You just need to prefix the line you pointed with the keyword 'var'.

I'll merge it next week

**Comment by leecheromerevilit** [comment]
Hi @btry. I'll create a PR for this but I need to fix the underlying error and the reason why I found this bug.

Upon upgrading to glpi v9.4.5 from 9.4.3, FormCreator plugin will show this error on FormList page. 

On browser console, there's a js on glpi itself and a missing package on the lib folder.

"Uncaught TypeError: $(...).masonry is not a function
    at Object.<anonymous> (scripts.js.php?v=2.9.0:286)
    at fire (jquery.js?v=9.4.5:3232)
    at Object.fireWith [as rejectWith] (jquery.js?v=9.4.5:3362)
    at Object.deferred.<computed> [as reject] (jquery.js?v=9.4.5:3461)
    at Object.<anonymous> (scripts.js.php?v=2.9.0:224)
    at fire (jquery.js?v=9.4.5:3232)
    at Object.fireWith [as rejectWith] (jquery.js?v=9.4.5:3362)
    at done (jquery.js?v=9.4.5:9842)
    at XMLHttpRequest.callback (jquery.js?v=9.4.5:10311)
formlist.php:293"

"see_debug #debugtabs1955502755"

"DevTools failed to load SourceMap: Could not load content for http://127.0.0.1/lib/leaflet/plugins/Leaflet.markercluster/leaflet.markercluster.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"


I have no problem with glpi version 9.4.3 with FormCreator plugin developer version.

No sql error can be seen on the Debug Mode also.

**Comment by btry** [comment]
P
Hi

Please check the file sql-errors.log in your glpi instance. I expect you get an error die to a missing column. There are several closed tickets about that. The solution is a fix for GLPI.

**Comment by btry** [comment]
I checked in the old tickets. GLPI 9.4.4 (not 9.4.5) you need the following fix https://github.com/glpi-project/glpi/pull/6365

It appears that you're not in this case. This needs more investigation

**Comment by leecheromerevilit** [comment]
Hi @btry.

I did a fresh install in both GLPI and FormCreator plugin.
GLPI = 9.4.5
FormCreator = v2.10.0-beta.1
All good for now. 

This is the version where I encounter the error.
GLPI = 9.4.3
FormCreator = develop

Just a side question.
I was developing a feature on the develop branch and is planning to create a PR when I'm done when I encountered the error. Now I tried to use the develop branch again and apply my changes for the feature but it seems that I cannot load the develop branch on glpi even If I renamed the folder to "formcreator". 

1. Does this suggest that the develop branch is not compatible with GLPI v9.4.5? I was developing the feature on GLPI v9.4.3 before.

**Comment by btry** [comment]
You should keey the same version of GLPI and change only the version of Formcreator. If not, it is harder to find if the bug is in the plugin or not.

If the issue appears only in the branch develop, either i forgot to put a fix from 2.10 or 2.9 in the branch develop, either there is a regression. To be sure about that, you should upgrade yout GLPI to 9.4.5.

About your development : the branch develop is still compatible with GLPI 9.4 : https://github.com/pluginsGLPI/formcreator/blob/develop/setup.php#L41

Please check in the plugins list of GLPI if you ran the upgrade process.

**Comment by leecheromerevilit** [comment]
I will dig deeper into this and will get back as soon I have the report.

**Comment by leecheromerevilit** [comment]
Hi @btry.

These reports may sound weird but I hope this will help in the future.

GLPI v9.4.3, v9.4.4 and v9.4.5
FormCreator developer
Status: Missing plugin on plugin list page.

I have no idea what causes this issue.

But, when I tried my backup file for FormCreator developer version it shows on the plugin list. This version is not updated btw. 

PS. This maybe an isolated case but just to place it here for reference. For Now I'll be using this version to continue my development on the feature. 

Thanks.

**Comment by btry** [comment]
There are 2 main reasons to make the plugin missing : 
- the folder of the plugin does not has the expected name (here: "formcreator")
- the rights of the files of the plugin don't allow the HTTP server to read them.

I would recomment you have GLPI somewhere in your $HOME + the plugin installed. Next run PHP as a HTTP server with **php -S localhost:80** (you must be located in the root of GLPI or you need to specify its path with the argument **-t** (example **php -S localhost:80 -t ~/glpi**

**Comment by btry** [comment]
The varaible declaration for tje JS code is fixed : 071d39d0

**Comment by btry** [comment]
Hi 

I guess we can close this issue ?

**Comment by btry** [comment]
Hi

Having no feedback here, I guess I can close.
