### ISSUE TITLE
Section Condition bug

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1753]
**Describe the bug**
Section condition still exists after setting section condition to Always displayed.

**To Reproduce**
1. Go to section
2. Update 'Condition to show the section' to any condition
3. Refresh page
4. Update 'Condition to show the section' to 'Always displayed'
5. Refresh page
6. Return to section

**Expected behavior**
There should be no condition displayed if section is set to 'Always displayed'

**Additional context**
GLPI v9.4.5
FormCreator v2.11.0-nightly

**Propose Fix**
Add delete on [this](https://github.com/pluginsGLPI/formcreator/blob/c7a2537bdc0c95373936296759489355524d57ce/inc/conditionnable.class.php#L39) condition to delete all conditions set per section.

**Comment by btry** [comment]
Hi

Here is a fix b2655e54. The bug impacted all conditionable objects.
