### ISSUE TITLE
mail générer automatiquement lors de la création de formulaire

### ISSUE THREAD

**Issue by lucas693600** [pluginsGLPI/formcreator#1756]
bonjour lorsque je créer un formulaire j'ai en réponse automatique un mail 
[GLPI] ##ticket.action## ##ticket.title## en sujet 
et j'ai dans le mail Généré automatiquement par GLPIGénéré automatiquement par GLPI
j'aurais voulu savoir s'il était possible d'avoir un mail automatique comportant en sujet demande de validation de formulaire en attente? 
Merci d'avance pour vos réponses 

hello when i create a form i have an automatic response an email
[GLPI] ## ticket.action ## ## ticket.title ## in subject
and I have in the mail Automatically generated by GLPIGenerated automatically by GLPI
I would have liked to know if it was possible to have an automatic e-mail comprising in subject pending form validation request?
Thank you in advance for your answers

**Comment by lucas693600** [comment]
up

**Comment by btry** [comment]
Hi 

This duplicated #1759, closing
