### ISSUE TITLE
request mail

### ISSUE THREAD

**Issue by lucas693600** [pluginsGLPI/formcreator#1759]
hello when i create a form i have an automatic response an email
[GLPI] ## ticket.action ## ## ticket.title ## in subject
and I have in the mail Automatically generated by GLPIGenerated automatically by GLPI
I would have liked to know if it was possible to have an automatic e-mail comprising in subject pending form validation request?
Thank you in advance for your answers

**Comment by btry** [comment]
Hi

There is a notification named **A form need to be validate**. It should  be enabled by default and have **approver** as recipient.

**Comment by btry** [comment]
Hi

Do you have any additional information about this issue, or should I close it ?
