### ISSUE TITLE
In "objects GLPI", no way to use objects from plugin "Generic Objects"

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1762]
**Describe the bug**
In type of question "GLPI object", objects from plugin generic objects are not presents.
They are present in target/associated elements, but can't be selected in the questions choice.

In fact, it's the same demand as https://github.com/pluginsglpi/formcreator/commit/25848d5e , but for genericobject.

We can select a Object from in target from genericobject but we can't create it in question. So how can associate question to target ?

**To Reproduce**
Add an object in generic object, fully configured (it's in the park menu)
Try to select it in glpi object, it's not shown.

**Expected behavior**
Can selecting objects from generic objects plugin.

GLPI 9.4.5+FormCreator 2.9.1

**Comment by mab18** [comment]
Hi,
Same problem with FC 2.9.2

**Comment by btry** [comment]
Linked to #1189
