### ISSUE TITLE
Duplicate a form - technician and observator are not copied

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#1765]
**Describe the bug**
When you duplicate a form : in the target section the Technician and Observator are not copied

**To Reproduce**
1. Go to 'Assistance' - Formulaires
2. Check on a Form which has a custom technician and a custom observator on the target
3. Duplicate it
4. Go to the duplicate form
5. Click on Target
6. Verify the technician and observator field

**Expected behavior**
Tehnician and observator fields should be copied

**Comment by btry** [comment]
Hi 

Which version of the plugiin ?

**Comment by btry** [comment]
Hi

I did a quick test with the branch support/2.9.0 (a few commits after the release 2.9.2 due tomorrow)

The valodator us in observers by default, and I added it again on assigned, then tried du duplicate the form. 

All actors are duplicated un the duplicated target ticket. Maybe are you using an version 2.9.1 or older ?

**Comment by btry** [comment]
Hi

Do you have feedback about his issue ?

**Comment by btry** [comment]
Hi

As I solved several duplication bugs recently, could you give feedback about this issue ?

**Comment by btry** [comment]
Hi

HAving no feedback about this issue, I close it. Feel free to open a new one if the problem persists with latest version of the plugin.
