### ISSUE TITLE
[2.11]  Update to 2.9 -> 2.11 breaks forms

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#1773]
As we discussed : 

- Checkbox values and default values are broken (expect JSON in 2.11, was plain text in 2.9)
- In admin view, form is rendered but send button is missing
![image](https://user-images.githubusercontent.com/42734840/82427770-d43a2980-9a89-11ea-997a-f474a9c34c38.png)

- In self-service view, send button is rendered but the form is missing
![image](https://user-images.githubusercontent.com/42734840/82427783-d7351a00-9a89-11ea-8c37-00fc7975d391.png)

Edit: point 2 & 3 are not specific to upgraded 2.9 forms, it will happen with any forms

**Comment by btry** [comment]
Hi

See #1772 for checkboxes (+ radios, select and multiselect)

> In admin view, form is rendered but send button is missing
I don't reproduce

> In self-service view, send button is rendered but the form is missing
image

I don't reproduce.

**Comment by AdrienClairembault** [comment]
I have another similar instance where everything are working...
I'll t

**Comment by AdrienClairembault** [comment]
I've pulled both glpi/9.5 and formcreator/develop.
Created a new test form:
![image](https://user-images.githubusercontent.com/42734840/83652039-74c83780-a5ba-11ea-9d02-fe23ee5c6005.png)

Added a section with a simple question:
![image](https://user-images.githubusercontent.com/42734840/83652125-8b6e8e80-a5ba-11ea-8945-2784986b0299.png)
![image](https://user-images.githubusercontent.com/42734840/83652151-93c6c980-a5ba-11ea-8750-17d0d1d28703.png)

When the form is displayed, the "send" button is still missing:
![image](https://user-images.githubusercontent.com/42734840/83652245-afca6b00-a5ba-11ea-91ac-5e59e57eb138.png)

It does appear a few milliseconds before being hidden so it's definitely some JS code that hide it.

**Comment by AdrienClairembault** [comment]
I'll try to find more details to help you reproduce.

**Comment by AdrienClairembault** [comment]
This happens because I'm missing the `show_rule field` in `glpi_plugin_formcreator_sections`
![image](https://user-images.githubusercontent.com/42734840/86803001-e0983700-c075-11ea-8825-06fa28cbed8b.png)

Not sure how this happened since this field was added in 2.9.

I think we can close this, probably a corrupted update ?

**Comment by btry** [comment]
Hi

OK to close: the DB is tested by comparing fresh and upgrade. I think that your DB was corrupted for some external reason
