### ISSUE TITLE
[2.11]  Modal misplaced + warning on new section

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#1774]
**Describe the bug**
When adding a section :
- The modal is not centered
- There is a warning on debug mode

**To Reproduce**
Create a new form, create a section

**Expected behavior**
Modal centered + no warning

**Screenshots**
![image](https://user-images.githubusercontent.com/42734840/82429977-fda88480-9a8c-11ea-81ac-d4e3337e2a1a.png)
PHP Notice (8): Undefined index: show_rule in /home/teclib/Main/html/glpi-fusion-94/plugins/formcreator/inc/condition.class.php at line 235

**Desktop (please complete the following information):**
Linux / Firefox

**Comment by btry** [comment]
Modal positioning : i did not investigated about that yet, but the plugin does not chooses how to set it. I don't know at this time if this is an issue in glpi side or plugin side.

About the php warning. I believe I fixed it recently. If your develop branch is not up to date, please try to pull the latest commits.

**Comment by btry** [comment]
Modal positionning should be related to #1867 

OHO warning should be solved also.
