### ISSUE TITLE
[2.11] Form data not displayed in ##FULLFORM##

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#1775]
**Describe the bug**
Form target: 
![image](https://user-images.githubusercontent.com/42734840/82431088-7f4ce200-9a8e-11ea-9337-3ef63a835e97.png)

Form answer: 
![image](https://user-images.githubusercontent.com/42734840/82431166-9b508380-9a8e-11ea-9960-7c6df7c2cf3b.png)

Ticket created:
![image](https://user-images.githubusercontent.com/42734840/82431243-b58a6180-9a8e-11ea-9730-7c44a97c5758.png)

**To Reproduce**
Create a form with a question and send it.
The form sections are displayed in the ticket but not the questions and their answers

**Expected behavior**
The answer to the checkbox should be displayed in the ticket description.

**Comment by btry** [comment]
This might be related to #1772 : values to be displayed must belong to the set of available values. If they are not migrated to JSON, the plugin could not recognize the available values.

Seems working when data in DB are correct ( fresh or properly migrated)

![image](https://user-images.githubusercontent.com/14139801/82725969-3345ab80-9ce1-11ea-9650-4155793a0363.png)

**Comment by btry** [comment]
waiting for a  re-check, might be solved now.
