### ISSUE TITLE
Actor field empty after failed submission of form answer

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1776]
**Describe the bug**
In a form with multiple fields, if the user provides a wrong type of answer and select  a correct actor on one of the actor fields, after the failed submission of the answer, the Actor fields will be cleared out.

**To Reproduce**
1. Create sample form with two fields. Integer and Actor
2. Insert non-integer on the integer fields and select a user on the actor field.
3. Click submit.
4. As expected, the form fail to submit the answer because of the provided data on integer field.

**Expected behavior**
The Actor field should retain the data provided by the user.

Versions
GLPI 9.4.5
FormCreator 2.11.0-nightly

**Comment by leecheromerevilit** [comment]
Hi @btry 

Do we have updates for this bug?

**Comment by btry** [comment]
Hi

not yet. I'm having a lot of minor fixes for 2.9.3 and 2.10.0 to do. I'll check if this occur on them. If yes, I'll raise priority.

**Comment by leecheromerevilit** [comment]
Hi @btry 

When submitting a form with some missing important fields, the actor field returns NULL on deserializeValue function.

It says "array given, expecting string".

**Comment by leecheromerevilit** [comment]
#1659

**Comment by btry** [comment]
Found 2 PHP warnings

PHP Warning (2): json_decode() expects parameter 1 to be string, array given in /home/tbugier/public_html/glpi-95/plugins/formcreator/inc/fields/actorfield.class.php at line 149
PHP Warning (2): Invalid argument supplied for foreach() in /home/tbugier/public_html/glpi-95/plugins/formcreator/inc/fields/actorfield.class.php at line 151

**Comment by btry** [comment]
Fixed in : 5963666f
