### ISSUE TITLE
Notification on Important Fields missing

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1777]
**Describe the bug**
Missing important field if there's a Date Field on the form. This goes to multiple fields on the forms. I cannot test every fields but I'm sure that the Date field is affecting the Missing Important Notification.

**To Reproduce**
1. Create form with two fields, 1 Actor and 1 Date field
2. Select Actor as important field.
3. Click submit with no data on all fields

**Expected behavior**
Submit the form with missing data on important field. No prompt 

Version: 
GLPI 9.4.5
FormCreator 2.11.0-nightly

**Comment by btry** [comment]
Hi

Is an important field a mandatory field ?

**Comment by leecheromerevilit** [comment]
Hi @btry 

Yes, it's marked as mandatory.

**Comment by btry** [comment]
Hi

The latest revision of the develop branch should solve your issue. Can you check, please ?

**Comment by btry** [comment]
Hi

Having no feedback, I close.
