### ISSUE TITLE
Aucun lieu quand utilisation racine sous arbre

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#1778]
**Describe the bug**
Quand j'utilise un intitulé lieu avec une racine de sous arbre.
Aucun lieu n’apparaît dans la liste.
J'ai essayé de changer la profondeur, sans résultat.

**To Reproduce**
Créer un formulaire avec une question de type intitulé>lieu
Choisir une racine de sous arbre.

**Expected behavior**
Affichage des lieux

**Screenshots**
![image](https://user-images.githubusercontent.com/47602797/82445160-a1e9f580-9aa4-11ea-8623-a8d520c67f32.png)

![image](https://user-images.githubusercontent.com/47602797/82445283-d067d080-9aa4-11ea-872c-24811d8cc64f.png)

![image](https://user-images.githubusercontent.com/47602797/82445310-dd84bf80-9aa4-11ea-92b6-475600aaacb8.png)

Formcreator 2.9.2
GLPI 9.4.6

**Comment by tguichard25** [comment]
Fix working ty

**Comment by btry** [comment]
Hi

Thank you for your feedback
