### ISSUE TITLE
White screen when duplicate a form

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1779]
**Describe the bug**
When I want to duplicate a form, I have a blanck screen. If I go back, the form is created, I don't know if good creation. For example, it's not marked "copy".

Debug mode display an error:
```
PHP Notice: Undefined index: _group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php at line 133

Fatal error: Uncaught GlpiPlugin\Formcreator\Exception\ImportFailureException: failed to find a group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php:135 
Stack trace: 
#0 /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php(946): PluginFormcreatorTarget_Actor::import(Object(PluginFormcreatorLinker), Array, 32) 
#1 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2051): PluginFormcreatorTargetTicket::import(Object(PluginFormcreatorLinker), Array, 39) 
#2 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1514): PluginFormcreatorForm::import(Object(PluginFormcreatorLinker), Array) 
#3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1579): PluginFormcreatorForm->duplicate() 
#4 /var/www/html/glpi/inc/massiveaction.class.php(990): PluginFormcreatorForm::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginFormcreatorForm), Array) 
#5 /var/www/html/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes() 
#6 /var/www/html/glpi/fro in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php on line 135
```
**To Reproduce**
I am not sure, but, I think the problem occurs when a form with a group is affected to tech and the form is exported to another system who don't have this group.
It's remain that the group is not shown, so it's not visible and can't be deleted. The form is broken.

**Expected behavior**
Could delete a bad group (marked in the form but doesn't exists in base.

Version :
GLPI 9.4.5+Form 2.9.1

**Comment by mab18** [comment]
Hi, 
Same with FC 2.9.2

**Comment by btry** [comment]
Hi

It seems that you have a target ticket with a group assigned as an actor (requester, observer or assigned). This group was probably deleted later. 

Could you edit the target ticket and check if you see a group labelled "N/A"  in the actors ?

**Comment by mab18** [comment]
Hi, 
Missing group in the form in target environment is not on the screen, and there is no N/A.

**Comment by btry** [comment]
Hi

Please try this fix and feedback.

**Comment by mab18** [comment]
Bonjour,
J'ai réussi reproduire le cas (ayant pas mal modifié mes formulaires, mon cas de test n'en n'était plus un) : 
J'ai cette erreur sans le patch :
`Fatal error: Uncaught GlpiPlugin\Formcreator\Exception\ImportFailureException: failed to find a group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php:135 Stack trace: #0 /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php(946): PluginFormcreatorTarget_Actor::import(Object(PluginFormcreatorLinker), Array, 37) #1 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2082): PluginFormcreatorTargetTicket::import(Object(PluginFormcreatorLinker), Array, 45) #2 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1541): PluginFormcreatorForm::import(Object(PluginFormcreatorLinker), Array) #3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1606): PluginFormcreatorForm->duplicate() #4 /var/www/html/glpi/inc/massiveaction.class.php(990): PluginFormcreatorForm::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginFormcreatorForm), Array) #5 /var/www/html/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes() #6 /var/www/html/glpi/fro in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php on line 135`
Avec le patch : 
`PHP Notice: Undefined index: _group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php at line 133
Fatal error: Uncaught GlpiPlugin\Formcreator\Exception\ImportFailureException: failed to find a group in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php:135 Stack trace: #0 /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php(946): PluginFormcreatorTarget_Actor::import(Object(PluginFormcreatorLinker), Array, 36) #1 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2082): PluginFormcreatorTargetTicket::import(Object(PluginFormcreatorLinker), Array, 44) #2 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1541): PluginFormcreatorForm::import(Object(PluginFormcreatorLinker), Array) #3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1606): PluginFormcreatorForm->duplicate() #4 /var/www/html/glpi/inc/massiveaction.class.php(990): PluginFormcreatorForm::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginFormcreatorForm), Array) #5 /var/www/html/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes() #6 /var/www/html/glpi/fro in /var/www/html/glpi/plugins/formcreator/inc/target_actor.class.php on line 135`

A noter la 1ère ligne d'erreur ligne qui n'est pas présente sans le patch (ça n'est pas un oubli de copier/coller)

**Comment by btry** [comment]
Apparemment le patch fait son office; mais l'exception devrait être interceptée pour éviter une page blanche.

En tout cas, c'est clair, le groupe n'est pas rtrouvé dans la BDD, ou alors il y a un souci de conversion UUID / ID ou NOM / ID à résoudre.

Il faudrait lire le fichier JSON pour trouver le groupe, puis vérifier en BDD si il existe bel et bien. Si il n'existe pas, l'import devrait échouer, mais l'exception doit être interceptée pour éviter une page blanche.

**Comment by mab18** [comment]
Ce formulaire provient d'un autre environnement (dev), et les groupes de même nom ne sont pas forcément numérotés (id) de façon identique dans la cible, effectivement.
Ca va rendre compliqué l'usage de l'import/export et si ça devient bloquant, cette fonctionnalité bien pratique deviendra inutile dans nombre de cas.

**Comment by btry** [comment]
Bonjour,

Je vois qu'en effet la gestion d'exceptions n'est pas faite dans le cas d'une duplication de formulaire.

Voilà un patch qui devrait rendre l'echec plus "user friendly"

Pouvez-vous l'essayer et me faire un retour ? Notez que le duplicata du formulaire ne devrait plus persister comme c'était le cas avant.

**Comment by mab18** [comment]
Je regarde ;-)

**Comment by btry** [comment]
Ajoutez le 2e commit du fix précédent, et ajoutez également celui-ci: https://github.com/pluginsGLPI/formcreator/pull/1820/commits/2df515bc9e8873e890685b6c4bc067ef5154c7a3

Les groupes manquants devraient arfficher leur ID, et le formulaire dupliqué persistera en BDD, mais renommé de manière explicite.

**Comment by mab18** [comment]
Celui-ci ? https://github.com/pluginsGLPI/formcreator/commit/aaaf7a7fee50dc9bb23f91acd732d9b7c82f54ba

**Comment by btry** [comment]
Non, celui-ci : 4a1ccc1d333581beef91d0e554dc10916c2ccae4

**Comment by mab18** [comment]
Cela me donne ça : 
![image](https://user-images.githubusercontent.com/55535560/84781370-0be3b500-afe7-11ea-991b-aeb37a5aa578.png)
et 
![image](https://user-images.githubusercontent.com/55535560/84781434-1e5dee80-afe7-11ea-9c03-508a1bab9404.png)
Ca me semble parfait ! C'est juste déroutant qu'il affiche un message d'erreur et que ce soit fait quand même, mais ce n'est pas bien grave.
Super !!

**Comment by btry** [comment]
Je vais laisser le mesage d'erreur, ca attierra bien sur le fait que le formulaire ne fonctinnera pas comme voulu. J'espère avoir la possibilité de créer des uuid dans le coeur de GLPI 9.6 pour résoudre cela au mieux.

**Comment by mab18** [comment]
Ah mais je vois que je n'ai pas appliqué https://github.com/pluginsGLPI/formcreator/pull/1820/commits/2df515bc9e8873e890685b6c4bc067ef5154c7a3

**Comment by btry** [comment]
En effet. J'attends votre retour avant de merger ce commit

**Comment by mab18** [comment]
Avec, ça me donne : 
![image](https://user-images.githubusercontent.com/55535560/84782507-629dbe80-afe8-11ea-8dfc-476c0145a5e3.png)
Je suppose que ça doit afficher un id utilisable dans d'autres cas :-)  
Vu que j'ai déjà écrit que c'était super, c'est maintenant excellent ;-) On atteindra l'extraordinaire quand il y aura la traduction :-))

**Comment by mab18** [comment]
Comment il y a pu avoir un ID 0 dans ce formulaire ??

**Comment by btry** [comment]
Pour trouver pourquoi il y a un ID 0, i lfaut vérifier si on a bien un nombre stocké dans le JSON, et éventuellement analyser le formulaire  d'origine, et vérifier le code d'export (dans un autre ticket si on ne veut pas se perdre)

**Comment by mab18** [comment]
Ca pourrait être ceci : 
"_actors": [
                            {
                                "actor_role": 1,
                                "actor_type": 1,
                                "actor_value": null,
                                "use_notification": 1,
                                "uuid": "de574297-91f503...
?

**Comment by btry** [comment]
les UUID figurant dans le .json d'export sont ceux dans la BDD d'où est tiré l'export. Seuls les objets du plugin sont concernés par ces UUID.

Ils servent d'identifiant alternatifs pour ne pas s'appuyer sur des ID ai moment de l'import (ceux-ci pourraient être éjà utilisés). 

Il y a à mon avis d'autres soucis dans l'import, il  ya encore des PR en attente afin de corriger cela.

Je ferme ce ticket, puisque résolu. Merci pour les retours, ils sont appréciables pour améliorer cette partie du plugin.
