### ISSUE TITLE
Full answer description in target ticket

### ISSUE THREAD

**Issue by ghiglesias** [pluginsGLPI/formcreator#1780]
Hi!
When set up a form to create a ticket, the answers in the "content" field is related to IDs, but I requiere to be the "description". Is it possible?
For example in fieldtypes like :
actor
urgency
dropdown
file
glpiselect

![issue](https://user-images.githubusercontent.com/62549779/82617976-18235080-9ba8-11ea-9a50-c9e1f68e3180.png)

I want to see : 
1) Computer name instead of ID 
2) Itilcategory name instead of ID
3) Urgency name instead of ID
4) Actor username instead of ID

I tried ##FULLFORM## and pairs ##QUESTION##-##ANSWER## but I can't reach this function.
Is it possible?

Thanks so much!

**Comment by btry** [comment]
Hi

Which version of Formcreator are you using ?

**Comment by mab18** [comment]
Bonjour,
Y aurait-il possibilité d'un lien avec https://github.com/pluginsGLPI/formcreator/issues/1782 ?

**Comment by ghiglesias** [comment]
> Hi
> 
> Which version of Formcreator are you using ?

apologize the delay

It was an old one, I soled by coding. In new version it is the common function

**Comment by btry** [comment]
Hi @ghiglesias,

This issue was fixed long ago. I tried 2 types of fields, this is OK for me.

If you tried with Formcreator 2.9.2 or 2.10.0 (to be released soon), please show a screenshot of your form.

**Comment by ghiglesias** [comment]
sorry is not an issue, I was using an old version.
apologize
