### ISSUE TITLE
Status is number instead of text in waiting list of forms to validate

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1782]
Hi,
**Describe the bug**
In //a.b.c.d/glpi/plugins/formcreator/front/formanswer.php?criteria[0][field]=5&criteria[0][searchtype]=equals&criteria[0][value]=597&criteria[1][link]=OR&criteria[1][field]=7&criteria[1][searchtype]=equals&criteria[1][value]=mygroups 
When we add status column, we can see "101", "102", "103" in the column instead of text in french "En attente", "Refusé", "Accepté"

**To Reproduce**
Add the column "statut" 

**Expected behavior**
The column status should let see "en attente", "refusé" and "accepté" instead of "101", "102", "103"

**Screenshots**
![2020-05-23 21_25_32-Window](https://user-images.githubusercontent.com/55535560/82738961-14283780-9d3c-11ea-9b75-11282518db7e.png)

**Additional context**
GLPI 9.4.6+FC 2.9.2

**Comment by btry** [comment]
Hi 

Use a copy of you DB with a testing instance of GLPI. On this test instance run an upgrade with the CLI : php scripts/cliinstall.php --force-upgrade.

This might an issue related to the upgrade to 2.9.0 fixed a bit later.

**Comment by mab18** [comment]
Hi, 
Sorry, but it's doesn't correcting.

**Comment by btry** [comment]
Hi,

This issue is not related to #1780

**Comment by leecheromerevilit** [comment]
Hi @mab18 

I fixed mine by adding a block of code on function getSpecificValueToDsiplay of formanswer.class.php. Instead of displaying the icons, words such as (Cancelled, Wating, Disapproved, Accepted) will be displayed. I haven't applied for PR on this one.

`switch ($field) {
         case 'status' :
            // $output = '<img src="' . $CFG_GLPI['root_doc'] . '/plugins/formcreator/pics/' . strtolower($values[$field]) . '.png"
            //              alt="' . __($values[$field], 'formcreator') . '" title="' . __($values[$field], 'formcreator') . '" /> ';]
            if($values[$field] == 100){
               $output = 'Cancelled';
            } else if($values[$field] == 101){
               $output = 'Waiting';
            } else if($values[$field] == 102){
               $output = 'Disapproved';
            } else if($values[$field] == 103){
               $output = 'Accepted';
            }
            return $output;
            break;
      }`

**Comment by btry** [comment]
Hi

Can you try the patch in #1801 ?

**Comment by mab18** [comment]
Bonjour,
Excellente correction !
![image](https://user-images.githubusercontent.com/55535560/84126017-a703ea00-aa3d-11ea-87ec-ba2c1a79021b.png)
