### ISSUE TITLE
Image paste on followup using Service Catalog view

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#1784]
**Describe the bug**

**To Reproduce**
1. Go to service catalog view as Self-Service
2. Create a ticket using a form
3. Add an image on a followup using copy/paste

**Expected behavior**
The image should display

**Screenshots**
![image](https://user-images.githubusercontent.com/2960490/82791892-d4ae3800-9e6e-11ea-9a47-6ea266111a63.png)

**Additional context**
GLPI 9.4.5
FormCreator 2.9.2

**Comment by lolokai** [comment]
up ?

**Comment by btry** [comment]
Bonjour

Pouvez-vous faire un essai avec la branche support/2.10.0 et un environnement de test ?

Je n'ai pas reproduit avec la branche 9.4/bugfixes de GLPI

![image](https://user-images.githubusercontent.com/14139801/84169656-28c53900-aa79-11ea-88b5-18b60e868f3e.png)

**Comment by btry** [comment]
Bonjour

Ce problème devrait être résolu avec Formcreator 2.10 et GLPI 9.5. Je ferme ce ticket
