### ISSUE TITLE
##formcreator.form_validator## affiche "N/A" dans les notifications

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1789]
Bonjour,
**Describe the bug**
Je constate que dans les notifications, ##formcreator.form_validator## est remplacé par N/A dans les notifications courriel au lieu du nom utilisateur valideur.

**To Reproduce**
Créer un formulaire qui demande à être validé, avec une notification lors de la validation (ou de refus). Ce formulaire doit avoir la variable ##formcreator.form_validator##
Valider ou refuser afin d'envoyer une notifications.
Le mails contiendra N/A au lieu du nom du valideur.

**Expected behavior**
Le nom du valideur doit apparaitre au lieu de N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/83114487-497cae80-a0c9-11ea-8feb-a9864f0b2b75.png)
![image](https://user-images.githubusercontent.com/55535560/83114535-5bf6e800-a0c9-11ea-8af0-1d8d7dcc6325.png)

**Additional context**
GLPI 9.4.6+FC 2.9.2

**Comment by btry** [comment]
Bonjour

Je nre reproduis pas sur la branche support 2.10.0; et le code concerné n'a pas changé depuis très longtemps. Il doit y avoir quelque chode de propre à l'utilsiateur validateur.

**Comment by mab18** [comment]
Bonjour,
Effectivement, du code nouveau a dû changer le comportement, je ne peux plus reproduire non plus ce problème avec le même cas de test.

Je clos ce ticket ;-)
