### ISSUE TITLE
Mots clefs de recherche de formulaire

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1791]
Bonjour,
**Is your feature request related to a problem? Please describe.**
Il serait super de pouvoir avoir une zone de mots clefs qui permettraient de chercher le bon formulaire en fonction de ce que cherche l'utilisateur.

**Describe the solution you'd like**
En effet, par exemple d'école, un formulaire qui traite des incidents bureautique, on pourrait saisir dans cette zone, les mots clefs suivants "crash, plantage, blocage, erreur, fatal, freeze, error #191992, 0x09b2200..."etc

**Describe alternatives you've considered**
La zone "description" est visible, cela rend peu clair cette zone pour faire ceci.

**Comment by btry** [comment]
Bonjour

Il est prévu que le concepteur d'un formulaire prenne le temps d'écrire une description lisible par une personne, tout en y insérant les mots clé. 

Efectiveemnt, il peut y avoir des cas il devient compliqué de répondre aux deux besoins en un seul champ. Cependant, le système de recherche ne fonctinne pas très bien, à cause de contraintes du syst-me de recherche de MySQL/MariaDB. Je met de côté ce  besoin pour le moment.

**Comment by mab18** [comment]
Bonjour,
En fait, je viens de constater que je ne savais pas que le moteur recherchait aussi dans le contenu des formulaires.
Du coup, j'ai créé un bloc qui est caché de façon permanente et non conditionné, j'y ajoute un champ de type texte et dans la description de ce champ, je met mes mots clefs.
C'est largement suffisant comme ça.
Ce contournement est tellement efficace qu'il rend cette demande quasi inutile. Je peux la clore si ça peut faire de la place.

Merci @btry

**Comment by btry** [comment]
Bonjour

C'est une bonne idée :+1: et je suis rpeneur d'un peu de place :)
