### ISSUE TITLE
Notification par mail

### ISSUE THREAD

**Issue by lucas693600** [pluginsGLPI/formcreator#1792]
bonjour,
j'ai créer plusieurs formulaires sur GLPI,
Chaque personnes associer aux différents formulaires à la possibilité de le valider à travers un profil validation
Cependant, lors des notifications par e-mail chaque personne ayant le profil valideur reçoit une notification même si la personne n'ai pas associé aux formulaires
Serait-il possible de paramétrer les notifications juste pour les valideurs associés à chaque formulaires?
Comme ça chaque personne responsable d'un formulaire recevra la notification et les autres ne seront pas spammer merci

**Comment by btry** [comment]
see #1793
