### ISSUE TITLE
Show all my forms (Requester)

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1799]
**Describe the bug**
Cannot view all my forms if I use Self-Service profile but can be viewed using Technician profile.

**To Reproduce**
1. Fill up form as Self-Service.
2. Click "All my forms (Requester)"
3. Switch between Technician profile.
4. There you can see the form using Technician profile but not Self-Service.

**Expected behavior**
Both profiles should have the capability to view the forms submitted.

GLPI: v9.4.5
FromCreator: 2.11.0

**Additional context**
I've noticed that when I use Self-Service profile, the query changes from "WHERE `glpi_plugin_formcreator_formanswers`.`requester_id`" to "`glpi_plugin_formcreator_formanswers`.`users_id_validator`"

No changes on the table filters as well as the link for SearchEngine.

**Comment by leecheromerevilit** [comment]
Further investigation shows that on Self Service Privileges, when I unchecked "Validate a Request" and "Validate an Incident" the query did not change to "users_id_validator" instead of "requester_id".

I have no idea yet the reason behind this but an explanation from the devs. will suffice.

**Comment by btry** [comment]
Hi

I'm focusing right now on Formcreator 2.10. Please be patient.

**Comment by leecheromerevilit** [comment]
Sure, np.

Just reporting all bugs that I encountered, including the solution If I have one.

**Comment by leecheromerevilit** [comment]
Update

Just saw the code that overrides the normal Search Engine query. 

With this, when a self-service user has no privileges on "Validate a Request" and "Validate an Incident", The user can view his submitted forms. But if 2 privileges were enabled, the user can view his submitted forms but cannot validate the forms assigned to him.

**Comment by btry** [comment]
Maybe the same as #1755 (in french)

**Comment by btry** [comment]
Hi @leecheromerevilit 

I did some progress on this issue, and I have a question. How can you as a self-service user access to the view "All my forms (requester)" ? There is no link from the service catalog or simplified interface to reach it.

If I work only by reading the code I found  that the code involved in the WHERE you pointed is in plugin_formcreator_getCondition().

I Think that your issue can be solved if I implement a logical OR between the 2 variants of the WHERE clause. When the call to plugin_formcreator_canValidate() returns true, after computing the variable $condition, I should not return, and just concatenate with the string expression in the very last line of plugin_formcreator_getCondition().

If you're agree with that, see the PR #1815 and test it. I did not ran it because I did not reprouced the issue. I believe I was careful enough to not introduce a SQL error.

**Comment by leecheromerevilit** [comment]
Hi @btry 

I just saw the PR and it's still not working on my end. I just happen to saw the cause of the problem. 

So here's how to replicate:
1. Fill up a form using an account that can validate (so plugin_formcreator_canValidate will trigger after)
2. Assign validator as any user aside from the requester.
3. Click "All my forms (requester)" link.
4. Result should have 1 entry but no results found.

This is because the plugin_formcreator_getCondition will return the expected added where clause 
"(`$table`.`users_id_validator` = ". $_SESSION['glpiID'])" at the same time adding the "AND" on the query. Thus return false for the entire Search Query. 

Here's the where clause after clicking the "All my forms (requester)" link.
`WHERE (`glpi_plugin_formcreator_formanswers`.`users_id_validator` = 474) AND ( `glpi_plugin_formcreator_formanswers`.`entities_id` IN ('0') ) AND ( (`glpi_plugin_formcreator_formanswers`.`requester_id` = '474') )`

The solution is adding OR instead of AND after for the plugin_formcreator_getCondition result.

**Comment by leecheromerevilit** [comment]
Hi @btry 

I have no way of changing the logical operator for the result of plugin_formcreator_addDefaultWhere function so my solution is to add the users_id_validator and requester_id on the $condition.

`$condition .= " (`$table`.`users_id_validator` = ". $_SESSION['glpiID'] . " OR `$table`.`requester_id` = ". $_SESSION['glpiID']`

So even if the logical operator is AND, the added condition's logical operator is OR.

Code above was slightly modified to only show forms that belongs to the logged in user (Requester or Validator)

**Comment by btry** [comment]
Hi

Thanks for your investigations. I'll try to reproduce with your latest steps and I'll review the complete query. It os risky to add a logical OR because there is a risk to "escape" from the entities restrictions if any. 

I also think that this issue may occurs in current stable releases.

**Comment by btry** [comment]
Hi @leecheromerevilit 

I created an other PR which cleans up the function involved to this issue. Can you test #1892  and feedback ?

**Comment by leecheromerevilit** [comment]
Hi @btry 

Apologies for the late reply.

Newly added line will result to sql error.
"$condition = " OR `$table`.`users_id_validator` =". $_SESSION['glpiID'];"

Changing OR to ( will solve the problem.

**Comment by btry** [comment]
Hi

OK, maybe I left an inconsistency.

Can you show the complete faulty request from your log, to ensure that your suggestion is correct in a business logic point of view ?

**Comment by btry** [comment]
Hi

I just fixed a problem with similar topic in Formcreator, then I thought a good opportunity to check again this issue. 

I don't reproduce by following the procedure if this comment: https://github.com/pluginsGLPI/formcreator/issues/1799#issuecomment-645311580, and the SQL query looks good to me. Then I close.

It the problem still occurs with a recent version, feel free to open a new ticket.
