### ISSUE TITLE
Ajouter un nouveau type de cible: mail

### ISSUE THREAD

**Issue by Sismic** [pluginsGLPI/formcreator#180]
Bonjour serait il possible d'ajouter comme cible un envoi par mail ? 
Je souhaite utiliser le GLPI pour générer un formulaire de question qui serait envoyer par mail à une BAL.

Qu'en pensez vous ?

**Comment by neeftarah** [comment]
Bonjour,
C'est une des fonctionnalités prévues dès le départ qui n'ont toujours pas été implémentées faute de temps.

Cordialement,
Jérémy

**Comment by juliencheval** [comment]
Bonjour, nous sommes également très interessé par cette fonctionnalité.
Pouvez-vous nous donner un délai pour que cette fonction soit mise en place ? Merci beaucoup

**Comment by btry** [comment]
Bonjour

Un plugin sous souscription apportant cette fonctionnalité sera bientôt disponible. Le besoin est déjà implémenté.
