### ISSUE TITLE
balise <p> à tord dans réponse refus du valideur

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1802]
Bonjour,
**Describe the bug**
Quand un valideur refuse un formulaire, l'utilisateur voit sa réponse avec des balises <p>
**To Reproduce**
Utiliser un formulaire avec validation, refuser la validation, aller en demandeur constater les balises

**Expected behavior**
Les balises ne devraient pas êtres ajoutées, Elles ne sont pas réaffichées en cas de 2ème refus.

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/84161014-17772f00-aa6f-11ea-9b65-c46b8518c22d.png)

**Additional context**
GLPI 9.4.6+FC 2.9.2

**Comment by btry** [comment]
Hi

I reproduce. It appears that when viewing a refused form, a text area is displayed as simple text instead of rich text.

**Comment by btry** [comment]
Bonjour 

Essayez le correctif ci-dessus. Il devrait résoudre le souci

**Comment by mab18** [comment]
Bonjour,

C'est parfait !!

**Comment by mab18** [comment]
Je constate des problèmes avec les balises quand il y a des cadres : 
Je n'ai pas mis de texte, afin de mieux voir : 
![image](https://user-images.githubusercontent.com/55535560/85402937-d1d16080-b55c-11ea-899d-6ddb00978610.png)
