### ISSUE TITLE
Installtion 2.10.0-rc.1

### ISSUE THREAD

**Issue by orderman** [pluginsGLPI/formcreator#1806]
GLPI 9.4.2

bonjour
suite a migration form Creator en 2.10.0-rc.1
pensant que les copie ecran dans les tickets allait fonctionner car vous avez semble t il résolu le pb avec la version précédente (alors que sur ma plateforme ca ne fonctionne toujours pas mais je vais patiente n'étant pas bricoleur )

Il m'est impossible de faire le prévisualisation de formulaire existant ou  venant d'être créé  de plus  un clic sur le menu formulaire m'indique  : file not fond

Lassé je me suis dit qu'en désinstallant / réinstallant le plugin ca fonctionnerait 
mais  quand je veux relancer l'installation j'ai cela

Upgrade glpi_plugin_formcreator_answers (0 seconde)
Table 'glpidb.glpi_plugin_formcreator_answers' doesn't exist
Please, check migration log

J'ai désinstallé supprimé  les fichiers du plugin ,nettoyé et relancé de zéro la réinstallation
même résultat 
J'ai perdu tout le travail que j'avais fait sur cette plateforme de test 
votre version est pourtant compatible 9.4 / 9.5 

cdt

Philippe

**Comment by btry** [comment]
Bonjour

D'abord quelques remarques d'ordre général.

Je vous conseille de passer en GLPI 9.4.6 car le plugin dépend de certains correctifs faits après la version 9.4.2.

Cocnernant les problèmes sur les zones de texte, la RC.1 contient des contournements qui réduiront les bugs, mais ne les supprimeront pas complètement. Il faudra attendre GLPI 9.5 pour cela. Je vous invite d'ailleurs à   la tester et remonter les éventuels bugs. Seul le passage à GLPI 9.5 vous assure une vraie correction des uploads des zones de texte.

En ce qui concerne votre souci d'upgrade, vous semblez avoir un souci bien connu qui est lié à une très ancienne versin du plugin. Il y a plusieurs années, le plugin ne se désinstallait pas correctement et laissait des traces en BDD nottament des tables. Cela perturbe le processus d'install / upgrade qui vérifie la présence de tables pour déterminer comment s'installer.

Si vous faites une installation fraîche, veuillez supprimer toutes les tables glpi_plugin_formcreator_* et les entrées dans glpi_configs ayant context="formcreator". Ensuite réessayez l'installation.

ATTENTION : 
- veillez à faire  un backup de votre BDD avant de la modifier !! 
- testez votre procédure de réparation sur une instance de tests !!

**Comment by btry** [comment]
Bonjour @orderman 

Avez vous pu résoudre votre problème à l'aide des indications que je vous ai données ?

**Comment by orderman** [comment]
Bonjour,

Non. Je n’ai pas suivi les recommandations Je ne suis pas un expert en BDD et autre système Linux
Langage PHP…
Donc aller supprimer des tables et autre manip non merci
D’autre part l’installation de FormCreator n’était pas si ancienne que ca  quelques mois
Je préfère repartir de zéro tant pis
Cette fois je n’oublierai pas de faire un snapshots de ma VM avant mise a jour

Je suis donc en train de remonter une plateforme de test
A partir de ma prod.

Je vous tiendrai informé  des que tout sera en place pour test
Merci pour tout

Cdt


De : btry <notifications@github.com>
Envoyé : lundi 22 juin 2020 11:14
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : LAFOREST Philippe <LAFOREST.P@mipih.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Installtion 2.10.0-rc.1 (#1806)


Bonjour @orderman<https://github.com/orderman>

Avez vous pu résoudre votre problème à l'aide des indications que je vous ai données ?

**Comment by btry** [comment]
Bonjour

N'ayant pas de retour, je ferme le ticket.
