### ISSUE TITLE
Error Message to install : You must run vendor/bin/robo build:fa-data in the directory of the plugin

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#1807]
Hello,

I would like to test your new version 

GLPI 9.5 test
Formcreator release 2.10.0-rc1

I have copied the directory, renamed it and I have this message to activate the plugin

"You must run vendor/bin/robo build:fa-data in the directory of the plugin"

Thank you for your help

![image](https://user-images.githubusercontent.com/30655170/84389213-03116e80-abf6-11ea-9dcf-10bf7ea2a553.png)

**Comment by btry** [comment]
Hi

You probably downloaded the ZIP archive from the source code repository or the source code joint to the published release. 

Download instead the release : https://github.com/pluginsGLPI/formcreator/releases/download/v2.10.0-rc.1/glpi-formcreator-2.10.0-rc.1.tar.bz2

**Comment by yalgva** [comment]
Thank you it works now
