### ISSUE TITLE
Sous formulaire

### ISSUE THREAD

**Issue by mkael29** [pluginsGLPI/formcreator#181]
Bonjour,
serait-il possible d'avoir la possibilité d'ouvrir un sous-formulaire suivant la valeur d'un autre champs ou de l'entité de l'utilisateur?

**Comment by neeftarah** [comment]
Bonjour,

actuellement non.
Il est possible, cependant, d'afficher certains champs en fonction de la valeur d'un champs et donc, pourquoi pas, de "simuler un sous-formulaire" en fonction de la valeur d'un champ.
Il n'y a en revanche rien pour les entités si ce n'est de créer des formulaires différents pour les différentes entités.

Cordialement,
Jérémy

**Comment by mkael29** [comment]
Bonjour,

mon besoin c'est que l'utilisateur sélectionne la société pour lequel il fait le formulaire en sélectionnant une entité dans la liste déroulante Objet GLPI--Entités. Seulement actuellement la liste affiche toutes les entités de la base et pas seulement les entités sur lequel l'utilisateur a des droits.
Pouvez-vous faire comme les autres Objets GLPI, c'est à dire mettre une gestion des droits sur les entités?

Cordialement
