### ISSUE TITLE
error on first display of formcreator

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#1810]
glpi 9.5 rc yesterday
formcreator yesterday rc1

![image](https://user-images.githubusercontent.com/30655170/84471525-ce4cf800-ac85-11ea-9e2e-fc013744f5b0.png)

Hello
I succeed to install it and activate it.

Configuration is ok

Form page is 404

Thank you for your help

**Comment by btry** [comment]
Hi

It works well for me, I checked the release archive and the file is present, as it should. Could you check in your instance if the file glpi/plugins/formcreator/front/formlist.php is present ?

**Comment by yalgva** [comment]
Yes it is
![image](https://user-images.githubusercontent.com/30655170/84482380-e9286800-ac97-11ea-9337-a39859415196.png)

**Comment by btry** [comment]
Then there is maybe a problem in the configuration of your http server ? A rewrite rule or something like that ?

You may enable the debug mode of the server to see which file in your FS is associated to this URL.

**Comment by yalgva** [comment]
I don't have any rewrite rule, however, I have seen that
http://glpi03.latour.ch/95test/**95test**/plugins/formcreator/front/formlist.php 

the good line would be http://glpi03.latour.ch/95test/plugins/formcreator/front/formlist.php

the 95test directory is doubled

**Comment by yalgva** [comment]
Same issue with http://glpi03.latour.ch/95test/plugins/formcreator/**95test**/plugins/formcreator/plugins/formcreator/front/reservationitem.php

**Comment by btry** [comment]
Ok, I think this is related to #1795 

I'll search quickly a fix. Stay tuned.

**Comment by btry** [comment]
Hi

Please apply the following fix and feedback 3ba9748f

**Comment by btry** [comment]
Here is the 2nd fix for the other bad URLs : 6869b646

**Comment by btry** [comment]
Bonjour

Les corectifs  ont ils résolu votre problème ?

**Comment by btry** [comment]
Hi

The release 2.10.1 should solve your problem. Can you feedback ?

**Comment by btry** [comment]
This issue was bery likely related to path problems when the plugin is instaled from the new marketplace. Got positive feedbacks with the versin 2.10.1. I think I can close.

If you still have problems with latest  release, please open a new ticket.
