### ISSUE TITLE
 [formcreator 2.9.2 ] Liste des catégories affichées. GLPI 9.4.6

### ISSUE THREAD

**Issue by falco2001** [pluginsGLPI/formcreator#1811]
Bonjour,
en post-only il y a maintenant la liste de toutes les catégories qui s'affiche. Dans les anciennes versions il y avait que celles de l'entité. Comment corriger ceci dans le code. Merci
PS : ceci est bloquant vu que l'on a 30 catégories; Je regarde dans le code si je peux le modifier

**Comment by charleneauger** [comment]
Bonjour @falco2001 ,
Nous avons rencontré le même problème sur nos formulaires (liste complète des catégories sans filtre d'entité). J'ai effectué une modification dans le code et de mon côté ça fonctionne. Je ne sais pas si c'est "propre" mais je vous le partage, ça vous aidera en attendant qu'il corrige le bug : 
Dans inc/fields/dropdown.class.php - ligne 168
```php
                 // code ajouté
                  $forms = new PluginFormcreatorForm();
                  $form = $forms->find("id = " .$_GET['id']);

                  $entities = getSonsOf('glpi_entities', $form[$_GET['id']]['entities_id']);
                  $son = [];

                  foreach($entities as $entity) {
                     $son[(int) $entity] = (int) $entity;
                  }

                  $dparams['entity'] = $son;
               
                  /*switch ($decodedValues['show_ticket_categories']) {
                     case 'request':
                        $dparams_cond_crit['is_request'] = 1;
                        break;
                     case 'incident':
                        $dparams_cond_crit['is_incident'] = 1;
                        break;
                     case 'both':
                        $dparams_cond_crit['OR'] = [
                           'is_incident' => 1,
                           'is_request'  => 1,
                        ];
                        break;
                     case 'change':
                        $dparams_cond_crit['is_change'] = 1;
                        break;
                     case 'all':
                        $dparams_cond_crit['OR'] = [
                           'is_change'   => 1,
                           'is_incident' => 1,
                           'is_request'  => 1,
                        ];
                        break;
                  }*/
```

**Comment by btry** [comment]
Bonjour

Je vais examiner votre correction bientôt. En  lecture rapide, c'est proche de ce qu'il faut faire.

**Comment by phamorais** [comment]
@charleneauger u solution is in Formcreator?


In Formcreator, in inc / fields there is no dropdown.class.php

![image](https://user-images.githubusercontent.com/35368369/84553091-6203e000-ace9-11ea-82c0-506a06f0dace.png)


Did you mean "dropdownfield.class" ?

I say this because I have the same problem, and I need to correct it urgently

**Comment by phamorais** [comment]
Hi, @charleneauger , dont work for me :(

Form v2.9.2

**Comment by btry** [comment]
Hi

The fix must collect the active entities of the current user, and filter the itemtype of the dropdown with this, only when the itemtype has a entities_I'd column.

The following may contain errors, because I don't have access to the source code for now. If you use those informations, please double check with the source code.

CommonDBTM provides a method isEntityAsssign(). It tells if you need to filter with active entities.

There is a method in Session which gives the active entities of the currently connected user.

I hope this will help to find a fix if someone handle this bug before me. I'll try to allocate some time next week

**Comment by btry** [comment]
Bonjour

@falco2001 : je suppose que vous utiliser la versin 2.9.x ou 2.10.0-rc.1 ?

@charleneauger : je ne comprends pas pourquoi vous avez désactivé le filtrage selon le type de catégorie (is_request, is_incident, ...). Y a-t-il un problème avec cette partie ?

le filtrage par entité est déjà réalisé dans le code, Pour étudier le problème j'ai besoin de reproduire une situation semblable à la vôtre. 

- une arborescence d'entités simple
- un utilsiateur (qui sera le demandeur) dans une de ces entités
- une structure de catégories réparties dans les différentes entités
- (à priori trivial) un formulaire avec une questin pout choisir une catégorie de ticket.

**Comment by phamorais** [comment]
@btry 


I have the same situation as him and I am also in error. (Form v292).

I upgraded but had to rollback

The attached image is the environment with the forms filtered by entity

![image](https://user-images.githubusercontent.com/35368369/84581681-4583a880-adba-11ea-86cc-abc54945eaee.png)


The image below is the same environment, after upgrading to v292. Note that there is no category filter.

![image](https://user-images.githubusercontent.com/35368369/84581732-d65a8400-adba-11ea-8e8e-8754cbd7e135.png)

As for your question in the previous comment

" je ne comprends pas pourquoi vous avez désactivé le filtrage selon le type de catégorie (is_request, is_incident, ...). Y a-t-il un problème avec cette partie ?"

The option is good, but it shouldn't be Mandatory.
For example, I use the question with the category. And I inform in the category if he will use the "Requisition" or "incident" ticket template. This new option on the form, prevents me from using the native GLPI feature, and it will be a lot of work to change all forms.

I commented on this on partner support : https://support.teclib.com/front/ticket.form.php?id=19772&forcetab=Ticket$2.

In my view, the option should be Optional, not mandatory.

**Comment by falco2001** [comment]
Merci à vous.
Je n'ai pas encore testé sur ma version 2.9.X
La solution de @charleneauger   fonctionnelle ? ou faut-il faire le correctif https://github.com/falco2001/formcreator/commit/2b8b7f12ff272fe538c0ab3a486bc6b97479e534 de @btry
Merci pour votre réactivité.

**Comment by phamorais** [comment]
Hi @falco2001 
In my version v292, the solucion of @charleneauger dont work.

**Comment by btry** [comment]
Hi

It appears that you're not all talking about the same issue.

Bonjour

Il semble que vous ne parlez pas tous du même problème.

**Comment by phamorais** [comment]
@btry 
HI

I think we are, yes, haha. The problem in question is that the categories of the form do not obey the visualization of the forms available in the entity

**Comment by btry** [comment]
Hi

Please, @charleneauger and @falco2001 can you both explain where you find a problem ? is it in a question of type dropdown > ticket category or is it in the categories displayed by the service catalog ?

**Comment by falco2001** [comment]
Bonjour, le problème est celui mentionné par @phamorais  qui montre en post-only aucune catégorie filtrée.
La solution de @charleneauger  ne fonctionne pas chez moi en V292

**Comment by btry** [comment]
Bonjour

@falco2001 : Du coup ce que propose @charleneauger ne correspond pas à votre problème.

@charleneauger je vous invite à ouvrir un ticket différent pur décrire votre problème, et je verrai comment votre proposition de correction peut être utilisée.

@falco2001 : pourriez vous utiliser Toolbox::logWarning() pour enregistrer la requête SQL générée dans PluginFormcreatorCategory::getCategoryTree() ?

Voilà un diff pour appliquer facilement la ligne de debug

```diff
diff --git a/inc/category.class.php b/inc/category.class.php
index 322a2586..a956a85b 100644
--- a/inc/category.class.php
+++ b/inc/category.class.php
@@ -144,6 +144,7 @@ class PluginFormcreatorCategory extends CommonTreeDropdown
          'ORDER' => ["level DESC", "name DESC"],
       ];
       $result = $DB->request($request);
+      Toolbox::logWarning($result->getSQL());
 
       $categories = [];
       foreach($result as $category) {
```

Après avoir reproduit le bug en self-service nous pourrons vérifier si les restrictions d'entités sont corectes.

**Comment by falco2001** [comment]
`glpiphplog.WARNING: PluginFormcreatorCategory::getCategoryTree() in /var/www/html/plugins/formcreator/inc/category.class.php line 148
SELECT `id`, `name`, `plugin_formcreator_categories_id` AS `parent`, `level`, (SELECT COUNT(*) AS count FROM `glpi_plugin_formcreator_forms` WHERE `is_active` = '1' AND `is_deleted` = '0' AND `glpi_plugin_formcreator_forms`.`plugin_formcreator_categories_id` = glpi_plugin_formcreator_categories.id AND `language` IN ('fr_FR', '', '0', NULL) AND (`access_rights` != '2' OR `id` IN (SELECT `plugin_formcreator_forms_id` FROM `glpi_plugin_formcreator_forms_profiles` WHERE `profiles_id` = '1'))) + (SELECT COUNT(*) AS count FROM (SELECT DISTINCT `glpi_knowbaseitems`.*,
 `glpi_knowbaseitemcategories`.`completename` AS category,
 COUNT(`glpi_knowbaseitems_users`.`id`)
 + COUNT(`glpi_groups_knowbaseitems`.`id`)
 + COUNT(`glpi_knowbaseitems_profiles`.`id`)
 + COUNT(`glpi_entities_knowbaseitems`.`id`) as visibility_count
 
 
 FROM `glpi_knowbaseitems`
 LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_groups_knowbaseitems` ON (`glpi_groups_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_knowbaseitems_profiles` ON (`glpi_knowbaseitems_profiles`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_entities_knowbaseitems` ON (`glpi_entities_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`)
 LEFT JOIN `glpi_knowbaseitemcategories`
 ON (`glpi_knowbaseitemcategories`.`id`
 = `glpi_knowbaseitems`.`knowbaseitemcategories_id`)
 WHERE (`glpi_knowbaseitems`.`users_id` = '9753' OR `glpi_knowbaseitems_users`.`users_id` = '9753' OR (`glpi_groups_knowbaseitems`.`groups_id` IN ('14', '122') AND (`glpi_groups_knowbaseitems`.`entities_id` < '0' OR ((`glpi_groups_knowbaseitems`.`entities_id` IN ('7') OR (`glpi_groups_knowbaseitems`.`is_recursive` = '1' AND `glpi_groups_knowbaseitems`.`entities_id` IN ('0')))))) OR (`glpi_knowbaseitems_profiles`.`profiles_id` = '1' AND (`glpi_knowbaseitems_profiles`.`entities_id` < '0' OR (((`glpi_knowbaseitems_profiles`.`entities_id` IN ('7') OR (`glpi_knowbaseitems_profiles`.`is_recursive` = '1' AND `glpi_knowbaseitems_profiles`.`entities_id` IN ('0'))))))) OR ((`glpi_entities_knowbaseitems`.`entities_id` IN ('7') OR (`glpi_entities_knowbaseitems`.`is_recursive` = '1' AND `glpi_entities_knowbaseitems`.`entities_id` IN ('0'))))) AND (`glpi_knowbaseitems`.`is_faq` = '1') AND (`glpi_knowbaseitems`.`is_faq` = 1)
 GROUP BY `glpi_knowbaseitems`.`id`
 ) as faqs WHERE (faqs.knowbaseitemcategories_id = glpi_plugin_formcreator_categories.knowbaseitemcategories_id) AND (`faqs`.`knowbaseitemcategories_id` != '0')) as items_count FROM `glpi_plugin_formcreator_categories` ORDER BY `level` DESC, `name` DESC `

**Comment by falco2001** [comment]
Bonjour, pour résoudre temporairement  le problème, j'ai copié le category.class.php b/inc/category.class.php de l'ancienne version et c'est ok . Pas propre !!

**Comment by btry** [comment]
Pouvez vous préciser la version exacte d'où provient le fichier repris ? Si le patch précédent est encore applicable, vous pouvez aussi partager la requête en veillant à être dnas la même entité que pour l'essai précédent. Cela devrait rendre la comparaison plus évidente.

**Comment by falco2001** [comment]
Version 2.8.0 de category.class.php du plug-in

**Comment by btry** [comment]
Ok, je n'étais pas remonté si loin. Le patch ne devrait plus s'appliquer tel quel pour obtenir la requête SQL.

**Comment by btry** [comment]
Bonjour

J'ai trouvé un problème lors de l'ajout de la restriction d'entités dans la requête cherchant les catégories à afficher.

Pouvez-vous essayer le correctif ci dessus et me faire un retour ?

De ce que j'ai vu, le souci est apparu dans al version 2.9.0.

**Comment by falco2001** [comment]
Bonjour,
il faut que je supprime la ligne $dbUtils->getEntitiesRestrictCriteria($form_table, "", "", true, false),
je pense ne pas avoir compris ?
Merci

**Comment by btry** [comment]
Bonjour,

Non. Il faut juste encadrer l'appel à cette méthode par des crochets. Regardez bien, ils sont mis en surbrillance dans la ligne à fond vert du diff.

**Comment by phamorais** [comment]
@btry 

After apply https://github.com/pluginsGLPI/formcreator/pull/1824/commits/fd9f917e3c689a589452c565ffe2623655cc1dd6

Works for me.

After applying the category it was filtered.

before applying the correction

![image](https://user-images.githubusercontent.com/35368369/85036579-b03a3880-b15a-11ea-9cb6-43d2e7f961ef.png)

after applying the correction

![image](https://user-images.githubusercontent.com/35368369/85036722-d9f35f80-b15a-11ea-9477-15a1f18ba7a6.png)

**Comment by phamorais** [comment]
@btry 

It is not related to this correction.

MAs checked that by clicking on the name of the entity, and I expected to see the list of entities.

By clicking on the list of entities

![image](https://user-images.githubusercontent.com/35368369/85037443-c09ee300-b15b-11ea-8eab-c6a6e12df536.png)


The list of entities is not displayed

![image](https://user-images.githubusercontent.com/35368369/85037554-ea580a00-b15b-11ea-9c8b-b1e82f9118ea.png)

**Comment by falco2001** [comment]
Bonjour,
je ne trouvais pas [https://github.com/pluginsGLPI/formcreator/commit/fd9f917e3c689a589452c565ffe2623655cc1dd6](url). Je ne sais pas où le trouver sans connaître ce lien !!
Après la modification tout est ok !!  merci

**Comment by btry** [comment]
Merci à vous tous pour les retours. Je fusioinne pour les prochaines versions.
