### ISSUE TITLE
[2.10.0-RC1] New GLPI 9.5 object

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1816]
A GLPI object type question, do not list the new device type "Passive Object" of GLPI 9.5

**Comment by btry** [comment]
Hi,

Please, try the above patch

**Comment by jvergacas** [comment]
Hi @btry 

Thanks for the feedback, the patch partially solved the issue, it is still missing to associate the equipment with the ticket.

**Comment by btry** [comment]
I dont have the source code with me for now, but I believe that your user might not have the right to associate this type with a ticket. Please check this un his profile and feedback.

**Comment by jvergacas** [comment]
Thanks @btry

The problem is in GLPI 9.5, which does not allow associating the new device with a ticket.

**Comment by btry** [comment]
You may create an issue in the glpi project, maybe the change will be accepted early enough to be included in the final release of GLPI 9.5

**Comment by jvergacas** [comment]
I did it.

**Comment by jvergacas** [comment]
Thanks

**Comment by btry** [comment]
Hi

I'll merge the PR. It is up to GLPI to allow to link this type to a ticket. With this PR you can show the name of the item in a ticket.

**Comment by jvergacas** [comment]
Thanks
