### ISSUE TITLE
[2.11] Glpi object question not working

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#1819]
**Describe the bug**
The inputs for "GLPI object" questions are not displayed:
![image](https://user-images.githubusercontent.com/42734840/84760770-cca66b80-afc8-11ea-91d8-d06c0f5df27a.png)

![image](https://user-images.githubusercontent.com/42734840/84760675-a8e32580-afc8-11ea-9400-a99f5de371d1.png)

**To Reproduce**
1. Create a form
2. Add a "GLPI object" question
3. Display the form

**Expected behavior**
The input should be displayed.

**Desktop (please complete the following information):**
- Firefox

**Comment by leecheromerevilit** [comment]
PluginFormcreatorGlpiselectField class extends PluginFormcreatorDropdownField. 

Upon checking, dropdown also shows empty field.

Hi @AdrienClairembault , can you check on your end if you have the same issue on dropdown fields. 

GLPI 9.4.5
FC 2.11

**Comment by btry** [comment]
Hi. I reproduced. The fix is pushed in develop: a2633082

**Comment by AdrienClairembault** [comment]
Looks good to me after rebase :+1:
