### ISSUE TITLE
Pas de mail pour le valideur

### ISSUE THREAD

**Issue by ChristopheG77** [pluginsGLPI/formcreator#182]
Bonjour

Je ne sais pas si c'est un bug ou pas mais je rencontre un soucis sur mon install (GLPI 0.90.1 / 1.3.3)
Lors de la création d'une demande via le formulaire avec choix d'un valideur, il n'y a pas d’émission de mail à destination du valideur, est ce normal ?

Merci de votre retour

**Comment by neeftarah** [comment]
Bonjour,

Non ce n'est pas normal. Sauf si vous avez désactiver les notification ou que le validateur en question n'a pas d'adresse e-mail.

Pouvez-vous me confirmer que les autres notifications partent bien et que le valideur à bien une adresse e-mail ?

Je regarde de mon coté si je trouve un soucis à ce niveau.

Cordialement,
Jérémy

**Comment by ChristopheG77** [comment]
Bonjour

toutes les notifications fonctionne et les utilisateurs ont bien une
adresse mail

Le 10 février 2016 à 12:32, Jérémy MOREAU <notifications@github.com> a
écrit :

**Comment by neeftarah** [comment]
Bonjour,

De mon coté, je n'ai rien trouver de particulier, la notification de validation part bien.

Toutefois, cette notification doit être configurer et activé (**Configuration > Notifications > Notifications > "Un formulaire est en attente de validation"**).

De plus, depuis GLPI 0.85, les notifications sont mises en liste d'attente et envoyées par une tâche planifiée avec un quota maximum. Vous pouvez vérifier les notifications en attente dans **Administration > File d'attente des courriels**

Cordialement,
Jérémy

**Comment by ChristopheG77** [comment]
Super tu me fais découvrir une fonction que je ne connaissais pas,
effectivement les mail était bloqué en file d'attente

Merci pour ton aide

Le 10 février 2016 à 12:42, Jérémy MOREAU <notifications@github.com> a
écrit :
