### ISSUE TITLE
Erreur SQL dans les logs

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1827]
Bonjour,
Je constate cette erreur dans les logs, je ne sais pas pourquoi :-/
**Describe the bug**
```
[2020-06-19 15:37:43] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: DELETE `glpi_plugin_formcreator_conditions` FROM `glpi_plugin_formcreator_conditions` WHERE (`plugin_formcreator_questions_id` = '378' OR `show_field` = '378')
  Error: Unknown column 'show_field' in 'where clause'
  Backtrace :
  inc/dbmysql.class.php:1055
  plugins/formcreator/inc/question.class.php:751     DBmysql->delete()
  inc/commondbtm.class.php:1685                      PluginFormcreatorQuestion->post_purgeItem()
  plugins/formcreator/front/question.form.php:71     CommonDBTM->delete()
```

Elle est présente plusieurs fois 

**Additional context**
GLPI 9.4.6+FC 2.9.2

**Comment by btry** [comment]
Hi

I see : you deleted a question, and this event truggers deletion of conditions attached to it. The SQL request was not updated after a schema change.

**Comment by mab18** [comment]
Bonjour,

Au vu de votre réponse, alors c'est peut-être lié au bug  https://github.com/pluginsGLPI/formcreator/issues/1779 
En effet, quand j'ai dupliqué, mais sans en avoir fait de trace pour cette fin, il me manquait justement toute une partie du formulaire...

Je ne vois que cette piste pour l'instant.

**Comment by btry** [comment]
Cela a pu arriver quand vous avez testé le patch qui détruit un formulaire mal dupliqué. Dans ce cas, les questions sont effacées provoquant un effacement des conditions.

Si vous n'avez pas encore appliqué le patch, le bug doit être reproductible en effaçant une question d'un formulaire manuellement.

**Comment by mab18** [comment]
Exactement alors, c'est très certainement ça. Ca s'est produit dans ces moments là, je note tout ce que je fais afin de savoir ce qui produit quoi, mais là, je n'avais pas de lien direct, juste temporel.
Et j'ai appliqué le patch :-/

**Comment by btry** [comment]
Vous pouvez retirer un patch en exécutant la même commande patch et en ajoutant l'argument **--reverse**

**Comment by mab18** [comment]
J'ai modifié le code directement. Je ne sais pas faire le patch :-/
Je constate qu'il me manque des briques de connaissances bien utiles

**Comment by mab18** [comment]
Du coup, je pense qu'on peu clore cet incident ?

**Comment by btry** [comment]
Je viens de trouver un autre souci dans cette partie. C'est maintenant bien corrigé et mergé.

Merci pour les retours.

**Comment by mab18** [comment]
... d'accord, c'est quel correctif ?

**Comment by btry** [comment]
Celui-ci: https://github.com/pluginsGLPI/formcreator/commit/22f687396d97de524e7019c77d8969a570243f98

Quand on supprime une question elle peut être liée à uen condition de deux manières :
- la question visible en fonction d'une condition
- la question est utilisée pour calculer la visibilité d'une autre question

Il faut evidemment supprimer la relation dans les deux cas, quand une question est effacée.
