### ISSUE TITLE
Impossible d'affecter un groupe en Demandeur d'un ticket

### ISSUE THREAD

**Issue by jpegli** [pluginsGLPI/formcreator#1829]
Version Plugin : 9.2.1
Version GLPI : 9.4.6

**Describe the bug**
Dans la cible d'un formulaire, je ne peux pas ajouter en Demandeur un groupe depuis une question. Je n'ai aucun pb pour l'Observateur ou Attribué à.

**To Reproduce** : depuis une cible de type ticket
1. Appuyer sur "Demandeur +"
2. Sélectionner "Groupe depuis la question"
3. Sélectionner le champ correspondant à la question et appuyer sur "Ajouter" (en l’occurrence "Référent Client pour les tickets")
4. Cela affiche "Groupe depuis la question "N/A"
Si je fais la même opération en voulant rajouter en Observateur, j'ai un autre affichage "Groupe depuis la question "Référent Client pour les tickets"

**Screenshots**
![Capture](https://user-images.githubusercontent.com/60389004/85292453-2fea3f00-b49c-11ea-9d01-ac88622ea302.PNG)

Merci pour votre aide.

**Comment by btry** [comment]
Bonjour

Utilsiez un environnement de test pour tester la version 2.9.2. De mémoire, ce bug est résolu.

Après upgrade vous devrez détruire cet acteur demandeur et le recréer.

**Comment by jpegli** [comment]
Merci bcp.

**Comment by btry** [comment]
Bonjour

l'ajout du label "need feedback" a dû se croiser avec votre dernier commentaire. Je suppose que votre problème est résolu. Si ce n'est pas le cas, merci de tester avec la toute dernière version du plugin, et ennsuite, si le problème persiste, d'ouvrir un novueau ticket.
