### ISSUE TITLE
Technicien affecté lors de la génération d'un ticket

### ISSUE THREAD

**Issue by Zopla** [pluginsGLPI/formcreator#183]
Bonjour
je teste actuellement la version 0.90-1.3 du plugin sur une version GLPI 0.90.1.
Je constate que quand je génère un ticket via le formulaire, un technicien est affecté automatiquement au ticket généré et ce technicien est la personne qui a installé le plugin, alors que j'ai par ailleurs choisi un groupe d'affectation spécifique. Je précise que je n'utilise pas de gabarit.
Est-ce qu'il y a une option particulière pour que le nom de ce technicien n'apparaisse pas dans le formulaire généré?
Merci

**Comment by neeftarah** [comment]
Bonjour,

Les acteurs d'un ticket sont définis dans les "destinations" d'un formulaire.
Par défaut, Formcreator n'ajoute aucun technicien !

Un technicien peut être affecté automatiquement pour les raisons suivantes :
* Gabarit (vous avez obligatoirement un gabarit par défaut, mais qui n'est initialement pas configurer pour ça)
* Règles
* Affectation automatique des entités (responsable technique de l'ordinateur ou de la catégorie de ticket)

Cordialement,
Jérémy
