### ISSUE TITLE
Balises </div> présentes avec tableaux et aussi sans tableaux

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1832]
**Describe the bug**
Je refais quelques tests pour valider globalement des fonctionnalités et je constate qu'il y a des balises </div> qui apparaissent quand des tableaux sont dans le formulaire.

[Edit]
Je constate que sans tableau, il y a quand même des balises qui apparaissent : 
![image](https://user-images.githubusercontent.com/55535560/85407129-17912780-b563-11ea-8b21-54d859c6c87d.png)
Je ne sais pas pourquoi ça se met en blanc, et on peut voir un "< /span>" en plus des "< /div>".
Je n'ai aucun formatage dans la description du formulaire, juste des sections.
Il semble que cela arrive quand il y a quelques sections, je n'arrive pas à comprendre ce qui déclenche le bug.
Autre test : 
![image](https://user-images.githubusercontent.com/55535560/85411019-1c0c0f00-b568-11ea-8988-e45d41e6e689.png)
[/Edit]
[Edit2]
J'ai trouvé ! J'ai copié collé la description dans Word, en affichant les codes de formatage : 
![image](https://user-images.githubusercontent.com/55535560/85411899-3eeaf300-b569-11ea-9f79-3b66e0ac9b16.png)
J'ai effectivement fait des [MAJ]+[Entrée] et des [Entrée]
[/Edit2]

**To Reproduce**
Créer un formulaire avec des tableaux, y insérer quelque champs, même non remplis.
Faire fonctionner le formulaire afin de créer un ticket.
Je n'ai que ça dans mon formulaire :
 ```
##question_269## demandée : ##answer_269##
##question_270## ##answer_270##
##question_355## ##answer_355##
##question_273## ##answer_273##
##question_274## ##answer_274##
##question_356## ##answer_356## ##question_357## ##answer_357##
##question_358## ##answer_358## ##question_359## ##answer_359##
##question_275## ##answer_275##
##question_276## ##answer_276##
##question_277## ##answer_277##
##question_278## ##answer_278##
##question_279## ##answer_279##
```

**Screenshots**
Traitement du ticket : 
![image](https://user-images.githubusercontent.com/55535560/85403627-0265ca00-b55e-11ea-83df-88cf0383b191.png)
Entête du ticket : 
![image](https://user-images.githubusercontent.com/55535560/85403678-15789a00-b55e-11ea-8da5-f9e3d40416b6.png)

**Additional context**
GLPI 9.4.6+FC 2.9.2+qq correctifs

**Comment by mab18** [comment]
En supprimant tous les [MAJ]+[Entrée] par des [Entrée], j'ai maintenant : 
![image](https://user-images.githubusercontent.com/55535560/85414109-f84ac800-b56b-11ea-9086-571ceee6f0ed.png)

**Comment by mab18** [comment]
C'est traduit comme ça dans la table glpi_plugin_formcreator_targettickets : 
(J'ai mis en forme pour une meilleure lecture)
```
<div><span style="background-color: #ffffff;">##question_269## demandée : ##answer_269##</span></div>
<div><span style="background-color: #ffffff;">##question_270## ##answer_270##</span></div>
<div><span style="background-color: #ffffff;">##question_355## ##answer_355##</span></div>
<div> </div>
<div><span style="background-color: #ffffff;">##question_273## ##answer_273##</span></div>
<div><span style="background-color: #ffffff;">##question_274## ##answer_274##</span></div>
<div> </div>
<div><span style="background-color: #ffffff;">##question_356## ##answer_356## ##question_357## ##answer_357##</span></div>
<div><span style="background-color: #ffffff;">##question_358## ##answer_358## ##question_359## ##answer_359##</span></div>
<div> </div>
<div><span style="background-color: #ffffff;">##question_275## ##answer_275##</span></div>
<div><span style="background-color: #ffffff;">##question_276## ##answer_276##</span></div>
<div><span style="background-color: #ffffff;">##question_277## ##answer_277##</span></div>
<div><span style="background-color: #ffffff;">##question_278## ##answer_278##</span></div>
<div><span style="background-color: #ffffff;">##question_279## ##answer_279##</span></div>
<div> </div>
```

**Comment by mab18** [comment]
J'ai retiré toutes les balises < span> et < /span> en éditant directement la table, je n'ai plus le problème de la balise <p> et </p>
Je n'ai aucune idée du pourquoi ça m'a mis un fond en blanc.
Avec l'éditeur du plugin, j'ai ajouté du gras sur certaines zone, le problème ne réapparaît pas.

Je suppose qu'il y a un bug dans la gestion des SPAN et aussi dans le généré avec [MAJ]+[Entrée] par des [Entrée] (je n'ai pas de cature, mais je peux la faire).

**Comment by btry** [comment]
Bonjour

J'ai reformaté la partie HTML pour avoir un (encore) meilleur rendu. 

Quand le plugin génère un ticket, le texte riche (donc HTML) passe dans une librairie assez pénible à gérer. Tant qu'elle sera là, il sera souvent impossible de résoudre des problèmes de ce genre. Plusieurs tickets on déjà été traités ces dernières années à ce sujet.

Vous pouvez éditer le code HTML directement depuis le plugin : la zone de texte permet d'aficher et éditer le code HTML corespondant à son contenu. C'est un peu mieux que de modifier directement la table.

Je mets ce ticket en suspens car j'ai énormément de choses à faire autour de ce plugin pour le moment.

**Comment by mab18** [comment]
Bien vu le bouton "code source" !!!! 👍 

Merci

**Comment by btry** [comment]
Bonjour

Si l'onglet "code source" a résolu la question, peut on fermer le ticket ?

**Comment by mab18** [comment]
Bonjour,
Je reviens de congés, désolé pour le délai,
Je reprends ce contenu...
Je viens de tester, le problème est toujours là le ticket est créé avec des balises "</div>" et uniquement celle-ci. 
On les voit comme dans ma copie d'écran. Pour se débarrasser du problème, il faut donc aller modifier le code source et supprimer les nombreuses balises bizarres et sorties de nulle part.
du style `<p style="color: #000000; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">`
Une fois supprimé ce code, le problème n'apparait plus, mais perdure. Si j'avais besoin de formater avec du code, ça serait sans doute problématique.

On peut admettre que l'unique possibilité par édition du code permet de faire disparaître la conséquence de ce bug.
Même si cette possibilité n'est pas solution et mais un contournement, on peut clore ce ticket. ;-)

**Comment by btry** [comment]
Bonjour

Il n'y a pas de solution envisageable pour le moment. Les balises colle celle que vous mentionnez doivent venir de la librairie de l'éditeur de texte riche, et il me semble difficile d'implémenter l'intelligence permettant de réduire le formatage à son strict minimum pour tous les usages (GLPI n'est pas seul à se servir de cette librairie). 

Le code généré passe dans une librairie pour assainir le code HTML par sécurité, et cela hors du contrôle du plugin. Les modifications qui peuvent survenir incluent l'échappement de balises HTML, leur suppression. 

Il faudra attendre que GLPI change de méthode d'assainissement pour envisager de résoudre ce bug, mais cela n'est pas envisageable à court terme à cause d'un très gros pré-requis. 

Je ferme le ticket puisque le contournement fonctionne. Merci pour les retours.
