### ISSUE TITLE
Cible ticket ne crée pas de nouveau ticket

### ISSUE THREAD

**Issue by vl20100** [pluginsGLPI/formcreator#1836]
Bonjour,

Lorsque je crée un formulaire avec pour cible de type "Ticket cible", aucun ticket n'est créé à sa validation.

![image](https://user-images.githubusercontent.com/11457015/85833287-c7e47300-b791-11ea-9bca-637dba88c5a6.png)

Voici ce à quoi ressemble mon formulaire : 

![image](https://user-images.githubusercontent.com/11457015/85833486-14c84980-b792-11ea-84b3-bdc5237ec5f1.png)

Merci.

Version GLPI : 9.4.2
Version FormCreator : 2.10 stable

**Comment by btry** [comment]
Bonjour

Vérifiez si il y a des erreurs dans les journaux de GLPI. 
- glpi/files/_log/php-errors.log
- glpi/files/_log/sql-errors.log

Voyez aussi si vous avez une erreur HTTP 500 avec les outils de développeur de votre navigateur. Si c''est le cas, vous trouverez un backtrace dans les logs du serveur HTTP.

Envisagez de mettre votre GLPI à jour en  version 9.4.6 : vous êtes probablement impactés par un bug qui impacte les champs de type date & heure.

**Comment by vl20100** [comment]
Dans le sql-errors.log, j'ai l'erreur suivante : 

`  *** MySQL query error:
  SQL: DELETE `glpi_plugin_formcreator_formanswers` FROM `glpi_plugin_formcreator_formanswers` WHERE (plugin_formcreator_formanswers_id)
  Error: Unknown column 'plugin_formcreator_formanswers_id' in 'where clause'
  Backtrace :
  inc/dbmysql.class.php:1044                         
  plugins/formcreator/inc/formanswer.class.php:1171  DBmysql->delete()
  inc/commondbtm.class.php:1678                      PluginFormcreatorFormAnswer->post_purgeItem()
  inc/massiveaction.class.php:1076                   CommonDBTM->delete()
  inc/massiveaction.class.php:991                    MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()`

Je vais mettre à jour GLPI et voir si j'ai toujours mon problème.

Merci pour la réponse rapide.

**Comment by btry** [comment]
la mise à jour de GLPI ne résoudra pas ce problème SQL. 

Cette erreur n'est pas en lien avec la création de tickets. Quelqu'un a fait une action massive, probablement pour supprimer des réponses à un formulaire.

Je n'ai donc pour le moment aucune piste pour comprendre pourquoi vos tickets ne se créent pas. Essayez de reproduire le bug, et vérifiez les logs immédiatment après.

**Comment by btry** [comment]
Bonjour

Avez vous trouvé d'autres éléments utiles pour cibler votre problème ?

**Comment by btry** [comment]
Bonjour

A défaut d'informations supplémentaires, je ferme le ticket. Si le problème persiste avec uen version récente du plugin, vous pouvez rouvrir un nouveau ticket.
