### ISSUE TITLE
Form fields disappear when opening form. Leaves title and header with no fields.

### ISSUE THREAD

**Issue by tomSDL** [pluginsGLPI/formcreator#1838]
Describe the bug
Upgraded to 2.10.0 yesterday. Now when I open any form I see it momentarily then most of it disappears. The screenshot shows what I am left with. 

To Reproduce
Open any form and the fields disappear.

Expected behavior
Form should display and be usable

**Screenshots**
![image](https://user-images.githubusercontent.com/32687810/85875563-5249c880-b7cc-11ea-8da1-6fd3804dcf69.png)

Desktop (please complete the following information)
 - OS: Windows 10 1909
 - Browser [chrome, edge chromium, Firefox]

**Additional context**
GLPI 9.4.6

**Comment by btry** [comment]
Hi 

Refresh the page on tour browser. Maybe you have a caching issue. Next, use the developper tools of your browser to see if you have HTTP errors. Check the PHP and SQL error logs. Also considéré to export the form to let le test it on my environment.

**Comment by tomSDL** [comment]
Hi,
Thanks for your reply. I tried all the things above and could not conclude anything.
I did notice when using chrome dev tools and checking elements that form elements are set to hidden="hidden". I don't use the "show field" logic in forms. Sections and questions are set to "Always displayed"

![image](https://user-images.githubusercontent.com/32687810/86018269-0346a200-ba1d-11ea-9f06-15a43c769c48.png)


I am not sure why everything is set to hidden.

Thanks,
Tom

**Comment by btry** [comment]
Hi

When a requester selects a form, it is displayed and the browser immediately sends a HTTP request to get the visibility of all questions. The visibility is computed from the inputs of each question. The questions are initialized with the default values you (as admin) previously set. This occurs even when there is no condition.  

i think you should check this request in detail. With the browser development tools check the HTTP request to showfields.php. The HTTP body returned to the browser must be a JSON and it contains booleans for each item with show/hide capability. False means hidden.

**Comment by tomSDL** [comment]
Hi Btry

Further to this on my production GLPI I have enabled GLPI debug mode to try and see if it show me anything and the forms load fine. Turn of debug mode and they stop loading again!

I have also spun up a test replica server to try somethings.

If I remove all the forms and create a new one I still have the issue.

If I remove the plugin and drop all the tables , upon re-installation it works fine. 

I cannot import the JSON as it says it is impossible as it was created in an earlier version.

I was hoping debug mode would show me which table is messing around.

Thanks

Tom

**Comment by btry** [comment]
Hi

A fix was added today on the export / import version check. To workaround the problem:
- edit the JSON file. 
- You will find a key "schema_version". Remove it, ensure you still have a valid JSON, and save. 
- Try to import again

It is quite surprising that the debug mod resolve your issue. Let's see if the problem persists after you reinstalled the plugin and reimported your forms.

**Comment by btry** [comment]
Hi

Having no feedback, I assume this ticket may be closed.

**Comment by tomSDL** [comment]
Hi. Sorry for not following up!

I had to completely remove the plugins tables from the database and start again. It has been fine since.

Tom
