### ISSUE TITLE
Forms only available to the original creator

### ISSUE THREAD

**Issue by ggarrard** [pluginsGLPI/formcreator#1839]
**Describe the bug**
Each form is only available in the account that created it, regardless of the type of access used.

**To Reproduce**
1. Create a form and set its access (tested primarily with restricted & public). Activate it and set to show on home page.
2. Log in as a different user, with appropriate access rights and no forms of its own.
3. Open home screen Forms tab... No form.
4. No form tab in menu bar or assistance tab.

**Expected behavior**
Since there is an active form, it is expected that there should be a form entry in the menu bar tabs. Furthermore, the form itself should be available through the forms tab on the homepage.

**Screenshots**
--None--

**Desktop (please complete the following information):**
- OS: Windows 7
 - Browser: Chrome
 - Version: 83.0.4103.116

**Smartphone (please complete the following information):**
N/A

**Additional context**
Server: Gentoo Linux (4.19.86-gentoo #1 SMP Mon Dec 16 20:39:17 MST 2019 i686 Intel(R) Xeon(TM) CPU 2.80GHz GenuineIntel)
PHP: 7.4.6
GLPI: 9.4.6
formcreator: 2.10.0

**Comment by btry** [comment]
Hi

Please check the following
- the form has no language set or has the same language as the user who does not see it
- the form is active
- the form is not deleted
- the user has access to the entity of the form, or the form is is in a parent entity and is recursive.

**Comment by ggarrard** [comment]
D'oh. English and English (US) are not the same, even if I think they are.
