### ISSUE TITLE
Insérer le champ "ticket.urgency" dans le formulaire.

### ISSUE THREAD

**Issue by nblaisonneau** [pluginsGLPI/formcreator#184]
Bonjour,

Je voulais savoir comment je pourrais récupérer le champ ##ticket.urgency## pour que les utilisateurs puissent déterminer l'urgence de la demande et qu'elle soit prise en compte.

J'ai tenté ça: 
##ifanswerXY=Basse####ticket.urgency=basse####EndifanswerXY##

Mais ça ne fonctionne pas, il n'y a pas de traitement derrière.

Pourriez-vous m'aider?

Merci.
Cordialement,
N1c0

**Comment by neeftarah** [comment]
Bonjour,

Cette fonctionnalité n'a pas encore été implémenté.
Il n'y a actuellement pas de moyen automatique de changer la priorité d'un ticket via Formcreator.

La seule solution est d'intégrer la priorité dans le contenu du ticket a partir de Formcreator puis de le changer manuellement une fois généré.

Votre demande correspond et duplique la demande N° #15

Cordialement,
Jérémy
