### ISSUE TITLE
Form categories are not displayed

### ISSUE THREAD

**Issue by jonaigringo** [pluginsGLPI/formcreator#1843]
**Describe the bug**
Form categories are not displayed on the home page

**Reproduce**
1. Go to home page
2. The categories are not displayed, according to the annexes

**Expected behavior**
You should display the categories as in: Setup > Dropdown> Forms Categories.

**Desktop (please complete the following information):**
OS: Win 10
Chrome and Opera browser
Version 79.0.3945.88 and 65.0.3467.78

**Additional context**
The problem happens in version GLPI 9.4.6 and formcreator 2.10.0

![1-home-page](https://user-images.githubusercontent.com/59033130/86024809-d639c580-ba03-11ea-9604-cb71cab01bf2.png)
![error](https://user-images.githubusercontent.com/59033130/86025613-cc649200-ba04-11ea-8283-27287e7aef98.png)
![2-categories](https://user-images.githubusercontent.com/59033130/86024812-d76af280-ba03-11ea-9928-34c77341117d.png)
![3-form](https://user-images.githubusercontent.com/59033130/86024817-d8038900-ba03-11ea-9f7c-b7b863adc8fd.png)

**Comment by btry** [comment]
Hi

Apply this patch for the JS error: a71d468ef1bd71b3b13e216273b0c1bb6fcc0665
Apply this patch for the not displayed categories : 4e468e3f35c73f78ece6bdf60b1b255ce3535fdf

**Comment by jonaigringo** [comment]
Thanks a lot for your reply!
