### ISSUE TITLE
Table borders missing on GChrome

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1846]
**Describe the bug**
Table border on textArea field is missing on GChrome

**To Reproduce**
1. Create field with textArea field
2. Add table
3. Save
4. View in Chrome

**Expected behavior**
Borders should be displayed on chrome. Working on Firefox.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**
On glpi's style.css, it overrides the border property with border = 0. This doesn't affect firefox, only on chrome.

**Comment by btry** [comment]
Hi

Do this bug also occur in glpi (for example in the ticket's form) ?

**Comment by leecheromerevilit** [comment]
Hi @btry .

Nope. 

This [line](https://github.com/glpi-project/glpi/blob/b5530af86e58df4b15c81562cce394cdae1916ae/css/styles.scss#L1144) causes the problem on FC but not on GLPI Ticket since it wasn't called.

**Comment by btry** [comment]
Hi

Formcreator 2.13 is about to be released, and GLPI 10 has huge CSS changes, making this issue obsolete. I close. You may create a new one if the problem persists with GLPI 10 and Formcreator 2.13.
