### ISSUE TITLE
Suggestions on forum

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#185]
http://forum.glpi-project.org/viewtopic.php?id=148523

**Comment by neeftarah** [comment]
This issue retake 2 feature already asked :

* Create several tasks per ticket : #16
* Allow ticket field targeting for answer : #15 

-----------

Cette issue reprend 2 amélioration déjà demandées :

* Création de plusieurs tâches : #16
* Ciblage des champs d'un ticket avec une question : #15
