### ISSUE TITLE
form is save only one time

### ISSUE THREAD

**Issue by abJEANLAIN** [pluginsGLPI/formcreator#1850]
Hello,

I have created 2 forms.
If i sub one time the forms and ticket is created, but if i want to send again the form stay on my browser whith no error except 

SCRIPT1010: Identificateur attendu
file-type.js (2114,7)

I have test on several browsers.

Ty for you help

**Comment by btry** [comment]
Hi

Can you use the developer tools of your browser (Microsoft Edge I guess ?) to find the full path of the JS file you mentioned ?

I think it belongs to GLPI. Please tell which version you're using.

**Comment by abJEANLAIN** [comment]
The file is on /lib/file-type.js
version of formcreator 2.10
version of GLPI 9.4.6

After several tests I found where the problem was.
I use dynamic fields, when I delete them the form works without problem.

**Comment by btry** [comment]
Dynamic fields ? Do you mean fields displayed / hidden with some conditions in Formcreator ?

**Comment by abJEANLAIN** [comment]
Yes fiels hidde or display with conditions

**Comment by btry** [comment]
Do you have such conditions on at least one textarea field, or does the bug occurs no matter the type of dynamic fields ?

**Comment by abJEANLAIN** [comment]
I use text field or checkboxe for dynamic fields but conditions are on several, entitled and scrolling menu.
Bug are present on both

**Comment by btry** [comment]
This problem has not yet an obvious cause for me, and it is not obvious that the JS error is related.

Could you try to build a new form as simple as possible (as few as sections and questions as you can) to reproduce ? If you succeed to build this form, export it and put the .json here.

**Comment by abJEANLAIN** [comment]
It's Work with this simple form
[export_formcreator_20200703_1554.json.txt](https://github.com/pluginsGLPI/formcreator/files/4870068/export_formcreator_20200703_1554.json.txt)

**Comment by btry** [comment]
Hi

I don't reproduce. I tried with and without an upload in the last field.

**Comment by abJEANLAIN** [comment]
Hi,

I attach the form not working.
But doesn't work only on IE11
[export_formcreator_20200713_1105.json.txt](https://github.com/pluginsGLPI/formcreator/files/4911428/export_formcreator_20200713_1105.json.txt)


If you want i can give the url of the form

**Comment by btry** [comment]
Hi

Your issue is probably related to IE11, and it is no longer supported by GLPI (version 9.5). 

GLPI 9.4 is no longer supported, then your best option is to upgrade to Edge now.

Could you try and see if your problem persists ?

**Comment by abJEANLAIN** [comment]
I've found the problem.


There was a restriction on the telephone field.
However the form did not give the error message concerning a problem of character length.
