### ISSUE TITLE
[2.10] - problems with approvals

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1855]
Hi

When a ticket is opened by a user and has the status is processing, it appears in the ticket bar:

![2020-07-07 17_25_08-GLPI - Service catalog](https://user-images.githubusercontent.com/43650152/86838763-f35f3b80-c076-11ea-8ad5-358210e9da29.png)

In the glpi_plugins_formcreator_issues table, it receives status 2:
![2020-07-07 17_27_38-DBeaver 7 1 0 - glpi_plugin_formcreator_issues](https://user-images.githubusercontent.com/43650152/86838994-39b49a80-c077-11ea-926e-d47e950eea86.png)

If a ticket approval request is sent to any user, this Status is changed to 101 and the ticket does not appear on the user's screen:
![2020-07-07 17_30_21-GLPI - Tickets - 4](https://user-images.githubusercontent.com/43650152/86839702-25bd6880-c078-11ea-9d11-b9232b070bc4.png)

![2020-07-07 17_31_43-DBeaver 7 1 0 - glpi_plugin_formcreator_issues](https://user-images.githubusercontent.com/43650152/86839435-ceb79380-c077-11ea-919f-53d8a04cfbe4.png)

![2020-07-07 17_35_20-GLPI - Service catalog](https://user-images.githubusercontent.com/43650152/86839803-45ed2780-c078-11ea-8b25-6a16172cc52a.png)

**Comment by btry** [comment]
Hi

I'll check this quickly. Can you confirm that the approval is the workflow of the plugin and not the workflow of GLPI ?

**Comment by jvergacas** [comment]
Is the workflow of GLPI.

**Comment by btry** [comment]
Hi

Could you try this patch and feedback ?

**Comment by jvergacas** [comment]
Hi @btry 

It´s working fine.

Thanks

**Comment by btry** [comment]
Thank you, the fix is ready for the next release.
