### ISSUE TITLE
"Add Section" / "Add Target" don't react (error in debugger)

### ISSUE THREAD

**Issue by philippeplatiau** [pluginsGLPI/formcreator#1856]
Hello, 

I have an issue with the latest version of GLPI 9.5.0 + Formcreator 2.10.0 

Adding a form works
But when I try to add a section (to add questions afterwards), nothing happens. 

Error received in the debugger (F12) : 

"Add section :" 

VM4854:1 Uncaught ReferenceError: plugin_formcreator_addSection is not defined
    at <anonymous>:1:1

"Add target" : 

Uncaught ReferenceError: plugin_formcreator_addTarget is not defined
    at <anonymous>:1:1
(anonymous) @ VM4855:1

Tested with Chrome, Firefox
Tested in a Proxied environment : a container "proxy", 2 other containers behind : DB + GLPI 
Tested with a direct connection : on a linux distribution, with Apache, MySQL, PHP : same error... 

Any idea ? 

Regards,

Philippe

**Comment by btry** [comment]
Hi

Try to refresh the page with F5. I believe that your browser uses an obsolete version of the JS scripts because it is cached. Did you upgraded the plugin from an earlier version ?

**Comment by philippeplatiau** [comment]
Hi,

This is due to the Marketplace. When you add the plugin "Formcreator" with
the Marketplace, it doesn't install it correctly.
Even if you install it in the "plugins/" subfolder (with a wget, then unzip
it) ... It's too late, the Marketplace corrupted the system.

I re-created the instance from scratch (new db + new installation of glpi)
and I installed the plugin with the old method (without the marketplace)
and that worked perfectly.

So, I think there is something wrong with the new feature Marketplace.
Possible ?

Regards,

Philippe

**Comment by btry** [comment]
Hi

Do you have details about how your instance was corrupted ? (added files in an unexpected location, deleted files which should remain, ...)

**Comment by philippeplatiau** [comment]
No, I really don't know why it corrupted the system

My steps :

1) installation of GLPI (new instance) 9.5.0
2) installation of the DB (new db)
3) add registration key for Marketplace
4) installation of the plugin FormCreator via Marketplace within the GLPI
interface (Formcreator version 2.10.0)
5) add a new form
6) next step : add section... => the layer doesn't appear on the top left
...
7) same behavior for "add target", as it's also a "javascript;" call.

I checked in the /var/www/html/glpi/plugins , nothing was installed...

I deleted everything

Then, other method (the old one : manual installation of the plugin)

1) installation of GLPI (new instance) 9.5.0
2) installation of the DB (new db)
3) bash terminal, cd /var/www/html/glpi/plugins
4) wget the formcreator bz2 file from github (Formcreator version 2.10.0)
5) uncompress
6) activation of the plugin in GLPI web interface
7) next step : add section... => it works !

I hope it helps...

Regards,

Philippe

**Comment by btry** [comment]
OK, I think this is more related to the plugin than the marketplace itself. I'll care your issue this week.

I plan to release a first maintenance release of 2.10 within 2 weeks; I'll include the fix if a bug is actually spotted.

**Comment by philippeplatiau** [comment]
Thanks a lot for your fast reply !

I'll keep you posted if I have something else about it as well.

As long as it works without the marketplace, it's ok for me. But other
users could have the same issue...

Have a nice day

Regards,

Philippe

**Comment by btry** [comment]
Hi

I foud some failing path computation in the plugin to make it compatible with the marketplace. This should be fixed in the next release (2.10.1) planned this month.

see 9b75f05f85fed8192fbe611469fb85a9c1d576e9 e8b38f0cdb6767d708cc24c2d6c70d6ad5223005

**Comment by philippeplatiau** [comment]
Thank you for the fix !

**Comment by btry** [comment]
Thank you for your feedback.

**Comment by bacus99** [comment]
No go for me, no errors in logs.  Tested in Firefox and Chrome

**Comment by btry** [comment]
Hi @bacus99 

you probably have 404 errors when the browser requests some resource. Can you investigate in the developer tools of your browser in the **network**  tab ? Don't forget to open the developer tools before browsing to the faulty page.

I'm waiting for your feedback.

**Comment by bacus99** [comment]
Issues are in the QUESTIONS and TARGET tab

![image](https://user-images.githubusercontent.com/11425241/87333717-8121a780-c50b-11ea-958b-0b301f71cc12.png)

**Comment by bacus99** [comment]
Got it!
VM1636:1 Uncaught ReferenceError: plugin_formcreator_addSection is not defined
    at <anonymous>:1:1

**Comment by bacus99** [comment]
same for target

Uncaught ReferenceError: plugin_formcreator_addTarget is not defined
    at <anonymous>:1:1

**Comment by btry** [comment]
Hi

All your errors are related to plugins/formcreator/js/scripts.js.php being not loaded. 

In the network history you leed to check HTTP requests occurring a bit earlier. Maybe you opened the dev tools just before loading a tab.

![image](https://user-images.githubusercontent.com/14139801/87342357-666f2300-c54b-11ea-8433-43a5210776fc.png)

**Comment by btry** [comment]
Hi

I got positive feedback about the path problems found in the previous release. Can you check that the release 2.10.1 solve your issue ?

**Comment by philippeplatiau** [comment]
Hello,

You can close the ticket, it's ok for me as well ! Thank you !

Regards,

Philippe

**Comment by btry** [comment]
Hi

Thann you
