### ISSUE TITLE
Préremplissage d'un formulaire

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1857]
Bonjour,
Je ne sais pas si c'est possible, mais je souhaiterai pouvoir préremplir un formulaire depuis une page web, passer en paramètre dans l'url les valeurs de certains champs d'un formulaire. 
Est-ce que ce serait possible dans les version actuelles?
Merci

**Comment by btry** [comment]
Bonjour

Le plugin ne prend pas cela en charge. Les valeurs par défaut sont définie par le concepteur du formulaire.
