### ISSUE TITLE
 Reopening calls in the form creator's simplified interface does not work.

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#1858]
Quan
When I am in the simplified (expanded) interface and I click the reopen button it does not reopen, if I change the interface to the help desk glpi the button reopens normally, which rules out permission and lifecycle problems.
Do you know how to resolve to be able to reopen the ticket in the simplified form creator interface?

**Screens using the simplified form builder interface (does not work)**
![1](https://user-images.githubusercontent.com/42414051/86935605-661df480-c113-11ea-9419-f02158b4301c.png)
![2](https://user-images.githubusercontent.com/42414051/86935616-68804e80-c113-11ea-940e-84ce51dca473.png)
![3](https://user-images.githubusercontent.com/42414051/86935627-69b17b80-c113-11ea-9790-d764b70be856.png)

**Screens using the simplified GLPI interface (Works)**
![4](https://user-images.githubusercontent.com/42414051/86935634-6b7b3f00-c113-11ea-956e-61a230a1f197.png)
![5](https://user-images.githubusercontent.com/42414051/86935636-6cac6c00-c113-11ea-82ad-e7eebf1a36e2.png)
![6](https://user-images.githubusercontent.com/42414051/86935640-6ddd9900-c113-11ea-9744-ccd8ad10e1be.png)

**Comment by btry** [comment]
Hi

Please apply (on a testing environemnt) this fix and feedback

**Comment by TR0LLL** [comment]
I performed the test in my test environment and everything worked correctly, as you can see in the image the reopen button loaded and the reopening worked.
Thank you very much

![glpi ok](https://user-images.githubusercontent.com/42414051/87545508-73406380-c67e-11ea-8ec1-f08c8feb1f88.png)

**Comment by btry** [comment]
Hi

Thank you for your feedback.
