### ISSUE TITLE
Traitement des règles metiers pour les demandes

### ISSUE THREAD

**Issue by InfoFDADMR54** [pluginsGLPI/formcreator#186]
Bonjour,

J'ai une règle qui va vérifier si une phrase précise est bien dans la description. Dans ce cas le ticket passe directement en résolu. Cela fonctionne lorsque je crée le ticket de manière classique, mais pas lorsque c'est généré via formcreator.

Comment sont gérés les règles métiers pour les demandes qui sont créées via les formulaire ?

**Comment by neeftarah** [comment]
Bonjour,

Elles sont normalement gérer comme n'importe quel ticket GLPI.
Votre règle devrais donc fonctionné.

Toutefois, il se peut que le contenu diffère si dans votre phrase, vous avez des caractères spéciaux ou guillemets, les caractères étant encodé via Formcreator.

Le plus, simple, si vous avez accès à la base de donnée, étant de regarder comment sont enregistrer les tickets comportant cette phrase dans la base de données.

Cordialement,
Jérémy

**Comment by InfoFDADMR54** [comment]
Effectivement, ma phrase contenait des caractères spéciaux. L'encodage étant différent la règle ne fonctionnait pas.

Après modification tout marche a merveille.

Merci pour la réponse rapide :+1: 

Cordialement.
