### ISSUE TITLE
Modal in the top of the page GLPI 9.5 and FormCreator 2.10.0

### ISSUE THREAD

**Issue by mecmav** [pluginsGLPI/formcreator#1867]
Hi,

Using these version specified in the title, if we have a very large form, with several sections and questions and all properly configured by the rules, when clicking to add a section or question, the config modal is always displayed at the top of the page, being necessary to scroll up every time.

This is not a serious problem, but a nuisance, because if we are working with large forms, it is boring every time having to roll up until we reach the configuration mode.

What can I do to try make a correction?

**Comment by btry** [comment]
Hi

Please test this fix and fedback

**Comment by mecmav** [comment]
Hello again,

Yess, this fixes the issue. Now when click to add a question or section the modal is displayed at in the current position and correctly centered.

Thanks!
