### ISSUE TITLE
Formcreator doesn't attach documents after update 2.10

### ISSUE THREAD

**Issue by fedieva** [pluginsGLPI/formcreator#1869]
I just update glpi to 9.5, and formcreator plugin to 2.10.
Now forms create tickets but doesn't create documents. Files are upload to var/lib/glpi/_tmp directory but doesn't create this document therefore it is not attached to the ticket either. 
If i create a simply ticket thorugh glpi interface the document is attached, and if i create a ticket from an email, the document is attached too.
I tried to uninstall plugin, and reinstall it, but it has the same behaviour.

In debug mode doesn't appear any error of php.
Log files don't show any error of create documents.

**Comment by btry** [comment]
Hi

How do you join attachments ? With a textarea field or with a file field ?

**Comment by fedieva** [comment]
With a file field.

**Comment by btry** [comment]
Hi

Try the above fix and feedback

**Comment by philippeplatiau** [comment]
Hi ! 

That's why I found, indeed, in my post. I didn't remove the whole section, but I just changed the sign :-) 

https://github.com/pluginsGLPI/formcreator/issues/1702#issuecomment-655905305

Regards,

Philippe

**Comment by btry** [comment]
Hi

@philippeplatiau : the plugin must move uploaded files to "convert" them as documents. What I found so far is I need to move the uploads later in the workflow to keep all GLPI versions happy.

If you're also impacted by this issue, I would appreciate your feedback with the fix. It tried to maintain compatibility with GLPI 9.4 and 9.5. In the next minor version of the plugin, I'll enjoy removing this ugly and hard-to-maintain check.

**Comment by fedieva** [comment]
Great!! The files already attached! it runs ok. Tou're the best btry!

**Comment by btry** [comment]
Thank you for your feedback. It will be ready for the next release.
