### ISSUE TITLE
Form List not showing on IE11

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1875]
Hi,

This is kind of a backward issue but I'll just report it anyway. Form List is not showing using IE11 v11.900.18362.0

**Comment by leecheromerevilit** [comment]
UPDATE 

Form List didn't load since there's an error on the console.

SCRIPT1010: Expected identifier
file-type.js (2114,7)

SCRIPT1002: Syntax error
scripts.js.php (571,10)

if one's fixed, then other error will occur, I don't know how far these errors goes.

**Comment by btry** [comment]
Hi

This seems similar to the report iin #1850

**Comment by btry** [comment]
This error is related to GLPI.

GLPI 9.4 is no longer supported and you should switch to GLPI 9.5, which dropped support of IE11. This browser is way too old. You may upgrade to Edge.

By the way, I expect to drop support of GLPI 9.4 in the develop branch; the version 2.10 is the version to use for transition between GLPI 9.4 and 9.5.

**Comment by leecheromerevilit** [comment]
Hi @btry 

Noted on this one. Thank you. I'll close this issue.
