### ISSUE TITLE
Service catalog mode: Search the FAQ

### ISSUE THREAD

**Issue by Giudy** [pluginsGLPI/formcreator#1876]
Hello, 
 it looks like it is impossible to search in the FAQs using the service catalog mode

If I create a KB-Faq, called "password reset" (title) with the description "password" , if I type "password" in the search , I get no results
![image](https://user-images.githubusercontent.com/7987648/87655704-e0282c00-c758-11ea-923f-3b31420197b5.png)

after search:
![image](https://user-images.githubusercontent.com/7987648/87655772-f635ec80-c758-11ea-8b2c-554ff7f47285.png)

this is the FAQ contents:
![image](https://user-images.githubusercontent.com/7987648/87655998-3301e380-c759-11ea-935f-ff21cb892020.png)

I've tried with or without translations activated.

if I search the FAQ through the knowledgebase search menu, it does work
if I search the ticket, it does work in the service catalog form

![image](https://user-images.githubusercontent.com/7987648/87656311-9db31f00-c759-11ea-8c6d-587ab72b7590.png)

GLPI 9.4.5
Formcreator: 2.10.0

Davide

**Comment by btry** [comment]
Hi

toe FAQ items must be associated to a KB category and the KB categories must be associated to form categories. If there is no relational path froma form category to a FAQ item it cannot be displayed.

I reproduced your issue only if this path does not exists. Please check the above mentioned relations.

**Comment by Giudy** [comment]
Thank you for your answer, but this chain has been accomplished:
form category=BASE linked to the KB category called KB

![image](https://user-images.githubusercontent.com/7987648/87689048-0c0ed600-c788-11ea-86a9-fe5477f1b2f2.png)

![image](https://user-images.githubusercontent.com/7987648/87689117-1df07900-c788-11ea-9bb0-61f6a8e3ae37.png)

![image](https://user-images.githubusercontent.com/7987648/87689257-4a0bfa00-c788-11ea-9db1-3a405d914f90.png)

**Comment by Giudy** [comment]
I'm wondering why the message in the service catalog mode is "No form found" as it should search also in FAQ. is there something missing to me?

![image](https://user-images.githubusercontent.com/7987648/87689783-e930f180-c788-11ea-970b-030776e08eb8.png)

**Comment by btry** [comment]
Don't worry about the message. It does not mentions that ni FAQ item was retrieved. I may improve this message in the next minor version.

For now, I could not reproduce with a proper chain of relations. You should maybe check the entity settings on all involved items. In my setup and having everything in the root entity, the plugin seems to behave as expected.

Describe your entity tree, in which entity are each item and how is set they their recursivity.

**Comment by Giudy** [comment]
Hi, 
 unfortunately just one entity with no subentities. the search seems working only through the forms.
I've tried with new article, new targets (as per entity, per user, per profile), but nothing.
using debugging seems does not help. is there something I can check?

**Comment by btry** [comment]
Check if you have php errors or sql warnings. Also check the SQL query built by the plugin. 

You can find the code in PluginFormcreatorForm::showFormList(). There is a line

```$result_faqs = $DB->request($query_faqs);```

After this line, add ```Toolbox::logSqlDebug($result_faqs->getSQL());```

This should generate a log entry in sql-errors.log with the query I need to exsamine.

**Comment by btry** [comment]
Hi

Could you test this patch ? : b816448c4d4b59b24f3591cf6db645b70eed0c6f

It fixes a possible SQL error while searching for KB items. If you have few forms in the database, the fix might resolve your issue.

**Comment by Giudy** [comment]
yes, sure!
g

Il giorno ven 17 lug 2020 alle ore 11:58 btry <notifications@github.com> ha
scritto:

**Comment by Giudy** [comment]
Yep! It did the job!
Great!
Davide

**Comment by Giudy** [comment]
Hi, is this patch gonna be inserted in some branch?

d

**Comment by btry** [comment]
Hi

Sorry, I missed the latest notifications for  this issue. The patch has been merged in branch support/2.10.0. See https://github.com/pluginsGLPI/formcreator/pull/1878 . This means that it will be released in the next bugfix release.

I think I'll release the version 2.10.2 in september. In the mean time, feel free to patch your copy of the plugin to have the fix earlier.
