### ISSUE TITLE
Problème de récupération de données

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/formcreator#188]
Bonjour,

J'ai ouvert un sujet sur le forum GLPI : `http://forum.glpi-project.org/viewtopic.php?id=148679` pour une erreur lors de l'installation de formcreator. 

Suite à une migration de GLPI de version 0.83.7 à 0.90, le plugin formcreator n'arrive pas s'installer, il affiche le message d'erreur suivant sur le navigateur :
Incorrect integer value: "for column 'show_field' at row 1

J'ai réussi à l'installer sur une machine test où j'ai supprimé un table dont les champs ne se sont pas rempli et j'ai modifié le nom d'une table; mais cela me force à recréer quand même tous mes formulaires.

Est ce que vous auriez une diée pour ce problème ?
Merci d'avance.

Cordialement

**Comment by neeftarah** [comment]
Bonjour,

Pouvez-vous e transmettre le message d'erreur complet (avec fichier et N° de ligne) ainsi que les numéros de version du plugin Formcreator (pour la 0.83 et la 0.90).

Merci d'avance,

Cordialement,
Jérémy

**Comment by usrqmor** [comment]
Bonjour,

Voici une capture d'écran du log sql.
![captureecran](https://cloud.githubusercontent.com/assets/17316903/13173378/6ecaba28-d6fd-11e5-8e74-0f0d8fe7494b.jpg)

Concernant la version de formcreator pour le GLPI en v0.83.7 : 1.7.5 et pour le glpi en v0.9 : 0.90-1.3.3
N'hésitez pas à me signaler s'il vous manque des informations.

Cordialement.

**Comment by neeftarah** [comment]
Merci de votre aide. Le commit 49beb11 ci dessus doit corriger votre problème. Il sera intégrer dans la prochaine version de FormCreator.

Cordialement,
Jérémy
