### ISSUE TITLE
[2.10.1] - Does not recognize attached file.

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#1882]
When a file is configured to be mandatory, the plugin does not recognize that it has been attached.

![2020-07-20 11_13_00-Window](https://user-images.githubusercontent.com/43650152/87948649-5ee3d880-ca7b-11ea-8a40-97d229e29424.png)

Thanks.

**Comment by btry** [comment]
Hi

Can you explain the missing process ? The file shall be added as a new document (visible in the Documents section of GLPI), and attached to a target ticket or a target change. From which step the plugin does not behave as expeectd ?

**Comment by jvergacas** [comment]
The error is visible in self-service profile whem i send the form.

**Comment by leecheromerevilit** [comment]
Hi @jvergacas 

Just a quick question. On your screenshot, how can you still have the file on the file field after throwing an error that it's missing? 

Hi @btry 
I'm referring to this issue which might be related to this one if not fixed. [link](https://github.com/pluginsGLPI/formcreator/issues/1507#issuecomment-536550051)

**Comment by btry** [comment]
Hi

I did not saw the error message i the bottom right corner. I understand now the issue.

@leecheromerevilit : with GLPI 9.5 and the latest release the plugin is able to "keep" the uploads when the answers are submitted but are incorrect. The same applies for pictures embedded in a rich text area.

**Comment by btry** [comment]
Hi

I found the fix. Please test it and feedback.

**Comment by leecheromerevilit** [comment]
Hi @btry 

All good now after applying the fix using glpi v9.5 and fc v2.10.1

If it's not too much to ask, do you have the link for the patch on the bug for files not being retained after page reload?

**Comment by btry** [comment]
Hi
I'm afraid that the fix is hard to find : it was done a few weeks ago, and was delayed by the extesive code review of the fix GLPI-side. Moreover, the fix in the plugin was not accurate and broke compatibility with GLPI 9.4. This was corrected in the release 2.10.1.

However, all fixes are cherry-picked to the develop branch (I guess you work with it).

**Comment by btry** [comment]
Thank you for your feedback. I close this issue.

**Comment by phamorais** [comment]
Hello
Just to contribute

This bus also occurred to me in 2.10.1 with glpi 9.4.6

And the applied correction worked for version 9.4.6

**Comment by btry** [comment]
Nice, thank you for your precision !
