### ISSUE TITLE
[Question] Alignment of forms V2.10.1 - 

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1884]
Hello!
I don't think it's a BUG, ​​just a doubt

Version 2.9.2 had the style of the cards in a "centralized" way

![image](https://user-images.githubusercontent.com/35368369/88053032-901ee000-cb31-11ea-99be-2e7ff36e4c5d.png)

After upgrading to v2.10.1 I checked the style returned to be left aligned

![image](https://user-images.githubusercontent.com/35368369/88053224-d116f480-cb31-11ea-97db-9f3e7af809ca.png)

Has the alignment changed?

**Comment by btry** [comment]
Hi

This is maybe a side effect of a change in the CSS of the plugin. This is unintentional.

**Comment by phamorais** [comment]
@btry 

I believe it is something from the new version 2.10.1.

I removed my CSS change, keeping the original form code

In Version 2.10.0 Cars are aligned to the left

![image](https://user-images.githubusercontent.com/35368369/88333658-fe68cb80-cd06-11ea-970b-840636ae5179.png)


with 2.10.1 the cards change the style

![image](https://user-images.githubusercontent.com/35368369/88333930-5d2e4500-cd07-11ea-8a00-d8856c691716.png)

**Comment by btry** [comment]
Hi

I checked : the diff is empty between the tag v2.10.0 and v2.10.1 in css/styles.css or the masonry library. 

On my instance I don't see any difference between those version. Are you sure the change does not appear between 2.9.x and 2.10.0 ?

**Comment by phamorais** [comment]
Hi @btry 


In version 2.9.2 the cards are centered.

The print below is from my production environment and despite the change in styles, alignment has not changed.

I honestly don't know what it might be, but I realized that alignment to the left only happened after upgrading to 2.10.1

**Comment by btry** [comment]
Hi

I did not found yet what caused this change, and I don't have a lot of time to allocate to this minor change. Do you have ability to check the display with the version 2.10.0 ?

**Comment by phamorais** [comment]
@btry 

I already did it.
In yesterday's post, the first image is with v2.10.0

![image](https://user-images.githubusercontent.com/35368369/88388102-3c5b0380-cd8a-11ea-8985-d1eda1e516f6.png)


You can stop a small change without much value, but it is the interface presented to the customer. Everything that has a visual impact on the customer is always important :(

**Comment by btry** [comment]
I'll search soon how to restore the previous visual change.

**Comment by phamorais** [comment]
It's ok
Thank you @btry

**Comment by phamorais** [comment]
@btry 
Hello

So far it is still aligned to the left. (V2.10 and v2.11). 
Although I personally find centralized ordering more friendly, the current ordering is not necessarily an error.
For me we can close this ticket, or I can leave it open if you want to analyze the feasibility of leaving it centralized.

**Comment by phamorais** [comment]
This is not more necessary.
