### ISSUE TITLE
Doubts about whether there is a way to open different types of calling depending on the response of the formula

### ISSUE THREAD

**Issue by apithon2** [pluginsGLPI/formcreator#1885]
Hello with day I am a support analyst for a company that manufactures truck parts.
Through colleagues who work in the IT area who will introduce me to GLPI and I decided to implement this helpdesk in the company where I work because my helpdesk system is not the best. and through research I found this plugin wonderful. 

Doubts about whether there is a way to open different types of calling depending on the response of the formula
example if I create a form of software categories and within it create a question of ticking the type install chorme another chrome update would have as depending on the option he marked would open a different call with different SLA

Because then would do something more organized would create the principles like Hardware / Software / Support / internet / Email. And within each form would pose the problem

**Comment by btry** [comment]
Hi

If I understand well, you need to set the request type to request or incident depending on any type of question. 

The plugin does not allows that for now. you can only set the request type from a question of type **request type**.

The easiest workaround is to have a form for software installations and an other for software updates.

A way to implement this would be to extend conditions usage. Depending on the condition evaluation result, the target ticket can be a request or an incident.

**Comment by apithon2** [comment]
Ok thank you very much

**Comment by btry** [comment]
Hi

 If the workaround is not sufficient and you want to sponsor the development I described above, please contact us : contact@teclib.com 

I guess I can close this issue. Feel free to ask if you still need help.
