### ISSUE TITLE
Last valid answer not working

### ISSUE THREAD

**Issue by lucascacardoso** [pluginsGLPI/formcreator#1886]
I've created a form to open tickets that shows a dropdown question to incident categories or request categories depending on the request type. In the target, i've selected the "last valid answer" option to Category. 

With this form, incident tickets are created correctly, but when the user choose the type "request" and select a request category, the ticket category appears in blank.

According to the PR #1681, this new feature looks for "answer" in glpi_plugin_formcreator_answers table. If empty, pass to next row. But, i've noticed that the incident category question in my form, when not answered, receive 0, not NULL.

I'm using formcreator 2.10.1

**Comment by btry** [comment]
Hi

I tried to reproduce. I'm not sure my test is strictly identical to yours, but I think that the code should handle invisible questions and skip them.

**Comment by btry** [comment]
Hi

Please test the above fix and feedback. With this patch the last valid answer shall take into account the hidden status of a question.

**Comment by btry** [comment]
Hi

Did you tried the above patch ?

**Comment by btry** [comment]
The patch conflicts withan other commit. Updating the Pr makes harder for you to test it. I'll rely on the unit tests and the code review, then assume it will work for you. 

To test it in a reliable way, you would now need to run  the latest revision of support/2.10.0 branch. If you can do it and still have problems, please leave a comment her, and I'll reopen.

**Comment by lucascacardoso** [comment]
Hi, sorry taking so long to reply...

I've tested formcreator 2.10.2-dev in GLPI 9.5.1 and it worked!

**Comment by btry** [comment]
Hi

Thank you for your feedback. The fix is ready for the next release.
