### ISSUE TITLE
forms Access types couldn't be altered [v2.10.1]

### ISSUE THREAD

**Issue by sinisamars** [pluginsGLPI/formcreator#1887]
**Describe the bug**
Cannot (de)assign user profiles to any of the forms.

**To Reproduce**
1. Go to  Assistance---> Forms---wrench tool (Setup)
2. Click on Any previously defined Form
3. Select Access types tab on the left  Somehow, all profiles have access!
4. Try to deselect and 'Save'  any of the profiles (every profile is selected with the checkbox filled in)

**Expected behavior**
After selecting profiles that should have allowed access, after clicking the Save, it should show correct checkboxes selected, 
and with the corresponding profiles with the access to selected forms.

**Screenshots**
![forms_access_problem](https://user-images.githubusercontent.com/68612352/88094099-48c93b80-cb93-11ea-81c8-46cb18f571ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10  (GLPI is hosted on Centos 7 machine)
 - Browser  Firefox 
 - Version 78.0.2

additional comment:

 Those were the Forms inherited from the previous GLPI version  9.4.2  and Formcreator plugin 2.8.6  where everything worked
as it sould.
After updating GLPI to 9.5.1 and Formcreator to 2.10.1 I was testing every Formcreator functionality, but unfortunately, Access rights are unable to persist after saving.
Even if I create completely new Form, it wouldn't save Access rights.

Please check, 

Thanks!

**Comment by btry** [comment]
Hi

bug confirmed

**Comment by btry** [comment]
Please test the above patch. 

FYI : the settings are actually saved and taken into account. The issue impacted only the display.

**Comment by sinisamars** [comment]
I can confirm that after applying the patch, everything works normal (as expected).

Thank you!

**Comment by btry** [comment]
Hi

Thank you for your feedback. The patch was merged.
