### ISSUE TITLE
Loading time for large forms

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1888]
Hi

I have a large form with at least 273 questions in it with different kinds of fields. If I try to enter data on say text field, showfields.php gets called. I assume that this is an ajax call to see if there's a condition to show other fields or section every time there's an interaction within the form. With this kind of behavior, it will take a long time for the form to check each fields (I found out that it will all through all the questions within the form).

Do we have a fix for this in which, the system will check if that field has a condition and if true, that's the only time to trigger showfields.php. This will save a lot of time for fields with no condition but still calling the showfields.php every time user inputs on the field.

Best Regards,

**Comment by leecheromerevilit** [comment]
Hi @btry 

Do we have any updates on this? It would be great to add a 1st layer of condition checking before calling showfields.php.

**Comment by btry** [comment]
Hi

Not yet. this might be very nice ti implement browser side validation in the process. A sponsor would be welcome to let me allocate time more quickly.

**Comment by btry** [comment]
Hi

I got a PR to improbe performance on condition evaluation. Something quite obvious, related to use of a foreach language construct. This should impact slightly the loading of a form.

However, there is also a performance impact caused by the new column structure of a form, which seems to depend on the gridstack library.

See #1935

**Comment by btry** [comment]
Hi 

I have a form with more than 1400 items (206 questions, others are sections, conditions, some targets).. Compared to the first versions showing questions with several columns the performance is much better.

This forms loads within about 10 seconds in design interface, and 2 or 3 seconds in preview. This looks acceptable to me considering the unusual complexity of this sample.
