### ISSUE TITLE
Erreur : Unsupported operand types

### ISSUE THREAD

**Issue by sjailliard** [pluginsGLPI/formcreator#189]
Bonjour,

Nous avons installé Form Creator sur un GLPI 0.90.1 puis nous avons créé un formulaire "test".
Lorsque nous allons sur le formulaire et que nous cliquons sur "Envoyer" nous obtenons une erreur 500.
Dans les logs Apache nous avons alors la ligne suivante :

PHP Fatal error:  Unsupported operand types in /usr/share/glpi/plugins/formcreator/inc/form.class.php on line 930, referer: http://intrasi/glpi/plugins/formcreator/front/formdisplay.php?id=3

A priori la ligne concerné est juste une récupération de données d'un formulaire :

$datas = $datas + $_POST;

Quelqu'un aurait-il des suggestions afin de résoudre ce problème ?

Merci.

**Comment by neeftarah** [comment]
Bonjour,

Pouvez-vous me préciser votre environnement OS + version de PHP ?

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
Merci de me dire si la correction ci-dessus corrige votre problème ou de rouvrir cette issue si ce n'est pas le cas.

Votre erreur est très étrange et ne devrais jamais se produire sauf peut-être si vous avez créer un formulaire sans aucune question ?

**Comment by sjailliard** [comment]
Bonjour,

Il s'agit d'un OS Linux Ubuntu 14.04.2 LTS
PHP 5.3.0.1

En fait j'ai résolu le problème de mon côté entre temps.
J'ai simplement ajouté une question au formulaire (car j'avais créé un formulaire vide juste pour tester) et maintenant cela fonctionne.

Apparemment la condition du cas où il n'y a pas de question n'est pas testée dans le code php et provoque une erreur.

Bon week-end.

**Comment by sjailliard** [comment]
Désolé, je n'ai pas vu votre second message lorsque j'ai répondu.
Oui ça fonctionne avec votre correctif.

merci beaucoup.

**Comment by neeftarah** [comment]
OK.
NB : GLPI 0.90+ requiers PHP 5.4+

Cordialement,
Jérémy
