### ISSUE TITLE
Validation de formulaire

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#1897]
Bonjour,

Nous utilisons le processus de validation de formulaire pour certains types de demande.
Par contre un certain nombre de demandes ont été créées alors que le valideur par défaut est absent pour une longue période. Comment peut-on valider ces demandes en attentes? Même en super-admin je ne vois pas comment faire.

D'avance merci

**Comment by btry** [comment]
Bonjour

Le problème de l'intervenant en congés est un problème récurrent, que ce soit dans Formcreator ou non. Pour éviter cela il vaut mieux utiliser des groupes, ce qui offre plus de souplesse.

En vérifiant le code du plugin, le super admin n'a en effet pas de super-pouvoir sur la validation des formulaires. C'est une fonctionnalité qui serait la bienvenue.

**Comment by eckorion** [comment]
Oui c'est ce que j'ai fait du coup.
Merci
