### ISSUE TITLE
Tout les formulaire ne s'affiche plus

### ISSUE THREAD

**Issue by maules** [pluginsGLPI/formcreator#1898]
Bonjour,

J'ai effectuer la mise à jour vers Formcreator 2.10.1, malheureusement lorsque je consulte les formulaires il disparaissent dès que j'accedes à la page du formulaire.
Avez vous déjà eu vent de ce probleme.
Merci pour votre aide.
vers.2.6 vers 2.10.1

Cordialement,

**Comment by btry** [comment]
Bonjour

C'est la liste des formulaires ou le contenu de l'un d'eux qui disparaît ?

Pensez à vérifier les logs de glpi à la recherche d'erreurs PHP ou SQL.

**Comment by maules** [comment]
Bonsoir,

Merci pour votre retour rapide.
C'est le contenu, la liste s'affiche correctement.
Si vous parlez des journaux dans le module Administration, je ne vois rien, a part des evenements comme les connexion.
Ou dois-je plutôt regarder les log côté Debian.

Merci

Cordialement,

**Comment by btry** [comment]
Ce problème est déjà arrivé. De ce que j'ai trouvé cela arrive a cause d'erreurs PHP qui polluent des données au format JSON entre le serveur et le navigateur. Il faut que le mode debug de GLPI soit activé. Vous verrez les erreurs dans les outils de développement du navigateur, onglet réseau.

Les logs dont je parle sont dans le système de fichiers du serveur. Il est sûr qu'il y a quelque chose d'utile.
- glpi/files/_log/php-errors.log
- glpi/files/_log/sql-errors.log

Pour faciliter la recherche du bug, vous pouvez exporter le formulaire et le déposer ici. Veillez à ce qu'il ne contienne la d'information sensible (une description par exemple).

**Comment by maules** [comment]
Ok 
Je vais suivre vos recommandation dans l'ordre et vous ferais un retour qui j'espère sera claire.
Merci

**Comment by maules** [comment]
Désolé de vous demandez ca mais comment je procede pour partager avec vous le formulaire exporter.
Pour etre honnete c'est ma premiere fois sur Github
Merci

**Comment by maules** [comment]
Voici l'export d'un formuliare de test.

[export_formcreator_20200727_2141.json.zip](https://github.com/pluginsGLPI/formcreator/files/4984098/export_formcreator_20200727_2141.json.zip)

**Comment by maules** [comment]
Voici les fichiers de log :

J'ai pris les dernières lignes a la date d'aujourd'hui après la MAJ.

[Error_Log_PHP.zip](https://github.com/pluginsGLPI/formcreator/files/4984122/Error_Log_PHP.zip)
[Error_Log_SQL.zip](https://github.com/pluginsGLPI/formcreator/files/4984123/Error_Log_SQL.zip)

Merci encore.

**Comment by maules** [comment]
Pour info en mode debug le formulaire s'affiche correctement, mais je penses que vous le saviez deja.

**Comment by maules** [comment]
[Uploading Capture d’écran 2020-07-27 à 21.53.08.png…]()

**Comment by maules** [comment]
![Capture d’écran 2020-07-27 à 21 56 15](https://user-images.githubusercontent.com/68870559/88585938-0c468580-d054-11ea-9649-4d1ec121e5f0.png)

**Comment by btry** [comment]
Coté navigateur, l'erreur doit se trouver sur une requête vers le fichier showfields.php (de mémoire). Elle sera visible dans le corps HTTP de la réponse. Le code HTTP étant **200 OK** l'erreur est un peu difficile à localiser.

Le plus utile sera le log de glpi. La même erreur sera journalisée et il y a un backtrace, très utile pour identifier le bug.

**Comment by maules** [comment]
Info que j'ai omis précédemment je suis sur GLPI 9.4.2

Les logs que je vous ai envoyer ne sont pas bons?

Vous parler du fichier LOG tout court?

Merci infiniment de votre aide

**Comment by btry** [comment]
Bonjour

J'ai manqué la notification sur les logs. Je vais les examiner.

**Comment by btry** [comment]
Le message **Unknown column 'glpi_users_users_id_validator.id' in 'where clause'** montre que vous avez une incohérence entre la version du schéma (lea structure des tables) du plugin et la version du code du plugin.

Vérifiez la structure de table concernée et comparez la à la structure décrite dans le fichier .sql disponible dans le dossier install du plugin.

**Comment by maules** [comment]
Bonjour

Ok je vais regarder ca et vous tiens au jus.
Merci

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : btry <notifications@github.com>
Envoyé : Tuesday, July 28, 2020 12:16:09 PM
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : Mohamed BENKINIOUAR <mbenkiniouar@talentsoft.com>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Tout les formulaire ne s'affiche plus (#1898)


Le message Unknown column 'glpi_users_users_id_validator.id' in 'where clause' montre que vous avez une incohérence entre la version du schéma (lea structure des tables) du plugin et la version du code du plugin.

Vérifiez la structure de table concernée et comparez la à la structure décrite dans le fichier .sql disponible dans le dossier install du plugin.

**Comment by maules** [comment]
Bonjour btry,

J'espère que vous allez bien!

Je n'ai pas pu regarder l'incohérence en question car mon N+1 à fait une restauration du serveur à une version antérieure.
Du coup, le plugin fonctionne comme avant.
Je ne sais pas si je peux clôturer cette discussion.
Merci pour votre disponibilité et votre proactivité impressionnante 👍 

Cordialement,

**Comment by btry** [comment]
Bonjour

Je pense qu'on peut fermer et classer sans suite, puisque l'opportunité de trouver le problème est manquée. Merci pour votre retour.

**Comment by xdaftcraft** [comment]
Bonjour,

Je me permet de répondre ici, car j'ai exactement le même problème.
Cela est apparu sur une migration 2.9.2 --> 2.10

**Comment by xdaftcraft** [comment]
Bonjour,

Voici ce que nous avons sur la Réponse de la requête vers showfields.php 

![image](https://user-images.githubusercontent.com/17741063/92902248-655e5300-f421-11ea-9d7e-5a866c5344c1.png)

**Comment by btry** [comment]
Bonjour

Il ne devrait pas y avoir de valeur null; seulement true ou false. Il doit y avoir un problème pendant l'évaluation de vos conditions.

Toutes les questions ont un retour null dans votre JSON ? Vous devriez avoir au moins une question sans condition; et avoir une évaluation à null pendant l'évaluation de sa condition me permettra peut être de cibler une 30 aine de lignes de code où serait le bug.

**Comment by btry** [comment]
Hi

With @fralla2 I found you may have a bad DB schema.

Please read the issue #1941 to get instruction to check some tables of the plugin.

**Comment by btry** [comment]
Bonjour @xdaftcraft : vérifiez que la table glpi_plugin_formcreator_sessions contient une colonne show_rule. Si elle n'existe pas, ajoutez la comme décrit dans install/mysql/plugin_formcreator_empty.sql .

**Comment by btry** [comment]
Bonjour

A défaut de nouvelle, je ferme le ticket. Si il  ya besoin de reprendre le sujet, ilf audra chercher dans une incohérence de format des tables, visible en comparant les tables contenant une colonne show_field dans install/mysql/plugin_formcreator_empty.sql .
