### ISSUE TITLE
Performance issue with GLPI-object fields

### ISSUE THREAD

**Issue by Kahalisto** [pluginsGLPI/formcreator#190]
Bonjour,

Je suis face à un problème de performance lorsque dans un formulaire j'utilise le champ Object GLPI > Utilisateurs.
Ma liste d'utilisateurs est proche des 10000 répartis dans un peu plus de 150 entités.
Mon formulaire de test est créé sur l'entité racine et est visible dans les sous entités
Il ne contient qu'un seul champ, la liste déroulante utilisateurs.

Mon premier problème est que l'affichage même du formulaire est très lent.

Mon second problème est un freeze de plusieurs secondes lors que je souhaite utiliser le champ de recherche intégré dans la liste déroulante.

J'ai remarqué que le comportement des listes déroulantes ajoutées à un formulaire Formcreator ne se comportent pas de la même manière que celles présentent dans GLPI.

Par exemple dans un ticket lorsque je clique sur la liste déroulante pour ajouter un demandeur, celle-ci ne charge le contenu que lorsque je clique dessus
Dans Formcreator le contenu est déjà chargé au chargement de la page.

**Comment by btry** [comment]
Bonjour

Il semble que le problème ne soit plus d'actualité suite aux commits du 21/06/2016.
