### ISSUE TITLE
 Tickets with status 101 - Form 2.10.1 after update

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1902]
**Describe the bug**

When upgrading to Formcreator 2.10.1 the "status" column of the simplified interface receives the value "103" for some tickets

**To Reproduce**
1.log into the system
2. Click on My requests for assitance
3. see the tickets
4- see the error

**Expected behavior**
The status column should include "Processing", "Solved", "Closed" or "new"

**Screenshots**
See the ticket t_43666, have status "103"
![image](https://user-images.githubusercontent.com/35368369/88658624-1abf8c00-d0aa-11ea-8abc-78bc25e65803.png)

But on ticket he has status "Closed"
![image](https://user-images.githubusercontent.com/35368369/88658716-3f1b6880-d0aa-11ea-8eb1-db7bc19c2652.png)

In table "glpi_plugin_formcreator_issues"  have status "103"

![image](https://user-images.githubusercontent.com/35368369/88658805-670acc00-d0aa-11ea-8c14-4b22481f857c.png)

The "glpi_plugin_formcreator_formanswers" column also has several values ​​like 103 in the status column

![image](https://user-images.githubusercontent.com/35368369/88658933-a6391d00-d0aa-11ea-81d3-64d2f74b2e96.png)

But when looking at the ticket status in the glpi_tickets table the status is correct

![image](https://user-images.githubusercontent.com/35368369/88659055-ce288080-d0aa-11ea-977e-c0260960b92a.png)

GLPI 9.4.6
Formcreator 2.10.1

**Comment by btry** [comment]
Hi

it seems there (still) is some problems to render the status of the issues. I'll try to reproduce an submit a fix.

**Comment by phamorais** [comment]
Hi @btry 
Thank you very much.
How to update in production, unfortunately, I only noticed it 1 day after updating ... so I can't rollback.

But if you need to run a script you can let me know that I run in an approval environment.

**Comment by btry** [comment]
Hi

I foud the fix. Please apply the above patch then remove at least one line in the table **glpi_plugin_formcreator_issues**. Next, run the automatic action **Syncissues**. It will truncate and re-populate the whole table. The tickets using the apoval feature of GLPI should get the status 2 when they are approved, instead of 103.

This will fix the display of status, and this should be more consistent for the remaining of its file cycle.

**Comment by phamorais** [comment]
Hi @btry 

Thank you for your promptness. It worked perfectly for me.

![image](https://user-images.githubusercontent.com/35368369/88666154-0e413080-d0b6-11ea-8a91-5016c16c4aa0.png)

No Values with status 103 in "glpi_plugin_formcreator_issues"

![image](https://user-images.githubusercontent.com/35368369/88666194-21ec9700-d0b6-11ea-9cb6-fffeeb577a2c.png)

But in "glpi_plugin_formcreator_formanswers" still values 103. Is correct?

![image](https://user-images.githubusercontent.com/35368369/88666445-74c64e80-d0b6-11ea-80e4-68791e35bcb5.png)

**Comment by btry** [comment]
Yes : in the table glpi_plugin_formcreator_formanswers it is normal to have 103 as value. It means that a form answer has been accepted by a validator; this is not the same workflow as found in GLPI's tickets.

**Comment by phamorais** [comment]
@btry 


Sorry I'm late.

But I realized something. The change made placed status 2 for closed tickets

See the ticket "t_42512".

In the simplified version it is "Processing (assigned)"

![image](https://user-images.githubusercontent.com/35368369/88724428-d90e0000-d100-11ea-850b-e9d99c23fafa.png)

But when accessing the ticket, it is "closed"

![image](https://user-images.githubusercontent.com/35368369/88724583-24281300-d101-11ea-9631-4ae0a356d444.png)

Status 2 in the "glpi_plugin_formcreator_issues" table

![image](https://user-images.githubusercontent.com/35368369/88724630-373ae300-d101-11ea-9627-a4e241b6ad08.png)

But in glpi_tickets, have a correct status = 6

![image](https://user-images.githubusercontent.com/35368369/88724746-618ca080-d101-11ea-9fee-e003d89d3312.png)


commit applied in my environment

![image](https://user-images.githubusercontent.com/35368369/88724902-9ef12e00-d101-11ea-95c2-f082099af5b2.png)

**Comment by btry** [comment]
Hi

Good point. I think I can improve the SQL request to solve this. As I have other tasks right now, I think I'll submit an improvement friday or next week.

**Comment by phamorais** [comment]
@btry 

Thank u! I will wait
