### ISSUE TITLE
Access type - restricted rights (profile) checkbox always checked

### ISSUE THREAD

**Issue by R00t3n3d** [pluginsGLPI/formcreator#1912]
**Describe the bug**
Since the upgrade to Formcreator 2.10.1 from 2.9.1 with GLPI 9.5.1 :

In a form, when the access type is indicated on "restricted rights (profile)", the checkboxes allowing to select profiles with or without authority to view the form all appear checked.

Even when I uncheck them and save, they all come back checked.

But: The restriction works fine. In other words, it is only the display that is wrong and not the operation behind it.

This is problematic, however, because it is impossible to know at a glance which profile has access to the form. 

**To Reproduce**
1. Go to "Administration > Forms"
2. Chose or create one
3. Go to "Access type"
4. Choose "restricted rights (profile)"
5. Uncheck a box and save
6. See error

**Expected behavior**
When a checkbox is unchecked and the form is saved, the checkbox should no longer be checked.

**Screenshots**
![image](https://user-images.githubusercontent.com/46027518/89754950-fb7b2280-dadd-11ea-9eac-c9888e99dd4d.png)

**Desktop (please complete the following information):**
OS: Win 10
Browser Brave, Firefox, Chrome
Chromium: 84.0.4147.105 (Build officiel) (64 bits)

**Additional context**
Formcreator 2.10.1
GLPI 9.5.1

**Comment by btry** [comment]
Hi

Can you try this fix ? 1c0d27d5

**Comment by btry** [comment]
Duplicate of :  https://github.com/pluginsGLPI/formcreator/issues/1887

**Comment by R00t3n3d** [comment]
Works great, thanks!
