### ISSUE TITLE
Importer un formulaire avec un nom déjà existant et supprimé fusionne le nouveau sur l'ancien

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1913]
**Describe the bug**

[Edit]
Quand on importe un formulaire dans une système qui comporte déjà un formulaire de même nom mais qui est supprimé, ça les fusionne ! Tous les champs (questions) du formulaire importé sont ajoutés à la fin du formulaire (questions) qui était supprimé, et toute la définition du formulaire (entête) est remplacée selon le formulaire importé.
[/Edit]

**To Reproduce**
Choisir un formulaire, l'exporter. 
Mettre dans la corbeille le formulaire exporté.
Importer le formulaire.
Constater dans "questions" que toutes les questions sont en double (dans le cas cité).

**Expected behavior**
Le formulaire supprimé devrait rester supprimé, et un nouveau devrait être créé.

**Additional context**
GLPI 9.4.6 + FC 2.9.2(plus correctifs)

**Comment by btry** [comment]
Bonjour

Les objets qui composent un formulaire contiennent une colonne uuid. C'est sur la correspondance entre l'UUID des formulaires en base de données et l'UUID contenu dans le fichier d'export qui permet de déterminer si il faut créer un formulaire ou bien le mettre à jour.

Tous les objets constituant un formulaire (sections, questions, conditions, ticket cible, changement cible) possèdent aussi un uuid pour que la correspondance puisse se faire à leur niveau de la même manière.

Dans vote cas vous avez 2 formulaires A et B. Si B est importé et écrase / modifie A, alors c'est que B est d'une certaine manière uen copie de A. Cela peut arriver si B est créé par recopie de la BDD sur une autre instance de GLPI, ou si B est créé sur un autre GLPI par import de A.

En revanche, quand vous dupliquez un formulaire au sein d'une instance de GLPI, les UUID de tous les objets sont recréés pour être uniques.

Le fait qu'un formulaire soit dans la corbeille ne constitue pas d'exception au traitement d'import.

A priori, il n'y a pas de bug, le comportement observé est celui attendu. Vous pouvez vérifier l'UUID dans le fichier .json avec l'UuID du formulaire en base de données. Ils devraient être les mêmes.

**Comment by mab18** [comment]
D'accord, 8-) c'est juste troublant.
Je ne savais pas que l'import pouvait provoquer une mise à jour d'un formulaire (définition) ET ajout (questions)... et donc une fonctionnalité.
Pour moi, c'était un import = création d'un nouveau.

**Comment by btry** [comment]
J'ai complété la documentation du plugin : https://github.com/pluginsGLPI/doc/pull/44

Vi qu'il n'y a pas de bug, je ferme le ticket.
