### ISSUE TITLE
Bug migration Form Creator 

### ISSUE THREAD

**Issue by JeanBonDeParme** [pluginsGLPI/formcreator#1919]
Bonjour,

Suite à la maj 9.5.1, j'ai plus l'ancien répertoire formcreator. je souhaite donc installer la nouvelle version, j'ai une erreur:

**Expected behavior**

**Cela reste figé sur : Upgrade glpi_plugin_formcreator_questions_conditions**

**En cli j'ai lancé le : ./scripts/cliinstall.php**

./scripts/cliinstall.php: ligne 1: ?php: Aucun fichier ou dossier de ce type
./scripts/cliinstall.php: ligne 2: /bin : est un dossier
./scripts/cliinstall.php: ligne 3: ajax : commande introuvable
./scripts/cliinstall.php: ligne 4: ajax : commande introuvable
./scripts/cliinstall.php: ligne 5: ajax : commande introuvable
./scripts/cliinstall.php: ligne 6: ajax : commande introuvable
./scripts/cliinstall.php: ligne 7: ajax : commande introuvable
./scripts/cliinstall.php: ligne 8: ajax : commande introuvable
./scripts/cliinstall.php: ligne 9: ajax : commande introuvable
./scripts/cliinstall.php: ligne 10: ajax : commande introuvable
./scripts/cliinstall.php: ligne 11: ajax : commande introuvable
./scripts/cliinstall.php: ligne 11: you : commande introuvable
./scripts/cliinstall.php: ligne 12: ajax : commande introuvable
./scripts/cliinstall.php: ligne 13: ajax : commande introuvable
./scripts/cliinstall.php: ligne 13: either : commande introuvable
./scripts/cliinstall.php: ligne 14: erreur de syntaxe près du symbole inattendu « at »
./scripts/cliinstall.php: ligne 14: ` * (at your option) any later version.'

**LOG de migration to 2.10.1:**

2020-08-17 09:05:23 [2***]
0 seconde for "Traitement en cours..." @ 2020-08-17 09:05:23 [2***]
0 seconde for "Upgrade to schema version 2.5" @ 2020-08-17 09:05:23 [2***]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2020-08-17 09:05:23 [2***]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2020-08-17 09:05:23 [2***]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-08-17 09:05:23 [[2***]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-08-17 09:05:23 [2***]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-08-17 09:05:25 [[2***]
2 secondes for "Upgrade glpi_plugin_formcreator_forms" @ 2020-08-17 09:05:25 [2***]
0 seconde for "Drop glpi_plugin_formcreator_headers" @ 2020-08-17 09:05:26 [2***]
1 seconde for "Upgrade glpi_plugin_formcreator_issues" @ 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian 9

Que serait la manip? 
Merci

**Comment by btry** [comment]
Bonjour

A priori vous avez lancé le script d'installation / upgrade en CLI sans l'interpréteur PHP.

A supposer que votre répertoire courant est le dossier du plugin, réessayez ceci:
```sh
php scripts/cliinstall.php
```

**Comment by JeanBonDeParme** [comment]
Effectivement.

Donc: Installing Plugin Id: 23 version 2.10.1...

En Gui, j'ai toujours le bouton "installer" actif

Il y a une autre manip?

**Comment by btry** [comment]
L'installateur en mode CLI va jusqu'à activer le plugin pour vous. Il n'y a pas eu d'erreur avec un backtrace à l'écran ? Avez vous vérifié le fichier glpi/files/_log/migration_to_2.10.1.log ? (2.10.1 est à remplacer par la version courante du plugin)

**Comment by btry** [comment]
Je réalise que vous semblez upgrader depuis une version antérieure à 2.5.0. Est bien le cas ?

**Comment by JeanBonDeParme** [comment]
Non, pourtant le nom du fichier de log migration_to_2.10.1.log ..

**Comment by btry** [comment]
Bonjour

Je ne sais pas à quelle question vous répondez "non".

J'ai besoin d'avoir les réponses à toutes mes question pour trouver une solution.

Vu la nature du plantage, je vous invite aussi à vérifier votre version de PHP. GLPI 9.5 requiert PHP 7.2+ et GLPI 9.4 requiert PHP 5.6+.

**Comment by JeanBonDeParme** [comment]
Bonjour,

Nous sommes sur glpi 9.5.1 et php 7.4 .

Voici le fichier : migration_to_2.10.1.log

2020-08-18 11:22:52 [[2@**]
0 seconde for "Traitement en cours..." @ 2020-08-18 11:22:52 [2@**]
0 seconde for "Upgrade to schema version 2.5" @ 2020-08-18 11:22:52 [2@**]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2020-08-18 11:22:52[2@**]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2020-08-18 11:22:52 [2@**]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-08-18 11:22:53 [2@**]
1 seconde for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-08-18 11:22:53 [2@**]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-08-18 11:22:53 [2@**]
0 seconde for "Upgrade glpi_plugin_formcreator_forms" @ 2020-08-18 11:22:53 [2@**]
0 seconde for "Drop glpi_plugin_formcreator_headers" @ 2020-08-18 11:22:56 [2@**]
3 secondes for "Upgrade glpi_plugin_formcreator_issues" @

**Comment by btry** [comment]
Quelle était la version de formcreator avant la tentative d'upgrade ?

**Comment by JeanBonDeParme** [comment]
en v2.8.2

**Comment by btry** [comment]
Donc il y a un problème : l'installateur tente de faire un upgrade à partir d'une version encore plus ancienne. 

Pouvez vous montrer le résultat de la requête SQL suivante ?
```sql
SELECT * FROM glpi_configs WHERE context='formcreator';
```

**Comment by JeanBonDeParme** [comment]
est ce ok? :/

MariaDB [glpi]> SELECT * FROM glpi_configs WHERE context='formcreator';
Empty set (0.00 sec)

**Comment by btry** [comment]
Ce n'est pas bon. En version 2.8 le nouveau système d'upgrade était en place.

Il y a eu quelques bugs sur ce système à ses débuts, mais en 2.8, de mémoire, il n'y avait plus de problème particulier.

la table glpi_configs devrait contenir une ligne avec context='formcreator', name='schema_version' et value='2.8'. 

Je vous conseille de créer un GLPI de test contenant uen copie stricte des fichiers et de  la base de données de votre instance en panne. Ensuite, faites un snapshot de la BDD, vers lequel vous pourrez revenir librement jusqu'à avoir mis au point la procédure d'upgrade pour votre situation. Cette instance devra contenir Formcreator 2.10., la version que vous voulez obtenir.

Recréez la ligne manquante dans **glpi_configs**

```sql
INSERT INTO `glpi_configs` (`context`, `name`,`value` ) VALUES ('formcreator', 'schema_version', '2.8');
```

Ensuite relanez le processus d'upgrade avec l'outil d'upgrade en ligne de commande. L'upgrade doit commencer à la version 2.8.   Dans la sortie de la commande vous ne devez pas voir une ligne comme celle ci
```
0 seconde for "Upgrade to schema version 2.5" @ 2020-08-17 09:05:23 [2***]
``` 
contenant une version inférieure ou égale à 2.8. La première de ces lignes doit mentionner la version 2.9.

**Comment by JeanBonDeParme** [comment]
Bonjour, c'est fonctionnel ! dans l'interface plugins la dernière version est installée/active, par contre j'ai pas les droits pour créer, 
dans administration j'ai rien trouvé..

**Comment by btry** [comment]
Pour avoir le droit de créer des formulaires dans l'administration vous avez besoin du droit de modification des entités. Vérifiez votre profil. Si vous ajoutez le droit, fermez puis rouvres votre session (logout/login) pour appliquer le changement.

**Comment by JeanBonDeParme** [comment]
Merci de votre disponibilité et de votre aide.
