### ISSUE TITLE
conditions d'affichage impossible à supprimer et inopérantes

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1920]
Bonjour, 
**Describe the bug**
J'ai transféré un formulaire assez sophistiqué d'un environnement vers un autre, sur la cible, les conditions d'affichage des **sections** sont toutes inopérantes et il est impossible de les changer.
Quelle que soit la condition (toujours visible/masqué.../affiché...) , que je supprime la condition ou pas, elle se ré-affiche, et de toutes façons, ça reste inopérant.
Il est impossible d'ajouter une condition supplémentaire.
cliquer sur supprimer l'enlève à l'écran, mais réapparaît dès qu'on revient dessus.
Je ne comprends pas vraiment l'incidence du changement d'environnement, et c'est même pas certain que ce soit lié.
Ca fonctionne sans problème pour l'affichage des champs.

[edit]
Je me rends compte que l'ensemble du formulaire est totalement inactif (on ne peut même pas saisir, les boutons radio fonctionnent)
[/edit]

**To Reproduce**
exporter/importer sur un autre environnement.

**Expected behavior**
Pouvoir modifier ces conditions.

**Additional context**
GLPI 9.4.6 / FC 2.9.2+correctifs

**Comment by btry** [comment]
Bonjour

Je vous recommande de passer à Formcreator 2.10.1. Il y a eu des corrections sur des anomalies d'édition des conditions. Par contre, pas de souci majeur sur leur comportement depuis 2.9.2.

**Comment by mab18** [comment]
J'upgrade en 2.10.1

**Comment by mab18** [comment]
Voilà, c'est parfait ! J'ai pu corriger avec cette version 2.10.1 le bug ci-dessus décrit.

:-)

**Comment by btry** [comment]
Merci pour votre retour.
