### ISSUE TITLE
Perte des forms suite a la mise a jours 9.5.0

### ISSUE THREAD

**Issue by benoooo85** [pluginsGLPI/formcreator#1921]
**Describe the bug**
Bonjour a tous,

Suite a la mise a jours 9.5 j'ai du reinstaller FormCreator et comme un champion je n'ai pas exporté mes forms avant l'update et la reinstallation du plugin form creator. Je me suis apercu trop tard de la perte de mes forms.

Je souhaiterais savoir si il y a possibilité de retrouver les forms créé. Je suis sous windows et MySQL et j'ai des backups (folder et files) de mon GLPI avant la mise a jour. Ya t'il un endroit ou sont stocké les forms ? j'ai fait une recherche *.json mais je n'ai rien trouvé.

J'espere avoir ete clair.
Merci pour votre aide.

**To Reproduce**
Update 9.4.3 to 9.5
desinstaller et supprimer le plugin FormCreator
Reinstaller la version compatible de FormCreator pour GLPI 9.5

**Expected behavior**
Comment retrouver mes forms dans mes backup fait sous windows (Copie du repertoire GLPI)

**Desktop (please complete the following information):**
 - OS: Windows 2016 Server Standard
 - Browser: Chrome
 - Version : 9.4.3 to 9.5

**Comment by btry** [comment]
Bonjour

Les formulaires sont stockés en base de données.

Voici une procédure à valider sur une instance de test.

Restaurée et écrasez les tables commençant par glpi_plugin_formcreator_ par celles venant de votre backup. 

Dans la table glpi_configs, vous trouverez une ligne correspondant à la requête suivante 

Select * from glpi_configs where context='formcreator';

Void trouverez une ligne indiquant la version des tables du plugin en BDD. Ajoutez cette ligne dans votre instance à restaurer, sans spécifier la colonne ID (elle est automatique).

Ensuite, étant donné que vous avez la dernière version du plugin, vous n'avez plus qu'à faire un upgrade via GLPI ou via le script CLI dans le dossier scripts du plugin : cliinstall.php

Une fois la procédure validée, vous pourrez ma recommencer sur votre prod.

**Comment by btry** [comment]
Note : pour upgrader glpi, il ne faut pas désinstaller les plugins. La désactivation suffit, et elle est faite automatiquement par glpi pendant son processus d'upgrade.

**Comment by benoooo85** [comment]
Merci pour votre reponse rapide.
Bonne journee
