### ISSUE TITLE
 Form question filter by group.

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#1924]
Good afternoon,

I have a question, it is possible to perform the validation / filter of one form per group. Example: I have a form with several support request items, but the item "request permission to access folders" I need to be used only by users who belong to the group "manages". Is there any way to perform this filter?
NOTE: I use GLPI 9.5.1 and formcreator 2.10.1.
Thank you very much

**Comment by btry** [comment]
Hi

No, this is currently not supported. You may workaround by creating a distinct form reserved to the profile of users granted to do this kind of request.

**Comment by TR0LLL** [comment]
Thanks for the quick response. I will try to segment the service in another form. If there is a possibility to insert this function in the next versions, I thank you very much.
See you and good work!

**Comment by btry** [comment]
Having conditions on items in question types checkboxes, radios, select and multiselect is quite complex. This might make the plugin too complex for things rarely used. This is also complex to develop as this requires a deep rework on the code of these question types

Is this is really needed, you may consider to sponsor this feature.
