### ISSUE TITLE
Start GLPI in the Forms tab

### ISSUE THREAD

**Issue by darthjuanan** [pluginsGLPI/formcreator#1925]
Hi everybody!

I'm trying to use Forms with the **self-service profile**, and I don't know how to **set the "_Forms_" tab as the welcome page** to the user.

Is any way to do this? Anybody has done?

Thanks in advance!!

**Comment by btry** [comment]
Hi

The welcome page you're talking about is probably central.php .

There is no way to force the forma tab to be active. For self service users, the plugin provides its own UI names service catalog. You may want to test it. Enable it by editing an entity (root maybe ?). In the tab Forms, switch to service catalog simplified or service catalog extended.

**Comment by btry** [comment]
Hi

Having no news, I assume your problem is solved.
