### ISSUE TITLE
fail in attachement mandatory

### ISSUE THREAD

**Issue by elazarine** [pluginsGLPI/formcreator#1927]
this attachment file recognition is not required. Although the file to be attached is included, the message appears that it is mandatory to include an attachment.

**Comment by btry** [comment]
Hi

Please try the support/2.10.0 branch and tell if the bug is still here.

**Comment by Nuysaki** [comment]
Hi,
I've the same problem.

Formcreator 2.10.1, GLPI 9.5.1 and 9.4.5
When mandatory is off, attachement is working

**Comment by btry** [comment]
Hi @Nuysaki 

Can you test the latest revision of the plugin and feedback ?

**Comment by Nuysaki** [comment]
I'm already in 2.10.1
Is there an other official version?

**Comment by btry** [comment]
Not new release yet. I want to release a maintenance release within 2 weeks.

Please try the version below. This is the current revision of the branch support/2.10.0. In short this is the future 2.10.2. Do not forget to use it on a testing environment !

[glpi-formcreator-2.10.2-dev.zip](https://github.com/pluginsGLPI/formcreator/files/5156087/glpi-formcreator-2.10.2-dev.zip)

**Comment by Nuysaki** [comment]
It's ok with this one 👍

**Comment by btry** [comment]
Nice; thank you for your feedback. We can close this issue.
