### ISSUE TITLE
 linking with Item Management > Lines does not work V2.9.2, 2.10 and 2.10.1

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1928]
Hi!!

I'm trying to automatically link a GLPI item to the ticket at the opening.

For that, I registered the item in Management > Lines

![image](https://user-images.githubusercontent.com/35368369/91767212-2d017e00-ebb2-11ea-94ee-36cea379d4a2.png)

I created the form, and in Targets, I'm trying to use the option "Associated elements" with the value "Equals to the answer to the question".

![image](https://user-images.githubusercontent.com/35368369/91767397-7651cd80-ebb2-11ea-91e7-bf3a04d00dd3.png)

I open the ticket by selecting the desired option

![image](https://user-images.githubusercontent.com/35368369/91767638-da749180-ebb2-11ea-8ac2-1c1331e54784.png)

However, the ticket is opened without making the relationship

![image](https://user-images.githubusercontent.com/35368369/91767724-fd9f4100-ebb2-11ea-8c24-761e8f4f4307.png)

The expected behavior was that the ticket was opened with the item relating

![image](https://user-images.githubusercontent.com/35368369/91767844-2cb5b280-ebb3-11ea-8fc1-be429fd67175.png)

GLPI 9.4.6
Formcreator 2.9.2 and 2.10 and 2.10.1

**Comment by btry** [comment]
Hi

Please check that the itemtype **lines** is added to the associatable itemtypes of your profile, in Administration > Profiles > tab Assistance.

On my side, the line is properly added to the ticket and is visible in the list.

**Comment by phamorais** [comment]
Hi!

That was exactly it! Thank you very much, I'm sorry for the inconvenience
