### ISSUE TITLE
Impossible de modifier le demandeur à la création du ticket

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/formcreator#193]
Bonjour,

Quand je créé des tickets à partir de formulaire, ceux-ci sont sans demandeur. J'ai trouvé le paramétrage sur Formcreator mais quand j'essaie de sélectionner le demandeur est "Demandeur du formulaire", la modification est prise en compte mais il n'y a pas de changement sur le paramétrage.

J'ai trouvé une erreur dans les logs : la voici : 
2016-02-26 16:14:05 [420@SRV]
  *** MySQL query error:
  SQL: INSERT INTO glpi_plugin_formcreator_targettickets_actors SET
                  `plugin_formcreator_targettickets_id` = 2,
                  `actor_role`                          = \"requester\",
                  `actor_type`                          = \"creator\",
                  `actor_value`                         = \"\",
                  `use_notification`                    = \"1\"
  Error: Incorrect integer value: '' for column 'actor_value' at row 1
  Backtrace :
  plugins\formcreator\front\targetticket.form.php:35 

Ce problème est également valable pour "valideur du formulaire" que ce soit en demandeur, en observateur ou en technicien.

J'ai cherché un problème similaire mais je n'ai pas trouvé.
Voici les informations de mon environnement : 
GLPI V0.90
Formcreator 0.90-1.3.3
Mysql 5.7
Apache 2.4
PHP 7
Windows Server Datacenter 2012

Merci d'avance pour votre aide.
Cordialement.

**Comment by usrqmor** [comment]
Bonjour,

J'ai trouvé d’où venait le problème.En mettant  à jour mon fichier targetticket.form.php dans le dossier front de formcreator, le problème est corrigé.

Cordialement.

**Comment by btry** [comment]
Hi 

Nice you found a working fix. Can you share the change you did ?

**Comment by usrqmor** [comment]
Hi,

My solution was to change the file targetticket.form.php in my repertory glpi/plugin/formcreator/front by this version of [targetticket.form.php](https://github.com/pluginsGLPI/formcreator/blob/master/front/targetticket.form.php).

Regards
