### ISSUE TITLE
Condition pour afficher la cible - comportement bizarre

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1930]
Bonjour,
***Describe the bug**
Quand on créé un formulaire et qu'on ajoute une cible, cliquer sur la liste de condition pour afficher la cible laisse apparaître un comportement bizarre dans les conditions : 

**To Reproduce**
Créer un formulaire, une question/une section (pas testé autre)
Créer une cible, aller à conditions d'affichage de la cible, cliquer sur "masqué par défaut", puis sur "affiché par défaut", recommencer.
Une condition vierge s'ajoute à chaque fois.

**Expected behavior**
Aucune condition ne devrait s'ajouter sans arrêt.

**Screenshots**
![animation_comportement_bizarre_fc_cible](https://user-images.githubusercontent.com/55535560/91852740-8b396a00-ec61-11ea-8e30-c8470983ae2a.gif)

**Additional context**
GLPI 9.4.6+FC2.10.1

**Comment by Nuysaki** [comment]
@btry Ce bug est corrigé dans la version 2.10.2-dev

**Comment by btry** [comment]
Bonjour,

De mémoire, j'ai fait une correction mineure sur les conditions.

@mab18 pouvez vous tester la dernière révision de la branche support/2.10.0 pour confirmer la résolution du bug ?

**Comment by btry** [comment]
J'ai donné un build en ZIP cette semaine dans un des derniers tickets fermés. Évidemment, je n'ai pas le numéro sous la main... 

Sinon, vous pouvez sélectionner la branche support/2.10.0 dans l'onglet code, puis cliquer sur le bouton download pour récupérer les sources brutes. Cette archive a besoin de fichiers supplémentaires dans le dossier data. Pour faire simple, prenez les fichiers .php provenant de votre version actuelle.

**Comment by btry** [comment]
Bonjour

Voilà une archive de la branche support/2.10.0 . Merci de faire un retour avec cette version.

[glpi-formcreator_2.10.2-dev.zip](https://github.com/pluginsGLPI/formcreator/files/5173354/glpi-formcreator_2.10.2-dev.zip)

**Comment by btry** [comment]
Bonjour @mab18 

La release 2.10.2 a été publiée, si vous avez upgradé, avez vous vérifié si le bug persiste ?

**Comment by mab18** [comment]
Bonjour,

Ce problème est corrigé !
Quel talent ! 😉

**Comment by btry** [comment]
Bonjour

Merci pour le retour; je ferme.
