### ISSUE TITLE
## FULLFORM ## including empty sessions

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#1931]
**Describe the bug**

Good Morning,

In the new version of the plugin, the destination field ## FULLFORM ## is including those sessions that have no response causing the open ticket to be very polluted.

![image](https://user-images.githubusercontent.com/42414051/92122247-97dcd000-edd1-11ea-87bf-56c9bd2861f8.png)

GLPI Version: 9.5.1
Plugin Version: 2.10.1

**Comment by btry** [comment]
Hi

Please test the latest revision of the support/2.10.0 branch. If I remember well, this is already fixed.

**Comment by TR0LLL** [comment]
I tested and in version 2.10.0 this problem does not happen.

**Comment by btry** [comment]
The branch support/2.10.0 contains all releases 2.10.x and is currently 2.10.2-dev. Then I guess you mean 2.10.2-dev ?

**Comment by btry** [comment]
Hi

Can you clarify the version you used ?

**Comment by TR0LLL** [comment]
Hello,
the problem was happening in version 2.10.1
I installed the latest version 2.10.2 and the problem has been resolved.
