### ISSUE TITLE
Question type "GLPI object" does not list all entities

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1936]
Hello!
In the question on the form I offer the list of all entities.

![image](https://user-images.githubusercontent.com/35368369/92942274-bd985380-f427-11ea-8b07-6256a62fdba9.png)

I have 318 entities

![image](https://user-images.githubusercontent.com/35368369/92942400-dbfe4f00-f427-11ea-9265-a5eba3a29865.png)

However, in the formulary not all entities are offered

![image](https://user-images.githubusercontent.com/35368369/92942744-3eefe600-f428-11ea-9afa-6e47d9474478.png)

Even if I type the name it doesn't find

![image](https://user-images.githubusercontent.com/35368369/92942841-5e870e80-f428-11ea-8a51-4e69ad720dbc.png)

Even though the entity is registered with the GLPI

![image](https://user-images.githubusercontent.com/35368369/92942927-7ced0a00-f428-11ea-9b0c-ff8b656150ad.png)

GLPI 9.4.6
Formcreator 2.10.1

**Comment by btry** [comment]
Hi

Is your user in the root entity ? If not, check if the displayed entities are all under the current entity, and the user has recursive access enabled (you can see it in the top right corner).

**Comment by phamorais** [comment]
Hello @btry 

Yes, even the print I took was with the Super-admin profile

![image](https://user-images.githubusercontent.com/35368369/92945237-61cfc980-f42b-11ea-83c1-b358eedd47c5.png)

The forms are in the ROOT Entity, and marked as recursive

![image](https://user-images.githubusercontent.com/35368369/92945465-ae1b0980-f42b-11ea-8bbb-42cf37b9bd69.png)


The structure looks like this:

![image](https://user-images.githubusercontent.com/35368369/92945724-0f42dd00-f42c-11ea-83b5-db437b4ac168.png)

All forms are in the ROOT entity


![image](https://user-images.githubusercontent.com/35368369/92945944-63e65800-f42c-11ea-8015-50dc1e655a05.png)

**Comment by btry** [comment]
Be careful : being super admin is not as being root under Linux. A user may be super-admin and locked in a subset of the existing entities.

Also, this is not the entity of the form which is important, but the current entity of the user. Like I said, you must check the current entity of the user displayed in top right corner (where you select your current entity). 

On my side, I need to check the source code to verify if there is the restriction I expect to find on the available entities I the dropdown.

**Comment by phamorais** [comment]
Hello! @btry 

The print I sent is with my Super-admin user.

Ticket analysts have another profile, in which I make all the necessary limitations.

However, both with my "super-admin" profile and the "attendant" profile the limitation of the list occurs.

**Comment by btry** [comment]
Hi

Please show the very top of the list in the entities dropdown. I want to check if there are some entities written in gray color.

![image](https://user-images.githubusercontent.com/14139801/93081661-e3c02c80-f68f-11ea-8119-e2cf493810a3.png)

**Comment by phamorais** [comment]
@btry HI!

![image](https://user-images.githubusercontent.com/35368369/93081902-5caa8e80-f666-11ea-86cc-86ea3e55da1c.png)

**Comment by btry** [comment]
Are all your entities children of  Wexxx > NOC ?

**Comment by phamorais** [comment]
@btry In that case Yes.

WEB -> my company name;
NOC -> IT Area
NOC> Area 1, Area 2 -> My IT clients

**Comment by btry** [comment]
Please patch Formcreator with the following patch, try again, and show what is written in php-errors.log.


[formcreator_debug_1936.txt](https://github.com/pluginsGLPI/formcreator/files/5218353/formcreator_debug_1936.txt)

Once done, you may revert the patch.

**Comment by phamorais** [comment]
@btry 

Sorry for my ignorance, but how do I apply this patch?

**Comment by btry** [comment]
You need the patch tool.

To use it, go to the directory of for creator

cd GLP/plugins/form creator

Next, run the patch tool

patch -p1 < /path/to/patch_or_diff_file

Carefully read the output.

You may dry run the patch by adding --dry-run to the above command.

To remove the patch, add -R to the above command.

As the patch is just an extra line you may open it, read it and add the line beginning with the + sign.

Understanding the format of the patch is quite easy.

**Comment by phamorais** [comment]
@btry 
I ran it directly on the code. The "result.txt" I posted above was not the result you expected?

**Comment by btry** [comment]
Hi

I saw a post where you asked how to apply the patch. I guess you edited / deleted it after finding a solution yourself.

I checked your file, and it contains the expected result, but there are several questions of type Dropdown / Glpi Object in your form. 

I guess the question ID relateds to your issue is 31. If I'm right, there is no condition limiting the available entities. The plugin runs as expected here, and I don't see right now what happens. 

I suggest to compare with an other entities dropdown in somewhere having GLPI the same user context. If there is a filtering added by GLPI, having the same result will show the evidence.

**Comment by phamorais** [comment]
@btry ,
Thank you for your promptness!
After your feedback I found this option on my GLPI

![image](https://user-images.githubusercontent.com/35368369/93216379-09a40a80-f73e-11ea-97b9-41b11e76a7b8.png)


It was marked for 30 items, a fact that caused only 30 items to appear in the list. After changing the value to 200 the incident was resolved

**Comment by btry** [comment]
Hi

This ils interesting. The search feature in the dropdown should be able to select items not visible in the liar, and this list should dynamically update.

Can you revert to 30 items and check if you have some JS errors in the browser ?

**Comment by phamorais** [comment]
Hi @btry 

Sorry for the delay, I hadn't seen the notification.

Follows console errors. The console displays the same information with a limit of 30 or 200

![image](https://user-images.githubusercontent.com/35368369/94011368-a0e01200-fd7d-11ea-9873-181e73558e67.png)

**Comment by phamorais** [comment]
@btry 

If you are not investigating anything further, we can download this issue

**Comment by btry** [comment]
Hi

I'm currently working on an other project. Please be patient, and dont't close this issue.

**Comment by btry** [comment]
Hi @phamorais : no JS error  related t your issue. If you try to scroll down the list of the dropdown, this should triger a HTTP request to load more items. Could you check it and verify in the dev tools of your browser if you have a request to getDropdownValue.php ?

**Comment by phamorais** [comment]
@btry 
Hi!
If I limit the number of items in Setup> General Setup> Page size for dropdown (paging using scroll) I have this on the console


![image](https://user-images.githubusercontent.com/35368369/96719585-f5c47780-137f-11eb-9965-d302efcddc51.png)

![image](https://user-images.githubusercontent.com/35368369/96719612-ff4ddf80-137f-11eb-8cd3-ee25f0bb7500.png)

![image](https://user-images.githubusercontent.com/35368369/96719641-08d74780-1380-11eb-9a9d-4517bf9cc6ed.png)

**Comment by btry** [comment]
Hi

I(m rereading this issue.

I said the following in the  thread

> this is not the entity of the form which is important, but the current entity of the user. Like I said, you must check the current entity of the user displayed in top right corner (where you select your current entity).


This will change in the version 2.11.0 : items will be filtered depending on the entity of the form. See #2023 .

I don't see what could happen in your case. I would suspect an corrupted JSON response due to a special char, but I think this would trigger a JS error.If you still need help, please check the name of the items. Let me know if you find chars that could cause problems (accented chars, special chars, ...)

**Comment by phamorais** [comment]
no longer needed
