### ISSUE TITLE
file print_form.css not found + disappearing forms

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/formcreator#1941]
**Describe the bug**
I'm having problem displaying forms on glpi 9.5.1 with the plugins installed from marketplace.
It might be related to #1898 

The plugins load correctly and I can navigate to all menu sections (Form, Questions, Access, Target, Answers and History) but when I try to access the preview page, I see the full form displaying for half a second, then it dissapears and only the title and the submit button stay displayed

The error message I get from Chrome debug is the following : 

GET https://GLPISERVERADDRESS/glpi-9.5.1-fix/glpi-9.5.1-fix/marketplace/formcreator/css/print_form.css?v=9.5.1 net::ERR_ABORTED 404 (Not Found)

Note : the file exists but the path is wrong because the "glpi-9.5.1-fix" part is repeated twice (in normal install that would translate to GLPISERVERADDRESS/glpi/glpi/markerplace.......

**To Reproduce**
- Install GLPI-9.5.1
- Install the version 2.10.2 of formcreator from GLPI marketplace
- Go to Administration -> Forms
- Open a form and try to preview it
- Same happens when displaying an active form from Helpdesk -> Forms menu

**Expected behavior**
Show the form preview and not hide it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Google Chrome 84.0.4147.135

**Comment by fralla2** [comment]
![image](https://user-images.githubusercontent.com/38400135/93518055-4ddc0a00-f8fa-11ea-9b1c-8030f9cbf447.png)

![image](https://user-images.githubusercontent.com/38400135/93518166-749a4080-f8fa-11ea-81bb-78adc5a5d0f4.png)

**Comment by fralla2** [comment]
![image](https://user-images.githubusercontent.com/38400135/93518283-9abfe080-f8fa-11ea-9024-f1fd3de45ba4.png)

![image](https://user-images.githubusercontent.com/38400135/93518407-c2af4400-f8fa-11ea-8053-39ed01a1d451.png)

**Comment by btry** [comment]
Hi

Please try the above patch and feedback.

**Comment by fralla2** [comment]
That fixed the error in the debug for file missing so your fix is working but the firm still hides wich is probably related to something else....

I'll try to find more logs but haven't found anything meaningful yet except this css file error ;)

**Comment by fralla2** [comment]
Ohhh I found this in the /var/log/httpd/ssl_error_log

`PHP Notice:  Undefined index: show_rule in /var/www/html/glpi-9.5.1-fix/marketplace/formcreator/inc/fields.class.php on line 166, referer: https://GLPISERVER/glpi-9.5.1-fix/marketplace/formcreator/front/formdisplay.php?id=1
`

**Comment by btry** [comment]
Ok ,then I can validate the patch for CSS.
The PHP wqrning you spotted may cause the form to completely hide. Can you check in the dev tools of your browser if the JSON returned by the call to showfields.php contains null values ?

**Comment by fralla2** [comment]
![image](https://user-images.githubusercontent.com/38400135/93523186-ae6e4580-f900-11ea-8257-1bb4a418ab1c.png)

![image](https://user-images.githubusercontent.com/38400135/93523563-3a806d00-f901-11ea-9e7d-9200247c71ed.png)



PluginFormcreatorForm: true
PluginFormcreatorQuestion: {1: null, 2: null, 3: null, 4: null, 5: null, 7: null, 8: null, 9: null, 10: null, 11: null, 12: null,…}
1: null
2: null
3: null
4: null
5: null
7: null
8: null
9: null
10: null
11: null
12: null
14: null
15: null
16: null
17: null
20: null
21: null
22: null
23: null
24: null
25: null
26: null
PluginFormcreatorSection: {1: null, 2: null, 3: null, 6: null}
1: null
2: null
3: null
6: null

**Comment by btry** [comment]
Hi

Please check in the following tables if the column show_rule exists :

Glpi_plugin_formcreator_forms
Glpi_plugin_formcreator_sections
Glpi_plugin_formcreator_questions
Glpi_plugin_formcreator_targettickets
Glpi_plugin_formcreator_targetchanges

**Comment by fralla2** [comment]
Only missing in Glpi_plugin_formcreator_sections

![image](https://user-images.githubusercontent.com/38400135/93594926-bff93100-f984-11ea-9b3f-3217edd49d8e.png)

**Comment by btry** [comment]
Ok, then please, take a backup of the DB. I want to investigate with you to find whi this column is missing.

Next, fix yout table by adding the column show_rule. You can find the structure of the table in the file install/mysql/plugin_formcreator_empty.sql

Once the issue solved, let's search how this happened. You told you installed the plugin from the marketplace. Before installing it, were you using a previous version of the plugin ? Maybe a version you downloaded from Github ?

**Comment by fralla2** [comment]
Should I backup the whole GLPI db? (it's a testing environment so I don't really care about restoring it) or just the sections table before doing the fix?

**Comment by fralla2** [comment]
Ok I'll do but it might take some time as it's a 70k + tickets and 10k assets database with more than 17k users that I need to anonymyze.

For starting points : 
- I was migrating from GLPI 9.4.5 with plugins v2-9-2 already installed
- Migrated to GLPI 9.5.0
- Then migrated to GLPI 9.5.1
- Then installed from repo the plugins version 2.10.1
- Then installed v2.10.2 from the marketplace few days later

Migrations logs bellow : 

**[root@glpi05 glpi-9.5.1-fix]# cat /var/log/glpi/migration_to_2.10.1.log**
2020-08-24 11:26:36 [1151@glpi05]
0 seconde for "Traitement en cours..." @ 2020-08-24 11:26:38 [1151@glpi05]
2 secondes for "Changement de la structure de la base de données - glpi_plugin_formcreator_issues" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_targetchanges" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_targettickets" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_issues" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Traitement terminé." @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Done" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Traitement terminé." @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "create database schema" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "Configure existing entities" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "create request type" @ 2020-08-24 11:26:38 [1151@glpi05]
0 seconde for "create default display preferences" @ 


**[root@glpi05 glpi-9.5.1-fix]# cat /var/log/glpi/migration_to_2.10.2.log**
2020-09-17 14:08:01 [1151@glpi05]
10 secondes for "Traitement en cours..." @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "Traitement terminé." @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "Done" @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "Traitement terminé." @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "create database schema" @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "Configure existing entities" @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "create request type" @ 2020-09-17 14:08:01 [1151@glpi05]
0 seconde for "create default display preferences" @ 


Other details : for show_rules
**On v2.9.2 :** 
Glpi_plugin_formcreator_forms (present)
Glpi_plugin_formcreator_sections (**not present**)
Glpi_plugin_formcreator_questions (present)
Glpi_plugin_formcreator_targettickets (**not present**)
Glpi_plugin_formcreator_targetchanges (**not present**)

**On v2.10.2 :** 
Glpi_plugin_formcreator_forms (present)
Glpi_plugin_formcreator_sections (**not present**)
Glpi_plugin_formcreator_questions (present)
Glpi_plugin_formcreator_targettickets (present)
Glpi_plugin_formcreator_targetchanges (present)

**Comment by btry** [comment]
As I do community support here, I won't ask you to send the copy of your DB, then you probably don't need to anonymize it.

Just plan to have this copy browsable somewhere to share some specific values there and here.

On the version 2.9.2 of the plugin show_rule exists only in the questions table and the sections table (not forms table as you reported).

The column has been added in 2.10.0 to extend conditions to more objects of the plugin. This is normal to find a difference between those 2 versions.

From the migration information you shared it seems that you had the plugin installed from a manual download and installation, then you switched to a version available from the marketplace, am I right ?

**Comment by fralla2** [comment]
<<From the migration information you shared it seems that you had the plugin installed from a manual download and installation, then you switched to a version available from the marketplace, am I right ?>>

Yes.  If I remember correctly, at the time of migration GLPI 9.4.5 to 9.5 and 9.5.1, the plugins wasn't available yet in the market place so I had to reinstall it manually with the downloaded version.  The 2.10.1 version had the same "hiding form" issue so when I saw the 2.10.2 version available on the market place last week I upgraded (from the marketplace) to see if it would fix the issue...

<<On the version 2.9.2 of the plugin show_rule exists only in the questions table and the sections table (not forms table as you reported).>>
Wow that bizarre to say the least....  
I might have migrated to a bugfixed version at some point in the past (prior to 2.9.2) but I don't recall having done this on the production instance.....

I'm pretty sure I did a clean install of version 2.9.2 to begin with on this instance

**Comment by fralla2** [comment]
FYI adding the show_rules column in the sections table fix the display

**Comment by fralla2** [comment]
Wow and in the production server (v2.9.2), the file plugins/formcreator/install/mysql/plugin_formcreator_empty.sql contains the correct code for this table...

I'll try to find if I have traces of previous migrations before that :S


CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_sections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `plugin_formcreator_forms_id` int(11) NOT NULL,
  `order` int(11) NOT NULL DEFAULT '0',
  `show_rule` int(11) NOT NULL DEFAULT '1',
  `uuid` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `plugin_formcreator_forms_id` (`plugin_formcreator_forms_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

**Comment by btry** [comment]
Nice ! 

You probably have an upgrade problem, despite it is checked by unit test. If you have a snapshot of your DB of your instance after upgrading to GLPI 9.5 **but** before upgrading to Formcrreator 2.10.x this is very important to keep it to verify in deep the upgrade process.

As you have access to the marketplace you probably have technical support. I suggest you get in touch with your support provider. This will be more efficient to understant what happened and find a fix.

**Comment by btry** [comment]
> Wow and in the production server (v2.9.2), the file plugins/formcreator/install/mysql/plugin_formcreator_empty.sql contains the correct code for this table...


Ok, accirdying to this information, the upgrade issue comes from an upgrade to 2.9.2. You may check the files in glpi/files/_log . List the files whose name begins with **migration_to** The contain a version number, some are for GLPI and some are for Formcreator. It is quite easy to dinstinguish them based on the  version number.

**Comment by fralla2** [comment]
**This one looks like a test I did back in January (and did not kept the database from that test)**
-rw-r--r-- 1 apache apache      382 Jan 15  2020 migration_to_2.9.1.log

**Those were for sure tests that were not kept either**
-rw-r--r-- 1 apache apache     1556 May 12 08:29 migration_to_2.10.0-beta.1.log
-rw-r--r-- 1 apache apache      655 May 13 12:33 migration_to_2.11.0-nightly.log
-rw-r--r-- 1 apache apache     1146 Jul  8 15:40 migration_to_2.10.0.log

**Those are currents migration logs on the test server :** 
-rw-r--r-- 1 apache apache     1147 Aug 24 11:26 migration_to_2.10.1.log
-rw-r--r-- 1 apache apache      594 Sep 17 14:08 migration_to_2.10.2.log

I didn't find any migration_to files on the production database but the formcreator folder date from May 27th but I have one test form dating back to March 26th....

**So I guess it went as follow :** 
- Probably installed v2.9.1 somewhere in March
- Applied a few 2.9.1 bugfix from the dev branch to fix some issues
- May 27th, probably applied the offical v2.9.2 (install file date from May 18th) but detected it was already at this version because of the bugfixes (and probably skipped some database migrations because of that)... Hence the no migration_to_2.9.2 logs.....
- August 24th : Backuped the database and files to the test server and upgraded from 2.9.2 to 2.10.1 (from github file)
- Sept 17 : Upgraded from 2.10.1 to 2.10.2 from the marketplace

**Comment by btry** [comment]
I checked the versions of the plugin. The columns show_rule was introduced in version 2.9.0 (time goes fast !).

As the column was missing I think the plugin was first installed in a version older than 2.9.0.

If you rebuild correctly the history of the plugin, maybe you have something not properly migrated between 2.9.1 and 2.10.1, but this cannot impact the show_rule column in the sections table.  I think there are events before the version 2.9.1; maybe the plugin has been upgraded to 2.9.1, from an older version. I remember that the upgrade test silently broke long ago. This may be a cause of a bad upgrade. It is also possible to have a broken schema by upgrading to a development version the upgrading again to the same version in its released revision.

If we cannot rebuild accurately the history of the plugin, I suggest we close this ticket.

And don't hesitate to use paid support (because you probably have it).

**Comment by fralla2** [comment]
I found no install file older than 2.9.1 for this plugins on either the production or the test servers but it's not impossible (althow really not probable from what I can recall)

No we don't currently have paid support (school districts here and money is always a problem haha) but we plan on getting the basic support tier sometime in the future.  So yes you can close this issue as it is resolved for us and thanks again for your great help.


![image](https://user-images.githubusercontent.com/38400135/93638728-d1aef880-f9c5-11ea-890c-f92233e969ae.png)

![image](https://user-images.githubusercontent.com/38400135/93638809-f5723e80-f9c5-11ea-95d7-2624a5a1da6e.png)

![image](https://user-images.githubusercontent.com/38400135/93638894-25b9dd00-f9c6-11ea-8240-7681df08a472.png)

Francois

**Comment by btry** [comment]
Hi

I think that there is missing reliable information about the history of your GLPI instance; then I cannon investigate further about a possible upgrade problem.

Let's close this issue, and I'll wait for news on the other issue you mentionned.

Thank you for your feedback.
