### ISSUE TITLE
pop-up on new followups

### ISSUE THREAD

**Issue by chagasgb** [pluginsGLPI/formcreator#1944]
Hello There,

Always when an user tries to add an follow up in the ticket this popup appears in all browsers.

I realized that the bug only happens when the Helpdesk mode (in the entity config) is "simple service catalog".

Thanks
![Screenshot_1](https://user-images.githubusercontent.com/70600712/93768133-5761bc80-fbef-11ea-9aa3-b556da36ad72.png)

**Comment by btry** [comment]
Hi @chagasgb : Please apply the fix mentionned here This will solve your issue.
