### ISSUE TITLE
Form not creates Ticket

### ISSUE THREAD

**Issue by thefamedtm** [pluginsGLPI/formcreator#1945]
Hello,

I have 3 forms with Ticket Target and when it creates someone, GLPI not creates ticket yet.

I see in php-errors.log:

`[2020-09-21 18:12:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: show_rule
  Backtrace :
  plugins/formcreator/inc/fields.class.php:166       
  plugins/formcreator/inc/formanswer.class.php:968   PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/formanswer.class.php:1163  PluginFormcreatorFormAnswer->generateTarget()
  inc/commondbtm.class.php:1136                      PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:134        CommonDBTM->add()
  {"user":"8@GLPI-v2"} `

It's to strange because with some users can create ticket but with others not. I try with super--admin privileges and not creates ticket.

I use GLPi 9.4.5 and formcreator 2.10.2.

Thank you.

**Comment by btry** [comment]
Hi

It seems that your database does not have the expected schema.

Please check the table glpi_plugin_formcreator_targettickets . It shall contain a column **show_rule** If not, please add the missing column in the right place. Refer to the table structure found in install/mysql/plugin_formcreator.sql

Also check if the column is missing on the other tables :
-glpi_plugin_formcreator_sections
-glpi_plugin_formcreator_questions
-glpi_plugin_formcreator_forms

Other users seems to have a similar problem, and I'm searching for information about a possible bugy upgrade procedure. Consider to collect the install and upgrade history of the plugin to help me to find this bug (which version was installed first, ahd to which versions the plugin has been upgraded over time). If you have DB snapshots of those events this would be great to investigate together.

**Comment by thefamedtm** [comment]
Hello,

Effectively the table glpi_plugin_formcreator_targettickets not have show_rule field.
I create fields and it works fine.

I install first time with version 2.10.0-beta1 and then I updated with 2.10.2.

I don't have DB snapshot.

Thank you so much.

**Comment by btry** [comment]
Hi

It is possible I added conditions on target tickets after  2.10.0-beta.1. This may explain the upgrade problem on this table.

Be careful with beta versions. You should use them on a testing environment and wait for the final release.
