### ISSUE TITLE
La désactivation du suivi courriel ne fonctionne pas

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#195]
La désactivation du suivi courriel pour un demandeur dans un ticket ne fonctionne pas

**Comment by giroli** [comment]
Bonjour
je rencontre le même problème : après validation du formulaire et création du ticket correspondant, le demandeur reçoit de nombreux mails de notification "mise à jour du ticket". J'ai essayé de modifier le gabarit du ticket créé mais impossible de mettre le suivi par mail à "Non" par défaut pour le demandeur.

**Comment by btry** [comment]
Bonjour

J'ai apporté des corrections qui sont susceptibles de résoudre le problème dans les versions 2.4.x du plugin. 

@lolokai , @giroli 
La  version 2.4.2 est sortie cette semaine, l'un de vous peut il l'essayer ?

**Comment by btry** [comment]
A défaut de retour sur une version récente, je ferme. N'hésitez pas à réouvrir si le bug persiste avec la version 2.4.2 ou supérieure.
