### ISSUE TITLE
idformcreatot et idticket

### ISSUE THREAD

**Issue by ludovicbernard** [pluginsGLPI/formcreator#1950]
Bonjour à tous ,
je voudrais récupérer l'Id du ticket généré par formcreator en commande sql ou autre , j'ai trouvé cette table glpi.glpi_plugin_formcreator_issues ou j'ai bien mon id du ticket sur la colonne `original_id`, mais je ne trouve pas la relation entre l'id formcreator et id ticket.
Pour trouver idticket j'ai utilisé l'interface web on sélectionnant le formulaire.
merci de votre aide.

**Comment by btry** [comment]
Bonjour

Lisez l'issue #1554
