### ISSUE TITLE
champ Valeurs par défaut d'une question mal reproduit à l'édition ou l'utilisation

### ISSUE THREAD

**Issue by MLOcc** [pluginsGLPI/formcreator#1955]
Bonjour,
J'utilise GLPI 9.5.1 et le plugin FormCreator 2.10.2

Dans une question du formulaire, lorsqu'on indique un texte avec une apostrophe dans le champ valeurs par défaut, le caractère est antislashé à l'affichage et quand on ré-édite la question
![image](https://user-images.githubusercontent.com/71837011/94674497-8deab600-0318-11eb-9f80-39a89f1164cb.png)

résultat à l'affichage
![image](https://user-images.githubusercontent.com/71837011/94674561-a6f36700-0318-11eb-8f4a-8d43ef890d8a.png)

résultat à la ré-édition de la question
![image](https://user-images.githubusercontent.com/71837011/94675555-32212c80-031a-11eb-8edc-c9913ea86f9c.png)

Sur une valeur par défaut d'une question de type Zone de texte, même problème de caractères antislashés et si l'on souhaite y insérer un tableau personnalisé, la mise en page est perdue à l'enregistrement.
![image](https://user-images.githubusercontent.com/71837011/94674989-4e709980-0319-11eb-981f-d2c7d4f41a12.png)
![image](https://user-images.githubusercontent.com/71837011/94675929-d014f700-031a-11eb-9458-16b32d53beac.png)

résultat à l'affichage du formulaire
![image](https://user-images.githubusercontent.com/71837011/94675102-7c55de00-0319-11eb-919b-db4603ac671a.png)

résultat à la ré-édition de la question
![image](https://user-images.githubusercontent.com/71837011/94675209-a909f580-0319-11eb-9d28-aa823c2a3169.png)

code source de la valeur par défaut
![image](https://user-images.githubusercontent.com/71837011/94675322-d3f44980-0319-11eb-8e2f-8b615e8d8fdc.png)

Bonne journée

**Comment by btry** [comment]
Bonjour

Je crois avoir déjà corrigé le souci dans les questions de type texte sur la dernière révision. Pouvez vous la tester sur un environnement dédié?


Les autres soucis doivent encore exister je vais m'en occuper bientôt.

**Comment by MLOcc** [comment]
J'ai réinstallé le plugin v2.10.2 sur une instance GLPI de test:
- depuis le marketplace
- depuis Github
![image](https://user-images.githubusercontent.com/71837011/94687167-29395680-032c-11eb-9669-7d430ed976db.png)

Je reproduis le comportement sur une question de type Text
![image](https://user-images.githubusercontent.com/71837011/94687258-54bc4100-032c-11eb-834f-5288d6fad367.png)

J'ai essayé en prenant les sources dans la section <>Code de Github mais je ne peux pas activer la version 2.11.0-nightly, j'ai une erreur du type _You must run vendor/bin/robo build:fa-data in the directory of the plugin_

Quand vous indiquez "la dernière révision", il s'agit de la 2.10.2 ou de la 2.11.0 ?

**Comment by MLOcc** [comment]
Bonjour,

dans /formcreator/inc/fields/**textfields.class.php**
et /formcreator/inc/fields/**textareafields.class.php**

dans la fonction **prepareQuestionInputForSave**
remplacer $this->value = str_replace('\r\n', "\r\n", $input['default_values']);
par $this->value = **Toolbox::stripslashes_deep**(str_replace('\r\n', "\r\n", $input['default_values']));

résout le problème pour les questions de type Texte et Zone de texte sur la v2.10.2.

**Comment by btry** [comment]
Bonjour

Pouvez-vous faire une PR ?

**Comment by MLOcc** [comment]
J'ai eu du mal à comprendre le principe des PR donc je sais pas si c'est bien fait, mais c'est fait.

**Comment by btry** [comment]
Bonjour, j'ai modifié votre PR pour suivre les conventions du projet, et j'ai fusionné. Merci pour votre contribution.
