### ISSUE TITLE
Le bouton cancel_my_ticket ne supprime pas la cible

### ISSUE THREAD

**Issue by TOH2F** [pluginsGLPI/formcreator#1956]
Bonjour,

Le bouton cancel_my_ticket  ne supprime pas la cible.

Quel est l’intérêt de ce bouton ?

Merci

**Comment by btry** [comment]
Bonjour

Cette fonctionnalité reprend une fonctionnalité disponible dans GLPI, ainsi que ses contraintes
- aucun suivi n'a été ajouté 
- aucune tâche n'a été ajoutée
- le ticket n'est ni résolu, ni clos

Si vous respectez bien ces conditions et que cela ne fonctionne pas, il y a bug.

**Comment by TOH2F** [comment]
Bonjour,

C'est bien le cas.

Donc il y à un BUG

**Comment by btry** [comment]
Bonjour

J'ai testé avec un tickte vréé par GLPI et un ticket créé par formulaire. Dans les deux cas j'ai pu fermer le ticket avec le bouton.

Essayez ce patch : il affichera un message en cas d’échec, et permettra de mieux comprendre à la nature du refus en interne.

https://github.com/pluginsGLPI/formcreator/pull/1959

**Comment by btry** [comment]
Bonjour 

n'ayant aucune nouvelle sur ce ticket, je ferme. Si le problème persiste, merci d'en ouvrir un nouveau.
