### ISSUE TITLE
Pas de notification par mail lors de la création d'un form

### ISSUE THREAD

**Issue by InfoFDADMR54** [pluginsGLPI/formcreator#196]
Bonjour,

Je ne reçois plus de notification par mail (vers technicien ou observateur) lorsque je valide mon formulaire. Par contre, lorsque je crée un ticket de manière classique, les personnes concernés reçoivent bien les mails.

J'ai vérifier les notifications et ses paramètres, pas de soucis là dessus. J'ai tenté de créer un autre formulaire, le résultat est le même.

Une idée de ce genre de bug ?

En vous remerciant.
Cordialement.

**Comment by InfoFDADMR54** [comment]
Je viens de faire d'autres essais dans les paramètres de notifications, en ajoutant un profil dans la liste des destinataires. Lorsque je met un profil (exemple ADMIN) je reçois bien un mail a la création du formulaire.
Mais le demandeur, l'observateur ou le technicien chargé du ticket ne reçoit toujours rien.
Donc le problème provient bien des destinataires du formulaire.

J'ai essayer de supprimer la notification, et de la recréer, mais c'est toujours la même situation.

**Comment by btry** [comment]
Bonjour,

Je vous invite à essayer la version 2.4.0 ou 2.4.1 (sortie aujourd'hui ) pour voir si le bug a disparu, il y a eu des travaux autour de cette partie du plugin.

**Comment by InfoFDADMR54** [comment]
Ce bug disparait bien depuis le dernière version.

Merci.
