### ISSUE TITLE
Asset booking search does not work in the simplified interface

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#1960]
Good Morning,

I noticed that when I'm in the simplified interface, asset search doesn't work, because it returns all assets including those that are reserved and shouldn't be showing up.
Do you know if you can fix this?

GLPI 9.5.1
FormCreator 2.10.2

**Comment by btry** [comment]
Hi

Can you check if the issue also ocurs in GLPI ? Disable the service catalog, to do the test and feedback.

**Comment by TR0LLL** [comment]
Hi,

So, before opening the ticket I carried out the tests to be sure what it was about, the problem only appears in the simplified interface, if it is through the GLPI interface it works.
If I find it necessary I can give you a printscreen.

**Comment by btry** [comment]
Hi

I did a try, and I sucessfully searched for items.

Please check the logs of GLPI, your HTTP server (for atal errors), and in the dev tools of your browser (javascript errors).

If you find something related, please share it.

**Comment by TR0LLL** [comment]
Hi,

I performed new tests with a different computer and also with another installation of GLPI and the plugin and the problem continues.
Try the following test to reproduce the problem:
1- reserve a computer for a certain day and time;
2- In the simplified interface, search for equipment available for the same day and time;
3- The search will return the computer booked in step 1, but it should not be showing up, as it is already reserved for this day and time.

Note: The schedule is working correctly, it is the search that is returning items that should not be showing up because they are already booked.

I didn't find any error logs in the app or in the browser.

Thank you very much

**Comment by btry** [comment]
Hi

The issue is caused by a redirection in the plugin. The redirection does not "forwards" the search form.

### GLPI core

![image](https://user-images.githubusercontent.com/14139801/97181209-521e0180-179b-11eb-8391-b08c4d5b99ca.png)

### service catalog

![Uploading image.png…]()

**Comment by btry** [comment]
Hi,

the above patch should fix the issue. Please test and feedback.

**Comment by TR0LLL** [comment]
Good Morning,

I ran the test with the version available and it worked perfectly.

Thank you!
