### ISSUE TITLE
Limited characters for Select and Multiselect field

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#1964]
**Describe the bug**
For Select and Multiselect questions, there's only limited characters for values.

**To Reproduce**
1. Create a sample form.
2. Create section.
3. Create question, choose select as type.
4. Provide characters on the values table
5. Error after saving for multiple characters on values field.

**Expected behavior**
For this type of question, the limit should be non existent since the type is select. 
Or if the limit is mandatory, there should be an error saying that the values reached its limit.

**Versions**
GLPI 9.5.1
FormCreator 2.11.0

**Comment by btry** [comment]
Hi

I don't understand which limit you encouteer. Is it a character count in the field ? A number if items in the field ?

Maybe could you provide the content causing the failure.

I checked, the column in teh databaase accepts up to 64K.

**Comment by leecheromerevilit** [comment]
Hi

I'm referring to the limit on the database column @btry 

Can we upgrade it to longtext instead of text since the value option will hold the data for Select and Multiselect field?

**Comment by btry** [comment]
OK.

What is the size of your column ? Does it match the empty.sql file of the installer ?

**Comment by leecheromerevilit** [comment]
Hi.

I have more than 65,535 characters which is the limit of the text datatype.

Is it possible to make it longtext since this column will hold the Select and Multiselect field type?

**Comment by btry** [comment]
Hi

You can upgrade the field to long text. 

It is unexpected to overflow this field. Are the items copied from some data source ?

**Comment by leecheromerevilit** [comment]
Hi

Yes. I have a data source with atleast 50k of options.

So I'm thinking, here are my options:
1. Create upgrade_to_2.11.1.php for the changing the data type of values column.
2. Update plugin_formcreator_empty.sql and install the plugin
3. Update DB.

Which one is best?

**Comment by btry** [comment]
Just update the DB to use medium or long text.

Maybe it would be interesting for you to have a question type able to read the items directly from your data source.

**Comment by btry** [comment]
Hi

I'll merge the above PR in the develop branch. In the versions following 2.10.x you won't need to handle the column type by hands.

**Comment by leecheromerevilit** [comment]
Hi

This is much appreciated. Thank you.

Last question. I saw your PR and there you added 2 lines on upgrade_to_2.11.php file.

Is there some way that I could run this file without having to reinstall the plugin itself for it to take effect?

**Comment by btry** [comment]
Hi

You may add those 2 lines in update_to_2.10.php (assuming you're running the version 2.10.x) and run the CLI tool to upgrade the plugin: 

```
php scripts/cliinstal --force-upgrade
```
 (to upgrade the latest upgrade script over the same version, assuming your current working dir is plugins/formcreator ).

**BUT** 

in your case it is much easier to directly change the type of column in the database with an ALTER request.

**Comment by leecheromerevilit** [comment]
Hi

Thank you @btry
