### ISSUE TITLE
Are all field available for destination?

### ISSUE THREAD

**Issue by piovisqui** [pluginsGLPI/formcreator#1967]
When creating a form, I would like to control the fields urgency, impact and priority when creating (destination) the ticket. Now I can only add the urgency field. Can I add the others?

In a broad sense, is it possible to manipulate all the ticket fields from FormCreator?

**Comment by btry** [comment]
Hi

The plugin does not provide such fields because :
- priority is computed from a urgency / impact matrix. See the config in GLPI.
- impact is set by technicians, not requesters.
