### ISSUE TITLE
Network device does not show on ticket

### ISSUE THREAD

**Issue by piovisqui** [pluginsGLPI/formcreator#1968]
**Describe the bug**
Network device does not show on ticket made from FormCreator.

**To Reproduce**
1. Make the form
2. Add GLPI object - network device
3. Set destination "associated elements -> the glpi object provided from the question (network device the user chose) "
4. The ticket is created, GLPi accounts 1 element associated, but does not show it.

**Expected behavior**
The associated element should show up. Worth mention that the entities from ticket and asset are different, but I enabled the child entities option in the network devices, form, ticket, etc. The bug is somewhat related to it. I have tested with other asset, like computer, and they work fine. So, it should work with network devices also.

**Screenshots**
The question
![image](https://user-images.githubusercontent.com/11858817/95599410-6afe8700-0a27-11eb-8f82-9d7f78392125.png)

The association
![image](https://user-images.githubusercontent.com/11858817/95599459-7c479380-0a27-11eb-89b1-e3cd18e0aa93.png)

The bug
![image](https://user-images.githubusercontent.com/11858817/95599192-2115a100-0a27-11eb-8edb-073602b8c7f0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10x64
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 81
GLPI 9.4.6
FormCreator 2.10.2

**Additional context**
I have tested all profiles, changed all kinds of entities related configs.

**Comment by btry** [comment]
Hi

Check the profile of the user where the problem occurs. I think that network devices are not in the list of associatable assets to a ticket. If you add it, then the item shall show.

**Comment by piovisqui** [comment]
I had the right permission. After removing it, the element count does not appear. 

![image](https://user-images.githubusercontent.com/11858817/95614376-c6873f80-0a3c-11eb-8dde-7a1dbc7d6d8b.png)

**Comment by btry** [comment]
OK, 

Based on your result, I think I should try to reproduce.

**Comment by btry** [comment]
Hi

Please find the ID of the question where the user selects a network equipment. In the table **glpi_plugin_formcreator_formcreator** checl the row matching this ID and read the column **values**.

I guess the  value is **Networkequipment**; it should be **NetworkEquipment**. I think this is the root cause of the bug.

**Comment by btry** [comment]
Try the fix in this commit : 203b5b9503d08bcf2fad1357a8970b93073311cf

**Comment by piovisqui** [comment]
The table you mentioned was not found.
```
desc glpi_plugin_formcreator_formcreator ;
ERROR 1146 (42S02): Table 'glpi.glpi_plugin_formcreator_formcreator' doesn't exist

show tables like '%formcreator%';
+----------------------------------------------+
| Tables_in_glpi (%formcreator%)               |
+----------------------------------------------+
| glpi_plugin_formcreator_answers              |
| glpi_plugin_formcreator_categories           |
| glpi_plugin_formcreator_conditions           |
| glpi_plugin_formcreator_entityconfigs        |
| glpi_plugin_formcreator_formanswers          |
| glpi_plugin_formcreator_forms                |
| glpi_plugin_formcreator_forms_profiles       |
| glpi_plugin_formcreator_forms_validators     |
| glpi_plugin_formcreator_issues               |
| glpi_plugin_formcreator_items_targettickets  |
| glpi_plugin_formcreator_questiondependencies |
| glpi_plugin_formcreator_questionranges       |
| glpi_plugin_formcreator_questionregexes      |
| glpi_plugin_formcreator_questions            |
| glpi_plugin_formcreator_sections             |
| glpi_plugin_formcreator_targetchanges        |
| glpi_plugin_formcreator_targetchanges_actors |
| glpi_plugin_formcreator_targettickets        |
| glpi_plugin_formcreator_targettickets_actors |
+----------------------------------------------+
19 rows in set (0.00 sec)

```

I altered the code in inc/fields/glpiselectfield.class.php, but probably still need to alter table fields.

**Comment by btry** [comment]
Hi

Sorry, this is not the good table name :  glpi_plugin_formcreator_questions

**Comment by piovisqui** [comment]
The reserved word "values" is used as a column name (that's not recommended). 

` desc  glpi_plugin_formcreator_questions ;
+--------------------------------+--------------+------+-----+---------+----------------+
| Field                          | Type         | Null | Key | Default | Extra          |
+--------------------------------+--------------+------+-----+---------+----------------+
| id                             | int(11)      | NO   | PRI | NULL    | auto_increment |
| name                           | varchar(255) | NO   | MUL |         |                |
| plugin_formcreator_sections_id | int(11)      | NO   | MUL | NULL    |                |
| fieldtype                      | varchar(30)  | NO   |     | text    |                |
| required                       | tinyint(1)   | NO   |     | 0       |                |
| show_empty                     | tinyint(1)   | NO   |     | 0       |                |
| default_values                 | text         | YES  |     | NULL    |                |
| **values**                         | text         | YES  |     | NULL    |                |
| description                    | text         | NO   |     | NULL    |                |
| order                          | int(11)      | NO   |     | 0       |                |
| show_rule                      | int(11)      | NO   |     | 1       |                |
| uuid                           | varchar(255) | YES  |     | NULL    |                |
+--------------------------------+--------------+------+-----+---------+----------------+
`
https://mariadb.com/kb/en/reserved-words/

Had to use backtrick to alter the values.
https://stackoverflow.com/questions/12400735/select-a-column-with-a-keyword-name

After all, it worked.
![image](https://user-images.githubusercontent.com/11858817/95864642-0d767d00-0d3c-11eb-9ff1-30ade61eea09.png)

**Comment by btry** [comment]
Don't worry about the column name : GLPI provides a query builder which protects column names eficiently.

Now your question is repaired, I recommend you apply the patch to ensure you won't be annoyed if you create new questions in the DB.
