### ISSUE TITLE
Email notifications not honoring different entities

### ISSUE THREAD

**Issue by Teraxi** [pluginsGLPI/formcreator#197]
Formcreator doesn't honor different notification settings and templates set for the root entity and a sub-entity. Even if the notifications are set to be not available for child entities formcreator uses them and ignores completely any notification setting set in the child entity.

Version of the formcreator used is 0.90-1.4 and GLPI 0.90.1.

**Comment by btry** [comment]
Hi

This issue is very old and has not been investigated. If the problem persists with the last version of the plugin please open a new ticket, with steps to reproduce your context.
