### ISSUE TITLE
Incorrect checkbox position

### ISSUE THREAD

**Issue by fbs1980** [pluginsGLPI/formcreator#1975]
**Describe the bug**
When opening a form, all check boxes appear misaligned.

**Expected behavior**
Correct placement of checkboxes in Formcreator.

**Screenshots**
![image](https://user-images.githubusercontent.com/71726378/96000277-1be09980-0e0d-11eb-8d8c-7c6cb54d051c.png)

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows 10 build 1909]
 - Browser [firefox]
 - Version [81.0.1 64-bit
 - GLPI 9.5.2

**Comment by btry** [comment]
Hi

Please check thar you're using the latest version (2.10.2). Next, try to refresh you cache by pressing F5 in the web page.

**Comment by fbs1980** [comment]
Hello. We are already using version 2.10.2. Since I upgraded to GLPI 9.5 and the Formcreator 2.10.1 plugin it stays that way.

**Comment by fbs1980** [comment]
> Hi
> 
> Please check thar you're using the latest version (2.10.2). Next, try to refresh you cache by pressing F5 in the web page.

Hello. We are already using version 2.10.2. Since I upgraded to GLPI 9.5 and the Formcreator 2.10.1 plugin it stays that way.

**Comment by btry** [comment]
Hi

I don't reproduce :

Firefox 81 on Ubuntu Linux 20.04

GLPI 9.5.2 (bugfixes btranch), and Formcreator (support/2.10.0 branch), on service catalog

![image](https://user-images.githubusercontent.com/14139801/96043482-50853d00-0e6f-11eb-820e-925642cee9fc.png)

Try to disable all extensions in your browser especially those affecting css.

**Comment by btry** [comment]
I noticed a difference here

![image](https://user-images.githubusercontent.com/14139801/96043761-bffb2c80-0e6f-11eb-8920-7c243f491521.png)

Maybe you have custom stylesheet in GLPI's style.css ?

**Comment by fbs1980** [comment]
Guys, I downloaded the plugin again and replaced it in my directory and the problem was solved. I thank everyone for their help.
