### ISSUE TITLE
I Cannot Delete this Plugin "Form Creator" from GLPI 9.5.2

### ISSUE THREAD

**Issue by wasonhome55555** [pluginsGLPI/formcreator#1977]
Hi GLPI Plugin Everyone

I Cannot Delete this plugin "Form Creator" and GLPI 9.5.X - 9.5.2 Has Remember old version and Cannot Install Form Creator New Version
I Install this **_"Form Creator" from GLPI 9.2.3 but I Has upgrade to GLPI 9.5.X - 9.5.2_** and I Cannot Upgrade "Form Creator" New Version Plugin.

<img src="https://www.img.in.th/images/532d1af643a915923f78768dff004fb2.jpg" alt="532d1af643a915923f78768dff004fb2.jpg" border="0">

<img src="https://www.img.in.th/images/fd4efa56ca574867be96446693a07112.jpg" alt="fd4efa56ca574867be96446693a07112.jpg" border="0">

<img src="https://www.img.in.th/images/2ad940bc2244023cffeb178b568450c0.jpg" alt="2ad940bc2244023cffeb178b568450c0.jpg" border="0">

**Comment by btry** [comment]
Hi

It looks like you have an inconsistency in a table of the plugin. 

Use a tool to edit the table **glpi_plugin_formcreator_targetchanges** and manually add the missing column **category_question** . To preoerly add it, please read  the CREATE TABLE statement here : https://github.com/pluginsGLPI/formcreator/blob/support/2.10.0/install/mysql/plugin_formcreator_empty.sql#L171 .

Once done, try again to upgrade the plugin.

**Comment by wasonhome55555** [comment]
> Hi
> 
> It looks like you have an inconsistency in a table of the plugin.
> 
> Use a tool to edit the table **glpi_plugin_formcreator_targetchanges** and manually add the missing column **category_question** . To properly add it, please read the CREATE TABLE statement here : https://github.com/pluginsGLPI/formcreator/blob/support/2.10.0/install/mysql/plugin_formcreator_empty.sql#L171 .
> 
> Once done, try again to upgrade the plugin.

I don't understand how to fix this. What kind of code do I have to change?

**Comment by btry** [comment]
Use a GUI tool or a CLI tool to acces your database and run this command :

```sql
ALTER TABLE `glpi_plugin_formcreator_targetchanges` ADD COLUMN `category_question` INT(11) NOT NULL DEFAULT '0' AFTER `category_rule`;
```

**Comment by btry** [comment]
Hi @wasonhome55555 

Do you have news about your problem. Is it solved ?

**Comment by wasonhome55555** [comment]
> Hi @wasonhome55555
> 
> Do you have news about your problem. Is it solved ?

I Cannot solve this problem , because has error not found database

[img]https://sv1.picz.in.th/images/2020/10/27/bwTEgI.jpg[/img]

**Comment by btry** [comment]
Hi

You have to use a database before doing a request. Click on the database **glpi** then try agan to run the request.

Your issue is related to the use of PhpMyAdmin or your knowkedge of a DBMS. If you need help on those topics, please use a forum dedicated to phpmyadmin or MySQL.

**Comment by tguichard25** [comment]
J'ai le même problème sur mon serveur de test.
J'ai désinstallé le plugin, supprimé le dossier mais impossible de nettoyer.
Le plus étrange c'est que malgré le fait que le dossier n'existe plus, je peux encore installer le plugin.

**Comment by btry** [comment]
Bonjour

Sur quelle interface : le marketplace ou l'interface traditionnelle ?

**Comment by tguichard25** [comment]
les 2

**Comment by btry** [comment]
Je viens de faire un essai :

le plugin était dans le dossier plugins/
J'ai désinstallé le plugin, puis déplacé le dossier hors de GLPI
j'ai cliqué sur le bouton "nettoyer" (interface marketplace)

Le plugin a disparu de la liste. Je rafraichis la page pour vérifier, le plugin est bien absent.

Avec le marketplace, les plugins peuvent être installés dans 2 endroits différents. Vérifiez que le plugin est bien absent de glpi/plugins/ et glpi/marketplace/

**Comment by btry** [comment]
Bonjour @tguichard25  : avez vous vérifié que le plugin est bien absent des 2 dossiers cités ci-dessus ?

Hi @wasonhome55555 : Is your problem solved ?

**Comment by btry** [comment]
Hi

No news on this issue. I guess I can close. Feel free to ask to reopen if needed.
