### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by maules** [pluginsGLPI/formcreator#1978]
Hello,

Sauf erreur de ma part, l'interface la vue wizard utilise bootstrap. 
Si c'est bien le cas, pourriez vous m'indiquer ou puis je modifier le code de la vie utilisateur "catalogue de service"
Merci d'avance pour vos retour. 

Cordialement,

**Comment by btry** [comment]
Bonjour

Non, il n'y a pas de bootstrap dans Formcreator. 

Si vous voulez modifier des choses : 
- vous trouverez le CSS dans css/styles.css
- et le HTML dans inc/wizard.class.php

**Comment by maules** [comment]
Merci. J’ai déjà modifier ces éléments mais c’est assez fastidieux.
Vous me confirmer bien qu’il n’y a que ces deux fichiers pour la mise en page.?
Encore merci pour votre pro-activité.
Après votre dernière réponse, nous pouvons considérer la demande close.

Bonne continuation.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : btry <notifications@github.com>
Envoyé : Monday, October 19, 2020 10:06:55 AM
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : Mohamed BENKINIOUAR <mbenkiniouar@talentsoft.com>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] Bootstrap (#1978)


Bonjour

Non, il n'y a pas de bootstrap dans Formcreator.

Si vous voulez modifier des choses :

  *   vous trouverez le CSS dans css/styles.css
  *   et le HTML dans inc/wizard.class.php

**Comment by btry** [comment]
Le catalogue de services utilse des librarires JS tierces pour présetner ls catégories et les formulaires. 

masonry et slinky, situées dans le dossier lib. Pour les interfacer avec le reste du plugin il y a du code dans js/scripts.js.php (attention, il y a quelques portions de PHP dans le fichier).
