### ISSUE TITLE
[2.10.3] probleme Affichage catégorie des sous entités

### ISSUE THREAD

**Issue by cp61** [pluginsGLPI/formcreator#1979]
**Describe the bug**

Suite à la mise à jour en 2.10.3, lorsque j'ouvrais un formulaire en 2.10.2 et que j'étais positionné dans l'entité principale et que je souhaitais faire un formulaire pour une sous-entitié, je voyais les catégories de la sous entité. Aujourd'hui les catégories des sous entités ne s'affiche plus. Pas de souci en 2.10.2.

**To Reproduce**

1. Creer une question de type intitulé - Assistance - Catégories de Ticket
2. Dans Valeur par défaut je vois bien les catégories des sous entités.
3. Dans racine sous arbre, je sélectionne ma sous entité 
4. si je vais dans prévisualisation, les catégories ne s'affichent pas
5. Pour contourner le problème pour le moment, j'affecte par défaut une catégorie mais sans avoir le choix des autres catégories disponibles

**Expected behavior**
Nous devrions vois toutes les sous catégories de la sous entité GSIC dans l'exemple

**Screenshots**

![image](https://user-images.githubusercontent.com/8723270/96440633-8b3cfb80-1208-11eb-8959-9d17daf5bc82.png)

![image](https://user-images.githubusercontent.com/8723270/96440715-a6a80680-1208-11eb-8a0b-adbb53c750b7.png)

**Comment by btry** [comment]
Bonjour

Pouvez- vous annuler ce commit et me dire si cela résout votre souci ?

https://github.com/pluginsGLPI/formcreator/commit/9f4b1addaaa39095a4a1ebcff5e64a579676bd20

**Comment by cp61** [comment]
Bonjour, 

En effet cela règle le problème.

Par contre je cherche toujours pour le problème "Bug affichage mes demandes d'assistances #1948"

Merci pour votre réactivité

**Comment by btry** [comment]
#1948 est compliqué à traiter avec les moyens disponible dans un contexte communautaire. Il faudrait qu'un utilisateur sous souscription soit impacté par le souci pour que je puisse examiner une base de données et faire une séance de debug. Ce serai plus efficace.

**Comment by tguichard25** [comment]
J'ai le même soucis qui n'est pas réglé par l'annulation du commit

**Comment by btry** [comment]
Bonjour 

le patch #981 devrait résoudre #1946 correctement. Je note que l'itemtype Document ne gère pas sa restriction par entité de la même manière que les autres.

**Comment by btry** [comment]
De mon côté, j'observe bien le problème quand le commit 9f4b1ad est en place, et il disparaît si je l'annule.

Test effectué en entité racine, vue arborescente activée, et avec des catégories de ticket dans des sous entités.

@tguichard25 : peut être que vous n'avez pas la vue arborescente activée pour accéder aux sous entités ?

**Comment by tguichard25** [comment]
Je suis bien en vue arborescente. J'ai testé avec, sans le commit, toujours pareil dans les deux cas.

**Comment by btry** [comment]
Bonjour

@tguichard25 : il faudrait trouver comment reproduire votre cas. Comme les catégories de tickets sont positionnées dans ces entités, peut être que le bug apparaît en fonction de votre configuration spécifique. Pouvez vous tenter reproduite le souci sur un GLPI fraîchement installé et décrire comment vous avez fait ?

**Comment by tguichard25** [comment]
Je vais voir pour tester sur un glpi fraichement installé.
Sinon voici la configuration.
Les utilisateurs sont en libre service en récursif sur l'entité racine.
Les formulaires et catégories sont dans des sous entités.
racine   >>> utilisateurs en récursif
- sous entité >>> formulaire et catégorie

Je ne vois les catégories que si je suis dans l'entité des catégories avec ou sans le commit cité ci-dessus.

**Comment by phamorais** [comment]
@btry 

I was having the same problem.

My scenario is:

All users are in entity A; All forms are in entity A;

The itil categories are in the child entities

After applying https://github.com/pluginsGLPI/formcreator/pull/1981/commits/fb10bf4e1d6f8655143bf61c6646afee613b565e

The list of itil categories in the forms has returned to work

Before applying the path (should upload the list of child entity categories)

![image](https://user-images.githubusercontent.com/35368369/97253928-14959480-17ec-11eb-939a-2485123abec6.png)


After applying the path (the categories were presented correctly)

![image](https://user-images.githubusercontent.com/35368369/97254024-44449c80-17ec-11eb-885b-7f6a696b4466.png)



GLPI 9.5.2
Formcreator 2.10.3

**Comment by tguichard25** [comment]
j'ai le même problème avec les lieux

**Comment by btry** [comment]
Bonjour

Le point commun entre les catégories de tickets et les lieux est qu'ils sont arborescents et appartiennent à une entité. Il est très probable que le même problème existe pour tous les autres objets ayant ces propriétés. Il reste à trouver une arborescence et une  répartition dans des entités me permettant de reproduire.

**Comment by tguichard25** [comment]
Si je me met dans l'entité des catégories, le champ fonctionne correctement.
Si je suis sur l'entité racine en arborescence ça ne fonctionne pas.

**Comment by btry** [comment]
Ok. Cette remarque pourrait suffire pour que je reproduise.

**Comment by tguichard25** [comment]
J'ai fait un formulaire test, j'ai juste mis une question 'intitulé catégorie'.
En fait je ne vois que les catégories de l'entité active de l'utilisateur.

**Comment by btry** [comment]
Bonjour

@tguichard25 : 

j'ai créé une arborescende minimale de catégories dans une entoté Root entity > entity 0001
j'ai créé un formulaire dans Root Entity avec uen question de type catégorie de tickets
en mode preview je déroule la liste, j'ai bien mes catégories

![image](https://user-images.githubusercontent.com/14139801/99056463-9e8a7f00-259a-11eb-9da8-83e40cb02d77.png)

par contre si je le mets en entité raciine sans vue récursive, je ne vois pas les catégories (c'est normal).
![image](https://user-images.githubusercontent.com/14139801/99056522-b06c2200-259a-11eb-9c16-c7ebadc498ff.png)


Donc je ne reproduis toujours pas votre problème.

**Comment by btry** [comment]
Vous pouvez upgrader à la version 2.10.4 pour que vote version soit la plus à jour, d'autant que la branche de développement ne contient encore aucun nouveau correctif susceptible d'avoir une influence sur le souci.

**Comment by tguichard25** [comment]
Bonjour, mon problème a bien été résolu par [fb10bf4](https://github.com/pluginsGLPI/formcreator/commit/fb10bf4e1d6f8655143bf61c6646afee613b565e)
Mon problème venait du marketplace.
J'ai tout supprimé et réinstallé et depuis plus de problème.

**Comment by btry** [comment]
Si l'installation du plugin via le marketplace pose un souci, vous pouvez ouvrir un ticket à ce sujet.

Le problème étant résolu, je ferme celui-ci. Merci pour les retours.
