### ISSUE TITLE
[FormCreator 0.90-1.3.3] Caractères spéciaux non pris en compte à la création du Ticket

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#198]
Nous utilisons FormCreator depuis quelque temps et avec plaisir ! (merci).

Cependant nous rencontrons des difficultés concernant un cas particulier. Dans un de nos formulaire un champ de type "Liste Déroulante" contient des "\" pour exprimer une liste de partage réseaux. Ces caractères sont considérés comme spéciaux, et nous devons donc les échappés en les doublant. Pour obtenir un \ nous tapons \. Pour obtenir \, nous tapons \\. 

Pour la partie formulaire, le fait d'échapper les caractères fonctionne correctement *(1). En revanche, une fois que le formulaire est validé, la création de ticket est générée et là, les caractères spéciaux disparaissent. Un texte qui apparaît comme ceci dans le formulaire : \server1\dossier2 apparait comme de la manière suivante dans le ticket GLPI : \server1dossier2.

*(1) : ça fonctionne correctement cependant lorsque l'on réédite le formulaire, les caractères d’échappement ont disparus, et du coup si l'on enregistre le formulaire, on perd encore des . 

Je peux reproduire le problème sur nos deux plateforme (test et Prod, dans le même niveau de version au niveau du plugin Formcreator et en 0.90.1 pour la prod, et 0.90.2 pour la test en ce qui concerne GLPI.)

Merci de votre retour.

**Comment by SylvainGuibert** [comment]
Sans réponse depuis 11 jours.. je continue mes recherches... je pense que le problème que je constate est lié au ticket #103 sur github/formcreator.

En ce qui me concerne, ma version de php est la suivante : 5.5.9

**Comment by SylvainGuibert** [comment]
-> Correction d'une partie du problème : Ce code corrige uniquement l'affichage des slashes dans le formulaire et l'éditeur de formulaire. Lors de l'intégration du formulaire dans le ticket, les slashes n’apparaissent toujours pas (correction en cours). [Merci MATPIF]

Ajout dans la classe: PluginFormcreatorQuestion
Fichier: /var/www/glpi/plugins/formcreator/inc/question.class.php
Les lignes suivantes :
278       else {
279         $input['values'] = addslashes($input['values']);
280       }

**Comment by SylvainGuibert** [comment]
Toujours le même problème en 0.90-1.3.4 ... Que faire pour que ce bug soit pris en compte ?

**Comment by SylvainGuibert** [comment]
Pour être encore plus concret : Voici ce que je saisi dans le formulaire au niveau de la qestion

![2016-07-26_09h14_04](https://cloud.githubusercontent.com/assets/16323410/17129144/aab73bc0-5311-11e6-8099-730ea08c3e1f.png)

Voici ce qui apparaît lorsque je clique sur "sauvegarder" et que je réédite la question.

![2016-07-26_09h14_16](https://cloud.githubusercontent.com/assets/16323410/17129160/cd2e99be-5311-11e6-81e2-f9f09290a93c.png)

Comme on peut le voir 1 Slash est supprimé après sauvegarde de la question...Si je sauvegarde a nouveau la question, le texte apparaîtra sans aucun slash...

**Comment by coni83210** [comment]
Bonjour,
je rencontre exactement le même problème.
Avez-vous trouvé une solution ?

**Comment by SylvainGuibert** [comment]
Non toujours pas de solution, je patiente.....

**Comment by btry** [comment]
Bonjour

Au vu de la discussion sur #103 ça semble être assez compliqué à résoudre.

J'ai fait une tentative de correction dans la branche suivante : https://github.com/btry/formcreator/tree/198_fix_slashes

Il ne traite que le cas du multiselect, j'espère qu'il n'a pas d'effet négatif ailleurs. 

Pouvez-vous tester ce correctif ?

**Comment by SylvainGuibert** [comment]
J'attends ce correctif, depuis un bon moment, du coup je viens de tester !

-> A la création du formulaire : OK, lorsque l'on réédite le champ multiselect, les slashes sont toujours présent !

![2016-11-16_09h54_43](https://cloud.githubusercontent.com/assets/16323410/20340705/310ca654-abe3-11e6-8ec3-dba09f3950ff.png)

-> Lors de l'utilisation du formulaire, par un utilisateur X : OK, les noms de partage sont lisible et les slash également présent.

![2016-11-16_09h55_08](https://cloud.githubusercontent.com/assets/16323410/20340709/33decec0-abe3-11e6-98c5-fd0b637a0dd5.png)

-> Lors de la visualisation du formulaire, (une fois qu'il a été complété par un utilisateur X) : OK 

![2016-11-16_09h55_46](https://cloud.githubusercontent.com/assets/16323410/20340733/47c46ff8-abe3-11e6-9bb2-58bd7b233538.png)

-> Dans le ticket GLPI crée suite au formulaire : OK, les slashes sont bien présent.

![2016-11-16_09h59_07](https://cloud.githubusercontent.com/assets/16323410/20340761/608102d6-abe3-11e6-9fb6-be06d70846c8.png)

A priori, le problème est corrigé !!

 Es ce possible d'appliquer le correctif sur les autres champs et soumettre ce dernier à la release officiel ?

**Comment by btry** [comment]
Tel qu'est fait le code, le correctif *devrait* affecter *de manière positive* les champs checkbox / radio / ldap.

Il me faut ajouter du code de test avant de soumettre ce patch.

Si vous avez identifié d'autres types de champs subissant le problème, merci de les lister. Cela me sera utile pour compléter le patch pour ensuite le soumettre au dépôt officiel.

**Comment by SylvainGuibert** [comment]
Alors, je viens de faire des tests complémentaires : 

-> Dans une question, les champs Titre et Description rencontrent le même problème
-> Les types de questions "description", "text" et "textearea" ont également le problème.

**Comment by btry** [comment]
Bonjour

Ces points devraient être corrigés.

**Comment by coni83210** [comment]
Bonjour,
est-ce que quelqu'un a testé et confirme le bon fonctionnement ?

**Comment by SylvainGuibert** [comment]
@btry : Impossible de mettre à jour le plugin : 

Configuration of existing entities (0 seconde)

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'p>Test a</p>' WHERE `id` = 16' at line 2

Le "Test a" correspond à un des tests que j'ai réalisé avec un "\".

**Comment by SylvainGuibert** [comment]
- Ci dessous la capture de l'entrée correspondante.

![2016-11-21_08h19_56](https://cloud.githubusercontent.com/assets/16323410/20473799/5327fee4-afc3-11e6-8b21-5c775058b452.png)

**Comment by btry** [comment]
Bonjour

Pouvez-vous montrer le backtrace de cette erreur ? Vous devriez trouver cela dans glpi/files/_log/sql-errors.log

**Comment by SylvainGuibert** [comment]
voici la backtrace : 
2016-11-21 08:03:05 [8@LAB-LIN-GLPI]
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET
                               `name`           = \'Test description \\\',
                               `values`         = \'\',
                               `default_values` = \'\',
                               `description`    = \'&lt;p&gt;Test a&lt;/p&gt;\'
                             WHERE `id` = 16
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'p&gt;Test a&lt;/p&gt;'
                             WHERE `id` = 16' at line 2
  Backtrace :
  plugins/formcreator/inc/question.class.php:825
  plugins/formcreator/hook.php:20                    PluginFormcreatorQuestion::install()
  inc/plugin.class.php:664                           plugin_formcreator_install()
  :                                                  Plugin->install()
  front/plugin.form.php:49                           call_user_func()

**Comment by btry** [comment]
Le patch est mis à jour avec une correction pour ce souci d'upgrade.

**Comment by SylvainGuibert** [comment]
-> Ok pour la mise à jour, elle s'installe correctement.
-> Par contre je pense que la MAJ à supprimé les anti-slashs présent sur les questions multiselect (j'ai du les repositionner) ( a tester dans la futur beta ?)

-> J'ai retesté l'intégralité des champs, de tous les types de questions : 
**Type : Urgent**
- Problème sur le champ description et value
**Type : Adresse IP**
- Problème sur le champ description
**Type : Champ Masqué**
- Problème sur le champ description
**Type : Courriel**
- Problème sur le champ description
**Type : Checkboxes**
- OK
**Type : Date**
- Problème sur le champ description
**Type : Datetime**
- Problème sur le champ description
**Type : Description** 
- OK
**Type : Fichier**
- Problème sur le champ description
**Type : Float**
- Problème sur le champ description
**Type : Integer**
- Problème sur le champ description
**Type : Intitulé**
- Problème sur le champ description
**Type : Multiselect**
- OK
**Type : ObjetGlpi**
- Problème sur le champ description
**Type : Radio**
- OK
**Type Select**
- OK
**Type Texte**
- OK
**Type Textearea**
- OK

-> Je constate également le même problème dans la description du formulaire lui même ainsi que l'entête

-> Merci de ton aide !

**Comment by btry** [comment]
Bonjour

J'ai mis à jour la branche en fonction des résultats ci dessus. 

Ca reste une version 1.4-beta5 alors que le plugin a évolué entre temps en version 1.4-beta7. Si vous avez mis à jour en version > 1.4-beta5, il vaut mieux que je mette à jour le correctif.

**Comment by SylvainGuibert** [comment]
Bonjour,

Non je n'ai pas mis à jour > a  1.4-beta5 donc j'ai repris ce correctif.
Concernant les types, j'ai refais le tour de qui était à corriger c'est ok pour moi.

Il reste cependant la partie "Formulaire", ou le même problème est présent dans la partie "Description" et "En tête" 

![2016-12-12_13h00_58](https://cloud.githubusercontent.com/assets/16323410/21098767/0aaee11a-c06b-11e6-9e53-c29cdec6ccf4.png)

Merci pour le travail effectué !

**Comment by btry** [comment]
Bonjour

J'ai refait le correctif sur la base de la dernière révision 1.4-beta7 du plugin, et j'ai corrigé les problèmes sur la création / modification de formulaire suite à votre dernier commentaire. 

https://github.com/btry/formcreator/tree/198_fix_slashes_2
