### ISSUE TITLE
Statut bug sur interface simplifiée 

### ISSUE THREAD

**Issue by morcra** [pluginsGLPI/formcreator#1980]
Bonjour,

Sur l'interface simplifiée, j'ai un bug sur le statut des tickets. 
Cela survient lors d'une demande de validation depuis le ticket (pas via formcreator). 

Fonctionnement actuel : Formcreator > Validation formcreator > Nouveau ticket > Règle automatique pour demander une validation à un user spécifique > Une fois validée ou refusée le ticket prend un statut "chiffre". 
![image](https://user-images.githubusercontent.com/73166955/96568999-e0d8dd00-12c8-11eb-9d95-5a92eec05d2f.png)

Sur l'interface Admin le statut est correcte. : 
![image](https://user-images.githubusercontent.com/73166955/96569135-0c5bc780-12c9-11eb-9aaf-02b7dd2453cf.png)

Je dispose actuellement des dernières version GLPI / PLUGIN 
Merci d'avance :)

**Comment by btry** [comment]
Bonjour

J'ai ce patch en attente de validation. Essayez-le et dites moi si il résout le souci.

https://github.com/pluginsGLPI/formcreator/pull/1940

Une partie du patch requiert que vous mettiez à jour le contenu de la table **glpi_plugin_formcreator_issues**. Pour cela vous devez effacer au moins une ligne de la table pour la "corrompre", puis lancer l'action automatique SyncIssues du plugin, disponible dans les actions automatiques de GLPI. Son traitement peut mettre quelques dizaines de secondes, en fonction de la taille de votre BDD.

Note : le statut que vous voyez dans GLPI (donc hors du plugin) est le statut d'un ticket. Par contre dans le catalogue de services vous verrez un statut appartenant à une demande (provenant ed la table mentionnée ci-dessus). C'est pour cela que le problème n’apparaît que dans le plugin.

**Comment by morcra** [comment]
Bonjour,

Je valide le patch. Cela a parfaitement corrigé le problème des statuts : )

Merci beaucoup !

**Comment by btry** [comment]
Merci pour votre retour. Le patch sera disponible dans la prochaine release.

**Comment by morcra** [comment]
Bonjour,

Après plusieurs autres tests complets... Le statut semble rester bloquer sur "en attente" :/ 
![image](https://user-images.githubusercontent.com/73166955/96692602-83a36100-1386-11eb-8287-e8237eb415db.png)

**Comment by btry** [comment]
Bonjour

In souci vient d'ere identifié dans les hooks du plugin. Il y a de bonnes chances qu'il débloque les statuts. Apluquez ce commit et voyez si il débloque ces statuts : https://github.com/pluginsGLPI/formcreator/commit/d2d99805c63dd6a51edde6ab1da01733e8915cd2

**Comment by morcra** [comment]
Bonjour,

Je viens de retester cela semble fonctionner maintenant :) Merci ! 

""""Dernière petite question : j'utilise un un groupe de validation sur mes formulaire. Sauf que quand le groupe est synchronisé avec LDAP. La zone Validation avec le menu déroulant ne s'affiche plus .... :/ Ce bug est remonté ? < Je vais réouvrir un BUG si non. """"

**Comment by btry** [comment]
Bonjour

Il faut au moins deux options pour faire un choix. Si votre formulaire n'a qu'un seul validateur ou groupe validateur, alors il est automatiquement choisi, sans afficher la liste au demandeur. Si vous n'êtes mas dans ce cas, ouvrez un autre ticket.
