### ISSUE TITLE
Formulaire "Dynamique"

### ISSUE THREAD

**Issue by techinfosbri** [pluginsGLPI/formcreator#1982]
Bonjour, je suis depuis un moment en train de chercher comment rendre mon formulaire "Dynamique", c'est à dire que le ticket va proposer des choix en fonctions du remplissage de l'utilisateur.
Par exemple, est-il possible (voir photo) d'utiliser non un seul objet glpi du genre "ordinateur" mais tout le parc, que l'utilisateur puisse choisir dans le ticket si c'est un ordinateur ou un écran etc...

Merci beaucoup

![prb technique](https://user-images.githubusercontent.com/73218157/96685687-c3b21600-137d-11eb-8421-de035de22e03.PNG)

**Comment by btry** [comment]
Bonjour

Il n'y a pas de moyen direct de faire cela dans le plugin. Il faudrait un nouveau type de question.

Beaucoup d’utilisateurs du plugin créent une question demandant le type de matériel (ordinateur, imprimante, écran) et utilisent les conditions pour afficher la dropdown du type de matériel correspondant.

**Comment by techinfosbri** [comment]
Très bien merci de la réponse
