### ISSUE TITLE
Creating tickets out of formcreator doesn't work

### ISSUE THREAD

**Issue by DoomRoman** [pluginsGLPI/formcreator#1986]
**Describe the bug**
When a form is submitted, the plguin doesn'T create a ticket out of this.
This problem occurs since the update to glpi 9.5. With the older version, it did work. We didn't make any changes in the configuration.
the error-log shows the following:
`[php7:notice] [pid 16701] [client 172.19.0.6:42032] PHP Notice: Undefined index: show_rule in /var/www/glpi/plugins/formcreator/inc/fields.class.php on line 166, referer: https://mydomain.com/plugins/formcreator/front/formdisplay.php?id=22 `

**To Reproduce**
1. Open a form
2. fill in my values (two inputs and one comment field)
3. submit form
4. now there should be a generated ticket.

**Expected behavior**
A ticket was generated with my values, based on my template

**Desktop:**
 - OS: Windows, Mac, Ubuntu
 - Browser: firefox, MS Edge, Safari

**Additional context**
We did an update of glpi and the plugin. Since this moment, it doesn't work anymore as expected.

Thank you!

**Comment by btry** [comment]
Hi

You veey likely upgraded Formcreator ans d'or sole reason, a table doesn't matches the expected design.

Search for the string show_rule in the file install/mysql/plugin_form creator_empty.sql. you will find several tables. Check In your DB that they all have this column, and add it if needed.

If you are able to tell what happened recently in the live of your plugin's instance, maybe we will find how you ended with the missing columns.

Someone else had the same problem, and I believe he may have used a development version. The upgrade process is unit tested to ensure the tables are properly upgraded.

**Comment by btry** [comment]
see #1945

**Comment by btry** [comment]
Hi

Did you checked the related ticket to see if it helps you to solve your issue ?

**Comment by DoomRoman** [comment]
Im so sorry!
Yeah, the problem we’re missing tables. I adapt my files and updated the database. Now it works :)

many thanks!

**Comment by btry** [comment]
Great ! thank you for your feedback
