### ISSUE TITLE
Instalação glpi 9.5 	

### ISSUE THREAD

**Issue by leoinfra** [pluginsGLPI/formcreator#1988]
Boa tarde meus caros! 

fiz a atualização para verso nova do GLPI 9.5.2
versao do plugin 
formcreator | 2.10.3 | GPLv2

 porem ocoretam varios erros. 

-------------------------------
primeiro este 

Upgrade glpi_plugin_formcreator_answers (0 segundo)  Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist  Please, check migration log

----------------------------
agora esse 
Upgrade glpi_plugin_formcreator_questions_conditions (1 segundo)
--------------------------

segue os logs da migração e so sql 
================ MIGRAÇÂO============

2020-10-26 15:48:41 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 15:48:41 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 15:48:41 [servidor.glpikofgfngfgng]
Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 plugin_formcreator_upgrade_error()
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
 @ 2020-10-26 15:54:54 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 15:54:54 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 15:54:54 [servidor.glpikofgfngfgng]
Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 plugin_formcreator_upgrade_error()
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
 @ 2020-10-26 16:07:33 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 16:07:33 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 16:07:33 [servidor.glpikofgfngfgng]
Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 plugin_formcreator_upgrade_error()
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
 @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_answers" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_categories" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms" @ 2020-10-26 16:13:01 [servidor.glpikofgfngfgng]
0 segundo for "Drop glpi_plugin_formcreator_headers" @ 2020-10-26 16:13:02 [servidor.glpikofgfngfgng]
1 segundo for "Upgrade glpi_plugin_formcreator_issues" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_answers" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_categories" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Drop glpi_plugin_formcreator_headers" @ 2020-10-26 16:13:18 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_issues" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_answers" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_categories" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Drop glpi_plugin_formcreator_headers" @ 2020-10-26 16:16:27 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_issues" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Trabalho em progresso..." @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade to schema version 2.5" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_answers" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_categories" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Upgrade glpi_plugin_formcreator_forms" @ 2020-10-26 16:25:47 [servidor.glpikofgfngfgng]
0 segundo for "Drop glpi_plugin_formcreator_headers" @ 2020-10-26 16:25:48 [servidor.glpikofgfngfgng]
1 segundo for "Upgrade glpi_plugin_formcreator_issues" @ 

===========SQL===================
[2020-10-26 15:48:41] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: ALTER TABLE  `glpi_plugin_formcreator_answers` CHANGE  `answer` `answer` text;
  Error: Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 15:54:54] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: ALTER TABLE  `glpi_plugin_formcreator_answers` CHANGE  `answer` `answer` text;
  Error: Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:07:33] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: ALTER TABLE  `glpi_plugin_formcreator_answers` CHANGE  `answer` `answer` text;
  Error: Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"[servidor.glpikofgfngfgng]"} 

==========PHP=================

[2020-10-26 15:48:36] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 15:48:38] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 15:49:47] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/var/www/html/glpi/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi/inc/toolbox.class.php at line 656
  Backtrace :
  inc/toolbox.class.php:656                          error_log()
  inc/crontask.class.php:876                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  
[2020-10-26 15:54:27] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 15:54:49] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 15:54:51] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 15:54:58] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:07:28] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:07:36] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:12:56] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:13:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFormcreatorQuestion_Condition' not found in /var/www/html/glpi/marketplace/formcreator/install/upgrade_to_2.5.php at line 565
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:51 PluginFormcreatorUpgradeTo2_5->updateQuestionCondition_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  
[2020-10-26 16:13:15] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:13:18] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFormcreatorQuestion_Condition' not found in /var/www/html/glpi/marketplace/formcreator/install/upgrade_to_2.5.php at line 565
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:51 PluginFormcreatorUpgradeTo2_5->updateQuestionCondition_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  
[2020-10-26 16:16:05] glpiphplog.WARNING: Test logger  
[2020-10-26 16:16:22] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:16:23] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:16:27] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFormcreatorQuestion_Condition' not found in /var/www/html/glpi/marketplace/formcreator/install/upgrade_to_2.5.php at line 565
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:51 PluginFormcreatorUpgradeTo2_5->updateQuestionCondition_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  
[2020-10-26 16:21:06] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1461
plugin_version_glpi_bettermailimporter-master method must be defined!  {"user":"[servidor.glpikofgfngfgng]"} 
[2020-10-26 16:25:48] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFormcreatorQuestion_Condition' not found in /var/www/html/glpi/marketplace/formcreator/install/upgrade_to_2.5.php at line 565
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:51 PluginFormcreatorUpgradeTo2_5->updateQuestionCondition_2_5()
  marketplace/formcreator/install/install.php:138    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:106    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:725                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  

====================================
Poderiam me ajudar com esse tópico ?

**Comment by btry** [comment]
Hi

I speak only French and English, so please let's continue with one of those languages.

As far as I understand you have an yupgrade problem with the plugin. Can you tell me which version you had before the upgrade attempt ?

**Comment by btry** [comment]
Hi

Having no feedback, I close this issue.

**Comment by Ogiaretta** [comment]
Hi, I have this error when I try to install the formcreator, can you help me?

Alteração de layout do banco de dados - glpi_plugin_formcreator_answers (0 segundo)

2.12.3 multiple alter in glpi_plugin_formcreator_answers - Erro na consulta ao banco de dados: ALTER TABLE `glpi_plugin_formcreator_answers` ADD INDEX `plugin_formcreator_forms_answers_id` (`plugin_formcreator_forms_answers_id`) , ADD INDEX `plugin_formcreator_question_id` (`plugin_formcreator_question_id`) - Erro é Key column 'plugin_formcreator_forms_answers_id' doesn't exist in table

**Comment by btry** [comment]
Hi

Is it a fresh install or an upgrade ?

**Comment by Ogiaretta** [comment]
Installation

**Comment by btry** [comment]
Maybe Formcreator was installed and there are still some uncleaned tables in the DB. Delete all tables with a name beginning with glpi_plugin_formcreator_ 

in the table glpi_configs remyve any line with context='formcreator' (you should find zero or one row). 

Try again.

**Comment by Ogiaretta** [comment]
can you tell me the path to where I find this db?
example: /var/www/html/glpi...
please.

**Comment by btry** [comment]
Hi

Never manipulate a DB directly in a filesystem. You must use a client for your database. Usually the binary mysql, pr a webinterface like phpmyadmin or a software like HeidiSQL.

With  any of them, connect to the DB and issue the SQL requests to do your task. I cannot do support for such basic things. You must document yourself on dedicated resources somewhere on internet.
