### ISSUE TITLE
Massive Action - Recursive

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1989]
Hello people!

It would be a good implementation for the next versions, if there was an option to update the "Recursive" option through the "Action> Update" button

![image](https://user-images.githubusercontent.com/35368369/97252638-3b9e9700-17e9-11eb-87af-577981c278e9.png)

![image](https://user-images.githubusercontent.com/35368369/97252694-5d981980-17e9-11eb-9c61-3447234a5f46.png)

**Comment by btry** [comment]
Hi 

a quick check on computers shows that this field is not available massive actions of GLPI as well. Your suggestion should be submitted to GLPI core to be available to most itemtypes. However this may be a big work, then do not expect a quick implementation.

Please consider opening this issue on GLPI project, and link it to this one.

**Comment by phamorais** [comment]
@btry Shouldn't massive action be implemented on the plugin side?

**Comment by btry** [comment]
Not all. Many massive actions are generic and are added by GLPI itself. A plugin may disable some irrelevant actions, and add new ones. Entity and recursive flag are very generic, then I think it would be better to do this effort of development once for all.

**Comment by phamorais** [comment]
Hi Btry, this need is still wanted. I return the topic for you to reanalyze if it is something to be considered to implement.

**Comment by btry** [comment]
Hi

Solved with 7c918d3b
