### ISSUE TITLE
Backslashes in the textarea field

### ISSUE THREAD

**Issue by Ruiseart** [pluginsGLPI/formcreator#199]
Backslashes entered in the Textarea field are removed. Unfortunately, users often put Windows path, which is not therefore clear.

**Comment by SylvainGuibert** [comment]
Same issue as #198 .

**Comment by btry** [comment]
Hi

This issue is very ols now, and should be fixed in latest releases of Formcreator. I close, but if the bug persits, feel free to open a new issue.
