### ISSUE TITLE
Documents doesn't attach after refused v2.10.3

### ISSUE THREAD

**Issue by jonaigringo** [pluginsGLPI/formcreator#1991]
Forms that contain file type fields, after being refused do not attach files new
GLPI 9.5.2 FormCreator 2.10.3

1. Refuse a form that contains an attachment type field
2. Submit the form again with another attachment

**Expected behavior**
Obtain the new attached document after the form is returned

** Screenshots **
There is no error when submitting or rejecting the form
![Screenshot_1](https://user-images.githubusercontent.com/59033130/97320196-50f8dd00-184c-11eb-9c99-9ad382db65b7.png)
![Screenshot_2](https://user-images.githubusercontent.com/59033130/97320198-522a0a00-184c-11eb-810f-75e12732167f.png)
![Screenshot_3](https://user-images.githubusercontent.com/59033130/97320202-52c2a080-184c-11eb-988e-67f3ca6d354d.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 86

**Comment by btry** [comment]
confirmed

**Comment by btry** [comment]
Hi

Please try the above patch and feedback.

**Comment by jonaigringo** [comment]
Thank you! Success
