### ISSUE TITLE
Internet Explorer - bad view

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#1995]
**Describe the bug**
Connect using Self service profile with the FormCreator interface.
The interface is not correctly shown.

**To Reproduce**
Connect using Self service profile with the FormCreator interface.
The interface is not correctly shown.

**Expected behavior**
The view should be OK

**Screenshots**
![image](https://user-images.githubusercontent.com/2960490/97410558-83174700-18ff-11eb-8e54-e861a9f93b37.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Browser : I.E.

**Additional context**
In order to correct this : I modified the styles.css (line 1302) using :

#page.plugin_formcreator_page {
   margin: 0 0 0 300px;
   padding: 0;
   max-height: 100%;
   top: auto;
   overflow-y: auto;
   height: calc(100% - 28px - 65px);
   min-height: 0;
   width: calc(100% - 300px);
   z-index:  0;
   position: absolute;
   transition: .3s;
   left: 0px;
}

instead of 

#page.plugin_formcreator_page {
   margin: 0 0 0 300px;
   padding: 0;
   max-height: 100%;
   top: 0;
   overflow-y: auto;
   height: calc(100% - 28px - 65px);
   min-height: 0;
   width: calc(100% - 300px);
   z-index:  0;
   position: relative;
   transition: .3s;
}

**Comment by btry** [comment]
Hi

Do you mean Edge instead of IE, or are you actually using IE ? Also, please, tell the version.

**Comment by lolokai** [comment]
Non it's Internet Explorer not Edge. Somes users keaping bad pratices :)
Internet Explorer last version 11.572.19041.0

**Comment by btry** [comment]
I'll test your patch against Firefox and a chrome based browser. If it works, I'll merge it.

**Comment by btry** [comment]
Hi

The patch has been applied in branch support/2.10.0 and is also available in the develop branch. Thank you for your contribution.
