### ISSUE TITLE
ticket status does not change

### ISSUE THREAD

**Issue by rodrigoalves1901** [pluginsGLPI/formcreator#1997]
Hello. I have a problem with the status of a ticket. When a post-only user opens a ticket the ticket comes as (new)> correct because I configured it like this. However, when the technician accesses the ticket and assigns it in the ticket, the ticket changes to processing (assigned). However, in the post-only user account, the status shown in the image below does not change.

GLPI version: 9.5.2 - FormCreator version: 2.10.3

![image](https://user-images.githubusercontent.com/43248152/97620219-a1f90480-19f7-11eb-8148-0a4988766438.png)

![image](https://user-images.githubusercontent.com/43248152/97620245-ad4c3000-19f7-11eb-9a62-6369b811c738.png)

**Comment by btry** [comment]
Hi

See #1996.
