### ISSUE TITLE
Calls opened by Formcreator are pulling history from other calls

### ISSUE THREAD

**Issue by apithon2** [pluginsGLPI/formcreator#1999]
Hi I'm having a problem I created all the calls for support from my company but if a person opens the call and I answer in the part of called processes it gets the stock histos of all so-called not only what I'm answering

![image](https://user-images.githubusercontent.com/14139801/98000473-d2bcad80-1dec-11eb-810a-cc056df2f9eb.png)

In this image shows an example the call has just been opened and not even meet I attended but he is already with seven accompaniments

Another problem too and that he's assigning a sector to observer that I didn't put to assign

**Comment by apithon2** [comment]
Do not know if it may be the problem anymore as I had finished creating all forms and was ready to implement GLPI in the company I gave truncate in some tables to delete the history of test calls but i did not delete even a table of FormCreator be that may be the reason ?                   
follows the tables I deleted

truncate glpi_crontasklogs;
truncate glpi_documents;
truncate glpi_documents_items;
truncate glpi_events;
truncate glpi_logs;
truncate glpi_queuedmails;
truncate glpi_taskcategories;
truncate glpi_ticketfollowups;
truncate glpi_tickets;
truncate glpi_tickets_users;
truncate glpi_ticketsatisfactions;
truncate glpi_tickettasks;
truncate glpi_ticketvalidations;

**Comment by apithon2** [comment]
Finding out what the problem was, I cleared some tables and others didn’t have a divergence problem because I had no more calls there were the call attentions there whenever I opened a new call he assigned the pk call for example that call was assigned to call 1 as I cleared the tickets the new ticket will be the id 1

**Comment by apithon2** [comment]
Here is the list I used for cleaning

truncate glpi_crontasklogs;
truncate glpi_documents;
truncate glpi_documents_items;
truncate glpi_events;
truncate glpi_logs;
truncate glpi_queuednotifications;
truncate glpi_taskcategories;
truncate glpi_itilsolutions;
truncate glpi_itilfollowups;
truncate glpi_ticketfollowups;
truncate glpi_tickets;
truncate glpi_tickets_users;
truncate glpi_ticketsatisfactions;
truncate glpi_tickettasks;
truncate glpi_ticketvalidations;
truncate glpi_changecosts;
truncate glpi_changes;
truncate glpi_changes_groups;
truncate glpi_changes_items;
truncate glpi_changes_problems;
truncate glpi_changes_suppliers;
truncate glpi_changes_tickets;
truncate glpi_changes_users;
truncate glpi_problemcosts;
truncate glpi_problems;
truncate glpi_problems_suppliers;
truncate glpi_problems_tickets;
truncate glpi_problems_users;
truncate glpi_problemtasks;
truncete glpi_projects;
truncate glpi_plugin_formcreator_answers ;

**Comment by btry** [comment]
Hi

Glpi uses a relational database, but integrity checks are not enabled in mysql/mariadb.

Adding, editing or deleting rows in the DB will often have incidence on other tables, and you did it massively.

I cannot support you on this issue as you broke many relations in glpi and its plugins. I would recommend you restore a backup and delete data from GLPI instead of truncating tables.
