### ISSUE TITLE
validator issue plugin 2.10.0 --> 2.10.3

### ISSUE THREAD

**Issue by benshoes** [pluginsGLPI/formcreator#2000]
GLPI 9.5.2 - plugin 2.10.0 --> 2.10.3
When a user validates a form, the ticket is not created.
If a validator is added on it, after a validation of this form, the ticket is not created.

**Comment by btry** [comment]
Hi

There is an annoying regression in 2.10.3. You can fix it by following the instructions here : https://github.com/pluginsGLPI/formcreator/issues/1996

I'll releaase a 2.10.4 within 2 weeks to get rid of that.

**Comment by benshoes** [comment]
Hi,
I modified setup and hook files but nothing.
It doesn't work.
When i confirm a Form, no ticket is created.
If i put a validator, no ticket is created at the validation.
Thx for your awesome work
Best regards,

**Comment by btry** [comment]
Hi

Keep the patch, as it actually solve a bug.

Reproduce again then check sql-errors.log qnd php-errors.log. Those files are un glpi/files/_logs .

**Comment by btry** [comment]
If you want to re-try to generate the tickets for an answer, you may access the database and change the status of the answer (table glpi_plugin_form creator_formanswers) and in the issue (table glpi_plugin_form creator_issues).

**Comment by benshoes** [comment]
It work if i uninstall the plugin and reinstall after modified setup and hook files.
Thx ;-)
