### ISSUE TITLE
Not syncs Ticket to Form Status with Automatic action SyncIssues

### ISSUE THREAD

**Issue by carlosbmc** [pluginsGLPI/formcreator#2002]
The forms creates one ticket.

The ticket is closed, but status in FormCreator is "Assigned"

![image](https://user-images.githubusercontent.com/31730629/98233675-ae351280-1f5f-11eb-87cb-d1eeaf5169e8.png)

But the ticket is closed

![image](https://user-images.githubusercontent.com/31730629/98233539-80e86480-1f5f-11eb-943d-3056bca42abb.png)

Running the SyncIssues automatic process detect nothing to sync, so never changes the status Assigned to closed

![image](https://user-images.githubusercontent.com/31730629/98233765-c7d65a00-1f5f-11eb-80e3-d3771fa1c813.png)

**Comment by btry** [comment]
Hi

If you're using the version 2.10.3, please apply the patch mentionned in #1996
