### ISSUE TITLE
simplify interface status update

### ISSUE THREAD

**Issue by pedrointobiz** [pluginsGLPI/formcreator#2005]
Admin change status of ticket, but ticket dont change in user with Self-Service profile

Create ticket with self-service profile, with simple interface, change status with admin, in simple interface dont show status changed.
If change interface to standard, ticket show status updated.

Its supost update the status with the simple interface enabled.

![imagem](https://user-images.githubusercontent.com/47425021/98394666-013bc200-2053-11eb-9e6a-604e825fe0d6.png)

**Comment by btry** [comment]
Hi

Version 2.10.3 ? Check #1996, apply the patch mentionned.

**Comment by pedrointobiz** [comment]
Hi,

GLPI 9.5.2 and Formcreator 2.10.3

I also have this problem with the accountant, but the most serious thing is that the ticket status does not change.

How can i run from GLPI the automatic action "SyncIssues"?

**Comment by btry** [comment]
> the most serious thing is that the ticket status does not change.

see #1996 to fix this. You'll also find instructions to run syncissues manually.

**Comment by btry** [comment]
Hi @pedrointobiz 

You may want to upgrade to the version 2.10.4: it contains the above mentioned patch. This version should solve your problem.

I'm waiting for your feedback.

**Comment by btry** [comment]
Hi

Having no feedback, I close this issue.
