### ISSUE TITLE
Modification Status BDD

### ISSUE THREAD

**Issue by morcra** [pluginsGLPI/formcreator#2006]
Bonjour,

Afin de réaliser des workflow automatiques, j'ai réalisé des scripts (requetes sql) qui modifies les status des tickets en fonction de certains paramètres dans les BDD (Exemple : Validationduticket = validée > Passage du status "En attente" à "En cours"). Cela fonctionne parfaitement coté GLPI mais du coté de l'interface simplifié le statuts n'est pas mis à jour .... Manuellement depuis GLPI cela fonctionne (ce problème ne provient pas de # 1983).

Est-ce qu'il y'a un élément à Refresh pour prendre en compte la modif de la BDD coté formcreator ???? Car via ces script les status restent bloqué et ne sont pas modifiés :/ 

Merci d'avance 👍

**Comment by btry** [comment]
Bonjour

Pour que le plugin puisse synchroniser les changements de la table glpi_tickets avec ses propres données, il faut que vos scripts ne modifient **pas** directement la base de données. Il vaut mieux recourir à l'API REST ou XMLRPC de GLPI. Cela permet à GLPI de déclencher les évènements que le plugin consomme pour ses propres besoins.

Si ce n'est ps le cas, vous devez vider la table glpi_plugin_formcreator_issues et lancer manuellement l'action automatique SyncIssues. La prochaine version fournira un point d'entrée CLI pour ce faire, mais il est à utiliser pour des réparations de la BDD (suite à un bug ou un problème de migration). Un usage normal vous pénalisera si vous avez une grosse BDD, le traitement pouvant mettre quelques dizaines de secondes sur de grosses bases.

D'ailleurs notez qu'il y a une régression dans la version 2.10.3 du plugin (voir #1996). Celle ci sera corrigée dans la prochaine version, et il y aura  d'autres améliorations sur la synchronisation du statut des tickets avec les demandes d'assistance du plugin.
