### ISSUE TITLE
Inclusion of "New" status in higher KPIs

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2008]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When opening a new ticket, tickets with "new" status could appear on the top KPIs

When we open a ticket, and it has the status "NEW" it is not shown in the top KPIs. Thus, the question "Has my ticket really been opened?" It would be interesting if he appeared on KPIs as well.

![image](https://user-images.githubusercontent.com/35368369/98683885-507c3e00-2344-11eb-97cc-dca69c459863.png)

**Comment by btry** [comment]
Hi

The counters don't include the new tickets. No existing counter may include new tickets because of their label. We need to add a new counter. 

This feature is waiting or a sponsor.

**Comment by phamorais** [comment]
Thanks @btry

**Comment by btry** [comment]
Hi

With Formcreator 2.13 the counters now show more statuses, including "new". Closing.
