### ISSUE TITLE
Forms Creator is interfering with the Radio buttons and interface of other plugins.

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/formcreator#2009]
**Describe the bug**
Forms Creator when active interferes with the Radio buttons of other plugins such as Activity and Protocolsmanager. But when deactivated these return to normal and their Radio buttons are displayed. It also appears to interfere with other parts or interface of these plugins.

I have 2 GLPI version: 9.4.6 and 9.5.2 - same Plugin version 2.10.4, on both the problem persists.

**Expected behavior**
That forms creator does not interfere with the interface of other plugins.

**Screenshots**
- When Forms creator is **disabled:**
> - Activity:
![image](https://user-images.githubusercontent.com/56606032/99086502-9e3cb480-2597-11eb-8baf-4f8f2f736e0f.png)

> - Protocolsmanager:
![image](https://user-images.githubusercontent.com/56606032/99086561-b1e81b00-2597-11eb-8347-b888668f7626.png)
![image](https://user-images.githubusercontent.com/56606032/99086592-bc0a1980-2597-11eb-9623-670e5cf4cb53.png)

**In this part I can edit everything**

> ![image](https://user-images.githubusercontent.com/56606032/99086615-c4faeb00-2597-11eb-8576-53a0f7c574a3.png)

**As you can see the radio buttons on both plugins are visible, and in the send email screen for Protocolsmanager I can edit it**

- But when Form Creator is **enabled:**
> - Activity:
![image](https://user-images.githubusercontent.com/56606032/99087005-40f53300-2598-11eb-9430-f23e39e9bac3.png)

> - Protocolsmanager:
![image](https://user-images.githubusercontent.com/56606032/99087158-713cd180-2598-11eb-85fe-e07decf550a1.png)
![image](https://user-images.githubusercontent.com/56606032/99087205-7ef25700-2598-11eb-9bc2-17a51341954b.png)

**In this part I cannot edit nothing**

> ![image](https://user-images.githubusercontent.com/56606032/99087289-96c9db00-2598-11eb-8a7b-3f7131a7b41f.png)

**As you can see the radio buttons on both plugins are invisible or not displayed, and in the send email screen for Protocolsmanager I cannot edit it**

**Desktop:**
 - OS: Windows 10
 - Browser: Edge, Chrome, Internet Explorer, Firefox
 - Version OS: 2004

**Additional context**
Tested in debug mode and in normal mode, same problem. I will also inform this problem to these two plugins.

**Comment by btry** [comment]
Hi 

please apply the above patch and feedback. Other plugins should no longer be impacted.

**Comment by jcervantes-sipecom** [comment]
OK, I already apply but the error persists, I also restart de apache2 service.

**Comment by btry** [comment]
Did you refresh your browser's cache with F5 ?

**Comment by jcervantes-sipecom** [comment]
No, sorry my mistake, I didn't refresh the cache, when openning again the error was solved. Thank you so much.

**Comment by btry** [comment]
Nice.

Thank you for your feedback.

Keep the patch in a safe place. Next release might take time to be delivered.
