### ISSUE TITLE
Select "Request Source" by Formcreator 

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2010]
**Is your feature request related to a problem? Please describe.**
The internal Helpdesk claims that the option "Assistance> Create ticket" has many fields and ends up making the experience to open the ticket on behalf of another user not good

**Describe the solution you'd like**
With the use of the formcreator, each day that passes we use less "Assistance> Create ticket", and more and more we improve the form for opening the tickets. Internally, we created a form for the Helpdesk to open the ticket on behalf of the user through Formcreator, facilitating and improving usability. In this form we insert only 3 fields where I ask for the "title"; "User name" and "Description of ticket". All other fields I fill in with the formcreator + ticket template. So it would be very good, if we could also use the "Origin of Request" form in the form, allowing the call to be with the "origin of the request" changed according to the selection of the form.

![image](https://user-images.githubusercontent.com/35368369/99095315-bf130300-25b3-11eb-8e95-a33e2b7b73a9.png)

![image](https://user-images.githubusercontent.com/35368369/99095339-c803d480-25b3-11eb-860b-2b918e2f2d1a.png)

**Comment by btry** [comment]
Hi

Someone recently pointed that the request sources are available in dropdown > request source.

I may add new settings in the target ticket, like it was done for urgency. 

You may request for a quote if you subscribed to glpi network.

**Comment by phamorais** [comment]
@btry 
this is exactly the need for improvement. Unfortunately I am unable to contribute financially due to the cost reduction of the COVID-19 pandemic, but here I leave a suggestion for improvement so that the community can contribute as well.

**Comment by btry** [comment]
Hi

Formcreator 2.13 provides settings in target tickets to set request source from template / user default. I think this issue is solved by this new feature.
