### ISSUE TITLE
Incorporate access to frequently asked questions

### ISSUE THREAD

**Issue by aleadco** [pluginsGLPI/formcreator#2013]
** Is your feature request related to a problem? Please describe. **
FAQs cannot be accessed when Helpdesk Mode is configured to use the Simplified Service Catalog.

** Describe the solution you'd like **
Incorporate access to frequently asked questions when Simplified Service Catalog mode is in use.

** Describe alternatives you've considered **
The mode used by default includes this function.

**Additional context**

**Comment by btry** [comment]
Hi

Please read the last paragraph of the section Service catalog : https://glpi-plugins.readthedocs.io/en/latest/formcreator/service_catalog.html#service-catalog

**Comment by btry** [comment]
It is also sometimes asked to implement a new left meny entry for the FAQ. Doing so would allow to browse the FAQ with a left category browser, like it is currently done for forms.

This development is waiting for a sponsor. If you're interested, please have a subscription to GLPI Network and request for a quote.

**Comment by btry** [comment]
Hi 

having no feedback Iclose this issue.
