### ISSUE TITLE
Campo modelo de chamado 

### ISSUE THREAD

**Issue by rafainpacto** [pluginsGLPI/formcreator#2019]
Boa tarde 

Estou com o erro o campo Modelo de chamado no destino ele não esta puxando nenhuma informação do chamado que estou vinculando como tempo de SLA, ou prioridade do modelo anexado.

GLPI versão 9.4.6 
Form Creator2.10.4

**Comment by btry** [comment]
Hi

Can you translate your request into english or french  ? I tried to translate it with an online tool, but the result not understandable enough to process it.

**Comment by piovisqui** [comment]
Well, he does not say much. Even in Portuguese it sounds confusing.

>>> I have an error on the field "Model" in ticket's target, it's not getting the info I'm attaching, like SLA or priority.

**Comment by rafainpacto** [comment]
> Oi
> 
> Você pode traduzir sua solicitação para inglês ou francês? Tentei traduzi-lo com uma ferramenta online, mas o resultado não é compreensível o suficiente para processá-lo.

Bom dia 

Acabei conseguindo alterar a forma que estava usando o form.
Obrigado

**Comment by piovisqui** [comment]
He said it worked, but did not explain. I suggest to close this.

**Comment by btry** [comment]
Hi @piovisqui 

Thank you for your help. I close as you suggested.
