### ISSUE TITLE
Impossible de renseigner le champ "attribué à" d'une destination

### ISSUE THREAD

**Issue by dhordelalay** [pluginsGLPI/formcreator#202]
![pbpluginformcreator](https://cloud.githubusercontent.com/assets/18721745/14893383/7cf6503c-0d6f-11e6-8ca1-052a5a8b1336.png)
Bonjour,

Quand je souhaite définir une destination, et attribuer à un groupe (ou une personne) selon la question, la liste proposée est vide...
Comment faire pour l'implémenter?
J'ai bien des groupes de type utilisateur qui peuvent être notifiés et attribué.

GLPI 0.90.1  Formcreator 0.90-1.3.3

**Comment by SylvainGuibert** [comment]
Bonjour,

-> Avez vous le problème pour l'ensemble des formulaires ?
-> Pouvez vous détailler un formulaire pour essayer de reproduire le problème sur une autre plateforme ?

**Comment by dhordelalay** [comment]
Bonjour,

En mode paramétrage, sur tous les formulaires.
Je vous joins la copie d'écran du paramétrage d'une destination s'agissant d'une question type bouton radio.

![pbpluginformcreator_question](https://cloud.githubusercontent.com/assets/18721745/14918202/e741d9a8-0e22-11e6-93ab-df2f5be6f318.png)

**Comment by dhordelalay** [comment]
Ci-dessous la structure de la question
![formcreator_question](https://cloud.githubusercontent.com/assets/18721745/14918269/32a370fa-0e23-11e6-9f87-6adaf9cbf54d.png)

**Comment by dhordelalay** [comment]
![formcreator_questionliste](https://cloud.githubusercontent.com/assets/18721745/14918292/65544cc2-0e23-11e6-9b69-9488a6de67b7.png)

**Comment by dhordelalay** [comment]
Est-ce que mes ajouts sont suffisamment significatifs pour vous (reproduire sur une autre plateforme)

Cordialement,

**Comment by btry** [comment]
Bonjour

La fonction "personne depuis la question" fait référence à une personne mentionnée dans une réponse à une question de votre formulaire. Apparemment vous n'avez pas de question de ce type dans votre formulaire.

Essayez d'ajouter dans votre formulaire un champ de type "Objet GLPi". Le type "Objet GLPi" étant "Administration - Utilisateurs" (voir les deux champs à droite de la capture ci-dessous)

![image](https://cloud.githubusercontent.com/assets/14139801/17480124/a35c64bc-5d76-11e6-89d8-e74f47155c79.png)

La dropdown vide dans votre premier message devrait contenir la  ou les question(s) de type "Administration - Utilisateurs"

**Comment by dhordelalay** [comment]
Bonjour,

Je vous remercie pour votre réponse. Je viens de tester, et je retrouve bien un élément dans la dropdown.
Cependant... ma problématique n'est pas résolue par cette fonctionnalité.
Je vous résume mes besoins:
Un formulaire de demande d'identifiant
- plusieurs types de tâches possibles (Création, modification, renouvellement)
- plusieurs types de fonctions (Médecins, Infirmiers, Secrétaires, ...) ET plusieurs groupes de techniciens selon la fonction (Gr1 pour med + secretaires, gr2 pour Infirmiers, aide-soignant,...)
Comment n'avoir qu'UN formulaire et créer X tickets en fonction des réponses?
Ex: Renouvellement IDCU Infirmière == Gabarit "Renouvellement IDCU" + "Réponse = Inf." + Gr 1
Création IDCU médecin == Gabarit "Création IDCU" + "Réponse = Med" + Gr 2

Merci

**Comment by dhordelalay** [comment]
Re bonjour,

En fait, l'utilisateur ne doit pas décider qui va être le groupe de technicien (le fait de répondre à cette question avant n'est donc pas la modalité attendue

Cordialement,

**Comment by btry** [comment]
Bonjour

Si je comprends bien, vous avez besoin d'assigner un groupe de techniciens en fonction de la réponse donnée au type de fonction. C'est bien ça ?

**Comment by dhordelalay** [comment]
Bonjour,

C'est déjà ce que je fais, mais en lisant cette fonctionnalité, mon esprit a fait un raccourci et j'ai donc pensé pouvoir ne faire qu'un formulaire de demande et dispatcher les tickets.
Tant pis pour moi.

Merci de vos réponses

**Comment by btry** [comment]
Bonjour

Etant donné qu'il y a une solution, je ne pense pas qu'il y ait de tel développement, surtout que ça ferait finalement doublon avec ce qui est déjà faisable.

Je note que vous confirmez le bon fonctionnement  de ce que j'ai proposé. Ca peut être utile aux lecteurs.

**Comment by dhordelalay** [comment]
Bonjour,

C'est une amélioration (évolution) qui serait appréciable.

Cordialement

**Comment by btry** [comment]
Bojnour

> Je vous résume mes besoins:
> Un formulaire de demande d'identifiant
> 
>     plusieurs types de tâches possibles (Création, modification, renouvellement)
>     plusieurs types de fonctions (Médecins, Infirmiers, Secrétaires, ...) ET plusieurs groupes de techniciens selon la fonction (Gr1 pour med + secretaires, gr2 pour Infirmiers, aide-soignant,...)
>     Comment n'avoir qu'UN formulaire et créer X tickets en fonction des réponses?
>     Ex: Renouvellement IDCU Infirmière == Gabarit "Renouvellement IDCU" + "Réponse = Inf." + Gr 1
>     Création IDCU médecin == Gabarit "Création IDCU" + "Réponse = Med" + Gr 2

Avec la dernière version du plugin il est possible de créer plusieurs objets cible (ticket et / ou changement) et de conditionner la génération des cibles à l'aide de conditions sur les questions du formulaire. Je pense que désormais le besoin devrait être couvert.
