### ISSUE TITLE
Confirmation pop-up 

### ISSUE THREAD

**Issue by ricostone** [pluginsGLPI/formcreator#2022]
**Describe the bug**

When adding a new follow up comment, the page ask to confirm leaving the page.

**To Reproduce**

1. Go to a ticket
2. Add a follow-up with some text
4. Click the "Add" button
4. A pop-up appears stating that we are leaving the page (content depend of the browser)
5. Confirm "leaving the page" to save correctly.

**Expected behavior**

We expect that we don't have any pop-up asking for confirming leaving the page when submitting the new message correctly using the submit button.

**Screenshots**

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/1039656/99969281-85ec4700-2d9a-11eb-8a8f-af43fc62efa4.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/1039656/99969284-8684dd80-2d9a-11eb-9b3a-828fa1307c2d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 pro
 - Browser : Firefox 78.5 , Edge 87.0
 - GLPI Version : 9.5.1
 - FormCreator version : 2.10.4

**Additional context**

I clearly think it's related to the beforeunload event : https://github.com/glpi-project/glpi/blob/31dccae2249b9504d94e5466b12ed9faf4f7b7c5/js/common.js#L1155

I think the global variable window.glpiUnsavedFormChanges should be set to false when submitting the new message using the submit button.

**Comment by btry** [comment]
Hi

This confirmation popup belongs to GLPI. It did not behaved well with Formcreator in GLPI 9.5.0 or 9.5.1 (not sure about the exact version).

Please check if this still ocurs with GLPI 9.5.2. Also, you may find in the closed issues of GLPI and here a ticket  related to this problem, and the patch which is in the latest release of GLPI.

**Comment by ricostone** [comment]
Thank you for your very fast answer, i'll go check GLPI project issues.

**Comment by ricostone** [comment]
Duplicate : https://github.com/pluginsGLPI/formcreator/issues/1944
