### ISSUE TITLE
Filtrage catégories disponibles

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/formcreator#2023]
Un formulaire de  dois pouvoir avoir accès qu'aux seules catégories disponibles dans l'entité du formulaire OU à celles provenant d'une entité supérieure (en mode récursif)

  English : A form shall access only the categories on the form's entity OR the categories with recursivity in ancestor entities.

**Comment by btry** [comment]
Hi

As discussed, I'll submit a fix for the develop branch : the fix will introduce a behaviour change which cannot be added in a bugfix release.

**Comment by btry** [comment]
Fixed by commit dc7dda94 in incoming beta version
