### ISSUE TITLE
Form loses conditions when cloning [2.10.4]

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2024]
**Describe the bug**
When we clone a form, and go to the "Preview" ana the form is presented without respecting the conditions of the old form

**To Reproduce**

Select the form> Click Actions> Duplicate. When doing this the form is cloned, however the conditions are lost

Note that the first form "Changing forms" has the following order of questions:
1 - "Selecione a entidade"
2 - "Informe o nome do serviço"
3 - "Descreva sua solicitação"

![image](https://user-images.githubusercontent.com/35368369/100027553-c617ed80-2dcb-11eb-8a10-b9ca8ed58f02.png) 

However after cloning, the order was changed

![image](https://user-images.githubusercontent.com/35368369/100027697-14c58780-2dcc-11eb-8ece-e686582fb1b0.png)

![order](https://user-images.githubusercontent.com/35368369/100027710-1abb6880-2dcc-11eb-9347-173842fa3778.gif)

**Expected behavior**
I hoped that by cloning the form, the order of the questions would be maintained

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : google chrome

GLPI 9.5.2
Formcreator 2.10.4

**Comment by btry** [comment]
Hi

There is the PR #1974 waiting for feedback. It should solve the order loss.

About conditions, there are many possible causes of duplication failure. Please reproduce and check the logs in GLPI. Check also if the name of the duplicate mentions a duplication error.

Finally, export the source form and share its content here. Errors may occur because of an inconaistency.

**Comment by phamorais** [comment]
@btry HI!


the https://github.com/pluginsGLPI/formcreator/pull/1974/commits/a54b873f7a0e0e5cc3e6c72dad32cc0aa78eafd8 it worked perfectly for me. Conditions have not been lost.

**Comment by btry** [comment]
Thank you for your feedbaack, the fix is ready for the next version.

Now, about your conditions : did you find something in GLPI's logs ?

**Comment by btry** [comment]
Hi

> Conditions have not been lost.

The fix should not solve conditions loss. Do you still observe such loss, or can I close ?

**Comment by phamorais** [comment]
@btry wen can close! 

Thx for u support!
