### ISSUE TITLE
le plugin n'apparait pas dans le panneau d'administration

### ISSUE THREAD

**Issue by Dujarrier** [pluginsGLPI/formcreator#2027]
Bonjour,

J'ai téléchargé et décompressé le plugin formcreator en suivant cette méthode 
wget https://github.com/pluginsGLPI/formcreator/releases/download/v2.10.4/glpi-formcreator-2.10.4.tar.bz2
tar jxvf glpi-formcreator-2.10.4.tar.bz2
puis je l'ai déplacé décompressé dans le répertoire qui va bien:
mv formcreator/ /usr/share/glpi/plugins
systemctl restart httpd

mais il n'apparait pas dans le panneau d'administration de glpi alors que fusion inventory et reprots sont bien présents.

J'ai donc testé en téléchargeant le plugin sur mon poste et en le transférant par filezilla

Ma configuration
CentOS Linux release 7.9.2009 (Core)
GLPI 9.4.6 installé depuis remy repository
Formcreator v2.10.4 (This version is compatible with GLPI 9.4.5 or later and GLPI 9.5)

mêmes droits que fusioninventory qui apparait dans le panneau d'administration:
drwxr-xr-x. 14 root root 4096 19 nov.  18:28 formcreator
drwxr-xr-x. 14 root root 4096 14 févr.  2020 fusioninventory 

Pouvez vous m'aider?
Merci par avance

**Comment by btry** [comment]
Bonjour

Il me semble que vote commande **mv formcreator/ /usr/share/glpi/plugins** n'est pas bonne. Vous avez déplacé le contenu di dossier formcreator dans le dossier /sr/share/glpi/plugins

Il fallait faire **mv formcreator /usr/share/glpi/plugins/** (formcreator sans slash final et /usr/share/glpi/plugins/ avec un slash final)

**Comment by btry** [comment]
Oups, je n'ai pas lu la fin... 

Apparemment votre commande était bonne. Vérifiez que le contenu du dossier contient tous les fichiers du plugin.

**Comment by Dujarrier** [comment]
Bonjour,

Je devrai avoir tout ce qui est présent sur la page Code de  [https://github.com/pluginsGLPI/formcreator](url) ?

**Comment by btry** [comment]
presque tout. Le dossier tests n'est pas dans l'archive, ni certains fichiers de la racine du projet.

**Comment by Dujarrier** [comment]
Voici ce qui est dans le répertoire formcreator:
total 348K
ajax          composer.json  css   front     icon.png  index.php  js   LICENSE.md  package.json  README.md  setup.php
CHANGELOG.md  composer.lock  data  hook.php  inc       install    lib  locales     pics          scripts    vendor

**Comment by Dujarrier** [comment]
Le problème ne vient pas du plugin.
J'ai tenté l'installation d'un autre plugin et le problème est le même.
Je vais donc creuser au niveau de mon glpi pour savoir pourquoi il  prend plus en compte les plugins.

Merci de votre aide.
Cordialement

**Comment by btry** [comment]
Je n'ai pas réagi au départ, mais le dossier où vous avez placé les plugins est inhabituel. Je n'ai pas les informations sur le packaging de GLPI depuis les dépôts de Remi. Il faut vous rapprocher du mainteneur du package pour vérifier cela.

Je ferme ce ticket vu qu'on sait qu'il ne s'agit pas d'un problème de Formcreator.
