### ISSUE TITLE
"Actor" type question form no result

### ISSUE THREAD

**Issue by fraktury** [pluginsGLPI/formcreator#2036]
**Describe the bug**
Hello,

I just updated GLPI and formcreator to the latest versions and all of my forms that used "actor" type questions no longer work and show the message "Results cannot be loaded".
Before this update it worked correctly and it was possible to choose several users. I used it to allow the creator to add additional people as requestor or supervisor

**To Reproduce**
1) Create a test form
2) Create an actor-type test question
3) Attempt to answer the form

**Expected behavior**
The list of users should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/23696544/101538239-1468e700-399d-11eb-9787-644cf4bc159e.png)
![image](https://user-images.githubusercontent.com/23696544/101538276-1fbc1280-399d-11eb-8279-8a82254b3290.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

**Smartphone (please complete the following information):**

**Additional context**
GLPI Version: 9.5.3
FormCreator version: 2.10.4

**Comment by btry** [comment]
Hi

Indeed : the field is broken with GLPI 9.5.3. I'm searching for a fix.

**Comment by btry** [comment]
Please test the above fix and feedback.

**Comment by fraktury** [comment]
Hello,
I applied the modifications for these three files, it is now possible for me to use the actor field. The people are also well recorded on the ticket (applicants or observers)
Thank you for your reactivation
I will immediately create a new emergency ticket for a problem with the "glpi_plugin_formcreator_issues" table. Following the migration and even afterwards for some tickets / people, they are not registered or end up disappearing following the passage of the automatic action.
Several users therefore do not see their assistance requests
Regards,
Matthew

**Comment by btry** [comment]
Hi

Thank you for your feedback. I'm waiting for your other issue. It might be related to other ones still pending.

**Comment by fraktury** [comment]
It's the same problem as here:
https://github.com/pluginsGLPI/formcreator/issues/1948
