### ISSUE TITLE
Notification to Observers

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/formcreator#204]
Hello,
It seems that formcreator, when it create a ticket, add the Observer after the creation.
So when you have configured a notification (New ticket) with Observers in "Recipient", the recipenets don-t receive email.
Is it possible to change this behavior?

Thks

**Comment by btry** [comment]
Hi

I don't remember if this was true in 2016. Nowadays, all actors are added early enough to let GLPI send all required notifications.
