### ISSUE TITLE
multi validation : self-service

### ISSUE THREAD

**Issue by morcra** [pluginsGLPI/formcreator#2040]
Hello,

je rencontre un bug sur les tickets avec un double validation (réalisées par une règle métier). 
Les tickets avec un double validation + Validation.percent = 100 %, ne s'affichent plus dans le self-service :/
![image](https://user-images.githubusercontent.com/73166955/101750035-bf2cf280-3ace-11eb-81f2-d65f4ad1c7ba.png)

Je suis actuellement en version 2.10.4-dev (modification #1904 réalisée).

Merci d'avance :)

**Comment by btry** [comment]
Bonjour

Bien que le plugin ne gère pas encore les validations multiples sur un ticket, il devrait y avoir une entrée correspondant à votre ticket dans la table glpi_pmlugin_formcreator_issues.

Pouvez-vous retrouver cette ligne et me dire quel est la valeur de sons statut ?

**Comment by morcra** [comment]
Bonjour,

Je viens de me rendre compte que SyncIssues était exécuté automatiquement toutes les minutes ... Une fois arrêté les tickets ne disparaissent plus... Est-ce correct que cela vient de cela ?

**Comment by btry** [comment]
Bonjour

Non : le plugin ne gère pour le moment qu'une seule validation sur les tickets. 

De mémoire, l'action automatique est réglée pour fonctionner chaque demi-heure. La régler à chaque minute risque d'être trop agressif pour le SGBD. De plus, l'action automatique doit idéalement ne rien faire. Si dans ses journaux vous avez des entrées de journal avec un nombre d'actions non nul, alors il y a eu une incohérence entre le nombre de tickets et le nombre de demandes d'assistance. Ce serait à creuser dans un autre rapport de bug.

Exemple: 
![image](https://user-images.githubusercontent.com/14139801/101884056-69bd1800-3b98-11eb-8766-692214c98433.png)


Si vous n'avez que des rapports avec "0 action terminée" alors tout va bien.

Patientez un petit peu, je devrais avoir un fix bientôt.

**Comment by morcra** [comment]
Bonjour,

Je viens de regarder (j'ai bien une incohérence) :
![image](https://user-images.githubusercontent.com/73166955/101891024-cbce4b00-3ba1-11eb-86f6-29e3765d86b2.png)

Très étrange lorsque Syncissue est exécuté, la demande dans glpi_pmlugin_formcreator_issues disparait. 

Mon process : 
Formulaire > Validation Form User > Ticket création > Règle métier avec deux validations utilisateur > ... 
A partir de de Ticket Création (type = Ticket et plus PluginFormcreatorForm ) si Syncissue est executé la demande disparait de self-service.

**Comment by btry** [comment]
Voici un patch à essayer (préférez un GLPI de test avec uen copie de votre prod). Tout d'abord désactivez l'action automatique de Formcreator. Ensuite appliquez le patch, et ignorez les éventuelles erreurs sur le dosseir tests/ .

Quand vous crééz ou modifiez un ticket, les validations multiples devraient être gérées correctement.

Ensuite, utilisez la requête de l'action automatique ci dessous et vérifiez que les statuts des tickets correspondent à ce qui est attendu. Vous pouvez aussi vérifier que toutes les lignes attendues sont présentes. Il sera peut être plus pratique de modifier la requête pour ajouter dans la clause WHERE de quoi filtrer pour certains tickets.

```sql
SELECT DISTINCT
                  NULL                            AS `id`,
                  `f`.`name`                      AS `name`,
                  CONCAT('f_',`fanswer`.`id`)     AS `display_id`,
                  `fanswer`.`id`                  AS `original_id`,
                  'PluginFormcreatorFormAnswer'   AS `sub_itemtype`,
                  `fanswer`.`status`              AS `status`,
                  `fanswer`.`request_date`        AS `date_creation`,
                  `fanswer`.`request_date`        AS `date_mod`,
                  `fanswer`.`entities_id`         AS `entities_id`,
                  `fanswer`.`is_recursive`        AS `is_recursive`,
                  `fanswer`.`requester_id`        AS `requester_id`,
                  `fanswer`.`users_id_validator`  AS `users_id_validator`,
                  `fanswer`.`groups_id_validator` AS `groups_id_validator`,
                  `fanswer`.`comment`             AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  `tic`.`name`                  AS `name`,
                  CONCAT('t_',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  'Ticket'                      AS `sub_itemtype`,
                  if(`tv`.`status` IS NULL,
                     `tic`.`status`,
                     if(`tv`.`status` IN ('1', '3'),
                        `tic`.`status`,
                        if(`tic`.`status` IN ('5', '6') AND `tv`.`status` = '4',
                           `tic`.`status`,
                           if(`tv`.`status` = '2',
                              '101',
                              '102'
                           )
                        )
                     )
                  )                             AS `status`,

                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tu`.`users_id`               AS `requester_id`,
                  `tv`.`users_id_validate`      AS `users_id_validator`,
                  0                             AS `groups_id_validator`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               LEFT JOIN (
                  SELECT DISTINCT `users_id`, `tickets_id`
                  FROM `glpi_tickets_users` AS `tu`
                  WHERE `tu`.`type` = '1'
                  ORDER BY `id` ASC
               ) AS `tu` ON (`tic`.`id` = `tu`.`tickets_id`)
               LEFT JOIN `glpi_ticketvalidations` as `tv`
                  ON (`tv`.`id` = (
                     SELECT `tv2`.`id`
                     FROM `glpi_ticketvalidations` AS `tv2`
                     WHERE `tic`.`id` = `tv2`.`tickets_id` AND `tv2`.`status` NOT IN (3, 1) 
                     ORDER BY `tv2`.timeline_position ASC, status DESC
                     LIMIT 1
                  ))
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1
```

**Comment by btry** [comment]
Bonjour 

J'ai retravaillé le patch ce matin pour gérer le taux de validation défini par les règles métier. J'ai édité la requête SQL de mon post précédent en fonction.

Si l'action automatique efface la demande d'assistance rattachée au ticket, j'aurai besoin de recouper la requête ci-dessus avec les données du ticket et du formulaire qui l'a généré.

**Comment by morcra** [comment]
Bonjour,

Désolé pour les délais... je n'ai pas compris ou je devais appliquer le patch ci-dessus :/ 
Je dois exécute la requête en direct dans ma BDD  ? 

Merci d'avance,

**Comment by btry** [comment]
Bonjour

Je pense que j'ai oublié de mettre le lien vers le patch pendant la rédaction du message.

De toute façon, la version 2.10 ne sera bientôt plus maintenue au niveau communautaire; et je focalise mes efforts sur le code de la 2.11 car j'ai rendu cette partie testable pour éviter des régressions.

J'ai également versé la semaine dernière des améliorations sur la gestion des validations de tickets.

Pour traiter ce bug, il faudrait que vous utilisiez un environnement de tests avec la dernière révision de la branche support/2.11.0. La version 2.11.0-beta.1 **ne contient pas** les changements que vous avez besoin de tester.

**Comment by btry** [comment]
Voilà un build de la branche support/2.11.0. Renommez l'archive en .tar.bz avant d'extraire son contenu : ce n'est pas un zip.


[glpi-formcreator-2.11.0-nightly.zip](https://github.com/pluginsGLPI/formcreator/files/5795127/glpi-formcreator-2.11.0-nightly.zip)

**Comment by morcra** [comment]
Bonjour,

Merci pour votre retour ! Je viens d'appliquer le patch 2.11.0-nightly et le problème semble toujours présent....
Si l'action auto SynIssue s'exécute alors que la validation n'est pas complété (double validation 50%+50%), le ticket disparait de l'interface self service.... Est-ce que sur 2.11 Synchissue doit être encore exécuté périodiquement ?

**Comment by btry** [comment]
Si vous vérifiez le statut de l'action automatique de Formcreator, vous devriez voir qu'elle est désormais désactivée. C'est programmé dans l'upgrade vers la version 2.11. Pour avancer sur votre ticket il faut tester les cycles de validation d'un ticket avec un ticket fraîchement créé (chronologiquement après votre upgrade).

Si il y a encore des soucis, je saurai où cela se passe, ce qui rendra les choses bien plus faciles à reproduire. De plus j'ai amélioré la  gestion des valdiations. Le plugin devrait pouvoir gérer un nombre quelconque de validations pour un ticket, avec prise en charge du ratio de validation.

**Comment by morcra** [comment]
Merci pour vos réponses et vos actions !!! 
Quels sont les ajouts dans la 2.11 concernant la multi-validation ? Il sera possible de valider plusieurs fois un meme formulaire par plusieurs personne ? Si c'est le cas, ca répondrait à ma problématique .... :) 

Concernant la chronologie de mon problème actuel : 

- Saisie des informations sur un formulaire > OK
- Validation Formcreator par utilisateurs > OK 
- Création du ticket > OK

Suite : 

- Règle métier demandant la validation avec validation pour un **seul utilisateur** supplémentaire > OK
- Règle métier demandant la validation à **deux utilisateurs** supplémentaires > **OK MAIS si SyncIssue le ticket disparait de self-service après toutes les étapes après ** > Ticket en "en attente de validation" (0%) ou Ticket en "validé" (100%)

J'ai l'impression que le problème provient uniquement lorsqu'une multi validation est initiée par GLPI avec un pourcentage de validation.

**Comment by morcra** [comment]
Yes ! je comprend mieux maintenant ! 

En tout cas merci pour toutes ces précisions ! Et pour le temps accorder à cette issue ! 

Bonne journée :)

**Comment by btry** [comment]
Bonjour

> Merci pour votre retour ! Je viens d'appliquer le patch 2.11.0-nightly et le problème semble toujours présent....
Si l'action auto SynIssue s'exécute alors que la validation n'est pas complété (double validation 50%+50%), le ticket disparait de l'interface self service.... Est-ce que sur 2.11 Synchissue doit être encore exécuté périodiquement ?

Je pense avoir trouvé le bug. Voyez le ticket #1948 et les 2 patches (un pour la version 2.10 et un pour la version 2.11). Ils sont à utiliser  en environnement de test ! Je suis très intéressé par des retours. Sy SyncIssues est désactivé, il est possible de tester sa requête manuellement. Si vous souhaitez faire un test de cette manière, je transmettrai la requête avec quelques instructions pour l'utiliser.

**Comment by btry** [comment]
Bonjour

Formcreator 2.11 est en fin de vie et des méliorations ont été faites depuis sur la synchro des demandes d'assistance et la validation. Ce ticket obsolète.

Note : en version 2.14.0 il sera pposible de faire de la validation multiple pendant la validation de la demande d'assistance, avant la génération des cibles.
