### ISSUE TITLE
Fields usage on forms

### ISSUE THREAD

**Issue by piovisqui** [pluginsGLPI/formcreator#2050]
Hello. Now I have a features requests :D

1. On the form question, could we have a multiple selection option for GLPI objects and items, like localizations and users? So we can select multiple users and attribute the ticket to them.
2. Could we use fields created with the "custom fields" plugin in the forms?

**Comment by bazingavp** [comment]
Hello,
I am not an expert at all on glpi and formcreator but I may have an answer for your 2nd point.
If you have the plugin "fields" (https://github.com/pluginsGLPI/fields), you can already add a question of type "Dropdown" ("intitulé" in French) and then you can select you additionnal field.

**Comment by btry** [comment]
Hi

1.
You can use the question of type Actors to choose several users (italso allows email addresses to handle accountless users). This question can be used to assign several users to a target ticket.

**Comment by piovisqui** [comment]
Thanks for the help, it worked. Is there a way to transport the custom field answer to the ticket field (the text already goes)?

**Comment by btry** [comment]
Hi

> Is there a way to transport the custom field answer to the ticket field (the text already goes)?

What do you mean ? Did you used Fields pltuin to display additional fields on Formcreator ? If yes, then Formcreator will ignore them.

**Comment by bazingavp** [comment]
I use a question with custom field just as a trick to be able to reuse a dropdownlist with the same options in several forms.
The text of the selected option goes in the ticket description (as it seems to work for you as well) and it is just the behaviour I expect.

**Comment by btry** [comment]
Hi 

@bazingavp

This should work. As soon as a dropdown is available in the form designer (admin side of Formcreator) then Formcreator shall behave flawlessly.

@piovisqui : did the answer helped you ?

**Comment by piovisqui** [comment]
As @bazingavp  said in question #1 , it works. I also understood the #2 configuration.  My point was to pass the custom field to the ticket instead of just writing it. This would make the info relational (an entry in a table rather than a text string). I understood that this behavior is not possible.
