### ISSUE TITLE
Catégorie du ticket généré non attribuée à partir du gabarit de ticket

### ISSUE THREAD

**Issue by bazingavp** [pluginsGLPI/formcreator#2051]
**Describe the bug**
Ticket généré sans catégorie alors que le gabarit en possède une.

**To Reproduce**
1. Créer un gabarit de ticket avec le champ prédéfini "Catégorie" avec une valeur affectée
2. Attribuer ce gabarit de ticket en cible d'un formulaire
3. Laisser le champ "Catégorie" dans la cible du formulaire sur la valeur "Catégorie depuis le gabarit ou aucune".
4. Saisir le formulaire et valider
5. Le ticket généré n'a pas de catégorie alors qu'elle est bien défini sur le gabarit

**Expected behavior**
Le ticket généré devrait avoir la catégorie définie sur le gabarit associé à la cible du formulaire

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge chromium
 - Version 80

**Comment by btry** [comment]
Bonjour,

Avec quelle version de Formcreator et de GLPI ?

**Comment by bazingavp** [comment]
Bonjour,
Cela se produit sur les dernières versions : GLPI 9.5.3 et formcreator 2.10.4.

Je suis en train de monter de version depuis GLPI 9.3.2 + formcreator 2.8.5, donc je ne sais pas depuis quelle version le problème apparaît.
Merci pour votre aide

**Comment by bazingavp** [comment]
Impeccable, je valide le correctif !
Merci beaucoup pour votre réactivité et votre efficacité.
Bonne journée

**Comment by btry** [comment]
Merci pour  votre retour.
