### ISSUE TITLE
wrong url link on validation request mail

### ISSUE THREAD

**Issue by spegghy69** [pluginsGLPI/formcreator#2057]
On validation form mail, the link is wrong on my case:

my URL application is https://mydomain.com/service/account/glpi/

The resulting link is    https://mydomain.com/service/account/glpi/service/account/glpi/marketplace/formcreator/front/formanswer.form.php?id=2

the 3 directory path of the URL are repeated.
-
The correct URL is 
https://mydomain.com/service/account/glpi/marketplace/formcreator/front/formanswer.form.php?id=2

**Comment by btry** [comment]
Hi

Can you try the above fix ? It should solve the prblem.

**Comment by spegghy69** [comment]
It's ok, thank you.
Pls, close the issue.

**Comment by spegghy69** [comment]
Solved

**Comment by btry** [comment]
Thank you for your feedback
