### ISSUE TITLE
Suggestion in textfield

### ISSUE THREAD

**Issue by lucastva** [pluginsGLPI/formcreator#2061]
Hi! I have suggest for yous, there is a possibility PASTE (CTRL+V) the printscreen or screenshot on textfield?
For example:
![image](https://user-images.githubusercontent.com/71664545/103029001-a1807400-4537-11eb-85e7-0423c1c0d866.png)

**Comment by lucastva** [comment]
**Note: The problem only happens when the user is not logged in to GLPI**

**Comment by btry** [comment]
Hi

This is a bug. If I add a file upload question in the form i can add a picture in the textarea.

As a workaround I believe (not tested yet) that you can add a file upload question and use a condition to make it always hidden.

**Comment by btry** [comment]
Hi

Please test the above fix and feedback.

**Comment by lucastva** [comment]
Hi! Worked now!
![image](https://user-images.githubusercontent.com/71664545/103601772-2335b180-4ee9-11eb-8448-3ca490ad9bc2.png)

Thanks!
