### ISSUE TITLE
Resize textarea and decrease the printscreens

### ISSUE THREAD

**Issue by lucastva** [pluginsGLPI/formcreator#2070]
I can resize the textarea?
I think small! And when i paste the printscreen, the images be giant!
My users suggest for me to increase the text area and resize the printscreen to smaller size.

See the example below: 
![image](https://user-images.githubusercontent.com/71664545/103602664-5b3df400-4eeb-11eb-87df-f3c5e2e05f59.png)

**Comment by lucastva** [comment]
**Note: This happens only with non-logged in users**

**Comment by btry** [comment]
Hi

The problem should be already solved in the next minor version of the plugin. Please wait for the release of the version 2.11.0-beta.1 .

**Comment by btry** [comment]
Hi 

The first beta of 2.11 is out today. If you have the opportunity run it on a testing environment, please check if this problem still occurs.

**Comment by btry** [comment]
Hi 

Having no feedback, I close. With versin 2.11 it appears that the textarea's width is correct

![image](https://user-images.githubusercontent.com/14139801/106459043-918e7500-6491-11eb-9405-66c3ba938119.png)
