### ISSUE TITLE
No form available when system language is changed

### ISSUE THREAD

**Issue by JhimmyLiborio** [pluginsGLPI/formcreator#2071]
**Describe the bug**

Regardless of the profile used, the forms created are unavailable when the default system language is changed. In some moments the default language has been changed automatically in the edge browser causing forms to be unavailable

**To Reproduce**

1. Go to 'HOME'
2. Click on 'THE FORM TAB'
3. Change the 'LANGUAGE' shown in the top right bar.
4. See error NO FORM AVAILABLE

**Expected behavior**

Forms created in the system's default Brazilian Portuguesel.

**Screenshots**

This is the screen with the active form

![Form ativo](https://user-images.githubusercontent.com/8010163/103666232-beab3e80-4f4a-11eb-978e-7d9bba5442ef.PNG)

![form-perfil-tecnico](https://user-images.githubusercontent.com/8010163/103665014-4b54fd00-4f49-11eb-8bdc-33d902165161.PNG)

This is one of the generic forms for registering service requests

![Requisição via form](https://user-images.githubusercontent.com/8010163/103665063-5b6cdc80-4f49-11eb-940d-bc2648b6b823.PNG)

After filling out the form and opening a ticket, the form is no longer available due to an automatic language change to English. And also manually changing the language

![Form-not-visible](https://user-images.githubusercontent.com/8010163/103665501-df26c900-4f49-11eb-9fdd-496d1bc0f9c6.PNG)

This is seen in all profiles. But the user profile (self-service) is the most affected. System logout is required as it is not possible in this profile to change the language in the top menu bar to gain access to the forms again.

![Form-Self-service](https://user-images.githubusercontent.com/8010163/103669115-51011180-4f4e-11eb-927b-58feb7692a6e.PNG)

![perfil self](https://user-images.githubusercontent.com/8010163/103669094-4b0b3080-4f4e-11eb-8853-0900e8c2be40.PNG)

My request

![My request](https://user-images.githubusercontent.com/8010163/103668549-98d36900-4f4d-11eb-8fea-4dfc5e58ac5c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Form Version 2.10.4

**Your GLPI setup **

```
GLPI 9.5.3 ( => /var/www/html/glpi)
Installation mode: TARBALL
```

**Comment by btry** [comment]
Hi

Can you show the main page of a form you expect to see ?

**Comment by JhimmyLiborio** [comment]
I hope to visualize the forms I created. But when the language is changed automatically after a request through form or manually for English the form is unavailable
 
 
user profile

![Form-perfil selfservice](https://user-images.githubusercontent.com/8010163/103662221-0ed3d200-4f46-11eb-9a86-cdab4562126f.PNG)

administrator profile

![form-perfil super admin](https://user-images.githubusercontent.com/8010163/103662592-84d83900-4f46-11eb-8fed-8b61f1ebb473.PNG)

**Comment by btry** [comment]
There are not the screens I expected. I meant the form in the administration part of the plugin. I want to check if the plugin is active, not deleted, iin which entity it is stored and which language it uses.

**Comment by JhimmyLiborio** [comment]
Sorry, update as screens in the question above

**Comment by JhimmyLiborio** [comment]
Thank you for your attention. Here's the screen.

![Form ativo](https://user-images.githubusercontent.com/8010163/103669663-0633c980-4f4f-11eb-97f4-ebe7be2b6e4e.PNG)

**Comment by JhimmyLiborio** [comment]
> There are not the screens I expected. I meant the form in the administration part of the plugin. I want to check if the plugin is active, not deleted, iin which entity it is stored and which language it uses.

Thanks for your attention here is the correct screen

![Form ativo](https://user-images.githubusercontent.com/8010163/103670139-9540e180-4f4f-11eb-8d2e-0d4b847d4de0.PNG)

**Comment by btry** [comment]
Ok 

I see
- all forms are active: OK
- they are not in the bin: OK
- they belong to the entity UFAM
- their language is pr_BR
- their access policy is either private or public

Lets focus on the form named **E-Mail**

Which profile is allowed to use this form ?

When you are on the central or in the service it appears your language is English (below the screenshot you shared earlier)
https://user-images.githubusercontent.com/8010163/103665501-df26c900-4f49-11eb-9fdd-496d1bc0f9c6.PNG

Then this is normal that the forms are not visible. You need to set them to English (with respect of the country variant), or "all languages". Try this and tell if it works.

**Comment by JhimmyLiborio** [comment]
> Ok
> 
> I see
> 
> * all forms are active: OK
> * they are not in the bin: OK
> * they belong to the entity UFAM
> * their language is pr_BR
> * their access policy is either private or public
> 
> Lets focus on the form named **E-Mail**
> 
> Which profile is allowed to use this form ?
> 
> When you are on the central or in the service it appears your language is English (below the screenshot you shared earlier)
> https://user-images.githubusercontent.com/8010163/103665501-df26c900-4f49-11eb-9fdd-496d1bc0f9c6.PNG
> 
> Then this is normal that the forms are not visible. You need to set them to English (with respect of the country variant), or "all languages". Try this and tell if it works.
> 
> EDIt: By the way, I don't understand how your language can be English, and the UI shows an other language (portuguese I guess ). This is not normal.


- All profiles have access to email forms. (self-service, technician, administrator)

- The language of the system and forms is Portuguese. The image I showed is the result of what happens when I make a request through the form. https://user-images.githubusercontent.com/8010163/103665501-df26c900-4f49-11eb-9fdd-496d1bc0f9c6.PNG

For example, when you open the e-mail form and fill in the information and click on send, automatically when you finish the request the language changes to English and consequently the form is no longer visible because it is set to Portuguese.

- I will set the form to English since every request within a form automatically changes the language to English while maintaining it in Portuguese.

**Comment by btry** [comment]
I never observed unexpected change of the current language. Also, when you submit a form, if the language changes, the UI should obey the change and switch to english.

Can you show the list of other plugins in GLPI ? Can you try to disable all plugins, keeping Formcreator active, and see if this strange behavior still occurs ?

**Comment by JhimmyLiborio** [comment]
Thanks, it worked, the form is available set for all languages. Although the language continues to change automatically after requests. There is a list of plugins:

![Lista de plugins](https://user-images.githubusercontent.com/8010163/103700022-347ace80-4f7a-11eb-977e-b9f74a10a087.PNG)

**Comment by btry** [comment]
Ok, nice, this is at least a workaround, but this is not satisfying to have this language switch. I believe that Formcreator is not responsible of this bug, but just in case, disable the plugins **Panel** and **GLPI Modifications**.

**Comment by JhimmyLiborio** [comment]
After deactivating the plugins, the behavior continues. I also believe now that it is not a Formcreator bug. Thanks for the help and workaround.

**Comment by btry** [comment]
If you identified where the bug comes from don't hesitate to report the bug in the appropriate repository, and add a link here to the other repository's issue.

If you think we can stop investigating about the language problem, feel free to close this issue.
