### ISSUE TITLE
Catégories de formulaire non fonctionnelles

### ISSUE THREAD

**Issue by maaxv** [pluginsGLPI/formcreator#2073]
Bonjour,

J'ai mis en place Fromcreator 2.9.1 sur un GLPI 9.4.6.

Tout est niquel au niveau des formulaires et des tickets.

Cependant, sur l'écran d'accueil, je souhaiterais que les formulaires désignés soient visibles. C'est le cas lorsque le formulaire est sans catégorie.

Mais lorsque j'y ajoute une catégorie, ou sous-catégorie, le formulaire n'est plus visible à l'accueil.

![image](https://user-images.githubusercontent.com/77054875/103764461-cbe42e00-501b-11eb-849e-c86045e7e873.png)

Je ne sais pas s'il s'agit d'un bug, ou si c'est moi qui ait mal testé, mais j'ai essayé plusieurs formulaires, sur plusieurs entités et rien y fait.

Eventuellement, si je pouvais renommer le texte "formulaires sans catégorie" cela pourrait m'offrir une solution de repli, étant donné que les formulaires sont visibles lorsqu'ils font parties de celle-ci.

Merci d'avance.

**Comment by btry** [comment]
Bonjour

Essayez la version 2.10.4. Je me souviens d'un bug avec les catégories et cette page.

Le libellé "formulaires sans catégorie" est codé en dur, il n'est pas possible de le modifier sans toucher au code du plugin. Il reste possible de le modifier en jouant sur les traductions, si vous savez manipuler l'outil gettext.

Notez que la version 2.10.4 est la dernière version prenant en charge GLPI 9.4, que la série 2.11 ne sera compatible qu'avec GLPI 9.5 et est sur le point de sortir. Les versions 2.9 ne sont plus prises en charge, et ce sera bientôt également le cas pour les versions 2.10. Envisagez la mise à jour de GLPI vers 9.5.

**Comment by maaxv** [comment]
Hello !

Ca marche niquel. Merci pour l'info !

A bientôt !
