### ISSUE TITLE
Forms : Spécifier un groupe acteur dependant d'une information supplementaire connue dans GLPI

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2077]
Actuellement, les acteurs ou groupes sont attribués **des la creation du formulaire**. OK
> Je n'ai pas trouvé le moyen de spécifier un groupe en fonction d'une question posée.

Exemple : on a besoin de supprimer une ressource (une DB, par exemple)
En fonction du type de la ressource (ici DB) les acteurs qui doivent réaliser cette tache sont différents.

Il serait dommage de devoir creer 'n' formulaires sachant que le type de la ressource n'est pas forcement connu par le demandeur, mais est stocké **dans GLPI (type moteur DB, par exemple et groupe technique DB)**

Comment faire alors pour implementer ce type de formulaire ?
Merci

**Comment by btry** [comment]
Bonjour

Dans Formcreator 2.11 il y a des nouvelles options :
- groupe depuis un objet
- groupe technicien depuis un objet

Ces options permettront de récupérer ces groupes pour les ajouter au ticket cible.

Vous pouvez tester cette fonctionnalité sur un environnement de test en attendant que la première release soit livrée. Profitez en pour faire un test de l'ensemble du plugin et remonter les éventuels bugs.

**Comment by EC2311** [comment]
Bonjour

En version 2.10.1, la possibilité de selectionner un groupe technique d'un objet GLPI est disponible :) 
Je l'ai testé : et ca marche !!!

On a aussi en effet la notion de 'groupe d'un objet' . je pense que dans le cadre ou un groupe autre que technique est present cela doit etre ok. mais si un groupe <> technique n'est pas present dans la table, alors on n'envoie nulle part.
Ex : Plugin Database : on a bien un groupe technique, mais il n'existe pas d'autre groupe...
contrairement à Ordinateurs , là on a bien 2 groupes.

**Comment by btry** [comment]
Bonjour

Je ne me souvenais plus d'avoir mis la fonctionnalité dans les version 2.10. 

Si le groupe n'est pas défini (ou est introuvable) alors il ne sera pas ajouté à la cible.

En effet, en relisant le code, si la colonne du groupe n'existe pas dans l'objet, il y aura un warning. Il faut que je renforce le code sur ce point.
