### ISSUE TITLE
Usage of external table to fill a dropdown list

### ISSUE THREAD

**Issue by coco221** [pluginsGLPI/formcreator#2078]
Hello,

My problem is as follow, in my form I ask questions with a textbox but frequently the users use different spelling of the words and that's not good. The solution would be to have a dropdown list instead of the textbox.

I would like to know if it's possible to inject data in the form to fill up the dropdown list, the data is not fixed and daily update would be necessary.

**Comment by btry** [comment]
Hi

The only and best way to do that would be to use the REST API provided by GLPI. But the plugin is not tested when used via the API. Use a testing environment first. If you find a bug, fill a dedicated issue.
