### ISSUE TITLE
Impossible d'afficher les resultats

### ISSUE THREAD

**Issue by Tijah82** [pluginsGLPI/formcreator#2080]
Bonjour,

J'ai mis a jour GLPI et Formcreator, depuis j'ai ce message lorsque je veux choisir un acteur

![image](https://user-images.githubusercontent.com/48673805/104568296-3581bf00-5650-11eb-9e99-a34eaae94d85.png)

Savez vous pourquoi et comment le résoudre ? Je n'ai pas de soucis dans les autres fonctions de GLPI je vois bien les utilisateurs.

Merci d'avance pour l'aide que vous m'apporterez

**Comment by btry** [comment]
Bonjour

Quelle est la version de Formcreator, et quelle est la version de GLPI ?

**Comment by Tijah82** [comment]
GLPI 9.5.3 et Formcreator 2.10.4. Cela se produit uniquement avec "Acteur", si je mets object GLPI - Utilisateur ca fonctionne.

![image](https://user-images.githubusercontent.com/48673805/104577008-41be4a00-5659-11eb-858e-335b1f91ad22.png)

**Comment by btry** [comment]
GLPI 9.5.3 contient un correctif de sécurité qui impacte Formcreator. Le souci est résolu avec le commit 048902af63d60b05ffc229d360a13b755c581d48 . Vous devez l'appliquer manuellement car il n'y aura pas de version 2.10.5 : la version 2.11 est imminente.

**Comment by Tijah82** [comment]
Ok merci, pour le moment je vais rester sur Object GLPI puisque cela marche aussi comme ca et je vais attendre la version 2.11 qui devrait corriger le problème non ? Cela n'impacte rien d'autre si ?

**Comment by btry** [comment]
Bonjour

La version 2.11 contient le correctif. Pas d'autre impact connu pour ce bug.

Du coup, je pense qu'on peut fermer ce ticket.

Label duplicate car le bug a été initialement remonté par la communauté dans une autre issue ici même. Pas le temps de chercher son id aujourd'hui.

**Comment by btry** [comment]
Dropdownfiels are impacted by this issue. Here is the patch for v2.11.0 : 44b5244d39bca5f0aafbaff409c6d98af6f6974d
