### ISSUE TITLE
Can't upgrade to v2.11.0-beta.1

### ISSUE THREAD

**Issue by capu81** [pluginsGLPI/formcreator#2083]
Hi, i like to upgrade from 2.10.4 to v2.11.0-beta.1. I deactivate old version, moved folder to /tmp, downloaded new package from here https://github.com/pluginsGLPI/formcreator/releases/tag/v2.11.0-beta.1 and unpack the new archive in plugins folder (like all other plugins), but in glpi config/plugin version remain 2.10.4 and no upgrade was made. Why?

Thank you

Ilario

**Comment by btry** [comment]
Hi

:warning:   : this version is for testing purpose only. Do not use on production !

- Did you actually move the files, or copy them ? 
- GLPI has now a marketplace. Did you check that you don't have two copies of the plugin : one in the marketplace folder and an other un the plugins folder ?

**Comment by capu81** [comment]
Solved, the problem is in the marketplace folder. Thank you.
I've upgrade to test if my problem #2081 was solved but not.

**Comment by btry** [comment]
Ok, I'll investigate your other issue with the beta version.

I close this isue, and let's see the other one.
