### ISSUE TITLE
Can't translate left menu items

### ISSUE THREAD

**Issue by capu81** [pluginsGLPI/formcreator#2088]
**Describe the bug**
I use formcreator in italian language. Left menu are partially translated. I've modifyed the it_IT.po with POedit and overwrite the old one but no translation appear. I've tried to clear cache, change browser and incognito mode (firefox and chrome)
Bugged menu are:
My requests for assistance
Knowledge Base (ther is no entry in .po file)
Consult feeds

**To Reproduce**
Set the italian language

**Expected behavior**
Right translation appear on left menu

**Screenshots**
![translate](https://user-images.githubusercontent.com/25194917/105326747-602ec300-5bce-11eb-9852-6fad2f88ddad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 18363
 - Browser: Chrome (87), Firefox (84)

**Additional context**
Formcreator version 2.11.0 beta (revision downloaded today 2021/01/21)

**Comment by btry** [comment]
Hi

Modifying a .po file is not sufficient. You also need to build the matching .mo file, which is the resource used by GLPI for translations.

If you want to update the locales, use a copy of the reporisoty of Formcreator by downloading a ZIP of the branch, or by using git.

Next, assuming you have composer and you are in the fodler of the plugin, install the dependencies: ```composer install```

Translate all strings you need on Transifex : https://www.transifex.com 

Download the locales and build .mo files with the command ```vendor/bin/robo locales:generate . Locales translated at 70% minimum will be updated

To apply the locales you may need to restart PHP-FPM or yout HTTP server (depending on your configuration).

**Comment by capu81** [comment]
POEdit make the new mo file. Now work, i've only to restart httpd.

Entry "Knowledge base" is not translatable? I can't find it in the po file

**Comment by btry** [comment]
It is translatable, I checked.If you don't follow the workflow I described above you may have an outdated version.  You may workaround by finding the missing entry in locales/glpi.pot and copying it in it_IT.po.

Please, consider to share your .po file, Italian spaking users will appreciate it.

**Comment by capu81** [comment]
Work!

[it_IT.zip](https://github.com/pluginsGLPI/formcreator/files/5848967/it_IT.zip)

**Comment by btry** [comment]
Thank you.

Your contribution is uploaded to Transifex, it should be available in the incoming release.
