### ISSUE TITLE
[2.11.0-beta.1] Cannot create a 1/4 field on a row

### ISSUE THREAD

**Issue by OscarBeiro** [pluginsGLPI/formcreator#2089]
**Describe the bug**
If you want to create a 1/4 field on a single row. It is not possible. 
It might be by design.

**To Reproduce**
If the field is 1/4 row, next field is added on its right. It can't be alone.
![image](https://user-images.githubusercontent.com/18396050/105378851-86735380-5c0c-11eb-944b-ae3a2f5d1f86.png)
However if the field size is increased to 1/2 row, it can be done
![image](https://user-images.githubusercontent.com/18396050/105379096-cb978580-5c0c-11eb-886a-98b2783842f8.png)

**Expected behavior**
It should be allowed a field with any size in any row.

**Screenshots**

**Desktop (please complete the following information):**
GLPI 9.5.3 
Formcreator 2.11.0-beta.1

**Additional context**
Congratulations on this new version. You might consider bumping Version to 3 :)

**Comment by btry** [comment]
Hi

I think the behabior you observe is related to a se"tting of the grid qhere questions are positionned. The grid is configured in a way that makes questions move up if there is no collision.

Here is an example:

![image](https://user-images.githubusercontent.com/14139801/105381119-f551ac00-5c0e-11eb-8c47-e9db9ab05fc1.png)


If I move the question **Move me** to the right then the question **See my move** will have room to jump 1 row up. And it will.

For the same reason, if you go bach to the initial positions, you won't be able to move **See my move** on the last column of its row. It will jump 1 row up because there is room for it here.

**Comment by btry** [comment]
Hi

I got an idea to workaround this limitation : use questions of type hidden. Be aware that you will have extra fields in your targets when you use ##FULLFORM## tag.

I think this will work.

**Comment by OscarBeiro** [comment]
Hi @btry,

When you talk about " setting of the grid where questions are positioned", do you mean this is a hardcoded setting or something that is configurable within the plugin?

About your workaround, it is not "elegant" but it works. Finally, I know what are hidden questions for :).

Thanks

**Comment by btry** [comment]
Hi

> When you talk about " setting of the grid where questions are positioned", do you mean this is a hardcoded setting or something that is configurable within the plugin?

This is not configurable in the UI. The grid is a 3rd party javascript library introduced in the core of GLPI (in version 9.4 if I remember well). The grid behaves in a very annoying way if I allow empty areas between questions. I think that the current behavior is not perfect but better. 

> About your workaround, it is not "elegant" but it works. Finally, I know what are hidden questions for 

Hidden questions are useful when you want to add a constant  data in a target  (which is defined by the form designer). I'm consideriing th add a dummy type of question to avoid impact on ##FULLFORM## tag.

**Comment by OscarBeiro** [comment]
Hi,

I don't know if it is that important. Of course, the dummy question will be easier to implement, than altering the library.

Thanks for the Hidden question information, eventually we will find the utility for it.

Cheers,

**Comment by btry** [comment]
Hi

I guess we can close this issue now.
