### ISSUE TITLE
Idée .

### ISSUE THREAD

**Issue by Metastase** [pluginsGLPI/formcreator#209]
Bonjour , je trouve le plugin excellent . Néanmoins il serait utile si il était possible d'ajouter des champs . Personnellement , j'ai crée un formulaire de demande de création de compte informatique. L'utilisateur renseigne et valide. Ce qui manque c'est l'ajout de champs uniquement visible par les techniciens leur permettant d'indiquer des commentaires par questions répondues (du style 'Fait' / en attente , etc)

**Comment by btry** [comment]
Bonjour

La finalité de ce plugin est de générer des tickets en utilisant des formulaires "spécialisés". Ce que vous décrivez est implémenté dans les suivis, tâches et statut des tickets.

**Comment by Metastase** [comment]
Effectivement mais il n'est pas ,enfin je crois possible d'ajouter un suivi rattaché une question du formulaire. Le suivi fonctionne pour l'ensemble du ticket. La solution serait peut être pour ma part si je comprend bien d'éclater mon formulaire en plusieurs formulaires, en fonction du nombre de techniciens. Ou bien a partir d'un formulaire de créer plusieurs tickets en fonction des questions  du formulaire (mais ici je ne suis pas sure de moi !)

**Comment by btry** [comment]
Le suivi concerne effectivement l'ensemble du ticket.

Je crois me souvenir qu'il est possible de générer plusieurs tickets à partir d'un seul formulaire. Ca peut prendre son sens si plusieurs tâches n'ont pas de dépendance les unes par rapport aux autres. Sinon, ça me parait plus compliqué d'éclater la demande en plusieurs tickets car la dépendance sera perdue et pourrait conduire à des difficultés dans le traitement de la demande.

**Comment by Metastase** [comment]
OK , merci pour les informations, je vais creusé un peu plus la question en faisant plusieurs tickets.
Plusieurs destinations avec chacun leur balises.

Bonne journée
