### ISSUE TITLE
[2.11-beta1] Ticket URL

### ISSUE THREAD

**Issue by morcra** [pluginsGLPI/formcreator#2090]
Hello,

je suis en test sur la Beta 2.11-beta1.  J'ai des bugs liés aux url des ticket sur le self-service... Est-ce que vous avez fait des modifications sur la 2.11 ? 
Pour exemple les notifications avec le paramètre ##ticket.url## redirige sur une page blanche :  issue.form.php?id=**128**&sub_itemtype=Ticket
L'adresse du ticket sur le self-service est maintenant sous la forme : issue.form.php?id=4

D'autre lien sont cassé suite à ces modifications comme ici : 
![image](https://user-images.githubusercontent.com/73166955/105467107-84090c00-5c95-11eb-8817-4b053f1b5e4d.png)

Merci d'avance,

**Comment by btry** [comment]
Bonjour

Il y a eu un correction de bug il y a quelques semaines portant sur la navigation dans les demandes d'assistance. Je pense qu'il  faut  chercher par là puisque les URL d'accès ont effectivement changé. Avant il fallait un couple ID + sub_itemtype. Maintenant l'ID suffit, mais l'ID de l'ancienne méthode n'est pas le même que l'ID de la nouvelle.

Tout d'abord, je vois sur la capture d'écran que vous n'êtes pas dans "mes demandes d'assistance". Par quel moyen êtes vous arrivés sur cette page ?

**Comment by morcra** [comment]
Merci pour le retour ! C'est donc pour cela que les valeurs de notifications ne fonctionne plus (utilisent l'ancienne méthode).

Hahaha désolé, c'était juste pour illustrer ... Cette interface n'est pas accessible normalement. 
Je suis passé par une notification et ##formcreator.validation_link## (si déjà validée on peut accéder à cette interface). 

Mon problème principal est lié au notification, ou il est impossible de rediriger vers le ticket...

**Comment by btry** [comment]
Bonjour

Est ce  qu'on peut fermer ce ticket ? Normalement tous les liens générés par Formcreator 2.11 doivent fonctionner. Les anciens seront cassés, à voir selon l'impact si il faut que je mette en place une solution.

**Comment by morcra** [comment]
Hello,

Pas de problème pour moi. Je repars de zéro sur la 2.11 :) 
Vous pouvez fermer le ticket.


Bonne journée,

**Comment by morcra** [comment]
Bonjour,

Désolé mais sur la v2.11 cela ne semble toujours pas marcher ...
![image](https://user-images.githubusercontent.com/73166955/106442869-1c647500-647c-11eb-8aba-b364c4a602a1.png)
Les paramètres suivant ne fonctionnent plus ... 

![image](https://user-images.githubusercontent.com/73166955/106442999-49188c80-647c-11eb-8df8-5b08742e566a.png)
Les url sont KO sur les notifications...

**Comment by btry** [comment]
Bonjour

##ticket.url## et ##ticlet.urlvalidation## donnent un accès direct aux tickets.

Si l'utilsiateur passe par le catalogue de services, il n'e pourra pas accéder aux tickets directement par ces liens.

Si le message est généré par une notification appartement à Formcreator (voir ci dessous), alors vous pouvez utiliser le tag ##formcreator.validation_link## qui sera peut être plus approprié à votre besoin. 

![image](https://user-images.githubusercontent.com/14139801/106446513-a1ea2400-6480-11eb-992e-db0c613fbafb.png)

**Comment by morcra** [comment]
Bonjour,

Le seul problème c'est que avec les notifications de type "Ticket". Il est impossible d'utiliser des gabarits "formcreator" et les variables formcreator (##formcreator.validation_link## ou ....) 
![image](https://user-images.githubusercontent.com/73166955/106468413-2a2af200-649e-11eb-8f48-137dbb04c1ff.png)

C'est vraiment dommage, car c'était vraiment pratique sur les versions précédentes :)

**Comment by btry** [comment]
Vous ne pouvez pas désactiver les notifications de ticket pour les demandeurs et laisser actives les notifications de Formcreator ?

**Comment by morcra** [comment]
Non car je réalise une deuxième validation (par une règle métier) sur glpi. Il faut donc prévenir l'utilisateur via cette notification.

**Comment by btry** [comment]
On est déjà dans un scénario où GLPI fait des redirections HTTP. Il faut que j'arive à intercaler Formcreator pour renvoyer vers la demande d'assistance correspondante.

**Comment by btry** [comment]
Je viens de faire un test sur le premier des 2 liens. Je ne vois pas de problème, je suis redirigé vers le ticket comme attendu.

**Comment by btry** [comment]
Bonjour

Je pense avoir trouvé ce qui ne va pas. J'ai besoin de voir la page que vous obtenez quand un utilisateur utilise ces liens. Il se peut qu'il arrive sur la mauvaise demande d'assistance, qu'il ait une erreur liée aux droits d'accès à une demande ou qu'il arrive sur une demande inexistante.

**Comment by btry** [comment]
Pouvez-vous essayer ce correctif ?

**Comment by btry** [comment]
Bonjour

J'ai eu un autre retour identique à ce ticket, et le correctif a été validé. Je ferme donc ce ticket et vous invite à prendre le correctif ci dessus.
