### ISSUE TITLE
Form duplicating backslashes

### ISSUE THREAD

**Issue by samuelstj** [pluginsGLPI/formcreator#2092]
When we use a form to create a new ticket, all fields with backslash get duplicated.

I tested on Title and Description.

Eg.:
I insert in a formcreator field: **\\networkfiles\folder\test**
It turns on the ticket description: **\\\\networkfiles\\folder\\test**

**Comment by btry** [comment]
Hi

What is your version of Formcreator ?

**Comment by btry** [comment]
I reproduce with 2.11.0-beta.1.

**Comment by btry** [comment]
Hi

Please test the fix #2093 and feedback. If you're quick enough, I may include it in the incoming 2.11.0. If not, I will include it in the next maintenance release.

**Comment by btry** [comment]
Thank you for your feedback on the PR.
