### ISSUE TITLE
[2.11] FullForm attribute is not translate in email notifications

### ISSUE THREAD

**Issue by boivink** [pluginsGLPI/formcreator#2096]
Since i upgraded formcreator to 2.11 latest release, all my new email notification forms has send only with HMTL attributes when i use ##formcreator.form_full_answers## attribute

i tried to reset HTML code in the notification's template but it's not better 

GLPI version 9.5.3
FullForm version 9.11

![image](https://user-images.githubusercontent.com/78158841/106154864-5a158500-6180-11eb-8122-b5b6a8437b7e.png)

**Comment by btry** [comment]
Hi

It appears that ##FULLFORM## is parsed and replaced with the default content : all question labels and answers tags are here. But they are not replaced themsele with the actual data submitted by the requester, right ?

**Comment by boivink** [comment]
Hi,
Exactly ! It seems the translation is good when the form become a ticket but not in email notification

**Comment by btry** [comment]
Please test the above patch and feedback. Note that attachments won't be added in the notification.

**Comment by boivink** [comment]
Hi,
i've just tested the patch and all work fine now !

thanks a lot for your help !!

**Comment by btry** [comment]
Hi

Thank you for your fedback. The fix will be available in the newt maintenance release.
