### ISSUE TITLE
[2.11.0] File is not attached if required

### ISSUE THREAD

**Issue by luisjosemachado** [pluginsGLPI/formcreator#2097]
**Describe the bug**
File is not attached if file field is setting to required.

**To Reproduce**
1. Create a form with file field and set it to required.
2. Run the form and fill it out.
3. The message is displayed: "A required file is missing". And the ticket is not created.

**Expected behavior**
The form is executed and creates a ticket.

**Screenshots**
![Screenshot_2021-01-28 GLPI - Forms - 15](https://user-images.githubusercontent.com/30940056/106154100-02662200-615e-11eb-9b92-ddb864d45409.png)

**Desktop:**
 - Linux Mint 20 x86_64
 - Firefox 84.0.2

**Additional context**
There is no problem if the file field is not set to requerid.

**Comment by btry** [comment]
Hi 

please test the above patch and fedback

**Comment by luisjosemachado** [comment]
Solved. Thank you.

**Comment by btry** [comment]
hank you, the fix will be available in the next maintenance release.
