### ISSUE TITLE
[ 2.11.0 ] - OLA is not Linking with Target Answer

### ISSUE THREAD

**Issue by Gambware** [pluginsGLPI/formcreator#2098]
As we can see, the form below has an OLA in a question
![image](https://user-images.githubusercontent.com/24397740/106176996-ba072e00-6176-11eb-8b15-50fa94c976af.png)

But, when set the target, we cant link with this answer
![image](https://user-images.githubusercontent.com/24397740/106176838-90e69d80-6176-11eb-9ffd-76dad04e514b.png)

**Comment by btry** [comment]
Hi 

Please test the fix #2107  and feedback. It should solve issues with all dropdowns of targets

**Comment by Gambware** [comment]
#2107 didn't solve the problem,

**Comment by btry** [comment]
Hi

I noticed that SLA / OLA support was somewhat broken. The qustion you want to use with OLA has maybe a missing data, preventing it to show in your target ticket. Please follow these instructions:

- edit  your question configured as OLA. Ensure you have a value set in **Type** (see the screenshot). It must be **Time to own** or **Time to resolve**. See the screenshot below.

![image](https://user-images.githubusercontent.com/14139801/106310956-acc86d00-6264-11eb-8192-f37eb759680a.png)

- save the question
- edit the target ticket. The question shall appear in either the 1st or the 2nd dropdown related to OLA. One is for time to own and the other is for time to resolve.

I'm waiting or your feedbaack. Don't hesitate to share screenshot.

**Comment by btry** [comment]
Hi @Gambware 

Did you tried the proceudre described above ? Please feedback.

**Comment by btry** [comment]
Hi @Gambware 

Do you have feedback ? Is your problem solved ?

**Comment by btry** [comment]
Hi

HAving no feedback, I assume I can close this issue.
