### ISSUE TITLE
2.11.0 - After the update, the author disappeared.

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#2099]
Hi,

After the update of version 2.10.4, in all existing forms, the destination ticket, the author disappeared:
![image](https://user-images.githubusercontent.com/43650152/106176842-9217ca80-6176-11eb-93f9-2630427303c0.png)

If a new ticket is created, the author is shown:
![image](https://user-images.githubusercontent.com/43650152/106177048-cb503a80-6176-11eb-9acf-e8bdd9678400.png)
 

When a ticket is opened, the author is shown normally, even though the field is empty in the configuration.

**Comment by jvergacas** [comment]
Here are the update LOGs
[migration_to_2.11.0.log](https://github.com/pluginsGLPI/formcreator/files/5889107/migration_to_2.11.0.log)
[warning_during_migration_to_2.11.0.log](https://github.com/pluginsGLPI/formcreator/files/5889108/warning_during_migration_to_2.11.0.log)

**Comment by btry** [comment]
Hi

Yes, it seems that there is a migration problem. I'll try to fix this quickly. Related to #2100

**Comment by btry** [comment]
Hi try this fix, follow the instructions to fix your upgrade.

https://github.com/pluginsGLPI/formcreator/pull/2102

**Comment by btry** [comment]
Hi

Did you had time to re-run the upgrade or use the 2 sql queries to manually restore the missing data ? (the 2nd solution is helpful to switch to maintenance mode). Everything is described in the PR comment.

**Comment by jvergacas** [comment]
Hi @btry 

I applied method 2 and the problem was fixed.

Now, I'm going to do a few more tests before I update my production environment.

Thank you.
