### ISSUE TITLE
Add groups to validators

### ISSUE THREAD

**Issue by arkan0iid** [pluginsGLPI/formcreator#210]
Hello,
I have an issue when I try to set up a group as validator on my forms:
Just one group is available (the first of my group list in "Administration/Groups").
For the test, one super-admin user is member of each groups.

Exemple, I have 3 groups in GLPI:
   - Administrators
   - Users
   - Validators
   
In the formcreator plugin, only the "Administrators" group is available as validator, if I delete it from the "groups" view, only the "Users" group is available in formcreator.

Thank a lot for your help.

Alexis.

**Comment by btry** [comment]
Hi

The plugin shows only groups contraining at least one user with ticket validation right. 

Deleting the Administrators group should not affect the availability of the users group in t he validators dropdown.

Can you ensure each group contains only one member with ticket validation right ?
user A => administrators
user B => users
user C => validators

then feedback the content of the dropdown, pease.

You may also try (first ?) the master branch of the plugin, many fixes have been pushed sinice you opened this ticket.

**Comment by btry** [comment]
I don't reproduce and I don't have feedback. 

Feel free to open a new ticket if it happens again.
