### ISSUE TITLE
[2.11.0] Warning: strlen() expects parameter 1 to be string, array given in /var/www/html/inc/dropdown.class.php on line 1890

### ISSUE THREAD

**Issue by aleadco** [pluginsGLPI/formcreator#2106]
**Describe the bug**
`Warning: strlen() expects parameter 1 to be string, array given in /var/www/html/inc/dropdown.class.php on line 1890`

**To Reproduce**
![image](https://user-images.githubusercontent.com/35962168/106203346-3c005280-6189-11eb-9cf3-8f4f72749ffa.png)

No drop-down menu is accessible. Nor does it ask to get a value based on the answer to a question.

I am aware of the note published in the release of the version ... I only leave the report so that this case is taken into account and see possible solutions.

Regards

**Comment by btry** [comment]
Duplicate #2098, I'm on it

**Comment by btry** [comment]
Hi

If you enable debug mode, you should see PHP warnings near all broken dropdown. Please show a screenshot, to let me check they all are impacted by the same problem.

**Comment by btry** [comment]
Hi

The above PR still needs some work, but I expect it should fix most (if not all) dropdowns). Can you test it ?

**Comment by aleadco** [comment]
> Hi
> 
> The above PR still needs some work, but I expect it should fix most (if not all) dropdowns). Can you test it ?

Without a doubt, as soon as it comes out I try it.

**Comment by btry** [comment]
I amended the patch to fix 2 more dropdowns. The 2 broken dropdowns from your screenshot should work now.

**Comment by aleadco** [comment]
> I amended the patch to fix 2 more dropdowns. The 2 broken dropdowns from your screenshot should work now.

If I already noticed, I will try applying the patch now.

**Comment by aleadco** [comment]
> Hi
> 
> The above PR still needs some work, but I expect it should fix most (if not all) dropdowns). Can you test it ?

@btry Sadly the patch did not solve my problem

**Comment by btry** [comment]
Hi

The fix worked for me, but I had to add more changes today, after your post https://github.com/pluginsGLPI/formcreator/issues/2106#issuecomment-769444895 19 hours ago.

Can you validate you have the same diff as github shows ?

**Comment by btry** [comment]
HI

Can you confirm that there is no more PHP errors displayed in debug mode before we continue investigation ?

**Comment by aleadco** [comment]
Sorry for the delay in answering.  Unfortunately I still do not have good results.
![Screenshot_20210201-074324_Firefox.jpg](https://user-images.githubusercontent.com/35962168/106460535-1d37df80-6459-11eb-9c38-aaeb74d30cb0.jpg)

**Comment by btry** [comment]
I would say that the patch is not properly applied, because I'm sure about the reliability of the fix.

You should fiind a backtrace in php-errors.log. This file is in glpi/files/_logs/. An entry should contain the same error message as the read rectangles. Please show the acktract matching this error.

Also, please veryfy that the patch is applied for the entity from a question dropdown. In inc/abstracttarget.class.php locate the line 

```protected function showDestinationEntitySetings($rand) {```

If you scroll near the end of the function you should find a call to **PluginFormcreatorQuestion::dropdownForForm()**

When the patch is applied you should see something like the following

![image](https://user-images.githubusercontent.com/14139801/106462996-1a5bdf80-6497-11eb-8ed6-df90fa386e36.png)

The arrow show an argument which is passed the right way. Without the fix, it was passed in an array.

**Comment by aleadco** [comment]
Well yes, my mistake in the implementation of the patch.  Yes it worked.

**Comment by btry** [comment]
Hi

OK, nice. I released 2.11.1 today, and the patch is included.

Next time you need to apply a patch, consider using the patch tool to avoid mistakes. Search "man patch" on internet to read its manual. A lot of resources also exist to learn only the basic usage.

Le 3 février 2021 12:36:09 GMT+01:00, Alejandro Colina <notifications@github.com> a écrit :
>Well yes, my mistake in the implementation of the patch.  Yes it
>worked.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pluginsGLPI/formcreator/issues/2106#issuecomment-772443542

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by aleadco** [comment]
@btry Thank you very much for the advice, I will seek information about it.
