### ISSUE TITLE
Rearrange questions, positions

### ISSUE THREAD

**Issue by benshoes** [pluginsGLPI/formcreator#2119]
GLPI 9.5.3
FORMCREATOR 2.11.1

**Describe the bug**
When i change the position on some questions, some of them doesn't want to keep the new position after saving.

**Screenshots**
![image](https://user-images.githubusercontent.com/53210764/107005730-6dcc7700-6790-11eb-8df7-56a016c8916d.png)

**Comment by btry** [comment]
Hi

The problem was solved yesterday. Please apply the following patch: https://github.com/pluginsGLPI/formcreator/pull/2117

**Comment by benshoes** [comment]
Excellent,
Thank you very much.
Have a good day
