### ISSUE TITLE
Mauvais alignement des cases de réponses sur une même ligne

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2120]
**Describe the bug**
Mauvais alignement des cases de réponses sur une même ligne lors de l'apercu formulaire. CF copie écran.
![align](https://user-images.githubusercontent.com/78594318/107030681-4639d680-67b1-11eb-8cbb-651459afb3e0.jpg)

**To Reproduce**
1. créer un formulaire
2. Aligner 3 questions sur une même ligne qui contiennent une descriptif de longueur différente
3. Regarder l'apercu

**Expected behavior**
Des cases alignées 

**Screenshots**
see screenshot

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox 85
 - Version formcreator 11.1

**Comment by btry** [comment]
Bonjour

Il est possible de faire ce rendu
![image](https://user-images.githubusercontent.com/14139801/108055056-bf59e900-704f-11eb-93f7-e110e2bb6eb7.png)

**Comment by mirda123** [comment]
![align2](https://user-images.githubusercontent.com/78594318/108409942-18c84080-7227-11eb-8a55-7ae326c0ade1.jpg)

Pas réussi à faire mieux que la copie écran en terme d'alignement en jouant avec des lignes vides...

**Comment by btry** [comment]
Bonjour

Je ne sais pas si il est préférable d'aligner les titres de questions ou les laisser "collés" à la description. C'est pour cela que je n'y ai pas touché. J'ai focalisé  sur l'alignement des zones de saisie pour le moment.

**Comment by btry** [comment]
Je fusionne pour la prochaine version le patch que j'ai fait. Je suis pour le moment indécis sur la meilleure manière de gérer les titres des questions. Les placer en haut de la zone est bien pour leur alignement de proche en proche et horizontalement, mais avoir des titres à l'écart de leur zone de saisie ou même plus proche d'une autre question que de la zone qui les concerne ne me parait pas très lisible.

**Comment by mirda123** [comment]
Merci pour la correction rapide. 
Pour le reste, je n'arrive pas non plus à visualiser ce qui répondrait le mieux à la problématique évoquée...
