### ISSUE TITLE
formcreator 2.11.0 / 2.11.1

### ISSUE THREAD

**Issue by hcimadomo** [pluginsGLPI/formcreator#2121]
in a dropwdown list, the list of object is not the list of object of current entity. So i have many forms where user see all users of all entitities !! It's very urgent to fix this bug.
Thank for your help.

**To Reproduce**
create a form, create a question, chose glpi objet and users. Go to a sub entity, use previsualisation , the list of user is the list of all user and non only the users of sub entity.

**Comment by btry** [comment]
Hi

Did you reviewed the release not of the version 2.11 ?

![image](https://user-images.githubusercontent.com/14139801/107035435-7638a800-67b8-11eb-9dc3-d2d6f841ea61.png)

As a urgency  measure, you can revert the following commit : https://github.com/pluginsGLPI/formcreator/commit/dc7dda940bb8235e6fa9728dd03616127aed1082

Next, consider moving your form in an other entity. I guess it is in the root for now.

**Comment by hcimadomo** [comment]
Hello,
Thank for your return. With you help, i can resolve the issue (Just i discover that plugin is now in marketplace folder and the folder formcreator in plugin folder is not more used...)
As each time i upgrade an plugin, I review the releases notes  and it's not precised that the dropdown list is now the list of the entity and sub entities of form..
I not agree with this change. the concept of entities is to see only object of an entity (and herital object), as list of users. With this modification, when the form is on master entity and we use in sub entity, we see all objet of sub entities of master entity !!!. The solution to duplicate a same form into all sub-entity is not compliant with a production environnement with the form is mutualised with sub entities.
Best regards

**Comment by btry** [comment]
Hi

> I not agree with this change. the concept of entities is to see only object of an entity (and herital object), as list of users. With this modification, when the form is on master entity and we use in sub entity, we see all objet of sub entities of master entity !!!. 

I'm searching for an other reference point of view to solve this problem. Maybe I'll need to create a new setting. I expect to find a better solution for version 2.12. When its beta will be available, please consider to test feedback the changes related to this issue.
