### ISSUE TITLE
Form fields (actors) not passed to form answer

### ISSUE THREAD

**Issue by RathW** [pluginsGLPI/formcreator#2122]
Dear Team,
first of all, thanks to the team, for the great and helpful plugin!

We are currently using GLPI Version 9.5.1 and Form Creator version 2.11.1

At the moment we are facing a little problem when filling up new forms.

In the form, we select a responsible person from Active Directory using the actor type question. 
This is working fine.

But when saving the form answer, the chosen Person is not handed over. 
Field in the form answer is empty.

We are grateful for any information and hints!

Thanks Wolfgang 

![formcreatorerror_1](https://user-images.githubusercontent.com/78726109/107201457-4af0cb80-69f9-11eb-9189-5f78ad5f03ce.png)
![formcreatorerror_2](https://user-images.githubusercontent.com/78726109/107201470-4fb57f80-69f9-11eb-9706-5be7c33d7a6e.png)
![formcreatorerror_3](https://user-images.githubusercontent.com/78726109/107201475-517f4300-69f9-11eb-903e-ca709d4dd00b.png)

**Comment by btry** [comment]
Hi

Please try the above fix and feedback.

**Comment by RathW** [comment]
Hi, thanks for the fast answer!
We rolled back to support/2.11.0 but the issue is still the same.

yours Wolfgang

**Comment by btry** [comment]
Hi

Do not roll back. Use the version 2.11.1 as it has some fixes. Next, apply the patch in the PR #2123. It describes a patch to apply to Formcreator. 

Here is the documentation of the patch tool : https://linux.die.net/man/1/patch

In short, you shall use patch the following way (assuming you're located in Formcreator's directory): **patch -p1 < /path/to/patch-file.patch**

patch-file.patch is downloadable here : https://patch-diff.githubusercontent.com/raw/pluginsGLPI/formcreator/pull/2123.patch

**Comment by RathW** [comment]
sorry for the misunderstanding. 
applied the patch now and it works like a charm! 

ça fonctionne parfaitement!
Merci bien pour votre aide!
Bien à vous!
Wolfgang

**Comment by btry** [comment]
Hi

Thank you for your feedback, the fix will be included in the next release.
