### ISSUE TITLE
perte des icones des formulaires 

### ISSUE THREAD

**Issue by OClaveau** [pluginsGLPI/formcreator#2124]
**Describe the bug**
Bonjour,
lors de l'edition d'un formulaire, l'icone n'est pas affichée et ecrasée par 0 lors de l'enregistrement

**To Reproduce**
liste des formulaires : 1 icone est associee
![image](https://user-images.githubusercontent.com/13663627/107487653-b025f780-6b86-11eb-9e0d-1b2cd3cc77af.png)

edition du formulaire : l'icone n'est pas affichée
![image](https://user-images.githubusercontent.com/13663627/107488286-76a1bc00-6b87-11eb-9077-3b1ab562653b.png)

resultat après sauvegarde (sans modification) : le nom de l'icone est remplace par '0'
![image](https://user-images.githubusercontent.com/13663627/107488464-af419580-6b87-11eb-8217-f3a094bc7be2.png)

**Expected behavior**
conservation de l'icone

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  windows 10
 - Browser EDGE
 - Version GLPI 9.5.3
                Formcreator 2.11.1

pour info : cette anomalie n'existe pas en GLPI 9.4.6 et formcreator 2.9.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment]
Bonjour, en effet il y a une erreur de logique quand on affiche un formulaire existant en base de données. Le fix ci dessus devrait résoudre votre problème. Il vous faudra par contre reconfigurer les icônes des formulaires impactés.

Merci de tester le fix cu dessus et me faire un retour.

**Comment by OClaveau** [comment]
fix appliqué : comportement OK

Merci

**Comment by OClaveau** [comment]
Bonjour,

Merci beaucoup, le pb est résolu

Cordialement

[Logo Essonne]<https://www.essonne.fr/>

Odile CLAVEAU
Ingenieur systeme d'info metier
DGAAR / DSI / DSI/SCE DOMAINE SI RESSOURCES

Conseil départemental de l'Essonne
01 60 91 94 18
essonne.fr <https://www.essonne.fr/>   [http://webmaster.essonne.fr/signature/signature-insta.png] <https://www.instagram.com/cdessonne/>   [http://webmaster.essonne.fr/signature/signature-FB.png] <https://www.facebook.com/CDEssonne/>   [http://webmaster.essonne.fr/signature/signature-yt.png] <https://www.youtube.com/c/essonnefr/featured/>   [http://webmaster.essonne.fr/signature/signature-Tw.png] <https://twitter.com/cdessonne/>   [http://webmaster.essonne.fr/signature/signature-Li.png] <https://www.linkedin.com/company/departement-de-l-essonne/>


De : btry <notifications@github.com>
Envoyé : mercredi 10 février 2021 10:24
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : Odile CLAVEAU <OClaveau@cd-essonne.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/formcreator] perte des icones des formulaires (#2124)


Bonjour, en effet il y a une erreur de logique quand on affiche un formulaire existant en base de données. Le fix ci dessus devrait résoudre votre problème. Il vous faudra par contre reconfigurer les icônes des formulaires impactés.

Merci de tester le fix cu dessus et me faire un retour.
