### ISSUE TITLE
Date d'ouverture ne remonte pas dans les tickets

### ISSUE THREAD

**Issue by amongreville** [pluginsGLPI/formcreator#2127]
**Describe the bug**

**To Reproduce**
1. Créer un formulaire
2. Ajouter une cible vers ticket

**Expected behavior**
Aucune Date ne remonte lors de la création du ticket

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser chrome
 - Version 88.0.4324.150
![Capture](https://user-images.githubusercontent.com/78857908/107515105-e07f8d00-6baa-11eb-9ec3-346747423be6.PNG)

**Comment by btry** [comment]
Bonjour

Quelle version de Formcreator ? 

Pouvez vous aussi montrer un exemple de date saisie ?

**Comment by amongreville** [comment]
Bonjour,
La version de GLPI est 9.5.3 et la version de Formcreator est la 2.11.1.

Voici les captures

![Capture3](https://user-images.githubusercontent.com/78857908/108056707-e7e2e280-7051-11eb-9ea0-c1b50571829e.PNG)
![Capture](https://user-images.githubusercontent.com/78857908/108056708-e7e2e280-7051-11eb-95b4-d6588d97e34b.PNG)
![Capture2](https://user-images.githubusercontent.com/78857908/108056709-e87b7900-7051-11eb-83f0-f1c8f3a43a79.PNG)

Merci d'avance,

**Comment by amongreville** [comment]
Bonjour,

Même en insérant un champ "date" ou "date&heure", j'obtiens la même anomalie.

**Comment by btry** [comment]
Bonjour

Alors.. que dire ?

J'ai reproduit, commencé à chercher, puis le bug a disparu spontanément. Je n'arrive plus à reproduire. 

J'ai fait un correctif pour un plantage si on ne remplit pas le champ date : 940bfee2ecf7a22a4fc5033d81c90536e0baeac8. L'annuler ne me permet pas de reproduire de nouveau.

**Comment by btry** [comment]
Le message d'erreur semble provenir de GLPI, quand on ajoute ou modifie quelque chose. Impossible de savoir quoi sans backtrace.

Comme je ne reproduis plus, j'ai besoin que l'un d'entre vous applique ce patch (de préférence sur une instance de TESTS) pour récupérer un backtrace. A priori c'est à l'endroit décrit dans le diff que le message est émis.

```diff
diff --git a/inc/commondbtm.class.php b/inc/commondbtm.class.php
index f4526ee058..dec57b4c81 100644
--- a/inc/commondbtm.class.php
+++ b/inc/commondbtm.class.php
@@ -4069,6 +4069,7 @@ class CommonDBTM extends CommonGLPI {
                      preg_match($pattern, $value, $regs);
                      if (empty($regs)) {
                         $unset = true;
+                        Toolbox::logDebug("formcreator: date error message debug", Toolbox::backtrace(''));
                      }
                      break;
 
```

Le backtrace sera enregistré dans php-errors.log.

Je suis en attente de retour pour avancer sur ce bug.

**Comment by amongreville** [comment]
D'accord, j'active une instance de tests

La version PHP n'a pas d'incidence ?

**Comment by btry** [comment]
Du moment que vous respectez les prérequis de GLPI (, pas de souci. PHP 7.2 minimum.

**Comment by btry** [comment]
Bonjour

Avez vous pu générer le backtrace à l'aide du patch ?

**Comment by amongreville** [comment]
Bonjour,

Malgré l'ajout de la ligne dans commondbtm.class.php de 
                  case 'datetime' :
                     // Date is already "reformat" according to getDateFormat()
                     $pattern  = "/^([0-9]{4})-([0-9]{1,2})-([0-9]{1,2})";
                     $pattern .= "([_][01][0-9]|2[0-3]:[0-5][0-9]:[0-5]?[0-9])?/";
                     preg_match($pattern, $value, $regs);
                     if (empty($regs)) {
                        $unset = true;
			_**Toolbox::logDebug("formcreator: date error message debug", Toolbox::backtrace(''));**_
                     }
                     break;

J'ai aucune ligne concernant le libellé qui remonte dans php-errors.log

**Comment by amongreville** [comment]
j'ai par-contre cette erreur sans sql-errors.log :

[2021-02-24 11:34:10] glpisqllog.ERROR: DBmysql::query() in D:\WAMP\PROD\HTTPD\WWW\glpi\inc\dbmysql.class.php line 306
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_issues` (`original_id`, `sub_itemtype`, `name`, `status`, `date_creation`, `date_mod`, `entities_id`, `is_recursive`, `requester_id`, `users_id_validator`, `groups_id_validator`, `comment`, `display_id`) VALUES ('2021022427', 'Ticket', 'demande en ligne HS', '2', NULL, '2021-02-24 11:34:09', '6', '0', '34', '', '', '&lt;div&gt;&lt;h1&gt;Donn&eacute;es du formulaire&lt;/h1&gt;&lt;h2&gt;Informations sur la demande : &lt;/h2&gt;&lt;div&gt;&lt;b&gt;1) Type de demande :  : &lt;/b&gt;DSI > 05 - Cellule Hotline&lt;/div&gt;&lt;div&gt;&lt;b&gt;2) Urgence :  : &lt;/b&gt;Moyenne&lt;/div&gt;&lt;div&gt;&lt;b&gt;3) Lieu : : &lt;/b&gt;00 - SITES COMMUNS > 01 - VICHY COMMUNAUTE > 01 - HOTEL D\'AGGLOMERATION > ETAGE 0 RDC > 000 > GUICHET 003&lt;/div&gt;&lt;div&gt;&lt;b&gt;4) Demande pour un autre agent : : &lt;/b&gt;NON&lt;/div&gt;&lt;h2&gt;Votre demande : &lt;/h2&gt;&lt;div&gt;&lt;b&gt;5) Libellé de la demande :  : &lt;/b&gt;demande en ligne HS&lt;/div&gt;&lt;div&gt;&lt;b&gt;6) Description de la demande :  : &lt;/b&gt;&lt;p&gt;à faire&lt;/p&gt;&lt;/div&gt;&lt;h2&gt;Pi&egrave;ces jointes : &lt;/h2&gt;&lt;div&gt;&lt;b&gt;7) Documents :  : &lt;/b&gt;Pas de document rattaché&lt;/div&gt;&lt;/div&gt;', 't_2021022427')
  Error: Column 'date_creation' cannot be null
  Backtrace :
  inc\dbmysql.class.php:1127                         
  inc\commondbtm.class.php:602                       DBmysql->insert()
  inc\commondbtm.class.php:1142                      CommonDBTM->addToDB()
  plugins\formcreator\inc\formanswer.class.php:1289  CommonDBTM->add()
  plugins\formcreator\inc\formanswer.class.php:1013  PluginFormcreatorFormAnswer->createIssue()
  inc\commondbtm.class.php:1143                      PluginFormcreatorFormAnswer->post_addItem()
  plugins\formcreator\front\form.form.php:142        CommonDBTM->add()
  {"user":"34@CAWEB","mem_usage":"0.052\", 33.58Mio)"}

**Comment by btry** [comment]
Bonjour

Je vais faire un patch pour le souci de valeur null non permise.

Si on ne génère pas de backtrace. Est ce que l'erreur se produit encore ? Ou a t elle disparu comme je l'ai observé ?

**Comment by amongreville** [comment]
L'anomalie persiste malgré la suppression du backtrace
j'ai pris le contenu du support 2.11.0, est-ce la bonne méthode ?
![Capture-support](https://user-images.githubusercontent.com/78857908/108991815-d7a5b580-7698-11eb-9e9b-f431fc248cb2.PNG)

Que pensez-vous de pouvoir associer la date à une question via le paramétrage de la cible ? Comme pour les champs catégories, lieux, ...
![Capture-date](https://user-images.githubusercontent.com/78857908/108991819-d83e4c00-7698-11eb-9067-ae2877c469ab.PNG)

Sauf si une autre option le permet. Que pensez-vous également, d'avoir l'option "Maintenant" dans le pré-rempilage d'une zone date ?
![Capture-saisie](https://user-images.githubusercontent.com/78857908/108992719-e9d42380-7699-11eb-88d4-1448a3d705b8.PNG)


Encore merci pour votre aide,

**Comment by btry** [comment]
Bonjour

Ne mélangeons pas tout dans le même ticket. Il faut rester ici sur le souci lié au message d'erreur. Pour les demandes de fonctionnalité, contactez nous : contact@teclib.com .

Pour appliquer le patch vous devez récupérer le "diff" et l'appliquer avec la commande patch. Si vous avez juste pris la branche support/2.11.0, le patch n'est pas inclus, surtout qu'il s'agit d'une modification visant à faire du debug.

**Comment by amongreville** [comment]
Merci pour l'information,
Je dois bien lancer cette commande :
diff -u D:\WAMP\PROD\HTTPD\WWW\glpi\plugins\formcreator C:\TEMP\new\formcreator-develop > prog.patch
puis :
patch -p0 < prog.patch

**Comment by amongreville** [comment]
Je viens d'essayer la version 2.11.2 :
l'anomalie persiste.

![Capture-2-11-2](https://user-images.githubusercontent.com/78857908/109024391-ff5b4480-76bd-11eb-8847-65b560ceaefc.PNG)

**Comment by btry** [comment]
Non. Copiez / collez le diff que j'ai partagé dans un fichier à la racine de Formcreator. Disons debug.patch

Ensuite toujours dans le même dossier faites ```patch -p1 < debug.patch```

**Comment by amongreville** [comment]
Bonjour,

Je n'ai pas retrouvé de fichier *.patch dans les branches et 940bfee2ec

**Comment by btry** [comment]
Il faut juste copier dans un fichier le patch de ce commentaire : https://github.com/pluginsGLPI/formcreator/issues/2127#issuecomment-779851341

**Comment by amongreville** [comment]
La correction est appliquée mais l'erreur persiste.
public function getValueForTargetText($richText): ?string {

J'ai réactivé le backtrace, j'obtiens le log en PJ après 2 test.
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/6042059/php-errors.log)

**Comment by btry** [comment]
Le correctif est pour un autre problème que j'ai trouvé en cherchant votre souci. J'en suis encore à chercher les indices pour comprendre comment on en arrive au message d'erreur. 

Le fichier php-errors.log ne contient pas de backtrace, seulement des warnings lancés par GLPI, à priori pour un autre problème.

**Comment by btry** [comment]
Pour le bug cité ici https://github.com/pluginsGLPI/formcreator/issues/2127#issuecomment-784979798 ça ne doit pas arriver. Il ya 2 dates toutes les deux issues d'une même donnée. Or une est NULL et l'autre contient bine une date. Si je remonte à la version 2.11.0, le code ne permet pas cette erreur. Vous avez peut être des modifications dans le plugin.

**Comment by amongreville** [comment]
Aucune modification en dehors de la mise à jour 2.11.2 et du backtrace.

Je viens de repartir de la version 10.0.0, et je n'ai plus l'anomalie. Je vais tester chaque mise à jour.

La zone temps de résolution ne se remplie pas de la même manière entre la version 10 et 11...
![Capture-temps](https://user-images.githubusercontent.com/78857908/109149101-697bf400-7767-11eb-9f79-33bed43febb5.PNG)

j'avais un problème équivalent avant quand je précisais un gabarit de ticket
![Capture-gabarit](https://user-images.githubusercontent.com/78857908/109149366-c081c900-7767-11eb-9479-58cdc392f8d5.PNG)

**Comment by amongreville** [comment]
Aucune anomalie jusqu'à la version 2.10.4.
L'anomalie apparait dès la version 2.11.0
Ce n'est pas lié au nouvelle zone SLA et OLA qui apparaisse dès la version 2.11.0 ? Nous n'avons pas activé de SLA sur notre site.
2.10.4 :
![Capture-2-10-4](https://user-images.githubusercontent.com/78857908/109153243-ef4e6e00-776c-11eb-9692-c5482cff52dc.PNG)

2.11.0
![Capture-2-11-0](https://user-images.githubusercontent.com/78857908/109153255-f5dce580-776c-11eb-9705-0a8a2b02c6ea.PNG)

**Comment by btry** [comment]
Vu qu'on manipule des dates avec les SLA et OLA, c'est possible. Il faudrait voir si vous utilisez ces champs dans vos tickets cobles ? Pour ma part ils sont vides dans le formulaire que j'ai créé pour les tests.

**Comment by amongreville** [comment]
Initialement : J'ai sélectionner "depuis le gabarit ou aucun"

j'ai essayé avec une SLA spécifique, l'anomalie persiste.

De même en appelant un gabarit.

**Comment by amongreville** [comment]
Bonjour,
Je retrouve la même anomalie en 2.10.4 si je sélectionne un Gabarit de tickets.

**Comment by amongreville** [comment]
Je n'ai plus l'anomalie en version 2.11.2, si je défini un gabarit de ticket sans pré-remplissage de la date d'ouverture.

**Comment by btry** [comment]
Bonjour

Toutes ces informations ne m'aident pas à trouver comment reproduire. Dans votre post initial, vous dites que créer un formulaire avec un ticket cible suffit à reproduire. Donc vous créez un formulaire sans section ni question vous arrivez à reproduire le bug ?

**Comment by amongreville** [comment]
Bonjour,

Pour reproduire l’anomalie, il faut définir en champ prédéfini, la date d’ouverture avec la valeur « Maintenant ».
[cid:image003.jpg@01D70E8A.C42F0310]


Aurélien Mongréville
Direction des Systèmes d’Information
Tel Fixe : 04 70 30 55 29
Tel Télétravail : 07 63 60 25 40
a.mongreville@vichy-communaute.fr<mailto:a.mongreville@vichy-communaute.fr>

[cid:image001.jpg@01D587F3.B4F8E1F0]

De : btry [mailto:notifications@github.com]
Envoyé : lundi 1 mars 2021 10:43
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : MONGREVILLE Aurelien <a.mongreville@vichy-communaute.fr>; Author <author@noreply.github.com>
Objet : [NEWS] Re: [pluginsGLPI/formcreator] Date d'ouverture ne remonte pas dans les tickets (#2127)


Bonjour

Toutes ces informations ne m'aident pas à trouver comment reproduire. Dans votre post initial, vous dites que créer un formulaire avec un ticket cible suffit à reproduire. Donc vous créez un formulaire sans section ni question vous arrivez à reproduire le bug ?

**Comment by amongreville** [comment]
Bonjour,

Pour reproduire l’anomalie, il faut définir en champ prédéfini, la date d’ouverture avec la valeur « Maintenant ».

![capture-form PNG](https://user-images.githubusercontent.com/78857908/109482610-8160ba00-7a7e-11eb-9cab-5b667e06968a.jpg)

**Comment by amongreville** [comment]
Ma description, n'est pas complète : 
Pour reproduire l’anomalie, il faut définir en champ prédéfini, la date d’ouverture avec la valeur « Maintenant » dans le gabarit appelé dans la cible.

**Comment by btry** [comment]
Ah, donc en fait le bug est lié à la  gestion d'un gabarit de ticket ! 

Je tente de reproduire.

Une astuce pour les prochains bugs. Quand vous en rencontrez un essayez d'isoler le bug en créant un formulaire le plus simple possible. Moins il contient de choses plus on peux le cerner facilement.

**Comment by amongreville** [comment]
Jusqu’à la version 2.11.*, pour ne pas rencontrer l’anomalie, je ne rattachais aucun gabarit.

J’ai donc créé un gabarit spécifique pour les formulaires sans date d’ouverture prédéfinie.

De : btry [mailto:notifications@github.com]
Envoyé : lundi 1 mars 2021 14:04
À : pluginsGLPI/formcreator <formcreator@noreply.github.com>
Cc : MONGREVILLE Aurelien <a.mongreville@vichy-communaute.fr>; Author <author@noreply.github.com>
Objet : [NEWS] Re: [pluginsGLPI/formcreator] Date d'ouverture ne remonte pas dans les tickets (#2127)


Ah, donc en fait le bug est lié à la gestion d'un gabarit de ticket !

Je tente de reproduire.

Une astuce pour les prochains bugs. Quand vous en rencontrez un essayez d'isoler le bug en créant un formulaire le plus simple possible. Moins il contient de choses plus on peux le cerner facilement.

**Comment by btry** [comment]
Essayez ce patch, ça devrait mieux fonctionner.

**Comment by amongreville** [comment]
Merci beaucoup !
Le test est concluant.

Le ticket peut-être clôturé. 👍

**Comment by btry** [comment]
Merci, le patch sera dans la prochaine release.
