### ISSUE TITLE
Incompatibilité catalogue de service / internet explorer 11

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2128]
![Iexplorer 11](https://user-images.githubusercontent.com/78594318/107519067-12472280-6bb0-11eb-938a-9f5fa563df56.jpg)

**Describe the bug**
Mode catalogue de service et internet explorer 11 non compatible 

**To Reproduce**
glpi mode service catalog
ouvrir l'application avec IE 11

**Expected behavior**
Affichage des formulaires

**Screenshots**
see screenshot

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : Internet explorer 11
 - Version form 11.1

**Comment by btry** [comment]
Bonjour

IE11 est vraiment vieux, et arrive en fin de vie en août prochain. De plus, GLPI 9.5 ne supporte plus IE11, cela se propage naturellement à Formcreator 2.11. 

Il est préférable que vous mettiez à jour votre navigateur.
