### ISSUE TITLE
Problème de redirection vers le ticket dans le portail simplifié

### ISSUE THREAD

**Issue by corzakiewicz** [pluginsGLPI/formcreator#2129]
**Describe the bug**
Lorsqu’un utilisateur ouvre un ticket au travers le portail simplifié (Self-Service) FormCreator, via un formulaire, il reçoit une notification mail contenant le lien vers le ticket qu’il a ouvert.
Lorsqu’il clique sur ce lien, il est redirigé vers son espace du portail simplifié mais le ticket ne s’ouvre pas, à la place, une page sans contenu s’affiche.
L’URL en question est formée d’après la balise ###ticket.id## proposée par GLPI.

**To Reproduce**
1. Aller sur le portail simplifié en tant qu’utilisateur final
2. Cliquer sur le formulaire ‘Signaler un dysfonctionnement ‘
3. Remplir les champs du formulaire puis cliquer sur Envoyer
4. Dans le mail reçu par l’utilisateur (notification d’ouverture), cliquer sur le lien pour accéder au ticket

**Expected behavior**
Le comportement attendu est que l’utilisateur accède directement au ticket lorsqu’il clique sur le lien ticket dans le mail de notification.

**Screenshots**

1/ Depuis le portail simplifié, l’utilisateur clique sur la tuile suivante :
![Screenshot01](https://user-images.githubusercontent.com/75740722/107745097-0bd1bb80-6d14-11eb-8936-7d54d0adfbe3.jpg)

2/ le formulaire correspondant s’ouvre. L’utilisateur remplit les champs et clique sur Envoyer :
![Screenshot02](https://user-images.githubusercontent.com/75740722/107745157-2146e580-6d14-11eb-8275-ae7fc4998111.jpg)

3/ L’utilisateur reçoit la notification suivante par mail : 
![Screenshot03](https://user-images.githubusercontent.com/75740722/107745205-3885d300-6d14-11eb-8d7e-97130c3887e0.jpg)

4/ L'utilisateur clique sur le lien présent dans le mail pour ouvrir le ticket (tout en bas du mail) et est redirigé vers cette page (qui affiche donc une page vide au lieu d'afficher le ticket) :
![Screenshot04](https://user-images.githubusercontent.com/75740722/107745290-61a66380-6d14-11eb-95c3-252709344f1b.jpg)

Lien du champ Ticket #0000115 : https://monserveurglpi/index.php?redirect=ticket_115&noAUTO=1

Lien direct vers le ticket sur le portail simplifié (qui fonctionne) :
https://monserveurglpi/plugins/formcreator/front/issue.form.php?id=135

id réel du ticket visible depuis l’interface complète de GLPI (ticket_id) : 115

**Desktop (please complete the following information):**
 - OS : Windows 10 Pro64 bits (20H2, 19042.804)
 - Browser : Chrome 88.0.4324.150 (Build officiel) (64 bits)

**Additional context**
GLPI v9.5.3
FormCreator v2.11.1

Par le passé, le lien inscrit dans la notification mail vers le ticket utilisateur fonctionnait sans problème. Je ne sais pas dire depuis quand ça ne fonctionne plus.

**Comment by khblkhivygiyfg** [comment]
Bonjour à tous,
Je confirmer tes dires corzakiewicz, j'ai exactement le même soucis, le tous avec les mêmes versions que toi (glpi 9.5.3 et FormCreator 2.11.1).
Aurez-tu trouvé une solution s'il-te-plait ou bien quelqu'un d'autre en aurait une?

cordialement.

**Comment by btry** [comment]
Bonjour

Je ne suis pas encore sur ce ticket, ça va venir.

Juste une note sur les ID : l'ID qui est visible sur une URL finissant en issue.form.php peut être différent de l'ID d'une URL qui finit en ticket.form.php

un objet issue n'est **pas** un objet ticket. Le problème que vous rencontrez doit être résolu par une gestion de redirection côté plugin. 

Il me semble que j'ai fait un correctif après la version 2.11.1, de mémoire ce commit : b99b19b4e8ec56602652c6c67c53af451f365e8f

Merci de faire un test avec ce commit, sur une instance de test, ou bien si vous êtes sûr de pouvoir annuler le changement qu'il opère.

**Comment by corzakiewicz** [comment]
> Bonjour à tous,
> Je confirme tes dires corzakiewicz, j'ai exactement le même soucis, le tout avec les mêmes versions que toi (glpi 9.5.3 et FormCreator 2.11.1).
> Aurai-tu trouvé une solution s'il-te-plait ou bien quelqu'un d'autre en aurait une?
> 
> cordialement.

Bonjour,
Non, je n'ai pas encore trouvé de solution.

**Comment by corzakiewicz** [comment]
> Bonjour
> 
> Je ne suis pas encore sur ce ticket, ça va venir.
> 
> Juste une note sur les ID : l'ID qui est visible sur une URL finissant en issue.form.php peut être différent de l'ID d'une URL qui finit en ticket.form.php
> 
> un objet issue n'est **pas** un objet ticket. Le problème que vous rencontrez doit être résolu par une gestion de redirection côté plugin.
> 
> Il me semble que j'ai fait un correctif après la version 2.11.1, de mémoire ce commit : [b99b19b](https://github.com/pluginsGLPI/formcreator/commit/b99b19b4e8ec56602652c6c67c53af451f365e8f)
> 
> Merci de faire un test avec ce commit, sur une instance de test, ou bien si vous êtes sûr de pouvoir annuler le changement qu'il opère.

Bonjour,
Merci pour cette mise à jour.
Malheureusement, je n'ai pas d'environnement de test pour vérifier si ce commit résout bien le problème que je rencontre.

**Comment by Tijah82** [comment]
Bonjour,

Je confirme le même bug de mon coté sur les mêmes version de GLPI et FormCreator.

En cliquant sur le lien si le ticket est "nouveau/en cours/en attente" j'ai la même page que corzakiewicz

En cliquant sur le lien et si le ticket est en "résolu/clos" j'ai carrément la page suivante 
![image](https://user-images.githubusercontent.com/48673805/108364563-8019cc80-71f6-11eb-9121-4e636d82344e.png)

Par contre cela ne veut pas dire qu'ils ne sont pas accessible si on reclic sur "mes demande d'assistances" on le voit. On a juste l'impression que d'utiliser le lien du mail n'est pas autorisé.

**Comment by Tijah82** [comment]
J'ai peut etre une piste 

Le lien dans le mail se presente ainsi -> https://monglpi/glpi/front/ticket.form.php?id=16843

Par contre si on va sur le ticket directement via l'interface il se presente ainsi -> https://monglpi/glpi/marketplace/formcreator/front/issue.form.php?id=16919

Je pense donc que le lien du mail est un lien valable si on utilise pas l'interface simplifié.

**Comment by corzakiewicz** [comment]
> Bonjour,
> 
> Je confirme le même bug de mon coté sur les mêmes version de GLPI et FormCreator.
> 
> En cliquant sur le lien si le ticket est "nouveau/en cours/en attente" j'ai la même page que corzakiewicz
> 
> En cliquant sur le lien et si le ticket est en "résolu/clos" j'ai carrément la page suivante
> ![image](https://user-images.githubusercontent.com/48673805/108364563-8019cc80-71f6-11eb-9121-4e636d82344e.png)
> 
> Par contre cela ne veut pas dire qu'ils ne sont pas accessible si on reclic sur "mes demande d'assistances" on le voit. On a juste l'impression que d'utiliser le lien du mail n'est pas autorisé.

Bonjour,
Dans mon cas néanmoins, je n'ai pas de message d'erreur "Vos n'avez pas les droits..." et j'arrive à voir correctement les tickets en cliquant sur le menu "Mes demandes d'assistance".

**Comment by btry** [comment]
Le message d'erreur sur les droits doit être lié à une confusion d'ID en lien avec ce que j'ai dit tout à l'heure. Vous êtes à priori impactés par le même souci malgré cette différence.

**Comment by corzakiewicz** [comment]
> Bonjour
> 
> Je ne suis pas encore sur ce ticket, ça va venir.
> 
> Juste une note sur les ID : l'ID qui est visible sur une URL finissant en issue.form.php peut être différent de l'ID d'une URL qui finit en ticket.form.php
> 
> un objet issue n'est **pas** un objet ticket. Le problème que vous rencontrez doit être résolu par une gestion de redirection côté plugin.
> 
> Il me semble que j'ai fait un correctif après la version 2.11.1, de mémoire ce commit : [b99b19b](https://github.com/pluginsGLPI/formcreator/commit/b99b19b4e8ec56602652c6c67c53af451f365e8f)
> 
> Merci de faire un test avec ce commit, sur une instance de test, ou bien si vous êtes sûr de pouvoir annuler le changement qu'il opère.

J'ai finalement changé le code tel que proposé dans le commit. Résultat : ça n'a pas changé le comportement, le défaut continue de se produire.

**Comment by Tijah82** [comment]
> > Bonjour,
> > Je confirme le même bug de mon coté sur les mêmes version de GLPI et FormCreator.
> > En cliquant sur le lien si le ticket est "nouveau/en cours/en attente" j'ai la même page que corzakiewicz
> > En cliquant sur le lien et si le ticket est en "résolu/clos" j'ai carrément la page suivante
> > ![image](https://user-images.githubusercontent.com/48673805/108364563-8019cc80-71f6-11eb-9121-4e636d82344e.png)
> > Par contre cela ne veut pas dire qu'ils ne sont pas accessible si on reclic sur "mes demande d'assistances" on le voit. On a juste l'impression que d'utiliser le lien du mail n'est pas autorisé.
> 
> Bonjour,
> Dans mon cas néanmoins, je n'ai pas de message d'erreur "Vos n'avez pas les droits..." et j'arrive à voir correctement les tickets en cliquant sur le menu "Mes demandes d'assistance".

Comme je l'ai dit, le message "vous n'avez pas les droits" n'apparait que si le ticket est en statut résolu ou clos. Dans tous les autres cas je n'ai pas de message mais une page vide comme vous. Et je vois aussi correctement les tickets dans "mes demandes d'assistance". 

Cela est problématique car du coup on est inondé de mail nous disant qu'ils n'ont pas accès au ticket. 

Dans un mail datant de fin novembre le lien se présentait de cette façon et ca fonctionnait tres bien
https://monglpi/glpi/index.php?redirect=ticket_14256_Ticket$1&noAUTO=1

Désormais il se présente comme ceci 
https://monglpi/glpi/index.php?redirect=ticket_16875_Ticket$1

J'ai bien entendu essayé de rajouter "&noAUTO=1" a la fin du lien mais ca ne marche pas mieux.

Ce qui est bizarre c'est que tout le monde devrait avoir ce soucis et pas seulement 2 ou 3 personnes.

**Comment by khblkhivygiyfg** [comment]
Bonjour.

Je reviens vers vous pour vous confirmer que le commit (b99b19b) à bien résolu notre soucis d’URL aux chemins quelque peu étranges.

**Comment by btry** [comment]
Bonjour

@corzakiewicz @khblkhivygiyfg : Si vous avez une page blanche, il y a peut être une erreur fatale. Vous devriez pouvoir le confirmer en ouvrant les outils de développeur de votre navigateur avant de reproduire. Si vous trouvez dans l'onglet Network (réseau) une erreur HTTP 500, alors vous devriez trouver le détail dans les logs de votre serveur HTTP (apache, nginx, ...)

@Tijah82 : Pour votre cas, c'est le ticket 16798. Cherchez : 
- dans la table glpi_items_tickets les lignes avec pour valeur tickets_id=16798 et itemtype=PluginFormcreatorFormAnswer. 
- dans la table glpi_plugin_formcreator_issues les lignes ayant sub_itemtype=Ticket et original_id=16798

Pouvez-vous montrer les résultats ?

@khblkhivygiyfg merci, cela fait une confirmation supplémentaire pour ce commit. et m'indique que les autres problèmes ont des contextes différents.

**Comment by corzakiewicz** [comment]
> Bonjour.
> 
> Je reviens vers vous pour vous confirmer que le commit ([b99b19b](https://github.com/pluginsGLPI/formcreator/commit/b99b19b4e8ec56602652c6c67c53af451f365e8f)) à bien résolu notre soucis d’URL aux chemins quelque peu étranges.

J'ai peut-être loupé une étape dans l'application de commit.
Voici comment j'ai procédé :
1/ j'ai édité le fichier \plugins\formcreator\setup.php
2/ j'ai supprimé une ligne et ajouter les autres comme décrit dans le commit
puis j'ai refait des tests.
Est-ce bien les seules manipulations à faire pour appliquer ce commit ?
Merci.

**Comment by btry** [comment]
Oui, mais c'est pas la méthode la plus sûre. Préférez l’utilisation de l'outil patch ou de git (git apply).  JE vous laisse vous documenter sur internet pour l’utilisation de ces commandes.

**Comment by corzakiewicz** [comment]
> s outils de développeur de votre navigateur avant de reproduire. Si vous trouvez dans l'

Je viens de faire le test en activant les outils développeur du navigateur (Chrome dans mon cas). Aucune erreur ne remonte dans l'onglet 'Network'. Si vous le souhaitiez, je peux vous envoyer des détails.

**Comment by btry** [comment]
Oui, ajoutez le screenshot. Je voudrais regarde autre chose dans les URL.

**Comment by corzakiewicz** [comment]
> Oui, ajoutez le screenshot. Je voudrais regarde autre chose dans les URL.

et voici :-)

![Screenshot05](https://user-images.githubusercontent.com/75740722/108491478-41425000-72a4-11eb-8d7e-f3f4efea6b57.jpg)

**Comment by corzakiewicz** [comment]
> > s outils de développeur de votre navigateur avant de reproduire. Si vous trouvez dans l'
> 
> Je viens de faire le test en activant les outils développeur du navigateur (Chrome dans mon cas). Aucune erreur ne remonte dans l'onglet 'Network'. Si vous le souhaitez, je peux vous envoyer des détails.
> 
> ![Screenshot05](https://user-images.githubusercontent.com/75740722/108491478-41425000-72a4-11eb-8d7e-f3f4efea6b57.jpg)

**Comment by btry** [comment]
Je pense que le patch d'hier n'est pas (ou plus)  appliqué. Pouvez-vous le remettre car il est nécessaire pour d'autre chose et on a maintenant la certitude qu'il ne casse rien ?

**Comment by corzakiewicz** [comment]
Voici un screenshot plus précis (avec les chemins complets) :

![Screenshot06](https://user-images.githubusercontent.com/75740722/108491900-caf21d80-72a4-11eb-87ae-0ddbb2c31212.jpg)

**Comment by btry** [comment]
Je tente de réduire la taille du fil en nettoyant le fil... La capture que j'ai lassée (la seconde à cet instant) me parait la même que la première (que j'ai déplacé d'ailleurs).

**Comment by corzakiewicz** [comment]
> Je tente de réduire la taille du fil en le nettoyant... La capture que j'ai lassée (la seconde à cet instant) me parait la même que la première (que j'ai déplacé d'ailleurs).

👍  merci.

**Comment by corzakiewicz** [comment]
Je viens de remplacer le fichier setup.php de mon installation par la version récupérée sur votre GitHub et...ça fonctionne très bien désormais.
J'ai manifestement fait une erreur quelque part depuis le début, je n'ai pas identifié laquelle.

Merci encore pour votre aide et bon courage pour les autres travaux en cours, FormCreator est un superbe plugin et plein d'avenir, je ne dois pas être le seul à être impatient de découvrir les prochaines fonctionnalités.

**Comment by khblkhivygiyfg** [comment]
@corzakiewicz 
Concernant la résolution de mon problème, oui j'ai bien fait comme ça: j'ai exporter mes formulaires, désinstaller le plugins, modifié le .php à la main,  réinstaller avec le .php rectifié, puis réinstallation et réimportation des formulaires.
Je précise que je suis en environnement "Bac à sable" : un GLPI de test (clone du prod' ) installé sur un hyperviseur, donc j'ai pu me permettre ces actions car si tout se pète c'est pas grave ^^.

**Comment by khblkhivygiyfg** [comment]
@corzakiewicz 
Je suis trop lent, désolé ^^

**Comment by btry** [comment]
OK, donc il ne reste que le retour de @Tijah82 .

Merci pour vos retours.

**Comment by Tijah82** [comment]
- dans la table glpi_items_tickets les lignes avec pour valeur tickets_id=16798 et itemtype=PluginFormcreatorFormAnswer.

> localhost/glpi/glpi_items_tickets/		http://localhost/phpmyadmin/tbl_select.php?db=glpi&table=glpi_items_tickets
> Affichage des lignes 0 -  0 (total de 1, traitement en 0.0001 seconde(s).)
>
> SELECT *  FROM `glpi_items_tickets` WHERE `tickets_id` = 16798
>
>
>
> 6679	PluginFormcreatorFormAnswer	6557	16798	

- dans la table glpi_plugin_formcreator_issues les lignes ayant sub_itemtype=Ticket et original_id=16798

> localhost/glpi/glpi_plugin_formcreator_issues/		http://localhost/phpmyadmin/tbl_select.php?db=glpi&table=glpi_plugin_formcreator_issues
> Affichage des lignes 0 -  0 (total de 1, traitement en 0.0049 seconde(s).)
>
>SELECT *  FROM `glpi_plugin_formcreator_issues` WHERE `original_id` = 16798 AND `sub_itemtype` = 'Ticket'
>
>
>
> 16874	LYNKS - Commerce	t_16798	16798	Ticket	2	2021-02-16 16:05:32	2021-02-17 07:28:42	22	0	372	0	0	&lt;div&gt;&lt;h1&gt;Données du formulaire&lt;/h1&...

**Comment by Tijah82** [comment]
Il n'y aurait pas comme un decalage entre 16874 et 16798 ? Je m'y connais pas du tout en base sql.

**Comment by Tijah82** [comment]
Je viens de faire le test en change l'id du lien en 16874 et la j'ai bien le ticket qui s'affiche. Comment faire pour reparer le decalage ?

**Comment by Tijah82** [comment]
Donc je confirme mes dires, j'ai testé sur plusieurs tickets et il y a un decalage entre l'ID GLPI et l'ID formcreator de 76 a chaque fois. Par exemple le ticket GLPI 16919 donne l'ID formcreator 16995. Une petite ligne de commande magique ? Ou va falloir que je me tape tout a la main ce weekend en allant du plus recent au plus ancien jusqu'a reparer tout ca ?

**Comment by Tijah82** [comment]
En fait il y a des soucis sur toute la base au niveau des ID. Meme sur les vieux tickets.
J'ai vu que la tache syncissue se lance toutes les heures depuis le 21 janvier alors qu'elle est desactivée.

En gros faudrait pouvoir avoir une commande qui permet de copier l'original ID sur l'ID. Parce que la c'est la misere sinon...

![image](https://user-images.githubusercontent.com/48673805/108559727-fe13cb80-72fb-11eb-8b8e-47687cd74a9b.png)

**Comment by btry** [comment]
Bonjout @Tijah82 

Si l'action automatique syncIssue est désactivée au niveau de GLPI, elle ne peut pas se lancer.

En ce qui concerne le décalage que vous observez, j'ai du mal à me faire mon idée : vous n'avez pas donné les noms de colonne sur les données extraites depuis la BDD. Du coup je ne suis pas certain de les interpréter correctement.

Vous avez trouvé un dacalage de 76 entre l'id d'un ticket et l'id d'un "issue" (une demande d'assistance) ? Comme je l'ai dit plus haut, ces ID n'ont rien à voir et ne sont pas nécessairement identiques.

**Comment by Tijah82** [comment]
Bonjour Btry,

Voici les 2 résultats précédents en image, si ca peut t'aider :)

![image](https://user-images.githubusercontent.com/48673805/108690029-236e2880-74fa-11eb-9259-2e96f28871c7.png)

![image](https://user-images.githubusercontent.com/48673805/108689850-e30eaa80-74f9-11eb-98b0-519b088be896.png)

**Comment by btry** [comment]
Je place vos captures dans votre commentaire précédent et supprime celui ci; pour faciliter la relecture.

**Comment by btry** [comment]
Je confirme : le décalage que  vous avez remarqué peut être normal. l'ID de la table issues n'est pas l'ID de la table tickets. En faisant la modification que vous avez soumise vous allez endommager votre table.

En version 2.10.2 et supérieur, l'action automatique du plugin avait quelques problèmes. Cela doit être maintenant résolu. De plus n'étant plus utile, elle a été désactivée en 2.10.0. Elle reste disponible car j'ai prévu de l’utiliser pour résoudre des soucis comme le vôtre.

Restons sur la demande d'assistance et le ticket que vous avez montré. L'url de votre notification par email est ```https://monglpi/glpi/index.php?redirect=ticket_16798``` et doit rediriger vers la demande d'assistance 16874. Quand vous arrivez sur la page montrée en https://github.com/pluginsGLPI/formcreator/issues/2129#issuecomment-781349180 , quelle est l'URL dans le navigateur ?

**Comment by Tijah82** [comment]
![image](https://user-images.githubusercontent.com/48673805/108696935-7ea41900-7502-11eb-8e08-414961a6b290.png)

**Comment by Tijah82** [comment]
J'ai bien essayé sur la base de test de désinstaller le plugin en ayant au préalable sauvegarder les formulaires puis j'ai réinstallé le plugin avec la dernière version, j'ai réimporté les formulaire mais j'arrive sur la page classique du ticket GLPI minimaliste. C'est comme ci il refusait de se réintégré a la base de donnée.

**Comment by Tijah82** [comment]
J'ai appliqué le patch mais ca ne change rien apres un nouvel essai, lien du mail

![image](https://user-images.githubusercontent.com/48673805/108698025-ec9d1000-7503-11eb-8f75-ad8d54c2dd7b.png)

qui donne 

![image](https://user-images.githubusercontent.com/48673805/108698215-2bcb6100-7504-11eb-96e4-b3c6671bbdee.png)


et en passant par "mes demandes d'assistance

![image](https://user-images.githubusercontent.com/48673805/108698150-16eecd80-7504-11eb-9a47-921c61504b52.png)

**Comment by btry** [comment]
Vous l'avez pas les mêmes ID, sans doute parce que vous êtes passé de prod à préprod.

Il faaut rejouer les requêtes SQL de l'autre jour

SELECT * FROM glpi_items_tickets WHERE tickets_id = 16930

SELECT * FROM glpi_plugin_formcreator_issues WHERE original_id = 16930 AND sub_itemtype = 'Ticket'

**Comment by Tijah82** [comment]
![image](https://user-images.githubusercontent.com/48673805/108700716-4f43db00-7507-11eb-94c3-125f7c4df274.png)

![image](https://user-images.githubusercontent.com/48673805/108700786-6a164f80-7507-11eb-8604-25fd036ed180.png)

**Comment by btry** [comment]
Je pense que le patch n'est pas appliqué correctement : une fois les redirectionsf faites par GLPI puis Formcreator, l'URL devrait être glpi-preprod/marketplace/formcreator/front/issue.form.php?id=17006

Je joins une petite explication du code concerné par le patch, une fois appliqué. 

![image](https://user-images.githubusercontent.com/14139801/108701893-d2196580-7508-11eb-94ad-512627194cef.png)

**Comment by Tijah82** [comment]
Je viens de faire l'essai sur le preprod, et cette fois ci ca fonctionne.
J'ai du faire un dump de la base mysql puis désinstaller Formcreator, le réinstaller et réimporter la base.

Cette fois le lien m'emmène sur le bon ticket. Ce soir je vais le mettre en place sur le base de prod et vous ferez un retour dans la foulée.

Merci :)

**Comment by Tijah82** [comment]
J'avais un exemplaire dans le dossier plugin et un autre dans le dossier market. J'ai viré le market et j'ai conservé uniquement celui du dossier plugin. Il y a peut être eu confusion entre les 2.

**Comment by btry** [comment]
Oui : il ne faut pas avoir le plugin dans 2 dossiers différents. Seulement un des deux s'appliquera.

**Comment by Tijah82** [comment]
L'opération sur le prod s'est bien passée. tout fonctionne a nouveau correctement.

Merci. ;)

**Comment by btry** [comment]
Merci pour le retour.
