### ISSUE TITLE
Cible : groupe d'utilisateurs

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#2132]
Bonjour, 
malgré les excellentes avancées et nouveautés du plugin ; encore une fois, bravo pour ce super boulot ; je toruve dommage et parfois gênant que les cibles d'un formulaire ne soient pas aussi basées sur des groupes utilisateurs.
En effet, si je souhaite permettre certains formulaires à certains utilisateurs, je n'ai pas d'autres choix que de leur assigner un profil dédié à ce seul usage ce qui est lourd pour l'utilisateur final et illogique au regard d'autres méthodes d'organisation ou classification des utilisateurs (AD, etc).
Je pense ne pas être le seul à demander cette modification ;)
Merci pour le travail réalisé, cette dernière version et la mise en forme des formulaires est aussi une réelle avancée.
Cet unique plugin joue beaucoup dans le choix d'un outil ITSM dans notre organisation ; GLPI ne permettant pas de couvrir l'ensemble des besoins correctement (remontée d'inventaire de logiciels, gestion des licences, etc ...). Teclib' doit l'entendre et vous aider à son developpement :)
Bonne journée

**Comment by btry** [comment]
Bonjour

> Teclib' doit l'entendre et vous aider à son developpement :)

Ce plugin est développé au sein de Teclib et est inclus dans l'offre GLPI Network.

> je toruve dommage et parfois gênant que les cibles d'un formulaire ne soient pas aussi basées sur des groupes utilisateurs.

C'est effectivement une fonctionnalité demandée régulièrement. Un sponsor serait le bienvenu pour soutenir Teclib' dans ce développement.

**Comment by Sicoval31** [comment]
La signature est en cours et je crois en attente chez Teclib ... pas eu de retour depuis ;)

**Comment by btry** [comment]
Bonjour

J'ai obtenu des renseignements. Une proposition vous normalement a été transmise le 24 janvier dernier.
