### ISSUE TITLE
Au moins un champ a une valeur incorrecte : Date d'ouverture

### ISSUE THREAD

**Issue by amongreville** [pluginsGLPI/formcreator#2134]
Bonjour,

Ma version de glpi = 9.5.3
Ma version formcreator = 2.11.1

Ma question est la suivante

j'ai un message a chaque fois que je valide un formulaire (Au moins un champ a une valeur incorrecte : Date d'ouverture)
Le ticket est créé mais sans date d'ouverture

![Capture3](https://user-images.githubusercontent.com/78857908/108056581-bd912500-7051-11eb-9603-54780d918524.PNG)
![Capture](https://user-images.githubusercontent.com/78857908/108056585-be29bb80-7051-11eb-93b7-8f481ef1e650.PNG)
![Capture2](https://user-images.githubusercontent.com/78857908/108056587-bec25200-7051-11eb-8892-913e79a3a045.PNG)

Auriez-vous, une idée?

merci de votre aide

**Comment by btry** [comment]
Bonjour

9a doit être la même chose que #2127

**Comment by amongreville** [comment]
Bonjour,

Merci, ce sont bien les deux mêmes demandes, je clôture donc celle-ci.
