### ISSUE TITLE
Validation de formulaire

### ISSUE THREAD

**Issue by grpinfra** [pluginsGLPI/formcreator#2139]
Je vous contacte suite à la mise à jour de Formcreator de la version 2.10.4 vers la version 2.11.1.
Depuis cette dernière, certains formulaire n'arrivent pas à être valider pour la création des tickets.
Aucun message d'erreur s'affiche et la popup de création de ticket ne s'affiche pas.

Les formulaires concernés contiennent des champs "date" et "date et heure" qui ne sont pas présents sur les formulaires qui ne sont pas concernés par le problème.

J'ai souhaité revenir sur la version 2.10.4 du plugin mais dès le transfert des fichiers terminés, les formulaires n'affichent plus aucunes questions et les éléments dans la cible du formulaire disparaissent.
Je suis donc revenu à la version 2.11.1.

Pour info, le GLPI que j'utilise est sur la version 9.5.1

A dispo si besoin de détails.
Merci pour vos retours.

**Comment by btry** [comment]
Bonjour

Je pense que votre souci est un doublon de #2127. Je suis en attente de retour des personnes dans cet autre fil : pendant mes recherches le bug a subitement cessé de se produire. Je manque d'informations pour trouver le souci dans ces conditions.

**Comment by grpinfra** [comment]
Bonjour,

Je viens de consulter l'issue #2127 et il y a effectivement des similitudes bien que amongreville puisse valider ses formulaires.
Ce qui est étrange c'est que j'ai d'autres formulaires avec des champs "date" qui ne pose aucun problème (1/13 formulaires rencontre ce bug).

La semaine dernière, j'ai réussi à contourner le problème en remplissant l'intégralité des champs avec une valeur (même nulle) mais aujourd'hui ce n'est pas suffisant :/

**Comment by btry** [comment]
Je pense qu'il y a un souci avec les champs date et date / heure. Si vous avez vous aussi le message d'erreur décrit en #2127, merci d'appliquer le patch que j'ai proposé pour générer un backtrace. J'en ai besoin pour cerner comment ce message peut apparaitre.

**Comment by grpinfra** [comment]
Je ne rencontre pas le message d'erreur décrit dans l'issue #2127.
Quand le formulaire est soumis pour création du ticket, la page s'actualise en conservant les données des champs du formulaire et sans créer le ticket.

Je ne sais pas si pour ma demande le backtrace sera essentiel mais je suis en attente d'un environnement de test.

**Comment by btry** [comment]
Si la page s'actualise et conserve les donné&es, c'est que le formulaire ne passe pas la phase de validation. Est ce que cela se produit si vous laissez votre champ date (ou date heure) vide ?

**Comment by grpinfra** [comment]
Oui c'est effectivement le cas quand un champ date (ou date et heure) est vide.
J'ai même essayé en remplissant ces champs afin de n'avoir aucun champs vide mais sans succès.
Dans le formulaire en question, il y a 1 champ date et 6 champs date et heure.

**Comment by btry** [comment]
Ca ressemble à ce que j'ai trouvé en cherchant l'autre bug. 

Prenez ce fix, ça devrait fonctionner: https://github.com/pluginsGLPI/formcreator/commit/940bfee2ecf7a22a4fc5033d81c90536e0baeac8

**Comment by grpinfra** [comment]
Je viens d'appliquer le fix sans changement.
Par contre je n'ai pas de dossier "tests" dans mon arborescence de plugin. Je n'ai pas pu corriger cette ligne : tests/fixture/PluginFormcreatorDependentField.php 

Voici l'arborescence : 
![image](https://user-images.githubusercontent.com/79251875/108346761-0676e400-71e0-11eb-987d-0ec83ba757ca.png)

**Comment by btry** [comment]
Le dossier tests n'est pas présent si vous téléchargez le plugin à partir d'une archive de release. vous pouvez ignorer ce dossier.

On va procéder autrement : exportez le formulaire en question ou créez en un très simple permettant de reproduire le souci. Déposez ici son export.

**Comment by grpinfra** [comment]
Voici le formulaire en question : 
[export_formcreator_20210218_1309.zip](https://github.com/pluginsGLPI/formcreator/files/6002629/export_formcreator_20210218_1309.zip)

**Comment by btry** [comment]
Ce n'est pas en lien avec des quesxtions de type date, mais les questions de type select. C'est dû à une réorganisation de classes sur les types de question. J'ai un peu trop factorisé et laissé passer des petites différences. Le fix sera bientôt disponible.

**Comment by grpinfra** [comment]
Merci pour ce retour ! Hâte de pouvoir appliquer le fix

**Comment by btry** [comment]
Voilà le fix. Merci de me faire un retour. Vous pouvez garder le précédent; il vous évitera un autre bug.

**Comment by grpinfra** [comment]
Je viens d'appliquer le fix et ça a l'air de fonctionner.
J'ai repris les mêmes données de champs sur le formulaire que ce matin et le ticket est créé.

Peut-on garder l'issue ouverte jusqu'à mardi ou mercredi prochain afin de voir si j'ai des retours utilisateurs ?

Thanks !!

**Comment by btry** [comment]
Oui, on peut attendre un peu avant de  fermer.

**Comment by grpinfra** [comment]
Bonjour,
Le fix fonctionne a merveille, il y a eu environ une dizaine de formulaire soumis depuis notre dernier échange.
Aucun retour de bug n'a été remonté au service.
Merci encore pour la réactivité !
