### ISSUE TITLE
Impossible to add destination

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#214]
Hello

When I want to add a destination nothing happens

try with 0.91 - 9.1 glpi version and form creator master

**Comment by satyan01** [comment]
2016-06-21 12:04:40 [854@UNGSRVGVA118]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targets` (`name`,`itemtype`,`plugin_formcreator_forms_id`,`items_id`) VALUES (\'database creation\',\'PluginFormcreatorTargetTicket\',\'12\',\'\')
  Error: Incorrect integer value: '' for column 'items_id' at row 1
  Backtrace :
  inc\commondbtm.class.php:425                       
  inc\commondbtm.class.php:831                       CommonDBTM->addToDB()
  plugins\formcreator\front\target.form.php:14       CommonDBTM->add()

**Comment by satyan01** [comment]
Hello

no up ?

**Comment by Kahalisto** [comment]
Hello !

Same issue for me with same error in sql_errors.log

**Comment by flegastelois** [comment]
Hello,

What is the version of your MySQL Server ? Is STRICT mode is enable ?
And what is the version of PHP ?

regards,

**Comment by satyan01** [comment]
mariadb10.2 php 7.04

**Comment by satyan01** [comment]
yes but same issue
