### ISSUE TITLE
Icône de formulaire

### ISSUE THREAD

**Issue by grpinfra** [pluginsGLPI/formcreator#2140]
**Describe the bug**
Problème d'affichage de l'icône sélectionné pour un formulaire.

**Expected behavior**
Depuis la mise à jour 2.11.1, j'ai remarqué que les icônes de formulaire ne s'affiche pas lors de la modification de celui-ci.
Néanmoins l'icône est bien visible sur le catalogue de service.

Si l'on sauvegarde un formulaire sans toucher à l'icône, ce dernier disparaît et il faut le re-sélectionner.

**Screenshots**
![image](https://user-images.githubusercontent.com/79251875/108340307-b7798080-71d8-11eb-9d47-66786d67dd5b.png)

**Additional context**
GLPI version : 9.5.1
Formcreator version : 2.11.1

**Comment by btry** [comment]
Bonjour

Vérifiez le ticket #2124; il y a un correctif qui devrait fonctionner pour vous aussi.

**Comment by grpinfra** [comment]
Bonjour,
Je viens d'appliquer le fix et c'est OK ;)
Merci beaucoup !

![image](https://user-images.githubusercontent.com/79251875/108342275-eb55a580-71da-11eb-8bf8-895b3e8690cc.png)
