### ISSUE TITLE
Impossible d'ajouter un valideur

### ISSUE THREAD

**Issue by supraviirus** [pluginsGLPI/formcreator#2141]
Bonjour, 

Apres plusieurs test sur mon glpi (version 9.4.5 et 9.5.3) il m'est impossible d'ajouter des groupes valideurs ou même des utilisateur de mon AD
Que se soit sur des crée a l'instant ou alors des formulaire importé
version formcreator tester : 2.9.1 / 2.10.4 / 2.11.2

Si vous avez une idee ou une astuce ?

**Comment by btry** [comment]
Bonjour

Il faut se concentrer sur Formcreator 2.11. Les autre versions ne sont plus maintenues. 

Vos groupes et utilisateurs sont-ils importés dans GLPI ?

**Comment by supraviirus** [comment]
Bonjour,

D'accord mais même avec la version 2.11.2 j'ai le soucis,
Oui oui tous mes groupes sont présent ainsi que mes utilisateurs

**Comment by btry** [comment]
Vérifiez maintenant que dans vos groupes il y a au moins un utilisateur ayant le droit de valider un ticket en incident ou en demande. Seul les utilsiateurs avec ce droit sont disponibles, et seuls les groupes ayant de tels utilisateurs sont disponibles.

![image](https://user-images.githubusercontent.com/14139801/108355209-cbc67900-71ea-11eb-9d9e-5d752b39bbf0.png)

**Comment by supraviirus** [comment]
Merci, par ou passez vous pour accédez a ce menu ?

**Comment by supraviirus** [comment]
Super merci j'ai trouver il faut crée un profile avec les autorisations, puis ajouté les utilisateurs au profiles crée et le tour et joué
