### ISSUE TITLE
Affectation "entité" au Ticket

### ISSUE THREAD

**Issue by plrlux** [pluginsGLPI/formcreator#215]
Hy,

Environnement : GLPI = 0.90 /  Forms = 0.90-1.3.3

Configuration :
Nous avons créé des formulaires dans l'**entité "Parent"** avec "Sous-entités" à "oui"
Le **validateur** fait parti de l'entité "Parent".

Quand un collaborateur ( demandeur ), d'une sous-entité, crée un formulaire et que celui-ci et validé, la création du ticket et créé dans **l'entité par défaut du validateur.** 

Je n'ai pas trouvé dans les règles, comment affecter **l'entité "demandeur"** au ticket créé.

Cordialement.

**Comment by plrlux** [comment]
Hy,

Environnement : GLPI = 0.90 /  Forms = 0.90-1.3.3

Configuration :
Nous avons créé des formulaires dans l'**entité "Parent"** avec "Sous-entités" à "oui"
Le **validateur** fait parti de l'entité "Parent".


Quand un collaborateur ( demandeur ), d'une sous-entité, crée un formulaire et que celui-ci et validé, la création du ticket et créé dans **l'entité par défaut du validateur.** 

Je n'ai pas trouvé dans les règles, comment affecter **l'entité "demandeur"** au ticket créé.

Cordialement.

**Comment by btry** [comment]
Bonjour

Ouvrez en modification la destination de votre formulaire en charge de générer le ticket. Il y a plusieurs choix dans la dropdown **"Entité de destination"**

![image](https://cloud.githubusercontent.com/assets/14139801/17483458/5f1efc8c-5d86-11e6-8f14-fb4e225b8b20.png)

**Comment by plrlux** [comment]
Merci beaucoup de votre retour,
et,
autant pour moi, je n'avais pas vue (ou oublié) le "crayon" pour modifier la destination.

Merci encore.
