### ISSUE TITLE
Laisser la possibilité aux demandeurs d'attribuer aux techniciens

### ISSUE THREAD

**Issue by techinfosbri** [pluginsGLPI/formcreator#2153]
Bonjour,
Dans notre service informatique, nous ne gérons pas tous la même chose, j'ai réalisé des formulaires dynamiques laissant le choix aux utilisateurs pour nous expliquer au mieux leur problème.

Est-il possible de laisser la possibilité aux utilisateurs de choisir a qui attribuer le ticket?

Merci

**Comment by btry** [comment]
Bonjour

Vous devriez pouvoir faire cela en ajoutant une question de type objet GLPI / Utilisateur et en utilisant sa réponse pour assigner l'utilsiateur en tant que technicien. Cela se passe dans la configuration du ticket cible, dans la partie dédiée aux acteurs.

**Comment by techinfosbri** [comment]
Bonjour,
Merci de votre réponse, si je fais ça, il va chercher dans tout la base de donnée de glpi et je voudrais laisser le choix avec seulement tous les techniciens et pas toute la liste des utilisateurs, je sais pas si c'est possible.

Merci

**Comment by btry** [comment]
Il n'y a pas de fonction de filtrage possible pour le moment.

**Comment by techinfosbri** [comment]
> Il n'y a pas de fonction de filtrage possible pour le moment.

Vous savez si elle sera possible prochainement?

**Comment by btry** [comment]
Ce n'est pas dans la roadmap pour le moment?

**Comment by techinfosbri** [comment]
> Ce n'est pas dans la feuille de route pour le moment?

Parfait merci

**Comment by btry** [comment]
Précision. J'ai laissé un point  d'interrogation en fin de phrase.. C'est une erreur de frappe. C'était une affirmation. Pas de plan à ce jour sur la fonctionnalité.

**Comment by techinfosbri** [comment]
> Précision. J'ai laissé un point d'interrogation en fin de phrase .. C'est une erreur de frappe. C'était une affirmation. Pas de plan à ce jour sur la fonctionnalité.

Oui je m'en suis douté.
Merci de la réponse
