### ISSUE TITLE
Importation des formulaires impossible

### ISSUE THREAD

**Issue by khblkhivygiyfg** [pluginsGLPI/formcreator#2154]
Bonjour,

Je revient vers vous après le bug des URL pour la 2.11.1

Ayant vu qu'une nouvelle MAJ du plugin à été faites a la suite de ce souci, j'ai mis a jour Formcreator sur le serveur de prod et test. 
Le problème est que l'importation des formulaires du GLPI-test ne s'importe pas dans le GLPI-Prod (Importation du formulaire impossible, le fichier a été généré avec une autre version). 
Le glpi-test est un clone du prod (mes serveurs sont virtualisés). Il ont la même version de php et de glpi, il ont la même version de Formcreator (2.11.2 car mise a jour correctement sur le prod et test : suivi le tuto de btry). mais cela ne veut pas se faire...

Est-il possible de modifier quelques chose quelque part pour forcer l'importation SVP ?? car je sais que les formulaires sont bons et beaucoup trop long a refaire à la main sur le prod.

Merci

**Comment by btry** [comment]
Bonjour

Vous avez donc un export fait avec Formcreator 2.11.2 et il ne s'importe pas dans une autre version 2.11.2 ?

**Comment by khblkhivygiyfg** [comment]
C'est ca.

J'ai essayé dans plusieurs sens possible pour essayer que l'importation marche mais que ce soit en 2.11.2 des deux cotés ne m'aide pas.

**Comment by btry** [comment]
Bon.. 

Je vais revoir ça et mettre des tests unitaires. Un peu de patience, le temps que je fasse le fix.

**Comment by khblkhivygiyfg** [comment]
OK, merci bien

**Comment by btry** [comment]
Voilà un fix qui devrait résoudre le souci.

**Comment by btry** [comment]
Bonjour

Avez vous pu tester le correctif ?

**Comment by btry** [comment]
Bonjour

A défaut de retour, je ferme le ticket.
