### ISSUE TITLE
PHP Warning with GLPI 9.5.4

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2158]
**Describe the bug**
After updating to GLPI 9.5.4 I receive the following error in "php-errors.log"

![image](https://user-images.githubusercontent.com/35368369/109723704-3aadb580-7b8d-11eb-8b3f-126031c33c9a.png)

**To Reproduce**
1. Go to 'any form'
2. Click on 'open ticket'
3. See error like print

**Expected behavior**
Open a ticket and receive no errors in the log

**Screenshots**

GLPI 9.5.4
Formcreator 2.11.2

Obs: Despite the message, I didn't notice any specific errors

**Comment by btry** [comment]
Bonjour

Je pense qu'en GLPI 9.5.3 le bug devait déjà être là, vous en avez une trace ?

**Comment by btry** [comment]
Avec un test je ne reproduis pas. Il pourait y avoir une anomalie dans le stockage en BDD des valeurs de votre multiselect.

Regardez en BDD la question correspondante et montrez moi le contenu de la colonne **value**..

**Comment by phamorais** [comment]
@btry 
Hi!
the error did not happen in 9.5.3.
Sorry, but I could not understand your request, I believe that in English it is better.

what values do i need to show you in the database?

**Comment by btry** [comment]
Hi, 

Sorry, I did not noticed that the thread is in english 

Please find the row of the question in the  database. The table is **glpi_plugin_formcreator_questions**.  Once you fond the rown show the content of the **values** column. This must be a JSON string like the following

["a","b","c","d"] which represents 4 choicies: a, b, c and d

**Comment by phamorais** [comment]
this issue is no longer needed
