### ISSUE TITLE
Issue about rights - no possibility to delete form after create

### ISSUE THREAD

**Issue by tunibet** [pluginsGLPI/formcreator#216]
No possibility to delete form after create. an idea ?

we are in latest version of the plugins and glpi in ver  0.90.3 

thanks for your help

best regards

Flo

**Comment by btry** [comment]
Hi

Your question is ambiguous to me. Do you mean delete a form in the forms administration, or delete a form after filling it to request assistance ?

**Comment by btry** [comment]
Hi

Having no feedback, I close.
