### ISSUE TITLE
Problem when trying to make visibility dependent on the result of a question which type is ITIL category

### ISSUE THREAD

**Issue by nsalguero** [pluginsGLPI/formcreator#2163]
Hi,

**Describe the bug**
When trying to make visibility of a question or of the submit button (or even condition to create a target) dependent on the result of a question which type is ITIL category, it does not work if the value of the condition corresponds to a subcategory.

**To Reproduce**
1. Create a question "ITIL category" (with categories, for instance: A > B).
2. Create another question, for example radio buttons with test1 and test2.
3. Try to set the visibility of the second question, either shown by default or masked by default.
4. It only works when comparing to A.  The condition is never met when comparing to B.

**Expected behavior**
Being able to set a condition of visibility dependent on the result of a question "ITIL category" not only for a category but also for a subcategory.

Best regards,

Nicolas Salguero.

**Comment by btry** [comment]
Hi

Can you show how you set the condition in the above scenario ?

**Comment by nsalguero** [comment]
Here are two screenshots: the first one is a question of type "ITIL category" (ITIL categories are "A" > "B") and the second one is a question which should be displayed only if the response to the first question is "B".  In my tests, the second question is never displayed whereas, if I set the second question to be displayed only if the response to the first question is "A", it works.

![question_category](https://user-images.githubusercontent.com/14334161/110350630-36254900-8034-11eb-8440-95ef9bddccfd.png)
![question_depending_category](https://user-images.githubusercontent.com/14334161/110350662-3d4c5700-8034-11eb-8876-eb910903ae2f.png)

**Comment by nsalguero** [comment]
Hi,

I found the solution for my problem: the value of the condition must be "A > B" and not just "B" as I thought.

Best regards,

Nico.
