### ISSUE TITLE
Question - Register all tickets (not the forms) on formcreator_issue table (2.11.2 - Marketplace version)

### ISSUE THREAD

**Issue by dfper-tjpa** [pluginsGLPI/formcreator#2165]
Fellows,

I want to see all my tickets (include those are multiples creates by 1 form) in my requests list... I have made changes on issue.class.php to tell $union = $query2 and comment the line that doesn't list the tickets when have more than 1  by form. Have any other change that i have to do?
![image](https://user-images.githubusercontent.com/80268312/110435472-d2316d80-8091-11eb-9e57-7359dc961bb1.png)
Now the changes that i made are rollback to avoid any mistake.

**Comment by btry** [comment]
Hi 

There are a lot of other changes to do, in formanswer.class.php

Whena form is filled and it generates several tickets the issues table is added a row representing the formanswer, not the tickets. Changes need to be done here.

I cannot tell much more as this change may require a lot of checks and code changes. 

It seems you want to remove the assistance request concept of the plugin, which somewhat its core. This may be the signal that Formcreator is not for you or at a bug code change cost. Moreover you won't be able to upgrade the plugin after such change, and you will be stuck to a given Formcreator version and on medium term this will stick you to a given GLPI version as well.
