### ISSUE TITLE
Affichage du champ selon condition

### ISSUE THREAD

**Issue by Imad94** [pluginsGLPI/formcreator#217]
Bonjour,

un problème lié à l'affichage du champ en fonction des conditions semble persister.

J'ai une première question sous forme de bouton radio avec 2 réponses A ou B (A par défaut)

Toutes les questions suivantes (réponses obligatoires si affiché) dépendent de la première question:

Affiché par défaut sauf si, première question = B

Logiquement, je m'attends à une action de javascript "cachant" le ou les champs si B est sélectionné. Mais cela ne fonctionne pas.

Configuration : glpi 0.85, Formcrator 0.90-1.3.3 testé avec Firefox 47, Chrome 51 Javascript activé,

**Comment by btry** [comment]
Hi

I created a form with two questions as you described.

In preview mode it seems to work : 

![image](https://cloud.githubusercontent.com/assets/14139801/17409199/73d50b32-5a6e-11e6-8ab0-97b527312d88.png)

As sook I click on "B" the mandatory field disappears.

![image](https://cloud.githubusercontent.com/assets/14139801/17409202/7a048c3a-5a6e-11e6-96ee-c3930b439e40.png)

Can you check with the developer tools of your browser if there is a Javascript error ?

Tests with glpi 0.85.5 + FormCreator 0.90-1.3.3 from repo against Firefox 45.2 ESR and Chromium 51.0.2704.79 (Debian Stretch)

**Comment by btry** [comment]
Hi

This issue is very old, then I close. If the problem persists, please have a recent version of Formcreator and open a new ticket.
