### ISSUE TITLE
Champ demandeur

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#2172]
**Describe the bug**
When we use Requester field in a form we have an error 500 with GLPI 9.5.4 and FormCreator 2.11.2

**To Reproduce**
1. Go to a form using requester field
2. Create your ticket

**Expected behavior**
The ticket should be create

**Screenshots**
Log error : glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to PluginFormcreatorTargetTicket::setTargetAssociatedItem() must be of the type array, int given, called in /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php on line 781 in /var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php at line 1010
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:781 PluginFormcreatorTargetTicket->setTargetAssociatedItem()
  plugins/formcreator/inc/formanswer.class.php:814   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:1000  PluginFormcreatorFormAnswer->generateTarget()
  inc/commondbtm.class.php:1151                      PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()

**Comment by btry** [comment]
Hi

Can you explain what is a requester field ?

Is it a question of type user, which is used to fill the requesters of a target ticket ? (with Person from a question) ?

**Comment by lolokai** [comment]
Yes

**Comment by btry** [comment]
Hi

I don't reproduce, but by reading the code I guess you're impacted by a bug I found myself a few days ago.

Try to apply this fix and feedback

https://github.com/pluginsGLPI/formcreator/commit/eff7ade42b17e88f59df055e403d3285271857b4

**Comment by btry** [comment]
Hi

@lolokai did you had time to try the above patch ?

**Comment by btry** [comment]
Hi

Having no feedback, I close. The fix is merged.
