### ISSUE TITLE
Forms does not display "ITIL OBJECT" list if it is a child of the form

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2176]
Hi! @btry 
I don't know if it is an error or a new functionality in the formcreator in version 2.11.

I currently have the following structure

Entity X (root)
Entity X> Child 1
Entity X> Child 2

All my forms. are created in "Entity X", so that users do not have to keep selecting the entities before opening a new ticket. After opening the ticket I configure it to go to "Entity X> Child 1" or "Entity X> Child 2". It always worked perfectly.

My forms, has a question as below, where based on the answer, the ticket is already categorized automatically.

Before version 2.11, I accessed the form and had the list being offered correctly, like next gif

![funcionando](https://user-images.githubusercontent.com/35368369/111383398-e8898b80-8686-11eb-9d6c-2343a819f387.gif)

After the upgrade to 2.11, the lists are no longer offered, like next gif

![nao funcionando](https://user-images.githubusercontent.com/35368369/111383530-1a9aed80-8687-11eb-9c63-4f2c69761a56.gif)

The question in form is like this

![image](https://user-images.githubusercontent.com/35368369/111383847-8e3cfa80-8687-11eb-8a1e-08114ce5c1ad.png)

![image](https://user-images.githubusercontent.com/35368369/111384553-6ac67f80-8688-11eb-999b-0827af1e7372.png)

The categories offered in the form are from Child entities, that is, they are not in the same entity as the form.

Doesn't my implementation method work with version 2.11?

GLPI 9.5.4
Formcreator 2.11.2

**Comment by btry** [comment]
Hi

I'm unsure because I don't know in which entity is the requester. I think you're impacted by the change done to fix the following issue: https://github.com/pluginsGLPI/formcreator/issues/2023

This change was announced in the version 2.11.0-beta and repeated in all next releases.

**Comment by phamorais** [comment]
@btry 

The requester is in entity X.
All Forms are in entities X

However, the ITIL categories are in the entities:

Entity x> child 1
Entity x> Child 2

In this way, all companies that use this form in the formcreator will be prevented from upgrading to version 2.11
The formcreator's functionality to filter the lists according to the entity was really expected and beneficial.
However, if you have a form that has the option of "recursive" it should see the child entities, as is the logic of GLPI.,

**Comment by phamorais** [comment]
@btry 

Analyzing another environment, I have the same structure.

ROOT entity
Entity> 1
Entity> 2

The forms are registered with the ROOT entity
And the ITIL categories are in the Daughters entities.

See.

List of entities

![image](https://user-images.githubusercontent.com/35368369/111486635-6a74c580-8716-11eb-9364-ff2bd008b670.png)

The form "motoboy" is in root entitie

![image](https://user-images.githubusercontent.com/35368369/111486728-80828600-8716-11eb-855f-428448406697.png)

The form has a question like "Assistance - Ticket categories"

![image](https://user-images.githubusercontent.com/35368369/111486939-af006100-8716-11eb-8fd7-00e66c1b10da.png)

See that the category "Services> Motoboy" is in a child entity

![image](https://user-images.githubusercontent.com/35368369/111487124-d9eab500-8716-11eb-8a1b-0b24ffda0c0b.png)

And in this one the category is displayed as expected

![image](https://user-images.githubusercontent.com/35368369/111487238-f1c23900-8716-11eb-9762-7955fcef16b1.png)

In this environment I have GLPI 9.5.3 and Formc 2.11.2

Is it a bug with version 9.5.4?

**Comment by btry** [comment]
Hi

Do you use the version tagged 2.11.2 or do you use the latest revision of the branch support/2.11.0 ? 

loHave a look in formcreator/inc/fields/dropdownfield.class.php, method buildParams()

```php
   public function buildParams($rand = null) {
      global $DB, $CFG_GLPI;

      $id        = $this->question->getID();
      $fieldName = 'formcreator_field_' . $id;
      $itemtype = $this->getSubItemtype();

      $form = new PluginFormcreatorForm();
      $form->getFromDBByQuestion($this->getQuestion());
      $dparams = [
         'name'     => $fieldName,
         'value'    => $this->value,
         'display'  => false,
         'comments' => false,
         'entity'   => $form->fields['entities_id'],
         //'entity_sons' => (bool) $form->isRecursive(),
         'displaywith' => ['id'],
      ];

      if ($rand !== null) {
         $dparams['rand'] = $rand;
      }

```

Check the line commented out. Is it also commented out in your version ?

**Comment by btry** [comment]
If this line is commented out, please try the following patch for GLPI

https://github.com/glpi-project/glpi/pull/8834/files

Next re-enable the above line.

**Comment by phamorais** [comment]
@btry 
Hello
No first post (where the error is happening), I have GLPI version 9.5.4 and Formcreator 2.11.2

![image](https://user-images.githubusercontent.com/35368369/111623354-0828cd00-87c9-11eb-8c16-0232e3df4694.png)

After applying the path https://github.com/glpi-project/glpi/pull/8834/files and uncomment the buildParams () line, the list reappears


![image](https://user-images.githubusercontent.com/35368369/111623704-7a99ad00-87c9-11eb-9564-0271f01cf303.png)

I need to apply this 2 commits ?

![image](https://user-images.githubusercontent.com/35368369/111623811-a61c9780-87c9-11eb-85ac-a8e46a9c120f.png)

**Comment by phamorais** [comment]
@btry 
Thank you for your help!

Https://github.com/glpi-project/glpi/pull/8834/files Fixed the problem.
