### ISSUE TITLE
Formcreator Validation

### ISSUE THREAD

**Issue by flagada97** [pluginsGLPI/formcreator#2177]
Bonjour,

J'ai GLPI en version 9.4 et formcreator 2.10.3
J'aurais aimé savoir s'il était possible d'avoir cette option sur les formulaires : 

![image](https://user-images.githubusercontent.com/80892425/111616137-d4a66c80-87e1-11eb-85dc-147b985eda7a.png)

Car depuis une erreur réseau sur notre infrastructure, la validation n'apparait plus dans les formulaires.

Pouvez-vous me venir en aide car je tourne en rond?

**Comment by btry** [comment]
Bonjour 
Cette fonctionnalité étant implémentée, vous devez en bénéficier. 

Attention toutefois: si il n'y a qu'un seul utilisateur validateur  ou un seul groupe validateur, le choix ne sera masqué. Le plugin sait déjà quel validateur choisir puisqu'il n'y en a qu'un.

Formcreator 2.10.x est arrivé en fin de vie. Le support communautaire continue sur la version 2.11. Pour l'aide à l'utilisation du plugin, rendez-vous sur le forum communautaire de GLPI. Si vous avez besoin d'assistance professionnelle, vous pouvez souscrire à une offre de support GLPI Network: https://glpi-project.org/fr/support/

**Comment by flagada97** [comment]
Bonjour,

Savez-vous comment modifier le validateur sur le plugin?

**Comment by btry** [comment]
Bonjour

Posez votre question ici : https://forum.glpi-project.org/login.php

Github est pour le développement, les bugs et features.
