### ISSUE TITLE
Problems with entities and recursion

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#2180]
Hi,

  We have a very complex entity structure and, to work better, computers are at a higher level and we enable the recursion option so that they are accessed from the levels below. The forms are in the entity of the technical support contractor or in another entity that has services where it is necessary to indicate the user's computer.

  With printers, we work differently, we have 3 printer rental contracts and, therefore, 3 different entities with their printers in the entity. With this structure, the forms are above and with the option of active recursion, allowing the same form to serve the 3 companies without mixing the calls.

![image](https://user-images.githubusercontent.com/43650152/111683272-07615c80-8804-11eb-9771-959da44b1401.png)

  The problem that occurs with the new version (2.11.x) is that, the computer form, which is at a lower level than the equipment, does not list the equipment, the printers work normally.

  When applying the FIX "fix (dropdownfield): disable recursivity", the problem is reversed, the computer forms work normally, but the printer forms do not list the printers.

  I found a palliative solution to the problem that is not applying FIX and, disabling the recursion of the computers form, which, strangely, starts to list the computers.

Thanks for the help.

**Comment by btry** [comment]
Hi

Did you see for some cases a dropdown showing an error message "could not load data" or similar ?

**Comment by jvergacas** [comment]
Hi @btry 

An easy way to reproduce the problem is to place computers with active recursion in one entity and create a form in another entity below the first. If the form's recursion is active, it will not list the computers, to list, you must disable the form's recursion.

**Comment by btry** [comment]
Hi

I began to buld a set of data this way, but I'm busy on other things for now. Please be patient.

**Comment by btry** [comment]
Hi

I'm coming back to your issue.

I did a test with version 2.12.0-beta and it seems I don't reproduce.

I have 
- a computer un root entity, 
- a form in root entity > sub entity

if computer is recursive, no matter the recursion of the form, I can view the computer. I tried by locating myself in the root entity (recursive) and in the sub entity).

Please tell if you observe the bug in self-service or anonymous form.

**Comment by jvergacas** [comment]
This issue has been resolved.
