### ISSUE TITLE
SELECTION LDAP

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2182]
Hello,
in my form, I would like to have a drop-down list with the locations.
![image](https://user-images.githubusercontent.com/17006344/111999542-6208fa00-8b1d-11eb-85c9-f47487e7e0b3.png)
But the field is empty
![image](https://user-images.githubusercontent.com/17006344/111999631-75b46080-8b1d-11eb-992c-389ff7d8b572.png)

All my users are synchronized with the ad and it works. The location is also automatically uploaded to each user.
![image](https://user-images.githubusercontent.com/17006344/111999807-9ed4f100-8b1d-11eb-8eac-6f1437aac966.png)

Formcreator 2.11.2
GLPI 9.5.4
you need php-error.log?

Bests regards.

**Comment by btry** [comment]
Hi

Please try this patch for GLPI: https://github.com/glpi-project/glpi/pull/8834/files

Do not forget to feedback.

**Comment by btry** [comment]
Hi 

If the locations are in the GLPI database, why don't you create a regular dropdown using the locations in GLPI instead of picking them from LDAP ?

**Comment by Riesuu** [comment]
Hello,
I have well the places of informed in GLPI, but I do not have the option "place" in "Object GLPI
![image](https://user-images.githubusercontent.com/17006344/112114073-e90ab080-8bb7-11eb-9686-bee82c151024.png)

**Comment by btry** [comment]
Locations are dropdowns, not GLPI objects. This is the reason you don't find them.

**Comment by Riesuu** [comment]
Sorry but I can't find the drop down list, I only have "selection".

![image](https://user-images.githubusercontent.com/17006344/112130307-a56c7280-8bc8-11eb-8953-dee6df1cee2e.png)

**Comment by btry** [comment]
In french, this is "Intitulé". it matches the items found in the menu **Configuration > Intitulé**

**Comment by Riesuu** [comment]
Ah ok, problem is the same
![image](https://user-images.githubusercontent.com/17006344/112131434-d8633600-8bc9-11eb-8515-a86f5e5dd0d6.png)

![image](https://user-images.githubusercontent.com/17006344/112131492-e749e880-8bc9-11eb-8c39-b37c9b7566c7.png)

**Comment by btry** [comment]
I'm not sure the problem is the same with LDAP field. But with the dropdown question type and GLPI 9.5.4 you are imapcted by a GLPI bug.

Try this fix: https://github.com/glpi-project/glpi/pull/8834/files

**Comment by Riesuu** [comment]
It works! Thanks.

**Comment by btry** [comment]
:+1:
