### ISSUE TITLE
[ 2.11.2 ] Issue with Forms - Target Ticket 

### ISSUE THREAD

**Issue by alexanderheuserr** [pluginsGLPI/formcreator#2183]
Hi, 

Since we moved to GLPI 9.5.4 and Formcreator 2.11.2, we are unable to commit changes to the target : 

![image](https://user-images.githubusercontent.com/81176661/112016860-5fae9c00-8b2d-11eb-81ac-4129aed1939c.png)

We have found the following error in the php-errors.log :  

`[2021-03-22 16:36:04] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: strlen(): Argument #1 ($str) must be of type string, array given in /usr/share/glpi/inc/dropdown.class.php at line 1784
  Backtrace :
  plugins/formcreator/inc/question.class.php:1134    Dropdown::showFromArray()
  ...s/formcreator/inc/abstracttarget.class.php:1278 PluginFormcreatorQuestion::dropdownForForm()
  plugins/formcreator/inc/targetticket.class.php:191 PluginFormcreatorAbstractTarget->showPluginTagsSettings()
  inc/commonglpi.class.php:627                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:101                           CommonGLPI::displayStandardTab()`

**Comment by btry** [comment]
Hi

Test this fix and feedback.

**Comment by alexanderheuserr** [comment]
Hi,

Fix applied and it's all ok.

![image](https://user-images.githubusercontent.com/81176661/112118709-ed859800-8bbc-11eb-96f1-8585a2b3f9fe.png)

Thanks !

**Comment by btry** [comment]
Thank you for your feedback. The fix will be available in the next release.
