### ISSUE TITLE
Return value of DateField::getValueForTargetText() must be of the type string, null returned

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/formcreator#2187]
**Describe the bug**
If we have a form with an **optional** datefield and the user left it empty, if we specified this answer in the target ticket, glpi will show a blank page on form submit with the following error in the log file. Also, when this happens, no tickets are created for the assocated form.

`[2021-03-23 09:20:42] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of GlpiPlugin\Formcreator\Field\DateField::getValueForTargetText() must be of the type string, null returned in /var/www/html/glpi-9.5.3-bugfixes/marketplace/formcreator/inc/field/datefield.class.php at line 120
  Backtrace :
  ...place/formcreator/inc/formanswer.class.php:1103 GlpiPlugin\Formcreator\Field\DateField->getValueForTargetText()
  ...r/inc/notificationtargetformanswer.class.php:69 PluginFormcreatorFormAnswer->parseTags()
  inc/notificationtarget.class.php:1269              PluginFormcreatorNotificationTargetFormAnswer->addDataForTemplate()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:107        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:184                NotificationEventAbstract::raise()
  ...place/formcreator/inc/formanswer.class.php:1209 NotificationEvent::raiseEvent()
  ...tplace/formcreator/inc/formanswer.class.php:998 PluginFormcreatorFormAnswer->sendNotification()
  inc/commondbtm.class.php:1143                      PluginFormcreatorFormAnswer->post_addItem()
  marketplace/formcreator/front/form.form.php:142    CommonDBTM->add()
`

**To Reproduce**
1. Create a form with an optional datefield 
2. Specify this answer in the target ticket
3. Compleate a form and leave this field empty
4. Submit the form

**Screenshots**

![image](https://user-images.githubusercontent.com/38400135/112157128-46553080-8bbd-11eb-9763-0ffed48fe715.png)

![image](https://user-images.githubusercontent.com/38400135/112157264-713f8480-8bbd-11eb-8726-318e91a1e5d8.png)

![image](https://user-images.githubusercontent.com/38400135/112157635-cb404a00-8bbd-11eb-8a35-e6d3b0416d2a.png)

**Additional context**
GLPI v9.5.3 bugfixed
FormCreator v2.11.1

Thanks
Francois

**Comment by btry** [comment]
Hi

Please try the version 2.11.2 to check if this still occurs. If you have a testing environment available, you may try the branch support/2.11.0 which contains other fixes, not released yet (even better to see if the bug is already solved).

**Comment by fralla2** [comment]
I will configure my testing environment and report back to you this afternoon.
Thanks
Francois

**Comment by fralla2** [comment]
Edit : I will test tomorrow. The test server config took longer than expected. 

Francois

**Comment by fralla2** [comment]
After testings, it's been fixed on 2.11.2. Sorry for the inconveniences
