### ISSUE TITLE
Problème affichage champs masqué

### ISSUE THREAD

**Issue by mgallais76** [pluginsGLPI/formcreator#2188]
Bonjour,

Nous utilisons des champs descriptions pour donner plus d'information sur des sélections. Ces champs sont affiché ou masqué suivant la sélection effectuée.
Lorsque nous faisons un preview, ou remplissons le formulaire, tout se comporte normalement. Par contre à la création du formulaire celui-ci affiche tous les champs descriptions et même ceux masqués. Cela fonctionné dans la version précédente que nous avions.
Nous sommes en :
 GLPI : 9.5.3
FormCreatior : 2.11.2

**Expected behavior**
Est-il possible de ne pas affiché les champs masqué dans les formulaires créés.

**Screenshots**
Création de formulaire
![image](https://user-images.githubusercontent.com/38419829/112192374-3104f400-8c07-11eb-9ad7-a0c0070107aa.png)
![image](https://user-images.githubusercontent.com/38419829/112192477-424e0080-8c07-11eb-847f-070252bf07f1.png)
Formulaire crée
![image](https://user-images.githubusercontent.com/38419829/112192610-67db0a00-8c07-11eb-9679-c898e1c302e0.png)

**Additional context**
N'hésitez pas à me contacter si vous voulez plus de détails

**Comment by btry** [comment]
Bonjour

Si les champs masqués sont affichés sans respect de leur condition vous avez probablement une erreur HTTP. Ouvrez les outils de développeur de votre navigateur, puis reproduisez le problème.

Dans l'onglet "Réseau" de vos outils de développeur vous trouverez la liste des requêtes HTTP effectuées. Une d'elle est sur formcreator/ajax/showfields.php

Vérifiez le code de réponse HTTP et le body de la réponse (à la recherche d'une erreur PHP qui polluerait le JSON.

**Comment by mgallais76** [comment]
Bonjour,

Je viens de vérifier, et je n'ai d'erreur liée au fichier formcreator/ajax/showfields.php.
De ce que j'ai pu constater, sur la création d'un formulaire, j'ai bien l'appel a l'ajax showfields.php en xhr avec un status 200.
Par contre, sur l'affichage des formulaires existants, aucun appel showfields.php n'est effectué.

Cordialement,

**Comment by btry** [comment]
Bonjour

Je pense que le fix ci dessus devrait  résoudre le souci. Merci de me faire un retour.

**Comment by mgallais76** [comment]
Bonjour,

Je viens de faire la modification, j'ai toujours le même problème.
Toujours aucun appel showfields.php n'est effectué.

**Comment by btry** [comment]
C'était une tentative en lien avec un fix fait il y a quelques jours. J'ai effectivement reproduit, mais les conditions sont différentes.

Annulez la modification, téléchargez le patch à nouveau. Je l'ai mis à jour. Il n'y aura pas d'appel à showfield.php à vérifier; la visibilité doit être prise en compte au moment d'afficher les réponses.

**Comment by mgallais76** [comment]
Bonjour,

Je viens d'effectuer les modifications. On y est presque, les options cachés sont cachés, par contre, nous avons d'autres champs non masqué qui n'apparaisse plus et de gros vide ou il y a des champs masqués. 
Je mets des captures ci-dessous :
Création Formulaire : 
![image](https://user-images.githubusercontent.com/38419829/112330845-b4cae900-8cb8-11eb-8658-49e5517bc149.png)
![image](https://user-images.githubusercontent.com/38419829/112330857-b7c5d980-8cb8-11eb-9f8b-c3f9814e90fa.png)
Formulaire Crée
![image](https://user-images.githubusercontent.com/38419829/112330964-cca26d00-8cb8-11eb-9724-e03802983c23.png)
![image](https://user-images.githubusercontent.com/38419829/112330976-d035f400-8cb8-11eb-856e-9ac236cca56b.png)

**Comment by mgallais76** [comment]
Par ailleurs, les checkbox apparaissent maintenant dans le formulaire crée de la manière ["info1";"info2";"infoX"]. et non plus sous la forme de Checkbox

**Comment by btry** [comment]
Avant votre retour j'ai fait une modification. Ls espaces entre les questions ne devraient plus apparaître. Mettez votre patch à jour. 

Je doute que ça change quelque chose pour les cases à cocher.

Apparemment vous avez des sections qui sont complètement vides.  Ont elles des conditions pour les masquer ?

**Comment by mgallais76** [comment]
En effet, les espaces ont été supprimés.

J'ai des conditions sur les sections qui sont liée à des checkbox. 
Par contre, j'ai pu remarque que d'autres sections liée à des radio button s'affiche correctement.
Je pense que le problème est liée à restitution des checkbox.

**Comment by btry** [comment]
Je pense que ce souci de conditions avec les checkboxes n'est ps lié à ce ticket. Pouvez vous ouvrir un autre ticket pour cela ?

Ce ticket peut être fermé: j'ai eu l'occasion d'observer le bug ailleurs et de vérifier que le patch fonctionne.

**Comment by mgallais76** [comment]
Bonjour,

J'ai crée un nouveau ticket pour les problèmes des Checkbox.
Je ferme donc ce ticket
