### ISSUE TITLE
Filtre LDAP

### ISSUE THREAD

**Issue by Pierre-TRO** [pluginsGLPI/formcreator#219]
Bonjour,
Tout d'abord merci pour cet excellent plugin de GLPI.
Je souhaite faire apparaitre dans un formulaire le nom et le prénom de l'utilisateur en cours. Je crée donc une question de type "Liste LDAP" avec pour attribut "(LDAP) Common Name" et dans le filtre je met "(&(objectClass=user))". Malheureusement, la liste déroulante est vide. Je pense que le filtre est mauvais. Pouvez-vous m'aider svp?
Merci.

**Comment by achekmez** [comment]
My filter in quastion is 
(& (samaccountname=*) (&(objectCategory=person)(objectClass=user)))
and it works

**Comment by btry** [comment]
Hi 

I close this issue as it is stalled for years.
