### ISSUE TITLE
Cases à cocher vides après refus

### ISSUE THREAD

**Issue by Pant0ufle** [pluginsGLPI/formcreator#2190]
Bonjour,

Je me permet de faire une remontée de problème :

Après qu'un valideur ai refusé un formulaire, les cases à cocher choisies deviennent vides.

OS : Debian 10 64 bits
GLPI : 9.5.4
FormCreator : 2.11.2

**Comment by btry** [comment]
Hi

Try the above fix and feedback.

**Comment by btry** [comment]
Hi

The PR solved #2193. then I merged it. Having no feedback, I assume this issue can be closed as well.

**Comment by Pant0ufle** [comment]
Hello,

Thanks for your feedback.

Sorry I'm not used to github yet.

How can I update version 2.11.2 to 2.11.3 ?

**Comment by btry** [comment]
Hi

The version 2.11.3 is not released yet.

You need to download the patch from the PR (direct link https://patch-diff.githubusercontent.com/raw/pluginsGLPI/formcreator/pull/2196.diff) and apply it using the patch tool.

To apply a patch locate in the directory of Formcreator,  then run the command ```patch -p1 --dry-run < /path/to/file.diff```. The file file.diff is the patch you previously downoaded. Patch will simulate its job to test if the file will apply without conflict. If the command does not return any error then you can repeat it without the argument --dry-run to actually apply the file to the source code.
