### ISSUE TITLE
Problème champs conditionné avec des Checkbox

### ISSUE THREAD

**Issue by mgallais76** [pluginsGLPI/formcreator#2193]
**Describe the bug**
Bonjour,

Nous avons un problème d'affichage des conditions utilisant des CheckBox. En effet, lors de la création d'un formulaire ou le preview les conditions fonctionne, les champs masqués utilisant la validation ou non de checkbox fonctionne correctement. Par contre lors de l'affichage du Formulaire créé, les champs masqués ne sont pas affichés, même si la condition est remplis.

**To Reproduce**
Voici l'export du formulaire de test
[export_formcreator_20210325_0926.zip](https://github.com/pluginsGLPI/formcreator/files/6203111/export_formcreator_20210325_0926.zip)

**Expected behavior**
Nous devrions avoir le même visuel lors de la création du formulaire que lors de l'affichage du formulaire créé.

**Screenshots**
Création d'un formulaire
![image](https://user-images.githubusercontent.com/38419829/112442735-75e67300-8d4c-11eb-869b-35df88507674.png)
Affichage du formulaire créé
![image](https://user-images.githubusercontent.com/38419829/112442962-acbc8900-8d4c-11eb-9e24-bd1fc1353ad8.png)

**Desktop (please complete the following information):**
Server :
Windows 2016
GLPI 9.5.3
FormCreator 2.11.2

**Additional context**

**Comment by btry** [comment]
Bonjour

Quand vous modifiez des réponses dans le formulaire le navigateur envoie une requête au serveur GLPI pour évaluer les conditions et en déduire la visibilité des questions, sections et bouton envoyer. Utilisez les outils de développeur pour surveiller les  requêtes HTTP vers showfields.php. Quel est le code de retour HTTP ? Il doit être 200. 

Si vous avez le mode debug de GLPI activé, essayez de le désactiver pour voir su l'erreur persiste. Si elle disparait, je pense qu'il y a des warnings PHP qui polluent le JSON retourné par showfields.php. Vous trouverez dans les logs de GLPI les erreurs avec leur backtrace.

**Comment by mgallais76** [comment]
Bonjour,

Que le mode debug soit activé ou non, j'ai le même problème. Je viens de vérifier avec les outils de développeur, et je n'ai pas d'erreur dans les requêtes. le code retour http est 200.

**Comment by btry** [comment]
Bonjour

Je vais tenter de reproduire. En attendant, essayez le patch #2196 : Il résout un autre problème qui m'a été remonté ces derniers jours sur les checkboxes. Il y a une probabilité qu'il contribue à résoudre votre problème également.

**Comment by mgallais76** [comment]
Bonjour,

Le patch  #2196  a corrigé le problème.
vous pouvez clôre l'issue.

Merci pour votre support et votre réactivité.,

**Comment by btry** [comment]
Merci pour votre retour.
