### ISSUE TITLE
Problem validate form

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2194]
Hi
I'm contacting you for a problem of sending email when I accept the request made via the form

Error when i accept or refuse:
```
PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php at line 1021
Uncaught Exception TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php at line 1536
```

the email is well present in the queues
![image](https://user-images.githubusercontent.com/17006344/112482346-40577f00-8d78-11eb-8116-30e168cad6c1.png)

Php error
![image](https://user-images.githubusercontent.com/17006344/112482684-9d533500-8d78-11eb-94c5-5b5358a16295.png)

[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/6205061/php-errors.log)

Thanks

**Comment by btry** [comment]
Hi

A few months ago I had a few feedbacks similar to the PHP errors you shared. Please check the tables of Formcreator in the database.

The following tables may show missing column show_rule:
- glpi_plugin_formcreator_questions
- glpi_plugin_formcreator_sections
- glpi_plugin_formcreator_forms

This is very likely an upgrade issue; but I don't have any proof that the issue is caused by a bug in the upgrade code of the plugin. If you have ability to replay an upgrade to your version of Formcreator, this would be interesting to do it a few times to check the upgrade process.

**Comment by btry** [comment]
Also, please tell the exact version of Formcreator you're using. I need this to gather information from the backtrace.

**Comment by Riesuu** [comment]
Hi, OK I check it tomorrow or Monday. I use the latest version v2.11.2.

**Comment by btry** [comment]
Hi

 I'm suspecting that the table **glpi_plugin_formcreator_sections** does not contains the column show_rule.

If yes, I need confirmation that long ago Formcreator was upgraded from a version < 2.9.0.

**Comment by Riesuu** [comment]
Hi,
sorry i was very busy.
![image](https://user-images.githubusercontent.com/17006344/112985206-3068e200-9160-11eb-8bb8-b1341356a190.png)


bests regards

**Comment by btry** [comment]
Ok, this table is ok, I wanted to check the possible relation with an other issue.

You should find a complete backtraces for all your errors in glpi/files/_logs/php-errors.log and sql-errors.log (same folder).

Please isolate the entries related to this issue then share them.

**Comment by Riesuu** [comment]
phperror:
![image](https://user-images.githubusercontent.com/17006344/112988860-9c4d4980-9164-11eb-9914-46d29ec62638.png)
![image](https://user-images.githubusercontent.com/17006344/112988938-b129dd00-9164-11eb-82ba-7f3522375e19.png)

sql-error, just this:
![image](https://user-images.githubusercontent.com/17006344/112989243-fc43f000-9164-11eb-9f85-d607d1c44605.png)

**Comment by btry** [comment]
Hi

The backtrace for the SQL error is incomplete. I cannot determine if Formcreator is involved.

**Comment by btry** [comment]
The 2nd screenshot show an error which should be solved by this fix https://github.com/pluginsGLPI/formcreator/pull/2169.

**Comment by Riesuu** [comment]
Hi,
thanks for the fix, i have apply it.

php-error:
```
[2021-03-31 15:58:08] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2256@sai-glpi-prd-01"} 
[2021-03-31 15:58:17] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php at line 1021
  Backtrace :
  inc/commondbtm.class.php:1568                      PluginFormcreatorFormAnswer->post_updateItem()
  plugins/formcreator/front/formanswer.form.php:54   CommonDBTM->update()
  
[2021-03-31 15:58:17] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php at line 1536
  Backtrace :
  plugins/formcreator/inc/formanswer.class.php:1536  array_keys()
  plugins/formcreator/inc/formanswer.class.php:893   PluginFormcreatorFormAnswer->deserializeAnswers()
  ...r/inc/notificationtargetformanswer.class.php:69 PluginFormcreatorFormAnswer->getFullForm()
  inc/notificationtarget.class.php:1269              PluginFormcreatorNotificationTargetFormAnswer->addDataForTemplate()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:107        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:184                NotificationEventAbstract::raise()
  plugins/formcreator/inc/formanswer.class.php:1207  NotificationEvent::raiseEvent()
  plugins/formcreator/inc/formanswer.class.php:1041  PluginFormcreatorFormAnswer->sendNotification()
  inc/commondbtm.class.php:1568                      PluginFormcreatorFormAnswer->post_updateItem()
  plugins/formcreator/front/formanswer.form.php:54   CommonDBTM->update()
```

I have no log sql
![image](https://user-images.githubusercontent.com/17006344/113156644-78f4ce00-923a-11eb-8900-4984a2ffe99d.png)

**Comment by btry** [comment]
Hi

Try the patch #2201 It should solve your issue. Don't forget to feedback.

**Comment by Riesuu** [comment]
Hi,
it work ! thanks! But i have a new problem now.
My notification does not display the form anymore, before the fix it worked
![image](https://user-images.githubusercontent.com/17006344/113288231-f843d980-92ee-11eb-9d06-39f27a19810b.png)
![image](https://user-images.githubusercontent.com/17006344/113288394-3214e000-92ef-11eb-816c-3209979cf146.png)

**Comment by btry** [comment]
Then the fix is not good.

Is your 1st screenshot an example of email notification BEFORE the fix ?

**Comment by Riesuu** [comment]
No it was after.
Below is the image before the fix
![image](https://user-images.githubusercontent.com/17006344/113297121-8a9daa80-92fa-11eb-8d28-4999860106ca.png)

**Comment by btry** [comment]
Ok,

A part of the form is generated anyway, I guess there is a problem to compute visibility of sections ans questions.

Can you tell more about the line you blurred in this comment https://github.com/pluginsGLPI/formcreator/issues/2194#issuecomment-811846863 ? Does it contains the label and the answer of a question ?

**Comment by Riesuu** [comment]
It contains the link to go to the form
![image](https://user-images.githubusercontent.com/17006344/113304057-f20b2880-9301-11eb-83f2-8d604115d0dd.png)

**Comment by btry** [comment]
I tried to reproduce, and on my side, email notification is properly generated. I used a real life form with many questions and visibility conditions.

Can you check in the notification queue the content of an email notification ? You can see here the simple text and the HTML version of the email.

**Comment by Riesuu** [comment]
Hi,
form is empty
![image](https://user-images.githubusercontent.com/17006344/113386400-77d2b680-938a-11eb-8f5d-fd812fb1eb63.png)

**Comment by btry** [comment]
Hi

Can you do the following tests

- create a form with only 1 question, answer it and see if the notification is correct.
- remove the patch and run the above form again to see if the notification is now OK.
- after those 2 tries, check the file sql-errors.log.

I believe (no proof yet)  that the fault occurs in PluginFormcraetorFormAnswer::getFullForm(). Maybe there is a SQL error.

Apply the patch below, and run any form to generate a notification. A SQL query will be saved in the file sql-errors.log. Retrieve it and show it. You may also execute it to see the results.

```diff
diff --git a/inc/formanswer.class.php b/inc/formanswer.class.php
index bf8bf64a..c75a5180 100644
--- a/inc/formanswer.class.php
+++ b/inc/formanswer.class.php
@@ -929,6 +929,7 @@ class PluginFormcreatorFormAnswer extends CommonDBTM
             "$questionTable.col *ASC",
          ],
       ]);
+      Toolbox::logSqlError($questions->getSQL());
       $last_section = -1;
       while ($question_line = $questions->next()) {
          // Get and display current section if needed
```

The SQL query looks like the following


```sql

SELECT `glpi_plugin_formcreator_sections`.`name` AS `section_name`, 
`glpi_plugin_formcreator_questions`.`id`, 
`glpi_plugin_formcreator_questions`.`fieldtype`, 
`glpi_plugin_formcreator_questions`.`plugin_formcreator_sections_id` 
FROM `glpi_plugin_formcreator_questions` 
INNER JOIN `glpi_plugin_formcreator_sections` ON (`glpi_plugin_formcreator_questions`.`plugin_formcreator_sections_id` = `glpi_plugin_formcreator_sections`.`id`) 
WHERE (`glpi_plugin_formcreator_sections`.`plugin_formcreator_forms_id` = '32') 
GROUP BY `glpi_plugin_formcreator_questions`.`id` 
ORDER BY `glpi_plugin_formcreator_sections`.`order` ASC, 
`glpi_plugin_formcreator_sections`.`id` ASC, 
`glpi_plugin_formcreator_questions`.`row`, 
`glpi_plugin_formcreator_questions`.`col`  
```

**Comment by Riesuu** [comment]
I think you will hate me, I had deleted $sectionFk = PluginFormcreatorSection::getForeignKeyField(); and not   $formFk = PluginFormcreatorForm::getForeignKeyField(); 

Actually it works with the #2201 
sorry again and thank you.

**Comment by btry** [comment]
OK, this may happen :D 

Next time use the patch tool to apply fixes. This is safer. Here is its documentation : https://linux.die.net/man/1/patch .

I merge the fix for the next release.
