### ISSUE TITLE
Ticket ne se créé pas (renvois vers une page blanche)

### ISSUE THREAD

**Issue by Tartiflette-debug** [pluginsGLPI/formcreator#2195]
Je rencontre un soucis depuis la mise à jour de mon GLPI vers la version 9.5.3.
En effet, je ne peux plus créer de ticket via le plugin Form Creator et ce, quelque soit le formulaire choisi. 

Lorsque je sélectionne l'un de mes formulaires, j'inscris une demande et que je clique sur "Envoyer", celui-ci reste bloqué sur la page suivante: form.form.php, une page blanche..
Le ticket n'est évidemment pas créé.

Auriez-vous une idée sur le problème ?

Voici quelques images illustrant le problème : 
https://i.ibb.co/0BVXjGd/1.png
https://i.ibb.co/NYF263t/3.png

LOGS:
Dans /var/www/html/glpi/files/_log/php-errors.log j'ai :

`[2021-03-26 11:16:36] glpiphplog.CRITICAL:   *** Uncaught Exception Xylemical\Expressions\LexerException: Unable to tokenize string. in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php at line 51
  Backtrace :
  ...dor/xylemical/php-expressions/src/Parser.php:63 Xylemical\Expressions\Lexer->tokenize()
  plugins/formcreator/inc/fields.class.php:336       Xylemical\Expressions\Parser->parse()
  plugins/formcreator/inc/fields.class.php:166       PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/fields.class.php:176       PluginFormcreatorFields::{closure}()
  plugins/formcreator/inc/formanswer.class.php:1166  PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/formanswer.class.php:684   PluginFormcreatorFormAnswer->validateFormAnswer()
  inc/commondbtm.class.php:1102                      PluginFormcreatorFormAnswer->prepareInputForAdd()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()
`

Et dans /var/www/html/glpi/files/_log/sql_errors.log J'ai ceci :

`[2021-03-03 14:23:58] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_targets_actors` (`actor_role`, `actor_type`, `actor_value`, `use_notification`, `uuid`, `itemtype`, `items_id`) VALUES ('3', '9', '106', '1', 'b5c8e5a5-91f5039d-5f75c3538f8068.83920049', 'PluginFormcreatorTargetTicket', '4')
  Error: Table 'GLPI_DATA.glpi_plugin_formcreator_targets_actors' doesn't exist
  Backtrace :
  inc/dbmysql.class.php:1127                         
  ...ins/formcreator/install/upgrade_to_2.11.php:265 DBmysql->insert()
  ...ins/formcreator/install/upgrade_to_2.11.php:158 PluginFormcreatorUpgradeTo2_11->migrateTargetTicket_Actor()
  plugins/formcreator/install/install.php:139        PluginFormcreatorUpgradeTo2_11->upgrade()
  plugins/formcreator/install/install.php:107        PluginFormcreatorInstall->upgradeOneStep()
  plugins/formcreator/hook.php:48                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:726                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"2@SRVGLPI","mem_usage":"0.000\", 3.84Mio)"} `

GLPI: 9.5.3
Form Creator: 2.11.0
OS: Debian 10 (BUSTER)
Browser: Chrome et Firefox

**Comment by btry** [comment]
Bonjour

Upgradez à Formcreator 2.11.2 et voyez si le bug persiste. Si il persiste, prenez un environnement de tests et essayez la dernière révision de la branche support/2.11.0 . 

J'attends votre retour; à priori votre problème est dans l'évaluation d'une condition.

**Comment by Tartiflette-debug** [comment]
> Bonjour
> 
> Upgradez à Formcreator 2.11.2 et voyez si le bug persiste. Si il persiste, prenez un environnement de tests et essayez la dernière révision de la branche support/2.11.0 .
> 
> J'attends votre retour; à priori votre problème est dans l'évaluation d'une condition.

Bonjour,

J'ai essayé avec la version la plus récente, et il semblerai que cette solution soit pire, le bouton "Envoyer" n'est plus présent lorsque je passe en version 2.11.2...

Je suis actuellement en test sur une VM, je reviens vers vous pour les résultats

**Comment by btry** [comment]
Bonjour

J'attends votre retour sur la dernière révision de la branche support/2.11.0. Je pense que le problème va persister. Sachant que le problème vient de l'évaluation d'une condition, essayez de créer un formulaire minimaliste pour reproduire le souci. Sinon, envisagez d'envoyer un export de votre formulaire, si aucune donnée sensible ne s'y trouve.

**Comment by btry** [comment]
Bonjour

Vous pouvez exporter des formulaires en affichant la liste des formulaires. A gauche de chaque ligne vous avez uen case à cocher pour faire des actions massives. Sélectionnez votre formulaire, puis cliquez sur le bouton "Actions". Une fenêtre modale va apparaître. Choisissez "exporter" dans la dropdown, et vous serez invités à  télécharger un fichier (en format JSON).

Déposez le ici en PJ, peut être qu'il faudra le renommer en .txt.

**Comment by Tartiflette-debug** [comment]
Merci, voilà un exemple, un de mes formulaires pour une demande "quelconque" :

[export_formcreator_20210331_1552.txt](https://github.com/pluginsGLPI/formcreator/files/6237074/export_formcreator_20210331_1552.txt)

**Comment by stdglpi** [comment]
Bonjour, 

Je suis sur une version GLPI 9.5.4 et le plugin formcreator 2.11.12 et je rencontre exactement le même soucis.
Une fois le formulaire complété on est redirigé vers une page blanche avec ce lien.

![image](https://user-images.githubusercontent.com/63521311/113929782-bafcb180-97f0-11eb-8eb6-6860cfa31dbb.png)

**Comment by btry** [comment]
Bonjour

@Tartiflette-debug : le formulaire ne contient aucune condition, ce qui est inattendu. Vous confirmez qu'aucun élément du formulaire n'a de condition ?

**Comment by btry** [comment]
Bonjour
J'ai testé le formulaire, tout fonctionne correctement, aucune exception.

Dans le fichier formcreator/vendor/xylemical/php-expressions/src/Lexer.php ligne 51, ajoutez le code suivant

```php
            \Toolbox::logError("Formcreator debug: " . $regex);
            \Toolbox::logError("Formcreator debug: " . $string);
```

Le résultat doit ressembler à ceci

```php
        // Check that we have matched all the tokens in the string.
        if (!preg_match_all($regex, $string, $matches, PREG_SET_ORDER)) {
            \Toolbox::logError("Formcreator debug: " . $regex);
            \Toolbox::logError("Formcreator debug: " . $string);
            throw new LexerException('Unable to tokenize string.');
        }
```

Ensuite reproduisez à nouveau. Il doit y avoir des entrées de log supplémentaires dans php-errors.log.

**Comment by Tartiflette-debug** [comment]
Bonjour,
Qu'entendez-vous par "condition" ?

php-errors.log :
```
[2021-04-08 09:27:54] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 51
Formcreator debug: #(?:(?<!\d)-?\d+(?:\.\d+)?|\*|\/|\%|\-|\+|>=|==|!=|<=|<|>|AND|OR|NOT|MIN|MAX|\(|\)|,)#i  {"user":"152@SRVGLPI"} 
[2021-04-08 09:27:54] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 52
Formcreator debug:   {"user":"152@SRVGLPI","mem_usage":"0.000\", 3.70Mio)"} 
[2021-04-08 09:28:00] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 51
Formcreator debug: #(?:(?<!\d)-?\d+(?:\.\d+)?|\*|\/|\%|\-|\+|>=|==|!=|<=|<|>|AND|OR|NOT|MIN|MAX|\(|\)|,)#i  {"user":"152@SRVGLPI"} 
[2021-04-08 09:28:00] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 52
Formcreator debug:   {"user":"152@SRVGLPI","mem_usage":"0.000\", 3.70Mio)"} 
[2021-04-08 09:28:02] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 51
Formcreator debug: #(?:(?<!\d)-?\d+(?:\.\d+)?|\*|\/|\%|\-|\+|>=|==|!=|<=|<|>|AND|OR|NOT|MIN|MAX|\(|\)|,)#i  {"user":"152@SRVGLPI"} 
[2021-04-08 09:28:02] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 52
Formcreator debug:   {"user":"152@SRVGLPI","mem_usage":"0.000\", 3.70Mio)"} 
[2021-04-08 09:28:04] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 51
Formcreator debug: #(?:(?<!\d)-?\d+(?:\.\d+)?|\*|\/|\%|\-|\+|>=|==|!=|<=|<|>|AND|OR|NOT|MIN|MAX|\(|\)|,)#i  {"user":"152@SRVGLPI"} 
[2021-04-08 09:28:04] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 52
Formcreator debug:   {"user":"152@SRVGLPI","mem_usage":"0.000\", 3.70Mio)"} 
[2021-04-08 09:28:05] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 51
Formcreator debug: #(?:(?<!\d)-?\d+(?:\.\d+)?|\*|\/|\%|\-|\+|>=|==|!=|<=|<|>|AND|OR|NOT|MIN|MAX|\(|\)|,)#i  {"user":"152@SRVGLPI"} 
[2021-04-08 09:28:05] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 52
Formcreator debug:   {"user":"152@SRVGLPI","mem_usage":"0.000\", 3.70Mio)"} 
[2021-04-08 09:28:09] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 51
Formcreator debug: #(?:(?<!\d)-?\d+(?:\.\d+)?|\*|\/|\%|\-|\+|>=|==|!=|<=|<|>|AND|OR|NOT|MIN|MAX|\(|\)|,)#i  {"user":"152@SRVGLPI"} 
[2021-04-08 09:28:09] glpiphplog.ERROR: Xylemical\Expressions\Lexer::tokenize() in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php line 52
Formcreator debug:   {"user":"152@SRVGLPI","mem_usage":"0.000\", 3.72Mio)"} 
[2021-04-08 09:28:09] glpiphplog.CRITICAL:   *** Uncaught Exception Xylemical\Expressions\LexerException: Unable to tokenize string. in /var/www/html/glpi/plugins/formcreator/vendor/xylemical/php-expressions/src/Lexer.php at line 53
  Backtrace :
  ...dor/xylemical/php-expressions/src/Parser.php:63 Xylemical\Expressions\Lexer->tokenize()
  plugins/formcreator/inc/fields.class.php:336       Xylemical\Expressions\Parser->parse()
  plugins/formcreator/inc/fields.class.php:166       PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/fields.class.php:176       PluginFormcreatorFields::{closure}()
  plugins/formcreator/inc/formanswer.class.php:1166  PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/formanswer.class.php:684   PluginFormcreatorFormAnswer->validateFormAnswer()
  inc/commondbtm.class.php:1102                      PluginFormcreatorFormAnswer->prepareInputForAdd()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()
  

```

**Comment by btry** [comment]
Les conditions sont les expressions qui permettent d'afficher ou non des questions, des sections ou le bouton "envoyer" d'un formulaire. Elles permettent aussi de déterminer si il faut ou pas générer une cible.

**Comment by stdglpi** [comment]
@gitter-badger des news ? merci

**Comment by btry** [comment]
Bonjour

Ajoutez le patch suivant à Formcreator pour enregistrer dans php-errors.log le contenu d'une variable à surveiller.

```diff
diff --git a/inc/fields.class.php b/inc/fields.class.php
index 59cc1880..f9666200 100644
--- a/inc/fields.class.php
+++ b/inc/fields.class.php
@@ -323,6 +323,7 @@ class PluginFormcreatorFields
          $expression[] = $value ? '1' : '0';
       }
       // Drop the first logic operator as it is irrelevant
+      \Toolbox::logError(var_export($expression, true));
       array_shift($expression);
       $expression = implode(' ', $expression);
 
```

Ensuite reproduisez le bug et montre les entrées de log produites par le patch. Si le formulaire contient des conditions, il y aura une entrée par condition.

**Comment by stdglpi** [comment]
@btry merci je fais le test dans la soirée et reviens vers vous.

**Comment by btry** [comment]
Bonjour

Avez vous pu collecter des données supplémentaires à l'aide du patch ?

**Comment by stdglpi** [comment]
@btry Bonsoir, 

chemin : GLPI\plugins\formcreator\inc\fields.class.php

Sur mon instance windows j'arrive à trouver les lignes : 

// Drop the first logic ...

Sur mon instance linux je n'arrive pas à le trouver, pourtant je suis bien en Formcreator dernière version.



cdlt,

**Comment by btry** [comment]
Bonjour

Vérifiez la version de votre  instance linux. Vous êtes peut être en version 2.10 ou inférieure, et donc avec un code qui était très différent. En 2.11 j'ai délégué le calcul des conditions à une librairie tierce pour avoir un code de meilleure qualité et préparer le plugin pour une éventuelle prise en charge de conditions encore plus complexes (parenthèses par exemple)

**Comment by stdglpi** [comment]
Bonsoir @btry 

Je suis bien en Formcreator 2.11 (la dernière)

j'ai ajouté en PJ le fichier situé à l'endroit suivant : /var/www/glpi/plugins/formcreator/inc
[fields.class.php.zip](https://github.com/pluginsGLPI/formcreator/files/6331965/fields.class.php.zip)

Pouvez vous jeter un coup d'œil ?

merci

Cordialement,

**Comment by btry** [comment]
Bonjour @stdglpi 

Dans l'entête du fichier je vois un copyright 2019. Il y a parfois un délai conséquent avant la mise à jour de l'entête, mais voir 2019 me laisse penser que le fichier n'est pas récent.

En tout cas le code où insérer la ligne de débug n'est pas présent. Je pense que vous êtes avec une version (très ?) inférieure à 2.11.0

**Comment by Tartiflette-debug** [comment]
@btry Bonjour, veuillez m'excuser, j'étais en cours la semaine passée
Lorsque j'ajoute ces lignes-ci, mon formulaire n'apparait plus correctement. (il affiche seulement le titre du formulaire, les questions n'apparaissent pas)..

**Comment by btry** [comment]
Il n'y a qu'une ligne à ajouter; les autres servent à repérer où l'insérer. Il faut utiliser l'outil patch (https://linux.die.net/man/1/patch) pour insérer ou retirer des modifications dans le code. C'est plus sûr.

Si une page parait incomplete vous avez sûrement une erreur  fatale quelque part, vous trouverez le backtrace correspondant et l'erreur dans les logs du serveur HTTP.

**Comment by stdglpi** [comment]
@btry 

Je vais le réinstaller manuellement avec la dernière version et je vous fait un retour dans la soirée.
Merci

**Comment by stdglpi** [comment]
@btry Bonsoir

Après réinstallation du plugin manuellement voici ce que j'obtiens en ajoute la ligne de code.

/var/www/glpi/files/_log/php-errors.log

[2021-04-19 22:17:14] glpiphplog.CRITICAL:   *** Uncaught Exception Xylemical\Expressions\LexerException: Unable to tokenize string. in /var/www/glpi/marketplace/formcreator/vendor/xylemical/php-expressions/src/Lexer.php at line 51
  Backtrace :
  ...dor/xylemical/php-expressions/src/Parser.php:63 Xylemical\Expressions\Lexer->tokenize()
  marketplace/formcreator/inc/fields.class.php:336   Xylemical\Expressions\Parser->parse()
  ...place/formcreator/inc/formanswer.class.php:1168 PluginFormcreatorFields::isVisible()
  ...tplace/formcreator/inc/formanswer.class.php:684 PluginFormcreatorFormAnswer->validateFormAnswer()
  inc/commondbtm.class.php:1132                      PluginFormcreatorFormAnswer->prepareInputForAdd()
  marketplace/formcreator/front/form.form.php:142    CommonDBTM->add()

**Comment by btry** [comment]
Bonjour

La ligne de debug n'a apparemment pas été exécutée. 

Il pourrait y avoir un lien avec une expression de condition vide, mais je n'ai pas réussi à reproduire. Essayez quand même le fix proposé ci dessus, et faites moi un retour. Je retarde la release 2.11.3 pour inclure la solution à ce problème.

**Comment by Tartiflette-debug** [comment]
@btry 
Bonjour,
Merci beaucoup, ça fonctionne avec ce fix, de mon côté ! Le ticket se créé bien, plus de problème de page blanche

**Comment by btry** [comment]
Bonjour

Merci pour ce retour.

Je pourrais ajouter ce fix dans le code, mais d'abord j'aimerais comprendre comment on arrive à votre situation. 

Je suis maintenant sûr que le bug vient d'une expression de condition vide. Or cela ne devrait pas se produire car si il n'y a pas d'expression de condition, il n'y a aucune évaluation de condition à faire.

Avez vous la possibilité de vérifier en BDD si un élément du formulaire concerné contient des conditions ? 

Les conditions sont dans la table glpi_plugin_formcreator_conditions, et les lignes sont associées au formulaire, aux sections, questions ou cibles via les colonnes itemtype et items_id. Il y a peut être une condition qui fait référence à une question qui n'existe pas.

Pour cela la requête suivante permettra de trouver une incohérence.

```sql
select id FROM glpi_plugin_formcreator_conditions WHERE plugin_formcreator_questions_id not in (select id from glpi_plugin_formcreator_questions);
```

Si tout va bien, la requête ne devrait retourner aucune ligne. Si quelque chose ne va pas les lignes forment une liste des id à examiner.

**Comment by stdglpi** [comment]
Bonjour @btry 

j'ai essayé de passer le fix à chaud 651efd4 ainsi que 21a2128 puis tenter un formulaire mais même résultat.
Je n'ai pas pu reboot GLPI également mais je pense qu'il n'y a pas besoin.

Merci pour votre temps.

**Comment by btry** [comment]
Bonjour @stdglpi 

Les 2 commits que vous avez tenté d'appliquer ne sont pas les définitifs. Il faut prendre la derni-re version de la PR. Son unnique commit est : f2be0f43020ece44054f3180642f3b28fd731322. 

Formcreator est écrit en PHP, il n'y a donc pas besoin de relancer le serveur HTTP pour prendre en compte les changements.

**Comment by stdglpi** [comment]
> Bonjour @stdglpi
> 
> Les 2 commits que vous avez tenté d'appliquer ne sont pas les définitifs. Il faut prendre la derni-re version de la PR. Son unnique commit est : [f2be0f4](https://github.com/pluginsGLPI/formcreator/commit/f2be0f43020ece44054f3180642f3b28fd731322).
> 
> Formcreator est écrit en PHP, il n'y a donc pas besoin de relancer le serveur HTTP pour prendre en compte les changements.

Bonjour,

Du coup après avoir appliqué le fix f2be0f4 je n'ai pas eu de changement.
Neamoins j'avais un formulaire plus récent que les autres qui lui passé étrangement.

Dans la partie "cible" celui ci se transformait comme TICKET avec les mêmes paramètres que les autres..
J'ai testé plusieurs choses mais je n'ai pas réussi à isoler le problème.

J'ai donc cloner celui qui passait et j'ai recréer mes 10 formulaires.

merci

**Comment by btry** [comment]
Bonjour

Même "punition" que @Tartiflette-debug : si vous avez encore les formulaires posant problème, il faut regarder en BDD si il y a une incohérence.

**Comment by stdglpi** [comment]
Bonsoir @btry 

ça me semble correct de mon côté !

![image](https://user-images.githubusercontent.com/63521311/116005913-5c656f00-a609-11eb-9a65-f65ba154dd89.png)

Je peux néamoins vous envoyez un formulaire qui ne fonctionne pas si vous le souhaitez.

cordialemnt,

**Comment by stdglpi** [comment]
D'ailleurs je ne sais pas si je dois créer une autre "issue" mais lorsque je duplique certains formulaires j'ai une page blanche avec "massive action" qui apparait et qui est peut être lié.

En passant GLPI en mode debug j'ai l'erreur suivante : 

![image](https://user-images.githubusercontent.com/63521311/116009867-1534a980-a61c-11eb-8548-d197e4f654b1.png)

![image](https://user-images.githubusercontent.com/63521311/116009875-2087d500-a61c-11eb-97e6-a7187a84f67c.png)


merci

**Comment by btry** [comment]
Bonjour

> Je peux néamoins vous envoyez un formulaire qui ne fonctionne pas si vous le souhaitez.

Oui, ça peut donner une indication sur la source du problème. 


> D'ailleurs je ne sais pas si je dois créer une autre "issue" mais lorsque je duplique certains formulaires j'ai une page blanche avec "massive action" qui apparait et qui est peut être lié.

Il faut ouvrir un ticket séparé. Pour le moment, ça semble être un problème distinct.

**Comment by btry** [comment]
Bonjour

 Le correctif a été ajouté dans la release 2.11.3 livrée aujourd'hui. Je ferme, le problème semblant être résolu.
