### ISSUE TITLE
EVO ? Utilisateur/demandeur par defaut

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2198]
Lors de la creation d'un ticket via form, ce ticket peut etre fait pour soi-meme, ou pour quelqu'un.

Si je mets une question utilisateur/demandeur (objet glpi) il serait pratique que ce champ utilisateur (donc demandeur) soit par defaut positionné à la valeur de celui qui crée le formulaire, soit l'auteur.
Il permettrait ainsi de pouvoir le laisser apr defaut à soi, ou de choisir donc une autre personne.

peut etre meme chose en case de choix utilisateur/demandeur par Ldap...

Merci

**Comment by btry** [comment]
Bonjour

Il est compliqué de gérer les utilisateurs via une question de type LDAP. Formcreator n'a pas les fonctionnalités nécessaires pour cela, et ce n'est pas prévu à ce jour. Vous devez importer vos utilisateurs avec la synchronisation de GLPI et utiliser des questions type Objet GLPI / Utilisateur.

Mettre une option pour préselectionner l'utilisateur courant est compliqué car le type de question est d'une certaine manière générique. On choisit un sous-type qui peut être Utilisateur, Entité, etc. Ce type de choix par défaut ouvrirait la voie à de trop nombreuses options, rendrait le code beaucoup plus compliqué qu'il ne l'est déjà, et rendrait plus difficile la prise en main du plugin.  Le plugin s'enrichit très vite et on atteint un stade où il faut réfléchir au rapport complexité (du code et d'utilisation) / fonctionnalité. Je pense qu'il vaut mieux contourner le besoin de la manière suivante (je le vois déjà assez souvent), avec 2 questoins :


Radios : "Ce formulaire est il pour un autre utilisateur ?" (Oui / Non)
Glpi Object / User : "Utilsiateur"

Quand le demandeur choisit "Oui" alors la question de type Objet GLPI / Utilisateur s'affiche. Cette question alimente les demandeurs du ticket cible.

**Comment by EC2311** [comment]
OK, bonne astuce en effet.
Il me semble que dans les champs on peut recuperer (peut etre ) l'auteur du formulaire.

**Comment by btry** [comment]
Le seul endroit où vous pouvez utiliser l'auteur des réponses est dans les acteurs des tickets ou changements cibles. C'est cet acteur qui est présent par défaut dans un ticket cible fraîchement créé.

**Comment by EC2311** [comment]
je l'ai mis au niveau demandeur, choix d'apres question.
![image](https://user-images.githubusercontent.com/42341169/112837174-d69ee400-909b-11eb-8db2-15cfc6daa094.png)
Le but étant que le demandeur 'initial' soit prevenu de la dépose d'une demande en son nom.
Je pense que cela devrait fonctionner ;)

**Comment by btry** [comment]
Je confirme, ça doit fonctionner.

**Comment by EC2311** [comment]
Je vous tiens au courant
En tout cas Merci !

**Comment by btry** [comment]
Bonjour

A défaut de retour je considère le sujet comme résolu. Je ferme.
