### ISSUE TITLE
Liste déroulante Validation Group dans création formulaire (Form Creator)

### ISSUE THREAD

**Issue by RdENIM** [pluginsGLPI/formcreator#220]
Bonjour à vous,

Lorsque je souhaite choisir un groupe lors de la création / modification d'un formulaire (Form Creator), dans la liste déroulante permettant de choisir le / les groupes je n'en vois que 4, même si potentiellement il y en a plus de disponible.

Version de GLPI :  0.90.3
Version de Formcreator : 0.90-1.3.3

Cordialement,

René Danilo

**Comment by orthagh** [comment]
bonjour @RdENIM 

Je viens de publier la version 1.3.4 du plugin qui corrige un certain nombres de problèmes (environ 60 corrections effectuées)
Pouvez-vous la télécharger, l'installer et vérifier si votre bug persiste ou non.

Merci d'avance.

**Comment by RdENIM** [comment]
Rebonjour,

J'ai installé la version 1.3.4. Effectivement je vois maintenant plus de groupe (dans certains plusieurs fois d'ailleurs). Je vous joins une copie d'écran.

Pour l'autre ticket 221, J'ai refait des tests complémentaires du coup. J'ai le même problème. Je mets à jour ce ticket avec les tests complétés avec la version 1.3.4. Le fait d'attribué à un groupe un formulaire nous permet en interne dans notre organisation de gérer les absences pour être sûr que quelqu'un va valider le formulaire pour générer le ticket et qu'il soit traité, et cela ne fonctionne pas.  c'est très génant.

**Comment by RdENIM** [comment]
[test_formcreator_0.90.1.3.4.docx](https://github.com/pluginsGLPI/formcreator/files/376120/test_formcreator_0.90.1.3.4.docx)

**Comment by RdENIM** [comment]
Bonsoir,

J'ai refait un test en supprimant mes deux utilisateurs et en positionnant un groupe au niveau d'un formulaire déjà existant et il m'a validé les deux groupes identiques (je n'ai pas eu l'anomalie remontée hier). J'imagine que les deux groupes correspondent à mes deux utilisateurs correspondants. J'ai refait un test ensuite entre demandeur et valideur. Lorsque je me connecte à mon compte valideur, je ne vois pas le formulaire à valider. Je suis dans le problème d'origine au niveau des groupes et les formulaires.

En vous remerciant d'avance de votre retour,

Cordialement,

René Danilo

**Comment by orthagh** [comment]
Bonjour @RdENIM 

Je viens de faire un premier correctif au niveau de cette liste.
Pouvez vous tester la version intermédiaire disponible ici : https://github.com/pluginsGLPI/formcreator/archive/master.zip

**Comment by RdENIM** [comment]
Bonsoir à vous,

Je viens de faire un test. S'il y a plusieurs utilisateurs dans le même groupe et même profil potentiel valideur dans la liste déroulante (en modification du formulaire) je vois qu'une seule fois le groupe. C'est ok. C'est la correction que vous avez effectuez ?

Après lorsque je me connecte avec le profil valideur je ne vois pas le  formulaire à valider. (:(

En vous remerciant d'avance pour la suite ...

Cordialement,

René Danilo

**Comment by RdENIM** [comment]
Bonjour à vous,

Je reviens de congés.
Je reviens aux nouvelles car avant que je parte, j'avais toujours un problème sur les validations de formulaire en passant par les groupes.

En vous remerciant d'avance de votre retour,

Cordialement,

René Danilo

**Comment by btry** [comment]
Bonjour

Je voudrais savoir quel type de valideur vous avez configuré dans votre formulaire. Est-ce un utilisateur valideur, ou un groupe valideur ?

Dans la seconde hypothèse, l'utilisateur devant valider la demande est (je suppose) membre du groupe valideur, n'est ce pas ?

**Comment by RdENIM** [comment]
Bonjour à vous,

C’est des utilisateurs « valideurs ». La notion de Groupe Valideur existe ?

Cordialement,

René Danilo, ENIM/SDSI/DIP (Adjoint au Chef du Département des Infrastructures et de la Production)
Ligne directe : 02 97 64 79 23
[cid:image001.jpg@01CEB2FC.60884890][cid:image002.jpg@01CEA7E6.57ECDAA0]
N’imprimez ce mail qu’en cas de nécessité

De : btry [mailto:notifications@github.com]
Envoyé : lundi 5 septembre 2016 14:27
À : pluginsGLPI/formcreator
Cc : DANILO René; Mention
Objet : Re: [pluginsGLPI/formcreator] Liste déroulante Validation Group dans création formulaire (Form Creator) (#220)


Bonjour

Je voudrais savoir quel type de valideur vous avez configuré dans votre formulaire. Est-ce un utilisateur valideur, ou un groupe valideur ?

Dans la seconde hypothèse, l'utilisateur devant valider la demande est (je suppose) membre du groupe valideur, n'est ce pas ?

**Comment by RdENIM** [comment]
Bonjour à vous,

C’est des utilisateurs « valideurs » dans un groupe simple.
C'est à dire que si au lieu de prendre un groupe de valideurs, je prends mes deux utilisateurs de test qui sont valideur, cela fonctionne. Si je mets mes deux utilisateurs dans un groupe et que je paramètre mon formulaire avec ce groupe, je ne vois pas les formulaires à valider avec ces utilisateurs.

La notion de Groupe Valideur existe ? Si oui comment paramétrer cela ?

En vous remerciant d'avance de votre retour,

Cordialement,

René Danilo

**Comment by btry** [comment]
Ce que j'appelle un groupe valideur est ce que vous avez décrit et que je reprends ci dessous: 

> Si je mets mes deux utilisateurs dans un groupe et que je paramètre mon formulaire avec ce groupe, je ne vois pas les formulaires à valider avec ces utilisateurs.

![image](https://cloud.githubusercontent.com/assets/14139801/18248518/f211bec8-7378-11e6-8be4-f74839bb7508.png)

J'ai posé cette question car j'ai remarqué la même chose que vous. Je comptais sur votre retour pour confirmer qu'il s'agit d'un bug. C'est chose faite :) 

Sa correction va nécessiter un certain soin, donc je vous invite pour le moment à énumérer un à un les utilisateurs habilités à valider votre formulaire, jusqu'à ce que le correctif soit créé et publié.

**Comment by btry** [comment]
Note : il me semble que votre ticket #221 concerne exactement ce problème, n'est ce pas ?

**Comment by RdENIM** [comment]
Bonsoir à vous,

Merci à vous. Pour le #221 oui c'est bien la même chose.

Oui effectivement au moment de faire le formulaire, il faut choisir un des utilisateurs. Par contre si cette personne est absente, elle ne peut pas le valider (et pour cause, c'est pour cela que la notion de groupe nous intéresse beaucoup.). Le Demandeur du formulaire n'aurait pas moyen de modifier cet utilisateur valideur et le remplacer par un autre, s'il aperçoit que la personne choisit préalablement est absente ? 

En vous remerciant d'avance de votre retour,

Cordialement, 

René Danilo

**Comment by btry** [comment]
Merci, donc comme le problème initial de ce ticket semble résolu, je vais le fermer. L'autre sera plus clair pour suivre l'avancement des travaux sur ce bug.
