### ISSUE TITLE
Type "Sélection LDAP" ne fait rien/fonctionne pas

### ISSUE THREAD

**Issue by Ragzer** [pluginsGLPI/formcreator#2200]
Bonjour, 

J'ai un soucis avec le type/champ "Sélection LDAP" dans la création de formulaire. Quand je le sélectionne, il ne se passe rien (Le Type passe bien sur "Sélection LDAP" mais le reste de l'interface ne change pas et reste identique au dernier type sélectionné).
Voici un exemple où le précédent type était "Objet GLPI":
![image](https://user-images.githubusercontent.com/26622796/112839762-d3f1be00-909e-11eb-92c4-57436699d9c0.png)

Tout mes autres types fonctionnent correctement.
Il me semble que la sélection LDAP s'affichait correctement avant que je configure l'annuaire LDAP début Mars (annuaire qui fonctionne correctement).

J'ai mis à jour formcreator avec la version la plus récente aujourd'hui mais cela n'a pas résolu mon problème. Je tourne sous glpi 9.5.4.

Merci pour votre aide

**Comment by btry** [comment]
Bonjour

Avec la branche de maintenance support/2.11.0 le type de question semble se comprter comme prévu.

Ouvrez les outils de développement de votre navigateur, essayez de créer une question de type LDAP, et voyez dans la console si il y a des erreurs javascript ou des requêtes XHR en erreur (onglet réseau).

Ensuite vérifiez les logs de GLPI (php-errors.log et sql-errors.log). Enfin, si vous avez des erreurs HTTP 500, vous trouverez des backtraces dans les logs du serveur HTTP (apache, nginx, ...)

**Comment by CireSacud26** [comment]
Bonjour,
Est-ce que par hasard vos formulaires qui contiennent une question "selection LDAP" sont créés avec la récursivité d'entité (sous-entités = Oui) comme je le décris ici : https://github.com/pluginsGLPI/formcreator/issues/2209 ?

**Comment by btry** [comment]
Bonjour

Suivez les instructions que j'ai mises dans  #2209.
