### ISSUE TITLE
Atualização do FormCreator para 2.11.2 - Erro nos formulários customizados

### ISSUE THREAD

**Issue by WeronicaSS** [pluginsGLPI/formcreator#2206]
Após atualização do plugin FormCreator para a versão 2.11.2, os chamados que são abertos estão com o campo "Data de abertura" em branco, e o GLPI mostra a seguinte mensagem de erro durante a abertura do chamado: 

"Erro: Pelo menos um campo possui valor incorreto: Data de abertura"

English : After updating the FormCreator plugin to version 2.11.2, the tickets that are opened have a blank "Opening date" field, and the GLPI shows the following error message when opening the ticket:

"Error: At least one field has an incorrect value: Opening date"

![image](https://user-images.githubusercontent.com/33072477/114190164-6147d480-9921-11eb-860e-b72eaf686d65.png)

Além disso, o chamado criado não fica visível para o usuário:
English: In addition, the created ticket is not visible to the user:
![image](https://user-images.githubusercontent.com/33072477/114190500-bf74b780-9921-11eb-93c9-990e05b2f05b.png)

Na versão versão 2.10 do FormCreator, esse problema não ocorria. Como é possível corrigir isso no GLPI, usando a nova versão do plugin?
English: In version 2.10 of FormCreator, this problem did not occur. How is it possible to correct this in GLPI, using the new version of the plugin?

**Comment by btry** [comment]
Hi

Please use english instead. I had to use a translator to understand the request.

**Comment by btry** [comment]
I need details about the Opening date question. Is it a date or a datetime question ?

**Comment by WeronicaSS** [comment]
É o campo "Data de abertura" existente dentro do chamado, na aba "Chamado", conforme print a seguir:

![image](https://user-images.githubusercontent.com/33072477/114217078-1b4d3980-993e-11eb-8775-074b787af87f.png)

**Comment by btry** [comment]
Hi

I don't reproduce the bug. Which version of GLPI are you using ?

Disable all plugins except Formcreator, then try to reproduce again.

**Comment by WeronicaSS** [comment]
Uso a versão 9.5.2 do GLPI:

![image](https://user-images.githubusercontent.com/33072477/114394090-2f2cb180-9b71-11eb-9bf0-1eb12c1ed387.png)


Desabilitar os demais plugins, não resolveu o problema do plugin FormCreator.

**Comment by btry** [comment]
Do the form use a ticket template ? If yes, check if the ticket template contains a default value for a date.

**Comment by WeronicaSS** [comment]
Deu certo!

Eu verifiquei que as categorias dos formulários estavam atreladas a um modelo de chamado. Dentro do modelo de chamado, a data de abertura estava predefinida, conforme o print abaixo:

![image](https://user-images.githubusercontent.com/33072477/114431994-8729df00-9b96-11eb-9a36-cbb49e2a2f2a.png)

Então, eu removi essa predefinição e verifiquei que todos os problemas citados anteriormente, foram resolvidos! 

Caminho realizado no GLPI:
Home >> Asssistência >> Chamados >> Modelos de chamados >> Alterei o modelo que estava sendo utilizado

Muito obrigada pela ajuda @btry!
Thank you very much!

**Comment by btry** [comment]
Hi

Great. I can close now. Thank you for your feedback.

Special thanks to an online translator :).
