### ISSUE TITLE
ID formulaire incorrect

### ISSUE THREAD

**Issue by khblkhivygiyfg** [pluginsGLPI/formcreator#2208]
**Describe the bug**
Bonjour,
Je reviens vers vous (https://github.com/pluginsGLPI/formcreator/issues/2129) pour un nouveau problème très dérangeant.

Certaines personnes, pas toutes, lors de la création d'un ticket via formulaire n'auront pas le bon ID de ticket: L'ID du ticket ne correspond pas avec celui du formulaire:

_Le ticket est créé (non visible dans "mes demandes d'assistance", uniquement mode tech ou admin)
_Si je clique sur le message en bas a droite lors de la création du ticket via formulaire (votre ticket a été enregisté (ticket : xxxx), j'arrive sur une page qui m'annonce que j'ai pas les droits requis.
_si je renseigne l'ID (1318 comme dans le screenshot) dans en mode admin, j'arrive bien sur mon ticket. MAIS si je renseigne l'ID du formulaire, j'arrive soit sur rien, soit sur un ticket déjà fait d'une autre personne.

J'ai vraiment l'impression que c'est le reglage "ID ticket <==> ID Formulaire" qui foire.
Je suis en environnement de test pour le moment, mais le formulaire doit normalement être rapidement mis en prod une fois ce problème réglé.

Auriez-vous une idée ?

Cordialement.

**Screenshots**

![2021-04-12 13_41_35-GLPI - Catalogue de service - Chromium](https://user-images.githubusercontent.com/79261815/114390452-96109180-9b96-11eb-9d9d-29a4c71edfca.png)
![2021-04-12 13_41_44-GLPI - Catalogue de service - 1241 - Chromium](https://user-images.githubusercontent.com/79261815/114390439-914bdd80-9b96-11eb-8ccb-5ecf9b301c6b.png)

**Others informations:**
GLPI 9.5.3 sous Proxmox
PHP8
Nginx
Formcreator 2.11.2

**Comment by btry** [comment]
Bonjour

Quand vous listez des demandes d'assistance dans le catalogue de service les ID sont préfixés d'un T ou d'un F, selon qu'il s'agit d'un ticket ou d'une réponse à un formulaire. 

Les lignes dont l'ID commence par T correspond à des tickets. Vous pouvez utilsier le nombre pour retrouver le ticket dans GLPI. Dans les cas où l'ID commence par F, le nombre correspond à une réponse à un formulaire. Les ID de ticket et de réponse à un formulaire ne sont pas interchangeables, il n'y a pas de correspondance. 

Dans votre cas le formulaire a généré immédiatement un ticket numéro 1318. Vérifiez que ce ticket est dans une entité accessible par le demandeur, avec le bon profil (si il en a plusieurs). Si le ticket n'est pas visible, il y a des chances que l'entité ne soit pas accessible, et donc cliquer sur le lien aboutit à un refus d'affichage.

**Comment by khblkhivygiyfg** [comment]
Re-Bonjour

En effet, on avaient des tech' en self-service ET admin pour une entité, alors que d'autre n'avait que le profil Admin (ce qui semblait suffisant jusqu’à maintenant). En ajoutant ces tech' en self-service, la listes de tous les anciens tickets de tests sont enfin apparus, et les tickets on bien le bon ID.

Encore merci à vous pour la rapidité et précision.
