### ISSUE TITLE
[2.11.2] Selection d'objets GLPI et LDAP KO si récursivité d'entités

### ISSUE THREAD

**Issue by CireSacud26** [pluginsGLPI/formcreator#2209]
Bonjour,

Avant d'installer la dernière version 2.11.2 de FormCreator sur mon GLPI de production (v9.5.4), je le teste sur une plateforme clonée. Je constate que les questions de type dropdown "Selection LDAP" ou "Objet GLPI" ne fonctionnent plus si le formulaire est créé avec l'option "Sous-entités" = Oui.

Si on modifie cette option à Non. Les dropdown refonctionnent, quelque soit l'entité d'accueil du formulaire (racine ou sous-entités).

**Pour reproduire**
1. Création d'un formulaire vierge sous l'entité racine (ou n'importe quelle sous-entité de la racine) avec l'option "Sous-entités" = Oui
2. Création d'une section vierge "Test"
3. Création d'une question "Test LDAP" avec
type = "Selection LDAP"
choix de l'annuaire
champ obligatoire = Non
afficher une valeur vide = Oui
filtre = (& (samaccountname=*) (&(objectClass=user)(objectCategory=person)))
attribut = (AD) Nom affiché

Condition d'affichage = Toujours afficher

4. Dans la prévisualisation du formulaire, le dropdown pour la question "Test" affiche le message "les résultats ne peuvent pas être chargés"

5. En ne modifiant que la portée du formulaire Sous-entité = Non, le dropdown de la question "Test" fonctionne

Le phénomène se reproduit à l'identique pour les autres type questions basées sur des requêtes d'objets en dropdown comme les objets GLPI.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 1903
 - Browser : Firefox 87.0 x64

Cordialement,
Eric

**Comment by btry** [comment]
Bonjour

Mettez sur votre GLPI le patch suivant : https://github.com/glpi-project/glpi/pull/8834/files ou bien upgradez à GLPI 9.5.5 .

Ensuite annulez le patch suivant dans Formcreator: https://github.com/pluginsGLPI/formcreator/pull/2164/files

**Comment by CireSacud26** [comment]
Bonjour,

J'ai suivi les instructions et je confirme cela fonctionne.

Merci !

**Comment by btry** [comment]
Bonjour

Merci pour le retour. GLPI 9.5.5 est sorti, et il y aura très bientôt une version 2.11.3 de Formcreator. Avec cette combinaison, les patchs ne seront plus nécessaires.
