### ISSUE TITLE
Errors log : "Missing type for Ticket template!"

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#2210]
issue reported in GLPI : https://github.com/glpi-project/glpi/issues/8418

**Comment by btry** [comment]
Cannot investigate without a complete backtrace (see the backtrace shared in the linked issue)

**Comment by phamorais** [comment]
@btry Hi !

follow last 50 lines in backtrace

  plugins/formcreator/inc/formanswer.class.php:1001  PluginFormcreatorFormAnswer->generateTarget()
  inc/commondbtm.class.php:1173                      PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()

[2021-04-13 18:46:23] glpiphplog.WARNING:   *** PHP User Warning (512): Missing type for Ticket template! in /home/paulo/myglpi/glpi/inc/commonitilobject.class.php at line 7957
  Backtrace :
  inc/commonitilobject.class.php:7957                trigger_error()
  inc/commonitilobject.class.php:7918                CommonITILObject->getTemplateFieldName()
  inc/commonitilobject.class.php:792                 CommonITILObject->getITILTemplateToUse()
  inc/ticket.class.php:974                           CommonITILObject->handleTemplateFields()
  inc/commondbtm.class.php:1484                      Ticket->prepareInputForUpdate()
  inc/ticket.class.php:2332                          CommonDBTM->update()
  inc/commonitilactor.class.php:382                  Ticket->updateDateMod()
  inc/group_ticket.class.php:66                      CommonITILActor->post_addItem()
  inc/commondbtm.class.php:1173                      Group_Ticket->post_addItem()
  inc/commonitilobject.class.php:1969                CommonDBTM->add()
  inc/ticket.class.php:1924                          CommonITILObject->post_addItem()
  inc/commondbtm.class.php:1173                      Ticket->post_addItem()
  plugins/formcreator/inc/targetticket.class.php:808 CommonDBTM->add()
  plugins/formcreator/inc/formanswer.class.php:816   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:1001  PluginFormcreatorFormAnswer->generateTarget()
  inc/commondbtm.class.php:1173                      PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()

[2021-04-13 18:48:08] glpiphplog.WARNING:   *** PHP User Warning (512): Missing type for Ticket template! in /home/paulo/myglpi/glpi/inc/commonitilobject.class.php at line 7957
  Backtrace :
  inc/commonitilobject.class.php:7957                trigger_error()
  inc/commonitilobject.class.php:7918                CommonITILObject->getTemplateFieldName()
  inc/commonitilobject.class.php:792                 CommonITILObject->getITILTemplateToUse()
  inc/ticket.class.php:974                           CommonITILObject->handleTemplateFields()
  inc/commondbtm.class.php:1484                      Ticket->prepareInputForUpdate()
  inc/ticket.class.php:2332                          CommonDBTM->update()
  inc/commonitilactor.class.php:382                  Ticket->updateDateMod()
  inc/group_ticket.class.php:66                      CommonITILActor->post_addItem()
  inc/commondbtm.class.php:1173                      Group_Ticket->post_addItem()
  inc/commonitilobject.class.php:1969                CommonDBTM->add()
  inc/ticket.class.php:1924                          CommonITILObject->post_addItem()
  inc/commondbtm.class.php:1173                      Ticket->post_addItem()
  plugins/formcreator/inc/targetticket.class.php:808 CommonDBTM->add()
  plugins/formcreator/inc/formanswer.class.php:816   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:1001  PluginFormcreatorFormAnswer->generateTarget()
  inc/commondbtm.class.php:1173                      PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()

[2021-04-13 18:50:32] glpiphplog.DEBUG: Html::compileScss() in /home/paulo/myglpi/glpi/inc/html.class.php line 7505
css/palettes/automn.scss is new, loading  {"user":"6@myserver"}
[2021-04-13 18:50:32] glpiphplog.DEBUG: Html::compileScss() in /home/paulo/myglpi/glpi/inc/html.class.php line 7505
css/dashboard.scss is new, loading  {"user":"6@myserver"}
[2021-04-13 18:50:32] glpiphplog.DEBUG: Html::compileScss() in /home/paulo/myglpi/glpi/inc/html.class.php line 7505
css/styles.scss is new, loading  {"user":"6@myserver"}


And "**Also, please confirm that the ticket being created has a group in the actors. It seems this is important to reproduce**."

the ticket was actually opened without assigning the group or technician


![image](https://user-images.githubusercontent.com/35368369/114702808-ea348680-9cfa-11eb-8902-f3753c7aac93.png)


I´m GLPI 9.5.5 and Formcreator 2.11.2

**Comment by btry** [comment]
Thank you for your information, but so far I could not reproduce.

The backtrace shows that a relation between a group and the ticket is involved in the bug, and adding a group to  the target ticket is not sufficient to generate the error.

Can you show the definition of the actors of the target ticket in Formcreator ? If there are no group added here, can you tell how the group is added to the ticket (ticket template, business rule)  ?

**Comment by phamorais** [comment]
OIa @btry 

Follow the print of the "target"

![image](https://user-images.githubusercontent.com/35368369/114722224-fe36b300-9d0f-11eb-97a7-73f05600dcdb.png)

In the environment, the attribution of the Technician or Group to the ticket is used by means of the rule in "ITIL Category" and "Rules of the entity"

1 - I set up the automatic assignment of technicians or groups through ITIL Categories. For that I need to go to the entity configuration and select the option below

![image](https://user-images.githubusercontent.com/35368369/114724461-f2e48700-9d11-11eb-8312-42d1a8ba8b18.png)


2 - First I create the ITIL Category and inform which group will attend the ticket

![image](https://user-images.githubusercontent.com/35368369/114724210-b57ff980-9d11-11eb-954c-f87dd6eb654c.png)

3 - When I create the form, select only the category in the "target"

![image](https://user-images.githubusercontent.com/35368369/114724528-05f75700-9d12-11eb-9fbb-7ce25cfeb599.png)

**Comment by btry** [comment]
Hi

I created an ITIL category with a group in charge of the ticket, then configured the entity to automatically assign the ticket based on the category.

Running a test form runs without error, then I still don't reproduce. I notice that in your screenshots, the group in charge of the hardware is added in the requesters, instead of the assigned (like it is expected and i observe on my own instance).

**Comment by phamorais** [comment]
@btry sorry for delay!

Sorry I did not understand the problem in the statement:
"... I notice that in your screenshots, the group in charge of the hardware is added in the requesters, instead of the assigned (like it is expected and i observe on my own instance)."

See the behavior below in my production instance with GLPI 9.5.4 and Form 2.11.2

![image](https://user-images.githubusercontent.com/35368369/115155296-9f49a480-a055-11eb-84b6-e86c4dea6d24.png)

![image](https://user-images.githubusercontent.com/35368369/115155302-abcdfd00-a055-11eb-959b-8e3d6ef06f8e.png)
![ticket_open](https://user-images.githubusercontent.com/35368369/115155450-678f2c80-a056-11eb-9fc4-d18d774a325a.gif)

See that the ticket opens without errors, and I have the same configuration in the ITIL Category

![image](https://user-images.githubusercontent.com/35368369/115155549-ea17ec00-a056-11eb-9176-faf9bb9ae22b.png)

Targets in Form

![image](https://user-images.githubusercontent.com/35368369/115155579-0caa0500-a057-11eb-8340-cadd88b8db21.png)

**Comment by stdglpi** [comment]
Same error for me (GLPI 9.5.5 with Formcreator 2.11.2

When I'm writing a solution just after "Error 500" and in the Php-errors.log

[2021-04-19 22:34:16] glpiphplog.WARNING:   *** PHP User Warning (512): Missing type for Ticket template! in C:\inetpub\wwwroot\GLPI 9.5.5\inc\commonitilobject.class.php at line 7957
  Backtrace :
  inc\commonitilobject.class.php:7957                trigger_error()
  inc\commonitilobject.class.php:7918                CommonITILObject->getTemplateFieldName()
  inc\commonitilobject.class.php:792                 CommonITILObject->getITILTemplateToUse()
  inc\ticket.class.php:974                           CommonITILObject->handleTemplateFields()
  inc\commondbtm.class.php:1484                      Ticket->prepareInputForUpdate()
  inc\itilsolution.class.php:372                     CommonDBTM->update()
  inc\commondbtm.class.php:1173                      ITILSolution->post_addItem()
  front\itilsolution.form.php:57                     CommonDBTM->add()

i'm using ITIL Category for the tickets.

**Comment by phamorais** [comment]
@btry I update in another GLPI instalation.. with GLPI 9.5.5 and Form 2.11.3, and de the error still the same :(

**Comment by btry** [comment]
Hi

The original issue on GLPI is reopened because it seems to also occur with the mail collector. We are currently missing data to find the cause of the problem.

**Comment by phamorais** [comment]
@btry I can provide ssh access to a test environment for you to access.

**Comment by phamorais** [comment]
@btry 
We were partners through Oriontech, but it is in renegotiation.

Anyway, if you want to analyze the incident just let me know. Until then, I will keep pausing the update of the environment.

**Comment by stdglpi** [comment]
from my side the problem start to occur since the GLPI update 9.5.4 to 9.5.5.
Also I always use the mail collector to create my tickets. 

This problem happens when I try to : 

- Transfert a ticket to another Entitie
- Solve a ticket

Have a good day

**Comment by btry** [comment]
Hi

Thank you @stdglpi  for those useful  information.

**Comment by btry** [comment]
Hi

A fix for GLPI was found. Closing this issue.
