### ISSUE TITLE
Liaison FormCreator 2.11.2 avec autre plugin

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2213]
Bonjour

Initialement j'etais en version 2.10.4 et j'avais trouvé l'endroit pour ajouter les liens avec plugin Database etc.
( source dans glpiselectfield.class.php, j'ajoutais dans la ligne 64 
Appliance::class		=> Appliance::getTypeName(2)],
puis en 74
	     __("Plugins") => [
		PluginDatabasesDatabase::class              => PluginDatabasesDatabase::getTypeName(2),
		PluginArchiswSwcomponent::class  => 	PluginArchiswSwcomponent::getTypeName(2)],

Maintenant en version 2.11.2 : je ne vois pas où je peux les rajouter. 
Dans le meme fichier on trouve une notion de GLPI_OBJECTS, terme que j'ai essayé de rechercher dans les différents sources
mais ma foi... 

> on ne trouve pas la liaison 'native' avec appliance alros que c'est un objet natif de glpi ?

Merci

**Comment by btry** [comment]
Bonjour

C'est par ici : https://github.com/pluginsGLPI/formcreator/blob/support/2.11.0/inc/field/glpiselectfield.class.php#L116

Prenez exemple sur le test d'existence du plugin Appliance. 

L'objet natif a été rajouté, je ne me souviens plus quand. Si il n'est pas dans la version 2.11.2 vous l'aurez très bientôt, puisque j'ai commencé à préparer la version 2.11.3

**Comment by EC2311** [comment]
Bonjour

Merci pour le lien
petites questions : 
- pour ce qui est des appliances  : pourquoi ne pas le mettre en dur dans la partie assets sachant qu'il fait partie du coeur glpi. certes le plugin existe toujours, mais dans ce cas : il n'y aurait pas un risque de doublon dans le menu assets (lignes 116) ?

- Insertion du plugin Databases
      Dans la version précédente de formcreator, j'avais créé un menu 'plugin'
       __("Plugins") => [
            PluginDatabasesDatabase::class              => PluginDatabasesDatabase::getTypeName(2)] 
et cela fonctionnait.

j'ai repris les lignes 'appliances' et modifié comme ci-dessous
if ((new Plugin())->isActivated('databases')) {
         $optgroup[__("Assets")][PluginDatabasesDatabase::class] = PluginDatabasesDatabase::getTypeName(2) . ' (' . _n('Plugin', 'Plugins', 1) . ')';
      }
-> le menu Database n'apparait pas : je vois bien 'objet glpi' mais pas de case à cote
![image](https://user-images.githubusercontent.com/42341169/114825001-f3d6f080-9dc5-11eb-8d72-395b3bef90d9.png)

aurai-je oublier quelque chose ? certainement...
Merci

**Comment by btry** [comment]
Bonjour

> pour ce qui est des appliances : pourquoi ne pas le mettre en dur dans la partie assets sachant qu'il fait partie du coeur glpi. certes le plugin existe toujours, mais dans ce cas : il n'y aurait pas un risque de doublon dans le menu assets (lignes 116) ?

Les appliances natives de GLPI sont prises en charge par le plugin. Cet ajout a été fait il y a environ 4 mois. Cependant certains utilisent encore le plugin. J'ai donc maintenu la prise en charge du plugin, et le terme "Plugin" est ajouté pour permettre de faire la distinction.


> le menu Database n'apparait pas : je vois bien 'objet glpi' mais pas de case à cote

Vous avez probablement oublié de déclarer l'espace de noms de la classe du plugin. https://github.com/pluginsGLPI/formcreator/commit/e245ba5938ca12e942c4c9e28a645b7ea61eb7e0

**Comment by EC2311** [comment]
Exact !
Désolé, ne connaissant rien en php :(

super et merci bien
