### ISSUE TITLE
Probleme statut "en attente de validation"

### ISSUE THREAD

**Issue by Tijah82** [pluginsGLPI/formcreator#2217]
Bonjour,

J'utilise la version GLPI 9.5.5 et le plugin Formcreator 2.11.2.

Je m'explique 

1) Je créé un formulaire de demande de matériel.
2) Je joue une règle métier pour les tickets en lui demandant d'envoyer une validation au responsable du demandeur si la catégorie est "demande de matériel"

![image](https://user-images.githubusercontent.com/48673805/115263879-16566a00-a136-11eb-8f36-93b95102682a.png)

![image](https://user-images.githubusercontent.com/48673805/115263938-240bef80-a136-11eb-9711-01309f3231ce.png)

Résultat, le ticket est créé et la demande de validation est envoyé.

Le problème est que dans l'interface Formcreator le ticket apparait en tant que "en cours" et non pas en attente de validation alors que le statut de validation dans le ticket est bien en "attente de validation"

![image](https://user-images.githubusercontent.com/48673805/115264237-69302180-a136-11eb-8f0f-53e5a992cc73.png)

![image](https://user-images.githubusercontent.com/48673805/115264346-8238d280-a136-11eb-92bd-05d345b84e15.png)

Quand j'ouvre le ticket via l'interface formcreation on voit bien qu'il y a une demande de validation

![image](https://user-images.githubusercontent.com/48673805/115264537-ac8a9000-a136-11eb-99bf-f552abc791b6.png)

et du coté technicien on voit bien le statut en "en attente de validation"

![image](https://user-images.githubusercontent.com/48673805/115264676-cdeb7c00-a136-11eb-867c-a49b02c8db20.png)

Par contre si je rentre dans le ticket en tant que technicien (sans rien changé) et que je fais "sauvegarder" le statut passe bien en "attente" dans l'interface.

![image](https://user-images.githubusercontent.com/48673805/115264911-05f2bf00-a137-11eb-94a3-50208c864682.png)

![image](https://user-images.githubusercontent.com/48673805/115264978-14d97180-a137-11eb-9d97-0cfd9d682679.png)

![image](https://user-images.githubusercontent.com/48673805/115265073-2a4e9b80-a137-11eb-9be3-4182f59c16ea.png)

Cela est un gros inconvénient car si de notre coté on ne fait pas d'action sur le ticket, le valideur ne voit pas qu'il a un ticket a valider.

Avez vous une idée du pourquoi du comment ?

Merci d'avance.

LG

EDIT : Je précise que j'avais le même soucis avec la version GLPI 9.5.4.

**Comment by Tijah82** [comment]
Je precise que j'avais le meme soucis avec la version GLPI 9.5.4.

**Comment by btry** [comment]
Bonjour

Vérification faite sur la version actuelle du plugin, les changements auxquels j'ai pensé n(touchent au statut résolu des tickets. Ils n'ont pas d'incidence sur votre problème. 

Je mets ce souci en suspens car je suis occupé en ce moment sur une tâche qui touche directement à cela. C'est assez compliqué pour que j'évite de mélanger 2 contextes de code dans ma tête.  Je reviendrai sur votre problème après la release 2.11.3. En attendant, essayons de simplifier le scénatrio au maximum pour le moment où je tenterai de reproduire. Je pense qu'on peut tenter sans aucune question, ni règle métier apr exemple. Si vous voyez d'autres choses inutiles, essayez d'épurer sur une instance de test.

**Comment by Tijah82** [comment]
Bonjour,

Ok je vois mais je suis obligé de passer par une règle pour envoyé automatiquement la demande de validation au responsable du demandeur, il n'y a pas d'autre solution.

Pour le moment je contourne le problème avec une règle SLA en plus qui effectue une action automatique 1min après la création du ticket (ajout du technicien par défaut). De ce fait le ticket passe bien en attente de validation dans l'interface Formcreator.

Je peux donc patienter encore un peu mais mon système n'est une solution viable que sur une courte durée. Je compte sur vous pour régler ce soucis dans la version 2.11.4 ou 2.12 ;)

Merci pour votre retour.

Bonne journée

**Comment by btry** [comment]
Bonjour

La simplification que je vous ai décrite ne concerne que la recherche du bug, à faire sur une instance de tests si vous avez la possibilité d'en avoir une. 

> Je peux donc patienter encore un peu mais mon système n'est une solution viable que sur une courte durée. Je compte sur vous pour régler ce soucis dans la version 2.11.4 ou 2.12 ;)

Pour rappel le support communautaire est fait en best effort. Si vous avez besoin de support professionnel vous pouvez considérer une des offres suivantes  : https://glpi-project.org/fr/support/

**Comment by Tijah82** [comment]
J'ai pas tout compris, enfin j'en ai pas l'impression.

Si je ne mets pas de règle il n'y aura pas de demande de validation donc il ne risque pas d'être en statut "attente de validation".
Si je fais la demande de validation après que le ticket soit créé il n'y a pas de soucis, le statut sera "en attente de validation"

Le problème est que lors de la création du ticket, il ne prends pas en compte la demande de validation immédiatement. Il ne prends pas en compte le "statut de la validation" comme s'il n'y avait aucun argument qui check le statut de validation à la création.

Je ne sais pas si je suis assez clair :)

Et quand je dis "je compte sur vous" c'est en fait un mot d'encouragement et non une obligation.

**Comment by btry** [comment]
> Si je ne mets pas de règle il n'y aura pas de demande de validation donc il ne risque pas d'être en statut "attente de validation".
Si je fais la demande de validation après que le ticket soit créé il n'y a pas de soucis, le statut sera "en attente de validation"

Ce détail est intéressant, en effet. Ca constitue une piste intéressante pour chercher le souci.

> Et quand je dis "je compte sur vous" c'est en fait un mot d'encouragement et non une obligation.

Pas de souci.

**Comment by btry** [comment]
Bonjour

J'ai une incertitude sur la façon d'ajouter un validateur au ticket. Je pense que le fix ci dessus a des chances de résoudre votre probème. Merci de faire un retour.

**Comment by Tijah82** [comment]
Bonjour,

Ok je teste des que possible et vous dit ca.

Merci

**Comment by btry** [comment]
Bonjour


Avez-vous pu tester le correctif ?

**Comment by btry** [comment]
Hi

After deeper tests, it appears that  the fix does not works. I could reproduce and find a working patch (PR updated). Having no feedback, I assume it will work for you.
