### ISSUE TITLE
I need the targets to have included the tittle of the ticket

### ISSUE THREAD

**Issue by DemonOfDarkness** [pluginsGLPI/formcreator#2219]
**Is your feature request related to a problem? Please describe.**

Im trying to organize the tickets that we receive, and i wanted a format of Ticket Type: Question - What does this?
The What does this, or other thing, will be the title that the users send us, so we dont have a lot of the same ticket, more like

Question - What colour is the sky?
Question - Why i dont have internet?
Problem - The office is on fire

**Describe the solution you'd like**
I will like to add or include the tittle or a text that writes the users in the target to see then like that.

**Describe alternatives you've considered**
Select the target like the title for example, will be less organized but is a solution.

**Comment by btry** [comment]
Hi

If you insert a tag in the title of a target ticket, then Formcreator will resolve the tag and make the ticket have a title depending on the answer fivengiven by the requester 

![image](https://user-images.githubusercontent.com/14139801/116047510-6ec8c280-a674-11eb-8e84-632d3c49bdec.png)


![image](https://user-images.githubusercontent.com/14139801/116047653-96b82600-a674-11eb-979a-8294e905c02e.png)

![image](https://user-images.githubusercontent.com/14139801/116047685-a2a3e800-a674-11eb-8515-9841f82e4839.png)

**Comment by DemonOfDarkness** [comment]
Thanks a lot :D

**Comment by btry** [comment]
Hi

 I assume I can close the issue.
