### ISSUE TITLE
[SUGGESTION] Champe "Titre du ticket" égale à la réponse...

### ISSUE THREAD

**Issue by jcovillers78114** [pluginsGLPI/formcreator#2225]
Bonjour,

Est-il envisageable de transformer le champ "Titre du ticket" de l'onglet "cible" par un champ de sélection "égale à la réponse" comme c'est le cas pour les éléments associés par exemple ?
Ca éviterait d'avoir une multitude de tickets avec le même titre, ce qui est plus simple pour l'utilisateur final lorsqu'il recherche une ancienne réponse clôturées.

Merci !

**Comment by btry** [comment]
Bonjour,

Vous pouvez utiliser toutes les balises proposées par Formcreator dans le titre de ticket. Elles seront remplacées de la même manière que dans le contenu du ticket.

**Comment by btry** [comment]
Duplicates #2219

**Comment by jcovillers78114** [comment]
Merci ! C'est exactement ce qu'il me faut et je me doutais bien que l'on pouvait faire ce genre de chose aussi mais je ne vois pas où trouver le N° de balise (181 dans l'exemple) qui correspond à mon champ texte à insérer dans le field "Titre du ticket"

**Comment by btry** [comment]
Quand vous éditez un objet cible, la liste des balises se trouve en bas de la fenêtre modale (pop up).

**Comment by jcovillers78114** [comment]
Effectivement !
C'est pourtant sous mes yeux !

Merci.
