### ISSUE TITLE
KB subject translations not used in FAQ

### ISSUE THREAD

**Issue by vincentdeniau** [pluginsGLPI/formcreator#2226]
**Describe the bug**
We use several KB with two translations (English and French), which are published in the FAQ. On the standard interface, going to _Tools > Knowledge base_ shows the correct language depending on user preferences. On the simplified interface with Form Creator, the FAQ seems to ignore the KB translation and always shows the subject in the default language (the one you set on the Edit tab). However, when you click on the KB entry to see its content, you then access the correct translation.

**To Reproduce**
1. Create and KB with some title and publish it in the FAQ
2. Add a translation (choose any non default language)
3. Change you user preferences to match this language
4. Visit the simplified interface and see the title is not translated

**Expected behavior**
If a translation exists in the user's language, the title of the KB should be translated in the FAQ. 

**Versions**
GLPI 9.5.5 and Form Creator 2.11.2
__

**Comment by btry** [comment]
Hi

Please test the above fix and feedback.

**Comment by vincentdeniau** [comment]
Hello,
The problem is fixed, probably by applying the last update.

**Comment by btry** [comment]
Hi,

Yes, I added the fix I submitted to you in the release. Thank you for your feedback.
