### ISSUE TITLE
[2.11.2] Using duplicate icon on section set the same order value to the new section

### ISSUE THREAD

**Issue by MLOcc** [pluginsGLPI/formcreator#2228]
**Describe the bug**
When using duplicate icon on a section, the new section have the same order value than the duplicated one in glpi_plugin_formcreator_sections.
Sorting sections become impossible or have bad behavior.

**To Reproduce**
Add a section named "section 1"
![image](https://user-images.githubusercontent.com/71837011/116248872-82575480-a76c-11eb-86fa-b41f43d4b9fa.png)
Use duplicate icon and rename new section "section 2"
![image](https://user-images.githubusercontent.com/71837011/116249885-889a0080-a76d-11eb-9e25-4b0cad1d5834.png)
Save
![image](https://user-images.githubusercontent.com/71837011/116249189-d82bfc80-a76c-11eb-9889-224ed94a2851.png)
It's not possible to set "section 2" before "section 1"

Add a new section named "section 3"
![image](https://user-images.githubusercontent.com/71837011/116249485-29d48700-a76d-11eb-9853-2ec6bb590186.png)
Use duplicate icon on "section 3" and rename new section "section 4"
![image](https://user-images.githubusercontent.com/71837011/116249668-57213500-a76d-11eb-81a5-994823bc8509.png)
Save

Set "section 1" order after "section 2" and before "section 3" using arrow icon
![image](https://user-images.githubusercontent.com/71837011/116251093-9ef48c00-a76e-11eb-8741-ed06c0a8236a.png)

Save
![image](https://user-images.githubusercontent.com/71837011/116250367-f47c6900-a76d-11eb-8bee-eadde342c8b8.png)
![image](https://user-images.githubusercontent.com/71837011/116250440-04944880-a76e-11eb-9718-b15417832235.png)
It displays sections 2-3-1-4 instead of 2-1-3-4

**Expected behavior**
When using duplicate icon on section A, the new section B must have set "order of B"="order of A"+1 and all the sections C having their order > "order of A" have to be updated with "order of C"="order of C"+1

Best regards

**Comment by btry** [comment]
Hi

Please test the above fix and feedback.

**Comment by MLOcc** [comment]
Hi,
After testing, I'm OK with this fix.

We have to keep in mind that new sections duplicated are now set in last position, no longer just after the section where we have used the duplicate icon.

Have a good day.

**Comment by btry** [comment]
Hi

having the duplicate just after the original section is a side effect of  the bug. It is expected to have the duplicate at the last position.

I'll merge the patch now, and it will be available in the next release. Thank you for your feedback.
