### ISSUE TITLE
syntax ldap

### ISSUE THREAD

**Issue by flagada97** [pluginsGLPI/formcreator#2231]
Bonjour,

Dans une question sur le formulaire, j'ai sélectionné le type LDAP, Attribut Common Name et dans la values j'ai renseigné cette syntaxe : 
{"ldap_auth":"3","ldap_filter":"(&(memberOf=CN=***,OU=***,OU=Groupes,OU=***,DC=***,DC=***) )","ldap_attribute":"2"}
J'aimerais savoir quelle est la syntaxe LDAP pour rajouter des utilisateurs en plus à cette syntaxe?

Cordialement

**Comment by btry** [comment]
Bonjour

Vous avez besoin d'apprendre la syntaxe des filtres de recherche. Voici un exemple de ressource : http://www.ldapexplorer.com/en/manual/109010000-ldap-filter-syntax.htm

**Comment by flagada97** [comment]
Merci pour le lien.
