### ISSUE TITLE
ISSUE: Objet GLPI --> Utilisateurs

### ISSUE THREAD

**Issue by benshoes** [pluginsGLPI/formcreator#2232]
GLPI 9.5.5
Formcreator 2.11.3

Type: Objet GLPI --> Utilisateurs
Users list is not displayed. 
We see only the users with root abilities
Everything is fine on 2.11.2

Best regards

**Comment by btry** [comment]
Hi

I found a regression compared to v2.11.2. This fix shoud work, assuming that your form has recursivity enabled.

**Comment by btry** [comment]
Hi

HAving no feedback, I close this issue. Duplicates are open for now.
