### ISSUE TITLE
Objet "Ordinateur" non récursif

### ISSUE THREAD

**Issue by Tijah82** [pluginsGLPI/formcreator#2235]
Bonjour,

Dans la nouvelle version lorsqu'on veut choisir un objet GLPI "ordinateur" on ne voit que ceux de l'entité actuelle ou de l'entité parent. On ne voit plus ceux des sous entités. Le champ ne semble plus être récursif.

J'ai du repasser en version 2.11.2 pour ne pas avoir ce soucis.

Je n'ai pas pris de Screenshot avec de revenir en arrière, désolé.

Version utilisé de GLPI, la 9.5.5.

Merci.

**Comment by btry** [comment]
Hi

Try the fix submitted in #2232
