### ISSUE TITLE
PHP Fatal error:  Cannot declare class GlpiPlugin\Formcreator\Command\SyncIssuesCommand, because the name is already in use in syncissuescommand.class.php on line 39

### ISSUE THREAD

**Issue by ftoledo** [pluginsGLPI/formcreator#2236]
**Describe the bug**
formcreator break console scripts 

**To Reproduce**
```
$ php7.4 bin/console
 
GLPI CLI 9.5.5

Usage:
  command [options] [arguments]

Options:
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --config-dir[=CONFIG-DIR]  Configuration directory to use
      --no-plugins               Disable GLPI plugins (unless commands forces plugins loading)
      --lang[=LANG]              Output language (default value is existing GLPI "language" configuration or "en_GB")
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

PHP Fatal error:  Cannot declare class GlpiPlugin\Formcreator\Command\SyncIssuesCommand, because the name is already in use in /home/xxxxxxxx/plugins/formcreator/inc/command/syncissuescommand.class.php on line 39

```

**Expected behavior**
show list of console commands

**Data**
Debian Stretch 
php 7.4
GLPI 9.5.5.
FormCreator 2.11.3

**Comment by btry** [comment]
Hi

Please check if the plugin is installed in the plugins directory and the marketplace directory.

If it is Installed in both, then the determine which one is the most recent version and drop the older one. Use the version constant in setup.php to get the version.

**Comment by ftoledo** [comment]
Exactly. I made the update from the market panel. The plugin updated fine, but I left the version of the old plugins directory.
I think the old version should be removed in this process

**Comment by btry** [comment]
Hi

I'm not sure that installing a plugin from the marketplace should automatically remove the same plugin in the regular directory. In some instances the plugin directory may not allow write access. I believe it would  be  better to give up with admin-friendly error.

Also, the CLI framework should be resilient against this case, as it seems  that al CLI commands are broken, causing significant impact.

**Comment by ftoledo** [comment]
I agree. The core should be able to detect that there are two (or more) duplicate installed plugins and catch that error 
Saludos!

**Comment by cedric-anne** [comment]
Should be fixed by https://github.com/glpi-project/glpi/pull/9053
