### ISSUE TITLE
Looping Form

### ISSUE THREAD

**Issue by stevansantos** [pluginsGLPI/formcreator#2238]
Facing issues with formcreator 2.11.3 and GLPI 9.5.5

When using "`:\`" inside a form question, form is looping everytime after submitting.

I've checked php-errors.log while submitting and it returned no data for this issue.

![2021-05-07_11-20-09](https://user-images.githubusercontent.com/73721973/117466617-4e78ed80-af29-11eb-9e9b-3fbe7490d3b7.gif)

**Comment by btry** [comment]
hi

Please try the fix #2237  and feedback.

**Comment by btry** [comment]
Great! 

Thank you for your feedback
