### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by mihalab** [pluginsGLPI/formcreator#2239]
i have xampp server with php 8.0.3 and formcreator 2.11.3
When i try save question form, server show me error:
Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in C:\xampp\htdocs\glpi\marketplace\formcreator\inc\field\ldapselectfield.class.php at line 241

in https://www.php.net/manual/en/function.ldap-control-paged-result.php was written This function has been DEPRECATED as of PHP 7.4.0, and REMOVED as of PHP 8.0.0

I couldnot find information about compatibility ForrmCreator and php 8

**Comment by btry** [comment]
Hi

The above PR is WIP. You're welcome to try it, but **only** on a testing environment.

**Comment by btry** [comment]
Hi

Can you test the above PR and feedback ?

**Comment by mihalab** [comment]
It works ok, thank you

**Comment by btry** [comment]
Merged. Thank you for your feedback.
