### ISSUE TITLE
Import LDAP Title

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2249]
Hello,
I would like to use the "title" field in my form but it is impossible to save it. 
![image](https://user-images.githubusercontent.com/17006344/119470192-641f4d00-bd48-11eb-9276-3f252fd24f87.png)

![image](https://user-images.githubusercontent.com/17006344/119470293-7e592b00-bd48-11eb-83ca-dd645859db0b.png)

php-error.log:

```
[2021-05-25 10:53:14] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/plugins/formcreator/inc/field/ldapselectfield.class.php at line 240
  Backtrace :
  plugins/formcreator/inc/question.class.php:361     GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  plugins/formcreator/inc/question.class.php:385     PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1110                      PluginFormcreatorQuestion->prepareInputForAdd()
  plugins/formcreator/ajax/question_add.php:43       CommonDBTM->add()
```

**Comment by btry** [comment]
Hi

Which version of PHP are you using ?

**Comment by Riesuu** [comment]
PHP 8.0.3

**Comment by btry** [comment]
Try this patch : https://github.com/pluginsGLPI/formcreator/commit/ca09db9aa9e53908973d6e19f0519b76b8ed23b7

**Comment by Riesuu** [comment]
It work !

many thanks

**Comment by btry** [comment]
Great ! Thank you for your fedback.
