### ISSUE TITLE
Plusieurs notifications identique

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2250]
Bonjour,
j'utilise formcreator pour différents formulaires:

- Création de compte user pour un ERP
   -> Création d'un ticket, la notification du ticket est utilisée.

- Création d'un formulaire de retour de matériel au fournisseur
  -> Utilisation de la notification "nouveau fournisseur responsable" dont le custom a directement été fait sur le modèle de notification présent dans glpi (ticket/nouveau fournisseur responsable)

- Déclaration d'incident des imprimantes au fournisseur
  -> Le problème se pose est que j'ai déjà custom la notification (ticket/nouveau fournisseur responsable).

Pour gérer cette problématique, est ce que je dois modifier le template pour n'afficher QUE ##ticket.description##.. et la suite de la customisation se passe dans les paramètres cible du formulaire?

merci d'avance !

**Comment by btry** [comment]
Bonjour

Formcreator n'a pas le pouvoir de géénrer lui-même le contenu des notifications. 

Peut être que vous pourriez avoir une notification avec un template diférent en jonglant avec les entités de GLPI. Chaque entité peut avoir ses propres notifications (avec des templates diférents).

Votre question concerne l’utilisation du plugin (et de GLPI). Je vous invite à utiliser le forum pour ce type de besoins, et n'utiliser GitHub que pour les sujets relatifs au développement du plugin (bugs, fonctionnalités).

**Comment by btry** [comment]
Bonjour,

Ce ticket étant ancien, je ferme.
