### ISSUE TITLE
Can't see vinculated form answer in a ticket

### ISSUE THREAD

**Issue by GonzaCoding** [pluginsGLPI/formcreator#2252]
**Describe the bug**
When I create a ticket from a Formcreator form, I can't see vinculated form answer.
I can see the register in tables glpi_logs and glpi_items_tickets with itemtype = "PluginFormcreatorFormAnswer", but no one appear in ticket form.

**To Reproduce**
1. Create a new form
2. Set up destination to ticket
3. Answer the form in order to create a ticket

**Expected behavior**
See form answer link in ticket form

**Screenshots**
In GLPI 9.2.2 and Formcreator 2.5.1 I can see:
![image](https://user-images.githubusercontent.com/62549779/119765339-7654d480-be89-11eb-9f2d-20e4520885e8.png)
But now in GLPI 9.4.6 and Formcreator 2.10.4 I can't see:
![image](https://user-images.githubusercontent.com/62549779/119765469-b4ea8f00-be89-11eb-8aaa-36008686a42b.png)

**Desktop (please complete the following information):**
 - OS: Win
 - Browser: Chrome
 - Version:  90.0.4430.212 (Build oficial) (64 bits)

**Comment by btry** [comment]
Hi

First, Formcreator 2.10 is no longer maintained. You're encouraged to upgrade to GLPI 9.5 and Formcreator 2.11.

Please, check that formanswer is added in the helpdesk types list. This is a multiselect input. If I remember well it is in the profile's settings.

**Comment by GonzaCoding** [comment]
@btry I'm upgrading from 9.2 to 9.4, cant go to 9.5 yet.
I believe it's a common function in Formcreator, to link formanswer to ticket.
I can't reach "helpdesk types list", do you remember the table name or the section?
Thanks in advance! Regards,

**Comment by btry** [comment]
> I believe it's a common function in Formcreator, to link formanswer to ticket.

Formcreator creates the link, but GLPI filters the associated items depending on the setting I mentionned.

Check in Administration > Profile > (choose a profile) > tab Assistance > section Association > setting Associable items to a ticket

**Comment by GonzaCoding** [comment]
@btry I've added this association (in super-admin profile, that i'm using):
![image](https://user-images.githubusercontent.com/62549779/119907282-52939c00-bf26-11eb-80ed-adc0d20e45d8.png)
("respuestas al formulario" means "form answers")
But can't see association, neither in new tickets or old ones

I've checked in my old glpi 9.2.2 and formcreator 2.5.1 and this association is not made in any profile

Are there another table to check? (not glpi_logs or glpi_item_tickets) I believe, maybe some plugin is broken other needed association between ticket and form answer.

Thanks!!!

**Comment by GonzaCoding** [comment]
I found this piece of code in Ticket class, showForm method:
![image](https://user-images.githubusercontent.com/62549779/119913879-6e526e80-bf35-11eb-95c6-7f3e676d7eb3.png)
If I change line 5114 to: if($ID) instead of if(!$ID), now I can see associated elements in form:
![image](https://user-images.githubusercontent.com/62549779/119914003-afe31980-bf35-11eb-9f82-2a6da3d0fa82.png)

I don't know if it's a good idea, of it's impact in other pages.
@btry

**Comment by btry** [comment]
Hi

If you changed your own current profile you need to logout then login to refresh your sesion with the new parameters. Formcredator does not adds automatically its itemtype in the associatable items to tickets. Actually, it is generaly useless to access the form answers from a ticket, as the ticket should contain most or all data from the form answer.

The change you did id very likely not good : the ```if ($ID) ``` statement is here to show the associated elements onmy if the ticket exists. If the ticket does not exists then associated elements cannot exist and should not be displayed. This case ocurs when you are on a new ticket form. I recommend you revert this change.

**Comment by GonzaCoding** [comment]
@btry thanks for your answer
I tried to add a new ticket throu ticket form and no problems
Do you know other cases that this change can break?
regards!

**Comment by btry** [comment]
No, I don't see any other impact.

**Comment by btry** [comment]
J'ai trouvé un fix. Essayez-le et faites un retour.

**Comment by btry** [comment]
Hi

This issue is stalled then I assume the problem is solved.
