### ISSUE TITLE
object type users entity

### ISSUE THREAD

**Issue by lovayjano** [pluginsGLPI/formcreator#2254]
**Describe the bug**
I just upgraded our glpi from version 9.4.5 to 9.5.5. The formcreator is also up-to-date: 2.11.4.
I have a question on Questions tab, a list of users.
Type: GLPI object
GLPI object: Administration - Users
If I list the Default values, then everything alright. But when I preview this question and listing it, then I only see users from my entity.
On previous version (glpi 9.4.5 compatible formcreator) everything worked alright.

**Expected behavior**
To list every User.

**Desktop:**
 - OS: Windows10
 - Browser: Firefox
 - Version 88.0.1

**Comment by btry** [comment]
Hi

In formcreator 2.11.0 and later, the restriction by entity is relative to the form's entity. Before this  version, the reference entity was the curent entity of the user. I think that this change is responsible of your problem. You may find more information in the release notes on any version from 2.11.0 to 2.11.4. The release notes will also help you to find  the commit making the change, to revert it, if you need to.

In version 2.12 the plugin will provide a new setting to choose the best behavior, for each question.

**Comment by btry** [comment]
You need to revert this patch : https://github.com/pluginsGLPI/formcreator/pull/2047/files

**Comment by lovayjano** [comment]
thank you very much for the help, that was the problem! :)

have a great day!
