### ISSUE TITLE
Elements not found when we want to access a ticket generated by a multiple target form

### ISSUE THREAD

**Issue by cgrzl** [pluginsGLPI/formcreator#2255]
**Describe the bug** @btry 

Whether in version 9.5.2 with the plugin 2.11.2 or with glpi 9.5.5 and the plugin 2.11.4, I have elements not found when I am with a "helpdesk" profile but with a "central" profile it works normally.

I am on a test version with basic GLPI, a single entity, the default profiles, ...

**To Reproduce**

With a Admin or other profile that can create a form, create a form with multiple targets (that create more than 1 ticket)
With a self service user, answer this form.
Go the the my requests lists and find this answer
Get the tickets list from this answer and try to open the tickets to get the error
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85362794/121210947-64f1cc00-c87c-11eb-8249-3ec7ea6cfad2.png)

**Additional context**

Log Error SQL :

SELECT COUNT(*) AS cpt FROM glpi_items_tickets INNER JOIN glpi_tickets ON (glpi_items_tickets.tickets_id = glpi_tickets.id) WHERE itemtype = 'PluginFormcreatorFormAnswer' AND items_id = '48' AND is_deleted = '0'
Error: Column 'itemtype' in where clause is ambiguous
Backtrace :
inc/dbmysqliterator.class.php:95
inc/dbmysql.class.php:857 DBmysqlIterator->execute()
inc/dbutils.class.php:345 DBmysql->request()
inc/db.function.php:178 DbUtils->countElementsInTable()
inc/ticket.class.php:698 countElementsInTable()
inc/commonglpi.class.php:339 Ticket->getTabNameForItem()
plugins/formcreator/inc/formanswer.class.php:360 CommonGLPI->addStandardTab()
inc/commonglpi.class.php:294 PluginFormcreatorFormAnswer->defineTabs()
ajax/updatecurrenttab.php:46 CommonGLPI->defineAllTabs()

**Comment by btry** [comment]
Hi

Can you apply the following patch on GLPI (not Formcreator), and see if it helps ?

```diff

diff --git a/inc/ticket.class.php b/inc/ticket.class.php
index 6c5a99c557..eeb86da1f2 100644
--- a/inc/ticket.class.php
+++ b/inc/ticket.class.php
@@ -717,7 +717,7 @@ class Ticket extends CommonITILObject {
                                  ]
                               ],
                               'WHERE' => [
-                                 'itemtype' => $type,
+                                 'glpi_tickets.itemtype' => $type,
                                  'items_id' => $tab,
                                  'is_deleted' => 0
                               ]

```

**Comment by btry** [comment]
I had a similar  error in a big SQL request a few weeks ago, and it did not occurred on my computer.

Can you tell the name and the version of your DBMS ?

**Comment by cgrzl** [comment]
@btry I tested with MariaDB 10.3.27 and MySQL 5.7.31

**Comment by btry** [comment]
Hi

Your error should hapen because the column itemtype exists in the 2 tables mentioinned in  the query. The problem is that one of those table does not has such column.

Please show the result of the two following queries

SHOW CREATE TABLE glpi_tickets;
SHOW CREATE TABLE glpi_items_tickets;

Also, the SQL error seems to not be related to the "Item not found" error you have on screen. 

Please describe your tree of entities, and tell in which entity is the user (as displayed on the top right corner), in which entities are the 2 generated tickets, and in which entity is the form.

**Comment by cgrzl** [comment]
@btry Hello, column 'itemtype' exists in glpi_items_tickets : 

![image](https://user-images.githubusercontent.com/85362794/121339393-ba7eb500-c91e-11eb-8e53-1782975ee244.png)

but does not exist in glpi_tickets

I only have one entity so ticket and form user profiles are in the same entity

![image](https://user-images.githubusercontent.com/85362794/121339661-ff0a5080-c91e-11eb-88d5-43ca5ecbc8ab.png)

**Comment by NeyRamon** [comment]
I have the same problem!
I've updated with the patch mentioned above and nothing.

GLPI: 9.5.5 Formcreator: 2.11.4
MariaDB: 10.4.13 PHP 7.3

**Comment by cgrzl** [comment]
@btry When I switch to "Standard interface" it works but to "simplified interface" no.

![image](https://user-images.githubusercontent.com/85362794/121516831-f1240080-c9ee-11eb-9fdb-656abd7bc165.png)

**Comment by btry** [comment]
Hi

I think the SQL error is not related to the error message on screen. This request is used to display associated items to a ticket. If one of you try to disable the block of code in glpi/inc.ticket.class.php the ticket should not show anymore the associated items, and I expect that the error "item not found" will still occur. I would appreciate a feedback to validated my assumption (even if I'm sure about it).

@cgrzl : if I understand well, you can access a ticket (ID 10 or 11) from the standard interface, but not with the simplified one ?

**Comment by cgrzl** [comment]
@btry Yes, with the standard interface I have no problem but it is when I use a profile with a simplified interface or I have this error

**Comment by cgrzl** [comment]
@btry I have deleted the file "ticket.class.php" but the tickets still display the associated elements and the error "elements not found" still appears.

![image](https://user-images.githubusercontent.com/85362794/121549191-ecbb1000-ca0d-11eb-928a-701798b08287.png)

**Comment by NeyRamon** [comment]
That's right!
With the standard interface I have no problem, only with the simplified interface.

**Comment by cgrzl** [comment]
@btry Hello, do you think it is possible to have a "patch" for this bug or it will be necessary to wait for the release of a new version of the plugin? thank you

**Comment by btry** [comment]
Hi

I usually submit a patch to bug requesters to validate it. Sometimes I merge it without validation (when bugs are easy and fix is obvious).

The first screenshot of your bug report mentions that some you don't have right to view all tickets. I think that your issue is a right problem.

For example : the requester of your tickets is **glpi**, I don't know which user and which profile (self-service for sure, but with which rights ?) was used to list the tickets of the form answer.

If you have skills you may run a debug session with a 1st breakpoint in glpi/front/ticket.form.php. I believe the error may be triggered in Ticket::display() method. The implementation is in the class CommonGLPI.

![image](https://user-images.githubusercontent.com/14139801/121819805-6e6da080-cc8f-11eb-8f11-3cebbdae48dc.png)

**Comment by cgrzl** [comment]
I created tickets with the "glpi" user and when I want to view the tickets it is always with the "glpi" user with the "Self-Service" profile who has the rights below.
But I have already tried to check everything on the profiles in all sections and that does not change the problem ...

![image](https://user-images.githubusercontent.com/85362794/121820006-a9bc9f00-cc90-11eb-9933-1a6315a249aa.png)

**Comment by btry** [comment]
Your scenario looks simple, then I think i may succeed to reproduce.

**Comment by cgrzl** [comment]
I tried debugging but I don't have the skills to unfortunately if you need precision to reproduce the scenario do not hesitate, hoping that it is not too complex to solve

**Comment by btry** [comment]
good news : I reproduce

**Comment by btry** [comment]
I found a fix, please test it and feedback.

**Comment by cgrzl** [comment]
@btry Perfect problem solved with the patch, unbelievable thank you very much

**Comment by btry** [comment]
The counters are maintained from the assistance requests table (glpi_plugin_formcreator_issues). You should check the status of the assistance request and see if it consistent against all tickets linked to it.
