### ISSUE TITLE
Saisie de la date : problème avec l'année

### ISSUE THREAD

**Issue by jpclerc** [pluginsGLPI/formcreator#2256]
Bonjour

Suite à la saisie dans un formulaire, nous récupèrons très souvent des erreurs dans le ticket.
En effet, lors de la saisie par exemple de 01-07-98 (date de naissance ou autre), on récupère dans le ticket 01-07-2021

L'année est mise à l'année en cours quand la saisie n'est pas au format AAAA

Serait-il envisageable d'avoir une obligation de formatage au niveau de la saisie pour imposer la saisie de l'année sur 4 caractères ?
Y a-t'il un astuce pour contourner ce fonctionnement ?

Je suis en version 2.10.4 du plugin et 9.5.4 de GLPI

**Comment by btry** [comment]
Bonjour

La zone de saisie de date est fournie par GLPI. Vérifiez que votre problème est reproductible avec une date quelque part dans GLPI (par exemple les informations financières d'un asset). 

Si le problème se reproduit ici, alors votre demande concernera GLPI.

**Comment by jpclerc** [comment]
Effectivement.... même fonctionnement hors FormCreator

**Comment by btry** [comment]
Ok, alors il faut faire le rapport de bug dans le dépôt de GLPI, ou sur le support professionnel si vous en avez.

Je ferme ce ticket car le bug n'est pas dans le plugin.
