### ISSUE TITLE
Can't upgrade from 2.4.2 to 2.11.x - (Upgrade glpi_plugin_formcreator_questions_conditions)

### ISSUE THREAD

**Issue by rzmunch** [pluginsGLPI/formcreator#2257]
Hello, I migrated GLPI from an old version (0.93 to 9.5.5- Debian10 - Mysql5.7). And I'm having problems with formcreator.

I tried upgrading from 2.4.2 to: 2.11.4, 2.11.0, 2.10.0, 
And I always stays here:
0 segundos for "Trabajo en progreso..." @ 2021-06-09 21:50:14 [7@glpi955]
0 segundos for "Upgrade to schema version 2.5" @ 2021-06-09 21:50:14 [7@glpi955]
0 segundos for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-09 21:50:14 [7@glpi955]
0 segundos for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-09 21:50:14 [7@glpi955]
0 segundos for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2021-06-09 21:50:14 [7@glpi955]
0 segundos for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2021-06-09 21:50:14 [7@glpi955]
0 segundos for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2021-06-09 21:50:15 [7@glpi955]
1 segundo for "Upgrade glpi_plugin_formcreator_forms" @ 2021-06-09 21:50:15 [7@glpi955]
0 segundos for "Drop glpi_plugin_formcreator_headers" @ 2021-06-09 21:50:15 [7@glpi955]
0 segundos for "Upgrade glpi_plugin_formcreator_issues" @ 2021-06-09 21:50:15 [7@glpi955]
**0 segundos for "Upgrade glpi_plugin_formcreator_questions_conditions" @** 

I tried activating 2.4.2 but it doesnt work.

php-error.log

[2021-06-09 21:50:07] glpiphplog.ERROR: Plugin::getInfo() in /var/www/glpi/inc/plugin.class.php line 1476
plugin_version_addressing-2.3.0 method must be defined!  {"user":"7@glpi955"}
[2021-06-09 21:50:15] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFormcreatorQuestion_Condition' not found in /var/www/glpi/plugins/formcreator/install/upgrade_to_2.5.php at line 565
  Backtrace :
  plugins/formcreator/install/upgrade_to_2.5.php:51  PluginFormcreatorUpgradeTo2_5->updateQuestionCondition_2_5()
  plugins/formcreator/install/install.php:137        PluginFormcreatorUpgradeTo2_5->upgrade()
  plugins/formcreator/install/install.php:105        PluginFormcreatorInstall->upgradeOneStep()
  plugins/formcreator/hook.php:48                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:726                           plugin_formcreator_install()
  front/plugin.form.php:47                           Plugin->install()

Thanks!

**Comment by btry** [comment]
Hi

Please have a testing instance of GLPI with a copy of your latest backup before the upgrade. Then patch Formcreator 2.11.4 with the PR https://github.com/pluginsGLPI/formcreator/pull/2258

Try to upgrade again and feedback.

**Comment by rzmunch** [comment]
Upgraded correctly to 2.11.4, and I activated the plugin without problems. Thanks!

**Comment by btry** [comment]
Hi

Thank you for your feedback.
