### ISSUE TITLE
Duplicating forms. Show field Conditions are not accepted

### ISSUE THREAD

**Issue by flo1994** [pluginsGLPI/formcreator#226]
Hello,

I have created a form with many conditions. (Hidden unless). 

I would like to duplicate this form several times. This works so far.....

However, the conditions set (Hidden unless) are no longer displayed. 

Although it has been absolutely still nothing changed on the form (questions, show field etc.)

Does somebody has any idea?

Thanks a lot for your help.
Florian

**Comment by btry** [comment]
Hi

I tried with a a form having 2 questions, the second hidden unless the first one has a specific value.

A clone seems to work as expected.
Can you show a conditions on the form used as source of the clone process ?

Also can you try to clone the form and check for errors in php-errors.log and sql-errors.log ?

**Comment by flo1994** [comment]
I could now adjust how this problem occurs. If i duplicate a form, the value of hidden unless for example is lost. The value must be re-entered. Then it works.
