### ISSUE TITLE
Clic sur le label / Focus sur un champ manquant 

### ISSUE THREAD

**Issue by MaximeMeriot** [pluginsGLPI/formcreator#2260]
Bonjour,
Je me permets d'ouvrir une demande sur le plugin.
Nous travaillons sur GLPI 9.4 avec FormCreator en version 2.10.4

Nous avons remarqué deux petites améliorations possibles sur le plugin : 

- Lorsque l'on clique sur un label du formulaire, celui-ci ne sélectionne pas le champ à remplir correspondant (puisque l'id est généré par formcreator et ne correspond pas au 'for' du label).
- A la validation du formulaire, si une réponse à une question obligatoire n'a pas été faite, serait-il possible de mettre le focus sur la question en la mettant en exergue (encadré de couleur ou autre ?)

Peut-être avez-vous déjà eu des retours sur ce genre de fonctionnalités ?

Merci d'avance,

Cordialement,

Maxime, Département de Maine-et-Loire.

**Comment by btry** [comment]
Bonjour

> Lorsque l'on clique sur un label du formulaire, celui-ci ne sélectionne pas le champ à remplir correspondant (puisque l'id est généré par formcreator et ne correspond pas au 'for' du label).

En l'état ce n'est pas possible de réaliser cela sur tous les champs. GLPI ne crée pas d'attribut **id** pour les zones de saisie de date par exemple. Il faut donc d'abord faire en sorte que GLPI ajoute ces attributs.

> A la validation du formulaire, si une réponse à une question obligatoire n'a pas été faite, serait-il possible de mettre le focus sur la question en la mettant en exergue (encadré de couleur ou autre ?)

Cela n'est pas possible pour le moment car la validation se fait côté serveur et en cas d'erreur il n'y a pas de donnée transmise au navigateur pour indiquer les champs problématiques. Cette demande doit se traiter en même temps qu'un basculement de la validation côté client. C'est une partie assez lourde vu le nombre de points de validation et le nombre de types de questions.

**Comment by MaximeMeriot** [comment]
Bonjour,

Je comprends mieux, merci de votre retour sur le sujet.

Cordialement,

Maxime.
