### ISSUE TITLE
Ticket status not counted from a multiple target form

### ISSUE THREAD

**Issue by cgrzl** [pluginsGLPI/formcreator#2262]
**Describe the bug**
When a user submits a form with multiple targets, the status of the tickets is not counted on the top left part of the interface even though they have the status "In progress"

**To Reproduce**
With a Admin or other profile that can create a form, create a form with multiple targets (that create more than 1 ticket)
With a self service user, answer this form.

**Screenshots**

![image](https://user-images.githubusercontent.com/85362794/121823798-c6180600-cca7-11eb-9fa9-41473d3336a2.png)

![image](https://user-images.githubusercontent.com/85362794/121823775-b3053600-cca7-11eb-94f3-7b71ad34e710.png)

**Comment by btry** [comment]
Hi

As a super admin open one of the tickets and find the form answer associated to it. Open it, and you will find its ID in the address bar of the browser.

Next, search in the DB, table glpi_plugin_formcreator_issues the row matching this form answer. The row has sub_itemtype = PluginFormcreatorFormAnswer and tie original_id is the ID you obtained earlier. Show the value un the column status. 

If your tickets had the status "new" after they were created, maybe the issue still has the "new" status.

**Comment by cgrzl** [comment]
Even when I create tickets that are automatically assigned after the form is submitted the status of the problem is the same.

Attached is a capture of the request line (the id is different because it is another request but under exactly the same conditions)

![image](https://user-images.githubusercontent.com/85362794/121867639-7580c700-cd00-11eb-8caf-6edab939a1c6.png)

**Comment by btry** [comment]
Hi

Soem enhancements were done in latest versions of the plugin. Could you check the problem is solved ?

Note: further enhancements impacting the status of assistance requests are ready in future 2.13.0 version.

**Comment by btry** [comment]
Hi

Formcreator now computes an aggregation of the status of several tickets tu maintain a consistent status of assistance requests. This problem should be solved.
