### ISSUE TITLE
Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist

### ISSUE THREAD

**Issue by Mclaren974** [pluginsGLPI/formcreator#2263]
**Describe the bug**
When i try to install the formcreator plugin i've got the follwing message "Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist"

**Screenshots**
Here you see the content of my log files about formcreator :
Table 'glpi.glpi_plugin_formcreator_answers' doesn't exist
  Backtrace :
  ...place/formcreator/install/upgrade_to_2.5.php:71 plugin_formcreator_upgrade_error()
  ...place/formcreator/install/upgrade_to_2.5.php:43 PluginFormcreatorUpgradeTo2_5->updateAnswer_2_5()
  marketplace/formcreator/install/install.php:140    PluginFormcreatorUpgradeTo2_5->upgrade()
  marketplace/formcreator/install/install.php:108    PluginFormcreatorInstall->upgradeOneStep()
  marketplace/formcreator/hook.php:48                PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:726                           plugin_formcreator_install()
  :                                                  Plugin->install()
  inc/marketplace/controller.class.php:472           call_user_func()
  inc/marketplace/controller.class.php:391           Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:77                            Glpi\Marketplace\Controller->installPlugin()
 @ 2021-06-15 10:20:16 [282@glpi]

**Desktop (please complete the following information):**
GLPI version 9.5.5

Best regards;

**Comment by btry** [comment]
Hi

The backtrace shows that Formcreator tried to upgrade from a version earlier than 2.5.0. Are you doing a fresh install or an upgrade ?

**Comment by Mclaren974** [comment]
an Upgrade but the last version don't work correctly already.

**Comment by btry** [comment]
Can you tell which was the previously installed version ?

**Comment by Mclaren974** [comment]
the previous version was 2.10.2

**Comment by btry** [comment]
Version 2.10.2 is not known to have upgrade issues like you have.

Please show the result of the following SQL query

SELECT * FROM glpi_configs WHERE context='formcreator'

**Comment by Mclaren974** [comment]
the result : 
MariaDB [glpi]> SELECT * FROM glpi_configs WHERE context='formcreator';
Empty set (0.000 sec)

**Comment by btry** [comment]
The request shoud return a row, and its content tells Formcreator from which version it must upgrade.


Insert a row with the following values
context='formcreator'
name='schema_version'
value='2.10.2'

Once done, you may want to verify that the row is actually added by running the previous SQL request again.

Finally, re-run the upgrade process of Formcreator. It should run properly.

**Comment by Mclaren974** [comment]
here the result :
MariaDB [glpi]> SELECT * FROM glpi_configs WHERE context='formcreator';
+-----+-------------+----------------+--------+
| id  | context     | name           | value  |
+-----+-------------+----------------+--------+
| 269 | formcreator | schema_version | 2.10.2 |
+-----+-------------+----------------+--------+
1 row in set (0.001 sec)

when i execute the upgrade process now i've got this message : 
Changement de la structure de la base de données - glpi_plugin_formcreator_questions (1 seconde)

2.11.4 multiple alter in glpi_plugin_formcreator_questions - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_questions` ADD `col` INT(11) NOT NULL DEFAULT '0' AFTER `row` , ADD `width` INT(11) NOT NULL DEFAULT '0' AFTER `col` - L'erreur est Table 'glpi.glpi_plugin_formcreator_questions' doesn't exist

**Comment by btry** [comment]
Hi

It looks like the table glpi_plugin_formcreator_questions is missing. This table is a fundamental table of the plugin, and always existed. I don't have in ming an upgtrade step where this table is deleted (then recreated). I guess something damaged your database.

If you did a backup before trying to migrate, you should show the name of all tables beginning with glpi_plugin_formcreator . I guess that at least one table of th plugin version 2.10.2 is missing.

**Comment by Mclaren974** [comment]
Is there a way to cleanly remove all dependencies linked to "form creator" in order to redo a clean installation of the plugin?
If, yes can you give me a procedure to follow.

**Comment by btry** [comment]
Delete the row you added in glpi_configs and delete all tables having a name starting with glpi_plugin_formcreator_

Once done, you should be able to run a clean install.

**Comment by Mclaren974** [comment]
It works now, thank you very much for your help !
