### ISSUE TITLE
Question : Lien entre formulaire et Ticket

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2264]
Bonjour

Je n'arrive pas à trouver par quelle table est fait le lien entre formulaire et ticket(s)

j'ai un formulaire (table glpi_plugin_formcreator_forms), qui créé des forms (glpi_plugin_formcreator_formanswers) : ok
ce formulaire peut creer des tickets (ou des changements)

dans glpi_plugin_formcreator_issues je vois bien le numéro ticket (avec eventuellement t-xxx (display id) ou xxxx ((original id)
qui correspond en effet au ticket créé... mais l'id de cet enregistrement n'est pas celui du formulaire (formanswers) : donc je ne vois pas :(

Merci

**Comment by btry** [comment]
Bonjour,

La relation "réponses au formulaire" / "ticket" est dans la table glpi_items_tickets (qui appartient à GLPI).

**Comment by EC2311** [comment]
Merci beaucoup !
