### ISSUE TITLE
Compatibility with "PDF" plugin

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2265]
**Is your feature request related to a problem? Please describe.**
Helo!

When we use the formcreator with the option "Helpdesk mode" > "Service catalog simplified" , when we try to generate a PDF of the ticket's content, it comes out with a very bad preview

![image](https://user-images.githubusercontent.com/35368369/122088800-7e46cb00-cddc-11eb-9602-5247352b79f5.png)
![image](https://user-images.githubusercontent.com/35368369/122088924-9fa7b700-cddc-11eb-8736-b4cc2d9c153b.png)

**Describe the solution you'd like**
Plugin "[PDF](https://plugins.glpi-project.org/#/plugin/pdf)" solves this problem and outputs the PDF correctly.

If we use the "Service catalog extented" option, the option to print in .PDF is displayed in Fomcreator

![image](https://user-images.githubusercontent.com/35368369/122089251-f57c5f00-cddc-11eb-8ef3-6fb6230b4bd2.png)
![image](https://user-images.githubusercontent.com/35368369/122089368-104ed380-cddd-11eb-8d38-7881012b2743.png)
![image](https://user-images.githubusercontent.com/35368369/122089426-20ff4980-cddd-11eb-9f10-0943e8833f61.png)

**Describe alternatives you've considered**
Would it be possible to add compatibility with the "PDF" plugin to the "Service catalog simplified" interface?

**Comment by btry** [comment]
Hi

The simplified service catalog does not allows to show tabs of a ticket, then it is not possible tu acces PDF plugin from a tab. I guess that PDF plugin does not provide any mechanism to be accessed from an other way, then (if confirmed) the best option is probably to make Formcreator more compliant with PDF print.

**Comment by btry** [comment]
Hi

Please test  the folllowing fix and feedback.

**Comment by phamorais** [comment]
@btry Hi!


I don't understand what the expected behavior would be.

However, I made the change and it still looks like the image below. Using Google Chrome

![image](https://user-images.githubusercontent.com/35368369/123967419-ad3c6f80-d98c-11eb-9881-e98740344459.png)

**Comment by btry** [comment]
Hi

The fix modifies CSS for printing. In most cases, you need to refresh the browser's cache to get the up to date CSS after applying the patch. Try F5 and Ctrl+F5.

The fix modifies the left margin on the main area and the top bar.

**Comment by btry** [comment]
Oh, I see on your screenshot that the left margin is reduced and I may need to fix the width of the main area for the ticket. I'll check that quickly.

**Comment by phamorais** [comment]
@btry 

When I applied the patch I had cleared the temp as well as run it in an anonymous browser tab.

**Comment by btry** [comment]
Hi

I updated the fix. Can you try it and feedback again ?

Here is the result when emulating print rendering

![image](https://user-images.githubusercontent.com/14139801/124439983-6084da00-dd7a-11eb-819e-d9d73b5a5d4e.png)

**Comment by phamorais** [comment]
@btry Hi :)

I applied the fix and it improved a little.

However, when we have a lot of content on the ticket:

1. It is showing the sidebar of the browser;
2. The red color at the bottom shows that there is more content to be displayed, however it is only showing the '1 page' print to be printed.

I don't have much development knowledge, but would using PDF plugin compatibility be the best way?

![image](https://user-images.githubusercontent.com/35368369/124589291-368def00-de30-11eb-9712-6542c3c4cfd5.png)

**Comment by btry** [comment]
Hi

I think it is better to improve Formcreator instead on relying on the PDF plugin. 

I'll iterate again soon to fix that.

**Comment by phamorais** [comment]
@btry  thx!

**Comment by phamorais** [comment]
up

**Comment by btry** [comment]
Hi

In version 2.13.0 (in development) and with GLPI 10 the rendering for printing is better. It may be interesting to get your feedback. Please wayt the release of 2.13.0-alpha.3

**Comment by btry** [comment]
Hi

This issue should be solved with Formcreator 2.13.0. I close it. If the problem persists, please open a new issue.
