### ISSUE TITLE
Questions like "Tags" are not included in the ticket [Ref #2253]

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2266]
**Describe the bug**
When using Formcreator 2.11.3 and using the question "Type" > "Tags", the tag is not added to the ticket on opening, even after applying the path https://github.com/pluginsGLPI/formcreator/issues/2253

![image](https://user-images.githubusercontent.com/35368369/122093025-016a2000-cde1-11eb-95e5-6a78b5b5ee8f.png)

In Target was configured

![image](https://user-images.githubusercontent.com/35368369/122093159-25c5fc80-cde1-11eb-8c58-b6d03fa12cf3.png)

However, when opening the ticket the label is not added to the ticket

![tags](https://user-images.githubusercontent.com/35368369/122093418-72a9d300-cde1-11eb-91bf-98a5f266ede9.gif)

question.class.php

![image](https://user-images.githubusercontent.com/35368369/122093574-9240fb80-cde1-11eb-8fc4-10953cc2906d.png)

**Expected behavior**

Ticket be opened with the selected tag

**Comment by btry** [comment]
Hi

Please edit the target ticket and save it, even if you have nothing to update. The bug may occur because the tag question were not saved in the DB.

**Comment by phamorais** [comment]
@btry 

I did it exactly according to your orientation. I re-applied "Target" and the problem was fixed... even with version 2.11.3 and 2.11.4

Thanks for the always thoughtful support!

**Comment by btry** [comment]
You're welcome. Thanks for the feedback
