### ISSUE TITLE
EVO : XML Export 

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2267]
Bonjour

Comment pourrait-on générer un export XML du ticket généré par FormCreator ?

Sans pour autant (dans un premier temps) l'inclure dans formcreator et donc faire un script 'isolé' y aurait-il un moyen simple de réaliser un export XML ?

Cette option pourrait être disponible pour n'importe quel type d'element de GLPI, fonction de l'endroit ou du choix...

Merci des conseils

**Comment by btry** [comment]
Bonjour

Pour autant que je sache, il n'y a pas de focntion d'export vers un fichier XML en natif dans GLPI. Le plus proche de votre besoin serait de faire un export en CSV ou SLK depuis la liste des tickets de GLPI, en faisant un filtre de recherche limitant les tickets à celui qui vous intéresse.

Autre solution : créer un outil qui récupère le ticket depuis l'API de GLPI, et qui fait une conversion en XML.
