### ISSUE TITLE
Add new columns to the simplified interface

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2269]
**Is your feature request related to a problem? Please describe.**
It is very common for users to request new information in the ticket grid. Example: list for the user the SLA date for service, but unfortunately today the user cannot add or add new columns.

**Describe the solution you'd like**
Possibility of the user with a simplified interface to be able to select which columns he would like to see in the ticket grid.
![image](https://user-images.githubusercontent.com/35368369/122421904-18388000-cf63-11eb-817b-953bde37430a.png)

Another good possibility is to include a new option to include columns in the configuration screen Administration > Entities > Forms
![image](https://user-images.githubusercontent.com/35368369/122422541-9b59d600-cf63-11eb-8db0-563462089547.png)

**Comment by btry** [comment]
Hi

It is already possible with a secret trick to setup the display preferences for self service users.

However I had recently a bug report which shows that adding some columns will break the plugin. Then let me fix this big first, then I may consider to allow customization.

**Comment by phamorais** [comment]
@btry 

I Understand.
Thank you so much for your support, this is a really nice improvement.

**Comment by btry** [comment]
Hi

In version 2.13.0 of Formcreator, the list of assistance requests is available from the administration part of the plugin. The admin can now setup global display preferences, which applies to service catalog users, as long they don't have an administrative profile allowing them to set custom display preferences.

**Comment by arthurrschaefer** [comment]
Hi.
Would you mind sharing the path to get to the Global View of columns?
I can find the configuration just for the list of forms, but I couldn't find it for the assistance request list.

**Comment by phamorais** [comment]
Hi!

This request is very useful and has not yet been answered. We will wait for Teclib, if they find it useful.

**Comment by btry** [comment]
Hi

To maange global display preferences for assistance requests you must use a user with the ability  to administrate forms.

In the top toolbar you have a icon representing a paperplane. Itl gives access to assistance requests. From that page you can edit the display preferences like any usual asset. Changing global display preferences will impact the columns for the service catalog.

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/8f052259-78f0-472b-b90b-aecfe1c1f12a)
