### ISSUE TITLE
Impossible de supprimer la réponse d'un formulaire

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#2271]
Je ne peux pas supprimer les réponses à mes formulaires.

Ouvrir un formulaire.
Afficher les réponses.
Sélectionner les réponses.
Action.
Pas de choix pour supprimer la réponse.

![image](https://user-images.githubusercontent.com/47602797/122880660-894cae80-d33a-11eb-9be0-a14b91588b4b.png)

 - Windows 10
 - Chrome
 - Version 91.0.4472.114

**Comment by btry** [comment]
Bonjour

Avec quelle version de Formcreator ?

**Comment by tguichard25** [comment]
Bonjour,

2.11.4

**Comment by btry** [comment]
Avez vous le droit de modifier les entités ?

**Comment by tguichard25** [comment]
Oui en super-admin

**Comment by btry** [comment]
OK, je marque en bug. Je ne peux pas faire de recherche aujourd'hui. Si vous voulez supprimer le formulaire, vous devriez au moins pouvoir le désactiver, le rendant indisponible dans le catalogue de service.

**Comment by btry** [comment]
Bonjour

Pouvez-vous vérifier les 2 méthodes ci dessous dans formanswer.class.php ? Je reproduis si canPurge retourne false.

![image](https://user-images.githubusercontent.com/14139801/123795635-81fe4580-d8e4-11eb-9731-77f45407dbaf.png)

**Comment by tguichard25** [comment]
J'ai la même chose.

**Comment by btry** [comment]
Il y a quelques qnnées les réposnes aux formulaires pouvaient être mises à la corbeille. Ca ne fonctionnait pas bien, et je me souviens l'avoir retirée. Vérifiez que la table **glpi_plugin_formcreator_formanswers** ne contient pas de colonne **is_deleted**.

**Comment by tguichard25** [comment]
J'ai bien la colonne.

**Comment by btry** [comment]
Il y a des chances que le problème vienne de  là.

Voici la structure théorique de la table. Comparez avec la vôtre. au cas où il y ait d'autres différences. La colonne **is_deleted** peut être supprimée. Faites un backup de précaution au préalable.

```sql
CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_formanswers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `entities_id` int(11) NOT NULL DEFAULT '0',
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
  `plugin_formcreator_forms_id` int(11) NOT NULL,
  `requester_id` int(11) DEFAULT NULL,
  `users_id_validator` int(11) NOT NULL DEFAULT '0',
  `groups_id_validator` int(11) NOT NULL DEFAULT '0',
  `request_date` datetime NOT NULL,
  `status` int(11) NOT NULL DEFAULT '101',
  `comment` text,
  PRIMARY KEY (`id`),
  INDEX `plugin_formcreator_forms_id` (`plugin_formcreator_forms_id`),
  INDEX `entities_id_is_recursive` (`entities_id`, `is_recursive`),
  INDEX `requester_id` (`requester_id`),
  INDEX `users_id_validator` (`users_id_validator`),
  INDEX `groups_id_validator` (`groups_id_validator`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by tguichard25** [comment]
Une fois la colonne supprimée, ça fonctionne.

Merci ^^

**Comment by btry** [comment]
Parfait; merci pour votre retour.
