### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2274]
Bonjour,
je me connecte se matin comme à mon habitude et le warning suivant apparait:

```
Warning: Undefined array key "formcreator_field_186" in /var/www/html/glpi/marketplace/formcreator/inc/formanswer.class.php on line 1534

Warning: Undefined array key "formcreator_field_186" in /var/www/html/glpi/marketplace/formcreator/inc/formanswer.class.php on line 1534
1018
```

formcreator 2.11.4 -> GLPI 9.5.5
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/6706930/php-errors.log)

**Comment by btry** [comment]
Bonjour

Dans catalogue de services ?

**Comment by Riesuu** [comment]
Bonjour,
non sur la page d'accueil

![image](https://user-images.githubusercontent.com/17006344/123216222-96e46e80-d4c9-11eb-92da-48597c764fb9.png)

**Comment by btry** [comment]
Au vu su screenshot, c'est le catalogue de service.

J'ai fait des corrections il y a quelques jours versées dans la version 2.12.0 en  beta. Votre problème vient probablement d'un formulaire qui a été modifié alors qu'il a été utilisé auparavant par des demandeurs. Typiqueemnt un ajout de question peut provoquer le souci.

Essayez d'appliquer les corectifs suivants; je pense qu'ils s'appliqueront sans encombre à votre version.

2d1b85d900b0a1e8ec903ddd6c30d533db88f687
f054bbcdd9e0b41084ea6e94e03aded7abad32e6

Si cela ne suffit pas, allez en BDD et retrouvez la question portant l'ID 186. Remontez à sa section puis à son formulaire. Connaitre le formulaier et son historique peut servir à comprendre le souci; même si je suis relativement sûr de mon hypothèse.

**Comment by Riesuu** [comment]
Non ça n'a pas marché. Mais effectivement j'ai rajouté une question dans un formulaire hier.
En supprimant la question le message disparait.

**Comment by btry** [comment]
Quel est le type de la question ajoutée ?

**Comment by Riesuu** [comment]
Il s'agit d'un champ texte qui ne s'affiche que si la condition est validée.

**Comment by btry** [comment]
J'utilise la dernière révision de la branche 2.11.0 (donc la 2.11.4 + des corrections). 

Etant donné qu'on est en période de tests de la version 2.12, avec vous une instance de tests sur laquelle essayer la version 2.12.0 beta ?

**Comment by Riesuu** [comment]
Hélàs non

**Comment by btry** [comment]
il vous est impossible d'en créer une ? Ca vaudrait le coup de vérifier plutôt que de chercher le détail qui me permettra de reproduire.

**Comment by Riesuu** [comment]
Bonjour,
là de tout de suite non je ne peux pas la cloner, je regarde semaine prochaine.
J'ai pu ajouter un champ  avec condition sur un autre formulaire et cela a fonctionné sans message d'erreur. Je vous tiens au courant.

**Comment by Riesuu** [comment]
Bonjour,
pour information, j'ai demandé à ce que l'on me fasse un clone de la vm.

**Comment by btry** [comment]
Bonjour

Avez vous pu tester la  version 2.12.0-beta ?

**Comment by btry** [comment]
Bonjour

A défaut de retour, je ferme ce ticket. Il est probable que qu'il soit devenu obsolète.
