### ISSUE TITLE
Documents uploaded in a textarea are not visible sometimes

### ISSUE THREAD

**Issue by nsalguero** [pluginsGLPI/formcreator#2275]
Hi,

I found two problems in a form with a textarea:

1) In that field, if someone adds a document which is not a picture, the document is not uploaded and is replaced by a white square.

2) In that field, if someone adds a document which is a picture, the document is uploaded but it is not visible by technicians if their profile is not allowed to access documents.  The same picture, uploaded from a file selector, is visible.  Compared to the picture uploaded with a file selector, I see two differences:
  2.1) The URL is ".../front/document.send.php?docid=xxx" (textarea) vs. ".../front/document.send.php?docid=xxx&tickets_id=yyy" (file selector).
  2.2) In the document, the tab "associated items" do not contain a link to the ticket (textarea) vs. contains a link to the ticket (file selector).

Best regards,

**Comment by nsalguero** [comment]
Hi,

I forgot to mention that the problem occurs if the textarea from the form is configured to be the source of the content of the generated ticket.

Best regards,

**Comment by btry** [comment]
Hi

You said that the bug occurs "sometimes". There must be some difference between the cases where the bug occurs and the cases where the bugs doesn't occurs. Did you find the difference ?

I saw your contribution. There are 2 things I notice
- the new method does not always returns a ticket, and this return value is used as return of the caller. This will introduce bugs.
- I'm not in favor of string manipulation to modify an URL. Maybe this is really necessary, I don't know so far, because of incomplete data to handle this bug properly. I did not tried to reproduce myself yet.

**Comment by btry** [comment]
> In that field, if someone adds a document which is not a picture, the document is not uploaded and is replaced by a white square.

Uploads in a textarea should be pictures; nothing else. You should consider to upload documents wit a File question.

> In that field, if someone adds a document which is a picture, the document is uploaded but it is not visible by technicians if their profile is not allowed to access documents. The same picture, uploaded from a file selector, is visible. [...]

This must be compared against the behavior of GLPI when uploading things in a ticket. 

So far, your observations looks interesting. Need some time on my side to continue investigation.

**Comment by nsalguero** [comment]
> You said that the bug occurs "sometimes". There must be some difference between the cases where the bug occurs and the cases where the bugs doesn't occurs. Did you find the difference ?

Sorry, I was not clear: when saying "sometimes", I referred to the configuration of the Technician profile.  If the Technician profile is not allowed to access documents, then the problem always occurs.

> I saw your contribution. There are 2 things I notice
> 
>     * the new method does not always returns a ticket, and this return value is used as return of the caller. This will introduce bugs.

Maybe a better code could be removing the "else" and always finish by returning "$ticket" or do I miss something else?

>     * I'm not in favor of string manipulation to modify an URL. Maybe this is really necessary, I don't know so far, because of incomplete data to handle this bug properly. I did not tried to reproduce myself yet.

I agree it is a bit dirty.

**Comment by nsalguero** [comment]
> This must be compared against the behavior of GLPI when uploading things in a ticket.

I did the test and the result is that, when a ticket is directly created (or when a followup is added) with an image in the content, the generated link contains the "&tickets_id=<id of the ticket>" and a row is added in glpi_documents_items.

**Comment by btry** [comment]
Hi

# if someone adds a document which is not a picture, the document is not uploaded and is replaced by a white square

I tried to drop a text file or a binary (actually an archive) and nothing happens. It seems that the drop is ignored (as I would expect). 

### after a drop : 
![image](https://user-images.githubusercontent.com/14139801/124712974-39f0ab80-df00-11eb-94d6-fe6388aa6d16.png)


# the document is uploaded but it is not visible by technicians if their profile is not allowed to access documents 

When you paste a picture in a textarea it is uploaded then used in a IMG tag as a BLOB . I think that for now your solution is, in short term perspective, the best we can do. I will add a commit to your PR to handle changes as well

see Document::canViewItem() : https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/document.class.php#L605

**Comment by btry** [comment]
I think there is a better solution 

If I add a picture in the devault value of a textarea then it is processed a way which does triggers the bug.

Below an example with 2 pictures

The first is set as a default value, the 2ns is added when filling the test form. When viewing the generated ticket from a tech without rights on documents we can see the difference of rendering


![image](https://user-images.githubusercontent.com/14139801/124758862-4c360e00-df2f-11eb-9d77-1efcb3d8880e.png)

**Comment by btry** [comment]
Hi

There is work in progress 
https://github.com/pluginsGLPI/formcreator/pull/2320

This PR currently relies on a small code refactor in GLPI: https://github.com/glpi-project/glpi/pull/9335

**Comment by btry** [comment]
Hi

The PR is ready. It solves the problem by doing same manipulations as GLPI does. The PR has an update to no longer depend on GLPI changes. If you want to test it, I would appreciate your feedback.

**Comment by nsalguero** [comment]
Hi,

Sorry for this late response.

I applied the patch from PR2320 to formcreator 2.12.1 (the only part that I needed to fix was for the file inc/common.class.php) and I saw that it worked: the link for embedded images now contains the part that was missing e.g. "tickets_id=xxx".

Big thanks!
