### ISSUE TITLE
Upgrade glpi_plugin_formcreator_forms_answers

### ISSUE THREAD

**Issue by ClementChamayou** [pluginsGLPI/formcreator#2276]
**Description of the bug**
I am working with GLPI 9.5.5 and tried to add the plugin Formcreator 2.11.4 and then the latest version. However when I try to install it from GLPI I get redirected to a blank page with this written : Upgrade glpi_plugin_formcreator_forms_answers (0 seconde)

**Question**
Do you know why this happens ? And if yes, how can I solve it ?

**Desktop**
 - OS: Windows 10
 - Browser : Microsoft Edge
 - Version : 91 I think so

**Comment by btry** [comment]
Hi

It seems you are doing a fresh install of the plugin (please confirm), but the plugin detects something which leads it to run its upgrade process instead of a fresh install.

You should find a PHP backtrace in the HTTP server log and maybe something useful in glpi/files/_log/migration_to_2.11.4.log

**Comment by ClementChamayou** [comment]
Hi btry,

Well I updated my GLPI from 0.90.4 to 9.5.5 and upgrated as well Debian 7 to Debian 10 and formcreator was working with GLPI 0.90.4 so as we updated our GLPI (without importing our AD and databases) I don't now if it counts as a fresh install (to me it is).

I looked into the file you suggested and here is it's content : 

2021-06-21 17:15:23 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-21 17:15:23 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-21 17:15:23 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-21 17:15:23 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-21 17:15:39 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-21 17:15:39 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-21 17:15:39 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-21 17:15:39 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-21 17:19:25 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-21 17:19:25 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-21 17:19:25 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-21 17:19:25 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-21 17:21:10 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-21 17:21:10 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-21 17:21:10 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-21 17:21:10 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-21 17:45:17 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-21 17:45:17 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-21 17:45:17 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-21 17:45:17 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-22 11:31:19 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-22 11:31:19 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-22 11:31:19 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-22 11:31:19 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-24 10:51:52 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-24 10:51:52 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-24 10:51:52 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-24 10:51:52 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2021-06-24 12:01:56 [2@oiglpi]
0 seconde for "Traitement en cours..." @ 2021-06-24 12:01:56 [2@oiglpi]
0 seconde for "Upgrade to schema version 2.5" @ 2021-06-24 12:01:56 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2021-06-24 12:01:56 [2@oiglpi]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @

**Comment by btry** [comment]
Formcreator detects a version older than 2.5.0, but you said you did not import the database. For some reason you very likely have at least one table with a name beginning with glpi_plugin_formcreator_ .

**Comment by ClementChamayou** [comment]
Mhhh okay, how could I drop this table ?

**Comment by btry** [comment]
you need to write all steps of your upgrade process. There is something unclear to me. I assume you created a fresh Debian OS, then imported the files of GLPI (and its plugins). I don't understand why you did not imported the database as well. Also this is not consistent to create a GLPI install from scratch and having tables from a plugin.

**Comment by ClementChamayou** [comment]
I cannot explain clearly all these steps because a collegue of mine updated both Debian OS and GLPI, I did not do it by myself. 

Thank you for your patience, I'm a trainee and I am learning all these server stuff and GLPI functionnality as well. 

So, to me we first updated our Debian OS, then we dowloaded the latest version of GLPI and updated it on our server. Then I copied the plugins into /var/www/glpi/plugins.

**Comment by btry** [comment]
Ok, then the database of GLPI 0.90 was actually upgraded. If I understand well, you want to do a fresh install of Formcreator. In other words you don't have any data related to the plugin or don't need to keep previous data of the plugin.

If I'm right, drop all tables whose name begins with glpi_plugin_formcreator_. Next check run the following query

Delete from glpi_configs where context='formcreator';

Be careful, take a backup first.

Once done, then try again to install the plugin.


If you need to keep data from the plugin, this is more complicated. You need to restart the upgrade of GLPI from 0.90.0 (this means restoring the backup of the database and the files of GLPI).

Many people succeeded to upgrade with intermediate steps. Upgrade to 2.5.0, then 2.6.0 then 2.7.0. Next you should be able to upgrade with larger steps. Each time, use a GLPI version compatible with the version of Formcreator for your current step. This is a long process, but you may workaround some problems.

You should search in the community forum : some threads tell which steps you should use. When you reach version 2.8.0 or 2.9.0 I think you will be able to upgrade to the latest without problem.

**Comment by ClementChamayou** [comment]
Thank you so much for your answer.

I think I won't try to recover anything from the last forms, because it's too much of a hastle for us and we might lose a lot of time. We will recreate the forms after upgrading. However, I quite confused on how to drop the tables, do you know what tools should I use ? How can I drop tables ?

**Comment by btry** [comment]
You need to use the MySQL client (in a terminal) or a GUI tool like heidisql. If you don't have enough knowledge to maintain a GLPI you should ask on the community forum. I cannot allocate time to help on assistance topics.

**Comment by ClementChamayou** [comment]
Okay I will look for this solution. Thank you for your quick and detailed answers !

Wish you the best

Clément

**Comment by btry** [comment]
You're welcome.

I close this ticket as the solution is found.

**Comment by btry** [comment]
Ok, then time to brute force.

in a terminal, locate in the folder of Formcreator.

run  the following : ```php scripts/cliinstall.php --force-install```

it will force the installer to install ignoring a previous installation of the plugin. I never had to use it so far, then again, take a backup first. As you don't have any valuable data from the plugin, it should be safe.

**Comment by ClementChamayou** [comment]
So I tried what you suggested and I got this error :

`could not open input file: scripts/cliinstall.php`

I looked into the scripts folder (in formcreator) and I didn't find any cliinstall.php file.

**Comment by btry** [comment]
Hi

I checked the oficial archive of the version 2.11.4, the script is here. I assume that the script is deleted for some reason.

Replace your copy of Formcreator with the version 2.11.4 (https://github.com/pluginsGLPI/formcreator/releases/download/v2.11.4/glpi-formcreator-2.11.4.tar.bz2) or grab the cliinstall.php file to your copy.

**Comment by ClementChamayou** [comment]
I grabbed the cliinstall.php file to my copy and this is what I got : 

`PHP Warning:  include(): Failed opening '/var/www/glpi/plugins/formcreator/scripts/../vendor/docopt/docop              t/src/docopt.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/formcreator/sc              ripts/cliinstall.php on line 40
PHP Fatal error:  Uncaught Error: Class 'Docopt\Handler' not found in /var/www/glpi/plugins/formcreator/s              cripts/cliinstall.php:56
Stack trace:
#0 {main}
  thrown in /var/www/glpi/plugins/formcreator/scripts/cliinstall.php on line 56
`

**Comment by btry** [comment]
Your copy of Formcreator is very likely damaged. You don't have the CLI install script, and you don't have the dependencies.

Remove your copy of Formcreator and reinstall it using the archive.

**Comment by ClementChamayou** [comment]
Update : restarting the server solved the issue ! Now I have access to the "Formulaire" tab. Next step is to make tickets from a form.

Thank you so much btry for your patience and help, wish you a great day !
