### ISSUE TITLE
v2.12.0-beta.1 Reset translation cache after translate a new Form

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/formcreator#2278]
Once a form has been translated, the translation cache must be reset for it to be taken into account.

**Comment by btry** [comment]
Hi

While fixing bug #2277, I created a form and added a translation. The translation was applied without resetting the cache. This needs more investigation. Maybe check together on your instance.

**Comment by btry** [comment]
Hi

Should be solved with 79840b41d41a5aab2a782272f5decf111e43f028
