### ISSUE TITLE
Condition to Fire a Destination

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/formcreator#228]
Hello,

I saw that if you can add multiple destinations in a form. But I could not find a way through to a condition trigger allocation.
Example: If a field is selected on a checkbox give then performs the allocation.

Thank you,
Sidnei

**Comment by Miminoux** [comment]
:+1:

**Comment by msizec** [comment]
need, oh yeah

**Comment by tdelaux** [comment]
+1

**Comment by btry** [comment]
Hi

Feature implemented. I close this issue.

**Comment by Miminoux** [comment]
Thank you ! I can't wait to try this new feature !!!
🥇

**Comment by btry** [comment]
The feature was added a few months ago. Then you probably found it already if you upgraded regularly.
