### ISSUE TITLE
Automatically fill in info from GLPI object

### ISSUE THREAD

**Issue by ThibautStark** [pluginsGLPI/formcreator#2280]
I've begun creating a form designed towards ticketting. One of the first info I ask of the one filling the ticket is his GLPI account. For future reference, I then ask them their email address and his telephone number. Those informations are already in GLPI and linked to his account. It would be nice if the form could fill those in automatically.

I guess the solution would be : as you get the GLPI object, get also its characteristics. Enable those characteristics as possible types and enable the characteristic of the selected user as the by default one.

Thank you for all you've done.

**Comment by btry** [comment]
Hi

If you check the defaults settings of a target ticket you will find in the requesters that the requester (the one who fills the form) is already added. You don't need to ask email or phone number of the requester. The generated ticked is associated to the requester then you can find all data of the requester by clicking on his name.

**Comment by ThibautStark** [comment]
Yeah, my problem is that in the event that they're not calling from their assigned phone, the info could be wrong. I guess I'll work around that by putting a field Phone where they'll enter their own phone number.

Another question I wanted to ask : is it possible to hide fields that were not filled in the form answers ? In the event of entire blocks being empty because of an entry in the first block, it would be more readable to hide all empty fields/blocks instead of having them be blank.

**Comment by btry** [comment]
If your users know their credentials they should be able to login from any device and fill the form.

> Another question I wanted to ask : is it possible to hide fields that were not filled in the form answers ? In the event of entire blocks being empty because of an entry in the first block, it would be more readable to hide all empty fields/blocks instead of having them be blank.

I think that you should use conditions on question or sections to show or hide them depending on the content of the first questions.

**Comment by ThibautStark** [comment]
Yes, but even if conditions are used, it only hides the fields while filling in the form. The one that reads it has all fields, even those that are empty.

**Comment by btry** [comment]
This is not normal : conditiosn are evaluated after loading the form then shortly after the page is loaded, hidden form will disappear.

If I remember well, in the incoming version, this was optimized to avoid 1 HTTP request and hide the hidden fields earlier.

**Comment by ThibautStark** [comment]
Problem solved, I simply wasn't on the last version of FormCreator. Sorry for taking up your time.

**Comment by btry** [comment]
Hi

You're welcome. Thanks for your feedback.
