### ISSUE TITLE
Choisir le format du champ heure

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#2282]
Bonjour,

Serait-il possible de rajouter une option pour les champs heures afin de choisir si l'on veut afficher les heures/minutes/secondes.

![image](https://user-images.githubusercontent.com/47602797/123634893-48add300-d81b-11eb-8308-fa03d4ec315b.png)

**Comment by btry** [comment]
Bonjour

Formcreator s'appuie sur l'API de GLPI pour gérer ce type de champ, et GLPI n'offre pas d'option pour cacher les secondes. 

Vous devriez faire votre demande sur le dépôt de GLPI.

**Comment by btry** [comment]
Bonjour

A défaut de retour, et n'ayant pas de ticket pour GLPI à lier à celui-ci, je ferme cette demande.
