### ISSUE TITLE
Spanish Latin America Language error.

### ISSUE THREAD

**Issue by cadamuroa** [pluginsGLPI/formcreator#2285]
**Describe the bug**
When we created one form and register it as Spanish Latin America language, the system is not saving correctly.

**To Reproduce**
1. Go to 'Administration -> Forms'
2. Create a new form and put the language as 'Spanish Latin America'
3. Look the languagem in the list the system shows es_41.

Looking the table I saw that the field language have just 5 caracters and the code of spanish for latin america is 6.

**Screenshots**

![image](https://user-images.githubusercontent.com/48462877/123886830-b135a680-d926-11eb-91ba-c6270c1a88f7.png)

![image](https://user-images.githubusercontent.com/48462877/123886884-cca0b180-d926-11eb-9fa4-ac9134732984.png)

**Additional context**
I'm using the version of 9.5.5 (glpi) and form creator (2.11.4)

**Comment by cadamuroa** [comment]
The code of latin america spanish is es_419.

**Comment by btry** [comment]
Hi

Indeed, the column is too short. Change it to VARCHAR(255). I'll add a fix for the next release.

**Comment by btry** [comment]
Hi

Did you changed the column of the table ? Does it resolve your issue ?

**Comment by cadamuroa** [comment]
I changed the column of the thable and the language was saved correctly.

**Comment by cadamuroa** [comment]
@btry ,

Let me know if you need something more!

Thank you

**Comment by btry** [comment]
Hi

I just needed a confirmation that the fix works as expected. It is ready for the next release.

Thank you for your feedback.
