### ISSUE TITLE
Attachment documents in KB formcreator

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2286]
**Describe the bug**
No attachment  files for the user when i put a document with attachment files in FAQ  Knowledge Database . 

**To Reproduce**
1. As Admin go to Manage > Documents
2. Create a document, import file, put in FAQ
3. Activate formcreator "Knowledge database distinct"  menu, 
4. Log in as a simple user
5. Open the document
6.  subject and description are there but no files.

**Expected behavior**
The user can see the attachment files

**Screenshots**
![kb](https://user-images.githubusercontent.com/78594318/123918271-ffc55e00-d983-11eb-8596-0d033c8c5165.jpg)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser : firefox

**Additional context**
Was ok in glpi 9.5.3 + formcreator 2.11.2
Not ok  in glpi 9.5.5 + formcreator 2.11.4

**Comment by btry** [comment]
Hi

Apply the following patches on GLPI

First : https://github.com/glpi-project/glpi/pull/8847
second: https://github.com/glpi-project/glpi/pull/9041

**Comment by mirda123** [comment]
thank you so much  !!! i will try that and come back for feedback after !!  : )

**Comment by mirda123** [comment]
Works perfectly now many thanks !

**Comment by mirda123** [comment]
Bonjour, le problème se produit de nouveau suite au passage en glpi 9.5.6 ET Formcreator 2.12.14  .  Plus de doc visible en profil utilisateur. Faut-il repasser le fix ?
![doc_form](https://user-images.githubusercontent.com/78594318/149994336-66ad5595-ccf6-4431-aaa8-4b28fc30e52a.jpg)

**Comment by btry** [comment]
Bonjour

Le premier correctif cible GLPI 10. Vous devez réappliquer les patchs sur votre nouvelle version de GLPI.

**Comment by mirda123** [comment]
Bonjour, réappliqué, résolu, merci : )
