### ISSUE TITLE
Intégration du workflow

### ISSUE THREAD

**Issue by ThibautStark** [pluginsGLPI/formcreator#2288]
Bonjour,

Je cherche à intégrer le workflow des demandes de nouveau matériel aux formulaires. Le problème est qu'il ne peut pour l'instant exister que des valideurs fixes pour toutes les demandes. Or, dépendant du type de demande faite (serveur, compte LDAP, base de données, ...) j'aimerai pouvoir renvoyer le formulaire vers différents valideurs. Je me demande donc si c'est déjà possible et que je n'ai simplement pas trouvé comment faire ou s'il faudrait diviser les demandes.

**Comment by btry** [comment]
Bonjour

Vous pouvez définir plusieurs tickets ou changements cibles pour un même formulaire. Cela permet de répartir le sréponses à différents techniciens.

De plus les conditions ont été étendues aux cibles permettant de les générer seulement si des réponses correspondent aux critères définis dans les conditions..

Avec tout cela vous devriez arriver à vos fins.

**Comment by ThibautStark** [comment]
Merci pour cette réponse rapide,

Il est en effet possible de remettre les formulaires à des techniciens en fonction du type de la demande, mais le valideur semble être défini par le formulaire, pas par les cibles.

**Comment by btry** [comment]
Ce besoin se manifeste de plus en plus depuis quelques mois, et il me semble qu'il n'y a pas encore de solution. Il faut vérifier si on peut définir des validateurs via les gabarits de tickets. Sinon vous pouvez utiliser le système de validation de Formcreator. il fonctionne en amont de la création cibles, ce qui n'est peut être pas plus mal dans votre cas car il y aurait une validation avant de géénrer toutes les cibles, et pas une validation par cible.
