### ISSUE TITLE
Preguntas de Tipo Objeto GLPI no muestra los objetos creados con el plugin GenericObject (Gestion de Objetos)

### ISSUE THREAD

**Issue by alexmicontini** [pluginsGLPI/formcreator#2289]
Hola,

Cuando creo un objeto nuevo con el Plugin GenericObject, este aparece en el menú Activos, pero al crear una pregunta de tipo ObjectGLPI, el objeto creado no aparece entre los seleccionables. De entre los Activos seleccionables, sólo aparecen los siguientes: Computadores, Monitores, Software, Dispositivos de red, Dispositivos, Impresoras, Modelos de cartuchos, Modelos de consumibles, Teléfonos y Líneas.

Objeto creado: plataformasdeformacion

Versión de Glpi: 9.4.6
Versión del plugin FormCreator: 2.10.4
Versión del plugin GenericObject: 2.7.0

Por el momento no me es posible actualizar la versión de Glpi, ni por tanto, la de los plugins indicados.

![image](https://user-images.githubusercontent.com/86783891/124127692-f3b8c980-da73-11eb-9b42-878ee784d064.png)

![image](https://user-images.githubusercontent.com/86783891/124127846-1d71f080-da74-11eb-9af4-4df5e318aa84.png)

![image](https://user-images.githubusercontent.com/86783891/124128890-1dbebb80-da75-11eb-8e3b-f98f51309125.png)

**Comment by btry** [comment]
Hi

Please write in english, to make the conversation accessible to everyone (and myself; I had to use a translator).

Support for Generic object was added in Formcreator 2.11.4. You also need to update Generic object to the latest version. 

To upgrade to Fotrmcreator 2.11.4 you need to upgrade GLPI to version 9.5.5.
