### ISSUE TITLE
Règles sur formulaires

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#2294]
Bonjour,

Je suis en GLPI 9.5.5 et form creator 2.11.4
Je constate un souci sur les règles lorsque j'intègre l'intitulé du champs depuis que le texte riche est par défaut dans GLPI.  Exemple:
La règle suivante
![image](https://user-images.githubusercontent.com/25478777/124436474-48ab5700-dd76-11eb-860b-eb6af581a0df.png)
Ne fonctionne pas. Si je fais ma règle juste sur le mot Non qui est la réponse à la question cela fonctionne correctement.
J'espère que c'est assez clair.
Merci

**Comment by btry** [comment]
Bonjour

A priori, votre problème est bien connu. Le texte riche contient géénralement du HTML (balises pour la couleur, l'italique, gras, ...). Les règles métier sont en texte brut, ce qui fait que vous devez écrire les balises HTML qui peuvent se trouver dans le texte testé.

En supposant que le HTML du texte testé est invariable d'un cas à un autre, vous devez récupérer un échantillon du texte en BDD pour savoir à quoi doit ressembler le texte de votre règle métier.

Je ne suis pas sûr que ce soit pertinent, mais il faudrait que les règles métier nettoient le HTML avant la comparaison. Il y a probablement un ticket à faire sur repo de GLPI pout étudier la qustion.

**Comment by eckorion** [comment]
Ah oui en effet ça marche mieux. 
Merci beaucoup

**Comment by btry** [comment]
Très bien, je ferme le ticket.

Merci pour votre retour.
