### ISSUE TITLE
Tickets created by the plugin do not contain the answers

### ISSUE THREAD

**Issue by ClementChamayou** [pluginsGLPI/formcreator#2295]
**Describe the bug**
I created a form and linked to it a  ticket target. When I fill the form, the ticket is created however the answers do not appear anywhere. The ticket's description only contain the questions of the form and not the answers. In the ticket target, I linked the request type to the answer from a question however in the ticket it is always "Incident" even if "Demande" was specified in the form.
Another issue I encountered was that I can't link in the ticket target the "Catégorie" section to an answer, I tried every type of answer but nothing worked. I did Catégorie > Egale à la réponse à la question / Question > Aucun résultat trouvé

**To Reproduce**
1. Create a form
2. Fill it as an user
3. Open the ticket created

**Expected behavior**
I expected the ticket to be filled with the form answers.

**Screenshots**
Problem 1 :
![image](https://user-images.githubusercontent.com/71630883/124453510-ba3fd100-dd87-11eb-82ca-3bbd2fd0a4b9.png)

**Desktop :**
 - OS: Windows 10
 - Browser : Chrome
 - Version : recent

Do you have a clue of what's going on ?

**Comment by btry** [comment]
Hi

Did you check php-errors.log and sql-errors.log ?

**Comment by ClementChamayou** [comment]
Hi ! So I checked php-errors.log, I have a warning about another plugin (fields) but I don't think it's this because I've had this warning for a bit and my computer had not exploded yet.

However in sql-errors.log I got this : 

> glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: SELECT `plugin_formcreator_questions_id`, `answer` FROM `glpi_plugin_formcreator_answers` WHERE `plugin_formcreator_formanswers_id` = '6'
  Error: Unknown column 'plugin_formcreator_questions_id' in 'field list'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:876                          DBmysqlIterator->execute()
  plugins/formcreator/inc/formanswer.class.php:841   DBmysql->request()
  plugins/formcreator/inc/formanswer.class.php:1532  PluginFormcreatorFormAnswer->getAnswers()
  plugins/formcreator/inc/formanswer.class.php:1092  PluginFormcreatorFormAnswer->deserializeAnswers()
  plugins/formcreator/inc/targetticket.class.php:753 PluginFormcreatorFormAnswer->parseTags()
  plugins/formcreator/inc/formanswer.class.php:811   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:997   PluginFormcreatorFormAnswer->generateTarget()
  inc/commondbtm.class.php:1173                      PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:142        CommonDBTM->add()

>

**Comment by btry** [comment]
The table **glpi_plugin_formcreator_answers** does not exists anymore in the plugin. It should be **glpi_plugin_formcreatoranswers** . 

Which version of the plugin are you using ?

**Comment by ClementChamayou** [comment]
I am currently using 2.11.4 version

**Comment by btry** [comment]
There is a problem in the files of your plugin. As far as I know it is not possible for the code to read this old table with a recent version of the plugin.

The old table exists in your DB, then a migration problem occurred in the past.
The source code responsible of this bad SQL query never triggered such error as far as I remember (customers and community). 

Then you should analyze all tables of the plugin and check their structure matches the CREATE TABLE statements inf the installer.

You should also check all files of the plugin, maybe by running a SHA256 checksum of the Formcreator folder. 

I'm afraid I won't be able to help more on such problem without this diagnostic work on your side. You may consider to get professional support as I expect your problem requiring deep diagnosis.

**Comment by ClementChamayou** [comment]
Hi !

I checked the deferent tables and their structures matches the ones in the CREATE TABLE statements in the installer.

What seems strange is that I made a SELECT * on this one : glpi_plugin_formcreator_answers 
And the table contains data obtained after filling the forms I created, but the plugin_formcreator_forms_answers_id and plugin_formcreator_question_id are always equal to 0, so when the query asks for ` plugin_formcreator_formanswers_id = '6'` an error occurs.

**Comment by btry** [comment]
Hi,

This is not normal. These inconsistencies are critical. You really need to check the integrity of all files of the plugin. I don't have in mind any such bug report then I expect to find something wrong in your setup.

**Comment by ClementChamayou** [comment]
Soooo I finished checking the integrity of all files of the plugin. And they are in perfect shape. I ran as you suggested a sha256 checksum of the plugin folder from my server and from the folder obtained from your github. Then I compared the hash expressions and they are the same. I can uninstall the plugin, download it again and install it again but I don't think it would work.
What would you suggets to explore next ?

**Comment by btry** [comment]
OK, thats good.

So, I checked again your SQL error, and I mis read the table name

> The table glpi_plugin_formcreator_answers does not exists anymore in the plugin. It should be glpi_plugin_formcreatoranswers .

I confused with the table glp_plugin_formcreator_**form**_answer which existed and was renamed glpi_plugin_formcreator_**form**answers. Don't ask why, I remember reading your comment twice to be sure about the table name. Sorriy for the wast of time checking your files.

That said, your error remains strange. You checked all tables, and you did not find anything wrong ?

Please check again the table glpi_plugin_formcreator_answers. It should look like the following :

```SQL
DESCRIBE glpi_plugin_formcreator_answers

+-----------------------------------+----------+------+-----+---------+----------------+
| Field                             | Type     | Null | Key | Default | Extra          |
+-----------------------------------+----------+------+-----+---------+----------------+
| id                                | int(11)  | NO   | PRI | NULL    | auto_increment |
| plugin_formcreator_formanswers_id | int(11)  | NO   | MUL | 0       |                |
| plugin_formcreator_questions_id   | int(11)  | NO   | MUL | 0       |                |
| answer                            | longtext | YES  |     | NULL    |                |
+-----------------------------------+----------+------+-----+---------+----------------+

```

Source code of the SQL Schema from tag 2.11.4
https://github.com/pluginsGLPI/formcreator/blob/v2.11.4/install/mysql/plugin_formcreator_empty.sql#L4

**Comment by ClementChamayou** [comment]
Nope that's what's confusing. Well my tbale isn't exactly yours but I don't think the differences matters, here is what I got : 
![image](https://user-images.githubusercontent.com/71630883/124616905-c5bdf580-de76-11eb-81ee-0b0242a2ffbf.png)

**Comment by btry** [comment]
Maybe you're checking the wrong database ? Check its name against the DB found in the file glpi/config/config_db.php

**Comment by ClementChamayou** [comment]
I checked its name against the one you suggested and they are the same. 

For the serveur adress, why to you want me to check ? (it's the right one btw)

So if my structure is very old, how can I refresh it ? Yet during install I used path/cliinstall.php --force-install which normally does a forced fresh install right ? So I shouldn't have this old structure, yet I still got it.

**Comment by btry** [comment]
> For the serveur adress, why to you want me to check ?

I already had to search a problem and finally found the customer was working on the wrong DB or server. Then when things looks really weird, it's a good idea to double check.

Same server and DB, then this eliminates a possible problem.

> So if my structure is very old, how can I refresh it ? Yet during install I used path/cliinstall.php --force-install which normally does a forced fresh install right

No, this a bit more complex. Table creation have a statement IF NOT EXISTS. Then the table may have an old structure if it existed in the DB when you forced the install, and in such case, the old structure is not updated. You can update the structure to match the description I shared above. 

For now I still don't see why some SQL queries fail to find the column```plugin_formcreator_questions_id```

**Comment by ClementChamayou** [comment]
Hi, thank you for your answer !

Sooo I couldn't find how to update the table, so what my collegue did was to drop the table, and then to recreate it using the structure code in formcreator>install>mysql>plugin_formcreator_empty.sql

And guess what ? It worked ! I don't know why those little changes were this paramount. 

Anyway, thank you again for all the pieces of advice you gave me.

Best regards

**Comment by btry** [comment]
Hi

Good news.

> when creating a ticket target, when I chose "Catégorie -> égale à la réponse à la question" no question matches, whatever the type is (I tried them all). Do you know why ?

The list shows only questions of type Dropdown, with sub-type ITIL Category. All other questions are ignored.

**Comment by ClementChamayou** [comment]
Well, I tried it and it worked too, thank you for this beautiful tool you created.

**Comment by btry** [comment]
You're welcome.

 As your issue is solved, I close.
