### ISSUE TITLE
Set Ticket Form as default Ticket

### ISSUE THREAD

**Issue by ThibautStark** [pluginsGLPI/formcreator#2296]
Hello again,

I'd like to redirect the "Create a ticket" button to a FormCreator form. I'd like to know if it was easily doable through the GLPI graphic interface or if it was necessary to go through the code ? And if it is necessary to go through the code, where would it be, because I'm not finding any redirection to ticket.form.php in the code.

**Comment by btry** [comment]
Hi

I which interface ? self service or helpdesk ?

**Comment by ThibautStark** [comment]
Both if it's possible.

**Comment by btry** [comment]
For self-service the closest would be to enable the service catalog and provide only one form.

For helpdesk, or i you strictly want the feature you described, a change in the source code is requred.

**Comment by ThibautStark** [comment]
Problem solvd, I found the lines to change to get what I wanted
