### ISSUE TITLE
Bug plusieurs groupes valideur

### ISSUE THREAD

**Issue by Bliebard** [pluginsGLPI/formcreator#2301]
Bonjour,
Lors de la création d'un formulaire, il est possible de choisir plusieurs  potentiels validateurs ou groupe de validateurs.
Lorsque je choisis plusieurs potentiels groupes de validateurs et que je créais ma requête de formulaire en sélectionnant un de ces groupes, tous les utilisateurs de tous les groupes peuvent valider la requête. (est ce normal ?)

**To Reproduce**
1. créer un formulaire
2. ajouter plusieurs groupe validateurs (groupe A et Groupe B)
3. création d'une requête de formulaire en choisissant un des deux groupes pour validation du formulaire (par exemple le Groupe A)
4. Connexion sur le compte d'un des utilisateurs du groupe A: il peut valider la demande de formulaire.
5. Connexion sur le compte d'un des utilisateurs du groupe B : il peut aussi valider la demande de formulaire. Même si celui ci n'appartient pas au groupe A.

Normalement seulement les utilisateurs du groupe A peuvent valider le formulaire, puisque c'est ce groupe qui a été choisi dans la demande de formulaire. (Ou alors je n'ai pas bien saisi le principe de validation par groupe)

Mon Glpi fonctionne sous apache2 sur une machine Linux Debian 10 (buster)
version de GLPI : 9.5.5
version de Formcreator :2.11.4 

Merci pour vos retours

**Comment by btry** [comment]
Bonjour

Il y a bien un bug. Essayez le patch i dessus. Attention, il est basé sur la version 2.12.0 sur le point de sortir. Si le patch ne s'applique pas, il faudra le porter sur la version 2.11.4

**Comment by btry** [comment]
Bonjour

A défaut de retour, je suppose que le fix fonctionnera pour vous, je fusionne pour la prochaine release.
