### ISSUE TITLE
Cacher l'option "créer un ticket" pour ne laisser que l'option "Formulaire"

### ISSUE THREAD

**Issue by Mysterehyde** [pluginsGLPI/formcreator#2306]
Bonjour, 

J'ai une question ;-)

Depuis mes MAJs sur GLPI 9.5.5 et FormCreator 2.11.4, je n'arrive plus à trouver un réglage pour ne laisser que les Formulaire comme option de création de ticket.
En effet mes utilisateurs ont maintenant l'option "Créer un ticket" directement affiché dans le menu :
![image](https://user-images.githubusercontent.com/65338737/125786044-fa1f7bb0-e231-46f4-9be4-4758cb4ed0c4.png)
Et si je fais comme avant, et que j'enlève l'option de profil qui permet de créer un ticket.... ils ne peuvent plus créer de formulaire non plus ! 
J'ai raté quelque chose dans les notes de mises à jour??

Merci d'avance !

**Comment by btry** [comment]
Bonjour

Quelles étaient les versions de GLPI et Formcreator quand ça fonctionnait ?

**Comment by Mysterehyde** [comment]
On était en :
FormCreator 2.9.2 
GLPI 9.4.5

Après on a fait plusieurs MAJ pour lesquelles on avait pas eu ce problème. C'était donc également fonctionnel pour moi en 9.4.5 et 2.9.1.

Merci !

**Comment by Mysterehyde** [comment]
Je dois aussi dire que ça ne me dérange pas d'avoir une solution de contournement provisoire, par exemple en modifiant le CSS pour cacher le champ de "création de Ticket" du menu... mais bon je préfèrerais juste avoir raté une nouvelle option quelquepart ;-)

Je peux également vous dire que dans notre workflow, les utilisateurs utilisants le formulaire crééent directement le ticket, il n'y a pas d'étape de validation du formulaire avant la création en ticket, je ne sais pas si cela influe..

**Comment by btry** [comment]
Si vous activez le mode catalogue de services, vous n'aurez plus du tout de menu. Le plugin va remplacer toute l'interface de GLPI par la sienne. Vous aurez accès à tout , sauf la création de tickets.

**Comment by Mysterehyde** [comment]
Bonjour, 
Merci pour vos idées, mais j'ai quand même quelques problèmes avec le catalogue de services.. car il vient cacher des menus que nous utilisons comme la foire aux questions ou encore les flux RSS par exemple..

Je ne comprends pas cette différence de comportement constatée depuis la MAJ du coup..

**Comment by btry** [comment]
Bonjour

Il y a 2 modes de fonctionnement pour accéder à la FAQ. 

![image](https://user-images.githubusercontent.com/14139801/125903213-08fc1cbe-996c-4f7a-b2da-a702b63a5e3a.png)


Par défaut les éléments de FAQ apparaissent avec les formulaires en fonctin de la catégorie et des mots clés. La contrainte est de relier les catégories de KB et les catégories de formulaire. Cela se passe dans l'édition de ces dernières.

![image](https://user-images.githubusercontent.com/14139801/125903405-ea020fe8-2583-47f5-8ebb-0fbc4d224dc8.png)

L'autre mode sépare les formulaires et la FAQ, via un menu dans le panneau de gauche. Il n'y a pas besoin de faire de liaison entre les 2 types de catégories. Pour activer ce mode, vous devez éditer les paramètres du plugin dans l'onglet Formulaires de l'entité qui vous intéresse (probablement la racine). Il y a un système d'héritage des paramètres d'une entité vers les entités filles.

![image](https://user-images.githubusercontent.com/14139801/125903052-c4d34efe-e64a-43b6-84aa-9637da9faf67.png)

**Comment by Mysterehyde** [comment]
Bonjour, 

Merci pour cette réponse très détaillée ! 

J'admets que ça viendrait pas mal changer nos habitudes (ainsi que toutes nos docs , snif) mais ça pourrait effectivement le faire... 
Tant que je n'ai pas encore bien testé, je reste un peu dubitatif, je dois bien l'avouer, mais ça résoudrais mon problème actuel, car si je comprends bien, l'ancien mode de fonctionnement qui permettait d'avoir l'un et/ou l'autre ne sera plus d'actualité, jamais..?

Merci en tout cas !
