### ISSUE TITLE
Champs titre dans un ticket via formcreator

### ISSUE THREAD

**Issue by AdminNge** [pluginsGLPI/formcreator#2309]
Bonjour,

Avant toute chose merci pour votre travail, Formcreator devient clairement un incontournable si on souhaite rendre plus accessible GLPI à ses utilisateurs.

Dans notre cas, nous n'utilisons GLPI que pour la partie gestion des tickets.
Afin de simplifier la création des tickets, j'ai opté pour un choix en "Catalogue de service simplifié" sur mon entité.

J'ai par la suite créés des formulaires en fonction des types de demandes, par exemple "Création d'un nouveau profil", Demande de droits d'accès etc... Jusqu'ici tout va bien.

Je souhaite créer un formulaire, à l'image de ce que propose déjà GLPI sans Formcreator, pour la création d'un ticket libre.
J'ai donc créé un formulaire "Demande d'assistance" et j'ai ajouté une section avec dedans deux questions :

- Titre (Texte) / qui servira à résumer le problème
- Description du problème (Zone de texte) / Pour décrire en détail l'anomalie 

Mon problème est le suivant :
Pour les personnes traitants les tickets, dans le listing des tickets > champs Titre, il apparait Demande libre.
Je souhaite que ce soit le contenu de la question Titre rédigé par l'utilisateur à l'initiative du ticket qui apparaisse.
Sur des dizaines de demande par jour, il n'est pas pratique de rentrer dans chaque demande pour avoir une idée du problème à traiter, surtout si une seul personne à plusieurs demande en cours...

Je ne sais pas si je suis très clair mais je commence à sécher malgré mes recherches.

Merci du temps passé sur ma demande.

**Comment by AdminNge** [comment]
En complément pour expliquer ma question, je souhaite le même résultat que si je passe par un ticket classique GLPI en interface simplifié.
Dans ce cas de figure, le contenu du champ "Titre" est ce qui remonte quand on visualise la liste des tickets comme descriptif.

Idem quand un utilisateur ouvre un ticket par le collecteur, le champ "Titre" est automatiquement rempli avec le "l'objet" du mail de l'émetteur.

Je ne pense pas avoir la bonne pratique pour arriver à ce résultat via Formcreator. 
Merci

**Comment by btry** [comment]
Bonjour

Dans les tickets cibles, le champ "Titre du ticket" prend en charge les balises du plugin. Vous pouvez utiliser la balise correspondant à la réponse de la question "Titre" pour obtenir le résultat attendu.

![image](https://user-images.githubusercontent.com/14139801/126351758-f1a7f963-0f03-4546-8463-32400c9838ea.png)

**Comment by AdminNge** [comment]
Bonjour,

Un grand merci pour votre réactivité, votre réponse est parfaite j'ai pu arriver à mes fins.

Le sujet peut être clôturé, bonne journée à vous.
