### ISSUE TITLE
Actor field not restricting to existing GLPI users

### ISSUE THREAD

**Issue by legoulot** [pluginsGLPI/formcreator#2311]
Hello!

When answering a question of actor type, you can press enter to validate a name at any moment, which can create a label for a non using user.

**Steps to reproduce this issue:**
a. When entering the field, the list of existing users appears
b. When typing, it creates a line for the current entry, not linked to any existing user
c. This line can be validated at any time, thus adding the label in the answer
d. When the form is submitted, an error is triggered because the user does not exist

**Screenshots**
![image](https://user-images.githubusercontent.com/72995702/126622652-f1461cf5-6d40-4b57-b28c-888fa3abcfd1.png)

**Expected behavior**
The behavior should be the same as the "multiselect" type: restricting the input to existing users and not allowing to enter an invalid name, as this triggers an error at the end.

**Comment by btry** [comment]
Hi

The actors field allows requesters to type an email address, including email addresses not maching any user in DB. Then restricting to existing users is not wanted.

The best we can do is to validate each user when the user's input is complete, but this should be done while mobing all server side checks to the client side. This is a lot of work, and not yet in the roadmap.

**Comment by legoulot** [comment]
Oh ok my bad I was not aware of this behavior, I understand your point of view.
I suppose we'll have to teach our users to use their brain when filling in the forms then! (-:

Thank you for your answer, have a good day.

**Comment by btry** [comment]
The plugin will warn users as you described. Then I guess this will not hurt too much.
