### ISSUE TITLE
Formcreator 2.12.00 Filter category doesn't work properly

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2313]
**Describe the bug**
En mode catalogue de service simplifié, le filtrage des formulaires par catégorie fonctionne de manière dégradée.
Si je clique sur les lettres du nom de la catégorie, il ne filtre plus aucun formulaire et les affiche tous.  (testé sur 2 bases glpi distinctes en 9.5.5 ) . SI je clique sur le reste de la ligne ou s'affiche la catégorie, cela filtre bien les formulaires.   Lien avec la résolutioné écran ? 

**To Reproduce**
1. Activer catalogue de service simplifié
2. Afficher des formulaires et des catégories de formulaires
3. cliquer sur le filtrage par catégories sur le nom de la catégorie

**Expected behavior**
Filtrage dans tous les cas

**Screenshots**
![Capture d’écran 2021-07-22 162833](https://user-images.githubusercontent.com/78594318/126656597-dbcd6da9-36ae-4fa4-aee3-2f91f0e166ba.jpg)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser  firefox

**Additional context**

**Comment by btry** [comment]
Bonjour

Activez le mode développeur du navigateur, reproduisez le souci et voyez si il y a des erreurs JavaScript ou des erreurs de requêtes http

**Comment by mirda123** [comment]
bonjour je viens de modifier la teneur du msg d'origine; Clea vient de l'endroit ou l'on clique sur la ligne de la catégorie  :  sur les lettres du nom de la catégorie : KO, sur le reste de la ligne OK.

Je suis sur pc portable mais mon collègue reproduit sur pc fixe et écran 22 ou 24 ' 
![Capture d’écran 2021-07-22 162833](https://user-images.githubusercontent.com/78594318/126657521-8bc317fa-adc6-4faa-a6e9-e4a80ffc759f.jpg)

**Comment by btry** [comment]
Bonjour

Essayez le correctif ci dessus et dites moi si ça fonctionne.

**Comment by mirda123** [comment]
Bonjour
Ca marche parfaitement !! Merciiii , on va pouvoir utiliser cette version la du plug in  !!   : )
