### ISSUE TITLE
Target Ticket - don't list request type entity

### ISSUE THREAD

**Issue by biohazard976** [pluginsGLPI/formcreator#2314]
**Describe the bug**
J'ai un formulaire avec 3 questions de type entités. Sur les cibles de ticket, pour le choix de l'entité de destination, je n'ai aucun résultat trouvé sur la liste "Question de type entité" !!

**To Reproduce**
J'ai essayé de modifier les questions, ...Etc rien n'y fait sur la version précédente cela fonctionnait.

**Screenshots**
Exemple de question de type entité :
![image](https://user-images.githubusercontent.com/32727400/126721148-75124c03-5fad-4a47-ada7-23d0a7aef7a2.png)

Cible de ticket : liste de question type entité vide
![image](https://user-images.githubusercontent.com/32727400/126721227-7ce48745-e0ef-4994-94d5-151f146b2647.png)

**Desktop (please complete the following information):**
 - OS client : windows 10 20H2
 - Browser client : firefox 78.11 (64bits)

**Comment by btry** [comment]
Hi

Please try the above fix and feedback.

**Comment by biohazard976** [comment]
OK it's work !!
Thank you

**Comment by gorupthedevel** [comment]
you guys are the best.
