### ISSUE TITLE
Ou changer la couleur de la case de recherche de formulaire

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2317]
**Is your feature request related to a problem? Please describe.**
Pourriez-vous m'indiquer dans quel fichier et à quelle ligne je peux changer l'encadrement de la case de  recherche afin de modifier le rouge par une couleur neutre. 
De même quand on clique dans la case, l'encadrement passe cette fois en bleu (ma charte est sur du dégradé de vert). Par avance merci.

**Describe the solution you'd like**
Couleur neutre ou en lien avec la charte glpi choisie.
![couleur](https://user-images.githubusercontent.com/78594318/126772750-59922c0a-69bf-43ac-a7b9-8eee093c2d23.jpg)
![couleur2](https://user-images.githubusercontent.com/78594318/126773222-a3786143-4e68-43b7-8ba9-76818b63b1a6.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by btry** [comment]
Bonjour

Ce type de question a plutôt sa place dans le forum https://forum.glpi-project.org/ .

**Comment by mirda123** [comment]
Bonjour, 
Cela peut etre aussi une demande d'evolution pour accorder le plug in avec la charte glpi...  

Et Sur le forum, je ne recois pas de réponse a mes demandes.. aucune...
