### ISSUE TITLE
All forms displayed in the default service catalog

### ISSUE THREAD

**Issue by GuiGuiSoft** [pluginsGLPI/formcreator#2322]
**Describe the bug**
All forms displayed in the service catalog.  
_(I am not sure if it is a bug or a misunderstanding on my side)_

**To Reproduce**
1. Create a form and choose to not display it in the default service catalog
![image](https://user-images.githubusercontent.com/8069239/127179754-6dfa24c6-e440-438c-9167-61958ab1e688.png)
2. Click on Assistance > Forms

**Expected behavior**
The form is not displayed

**Current behavior**
The form is displayed

**Comment by btry** [comment]
Hi

A default form only has a  speial power compared to others. When a seearch returns no result, default forms are provided, to give a fallback solution for assistanec request. Imagine you have plenty of forms for specific problems : computer, network, softwware, . You can build a generic form which may be used when o specialized form matches.

**Comment by GuiGuiSoft** [comment]
Ok I understand !

Is there a tip (or an existing feature request) to select form displayed by default ? 
_When there are dozen of forms, the "big list" can be quite disturbing_ 😅 

Regards

**Comment by btry** [comment]
Do you want to show a form directly without having to select it first ?

**Comment by GuiGuiSoft** [comment]
Actuellement ous les formulaires sont affichés (si on ne lance aucune recherche ou si on ne clique sur aucune (sous-)categorie). 

Je voudrais choisir (et même idéalement ordonner) les formulaires qui s'affichent sur la page d'accueil (des formulaires), un peu comme on choisit ceux qui s'affichent sur la page d'accueil de l'assistance GLPI.

L'intégralité des formulaires serait toujours disponible en naviguant dans les (sous-)catégorie ou en utilisant la recherche.

**Comment by btry** [comment]
If I understand well, you need to show forms in the helpdesk, but noti in the service catalog.

The 2 interfaces are mutually exclusive, then I think you can get the expected behavior by restricting the profiles which are allowed to use a form.

![image](https://user-images.githubusercontent.com/14139801/127200557-ff44dc22-1d81-4a57-b448-668cdc293145.png)

Select all profiles except self-service or profiles using the simplified interface.

**Comment by GuiGuiSoft** [comment]
Hello,

I understand that my issue is not a bug but a feature request so I will create a new one.

Regards.
