### ISSUE TITLE
Pouvoir mettre en forme le texte ajouté au dessus des formulaires

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2324]
**Is your feature request related to a problem? Please describe.**
Pouvoir mettre en page (Bold, retour à la ligne... ) le texte d'en-tête en mode full formulaire.
On peut le faire dans le paramétrage de l'entité mais dès qu'on enregistre , tout le texte se colle et la mise en page se supprime.

**Describe the solution you'd like**
![formC](https://user-images.githubusercontent.com/78594318/127499586-7ee93f60-cc4d-4785-b4c4-c97a0ff1058a.jpg)

**Describe alternatives you've considered**
Utiliser le plug in alerte à la place mais pas satisfaisant.

**Additional context**

**Comment by btry** [comment]
Bonjour

Essayez le patch ci dessus.

**Comment by mirda123** [comment]
bonjour

Merci je teste ca
A la ligne 124 et 135 du patch, c'est  normal d'jaouter une ligne vide ?

**Comment by btry** [comment]
Les lignes vides sont juste pour la lisibilité du code.

**Comment by mirda123** [comment]
Le patch fonctionne ! merci !
Juste une précision, si je retourne dans administration/ entité après coup  :  
![FC10](https://user-images.githubusercontent.com/78594318/128174339-c115978e-8422-4bd5-99d6-d2458460bcf0.jpg)

**Comment by btry** [comment]
Merci pour le retour. 

Pour la perte de la barre d'outil d'édition, j'ai vu cela. Vous pouvez appliquer le patch suivant : https://github.com/pluginsGLPI/formcreator/commit/f2cd1439b55699eb265da0b72d1451d24fc843a7

**Comment by mirda123** [comment]
Le second patch se corrige pas la perte de la barre d'edition d'outil dans administration - entité  ni le fait que le texte passe en htmldans cette même page . Mais ce n'est pas très grave. Au moins coté rendu, la mise en forme fonctionne , c'est top !
