### ISSUE TITLE
New Feature - link a ticket from selection in form

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2327]
**Is your feature request related to a problem? Please describe.**
Enable automatic ticket listing from a selection in the form

**Describe the solution you'd like**
We have a need to open some ticket, but with the following question:

1 . Inform the ticket that originated this demand

We currently offer a text field, and after opening the ticket, the technician uses the option to manually list the ticket through the "Linked Tickets";

![image](https://user-images.githubusercontent.com/35368369/127529900-d322baea-b889-4fbf-9554-ab51d921aefd.png)

The formcreator already has the ticket relationship option, but only for pre-populated tickets.

![image](https://user-images.githubusercontent.com/35368369/127530181-7682b978-4e3d-4a61-97db-97de0d995c03.png)

We would like to know if it is possible to create the condition "Equals to the answer to the requestion" as it exists in other fields

![image](https://user-images.githubusercontent.com/35368369/127530332-d6057f10-e1f8-4e42-9677-8625e0c3963d.png)

**Comment by btry** [comment]
Hi

If you need this feature quickly, you may want to get a quote. Fill the form below

http://portal.glpi-network.com/contact-us

**Comment by phamorais** [comment]
@btry u Can close this issue.

**Comment by btry** [comment]
Hi 

Yes, this is now implemented.
