### ISSUE TITLE
REGEXP Condition to hide the question not working

### ISSUE THREAD

**Issue by TylerVD** [pluginsGLPI/formcreator#2328]
**Describe the bug**
When using the "Hidden unless" option with Regexp, question is not hidden and Warning pops up in php-errors.log

**To Reproduce**
Create first question
![image](https://user-images.githubusercontent.com/82641169/127635282-19db389d-9614-4ffb-9a83-4d8f95250059.png)
Create next question
![image](https://user-images.githubusercontent.com/82641169/127635443-f6713dcd-8654-4492-a826-a5425c92188a.png)

Select Hidden Unless with regexp match with any value
![image](https://user-images.githubusercontent.com/82641169/127635189-ff21e580-806a-450b-94b1-934a824bd94c.png)
or
![image](https://user-images.githubusercontent.com/82641169/127636742-fd631c50-539e-4376-857f-6738bd87d0b7.png)

Go to preview, the question is displayed even without match
![image](https://user-images.githubusercontent.com/82641169/127636112-f1f50587-94c2-462f-8812-52f530d81acb.png)

Open files/_log/php-errors.log and look for 
PHP Warning (2): preg_grep() expects parameter 2 to be array, string given

> glpiphplog.WARNING:   *** PHP Warning (2): preg_grep() expects parameter 2 to be array, string given in /home/glpi/glpi-9.5.n/plugins/formcreator/inc/field/radiosfield.class.php at line 275
  Backtrace :
  ...formcreator/inc/field/radiosfield.class.php:275 preg_grep()
  plugins/formcreator/inc/fields.class.php:314       GlpiPlugin\Formcreator\Field\RadiosField->regex()
  plugins/formcreator/inc/fields.class.php:366       PluginFormcreatorFields::isVisible()
  plugins/formcreator/ajax/showfields.php:35         PluginFormcreatorFields::updateVisibility()

**Expected behavior**
This should work like the egal operator
![image](https://user-images.githubusercontent.com/82641169/127635862-edbde714-84ef-4432-b326-32c3deefb096.png)
![image](https://user-images.githubusercontent.com/82641169/127636015-c2d8cc5b-7da9-46d6-ab92-2255b5d41c76.png)
![image](https://user-images.githubusercontent.com/82641169/127636041-8f6fbb79-471a-46f9-9f48-e118dd1f4d69.png)

Server LAMP
Debian 10
PHP : 7.3
DB : 10.3.29-MariaDB
GLPI : 9.5.5
FormsCreator : 2.12.0

Client
 - OS: Windows 10
 - Browser: Firefox 90.0.2 (64 bits)

**Comment by btry** [comment]
Hi

A regular expression must begin and end with a delimiter. The delimiter is usually a slash or a hash.

I reproduce your problem, but it is solved by writing the reges **/yes/** instead of **yes**

**Comment by TylerVD** [comment]
Yes, i know. I used it in the previous version of the plugins.
In my case, i have screenshot for the 2 values "yes" and "/yes/"
![image](https://user-images.githubusercontent.com/82641169/127647571-9eacb74d-bdb8-4de6-9ce2-e99ede8b9163.png)

When i tail the logfile and display, refresh or change the previous answer, a new entry (like below)pops up each time.
![image](https://user-images.githubusercontent.com/82641169/127647691-8e9b9aac-2054-47c8-8fc3-7fc5222ba071.png)

The form doesn't contains any radio button.

**Comment by btry** [comment]
The PR above adds a valdiatin step for  the regexes in the conditions. You may want to test it, and see an error message on the bottom of the modal dialog if you use an invalid regex.

**Comment by btry** [comment]
> The form doesn't contains any radio button.

Your form does not contains any radio button, but you probably use a question of type select which is inherits from radio buttons.

**Comment by btry** [comment]
This 2nd PR will fix the PHP warning for radio and select questions compared against a regex.

Please test and feedback.

**Comment by TylerVD** [comment]
> 
> 
> This 2nd PR will fix the PHP warning for radio and select questions compared against a regex.
> 
> Please test and feedback.

Working like a charm ! Cela fonctionne nickel.
Thanks Again. Merci encore.

**Comment by TylerVD** [comment]
My other PROD bigger form is displaying correctly now.

If you need further tests, feel free to ask me.

**Comment by btry** [comment]
Thank you for your feedback.

The tests are sufficient. I can close this issue.
