### ISSUE TITLE
 form (tree structure)

### ISSUE THREAD

**Issue by virginiacorrea** [pluginsGLPI/formcreator#233]
Good day.

What I can do for a form (non-recursive) only see in the state in which it was created.

Example:
![image](https://cloud.githubusercontent.com/assets/16838689/17748994/8f12bcba-6481-11e6-84d7-6fb5d073db6f.png)

The drawback is that if given show all ...
![image](https://cloud.githubusercontent.com/assets/16838689/17749049/ca21431c-6481-11e6-9b08-df10169008a6.png)

Appear all forms ...
![image](https://cloud.githubusercontent.com/assets/16838689/17748976/73c8dfca-6481-11e6-9047-b7d7c6df5a1b.png)

It shows all the forms and this makes it possible to create or validate a different entity, therefore the form is created in an entity that does not correspond.

If anyone can help I would appreciate it.

Cordially,

**Comment by btry** [comment]
Hi

Can you tell in which entities are the two forms of your last screenshot, and tell if they are recursive ?

**Comment by virginiacorrea** [comment]
Hello they are created in each entity and are not recursive.

The version used in glpi is 090.1
I tried to 090.5 and behavior is the same.

**Comment by btry** [comment]
I don't understand well the meaning of "each entity". A form ca be in one entity and only one and viewable from sub entities when recursivity is enabled.

To ensure I understand your exact setup, just give the complete name of the entity of the forms
- Applicationes (Gestion documental)
- Alquiller > (Equipo, Escaner, Impresora, Monitor, Licencia)

I also think this would be useful to know the entity of 
Alquiller > (Equipo, Escaner, Impresora, Monitor, Licencia) [GD] 

You can find easily the complete name of the entity of a form when you open a form to modify it 

![image](https://cloud.githubusercontent.com/assets/14139801/17781103/39d3f24e-656e-11e6-9bd2-4e7874132e74.png)

**Comment by virginiacorrea** [comment]
I understand the concept of recursion GLPI.

It happens that if I'm recursively and income to form a sub-distributor.
(Form created in the sub-entity and non-recursive) creates the ticket in the parent entity.

It is not a consistent behavior because if the form is a specific entity with other specific template and an entity should create the case in the state of form, not in the parent entity.

Applicationes (Gestion documental)
Alquiller > (Equipo, Escaner, Impresora, Monitor, Licencia) [GD]
![image](https://cloud.githubusercontent.com/assets/16838689/17822857/081894ce-661f-11e6-957e-bbdc70c2cd78.png)

Alquiller > (Equipo, Escaner, Impresora, Monitor, Licencia)
![image](https://cloud.githubusercontent.com/assets/16838689/17822880/29923cb8-661f-11e6-98af-302b703f1959.png)

I hope the question remains clearer configuration.

**Comment by btry** [comment]
Hi

When you create a target for your form, you can choose some kind of policy to determine in which entity the ticket is created. By default it is **Default requester user's entity** . This policy seems to match the behavior you explained.

Just change this setting to an other value. I guess **The form entity** is better for you.

I provide a screenshot with language set to spanish.
![image](https://cloud.githubusercontent.com/assets/14139801/17921869/5d587d44-69dc-11e6-9454-c7f0c8920dfc.png)

Let me know if this solves your issue

**Comment by btry** [comment]
Hi 

Did the option in my previous message helped you ?

Thank you for your feedback

**Comment by virginiacorrea** [comment]
Hello, btry...

I apologize but had been unable to enter to give many many thanks for your contribution I could solve the problem.

Basically I lowered my plugin update for version 0.90-1.3.3 since it had but the choices you had in me the image did not appear.

Download the latest sources from github and ready.

I am very grateful for your help, can not imagine how much and how valuable to me was his contribution.

Again many thanks !!!

**Comment by btry** [comment]
Hi

I'm happy to see this plugin helps you so much. Thank you again for you feedback.
