### ISSUE TITLE
Too few arguments to function plugin_formcreator_ldap_warning_handler

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2330]
Bonjour,
j'ai migré se matin sur la dernière version du plugin. Et sur l'un de mes formulaire, je ne peux plus afficher mes objets Utilisateur/entité ,etc... même en cliquant sur le calendrier, rien ne s'affiche. 
Ce  qui est étonnant est qu'un prévisualisation, tout fonctionne..

En bas du formulaire j'ai l'erreur:
`Uncaught Exception ArgumentCountError: Too few arguments to function plugin_formcreator_ldap_warning_handler(), 4 passed and exactly 5 expected in /var/www/html/glpi/marketplace/formcreator/setup.php at line 462`

Aucun changement n'a été fait sur le formulaire avant la maj.

merci

**Comment by btry** [comment]
Bonjour

Essayer le correctif ci dessus et faites un retour.

**Comment by Riesuu** [comment]
Toujours pareil

**Comment by btry** [comment]
Vous avez PHP 7.3 ou supérieur ?

**Comment by btry** [comment]
J'ai modifié le patch, Appliquez-le le à nouveau. Cette fois ça doit passer puisque je supprime carrément l'argument en trop.

**Comment by Riesuu** [comment]
Ok ça fonctionne. Par contre je n'arrive plus à récupérer la sélection LDAP Title.

merci beaucoup pour votre réactivité

**Comment by btry** [comment]
Le code que j'ai corrigé sert à intercepter une erreur pouvant survenir pendant l'interrogation de l'annuaire. 

Peut être qu'il faudrait vérifier si l'erreur interceptée est liée à la lecture de l'attribut  LDAP Title. Le traitement des erreurs par le plugin est silencieux

**Comment by btry** [comment]
Bonjour

Dans inc/field/ldapfieldselect.class.php vous trouverez 2 appels à set_error_handler() et 2 autres appels à restore_error_handler(). 

Mettes les en commentaire et voyez si vous avez des logs dans php-errors.log concernant la lecture de votre annuaire.

**Comment by Riesuu** [comment]
Bonjour,
je viens d'effectuer les manipulations demandés, cependant, je n'arrive pas à valider l'ajout de la nouvelle question selection LDAP.Je suppose que c'est normal.

Voici le php-error

```
[2021-08-17 11:00:33] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:34] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:34] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:34] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:34] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:35] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:35] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 11:00:35] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
```

**Comment by btry** [comment]
Bonjour

Vous utilisez quelle version de PHP ?

**Comment by Riesuu** [comment]
PHP 8.0.7

**Comment by btry** [comment]
OK, la fonction a été supprimée en PHP 8.0. Il faut remplacer ces fonctions.

**Comment by btry** [comment]
Annulez la mise ne commentaire de set_error_handler(), et appliquez le patch ci dessus. Est ce que ça fonctionne ?

**Comment by Riesuu** [comment]
Toujours pareil

```
[2021-08-17 14:37:40] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 14:37:45] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 14:38:05] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 14:38:30] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
  
[2021-08-17 14:38:31] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function GlpiPlugin\Formcreator\Field\ldap_control_paged_result() in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 273
  Backtrace :
  marketplace/formcreator/inc/question.class.php:388 GlpiPlugin\Formcreator\Field\LdapselectField->prepareQuestionInputForSave()
  marketplace/formcreator/inc/question.class.php:412 PluginFormcreatorQuestion->checkBeforeSave()
  inc/commondbtm.class.php:1132                      PluginFormcreatorQuestion->prepareInputForAdd()
  marketplace/formcreator/ajax/question_add.php:43   CommonDBTM->add()
```

**Comment by btry** [comment]
Si vous avez réactivé les 2 appels à set_error_handler(), vous ne devriez plus avoir d'erreur dans les log, et si vous avez bien appliqué le patch #2359, il ne devrait plus y avoir d'appel à une méthode qui n'existe pas. Est ce que les 2 modifications sont bien inscrites dans le fichier ?

**Comment by Riesuu** [comment]
Ok je sais pourquoi, je dispose d'un dossier formcreator dans glpi/plugins ainsi que dans glpi/marketplace ...je suppose que ce n'est pas normal? Cela est peut être du à une installation en manuel et à une maj via le market place.

J'ai pu cette fois si ajouter la question, j'obtiens l'erreur suivante:
![image](https://user-images.githubusercontent.com/17006344/129731883-531e1b69-3099-4591-ab10-f005d6b47287.png)

mais le php-error est vierge.

**Comment by btry** [comment]
> je dispose d'un dossier formcreator dans glpi/plugins ainsi que dans glpi/marketplace ...je suppose que ce n'est pas normal? Cela est peut être du à une installation en manuel et à une maj via le market place.

Non, ce n'estg pas normal, et c'est effectivement ce qu'il a dû se passer pour avoir le plugin en doublon. GLPI n'a ps de farde-fou contre cela pour l'instant.

> J'ai pu cette fois si ajouter la question, j'obtiens l'erreur suivante: "Récupération des données de l'annuaire LDAP impossible" mais le php-error est vierge.

C'est par ce que le plugin fait un test de connexion à l'annuaire, mais ça se passe mal. L'erreur est interceptée pour être affichée sans être envoyée dans les logs. Désactivez les appels à set_error_handler() pour réactiver l'envoi dans les logs.

**Comment by Riesuu** [comment]
J'ai bien mes données qui s'affichent avec une erreur `PHP Warning (2): Undefined variable $limitexceeded in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 180`

php-error:

`[2021-08-17 15:20:33] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $limitexceeded in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 180
  Backtrace :
  .../formcreator/inc/field/selectfield.class.php:62 GlpiPlugin\Formcreator\Field\LdapselectField->getAvailableValues()
  ...lace/formcreator/inc/abstractfield.class.php:94 GlpiPlugin\Formcreator\Field\SelectField->getRenderedHtml()
  marketplace/formcreator/inc/question.class.php:310 PluginFormcreatorAbstractField->show()
  marketplace/formcreator/inc/form.class.php:1336    PluginFormcreatorQuestion->getRenderedHtml()
  marketplace/formcreator/front/formdisplay.php:92   PluginFormcreatorForm->displayUserForm()
`

**Comment by btry** [comment]
On avance. Ajoutez ce patch : https://github.com/pluginsGLPI/formcreator/pull/2359/commits/2dddc301f7a137ceb03c4602b89f8b5236ea6a55

puis essayez. Je pense qu'il n'y aura plus d'erreur dans les logs.

**Comment by Riesuu** [comment]
C'est parfait!
encore merci pour le travail et la rapidité du debug.

**Comment by btry** [comment]
Merci pour les retours. Je fusionne les patchs. Malheureusement la version 2.12.1 est prête, donc ils seront inclus dans la 2.12.2

**Comment by Sicoval31** [comment]
Bonjour, ayant la même erreur mais à la ligne 480 est-il possible d'avoir le patch fusionné afin de régler le problème en attendant la mise à jour du plugin ?

Uncaught Exception ArgumentCountError: Too few arguments to function plugin_formcreator_ldap_warning_handler(), 4 passed and exactly 5 expected in C:\wamp\www\glpi\marketplace\formcreator\setup.php at line 480

**Comment by Sicoval31** [comment]
j'ai modifié la ligne de code (ligne 480) en commentant /*, array $errcontext*/ et tout semble rentrer dans l'ordre : affichage du bouton valider, affichage des listes déroulante type acteur ou intitulé et des champs date
