### ISSUE TITLE
Missing translation for description in formlist

### ISSUE THREAD

**Issue by TylerVD** [pluginsGLPI/formcreator#2333]
**Describe the bug**
In the list of forms, the description is not translated like other labels. (/plugins/formcreator/front/formlist.php)

**To Reproduce**

Fill the description from the main form tab:
![image](https://user-images.githubusercontent.com/82641169/127667156-3abea1b7-1c83-4659-99bd-944c87a45136.png)

Add new language :
![image](https://user-images.githubusercontent.com/82641169/127667337-605f43b8-6891-48da-b3e9-43f963cc59c9.png)

Translate labels and save:
![image](https://user-images.githubusercontent.com/82641169/127667407-8b8824a2-ee44-4e41-b173-5e292609a037.png)

Go back to list form:
![image](https://user-images.githubusercontent.com/82641169/127667587-99997e04-1919-40e5-a0b6-455df8a46230.png)

Change language:
![image](https://user-images.githubusercontent.com/82641169/127667675-88060487-ed59-430d-94bc-8db9e7442ecf.png)

Bug : The description displayed is not the translated one.

**Expected behavior**
![image](https://user-images.githubusercontent.com/82641169/127667886-5bd29fbc-897f-4a7d-acac-756b3379d83b.png)

Server LAMP
Debian 10
PHP : 7.3
DB : 10.3.29-MariaDB
GLPI : 9.5.5
FormsCreator : 2.12.0

Client
OS: Windows 10
Browser: Firefox 90.0.2 (64 bits)

**Comment by btry** [comment]
Hi

Please try the above fix and feedback

**Comment by TylerVD** [comment]
Now Working.

![image](https://user-images.githubusercontent.com/82641169/128681599-65dbae37-080b-45c0-932b-49d2990bb61e.png)

![image](https://user-images.githubusercontent.com/82641169/128681661-a55e5b47-3633-47be-a08b-e1d2eb1e4a82.png)

**Comment by btry** [comment]
Hi

Thank you, the fix will be available in the next maintenance release.

**Comment by TylerVD** [comment]
I'm sorry, it seems to have an other issue linked to this

**Comment by TylerVD** [comment]
Editing the translation does not update the display.

Display
![image](https://user-images.githubusercontent.com/82641169/128705433-52a7d95f-9bef-4e63-8aff-4b35fc0625de.png)

But in the translations
![image](https://user-images.githubusercontent.com/82641169/128705531-2f60080b-21a0-4482-97e6-f2ce63a5cd47.png)

Where are located the transaltions in the DB ?
I have cleared my browser cache.

**Comment by TylerVD** [comment]
It's Ok with a service php restart

![image](https://user-images.githubusercontent.com/82641169/128714610-a663dd04-5bfd-4b91-8aa9-fe0e64527ed5.png)

**Comment by btry** [comment]
Hi

GLPI uses cache to manage locales. For now I did not observed problem of not applied (or not up to date ) translation. Clearing the cache may help; please wait a bit until I provide a PR to test.

**Comment by btry** [comment]
Hi

This commit should fix the cache problem 79840b41d41a5aab2a782272f5decf111e43f028

Please try it and feedback.

**Comment by TylerVD** [comment]
Fix Applied.
Edited translation now display immediatly (with a simple refresh of the page).

![image](https://user-images.githubusercontent.com/82641169/129540647-662afa15-61dd-4b20-a3ac-57b5f469266f.png)

![image](https://user-images.githubusercontent.com/82641169/129540684-04b8d889-24cd-464d-876f-c1313b679fe3.png)

**Comment by btry** [comment]
Hi

GTreat; thank you for your feedback.

Other minot translation problems were reported and fixes were added. Relese planned this week.
