### ISSUE TITLE
Target ticket description field limited to 256 characters 

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#2337]
In some forms, I need to generate a specific description for the target tickt, but in version 2.12.0 it is limited to 256 characters.

**Comment by btry** [comment]
Hi

Please show the result of the SQU query :

```sql
show create table glpi_plugin_formcreator_targettickets
```

**Comment by jvergacas** [comment]
I type this: 
![image](https://user-images.githubusercontent.com/43650152/128063714-2cf822ae-1bee-4a06-8616-da9263c769d7.png)

After saving it looks like this: 
![image](https://user-images.githubusercontent.com/43650152/128063819-50798adf-ac0d-4eb8-af9d-f9c446e669b4.png)

**Comment by btry** [comment]
The content should be stored in a column of type LONGTEXT. This allows you approximatively 4GB  of text. 

Please show the result of the above SQL  query

**Comment by jvergacas** [comment]
CREATE TABLE `glpi_plugin_formcreator_targettickets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `plugin_formcreator_forms_id` int(11) NOT NULL DEFAULT 0,
  `target_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `type_rule` int(11) NOT NULL DEFAULT 0,
  `type_question` int(11) NOT NULL DEFAULT 0,
  `tickettemplates_id` int(11) NOT NULL DEFAULT 0,
  `content` longtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `due_date_rule` int(11) NOT NULL DEFAULT 1,
  `due_date_question` int(11) DEFAULT NULL,
  `due_date_value` tinyint(4) DEFAULT NULL,
  `due_date_period` int(11) NOT NULL DEFAULT 0,
  `urgency_rule` int(11) NOT NULL DEFAULT 1,
  `urgency_question` int(11) NOT NULL DEFAULT 0,
  `location_rule` int(11) NOT NULL DEFAULT 1,
  `location_question` int(11) NOT NULL DEFAULT 0,
  `show_rule` int(11) NOT NULL DEFAULT 1,
  `sla_rule` int(11) NOT NULL DEFAULT 1,
  `sla_question_tto` int(11) NOT NULL DEFAULT 0,
  `sla_question_ttr` int(11) NOT NULL DEFAULT 0,
  `ola_rule` int(11) NOT NULL DEFAULT 1,
  `ola_question_tto` int(11) NOT NULL DEFAULT 0,
  `ola_question_ttr` int(11) NOT NULL DEFAULT 0,
  `uuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `validation_followup` tinyint(1) NOT NULL DEFAULT 1,
  `destination_entity` int(11) NOT NULL DEFAULT 1,
  `destination_entity_value` int(11) DEFAULT NULL,
  `tag_type` int(11) NOT NULL DEFAULT 1,
  `tag_questions` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `tag_specifics` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `category_rule` int(11) NOT NULL DEFAULT 1,
  `category_question` int(11) NOT NULL DEFAULT 0,
  `associate_rule` int(11) NOT NULL DEFAULT 1,
  `associate_question` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `tickettemplates_id` (`tickettemplates_id`)
) ENGINE=InnoDB AUTO_INCREMENT=170 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by btry** [comment]
Your column is LONGTEXT. this needs more investigation.

**Comment by jvergacas** [comment]
If I enter the information into the database, it remains, but if I click the save button, it limits it to 256 characters.

**Comment by btry** [comment]
I found the problem. Search options declared some fields as strings, and for hose types, GLPI truncated itself too long content.

Try the patch above and feedback.

**Comment by jvergacas** [comment]
The fix works perfectly.

Thanks.
