### ISSUE TITLE
Filter in question object GLPI

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/formcreator#234]
Hi,

I have a question set to Assets - Computers. But I have a difficulty because this way your form to the User to list all computers and our reality would have to display only the computers of the User Group.

A tip might be to create a configuration shown All Computers or Only the User Group.
![image](https://cloud.githubusercontent.com/assets/2439826/17776691/f64a14e8-6533-11e6-8708-aa6bc94181e2.png)

Thank you.

**Comment by btry** [comment]
The plugin now obeys to profile restrictions. This issue may  be closed.
