### ISSUE TITLE
Answer tags were lost when updating formcreator to version 2.11.4

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2344]
**Describe the bug**
We use the tag "Answers" to concatenate with the titles of the tickets as shown in the image below

![image](https://user-images.githubusercontent.com/35368369/128252595-9e14edfe-1b3c-434f-ba70-fd9fcd09863c.png)

We noticed that when using for version 2.11.4 all tags were lost in the forms

![image](https://user-images.githubusercontent.com/35368369/128252684-fb883d6e-cffe-4a58-b3ab-87958ba438dc.png)

GLPI 9.5.5
Form 2.11.4

**Comment by btry** [comment]
Hi

From which version did you upgrade ?

**Comment by phamorais** [comment]
@btry Hi!

Update do 2.8.5 to 2.11.4 sorry for delay!

**Comment by btry** [comment]
HI

I think the bug occurs when upgrading to version 2.9.0

Can you show the data of your target **as it was before the upgrade** ?

Don't forget to replace the ID with the value of the impacted target ticket 

```sql
SELECT name FROM glpi_plugin_formcreator_targets WHERE itemtype='PlugiFormcreatorTargetTicket' AND items_id=42;

SELECT name FROM glpi_plugin_formcreator_targettickets WHERE id=42;
```

**Comment by phamorais** [comment]
@btry Hi!

follows!

SELECT name FROM glpi_plugin_formcreator_targets WHERE itemtype='PlugiFormcreatorTargetTicket' AND items_id=20;

![image](https://user-images.githubusercontent.com/35368369/128345526-8d568d56-ea73-432e-9add-9debba1d59b1.png)

SELECT name FROM glpi_plugin_formcreator_targettickets WHERE id=20;

![image](https://user-images.githubusercontent.com/35368369/128345655-e546db27-7a39-4e7c-bb2e-8298dfb21f33.png)

**Comment by btry** [comment]
The first request shall return a row. There is a problem. If I remember well this old design, the column name should match the name of the target ticket in the list of targets of the form. Were the queries executed on a copy of the DB before the migration ?

Maybe will find it by name.

**Comment by phamorais** [comment]
@btry Hi!

As there was a BUG reported in this issue, we did the rollback of db. 

Therefore, the query was used in the production db, and it is working.

However, I have a DEV environment so I can test the upgrade. So, if you want, I can analyze both scenarios.

**Comment by phamorais** [comment]
@btry If you want, I can provide access to our test base so you can analyze it more carefully.

**Comment by btry** [comment]
> I have a DEV environment so I can test the upgrade

Configure your dev environment with the snapshot of your GLPI before the upgrade. Take a snapshot, to easily go back to this state each time we need to retry. Try to upgrade Formcreator to the version 2.9.0 and see if the problem appears with this version. Keep the snapshot until the final solution is found.

I also think I'll have to setup a GLPI with version 2.8.5 of Formcreator, as your results are not whet I expected. Please wait a bit until I found time to build this setup.


>  I can provide access to our test base so you can analyze it 

I assume you don't subscribed support, then I cannot access your infrastructure. Obviously, in some cases this is way more efficient to investigate a bug. You may subscribe here, this is also a way to support GLPI and its ecosystem : http://portal.glpi-network.com/contact-us

**Comment by phamorais** [comment]
@btry 

Hi!
The subscription request has already been requested and is in progress, it is not a trivial process internally.

Anyway, I'll upgrade from version 2.8.5 to the last stable version on 2.9 and I'll bring you the results.

**Comment by phamorais** [comment]
@btry

I'll upgrade from version 2.8.5 to the last stable version on 2.9 and I'll bring you the results. 

What do you think and make the gradual upgrade?

1. upgrade from 2.8 to 2.9;
2. upgrade from 2.9 to 2.10;
3. upgrade from 2.10 to 2.11

and analyze test by test.

**Comment by phamorais** [comment]
@btry Hi!

I remade the following step by step and it worked

1. Upgrade GLPI 9.4.4 to 9.5.5 --> OK
2. Upgrade Formcreator from 2.8 to 2.9 --> OK
4. Upgrade Formcreator from 2.9 to 2.10 --> OK
5. Upgrade Formcreator from 2.10 to 2.11 --> OK

And the tags were not lost

1. If I upgrade formcreator from 2.8.5 to 2.10.4 --> OK;
2. But if I upgrade formcreator from 2.8.5 to 2.11.4 the error happened;

**Comment by btry** [comment]
Interesring.

Then the error is probably In the upgrade code between 2.10.4 and 2.11.4.

**Comment by btry** [comment]
Hi 

I checked the upgrade code : 
There is only one place impacting the columns of impacted data : it is in the migration from 2.8 to 2.9.

When upgrade issues occurs on old version and a fix is found, then newer version of the plugin have difference in old upgrade code. This is true for the 2.8 to 2.9 upgrade : I found a fix on the upgrde code of the columns target_name (which is related to your issue).

I think we need to operate differently to find where is the bug. We need to use the latest version of Formcreator (2.12.0) but modify the upgrade code to stop or pause between each version jump, to view in the database if the column's data become  broken.

I created the following patch which waits or a keyboard input before each upgrade step. It will enable when upgrade is exsecuted from CLI only. I did not tested it., I hpe the Symfony framework used in CLI upgrade won't alter the behavior of the code.

Use the version 2.12.0, apply this patch and run the upgrade from 2.8.5 to 2.12.0. Before each step, check in the DB if the data is correct.

To run the upgrade, use the following command 

```bin/console glpi:plugin:install formcreator```

If the patch works well then you will have a prompt tellong to which versio nyou need to upgrade. Type y (lower caps) to proceed, any other key to exit and go back to your shell.

```diff
diff --git a/install/install.php b/install/install.php
index 4b3caf4f..4c2dd4f4 100644
--- a/install/install.php
+++ b/install/install.php
@@ -135,6 +135,19 @@ class PluginFormcreatorInstall {
--- a/install/install.php
+++ b/install/install.php
@@ -135,6 +135,19 @@ class PluginFormcreatorInstall {
       ini_set("max_execution_time", "0");
       ini_set("memory_limit", "-1");
 
+      if (isCommandLine()) {
+         // Pause : wait for keyboard input
+         echo "Do you want to proceed upgrade to $toVersion ?  Type 'y' to continue: ";
+
+         $handle = fopen ("php://stdin", "r");
+         $line = fgets($handle);
+         if(trim($line) != 'y'){
+            echo "ABORTING!\n";
+            exit;
+         }
+         fclose($handle);
+      }
+
       $suffix = str_replace('.', '_', $toVersion);
       $includeFile = __DIR__ . "/upgrade_to_$toVersion.php";
       if (is_readable($includeFile) && is_file($includeFile)) {
```

**Comment by phamorais** [comment]
Hi @btry 

How I apply this path?

**Comment by btry** [comment]
Hi

Use the account 'glpi' or any other user with superadmin profile.

**Comment by phamorais** [comment]
@btry  Hi!

Got frozen without update to 2.11. I stand still for 45 minutes.

I have 143 forms..usually the update process doesn't take even 2 minutes.

![image](https://user-images.githubusercontent.com/35368369/128875496-42b14565-5cc6-4aee-b775-67087d5bcb6e.png)

**Comment by phamorais** [comment]
@btry Hi! :)

Impossible to develop a workaround for 2.11.4?

**Comment by btry** [comment]
Hi

well, I did not had feedback about a infinite loop in the upgrade process, and it seems the upgrade code was complete when you upgraded before the patch. I checked the upgrade code and I think there is no place for such lock, if it is an infinite loop.

I would try a second time after restoring the snapshot. No need to try more if it fails again. 

If this fails again the same way then maybe the patch has some unwanted effect. 

It is complicated to change the uptrgade code without doing errors then I think I need to reproduce myself.

Do ou confirm that the tags were not lost in the DB after the plugin upgraded to 2.10.2 ? This would be already useful to not replay upgrade from 2.8.

**Comment by phamorais** [comment]
@btry 

Yes I confirm.

However, there is a caveat, my production environment was with Form GLPI 9.4.4 and 2.8.5.

By keeping 9.4.4, I can go to version 2.9.2 (last stable version of v2.9), meaning that 2.9 is not compatible with GLPI 9.4.

So the tests I'm trying to do is:

I update GLPI from 9.4 to 9.5.5.

I need to upgrade form 2.8.5 to 2.11.4 or 2.12.

When I try to go straight from 2.8.5 to 2.12 (without the correction path you received) I get the following, but the plugin dont upgrade. :(

![image](https://user-images.githubusercontent.com/35368369/129029293-b26de2eb-cead-4b74-8d64-501d8c198561.png)

If  I update to clie MODE, its OK 

![image](https://user-images.githubusercontent.com/35368369/129030449-eb98da52-9298-4487-831a-2bd171a1bbec.png)

But the final result is error in table againt

![image](https://user-images.githubusercontent.com/35368369/129030717-85bd63b6-b079-4b94-a98d-68c306cc623a.png)

**Comment by btry** [comment]
The error in php-errors.log is incomplete. There must be a message before the backtrace. 

I think I should be able to reproduce by testing upgrades from 2.10.4 to 2.11.4

**Comment by phamorais** [comment]
@btry hi!

So, don't you recommend that I upgrade with GLPI 9.5.5, going from formcreator version 2.8.5 to 2.10.4 ??

I returned the database, and it would simulate upgrading from 2.8.5 to 2.10.4 in cli mode.

it's possible?

**Comment by btry** [comment]
> So, don't you recommend that I upgrade with GLPI 9.5.5, going from formcreator version 2.8.5 to 2.10.4 ??

I did a check : Formcreator 2.10.4 is allowed to run on GLPI 9.5. Then you can upgrade GLPI to 9.5.5, check if the data are still correct in the Formcreator's tables, just in case. Next, upgrade Formcreator to 2.10.4. Check again that the data are correct in the DB. Finally take a snapshot here. This will be a better starting point tu test the upgrade a few times with less iterations and manipulations.

Upgrade from CLI and GUI do the same. They execute the same code. The trick is that after feedbacks like yours, some fixes were done in ond upgrade code. The upgtraed code from 2.10.2 to 2.11.0 may be slightly different when you read it in a release 2.11.0 or a release 2.12.0, due to bugfixes. Therefore to find the bug we need to achieve the upgrade process step by step, with the latest revision of the upgrade files, those we have in 2.12.x versions. The patch was an attempt to pause the upgrade between each step. 

As this becomes a bit tricky, and the patch seems to not work very well for you, the best would be to use a debugger.

**Comment by phamorais** [comment]
@btry Hi!

I reworked the steps to try to capture everything step by step.

Step 1.  Proof of GLPI 9.4.4 and Form 2.8.5 (Before doing any updates)

![image](https://user-images.githubusercontent.com/35368369/129073184-4fc1fc4a-e846-4e72-9423-61c581ade1c1.png)

Step 2. Form with TAG in the name

![image](https://user-images.githubusercontent.com/35368369/129073308-c98d0e35-b533-47d3-9baa-7c001b310cec.png)

Step 3. doing the queries at the bank

![image](https://user-images.githubusercontent.com/35368369/129073543-f707823c-6f9d-43d9-be8a-c006e52b2345.png)

![image](https://user-images.githubusercontent.com/35368369/129073588-2c8c245a-f364-4fea-b270-65f433fa6e4f.png)

Step 4 . update formcreator to version 2.9.2

![image](https://user-images.githubusercontent.com/35368369/129074167-128d3e81-7b7f-497b-9d10-4ce22879207f.png)

Logs in php-erros.log

![image](https://user-images.githubusercontent.com/35368369/129074451-0c847450-e7e9-47b1-b67d-ecdf783d803d.png)

Logs in 'migration_to_2.9.2.log'

![image](https://user-images.githubusercontent.com/35368369/129074602-fe5733af-127c-4234-b521-a6001d4a5b98.png)

Formcreator dont update (similar I have with update in GLPI 9.5.5 and 2.10.4


![image](https://user-images.githubusercontent.com/35368369/129074852-5b62ac44-03cf-446b-b91b-129bf4b9c192.png)
![image](https://user-images.githubusercontent.com/35368369/129074745-fdf1f9fd-b6a6-4cb9-ab93-9eb342eaace5.png)

The strange thing is that in the first test I did everything worked.

I repeated these steps 2 times and got the same situation. I'm starting to believe that there is some error in the 2.8 to 2.9 update script as you mentioned earlier.

**Comment by btry** [comment]
Hi 

I'm focusing on the loss of tags in the target title.

I reproduced the bug the tags are lost in DB when upgrading to 2.9.0

**Comment by phamorais** [comment]
OK  @btry  thank you!
If there are any other tests that I can help you with, please let me know.

As I understand it, when we update from 2.8 to 2.11, the update step that goes from 2.8 to 2.9 loses the tags, right?

**Comment by btry** [comment]
Hi

After some tests, it seems that upgrading to 2.11.4 trigggers the bug. But if you upgrade to 2.12.0 or later, the bugs does not occurs.

Then I would recommend you to try to upgrade directly to 2.12.0. This makes sense as the version 2.11.4 reached end of life.

**Comment by phamorais** [comment]
@btry 
Hi!

Well, I understand your position regarding the use of version 2.12. I will perform the necessary tests, thank you very much.

**Comment by phamorais** [comment]
@btry 

I can use the version 2.12.1? 

![image](https://user-images.githubusercontent.com/35368369/129756014-710f9aab-fe2a-472d-b4ca-49f60145c125.png)

**Comment by btry** [comment]
Hi

i will publish the build tomorrow. If you have skills to use a development version, go ahead.

**Comment by phamorais** [comment]
@btry in 2.12.1 this issue was resolved!

**Comment by btry** [comment]
Hi

Good news ! Thank you for your feedback.
