### ISSUE TITLE
Bug Description  cible

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/formcreator#2345]
Bonjour,

J'ai un problème quand je veux ajouter les valeurs des questions et des réponses dans le champ description de ma cible.
Si je copie/colle et enregistre, j'ai des questions/réponses qui disparaissent.

Avant sauvegarde:
![image](https://user-images.githubusercontent.com/47602797/128355831-f9e2b34c-06c9-414e-b7e3-ee8a4a0e5682.png)

Après sauvegarde:
![image](https://user-images.githubusercontent.com/47602797/128355890-5d792f8c-0e67-4029-aa6f-970b3dfc6396.png)

**Comment by btry** [comment]
Bonjour

Il y a eu une remontée similaire il y a quelques jours. Un fix a été fait, regardez dans les issues fermées ou les PR fermées récentes. C'est cause ar la troncature de la description par GLPI a cause d'une mauvaise définition de la colonne dans les search options.

**Comment by tguichard25** [comment]
En effet ça marche avec le fix
https://github.com/pluginsGLPI/formcreator/pull/2339
