### ISSUE TITLE
Target ticket Forms : person from the question is empty

### ISSUE THREAD

**Issue by SYLWAD** [pluginsGLPI/formcreator#2346]
**Describe the bug**
in the requester or observer forms when adding "person from the question" is empty

**To Reproduce**
1. Go to 'forms'
2. Click on 'target'
3. Scroll down to 'ticket' and requester and person from the question is empty

**Screenshots**
![image](https://user-images.githubusercontent.com/21087262/128374900-ad23bf89-8aeb-4333-9aa8-acd2b85257a6.png)
![image](https://user-images.githubusercontent.com/21087262/128374958-8d6d0fee-19a2-46cb-98f1-dc5957ee617f.png)

**Desktop (please complete the following information):**
 - W10: [e.g. iOS]
 - EDGE [e.g. chrome, safari]

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/21087262/128375428-8d3b33ef-8419-4064-b150-80f42610f0cf.png)

**Comment by btry** [comment]
Hi

What is the type of the question you created to select a user ?

**Comment by btry** [comment]
Hi

Try this fix : https://github.com/pluginsGLPI/formcreator/pull/2315/files

**Comment by SYLWAD** [comment]
Hi,

where is this file located?

**Comment by btry** [comment]
download the patch from github: https://patch-diff.githubusercontent.com/raw/pluginsGLPI/formcreator/pull/2315.diff
, and apply it with the patch tool this way

- locate in the Formcreator's directory
- run **patch -p1 --dry-run < path/to/file.diff**
- check that there was no error to emulate the application of the match
- if no error, run patch again: **patch -p1  < path/to/file/diff**

then check if the fix worked for you.

**Comment by SYLWAD** [comment]
Hi,
thank you for your quick feedback.

i'm on windows

**Comment by btry** [comment]
This is not a problem : manu GNU utils ase ported for windows 

http://gnuwin32.sourceforge.net/packages/patch.htm

**Comment by SYLWAD** [comment]
![image](https://user-images.githubusercontent.com/21087262/128504623-e8303293-cdb8-4b12-8fb4-ff9555cc4f70.png)

**Comment by SYLWAD** [comment]
![image](https://user-images.githubusercontent.com/21087262/128505429-6600eb4d-a9b3-4db1-ad4f-5e1cf4c1f854.png)

**Comment by btry** [comment]
Your current directory is C:\Program files (x86)\GnuWin32\bin . You muse locate in the directory of Formcreator. In the .diff file the path to the files to patch are relative to your current directory. The argument -p 1 tells patch to truncate the a/ and b/ at the beginning  of the relative pah.You can see the path in the .diff by opening it with notepad.

**Comment by SYLWAD** [comment]
> Your current directory is C:\Program files (x86)\GnuWin32\bin . You mus locate in the directory of Formcreator. In the .diff file the path to the files to patch are relative to your current directory. The argument -p 1 tells patch to truncate the a/ and b/ at the beginning of the relative pah.You can see the path in the .diff by opening it with notepad.

If I am not on the GNU directory the patch command does not work

**Comment by SYLWAD** [comment]
> > Your current directory is C:\Program files (x86)\GnuWin32\bin . You mus locate in the directory of Formcreator. In the .diff file the path to the files to patch are relative to your current directory. The argument -p 1 tells patch to truncate the a/ and b/ at the beginning of the relative pah.You can see the path in the .diff by opening it with notepad.
> 
> If I am not on the GNU directory the patch command does not work

![image](https://user-images.githubusercontent.com/21087262/128508985-68eedd52-67c8-4e34-8c0c-03e3477c14a4.png)

**Comment by SYLWAD** [comment]
![image](https://user-images.githubusercontent.com/21087262/128512998-142f9b3d-ef83-4eff-a4b7-b481a8a24695.png)

**Comment by SYLWAD** [comment]
![image](https://user-images.githubusercontent.com/21087262/128519078-fa0726fc-64a7-4e18-ae02-2c337e0e8c0a.png)

**Comment by btry** [comment]
When a hunk fails to apply this is because the context in the files to patch is not the same as the context in the .diff file. This happens because your version has already some differences with the version I used to create the patch. There are already several patches  in the development version compared to the release. But I also see you used the --binary argument and the fiels to patch are not binary. I never reied this argument on non-binary files.

You shoud try without this argument. You can keep --verbose.

It this still doesn't work then there is for sure a context difference.  In such case I can provide to you a build of the plugin (like the one you downloaded from the marketplace or  the plugins website).

**Comment by SlYer73** [comment]
Hello,
patch correcly applied but no change for me : 
![image](https://user-images.githubusercontent.com/88546183/128519881-ecec884f-7078-400b-b445-c8eb4ec09ed8.png)

i restart my apache and my server. 
I'm on a centos7. 
![image](https://user-images.githubusercontent.com/88546183/128520680-d9f8d81e-d842-4324-91c6-a6c380b2d82b.png)

**Comment by btry** [comment]
@SlYer73 : thank you, I can go forward in the research.

Please find in the database the missing question. Next show the row as returned by a SELECT SQL query.

**Comment by SYLWAD** [comment]
> It this still doesn't work then there is for sure a context difference. In such case I can provide to you a build of the plugin (like the one you downloaded from the marketplace or the plugins website).

![image](https://user-images.githubusercontent.com/21087262/128523072-722b8924-271c-48d4-9038-e4aa74bcf978.png)
Only one succeeded

**Comment by SlYer73** [comment]
is that help you ? 
![image](https://user-images.githubusercontent.com/88546183/128523060-994b1332-b899-4f53-8ddd-8f0cabe7add4.png)

my form is configured like this : 
![image](https://user-images.githubusercontent.com/88546183/128523112-edc4cb90-bd22-405c-bccd-5762678073eb.png)
![image](https://user-images.githubusercontent.com/88546183/128523144-3ce4e111-3bff-4a15-ae5e-cf1bea6bba59.png)


sry for the GUI in french...

**Comment by SlYer73** [comment]
@SYLWAD for me the patch worked with the 2.11.4 release. Not the latest.

**Comment by SYLWAD** [comment]
> @SYLWAD for me the patch worked with the 2.11.4 release. Not the latest.

I will have to install version 11 of the plugin

**Comment by btry** [comment]
The patch should also work on 2.12.0 : it was created from this branch.

**Comment by SlYer73** [comment]
nah just wait for a patch update, because the patch doesn't solve the problem anyway. So, I think they will make a new patch for the latest release.

**Comment by SlYer73** [comment]
wait ! 
![image](https://user-images.githubusercontent.com/88546183/128524640-fb861fd0-8560-46f1-a76b-57fb5b763681.png)

**Comment by btry** [comment]
ah ! good news !

**Comment by SlYer73** [comment]
Ok guys good news, it's work ! 
![image](https://user-images.githubusercontent.com/88546183/128524807-600fafca-b9c8-4008-9200-474ac5c93162.png)

bad news, I don't know why...
I just make these command but wtf : 
![image](https://user-images.githubusercontent.com/88546183/128524912-43f2cd22-37e3-4ab6-ad5b-fbb7ffe4c862.png)

**Comment by btry** [comment]
[formcreator'2.12.1-dev.zip](https://github.com/pluginsGLPI/formcreator/files/6946106/formcreator.2.12.1-dev.zip)

Try this build : it contains the patch and al others since version 2.12.0.

**Comment by btry** [comment]
beware it is a development versoin ! use it only on a testing environment.

I plan to wait feedback for several other issues before releasing a 2.12.1 in 15 days maximum.

**Comment by SYLWAD** [comment]
> [formcreator'2.12.1-dev.zip](https://github.com/pluginsGLPI/formcreator/files/6946106/formcreator.2.12.1-dev.zip)
> 
> Try this build : it contains the patch and al others since version 2.12.0.

can i just copie this file abstracttarget.class in my forms plugin 12.0

**Comment by btry** [comment]
no : if an other patch did a change in the file but requires change elsewhere, you will break the code

**Comment by SYLWAD** [comment]
it's work with just file 
![image](https://user-images.githubusercontent.com/21087262/128526710-9166e482-56a6-4596-8ca6-ee6edd6cd1c8.png)

**Comment by SYLWAD** [comment]
> no : if an other patch did a change in the file but requires change elsewhere, you will break the code

at the time of the new release I would put the old php file

**Comment by btry** [comment]
As the solution is found, I close this issue, and mark it as duplicate.
