### ISSUE TITLE
Unable to accept New forms

### ISSUE THREAD

**Issue by BboivinFOCSS** [pluginsGLPI/formcreator#2349]
Hi Everyone !

I've just upgraded the plugins on v2.12. since then, i'm unable to accept New forms. When i'm click on "Accept", it doesn't create ticket and the forms keep stay in waiting state.

I tried on different PC and also on my Android smartphone.

Is there anyone who has already happened ?

**Comment by btry** [comment]
Hi

Do you have errors in glpi/files/_logs/php-errors.log or sql-errors.log ?

**Comment by BboivinFOCSS** [comment]
Hi,

Here's what i found in php_errors. There's no relevant errors in sql_errors file
[php_errors.txt](https://github.com/pluginsGLPI/formcreator/files/6940823/php_errors.txt)

**Comment by btry** [comment]
I see errors related to the use of a regex data validation .

Add this fix https://github.com/pluginsGLPI/formcreator/pull/2331

Then try to generate your targets

**Comment by BboivinFOCSS** [comment]
I applied the fix but it don't resolve the issue. even with a new form request

**Comment by btry** [comment]
I assume you no longer have errors in php-errors.log. do you confirm ?

**Comment by BboivinFOCSS** [comment]
Unfortunately, i've got same errors

[php_errors.txt](https://github.com/pluginsGLPI/formcreator/files/6940909/php_errors.txt)

**Comment by btry** [comment]
I got it : an other issue was opened recently for these errors, and in the thread I said that the error comes from an invalid regular expression.

The documentation of the plugin stated that the regex does not needs delimiters (usually / or #) but this is wrong. The documentation is fixed. If your regex does not has delimiters, add them. See https://github.com/pluginsGLPI/formcreator/issues/2328

But I believe this will not fix the problem to generate tickets. This may need a debugging patch.

**Comment by BboivinFOCSS** [comment]
Ok thanks for the advice
I made the changes and i don't have any errors now.

However it dont resolve my initial issue. Any idea ?
Otherwise, i have to rollback to a previous version while a patch is developping

**Comment by btry** [comment]
Hi

No idea yet, I'll provide a patch soon to generate debug information in php-errors.log. 

If you have skills and want to investigate yourself read the code in inc/formanswers.class.php, mzethods post_addItem() and post_updateItem(). In both methods you will find a call to generateTarget(). If this call returns a failure, then the formanswer status is not updated. I think this is what happens to you: somethings fails when creating the target ticket.

If you investigate and find something, share the info here. If not, wait until I find time to investigate deeper.

**Comment by btry** [comment]
Hi

I created a patch to log possible errors generated by GLPI when creating a ticket.

Please apply the following patch, reproduce your issue, and check php-errrors.log. I'm not sure you will find somethig as I tried to create an invalid ticket, and it succeded without error.

```diff
diff --git a/inc/formanswer.class.php b/inc/formanswer.class.php
index 2438cfc0..48b78545 100644
--- a/inc/formanswer.class.php
+++ b/inc/formanswer.class.php
@@ -817,6 +817,7 @@ class PluginFormcreatorFormAnswer extends CommonDBTM
             $generatedTarget = $targetObject->save($this);
             if ($generatedTarget === null) {
                $success = false;
+               Toolbox::logError('[Formcreator debug]: Failed to generate a target' . implode(' ', $_SESSION['MESSAGE_AFTER_REDIRECT'][ERROR]));
                break;
             }
             $this->targetList[] = $generatedTarget;
```

**Comment by UTU972** [comment]
Hello btry

thanks for this patch, but how do you apply it?

**Comment by btry** [comment]
You can apply a patch with the patch binay. It is available under windows and linux.

Documentation: https://linux.die.net/man/1/patch

To apply the patch locate in the Formcreator's directory and type 

patch -p1 --dry-run < path/to/patch-file.patch

If there is no error to apply the patch, repeat the command without --dry-run

**Comment by UTU972** [comment]
I applied the patch, but no new error message,

in addition when validating the form, there is no longer the pop-up indicating the validation of the form and the creation of the ticket

**Comment by btry** [comment]
Hi

Please use a testing environment with a copy of your producetion databae (I assume your problem occurs on production). Try to reproduce the bug. If you can reproduce, upgrade Formcreator (still on the testing environment) with the version below.

I'm suspecting that your bug is related to a problem I found myself a few weeks ago. It is fixed in this archive. 


[formcreator_2.12.1-dev.zip](https://github.com/pluginsGLPI/formcreator/files/6986456/formcreator_2.12.1-dev.zip)

I'm waiting your feedback quickly, as the release 2.12.1 will be released wednesday, and I wish to be sure it is fixed in this version.

**Comment by btry** [comment]
Hi @BboivinFOCSS 

The other ticket was solved, by testing the  bugfix version î uploaded here. Please test it and feedback. The problem should be solved.
