### ISSUE TITLE
Add Destination - Forms 0.90-1.3.4

### ISSUE THREAD

**Issue by Miudon** [pluginsGLPI/formcreator#235]
Hi,

When I try create a Destination nothing happens and this error occurs on sql-erros.log

GLPI 0.90.3
Forms 0.90-1.3.4
sql-erros.log

2016-08-21 08:25:14 [6849@suporte]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targettickets` (`name`,`comment`) VALUES (\'NewDest\',\'##FULLFORM##\')
  Error: Field 'tag_questions' doesn't have a default value
  Backtrace :
  inc/commondbtm.class.php:425                       
  inc/commondbtm.class.php:831                       CommonDBTM->addToDB()
  plugins/formcreator/inc/target.class.php:128       CommonDBTM->add()
  inc/commondbtm.class.php:799                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins/formcreator/front/target.form.php:14       CommonDBTM->add()
2016-08-21 08:25:14 [6849@suporte]
  *** MySQL query error:
  SQL: INSERT INTO glpi_plugin_formcreator_targettickets_actors
                      (`plugin_formcreator_targettickets_id`, `actor_role`, `actor_type`, `use_notification`)
                      VALUES (
                         , \'requester\', \'creator\', 1
                      ), (
                         , \'observer\', \'validator\', 1
                      );
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 'requester', 'creator', 1
                      ), (
                         ,' at line 4
  Backtrace :
  plugins/formcreator/inc/target.class.php:139       
  inc/commondbtm.class.php:799                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins/formcreator/front/target.form.php:14       CommonDBTM->add()
2016-08-21 08:25:14 [6849@suporte]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targets` (`name`,`itemtype`,`plugin_formcreator_forms_id`,`items_id`) VALUES (\'NewDest\',\'PluginFormcreatorTargetTicket\',\'8\',\'\')
  Error: Incorrect integer value: '' for column 'items_id' at row 1
  Backtrace :
  inc/commondbtm.class.php:425                       
  inc/commondbtm.class.php:831                       CommonDBTM->addToDB()
  plugins/formcreator/front/target.form.php:14       CommonDBTM->add()

**Comment by btry** [comment]
Hi

Have a look to this fix : https://github.com/Kahalisto/formcreator/commit/9cdb2b74375c152243b037eac8178bf645ec96e7

You should check your DB and ensure there is a default value as described in the above mentionned patch.

Next, try again and report if both errors disappeared.

**Comment by Miudon** [comment]
Hi,
Thanks a lot for these tips.
That works for me:
1. Download latest version (master) of plugin with recent fix ( #214 , #225 , #237 )
2. Disable STRICT MODE on MySQL by editing /etc/mysql/my.cnf
sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by btry** [comment]
Thank you for your feedback
