### ISSUE TITLE
Erro ao anexar arquivo obrigatorio

### ISSUE THREAD

**Issue by Rafaeldgs** [pluginsGLPI/formcreator#2351]
Quando coloco o campo Anexo (Arquivo) como obrigatório, o GLPI retorna erro " Um arquivo obrigatório esta ausente".

Porem se deixar o campo sem ser obrigatório, o anexo e inserido normalmente e o chamado é aberto.

FormCreator V 2.10
GLPI V 9.4.4

Alguem ja teve este erro, como posso corrigir, visto que preciso que o anexo seja obrigatório.

**Comment by btry** [comment]
Hi,

Formcreator 2.10 and 2.11 reached end of community  support. Use a testing environment to try the version 2.12.0, and if the bug persists, open a new issue.

Also, use English, please: I don't understand your language.

**Comment by Rafaeldgs** [comment]
Resolvido alterando o arquivo  inc / fields / filefield.class.php 

https://github.com/pluginsglpi/formcreator/commit/f70a8472

fix(filefield): broken mandatory check
Showing  with 2 additions and 1 deletion.

   private function isValidValue($value) {
      // If the field is required it can't be empty
 -     return (count($this->uploadData) > 0);
 +     $key = 'formcreator_field_' . $this->question->getID();
  +    return (count($this->uploads["_$key"]) > 0);
   }

   public static function getName() {
