### ISSUE TITLE
target

### ISSUE THREAD

**Issue by mihalab** [pluginsGLPI/formcreator#2352]
when I create formanswer with Target, when assigner in not filled in, and glpi user is not logged into glpi, ticket was created with no assigner.
if glpi user is logged, ticket created with assigned as self user
i change targetticket.class.php file this line
if (count($this->assigned['_users_id_assign']) > 0) {
         $data = $this->assigned + $data;
      }

add next:

else {
         $data['_users_id_assign'] = 0;
      }

**Comment by btry** [comment]
Hi

I need clarification to understand your problem.

What is assigner ?

There are 3 types of actors, commonly named as follow:
- requester
- observer (or watcher)
- technician (or assigned)

Also, please, create a pull request. This is easier to review, instead of applying again myself the patch (with possible misinterpretation of your instructions).

**Comment by mihalab** [comment]
technician. make pull request is hard for me because I'm not a real programmer. in targetticket.class.php i made changes at 831 line

**Comment by btry** [comment]
Thanks.

I'll look into this contribution. It should not be necessary as the current user should be assigned only if his current profile has the auto assign setting enabled.

**Comment by mihalab** [comment]
where i can find this setting? may be it's turn on?

**Comment by btry** [comment]
Administration > profiles

**Comment by mihalab** [comment]
i couldn't find this setting :(

**Comment by btry** [comment]
GLPI auto assigns the current user when the following right is enabled

![image](https://user-images.githubusercontent.com/14139801/128667698-ba0ff7d2-4d62-4279-999b-23e9e0a41eb6.png)

and the following preference is elabled at the same time

![image](https://user-images.githubusercontent.com/14139801/128667860-920e6d95-fc4a-43fe-8341-24cc63bb0c7c.png)

This should make your code change useless.

**Comment by mihalab** [comment]
"Pre-select me as a technician when creating a ticket" is working, but it was selected "No". I changed it to "Yes", and then to "No", and ticket target became nobody. Thanks!

**Comment by btry** [comment]
Hi

Ok, then no need to fix the code.

This is not mormal that the setting was not honoured  by GLPI. If you see an other profile which does not behaves as expected, this problem needs to be investigated by checking data in DB, and comparing this value with the same after each change of the setting. If you find a case, please open a issue in the GLPI repository.
