### ISSUE TITLE
Formcreator 2.12.0 Ticket cible autre que fullform bug : plus de mise en page specifique possible

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2355]
**Describe the bug**
La mise en page en ticket cible avec tableau  dysfonctionne.
J'ai eu le malheur d'enregistrer une modif sur un de mes tableaux cible (créé en version antérieure) et j'ai tout perdu..
J'essaie de re créer un tableau cible mais il ne s'enregistre pas correctement...

**To Reproduce**
1. créer ou re enregistrer un tableau

**Expected behavior**
un tableau

**Screenshots**
![bug02](https://user-images.githubusercontent.com/78594318/128877654-8a3cce09-bf00-43dc-804a-e4b3526cf3c1.jpg)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefox

**Additional context**

**Comment by mirda123** [comment]
Je corrige / complete ma demande, le pb n'est pas que sur un tableau, il est pour n'importe quelle mise en page spécifique du ticket clible de plus de 3 champs / lignes...

**Comment by mirda123** [comment]
Bonjour
Refaire ma modif je ne peux plus , j'avais 40 lignes de tableau et de questions spécifiques et dès que j'ai enregistré j'ai tout perdu. Pas de svg : (
Par contre vous devez pouvoir reproduire le pb car je l'ai sur tout mes bases qui ont cette version du plug in, je viens de  tester sur un autre 

![Cap1](https://user-images.githubusercontent.com/78594318/128999888-5cf5b93c-18b0-49be-b093-ebcb01dd0328.jpg)

j'enregistre et je retourne dedans : 
![Cap2](https://user-images.githubusercontent.com/78594318/128999909-eb06200e-f81f-44c5-b88f-df214bd5ab44.jpg)

je vais tester le patch.

**Comment by mirda123** [comment]
Le patch a l'air de corriger le pb sur ma dev , je  peux remettre des tableaux ! yeah ! Je passe en prod et je refais toute ma cible pour verif. 
Merci , ca va me sauver !

**Comment by btry** [comment]
Duplicate of #2337

**Comment by btry** [comment]
Merci pour votre retour; je ferme ce ticket.
