### ISSUE TITLE
Apres validation d'un formulaire - ticket non créé - After validation of a form - ticket not created

### ISSUE THREAD

**Issue by UTU972** [pluginsGLPI/formcreator#2357]
Bonjour à tous 

nous utilisons GLPI 9.5.5 et Form Creator 2.12.0 

depuis la mise à jour de Form Creator vers la 2.12.0, la création auto des tickets ne fonctionne plus 
voici les actions de l'utilisateur jusqu'à la création du ticket automatique 

1.  mise à jour du formulaire 
2. envoi de la validation au service RH
3. le service RH valide le formulaire 
4. Création du ticket selon le gabarit RH

il y a til un problème avec la dernière version de FromCreator ? 

je vous remercie pour votre aide 

Hello everyone

we are using GLPI 9.5.5 and Form Creator 2.12.0

Since updating Form Creator to 2.12.0, auto ticket creation no longer works
here are the actions of the user until the creation of the automatic ticket

1. update of the form
2.send validation to the HR department
3.the HR department validates the form
4. Creation of the ticket according to the HR template

Is there a problem with the latest version of FromCreator?

Thank you for your help

**Comment by btry** [comment]
Bonjour

De mémoire il y a un autre remontée de ce type pour Formcreator 2.12.0, mais il n'y a pas assez d'informations pour comprendre ce qu'il se passe. 

Pouvez vous vérifier si vous avez des erreurs SQL ou PHP dans les logs de GLPI ? Si vous trouvez quelque chose, ne mettez que l'extrait en rapport avec le souci.

**Comment by btry** [comment]
Je ne pense pas que cette erreur ait de lien avec vote problème. A priori vous avez un problème de droits dans le dossier glpi/files/_locales . Formcreator doit pouvoir y créer des sous dossiers.

**Comment by UTU972** [comment]
j'ai effectué mes tests dans un environnement de préprod
avec la version beta 2.12.1 ça refonctionne pour moi, le ticket est bien créé 
![image](https://user-images.githubusercontent.com/88826263/129448056-40de49fb-625c-4115-83fd-6ea309b719f2.png)

![image](https://user-images.githubusercontent.com/88826263/129448063-4c42f7a4-a0ff-4dfc-97d9-5d346dd3280f.png)

Merci beaucoup pour ton aide :-)

**Comment by btry** [comment]
Bonjour

C'est une bonne nouvelle. Rendez vous à la release 2.12.1 finale; je ferme le ticket, merci pour le retour.
