### ISSUE TITLE
Text Filed - HTTP ERROR 500

### ISSUE THREAD

**Issue by Miudon** [pluginsGLPI/formcreator#236]
Hi,

If I use Text Field Type for a question, the Form doesn't work.
The "HTTP ERROR 500" message appears on web  and after I try refresh it, by press F5, appears "You don't have permission to perform this action"
This error occurs even if user is a Super-Admin profile
The same thing doesn't occurs if i use Text-Area field type and the form works very well.

I tried use this on the versions:
GLPI 0.90.3
glpi-formcreator-0.90-1.3.4.tar
glpi-formcreator-0.90-1.3.3.tar
glpi-formcreator-0.90-1.3.2.tar

**Comment by btry** [comment]
Hi

Please check your HTTP server's logs. There is probably useful info to fond where in the code the error occured. As you tried several versions of the plugin, try to locate the error matching the latest version.

Thank you

**Comment by Miudon** [comment]
Hi,
Thanks a lot for your answer.
That works for me!!!!
The error was fixed after apply these commands:
# sudo apt-get install php-xml
# sudo apache2ctl graceful

I followed your tip and the log /var/log/apache2/error.log shows me up the following error
The error was fixed after apply these commands:

sudo apt-get install php-xml
sudo apache2ctl graceful

[Mon Aug 22 07:50:41.422981 2016] [:error] [pid 43749] [client ip:50469] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/servicos/plugins/formcreator/inc/fields/text-field.class.php:8\nStack trace:\n#0 /var/www/html/servicos/plugins/formcreator/inc/form.class.php(936): textField->isValid('milt')\n#1 /var/www/html/servicos/plugins/formcreator/front/form.form.php(50): PluginFormcreatorForm->saveForm()\n#2 {main}\n  thrown in /var/www/html/servicos/plugins/formcreator/inc/fields/text-field.class.php on line 8, referer: http://IP/plugins/formcreator/front/formdisplay.php?id=2

**Comment by dethegeek** [comment]
I was not expecting this kind of error. Thank you for your feedback. 

Let's keep the issue open : there is a check to add at the installation time of the plugin

**Comment by btry** [comment]
https://github.com/pluginsGLPI/formcreator/pull/238

**Comment by btry** [comment]
patch merged
