### ISSUE TITLE
Target Type : "Incident" ou "Demande"

### ISSUE THREAD

**Issue by EnLef** [pluginsGLPI/formcreator#2363]
Dans mon ticket cible, je sélectionne le type "Demande". Mais lors de la création du ticket c'est tout le temps un ticket "Incident" qui est créé.

Bug introduit dans la version 2.12.0 et persistant sur la version 2.12.1 avec GLPI 9.5.5.

**Comment by btry** [comment]
Bonjour

Essayez le patch ci dessus. Il y a eu une perte pendant une mise en commun de code identique.

**Comment by EnLef** [comment]
Bonjour,

C'est résolu. Merci de la rapidité !
