### ISSUE TITLE
Ergonomie d'un formulaire

### ISSUE THREAD

**Issue by AdminNge** [pluginsGLPI/formcreator#2367]
Bonjour,

Est-il possible dans un formulaire de permettre d'afficher une image ?
Je souhaite montrer une photo d'un équipement réseau puis de poser des questions en dessous sous forme de boite à cocher (voyant allumé, oui non etc).

Je profite de cette question pour demander si il était possible de gérer le positionnement des questions.
J'aimerais en avoir l'une à coté de l'autre et pas forcément en dessous à la suite.

![image](https://user-images.githubusercontent.com/87705862/130201407-1f19f38f-b7f1-4816-9419-8c21b655c6ed.png)

Il y a un gros vide sur la droite des boutons, pouvoir utiliser cette espace serait un gros plus.

Merci à vous et bonne journée.

**Comment by btry** [comment]
Bonjour

Vous pouvz utiliser une question de type description pour mettre votre image.

Vous pouvez agencer les questions sur 4 colonnes et choisir la largeur des questions pour couvrir 1 colonne jusqu'à la totalité de la ligne où elle se trouve.

**Comment by AdminNge** [comment]
Merci pour votre rapidité !

Ok pour la partie description je vais passer par la.

Je n'ai pas bien compris la deuxième partie, comment les agencer sur 4 colonnes (c'est exactement ce que j'aimerais).

**Comment by btry** [comment]
Vous n'avez peut être pas la dernière version du plugin. D'ailleus p récisez toujorus votre version de Formcreator et de GLPI.

**Comment by AdminNge** [comment]
Effectivement oublie de ma part, je suis sur la dernière version V2.12.1

**Comment by btry** [comment]
Donc vous pouvez dimensionner les questions en glissant leur coin inférieur droit.

**Comment by AdminNge** [comment]
Ca fonctionne très bien, un grand merci à vous.
Le sujet est donc solutionné ;-)
