### ISSUE TITLE
2.12.1 Champs Urgence - valeur vide dans tous les cas

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2368]
**Describe the bug**
Lorsque je créé dans un formulaire un champs urgence (avec moyenne, haute, basse) et option pas de valeur vide , la valeur vide apparait quand meme dans mon formulaire.

Testé sur 2 bases distinctes

**To Reproduce**

**Expected behavior**
¨Pas de valeur vide

**Screenshots**
![FC-urg01](https://user-images.githubusercontent.com/78594318/130227352-7e4fddc4-8a4a-49ce-9856-13d56a5c75a1.jpg)

![FC-urg02](https://user-images.githubusercontent.com/78594318/130227373-12804cf0-014f-469a-8f0e-cbcc25d223f4.jpg)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefox

**Additional context**

**Comment by btry** [comment]
Bonjour

Essayez le patch ci dessus.

**Comment by mirda123** [comment]
Bonjour 
Le patch fonctionne merci !!

**Comment by btry** [comment]
Bonjour 
Merci pour votre retour.
