### ISSUE TITLE
Affectation automatique user sur ticket cible si aucun utilisateur n'est renseigné

### ISSUE THREAD

**Issue by sibt86** [pluginsGLPI/formcreator#2370]
Si aucun utilisateur spécifique n'est renseigné dans la zone "Attribué à" dans un ticket cible de formulaire, lors de la génération du ticket après validation du formulaire, un user non souhaité est quand meme automatiquement ajouté (le créateur du formulaire dans mon cas).

Si un utilisateur lambda est renseigné dans la zone "attribué à", il n'y a pas de problème et aucun compte supplémentaire n'est ajouté en plus de celui souhaité.

Desktop (please complete the following information):
 - OS: Windows10
 - Browser Chrome
 - Version 92.0.4515.131

**Comment by btry** [comment]
Bonjour

Si vous créez un ticket sans Formcreator, avec le même utilisateur, le même profil et ne choisissez aucun technicien, est ce que l'utilisateur est ajouté aux techniciens ?

**Comment by sibt86** [comment]
L'utilisateur testé initialement possède un profil qui permet de créer uniquement des tickets via formulaire.
Je l'ai ajouté dans un autre profil pour pouvoir créer un ticket sans formcreator, l'utilisateur testé est automatiquement ajouté en technicien si aucun technicien n'est précisé dans le ticket.
J'ai également essayé avec mon compte (qui avait le meme problème) et si je ne renseigne pas de technicien, mon compte est quand meme ajouté aux techniciens après création du ticket.
C'est un problème de paramétrage ?
(pour info, je suis en congés ce soir pour une semaine)

**Comment by btry** [comment]
Oui, c'est certainement un problème de paramétrage. GLPI fait cela 

Voici les réglages qui doivent provoquer ce comportement.

![image](https://user-images.githubusercontent.com/14139801/130269629-b11039ca-b640-4dbc-85c2-4789b9d8da34.png)

![image](https://user-images.githubusercontent.com/14139801/130269730-9e66a9e7-7933-433c-8df0-102414b1a765.png)

**Comment by sibt86** [comment]
Merci beaucoup.
C'était bien le problème de paramétrage indiqué.
Merci beaucoup pour la qualité de la réponse et la rapidité !
