### ISSUE TITLE
Improve filter by clicking on forms awaiting approval icon

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2371]
**Describe the bug**
Hi! I don't know if this is a bug, or a feature improvement.

The icon below exists to list all forms awaiting approval. 
![image](https://user-images.githubusercontent.com/35368369/130242786-a661666c-61ad-4157-acc8-b0c1ff72bfd6.png)

So when I clicked on the icon, I expected the result "Status > IS > Waiting for approval" with default

![image](https://user-images.githubusercontent.com/35368369/130243035-5965dcb4-30c3-4251-ab96-fda3d0731aab.png)

However, when clicking on the icon the filter comes up as "Iteems seen > Contains > "

![image](https://user-images.githubusercontent.com/35368369/130243105-71470597-7a3b-44ec-860c-2c4ce6862f24.png)

So, whenever I click on the icon to view the forms that are awaiting approval, I still have to perform one more operation to change the filter and search again.

**Expected behavior**
Click on the icon, and the filter will already be filled in as "Status > Is > wating approval"

**Comment by phamorais** [comment]
@btry Hi :)

What do you think about this issue? do you understand that it's really a bug or a lack of functionality?

**Comment by phamorais** [comment]
@btry I understand that by the time this development is no longer needed by TEclib. If you are not interested in improving this item, you can close the issue.

**Comment by btry** [comment]
Hi

Actually, this issue is already fixed. Now, when you click on the button, the filter shows the following:

![image](https://user-images.githubusercontent.com/14139801/237010387-af43a057-73de-42be-8664-b806080e27d2.png)
