### ISSUE TITLE
Filtrage par groupe

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2373]
Bonjour,
nous utilisons pas mal le plugin pour avoir des demandes en plug n play, sauf que notre GLPI est utilisé par mes tech et petit à petit par nos utilisateurs. Sauf que j'ai autant de formulaire dédié au support, que des formulaires utilisateurs (création de comptes ou autre). 

Je souhaite donc empêcher Michel de la compta d'utiliser mon formulaire pour déclarer un incident sur l'infra.Hors, aujourd'hui, nous ne pouvons appliquer le filtrage que via les profils.Cela m'est bloquant car j'ai certains de mes utilisateurs "lambda" au profil de "self service" qui doivent absolument utiliser des formulaires spécifiques. Typiquement, un responsable d'agence aura plus de formulaire que l'assistante administrative.

Ma question est, est il possible de gérer les accès aux formulaires via les groupes de GLPI et non( ou en plus) via les profils.

Merci !

**Comment by btry** [comment]
Bonjour

Formcreator ne gère pas la restriction par groupe pour le moment. Il y a besoin d'un sponsor pour financer cette fonctionnalité.

Si vous souhaitez sponsoriser la fonctionnalité, merci de remplir ce formulaire: 
https://glpi-project.org/fr/contactez-nous/

**Comment by Riesuu** [comment]
Bonjour,
d'accord, avez-vous à combien cela peut s'élever? Clairement ma société ne cotisera pas, par contre si nous sommes plusieurs à mettre chacun x euros sur notre fond propre...
