### ISSUE TITLE
Ne voir que les catégories sur la page d'accueil

### ISSUE THREAD

**Issue by AdminNge** [pluginsGLPI/formcreator#2374]
Bonjour,

Pouvez vous m'aider sur les interrogations suivantes svp,

1- Est-il possible de n'afficher que les catégories sur la page d'accueil ?

Sur mes formulaires, j'ai bien défini Page d'accueil "Non" mais ils apparaissent quand même par défaut.
Ils sont pourtant bien affectés à des catégories.

![image](https://user-images.githubusercontent.com/87705862/130761153-4d5498d8-1f63-4b80-8b39-b31fdda6b155.png)

Du coup la visibilité et l'intérêt des catégories est moins intéressent.
Il faudrait que les catégories soit affichées à la place des formulaires sur ma capture d'écran.

C'est peut être une option que je n'ai pas trouvé...
J'ai cherché des sujets sur cette demande avant de la poster mais sans trouver ma réponse.

2- Existe t-il un moyen de masquer ou supprimer "Recherches sauvegardées" et le le bouton "Voir tous" ?
Nous avons peu de formulaire du coup ça ne sera pas utilisé.

3- Les 4 boutons en haut à droite du logo GLPI sont ils paramétrables ?

![image](https://user-images.githubusercontent.com/87705862/130761330-044aee3c-4f18-425c-ad3d-7ece140572c7.png)

Par exemple, pour le bouton vert qui affiche le compteur de ticket en cours, nous aimerions qu'il affiche les nouveaux tickets même si ils ne sont pas encore attribué.
A l'heure actuelle si un usagé ouvre un ticket peut importe la demande, de base le compteur reste à 0 car c'est un "nouveau ticket" ce qui est trompeur (il a bien une demande en attente...).

Merci à vous, encore une fois le plugin est tout simplement indispensable et très pratique.

**Comment by btry** [comment]
Bonjour

1 - la page d'accueil correspond à la page après login, en interface standard. L'option que vous mentionnez n'a pas d'effet sur le catalogue de service.

2 - il n'y a pas d'option pour cacher cela

3 - les compteurs ne sont pas paramétrables. Effectivement les demandes en statut "nouveau" ne sont incluses dans aucun des 4 compteurs. Une réflexion a déjà été menée entre l'ajout d'un 5e compteur ou l'inclusion des nouvelles demandes dans le premier. L'implémentation attend un sponsor.

Si sponsoriser la fonctionnalité (ou celles du point 2) vous intéresse, merci de faire une demande ici : https://glpi-project.org/fr/contactez-nous/

**Comment by AdminNge** [comment]
Merci de votre retour.

Ok pour la 2 et 3.

Par contre pour la 1, y a t-il un moyen d'y parvenir via une autre façon de faire svp ?

**Comment by btry** [comment]
Uniquement en modifiant le code du plugin.

**Comment by AdminNge** [comment]
Très bien merci, je ne souhaite pas modifier le code source du plugin ou même de GLPI donc je vais partir du principe que c'est comme ça.

Bonne journée à vous
