### ISSUE TITLE
[2.12.1] Object is not associated with ticket 

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#2377]
Hi,

In GLPI 9.5.5 and Formcreator 2.12.1, when I create a new form, I cannot associate an object with the ticket created. 
![image](https://user-images.githubusercontent.com/43650152/131019577-b338a8cf-657e-4489-8575-dfd6c841bb66.png)

![image](https://user-images.githubusercontent.com/43650152/131019735-610dd6e2-c435-498d-aedb-5b3c4ee74721.png)

In forms imported from previous versions, the object question appears normally but if I edit the question and click on the save button, the ticket will not show the object question either.

**Comment by jvergacas** [comment]
Hi,

The support/2.12.0 version has the same problem.

**Comment by btry** [comment]
Hi

Ok, I'll investogate on it.

**Comment by btry** [comment]
Hi

I must disable a choice restriction on the impacted dropdown.  Have the following workaround https://github.com/pluginsGLPI/formcreator/commit/2cd2bd62e8767b8eba63f0a617053a0fed6ea44d

**Comment by jvergacas** [comment]
Hi @btry 

Thanks, now it's working.

**Comment by btry** [comment]
Hi

Thanks, I close.
