### ISSUE TITLE
Wrong Italian translation

### ISSUE THREAD

**Issue by rizrob66** [pluginsGLPI/formcreator#2378]
Thanks for the plugin, it's great, 
I would like to make a small contribution by pointing out that

"Displayed unless" is currently translated as "Mostra se" 
the correct translation is instead 
"Mostrato a meno che"

Also "Hidden unless" is currently translated as "Nascosto se"
the correct translation is instead 
"Nascosto a meno che" 

The meaning is very different, and it confused me a lot in the creation of conditional fields. 
I thought there was a bug. 
Check well even google translator translates them as I reported there.

Thanks Roberto

**Comment by btry** [comment]
Hi

I checked the translation on transifex, and it appears that your change is properly saved in Transifex. I had to update locales today then next release should be OK.

Thank you for your contribution.
