### ISSUE TITLE
Issue link menu with the front form

### ISSUE THREAD

**Issue by cillox54** [pluginsGLPI/formcreator#2379]
**Describe the bug**
GLPI 9.5.5
Plug-in Formcreator 2.12.1

The link from the front formcreator open this path /marketplace/formcreator/front/form.php but if the replace "marketplace" with the "plugins" /plugins/formcreator/front/form.php open correctly.

**To Reproduce**
1. Go to Menu Administration, Form
2. Click on Form
3. See error 500 Error. Internal Server Error.

**Expected behavior**
When the user click the form, he can see the front of the form plug in.

**Screenshots**
Error message
![Screenshot_marketplace](https://user-images.githubusercontent.com/68488544/131240544-cfde71cc-787f-487c-9baa-1000ae3a8749.png)

Replace path 
![Screenshot_plugins](https://user-images.githubusercontent.com/68488544/131240515-81495553-6ebb-4e1c-8de7-797363ad25fb.png)

**Comment by btry** [comment]
Hi

In which folder Formcreator is installed ?

**Comment by cillox54** [comment]
Hi,

Folder plugins is the default folder for this purpose, the complete path is */plugins/formcreator/


De: btry ***@***.***>
Enviado el: domingo, 29 de agosto de 2021 02:56 a. m.
Para: pluginsGLPI/formcreator ***@***.***>
CC: cillox54 ***@***.***>; Author ***@***.***>
Asunto: Re: [pluginsGLPI/formcreator] Issue link menu with the front form (#2379)


Hi

In which folder Formcreator is installed ?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FpluginsGLPI%2Fformcreator%2Fissues%2F2379%23issuecomment-907747418&data=04%7C01%7C%7Cf70b060540bb4d7a54bb08d96ac27200%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658205628684824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jcbZ%2F8qEudA%2FRF7ZuuQEfgmmi1Nra%2BK9iINoAyLGJh0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQKQ2YF7YN4NGGRVJZP66M3T7HRZDANCNFSM5C74OKAQ&data=04%7C01%7C%7Cf70b060540bb4d7a54bb08d96ac27200%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658205628684824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2e5BiZMONV0iIz9emcbPPVtVpZ3pGL7m7jBUGyafJO8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf70b060540bb4d7a54bb08d96ac27200%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658205628694781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6k8%2FBfF39fVf0k7rG4aPpUz4itvDp3MCPJ8wdN7Y3wY%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf70b060540bb4d7a54bb08d96ac27200%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658205628694781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rKHeoa9Cs9lPxkT%2BxZRvJUmcdWWPOQ%2BM1SNV9R1g%2BCo%3D&reserved=0>.

**Comment by btry** [comment]
Hi

I'm suspecting that you have a second copy of Formcreator in the folder marketplace. 

If I'm right, then read setup.php of both copies. At the beginning there is a constant telling the version. Keep the most recent version, and remove the old one. I think this will solve your problem.

**Comment by cillox54** [comment]
Hi,

Thankyou, in fact exist two folders, old plugins and new marketplace in both exist formcreator. The problem is solved.

King regards.



-------- Original message --------
From: btry ***@***.***>
Date: 30/08/2021 04:16 (GMT-06:00)
To: pluginsGLPI/formcreator ***@***.***>
Cc: cillox54 ***@***.***>, Author ***@***.***>
Subject: Re: [pluginsGLPI/formcreator] Issue link menu with the front form (#2379)


Hi

I'm suspecting that you have a second copy of Formcreator in the folder marketplace.

If I'm right, then read setup.php of both copies. At the beginning there is a constant telling the version. Keep the most recent version, and remove the old one. I think this will solve your problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FpluginsGLPI%2Fformcreator%2Fissues%2F2379%23issuecomment-908182079&data=04%7C01%7C%7C34e2d146385a4015674808d96b96c82d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659117608957236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X8R9675qeGtokyOx1U4Yry9UCIl7RxktA56wRPFuVrU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQKQ2YBKJBR5QM2RCZDWT3DT7ND45ANCNFSM5C74OKAQ&data=04%7C01%7C%7C34e2d146385a4015674808d96b96c82d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659117608957236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pWUzPki1jLEzJ0PQNXPsdczmYn%2BdyJQSFsDzkXhrLGw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C34e2d146385a4015674808d96b96c82d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659117608967204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Dr3w9VZffz4%2B7wxAXHtDFY0hBQkv7a8kyh0%2FgBDMrlM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C34e2d146385a4015674808d96b96c82d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659117608967204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xqGxIU6nydxAh1FFIyHOoH1W8AbkeLCvE%2BTNAJIUEks%3D&reserved=0>.

**Comment by btry** [comment]
Hi

You're welcome.
