### ISSUE TITLE
KB disappear after 2.12.1 update

### ISSUE THREAD

**Issue by capu81** [pluginsGLPI/formcreator#2381]
**Describe the bug**
KB link in the side menu disappeared after update from 2.12.0 to 2.12.1

**To Reproduce**
1. update plugin from marketplace from 2.12.0 to 2.12.1
2. in front/wizard no KB link in the left menu

**Expected behavior**
KB show in the left menu

**Screenshots**
![Immagine](https://user-images.githubusercontent.com/25194917/131322060-036a4d89-8c36-4834-8cfe-df626041e44b.png)

**Additional context**
GLPI 9.5.5

Operating system: Linux intranet 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64
PHP 8.0.9 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, snmp, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at servizi.comune.calenzano.fi.it Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Server Software: Ubuntu 20.04
	Server Version: 10.3.31-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by btry** [comment]
Hi

The version 2.12.1 has a bugfix for the settings you can find in the tab "Forms" of entities. Maybe there is a side effect.

Please check those settingsn correct them if needed and tell if the problem disappeared.

**Comment by capu81** [comment]
Thank you @btry . I've changed the value to "Distinct menu entry" and now works.
