### ISSUE TITLE
Ticket assigned to the requester (technician)

### ISSUE THREAD

**Issue by luisjosemachado** [pluginsGLPI/formcreator#2383]
**Is your feature request related to a problem? Please describe.**
When the requester is a technician and the user personalization is setting "Pre-select me as a technician when creating a ticket = yes", the ticket created through the form is assigned to the same technician.

**Describe the solution you'd like**
The ticket has not been assigned and its status is new.

**Comment by btry** [comment]
Hi

This is not a bug. Formcreator must create tickets the same way GLPI does, and this behavior is implemented in GLPI itself.
