### ISSUE TITLE
Sous catégories de la base de connaissance

### ISSUE THREAD

**Issue by bsauvajon** [pluginsGLPI/formcreator#2386]
Bonjour,

ma base de connaissance est structurée selon différents thèmes, qui ne concordent pas du tout avec les catégories de formulaires. Donc j'ai créé une catégorie racine dans ma base de connaissance, que j'ai liée à une catégorie de demande, et j'ai déplacé mes catégories de base de connaissance existantes sous cette racine.

Pourtant, dans le portail de service mes articles n'apparaissent pas avec les formulaires, je précise que j'ai bien paramétré le plugin pour qu'il fusionne les formulaires et la base de connaissance.

Est-ce que j'ai râté quelque chose ? Est-ce que c'est un fonctionnement normal ? Et si oui pourquoi cette fonctionnalité de fusion ne devrait pas être récursive ?

Merci pour votre aide

**Comment by btry** [comment]
Bonjour

La recherche d'éléments de KB dans une catégorie de formulaire ne couvre que la catégorie de KB liée à la catégorie de formulaire, pas les sous catégories de KB. C'est le comportement normal.

Aller chercher dans les sous catégories serait probablement problématique par le nombre de résultats retournés.

Il a été demandé parfois de pouvoir lier plusieurs catégories de KB à une catégorie de formulaire. C'est peut être ce qu'il vous faudrait. Cependant ce n'est pas encore implémenté.

**Comment by bsauvajon** [comment]
Bonjour,

merci pour cette réponse, effectivement pouvoir lier plusieurs catégories de kb à une catégorie de formulaire serait l'idéal. La catégorie racine que j'ai créé étant une sorte de contournement pour réaliser cette fonctionnalité.

Merci pour votre réponse
