### ISSUE TITLE
Lier un élément à un ticket

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2389]
Bonjour,
j'ai mon formulaire de création d'incident où, je demande à l'utilisateur de lier son ordinateur (vu que je ne peux pas le faire de manière automatique). 

![image](https://user-images.githubusercontent.com/17006344/132462725-7642d512-3c9f-43dd-86f4-4c61e0900ed0.png)

Mais il ne trouve aucun résultat quand je me place dans la cible et que je lui indique "réponse à la question" 
![image](https://user-images.githubusercontent.com/17006344/132463184-f6b66905-4172-40b6-8de2-4a31414607fa.png)

formcreator 2.12.1

**Comment by btry** [comment]
Bonjour

Pouvez-vous vérifier si la dernière révision de la branche support/2.12.0 présente le même comportement ? 

Il me semble avoir versé un correctif sur ce type de problème, qui n'est pas encore publié dans une release.

**Comment by Riesuu** [comment]
Question bête, ou puis-je trouver la branche support?

**Comment by btry** [comment]
ici : https://github.com/pluginsGLPI/formcreator/tree/support/2.12.0

Par contre vous devez avoir les compétences pour faire un build du plugin (installation des librairies javascript et php)

Eventuellement vous pouvez "tricher" en récupérant celles d'une release 2.12.1.

N'oubliez pas de faire le tests sur une instance dédiée, et surtout pas en prod.

**Comment by Riesuu** [comment]
Bonjour,
désolé je n'ai pas les compétences pour. Ce que je peux vous dire est qu'en 2.12.1, le problème est le même.
A votre dispo

**Comment by btry** [comment]
Bonjour

Voici un build pour tester
[formcreator-2.12.2-dev.zip](https://github.com/pluginsGLPI/formcreator/files/7152761/formcreator-2.12.2-dev.zip)

**Comment by Riesuu** [comment]
Bonjour,
merci beaucoup. J'ai tout un tas de warning qui m'empêche d'installer le plugin
![image](https://user-images.githubusercontent.com/17006344/133230802-eabcc0ab-7a06-43c8-8541-37e185a5658e.png)
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/7160541/php-errors.log)

**Comment by btry** [comment]
Bonjour

Vous avez certainement de mauvaises permissions dans votre système de fichiers. Rendez-vous sur le forum de GLPI pour obtenir de l'aide : https://forum.glpi-project.org/

**Comment by btry** [comment]
Bonjour

N'ayant pas de retour sur le problème d'association d'élément à un ticket, je ferme cette issue.
