### ISSUE TITLE
Bug in eMail notification´s 

### ISSUE THREAD

**Issue by flo1994** [pluginsGLPI/formcreator#239]
eMail notification: A form has been created
This notification receives the author only  when the form was accepted or refusey by the validator.

But then the author gets 2 email notifications. --> "A form has been created" and "Your form has been accepted by the validator."

Is it possible to fix this issue?

Version of the formcreator used is 0.90-1.4 and GLPI 0.90.3

**Comment by btry** [comment]
Hi

Can you validate the notifications with the latest revision of the plugin ?

**Comment by btry** [comment]
No feedback

Checked with 2.4.0 : the author receives a notification "Your request has been saved" after sending a form and before a validator handles it.

should be ok now.
