### ISSUE TITLE
INFO : Installation 2.12.1

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2390]
Bonjour

Version actuelle 2.11.2.

Qu'entendez vous par : 
"The install / upgrade script has been dropped. **GLPI provides a plugin management via CLI**, use it instead to install, upgrade, activate or deactivate the plugin"

> Quelles sont les commandes à executer ?
Merci

**Comment by btry** [comment]
Bonjour

Si vous êtes dans le dossier racine de GLPI, la comande d'installation (ou d'upgrade) est

php bin/console glpi:plugin:install formcreator

Des arguments peuvent être ajoutés, se référer à l'aide intégrée à la commande

**Comment by EC2311** [comment]
ok,merci,  mais alors à faire sur le serveur directement... ? de mon pc (sans remote) pas possible de le faire.
-> L'upgrade habituel fonctionne t-il toujours ?

**Comment by btry** [comment]
Vous pouvez faire la manipulation via l'UI de glpi, mais vous êtes soumis au temps d'exécution limité de PHP (30 secondes habituellement).

Et un serveur est souvent accessible par ssh  ou système similaire pour les environnements de type windows.
