### ISSUE TITLE
Question type "Object GLPI > Assets - Printers" does not filter data according to requester entity

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2391]
**Describe the bug**
When trying to use the "Assets - Printers" type question, when the applicant accesses the form, he sees the list of all printers, regardless of the printer he is part of

**To Reproduce**
1. Register printers in different entities

![image](https://user-images.githubusercontent.com/35368369/132605666-8f359c77-7707-494a-bb99-fb9cb87ecc58.png)

2. Create the question of type "GLPI Object" > "Assets - Printers"
![image](https://user-images.githubusercontent.com/35368369/132605766-519e415e-ef23-4edc-bdf8-87cac2f6e42b.png)

3. With the simplified interface open the ticket and select the created type question
![image](https://user-images.githubusercontent.com/35368369/132606050-c9843f8c-4fd2-42ff-adfc-c42fa9f43431.png)

**Expected behavior**
The user should only see the equipment related to the entity in which he is a part

GLPI 9.5.5
Formcreator 2.12.1

**Comment by btry** [comment]
Hi

In your 2nd screenshot, I see that the entity restriction is set to "Form"

![image](https://user-images.githubusercontent.com/14139801/132635132-1dd60c75-1f74-4ec2-8b70-041075624dfc.png)

If your form ins in an ancestor of entity 1 and entity 2, this behavior is normal. You may need to change this setting to change the entity restriction policy for this question.

**Comment by phamorais** [comment]
@btry hi!

Thank you very much!

After changing to the "User" constraint, the issue is resolved. 

![image](https://user-images.githubusercontent.com/35368369/132681896-e8aa21e8-6680-4b19-a5cf-b663e0d69579.png)

Question: This option will only show the assets available in the entity the user is part of?

**Comment by btry** [comment]
Hi

When you select "user" in entity restriction, the plugin uses the current active entity of the user to compute the restriction.

**Comment by phamorais** [comment]
@btry thx!
I agree that this is not a bug, it is just a configuration. Thank you very much for your support.
