### ISSUE TITLE
Validation accept with IP field fail

### ISSUE THREAD

**Issue by humbertocruz** [pluginsGLPI/formcreator#2392]
**Describe the bug**
A form with a IP address field and validation

**To Reproduce**
Create a form that needs validation from group
Create a input field type IP
Fill the form
Edit the answer and accept it
some times will show that you do not have permission to execute this action
or sometime it return to the forms answers list but with the answer not accepted
 
**Expected behavior**
Accept the answer and open  the issue

**Desktop (please complete the following information):**
 - OS: MacOS and Windows
 - Browser: Chrome
 - Version: last

**Additional context**
When Accept is pressed, the form post to the formanswer with the POST ip address who is accepting the answer.

**Comment by btry** [comment]
Hi

> some times will show that you do have permission to execute this action

Do you confirm that this error occurs only with this form ?

Also, please specify the version of GLPI and the version of Formcreator.

**Comment by humbertocruz** [comment]
GLPI 9.5.5 and form 2.12.1

**Comment by humbertocruz** [comment]
![Captura de Tela 2021-09-09 às 09 14 10](https://user-images.githubusercontent.com/187700/132683849-cdd36b1e-cf0f-452c-842a-124adc7322d8.png)
in file "formanswer.class.php" I also got that "$this->questionFields" is not a valid foreach input

**Comment by btry** [comment]
You will find a  backtrace for this error in glpi/files/_log/php-errors.log. Add it here please. By the way inspect also glpi/files/_log/sql-errors.log; and if you see an error related this this issue, show it as well.

**Comment by btry** [comment]
Hi

Try https://github.com/pluginsGLPI/formcreator/pull/2398 and feedback please

**Comment by btry** [comment]
Hi 

the above fix is validated; then I close this issue. The fix will be included in the next release.
