### ISSUE TITLE
Bloqué pour réinstaller la dernière version de Formcreator

### ISSUE THREAD

**Issue by extrapola** [pluginsGLPI/formcreator#2397]
Bonjour,

Je ne viens pas présenter un bug, c'est juste que je viens de passer avec succés de Glpi 9.1 à 9.5.5 et que je n'arrive pas sous quelque forme que ce soit à faire marcher formcreator. Je vais recréer mes formulaire, ce n'est pas un problème je ne souhaite pas garder mes données pour votre plugin, je les referai avec la dernière version. J'étais en version 0.90-1.3 et quand je fais nettoyer cela plante. J'ai tenté d'installer manuellement la version 2.4.0, cela m'a permis de faire disparaitre de la liste des plugins formcréator, mais dès que je repasse par le market pour installer la dernière version j'ai ce message d'erreur : Upgrade glpi_plugin_formcreator_answers (0 seconde)
Table 'glpidb.glpi_plugin_formcreator_answers' doesn't exist
Please, check migration log

J'ai même essayé de supprimer à la main toutes les tables glpi_plugin_formcreator_* mais il voit quand même la présence du logiciel. Si jamais vous pouviez m'indiquer la marche à suivre pour m'en sortir ce serait super sympa. Peut être dois-je passer certaines release dans un certain ordre ou alors il faut que je supprime autre chose que les tables pour que Glpi ne voit plus l'ancienne présence de formcreator. Tout ceci se passe en environnement de test, je restaure à chaque fois :)

Merci d'avance et bravo pour votre boulot colossale depuis tant d'années au vue du nombre de release,

Fabrice

**Comment by btry** [comment]
Bonjour

Supprimez toutes les tables comme vous l'avez fait, et supprimez dans la table glpi_configs les entrées ayant dans la colonne context la valeur formcreator. Il doit y avoir 1 ligne contenant un un numéro de version.

Une fois ce nettoyage fait, pour devriez pouvoir faire une installation fraîche.

**Comment by btry** [comment]
Bonjour

A défaut de retour, je ferme ce ticket.
