### ISSUE TITLE
Group Requester on Target Ticket

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/formcreator#240]
Hi,

We need to be the option of "Group Requester" on Target Ticket. This will help because all the Group must view the Tickets open the Group. I believe it is a simple change to make that will help in a lot not only for my case.

Thank you so much

![image](https://cloud.githubusercontent.com/assets/2439826/18009296/f31fbcc4-6b81-11e6-9e04-e2d03a047c3d.png)

**Comment by btry** [comment]
Hi

Implementing this option would generate many emails because a requester may belong to several groups. I think this option will be useful, but used with care.

**Comment by sidneim** [comment]
Hi, I solved this problem by using the plugin **Behavior** with the option "Use the technical group." I do not know if somebody else needs this option but can be treated using this plugin.

Thank you,
Sidnei

**Comment by btry** [comment]
Thank you for the feedback. 

If Behaviors solves this need, then it is not necessary to implement it in FormCreator.
