### ISSUE TITLE
Knowbase in Formcreator 2.12.x : selection problem

### ISSUE THREAD

**Issue by nsalguero** [pluginsGLPI/formcreator#2400]
Hi,

**Describe the bug**
Starting with Formcreator 2.12.x (including 2.12.2), with the knowledge base set as "Distinct menu entry" in root entity, when I click exactly on the name of a category of the knowledge base, I get all items of all categories (same as clicking "view all") whereas, when I click on the "line" containing the name of a category of the knowledge base, not directly on the name but next to it, I get the relevant items of that category.

**To Reproduce**
1. Go to 'knowledge base'
2. Click on the name of a category of the knowledge base, not next to it
3. See the result, which is the same as "view all"

**Expected behavior**
Show only the relevant items of the category on which I clicked.

Best regards,

Nicolas Salguero.

**Comment by btry** [comment]
Hi

It looks consistent with #2316

**Comment by btry** [comment]
Please rebase your PR on top of support/2.12.0

**Comment by btry** [comment]
Hi

Your problem should be solved by your contribution. It is merged, then I think I can close this issue.

Thank you for your contribution.
