### ISSUE TITLE
Create tab for plugin permission to GLPI profiles

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2403]
**Is your feature request related to a problem? Please describe.**
We have a profile that manages the GLPI (entities) and another that only manages the services catalog.
For this, we need the profile that has full permission to manage the entities, cannot edit / create / activate or perform any other administration operation on the forms.From what I analyzed the Plugin does not have a specific tab for permissioning only the Formcreator features.. 

Currently, the only option that allows a profile to view the administration of forms is Administration > Entities > Administration > "Update"

![image](https://user-images.githubusercontent.com/35368369/133518319-5532208a-2c12-4179-95b9-d6f90135ece7.png)

If this option is disabled, the profile will not see the option "Administration > Forms"

![image](https://user-images.githubusercontent.com/35368369/133518461-c4ba0540-4683-4982-a047-ac9de82bdb2a.png)

However, if I enable the functionality, the profile will have full editing access to the forms

![image](https://user-images.githubusercontent.com/35368369/133518579-22da004e-66b9-4d20-8756-55ceeb755cef.png)

**Describe the solution you'd like**

We would like to enable a new permission tab on the Profile, exclusively for formcreator features, such as:

- Create form
- Edit forms
- Send to trash / delete
- Change viewing permission
- 
![image](https://user-images.githubusercontent.com/35368369/133519159-be091307-5644-48cc-a405-8cd726898d5e.png)

**Comment by SkoEdi** [comment]
I will also need this feature
I don't know if it's feasible but why not manage accesses on form categories: create or edit forms only on one of the form categories

**Comment by SkoEdi** [comment]
> Hi, new rights have been implemented; they will be available in version 2.14. you need to wait the end of life of 2.13 to get a stable release with this feature.

Thanks for the info :)

**Comment by phamorais** [comment]
+1
