### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by tomSDL** [pluginsGLPI/formcreator#2404]
Good day,

How can I get all the answers when using **www.helpdesk.com/glpi/apirest.php/PluginFormcreatorFormAnswer/132**

id                          : 132
name                        : User Leaver Form
entities_id                 : 0
is_recursive                : 1
plugin_formcreator_forms_id : 3
requester_id                : 20
users_id_validator          : 0
groups_id_validator         : 0
request_date                : 2021-09-16 01:07:29
status                      : 103
comment                     :

Answers are missing or I have not specified the correct parameter more likely.

Thank you.

TC

**Comment by btry** [comment]
Hi

Do requests on the itemtype PluginFormcreatorAnswer.

If you need help, please ask on the forum : https://forum.glpi-project.org/
