### ISSUE TITLE
FormCreator 2.12.1 - filtrage par entité

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2405]
Bonjour

Formcreator propose le filtre sous-entités (formulaire/utilisateur/formulaire et utilisateur) : OK

![image](https://user-images.githubusercontent.com/42341169/133621265-6183caae-3c32-40e1-9652-e98953bb6ef9.png)

Si on ajoute une question (type choix de l'entité dans le formulaire) : il serait interessant de pouvoir filtrer alors selon la valeur choisie dans la question entité : Cas d'un formulaire 'root' + sous entité, valeur par defaut de l'entité formulaire 'root' : l'utilisateur souhaite choisir un équipement d'une autre entité...et ne voir que ceux de cette entité. Cela reviendrait alors à avoir un filtre sur 'reponse' 

Qu'en pensez vous ?

**Comment by btry** [comment]
Bonjour

Historiquement Formcreator faisait un filtrage par l'entité courante du demandeur. En  version 2.11, voulant mieux respecter le principe des entités de GLPI, le filtrage a été modifié sur la base de l'entité du formulaire. Cela a posé des problèmes pour une partie des utilisateurs, d'où l'existence de cette option.

Je pense qu'il ne faut pas donner plus de choix. Filtrer par utilisateur ne devrait normalement pas être possible : cela viole le principe de cloisonnement prévu par GLPI. Si Formcreator le permet c'est parce qu'il est compliqué de migrer fers une autre organisation de formulaires, et qu'il faudrait parfois dupliquer des formulaires dans de nombreuses entités (augmentant leur maintenance, ce qui est pénalisant). 

Quand une meilleure solution sera trouvée et implémentée, il se peut que cette option soit retirée; il faut donc éviter de l'enrichir encore plus.
