### ISSUE TITLE
Filtrer des formulaires par groupe d'utilisateur

### ISSUE THREAD

**Issue by AdminNge** [pluginsGLPI/formcreator#2406]
Bonjour,

Je suis sous la version 2.12.1 de formcreator.

Je cherche à filtrer les formulaires affichés en fonction de différents groupes d'utilisateur (ou service).

Par exemple, j'ai des formulaires dédiés à un service en particulier, il est inutile que les autres services puissent voir les formulaires en question cela pollue leurs interfaces plus qu'autre chose.

Je ne sais pas si c'est possible à l'heure actuelle.

Merci à vous pour vos lumières.

**Comment by btry** [comment]
Bonjour

Pour le moment seuls les profils peuvent être utilisés pour resteindre l'accès aux formulaires. Il faut réaliser un développement pour étendre les restrictions aux groupes.

**Comment by AdminNge** [comment]
Bonjour,

Merci, si les profils utilisateurs le permettent je peux en créer un par service afin d'affiner les formulaires qui leurs est destinés.

Par contre je ne vois pas bien ou dans la gestion des profils il est possible de paramétrer les accès à tel ou tel formulaire.

**Comment by AdminNge** [comment]
C'est bien dans un formulaire dans l'onglet "Types d'accès", merci beaucoup pour votre assistance et votre travail.

Bonne journée à vous.
