### ISSUE TITLE
Problème au sujet des dates

### ISSUE THREAD

**Issue by Vmarteel** [pluginsGLPI/formcreator#241]
Bonjour,

J'ai un problème au niveau de l'affichage de la zone de sélection date lors de la saisie d'un formulaire.
En effet la sélection de l'année remonte au maximum à 10 ans, c'est à dire 2006.

Ce qui n'est pas pratique lors de la saisie d'une date de naissance.

En vous remerciant d'avance de votre aide possible,

Cordialement,

**Comment by btry** [comment]
Bonjour

C'est une fonctionnalité du composant sélecteur de dates qui est à l'origine de votre problème.

La liste des années n'affiche que les 10 années suivant et précédant la date sélectionnée. Cela signifie que si vous cliquez sur l'année 2006, et que vous ré-ouvrez la liste déroulante des années, alors vous aurez les 10 années suivant et précédant 2006. Vous pourrez donc remonter à 1996, et ainsi de suite.

Il n'y a donc ni limitation, ni bug. 

Pour des dates de naissance, si l'année à saisir est éloignée de plus de 10 ans, il est peut être plus simple de directement saisir la date dans le champ texte au format AAAA-MM-JJ.
