### ISSUE TITLE
[Formcreator 2.12.2] : forms not displayed in the associated category when language used

### ISSUE THREAD

**Issue by enumanc** [pluginsGLPI/formcreator#2412]
**Describe the bug**
When a translation is configured on a form. The form is not displayed in the associated form's category.

**To Reproduce**
1. Configure a form translation let's say 'English'
2. Associate the form to a category
3. configure the defaut language of the form to 'French'
4. Save
5. Swith from French to English language on the top in GLPI language menu
6. Try to find your form in the form service catalogue
7. The form is displayed when we select 'see all' but the associated category is not displayed although it is if using the default language

**Expected behavior**
To see the form category displayed on the left of the service catalogue page.

**Comment by btry** [comment]
Hi

When you add translations to a form, configure it to "all languages". If a single language is set, then the form will show only if the language of the user matches.

**Comment by enumanc** [comment]
Thanks for the explanation. Ticket closed
