### ISSUE TITLE
no forms when changing entity  or profile; erreur : Criteria found both inside and outside "WHERE" key. 

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#2414]
Hi,
since update in glpi 9.5.6 and FC 2.11.2 we have an error  : Criteria found both inside and outside "WHERE" key. etc ...
before update, all works fine.

In super admin, all forms are displayed.
With a technicien+parc profile, some users have the error, others not ... ?!
When changing profile wich switch entity, no forms displayed

here the trace in phperrors.log
```
`[2021-09-21 15:52:24] glpiphplog.WARNING:   *** PHP User Warning (512): Criteria found both inside and outside "WHERE" key. Some of them will be ignored in C:\wamp\www\glpi\inc\dbmysqliterator.class.php at line 291
  Backtrace :
  inc\dbmysqliterator.class.php:291                  trigger_error()
  inc\dbmysqliterator.class.php:94                   DBmysqlIterator->buildQuery()
  inc\dbmysql.class.php:876                          DBmysqlIterator->execute()
  inc\dbutils.class.php:366                          DBmysql->request()
  inc\dbutils.class.php:409                          DbUtils->countElementsInTable()
  marketplace\formcreator\inc\form.class.php:1691    DbUtils->countElementsInTableForMyEntities()
  marketplace\formcreator\setup.php:225              PluginFormcreatorForm::countAvailableForm()
  inc\plugin.class.php:262                           plugin_init_formcreator()
  inc\plugin.class.php:224                           Plugin::load()
  inc\includes.php:106                               Plugin->init()
  ajax\notifications_ajax.php:33                     include()
  
[2021-09-21 15:52:24] glpiphplog.WARNING:   *** PHP Warning (2): Cannot modify header information - headers already sent by (output started at C:\wamp\www\glpi\inc\dbmysqliterator.class.php:291) in C:\wamp\www\glpi\ajax\notifications_ajax.php at line 37
  Backtrace :
  ajax\notifications_ajax.php:37                     header()`
```

After deactivated formcreator, no more errors (and no more forms off course).

----
Suite à la MAJ de GLPI en 9.5.6 et de FC en 2.11.2, nous rencontrons une cascade de message d'erreurs liés à formcreator.
Ces messages apparaissent sur les profils ayant accès aux formulaires (mais pas pour tous les utilisateurs de ce profils !!!!?). Pas d'erreurs en super-admin.
Sur un autre profil, qui a accès à plusieurs formulaires sur une entité spécifique, même messages ; plus aucun formulaires affichés.
Nous n'avions pas ce problème avant les updates, retour arrière impossible.
Base de test à iso version.
En désactivant FC, plus aucun messages d'erreurs.

Merci pour votre aide
Cdlt

**Comment by Sicoval31** [comment]
J'aki mis à jour glpi en 9.5.6 hier et dans la foulée vérifié les plugins et mis à jour FC. Dans le amrketplace, celui-ci apparait en V2.11.2 et non pas 2.12.2 !
Il n'est  plus dans le dossier plug-in pour ne pas créer de confusion avec le marketplace

**Comment by Sicoval31** [comment]
Probleme résolu en supprimant le dossier du marketplace et en mettant la dernière version dans le dossier plugin.
Tout fonctionne normalement, y compris les affichages des dashboards

**Comment by Sicoval31** [comment]
Ce que j'en retiens surtout, c'est que le marketplace ne va pas chercher systématiquement la dernière version à jour ! Et ce n'est pas pour me rassurer

**Comment by btry** [comment]
Vous pouvez contourner ce problème en suivant les news sur 
- facebook: https://www.facebook.com/glpiproject/
- twitter: https://twitter.com/teclib

**Comment by btry** [comment]
Le problème avec le marketplace devrait être corrigé.

**Comment by ftoledo** [comment]
can you confirm what plugin version was fixed? 
I have same issue on glpi 9.5.7 and form plugin 2.10.4

**Comment by btry** [comment]
Hi 

Form creator 2.10 is obsolete. You should upgrade to 2.12.5
