### ISSUE TITLE
FormCreator : validation requise/utilisateur/absence du bouton "tous" les utilisateurs 

### ISSUE THREAD

**Issue by ypk91** [pluginsGLPI/formcreator#2415]
Dans Accueil/Administration/Formulaires, pour "Validation requise", si le choix est "utilisateur", nous devons sélectionner un à un les utilisateurs valideur. Je n'ai pas trouvé comment sélectionner l'ensemble des utilisateurs.
![image](https://user-images.githubusercontent.com/91182488/134306427-ac8f6c0a-a180-4308-9f51-183b83593195.png)

Avec la version précédente FormCreator (2.11.3) que nous avions, en bas de la liste déroulante, il y a un bouton "Tous" qui permet d'ajouter l'ensemble des utilisateurs dans la liste de sélection. Dans l'installation de la version FormCreator 2.12.2, nous ne trouvons pas ce bouton.

![image](https://user-images.githubusercontent.com/91182488/134307178-1f98f9d0-2194-434b-882e-b517f89d99d2.png)

Le besoin initial est que les utilisateurs puissent sélectionner un utilisateur parmi la liste des utilisateurs actif GLPI. 

Nous utilisons GLPI 9.5.5 et FormCreator 2.12.2  (Edge 93.0.961.52, Windows 10 Enterprise)

**Comment by btry** [comment]
Bonjour

Il y a eu un changement sur cette dropdown pour résoudre un problème de performance quand il y a des milliers d'éléments à gérer. La dropdown est maintenant en chargement dynamique, et cela ne permet pas d'avoir un bouton pour tout sélectionner. 

Vous devriez envisager d'utiliser un groupe pour y mettre tous vos utilisateurs. et d'affecter ce groupe comme validateur.

**Comment by ypk91** [comment]
Merci de ce retour.
