### ISSUE TITLE
Form Creator 2.12.1

### ISSUE THREAD

**Issue by yves123456** [pluginsGLPI/formcreator#2418]
Bonjour
Depuis la mise à jour de GLPI en 9.5.5 sur un des formulaire j'ai ce message : 

Impossible de générer les destinations !

a la fin quand je valide le formulaire
Sur la version 9 je n'avais pas ce message.
Est ce qu'il faut modifier les formulaires après la mise à jour ?
merci

**Comment by btry** [comment]
Bonjour

La version 9 ??

**Comment by yves123456** [comment]
Bonjour 
Je suis passé de la version GLPI 9.4.1.1 a la version 9.5.5 et de formcreator 1.9.1 à 2.12.1 
Sur GLPI 9.4.1.1 et version 1.9.1 je n'ai pas le message d'erreur depuis la mise jour GLPI 9.4.1.1 à 2.12.1 : Impossible de générer les destinations !
Merci

**Comment by btry** [comment]
Bonjour

L'upgrade depuis Formcreator 1 n'est pas supporté. C'est même étonnant que l'upgrade aille jusqu'au bout.

Vous devez recréer vos formulaires
