### ISSUE TITLE
Fail update Formcreator 2.8.5 to 2.12.2

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2419]
Hi @btry  Another problem with 2.12.2.

When updating from version V2.8.5 to v2.12.2 When going to "Targets" the target is blank

![image](https://user-images.githubusercontent.com/35368369/135159433-2bb85dab-708f-48dc-9feb-d1e66acac792.png)

Name and Title is empty

![image](https://user-images.githubusercontent.com/35368369/135159491-b10ae848-538e-49c0-bc5b-80eeeb65d8f2.png)

Query in DB after update

![image](https://user-images.githubusercontent.com/35368369/135159996-39c3699b-bed8-47a8-bd48-f11cff555f06.png)

I found that in version 2.8.5 there was the table "glpi_plugin_formcreator_targets" there was the structure below

![image](https://user-images.githubusercontent.com/35368369/135164529-e7cf4ce3-243c-4b26-a2a6-a4daf89499b5.png)

And in the new versions (I can't identify which one) this unitized table.

**Comment by phamorais** [comment]
@btry 

Ps: IF I try update to 2.8.5 to 2.12.1 the error doesn't happen

**Comment by btry** [comment]
Hi

If you upgrade from 2.8.5 to 2.12.1, then 2.12.2, do the bug occur ?

**Comment by btry** [comment]
Nevermind : there is no upgrade process between 2.12.1 and 2.12.2,  so my test request has no sense.

By reading the upgrade code the issue should happen when upgrading to version 2.9.0.
The table glpi_plugin_formcreator_targets is removed. It contained the name of the targets.
target tickets and target changes have 2 names : 
- name
- target_name

One is for the display name of the target in the form administration area
the other is for the name of the generated target when form answers are processed (after validation if any).

Look into install/uprgade_to_2.9.php

As version 2.9.0 is very old, you may want to repair the upgrade by using the backup of glpi_plugin_formcreator_targets

**Comment by phamorais** [comment]
@btry 

Hi!
The update from version 2.8 to 2.12.1 worked for me. So I'll use it, and then update to 2.12.2 when I'm confident to use the version.

Thank you very much.
