### ISSUE TITLE
The options "Hide unless" or "Display unless" other than "=" doesn't work

### ISSUE THREAD

**Issue by Miudon** [pluginsGLPI/formcreator#242]
Hi,
The options "Hide unless" or "Display unless" other than "=" doesn't work. 
After set and save the question, choosing for example ">", the information "The question has been updated" shows up on the page but nothing happens. If I return and edit that question, i see the option returned to "="

No entrance at "php-errors.log" or "sql-erros.log"

Forms: 0.90-1.3.4
GLPI: 0.90.5

Thanks in advance

**Comment by btry** [comment]
Hi 

Please validate this commit, it should solve your issue

**Comment by Miudon** [comment]
Hy,

Yes, it solved

Thanks a lot

**Comment by btry** [comment]
Thank you for your feedback.
