### ISSUE TITLE
Form Creator 2.10.1 - wrong url path

### ISSUE THREAD

**Issue by SCGSGAog** [pluginsGLPI/formcreator#2420]
**Describe the bug**
We're currently using 2.10.1 because we haven't updated GLPI yet and in the plugin setup where it says Access Type the url path duplicates the root directory of glpi i.e. the path to correct to formcreator is /glpi/plugins/formcreator but in the setup page for the plugin it shows as /glpi/glpi/plugins/formcreator. This duplication also happens when the form sends an email to users when they create a new ticket. 

**To Reproduce**
1. In GLPI go to Setup>Plugins
2. Form Creator
3. New Ticket (Form I created)
4. Access Type
5. URL show is https://my.web.com/glpi/glpi/plugins/formcreator/front/formdisplay.php?id=1 

Additionally, this also happen when the email is sent from the formcreator form when a new ticket is created, the URL displayed is incorrect as above.

**Expected behavior**
The URL should be https://my.web.com/glpi/plugins/formcreator/front/formdisplay.php

**Desktop (please complete the following information):**
 - Windows 10
 - Edge

**Additional context**
Looking at form_profile.class.php and the function showForForm: 

$form_url = $CFG_GLPI['url_base'] . FORMCREATOR_ROOTDOC . '/front/formdisplay.php?id='.$item->getID();

Implies an issue with how FORMCREATOR_ROOTDOC is defined?

**Comment by btry** [comment]
Hi

Please upgrade to 2.12.2. older versions are no longer supported.
