### ISSUE TITLE
form.php Internal Server Error

### ISSUE THREAD

**Issue by breno404** [pluginsGLPI/formcreator#2426]
**Describe the bug**
When I go to the configuration page I receive Error 500.

**To Reproduce**
1. Go to '/front/plugin.php'
2. Click on 'setting button'
4. See the error in '/marketplace/formcreator/front/form.php'

**Expected behavior**
The page without error

**Screenshots**
![Captura de tela 2021-10-06 154712](https://user-images.githubusercontent.com/48841329/136264515-49b32dd2-7b40-4ae0-be8b-7162f6d3555f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [94.0.4606.61]

**Additional context**
This instance of GLPI was made based on another system, the instalation was made from zero but the data was migrated from an old database, in this migration some tables from formcreator plugin weren't created by the plugin. So I let the plugin do all the installation from scratch.

**Comment by breno404** [comment]
In this part "in this migration some tables from formcreator plugin weren't created by the plugin" is that in the new database the plugin don't created the same tables, some tables were not created.

**Comment by breno404** [comment]
Sorry, I didn't understand.
This is my formcreator folder
![Captura de tela 2021-10-07 094014](https://user-images.githubusercontent.com/48841329/136385892-8d0cdfe0-6ad2-44cc-b784-341fc140d7cc.png)
![Captura de tela 2021-10-07 094058](https://user-images.githubusercontent.com/48841329/136385913-4b80470e-c854-40ed-8f27-5907296a582d.png)

**Comment by breno404** [comment]
Now I installed the master version instead of the tag, I ran yarn and composer and apparently it worked

**Comment by btry** [comment]
Hi

There was probably something wrong while transferring the files from the marketplace to your server, as noone did such bug report so far.

As your problem is solved, I close this issue, thank you for your feedback.
