### ISSUE TITLE
After upgrading the plugin to the latest version (2.2.12) the conditions dosent work on new forms

### ISSUE THREAD

**Issue by glorenzutti** [pluginsGLPI/formcreator#2434]
**Describe the bug**
I cant make any condition work on new forms.

**To Reproduce**
1. Create a new form
2. Add a section
3. Add a question with some options

![image](https://user-images.githubusercontent.com/14139801/137016439-c16e634e-632a-414d-9728-57ec6c7b9719.png)

4. Add a new section with a condition

![image](https://user-images.githubusercontent.com/14139801/137016511-f64b4c19-fe7e-4346-83c9-16965ddfea45.png)

5. Test it!

![image](https://user-images.githubusercontent.com/14139801/137016571-a0e76524-2415-4a7c-8a47-4a19867a8ca8.png)

![image](https://user-images.githubusercontent.com/14139801/137016615-b044737f-a394-420f-9c1f-df0a60d4a8eb.png)

**Expected behavior**
I was expecting to don't show the new section, unless I choose option2.

Any condition dosen't work at all. This apply to the submit button too.

This does work with previous forms, created before the update.

**Comment by glorenzutti** [comment]
This is the json.

https://pastebin.com/yVfLn7rD

The showfields.php in the developer tools of the firefox says this:

https://imgur.com/haSuMVl

**Comment by btry** [comment]
The request to showfields.php is forbidden. In Formcreator 2.12.2 there are some security reinforcements to access this URL. But I fond after the release this may forbid admins when previewing a form. 

Try this patch, I think it may help you: 65c46bd7026c81735abaf9e09130e4dd396a88c9

**Comment by btry** [comment]
Hi 

As you solved your issue and my patch is merged, I close.

**Comment by glorenzutti** [comment]
thank u! it did work.
