### ISSUE TITLE
FormCreator 2.12.2 erreur duplication formulaire

### ISSUE THREAD

**Issue by psalanon** [pluginsGLPI/formcreator#2448]
Bonjour,

Ma version de glpi = 9.5.6
Ma version de form creator = 2.12.2

Mes questions sont les suivantes : 

- j'ai un message a chaque fois que je souhaite dupliquer un formulaire (Erreur d'implémentation) sur la page massiveaction.php
- ensuite il m'indique que l'entité racine > XXX est requise pour le formulaire YYYY alors qu'il n'y avait aucun problème juste avant notre migration de glpi en 9.4.3 (bien entendu l'entité racin > XXX est bien présente)

Quelqu'un a t'il une idée?

Bien entendu, aucun de mes formulaires ne sont dupliqués.

Merci à vous

**Comment by btry** [comment]
Hi

This fix should solve the problem: af084d9b

**Comment by btry** [comment]
Hi

HAving no feedback, I close this issue.
