### ISSUE TITLE
Validator gets all forms displayed

### ISSUE THREAD

**Issue by flo1994** [pluginsGLPI/formcreator#245]
If a ticket has been accepted or refused by validator, the validator is redirected to the following page:

http: //ticket01/glpi/plugins/formcreator/front/formanswer.php

The validator sees all forms here.
Also these, where he is not selected as validator. This may not be the case with us....

Only the forms of the validator may be displayed. Is it possible?

**Comment by btry** [comment]
solved in version 0.90-1.4-beta4

**Comment by flo1994** [comment]
Same behavior in the beta version

**Comment by btry** [comment]
Hi

I reopen. Does your URL contains a query string after the redirection ?

You should get a list filtered by validator equals  the currently logged in user.

**Comment by flo1994** [comment]
Hi

the URL is the same /glpi/plugins/formcreator/front/formanswer.php as before without a list filtered by validator

**Comment by flo1994** [comment]
Any news?

**Comment by Armin83** [comment]
Yes the list is filtered after clean new install but the validator can change the filter and can look an accept other forms.

**Comment by btry** [comment]
This issue is obsolete and should be solved by hook.php, function plugin_formcreator_addDefaultWhere().
