### ISSUE TITLE
In 2.12.3, preview tab does not honor display conditions

### ISSUE THREAD

**Issue by nsalguero** [pluginsGLPI/formcreator#2452]
Hi,

With version 2.12.3, the bug #2409, which was fixed by PR #2413 reappeared.

I found that the issue can be solved by adding "!Session::haveRight('entity', UPDATE)" to the condition "count($iterator) == 0".

Best regards,

Nicolas Salguero.

**Comment by btry** [comment]
Hi

There are not enough information to find how to reproduce your patch. Please create a pull request or share a diff here.

**Comment by btry** [comment]
Ok, I see your commit; i'll read it

**Comment by btry** [comment]
I would implement your fix slightly differently, to save a SQL query. Please  try my commit and feedback.

**Comment by nsalguero** [comment]
Hi,

Your commit solves the issue. Many thanks!

Best regards,

Nicolas Salguero.

**Comment by btry** [comment]
Thank you for your report and your contribution.
