### ISSUE TITLE
Export in CSV, JSON or XML (or even better to SQL)

### ISSUE THREAD

**Issue by bdrayersyno** [pluginsGLPI/formcreator#2455]
**Describe the solution you'd like**
Would be great to have the possibility to export the data to CSV or XML or JSON (or directyl to SQL databases) to be able to import the data in an other database, excel, ...

**Describe alternatives you've considered**
Make copy/paste of the data, ... Or use the GLPI API but I didn't find valuable documentation that allow me to do something like that, ...

**Comment by btry** [comment]
Hi

You can already export forms in JSON format to import them in an other GLPI instance. Constraint is that the version of Formcreator is the same on both instances of GLPI at time of export and import.

The export contains the definition of forms (name, sections, questions, targets, conditions, and so on). 

To export form answers you can select a form in backend, then tab "Form answers", then the link on top of the table "See all". You will get a regular list page (like computers, and most types handled by GLPI), tune the search criterias and use the export feature below the search tool bar 

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/58a2d430-b397-42e1-974f-0c972dd12495)
