### ISSUE TITLE
Export forms by cli

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#2456]
Not a bug, but quistion. Is it possible to export forms not by web interface, but by cli, or mysql dump?

**Comment by btry** [comment]
Hi

No. Export is only available from web interface.

It is possible to implment a CLI command to export a form.

Exporting a form from a DB dump should be avoided as the objects of the plugin may be linked to objects of GLPI (core) and the IDs may change accross GLPI instances.

**Comment by reinethernal** [comment]
How can i implement such feature? Because some of my forms are unable to export due to error 
![image](https://user-images.githubusercontent.com/35932698/141090224-32e18194-439e-4286-973a-38edee418773.png)

**Comment by btry** [comment]
The error in the red bottom right toast should be fixed. I think you have an inconsistency in the database.

You may fix it by editing all questions of the form able to use a regular expression. Do not change anything, and save them. This should recover the inconsistency. Once done, try again to export the form.

**Comment by reinethernal** [comment]
re-adding quiestions helped. thank you!
