### ISSUE TITLE
Affichage des reponses Formulaires : pb de droit suite migration ?

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2461]
Bonjour

Nous etions sur une version 'ancienne' de form.
Suite migration du plugin vers 2.10.1 (apres migration de glpi de 9.3 vers 9.5.5)
nous avons erreurs notamment dans les reponses formulaires utilisées (entre autres): 

SQL Error "1054": Champ 'glpi_plugin_formcreator_formanswers.**users_id_validator**' inconnu dans on clause in query "SELECT DISTINCT `glpi_plugin_formcreator_formanswers`.`id` AS id, 'xxxxxx' AS currentuser, `glpi_plugin_formcreator_formanswers`.`entities_id`, `glpi_plugin_formcreator_formanswers`.`is_recursive`, `glpi_plugin_formcreator_formanswers`.`name` AS `ITEM_PluginFormcreatorFormAnswer_1`, `glpi_plugin_formcreator_formanswers`.`id` AS `ITEM_PluginFormcreatorFormAnswer_1_id`, `glpi_plugin_formcreator_formanswers`.`id` AS `ITEM_PluginFormcreatorFormAnswer_2`, `glpi_plugin_formcreator_formanswers`.`id` AS `ITEM_PluginFormcreatorFormAnswer_2_id`, `glpi_plugin_formcreator_forms`.`name` AS `ITEM_PluginFormcreatorFormAnswer_3`, `glpi_users_requester_id`.`name` AS `ITEM_PluginFormcreatorFormAnswer_4`, `glpi_users_requester_id`.`realname` AS `ITEM_PluginFormcreatorFormAnswer_4_realname`, `glpi_users_requester_id`.`id` AS `ITEM_PluginFormcreatorFormAnswer_4_id`, `glpi_users_requester_id`.`firstname` AS `ITEM_PluginFormcreatorFormAnswer_4_firstname`, `glpi_users_users_id_validator`.`name` AS `ITEM_PluginFormcreatorFormAnswer_5`, `glpi_users_users_id_validator`.`realname` AS `ITEM_PluginFormcreatorFormAnswer_5_realname`, `glpi_users_users_id_validator`.`id` AS `ITEM_PluginFormcreatorFormAnswer_5_id`, `glpi_users_users_id_validator`.`firstname` AS `ITEM_PluginFormcreatorFormAnswer_5_firstname`, `glpi_plugin_formcreator_formanswers`.`request_date` AS `ITEM_PluginFormcreatorFormAnswer_6`, `glpi_groups_groups_id_validator`.`completename` AS `ITEM_PluginFormcreatorFormAnswer_7`, `glpi_groups_groups_id_validator`.`id` AS `ITEM_PluginFormcreatorFormAnswer_7_id` FROM `glpi_plugin_formcreator_formanswers`LEFT JOIN `glpi_plugin_formcreator_forms` ON (`glpi_plugin_formcreator_formanswers`.`plugin_formcreator_forms_id` = `glpi_plugin_formcreator_forms`.`id` )LEFT JOIN `glpi_users` AS `glpi_users_requester_id` ON (`glpi_plugin_formcreator_formanswers`.`requester_id` = `glpi_users_requester_id`.`id` )LEFT JOIN `glpi_users` AS `glpi_users_users_id_validator` ON (`glpi_plugin_formcreator_formanswers`.`users_id_validator` = `glpi_users_users_id_validator`.`id` )LEFT JOIN `glpi_groups` AS `glpi_groups_groups_id_validator` ON (`glpi_plugin_formcreator_formanswers`.`groups_id_validator` = `glpi_groups_groups_id_validator`.`id` ) WHERE `glpi_plugin_formcreator_formanswers`.`plugin_formcreator_forms_id` = 11 AND ( `glpi_plugin_formcreator_formanswers`.`entities_id` IN ('1', '5') OR (`glpi_plugin_formcreator_formanswers`.`is_recursive`='1' AND `glpi_plugin_formcreator_formanswers`.`entities_id` IN (0)) ) ORDER BY `ITEM_PluginFormcreatorFormAnswer_1` ASC LIMIT 0, 50"

sur une autre base avec plugin 2.11.2 : pas de souci
Nous avons migré alors en plugin 2.11.2 sur cette base : toujours meme souci
Migration avec la version 2.12.3 : toujours meme souci

Pour info, dans la visualisation des tickets : 
Undefined index : users_id_validator in inc\formanswer.class.php on line 98 et 104

En filtrant sur certaines tables
![image](https://user-images.githubusercontent.com/42341169/141975698-f0d288c6-6ebc-4e78-aee9-3cbb22237776.png)
![image](https://user-images.githubusercontent.com/42341169/141975775-400574b4-fedc-44e4-844c-3f0e5baf482e.png)

pb lors de migration 2.7 ?

Merci

**Comment by btry** [comment]
Bonjour

Vérifiez la structure de la table glpi_plugin_formcreator_formanswers. Elle doit correspondre à ce qui suit. PEut être que la colonne users_id_validator manque

````sql
CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_formanswers` (
  `id`                          int(11) NOT NULL AUTO_INCREMENT,
  `name`                        varchar(255) NOT NULL DEFAULT '',
  `entities_id`                 int(11) NOT NULL DEFAULT '0',
  `is_recursive`                tinyint(1) NOT NULL DEFAULT '0',
  `plugin_formcreator_forms_id` int(11) NOT NULL,
  `requester_id`                int(11) DEFAULT NULL,
  `users_id_validator`          int(11) NOT NULL DEFAULT '0' COMMENT 'User in charge of validation',
  `groups_id_validator`         int(11) NOT NULL DEFAULT '0' COMMENT 'Group in charge of validation',
  `request_date`                timestamp NULL,
  `status`                      int(11) NOT NULL DEFAULT '101',
  `comment`                     text,
  PRIMARY KEY (`id`),
  INDEX `plugin_formcreator_forms_id` (`plugin_formcreator_forms_id`),
  INDEX `entities_id_is_recursive` (`entities_id`, `is_recursive`),
  INDEX `requester_id` (`requester_id`),
  INDEX `users_id_validator` (`users_id_validator`),
  INDEX `groups_id_validator` (`groups_id_validator`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by EC2311** [comment]
en effet, il manque des champs
![image](https://user-images.githubusercontent.com/42341169/141982476-560953d3-8508-4735-bd4b-2ef7f6ea7c04.png)

**Comment by btry** [comment]
Ajoutez les, et veillez à respecter l'ordre des colonnes défini par pa commande CREATE TABLE de référence. Ca devrait résoudre le souci.

**Comment by EC2311** [comment]
Je suppose que validator_id devient users_id_validator ? (niveau reprise de données ?)
et qu'en fait il faut ajouter seulement le champ groups_id_validator ? (+ les index)

**Comment by btry** [comment]
Je ne me souviens plus très bien. C'est un bout de migration qui est assez ancien. Il me semble qu'il y avait une seule colonne pour les utilsiateurs et groupes validateur. L'ID était interprété en fonction du type de validation (utilsiateur ou groupe). Le but de la migration était d'avoir une colonne dont la signification ne varie pas en fonction d'une autre donnée. Il faut relire le code de migration correspondant. C'est dans le dossier install.

**Comment by EC2311** [comment]
Ajout des zones : ok plus d'erreur :) 

scripts de migration : 
![image](https://user-images.githubusercontent.com/42341169/142203824-3f173a92-6ff0-4053-a4f8-85206364cf40.png)

je pense que je dois eventuellement les recustomiser pour que les maj impactent formanswers (table actuelle) 

par contre quid des valeurs dans 'validator_id' pour lesquelles le validation_required = 0 (soit <>1 et <>2) : pas de maj ?

**Comment by btry** [comment]
Dans la version cible étape de l'upgrade, validation_required ne doit pas changer.

quand validation_required=1 validator_id était un ID d'utilisateur. Quand validation_required=2 validator_id était un ID de groupe. C'est hétérogène, et dans le code on ne pouvait pas savoir ce qui était manipulé en provenance de la colonne validator_id. Le changement de structure visait à arranger cela. la colonne validation_required n'a pas besoin de modification dans cette étape de l'upgrade.

Reste à comprendre pourquoi ce code n'est pas joué dans votre cas.

**Comment by EC2311** [comment]
ok pour les explications (user/groupe > validator_id), mais ce que je voulais dire c'est qu'il y a des validator_id (formanswers) pour lesquels le validation_required (forms) vaut 0 (si on fait le lien entre forms et formanswers). Si je supprime la colonne (validator_id) ces valeurs seront perdues... ? ou elles doivent etre stockées ailleurs ?

**Comment by btry** [comment]
Si validation_required = 0 alors la valeur validator_id n'a normalement pas de sens. Peut être que le formulaire a été utilisé avec une validation, et plus tard, la validation a été désactivée. Dans ce cas validator_id pouvait ne pas être à 0. Il me revient aussi que validator_id pouvait être l’utilisateur en charge de l validation, le groupe en charge de la validation et l'utilisateur qui a effectivement réalisé la validation. Cela fait 3 types d'information pour 1 seule colonne. Il fallait vraiment mettre de l'ordre là dedans.


Du coup si validation_required=0 la valeur de validator_id sera perdue après migration. N'ayant pas de sens logique, cette perte ne doit pas poser de problème, ce serait plutôt un assainissement des données.

**Comment by EC2311** [comment]
ok un grand merci

**Comment by btry** [comment]
Bonjour

Pouvons-nous fermer cette issue ?

**Comment by EC2311** [comment]
Oui désolé 
et encore un grand merci
