### ISSUE TITLE
Use Textarea field generates 404 em console

### ISSUE THREAD

**Issue by brtok** [pluginsGLPI/formcreator#2468]
**Description:** Every form with textarea generates 404 error in browser console.

**Steps to reproduce the behavior:**
1. Create a form with a question using "Textarea" field and save.
2. Preview the form or open the form to answer as usual.
3. Open the browser console.
4. See error "Failed to load resource: the server responded with a status of 404 ()".

Tinymce loads an invalid URL, but I don't know why.
meta tag at mce iframe loads something like
`<link rel="stylesheet" type="text/css" id="u1" href="https://yourglpiurl/plugins/formcreator/front/?v=9.5.6">`

**Screenshot**
![image](https://user-images.githubusercontent.com/11841638/142690481-7a68d0a1-08de-4aa1-a0da-cd1b56d71c04.png)

**GLPI / Plugins:**
- GLPI 9.5.6
- Plugins: behaviors, formcreator, pdf
- Formcreator versions tested: 2.12.2 and 2.12.3 (same problem in both)

**Desktop:**
 - OS: Windows 10 21H2
 - Browser: Chrome 96

**Comment by btry** [comment]
Hi

I'm aware about this error. Unfortunately, I did not find why this happens. 

This issue has no harmful impact and seems to disappear with the next version of GLPI and the next version of the plugin (both in development and to be released in a near future). Therefore I won't waste precious time on it for now and I will close without searching for a fix if my observation is confirmed.

**Comment by btry** [comment]
Hi

I confirm this does not occurs with Formcreator 2.13.0. I close this issue.
