### ISSUE TITLE
2.13.0-alpha.1 installation error

### ISSUE THREAD

**Issue by roshanroche** [pluginsGLPI/formcreator#2469]
Hi,

while installing the plugin 2.13.0-alpha.1 on glpi 10 im getting the following error.

2.13.0-alpha.1 multiple alter in glpi_plugin_formcreator_targettickets - Error during the database query: ALTER TABLE `glpi_plugin_formcreator_targettickets` CHANGE `tickettemplates_id` `tickettemplates_id` INT NOT NULL DEFAULT '0' AFTER `type_question` - Error is Data truncated for column 'tickettemplates_id' at row 52

**Comment by btry** [comment]
Hi

Is it a fresh install or an upgrade ?

Tha knyou for the testing effort, by the way. I appreciate your contribution

**Comment by roshanroche** [comment]
Hi..

its a fresh install

**Comment by btry** [comment]
You probably installed formcreator in the past. Very old version did not delete all its tables and the plugin believed it should upgrade.

As you're doing tests, i want to know if your glpi instance is fresh or uses a non empty database (a copy of a production environment, maybe?)

**Comment by btry** [comment]
Hi

I'm waiting for your answer, to determine if there is something wrong in the plugin install process.

If the GLPI instance is not a fresh one, check if you have tables having a name starting with glpi_plugin_formcreator_ . Delete them.

In the table glpi_configs check if you have rows related to Formcreator

select * from glpi_configs where context='formcreator'. You should fine zero or 1 row. If you have a a non empty result, delete the ro found.

Finally try agail to install the plugin.

**Comment by btry** [comment]
Hi

Do you have an update to share ? Do you have an empty DB for GLPI as well ?

**Comment by roshanroche** [comment]
Hi

Sorry for the late reply. Yesterday I installed fresh instance and it
worked fine.

Thank u so much

**Comment by btry** [comment]
Hi

Great ! Thank you for your feedback.
