### ISSUE TITLE
Formcreator 2.12.3 : Variable nb non definie

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2471]
Bonjour

![image](https://user-images.githubusercontent.com/42341169/143427381-d46de2fc-ec80-4ad1-83b6-8cc8d74c642d.png)

Ne manquerait-il pas $nb en ligne 1758 de inc/form.class.php afin d'initialiser la variable $nb ?

**Comment by btry** [comment]
Bonjour

Oui, c'est juste ! Vous pouvez faire une PR ?

**Comment by EC2311** [comment]
PR ? euh...

**Comment by btry** [comment]
Ok, je m'en occupe.

**Comment by btry** [comment]
Voilà le commit pour le fix: a5f12bc06996cbc5fd298217b4e15c8ddc39876d

**Comment by EC2311** [comment]
-> cela marche ;) 

Je l'avais deja anticipé pour etre sur avant de poster...

**Comment by btry** [comment]
ok, donc je ferme. Merci pour la contribution.
