### ISSUE TITLE
json_encode and json_decode for non latin strings (cyrillic)

### ISSUE THREAD

**Issue by Wel-lz** [pluginsGLPI/formcreator#2473]
Hi, I found a problem
If you ask the question type "LDAP selection", formcreator writes an invalid character encoding to the database.

locale = ru_RU

Example:
(& (objectCategory = person) (objectClass = user) (department = Дирекция по информационным технологиям))
After saving:
(& (ObjectCategory = person) (objectClass = user) (department = u0414u0438u0440u0435u043au0446u0438u044f u043fu043e u0438u043du0444u043eu0440u043cu0430u0446u0438u043eu043du043du044bu043c u0442u0435u0445u043du043eu043bu043eu0433u0438u044fu043c))

In the version before 2.12.3 it was solved by editing the file /inc/field/ldapselectfield.class.php line ~ 302, adding JSON_UNESCAPED_UNICODE

After the update, this solution stopped working, and the answer found here https://github.com/pluginsGLPI/formcreator/pull/510 does not work due to the lack of saveForm() function in inc/form.class.php and saveAnswers($datas) in inc/form_answer.class.php

**Comment by btry** [comment]
Hi

Your patch was probably for a version older than 2.12.0. It will require some work now to find an alternative solution. Don't hesitate tu submit a PR if you create a fix yourself.

**Comment by btry** [comment]
I did a test using your sample string, and I reproduce. But it is still possible to apply your fix, in the line you mentionned. It prevents escaping the characters in the DB, and going further shows that the filter is corect when requesting the LDAP server.

I conclude your fix is still valid.

**Comment by Wel-lz** [comment]
Thank you very much for your support. The problem was on my part, after the update, the current plugin was in the marketplace, and I edited the file in plugins

**Comment by btry** [comment]
Ok, so the fix is still good, and I can merge it. Thank you for your contribution
