### ISSUE TITLE
[SOLVED] [2.12.3] DateField::serializeValue() must be of the type string

### ISSUE THREAD

**Issue by WebGregGit** [pluginsGLPI/formcreator#2499]
**Describe the bug**
After accept form get stuck on the white page

**To Reproduce**

1. Create a form with 'Need to be validate?' per User
2. Create a question with a required datefield
2. Specify the target ticket.
3. Compleate a form and submit it.
4. Go to approving person account.
5. Accept form and... white page.

**Expected behavior**
Ticket should be create after accept form. 

**GLPI / Plugins (please complete the following information):**
- GLPI version: 9.5.6

Plugins:
	advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Installed / not activated
	impacts              Name: Asset impacts                  Version: 2.0.5      State: Installed / not activated
	databases            Name: Bazy danych                    Version: 2.3.2      State: Enabled
	browsernotification  Name: Browser Notification           Version: 1.1.9      State: Installed / not activated
	datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled
	fields               Name: Dodatkowe pola                 Version: 1.12.8     State: Installed / not activated
	mreporting           Name: Dodatkowe raporty              Version: 1.7.3      State: Enabled
	pdf                  Name: Drukuj do PDF                  Version: 2.0.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.3     State: Enabled
	fpconsumables        Name: FP Consumables                 Version: 1.3.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	glpicheckingversion  Name: GLPI Checking Version          Version: 1.0.1      State: Installed / not activated
	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled
	mycustomview         Name: MyCustomView                   Version: 1.2.1      State: Enabled
	news                 Name: Powiadomienia                  Version: 1.9.0      State: Installed / not activated
	printercounters      Name: Printer counters               Version: 1.7.0      State: Enabled
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Enabled
	dashboard            Name: Pulpit                         Version: 1.0.2      State: Enabled
	reports              Name: Reports                        Version: 1.14.1     State: Enabled
	room                 Name: Rooms                          Version: 3.1.3      State: Enabled
	treeview             Name: Tree view                      Version: 1.9.1      State: Enabled
	typology             Name: Typologies                     Version: 2.7.2      State: Enabled
	useditemsexport      Name: Used items export              Version: 2.4.0      State: Enabled
	watermark            Name: Watermark                      Version: 1.0.0      State: Enabled
	webresources         Name: Web Resources                  Version: 1.3.2      State: Enabled
	tag                  Name: Zarządzanie słowami kluczowymi Version: 2.8.1      State: Enabled

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.45 64-bit

**Additional context**
A message appears in debug mode: Uncaught Exception TypeError: Return value of GlpiPlugin\Formcreator\Field\DateField::serializeValue() must be of the type string, null returned in /var/www/html/glpi/marketplace/formcreator/inc/field/datefield.class.php at line 108

When the white page appears, I can refresh it and the form will be displayed saying that it has been approved, but the ticket will not be created. Rejection works fine ;)

edit: Maybe there is a connection with... If I set another question it is not visible unless the date field =/= empty - does not work for me. 

I know that officialy this version is compatible with GLPI 9.5.5 only. Does this error result from it? Is there any chance for a fix before implementing GLPI 10?

**Comment by btry** [comment]
topic on forum : https://forum.glpi-project.org/viewtopic.php?id=282568

**Comment by btry** [comment]
Hi

The problem is very likely related to a date field. I think I need to know the language used when the error occurs, and an example of a date found in the field. I think the value may be important to reproduce.

**Comment by WebGregGit** [comment]
Hi @btry. Thank you for your message. 
I use Polish. The error appeared both - when the field is empty and with a random date.

**Comment by btry** [comment]
Hi

The issue is related to an other prolem. 

Here is the fix https://github.com/pluginsGLPI/formcreator/commit/f9070765e5dc74983f20afb0de86f16a300d0756

**Comment by WebGregGit** [comment]
Thank You @btry - this is it :)
