### ISSUE TITLE
Forms display on homepage double or triple view

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#250]
If you click on "all" "global view" "group view" and then on persnal view. forms which are display on homepage or viewed 4 times. If you do browser refresh it it is correct displayed one time. (glpi rc2 9.1)
 Forms	0.90-1.3.4	GPLv2 older systems also firefox 48.0.2

**Comment by btry** [comment]
Hi

I'm currently testing with the **master** branch and tag **0.90-1.3.4** on **GLPi 9.1 RC2**.
* Firefox ESR 45.3.0   OK
* Chromium 52.0.2743.116  OK

I can't reproduce yet. I notice my firefox is different than yours anyway. Can you check with the master branch, with the same browser and an dofferent one ?

**Comment by Armin83** [comment]
I'm not sure how to change version correctly it it is an "older" one. 
I tried too change the folder against the 0.90-1.3.4 version but now i got an error on setup > plugins.

**Comment by Armin83** [comment]
I have this bug with all browser. 
![img_014](https://cloud.githubusercontent.com/assets/19192087/18698676/6e63b652-7fcc-11e6-8b9d-bd82729ac13e.jpg)

**Comment by btry** [comment]
Hi

A check has been added after version 0.90-1.3.4 which should prevent your issue. Can you try the latest revision and feedback ?

Thank you

**Comment by Armin83** [comment]
Now i only see form in Personal View and the issue don't occur agian. The problem is solved.

**Comment by btry** [comment]
Thank you very much !

**Comment by Armin83** [comment]
sorry @btry - i found something strange :| - if group view is selected it does not disply forms but if i press F5 forms it is displayed. Only one = good, but i don't know how you plan how it should works.

**Comment by btry** [comment]
You're right. I reproduce it.
