### ISSUE TITLE
Not Possible to add Text or Textarea

### ISSUE THREAD

**Issue by Hexxooor** [pluginsGLPI/formcreator#2507]
Hello,

Is not Possible to add a Text or a Textarea to Form.
<img width="941" alt="msedge_5uDUJozS0w" src="https://user-images.githubusercontent.com/75509223/146637531-15156262-f180-40a9-a08c-ce20f3c75315.png">

1. Go to 'Add a Question'
2. Click on 'Types /text,textfield'
3. See error

![image](https://user-images.githubusercontent.com/75509223/146637510-050722b6-96c1-4f58-bd52-0f535e70f932.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.0 Beta
- 	fields               Name: Additionnal fields             Version: 1.13.0-rc1 State: Enabled
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.1 State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc2  State: Enabled
	accounts             Name: Konten                         Version: 3.0.0-rc1  State: Enabled
	tag                  Name: Tag Management                 Version: 2.9.0-rc1  State: Enabled
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.0-rc1 State: Installed / not activated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 95.0 (64-/Edge Chrome 96.0.1054.53 /chrome 96.0.4664.110

**Comment by btry** [comment]
Hi

I don't reproduce with the latest developments. Let's wait the Alpha.2 version to validate that this is issue is solved.

**Comment by btry** [comment]
Hi

Having no feedback, and this version being obsolete, I close.
