### ISSUE TITLE
Error validating a form

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#2512]
**Describe the bug**
When a form that passes validation is generated, when clicking on the accept button it generates a blank call, without the fields filled out. If you click the "edit answer" button and then click "accept" it opens the ticket correctly.

**To Reproduce**
1. Fill out a form that requires validation
2. As a validator click on Accept
3. The ticket will be generated without the fields filled in by the applicant.
4. If you click "edit answer" before clicking "accept" the problem does not happen.

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.6
- 	behaviors            Name: Comportamentos                 Version: 2.5.0      State: Enabled
	escalade             Name: Escalonamento                  Version: 2.6.2      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.3     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled
	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled
	pdf                  Name: Imprimir em PDF                Version: 2.0.0      State: Enabled
	moreticket           Name: More ticket                    Version: 1.6.1      State: Enabled
	notifications        Name: Notifications                  Version: 9.5+1.0    State: Enabled
	dashboard            Name: Painel                         Version: 1.0.2      State: Enabled
	reservation          Name: Reservation                    Version: 2.3.5      State: Enabled

**Desktop (please complete the following information):**
 - OS: Windows 7, 10 and 11
 - Browser all
 - Version lastest

**Comment by btry** [comment]
Hi

Apply this fix : https://github.com/pluginsGLPI/formcreator/pull/2477

**Comment by btry** [comment]
Hi

Having no feedback, I assume the provided fix solved the issue.

**Comment by TR0LLL** [comment]
Yes, problem solved ;)
