### ISSUE TITLE
[2.13.0-alpha.2] FAQ and form categories mixed

### ISSUE THREAD

**Issue by jcovillers78114** [pluginsGLPI/formcreator#2520]
The form categories are mixed with the FAQ categories

Edit a form and pull down the menu of categories.
You will find the list of categories from the FAQ but no longer separate categories for forms.

If you create a new form category, it will be mixed with the FAQ categories.

On the simplified interface, all the mixed categories appear when you select the support request menu.

If you select the FAQ menu on the simplified interface, no categories will appear.

PS: my entity is set up to separate the support request menu and the FAQ menu
administration > entities> form tab >knowledge base = Distinct menu entry

**Comment by btry** [comment]
Hi

This is related to a development merged a few days before releasing the Alpha.2 version. This change is reverted in the support/2.13.0 branch.

if you need to test this part of the plugin, I may provide to you a build of the latest revision. Just ask.
