### ISSUE TITLE
 Can't find new locations

### ISSUE THREAD

**Issue by felipepimentel08** [pluginsGLPI/formcreator#2522]
The field type - Dropdown list - Common Location is not showing the new locations registered in GLPI, directly from GLPI it appears, from the form not.

**Comment by btry** [comment]
Hi



Please 

- tell the versin if GLPI and Formcreator
- describe how to reproduce

**Comment by felipepimentel08** [comment]
GLPI 9.5.5
Form Creator 2.12.3


the new locations for users to select in the form does not appear, displaying only the locations created before updating the plugin
![image](https://user-images.githubusercontent.com/47112555/148818916-84c23d08-636a-4b86-bfaa-27ccf2c9c15a.png)

**Comment by btry** [comment]
Hi

Having no feedback, and this version being obsolete, I close.
