### ISSUE TITLE
Prevent sql issues using unsigned int

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#2527]
Hi

The Behaviors plugin allows the formation of the Ticket ID as YYMMDDxxxx and YYMMxxxxxx, but this ID format caused an error when changing from 2021 to 2022 because, in the database, for the Ticket ID, the INT type is used, which goes from -2,147,483,648 to 2,147,483,647.

To fix this problem the suggestion is to change the type to INT UNSIGNED.

https://github.com/glpi-project/glpi/issues/10262

In FORMCREATOR plugin also occurs the error in the table 'glpi_plugin_formcreator_issues', column 'items_id', I suggest updating this column to INT UNSIGNED.

Thanks.

**Comment by btry** [comment]
Hi

GLPI 10 switched to unsigned int for IDs, and Formcreator has been updated to do the same. This issue should be solved. Can you cinform with the version 2.13.0-rc.1 (on a testing environment) ?
