### ISSUE TITLE
Objet Requete SQL

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2533]
Plutot que d'entrer des filtres dans les objets GLPI préexistant, ne pourrait-on pas imaginer que l'admin soit capable d'entrer un type "SQL"  (comme il existe objet GLPI, Intitulés...) correspondant alors à une requete SQL (Select **id**, name, * from glpi_yyyyy where xxxxxx) 
ce qui permettrait à tout a chacun de pouvoir 'lister' les objets GLPI dont il a besoin ?

Merci

**Comment by btry** [comment]
En version 2.13 les paramètres des cibles sont éclatés dans plusieurs onglets. Il faudrait faire de même pour le design des questions, et avoir un onglet dédié aux restrictions de valeurs (regex, limites numériques, longueur de  texte). Dans cet onglet on pourrait imaginer un système de conditions inspiré des conditions pour afficher / masquer des questions, ou mieux : arriver à réutiliser l'éditeur de filtres qu'on trouve dans les listes d'items de GLPI (pas sûr que ce soit techniquement possible ou facile).

**Comment by btry** [comment]
Pour le moment je suis fortement opposé à permettre de saisir du SQL à cause des risques de plantage d'une requête erronée, ou les risques d'injection SQL que cela peut ouvrir.

**Comment by EC2311** [comment]
en ce qui concerne l'injection, c'est vrai que cela pourrait etre une porte ouverte : il faudrait interdire toute requete contenant des mots comme 'insert', 'delete', 'update', 'create' ...
Si al requete ne fonctionne pas : code erreur retourné. : théoriquement, l'administration des formulaires est pour les Super-admin... 
mais il est vrai que ce n'est pas evident de voir ses propres besoins/fonctionnements  par rapport au fonctionnement/utilisation   faite de GLPI.

**Comment by btry** [comment]
Bonjour

Le filtrage des objets GLPI et des intitulés sera disponible sans SQL en version 2.14.0.
