### ISSUE TITLE
Multi Level Approval

### ISSUE THREAD

**Issue by h33raj** [pluginsGLPI/formcreator#2537]
Is there a multi-level approval there for GLPI or Formcreator?

**Comment by Pieurre** [comment]
Hello,
A plugin under GLPI Network subscription will be released soon and will include this functionality.

The GLPI Network services are available through our Partner's Network. We provide special training, bug fixes with editor subscription, contributions for new features, and more.

Obtain a personalized service experience, associated with benefits and opportunities. 

https://www.teclib-edition.com/en/partners/

**Comment by damien51** [comment]
hello,

Could you tell us a bit more ?
it could be what we need (a little more flexibility with approval process of forms).
Thanks

**Comment by btry** [comment]
The plugin targets the Formcreator 2.13, for GLPI 10.

It allows to setup users and groups for validation up to 5 levels (should be enough for anyone). When approval is granted for enough levels (0, 50% or 100%), the answers are approved and the targets are generated. 

When a level is approved or refused, validators of the next level are notified by email. The validation is non blocking. A level 4 validator may approve or refuse answers, even if one of lower levels is still waiting.

**Comment by damien51** [comment]
Ok , what we need is a way to use an answer of the forms as validator or for example a way to put a manager of someone automatically (via ldap or group with managers of a department or other )

**Comment by btry** [comment]
Hi

A requester is already able to choose his validator if there are several validators available. 

However, at this time, it is not possible to automatically select the manager of the requester. A development is required.

**Comment by btry** [comment]
Hi

> 
Hi

A requester is already able to choose his validator if there are several validators available.

However, at this time, it is not possible to automatically select the manager of the requester. A development is required.


This will be possible in Formcreator 2.14.0.

Multi level approval in Formcreator will also be available, up to  levels.
