### ISSUE TITLE
The problem of displaying data in the ticket. HTML tags 

### ISSUE THREAD

**Issue by kamxas** [pluginsGLPI/formcreator#2543]
#2521 This problem was mentioned 

![2022-01-16 205645](https://user-images.githubusercontent.com/84325346/149671849-6a90ea08-4f1e-4830-b385-10a7cc0638ef.jpg)

When creating a ticket (with the ##FULLFORM## tag), some input boxes in Description Field  will be displayed as source code with HTML-tags.
Version GLPI 10.0.0-beta 
Version Formcreator Plugin: 2.13.0-alpha.2

**Comment by triplility** [comment]
oh, yes, I met the same question with you. @btry Hi Btry, this is what I said another issue I met.

**Comment by stdonato** [comment]
Same error with 2.13.0-alpha.3, GLPI 10 beta

**Comment by btry** [comment]
Hi

From the latest duplicate, I believe the issue occurs when using a question of type text area. However, by re reading the initial message, it is mentionned this occurs with a description field. A description question, if I remember well, is not propagated to the target ticket.

Can you tell the type of the question's impacted by the issue ?

**Comment by btry** [comment]
So... good news : I reproduce with a textarea question. I guess most other question types are not related to this issue.

**Comment by btry** [comment]
Hi

Please try the above fix and feedback

**Comment by btry** [comment]
Hi

Having no feedback, I close. You may follow the issue #2568 which duplicates this one. A positive feedback was provided, then the bug may be solved soon.
