### ISSUE TITLE
[Question] Is it possible to add an image in a description ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [pluginsGLPI/formcreator#2546]
Hello,

Is it possible to use inline images in Description field ?

I tried to add an inline image in a description: 
![image](https://user-images.githubusercontent.com/8069239/150567963-9f718816-5a95-44be-8555-d86899e452e7.png)

But when I try to use the form (even in super-admin), the image is not displayed (only the alt text) :  
![image](https://user-images.githubusercontent.com/8069239/150568097-c1601b45-6b60-4272-967c-21577c59ab5b.png)

Regards

**Comment by btry** [comment]
Hi

Which version of Formcreator ?

**Comment by GuiGuiSoft** [comment]
Hi,

I use the version 2.12.3

**Comment by btry** [comment]
hi

Try this fix and feedback

**Comment by btry** [comment]
Hi

This is indeed a permissin problem: a self service user is not allowed to access a document. I think I need to embed the picture in an other way. Wait for an other attempt.

**Comment by btry** [comment]
I think a previous fix for this topc did too much work. I updated the PR. Cancel the previous patch, download it again and tell the result. On my isntance self service is proerly rendered, and in standard interface, it is still OK.

https://github.com/pluginsGLPI/formcreator/pull/2556

**Comment by GuiGuiSoft** [comment]
Hello, it seems to work fine on my side :)

**Comment by btry** [comment]
Well, I did further checks, and this breaks HTML escaping in other palces.

The solution seems even simpler. Revert, download, apply again.

**Comment by GuiGuiSoft** [comment]
Hello,

In this configuration the problem re-appears  
![image](https://user-images.githubusercontent.com/8069239/152357473-1dfcfb26-2fc9-4d44-9fc1-4051c6bc5143.png)

Regards.

**Comment by btry** [comment]
Ok, le patch est modifié avec une autre tentative. 

Pour que ça fonctionne je pense qu'il faut impérativement réécrire la description : retirer l'image et remettez la. C'est important car la façon de la stocker est diférente (il n'y a plus d'upload dans un itemtype document). On revient à quelque chose de proche du 1er essai.

**Comment by GuiGuiSoft** [comment]
It seems to work now 👍

**Comment by btry** [comment]
Great ! Thank you for your feedback
