### ISSUE TITLE
Multiple elements

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/formcreator#2548]
Bonjour 
Existe-t-il un moyen de lié plusieurs éléments à un ticket via formcreator ?
Exemple un écran et un ordinateur.
Merci par avance

**Comment by btry** [comment]
Bonjour

Pas pour le moment. 

Si l'écran et l'ordinateur sont branchés ensemble physiquement, un système d'inventaire automatique devrait modéliser cette relation. Dans ce cas rattacher l'ordinateur au ticket cible devrait faire l'affaire ?

**Comment by imanou10** [comment]
Oui tout à fait.
Merci pour votre retour
