### ISSUE TITLE
Base de connaissance

### ISSUE THREAD

**Issue by TeamSiPortalp** [pluginsGLPI/formcreator#2551]
Bonjour,

La base de connaissance n'est, encore une fois, plus accessible en selfservice. Comment faire pour la remettre visible ?

GLPI 9.5.6
FORMCREATOR 2.12.3 ou 2.12.4

![image](https://user-images.githubusercontent.com/86061241/151173320-617853ed-c1c2-4443-aa8f-7c14b48fd8bd.png)

Merci

**Comment by TeamSiPortalp** [comment]
![image](https://user-images.githubusercontent.com/86061241/151173291-19b31226-c2ba-41a9-9e5e-5cbede633a27.png)

**Comment by TeamSiPortalp** [comment]
Ah non c'est bon j'ai trouvé l'option qui permet de réafficher l'onglet.

**Comment by btry** [comment]
Bonjour

Quels sont les réglages de l'entité concernée (onglet "formulaires") ?

**Comment by btry** [comment]
Je pense que vous avez trouvé le bon endroit, en effet.

**Comment by TeamSiPortalp** [comment]
Oui merci. Ca serait bien que par défaut cela reste en section distincte lors d'une maj. :)

**Comment by btry** [comment]
Je n'ai pas le temps de vérifier, mais il me semble qu'il y a eu un changement dans du code d'upgrade ou de gestion de l'option qui pourrait expliquer votre souci. L'upgrade étant fait pour vous (et donc passé), cela ne devrait plus se produire.
