### ISSUE TITLE
[Formcreator] Documents non liés au ticket créé par le formulaire

### ISSUE THREAD

**Issue by selkopb** [pluginsGLPI/formcreator#2552]
Bonjour, 

Je rencontre un problème avec les formulaires.
Lorsque j'utilise un formulaire qui va créer un ticket d'incident, j'ai une question de type "fichier" qui devrait ajouter le document au ticket créé.
A l'issue du formulaire, le ticket est créé correctement, mais je ne vois aucun document s'ajouter au ticket.

Le document est cependant correctement uploadé dans GLPI car il est accessible depuis Gestion -> Documents.
Je vois que le document a comme "Élément rattaché" la réponse de formulaire mais il n'est pas lié au ticket.
Si je lie manuellement ce document au ticket, j'obtiens le ticket tel qu'il devrait être lors de sa création.

J'observe ce comportement sur plusieurs plateformes GLPI utilisant la version 9.5.6 de Glpi.
Les versions de FormCreator peuvent varier selon les plateformes (2.12.4 ou 2.12.2)

Cependant, j'ai une autre plateforme GLPI utilisant la version 9.5.6 avec la version 2.12.2 de Formcreator, je ne constate pas ce comportement sur cette plateforme.

Je ne suis pas parvenu a identifier les différences entre la plateforme "fonctionnelle" et les autres pour lesquelles je rencontre le soucis.

Auriez-vous une idée d'où pourrait provenir le soucis ? 

**Desktop (please complete the following information):**
 - OS: CentOS7

**Comment by btry** [comment]
Bonjour,

Montrez le champ description du ticket cible sur les 2 instances. Précisez lequel est l'instance qui. Et fonctionne pas comme attendu.

**Comment by selkopb** [comment]
Merci beaucoup pour vos indications ! 

Effectivement grâce aux réponses du topic que vous mentionnez, j'ai pu tester en ajoutant le tag correspondant à la réponse de la question type "fichier" dans le champ description de la cible.

La pièce jointe est désormais bien rattachée au ticket créé.
