### ISSUE TITLE
2.13.0-alpha.2 Installation Error

### ISSUE THREAD

**Issue by eleducq** [pluginsGLPI/formcreator#2558]
Hello,

I have a problem when installing the plugin 2.13.0-alpha.2 on the version of GLPI 10, I have the following error

Changing the structure of the database - glpi_plugin_formcreator_targettickets (2 secondes)

2.13.0-alpha.2 multiple alter in glpi_plugin_formcreator_targettickets - Error while executing the query : ALTER TABLE `glpi_plugin_formcreator_targettickets` CHANGE `tickettemplates_id` `tickettemplates_id` INT NOT NULL DEFAULT '0' AFTER `type_question` - Error is Data truncated for column 'tickettemplates_id' at row 3

I start from a low stable GLPI version 9.5.6 with a database filled in and currently used in my company.
Do you have any leads to correctly install the plugins on version 10.

**Comment by btry** [comment]
Hi

Please run the following SQL query, and show the result

describe glpi_plugin_formcreator_targettickets;

**Comment by eleducq** [comment]
Here is the result when I run this command

![image](https://user-images.githubusercontent.com/98739327/151783171-fcf56230-f1ba-431b-89c6-cc4bc957c4e8.png)

**Comment by btry** [comment]
What is the previous version of Formcreator installed in your instance ?

**Comment by eleducq** [comment]
The previous version is V2.10.1.

**Comment by btry** [comment]
In version 2.10.1 the column tickettemplates_id allowed NULL values. This is not conventionnal in GLPI, and the column should change. 

I guess that this column contains rows with a NULL value. Please check this and tell if you find at least one.

select count(*) from  glpi_plugin_formcreator_targettickets where tickettemplates_id IS NULL

**Comment by eleducq** [comment]
Thanks for the help, there was indeed a row with a null value, I changed it and it's fine. Thanks a lot!
