### ISSUE TITLE
Refus d'un formulaire 

### ISSUE THREAD

**Issue by RdENIM** [pluginsGLPI/formcreator#256]
Bonjour à vous,

Lorsque nous saisissons un formulaire. Si nous le validons c'est ok. Par contre si nous le refusons la page reste bloqué. Je vous joins des copies d'écrans.

**Comment by btry** [comment]
Bonjour, 

les copies d'écran ne sont pas passées. Pouvez vous les ajouter  ?

**Comment by RdENIM** [comment]
[refus_dun_formulaire_sur_glpi.docx](https://github.com/pluginsGLPI/formcreator/files/480166/refus_dun_formulaire_sur_glpi.docx)
[refus_dun_formulaire_sur_glpi.docx](https://github.com/pluginsGLPI/formcreator/files/480257/refus_dun_formulaire_sur_glpi.docx)

**Comment by RdENIM** [comment]
Je n'avais pas validé le champs "Comment". Veuillez m'excuser...

**Comment by btry** [comment]
Le champ des commentaire est obligatoire dans ce cas, en effet.

**Comment by RdENIM** [comment]
non, non, non c'est pas dans le formulaire GLPI que je n'ai pas mis le commentaire, c'est dans le ticket pour mettre les copies d'écran.
Comme vous pouvez le voir dans les copies d'écran (le Formulaire) avec saisie le commentaire + appui sur refuser, nous restons bloqués sur la page : 
http://rvmlgdp01.enim.l2/glpi/plugins/formcreator/front/formanswer.form.php

**Comment by btry** [comment]
D'accord. J'ai regardé votre fichier.

Si vous avez une page blanche comme celle là, vous avez très certainement une erreur 500. Reproduisez le bug, puis vérifiez les dernières lignes dans les journaux d'erreur du serveur HTTP. 

En supplément, il peut y avoir des erreurs en relation dans glpi/files/_log/php-errors.log et glpi/files/_log/sql-errors.log. Si il y en a (même date et heure à quelques secondes près) elles me seront utiles également.

**Comment by RdENIM** [comment]
Bonjour à vous,

Effectivement dans le journal d'erreur HTTP, c'est assez causant.
Je vous joins ces trois fichiers.

Merci d'avance de votre retour,

René Danilo

**Comment by RdENIM** [comment]
[log-files-errors.zip](https://github.com/pluginsGLPI/formcreator/files/481759/log-files-errors.zip)

**Comment by RdENIM** [comment]
Voici ces trois fichiers dans log-files-errors.zip

René

**Comment by btry** [comment]
Bonjour

C'est bon : j'ai pu reproduire le comportement hier, et j'ai apporté une correction. Vos logs montrent que ma correction porte bien sur le souci que vous avez rencontré.

Vous pouvez re-télécharger l'archive.

**Comment by RdENIM** [comment]
Merci pour votre retour,

l'url est t-elle la suivante https://github.com/pluginsGLPI/formcreator/archive/master.zip, comme lors de la dernière correction du #221 ?

**Comment by btry** [comment]
Oui

**Comment by RdENIM** [comment]
J'ai toujours le même problème. Je vous joins les logs.
[sql-errors.zip](https://github.com/pluginsGLPI/formcreator/files/481999/sql-errors.zip)

**Comment by btry** [comment]
C'est de ma faute : j'ai versé la correction dans mon fork au lieu de le verser directement ici. 

vous pouvez reprendre l'archive; j'ai reversé la correction et vérifié que le dépot l'affiche bien.

![image](https://cloud.githubusercontent.com/assets/14139801/18663955/04e662fc-7f21-11e6-950c-6c3be41247f7.png)

**Comment by RdENIM** [comment]
Je pense que c'est bon. Le refus a fonctionné et le demandeur a bien reçu le mél comme quoi sa demande a été refusé.

**Comment by btry** [comment]
Parfait ! Merci pour vos tests, ils me sont utiles.
