### ISSUE TITLE
Form goes blank for tickets with e-mail notifications

### ISSUE THREAD

**Issue by raulcezar** [pluginsGLPI/formcreator#2561]
**Describe the bug**
What is happening is that the page goes blank (redirecting to /plugins/formcreator/front/form.form.php) after saving a form for tickets that send email notification. When refreshing the homepage, the ticket counter and ticket list are not updated, but the tickets appear to technicians. So, the users try to create new tickets over and over as they can't see them. 
If the user open a ticket without using the form it goes fine, it is redirected to the homepage and the ticket counter is also ok.
The notification is working fine, all emails have been received.

**To Reproduce**
1. Create a form 
2. Enable notification using SMTP
3. Set a notification for new tickets
4. Create a new ticket using the form

**Expected behavior**
Redirect to home where ticket counter has been incremented properly. 

**Screenshots**
**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.5
- Form Creator version 2.12.4

**Comment by btry** [comment]
Hi

When there is a blank page you should check if the HTTP server has a PHP (fatal) error in its logs. If any you should also find a backtrace. Check the logs and show what you found.

**Comment by btry** [comment]
Hi

I need to reproduce. When you submit the form, you may be in several places. I need to find which one you used
- preview tab in the administrative part of the plugin
- in Assistance > Form with a user with standard interface
- in the simplified interface (self service with  service catalog disabled)
- in the service catalog (simplified or extended service catalog)

The service catalog is configured in the entities, tab Form.

i also need clarification with notifications, as it appears to be the key of your problem. How do you enable or disable it ? Is it simply the notification flag of an actor added to the ticket ? Feel free to send a screenshot.

**Comment by raulcezar** [comment]
**Setup notification**

![1](https://user-images.githubusercontent.com/42142588/151980049-5ed40b7b-db50-4cc2-b828-dc306c4b8505.png)
_enable notification_

![2](https://user-images.githubusercontent.com/42142588/151980190-1bd75376-da6a-4f0c-84ff-89d81520c8f9.png)
_send email when creating a new ticket_

![3](https://user-images.githubusercontent.com/42142588/151980212-0fe4ecfb-e17d-4e53-b523-a2d1cac86f00.png)
![4](https://user-images.githubusercontent.com/42142588/151980239-62eec9a5-f956-442f-af3b-09a51b9bb03a.png)
_setup smtp_ 


**Create a ticket using a Form**

![5](https://user-images.githubusercontent.com/42142588/151980257-2cc20d36-6e1b-4f42-9a9e-889f1b52eabe.png)
_open a form_

![6](https://user-images.githubusercontent.com/42142588/151980267-42ff0f61-7cb0-4d6d-97ed-1c34ebf3b1f5.png)
_submit_

![7](https://user-images.githubusercontent.com/42142588/151980281-cfba670e-0d23-4133-b869-162d6e1e09fc.png)
_blank page_

![8](https://user-images.githubusercontent.com/42142588/151980287-a8fd9257-c8f5-45f6-b111-b39dac03b53f.png)
_come back to homepage_

**PS** 
**- Technicians are able to see the tickets but the user doesn't.** 
**- When I turn off the notification or create a new ticket without using a form, the error doesn't happen.**
**- Emails have been sent normally.**

**Comment by btry** [comment]
Hi

Formcreator 2.13.0 will be released soon, Formcreator 2.12 will reach its end of life. if no major problem is detected / reported this is a matter of days. Can you consider to see if the problem persists with Formcreator 2.13.0-rc.1 ?

On my side I do not reproduce.

**Comment by btry** [comment]
Hi

Good news, then I close this issue.
