### ISSUE TITLE
The problem of displaying data in the ticket. HTML tags

### ISSUE THREAD

**Issue by eleducq** [pluginsGLPI/formcreator#2562]
Here I am again, already with a new problem.
The descriptive text field allows the user to add whatever they want, image table and such, and I have an error since migrating to display.

Do you have an idea of ​​how it would be possible to transform or adapt old entries in order to keep pre-existing ticket data?

![image](https://user-images.githubusercontent.com/98739327/151804642-5de5f075-5f3f-4454-bb2a-fb3a2638706d.png)

**Comment by eleducq** [comment]
When I create even the most basic form response the user display gets corrupted, do you have any solution?

**Comment by btry** [comment]
Hi

You're trying Formcreator for GLPI 10, am I right ? If yes, then check you're using the version Alpha.3. I published it a few hours ago.

**Comment by eleducq** [comment]
When launching the update for alpha 3, I currently have this error message.

Unknown column 'is_dashboard_visible' in 'field list'

**Comment by eleducq** [comment]
I removed the Alpha 2 version before adding and installing the Alpha3 version, is this the correct manipulation?
Or I have to leave the existing Alpha2 files to add your new Alpha3 version.

**Comment by btry** [comment]
I see: you need replay upgrade step from 2.12 to 2.13. 

To do this, locate un your GLPI folder and run the following commands.

```
php bin/console glpi:plugin:install formcreator -f -p force-upgrade 
php bin/console glpi:plugin:activate formcreator
```

**Comment by eleducq** [comment]
OK thanks but could you tell me why the first command asks me to specify a user to use. And it tells me that the user entered is invalid

**Comment by btry** [comment]
When you install a plugin from the UI of GLPI, you are logged in as a user (a super admin). Plugins may require a valid super admin session when they run their installation process. Therefore the CLI tool provided by GLPI asks for a super admin account. Use "glpi" or an equivalent.

If you have doubts about the authenticity of this tool, please check it in the repository of GLPI.

**Comment by eleducq** [comment]
Yes, I actually use the glpi account which is super administrator and I have this error return.
![image](https://user-images.githubusercontent.com/98739327/151929430-b3c06472-517c-4ddd-892a-61d39a8a2986.png)

**Comment by eleducq** [comment]
And actually I don't have colum name 'is-dashboard_visible' in my database

**Comment by btry** [comment]
I did a try on my development instance.

I removed the column from the DB, then I ran the upgrade as I desctribed.

I don't getr any error, and the column is created, as expected.

Under the red backgrounded error you probably have a backtrace. Can you show it ?

**Comment by eleducq** [comment]
Sorry for the bad screenshot

![image](https://user-images.githubusercontent.com/98739327/151930959-79639341-450a-4012-962d-1e2ecb155b15.png)

**Comment by btry** [comment]
No backtrace here. Look in sql-errors.log.

**Comment by eleducq** [comment]
I have this actually.
![image](https://user-images.githubusercontent.com/98739327/151932261-d3007aa7-5be2-4c4d-83a4-aa6d911c8e75.png)

**Comment by eleducq** [comment]
OK it's good, just typo error on my part...

**Comment by eleducq** [comment]
Il y a un problème d'affichage des formulaires dans l'outil d'administration, il n'apparaisse plus

**Comment by eleducq** [comment]
Sorry in english, there is a problem displaying forms in the administration tool, it no longer appears but create work

**Comment by eleducq** [comment]
I close this tickets and I open another ^^
