### ISSUE TITLE
Displaying of forms

### ISSUE THREAD

**Issue by eleducq** [pluginsGLPI/formcreator#2564]
Actually update to v2.13.0 alpha.3 and the forms disappear on display :
![image](https://user-images.githubusercontent.com/98739327/151935994-bb61db04-20b6-4459-affb-ef9806f0e2af.png)

but when I check the database, they are well existing.
![image](https://user-images.githubusercontent.com/98739327/151936150-247ec36d-9a09-4a83-a219-5ad3b4ad03d1.png)

**Comment by btry** [comment]
Search for a PHP fatal error in the HTTP server logs, and check glpi/files/_log/php-errors.log .

**Comment by btry** [comment]
Also, tell the revision or the revision date of your GLPI 10.

**Comment by eleducq** [comment]
The migration to version 10 dates from 28/01/2022.

And this is the last log in php-errors.log
![image](https://user-images.githubusercontent.com/98739327/151937418-5758ec01-eee2-4d71-ace8-e2f044110f4d.png)

**Comment by eleducq** [comment]
And the part you can't see on the first screenshot
![image](https://user-images.githubusercontent.com/98739327/151937825-291c2f83-ee05-40de-9270-5cc4bd5c84ac.png)

**Comment by btry** [comment]
Those errors are not related to your issue. 

Open the developer tools of your browser, refresh the page and see the HTTP requests in the "network" tab. Check you don't have any request returning the code 500

**Comment by eleducq** [comment]
So I don't have any requests that return the 500 code when the page loads. But I have this error.
![image](https://user-images.githubusercontent.com/98739327/151953529-ee3cbb2b-714e-41e7-91a8-56a615fdaab7.png)

**Comment by btry** [comment]
I'm suspecting you tried a previous Alpha version : the missing column has been removed in one of them, but re-added a few days later. As the versions was an Alpha, no upgrade code was produced to restore the column and an upgrade to Alpha.3 ignored the missing column. 

Let's fix it the simple way : add the column in the table, after the column **content**, The type is unsigned int(10) not null default 0

**Comment by btry** [comment]
> in the previous alpha version this column was not also needed to display the forms?

Not in Alpha.2 where the column was removed. This was a bad choice, and it has been readded. 

Also, the whole table glpi_plugin_formcreator_categories should be missing in your instance. If I'm right you must recreate it. Here is the query:

```sql
CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_categories` (
  `id`                               int(11) NOT NULL AUTO_INCREMENT,
  `name`                             varchar(255) NOT NULL DEFAULT '',
  `comment`                          text,
  `completename`                     varchar(255) DEFAULT NULL,
  `plugin_formcreator_categories_id` int(11) NOT NULL DEFAULT '0',
  `level`                            int(11) NOT NULL DEFAULT '1',
  `sons_cache`                       longtext,
  `ancestors_cache`                  longtext,
  `knowbaseitemcategories_id`        int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `name` (`name`),
  INDEX `knowbaseitemcategories_id` (`knowbaseitemcategories_id`),
  INDEX `plugin_formcreator_categories_id` (`plugin_formcreator_categories_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

```

I did a quick check : if the table glpi_plugin_formcreator_categories is missing, I get the same SQL error as yours in the URL **plugins/formcreator/front/form.php**. This is consistent with your blank page. Re-adding  the missing structures should solve your problem.

**Comment by eleducq** [comment]
This table exists but has no data in it in my database.

![image](https://user-images.githubusercontent.com/98739327/151981950-4c383e29-629f-404c-aa4c-c7e18e20d5e2.png)

**Comment by btry** [comment]
It may be empty, there is no problem with that. 

Did you readd the foreign key **plugin_formcreator_categories_id`** in the table  **glpi_plugi_formcreator_forms** ?

**Comment by eleducq** [comment]
No I don't have this foreign key in this table.

**Comment by btry** [comment]
add it as I decribed 

> Let's fix it the simple way : add the column in the table, after the column content, The type is unsigned int(10) not null default 0

**Comment by btry** [comment]
```sql

ALTER TABLE `glpi_plugin_formcreator_forms`
	ADD COLUMN `plugin_formcreator_categories_id` INT(10) NOT NULL DEFAULT '0' AFTER `content`;
```

**Comment by eleducq** [comment]
Thank you, this has indeed corrected my problem. However, there is still a problem with the post form display of some tickets. Is this supposed to be fixed in the Alpha.3 version?

**Comment by eleducq** [comment]
Agreed, thank you again
