### ISSUE TITLE
Opened requests doesn't appear on front page

### ISSUE THREAD

**Issue by ghost** [pluginsGLPI/formcreator#2565]
Opened requests doesn't appear on front page, and the number of requests or finnished request on the top of the page, doesn't appear too.

Only thing that shows is "**N/A N/A N/A N/A**"

**Screenshots**
![glpiformsbug](https://user-images.githubusercontent.com/83595272/151958643-d343c13f-206f-4ab9-8492-b51c7ec0511f.png)

- GLPI version: 9.5.5
- list of all plugins:
	actualtime           
	news                 
	archires             
	behaviors           
	formcreator          
	fusioninventory      
	order               
	tag                 
	mod                 
	karastock            
	moreticket           
	dashboard            
	tasklists           
	webresources

**Comment by btry** [comment]
Hi

Which version of Formcreator. Was your instance upgraded before apparition of the problem ?

Also check sql-errors.log. there are very likely useful entries inside

**Comment by usernedel** [comment]
![image](https://user-images.githubusercontent.com/83595272/151960120-454c6477-0f3c-41cf-b024-6c7dfce2d2ed.png)

**Comment by usernedel** [comment]
> 

"formcreator          Name: Form Creator                   Version: 2.12.4     State: Enabled"

Yes, it was upgraded.

Here I see another issue, could it be associated with my problem?
![marketplaceissue](https://user-images.githubusercontent.com/83595272/151960815-ec237a34-da2e-4f00-89bf-05e2fb21ab9d.png)

**Comment by btry** [comment]
I believe that there is no write permission in the folder 'marketplace'. This is an other problem, very likely unrelated to your broken counters.

Check glpi/files/_log/sql-errors.log . There must be errors after displaying the counters.

**Comment by usernedel** [comment]
When I inspect the front page, return this error from formcreator:

"The requested URL /css_compiled/css_styles.min.css.map was not found on this server."

**Comment by btry** [comment]
> I found this warnings:

This will not break the counters.

> "The requested URL /css_compiled/css_styles.min.css.map was not found on this server."

this is not related to your issue.

When a counter shows N/A, then there must be a SQL error. Is there really nothing in glpi/files/_log/sql-errors.log ? No entry with a malformed SQL query ?

**Comment by usernedel** [comment]
I don't know why, but this file "sql-errors.log" does not exist in this folder... Just a file "remove"...

![nolog](https://user-images.githubusercontent.com/83595272/152171792-b0f8c8b2-2316-4dee-bd3d-d72440938d48.png)

**Comment by btry** [comment]
Hi

If the file does not exists, then your instance never had any problem with SQL queries, or the file has been deleted (and no subsequent SQL error ocurred).

Apply the following patch on Formcreator, reproduce the bug then view the last lines in php-errors.log. 

```diff
diff --git a/inc/issue.class.php b/inc/issue.class.php
index 7008924b..709c411f 100644
--- a/inc/issue.class.php
+++ b/inc/issue.class.php
@@ -909,6 +909,7 @@ class PluginFormcreatorIssue extends CommonDBTM {
       if ($counter === null || $counter == 'incoming') {
          $searchIncoming = Search::getDatas(PluginFormcreatorIssue::class,
                                           self::getProcessingCriteria());
+         Toolbox::logError('total count incoming: ' . $searchIncoming['data']['totalcount']);
          if (isset($searchIncoming['data']['totalcount'])) {
             $status[Ticket::INCOMING] = $searchIncoming['data']['totalcount'];
          }

```

You should find a line containing something like the following. The number is the value which should show in the 1st counter.

```
total count incoming: 49  {"user":"2@my-computer"} 
```

If you don't have a number, then you probably have a PHP warning logged immediately before the line.

**Comment by btry** [comment]
Hi

Having no feedback and this issue being obsolete (version 2.12) I close.
