### ISSUE TITLE
Selection by Userprofile/Group/etc

### ISSUE THREAD

**Issue by magheinz** [pluginsGLPI/formcreator#2569]
Is it possible, to show a Selection filtered by User/Group/etc?

I wan't ro create a form, where User can select a Network-Share and a User for managing Access-Rights.
But the User in group "dev" should only select network-Shares from x:\folders\dev
But the User in group "test" should only select network-Shares from x:\folders\test

and so on.

any Idea?

**Comment by btry** [comment]
Hi

Please ask common usage question on the forum. You can open issues here for feature requests, bug report or contributions

The forum is here: https://forum.glpi-project.org/
