### ISSUE TITLE
upgrade on glpi 10.0.0-rc1 Unknown column 'is_dashboard_visible' in 'field list'

### ISSUE THREAD

**Issue by ftoledo** [pluginsGLPI/formcreator#2573]
Upgrade glpi to 10 rc1 , then upgrate the plugin:

```
Tarea completa. (0 seconds)
Unknown column 'is_dashboard_visible' in 'field list'
```
![imagen](https://user-images.githubusercontent.com/95441/152407904-e813b6a6-db46-4838-89fa-7d0254639db7.png)

**Comment by btry** [comment]
Hi

Which was the version of Formcreator before you upgrade it ?

**Comment by ftoledo** [comment]
was from 2.13.0-alpha.1

> Hi
> 
> Which was the version of Formcreator before you upgrade it ?

was from 2.13.0-alpha.1

**Comment by btry** [comment]
Ok

Locate in the root folder of glpi then run the following command.

php bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade

**Comment by ftoledo** [comment]
I run the follow thaks, i thnk that unsigned interger warnings will go away too

```
php7.4 bin/console glpi:migration:unsigned_keys
Found 5 primary/foreign key columns(s) using signed integers.
Desea continuar? [Yes/no]y
 5/5 [============================] 100%
Migration done.
```

**Comment by btry** [comment]
The warnings about the unsigned integers will remain. I began today a work to fix it. It should be ready soon.

**Comment by btry** [comment]
Hi

https://github.com/pluginsGLPI/formcreator/pull/2572 : merged.

To upgrade to Formcreator 2.13 (and from a GLPI 9.x), admins must upgrade the database with ```glpi:migration:unsigned_keys```, then run the upgrade of Formcreator.

Warnings will occur as you observed, but future upgrades should no longer show such warnings.

I think I can close this issue now. Thank you for your tests.
