### ISSUE TITLE
glpi 10.0.0-rc1 can assign myself (or observe) a ticket 2 times 

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2577]
**Describe the bug**
As a technician, i can assign myself a ticket 2 times (not 3), 
same for the observer, i can be 2 times an observer

When i try to remove 1 of the 2 identical names, it's very complicated ^^  my name remains 2 times.

**To Reproduce**
Open a ticket
assign to your name using the search list
save
self assign using the "small human icon"
save... 
==> your name is 2 times listed. (and the small human icon is still there...)
try to remove 1 of your name.. save...  your name is still listed 2 times.

**Expected behavior**
you can't list your name several times as a technician or an observer

**Screenshots**
)

**Comment by btry** [comment]
Hi

You said that ou open a ticket. Then you don't use formcreator for this step, right ?

**Comment by mirda123** [comment]
oups my bad, i posted the issue at the wrong place.... sorry.. , yes it's a glpi issue.. 
i will post again at the right place...

**Comment by btry** [comment]
Before opening an issue on glpi, search for my latest issues. I opened something similar to take note of a bug. Avoid duplicates

**Comment by mirda123** [comment]
this one ? https://github.com/glpi-project/glpi/pull/10496

**Comment by dethegeek** [comment]
No. It is a bit older, and as far as I know, it is  not fixed. To be
verified. You can write in the search area 'author:btry' to filter my
reports

**Comment by btry** [comment]
No. It is a bit older, and as far as I know, it is  not fixed. To be
verified. You can write in the search area 'author:btry' to filter my
reports
