### ISSUE TITLE
Add "Change template" on form target

### ISSUE THREAD

**Issue by cyh67** [pluginsGLPI/formcreator#2579]
Hello team

When we create a form, we can select a target (to create something from this form)

In target, we can select "Ticket" and then, select "Ticket Template"
But if we select "Change" we cannot select "Change template"

Could you please add this feature ? Select a "Change template" in the target of a form ?

If you need more precision, do not hesitate to let me know.
Cyril

**Comment by btry** [comment]
Hi

This is already implemented in the incoming 2.13.0 version.

Feel free to test it by installing GLPI 10 rc1 and Formcreator 2.13.0-alpha.3

![image](https://user-images.githubusercontent.com/14139801/152764978-9356b259-6a87-48d3-82d7-97c03ecaf840.png)

**Comment by cyh67** [comment]
Very nice
Thank you very much :)
Have a nice day
