### ISSUE TITLE
Feature Request:  Conditional/Dependant Questions

### ISSUE THREAD

**Issue by plight** [pluginsGLPI/formcreator#258]
This is a GREAT GLPI Plugin.  One thing that would make it better would be questions that depend on other questions. 

For example:
Question A asks about a type of object
Question will change depending on the type of object selected in Question A

Also, questions could be hidden unless some value is selected by the users within the form.

**Comment by sulian** [comment]
👍 Will be a great thing, I'm looking for a form for cartridge remplacement.

**Comment by gotanbl** [comment]
Also, if I choose Location in one question, it would be nice if in next question is possible to list all items on that location!

**Comment by Armin83** [comment]
Already done or ?

**Comment by btry** [comment]
Hi,

This is not done yet

**Comment by SylvainGuibert** [comment]
I'am agree. I'm looking for this feature too !

**Comment by btry** [comment]
Hi

The plugin now supports dependency between question. the questions using the feature are very specific to a user, then they were not added in the repository. Admins may develop theyr own type of questions to implement dependencies, and if these new types are relevant for generic use, they may be submitted via a pull request. For now no generic use case was submitted.

As the feature exists, I close this ticket.
