### ISSUE TITLE
New dropdown values not included in a form dropdown

### ISSUE THREAD

**Issue by kabassanov** [pluginsGLPI/formcreator#2584]
Hi,

I've just upgraded to 2.12.4 and I can observe something strange. In one of my forms I use a dropdown with values from a user defined list (through Fields plugin). I can see values already present before the upgrade, but any new value remains invisible to the form dropdown.

Ex: Let's say I defined "Tag" in Fields, so Setup -> Dropdowns displays: Additional Fields and Tag under it. Before plugin update I had values Value1 and Value2. Now, I create Value3. 

If I go to my form that uses Tag and I scroll in values, I can see Value1 and Value2, but not the freshly added Value3. 
It seems that it is because it is filtered in inc/dropdown.class.php function getDropdownValue as $post already contains a list of ids:

```(
    [itemtype] => PluginFieldsFinancialprojecttagfieldDropdown
    [display_emptychoice] => 1
    [displaywith] => Array
        (
            [0] => id
        )

    [emptylabel] => -----
    [condition] => Array
        (
            [glpi_plugin_fields_financialprojecttagfielddropdowns.id] => Array
                (
                    [0] => 0
                    [1153] => 1153
                    [1152] => 1152
                    [1154] => 1154
                    [1072] => 1072
...
```
but I don't see where this list is created...

I have still another instance of GLPI with Form Creator 2.12.2 and it works perfectly.

I use GLPI version 9.5.6 with all bug commits (so I use 9.5.7).

Any idea?

**Comment by btry** [comment]
Hi

Is the type PluginFieldsFinancialprojecttagfieldDropdown a tree dropdown ?

**Comment by kabassanov** [comment]
Hum... I use Fields 1.12.8...  I have only one Dropdown type in the field creation tab... Did I miss something?

**Comment by btry** [comment]
I did not worked not used the Fields plugin, then I don't know it well.

By reading the code of Formcreator, I found that the condition may be built from code dedicated to itemtypes using a tree structure (like entities, ITIL categories). I need confirmation.

**Comment by kabassanov** [comment]
I do use entities and subentities. I tried to debug a little bit, but I'm lost between ajax, js and php functions calls... In addition I think not to be able to Toolbox:logError from js calls...

**Comment by btry** [comment]
Toolbox::logError() is a PHP method.

The drop-down you use uses lazy loading. This emans that the drop-down is displayed, and only when you open it, an Ajax call gets items. If there are many items, scrolling among them will trigger more Ajax calls to get more items, with a pagination mechanism.

When the PHP code generated a dropdown, it sets a condition and stores it in the server side session. The HTML and js for the drop-down contains a hash of the condition. This hash is used serverside to recognize the condition to apply when searching the items to return to the browser.

**Comment by kabassanov** [comment]
OK.

I know that Toolbox::logError() is a PHP method, but tried to use it during ajax php calls... With no success. I'm sure the code is executed, because if I put a typo in it, this rises an error. But no log...

OK about lazy loading. That is the way I got the log I posted in my first message. But somehow the post condition was already set. So I need to find where conditions and their hashes are generated in the code.

**Comment by kabassanov** [comment]
Yes it seems that dropdowns are tree structures...
But should I clean cache every time a new entry is created in this dropdown ("intitulé" in order to distiguish from dropdown field)?

**Comment by btry** [comment]
No. The cache is invalidated in GLPI when you add / delete / move an item. You may try to use ITIL categories to check.

If you need to reset cache each time you edit your items then there is a problem.

**Comment by btry** [comment]
You probably have a cache problem

**Comment by kabassanov** [comment]
Does it work for you (not in glpi 10)?
In particular if you create a form with a dropdown linked to itil categorie, then you add an entry in itil categories dropdown, then you check if the value is present in your form fropdown...

I have no error messages related to cache in php-errors...

**Comment by btry** [comment]
Hi

I did a test with a form containing a glpi objetc / entitiy question. I see my entities as expected. With a new tab I add a new entity in the DB. After a refresh of the preview tab of my form, I see the newly created entity. 

Maybe your problem is just you did not refreshed the form ?

**Comment by kabassanov** [comment]
Hi,

I've just made another test following your setup. The issue is not present when I add a GLPI Object and then select Administration Entity. But I still have problem with dropdown type questions, like Dropdown and ITIL Category... Could you check this, please?

**Comment by btry** [comment]
I reproduced. Please try the above fix and fedback.

**Comment by kabassanov** [comment]
It is ok for me. Even without a form page refresh. 
But there is one general question remaining... when should cache entry be updated?

**Comment by btry** [comment]
From my findings, god news. The cache is not responsible of your problem.

Cache is updated in glpi core, in commondbtree.class.php.

**Comment by kabassanov** [comment]
Is it also true for [glpicondition] => Array ? Doesn't seem...

**Comment by btry** [comment]
glpicondition ? 

If you mean the condition to filter items to show in a dropdown, no. The condition is stored in $_SESSION.

**Comment by kabassanov** [comment]
Yes, this one. Hmmm, not sure to understand, it seems that cleaning the cache cleans it also... But who updates it?

**Comment by btry** [comment]
Hi

I cannot help you to investigate in the code about cache : I'm too busy with my tasks. To find how $_SESSIONS stores a codition for a lazy loaded dropdown, check in the code of GLPI for  the string ```$_SESSION['glpicondition']```

Hope this helps. 

Anyway, as the fix I found does not involves the cache, and you validated it is working, I guess you don't need to check how the  cache works.

I close this issue aas  the bug is solved. If you want to understand some parts of code in GLPI, I recommend you to ask on the forum instead. You will probably have more people available to help you.
