### ISSUE TITLE
Creating a question with conditionnal display based on a choosen entity AND a regexp filtering don't work

### ISSUE THREAD

**Issue by shalien** [pluginsGLPI/formcreator#2587]
**Describe the bug**
When isung conditional display for a question based on a previous question where the answer is an glpi entity, the regexp search won't work.

**To Reproduce**
1. Have at least to differents entity in your glpi
2. Create a new form
2. Create a new section
3. Create a question with : type = GLPi Object, Obhect = Entity
4. Create a second question of any type but in the condition for display choose either display / hide -> using regexp -> type the name of an entity 

**Expected behavior**
Being able to target entity using a regexp to discriminate the entities' name

**Screenshots**
Question 1
![image](https://user-images.githubusercontent.com/4563098/153608243-4fffa397-ecf3-4cfc-8895-43fd96571c75.png)
Question with conditional display
![image](https://user-images.githubusercontent.com/4563098/153608522-5330bb20-1e2f-4c60-9962-790ca60bc94f.png)
Form Preview
![image](https://user-images.githubusercontent.com/4563098/153608795-cf407f2f-07f1-4eee-bc6d-95c222ad7698.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.6
- formcreator          Name: Form Creator                   Version: 2.12.4     State: Enabled
  fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Installed / not activated

**Desktop :**
 - OS: Windows 10 
 - Browser [e.g. chrome, safari] : Opéra GX
 - Version [e.g. 22] LVL3 (core: 83.0.4254.46)

**Additional context**
Looking a the log show error messages like : 
AH01071: Got error 'PHP message: PHP Warning: preg_grep() expects parameter 2 to be array, string given in [glpi./marketplace/formcreator/inc/field/glpiselectfield.class.php](/smb/file-manager/code-editor?currentDir=%2F%2Fvar%2Fwww%2Fvhosts%2%2%2Fmarketplace%2Fformcreator%2Finc%2Ffield&subscriptionId=1&file=glpiselectfield.class.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F6) on line 249', referer: https://glpi/marketplace/formcreator/front/form.form.php?id=1

Further investigation show that in this case show that the preg_grep method is being given "user regexp" / "entity id" as input value cue the error

**Comment by btry** [comment]
Hi

This fix (for Formcreator 2.13.0, but should be appliicable to 2.12.x) should fix the problem.

**Comment by btry** [comment]
Hi

Having no feedback I asume the fix solved the problem.
