### ISSUE TITLE
Conditions are not completely removed

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#260]
Version 0.85-1.2.3 & 0.90-1.3.4
Add a condition to question2, depending on question1 (hidden unless...).
Go back to question2 is always visible -> table glpi_formcreator_questions_conditions is not cleanup : it remains a record for question2 with old values. Dangerous because when you go back to old condition (hidden unless..), you get the old data !

Additionnaly, delete question2 : table glpi_FC_questions_conditions is not cleaned up (when glpi_FC_questions is) -> the database is no longer consistent !

**Comment by btry** [comment]
Hi 

Here is a branch to fix this issue : https://github.com/btry/formcreator/tree/260_conditions_not_completely_removed

Direct download https://github.com/btry/formcreator/archive/260_conditions_not_completely_removed.zip

-Do not re-add a condition for a question reset to always visible
-remove conditions related to the question being deleted
-reset to always visible a question if the question providing the condition is removed

I think the glpi_plugin_formcreator_questions_conditions table will be more consistent now.

I'm waiting for your feedback

**Comment by blerohellec** [comment]
OK. Corrected

**Comment by blerohellec** [comment]
Pas tout à fait. J'ai cette erreur sql, lorsque l'on supprime la question (en l'occurence la question 87)

  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_questions` SET `show_rule`=\'always\'
            WHERE `id` IN (
                  SELECT * FROM `glpi_plugin_formcreator_questions_conditions`
                  WHERE `show_field` = \'87\'
            )
  Error: Operand should contain 1 column(s)
  Backtrace :
  plugins/formcreator/inc/question.class.php:499     
  inc/commondbtm.class.php:1338                      PluginFormcreatorQuestion->post_purgeItem()
  plugins/formcreator/front/question.form.php:33     CommonDBTM->delete()

**Comment by btry** [comment]
Hi

I updated the branch to fix this error. Please download again the file to test it.

Thank you for your feedback

**Comment by blerohellec** [comment]
OK. Corrected
