### ISSUE TITLE
Formcreator v2.13.0-alfa.3 in Simplified interface GLPI 10 RC1

### ISSUE THREAD

**Issue by bolivarf** [pluginsGLPI/formcreator#2612]
**Describe the bug**
Because when activating the formcreator plugin v2.13.0-alpha.3, in the Simplified interface of GLIP 10 RC1, the Create a ticket and Tickets menus do not appear, and instead the Issues menu appears.

**To Reproduce**
1. Login GLPI Simplified interface
2. Home, Forms, Issues, Reservations, FAQ menus shown

**Expected behavior**
See Home, Forms, Create a ticket, Tickets, Reservations, FAQ menus
**Screenshots**
**Desactivate Formcreator**
![Captura de pantalla de 2022-02-20 09-51-55](https://user-images.githubusercontent.com/7965864/154864268-f6d51a0f-2b66-4676-8496-5357bed115dc.png)
**Activate Formcreator**
![Captura de pantalla de 2022-02-20 09-21-47](https://user-images.githubusercontent.com/7965864/154864426-253269b7-ed07-405f-833b-f9699a60a325.png)

**GLPI / Plugins :**
- GLPI version GLPI 10.0.0-rc1
- list of all plugins (available in GLPI > Setup > General > tab System > bottom of the page)
	formcreator        Version: 2.13.0-alpha.3
	mreporting          Version: 1.8.0-rc2 ( activated or deactivated the result is the same)

**Desktop :**
 - OS:  Ubuntu 20.04
 - Browser Google Chrome
 - Version 98.0.4758.102 (Build oficial) (64 bits)

**Additional context**
The user profile that has the simplified interface does not have privileges to create or view issues only create and see tickets

**Comment by btry** [comment]
Hi

Please show the configuration of the entity : administration > entities > tab "forms"

I want to see if the service catalog is enabled

**Comment by bolivarf** [comment]
![Captura de pantalla de 2022-02-21 01-35-31](https://user-images.githubusercontent.com/7965864/154895554-c4dd3bb9-99c5-4405-bf76-7b368105451c.png)

**Comment by bolivarf** [comment]
Original screenshots the last one was a test
![Captura de pantalla de 2022-02-21 01-38-40](https://user-images.githubusercontent.com/7965864/154895767-51a00d40-0ef5-4059-9cb7-0df09108ea35.png)

**Comment by bolivarf** [comment]
Helpdesk mode: Service catalog simplified/Service catalog extended
![Captura de pantalla de 2022-02-21 01-45-31](https://user-images.githubusercontent.com/7965864/154897297-cb7f8b4f-d016-463c-942a-44906b965eaf.png)

**Comment by bolivarf** [comment]
I tried all the combinations in administration > entities > tab "forms"

**Comment by bolivarf** [comment]
I made the changes and these generated errors in the database that I was able to solve with

> ALTER TABLE `glpi_plugin_formcreator_entityconfigs` ADD `entities_id` INT UNSIGNED NOT NULL DEFAULT '0' AFTER `header`, ADD INDEX `entities_id` (`entities_id`);
> UPDATE `glpi_plugin_formcreator_entityconfigs` SET `entities_id`=`id`

but now if I enter the issues in simplified interface there is an error
**SQL error "1052": column 'users_id_recipient' in where clause is ambiguous in query "SELECT DISTINCT `glpi_plugin_formcreator_issues`.`id` AS id...**

**Comment by btry** [comment]
Hi @bolivarf 

The PR which appears in this thread does not fix anything yet. I just added automatic tests, I did not determined yet if this is a bug or not. 

Comment in the code says this behaviour is intentional; but I need to double check, as I have a doubt.

For your dv problem try to force upgrade the plugin. In recent closed issues, there are instructions do to it.

**Comment by bolivarf** [comment]
> Hola @bolivarf
> 
> El PR que aparece en este hilo no soluciona nada todavía. Acabo de agregar pruebas automáticas, aún no he determinado si esto es un error o no.
> 
> El comentario en el código dice que este comportamiento es intencional; pero necesito verificar dos veces, ya que tengo una duda.
> 
> Para su problema de base de datos, intente forzar la actualización del complemento. En números cerrados recientes, hay instrucciones para hacerlo.

ok thank you very much I no longer have the bd error when applying the Sql error solution: ambiguous column #2594

**Comment by stdglpi** [comment]
I'm following also this topic, Looks like I have the same issue.

I have GLPI RC2 and the last Formcreator v2.13.0-alfa-dev

I precise i'm not on the catalogue interface.

![image](https://user-images.githubusercontent.com/63521311/159531740-27578b3a-8c2d-41f6-ad13-991129b9d30b.png)

![image](https://user-images.githubusercontent.com/63521311/159532035-9b68f14c-945d-464b-be19-9a05ce9da911.png)

**Comment by bolivarf** [comment]
The same error occurs in GLPI 10 RC3

**Comment by stdglpi** [comment]
> The same error occurs in GLPI 10 RC3

They said this week end the alpha v4 will be available.

**Comment by btry** [comment]
Hi

@stdglpi : I guess you upgraded Formcreator from a 2.13.0-alpha (1, 2 or 3) to a more recent build. There were some changes in the DB, and the upgrade process does not supports upgrades between your previous  version to the curent one (this is normal).

Try to run a forced upgrade:
locate un formcreator's folder
run ```../../bin/console glpi:plugin:install formcreator -f -p force-upgrade```, then re-enable the plugin.
This should add the missing columns in the DB.

**Comment by btry** [comment]
@bolivarf :

I confirm that formcreator 2.13 will remove the menu entries to create and view tickets. The purpose of the plugin is to replace the helpdesk simplified interface. The entry "Issues" is the place for a self-service user to view his assistance requests. Assistance requests are a mix of answers to forms and tickets (included those not created via the plugin).

It is still possible to change this behaviour by patching the code ( PluginFormcreatorCommon::hookRedefineMenu() ). Mainstream branches will keep the current behaviour.

**Comment by stdglpi** [comment]
@btry

> Hi
> 
> @stdglpi : I guess you upgraded Formcreator from a 2.13.0-alpha (1, 2 or 3) to a more recent build. There were some changes in the DB, and the upgrade process does not supports upgrades between your previous version to the curent one (this is normal).
> 
> Try to run a forced upgrade: locate un formcreator's folder run `../../bin/console glpi:plugin:install formcreator -f -p force-upgrade`, then re-enable the plugin. This should add the missing columns in the DB.

After the command my GLPI is blocked with this error : 
`PHP Deprecated:  Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51`

I turned off the plugin for the moment.

thx

**Comment by bolivarf** [comment]
@btry 
I understand that it seems like a good idea to me but on the one hand when I check the privileges for the user profile with the simplified interface there is no way to give permission to problems and on the other hand it gives an error when querying issues Column 'users_id_recipient' in where clause is ambiguous me I am testing the plugin by uninstalling it and reinstalling it again to be sure that its database is deleted and does not bring garbage, I also directly check the content of the database and force the update of the plugin that would be unnecessary for this case.
![Captura de pantalla de 2022-03-23 09-19-19](https://user-images.githubusercontent.com/7965864/159711422-a2158440-e476-44f6-8a0e-ab31832c0cde.png)
SQL Error "1052": Column 'users_id_recipient' in where clause is ambiguous in query "SELECT DISTINCT `glpi_plugin_formcreator_issues`.`id` AS id, 'test' AS currentuser, `glpi_plugin_formcreator_issues`.`itemtype`, `glpi_plugin_formcreator_issues`.`entities_id`, `glpi_plugin_formcreator_issues`.`is_recursive`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_plugin_formcreator_issues`.`name`, '$#$' , `glpi_plugin_formcreator_issues`.`id`) ORDER BY `glpi_plugin_formcreator_issues`.`id` SEPARATOR '$$##$$') AS `ITEM_PluginFormcreatorIssue_1`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_formcreator_issues`.`display_id`, '__NULL__'), '$#$', `glpi_plugin_formcreator_issues`.`id`)ORDER BY `glpi_plugin_formcreator_issues`.`id` SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_PluginFormcreatorIssue_1_display_id`, `glpi_plugin_formcreator_issues`.`display_id` AS `ITEM_PluginFormcreatorIssue_2`, `glpi_plugin_formcreator_issues`.`status` AS `ITEM_PluginFormcreatorIssue_4`, `glpi_plugin_formcreator_issues`.`date_creation` AS `ITEM_PluginFormcreatorIssue_5`, `glpi_plugin_formcreator_issues`.`date_mod` AS `ITEM_PluginFormcreatorIssue_6`, `glpi_entities`.`completename` AS `ITEM_PluginFormcreatorIssue_7`, `glpi_users_requester_id`.`name` AS `ITEM_PluginFormcreatorIssue_8`, `glpi_users_requester_id`.`realname` AS `ITEM_PluginFormcreatorIssue_8_realname`, `glpi_users_requester_id`.`id` AS `ITEM_PluginFormcreatorIssue_8_id`, `glpi_users_requester_id`.`firstname` AS `ITEM_PluginFormcreatorIssue_8_firstname` FROM `glpi_plugin_formcreator_issues` LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24` ON (`glpi_plugin_formcreator_issues`.`itemtype` = "Ticket" AND `glpi_plugin_formcreator_issues`.`items_id` = `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`tickets_id` AND `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`type` = '1' ) LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd` ON (`glpi_plugin_formcreator_issues`.`itemtype` = "Ticket" AND `glpi_plugin_formcreator_issues`.`items_id` = `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`.`tickets_id` AND `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`.`type` = '3' ) LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5` ON (`glpi_plugin_formcreator_issues`.`itemtype` = "Ticket" AND `glpi_plugin_formcreator_issues`.`items_id` = `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`tickets_id` AND `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`type` = '2' ) LEFT JOIN `glpi_ticketvalidations` ON (`glpi_plugin_formcreator_issues`.`itemtype` = "Ticket" AND `glpi_plugin_formcreator_issues`.`items_id` = `glpi_ticketvalidations`.`tickets_id` )LEFT JOIN `glpi_groups` AS `glpi_groups_groups_id_validator` ON (`glpi_plugin_formcreator_issues`.`groups_id_validator` = `glpi_groups_groups_id_validator`.`id` ) LEFT JOIN `glpi_tickets` ON (`glpi_tickets`.`id` = `glpi_plugin_formcreator_issues`.`items_id` AND `glpi_plugin_formcreator_issues`.`itemtype` = 'Ticket' ) LEFT JOIN `glpi_ticketvalidations` AS `glpi_ticketvalidations_efead4a1e4d0f1413d363b6502c29dca` ON (`glpi_tickets`.`id` = `glpi_ticketvalidations_efead4a1e4d0f1413d363b6502c29dca`.`tickets_id` )LEFT JOIN `glpi_users` AS `glpi_users_users_id_validate_57751ba960bd8511d2ad8a01bd8487f4` ON (`glpi_ticketvalidations_efead4a1e4d0f1413d363b6502c29dca`.`users_id_validate` = `glpi_users_users_id_validate_57751ba960bd8511d2ad8a01bd8487f4`.`id` )LEFT JOIN `glpi_entities` ON (`glpi_plugin_formcreator_issues`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_users` AS `glpi_users_requester_id` ON (`glpi_plugin_formcreator_issues`.`requester_id` = `glpi_users_requester_id`.`id` ) WHERE (( `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.users_id = '35' OR `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`.users_id = '35' OR `glpi_plugin_formcreator_issues`.`requester_id` = '35' OR `glpi_ticketvalidations`.`users_id_validate` = '35') OR `glpi_plugin_formcreator_issues`.`users_id_validator` = '35' OR `glpi_plugin_formcreator_issues`.`groups_id_validator` IN ('') OR `glpi_users_users_id_validate_57751ba960bd8511d2ad8a01bd8487f4`.`id` = '35' OR `users_id_recipient` = 35 ) AND ( `glpi_plugin_formcreator_issues`.`status` IN ('5','6') ) GROUP BY `glpi_plugin_formcreator_issues`.`id` ORDER BY `ITEM_PluginFormcreatorIssue_6` DESC "

Patching the code ( PluginFormcreatorCommon::hookRedefineMenu() ) doesn't seem like a good idea, it's better to add a mode for the form plugin in the entity.
In any case, I already have an idea of where you want to go, maybe I can help is that.

**Comment by stdglpi** [comment]
for IFY i'm in GLPI RC3 now

**Comment by btry** [comment]
@stdglpi 

> After the command my GLPI is blocked with this error :
PHP Deprecated: Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51

I turned off the plugin for the moment.


Please open a distinct issue for  that. This requires attention. I think I'll have some questions to find how this happens.

@bolivarf : the same for you : you must open an other issue : this one becomes unreadable because of the off topic messages. This is important when it  takes time to solve reports.

**Comment by stdglpi** [comment]
> @stdglpi
> 
> > After the command my GLPI is blocked with this error :
> > PHP Deprecated: Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51
> 
> I turned off the plugin for the moment.
> 
> Please open a distinct issue for that. This requires attention. I think I'll have some questions to find how this happens.
> 
> @bolivarf : the same for you : you must open an other issue for your SQL error: this one becomes unreadable because of the off topic messages. This is important when it takes time to solve reports.

Well noted.

**Comment by btry** [comment]
@bolivarf : Your SQL error is very likely already fixed. Try this more recent build.

[glpi-formcreator-2.13.0-pre-alpha.4.zip](https://github.com/pluginsGLPI/formcreator/files/8333833/glpi-formcreator-2.13.0-pre-alpha.4.zip)

**Comment by stdglpi** [comment]
> @stdglpi : I think this fix should solve your deprecation notice
> 
> #2651
> 
> It impacts the way Formcreator adds its own menu entries. Check if they are all present, as expected.

@btry it seems that #2651 fixed the problem.
I can now use the plugin formcreator :)

I tried to check the simplified interface on a user and I have this info : 

![image](https://user-images.githubusercontent.com/63521311/159755122-66b3d740-181f-4cee-880b-f655a9896c69.png)

I tried to 
`php bin/console glpi:plugin:install -f -p force-upgrade formcreator`

But I obtain the same error.

**Comment by stdglpi** [comment]
@btry should I pass the [glpi-formcreator-2.13.0-pre-alpha.4.zip](https://github.com/pluginsGLPI/formcreator/files/8333833/glpi-formcreator-2.13.0-pre-alpha.4.zip) also ?

**Comment by btry** [comment]
@stdglpi : yes, there are too many changes and fixes since Alpha.3. It is better to  test pre-alpha.4 now.

I plan to release Alpha.4 this week.

**Comment by bolivarf** [comment]
@btry @stdglpi 
I tried with the development version of the plugin and I see that the database error does not appear, however the tickets that are seen in Issus are the ones that are created when the plugin is active, the tickets created previously or while the plugin is deactivated do not appear, I do not see in the glpi_plugin_formcreator_issues table any field that cannot be obtained from a view of the native glpi tables, since otherwise the plugin would have to verify during activation that tickets are not part of Issus. Maybe I still don't understand some things and I'm wrong.

**Comment by stdglpi** [comment]
@bolivarf  @btry  I tried to pass the pre alpha4 but I have still this error SQL 1054
As said @btry maybe I missed something during the upgrade (alpha 1,2,3, ..X)

I will waiting the ALPHA 4 this week and I will test.
If I have the same issue I will open a new topic 

I thought at first I had the same symptoms as @bolivarf  but that seems like a separate problem.

good evening

**Comment by btry** [comment]
Hi

> After the command my GLPI is blocked with this error :
PHP Deprecated: Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51

I thikn this patch will solve the deprecation notice: https://github.com/pluginsGLPI/formcreator/pull/2651

**Comment by stdglpi** [comment]
@btry it is better now :) !

![image](https://user-images.githubusercontent.com/63521311/160106323-d358cff3-7211-4274-be4a-6774e9584f67.png)

no errors on "issues" menu.

If I want to display all the forms they say we have to create a "category" 
is this behavior required?

![image](https://user-images.githubusercontent.com/63521311/160106356-c8aa8589-050e-4a09-b987-7715955f8b6e.png)

**Comment by stdglpi** [comment]
@btry sorry I think I have to re upload my forms. they are not present.

**Comment by btry** [comment]
> If I want to display all the forms they say we have to create a "category"
is this behavior required?

No, it is not said you must create a category. You must choose a category. But in your case none exist. The "home" pictogram is a root category containing all those you may create. If you are located in thos root, then forms will show without restriction by category (but keywords filtering will allpy)

**Comment by bolivarf** [comment]
I am trying to create a test form and when I try to add a question, the fields related to the question type do not appear, for example, for the checkboxes the values and default values so if I try to add it, I get an error that this type of question requires parameters. I am now using the plugin from the development source. I am also forcing the update and clearing the cache using the corresponding bin/console commands.
![Captura de pantalla de 2022-03-25 09-17-59](https://user-images.githubusercontent.com/7965864/160155582-ac203861-ca51-421b-8940-1ce9ed27ac35.png)
![Captura de pantalla de 2022-03-25 09-37-24](https://user-images.githubusercontent.com/7965864/160155579-6e5066cd-431b-4e6e-972d-eb3977a3cb08.png)

**Comment by bolivarf** [comment]
> I am trying to create a test form and when I try to add a question, the fields related to the question type do not appear, for example, for the checkboxes the values and default values so if I try to add it, I get an error that this type of question requires parameters. I am now using the plugin from the development source. I am also forcing the update and clearing the cache using the corresponding bin/console commands. ![Captura de pantalla de 2022-03-25 09-17-59](https://user-images.githubusercontent.com/7965864/160155582-ac203861-ca51-421b-8940-1ce9ed27ac35.png) ![Captura de pantalla de 2022-03-25 09-37-24](https://user-images.githubusercontent.com/7965864/160155579-6e5066cd-431b-4e6e-972d-eb3977a3cb08.png)

The behavior mentioned above seems to occur only in Google Chrome I cleared the cache of the site and nothing but in Firefox it seems to work.

**Comment by bolivarf** [comment]
> @btry @stdglpi I tried with the development version of the plugin and I see that the database error does not appear, however the tickets that are seen in Issus are the ones that are created when the plugin is active, the tickets created previously or while the plugin is deactivated do not appear, I do not see in the glpi_plugin_formcreator_issues table any field that cannot be obtained from a view of the native glpi tables, since otherwise the plugin would have to verify during activation that tickets are not part of Issus. Maybe I still don't understand some things and I'm wrong.

Run
bin/console glpi:plugins:formcreator:syncissues
fix this

**Comment by bolivarf** [comment]
> The behavior mentioned above seems to occur only in Google Chrome I cleared the cache of the site and nothing but in Firefox it seems to work.

I checked the plugin in incognito mode and adding questions works so I switched to normal mode and reset Google Chrome settings, checked that the plugin worked, changed my custom settings and checked again that it worked. I don't know what option was affecting the system but it works now.

**Comment by btry** [comment]
Hi

I shared in several threads a more recent build of the plugin, pre-alpha.4. a release is planned very soon, I hope this week. Please use this version instead of alpha.3, as many fixes were done.

**Comment by stdglpi** [comment]
@btry where I can dowload it ?

**Comment by bolivarf** [comment]
@btry I'm using the github development branch which has the most recent updates made by you. In any case, I have a branch with that version and if something strange happens to me, I change to that.

**Comment by btry** [comment]
Hi

Here is a build of the latest revision of the branch support/2.13.0 (identical to develop for now)

[glpi-formcreator-2.13.0-pre-alpha.4.zip](https://github.com/pluginsGLPI/formcreator/files/8360602/glpi-formcreator-2.13.0-pre-alpha.4.zip)

**Comment by bolivarf** [comment]
@btry thank you

**Comment by btry** [comment]
Hi

This issue is obsolete : changes have been done in the menu, latest testing versin is 2.13.0-rc.1. I close.
