### ISSUE TITLE
Attached files missing in mail notification for new tickets

### ISSUE THREAD

**Issue by kabassanov** [pluginsGLPI/formcreator#2614]
Hi,

Long time ago, we discussed about missing filenames and wrong counter in email notifications for new tickets created through Formcreator ( https://forum.glpi-project.org/viewtopic.php?id=251773 ). I was pretty sure to had opened a bug report for this, but it seems that I didn't...

In the meantime I created some messy patches as workaround, but now I try to find what happens... It seems that PluginFormcreatorTargetTicket->save() function is looking for document name in the content, but there is only an 'Attached document' instead ( foreach (PluginFormcreatorCommon::getDocumentsFromTag($data['content']) as $document) )

**Comment by btry** [comment]
Hi

Formcreator creates the ticket without documents then adds the relations with the documents. Doing so prevents to find the documents when creating the notifications. 

This is currently a limitation.

**Comment by btry** [comment]
In GLPI a document is uploaded the immediately linked to a ticket. In Formcreator  a delay may happen wuen a form answer must be validated. This validation step is problematic to pass an uploaded file like GLPI would do.

**Comment by kabassanov** [comment]
OK, but if I'm not wrong even if the form asks for validation, the ticket is created only when the form is accepted. So where is the problem? Did I miss anything?

**Comment by btry** [comment]
The problem comes from the way files are handled by GLPI when a ticket is ceated. Uploaded files are saved in temporary location un servers' filesystem, with metadata in $_FILE. GLPI uses it. When a form is under validation it is complex and risky (if not impossible) to emulate this intermediate state for uploads. 

Currently, the plugin does not distinguishes the 2 cases by linnking itself the documents to the ticket after its creation. Therefore GLPI is not aware of files to link.

**Comment by kabassanov** [comment]
Am I wrong when I say that ticket creation is the same for an ordinary ticket and a ticket created from a validated form? The way you keep files until validation changes nothing if you start ticket generation with the same paremeters as for usual tickets upon validation.

**Comment by btry** [comment]
> Am I wrong when I say that ticket creation is the same for an ordinary ticket and a ticket created from a validated form

this is the goal; but at least for files uploads this is false. Unfortunately this is very tricky to fix. A few things evolved in GLPI core to solve other file handling problems in Formcreator, then it is worth to investigate again on your topic. 

The 1st code location to analyze is CommonITILObject::post_addItem() and post_updateItem(). There are calls to CommonDBTM::addFiles()

> The way you keep files until validation changes nothing if you start ticket generation with the same paremeters as for usual tickets upon validation.

No : when file uploads are here, GLPI moves the uploaded files and create a Document item. When Formcereator does validation the files are already moved in documents.

**Comment by kabassanov** [comment]
You are right, about the case when there is a validation. Input is no more available once the form has been validated.

However I managed to make plugin work. Please, find attached my diff. I agree, it is not the prettiest way to do, but as workaround, I'm happy with this :).

[formcreator-ter.diff.txt](https://github.com/pluginsGLPI/formcreator/files/8146957/formcreator-ter.diff.txt)

**Comment by btry** [comment]
Hi

Could you create a PR instead, this is much more convenient to read your changes.

**Comment by btry** [comment]
Hi

What is the base branch or version of your PR ? I guess it should not merge un develop.

**Comment by kabassanov** [comment]
Hi, you are right...
I used glpi-formcreator-2.12.4...

**Comment by btry** [comment]
OK. For your information, it is possible to change the base branch of a pr without closing it.

**Comment by kabassanov** [comment]
OK, I changed the base branch to 2.12.5...

**Comment by btry** [comment]
Solved with https://github.com/pluginsGLPI/formcreator/pull/2648, based on your contribution. Thank you.
