### ISSUE TITLE
[RESOLU]Formcreator 2.12.3 - GLPI 9.5.5

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2618]
Bonjour

Nous essayons de saisir valeur max dans la longueur d'un champ
![image](https://user-images.githubusercontent.com/42341169/155343261-581e23c8-aeab-4f19-bad9-1db928cc5cfd.png)

les valeurs ne sont pas sauvegardées.
ou mauvaise utilisation ?

**Comment by btry** [comment]
Bonjour

Essayez d'abord avec la dernière version du plugin.

J'ai aussi besoin de connaître le type de la question.

**Comment by EC2311** [comment]
la question est de type "texte"

j'ai essayé sur un autre environnement (dev) en 2.12.3 -> cela passe...j'ai regardé les logs du serveur 
Ceci dit
en saisissant une nouvelle question (meme type etc) : cela passe.
je crois que l'enregistrement dans "formrange" n'a pas été créé initialement et de ce fait, ne permet pas sa sauvegarde ultérieure

**Comment by btry** [comment]
Il est arrivé dans le passé que des enregistrements soient absents pour les expressions régulières ou les limites de taille. Pourtant le fait de modifier la question impactée résolvait (et résout toujours) le souci.

Du coup, je pense que votre problème est différent, en l'état, je n'i aucun undice permettant de savori ce qu'il se passe.Il faudrait vérifier en base si les limites sont présentes pur la question et avec quelles  valeurs.

**Comment by btry** [comment]
Bonjour

Trouvez l'ID de la question, puis vérifiez si il y a une entrée pour cette questin dnas la table glpi_plugin_formcreator_questionranges. Si oui, essayez de saisir et sauvegarder des valeurs et voyez si elles sont  effectivement enregistrées en base de données.

**Comment by EC2311** [comment]
La ressaisie de la question a resolu le souci.

**Comment by btry** [comment]
Bonjour, merci pour votre retour. Je ferme.
