### ISSUE TITLE
Information button under username in ticket is broken

### ISSUE THREAD

**Issue by plburguet** [pluginsGLPI/formcreator#2620]
**Describe the bug**
A PHP error occur and is visible when debug is ON under the name of some user (not every users...) inside "Historique des actions"
This error is related to the little " i " button to get the full profile of the user
Also, it appears that sometimes, if an user with that error gets an answer, the error disappear but the little " i " point to the profile of the user who answered (not sure if it's understandable)
PS : this server was created with glpi-9.2.3 and got upgraded to 9.5.3 then now to 9.5.7

**To Reproduce**
1. Upgrade from 9.5.3 to 9.5.7
2. Enable debug
3. Click on any tickets
4. check the usernames of the people here
5. See error
PHP Warning (2): Undefined variable $userdata in /var/www/glpi/inc/commonitilobject.class.php at line 7550
PHP Warning (2): Trying to access array offset on value of type null in /var/www/glpi/inc/commonitilobject.class.php at line 7550
**Expected behavior**
No error should be displayed
Or-else, you get no error for the same user on another ticket, you click on the " i " and then you see the wrong user profile
The profile displayed looks like to be the one of the user who will answers to the ticket.

![Capture d’écran du 2022-02-24 16-08-17](https://user-images.githubusercontent.com/52488995/155550837-415901d2-e71b-4cdc-b6bf-8e5ddd6878a2.png)

**GLPI / Plugins (please complete the following information):**
- GLPI 9.5.7
- list of all plugins : dashboard  formcreator  fusioninventory  pdf  shellcommands

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, 18.04 and Windows 10
 - Browser Firefox
 - Version 97

**Comment by btry** [comment]
Hi

I'm suspecting that your GLPI has been modified.

When I check the code in inc/commonitilobject.class.php I find a variable ```$userdata``` but not ```$Userdata```. Notice the 1st uppercase letter.

**Comment by plburguet** [comment]
> Hi
> 
> I'm suspecting that your GLPI has been modified.
> 
> When I check the code in inc/commonitilobject.class.php L7550 I find a variable `$userdata` but not `$Userdata`. Notice the 1st uppercase letter.

Hi, sorry for late answer. So this uppercase is only visual and shown like this in debug mode, it is $userdata in the code.

**Comment by btry** [comment]
Hi

Indeed many words have a uppercase first letter. This is suspicious.

Please reproduce the error, then find its occurence in glpi/files/_logs/php-errors.log. Show the full entry, with its backtrace.

**Comment by plburguet** [comment]
Hello,
I reproduced the error, here are the logs in the file  ssl_error_log
[Mon Mar 21 17:32:36.297890 2022] [php:warn] [pid 154080] [client IPv4:53910] PHP Warning:  Undefined variable $userdata in /var/www/glpi/inc/commonitilobject.class.php on line 7550, referer: https://glpi.xxxx.fr/front/ticket.form.php?id=10117
[Mon Mar 21 17:32:36.297955 2022] [php:warn] [pid 154080] [client IPv4:53910] PHP Warning:  Trying to access array offset on value of type null in /var/www/glpi/inc/commonitilobject.class.php on line 7550, referer: https://glpi.xxxx.fr/front/ticket.form.php?id=10117

And the errors in glpi/files/_logs/php-errors.log : 
[2022-03-21 17:32:36] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $userdata in /var/www/glpi/inc/commonitilobject.class.php at line 7550
  Backtrace :
  inc/ticket.class.php:776                           CommonITILObject->showTimeline()
  inc/commonglpi.class.php:637                       Ticket::displayTabContentForItem()
  ajax/common.tabs.php:106                           CommonGLPI::displayStandardTab()
  
[2022-03-21 17:32:36] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in /var/www/glpi/inc/commonitilobject.class.php at line 7550
  Backtrace :
  inc/ticket.class.php:776                           CommonITILObject->showTimeline()
  inc/commonglpi.class.php:637                       Ticket::displayTabContentForItem()
  ajax/common.tabs.php:106                           CommonGLPI::displayStandardTab()

**Comment by plburguet** [comment]
Hi,
Just noticed i've posted that issues on the wrong page sorry.
here is a fix : https://github.com/glpi-project/glpi/pull/10461
