### ISSUE TITLE
Appliances IDs displayed in a form

### ISSUE THREAD

**Issue by paidge** [pluginsGLPI/formcreator#2633]
In my form, I have added a question of type "GLPI object" (Assets > Appliances) and the form displays an HTML `select ` with titles and IDs. I think the IDs should not be displayed.

**To Reproduce**
1. Create a form
2. In that form, create a question of type "GLPI object" (Assets > Appliances but it may concern other assets)
3. Go to the form to create a ticket (self-service role) and see the problem

**Expected behavior**
The IDs should not be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/2470104/157421618-8a55122b-f827-417e-b883-2efb48c67b9b.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.7
- list of all plugins : formCreator, genericobject

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox 97

**Comment by btry** [comment]
Hi

Which version of Formcreator ?

**Comment by paidge** [comment]
v2.12.5

**Comment by btry** [comment]
Hi

I did a check : the ID is explicitly displayed by the plugin (see commit dc402d931136cf156137d6c60e0d6efec74fe0c4). 

It is redundant with the following user preference, then I think it should be removed. A double check will be done before submitting a fix.

![image](https://user-images.githubusercontent.com/14139801/158844801-71fd1ef4-fbe3-44ff-9d0b-7e80c49a2335.png)

![image](https://user-images.githubusercontent.com/14139801/158844864-81c02e08-22bf-4885-ba1c-4ce8abcbbbfb.png)

**Comment by paidge** [comment]
Yes. The user preference should be taken in account. Thanks.

**Comment by btry** [comment]
Hi

Here is the fix: 53dc3aeb947ab7fed7c1127a975c8d247b1ddb63

**Comment by paidge** [comment]
Hi. Thanks. The ID is no more displayed.
Shouldn't this piece of code take this parameter in account ?

![image](https://user-images.githubusercontent.com/2470104/159226030-8876ff8f-3b7f-4ca8-b706-b50e8c5b9a21.png)

**Comment by btry** [comment]
Hi

Yes, it does. Enable the paraleter then refresh your form.
