### ISSUE TITLE
Installed FORMCREATOR 2.13.0 ALPHA 3, on GLPI 10 beta receiving exception error

### ISSUE THREAD

**Issue by zkfurskin** [pluginsGLPI/formcreator#2639]
error shown while adding question to formcreator form 
option dropdown: common/locations

PHP Notice (8): Undefined index: id in ~glpi_installation~/marketplace/formcreator/ajax/dropdown_values.php at line 48

**Comment by btry** [comment]
Hi

I don't have any context. I cannot investigate with this single line.

i assume you used the version tagged Alpha.3, not the latest revision. I also need a procedure to reproduce (ideally). Maybe the  backtrace will be enough. You can find this bbacktrace in glpi/files/_log/php-errors.log.

**Comment by zkfurskin** [comment]
[2022-03-11 08:54:20] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: id in /home/rcmwoksu/helpdesk.101designs.net/marketplace/formcreator/ajax/dropdown_values.php at line 48

**Comment by btry** [comment]
Hi

This line repeats the error message you already reported. After this line you should find a group of lines describing the methods call stack. 

An example

```
[2022-03-14 14:53:50] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class name must be a valid object or a string in /home/bugier/public_html/glpi-master/plugins/formcreator/inc/form.class.php at line 1911
  Backtrace :
  :                                                  PluginFormcreatorForm::getByItem()
  src/Application/View/Extension/PhpExtension.php:85 call_user_func_array()
  ...f954ca490cda29135f018208107b721728301a0a.php:81 Glpi\Application\View\Extension\PhpExtension->call()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_a627f52de25b8b40aa226860d932879b645f41a94dc7573675357ec71bb7b3e4->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  src/Application/View/TemplateRenderer.php:159      Twig\TemplateWrapper->render()
  plugins/formcreator/inc/condition.class.php:368    Glpi\Application\View\TemplateRenderer->render()
  plugins/formcreator/ajax/condition.php:62          PluginFormcreatorCondition->getConditionHtml()
```

**Comment by btry** [comment]
Hi

A new version is available for testing, I don't have enough information to process this issue and no news. Closing.
