### ISSUE TITLE
Validation with condition field

### ISSUE THREAD

**Issue by Alibaskins** [pluginsGLPI/formcreator#264]
Since the last update, it seems there is a problem with conditionnal fields.
For the validators and when the ticket is created, only the not conditionals fields are displayed.

I'm using a checkbox to add further questions.
But all this fields are hidden.

**Comment by Alibaskins** [comment]
![fom_test_1](https://cloud.githubusercontent.com/assets/22218247/18839507/8752836c-840b-11e6-
9340-184a0ed4e160.PNG)
![fom_test_2](https://cloud.githubusercontent.com/assets/22218247/18839506/874db4fe-840b-11e6-90ca-b16d13410eb5.PNG)

**Comment by Alibaskins** [comment]
![fom_test_1](https://cloud.githubusercontent.com/assets/22218247/18839522/95357912-840b-11e6-8814-ad8b3b2313d1.PNG)
![fom_test_2](https://cloud.githubusercontent.com/assets/22218247/18839523/9540ad8c-840b-11e6-8de0-85316e8e38c8.PNG)

**Comment by btry** [comment]
Hi 

The problem should be fixed now. Can you validate the fix ? 

Thank you

**Comment by Alibaskins** [comment]
Yes indeed it's now ok !

Thank you !

**Comment by btry** [comment]
Thank you for your feedback ;)

**Comment by btry** [comment]
I reopen because of your other issue #275 . I had to rewrite the fix and apply it to other comparison operators.

I would appreciate your feedback again

**Comment by btry** [comment]
Hi

Can you confirm the issue still does not occurs with the latest revision ?

Thank you

**Comment by Alibaskins** [comment]
Hi,

Yes it's ok for me.

Thank you to you !
