### ISSUE TITLE
Bug SQL FormCreator GLPI 9.5.7

### ISSUE THREAD

**Issue by JCO946901** [pluginsGLPI/formcreator#2640]
Bonjour,

j'ai un message d'erreur lors de l'installation du plugins FormCreator sur GLPI 9.5.7 ci-joint le message d'erreur 

Changement de la structure de la base de données - glpi_plugin_formcreator_forms_profiles (10 secondes)

2.12.5 multiple alter in glpi_plugin_formcreator_forms_profiles - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_forms_profiles` CHANGE `plugin_formcreator_profiles_id` `profiles_id` INT(11) NOT NULL DEFAULT '0' , ADD `id` INT(11) NOT NULL AUTO_INCREMENT , ADD PRIMARY KEY `id` (`id`) , ADD UNIQUE KEY `unicity` (`plugin_formcreator_forms_id`, `profiles_id`) , ADD `uuid` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL - L'erreur est Multiple primary key defined

Merci de m'indiquer qu'elles sont les démarches à effectuer.
Merci

**Comment by btry** [comment]
Bonjour

Est ce une installation ou un upgrade du plugin ?

**Comment by JCO946901** [comment]
Bonjour,

Il s'agit d'une upgrade de GLPI en 9.5.7
Et d'une installation de formcreator.

**Comment by btry** [comment]
Le plugin détecte une installation précédente pour déterminer si il soit faire une installation fraîche ou un upgrade. Il doit y avoir des traces d'une ancienne installation.

Vérifiez si il y a des tables dont le nom commence par glpi_plugin_formcreator_ et supprimez les. 

Vérifiez dans la table glpi,_configs si il y a des lignes concernant Formcreator avec la requête suivante

Select * de glpi_configs where context='formcrearor'. Si oui, supprimez les.

Enfin retentez l'installation du plugin.

**Comment by JCO946901** [comment]
Bonjour,

Tout a fonctionner je vous remercie.

Bonne fin de journée
