### ISSUE TITLE
No selectable entity

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2641]
Hello,
I updated to the latest version and I can't select my entities anymore. The field has only the root entity
![image](https://user-images.githubusercontent.com/17006344/158194780-254d59fc-0966-4601-901f-877c6e903a5d.png)

php error
![image](https://user-images.githubusercontent.com/17006344/158195098-d4e7a38e-2b53-4dd8-b40e-07698271fbe7.png)

**Comment by btry** [comment]
Hi
 Latest version is 2.12.5. is it the version you have ?

Which was the previous version ?

Can you show the row of the impacted question in the table glpi_plugin_formcreator_questions ?

**Comment by Riesuu** [comment]
Yes
![image](https://user-images.githubusercontent.com/17006344/158198922-26972ccb-65aa-4110-a8b1-32ba4c215ea5.png)
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/8245987/php-errors.log)

**Comment by btry** [comment]
Hi

I don't see any probley with the row in the database. I assume the problem occurs when you preview or use the form, am I right ? Please show it. I need to see in which entity is located the user, and if it has a recusrsive view.

If the user does not have recursion, then he will not see entities below his active entity.

**Comment by Riesuu** [comment]
Hi,
I am in super admin and the problem appears on the form and in preview.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/17006344/159005109-43a5bb6e-adff-475c-8de9-84d4b9fac6bb.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/17006344/159005139-05b00243-cade-4cdf-afea-d6774582ba15.png">

**Comment by Riesuu** [comment]
The form is on the root entity in recursion. The people using it have a technician profile in recursive via the master entity. Super-Admin has the rights on the master entity in recursive, the technicians too. I already deleted the block/recreated but same problem.

Master
Master>B
Master>C
Master>D

<img width="758" alt="image" src="https://user-images.githubusercontent.com/17006344/159008696-be51025a-26de-4644-a05b-bffa85e6f006.png">

**Comment by btry** [comment]
Hi

Select a user to reproduce the problem. If you are already logged in with this user, logout then login again (to clear the session serverside). 

- Enable GLPI's debug mode.
- show the form in preview mode to reproduce the issue
- Open the debug panel, tag Session, then search with Ctrl+F for **glpicondition**. You will find an occurence here
![image](https://user-images.githubusercontent.com/14139801/159221372-8059f669-bac4-41cc-a71b-1e50b95a3b21.png)
- develop this entry by clicking on the double arrow, and scroll unting finding an entry similar to the following
![image](https://user-images.githubusercontent.com/14139801/159221490-ff3aae95-86a8-4907-b727-ad12df8dead7.png)

Get a screenshot and show it. It represents the condition to filter the entities in the dropdown.

**Comment by Riesuu** [comment]
Hi,
![image](https://user-images.githubusercontent.com/17006344/159223171-47625733-6708-4331-9b9e-7664987089ac.png)
![image](https://user-images.githubusercontent.com/17006344/159223194-c2955252-f18a-43a2-a182-4c34108d7a0a.png)
![image](https://user-images.githubusercontent.com/17006344/159223205-0307ee5f-39e0-443a-a6d8-e237d8af8fc6.png)
![image](https://user-images.githubusercontent.com/17006344/159223223-85c5793a-5e37-4bfb-afdf-74c83ee44e14.png)

**Comment by btry** [comment]
Appliquez le patch suivant et voyez si ça résout le souci

```diff
diff --git a/inc/field/dropdownfield.class.php b/inc/field/dropdownfield.class.php
index 4ebf521d..407be8db 100644
--- a/inc/field/dropdownfield.class.php
+++ b/inc/field/dropdownfield.class.php
@@ -249,6 +249,7 @@ class DropdownField extends PluginFormcreatorAbstractField
          case Entity::class:
          case Document::class:
             unset($dparams['entity']);
+            break;
 
          case User::class:
             $dparams['right'] = 'all';
```

**Comment by Riesuu** [comment]
Je suis vraiment désolé mais je n'ai pas encore installé ce qu'il faut pour que je puisse effectuer les commandes demandés.En réalité je ne suis pas encore à l'aise avec github
Quel est la ligne à modifier?

**Comment by btry** [comment]
Vous n'êtes pas obligés d'utiliser git pour appliquer un patch. Vous pouvez utiliser l'outil patch dont la documentation est disponible ci dessous

https://man7.org/linux/man-pages/man1/patch.1.html

L'outil existe aussi pour windows.

pour appliquer le patch, copiez et collez le diff dans un fichier
rendez vous dans le dossier de Formcreator, et appliquez le patch avec la commande suivante
patch -p1 --dry-run < /path/to/diff-file.diff
si la commande ne retourne aucune erreur, répétez la sans l'argument --dry-run.

Pour annuler un patch, en cas de besoin 
patch -p1 --reverse < /pah/to/diff-file.diff

Si vous avez besoin de plus d'aider pour cela, il faudra vous tourner vers des ressources sur internet.

La ligne à modifier est à proximité de la ligne 249 (visible entre les @@ ), mais je déconseille de patcher à la main, car c'est vite fait de se tromper.

**Comment by Riesuu** [comment]
Merci pour le tuto, ça fonctionne.

**Comment by btry** [comment]
Le patch résout le souci ?

**Comment by Riesuu** [comment]
Oui tout à fait

**Comment by btry** [comment]
Merci; le patch est prêt pour la prochaine version

**Comment by btry** [comment]
Possible duplicate of #2492
