### ISSUE TITLE
[GLPI 10.0.0-rc2] [formcreator_2.13.0-alpha.3-dev] - Error on the question "object GLPI --> Entity"

### ISSUE THREAD

**Issue by stdglpi** [pluginsGLPI/formcreator#2649]
Hello,

When I try to add a question on the form
for example : type => GLPI object then "Entity" 

I have this error : 
![image](https://user-images.githubusercontent.com/63521311/159520331-744c2b18-0ae7-4559-965a-9a36c6437a9f.png)

On Php Errors file : 

[2022-03-22 16:31:07] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in C:\inetpub\wwwroot\glpi\plugins\formcreator\ajax\dropdown_values.php at line 48

**Comment by btry** [comment]
Hi

The Aplha.3 release is becoming old. Try this  version, it contains all changes / fixes until now, and tell if  the bug persists.

[formcreator_2.13.0-alpha.3-dev.zip](https://github.com/pluginsGLPI/formcreator/files/8325843/formcreator_2.13.0-alpha.3-dev.zip)
