### ISSUE TITLE
Ticket generation error - GLPI 10

### ISSUE THREAD

**Issue by JeanBuchweitz** [pluginsGLPI/formcreator#2652]
When the ticket is generated with
##FULL FORM## result is broken, not interpreting HTML

exemplo
7 / 5.000
Resultados de tradução
example : 

 Person
<h1>Form Data</h1><h2>Seção</h2><div><b>1) teste : </b>

tetegetet  et
</div> 

![image](https://user-images.githubusercontent.com/97294583/159748612-15897efe-85e5-4aed-98f3-df419554a62f.png)

![image](https://user-images.githubusercontent.com/97294583/159748795-d4070cb4-1dc0-4d59-85e3-53dbe7a4800f.png)

**Comment by btry** [comment]
Hi

This issue should be solved : try the following build and feedback. This version is very close to the Alpha.4 to be released very soon.

[glpi-formcreator-2.13.0-pre-alpha.4.zip](https://github.com/pluginsGLPI/formcreator/files/8334814/glpi-formcreator-2.13.0-pre-alpha.4.zip)

**Comment by JeanBuchweitz** [comment]
> Hi
> 
> This issue should be solved : try the following build and feedback. This version is very close to the Alpha.4 to be released very soon.
> 
> [glpi-formcreator-2.13.0-pre-alpha.4.zip](https://github.com/pluginsGLPI/formcreator/files/8334814/glpi-formcreator-2.13.0-pre-alpha.4.zip)

Thank you.

When I generated the ticket through Preview it worked perfectly.

But for some reason, it is not activating on the entity;.

I change from Helpdesk to Service Catalog, but it returns to default
![image](https://user-images.githubusercontent.com/97294583/159786127-487d8919-032e-4ff7-89c7-b7bf4f97a2ab.png)

,

**Comment by btry** [comment]
Hi

> But for some reason, it is not activating on the entity;.

I found the problem. The upgrade to version 2.13 does not support several executions, and it may damage the settings for the root entity. Here is the fix: 477b5f1e30471cf13da950fe9147bf7cee39f605

And an additional fix to repair this inconsistency: 490af18cf6a070c44cc77ac3411d57ba65b4eee6

Running again a forced upgrade will solve the issue.

**Comment by CartCaved** [comment]
I tried installing and force upgrading the plugin. I was previously on a dev version from issue 2582.
Result when processing the upgrade was a red:
SQL Error "1054": Unknown column 'entities_id' in 'where clause' in query "SELECT `id` FROM `glpi_plugin_formcreator_entityconfigs` WHERE `entities_id` = '0'"
but the plugin was installed and I activated it.
Unfortunately, the same issue with the entity settings remained.
I reran the same upgrade and got an issue that entities_id could not be set to 2 because it would not be unique.

The HTML also still remains in the ticket. To clarify, it's not just the form answer, it includes part of the formatting from the tiny html editor, in my case a lot of \\r\\n and <p></p>

**Comment by btry** [comment]
> The HTML also still remains in the ticket

The fix has no effect on previously created tickets. you need to generate a new ticket to validate it.

**Comment by btry** [comment]
For the following topic, please create a separate issue. For now I don't see which PHP code generated this query. I need a backtrace. 

> I tried installing and force upgrading the plugin. I was previously on a dev version from issue 2582.
Result when processing the upgrade was a red:
SQL Error "1054": Unknown column 'entities_id' in 'where clause' in query "SELECT id FROM glpi_plugin_formcreator_entityconfigs WHERE entities_id = '0'"
but the plugin was installed and I activated it.
Unfortunately, the same issue with the entity settings remained.
I reran the same upgrade and got an issue that entities_id could not be set to 2 because it would not be unique.

**Comment by CartCaved** [comment]
> > The HTML also still remains in the ticket
> 
> The fix has no effect on previously created tickets. you need to generate a new ticket to validate it.

Sorry for not being more clear, it was a newly submitted form resulting in the same artefacts in the new ticket.

**Comment by CartCaved** [comment]
> For the following topic, please create a separate issue. For now I don't see which PHP code generated this query. I need a backtrace.
> 
> > I tried installing and force upgrading the plugin. I was previously on a dev version from issue 2582.
> > Result when processing the upgrade was a red:
> > SQL Error "1054": Unknown column 'entities_id' in 'where clause' in query "SELECT id FROM glpi_plugin_formcreator_entityconfigs WHERE entities_id = '0'"
> > but the plugin was installed and I activated it.
> > Unfortunately, the same issue with the entity settings remained.
> > I reran the same upgrade and got an issue that entities_id could not be set to 2 because it would not be unique.

As I mentioned, I "upgraded" from another dev version posted in another ticket. If that has caused separate issue, I wouldn't be able to give assurances that it wasn't due to the crooked upgrade path. Would deleting the plugin from the UI clean the tables, allowing a clean install and upgrade? 

> For the following topic, please create a separate issue. For now I don't see which PHP code generated this query. I need a backtrace.
> 
> > I tried installing and force upgrading the plugin. I was previously on a dev version from issue 2582.
> > Result when processing the upgrade was a red:
> > SQL Error "1054": Unknown column 'entities_id' in 'where clause' in query "SELECT id FROM glpi_plugin_formcreator_entityconfigs WHERE entities_id = '0'"
> > but the plugin was installed and I activated it.
> > Unfortunately, the same issue with the entity settings remained.
> > I reran the same upgrade and got an issue that entities_id could not be set to 2 because it would not be unique.

Split into issue #2655

**Comment by btry** [comment]
> Would deleting the plugin from the UI clean the tables, allowing a clean install and upgrade?

Yes, : when you uninstall the plugin GLPI triggers an uninstallation process, and the plugin will delete all its tables.

**Comment by JeanBuchweitz** [comment]
> When the ticket is generated with ##FULL FORM## result is broken, not interpreting HTML
> 
> exemplo 7 / 5.000 Resultados de tradução example :
> 
> Person
> # Form Data
> ## Seção
> 1) teste :
> 
> tetegetet et
> 
> ![image](https://user-images.githubusercontent.com/97294583/159748612-15897efe-85e5-4aed-98f3-df419554a62f.png)
> 
> ![image](https://user-images.githubusercontent.com/97294583/159748795-d4070cb4-1dc0-4d59-85e3-53dbe7a4800f.png)

**Comment by JeanBuchweitz** [comment]
> Hi
> 
> > But for some reason, it is not activating on the entity;.
> 
> I found the problem. The upgrade to version 2.13 does not support several executions, and it may damage the settings for the root entity. Here is the fix: [477b5f1](https://github.com/pluginsGLPI/formcreator/commit/477b5f1e30471cf13da950fe9147bf7cee39f605)
> 
> And an additional fix to repair this inconsistency: [490af18](https://github.com/pluginsGLPI/formcreator/commit/490af18cf6a070c44cc77ac3411d57ba65b4eee6)
> 
> Running again a forced upgrade will solve the issue.


I followed the processes mentioned.

However, the forms do not appear in the assistance menu and do not appear in the self-service profile.

![image](https://user-images.githubusercontent.com/97294583/160007131-a66586bb-1fdb-4d49-adeb-62550166e2af.png)

![image](https://user-images.githubusercontent.com/97294583/160007233-c76bb797-1be0-48ed-b486-8a704c9648ad.png)
![image](https://user-images.githubusercontent.com/97294583/160007306-35379dd0-b367-4e1d-8108-f99712c6a8b5.png)

**Comment by JeanBuchweitz** [comment]
> > Hi
> > > But for some reason, it is not activating on the entity;.
> > 
> > 
> > I found the problem. The upgrade to version 2.13 does not support several executions, and it may damage the settings for the root entity. Here is the fix: [477b5f1](https://github.com/pluginsGLPI/formcreator/commit/477b5f1e30471cf13da950fe9147bf7cee39f605)
> > And an additional fix to repair this inconsistency: [490af18](https://github.com/pluginsGLPI/formcreator/commit/490af18cf6a070c44cc77ac3411d57ba65b4eee6)
> > Running again a forced upgrade will solve the issue.
> 
> I followed the processes mentioned.
> 
> However, the forms do not appear in the assistance menu and do not appear in the self-service profile.
> 
> ![image](https://user-images.githubusercontent.com/97294583/160007131-a66586bb-1fdb-4d49-adeb-62550166e2af.png)
> 
> ![image](https://user-images.githubusercontent.com/97294583/160007233-c76bb797-1be0-48ed-b486-8a704c9648ad.png) ![image](https://user-images.githubusercontent.com/97294583/160007306-35379dd0-b367-4e1d-8108-f99712c6a8b5.png)


I followed the processes mentioned.

However, the forms do not appear in the assistance menu and do not appear in the self-service profile.

![image](https://user-images.githubusercontent.com/97294583/160007131-a66586bb-1fdb-4d49-adeb-62550166e2af.png)

![image](https://user-images.githubusercontent.com/97294583/160007233-c76bb797-1be0-48ed-b486-8a704c9648ad.png)
![image](https://user-images.githubusercontent.com/97294583/160007306-35379dd0-b367-4e1d-8108-f99712c6a8b5.png)

**Comment by btry** [comment]
Hi

The "Forms" entry in the Assistance menu is available only if there is at least one form available for the user. Check your forms and see the access restrictions.

Also, ig you just enabled the plugin and doon't have debug mode enabled, the menu will not update. Try to logout and login again.

In the self service, click on the "home" pictogram, to refresh the forms list.

**Comment by btry** [comment]
Hi
Having no feedback, I close.
