### ISSUE TITLE
Error installing FORMCREATOR 2.12.5 on GLPI 9.5.7.

### ISSUE THREAD

**Issue by carlosbayerl** [pluginsGLPI/formcreator#2653]
When updating the version through filezilla, the browser behaves as if it were loading.... in GLPI the "TOP" command shows as if it were updating something in the tables. But the process never ends. I've already left two days in the approval environment testing and I was not successful. Can you help me?

**Comment by btry** [comment]
Hi

How many rows do you have in the table glpi_tickets?

**Comment by carlosbayerl** [comment]
Hi @btry 
Lost of...... 
The fact is that it is using version 2.12.3 and I tried to update to version 2.12.5 directly. However, I couldn't. So I upgraded to version 2.12.4 and it was on time. So I think there is a bug in version 2.12.5....

**Comment by btry** [comment]
Do you have a ssh accès to the server, to try to upgrade from CLI interface ?

**Comment by carlosbayerl** [comment]
Hi @btry 
I don't understand the difference. What's more, I've already disabled the plugin and updated it. And yet, the problem persists.

**Comment by btry** [comment]
Hi

As you updated Formcreator via Filezilla, I assume your GLPI is hosted on a 3rd party server, and you probably don't have access to a terminal. 

Using a terminal let you upgrade the plugin via CLI and use a 2nd terminal session to monitor CPU usage, process by process. I want to see if Mysql does a high CPU usage.

I also think I'll give you a patch which disables the part of the upgrade which would cause your problem.  This is an other way to find which part is responsible of the problem.

**Comment by btry** [comment]
Hi

I observed on an instance that the sync task which re populate the assistance requests causes big delays when GLPI has many tickets and form answers ( > 100 K). 

I'm searching for a solution

**Comment by btry** [comment]
Hi

I think I found a solution. Please try again to upgrade on a testing instance of GLPI with a copy of your production database (full of data).

- install the files of Formcreator 2.12.5
- apply the patch #2673 
- proceed with the upgrade if the plugin. It is better do to it from CLI to prevent hitting the 30 seconds limit.

On my side I observed that the query to build the data last less than 14 seconds.

**Comment by carlosbayerl** [comment]
Hi @btry 
It worked....and it worked very fast. Thank you so much for your effort and help.
Regards,
@carlosbayerl

**Comment by btry** [comment]
Hi

Thank you for your feedback.
