### ISSUE TITLE
Upgrade issue in relation to entities_id

### ISSUE THREAD

**Issue by CartCaved** [pluginsGLPI/formcreator#2655]
**Describe the bug**
Issue split from #2652 
> For the following topic, please create a separate issue. For now I don't see which PHP code generated this query. I need a backtrace.
> 
> > I tried installing and force upgrading the plugin. I was previously on a dev version from issue 2582.
> > Result when processing the upgrade was a red:
> > SQL Error "1054": Unknown column 'entities_id' in 'where clause' in query "SELECT id FROM glpi_plugin_formcreator_entityconfigs WHERE entities_id = '0'"
> > but the plugin was installed and I activated it.
> > Unfortunately, the same issue with the entity settings remained.
> > I reran the same upgrade and got an issue that entities_id could not be set to 2 because it would not be unique.

As I mentioned, I "upgraded" from another dev version posted in another ticket. If that has caused separate issue, I wouldn't be able to give assurances that it wasn't due to the crooked upgrade path. Would deleting the plugin from the UI clean the tables, allowing a clean install and upgrade? To see if the issue is reproducible.

**Comment by btry** [comment]
Hi

When you uninstall Formcreator it deletes all its tables.

I think you swched between 2 version using a different schema for glpi_plugin_formcreator_entityconfigs, without running a forced upgrade.

When you upgrade to a from a dev version to an other, you should run the following (assuming you're in glpi folder)

bin/console glpi:plugin:install -f -p force-upgrade formcreator

This should create the missing column by running again the upgrade from the last release (2.12.0) to the current version.

**Comment by btry** [comment]
An other reporter here

https://forum.glpi-project.org/viewtopic.php?id=283397

The forum user reported that the forced upgrade solves the issue. Closing.
