### ISSUE TITLE
GLPI 10 issue adding ticket "assigned to"

### ISSUE THREAD

**Issue by blackxthink** [pluginsGLPI/formcreator#2657]
Hello,

I have this error when trying to add "Assigned to" user.
It POST at 
`/marketplace/formcreator/ajax/target_actor.php`

but the URL I have for the plugin itself is:
`/marketplace/formcreator/front/targetticket.form.php?id=1`

![Untitled-4](https://user-images.githubusercontent.com/48074916/159989262-ce5b4619-b523-4fcd-a357-5d699fd715d8.png)

Thank you.

**Comment by blackxthink** [comment]
`var formcreatorRootDoc = rootDoc + '/' + GLPI_PLUGINS_PATH.formcreator;`
the root in the main URL as the "front".

but when it comes to :
`GLPI_PLUGINS_PATH.formcreator`
I get : 
`"marketplace/formcreator"`

In the javascript file, i get this but I don't know why the Front is ignored

`var formcreatorRootDoc = rootDoc + '/' + GLPI_PLUGINS_PATH.formcreator;`

**Comment by btry** [comment]
Hi

The file ajax/target_actor.php is in the repository, and a test with the latest revision of the branch support/2.13.0 shows expected behavior. Maybe the file has been deleted in your instance ?

**Comment by blackxthink** [comment]
> Hi
> 
> The file ajax/target_actor.php is in the repository, and a test with the latest revision of the branch support/2.13.0 shows expected behavior. Maybe the file has been deleted in your instance ?

After having access to the files, the php file was gone (or never been there, I'm not sure).
I remade the file with the github code and everything works fine now !

Thanks !
