### ISSUE TITLE
LDAP select not work

### ISSUE THREAD

**Issue by DoctorDeatch** [pluginsGLPI/formcreator#2663]
Every time I try to create a request form with LDAP, I get an error: Cannot recover LDAP informations! 
At the same time, synchronization with LDAP in the GLPI system works normally
https://www.radio-portal.su/temp/Screenshot2022-03-30105835.png
 [GLPI 10.0.0-rc2]
[FC 2.13.0-alpha.4]

**Comment by DoctorDeatch** [comment]
Spent in version 9.5.7 and the Creator of the form 2.12.5
everything works
the problem is in version 2.13.0-alpha.3 also as 2.13.0-alpha.4

**Comment by btry** [comment]
Hi

Please tell your version of PHP

**Comment by DoctorDeatch** [comment]
PHP Version 7.4.6

**Comment by btry** [comment]
Hi

Formccrator Alpha.4 contains a complete redesign of the forms to edit the questions (in the administration part). I think you should stick on this version and stop using 2.13.0-alpha.3.

this error (https://github.com/pluginsGLPI/formcreator/issues/2663#issuecomment-1099258423) should be obsolete.

**Comment by DoctorDeatch** [comment]
I wrote the post when there was an alpha 3 version, at the moment I have already installed the alpha4 version, but the problem continues to be. Nothing has changed.

**Comment by btry** [comment]
Hi

> at the moment I have already installed the alpha4 version

Good, we can investigate on a better basis.

The error you reported here should not occur again with the Alpha.4 : https://github.com/pluginsGLPI/formcreator/issues/2663#issuecomment-1099258423

Do you confirm ?

**Comment by btry** [comment]
Please apply the following patch : it will log a possible error which is not logged

```diff
diff --git a/inc/field/ldapselectfield.class.php b/inc/field/ldapselectfield.class.php
index 38d141bd..eedfe084 100644
--- a/inc/field/ldapselectfield.class.php
+++ b/inc/field/ldapselectfield.class.php
@@ -38,7 +38,7 @@ use Html;
 use Session;
 use RuleRightParameter;
 use Glpi\Application\View\TemplateRenderer;
+use Toolbox;

 class LdapselectField extends SelectField
 {
    public function showForm(array $options): void {
@@ -131,6 +131,7 @@ class LdapselectField extends SelectField
          asort($tab_values);
          return $tab_values;
       } catch (Exception $e) {
+         Toolbox::logError($e->getMessage());
          return [];
       }
 
```

**Comment by btry** [comment]
I have some more modifications on the LDAP field to have better error management, loging and a fix for translations

try to apply this PR on your copy. Your error will very likely occur again, but with a message on the webpage if debug mode is enabled, and in php-errors.log.

https://github.com/pluginsGLPI/formcreator/pull/2705

(tests in progress right now)

**Comment by DoctorDeatch** [comment]
The code was added, but there was no more information

[Thu Apr 14 17:25:52.536964 2022] [php7:error] [pid 24622] [client 185.8.181.37:35994] PHP Fatal error:  Declaration of GlpiPlugin\\Form
creator\\Field\\LdapselectField::getDesignSpecializationField(): array must be compatible with GlpiPlugin\\Formcreator\\Field\\SelectFie
ld::getDesignSpecializationField(): string in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php on
line 47, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marketplace/formcreator/front/form.form.php?id=1
[Thu Apr 14 17:25:55.847035 2022] [php7:error] [pid 14290] [client 185.8.181.37:36038] PHP Fatal error:  Declaration of GlpiPlugin\\Form
creator\\Field\\LdapselectField::getDesignSpecializationField(): array must be compatible with GlpiPlugin\\Formcreator\\Field\\SelectFie
ld::getDesignSpecializationField(): string in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php on
line 47, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marketplace/formcreator/front/form.form.php?id=1
[Thu Apr 14 17:26:01.994997 2022] [php7:error] [pid 29931] [client 185.8.181.37:36134] PHP Fatal error:  Declaration of GlpiPlugin\\Form
creator\\Field\\LdapselectField::getDesignSpecializationField(): array must be compatible with GlpiPlugin\\Formcreator\\Field\\SelectFie
ld::getDesignSpecializationField(): string in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php on
line 47, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marketplace/formcreator/front/form.form.php?id=1
[Thu Apr 14 17:44:39.508508 2022] [php7:notice] [pid 24619] [client 185.8.181.37:50110] PHP Notice:  Undefined index: formcreator_restri
ct_form in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/ma
rketplace/formcreator/front/formlist.php
[Thu Apr 14 17:44:39.508701 2022] [php7:warn] [pid 24619] [client 185.8.181.37:50110] PHP Warning:  Invalid argument supplied for foreac
h() in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/market
place/formcreator/front/formlist.php
[Thu Apr 14 17:44:40.066115 2022] [php7:notice] [pid 30615] [client 185.8.181.37:50116] PHP Notice:  Undefined index: formcreator_restri
ct_form in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/ma
rketplace/formcreator/front/formdisplay.php?id=1
[Thu Apr 14 17:44:40.066275 2022] [php7:warn] [pid 30615] [client 185.8.181.37:50116] PHP Warning:  Invalid argument supplied for foreac
h() in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/market
place/formcreator/front/formdisplay.php?id=1
[Fri Apr 15 21:32:52.614749 2022] [php7:notice] [pid 23114] [client 127.0.0.1:33358] PHP Notice:  Undefined index: formcreator_restrict_
form in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marke
tplace/formcreator/front/formlist.php
[Fri Apr 15 21:32:52.624311 2022] [php7:warn] [pid 23114] [client 127.0.0.1:33358] PHP Warning:  Invalid argument supplied for foreach()
 in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marketpla
ce/formcreator/front/formlist.php
[Fri Apr 15 21:32:52.900793 2022] [php7:notice] [pid 19856] [client 127.0.0.1:33370] PHP Notice:  Undefined index: formcreator_restrict_
form in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marke
tplace/formcreator/front/formdisplay.php?id=1
[Fri Apr 15 21:32:52.900952 2022] [php7:warn] [pid 19856] [client 127.0.0.1:33370] PHP Warning:  Invalid argument supplied for foreach()
 in /home/glpi/public_html/v10/marketplace/formcreator/inc/form.class.php on line 2499, referer: http://glpi10.[test.local](http://glpi10.test.local/marketplace/formcreator/front/form.form.php?id=1)/marketpla
ce/formcreator/front/formdisplay.php?id=1

**Comment by btry** [comment]
The following error should not occur. I don't have it and the signature of the methods is ok. Maybe you have 2 copies of formcreator : one in the plugins directory and an other in the marketplace directory. If I'm right delete the copy in the plugins directory. 


PHP Fatal error: Declaration of GlpiPlugin\Form
creator\Field\LdapselectField::getDesignSpecializationField(): array must be compatible with GlpiPlugin\Formcreator\Field\SelectFie
ld::getDesignSpecializationField(): string in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php on

**Comment by DoctorDeatch** [comment]
[2022-04-14 17:25:52] glpiphplog.ALERT:   *** PHP Compile Error (64): Declaration of GlpiPlugin\Formcreator\Field\LdapselectField::getDe
signSpecializationField(): array must be compatible with GlpiPlugin\Formcreator\Field\SelectField::getDesignSpecializationField(): strin
g in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 47
[2022-04-14 17:25:55] glpiphplog.ALERT:   *** PHP Compile Error (64): Declaration of GlpiPlugin\Formcreator\Field\LdapselectField::getDe
signSpecializationField(): array must be compatible with GlpiPlugin\Formcreator\Field\SelectField::getDesignSpecializationField(): strin
g in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 47
[2022-04-14 17:26:01] glpiphplog.ALERT:   *** PHP Compile Error (64): Declaration of GlpiPlugin\Formcreator\Field\LdapselectField::getDe
signSpecializationField(): array must be compatible with GlpiPlugin\Formcreator\Field\SelectField::getDesignSpecializationField(): strin
g in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 47
[2022-04-14 17:44:39] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /home/glpi/public_html/v10/m
arketplace/formcreator/inc/form.class.php at line 2499
  Backtrace :
  marketplace/formcreator/front/formdisplay.php:55   PluginFormcreatorForm->canViewForRequest()

[2022-04-14 17:44:40] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /home/glpi/public_html/v10/m
arketplace/formcreator/inc/form.class.php at line 2499
  Backtrace :
  marketplace/formcreator/ajax/showfields.php:53     PluginFormcreatorForm->canViewForRequest()

[2022-04-15 21:32:52] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /home/glpi/public_html/v10/m
arketplace/formcreator/inc/form.class.php at line 2499
  Backtrace :
  marketplace/formcreator/front/formdisplay.php:55   PluginFormcreatorForm->canViewForRequest()

[2022-04-15 21:32:52] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\LdapselectField::getAvailableValues() in /home/glpi/public_html/v10
/marketplace/formcreator/inc/field/ldapselectfield.class.php line 134
ldap_search(): Search: Bad search filter  {"user":"7@server"}
[2022-04-15 21:32:52] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /home/glpi/public_html/v10/m
arketplace/formcreator/inc/form.class.php at line 2499
  Backtrace :
  marketplace/formcreator/ajax/showfields.php:53     PluginFormcreatorForm->canViewForRequest()

**Comment by DoctorDeatch** [comment]
> The following error should not occur. I don't have it and the signature of the methods is ok. Maybe you have 2 copies of formcreator : one in the plugins directory and an other in the marketplace directory. If I'm right delete the copy in the plugins directory.
> 
> PHP Fatal error: Declaration of GlpiPlugin\Form creator\Field\LdapselectField::getDesignSpecializationField(): array must be compatible with GlpiPlugin\Formcreator\Field\SelectFie ld::getDesignSpecializationField(): string in /home/glpi/public_html/v10/marketplace/formcreator/inc/field/ldapselectfield.class.php on

a copy is present only in the marketplace

**Comment by btry** [comment]
There is something wrong in your copy. In the version Alpha.4 this method does not exists anymore. As I said earlier, the questions edition part has been rewritten to switch to Twig template library. 

Next week I'll send to you a build of the plugin from the branch I asked you to test.

**Comment by DoctorDeatch** [comment]
> There is something wrong in your copy. In the version Alpha.4 this method does not exists anymore. As I said earlier, the questions edition part has been rewritten to switch to Twig template library.
> 
> Next week I'll send to you a build of the plugin from the branch I asked you to test.

I will be waiting very much

**Comment by btry** [comment]
Hi

Try the following build and see if the error with getAvailableValues() still occurs. 

[glpi-formcreator-2.13.0-alpha.4.zip](https://github.com/pluginsGLPI/formcreator/files/8510455/glpi-formcreator-2.13.0-alpha.4.zip)

**Comment by DoctorDeatch** [comment]
LDAP works with this build !
Thanks!

**Comment by btry** [comment]
Hi

This is better than I expected. I'll merge the fix. Thank you for your feedback.
