### ISSUE TITLE
Entité du ticket de destination

### ISSUE THREAD

**Issue by AleksNovak** [pluginsGLPI/formcreator#267]
Bonjour,
Problème: Je n’arrive pas à transférer l’entité de l’utilisateur qui répond au formulaire, au ticket généré.
Impact: L’utilisateur ne peut pas suivre son ticket généré.

Mes tests:
Mes entités:
- Entité Racine
- Entité Racine / Entité A
- Entité Racine / Entité A / Entité A.A
- Entité Racine / Entité B

Utilisateurs:
Utilisateur A => Entité A
Utilisateur B => Entité B
Utilisateur A.A => Entitée A.A

Formulaire : « Entité Racine »

J’ai crée un nouveau formulaire. En destination -> créer un nouveau ticket, je tombe alors sur le menu déroulant: « Entité de destination ».

- Entité Active:
  Je déduis que c’est l’entité actuellement utilisé par l’utilisateur qui répond au formulaire. 
  J’ai fais plusieurs test, pour chaque utilisateurs l’entité du ticket généré est « Entité Racine ».

- Entité par défaut du demandeur:
  L’entité par défaut du demandeur ne me convient pas, un utilisateur « Admin » peut avoir plusieurs entités avec différents droit.
  De plus mes utilisateurs sont gérés via une connexion AD. L’entité par défaut de leur profil est « Entité Racine ». Je n’ai pas trouvé de règle pour changer automatiquement ce paramètre.

- Première entité dynamique du demandeur (Alphabétiquement)
  Fonctionne, j’utilise ce paramètre comme WorkAround. Les entités étant géré dynamiquement via l’AD ce n’est pas une solution pérenne.

Sinon, très bon plugin, bon courage aux devs :)

**Comment by btry** [comment]
Bonjour

Il y a effectivement un souci avec le choix *Entité active*. Pouvez-vous vérifier si la dernière révision corrige le problème ? Veillez à rester sur un environnement de test car les nouveaux développements sont en cours de validation. Vous pouvez en profiter pour les essayer; lisez #277 pour avoir un aperçu.

**Attention** : la page listant les formulaires pur le demandeur a été fortement modifiée. Vous aurez besoin de rafraîchir le cache de votre navigateur pour obtenir l'affichage correct.

**Comment by AleksNovak** [comment]
Bonjour,
Merci beaucoup pour le debug, je test tout ca demain.

**Comment by AleksNovak** [comment]
Bonjour,
J’ai simplement testé le patch de l’entité active et je confirme que le problème est résolu.

Merci :)
