### ISSUE TITLE
[ GLPI 10 rc2 ] [Formcreator 2.13.0-alpha.4] - Can't see forms and no "form" menu in Assistance

### ISSUE THREAD

**Issue by stdglpi** [pluginsGLPI/formcreator#2674]
Hello @btry 

I passed the last update with the command update before activate the plugin.
![image](https://user-images.githubusercontent.com/63521311/161297939-ae749a07-84db-4aca-b79c-76a95fa087a4.png)

After reactivate it no errors in GLPI
I tried to check my forms but I can't see them 
![image](https://user-images.githubusercontent.com/63521311/161298030-f4592689-4fc0-49f0-b5ca-cf2273001580.png)

Also no menu form in the assistance menu
![image](https://user-images.githubusercontent.com/63521311/161298103-633ddfc7-680d-4cd8-9b0e-0672eb9e4e71.png)

Logs : 

file : migration_to_2.13.0-alpha.4

2022-04-01 17:41:53 [@XXXXX]
0 seconde for "Traitement en cours..." @ 2022-04-01 17:41:53 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_entityconfigs" @ 2022-04-01 17:41:53 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_questions" @ 2022-04-01 17:41:54 [@XXXXX]
1 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_targettickets" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_formanswers" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_forms_profiles" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_forms_validators" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_sections" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_targetchanges" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_targets_actors" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_questionregexes" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_questionranges" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_entityconfigs" @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Traitement terminé." @ 2022-04-01 17:41:54 [@XXXXX]
0 seconde for "Traitement terminé." @

**Comment by btry** [comment]
Hi

Select a form in the root entity, and show its main tab.

**Comment by stdglpi** [comment]
> Hi
> 
> Select a form in the root entity, and show its main tab.

https://github.com/pluginsGLPI/formcreator/issues/2674#issuecomment-1086162185

**Comment by btry** [comment]
Hi

It looks like you don't have any form in your database, then everything looks normal so far. You may want to check if you have soem forms in the databae 

```sql
select count (*) from glpi_plugin_formcreator_forms;
```

**Comment by stdglpi** [comment]
Indeed, my instance went back to zero forms.
I tried to import with a .json file but it tells me that it is done with an old version.

Is it not possible to work around this?

![image](https://user-images.githubusercontent.com/63521311/161632292-90f9d145-250b-4b72-8abb-3027ceeaf671.png)
![image](https://user-images.githubusercontent.com/63521311/161632306-ba7190e9-c477-40d8-ab97-9a56d00da339.png)

**Comment by stdglpi** [comment]
for the moment I try to create a new one, I'm facing this issue 

PHP Deprecated:  Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51

  
[2022-04-04 23:20:41] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "groups_id_tech" in C:\inetpub\wwwroot\glpi\src\NotificationTarget.php at line 1087
  Backtrace :
  src\NotificationTarget.php:1199                    NotificationTarget->addItemGroupTechInCharge()
  src\NotificationEventAbstract.php:93               NotificationTarget->addForTarget()
  src\NotificationEvent.php:185                      NotificationEventAbstract::raise()
  src\Certificate.php:761                            NotificationEvent::raiseEvent()
  src\CronTask.php:1016                              Certificate::cronCertificate()
  front\cron.php:62                                  CronTask::launch()
  
[2022-04-04 23:20:41] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "users_id_tech" in C:\inetpub\wwwroot\glpi\src\NotificationTarget.php at line 1048
  Backtrace :
  src\NotificationTarget.php:1074                    NotificationTarget->addUserByField()
  src\NotificationTarget.php:1194                    NotificationTarget->addItemTechnicianInCharge()
  src\NotificationEventAbstract.php:93               NotificationTarget->addForTarget()
  src\NotificationEvent.php:185                      NotificationEventAbstract::raise()
  src\Certificate.php:761                            NotificationEvent::raiseEvent()
  src\CronTask.php:1016                              Certificate::cronCertificate()
  front\cron.php:62                                  CronTask::launch()
  
[2022-04-04 23:23:28] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php at line 51
  Backtrace :
  src\Html.php:1527                                  PluginFormcreatorFormList::getMenuContent()
  src\Html.php:1738                                  Html::generateMenuSession()
  plugins\formcreator\front\form.form.php:182        Html::header()

**Comment by btry** [comment]
Hi

> PHP Deprecated: Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51

I'm aware of this bug, and a fix is pending.

Apply this fix (pending for review) and feedback: https://github.com/pluginsGLPI/formcreator/pull/2651

 Carefully check if the menu entries of the plugin work as expected. On my side, I did not find any refression.

**Comment by stdglpi** [comment]
Hello @btry 

I followed theses 2 commits
![image](https://user-images.githubusercontent.com/63521311/161731194-94f464f6-29e4-43d2-a8f5-1b28c2358d72.png)

This message is now not present
`PHP Deprecated: Automatic conversion of false to array is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\formlist.class.php on line 51`

I can see my new form in the assistance menu 
If I clik on it I have this error 

`PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\field\filefield.class.php on line 103`

**Comment by btry** [comment]
Which  PHP version are you using ?

**Comment by stdglpi** [comment]
PHP 8.1.4
Winserver 2016

**Comment by btry** [comment]
OK, Let's wait for tests of patch #2680 before testing it (tests running).

**Comment by stdglpi** [comment]
> OK, Let's wait for tests of patch #2680 before testing it (tests running).

**Comment by btry** [comment]
Tests are green; you can try it

**Comment by stdglpi** [comment]
> Tests are green; you can try it

everything is working !
Except the paramater "Targets" for a exemple : form to a ticket

if I click on properties it loads indefinitely, should I create a new issue for this ?


![image](https://user-images.githubusercontent.com/63521311/161751807-f3f7b7c9-ac14-4024-9198-19b54f8e747f.png)

![image](https://user-images.githubusercontent.com/63521311/161751795-e4857526-231f-45d9-b14c-848296c074f7.png)

**Comment by btry** [comment]
Yes, let's create a separate issue : this one is solved.

**Comment by stdglpi** [comment]
Thank you

Closed fixed by [#2680](https://github.com/pluginsGLPI/formcreator/pull/2680)

**Comment by stdglpi** [comment]
Thank you

Closed fixed by [#2680](https://github.com/pluginsGLPI/formcreator/pull/2680)
