### ISSUE TITLE
email field : Msg in english when i'm in french

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#268]
0.90-1.3.4
I'm using GLPI in french.
In a question typed Email, I enter rubbish, and I get a msg in english : 'please enter an email address' !
I didn't find where this msg come from.

**Comment by blerohellec** [comment]
Same when the field is typed Integer

**Comment by btry** [comment]
Hi

This issue should be fixed now. Anyway, it is too ols, it needs ti be checked against a recent version.
