### ISSUE TITLE
[ GLPI 10 rc2 ] [Formcreator 2.13.0-alpha.4] - "Properties" load indefinitely

### ISSUE THREAD

**Issue by stdglpi** [pluginsGLPI/formcreator#2682]
Hello @btry 

I'm dealing with this bug

After creating one form 

Going to the paramater "Targets" for a exemple : form to a ticket

if I click on properties it loads indefinitely (seems to have no logs)

![image](https://user-images.githubusercontent.com/63521311/161761634-4ca3a8e2-84e0-4dec-99dc-391dc53cd494.png)

![image](https://user-images.githubusercontent.com/63521311/161751795-e4857526-231f-45d9-b14c-848296c074f7.png)

**Comment by btry** [comment]
Hi

Open the browser developer tools, then refresh the page. Open the **targets* tab and check in the networking tab of the dev tools if you have HTTP response codes >= 300

**Comment by stdglpi** [comment]
do you find something interesting here ?
![image](https://user-images.githubusercontent.com/63521311/161781899-57b8ae06-69fd-4f7f-9221-fa60fbbc386c.png)

**Comment by btry** [comment]
Hi

There is a HTTP 500 response code when calling targetticket.form.php.

You should find an error message and its backtrace in the HTTP server's log (by default /var/log/apache2/errors.log for Apache)

**Comment by stdglpi** [comment]
Hello

In fact I have one log in the SQL errors.logs 

`[2022-04-06 13:51:31] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 367
  *** MySQL query error:
  SQL: SELECT `glpi_plugin_formcreator_questions`.`id` AS `qid`, `glpi_plugin_formcreator_questions`.`name` AS `qname`, `glpi_plugin_formcreator_sections`.`id` AS `sid`, `glpi_plugin_formcreator_sections`.`name` AS `sname` FROM `glpi_plugin_formcreator_questions` LEFT JOIN `glpi_plugin_formcreator_sections` ON (`glpi_plugin_formcreator_questions`.`plugin_formcreator_sections_id` = `glpi_plugin_formcreator_sections`.`id`) WHERE (`plugin_formcreator_forms_id` = '3' AND `fieldtype` IN ('glpiselect') AND `itemtype` IN ('Ticket') AND `display` = '0') ORDER BY `glpi_plugin_formcreator_sections`.`order`, `glpi_plugin_formcreator_questions`.`row`, `glpi_plugin_formcreator_questions`.`col`
  Error: Unknown column 'display' in 'where clause'
  Backtrace :
  src\DBmysqlIterator.php:108                        
  src\DBmysql.php:1039                               DBmysqlIterator->execute()
  plugins\formcreator\inc\question.class.php:1022    DBmysql->request()
  plugins\formcreator\inc\question.class.php:1055    PluginFormcreatorQuestion::getQuestionsFromFormBySection()
  plugins\formcreator\inc\targetticket.class.php:471 PluginFormcreatorQuestion::dropdownForForm()
  plugins\formcreator\inc\targetticket.class.php:286 PluginFormcreatorTargetTicket->showCompositeTicketSettings()
  plugins\formcreator\inc\targetticket.class.php:152 PluginFormcreatorTargetTicket::showProperties()
  src\CommonGLPI.php:687                             PluginFormcreatorTargetTicket::displayTabContentForItem()
  ajax\common.tabs.php:107                           CommonGLPI::displayStandardTab()`

**Comment by btry** [comment]
It is possible that this error leads to an PHP error some lines later in the code. IS there really nothing in the HTTP server logs ?

**Comment by stdglpi** [comment]
I have something ! :)

[2022-04-06 16:47:31] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\abstractitiltarget.class.php at line 1307
  Backtrace :
  ...rmcreator\inc\abstractitiltarget.class.php:1307 json_decode()
  plugins\formcreator\inc\targetticket.class.php:276 PluginFormcreatorAbstractItilTarget->showValidationSettings()
  plugins\formcreator\inc\targetticket.class.php:152 PluginFormcreatorTargetTicket::showProperties()
  src\CommonGLPI.php:687                             PluginFormcreatorTargetTicket::displayTabContentForItem()
  ajax\common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-04-06 16:48:01] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\abstractitiltarget.class.php at line 1307
  Backtrace :
  ...rmcreator\inc\abstractitiltarget.class.php:1307 json_decode()
  plugins\formcreator\inc\targetticket.class.php:276 PluginFormcreatorAbstractItilTarget->showValidationSettings()
  plugins\formcreator\inc\targetticket.class.php:152 PluginFormcreatorTargetTicket::showProperties()
  src\CommonGLPI.php:687                             PluginFormcreatorTargetTicket::displayTabContentForItem()
  ajax\common.tabs.php:107                           CommonGLPI::displayStandardTab()

**Comment by stdglpi** [comment]
> This is a deprecation warning. I think it is not related to your problem, but I'll search a solution for it.
> 
> I need to find a way to reproduce without much clues. Stay tuned

Thx I try to found something tommorow morning

**Comment by btry** [comment]
Hi

Please check the table **glpi_plugin_formcreator_targettickets**. Do you have a column named **commonitil_validation_question** ?

**Comment by stdglpi** [comment]
> Hi
> 
> Please check the table **glpi_plugin_formcreator_targettickets**. Do you have a column named **commonitil_validation_question** ?

Hi

![image](https://user-images.githubusercontent.com/63521311/162152456-80f94da7-85a6-45f5-a297-9a6c7019c4ce.png)

**Comment by btry** [comment]
You show the wrong table: this is **glpi_plugin_formcreator_targets_actors**

**Comment by stdglpi** [comment]
@btry hello 

sorry, I have only two lines on this table

![image](https://user-images.githubusercontent.com/63521311/162437288-fa8f911d-f3b8-494b-9926-0b2fdbde63a1.png)

**Comment by btry** [comment]
Hi 

The fix above should solve the SQL query error with bad column **display**

**Comment by stdglpi** [comment]
> Please execute the following query in mysql, and show the result
> 
> You show the wrong table: this is glpi_plugin_formcreator_targets_actors
> 
> ```sql
> SHOW CREATE TABLE `glpi_plugin_formcreator_targettickets`
> ```

Hello

find bellow the result

![image](https://user-images.githubusercontent.com/63521311/162745433-e04793b3-8fe3-4ed6-86af-55805b064633.png)

I also passed the fix for the bad column display thx !

**Comment by stdglpi** [comment]
@btry  seems to be fixed with the SQL query !

I tried to check forms from a basic user (simplified interface) if I click on a form I have this error : 

> [2022-04-11 16:06:06] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "formcreator_restrict_form" in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\form.class.php at line 2499
  Backtrace :
  plugins\formcreator\front\formdisplay.php:55       PluginFormcreatorForm->canViewForRequest()
  
> [2022-04-11 16:06:06] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\form.class.php at line 2499
  Backtrace :
  plugins\formcreator\front\formdisplay.php:55       PluginFormcreatorForm->canViewForRequest()

**Comment by btry** [comment]
Thank you, the fix has been merged. Now try #2696 and feedback. Itr should solve this problem as well

**Comment by stdglpi** [comment]
> Thank you, the fix has been merged. Now try #2696 and feedback. Itr should solve this problem as well

problem with users fixed with this fix 

thx

**Comment by stdglpi** [comment]
@btry sorry for the missunderstanding the problem with the SQL errors is fixed.

But, the menu properties is always "loading" see here for example.

https://we.tl/t-eRdLEGB4O5

thx

**Comment by btry** [comment]
Hi

Open again the developer tools of the browser, reproduce  the problem, then show the content of the console tab. Do you have JS errors ?

**Comment by stdglpi** [comment]
@btry 

On Firefox
![image](https://user-images.githubusercontent.com/63521311/163043487-ed4ee3cc-d188-4c0b-bf70-e42db81fb3d6.png)

On MS edge
![image](https://user-images.githubusercontent.com/63521311/163043362-bda792f0-6ea8-4d36-a55f-b3249fdf4f11.png)

**Comment by btry** [comment]
Hi

We are back (or we are still) facing a fatal error. 

If your HTTP server is Apache, you have probably a backtrace in /var/log/apache2/errors.log.

If your HTTP server is nginx you have probably a backtrace in /var/log/nginx/errors.log.

With more specific configurations of those HTTP servers the logs may be actually elsewhere. Check your config if needed.

**Comment by stdglpi** [comment]
@btry  good news ! problem solved :) i'm able to access to properties now.

![image](https://user-images.githubusercontent.com/63521311/163130130-94c0ee55-a861-4171-9c7b-529e186ac104.png)

**Comment by btry** [comment]
The fix #2699 solved the problem ?

**Comment by stdglpi** [comment]
> The fix #2699 solved the problem ?

Yes just after apply this fix I tried to go to "target then "properties" and now it's functional.

I had nothing in the PHP errors, just the "Json_decode" error in php_errors in GLPI folders.

> [2022-04-12 16:39:18] glpiphplog.NOTICE: *** PHP Deprecated function (8192): json_decode(): Passing null to parameter https://github.com/pluginsGLPI/formcreator/issues/1 ($json) of type string is deprecated in C:\inetpub\wwwroot\glpi\plugins\formcreator\inc\abstractitiltarget.class.php at line 1307
Backtrace :
...rmcreator\inc\abstractitiltarget.class.php:1307 json_decode()
plugins\formcreator\inc\targetticket.class.php:276 PluginFormcreatorAbstractItilTarget->showValidationSettings()
plugins\formcreator\inc\targetticket.class.php:152 PluginFormcreatorTargetTicket::showProperties()
src\CommonGLPI.php:687 PluginFormcreatorTargetTicket::displayTabContentForItem()
ajax\common.tabs.php:107 CommonGLPI::displayStandardTab()

**Comment by btry** [comment]
I think that your log entry comes from glpi/files/_log/php-errors.log, am I right ?

**Comment by stdglpi** [comment]
yes
\wwwroot\glpi\files\_log\php-errors.log

Nothing on log about Php manager

**Comment by btry** [comment]
OK, then we can close.

Thank you for your feedback.
