### ISSUE TITLE
Uncaught Exception RuntimeException: Empty IN are not allowed in C:\wamp64\www\glpi\inc\dbmysqliterator.class.php at line 564

### ISSUE THREAD

**Issue by bazsaraa** [pluginsGLPI/formcreator#2685]
Hello,

Please I am using GLPI 9.5.7 and plugin Form Creator 2.12.5,

When I want to select a Condition to show the section in Administration > Forms Add a section it keep to gives me this error :

Uncaught Exception RuntimeException: Empty IN are not allowed in C:\wamp64\www\glpi\inc\dbmysqliterator.class.php at line 564

![Capture d’écran (38)](https://user-images.githubusercontent.com/101580625/162004119-9d8cbd3d-3bb8-448d-b153-069284ad4c14.png)

in php-errors.log : 

[2022-04-06 14:41:20] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Empty IN are not allowed in C:\wamp64\www\glpi\inc\dbmysqliterator.class.php at line 564
  Backtrace :
  inc\dbmysqliterator.class.php:536                  DBmysqlIterator->analyseCriterion()
  inc\dbmysqliterator.class.php:517                  DBmysqlIterator->analyseCrit()
  inc\dbmysqliterator.class.php:522                  DBmysqlIterator->analyseCrit()
  inc\dbmysqliterator.class.php:295                  DBmysqlIterator->analyseCrit()
  inc\dbmysqliterator.class.php:94                   DBmysqlIterator->buildQuery()
  inc\dbmysql.class.php:902                          DBmysqlIterator->execute()
  plugins\formcreator\inc\question.class.php:1182    DBmysql->request()
  plugins\formcreator\inc\question.class.php:1209    PluginFormcreatorQuestion->getQuestionsFromFormBySection()
  plugins\formcreator\inc\condition.class.php:386    PluginFormcreatorQuestion::dropdownForForm()
  plugins\formcreator\ajax\condition.php:37          PluginFormcreatorCondition->getConditionHtml()

thank you in advance.

**Comment by btry** [comment]
Hi

Try this patch https://github.com/pluginsGLPI/formcreator/pull/2688/commits/f693f869b28cb1f600d244019e33323823e21aa8

By the way you won't be able to set any condition on a section if the form does not already contains an other section.

**Comment by btry** [comment]
Hi

Do you have a feedback about the fix ?

**Comment by btry** [comment]
Hi

Having no feedback, I assume that the fix is ok, and I close this issue.
