### ISSUE TITLE
cannot create an ticket with validation when target use question answer

### ISSUE THREAD

**Issue by triplility** [pluginsGLPI/formcreator#2689]
Hi
Good day.

I update the glpi from 10RC1 to 10 RC3, and formcreator from 2.13.0-alpha2 to 2.13.0-alpha.4

One feature is missing.

when I set an question and the type is "Actor" in the form. 
Then, in the properties of target I set Validation column is "User from question answer" and the question column I selected that Actor.
![image](https://user-images.githubusercontent.com/96858670/162367023-015ebc0d-7ce4-41e6-a364-c4d28139d826.png)

It create tickets normally but without approval. ( the the validation column I set Specific people, it works fine)

**Comment by triplility** [comment]
is there any update?

**Comment by btry** [comment]
Hi

Pleaase upgrade to Formcreator 2.13.0-beta.1, add the following patch (prevents to select a question outside the form) https://github.com/pluginsGLPI/formcreator/commit/01ddc79f251a0e3f54639541dfd45f4461d6bce0 and check if the problem persists. On my side I failed to reproduce.

**Comment by triplility** [comment]
Great! all are working! so far I think it very nice for me. All the features I wanted seemed to be there, and I couldn't fault anything more! Thank you!

**Comment by btry** [comment]
Hi,

Great! I close this issue.
