### ISSUE TITLE
[GLPI 10.0.0-rc3, formcreator 2.13.0-alpha.4] Several textarea not displayed

### ISSUE THREAD

**Issue by cyh67** [pluginsGLPI/formcreator#2692]
Hello
When I create a form with multiple textarea, it works fine when I'm logged in.

But if I give this form access to all non-logged-in users, the form comes up, but only the first textarea works.

The others get the "hidden" attribute in the html console.(style="visibility: hidden;")

![image](https://user-images.githubusercontent.com/99176339/162452942-5b6ba3f8-f5f0-4b33-83c5-9b34ee703517.png)

**Comment by cyh67** [comment]
Hi

I have not a 500 error, but a 404 concerning the plugin.min.js file
![image](https://user-images.githubusercontent.com/99176339/162724046-b09e7d2a-480d-4ff5-ba3d-14569388fee6.png)

**Comment by btry** [comment]
Bug confirmed. No valuable error logged (JS, php-errors, sql-errors, http errors).

**Comment by btry** [comment]
Hi, the above fix should solve the problem. Please try it and fedback.

**Comment by btry** [comment]
Hi

Having no feedback, I assume the problem is solved by the above PR.

**Comment by cyh67** [comment]
Hi
Sorry, In france this friday and this monday were off.

I have no update avaible for this plugin in the marketplace of GLPI, how can I test the update ?

Cyril

**Comment by btry** [comment]
You need to apply the patch with the patch tool. 

To download the patch, append **.diff** to the URL of the PR.

**Comment by cyh67** [comment]
Thank you, it works for me :)

**Comment by btry** [comment]
Great. The fix is ready for the next release.
