### ISSUE TITLE
FC v2.12.5 - Export fail

### ISSUE THREAD

**Issue by CireSacud26** [pluginsGLPI/formcreator#2702]
Hi,

With FormCreator 2.12.5 used with GLPI 9.5.7, exporting forms failed with php notice "PHP Notice (8): Undefined index: identifier in ..\inc\massiveaction.class.php at line 262" and a GLPI error message "Cannot export an empty object: Question ranges"

**To Reproduce**
1. Go to 'Administration > Forms'
2. Select a from or open a form
3. Clic on "Action" and choose "Export" > Post
4. A blank page is displayed with php notice "PHP Notice (8): Undefined index: identifier in ..\inc\massiveaction.class.php at line 262" and a GLPI error message "Cannot export an empty object: Question ranges". The "Back" link does'nt work and we have to use browser history back button to exit the blanck page.

Regards,
Eric

**Comment by btry** [comment]
Hi

A row in the table glpi_plugins_formcreator_questionranges is probably missing.

To fix this, open your form in the administration part of the plugin. Edit all questions supporting question ranges or question regexes. Save them without modifying anything. This will create the missing row for each impacted question.

Finally, try again to export  the form.

**Comment by CireSacud26** [comment]
Hi btry,

Thanks a lot ! The fix works like a charm.

Just a bit borring to edit all questions to save them. It should be usefull to be able to select them for a massive save. But that will be an evolution issue ;-)

Regards,
Eric
