### ISSUE TITLE
[GLPI 9.5.6]  Formcreator [ 2.12.3] no search menu display in form

### ISSUE THREAD

**Issue by falco2001** [pluginsGLPI/formcreator#2704]
Good morning,
The intention is to be able to type a search word in a drop-down list.

In image 2 form selection I have the possibility to type a search while in image 1 not possible.
I don’t see any difference between the two! Do you have any idea?
Thank you
![Clipboard01](https://user-images.githubusercontent.com/31952346/163390768-5bcda35f-a519-49b9-bd16-c8cd2f1265e8.jpg)
![Clipboard02](https://user-images.githubusercontent.com/31952346/163390803-87bbacef-6ce1-4514-9aa2-93a0fcf3073b.jpg)

**Comment by btry** [comment]
Hi

The search input exists only when there more than N results availabie in the dropdown. N is configurable in GLPI (if I remember well, in your preferences)

**Comment by falco2001** [comment]
Hello, yes it is true that one who has a search prompt has many lines. I do not find in the general preferences but where? Users request the ability to type words to find the title in the Thank You drop-down list

**Comment by falco2001** [comment]
if it is ok. It is in general configuration then
![Clipboard01](https://user-images.githubusercontent.com/31952346/163552905-d93debce-b01a-4c61-a841-465a38c5b100.jpg)
Thanks a lot

**Comment by btry** [comment]
Yes, this is this setting !
