### ISSUE TITLE
[GLPI 10.0.0-rc3, formcreator 2.13.0-alpha.4] files added in a form are not added to a ticket

### ISSUE THREAD

**Issue by udi8** [pluginsGLPI/formcreator#2706]
Hi,
I'm using Forms to to create a tickets,
with the new version - files that been upload to the form are not transferring or linked to the ticket created from the form,
with previews versions it worked,
also in the email notification the files are not attaches.
can someone assist with solving this issue please?

**Comment by btry** [comment]
Hi

try the above fix and feedback.

**Comment by udi8** [comment]
it worked like a charm!
thank you so much!
