### ISSUE TITLE
Quand je créé le ticket j'ai cette erreur  : [2022-04-19 14:22:39] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of GlpiPlugin\Formcreator\Field\DateField::serializeValue() must be of the type string, null returned in /var/www/html/glpi/marketplace/formcreator/inc/field/datefield.class.php at line 108   Backtrace :   ...place/formcreator/inc/formanswer.class.php:1035 GlpiPlugin\Formcreator\Field\DateField->serializeValue()   inc/commondbtm.class.php:1601                      PluginFormcreatorFormAnswer->post_updateItem()   ...tplace/formcreator/front/formanswer.form.php:53 CommonDBTM->update()

### ISSUE THREAD

**Issue by SebaFR7474** [pluginsGLPI/formcreator#2708]
Bonjour, 

J'ai créé un formulaire qui marchais, il créé bien le ticket.

J4ai modifié la cible pour le ticket, dans l'objet en mettant un tableau et en mettant en gras la partie gauche du tableau et maintenant cela ne marche plus.

J"ai même supprimé ma cible et recréé un par defaut et j'ai toujous cette erreur : 

[2022-04-19 14:22:39] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of GlpiPlugin\Formcreator\Field\DateField::serializeValue() must be of the type string, null returned in /var/www/html/glpi/marketplace/formcreator/inc/field/datefield.class.php at line 108
  Backtrace :
  ...place/formcreator/inc/formanswer.class.php:1035 GlpiPlugin\Formcreator\Field\DateField->serializeValue()
  inc/commondbtm.class.php:1601                      PluginFormcreatorFormAnswer->post_updateItem()
  ...tplace/formcreator/front/formanswer.form.php:53 CommonDBTM->update()

Et au moment de valider le formulaire que j'envoi à une personne j'ai l'erreur, ci dessus.

Que faut-il vérifier ?

Merci

**Comment by btry** [comment]
Bonjour

Il me semble que cette erreur a déjà été signalée et corrigée. Vous utilisez quelle version de Formcreator ?

**Comment by SebaFR7474** [comment]
Bonjour, on utilise la version 2.7.0 sur GLPI 9.5.5

Merci

**Comment by btry** [comment]
Il n'y a plus de support communautaire pour cette version. Elle est bien trop ancienne.

Utilisez une instance de test pour upgrader vers la version 2.12.5 et voyez si le problème persiste.

**Comment by SebaFR7474** [comment]
Bonjour, je veins de mettre à jour le plugin en 2.12.5 et maintenant cela
remarche.

Merci
