### ISSUE TITLE
Error to display tickets

### ISSUE THREAD

**Issue by JeanBuchweitz** [pluginsGLPI/formcreator#2709]
Hello.

I need help, when users (self-service) go to consult their tickets, it shows this message

Unknown column 'glpi_plugin_formcreator_issues.users_id_recipient' in 'where clause'

![image](https://user-images.githubusercontent.com/97294583/164027516-c82e8779-e59a-4cba-a517-6f5c185b0520.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version - GLPI 10.0.0-rc3 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:pt_BR

- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
Activities	activity	3.1.0-rc3
ActualTime	actualtime	1.5.1
Alertas	news	1.10.0-rc2
analytics	analytics	1.0.2
Apps structures	archisw	2.2.9
Business Processes	archibp	1.0.3
Camera barcode	camerainput	2.0.0-beta1
Campos adicionais	fields	1.13.0-rc6
Captura de tela	screenshot	2.0.0-beta1
Carga de créditos	credit	1.11.0-rc1
Cartografia	positions	6.0.0-rc2
Comportamentos	behaviors	2.4.1
Contas	accounts	3.0.0-rc2
Costs	costs	2.2.3
Data injection	datainjection	2.11.0-rc3
Dataflows	dataflows	2.2.7
Form Creator	formcreator	2.13.0-alpha.4
Geração de número de inventário	geninventorynumber	2.6.0-rc3
Gerenciamento das ordens de compra	order	2.8.0-rc1
Gerenciamento de objetos	genericobject	2.12.0-rc4
GLPI Inventory	glpiinventory	1.0.0-rc7
Holidays	holiday	0.1
Karastock	karastock	1.3.1
Linha do tempo dos chamados	timelineticket	10.0+1.0-rc1
Mais Chamados	moreticket	1.7.0-rc1
Mais Relatórios	mreporting	1.8.0-rc1
Marca Comercial	trademark	1.2.4
metabase	metabase	1.3.0-rc2
Meu Painel	mydashboard	2.0.0-rc3
OS	os	0.2.0b
Outros alertas	additionalalerts	2.4.0-rc1
Painel	dashboard	1.0.2
Pedidos de consumíveis	consumables	2.0.0-rc1
PHP SAML	phpsaml	0
Portal de entidades	manageentities	4.0.0-rc1
Tipologias	typology	3.0.0-rc1

- 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] CentoOS 8
 - Browser [e.g. chrome, safari] All

**Comment by Uptacknerd** [comment]
Hi

If you upgraded from a previous alpha version you need to do a forced upgrade. Locate in the GLPI directory and issue the following commands

```bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade```
```bin/console glpi:plugin:activate formcreator```

**Comment by btry** [comment]
Hi

If you upgraded from a previous alpha version you need to do a forced upgrade. Locate in the GLPI directory and issue the following commands

```bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade```
```bin/console glpi:plugin:activate formcreator```

**Comment by btry** [comment]
Hi

Having no feedack I assume that your problem is solved.
