### ISSUE TITLE
ID in Dropdown GLPI

### ISSUE THREAD

**Issue by marvinrs** [pluginsGLPI/formcreator#2712]
Is it possible to remove these numbers that appear on the options side?
![Capturar](https://user-images.githubusercontent.com/72471673/164294344-ebad4c24-4076-4f24-895d-d9e6959b54bd.PNG)

**Comment by btry** [comment]
Hi

Dropdowns obey this personal setting

![image](https://user-images.githubusercontent.com/14139801/164390681-488c899a-cb75-4cf4-b99a-77f98805d08e.png)

**Comment by btry** [comment]
Hi

Having no feedback, I assume that your question is solved.
