### ISSUE TITLE
Release date next stable version

### ISSUE THREAD

**Issue by AdminNge** [pluginsGLPI/formcreator#2713]
Hello,

I just upgraded to GLPI V10.
Do you have an idea (even approximate) for the release of the next stable version of Formcreator compatible v10 please?

Thank you for your work and have a nice day

**Comment by btry** [comment]
Hi

We are debugging the plugin, and improving some parts of the UI.  No release date yet to communicate.

**Comment by AdminNge** [comment]
Ok ty !
