### ISSUE TITLE
FAQ items don't show attachments

### ISSUE THREAD

**Issue by paidge** [pluginsGLPI/formcreator#2715]
With GLPI v9.5.7 and plugin FormCreator v2.12.5, I created a FAQ item with an attachment. The FAQ item and the attachment (a PNG file) are linked to the main entity recursively but I can't see the attachment in FAQ : 
![image](https://user-images.githubusercontent.com/2470104/164497857-ecdd96eb-f97a-499f-8270-712c514838f3.png)
It seems that the plugin did not plan to display attachments in FAQ items.

**Comment by mirda123** [comment]
Hi ,  i had the same issue, you have to apply a fix until GLPI 10,  try this : https://github.com/pluginsGLPI/formcreator/issues/2286

**Comment by paidge** [comment]
OK super merci. J'essaierai ça et apporterai mon feedback au ticket que tu as mentionné.
