### ISSUE TITLE
The edit buttons not working

### ISSUE THREAD

**Issue by WebGregGit** [pluginsGLPI/formcreator#2716]
**Describe the bug**
I cannot edit description font style - edit buttons not working.

**To Reproduce**

1. I'm creating a new form.
2. Add a question > Description field.
3. Select the text, icons for simple editing appear, e.g. bold, color...
4. When I click on one, the options disappear, but are not applied (nothing changes). I also can't expand the list of colors.

**Expected behavior**
Font style should change

**GLPI / Plugins (please complete the following information):**
- GLPI version: GLPI 10.0.0-rc3
- list of all plugins with their version:
	datainjection        Name: Data injection                 Version: 2.9.0      State: Installed / not activated
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.4 State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Installed / not activated
	printercounters      Name: Printer counters               Version: 1.7.0      State: Installed / not activated
	treeview             Name: Tree view                      Version: 1.9.1      State: Installed / not activated
	webresources         Name: Web Resources                  Version: 1.3.2      State: Installed / not activated
	tag                  Name: Zarządzanie słowami kluczowymi Version: 2.8.1      State: Installed / not activated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Edge
 - Version 100.0.4896.88 and 100.0.1185.44

**Additional context**
Keyboard shortcuts (eg ctrl + b to bold) work and edit the html source
Buttons work example for edition the knowledge base.

**Comment by btry** [comment]
Hi

Confirmed. If I remember well this isa duplicate of an other issue.

**Comment by btry** [comment]
Hi

I found the problem. Plese try the aboce patch and feedback. It worked well for me.

**Comment by WebGregGit** [comment]
Hi @btry 

I installed [2.13.0-beta.1](https://github.com/pluginsGLPI/formcreator/releases/tag/2.13.0-beta.1) - work like a charm. Good job and thank you :)

**Comment by btry** [comment]
Hi

Thank you for your feedback. I see this morning I missed to share a mandatory upgrade intervention for counters in service catalog. Please releases note to execute them.

**Comment by WebGregGit** [comment]
Hi @btry 

I don't quite understand. The 2.13.0-beta.1 release has the changes you indicated in https://github.com/pluginsGLPI/formcreator/pull/2725. Should I do anything else?

**Comment by btry** [comment]
> I installed [2.13.0-beta.1](https://github.com/pluginsGLPI/formcreator/releases/tag/2.13.0-beta.1) - work like a charm. Good job and thank you :)

After the above message, I considered that the fix worked for you. and now you ask if you have something else to do.  So I'm lost. Did the fix worked or not ?

**Comment by WebGregGit** [comment]
Yes it is OK but you wrote about missed and: "Please releases note to execute them" and it was not understandable to me  :)
