### ISSUE TITLE
[2.13.0alpha4] plug in alerte does not show in full formulaire

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2720]
**Describe the bug**
Plug in alerte 1.10.0 + plug in formcreator 2.13.0 alpha4 
no alert content (text + picture)  shown above like before in "catalogue de service simplifié" mode.

**To Reproduce**

**Expected behavior**
Alerts

**Screenshots**

**GLPI / Plugins (please complete the following information):**
GLPI 10 official
Plug in alerte 1.10.0 + plug in formcreator 2.13.0 alpha4 

**Desktop (please complete the following information):**
 firefox

**Additional context**

**Comment by btry** [comment]
Hi

Please try the following branch. Do not apply the patch on 2.13.0-alpha.4 as it relies on an other work which has been merged today.

If you don't know how to build the plugin, let me know and I'll provide a build.

**Comment by mirda123** [comment]
hi,
 sorry for the delay, i have absolute no idea how to do that. I do usually apply "classic" patch but this time... i don't know what to do..

**Comment by mirda123** [comment]
just found and tried the new alert plugin 2.13.0beta1
alert n° 1 is back !! thanks !
But alert N°2 or 3 do not display

**Comment by mirda123** [comment]
Solved too : you have to create the alert, save it,  then open again and add a target.. and save again...

**Comment by btry** [comment]
Hi

Then I guess I can close ?

**Comment by mirda123** [comment]
yes
