### ISSUE TITLE
[Glpi 10.0.0] [FC 2.13.0-b1] yarn command not found

### ISSUE THREAD

**Issue by jcovillers78114** [pluginsGLPI/formcreator#2726]
Hello,
I have just installed this version. In the plugin manager I have this instruction

"Run yarn install --prod in the plugin directory"

When I run this command in the terminal in the plugin directory I get a return

"yarn : command not found"

Thx

**Comment by btry** [comment]
Hi

I'm checking the archive...

**Comment by btry** [comment]
The archive looks good, I was able to isntall it and enable it.

You probably downloaded a ZIP from Github as described in the screenshot below
![image](https://user-images.githubusercontent.com/14139801/165459932-99ec07b3-8e50-4438-80f5-1c7de10c64e7.png)

If I'm right you don't have the 3rd party libraries. The best would be to use the marketplace or the archives provided in  the releases : https://github.com/pluginsGLPI/formcreator/releases

I'm waiting for your feedback.

**Comment by jcovillers78114** [comment]
The archive I downloaded was from the releases. I'll try to download it again and redo the install

**Comment by btry** [comment]
Did you pick the .tar.gz ?

![image](https://user-images.githubusercontent.com/14139801/165462411-ec133e4a-2e46-443d-a08a-163d8adf8af9.png)

**Comment by btry** [comment]
This button is a link to the .tar.bz2 archive, then this is equivalent. I just checked, and the archive contains the 3rd party libraries.

in glpi/plugin/formcreatir/lib you should find the following.
![image](https://user-images.githubusercontent.com/14139801/165463968-757293cb-10c7-486d-8e96-19a9b1c9cd1c.png)

you must have the file .yarn-integrity. this file is generated by yarn after downloading the dependencies. as far as I see the archive contains all the dependencies, as expected.

**Comment by jcovillers78114** [comment]
Okay, I've done another install. It seems to work. I don't know what happened with the other archive...
Apparently there were a lot of corrections made because until now with alpha 4 my forms didn't work! :) cool

**Comment by btry** [comment]
Great ! Problem solved. 

You may read the changelog to know the fixes since Alpha.4

**Comment by jcovillers78114** [comment]
Oops. I spoke too fast!
There is only one form that works out of the 16 in the test profile :(

**Comment by btry** [comment]
Open a separate issue : one per bug. Don't forget to describe how to reproduce, and check the logs php-errors.log, sql-errors.log. If you encouteer a blank or incomplete page, check also the errors.log of the HTTP server (fatal errors uncatchable with PHP code).
