### ISSUE TITLE
Blank page when adding a question with an attachment

### ISSUE THREAD

**Issue by MMAPOPIT** [pluginsGLPI/formcreator#2728]
Hello,

Version Glpi : 10.0.0
Version formcreator : 2.13.0-alpha.4

When I add a question containing "file" "attachment", => when creating the ticket via form => I encounter a blank page
![form1](https://user-images.githubusercontent.com/104492129/165473786-88316d40-8899-4bb9-8b2a-09653382de89.png)

![form2](https://user-images.githubusercontent.com/104492129/165473845-2687d6b7-8974-4619-ac6f-332d012decdc.png)

Regards,

**Comment by btry** [comment]
Hi

Upgrade to Formcreator 2.13.0-beta.1 released yesterday. Follow upgrade instructions provided in the release notes (see #2727 related to counters)

**Comment by Pop-it** [comment]
Hi,
It's solved thanks.
It's just that I didn't see the last version of yesterday.

**Comment by btry** [comment]
Great

Thank you for your feedback.
