### ISSUE TITLE
[GLPI 10.0.0] [FC 2.13.0-b1] Can't add associated element in target property

### ISSUE THREAD

**Issue by jcovillers78114** [pluginsGLPI/formcreator#2730]
Hello,
I have created a form that contains a question of type "GLPI object" > computer, which allows the user to select the computer listed in GLPI.

In the properties of the target > Associated elements of the form, I cannot select the answer to the question corresponding to the GLPI object because the list is empty.

![2022-04-27 10_42_22-Formcreator - 27 - GLPI](https://user-images.githubusercontent.com/57490677/165479796-55c77b45-0605-4ab2-bd86-dbfd209064a3.png)

**Comment by btry** [comment]
Hi

confirmed

**Comment by btry** [comment]
Please add the following fix and feedback 0a62b976

**Comment by jcovillers78114** [comment]
The fix has corrected the problem.
Thx

**Comment by Ioannos** [comment]
Hello, I have the same issue but the fix seems to be already applied in my version

Item_Ticket::itemAddForm(new Ticket(), $options);
      echo '</div>';
      echo '<div id="plugin_formcreator_associate_question_value" style="display: none">';
      // select all user questions (GLPI Object)
      PluginFormcreatorQuestion::dropdownForForm(
         $this->getForm(),
         [
            'fieldtype' => 'glpiselect',
            'itemtype' => $CFG_GLPI['ticket_types']
         ],
         '_associate_question',
         $this->fields['associate_question']
      );
