### ISSUE TITLE
Drop-down list ldap no longer works

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2731]
Hello,
I reinstalled my glpi server following the official documentation word for word. Today, I realize that I cannot display the "title" function of my LDAP. No matter the profile, self-service or super admin. in preview the problem is present. I deleted:/recreated the field but same problem.
![image](https://user-images.githubusercontent.com/17006344/165511227-7fef90c6-58be-4f32-b2a8-34be0e24f75e.png)
MariaDV 10.5.15 PHP 8.0.17 formcreator 2.12.5

[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/8571713/php-errors.log)
![image](https://user-images.githubusercontent.com/17006344/165512533-8bedd470-4217-45e7-930a-d601960a6753.png)
![image](https://user-images.githubusercontent.com/17006344/165512710-20743d95-a4d6-4cfc-a3e1-91d45292d921.png)

**Comment by btry** [comment]
Hi

Is this issue related to Formcreator ?

Note: I cannot download the image. Please paste it directly here instead of using a 3rd party service.

**Comment by Riesuu** [comment]
Yes this is for formcreator, I corrected the error in the image

**Comment by Riesuu** [comment]
You can close the case. 
The problem was with my service account which was locked and I had to change the password to resynchronize everything.
thank you
