### ISSUE TITLE
[GLPI v10.0.0] [FC 2.13.0-b1] Pas de FAQ en entrées distinctes | No FAQ in separate entries

### ISSUE THREAD

**Issue by jcovillers78114** [pluginsGLPI/formcreator#2733]
Bonjour,

Lorsque "Fusionné avec les formulaires " est activé dans administration > entité > formulaires > base de connaissance, les faq s'affichent bien.

Lorsque " Entrée de menu distincte" est activé, le menu "Foire aux questions" s'affiche bien dans la barre latérale gauche de l'interface simplifiée, mais il n'y a aucune faq.

Hello,

When "Merged with forms" is activated in administration > entity > forms > knowledge base, the faqs are displayed well.

When "Separate menu entry" is enabled, the "Frequently Asked Questions" menu is displayed in the left sidebar of the simplified interface, but there are no faqs.

**Comment by jcovillers78114** [comment]
Les anciennes catégories de la FAQ ne sont pas reprises. La liste des catégories de FAQ est vide mais en cliquant sur l'icone "maison" les faq s'affichent

**Comment by jcovillers78114** [comment]
J'ai essayé de créer une catégorie directement dans la sous-entité concernée mais ça ne fonctionne pas non plus, la liste des catégories de faq reste vide.
![2022-04-28 11_32_37-Catalogue de service - GLPI](https://user-images.githubusercontent.com/57490677/165723408-b662183e-3a70-4987-8322-560e45062481.png)

**Comment by btry** [comment]
Hi

First I must remove the home pictogram to match the appearance of the forms list.

I found that the SQL query to get the categories is roken, due to a change in GLPI core. Work in progress.

**Comment by btry** [comment]
Apply the above patch and let me know your results.

**Comment by jcovillers78114** [comment]
Perfect, it works now. But the "see all" link does not work. It doesn't seem to be clickable

![2022-04-28 16_07_13-Catalogue de service - GLPI](https://user-images.githubusercontent.com/57490677/165771595-196300a3-9c30-4d9b-99e7-b618a169d861.png)

**Comment by jcovillers78114** [comment]
Is the "see all" link listed in the .po file?

**Comment by btry** [comment]
Hi

"See All" must be listed in the .po files. If not then there is a problem. You may easily check in Transifex. From what I see, the string is translatable a,d is translated for FR_fr.

**Comment by btry** [comment]
I added this commit 0b83e4cb3c683db5ce6adbc5febf398d22715dba ti the PR, this should fix the "see all" link.

**Comment by jcovillers78114** [comment]
![2022-04-29 08_37_39-fr_FR (1) po - Poedit](https://user-images.githubusercontent.com/57490677/165895910-b9237ae1-1b62-4bd4-84e8-54ed2f09bdee.png)

Hi!
I found it in the .po file but it seems that the translation does not apply. However the word "category" which is just above is translated as you can see on the previous screen

**Comment by btry** [comment]
This fx is to make the click work as expected. Problem with locales has been soved right now. 

As this is a bit complicated I would recommend you to build the plugin from the branch of the PR and install it. Translation should be good. Enable debug mode in GLPI to force refresh of locales cache, or stop the server, delete the locales cache manually,  then restart.

**Comment by jcovillers78114** [comment]
Sorry, I don't know enough about github to know how to build the plugin from the PR branch.

**Comment by btry** [comment]
Ok; try this build and feedback.

[glpi-formcreator-2.13.0-dev.zip](https://github.com/pluginsGLPI/formcreator/files/8589797/glpi-formcreator-2.13.0-dev.zip)

**Comment by jcovillers78114** [comment]
Ok the link is translated now. But if I change the translation in the PO file and reset the translation cache in debug mode it doesn't change the translation displayed on the screen for the user.
I can't find the temporary translation files in GLPI

![2022-04-29 12_35_57-Configuration - GLPI](https://user-images.githubusercontent.com/57490677/165929212-7929e3be-9674-4539-9a42-cae8ca1650ea.png)

**Comment by btry** [comment]
changing the .po file is not enough : .po files  are compiled in .mo files, and those .mo files are used by GLPI.

If you subscribe to a GLPI network offer you may have access to a plugin dedicated to easily change translations in GLPI and its plugins. As an alternative you need to compile yourself the .po file with gettext or the developer tools provided with source code of Formcreator.

**Comment by jcovillers78114** [comment]
My bad!
I forgot to transfer the MO file.
Everything is working normally.
Thx!

**Comment by btry** [comment]
Ok then I merge the fix.
