### ISSUE TITLE
glpi problem - formcreator

### ISSUE THREAD

**Issue by kleverson4g** [pluginsGLPI/formcreator#2736]
After updating to glpi10 and stable version formcreator plugin, it was verified that the glpi object option to add objects created from the Generic Objects plugin is no longer working, this in version 9.5.7 was normal, is there any fix?

**Comment by btry** [comment]
Hi

Please tell the exact version of Formcreator.

**Comment by btry** [comment]
Hi

confirmed. Please test the above patch and feedback.
