### ISSUE TITLE
[GLPI v10.0.0] [FC 2.13.0-b1] The FAQ search bar displays the support forms

### ISSUE THREAD

**Issue by jcovillers78114** [pluginsGLPI/formcreator#2739]
I have disabled the search bar in the support forms. However, it is still displayed in the FAQ section and if you use it to search for an FAQ it only displays support forms.

**Comment by btry** [comment]
Hi

I updated the PR to fix the KB search. I also found a proble in GLPI core, then you have to test with a 2nd patch :

https://github.com/glpi-project/glpi/pull/11469/files

I'm waiting for your feedback.

**Comment by btry** [comment]
Hi

If you have a blank page, then you have very likely a PHP fatal error. Check if you have a backtrace in the errors.log file of your HTTP server (not GLPI).

**Comment by jcovillers78114** [comment]
Uncaught Exception ParseError: syntax error, unexpected end of file, expecting ')' in /glpi/src/KnowbaseItem.php at line 2205

**Comment by btry** [comment]
I tried to browse through the KB of GLPI, no problem with this patch. 

How did you apply the patch in GLPI core ? I'm suspecting that you applied itmanually and introduced an error in the file.

**Comment by jcovillers78114** [comment]
I copy and paste to replace the old code with the new one

**Comment by btry** [comment]
The errors occurs more than 500 lines after the line where the patch is applied.

You should learn how to apply the patch with the patch tool. This is safer. There are plenty of tutorials and documentation on internet to learn how it works.

Restore the file to its original state and patch it properly. I think this will solve this blank page issue (the patch has been merged in GLPI already.

**Comment by btry** [comment]
I notice you closed the issue. Is the problem solved ?
