### ISSUE TITLE
Operators issue

### ISSUE THREAD

**Issue by Alibaskins** [pluginsGLPI/formcreator#274]
Hi,

In a question, when i try to set operators ( =, >=, <= ...) it doens't works. It's always "=".
To hide a question for exemple.
![form_test_operators](https://cloud.githubusercontent.com/assets/22218247/19040509/aa94c956-8984-11e6-8187-43aa402dc8c8.PNG)

I can used it only if i put the operator directly on the database.

**Comment by btry** [comment]
Hi

this bug has already been fixed, but after version 1.3.4. See #242 . With the master branch, it is confirmed the bug no longer happens.

**Comment by Alibaskins** [comment]
Ok indeed.

It's ok with this fix.

Sorry, i haven't see this issue.
