### ISSUE TITLE
FormCreator: Send button disappears sometimes

### ISSUE THREAD

**Issue by veniphere** [pluginsGLPI/formcreator#2741]
**Describe the bug**
Even if the "send" button is set to be seen in any case, there some circumstances when not. This according to the selected value of a select field

**To Reproduce**
1. Create a form with a few questions, first is "Select" with 4 or 6 choices and answer Yes to the show empty parameter, the lasts question may depend on the first question possible answers.
2. Go to preview tab then provide an answer of the first question and observe the behavior.
3. You should see the "send" button displayed or not depending on the choosen answer.
4. Changing the selected value and the form do not update the form at all except if you choose the default answer "-----" (this one when you do no select one of the provided possible answers)

**Expected behavior**
The send button should be seen in any case as configured so

**Screenshots**
![image](https://user-images.githubusercontent.com/104593546/165834636-7472c171-e820-4519-8672-918926ad69ad.png)

![image](https://user-images.githubusercontent.com/104593546/165834807-f6b9d7d0-0d0a-420b-8772-8711d2615870.png)

![image](https://user-images.githubusercontent.com/104593546/165834888-1d61b42c-1053-4b19-a86a-10d21857f717.png)

Form is not updated once select modified
![image](https://user-images.githubusercontent.com/104593546/165835104-a1917d40-01c0-46fc-ac02-fc9c72a23aae.png)

Except if back to default value
![image](https://user-images.githubusercontent.com/104593546/165835224-f321f139-0b58-4c31-9072-5c54ed14d359.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10
- Plugins list
--
formcreator          Name: Form Creator                   Version: 2.13.0-beta.1 State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+4.0    State: Not installed 	oauthimap            Name: Oauth IMAP                     Version: 1.4.0      State: Enabled 	screenshot           Name: Screenshot                     Version: 2.0.0      State: Enabled

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Firefox ]
 - Version [99.0.1 (64-bit)]

**Additional context**

**Comment by btry** [comment]
Hi

This is very likely related to conditions to show or hide the button.

Check if there are such conditions, and check phm-errors.log and sql-errors.log. 

Open developer tools in the browser, then reproduce again, and check in the developer tools of you have JavaScript error or http requests in error (code >=300)

**Comment by ashkurin** [comment]
Hi!

Have same error, version 2.14.0-dev. 
In developer tool i see:
"GET https://sd.r9b.kiev.ua/plugins/formcreator/css_compiled/styles.min.css?v=56725f7b48ca0f7c09f7e31c221480e6581c5b04 net::ERR_ABORTED 404 (Not Found)"

My form https://sd.r9b.kiev.ua/form1 or https://sd.r9b.kiev.ua/plugins/formcreator/front/formdisplay.php?id=1

Button Send visible in Mozilla Firefox, but not visible in Google Chrome.

**Comment by btry** [comment]
Hi

For the http 404 error, you need to compile the scss. 

I don't think this will solve the problem with the button, I'll investigate lzter

bin/console glpi:plugin:formcreator:scss 

For the button, I'll investigate later.

**Comment by btry** [comment]
Hi

I checked the form with several browers based on webkit. No problem on my side, the send buton is visible. Maybe there is some JS error ?

**Comment by veniphere** [comment]
Hi, i downloaded the last beta2 version and removed the conditions to display the send button (as it does not really matters when you set some mandatory fields that are doing the control to be able to send the form.)
Not sure the root cause is of if any problem at then end but not find some time to test it more deeply.
Case can be closed.
