### ISSUE TITLE
No selectable entity

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#2746]
Hello,
I still have a problem with entity selection on formcreator 2.12.5, either in preview or in production.

[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/8603225/php-errors.log)

![image](https://user-images.githubusercontent.com/17006344/166243796-e94b7b44-e347-4b6c-83c6-05f2a0247b8d.png)

GLPI 9.5.7
PHP 8.0.17
mariadb 10.5.15

**Comment by btry** [comment]
Hi

Can you check if the problem persists with the latest revision of the branch support/2.12.0 ?

**Comment by Riesuu** [comment]
Hello,
I was able to apply a command yarn install --prod  but not the second one, I tried several options but nothing works I am still in error.

![image](https://user-images.githubusercontent.com/17006344/167433451-68bac056-757b-4059-8257-3e307f2843e2.png)

any idea?

**Comment by btry** [comment]
You probably have a python program named yarn in your system. Thre is a name conflict with the nodeJS tool you need to use.

Here is a build to make things easier. Try it.

[glpi-formcreator-2.12.5-dev.zip](https://github.com/pluginsGLPI/formcreator/files/8669577/glpi-formcreator-2.12.5-dev.zip)

**Comment by Riesuu** [comment]
Hi,
the problem is resolved with the dev version

**Comment by btry** [comment]
Hi

Ok, then we can close this issue. Thank you for your feedback.
