### ISSUE TITLE
[v2.13.0-beta.1] Conditions based on dropdown questions don't work

### ISSUE THREAD

**Issue by paidge** [pluginsGLPI/formcreator#2749]
**Describe the bug**
When I create a form containing a question with a condition based on a dropdown question, the question with conditions is always displayed, even if the answer of the dropdown question don't match. Moreover, the submit button is not displayed.

**To Reproduce**
1. Create a form with 2 questions. The 1st one must be a dropdown, the second one (no matter what type) must be displayed only if the 1s one matches a value
2. Preview the form

**Expected behavior**
The 2nd question should respect the condition to be displayed. The submit button should be displayed.

**Screenshots**
Questions wihout the condition :
![image](https://user-images.githubusercontent.com/2470104/166679419-9dd8d886-8543-4c7f-a6b4-bc55cfedc58d.png)

Questions wih the condition :
![image](https://user-images.githubusercontent.com/2470104/166679241-b13995a2-03c7-4db9-96f5-641fae46d05d.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0
- list of all plugins with their version : FormCreator v2.13.0-beta.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox v99.0.1

**Comment by paidge** [comment]
This issue might be linked to #2741

**Comment by btry** [comment]
Hi

Yes there may be a relation with the other issue. Please check your logs and the developer tools, tab networking + JS console of the browser.

**Comment by paidge** [comment]
I already have checked the JS console and I saw nothing. Nothing with `tail -f sql-errors.log` neither. I just downgraded my GLPI server to v9.5 because we have to launch it in production soon so I can't dig anymore this issue.

**Comment by btry** [comment]
> I just downgraded my GLPI server to v9.5 because we have to launch it in production soon so I can't dig anymore this issue.

Did you tried to use  Formcreator 2.13 beta in production ??

Please keep the GLPI 10 instance somewhere and check if there is something in php-errors.log.

**Comment by paidge** [comment]
> Did you tried to use Formcreator 2.13 beta in production ??
Nope. I'am testing GLPI for 3 months on a VM provided by our AdminSys Team and we will launch it soon. I wanted to try GLPI v10 to see if it is ready to be used in production. But it is no. So I downgraded. I will check if the VM has enough space disk to host two GLPI instances

**Comment by paidge** [comment]
For the test, I created a new form with only two questions like explained in my first message (section **To reproduce**).
And [here is the JSON export of the form](https://pastebin.com/DUpZNu3v). 

`itemtype` is empty only for the 2nd question which is a text input ("fieldtype":"text")

**Comment by btry** [comment]
Hi

The json looks good, no problem with the **itemtype column**

**Comment by btry** [comment]
Hi

I think this patch will solve your problem, try it and feedback.

https://github.com/pluginsGLPI/formcreator/pull/2752

**Comment by paidge** [comment]
Perfect ! :)

**Comment by btry** [comment]
Thank you for your feedback; I close.
