### ISSUE TITLE
Default value in a select

### ISSUE THREAD

**Issue by Alibaskins** [pluginsGLPI/formcreator#275]
When i use a question with a select type.
I put the default value to 1.
![form_default_1](https://cloud.githubusercontent.com/assets/22218247/19041344/f78985aa-8987-11e6-9034-9ad7ba3f06ca.PNG)

But, when i am using the form, it's like if it is set 2 by default because the second question is displayed.
If i use the select menu to choose 2, nothing happens, and if i set again 1, only the first question is displayed.

Thank you for your work.

**Comment by btry** [comment]
Hi

Can you show the settings of the second question ?

**Comment by Alibaskins** [comment]
Here : 
![form_default_1-2](https://cloud.githubusercontent.com/assets/22218247/19042246/917510f0-898b-11e6-8002-28b0bef7a41e.PNG)

Show if value >= 2

**Comment by btry** [comment]
This issue should be fixed with the last commits.

**Comment by Alibaskins** [comment]
Hum it's not ok.

Now, when i add 2 questions, only the first question is displayed for validator (the 2nd is hidden).
And all values of a select filed are displayed.
It's like if now, the default value 1 is always selected. 

Exemples :
Form with 2 questions :
![form_with_2_questions](https://cloud.githubusercontent.com/assets/22218247/19065869/69a4b824-8a16-11e6-940a-5eb1a744376c.png)

Validator view of this form (issues in red) :
![form_with_2_questions_validator_view](https://cloud.githubusercontent.com/assets/22218247/19065879/771362f8-8a16-11e6-8e02-738cc8849340.png)

**Comment by btry** [comment]
Indeed, there was something still wrong.

I reproduced and fixed an error for *Nombre de règles** ; but I don't reproduce for *Protocole* and *Action*, even after disabling the fix.

Can you show the definition of Action and Protocole fields to ensure I used the same settings ? A screenshot would  be perfect.

**Comment by Alibaskins** [comment]
Ok, my fault for this case (Action and Protocole fields), sorry.
In default value, I had set all values...

**Comment by btry** [comment]
What about *Nombre de règles* ? Did the fix solved the issue ?

**Comment by Alibaskins** [comment]
Just to be sure, i have installed 0.90-1.4-beta2.
It's good ?

With this version, more details on screens : 

Form creation : 
![form_2_questions_default_1_ok](https://cloud.githubusercontent.com/assets/22218247/19074661/8bffd374-8a41-11e6-8037-331c2f1d23e3.png)

Form Validation : 
![form_2_questions_default_1_ok_validator_view_field_select_show_always_the_default_value](https://cloud.githubusercontent.com/assets/22218247/19074666/938bde12-8a41-11e6-9cd8-a650afec24ef.png)

Configuration of Action : 
![form_action1_configuration](https://cloud.githubusercontent.com/assets/22218247/19074675/9e0c8f1c-8a41-11e6-8131-ad5f200abb67.PNG)

Configuration of protocole : 
![form_protocole1_configuration](https://cloud.githubusercontent.com/assets/22218247/19074688/a9000318-8a41-11e6-833d-23788a70d935.PNG)

**Comment by btry** [comment]
Yes : 0.90-1.4-beta2 contains the latest development (branch master in the repo).

I used your screenshots for the fields *protocole* but I don't reproduce the empty values in the validator's view. (for *Actions* this should be the same problem)

**Comment by Alibaskins** [comment]
Hum, it's not working for me.
I have configured a new form : 
![form_test_just_a_select](https://cloud.githubusercontent.com/assets/22218247/19076225/31e5b8d4-8a48-11e6-8c0c-90bbd4fd389f.PNG)

When i create a form : 
![form_test_just_a_select_creation](https://cloud.githubusercontent.com/assets/22218247/19076237/3ea0d8ce-8a48-11e6-8bd3-cc6ea82d510d.PNG)

When the validator is viewing : 
![form_test_just_a_select_validator](https://cloud.githubusercontent.com/assets/22218247/19076246/45dfb16e-8a48-11e6-8bbd-361b0378365c.PNG)

**Comment by btry** [comment]
No, I still don't reproduce.

Maybe there is a problem while saving the value of a seelct field

Have a look in glpi/files/_log : fiels php-errors.log and sql-errors.log and check if there is something with the same date time as the  creation of the request.

If you can, also check in the DB the table glpi_plugins_formcreator_answers. If you create a request with your very last form (the single selct field) you should see the last entry containing a non empty value (1 or 2) in the column *answer*

**Comment by Alibaskins** [comment]
Ok for php-errors.log i have that when i complete the form : 
```
2016-10-04 16:12:12 [28@aixk]
  *** PHP Warning(2): in_array() expects parameter 2 to be array, string given
  Backtrace :
  :
  ...ormcreator/inc/fields/select-field.class.php:46 in_array()
  plugins/formcreator/inc/field.class.php:35         selectField->getAnswer()
  plugins/formcreator/inc/fields.class.php:111       PluginFormcreatorField->show()
  plugins/formcreator/inc/formanswer.class.php:315   PluginFormcreatorFields::showField()
  inc/commonglpi.class.php:464                       PluginFormcreatorFormanswer->showForm()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-10-04 16:12:12 [28@aixk]
  *** PHP Warning(2): in_array() expects parameter 2 to be array, string given
  Backtrace :
  :
  ...ormcreator/inc/fields/select-field.class.php:46 in_array()
  plugins/formcreator/inc/field.class.php:35         selectField->getAnswer()
  plugins/formcreator/inc/fields.class.php:111       PluginFormcreatorField->show()
  plugins/formcreator/inc/formanswer.class.php:315   PluginFormcreatorFields::showField()
  inc/commonglpi.class.php:464                       PluginFormcreatorFormanswer->showForm()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()


2016-10-04 16:12:30 [28@aixk]
  *** PHP Warning(2): in_array() expects parameter 2 to be array, string given
  Backtrace :
  :
  ...ormcreator/inc/fields/select-field.class.php:46 in_array()
  plugins/formcreator/inc/fields.class.php:75        selectField->getAnswer()
  plugins/formcreator/inc/formanswer.class.php:711   PluginFormcreatorFields::getValue()
  ...r/inc/notificationtargetformanswer.class.php:40 PluginFormcreatorFormanswer->getFullForm()
  inc/notificationtarget.class.php:1073              PluginFormcreatorNotificationTargetFormanswer->getDatasForTemplate()
  inc/notificationtemplate.class.php:240             NotificationTarget->getForTemplate()
  inc/notificationevent.class.php:168                NotificationTemplate->getTemplateByLanguage()
  plugins/formcreator/inc/formanswer.class.php:595   NotificationEvent::raiseEvent()
  plugins/formcreator/front/formanswer.form.php:37   PluginFormcreatorFormanswer->saveAnswers()
```
No error in the sql-error.log

In the database, the field "answer" is correctly set.

**Comment by btry** [comment]
I think you're not up to date. I fixed a bug this morning which may cause this error.

Update your copy of the plugin and try to show a request in a validator's point of view. I guess the bug also occurs in the requester's point of view.

For reference : the commit which should fix your issue
https://github.com/pluginsGLPI/formcreator/commit/24245af076489ebea78f46a6bb1979de7351d63d

**Comment by Alibaskins** [comment]
Ok yes indeed.
My last update was from 9h20.

With a new download it's ok for this issue.

Just a last thing i have noticed. 
The description fileds aren't displayed for validator.
For creator in green :
![creator_with_description_field](https://cloud.githubusercontent.com/assets/22218247/19079664/a86fbdae-8a54-11e6-8e33-991570163501.png)
For validator in red : 
![validator_without_description_field](https://cloud.githubusercontent.com/assets/22218247/19079678/b48733e2-8a54-11e6-9ad7-9ef77144fc8f.png)

**Comment by btry** [comment]
Dans le code source, les zones manquantes (champs de type description) sont explicitement exclues lors de l'affichage d'un formulaire en lecture seule. Cela concerne le demandeur affichant une demande qu'il a créée, ou le valideur qui examine une demande.

Cela me semble logique car la description devrait être utile uniquement pour celui qui remplit le formulaire. 

Je suppose que vous avez utilisé les descriptions pour faciliter la lecture rapide de vos formulaires en le divisant en plusieurs grandes parties.

Pour cet usage il serait plus approprié d’utiliser les sections. Je suppose que vous ne l'avez pas fait car il n'est pas possible de cacher une section et son contenu. Il est envisageable de rajouter cette fonctionnalité, à suivre dans un autre ticket qui reste à créer.

**Comment by Alibaskins** [comment]
Oui en effet c'est bien ça.
Je m'en étais vite rendu compte et donc contourné le souci.

Je rajoute un ticket donc pour cette fonctionnalité ? 

ps : Merci beaucoup pour les correctifs. Super boulot !

**Comment by btry** [comment]
Vous pouvez créer un ticket pour cela. De cette manière vous serez informé de l'avancement du sujet.

Si le problème de valeur par défaut est résolu pour vous, vous pouvez aussi fermer celui-ci :) 

Si vous avez envie d'essayer le nouveau catalogue de service (.90-1.4-beta2 et >) je vous invite à l'activer sur un GLPi de test (dans les entités > onglet Formulaires), et voir avec l'interface simplifiée (compte post-only par exemple) ce que ça donne. Les retours sont les bienvenus.

**Comment by Alibaskins** [comment]
Ok je testerai ça sur le glpi de recette.

Je fais un ticket pour la fonctionnalité et je clos ce ticket.

Encore merci !
