### ISSUE TITLE
Update Font Awesome to v6

### ISSUE THREAD

**Issue by darthjuanan** [pluginsGLPI/formcreator#2751]
Hi!

First of all, congratulations for your fantastic plugin!!!

I'm using it, and I miss many icons in the Font Awesome. Perhaps, because it is in v5 and the fontawesome is in v6.

I'm using your plugin with GLPI v9.5. Can I use Font Awesome v6 with it in any way?

Thanks in advance.

**Comment by btry** [comment]
Hi

You would need to try to upgrade font awesome in glpi and rebuild this project.

However I expect that several icons in GLPI will break, then I recommend you to wait until you upgrade to GLPI 10.
