### ISSUE TITLE
Feedback about formcreator and space characters

### ISSUE THREAD

**Issue by plburguet** [pluginsGLPI/formcreator#2757]
Hello,

I'm here to bring you an information on a case i encountered, i don't know if it can be classified as an issue or not.
Since the upgrade of our GLPI to 9.5.7 and formcreator to 2.12.4 (and also 2.12.5), the send button to create tickets wasn't working on some forms.
**No errors seen in any logs** from apache nor GLPI itself.
When you pressed "send", the form was acting like if you just refreshed the page, no ticket created.
i've been looking everywhere but I just found the issue.
In the forms concerned by the problem, I looked at every question and found out the problem.
In a question of type **selection**, i checked the different values, and i saw a little space right after one of the values
After removing it, the form was working again as intended.

So i came here to share that you must ensure that there are no spaces at all in values put on forms, if not you'll just have an unworking form.

(Also and tbh i have no way to verify that information but, i think the space was already there as no changes were done in years on that form and it was working with all the previous versions, before the upgrade we had the version 2.10.4. it really broke since 2.12.4)

Cheers,

**Comment by btry** [comment]
Hi

Is the debug mode of GLPI enabled ?

**Comment by plburguet** [comment]
Hi,
Yes it is. Logging level was set on 5 also

**Comment by btry** [comment]
Hi

Is your select question mandatory ?

**Comment by btry** [comment]
I could reproduce by cheating in  the database. Tha above fix should solve the issue.

Could you try it ? You need to edit a question directly in the database to add a trailing space in a value of a select question.

**Comment by plburguet** [comment]
> 

Hello,
yes it's mandatory, and also yes those forms are kinda old. 
Not sure how old though, i can tell that the first formcreator version installed was 2.6.3, i have no idea if 
So maybe this can only happen on old forms after upgrades ? Very specific situation then

i had another form with the same problem, there were trailing spaces, I just removed those and now it works.
I'll try to do the etst and come back at you

**Comment by plburguet** [comment]
Ok, i've been able to replicate this problem.
If i edit values from GLPI the trailing spaces are automatically removed.
But if I set the values with spaces directly in the database, it stays here and the form doesn't work when i select the choice with the trailing space

**Comment by btry** [comment]
Now apply the patch #2789. The form should behave as expected.

**Comment by btry** [comment]
Hi

Do you have feedback for  the patch ?

**Comment by plburguet** [comment]
Hello, I have applied the patch in abstractfield.class.php but it seems that didn't fix it.
It have the exact same behaviour  : when the choice in the dropdown list have the trailling space (added directly from the database), I click submit and it does not submit the ticket and only "refresh the page" (brings me back up at the beginning of the form)

**Comment by btry** [comment]
On my side the patch worked well. 

I recommend you to check if you have 2 copies of the plugin : one in plugins folder and an other in marketplace folder. This is a recurrent error. To solve it, drop the copy of Formcreator in plugins folder, and apply the patch again in the other copy in the marketplace folder.

**Comment by plburguet** [comment]
> On my side the patch worked well.
> 
> I recommend you to check if you have 2 copies of the plugin : one in plugins folder and an other in marketplace folder. This is a recurrent error. To solve it, drop the copy of Formcreator in plugins folder, and apply the patch again in the other copy in the marketplace folder.

Ah you're right ! thanks for that information, and yes the patch works now. :)

**Comment by btry** [comment]
Hi

Great, thank you for your  feedback.
