### ISSUE TITLE
[2.13.0alpha4] category form layout issue

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2759]
**Describe the bug**
glpi 10 +  plug in formcreator 2.13.0 alpha4
trouble with form categories layout :
1) sometimes blank in between
2) if title too long, it writes over the next title

**To Reproduce**

**Expected behavior**
harmonized layout

**Screenshots**
![glpi_menus](https://user-images.githubusercontent.com/78594318/167301648-7374ef43-e3d1-4cb9-8c18-440e0f5e6baa.jpg)

**GLPI / Plugins (please complete the following information):**
[2.13.0alpha4] 

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefo
**Smartphone (please complete the following information):**

**Comment by mirda123** [comment]
oups.. almost solved by the new plugin version 2.13.0.beta1 . 
Still a different lack of space when title too long (2 lines) but it's minor compared to previous version

![FC_image_display_solved](https://user-images.githubusercontent.com/78594318/167303006-5e07246a-e62e-497a-adf8-b810d19c104d.jpg)

**Comment by btry** [comment]
Hi

Try #2786 and feedback

**Comment by mirda123** [comment]
![space](https://user-images.githubusercontent.com/78594318/169700026-cd7bac71-fb3a-4c59-96db-7fa5d2bef442.jpg)


same

**Comment by btry** [comment]
Hi

Enable debug mode in glpi or recompile the CSS of the plugin

Command to recompile is bin/console glpi:plugin: formcreator:scss

**Comment by btry** [comment]
Hi
Having no fedback, I assume this is solved.
