### ISSUE TITLE
Hide Section

### ISSUE THREAD

**Issue by Alibaskins** [pluginsGLPI/formcreator#276]
It should be great to be able to hide a complete section (with all questions (requests)).

It should be more readable for the validator for example.

**Comment by OscarLoayzaB** [comment]
I agree with the idea.
In some cases, it is useful to hide the section of the form (with questions).
I wish to include this feature in the plugin.

**Comment by jstival** [comment]
Je pense également qu'il serait interessant de pouvoir faire comme pour les questions à savoir avoir la possibilité de cacher les sections et de les activer seulement si elles répondent à un critière.

Exemple pour un formulaire de commande d'un nouveau pc : 

Si le "type de pc" = "portable" alors on affiche une section "Accessoires" pour définir Sacoche, station d'accueil, etc... mais si "type de pc" = "Tour" alors on affiche rien !

**Comment by btry** [comment]
Hi

It is now possible to hide a section with a condition. I close this issue.
