### ISSUE TITLE
Nouvelles fonctionnalités dans les Formulaires

### ISSUE THREAD

**Issue by RdENIM** [pluginsGLPI/formcreator#277]
Bonjour à vous,

Pouvez vous m'en dire plus sur ce sujet ?

En vous remerciant d'avance,

Cordialement,

René Danilo

**Comment by btry** [comment]
Bonjour

# Présentation et unification avec la FAQ

Le plugin permet de ranger les formulaires dans des catégories. A partir de la version 0.90-1.4, les catégories peuvent être hiérarchisées comme le sont les entités ou les lieux.

Le plugin offre une nouvelle présentation pour l’utilisation des formulaires. Leur administration reste inchangée. La nouvelle présentation propose un moteur de recherche en langage naturel, qui explorera aussi bien les formulaires que les éléments de la FAQ. Cela permet aux utilisateurs de plus facilement trouver une réponse sans forcément solliciter le support, quand ce dernier entretient une FAQ.

L'unification des formulaires et de la FAQ passe par la mise à disposition de catégories de formulaires arborescent (comme les lieux ou les entités de GLPi). Les catégories de formulaires peuvent être associées à une catégorie de base de connaissance.

Sur la partie gauche vous trouverez une interface pour naviguer dans les catégories de formulaires (et par leur liens avec la base de connaissance, la FAQ également)

![image](https://cloud.githubusercontent.com/assets/14139801/19114646/22b8dd24-8b0f-11e6-883e-d3f191b64f64.png)

Au centre de la page vous trouverez le moteur de recherche et les résultats

![image](https://cloud.githubusercontent.com/assets/14139801/19114665/3858e458-8b0f-11e6-87e3-6db2a6be4203.png)

A droite, enfin, les formulaires récents, en tant que demandeur ou valideur (comme dans les versions précédentes)

![image](https://cloud.githubusercontent.com/assets/14139801/19114703/64874a2e-8b0f-11e6-947b-424f542ae55a.png)

# Catalogue de services

Le catalogue de service remplace l'interface simplifiée de GLPi pour offrir une expérience nouvelle utilisateur.  Il reprend le principe d'unification des formulaires et des éléments de la FAQ, et vise à unifier formulaires et tickets.

Vue pour créer une requête
![image](https://cloud.githubusercontent.com/assets/14139801/19115855/bf654294-8b13-11e6-914d-570ce3b5a74f.png)

Vues pour suivre les requêtes en cours
![image](https://cloud.githubusercontent.com/assets/14139801/19115861/c50a456e-8b13-11e6-9c13-51603549640a.png)

![image](https://cloud.githubusercontent.com/assets/14139801/19115868/cadea2b4-8b13-11e6-8baa-17ad7ca14cb7.png)

Il reste possible de consulter els flux d'information et réserver du matériel. Sur les captures d'écran précédentes ce sont les entrées du menu à gauche *Book an asset* et *Consult feeds*

**Comment by btry** [comment]
Pour activer le service catalog : avec un compte super admin éditez une entité et modifiez l'option de l'onglet *Formulaires*

![image](https://cloud.githubusercontent.com/assets/14139801/19115936/1752977c-8b14-11e6-9bec-2f2b63809086.png)

L'option prend en charge l'héritage d'une entité parent vers les entités enfant
![image](https://cloud.githubusercontent.com/assets/14139801/19115955/2bcd4fb2-8b14-11e6-9ee8-0c91d5d81682.png)

**Comment by RdENIM** [comment]
Bonjour à vous,

Parmi les derniers tests des formulaires avec validation créant un ticket, il m'a été demandé pour ceux qui créent les demandes via les formulaires de faire des recherches. Les éléments présentés ci-dessous semblent répondre à ce besoin ?

Une autre demande m'a été formulée, les utilisateurs qui ont saisis des formulaires souhaiteraient rajouter des colonnes pour l'affichage selon les critères de saisies qu'ils avaient. 
Cela leur permettrait de faire des recherches complémentaires à celles vues précédemment.

D'après vous est-ce possible ?

En vous remerciant d'avance,

Cordialement,

René Danilo

**Comment by btry** [comment]
Bonjour

Ceux qui crééent des formulaires peuvent faire utiliser le champ de recherche pour facilement trouver le ou les formulaires les plus appropriés. La recherche porte sur les noms et descriptions des formulaires.

Si vous utilisez beaucoup de formulaires (disons au moins 15 ou 20) il est bon d’utiliser les catégories de formulaires de manière arborescente. La recherche porte sur les formulaires de la catégorie courante. C'est à dire que si le demandeur s'enfonce dans l'arborescence des catégories, la recherche n'affichera pas les résultats des catégories en amont.

Il est aussi possible d'avoir un ou plusieurs formulaires "par défaut", qui s'afficheront si la recherche ne retourne aucun résultat.

A propos de l'ajout de colonnes pour afficher les formulaires selon plus de critères, cela n'a pas été prévu, car l'objectif visé est la simplification. Je vous invite à faire une demande de fonctionnalité à ce sujet si vous en avez besoin.

**Comment by RdENIM** [comment]
Bonjour à vous,

Je vais reprendre les tests. Pour la demande de fonctionnalité supplémentaire, je la fais dans ce forun ?

En vous remerciant d'avance,

Cordialement,

René Danilo

**Comment by btry** [comment]
Bonjour

Si vous voulez demander des fonctionnalités il faut faire un ticket par fonctionnalité, et si vous trouvez des bugs, un ticket par bug. N'oubliez pas de vérifier si un ticket équivalent existe avant de créer le vôtre (cela évite les doublons).

Pour information le plugin est passé en beta4; je vous invite à vous mettre à jour (et presser F5 sur le navigateur pour rafraichir votre cache).

**Comment by RdENIM** [comment]
Je viens de télécharger la beta4. Je refais une batterie de test entre cet après-midi et demain. Je regarde également l'aspect recherche de formulaire, une fonction très demandée dans notre établissement. Je vous fais un retour sur mes tests.
Autrement j'ai posté deux nouveaux tickets sur des fonctionnalités également très attendues chez nous.

**Comment by RdENIM** [comment]
Bonjour,

Je fais des tests à nouveau cette semaine.

Cordialement,

René Danilo

**Comment by RdENIM** [comment]
Bonjour à vous,

Concernant le catalogue de service, quand vous dites que celui-ci vise à unifier formulaires et tickets, il faut remettre à jour GLPI du coup ? Actuellement les tests réalisés entre formulaires et glpi nous sommes sur les versions suivantes : formulaire 0.90-1.4-beta4 et glpi 0.90.3.

En vous remerciant d'avance de votre retour,

Cordialement,

René Danilo

**Comment by RdENIM** [comment]
Dans un service (exemple de développement d'application), ceux qui ont fourni de demande de mise en production via un formulaire, veulent faire des recherches sur les champs des formulaires, est-ce possible du coup ?

**Comment by btry** [comment]
Le plugin est releasé, comaptible avec GLPI 0.90.

Ce sujet étant ancien et sans activité récente, je ferme.
