### ISSUE TITLE
[2.13.0-beta.1] Textarea

### ISSUE THREAD

**Issue by CDG47** [pluginsGLPI/formcreator#2774]
We can't see all the default content for the textarea element.
![firefox_PFnTm7LbgM](https://user-images.githubusercontent.com/11661365/167871111-31fc24de-74a5-4021-8b49-c53f152df940.png)
![firefox_LY0rBOsopL](https://user-images.githubusercontent.com/11661365/167871136-fec9e898-feba-4750-998e-c660724c702e.png)

**Comment by btry** [comment]
Hi

For some reason, TinyMCE sets a wrong height here. The fix is not obvious and may need time to find a soltion.

**Comment by btry** [comment]
Patch validated by reporter of #2818. Closing.
