### ISSUE TITLE
Champ 'glpi_plugin_formcreator_forms.plugin_formcreator_categories_id' inconnu dans on clause

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/formcreator#2776]
Bonjour, Sur GLPI V10.0.0 et FC 2.13.0-alpha.3, en allant sur Administration/Formulaires j'ai le message cité en objet qui s'affiche.

Aucun formulaires ne s'affichent,  pas de nouvelle version dans le marketplace

Le mode debug me renvoit cette information :

SQL Error "1054": Champ 'glpi_plugin_formcreator_forms.plugin_formcreator_categories_id' inconnu dans on clause in query "SELECT DISTINCT `glpi_plugin_formcreator_forms`.`id` AS id, '[MASQUE]' AS currentuser, `glpi_plugin_formcreator_forms`.`entities_id`, `glpi_plugin_formcreator_forms`.`is_recursive`, `glpi_plugin_formcreator_forms`.`name` AS `ITEM_PluginFormcreatorForm_1`, `glpi_plugin_formcreator_forms`.`id` AS `ITEM_PluginFormcreatorForm_1_id`, `glpi_plugin_formcreator_forms`.`is_active` AS `ITEM_PluginFormcreatorForm_30`, `glpi_plugin_formcreator_forms`.`description` AS `ITEM_PluginFormcreatorForm_4`, `glpi_plugin_formcreator_categories`.`name` AS `ITEM_PluginFormcreatorForm_10`, `glpi_plugin_formcreator_forms`.`helpdesk_home` AS `ITEM_PluginFormcreatorForm_8`, `glpi_plugin_formcreator_forms`.`language` AS `ITEM_PluginFormcreatorForm_7`, `glpi_plugin_formcreator_forms`.`access_rights` AS `ITEM_PluginFormcreatorForm_9` FROM `glpi_plugin_formcreator_forms`LEFT JOIN `glpi_plugin_formcreator_categories` ON (`glpi_plugin_formcreator_forms`.`plugin_formcreator_categories_id` = `glpi_plugin_formcreator_categories`.`id` ) WHERE `glpi_plugin_formcreator_forms`.`is_deleted` = 0 ORDER BY `ITEM_PluginFormcreatorForm_1` ASC LIMIT 0, 100"

**Comment by Sicoval31** [comment]
Même erreur :(
j'ai récupéré la 12.5 et copié (apres avoir désactivé le plugin) dans le dossier marketplace : erreur de version non compatible (logique)
même principe mais dans le dossier plugin : même résultat.
V2.1.0-beta-1 recuprée et copiée dans le dossier marketplace, passage des commandes SQL (pour le dashboard), puis de la commande CMD pour forcer la mise à jour.
V13.0 beta1 affichée dans le marketplace ; apres activation : message d'erreur identique

Je serai tenté de desinstaller, mais je vais vider toutes mes tables et références/liens avec mes formulaires existants et je vais pas refaire mes 30 formulaires ;)

**Comment by btry** [comment]
Ne  travaillez que dans le dossier marketplace ou plugins. Veillez à ne pas avoir uen copie du plugin dans les 2 dossiers à la fois.

Je n'aurais peut être pas dû parler du comportement d'upgrade à partir d'une version 2.12, c'était à titre informatif dans le contexte d'un uptgrade le jour d'une mise en production, et j'ai l'impression que vous avez pris cela pour une instruction.

Revenez en version 2.13.0-beta.1 et avant de procéder à l'upgrade, exécutez les requêtes SQL de ce message: https://github.com/pluginsGLPI/formcreator/issues/2681#issuecomment-1088759882. Enfin, procédez à l'upgrade forcé ```bin/console glpi:plugin:install formcreator -f -p force-upgrade```

**Comment by Sicoval31** [comment]
C’était un ancien dossier qui restait dans plugin, je l'ai supprimé pour éviter les problèmes.
C'est mieux avec le code SQL complet de l'issue 2681 (https://github.com/pluginsGLPI/formcreator/issues/2681)  j'ai désormais l'affichage de mes formulaires.
Il faudrait éventuellement rajouter un petit paragraphe concernant ce problème  sur la fiche de présentation de la dernière release ?

Merci encore pour cette aide précieuse et toujours aussi rapide
