### ISSUE TITLE
Affichage d'un ticket : item not found / élément introuvable

### ISSUE THREAD

**Issue by DeltatecAS** [pluginsGLPI/formcreator#2781]
Bonjour,

J'ai un gros souci. J'ai mis à jour ma version de GLPI et j'ai fatalement installé la V10. J'utilisais FormCreator et j'ai décidé d'installer la version beta (la dernière). J'ai effectué les différentes manipulations pour mettre à jour le plugin.

J'ai configuré le plugin comme suis ; 

![image](https://user-images.githubusercontent.com/77720940/169030012-218fe3cf-afcc-476f-acf2-b60982d11832.png)

Ce qui est génial c'est que tous mes formulaires sont bien présents. Je peux utiliser les formulaires pour créer un ticket, pas de soucis. Je peux créer des tickets normalement sans passer par le formulaire, pas de soucis.

Par contre, j'ai un souci plutôt embêtant. Le fait d'avoir activé FormCreator a créé des menus dans la partie de gauche de GLPI alors que je dis bien dans ma configuration que je veux l'assistance GLPI : 

![image](https://user-images.githubusercontent.com/77720940/169030483-c60f12fc-7d8c-45ed-8b37-d04d92bb2926.png)

Je voudrais ne pas avoir la partie "demandes d’assistance" car cela n'est pas utile vu que cela porte confusion car il est possible de visualiser tous les tickets via "Accueil" et soit "nouveau" ou "attribués"

![image](https://user-images.githubusercontent.com/77720940/169030850-e32bc7e3-1bb8-4a6e-8b8b-e23e857bbaf1.png)

Et j'en arrive à mon souci. Lorsque je passe par "Accueil" et ensuite "nouveau" que je clique sur un ticket (en tant qu'utilisateur avec interface simplifiée) j'obtiens cette erreur : 
 
![image](https://user-images.githubusercontent.com/77720940/169031427-426e8236-4b10-40e1-8ce5-099d1f7b11fe.png)

Je remarque comme intitulé de mon onglet : 

![image](https://user-images.githubusercontent.com/77720940/169031521-fdb1cea1-4f3d-47c4-a24a-2ae4304e07a2.png)

Et le menu à gauche qui a changé : 

![image](https://user-images.githubusercontent.com/77720940/169031578-8b570fdb-386d-461f-8c1a-e39430fa88e9.png)

Et si je désactive le plugin FormCreator, j'ai pas de soucis pour ouvrir ce même ticket, avec le même compte.

**Comment by btry** [comment]
Bonjour

Une modification a été introduite dans Formcreator 2.13. A partir du moment où le plugin est actif, le menu de GLPI est modifié pour passer par les formulaires et pas par les tickets. D'une certaine manière vous vous êtes évadés de ce que veut faire le plugin. J'ai besoin de faire quelques recherches pour voir comment résoudre cela.

**Comment by DeltatecAS** [comment]
D'accord. Ma société ne fait jamais comme tout le monde :D 

En fait on veut utiliser formcreator juste pour créer des formulaires qui permettent de créer des demandes.

**Comment by btry** [comment]
Sur mon instance je peux accéder à un ticket sans problème. Cependant c'est Formcreator qui prend la main pour l'afficher. J'ai besoin de voir l'URL correspondant à votre page "accès refusé".

**Comment by DeltatecAS** [comment]
Voici l'URL : http://servername/glpi/front/ticket.form.php?id=1469

Quand le clique sur un des tickets qui se trouve via le chemin que j'ai donné ci-dessus j'arrive sur cet url et du coup j'ai ce message d'erreur.

**Comment by btry** [comment]
Ce ticket n'a pas été généré par un formulaire de Formcreator ?

**Comment by DeltatecAS** [comment]
Non mais même ceux créé via un formulaire ça fait le même effet.

J'ai tenté de mettre le mode assistance en "catalogue simplifié" et lorsque je veux afficher les tickets via "mes demandes d'assistances" je n'ai aucun tickets

**Comment by DeltatecAS** [comment]
J'ai réglé mon erreur. C'était dû à la dernière beta. J'ai mis l'alpha et ça va mieux. Par contre dans "issue" j'ai rien du tout qui s'affiche dans la liste

**Comment by btry** [comment]
A mon avis votre table glpi_plugin_formcreator_issues a un problème.

Et les versions alpha sont obsolètes : vous avez rétrogradé en version.

>  Est ce qu'il y a moyen de cacher le menu "issue" dans le menu à gauche ?

Non. L'objectif est justement d'utiliser les formulaires quand le plugin est utilisé.

**Comment by DeltatecAS** [comment]
Sauf que le menu "issue" est sensé afficher les nouveau formulaires encodés ou ticket mais je n'ai que les anciens.

Et comment je peux faire pour réparer la table ? Et quelle version je dois prendre ?

**Comment by DeltatecAS** [comment]
Que puis-je faire ?

**Comment by DeltatecAS** [comment]
J'ai pris les devant et en fait j'ai exporté tous mes formulaires. J'ai supprimé totalement FormCreator. J'ai pris la dernière version Beta. J'ai réinstallé FormCreator. J'ai importé mes formulaires et tout semble redevenir à la normal sauf une seule chose :p Ca aurait été trop facile.

Quand je vais sur "Accueil" "nouveau"

![image](https://user-images.githubusercontent.com/77720940/169057925-526652fd-a449-45f6-bba0-f0ec8c1b90b4.png)

J'ai un souci avec la dashboard du dessus : 

![image](https://user-images.githubusercontent.com/77720940/169058125-a2b25fd9-84d3-460b-b9f2-212e3b332b08.png)

Du coup, je me souviens, ce que j'avais fait c'est que j'avais utilisé la commande d'update ect fourni avec le zip mais je n'ose pas le refaire car je pense que c'est ça qui a tout planté.

**Comment by btry** [comment]
Vous avez upgradé d'une Alpha vers une Beta. Lisez les notes de release de la versin Beta.2 pour faire migrer le dashboard.

Quelle est la commande d'update que vous avez utilisé ?

**Comment by DeltatecAS** [comment]
Bonjour,
Désolé pour le laps de temps. Merci en tout cas pour vos réponses.

Voici la ligne de commande : php bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade

J'ai peur que si je l'utilise les bugs réapparaissent.

**Comment by btry** [comment]
Bonjour

La commande rejoue l'uptgrade du plugin depuis la version mineure précédente jusqu'à la version actuelle. Dans votre cas : 2.12.0 vers 2.13.0-beta.2 (si c'est bien  cette version qui est installe).

Pour le moment je n'ai pas connaissance de problème sur l'upgrade des demandes d'assistance, hormis un problème de performance qui est déjà résolu. Avec quelques milliers de téléchargements des versions de test et aucun retour récent sur des demandes d'assistance erronées ou manquates, je ne pense pas qu'il y ait de souci. 

De toute façon vous utilisez bien un GLPI dédié aux tests ? Une version beta n'est pas recommandée pour une mise en production.

Vous pouvez faire un backup de la base de données avant de lancer la commande. Notez égalemetn qu'elle ne réalise pas les actions d'upgrade du dashboard comme décrit dans les notes de releases. C'est intentionnel car en situation normale (production) personne n'est supposé upgrader d'une version de développement à une autre.

**Comment by DeltatecAS** [comment]
D'accord, je comprends bien.

Mais dans ce cas-ci je n'ai pas fait d'upgrade de FormCreator vu que j'ai désinstallé complètement le plugin (donc plus de formulaire et plus rien), et j'ai installé la dernière beta. Et malgré cela j'ai le souci d'affichage de la dashboard.

Quel est la procédure dans ce cas vu que la commande c'est pour en cas de mise à jour du plugin

**Comment by btry** [comment]
Je viens de faire un  test de désinstallation et réinstallation du plugin, et le dashboard s'affiche correctement.

Le problème initial étant résolu, il faut faire une nouvelle issue et fermer celle ci (pour la lisibilité et faciliter le suivi).  Au moment de la rédiger, ajoutez les erreurs PHP et SQL que vous pourriez trouver dans glpi/files/_log/php-errors.log et /files/_log/sql-errors.log.

En attendant je fais une vérification supplémentaire.
