### ISSUE TITLE
Error message - 2.13.0-beta.2

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2784]
**Describe the bug**
Error message is presented when opening a new ticket through the simplified interface

When requesting a new ticket through the form, I get an error message as shown in the gif below
![error-new-ticket](https://user-images.githubusercontent.com/35368369/169171574-82cb3542-82a4-433e-a86d-91d7b6672e93.gif)

erros in php-errors.log

[2022-05-18 20:25:55] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /home/paulo/teste.myserver.com.br/glpi/plugins/formcreator/inc/abstractitiltarget.class.php at line 2226
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:934 PluginFormcreatorAbstractItilTarget->prepareUploadedFiles()
  plugins/formcreator/inc/formanswer.class.php:865   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:1086  PluginFormcreatorFormAnswer->generateTarget()
  src/CommonDBTM.php:1275                            PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:140        CommonDBTM->add()

**Comment by btry** [comment]
Hi

It seems the bug is related to the question of type file. 

I'll try to reproduce in a few hours. In the mea time, what happens if you try to add a file in the question ? Do the error persist?

**Comment by btry** [comment]
Please try the above fix and feedback

**Comment by phamorais** [comment]
@btry 

After applying the aforementioned improvement, the error was resolved. Thanks

**Comment by btry** [comment]
Hi

Thanks for your feedback
