### ISSUE TITLE
 [GLPI 10] Unable to view closed tickets on self-service profile

### ISSUE THREAD

**Issue by Wacxiuz** [pluginsGLPI/formcreator#2787]
**Describe the bug**
Hello,
Users create tickets which we process. Once processed, we close them directly.
Our users use the "SELF SERVICE" profile with default group permissions.
However, the problem is this:
Users cannot see the content of closed tickets, even though they are in the requester box.
The list is well displayed, but when they click on the closed tickets, there is a gray page.

**To Reproduce**

    Close a ticket
    Attempt to read the self-service content there
    See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83710370/169237626-dbc00446-4c79-4b08-b245-d34ca3e0747c.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10
- list of all plugins :
        news                 Name: Alertes                        Version: 1.10.2     State: Enabled
	screenshot           Name: Capture d'écran                Version: 2.0.0      State: Not installed
	fields               Name: Champs supplémentaires         Version: 1.15.0     State: Enabled
	behaviors            Name: Comportements                  Version: 2.6.0      State: Installed / not activated
	datainjection        Name: Data Injection                 Version: 2.11.1     State: Enabled
	escalade             Name: Escalades                      Version: 2.8.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.13.0-beta.2 State: Enabled
	fusioninventory      Name: FusionInventory                Version: 10.0.0+1.0 State: Enabled
	geninventorynumber   Name: Génération de numéros d'invent Version: 2.5.0      State: Not installed
	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.0      State: Not installed
	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.2      State: Installed / not activated
	metabase             Name: metabase                       Version: 1.2.2      State: Not installed
	reports              Name: Rapports                       Version: 1.14.0     State: Not installed

**Comment by Wacxiuz** [comment]
+ error /files/_log/php-error:

[2022-05-19 09:38:43] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Object of class Ticket could not be converted to string in /var/www/glpi/src/CommonDBTM.php at line 295
  Backtrace :
  src/CommonDBTM.php:2903                            CommonDBTM->getFromDB()
  src/CommonDBTM.php:2655                            CommonDBTM->check()
  src/CommonDBTM.php:483                             CommonDBTM->initForm()
  marketplace/formcreator/inc/issue.class.php:387    CommonDBTM->showForm()
  marketplace/formcreator/inc/issue.class.php:293    PluginFormcreatorIssue->displaySimplified()
  marketplace/formcreator/front/issue.form.php:89    PluginFormcreatorIssue->display()

**Comment by btry** [comment]
Hi
Please  try the above fix and feedback

**Comment by Wacxiuz** [comment]
Hello,
It's okey !

Thanks
