### ISSUE TITLE
Mail Notification

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/formcreator#279]
Opened by error as PR #251 by @mozes34
Hi,

I Have a problem with mail notification. When I select "Email followup" : **No**, when I create a new ticket with the form I have "Email followup" : **Yes** select in.

Can You fix it ?

Thank You

**Comment by btry** [comment]
The pending PR #311, would affect a fix for this issue. I think we should wait for the merge to see if the issue disappears. If not, then we can investigate.

**Comment by btry** [comment]
to check with #456

**Comment by btry** [comment]
Hi I close as it is way too old now. I assume this is fixed. If not on the latest version, please open a new issue.
