### ISSUE TITLE
if a validator is chosen it says missing validator when the submit button is pressed formcreator 2.13.0-beta.2

### ISSUE THREAD

**Issue by bolivarf** [pluginsGLPI/formcreator#2791]
Hello
I have a form for which a validator is required for the requesting entity, the form has the message Do you need validation? -> User > user lists

but when i enter the data one hand it is weird that the validator request is after the submit button and secondly even if a validator is chosen it says missing validator when the submit button is pressed so that the form cannot be completed.

**To Reproduce**
1. create a formulator
2. add a list of validators
3. choose preview
4. select a validator
5. press send
6. See error

**Expected behavior**
answers the form by choosing a validator
**Screenshots**
![image](https://user-images.githubusercontent.com/7965864/169293758-55509133-de51-4ed2-8261-3db53623cba9.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0
- list of all plugins
Form Creator formcreator 2.13.0-beta.2
GLPI Inventory glpiinventory 1.0.0
More Reports mreporting 1.8.0 GPLv2+

**Desktop**
       - OS: Ubuntu 22.04 (in another OS the same thing happens)
       -Google Chrome Version 101.0.4951.64

**Comment by btry** [comment]
Hi

I'm searching a way to move the validator dropdown above the submit button.

**Comment by btry** [comment]
Try the above fix and feedback.

**Comment by bolivarf** [comment]
@btry  make the changes to the 3 indicated files and it seems to solve the problem.

**Comment by btry** [comment]
Merged. Thank you for your feedback.
