### ISSUE TITLE
Mini Dashboard dans la vue des tickets sous le menu "Accueil" & affichage de nouveaux tickets sous "Demandes d'assitance"

### ISSUE THREAD

**Issue by DeltatecAS** [pluginsGLPI/formcreator#2794]
Bonjour,

J'ai réinstallé fraichement FormCreator et j'ai importé mes formulaires de mon ancienne version.

Tout semble fonctionner correctement sauf : 

* la mini dashboard qui se trouve sous tous les menus dans la partie "Accueil". Donc ceux-là : 
![image](https://user-images.githubusercontent.com/77720940/169526750-dcec1d0e-d84e-437b-9382-0f1e57c33cb0.png)

J'obtiens ceci : 

![image](https://user-images.githubusercontent.com/77720940/169526779-153a52b0-866b-4145-b40e-09679b43c192.png)

**Comment by btry** [comment]
Bonjour

Cela fait 2 problèmes distincts. 1 problème = 1 issue.

Gardons cete issue pour le dashboard, et créez en une autre pour les tickets qui n'apparaissent pas.(avec une procédure complète pour reproduire le souci : comment créer un formulaire pour reproduire, extrait de log des erreurs qui sont en relation avec le souci).

Pour le problème de dashboard Avez vous trouvé des erreurs dans les logs de GLPI ?

**Comment by DeltatecAS** [comment]
Non je n'ai rien trouvé. La seule chose que j'ai dans le log c'est ceci : 

[2022-05-20 13:45:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function getAllDatasFromTable() in /usr/share/glpi/plugins/notifications/hook.php at line 137
  Backtrace :
  src/Plugin.php:1448                                plugin_notifications_item_get_datas()
  src/NotificationTarget.php:1319                    Plugin::doHook()
  src/NotificationTemplate.php:276                   NotificationTarget->getForTemplate()
  src/NotificationEventAbstract.php:125              NotificationTemplate->getTemplateByLanguage()
  src/NotificationEvent.php:185                      NotificationEventAbstract::raise()
  src/TicketSatisfaction.php:187                     NotificationEvent::raiseEvent()
  src/CommonDBTM.php:1275                            TicketSatisfaction->post_addItem()
  src/Ticket.php:6029                                CommonDBTM->add()
  src/CronTask.php:1016                              Ticket::cronCreateInquest()
  front/cron.php:82                                  CronTask::launch()

**Comment by DeltatecAS** [comment]
J'ai retiré le plugin Notifications et je vais signaler sur leur github le bug en question.

Par contre malgré tout ma dashboard via le chemin expliqué ci-dessus ne fonctionne pas.

**Comment by DeltatecAS** [comment]
Même si ce n'est pas un upgrade mais un nouvelle installation ? 

La dernière fois que j'ai utilisé cette commande ça à tout fait planter...

**Comment by btry** [comment]
j'avais oublié que vous avez réinstallé. Essayez quand même, ca ne présente pas de risque particulier

**Comment by DeltatecAS** [comment]
Alors, quand je fais le delete dans la DB je n'ai plus de dashboard. Plus du tout, même si je l'ai activé.

Et lorsque je fais la commande : php bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade

La dashboard revient mais avec le problème d'affichage...

**Comment by DeltatecAS** [comment]
J'ai supprimé à nouveau le plugin FormCreator.

J'ai remis FormCreator. J'ai uploadé les formulaires (bon ça à un peu foiré car j'ai modifié des choses entre temps donc voilà mais soit). J'ai exécuté la requête SQL et je n'ai pas fait la commande PHP pour l'update.

Du coup je n'ai pas les soucis ci-dessus, et comme je n'ai pas la dashboard bhen j'ai pas de soucis non plus :p Mais du coup j'ai plus de dashboard.

**Comment by btry** [comment]
Bonjour

Je ne peux pas suivre le fil si vous essayez plein de cheminements différents. 

J'ai fait une correction hier dans le processus d'upgrade vers 2.12.5, qui peut échouer dans le contexte d'un upgrade vers 2.13.0. Le problème que j'ai trouvé pourrait se manifester dans votre scénario d'upgrade.

[glpi-formcreator-2.13.0-dev.zip](https://github.com/pluginsGLPI/formcreator/files/8760484/glpi-formcreator-2.13.0-dev.zip)

Essayons de repartir sur une base stable car sans cela je ne pourrai pas vous aider. 

Installez la version de Formcreator ci dessus (dernière révision en date de ce matin), avec une installation fraîche. N'importez pas vos formulaires, focalisons sur votre souci de dashboard. Après l'installation, activez le catalogue de services,  arrangez vous pour y accéderdepuis un compte super-admin (ajouter le profil self service à glpi suffit), activez le mode debug de GLPI, et passez en profil self service pour accéder au dashboard.  Prenez une capture d'écran du dashboard.

Si il ne fonctionne pas, ouvrez les outils de développeur de votre navigateur, rafraichissez la page. Cherchez les requêtes vers dashboard.php et cliquez sur la dernière trouvée.

LEs captures ci dessous sont faites avec Brave. Ce sera identique avec n'importe quel navigateur basé sur Chrome / Chromium.

![image](https://user-images.githubusercontent.com/14139801/169978607-674c1ff3-0ee5-4c50-a710-3666006b1677.png)

Vérifiez que le code HTTP de réponse est 200 (onglet Headers)
![image](https://user-images.githubusercontent.com/14139801/169978734-a1f20759-8376-474a-8b5c-95b9a5c80e9b.png)


Dans l'onglet "réponse" sélectionnez tout le texte et enregistrez le dans un fichier pour le déposer ici

![image](https://user-images.githubusercontent.com/14139801/169979098-0ac27b3b-f26b-4aa4-ba27-a0ce197285af.png)

**Comment by DeltatecAS** [comment]
Désolé, je voulais juste tester que juste avec la requête sql on arrivait à une solution stable.

Donc j'ai fait tout ce que vous avez dit et voici la capture d'écran : 

![image](https://user-images.githubusercontent.com/77720940/169983165-acd311af-7049-44b9-a390-5e1a595e7a9c.png)

Le souci est toujours là. 

J'ai vu dans l'outil développer déjà ceci : 

jquery.jss:4059 Uncaught ReferenceError: Dashboard is not defined
    at HTMLDocument.<anonymous> (ticket.php:1413:10)
    at mightThrow (jquery.jss:3766:1)
    at process (jquery.jss:3834:1)
    
Ensuite quand je suis vos print : 

![image](https://user-images.githubusercontent.com/77720940/169984991-006c2b5d-eacc-4fc3-bfc6-d14af91f878a.png)

Je n'ai pas de dashboard.php

**Comment by btry** [comment]
> Donc j'ai fait tout ce que vous avez dit et voici la capture d'écran :

(image)

Déjà les spinners devraient être disposés à l'horizontale, et  en service catalog, il ne devrait pas y avoir d'icone pour modifier les cartes du dashboard.

> J'ai vu dans l'outil développer déjà ceci :

(image)

On dirait que vous avez un souci avec votre GLPI. Etes vois bien ave cla release finale 10.0.0 ?

> Ha et visiblement on ne sait plus accéder aux formulaires :

Avez vous bien activé Formcreator ?

**Comment by btry** [comment]
Le 1er paramètre "mode d'assistance" doit être positionné sur "catalogue de service" Simplifié ou étendu, peu importe. Sans cela le dashboard de Formcreator ne sera pas utilisé.

Je soupçonne que votre souci de dashboard soit indépendant de Formcreator étant donné que vous n'avez pas activé le catalogue de services.

**Comment by btry** [comment]
Ce ticket a pour but d'identifier  et résoudre un éventuel bug, donc si on veut trouver quelque chose en lien avec le dashboard de Formcreator il faut passer par là, au moins provisoirement.

Si cela est un obstacle, ne je vois pas mieux que  fermer ce ticket à défaut de pouvoir chercher puis résoudre votre problème.

**Comment by DeltatecAS** [comment]
Mais... 

Je pense que vous n'avez pas compris alors. Le problème se situe lorsque je vais dans "Accueil/Nouveau" (ou tout autre choix dans "Accueil"). Donc, si je mets en mode "catalogue de service" je n'aurai plus accès à cette partie. Il est donc logique que du coup il n'y ait plus le souci vu que je n'y ait plus accès... 

La dashboard fonctionne bien dans le menu "demandes d'assistance" enfin quand j'y avais accès avant la version que vous m'avez donné ici qui ne me permet pas de coupler les deux.

**Comment by btry** [comment]
Donc comme je le pense depuis hier, il est très probable que votre souci concerne un dashboard qui ne fait pas partie de ce plugin.

**Comment by DeltatecAS** [comment]
Sauf que lorsque je désinstalle le plugin FormCreator je n'ai pas le souci. Je n'ai même pas de Dashboard à cet endroit

**Comment by btry** [comment]
Je vous recommande de souscrire à du support pour pouvoir qu'un technicien puisse faire des investigations via téléphone et / ou assistance à distance + accès au serveur.

**Comment by DeltatecAS** [comment]
Si tel est le cas, expliquez moi pourquoi lorsque je fais ceci : 

DELETE
FROM glpi_dashboards_items
WHERE dashboards_dashboards_id = (
	SELECT id
	FROM glpi_dashboards_dashboards
	WHERE `key`='plugin_formcreator_issue_counters'
);

DELETE FROM glpi_dashboards_dashboards WHERE `key`='plugin_formcreator_issue_counters';

Je n'ai plus de problèmes ???

**Comment by btry** [comment]
On piétine depuis 2 jours pour essayer de cerner votre souci. Il y a certainement  des informations indispensables qui ne sont pas portées à ma connaissance.  Pour les trouver il faut chercher en passant par des outils que je ne peux utiliser en support communautaire.
