### ISSUE TITLE
Affichage de nouveaux tickets sous "Demandes d'assitance"

### ISSUE THREAD

**Issue by DeltatecAS** [pluginsGLPI/formcreator#2795]
Bonjour,

Les nouveaux tickets que je créé (que ce soit via FormCreator ou via le ticket normal de glpi) n'apparaissent pas sous le menu "Demande d’assistance". En effet, je n'ai que les anciens tickets créés avant l'installation du plugin FormCreator. Les nouveaux apparaissent bien par contre sous le menu "Accueil/Nouveau".

Petite précision, ce problème n'apparait que pour un profil avec l'interface simplifiée.

Merci pour votre travail en tout cas !

**Comment by btry** [comment]
L'utilisateur qui tente de voir les tickets est il un acteur de ce dernier ? (Demandeur observateur, technicien ou auteur)

**Comment by DeltatecAS** [comment]
C'est l'auteur des tickets.

**Comment by btry** [comment]
Bonjour

Connectez vous en super admin, et dans la partie conceptin des formulaires, ouvrez le formulaire qui a été utilisé, et ouvrez l'onglet "Réponses aux formulaires". Trouvez la réponse correspondant à votre cas, et notez l'identifiant de cette réponse.

Ensuite il faut chercher en bdd une ligne dans glpi_plugin_formcreator_issues. Cette ligne dépend du nombre de tickets générés par le formulaire. Combien de tickets ont été générés ?

**Comment by DeltatecAS** [comment]
Dans "Demandes d'assistances" je vois TOUS les tickets ANCIENS qui ont étés créés par l'utilisateur même ceux qui ne sont pas créés par FormCreator. 

Ce qui est problématique c'est le fait que lorsque je créé un nouveau ticket (sans passer par FormCreator) je ne les vois pas

**Comment by btry** [comment]
La liste des demandes d'assistance est une liste construite de manière complexe. Il faut vérifier dans la table glpi_plugin_formcreator_issues si les données sont correctes en s'appuyant sur quelques cas choisis. 

Vous avez dit que les tickets créés via formcreator n'apparaissent pas non plus. 

> nouveaux tickets que je créé (**que ce soit via FormCreator** ou via le ticket normal de glpi) n'apparaissent pas sous le menu "Demande d’assistance". 

Commençons par ce cas.

**Comment by DeltatecAS** [comment]
Je viens de vérifier justement et j'ai constaté que mon ticket créé par formcreator s'est bien affiché, mais j'avais un autre souci que j'ai réglé. Désolé pour cette mauvaise information. C'est donc bien uniquement les tickets créé par le système GLPI que je ne vois pas

**Comment by btry** [comment]
Suivez les instructions ici https://github.com/pluginsGLPI/formcreator/issues/2795#issuecomment-1134296542

**Comment by DeltatecAS** [comment]
C'est bon, on peut clôturer ce bug... 

Le problème c'est le plugin NOTIFICATIONS

Il faut pas l'installer :D 

Comme ça vous savez

Par contre mon bug de dashboard est toujours là

**Comment by btry** [comment]
Si le plugin notification pose de tels problèmes, il présente peut être des bugs qui réclament des corrections. Il faut les signaler (vérifiez bien les logs car il vaut mieux décrire les bugs via des erreurs enregistrées dans les logs, plutôt que les effets indésirables sur un autre plugin).

**Comment by DeltatecAS** [comment]
D'accord. Par contre, une question rien à voir mais je profite de votre disponibilité, est ce qu'on sait changer la présentation de la liste des issues dans le menu "Demandes d'assistances" ? Je voudrais retirer la colonne "ID" par exemple.

**Comment by btry** [comment]
il faut modifier les préférences d'affichage de la liste. Cela est possible depuis la partier administration des formulaires. Un icone permet d'acéder à la liste des demandes d'assistance. Ensuite modifiez les préférences comme pour n'importe quelle liste, de manière globale..

**Comment by DeltatecAS** [comment]
Excellent merci pour tout !
