### ISSUE TITLE
Error to change to request

### ISSUE THREAD

**Issue by wc55** [pluginsGLPI/formcreator#2799]
**Describe the bug**
Good Morning

After changing the incident to request type in the target properties of a form, the change is not saved.

**To Reproduce**
1. Go to 'Administration' >> 'Forms'
2. Click on a 'Forms'
3. Click on a form
4. Scroll down to 'Targets'
5. Click on 'Add a target' and add
6. Click on created target
7. Click on 'Properties'
8. Change type to 'Request'
9. Click on 'Save'
10. The message confirm the action, but the change is not saved

**Expected behavior**
The type should be changed for request

**Screenshots**
![image](https://user-images.githubusercontent.com/106084399/169832742-3427ed23-5b49-4280-9b66-3bdf9ef6eb91.png)

>>
![image](https://user-images.githubusercontent.com/106084399/169842018-8e399acf-5c02-45c3-9443-1e7d9955aa2d.png)

>>

![image](https://user-images.githubusercontent.com/106084399/169842346-adbb149b-a606-458b-96fc-0f4421e4a10f.png)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.0
- Form Creator 2.13.0-beta.1. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [chrome]

**Additional context**
I'm studying GLPI for deployment, and initially, only requests would be opened

**Comment by btry** [comment]
Hi

Check if this persists with 2.13.0-beta.2

**Comment by btry** [comment]
Hi,

Fixed. Thank you for your feedback.

**Comment by wc55** [comment]
The error continues, but I will do additional tests in another environment. Thank you

**Comment by wc55** [comment]
> Oi,
> 
> Fixo. Obrigado pelo seu feedback.

The error continues, but I will do additional tests in another environment. Thank you

**Comment by btry** [comment]
Hi

did you apply the patch #2800 ?

**Comment by btry** [comment]
Hi

Having no feedback, I close.
