### ISSUE TITLE
Validator gets all forms displayed

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/formcreator#280]
Openend by error as PR #243 by @flo1994

If a ticket has been accepted or refused by validator, the validator is redirected to the following page:

http: //ticket01/glpi/plugins/formcreator/front/formanswer.php

The validator sees all forms here.
Also these, where he is not selected as validator. This may not be the case with us....

Only the forms of the validator may be displayed. Is it possible?

**Comment by btry** [comment]
This issue duplicates #245

**Comment by btry** [comment]
solved in version 0.90-1.4-beta4
