### ISSUE TITLE
Liste de choix de question vide dans ticket cible pour "groupe/lieu depuis le formulaire"

### ISSUE THREAD

**Issue by magicpower77** [pluginsGLPI/formcreator#2807]
**Describe the bug**
Dans ticket cible quand il faut associer une question dans l'onglet Propriétés ou Acteurs le champs liste est vide voir capture ci-jointe

**To Reproduce**
1. Go to 'Administration > Formulaires > Sélectionner un formulaire > Onglet Cibles > Sélectionner la cible >Onglet Propriétés  puis  choisir Lieux égale à la réponse à la question le champs de sélection d'une question est vide'
2.  Le problème est identique pour Acteurs > Demandeur > + (Ajouter) > Groupe depuis la question -> Le champ de selection de la question est vide avec un message informations à renseigner

**Screenshots**
![bug-formcreator-glpi10](https://user-images.githubusercontent.com/106238522/170274284-983baf5f-9a8b-4712-a39e-b529f971498a.jpg)
![bug2-formcreator-glpi10](https://user-images.githubusercontent.com/106238522/170274305-493ef516-8694-474b-bb9f-c2ee5d739f79.jpg)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10
![glpi-plugins](https://user-images.githubusercontent.com/106238522/170274377-80a2626d-ad3d-4593-a007-d51716a02519.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 91.8

**Comment by btry** [comment]
Bonjour

Normalement c'est déjà corrigé par le commit https://github.com/pluginsGLPI/formcreator/commit/6ad92e9ad880eec3ee121205a554e481f76fa17b . 

Appliquez-le et dites si cela a fonctionné.

**Comment by btry** [comment]
Vous avez reporté 2 problèmes dans un seul ticket. Pensez à créer un ticket par problème car les sujets compliqués seront difficiles à suivre quand 2 conversations sont entremêlées.

Je cherche ce qu'il se passe pour les acteurs.

**Comment by btry** [comment]
Au niveau des acteurs, je ne reproduis pas de problème. Si j'ai une qustion de type Objet GLPI / Groupe, elle peut être sélectionnée pour un acteur de type "groupe depuis une question".

Dans votre cas, vous avez déjà ajouté une question de type Objet GLPI / Groupe dans vos demandeurs. Elle n'est donc plus proposée pour un nouvel ajout.

J'ai par contre trouvé un problème pouvant provoquer le mauvais enregistrement d'un groupe depuis une question. Ajoutez ce fix: baf9c042ae5102c6f1e66c44dc66ca305265ca34
