### ISSUE TITLE
Message d'erreur indiquant champ obligatoire vide à la validation d'un formulaire

### ISSUE THREAD

**Issue by magicpower77** [pluginsGLPI/formcreator#2808]
Describe the bug
Lors de la validation d'une demande par un formulaire malgré la selection d'un ordinateur dans la liste un message d'erreur indiquant qu'un champ obligatoire est vide. Type de question Objet GLPI  / Parc- Ordinateur voir capture ci-jointe

To Reproduce

Go to 'Assistance > Formulaires > Sélectionner un formulaire > Puis remplir un formulaire contenant une question avec objet GLPI < Parc- Ordinateur'.

Avant  clic sur bouton envoyer:

![bug3-formcreator-glpi10](https://user-images.githubusercontent.com/106238522/170477731-24534a8b-57af-4f0b-9944-53c6fb0703d5.jpg)

Après clic sur le bouton envoyer avec le message d'erreur:

![bug4-formcreator-glpi10](https://user-images.githubusercontent.com/106238522/170478414-75c0f4dc-9488-4ee3-a001-9bd442e67432.jpg)

GLPI / Plugins (please complete the following information):

![glpi-plugins](https://user-images.githubusercontent.com/106238522/170477868-651c31cc-e935-4022-81c4-c6bcf2def96f.jpg)

Desktop (please complete the following information):

    OS: Windows 10
    Browser Firefox
    Version 91.8

**Comment by btry** [comment]
Bonjour

Quelle version de Formcreator ? Je ne reproduis pas avec 2.13.0-beta.2 ou la dernière révision.

**Comment by magicpower77** [comment]
C'est la version 2.13.0-beta.2

**Comment by btry** [comment]
Vérifiez si il y a des erreurs dans sql-errors.log ou php-errors.log.

**Comment by btry** [comment]
Bonjour

Cette erreur SQL n'a rien à voir avec le souci initial. Vous avez probablement eu un souci d'upgrade dans le passé car **validator_id** n'existe plus. Détruisez la table glpi_plugin_formcreator_issues puis recreéez la à partir de la requête CREATE TABLE présente dans **install/mysql/plugin_formcreator_empty.sql**.  Enfin resynchronisez le contenu de la table avec la commande **bin/console glpi:plugins:formcreator:syncissues**

**Comment by magicpower77** [comment]
Bonjour
,
J'ai bien fait les manip mais lors de la commande  bin/console glpi:plugins:formcreator:syncissues j'ai ce message d'erreur:

PHP Compile Error (64): Cannot declare class GlpiPlugin\Formcreator\Command\SyncIssuesCommand, because the name is already in use in /var/www/html/prod/glpi/plugins/formcreator/inc/inc/command/syncissuescommand.class.php at line 39

**Comment by btry** [comment]
Vous avez certainement 2 copies du plugin : vérifiez les dossiers marketplace et plugin.

**Comment by magicpower77** [comment]
J'ai une erreur avec la synchro. 

![error sql](https://user-images.githubusercontent.com/106238522/172389862-c5fae8bf-5260-4040-aeac-c7e825f497a7.png)

**Comment by btry** [comment]
remplacez l'image par le texte. Sans cela, je ne peux pas récupérer la requête SQL

**Comment by magicpower77** [comment]
SQL Error "1136": Column count doesn't match value count at row 1 in query "INSERT INTO `glpi_plugin_formcreator_issues` SELECT * FROM ((SELECT DISTINCT NULL as `id`, IF(`glpi_plugin_formcreator_formanswe                                                                                              rs`.`name` = '', CONCAT('(', `glpi_plugin_formcreator_formanswers`.`id`, ')'), `glpi_plugin_formcreator_formanswers`.`name`) as `name`, CONCAT('f_', `glpi_plugin_formcreator_formanswers`.`id`) as `display_id`, `glpi_pl                                                                                              ugin_formcreator_formanswers`.`id` AS `items_id`, 'PluginFormcreatorFormAnswer' as `itemtype`, `glpi_plugin_formcreator_formanswers`.`status` AS `status`, `glpi_plugin_formcreator_formanswers`.`request_date` AS `date_c                                                                                              reation`, `glpi_plugin_formcreator_formanswers`.`request_date` AS `date_mod`, `glpi_plugin_formcreator_formanswers`.`entities_id` AS `entities_d`, `glpi_plugin_formcreator_formanswers`.`is_recursive` AS `is_recursive`,                                                                                               `glpi_plugin_formcreator_formanswers`.`requester_id` AS `requester_id`, `glpi_plugin_formcreator_formanswers`.`users_id_validator` AS `users_id_validator`, `glpi_plugin_formcreator_formanswers`.`groups_id_validator` A                                                                                              S `groups_id_validator`, `glpi_plugin_formcreator_formanswers`.`comment` AS `comment`, `glpi_plugin_formcreator_formanswers`.`requester_id` AS `users_id_recipient`, NULL as `time_to_own`, NULL as `time_to_resolve`, NUL                                                                                              L as `internal_time_to_own`, NULL as `internal_time_to_resolve`, NULL as `solvedate`, NULL as `date`, 0 as `takeintoaccount_delay_stat` FROM `glpi_plugin_formcreator_formanswers` LEFT JOIN `glpi_plugin_formcreator_form                                                                                              s` ON (`glpi_plugin_formcreator_forms`.`id` = `glpi_plugin_formcreator_formanswers`.`plugin_formcreator_forms_id`) LEFT JOIN `glpi_items_tickets` ON (`glpi_items_tickets`.`items_id` = `glpi_plugin_formcreator_formanswe                                                                                              rs`.`id` AND `glpi_items_tickets`.`itemtype` = 'PluginFormcreatorFormAnswer') GROUP BY `glpi_plugin_formcreator_formanswers`.`id` HAVING COUNT(`glpi_items_tickets`.`tickets_id`) != 1) UNION (SELECT DISTINCT NULL as `id                                                                                              `, IF(`glpi_tickets`.`name` = '', CONCAT('(', `glpi_tickets`.`id`, ')'), `glpi_tickets`.`name`) as `name`, CONCAT('t_', `glpi_tickets`.`id`) as `display_id`, `glpi_tickets`.`id` AS `items_id`, 'Ticket' as `itemtype`, I                                                                                              F(`glpi_ticketvalidations`.`status` IS NULL,  `glpi_tickets`.`status`,  IF(`glpi_tickets`.`global_validation` IN ('1', '3'),  `glpi_tickets`.`status`,  IF(`glpi_tickets`.`status` IN ('5', '6'),  `glpi_tickets`.`status`                                                                                              ,  IF(`glpi_tickets`.`global_validation` = '2',  '101',  '102'  )  )  )  ) AS `status`, `glpi_tickets`.`date` AS `date_creation`, `glpi_tickets`.`date_mod` AS `date_mod`, `glpi_tickets`.`entities_id` AS `entities_id`,                                                                                               0 as is_recursive, COALESCE(`glpi_tickets_users`.`users_id`, 0) as `requester_id`, COALESCE(`glpi_ticketvalidations`.`users_id_validate`, 0) as `users_id_validator`, 0 as groups_id_validator, `glpi_tickets`.`content` A                                                                                              S `comment`, `users_id_recipient` AS `users_id_recipient`, `time_to_own` AS `time_to_own`, `time_to_resolve` AS `time_to_resolve`, `internal_time_to_own` AS `internal_time_to_own`, `internal_time_to_resolve` AS `intern                                                                                              al_time_to_resolve`, `solvedate` AS `solvedate`, `date` AS `date`, `takeintoaccount_delay_stat` AS `takeintoaccount_delay_stat` FROM `glpi_tickets` LEFT JOIN `glpi_items_tickets` ON (`glpi_items_tickets`.`tickets_id` =                                                                                               `glpi_tickets`.`id` AND `glpi_items_tickets`.`itemtype` = 'PluginFormcreatorFormAnswer') LEFT JOIN (SELECT DISTINCT `users_id`, `tickets_id` FROM `glpi_tickets_users` WHERE `type` = '1' GROUP BY `tickets_id` ORDER BY                                                                                               `id` ASC) AS `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`) LEFT JOIN `glpi_ticketvalidations` ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id`) WHERE `glpi_tickets`.`i                                                                                              s_deleted` = '0' GROUP BY `glpi_tickets`.`id` HAVING COUNT(`glpi_items_tickets`.`items_id`) = 0) UNION (SELECT NULL as `id`, IF(`glpi_tickets`.`name` = '', CONCAT('(', `glpi_tickets`.`id`, ')'), `glpi_tickets`.`name`)                                                                                               as `name`, CONCAT('t_', `glpi_tickets`.`id`) as `display_id`, `glpi_tickets`.`id` AS `items_id`, 'Ticket' as `itemtype`, IF(`glpi_ticketvalidations`.`status` IS NULL,  `glpi_tickets`.`status`,  IF(`glpi_tickets`.`globa                                                                                              l_validation` IN ('1', '3'),  `glpi_tickets`.`status`,  IF(`glpi_tickets`.`status` IN ('5', '6'),  `glpi_tickets`.`status`,  IF(`glpi_tickets`.`global_validation` = '2',  '101',  '102'  )  )  )  ) AS `status`, `glpi_ti                                                                                              ckets`.`date` AS `date_creation`, `glpi_tickets`.`date_mod` AS `date_mod`, `glpi_tickets`.`entities_id` AS `entities_id`, 0 as is_recursive, COALESCE(`glpi_tickets_users`.`users_id`, 0) as `requester_id`, COALESCE(`glp                                                                                              i_ticketvalidations`.`users_id_validate`, 0) as `users_id_validator`, 0 as groups_id_validator, `glpi_tickets`.`content` AS `comment`, `users_id_recipient` AS `users_id_recipient`, `time_to_own` AS `time_to_own`, `time                                                                                              _to_resolve` AS `time_to_resolve`, `internal_time_to_own` AS `internal_time_to_own`, `internal_time_to_resolve` AS `internal_time_to_resolve`, `solvedate` AS `solvedate`, `date` AS `date`, `takeintoaccount_delay_stat`                                                                                               AS `takeintoaccount_delay_stat` FROM `glpi_tickets` INNER JOIN `glpi_items_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id` AND `glpi_items_tickets`.`itemtype` = 'PluginFormcreatorFormAnswer') LEFT                                                                                               JOIN (SELECT DISTINCT `users_id`, `tickets_id` FROM `glpi_tickets_users` WHERE `type` = '1' GROUP BY `tickets_id` ORDER BY `id` ASC) AS `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)                                                                                               LEFT JOIN `glpi_ticketvalidations` ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id`) WHERE `glpi_tickets`.`is_deleted` = '0' GROUP BY `glpi_items_tickets`.`items_id` HAVING COUNT(`glpi_items_tickets`.`it                                                                                              ems_id`) = 1)) AS `union_a44574fbf9f3b1082e51a8f52844cc0b`"

**Comment by magicpower77** [comment]
I uploaded the 2.13.0-rc.1 version on Github in the releases but I manually added some committed file from the develop branch

**Comment by magicpower77** [comment]
I just put the files back in compliance and I was able to sync. 
I still have the original problem though.

**Comment by btry** [comment]
so far I failed to reproduce. There must be an unknown thing required to reproduce.

Could you try to create a very simple form to reproduce : having only 1 question of type GLPI Object / Computer is probably sufficient ?

If yes, then export it and drop its json here.

**Comment by magicpower77** [comment]
Bonjour,

Désolé pour ma réponse aussi tardive.
J'ai mis à jour le plugin formcreator en version 2.13.0-rc.1 et GLPI en 10.0.2
J'ai corrigé les erreurs et remis en conformité les tables GLPI.

J'ai créé un formulaire avec une seule question et quand je test j'ai cette erreur:. 

*** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_formanswers` (`plugin_formcreator_forms_id`, `name`, `status`, `users_id_validator`, `groups_id_validator`, `ent>
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  src/DBmysql.php:1312
  src/CommonDBTM.php:705                             DBmysql->insert()
  src/CommonDBTM.php:1304                            CommonDBTM->addToDB()
  plugins/formcreator/front/form.form.php:140        CommonDBTM->add()
  {"user":"119@SERVEURNAME"}

Avez-vous une idée ?

Merci d'avance !

**Comment by btry** [comment]
Bonjour

 Vérifiez votre table glpi_plugin_formcreator_formanswers. Il y a peut être une différence de schéma dans la colonne a la source de l'erreur. Je n'ai pas le code sous les yeux, mais je pense qu'elle est supposée avoir une valeur par défaut, et je pense que ce n'est pas le cas chez vous

**Comment by magicpower77** [comment]
Oui je viens de vérifier et j'ai mis la valeur à 0 de is_deleted par défaut. Formcreator fonctionne maintenant parfaitement ! 
Merci pour ton aide.
