### ISSUE TITLE
Catégorie du formulaire = Catégorie Ticket

### ISSUE THREAD

**Issue by duylong** [pluginsGLPI/formcreator#281]
Bonjour,

Ce serait super bien d'appliquer la catégorie du formulaire à la catégorie du ticket lors de la création. Pour l'instant je ruse un peu avec les gabarits des tickets, mais c'est lourd à gérer quand on a plusieurs dizaines de catégories.

Sinon donner la possibilité de choisir la catégorie lors du paramétrage de la destination.

Bien cordialement.

**Comment by btry** [comment]
Bonjour

Les catégories de tickets et les catégories de formulaires sont deux ensembles distincts. Par conséquent il serait nécessaire de créer une table de correspondance entre les deux. 

Votre solution passant par les gabarits me parait être la solution la plus appropriée, et recommandable. 

Donner un paramétrage dans le plugin qui dupliquerait ce que font les gabarits me semble plus discutable car cela induirait un conflit ou une priorité à établir (et qui pourrait perturber les adminsitrateurs de formulaires).

Je mets le label Question sur le ticket pour l'instant, c'est un sujet qui mérite réflexion.

**Comment by duylong** [comment]
Tant que j'ai une solution, qui de plus est recommandée O:-)

En tout cas c'est bien d'avoir la possibilité de lier les formulaires et les tickets bien que indépendant. A voir si catégories de tickets et les catégories de formulaires ne sont pas liés avec l'usage.

**Comment by flegastelois** [comment]
Duplique #15
