### ISSUE TITLE
Zone de texte : Le retour chariot a une réaction bizarre

### ISSUE THREAD

**Issue by DeltatecAS** [pluginsGLPI/formcreator#2818]
**Describe the bug**
J'ai un souci avec le retour chariot. En effet, lorsque je fait "enter" il déplace bien le curseur sur la ligne du dessous mais il agrandit la zone de texte sans faire descendre le texte. Ce qui fait qu'à un moment les premières lignes sont cachées par l'encadré de la zone. 

![image](https://user-images.githubusercontent.com/77720940/171608996-6c0614f4-c28d-42fc-9a55-41dfb44a0472.png)

En gros le curseur descend jusqu'à la position initiale de la zone de texte, et lorsque cette position est atteinte il déplace le texte vers le haut lorsqu'on fait à nouveau un retour chariot au lieu d'utiliser l'espace de la zone qui a été agrandie. Du coup à un moment on perd le texte et on a pas d'ascenseur pour revenir au début. 

**GLPI / Plugins (please complete the following information):**
- GLPI V10
- FormCreator 2.13.0-beta.2

**Desktop (please complete the following information):**
 - OS: W10
 - Browser : Firefox, Chrome, Edge

**Comment by btry** [comment]
Bonjour

Cela se produit sur quoi ? le remplissage d'un formulaire, la conception d'une question ?

**Comment by DeltatecAS** [comment]
Le remplissage du formulaire. Lorsqu'on encode dans la zone de texte lorsqu'on désire envoyer un formulaire.

**Comment by btry** [comment]
duplicate of #2774

**Comment by DeltatecAS** [comment]
Désolé je n'avais pas trouvé dans la recherche ce bug.

**Comment by btry** [comment]
JE pense avoir trouvé. Essayez le patch suivant et faites un retour : https://github.com/pluginsGLPI/formcreator/pull/2820

**Comment by DeltatecAS** [comment]
Parfait ! Merci beaucoup !

**Comment by btry** [comment]
Merci pour votre retour.
