### ISSUE TITLE
Pas de création du formulaire sur des erreurs de ticket

### ISSUE THREAD

**Issue by duylong** [pluginsGLPI/formcreator#282]
Bonjour,

J'ai des champs obligatoires dans les tickets. Quand je crée un formulaire et que je le valide, la création du ticket lié est refusé car des champs sont manquants, par contre le formulaire est tout de même crée. Ce serait bien de ne pas le créer, ça oblige à avoir un ticket pour un formulaire.

Bien cordialement.

**Comment by btry** [comment]
Bonjour

Un test sur al version 2.12.0 a été fait : avec un gabarit sur le ticket cible imposant la spécification d'une catégorie ITIL, le ticket est bien créé. 

Le problème n'existe plus.
