### ISSUE TITLE
Regression Formcreator 2.13.0-beta.2 + GLPI10

### ISSUE THREAD

**Issue by Mumurien** [pluginsGLPI/formcreator#2821]
**Describe the bug**
With simplified interface and "Create Ticket" right not checked, forms aren't visible on home page.
Yet forms are accessible from URL.
"Visible" and "direct acces..." are set on "yes" in forms and access for this profile is granted.

**To Reproduce**
1. Go to 'Profile', create a profile with simplified interface and uncheck "Create Ticket"
2. Log in a user with this profile
3. Forms tabs isn't visible

**Expected behavior**
On GLPI v9.5.7 + FormCreator 2.12.4, same parameters, "Forms" tab was visible and user could fill forms but no tickets.

Maybe it's related to #2596 but not sure.

**Comment by btry** [comment]
Hi

There is no tab to show forms in simplifeid interface. However, it has been reported a few days ago that the menu entry "Forms" was missing. Apply this fix : https://github.com/pluginsGLPI/formcreator/commit/5a07a70c066039d8c160608ce23077d96afc5bb5

**Comment by btry** [comment]
Hi

Having no feedback, I close this issue.
