### ISSUE TITLE
Formcreator 2.13.0-beta.2 with GLPI 10.0.0.1 // Not installing

### ISSUE THREAD

**Issue by tristangallet** [pluginsGLPI/formcreator#2822]
Hello,
I've just updated GLPI to 10.0.0.1. After updating from Formcreator  2.13.0-beta.1 to  2.13.0-beta.2, i can not activate the plugin.

Message : 
SQL Error "1054": Unknown column 'is_search_issue_visible' in 'field list' in query "INSERT INTO glpi_plugin_formcreator_entityconfigs (entities_id, replace_helpdesk, default_form_list_mode, sort_order, is_kb_separated, is_search_visible, is_dashboard_visible, is_header_visible, is_search_issue_visible, tile_design) SELECT ent.id, IF(ent.id = 0, 0, -2), IF(ent.id = 0, 0, -2), IF(ent.id = 0, 0, -2), IF(ent.id = 0, 0, -2), IF(ent.id = 0, 0, -2), IF(ent.id = 0, 1, -2), IF(ent.id = 0, 0, -2), IF(ent.id = 0, 1, -2), IF(ent.id = 0, 0, -2) FROM glpi_entities ent LEFT JOIN glpi_plugin_formcreator_entityconfigs conf ON ent.id = conf.entities_id WHERE conf.entities_id IS NULL"
Unknown column 'is_search_issue_visible' in 'field list'

**Comment by btry** [comment]
Hi

Did you follow the upgrade instructions in the release notes to upgrade from a previous alpha or beta version ?

**Comment by tristangallet** [comment]
I've uninstalled it and re-installed and it's ok.
