### ISSUE TITLE
Incorrect Auto Population of Search rule

### ISSUE THREAD

**Issue by SKupec** [pluginsGLPI/formcreator#2823]
**Describe the bug**
Accessing the Assistance / Forms and Selecting the "All my forms (validator)" Opens an automatic search with incorrect rules.

**To Reproduce**
1. Go to 'Assistance'
2. Click on 'Forms'
3. Right hand side of screen under "My 5 last forms (validator) Click "All my forms (validator)
4. Default "rule" shows as Items Seen contains 9 and Items Seen contains mygroups.
5. All changes to the rules are reset after leaving Forms.

**Expected behavior**
I expect to either have it remember the last rules used, or have the ability to change the rules to something useful and save it.

**Screenshots**
![image](https://user-images.githubusercontent.com/78433779/171884142-a3538311-b074-4d49-bead-2dba585881e8.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
- 	fields               Name: Additional Fields              Version: 1.15.2     State: Enabled
	advanceddashboard    Name: advanceddashboard              Version: 1.4.0      State: Enabled
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Installed / not activated
	formcreator          Name: Form Creator                   Version: 2.13.0-beta.2 State: Enabled
	agentconfig          Name: GLPI Agent config              Version: 1.2.0      State: Installed / not activated
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.8.0      State: Enabled
	oauthsso             Name: oauthsso                       Version: 1.5.1      State: Enabled
	genericobject        Name: Objects management             Version: 2.12.0     State: Enabled
	tag                  Name: Tag Management                 Version: 2.9.0      State: Enabled

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser chrome and safari have the same issues
 - Version Latest for both.

**Comment by btry** [comment]
Hi

First, I see the comparison operator is "contains" this should be "is". Also this should not be "items seen". There is a problem here.

2nd point : the customisations done on the search are not saved, this is normal. This is silply not implemented. I

**Comment by btry** [comment]
Hi

Apply this fix and feedback: 5335d0ae

**Comment by btry** [comment]
Hi

Having no feedback, I assume the patch solves the issue.
