### ISSUE TITLE
Icons swapped in formcreator 2.13.0-beta.2 in simplified interface GLPI 10

### ISSUE THREAD

**Issue by bolivarf** [pluginsGLPI/formcreator#2824]
Forms that come without icons from older versions of formcreator have the fa-question-circle icon and FAQs have the fa-clipboard-list icon should be the other way around.

**To Reproduce**
1 Create three forms for a category of frequently asked questions, the first since it could not be imported from previous schemes, just give it a title, faq category and export, edit the file and eliminate the fields "icon":0,"icon_color":"", "background_color":"", deleting the current form, import it again. The second just give it a title and the third change the icon
2 Create a FAQ in the category used by the forms
4. See error in simplified interface -> forms

**Expected behavior**
That the forms without previous icons have the icon of fa-clipboard-list or the icon fa-edit or neither and the FAQ the icon of fa-question-circle like the rest of GLPI

**Screenshots**
result
![Captura desde 2022-06-04 12-55-59](https://user-images.githubusercontent.com/7965864/172020379-a9b31017-dc44-441d-a4b2-e9de5f5a6aa2.png)
![Captura desde 2022-06-04 12-59-31](https://user-images.githubusercontent.com/7965864/172020705-6a49e26d-3161-4073-b042-ddca0ea766e8.png)

expected
![Captura desde 2022-06-04 12-55-59-spec](https://user-images.githubusercontent.com/7965864/172020510-e76b585c-d436-4e3d-a6b2-0634c5b51edd.png)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.1
	formcreator          Name: Form Creator                   Version: 2.13.0-beta.2 State: Enabled
	gantt                Name: gantt                          Version: 1.0.0      State: Not installed
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Installed / not activated
	mreporting           Name: Más Informes                   Version: 1.8.0      State: Installed / not activated
	telegrambot          Name: TelegramBot                    Version: 3.0.0      State: Not installed

**Desktop (please complete the following information):**
 - OS: UBUNTU 22.04
 - Browser Google Chrome
 - Versión 102.0.5005.61 (Build oficial) (64 bits)

**Comment by btry** [comment]
Hi

A fix has been merged this week, fixing a problem when forms are displayed instead of faq, in separated KB mode. It may help to solve this issue. Can you test the latest revision of the branch support/2.13.0 ?

**Comment by bolivarf** [comment]
hi
no problem i can try that branch

**Comment by bolivarf** [comment]
hello
what is the branch is this
https://github.com/pluginsGLPI/formcreator/tree/support/2.13.0

**Comment by bolivarf** [comment]
It says that it is 2.13.0-beta.2 and when it is active it does not appear in the simplified interface as if it were deactivated

**Comment by btry** [comment]
Check the status in the plugins page. If it ask you to run composer or yarn then you must do it. If you don't know these tools, then wait next week, i'll provide yo you a build

**Comment by bolivarf** [comment]
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
**Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package patchwork/jsqueeze is abandoned, you should avoid using it. No replacement was suggested.**
Generating optimized autoload files
31 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by bolivarf** [comment]
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.36s

**Comment by bolivarf** [comment]
Composer version 2.3.6 2022-06-01 21:57:13

**Comment by bolivarf** [comment]
copy the vendor folder from the old plugin and run composer again, the plugin works in the normal interface but does not appear in the simplified interface.

**composer install --no-dev**
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 2 updates, 0 removals
  - Upgrading symfony/polyfill-php80 (v1.23.1 => v1.26.0): Extracting archive
  - Upgrading symfony/finder (v4.4.30 => v4.4.41): Extracting archive
**Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package patchwork/jsqueeze is abandoned, you should avoid using it. No replacement was suggested.**
Generating optimized autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by bolivarf** [comment]
GLPI's Helpdesk
![Captura desde 2022-06-04 16-40-10](https://user-images.githubusercontent.com/7965864/172024930-7dd67b0c-2f10-4535-8438-43e08d2c6313.png)

Service catalog simplified
![Captura desde 2022-06-04 16-40-46](https://user-images.githubusercontent.com/7965864/172024928-7944b065-9526-4b50-8f7f-4524bc6b3e90.png)

Service catalog extended
![Captura desde 2022-06-04 16-39-41](https://user-images.githubusercontent.com/7965864/172024931-393c522a-8b7c-487e-91ee-fc987c7828ca.png)

It doesn't seem to work in GLPI's Helpdesk mode, the other two modes I don't see the difference.

**Comment by btry** [comment]
In glpi helpdesknmode, formcreator does not changes the menus of GLPI (there were changes unti beta 1 or 2, then reverted back to behaviour of 2.12.0. sole people were disturbed by that.

Simplified and extended service catalog differ only when displaying tickets. One show essential info, the other shows more.

Then the plugin is active and seems to work well as far as I see.

**Comment by bolivarf** [comment]
in previous versions the menu does not change but there is a new menu that called the forms here there is no way to use a form

**Comment by bolivarf** [comment]
![image](https://user-images.githubusercontent.com/7965864/172025420-0d1c923d-d12d-412b-a413-c7c444cd3816.png)
old glpi

**Comment by btry** [comment]
In gkpi helpdesknmode you don't have access to forms (this is the regular solicited interface). Forms are accessible from normal interface, in assistance > forms.

In service catalog, click on "seek assistance".

I'm not having a computer right now then I answer using my memory, then I might be inaccurate about some minor things.

**Comment by bolivarf** [comment]
the problem is not the normal interface, it is the simplified one because there are users who do not have privileges for the normal interface and must be able to fill out forms as they could in previous versions of GLPI from 0.x.x to 9.x.x

**Comment by btry** [comment]
Ah yes ! I got the point.

I'll do a fix next week.

**Comment by bolivarf** [comment]
OK thank you so much

**Comment by bolivarf** [comment]
anyway it seems that they are using some libraries that are no longer supported

**Comment by btry** [comment]
Hi

Here is a fix for the menu entry: 5a07a70c066039d8c160608ce23077d96afc5bb5

**Comment by btry** [comment]
and an other to un-swap the icons: 42a45579

**Comment by bolivarf** [comment]
Hi
The icons are fine, the name of the menu does not convince me much, but it could be fine.

**Comment by bolivarf** [comment]
For me this would make more sense, but it's just my opinion, I don't know what others may think
![Captura desde 2022-06-12 22-20-19](https://user-images.githubusercontent.com/7965864/173268281-b50ac8b0-5185-4d2a-a18a-5b3ec77aa70e.png)
.

**Comment by btry** [comment]
Hi

I agree, I'll change it to "Forms" like it was in 2.12.

**Comment by bolivarf** [comment]
Hi and thanks
The icon should also change based on the menu title, maybe not the one I put in the screenshot example, but something that better represents forms.

**Comment by btry** [comment]
Forms are used to fill a request for assistance or declare an incident. A headset icon has been selected because it is used in GLPI (10) for ticketing (see screenshot below). 

![image](https://user-images.githubusercontent.com/14139801/173323884-0d0de188-a897-4d90-886f-9f4208235c4e.png)

**Comment by bolivarf** [comment]
ok I understand, thanks.

**Comment by bolivarf** [comment]
Although in the support menu of the normal view, the form option has another icon.

**Comment by btry** [comment]
Here ?

![image](https://user-images.githubusercontent.com/14139801/173326337-4f369a72-8278-453f-b7fb-bbdb0737b403.png)

**Comment by bolivarf** [comment]
Yes, there should be no consistency.

**Comment by btry** [comment]
In this case forms are one of several possibilities (tickets, changes, ..., forms). This is a menu item, not a menu. It is bettter to have a more specialized icon as the headset is already used in the higher level.

**Comment by bolivarf** [comment]
Ok it's fine

**Comment by bolivarf** [comment]
You might also think there are other assistance options.
![Captura desde 2022-06-13 06-05-06](https://user-images.githubusercontent.com/7965864/173331500-6df6b844-d315-49de-94af-c5c002edfdc7.png)

**Comment by btry** [comment]
Which context for this screenshot ? Self service  with service catalog disabled ?

**Comment by btry** [comment]
HI

This does not helps me. I guess this is a self service with service catalog disabled. Do you confirm ?

**Comment by bolivarf** [comment]
if you mean the formcreator mode in the entity it is HelpDesk, if you mean the view it is simplified view

**Comment by bolivarf** [comment]
![image](https://user-images.githubusercontent.com/7965864/173527828-b82d368d-00b3-43b3-9ecb-1e26629d806c.png)

**Comment by btry** [comment]
OK. 

In this mode we need to maintain access ti ticket creation along access to forms. 

In this case, "seek assistance" is not appropriate as it would confuse with "Create ticket".

In short : "seek assistance should show only when it is tie only way to create a request (of any type).

**Comment by bolivarf** [comment]
that's correct

**Comment by btry** [comment]
Open a new issue to discuss about that. Follow the rule 1 topic or bug = 1 issue.

**Comment by btry** [comment]
Hi

Are the issues with menus solved ? Can I close ?

**Comment by bolivarf** [comment]
Yes, thank you very much, it's solved.
