### ISSUE TITLE
Ticket without observers after having set it on the target

### ISSUE THREAD

**Issue by alexmicontini** [pluginsGLPI/formcreator#2826]
**Describe the bug**

I have several applications registered. I have assigned a technical group to each of them in charge of the application.

For example:

Moodle - Technical Group: Moodle Technicians
PLACE - Technical Group: PLACE Technicians

**To Reproduce**

In a Formcreator form I have created a question called "Application" of type "GLPI Object" linked to the assets of type applications.

In the target configuration, I assign the Technical Group as an Observer from an "Application" object.

In the form, the user selects an application and creates the ticket, but the observer field is saved blank.

**Expected behavior**

If the user has selected Moodle, the ticket should have the Moodle Technicians group as observers but it remains blank, without observers.

**Screenshots**

Configuración de una Aplicación:
![image](https://user-images.githubusercontent.com/86783891/172356496-04fb6a51-0d78-45b1-ae68-0a7ecda48878.png)

Configuración del Objetivo:
![image](https://user-images.githubusercontent.com/86783891/172356794-ccd6d09b-2d98-4e63-b62b-bff852a32509.png)

Resultado:
![image](https://user-images.githubusercontent.com/86783891/172356933-7e4753a0-f5f8-4880-ae7c-ac9134bb06b1.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version: 9.5.7
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)

tag                  Name: Administración de etiquetas    Version: 2.8.3      State: Enabled
news                 Name: Alertas                        Version: 1.9.1      State: Enabled
fields               Name: Campos adicionales             Version: 1.13.0     State: Enabled
screenshot           Name: Captura de pantalla            Version: 1.1.6      State: Enabled
datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled
archimap             Name: Diagrams                       Version: 3.2.7      State: Enabled
escalade             Name: Escalado                       Version: 2.7.2      State: Enabled
formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled
fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled
genericobject        Name: Gestión de objetos             Version: 2.11.1     State: Enabled
metademands          Name: Meta-Demands                   Version: 2.7.9      State: Installed / not activated
statecheck           Name: Statecheck Rules               Version: 2.3.4      State: Installed / not activated
webresources         Name: Web Resources                  Version: 1.3.2      State: Enabled

**Additional context**

**Comment by btry** [comment]
Hi

Try the above fix and feedback

**Comment by alexmicontini** [comment]
Hi @btry ,
it worked with the fix.

Thank you very much!

![image](https://user-images.githubusercontent.com/86783891/172571634-c2aad09b-dd36-499e-92a9-d539a2555dcb.png)

**Comment by btry** [comment]
Thank you for your fedback; I close.
