### ISSUE TITLE
[GLPI v10.0.1] [FC 2.13.0-rc.1]Published Know Base Item in FaQ appears in Form UI

### ISSUE THREAD

**Issue by AdrianXuizGarcia** [pluginsGLPI/formcreator#2827]
When I try to make a **Knowing Base Item** to be published in FaQ, it appears in the User Interface reserved for the forms (formlist.php). I dont think this is a feature.... 

I guess the problem is in the _know item_ for the GLPI v10, because it has a "form" word in his name (The route that appears in the navigator is **/front/knowbaseitem.form.php?id=1**). Maybe it interfears with the function that obtains the forms from the database.

If I make the Know Item to not be published in the FaQ, it dissapears from the Form Interface.

**Screenshots**

Here i have 2 forms made with FormCreator, and the other is an know item.
![1](https://user-images.githubusercontent.com/60902503/172367839-e6611b2f-78f6-4764-8ec6-804e5d75b83f.png)
![2](https://user-images.githubusercontent.com/60902503/172367854-e6068b0f-984b-4562-8e1f-1b71211cd6c5.png)

**Comment by btry** [comment]
How is configured your entity ?

![image](https://user-images.githubusercontent.com/14139801/172370934-a88997e8-f4c9-4d86-a953-c0e1e4464f17.png)

**Comment by AdrianXuizGarcia** [comment]
Welp my bad, it was that. Didnt see it in previous versions, never saw that option, and it was with "Fusioned with Forms" by Default. Closing issue, thanks!
