### ISSUE TITLE
Type Adresse IP non affiché

### ISSUE THREAD

**Issue by duylong** [pluginsGLPI/formcreator#283]
Bonjour,

J'ai défini un type Adresse IP dans une question. Or il ne s'affiche pas lors de la prévisualisation. Avez-vous aussi ce souci ?

Je n'ai rien dans les logs et j'utilise le dernier release...

Bien cordialement.

**Comment by btry** [comment]
Bonjour

Effectivement ce champ ne s'affiche pas, mais c'est normal. Il sert à collecter l'adresse IP du demandeur au moment d'envoyer sa demande. 

Si vous avez besoin de faire saisir une IP, utilisez un champ texte, et si vous voulez garantir une saisie correcte, vous pouvez ajouter une expression régulière pour vérifier la saisie.

**Comment by duylong** [comment]
Merci je n'avais pas compris le fonctionnement du champ.
