### ISSUE TITLE
Displaying the knowledge base on the form creator plugin page.

### ISSUE THREAD

**Issue by basson63** [pluginsGLPI/formcreator#2838]
Hello!
How to disable the display of objects added to the knowledge base on the main page with forms created by the form creator plugin.
GLPI version 10 is used
![Screenshot-form](https://user-images.githubusercontent.com/87585178/173813115-532faf8f-baa6-46af-b9a1-c612e5fda035.png)

**Comment by btry** [comment]
Hi

Check if the display mode of kB items is merged or in a separate menu entry. The setting is in the entity settings, tab Form.

**Comment by basson63** [comment]
Please tell me where this tab is?

**Comment by btry** [comment]
Here


![image](https://user-images.githubusercontent.com/14139801/173831894-0b2a6cd2-47ef-4fce-8159-d3317f6c5e5c.png)
