### ISSUE TITLE
создание билета через form creator

### ISSUE THREAD

**Issue by basson63** [pluginsGLPI/formcreator#2839]
How to replace the standard ticket creation interface on the main user page with the interface from the form creator plugin.

![Screenshot_form2](https://user-images.githubusercontent.com/87585178/173817880-b062d1a3-a076-4144-987d-faf66d0950b1.png)
![My form](https://user-images.githubusercontent.com/87585178/173818107-e70fe65a-90f0-4626-b6e1-4938b88cfcf9.png)
.

**Comment by btry** [comment]
Here

Choose service catalog extended or service catalog simplified. It applies only on profiles using simplified interface. In standard interface, you may disable ticket creation by tuning rights.

The service catalog extended shows more informations from a ticket than service catalog simplified.
![image](https://user-images.githubusercontent.com/14139801/173832129-1cbdd64d-6035-4a53-971c-910bca17156f.png)

**Comment by basson63** [comment]
Hello! Thank you for your answer, it helped me a lot. Please tell me, maybe you have encountered. (I can't find a suitable forum thread).
the API mechanism does not work in glpi 10, there is no way to connect the browser extension "glpi reminders" and configure a bundle with zabbix.

**Comment by btry** [comment]
Hi

> Thank you for your answer, it helped me a lot.

Great, then I can close this issue.

I cannot help you with this browser extension "GLPI reminder". You should get in touch with its editor.

You should contact the editor of this extension
