### ISSUE TITLE
VERSION ERROR

### ISSUE THREAD

**Issue by Rizwan354** [pluginsGLPI/formcreator#2840]
Hi, I am trying to install this plugin on my GLPI version 10.0.1. But this plugin is not available for this version.
Can anyone please tell me which version of GLPI do I need for this plugin

**Comment by btry** [comment]
Hi

The version 2.13.0 for glpi 10 is in progress. The final release will happen soon. 

The latest stable release is 2.12.5, for glpi 9.5.7.
