### ISSUE TITLE
Problème d'accès de formulaires

### ISSUE THREAD

**Issue by flopich** [pluginsGLPI/formcreator#2842]
D'un point de vue "Self-Service", les formulaires ne sont plus accessibles depuis le passage en rc1. Les formulaires existent bien d'un point de vue "Super-Admin" et fonctionnent pour créer les tickets.

**Comment by btry** [comment]
Bonjour

Appliquez les patchs suivants :

https://github.com/pluginsGLPI/formcreator/commit/5a07a70c066039d8c160608ce23077d96afc5bb5

https://github.com/pluginsGLPI/formcreator/commit/07d27926543c75912d3748044f4ac93b0278b687

Vous devriez avoir des modifications sur les menus.

**Comment by flopich** [comment]
Merci beaucoup ! Les forms sont accessibles depuis le profil "Self-Service" !
