### ISSUE TITLE
Forms requiring approval do not appear in the "To validate" counter

### ISSUE THREAD

**Issue by xraive** [pluginsGLPI/formcreator#2844]
This is my first time using formcreator but I noticed the "To validate" counter doesn't show a list of forms that need to be validated.  After the form has been validated the form shows up in the "All, "New" or "Assigned" counters.

1. Go to Seek Assistance and complete a form that requires validation

I expected that any form needing validation would show up on the "To validate" counter.  If this isn't how it's supposed to work then my apologies in advance.  This would be helpful for bot the Requestor and Validator to know which form are waiting for approval.

**Screenshots**

I'm using formcreator version.  2.13 0-rc.1 and using GLPI Version 10.0.1.  This is a brand new install with only the formcreator plugin installed.

**Comment by xraive** [comment]
![image](https://user-images.githubusercontent.com/17913801/174435139-9417dc94-dbe9-42a9-b344-837588d50b94.png)

**Comment by btry** [comment]
Hi 

Try the fix above and feedback. It should solve this issue and the other one you created.

**Comment by btry** [comment]
Thank you for your feedback, I close both issues.
