### ISSUE TITLE
Can't see new forms created that require validation

### ISSUE THREAD

**Issue by xraive** [pluginsGLPI/formcreator#2845]
**Describe the bug**
When I submit a form that requires validation I don't see the form in my default form view.    I only see it once it's approved.  This might be related to issue #2844.

**To Reproduce**
1. Create a form that requires validation
2. Fill out forma and submit
3. Check out "My request for assistance" page

**Expected behavior**
I expect to see all forms that I submit and their current status.  The only way I can view the forms is by changing the default search filter  See attached image.

*I'm using formcreator version. 2.13 0-rc.1 and using GLPI Version 10.0.1. This is a brand new install with only the formcreator plugin installed.

Default Search filter
![image](https://user-images.githubusercontent.com/17913801/174445583-b8c48601-5947-4c71-bbb5-a3d4a361d07d.png)

Modified Search filter
![image](https://user-images.githubusercontent.com/17913801/174445370-184d4a10-782a-4a39-8ca6-9fd4eec85c41.png)

**Comment by btry** [comment]
Hi

I tried to reproduce and I see that in the table glpi_plugin_formcreator_issues the rows matching the answers to validate have status = 0. This is not normal. Can you cofirm you have the same in your DB ?

**Comment by btry** [comment]
Hi

My previous comment is very likely obsolete. Apply the above fix and tell if the problem disappears.

**Comment by xraive** [comment]
I just wanted to let you know your fix resolved both issues.  (#2844 & #2847).  Forms waiting for approval appear  and in the form list and have the correct status "Waiting".  Also the "To validate" counter reflects the number of form waiting for approval correctly.

Thanks you very much.


![image](https://user-images.githubusercontent.com/17913801/174608958-de7bde47-b570-4f78-88e5-ae315e85aa20.png)
