### ISSUE TITLE
Problème affichage en mode "Self-service" après installation plugin

### ISSUE THREAD

**Issue by Dydouche** [pluginsGLPI/formcreator#2850]
Bonjour, 

J'ai actuellement un problème avec l'affichage en mode "self-service" du plugin FormCreator version 2.12.5.
Je viens tout juste de l'installer. 

Voici a quoi ressemble l'interface.
![image](https://user-images.githubusercontent.com/48713562/174790453-76699c98-6b61-41d9-99ff-9b5d84ea623b.png)

J'ai essayé avec un compte ayant seulement le rôle "Self-service" et ça ne fonctionne pas non plus.

Quelqu'un aurait une idée du problème ?

Merci d'avance 

Info serveur : 
Windows Server 2012 R2
Wampserver 3.2.6
PHP 7.4.26
MySQL 5.7.36
Apache 2.4.51

**Comment by btry** [comment]
Bonjour

Essayez un rafraîchissement du cache du navigateur avec f5.

**Comment by Dydouche** [comment]
Bonjour, 

J'ai essayé de faire un F5 et même un Ctrl-F5 pour vider le cache. 
Ca ne fonctionne toujours pas :(

Cordialement,

**Comment by btry** [comment]
Avez vous télécahrgé l'archive provemant du bouton ci dessous ou utilisé le marketplace ?

![image](https://user-images.githubusercontent.com/14139801/174995974-61f00d33-1af6-4520-8ba6-188fabecea18.png)

**Comment by btry** [comment]
Le lien dans la capture d'écran ci dessus est dans Github.

Vous avez pris un ZIP, donc j'imagine que vous avez téléchargé à partir du lien ci dessous.
![image](https://user-images.githubusercontent.com/14139801/174997324-22605f04-8ee2-4b22-97fd-9e3d2f50ae1a.png)

Ne prenez pas ce lien : c'est le code source du plugin. Un build est requis avant de l'utiliser. Le lien que j'ai mentionné tout à l'heure vous fournit un build tout prêt, et vous pouvez également installer le plugin avec le marketplace pour encore plus de simplicité.

**Comment by Dydouche** [comment]
J'ai téléchargé le zip à cette endroit là. J'ai toujours téléchargé les plugins GLPI depuis github et je n'ai jamais eu de problème.
![image](https://user-images.githubusercontent.com/48713562/175001503-937b303e-042f-4b26-9157-4099d86280b1.png)

J'ai cliqué sur Source code (zip) dans l'encart Asset

**Comment by Dydouche** [comment]
Ok, bah désolé du dérangement, je pensais vraiment que le zip de la release 2.12.5 était ok. 

Merci pour votre rapidité.

Je me sens un peu stupide du coup :)
