### ISSUE TITLE
languages cannot be applied

### ISSUE THREAD

**Issue by basson63** [pluginsGLPI/formcreator#2855]
Hello.
the updates made to the localization files of the *.po and *.mo languages cannot be applied

![image](https://user-images.githubusercontent.com/87585178/175495796-67faf612-6528-4263-bd98-6a6e0d2dab52.png)

**Comment by basson63** [comment]
it doesn't help
systemctl restart apache2

**Comment by btry** [comment]
Hi

I don't understand your problem. Did you try to download latest .po and .mo files to have better translations ?

**Comment by basson63** [comment]
Where can I get them?

**Comment by btry** [comment]
You need to run transifex CLI tool (tx), then run **tx pull** 

GLPI uses cache for translations, then you may need to enable debug mode to reload up to date translations. You may also stop your apache / nginx server , clear the cache of GLPI then restart your apache / nginx server.

**Comment by btry** [comment]
Hi

Having no fedback, I assume your problem is solved.
