### ISSUE TITLE
Update with error

### ISSUE THREAD

**Issue by adrianolima-ti** [pluginsGLPI/formcreator#2865]
Server: Ubuntu 20
PHP: 8.1.7

I upgraded to glpi10, but I can't execute the statement "php bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade". Reports: Requirements not met for "formcreator" plugin. This plugin requires GLPI >= 9.5e <9.6.
I read a lot of material on the web and they all get the same result.
So I decided to remove the "formcreator" folder in "/var/www/html/glpi/plugins" and apply the above instruction again. Same error, even without having the plugin anymore.
I then noticed that I have some cache or instruction in the DB to be resolved, but I don't know which one.

ps.: sorry for the english of the "translate"

![image](https://user-images.githubusercontent.com/108683638/177183274-43677b55-015a-4f36-bda8-02d586145457.png)

![image](https://user-images.githubusercontent.com/108683638/177183113-c0423e78-3f13-46e3-8e8e-53637674e1a5.png)

**Comment by adrianolima-ti** [comment]
I managed to solve

![image](https://user-images.githubusercontent.com/108683638/177221120-e3f748d6-c8a9-4193-895e-12692f636eaf.png)

**Comment by btry** [comment]
Hi

You should not use the version 2.14-dev. Its development is only at its beginning.
