### ISSUE TITLE
Info : Traduction cible ticket

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#2867]
Bonjour

Comment est gérée la traduction d'un formulaire ?
Je vois qu'un enregistrement a été créé dans la table glpi_plugin_formcreator_forms_languages , ensuite j'ai entré les traductions des différents éléments du formulaire : ok. cela fonctionne : le formulaire passe bien en anglais. 
Où sont stockées ces valeurs ? je pensais à un .po, mais à priori non ?

En fait je pensais utiliser cela ,mais ne répond pas tout à fait à mon probleme : demandeur -> francais, acteurs : francais ou anglais...
Or le ticket ne peut etre créé que dans une seule langue (normal) 

Du coup je pense mettre les 2 traductions dans les différentes cibles.
Qu'en pensez vous ?
Merci

**Comment by btry** [comment]
Bonjour

les traductins sont dans glpi/files/_locales/formcreator/

les fichiers ont la forme form_{id}_{lang}.php

avec 
- {id} : l'ID du formulaire 
- {lang}: le code de langue de la traduction

Vous n'avez pas besoin de modifier ces fichiers : vous pouvez simplement éditer les traductions en vous rendant dans l'onglet "Traductions" d'une langue et en cliquant sur une entrée de la liste des traductions déjà enregistrées.
