### ISSUE TITLE
[GLPI 10.0.2] FC 2.13.0-rc.1 Acteurs ticket absents

### ISSUE THREAD

**Issue by michaelNFF** [pluginsGLPI/formcreator#2869]
Lors de la création d'un ticket depuis un formulaire les acteurs ne sont pas positionner les acteurs restent vide.

![image](https://user-images.githubusercontent.com/96116581/178009952-aed09049-00a1-4635-9456-638af62339ea.png)

**Comment by btry** [comment]
Bonjour

Pouvez vous montrer le ticket créé par le formulaire, vérifier si il y a des entrées de log utiles dans sql-erros.log et php-errors.log ?

**Comment by btry** [comment]
Précisez aussi la version de votre GLPI. Ca peut être utile

**Comment by michaelNFF** [comment]
[GLPI 10.0.2] je l'ai noté dans le titre :)

**Comment by btry** [comment]
ah oui, j'ai pas fait attention.

Je viens de faire un essai avec la version de développement (un peu en avance sur la RC.1). Un formulaire vide avec 1 ticket cible contenant les 2 acteurs par défaut + un GLPI comme utilisateur assigné. Ca fonctionne bien.

Pouvez vous faire un essai similaire ? Je voudrais voir si c'est quelque chose de spécifique à votre formulaire qui cause votre souci.

**Comment by michaelNFF** [comment]
Je vais tester et je vous tiens informé.

Juste une subtilité, le demandeur est issue d'une question du formulaire de type GLPI object -> Administration - Utilisateurs

Je vais aussi tester un formulaire tout simple et je vous donne le résultat de mes tests.

**Comment by btry** [comment]
La RC.1 a 1 mois d'ancienneté déjà. Je n'ai pas souvenir d'avoir corrigé un bug comme le votre ce mois ci, mais pour éviter de chercher un bug qui serait déjà corrigé, essayez d'upgrader vers cette version puis voyez si le souci persiste.

[formcreator-2.13.0-dev.zip](https://github.com/pluginsGLPI/formcreator/files/9072928/formcreator-2.13.0-dev.zip)

:warning: cette version contient des améliorations touchant à l'upgrade du plugin. Faites un backup avant de l'installer car vous pourriez avoir des difficultés à réaliser l'upgrade.

:warning: pour réaliser l'upgrade avec cette version vous devez utilsier la commande CLI suivante : **bin/console glpi:plugin:install formcreator -f -p force-upgrade** . **Cette commande n'est à utiliser que dans le cadre de ce rapport de bug et cette archive.**

**Comment by michaelNFF** [comment]
Merci je vais tester cette version de dev.
La dernière que j'ai testé est celle d'hier.
![image](https://user-images.githubusercontent.com/96116581/178017697-71c3d329-5d0a-4567-8e1d-4585190c8d56.png)

**Comment by btry** [comment]
Elle ne date pas du 7 juillet mais du 7 juin. J'attends votre retour sur cette version.

**Comment by michaelNFF** [comment]
Pardon nous sommes en Juillet :)
Très bien merci pour votre réactivité.

**Comment by michaelNFF** [comment]
J'ai testé ce formulaire et user Attribué à reste vide
[export_formcreator_20220708_1602.zip](https://github.com/pluginsGLPI/formcreator/files/9073025/export_formcreator_20220708_1602.zip)

**Comment by btry** [comment]
J'ai réussi à avoir un cas où un acteur n'est pas ajouté au ticket. Pour obtenir ce problème, l'acteur dans le ticket cible doit avoir les notifications désactivées 
![image](https://user-images.githubusercontent.com/14139801/178028595-48ba7200-9d05-4e08-a699-1bc166df5ed2.png)

Quand on passe dans [cette ligne de code de GLPI](https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/Ticket.php#L1856), le booléen qui active (ou non) les notifications est perdu et rempalcé par une chaine vide. 

Plus tard dans le CommonITILObject::post_addItem(), GLPI tente d'ajouter l'acteur, et la requête SQL écoue avec le log donné dans mon post précédent.

**Comment by btry** [comment]
Il faut certainement que je mette modifie le [format des données](https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/CommonITILObject.php#L7968) que Formcreator utilsie pour générer le ticket,

**Comment by btry** [comment]
Ce correctif dans Formcreator fonctionne pour moi.

```diff
diff --git a/inc/abstractitiltarget.class.php b/inc/abstractitiltarget.class.php
index 183edf1f..d6703850 100644
--- a/inc/abstractitiltarget.class.php
+++ b/inc/abstractitiltarget.class.php
@@ -645,12 +645,12 @@ PluginFormcreatorTranslatableInterface
       if ($actorKey === false) {
          // Add the actor
          $actorType[]                           = $userId;
-         $actorTypeNotif['use_notification'][]  = ($notify == true);
+         $actorTypeNotif['use_notification'][]  = $notify;
          $actorTypeNotif['alternative_email'][] = $alternativeEmail;
       } else {
          // New actor settings takes precedence
          $actorType[$actorKey]                           = $userId;
-         $actorTypeNotif['use_notification'][$actorKey]  = ($notify == true);
+         $actorTypeNotif['use_notification'][$actorKey]  = $notify;
          $actorTypeNotif['alternative_email'][$actorKey] = $alternativeEmail;
       }
 
```

**Comment by btry** [comment]
Bonjour

Essayez le patch mentionné ci dessus. J'attends votre retour.

**Comment by michaelNFF** [comment]
Bonjour,

Désolé pour le délais de réponse.

Je confirme que si les notifications de acteur sont désactivées l'acteur n'est pas ajouté au ticket.

Je valide aussi le match. :)

Quelle version de formcreator dois-je utiliser? Celle du 7 juin 2002 [2.13.0-rc.1] avec votre patch ?(https://github.com/pluginsGLPI/formcreator/releases/tag/2.13.0-rc.1)

Merci à vous.

**Comment by btry** [comment]
Bonjour,

Le patch doit s'appliquer sans souci avec la release de tests 2.13.0-rc.1 .

**Comment by btry** [comment]
Les retours étant ok, je ferme ce ticket. Le patch sera dans le prochain livrable.
