### ISSUE TITLE
[GLPI 10.0.2] FC 2.13.0-rc.1 Problem Attachments

### ISSUE THREAD

**Issue by Gitnor77** [pluginsGLPI/formcreator#2871]
Hi,
I have a problem with adding an attachment to a created form.
The form itself must be public (accessible to non-registered users).
![image](https://user-images.githubusercontent.com/109066311/178227185-d6a00c6e-11ff-4d18-b43f-92fc75cac615.png)

The problem for a registered user does not occur.
![image](https://user-images.githubusercontent.com/109066311/178226764-9bc0b219-5c22-4ebb-a6db-b13c47b610af.png)

Thanks a lot.

**Comment by btry** [comment]
Hi

I reproduce : I get a blank modal window to alert about a problem. It appears that GLPI does not allows file uploads when there is no session (aka user is not logged in).

From what I see, this question type should fail also in GLPI 9.5 for the same reason. I think this question type was allowed in public forms by mistake. Did you successfully use fiel uploads with a public form in an earlier version of GLPI ?

**Comment by dewuer** [comment]
Hi,

I can also confirm that in glpi (version 9.5.7) it was possible to add an attachment in formcreator plugin (version 2.12.5).

See below PrtScr, please.

![docs on glpi](https://user-images.githubusercontent.com/34125740/178241481-3e002c91-f67c-4367-9c05-3e978fd0867d.png)

**Comment by btry** [comment]
Hi @dewuer 

Is your form used without being logged in ?

**Comment by dewuer** [comment]
Yes, this was while I was not logged in.

**Comment by Gitnor77** [comment]
It works, the attachment adds.
Great, thanks a lot.

**Comment by btry** [comment]
Thank you for your feedback, the fix is ready for the final release.

**Comment by alexmicontini** [comment]
Hi,
When will stable version 2.13.0 be released?
Cheers

**Comment by btry** [comment]
Hi

We are working on the last step : a fluent migration. 

We want to provide a DB integrity check prior an upgrade starting from 2.13.0, and the feature helped to discover possible inconsistencies coming from very old instances of Formcreator. We are fixing those problems to have a good state for future upgrades.

**Comment by alexmicontini** [comment]
Hi @btry , 
thank you very much for answering.

**Comment by Gitnor77** [comment]
Hi,
I have the same problem with [GLPI 10.0.5] and [formcreator 2.13.2].

![image](https://user-images.githubusercontent.com/109066311/201017207-1d18f82a-45ee-4511-a0d0-817c9293d0e6.png)

**Comment by btry** [comment]
Hi @Gitnor77 

Please try this fix https://github.com/pluginsGLPI/formcreator/pull/3097

Once applied you have to use the console to upgrade the plugin: bin/console plugin:install formcreator -f -p force-upgrade -p skip-db-check

You will be prompted for a superadmin user account.

Once done, check that you have a new account created in GLPI : formcreator_public_user_ (followed with some random chars).

**Comment by Gitnor77** [comment]
Hi,
I have done, but... 
* removed all forms,
* forms are not available at all -> http error 500

A new user has been added to the list
![image](https://user-images.githubusercontent.com/109066311/205849329-8af519fa-e312-4dac-a19c-a1b3f54a53c2.png)

**Comment by Gitnor77** [comment]
> EDIT: for convenience, here is a build with the patch: [formcreator_2.13.4-dev.zip] -> #3095

On this version it works, maybe I change something wrong earlier.

**Comment by btry** [comment]
Hi

If you manually applied the patch (editing all files) then you took risks. Always use the patch tool.

Do you confirm that file uploads on public forms now work ? Did you checked that files are readable in the generated ticket and the form answer ?

**Comment by Gitnor77** [comment]
I will confirm tomorrow, the test version will be upgrade to 10.0.5 and I do tests.

**Comment by Gitnor77** [comment]
Looks ok, the attachment adds.

**Comment by btry** [comment]
Hi I did an update to the patch . Full instructions to apply it again are in this [comment](https://github.com/pluginsGLPI/formcreator/issues/3076#issuecomment-1353528549).

Please try it and feedback. I'm waiting to solve this problem to release 2.13.4.

**Comment by Gitnor77** [comment]
Thank you for your comment. I close this issue.
