### ISSUE TITLE
PHP warning : null passed to str_replace

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#2874]
@btry 

In the SQL file I didn't find anything related to the plugin

SQL-Errors.log
![image](https://user-images.githubusercontent.com/104385269/178600207-752afc5c-d495-4c33-9190-4317f6d02796.png)

In the PHP file I found this error several times, I don't know exactly what to look for, I'm sorry if it's not that, I'm still starting in this GLPI world, if not and can you guide me what I should look for I'd appreciate it.

php-errors.log
![image](https://user-images.githubusercontent.com/104385269/178601216-83e09638-3490-4ace-8e26-10daf8d76064.png)

`[2022-07-12 21:17:30] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/html/glpi/plugins/formcreator/inc/formanswer.class.php at line 1215
  Backtrace :
  plugins/formcreator/inc/formanswer.class.php:1215  str_replace()
  plugins/formcreator/inc/issue.class.php:830        PluginFormcreatorFormAnswer->parseTags()
  plugins/formcreator/hook.php:317                   PluginFormcreatorIssue::giveItem()
  src/Plugin.php:1550                                plugin_formcreator_giveItem()
  src/Search.php:6298                                Plugin::doOneHook()
  src/Search.php:1687                                Search::giveItem()
  src/Search.php:447                                 Search::constructData()
  plugins/formcreator/inc/issue.class.php:1072       Search::getDatas()
  :                                                  PluginFormcreatorIssue::nbIssues()
  src/Dashboard/Grid.php:955                         call_user_func_array()
  ajax/dashboard.php:139                             Glpi\Dashboard\Grid->getCardHtml()
`

_Originally posted by @LuizRicarte in https://github.com/pluginsGLPI/formcreator/issues/2873#issuecomment-1182532408_

**Comment by btry** [comment]
Hi @LuizRicarte

I created this new issue for the PHP Warning you discovered : this error is not related to your original issue, aned needs to be processed separately.

Identify the ID of the form then execute the following SQL query to list the name of all questions of the form. I'm suspecting that a question name contains NULL.

```sql
SELECT q.id, q.name 
FROM glpi_plugin_formcreator_questions AS q
LEFT JOIN glpi_plugin_formcreator_sections AS s ON (q.plugin_formcreator_sections_id = s.id)
LEFT JOIN glpi_plugin_formcreator_forms AS f ON (s.plugin_formcreator_forms_id = f.id)
WHERE f.id=1;
```

**Comment by btry** [comment]
Hi @LuizRicarte

The above fix should solve the php warning you reported yesterday. It is not related to the original issue then I craeted this one to avoid messing the initial thread.

**Comment by LuizRicarte** [comment]
@btry 

After the correction the error no longer appears in the php-error.log

Thanks.

**Comment by btry** [comment]
Hi

Thank you for your feedback.
