### ISSUE TITLE
Création de réponse malgré le bouton d'envoi non visible

### ISSUE THREAD

**Issue by SkoEdi** [pluginsGLPI/formcreator#2876]
**Describe the bug**
J'ai un formulaire qui demande un nom de domaine, si le nom de match pas un regex, je désactive le bouton pour envoyer le formulaire et tous les autres champs pour n'afficher qu'un message d'erreur via une question "Description".
Si je rentre un nom de domaine non valable et que je fais "enter",  le formulaire et ticket est quand même créé

**To Reproduce**
Créer un formulaire avec une question dont la réponse désactive ou non le bouton "send" puis faire "enter", la présence d'un target n'est pas nécessaire.
Ex: 
1. new form test
2. questions
3. ajouter la question test de type radios avec pour valeur vrai ou faux
4. pour le bouton send, ajouter la condition: display enless ma question test = faux
5. Allez dans le preview et cocher faux
6. faire "enter", le formulaire va être créé

Attention, si on clique ailleurs après avoir choisi faux mais avant de faire "enter", le "enter" a le comportement attendu car la sélection n'est plus sur une question

**Expected behavior**
Aucune réaction ne devrait se produire

**Screenshots**
![Config questions](https://user-images.githubusercontent.com/109290859/179218251-5f98f76b-a8eb-4aae-9b04-8bc13033d816.png)
![Configuration question test](https://user-images.githubusercontent.com/109290859/179218254-23432383-5f54-486a-89df-1e78b6ba02cb.png)
![etat test vrai](https://user-images.githubusercontent.com/109290859/179218260-e262401a-7bb5-4933-a4fa-dced557655d6.png)
![etat test faux](https://user-images.githubusercontent.com/109290859/179218258-9922fe7b-3f51-4e82-a831-21c302e9ea6b.png)
![creation réponse faux](https://user-images.githubusercontent.com/109290859/179218257-6bf77dc4-2916-44bb-99c5-3f0e4a875fc3.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version: 10.0.2
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
        news                 Name: Alerts                         Version: 1.10.4     State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	editus               Name: Editus AzureDevOps             Version: 1.0        State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.1 State: Enabled                                 
		Install Method: Manual
	fpsoftware           Name: FP Software                    Version: 2.0.0      State: Enabled                                 
		Install Method: Manual

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser [e.g. chrome, safari]: Edge
 - Version [e.g. 22]: 103.0.1264.49

**Smartphone (please complete the following information): N/A

**Additional context**
N/A

**Comment by btry** [comment]
Bonjour

Un peu ennuyeux comme souci; je regarde ça.

**Comment by btry** [comment]
Essayez ce fix; ça fonctionne de mon côté.

**Comment by SkoEdi** [comment]
malheureusement, aucun changement

**Comment by SkoEdi** [comment]
Je viens de tester à nouveau, le bug est toujours présent sur Edge mais il ne se produit pas sur Google Chrome. Je n'avais pas testé sur Chrome avant donc je ne sais pas si il se produisait déjà ou non

**Comment by btry** [comment]
Vous pouvez regarder dans les outils développeur de Edge si vous avez des erreurs javascript après chargement du formulaire ou après appui sur la touche entrée ?

**Comment by btry** [comment]
Cette erreur apparaît dans Chrome également ?

**Comment by SkoEdi** [comment]
non, aucune erreur sur Chrome

**Comment by btry** [comment]
Donc un navigateur trouve la fonction, et pas l'autre... :thinking:

**Comment by SkoEdi** [comment]
J'ai eu une mise à jour d'edge, la 103.0.1264.62 mais même comportement

**Comment by btry** [comment]
Je tente de reproduire dans la journée.

**Comment by btry** [comment]
Pas d'erreur de mon côté avec Edge (sous Linux) Version 103.0.1264.62 (Version officielle) (64 bits) . Le patch semble bien fonctionner.

**Comment by SkoEdi** [comment]
Bon, le problème est peut être lié à autre chose du coup. Merci pour la réactivité et super plugin en tout cas

**Comment by btry** [comment]
Si lors de votre remontée de bug vous utilisiez Edge, un simple F5 pour rafraichir le cache résoudra probablement le souci .
