### ISSUE TITLE
Update erro

### ISSUE THREAD

**Issue by glpibr** [pluginsGLPI/formcreator#2878]
Plugin is showing error during the update process from version 2.13.0-alpha4 to 2.13.0-rc.1:

Unknown column 'is_search_issue_visible' in 'field list'

![image](https://user-images.githubusercontent.com/22614882/179299271-f7e16901-28d1-44c8-b1a9-eba7f3536ddb.png)

![image](https://user-images.githubusercontent.com/22614882/179299486-159acd69-23d9-4f6b-8f9e-fa313bd8d865.png)

performing a clean install works perfectly

**Comment by btry** [comment]
Hi

I'm working on a branch to fix database schema inconsistencies whik may have occurred ling ago but left undiscovered in some instances. 

I think you should try it : https://github.com/pluginsGLPI/formcreator/pull/2863

Use glpi 1.0.2, Upgrade Formcreator as usual. It will fix many inconsistencies found so far, then compare the tables against the expected schema from a fresh install. If something is still wrong, the you will have to enable the plugin and run a CLI command (given in the error message) to show the inconsistences. 

Your feedback will be useful to improve this branch.

**Comment by btry** [comment]
A last word : the branch is the last task before releasing the stable version 2.13.0 !

**Comment by btry** [comment]
Hi

just in case here is a build of the above mentioned branch

[glpi-formcreator-2.13.0-dev.zip](https://github.com/pluginsGLPI/formcreator/files/9129934/glpi-formcreator-2.13.0-dev.zip)

**Comment by btry** [comment]
I'm checking the column. I see it has been intrroduced  in 2.13.0, then I'm suspecting that you did an upgrade from a previous 2.13.0-alpha or 2.13.0-beta version. Please confirm.

**Comment by glpibr** [comment]
Hi, thanks for the interactions!
In this migration I'm testing, I went from GLPi 9.5.8 with formcreator 2.12.4 to GLPi 10.0.2 with formcreator 2.13.0-rc.1

If you need more information, I'm available.

Saudações,
[https://verdanatech.com/wp-content/uploads/2021/05/halex.png]
Halexsandro Sales

CTO

Verdanatech Soluções em TI



[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
81 3091 42 52<tel:81%203091-4252> | 81 9 8802 30 11<tel:81%2098802-3011>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
***@***.******@***.***>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.verdanatech.com
www.verdanadesk.com<http://www.verdanadesk.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
Rua da Guia, n. 117,
Recife – PE , CEP: 50.030-210



[https://verdanatech.com/wp-content/uploads/2021/05/logos-footer.png]   [facebook] <https://www.facebook.com/verdanatech>

[linkedin]<https://www.linkedin.com/company/verdanatech/>

[instagram]<https://www.instagram.com/verdanatech/>




________________________________
De: btry ***@***.***>
Enviado: segunda-feira, 18 de julho de 2022 03:44
Para: pluginsGLPI/formcreator ***@***.***>
Cc: Halexsandro Sales ***@***.***>; Author ***@***.***>
Assunto: Re: [pluginsGLPI/formcreator] Update erro (Issue #2878)


I'm checking the column. I see it has been intrroduced in 2.13.0, then I'm suspecting that you did an upgrade from a previous 2.13.0-alpha or 2.13.0-beta version. Please confirm.

**Comment by glpibr** [comment]
Hello friend,
Sorry for the delay, but we have very high demands here at the office.
I performed the test with the new release (RC2).
This time, the process went all the way with only 1 post-installation notification.
I still haven't had time to use the plugin to analyze whether or not there are BUGs. I will now start this new stage.

But follow the message for you.

Thanks for the effort!


[cid:7e16c83c-0a71-4471-abfa-7ab324ddc18b]

Saudações,
[https://verdanatech.com/wp-content/uploads/2021/05/halex.png]
Halexsandro Sales

CTO

Verdanatech Soluções em TI



[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
81 3091 42 52<tel:81%203091-4252> | 81 9 8802 30 11<tel:81%2098802-3011>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
***@***.******@***.***>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.verdanatech.com
www.verdanadesk.com<http://www.verdanadesk.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
Rua da Guia, n. 117,
Recife – PE , CEP: 50.030-210



[https://verdanatech.com/wp-content/uploads/2021/05/logos-footer.png]   [facebook] <https://www.facebook.com/verdanatech>

[linkedin]<https://www.linkedin.com/company/verdanatech/>

[instagram]<https://www.instagram.com/verdanatech/>




________________________________
De: btry ***@***.***>
Enviado: quarta-feira, 20 de julho de 2022 08:30
Para: pluginsGLPI/formcreator ***@***.***>
Cc: Halexsandro Sales ***@***.***>; Author ***@***.***>
Assunto: Re: [pluginsGLPI/formcreator] Update erro (Issue #2878)


Hi

Today I released the version 2.13.0-rc.2 . It contains some bugfixes and a DB integrity check and is very close to the biuld I shared here 2 days ago. After copying the latest version of the plugin, use the fllowing CLI command to re-run the upgrade. It may fix some inconsistencies in the DB, and will let you know of some are still present

bin/console glpi:plugin:install formcreator -f -p force-upgrade

⚠️ This command must be used only upon request of a maintainer of the project.

**Comment by btry** [comment]
Hi

Upgrading from a stable version probably helped. If you have time, please show the post-installation notification you had.

**Comment by IP-V15** [comment]
> Hi
> 
> Today I released the version 2.13.0-rc.2 . It contains some bugfixes and a DB integrity check and is very close to the biuld I shared here 2 days ago. After copying the latest version of the plugin, use the fllowing CLI command to re-run the upgrade. It may fix some inconsistencies in the DB, and will let you know of some are still present
> 
> `bin/console glpi:plugin:install formcreator -f -p force-upgrade`
> 
> ⚠️ This command must be used only upon request of a maintainer of the project.

Hello
This commande was resolve my same problem.

**Comment by btry** [comment]
Hi

Then, I assume we can close this issue. Thank you for your fedback.
