### ISSUE TITLE
Technical Group performs not rule

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/formcreator#288]
Hi,

I created a form that the user selects the Entity and Group must follow the Ticket and together created a rule like the image below. The category is associated with the ticket template and the Technical Group is the form.

So that in this way this set, the rule is not enforced at all. Now if I put the Technical Group in the Ticket template along with the dai category yes runs the rule.

![image](https://cloud.githubusercontent.com/assets/2439826/19280408/2622966a-8fbc-11e6-94f6-e8d7610747fc.png)

![image](https://cloud.githubusercontent.com/assets/2439826/19280580/f8811000-8fbc-11e6-9bc6-f2451a09aab4.png)

![image](https://cloud.githubusercontent.com/assets/2439826/19280477/748d52fe-8fbc-11e6-98f1-4cbc2c4b1577.png)

**Comment by btry** [comment]
Hi

Do you have opportunity to test with Formcreator 2.6.0 (branch develop to be released this week) and see if your problem still occurs ? 

Other rules related issues seems fixed (thanks to code refactor).

**Comment by btry** [comment]
Hi

I was informed  that #927 solves an issue with business rules on tickets. This PR is still in progress, and will be integrated in 2.6.3

**Comment by btry** [comment]
Closing as I don't have any feedback. If the issue still happens, please test #927 in a testing environment and feedback.
