### ISSUE TITLE
 ticket without requester

### ISSUE THREAD

**Issue by wc55** [pluginsGLPI/formcreator#2883]
**Describe the bug**

When the target's requestor is configured to be the user indicated in a question, the ticket is generated with no requester:

**To Reproduce**
Obs:
- Busines Rules for tickets: disabled

- Group in charge of the hardware: none (form itil category)

- Form target:
 
![image](https://user-images.githubusercontent.com/106084399/179776370-186eefc7-9b09-4993-a18c-390249307218.png)

1. Go to a form:
![image](https://user-images.githubusercontent.com/106084399/179775419-42fa3d6a-6e74-4453-91f1-8cb6994567e9.png)

2. Choose a requester in an issue:

![image](https://user-images.githubusercontent.com/106084399/179776101-d89a363c-ead2-4ae2-8f2a-d21dc04e2f2d.png)

4. Open the ticket.

-----

Technician screen:

1. Ticket screen
![image](https://user-images.githubusercontent.com/106084399/179778374-d9a0185f-0365-4228-986f-71a03c6f4452.png)

2. Ticket Information:

![image](https://user-images.githubusercontent.com/106084399/179779114-1f275fcf-0d76-41e2-8bca-08d4ac449f5c.png)

**Expected behavior**

The ticket should be opened and the author should be the user indicated in the question

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.2
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page):

fields               Name: Additional fields              Version: 1.17.0     State: Installed / not activated       Install Method: Manual
behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                        Install Method: Manual
datainjection        Name: Data injection                 Version: 2.11.2     State: Installed / not activated   Install Method: Manual
formcreator          Name: Form Creator                   Version: 2.13.0-rc.1 State: Enabled                        Install Method: Manual
itilcategorygroups   Name: Grupos ItilCategory            Version: 2.5.0      State: Installed / not activated         Install Method: Manual

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome 103.0.5060.114 (Versão oficial) 64 bits

**Additional context**

Busines Rules for tickets: disabled

Group in charge of the hardware: none

Even with rules and other settings, the error happens

**Comment by btry** [comment]
Hi

I don't reproduce. I'm suspecting this issue was already solved recently, I merely remember about a similar report.

I released right now a version 2.13.0-rc.2 with additional upgrade checks and some fixes. You should check if it works for you. I'm waiting for your feedback.

**Comment by wc55** [comment]
Hi

I did the tests with version 2.13.0-rc.2 and the problem was solved.

Thanks

**Comment by btry** [comment]
Hi

Great, thank you for your feedback; I close this issue.
