### ISSUE TITLE
"Build passing" link

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/formcreator#289]
Hello,

The "build passing" (or failing :p) image points to image itself. Should not this link point to lastest build status?

**Comment by btry** [comment]
Hi

The content of README.md is 

```
![Build Status](https://travis-ci.org/pluginsGLPI/formcreator.svg)
```

Then I guess this is something done by Github itself when showing the content ?

**Comment by trasher** [comment]
Link provided from travis looks like: `[![Build Status](https://travis-ci.org/pluginsGLPI/formcreator.svg?branch=master)](https://travis-ci.org/pluginsGLPI/formcreator)`[![Build Status](https://travis-ci.org/pluginsGLPI/formcreator.svg?branch=master)](https://travis-ci.org/pluginsGLPI/formcreator)

**Comment by btry** [comment]
Do you prefer this way ?

**Comment by trasher** [comment]
LGTM ;) :+1:
