### ISSUE TITLE
BUG - Regular Expression with Textarea

### ISSUE THREAD

**Issue by SkoEdi** [pluginsGLPI/formcreator#2895]
**Describe the bug**
Un champs de type textarea n'est plus affiché si une condition "match regular expression" est appliquée à une description faisant appelle à la valeur du textarea

**To Reproduce**

1. créer une checkbox avec une valeur "visible"
2. créer une textarea qui n'est visible que si la valeur de la checkbox est à "visible"
3. creer une description qui ne s'affiche que si l'expression régulière suivante est vérifiée: /^test/ dans la textarea
4. Allez dans la preview et cocher la valeur visible

**Expected behavior**
Quand on coche la valeur "visible", la textarea devrait apparaitre

**Screenshots**
![image](https://user-images.githubusercontent.com/109290859/181028387-0e990309-fc33-4553-8d08-c4f93dfef042.png)
![image](https://user-images.githubusercontent.com/109290859/181028428-6f224ea2-d078-4c2b-9029-651efba918b1.png)
![image](https://user-images.githubusercontent.com/109290859/181028474-d056f25c-2f95-41ee-929f-f03add9f1909.png)
![image](https://user-images.githubusercontent.com/109290859/181028526-ac7c187f-7257-4f7f-97eb-d40bed09166f.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version: 10.0.2
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page):
        news                 Name: Alerts                         Version: 1.10.4     State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	editus               Name: Editus AzureDevOps             Version: 1.0        State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.1 State: Enabled                                 
		Install Method: Manual
	fpsoftware           Name: FP Software                    Version: 2.0.0      State: Enabled                                 
		Install Method: Manual

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22]: 103.0.1264.71

**Smartphone (please complete the following information):**

**Additional context**
Si j'affiche tout le temps la textarea, la description est tout le temps visible alors qu'elle ne devrait l'être que si la regular expression est vrai

**Comment by btry** [comment]
Bonjour

Attention avec les champs textarea. Ils sont enrichis et correspondent a du code HTML. Utilisez le code source de leur contenu pour mettre au point vos expressions régulières.

Extra : Si vous voulez utiliser des conditions sur un textarea, un patch a été versé cette semaine pour gérer ce cas d'utilisation. Appliquez le si vous êtes dans cette situation.

**Comment by SkoEdi** [comment]
Je n'arrive pas a trouver le patch, dans le doute j'ai mis à jour vers la rc2 mais sans changement.
Est-ce que vous pourriez me donner le lien vers le patch ?

**Comment by btry** [comment]
Bonjour
Le patch est ici: https://github.com/pluginsGLPI/formcreator/pull/2889

**Comment by SkoEdi** [comment]
Bonjour, je viens d'appliquer le patch mais sans changement.
Ma description a bien une regex qui prends en charge les balises html mais même si ma condition était fausse, cela ne devrait pas empêcher de faire apparaitre le champ textarea ni faire disparaitre le bouton send sur lequel je n'ai mis aucune condition

**Comment by btry** [comment]
J'ai trouvé: appliquez #2896 and dites moi si ça fonctionne mieux. Plusieurs types de questions ont été corrigées.

**Comment by SkoEdi** [comment]
Le bug n'est plus présent mais la détection du regex sur le champs description ne semble toujours pas fonctionné.
je rentre le mot test dans le textarea et la condition regex /^<p>test/ devrait être validée et afficher mon champs description mais ce n'est pas le cas. Est-ce que ça fonctionne chez vous?

**Comment by btry** [comment]
C'est normal : si votre textarea vaut  `Test` (tel qu'on le voit à l'écran) alors sa valeur réelle au moment de la comparaison est probablement `<p>Test</p>` (probablement car selon ce qui a été fait dans la zone de texte les balises HTML peuvent être différentes).

Votre requête devrait plutôt être quelque chose comme `/^<p>Test/`

**Comment by SkoEdi** [comment]
Désolé, je me suis trompé en mettant mon expression régulière. Je mets effectivement /^<p>test/ mais le champ description n'est pas visible

**Comment by btry** [comment]
J'ai modifié le patch :  ajoutez ce commit: https://github.com/pluginsGLPI/formcreator/pull/2896/commits/3299a1eb973c3cee503d2e0d96d45773b8c4acad

**Comment by SkoEdi** [comment]
Aucun changement pour moi

**Comment by btry** [comment]
Pourtant ça fonctionne chez moi 

![image](https://user-images.githubusercontent.com/14139801/181220549-c93beb5e-727c-451c-8755-0394aa0bb83b.png)


![image](https://user-images.githubusercontent.com/14139801/181220399-65456c6c-dbc1-42bb-9225-d248216b1d6e.png)


![image](https://user-images.githubusercontent.com/14139801/181220635-b9f05ee3-ca8d-45e4-9751-08adf48e7c2e.png)

![image](https://user-images.githubusercontent.com/14139801/181220480-d0bbba1a-c553-44e6-9afb-201403d99e86.png)

Vérifiez le code source de votre zone de texte pour voir si vous avez bien des balises HTML P

**Comment by SkoEdi** [comment]
Le formulaire est rempli avec test
![image](https://user-images.githubusercontent.com/109290859/181221350-af480ea3-4282-47ce-b4c8-0fc77a3488ef.png)
Pour la description, la condition est: caché sauf si textarea match /^<p>test/
![image](https://user-images.githubusercontent.com/109290859/181221486-154b25dc-9a10-4192-bc28-c6d350a7f8ad.png)
Mais la description n'est pas visible
![image](https://user-images.githubusercontent.com/109290859/181221741-673f676a-6c9b-4e67-9188-e4ca74c2c909.png)
Si je regarde la console au moment d'accèder à la page, j'ai une erreur, log en attach
[glpi-test.editushome.lu-1658916493064.log](https://github.com/pluginsGLPI/formcreator/files/9197339/glpi-test.editushome.lu-1658916493064.log)

**Comment by btry** [comment]
Comment appliquz vous les patchs ? Vous utilisez bien git ou l'outil patch ?

**Comment by SkoEdi** [comment]
Je fais les modifications manuellement dans les fichiers en faisant du copier/coller pour les lignes concernées

**Comment by btry** [comment]
Il est facile d'introduire des erreurs en procédant ainsi. Réinstallez Formcreator RC.2 à partir de son archive, puis appliquez tous les patchs. Pour les télécharger ajoutez .diff à la fin des URL de chacun d'eux.

Ensuite rendez vous dans le dossier de Formcreator et pour chacun des patchs faites les étapes suivantes
- `patch -p1 --dry-run < path/to/patch.diff `
- si le patch ne s'applique pas correctement en simulation (conflits par exemple) revenez ici avec le log
- si la simulation réussit faites `patch -p1 < path/to/patch.diff ` (la meme chose, sans `--dry-run`)

**Comment by SkoEdi** [comment]
Le 2889 s'est appliqué correctement mais une erreur est arrivée sur le deuxième:
Hunk #1 FAILED at 240.
1 out of 1 hunk FAILED
Concernant les logs, je n'ai trouvé que le .rej est-ce suffisant ?:
--- inc/field/textareafield.class.php
+++ inc/field/textareafield.class.php
@@ -240,7 +240,7 @@ public function lessThan($value): bool {
    }
 
    public function regex($value): bool {
-      return (preg_match($value, $this->value) === 1) ? true : false;
+      return (preg_match(Sanitizer::unsanitize($value), $this->value) === 1) ? true : false;
    }
 
    public function isPublicFormCompatible(): bool {

**Comment by btry** [comment]
Ah, oui, c'est normal : le 2e a été rajouté à #2889. Du coup il est déjà appliqué. Vous pouvez le vérifier dans le fichier concerné.

**Comment by SkoEdi** [comment]
J'ai appliqué les patchs via la commande mais sans changement
le code du textarea correspond à ma regex mais n'affiche pas la description
J'ai essayé en modifiant ma regex à `/test/` du coup cela devrait afficher la description peut importe ce qui se trouve avant ou apres le mot test. Mais même comme ça la description ne s'affiche pas.
J'ai testé la même regex mais avec un champ text et là ça fonctionne sans problème

**Comment by btry** [comment]
Appliquez ce patch 

```diff
diff --git a/inc/field/textareafield.class.php b/inc/field/textareafield.class.php
index 0b89ddb5..1007c62d 100644
--- a/inc/field/textareafield.class.php
+++ b/inc/field/textareafield.class.php
@@ -240,6 +240,7 @@ class TextareaField extends TextField
    }
 
    public function regex($value): bool {
+      Toolbox::logError('textarea compare: "' . Sanitizer::unsanitize($value) . '" against "' . $this->value . '"');
       return (preg_match(Sanitizer::unsanitize($value), $this->value) === 1) ? true : false;
    }
 
```

Il génèrera dans php-errors.log des entrées où on verra les 2 membres de la comparaison par regex. Attention : il ca y avoir beaucoup d'écritures. Enlevez le patch une fois le souci résolu.

**Comment by SkoEdi** [comment]
voila les entrées dans le log:
```
[2022-07-27 15:01:34] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\TextareaField::regex() in /var/www/html/plugins/formcreator/inc/field/textareafield.class.php line 242
textarea compare: "/test/" against ""  {"user":"977@dcsvt-glpi"} 
[2022-07-27 15:01:39] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\TextareaField::regex() in /var/www/html/plugins/formcreator/inc/field/textareafield.class.php line 242
textarea compare: "/test/" against ""  {"user":"977@dcsvt-glpi"} 
```

**Comment by btry** [comment]
Bonjour

Non, il n'a ps récupéré votre contenu; J'ai trouvé un souci ces derniers jours sur la surveillance des textarea pour les comparaisons. Ajoutez ce patch et voyez ce qui s'inscrit dans les logs : https://github.com/pluginsGLPI/formcreator/commit/9fb70edb12324e8d1be5ced762bb8eaaba445514

**Comment by SkoEdi** [comment]
C'est bon, c'est fonctionnel maintenant:
```
[2022-07-28 16:33:04] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\TextareaField::regex() in /var/www/html/plugins/formcreator/inc/field/textareafield.class.$
textarea compare: "/test/" against "<p>test</p>"  {"user":"977@dcsvt-glpi"}
```

**Comment by SkoEdi** [comment]
Bug corrigé:
![image](https://user-images.githubusercontent.com/109290859/181562411-2b2848bf-c4cd-4047-b4a2-e7f58af67681.png)

**Comment by btry** [comment]
Bonjour

Merci pour le retour, je fusionne les patches
