### ISSUE TITLE
Blank screen when not filling mandatory item

### ISSUE THREAD

**Issue by pedroigor17** [pluginsGLPI/formcreator#2902]
GLPI 10.0.2
Formcreator: 2.13.0-rc2

When you fail to complete a required item or attach a document and submit it. The system displays a blank screen as shown in the attachment instead of carrying out the validation and displaying the return. The error log returns the error:

```
[2022-07-28 10:18:05] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "_formcreator_field_2042" in /var/www/html/gra/plugins/formcreator/inc/field/filefield.class.php at line 154
  Backtrace :
  plugins/formcreator/inc/formanswer.class.php:1277  GlpiPlugin\Formcreator\Field\FileField->isValid()
  plugins/formcreator/inc/formanswer.class.php:718   PluginFormcreatorFormAnswer->validateFormAnswer()
  src/CommonDBTM.php:1262                            PluginFormcreatorFormAnswer->prepareInputForAdd()
  plugins/formcreator/front/form.form.php:140        CommonDBTM->add()
  
[2022-07-28 10:18:05] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/gra/plugins/formcreator/inc/field/filefield.class.php at line 154
  Backtrace :
  ...s/formcreator/inc/field/filefield.class.php:154 count()
  plugins/formcreator/inc/formanswer.class.php:1277  GlpiPlugin\Formcreator\Field\FileField->isValid()
  plugins/formcreator/inc/formanswer.class.php:718   PluginFormcreatorFormAnswer->validateFormAnswer()
  src/CommonDBTM.php:1262                            PluginFormcreatorFormAnswer->prepareInputForAdd()
  plugins/formcreator/front/form.form.php:140        CommonDBTM->add()
  
[2022-07-28 10:18:46] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key 0 in /var/www/html/gra/plugins/formcreator/inc/field/filefield.class.php at line 135
  Backtrace :
  plugins/formcreator/inc/formanswer.class.php:1065  GlpiPlugin\Formcreator\Field\FileField->moveUploads()
  src/CommonDBTM.php:1305                            PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:140        CommonDBTM->add()
```
![Captura de Tela (329)](https://user-images.githubusercontent.com/104610195/181523886-9698338e-a98f-43e8-afca-0f7aec7fcea6.png)

**Comment by btry** [comment]
Hi

Please test the above fix and feedback.

**Comment by pedroigor17** [comment]
Good afternoon! The failure with the blank screen worked, however the system continues without validating unfilled mandatory fields. Reload the page without the alert.

Log:
[2022-08-05 12:29:17] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key 0 in /var/www/html/gra/plugins/formcreator/inc/field/filefield.class.php at line 135
  Backtrace :
  plugins/formcreator/inc/formanswer.class.php:1057  GlpiPlugin\Formcreator\Field\FileField->moveUploads()
  src/CommonDBTM.php:1298                            PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/front/form.form.php:140        CommonDBTM->add()

https://user-images.githubusercontent.com/104610195/183114409-a8609864-3dd7-4c95-94fb-c660087c8aaf.mp4

**Comment by btry** [comment]
Hi

I tried a simple form with a text field (mandatory) and a file field (not mandatory), based on your video. If I submit the form keeping the text field empty I do have a message.

![image](https://user-images.githubusercontent.com/14139801/183354204-a9f4add2-8fc1-4685-9f7e-356b8f08edfd.png)

Try tu update the plugin to the latest revision of the branch support/2.13.0 and tell if it works better.

**Comment by pedroigor17** [comment]
Good afternoon! Error was in GLPI which I managed to fix. System is in perfect working order now. Thank you very much!

**Comment by btry** [comment]
Hi

If you had to modify the code of GLPI, please check if it was not already solved and create pull request to the project. You may also mention you PR here for documentation purpose th help other people who encounteer your problem.
