### ISSUE TITLE
issue creating forms

### ISSUE THREAD

**Issue by killmasta93** [pluginsGLPI/formcreator#2906]
**Describe the bug**
Hi Currently installed the form creator when i create does not let me save does not show any buttons?
**To Reproduce**
1. Go to 'home--administration--forms'
2. Click on '+ '
3. Scroll down to 'to find the save button did not find it'

**Screenshots**
![image](https://user-images.githubusercontent.com/13953629/182056148-59959a92-2b3f-4a64-9fb8-45a5e686e823.png)

**GLPI / Plugins 4.2.0
- GLPI version 9.5.2

Thank you

**Comment by btry** [comment]
Hi

You probably have an error in sql-errors.log, php-errors.log or in the errors log of your http server. Can you show it ? Select only those related to the problem. put it ( or them) here avoiding screenshot. Text is better

**Comment by killmasta93** [comment]
sorry for the late reply, didnt get alerted, i was checking on the logs but didnt see anything, currently i have docker as GLPI
whats odd is that im using version 2.15.5 but on the webgui shows 2.15.4
![image](https://user-images.githubusercontent.com/13953629/185268380-cb1a5a25-d748-4539-bd75-e8f945d5f553.png)

**Comment by btry** [comment]
Hi

Let's check if you have a HTTP 500 response code : open the developer tools of your browser, and view the tab "Network". Next browse in GLPI to the form and reproduce the problem. You will find a HTTP request to common.tabs.php. This request loads a tab content. Check if this request ends with the code 200 or the code 500.

If you get a code 500, then there is a high chance to get a PHP backtrace in the HTTP server's log. This log is (by default and for debian based distros) in /var/log/apache/errors.log or /var/log/nginx/errors.log for Anache and Nginx respectively.

Without backtrace I cannot investigate further because I don't have enough clues to find the faulty code.

**Comment by killmasta93** [comment]
thank you so much for the reply, so i ran the following tests but did not find the in HTTP request the common.tabs.php attaching picture

![image](https://user-images.githubusercontent.com/13953629/185539861-01ca8a3b-803f-4143-89b2-6c4853588b5a.png)

**Comment by btry** [comment]
Hi

I found the reason. I missed the fact that your form does not exist yet. In this case there is no  HTTP request to common.tabs.php. Check instead the HTTP request form.form.php. 

It appears that the problem is near the display of the HTML inputs for users and group validators.

**Comment by killmasta93** [comment]
thank you so much reply, 
so when i click at the bottom

![image](https://user-images.githubusercontent.com/13953629/185809500-51e8cf68-1c22-4849-96f2-30282f383ae9.png)

and i get this 

```
scripts.js?v=2.12.4:2034 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at plugin_formcreator_changeValidators (scripts.js?v=2.12.4:2034)
    at HTMLSelectElement.onchange (form.form.php:1)
    at Object.trigger (base.min.js?v=9.5.2:25)
    at HTMLSelectElement.<anonymous> (base.min.js?v=9.5.2:25)
    at Function.each (base.min.js?v=9.5.2:14)
    at jQuery.fn.init.each (base.min.js?v=9.5.2:14)
    at jQuery.fn.init.trigger (base.min.js?v=9.5.2:25)
    at n.i.define.n.select (base.min.js?v=9.5.2:446)
    at s.<anonymous> (base.min.js?v=9.5.2:446)
    at s.i.define.n.invoke (base.min.js?v=9.5.2:446)
plugin_formcreator_changeValidators @ scripts.js?v=2.12.4:2034
onchange @ form.form.php:1
trigger @ base.min.js?v=9.5.2:25
(anonymous) @ base.min.js?v=9.5.2:25
each @ base.min.js?v=9.5.2:14
each @ base.min.js?v=9.5.2:14
trigger @ base.min.js?v=9.5.2:25
i.define.n.select @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
i.define.n.invoke @ base.min.js?v=9.5.2:446
i.define.n.trigger @ base.min.js?v=9.5.2:446
i.define.s.trigger @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
i.define.n.invoke @ base.min.js?v=9.5.2:446
i.define.n.trigger @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
dispatch @ base.min.js?v=9.5.2:25
m.handle @ base.min.js?v=9.5.2:25
scripts.js?v=2.12.4:2037 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at plugin_formcreator_changeValidators (scripts.js?v=2.12.4:2037)
    at HTMLSelectElement.onchange (form.form.php:1)
    at Object.trigger (base.min.js?v=9.5.2:25)
    at HTMLSelectElement.<anonymous> (base.min.js?v=9.5.2:25)
    at Function.each (base.min.js?v=9.5.2:14)
    at jQuery.fn.init.each (base.min.js?v=9.5.2:14)
    at jQuery.fn.init.trigger (base.min.js?v=9.5.2:25)
    at n.i.define.n.select (base.min.js?v=9.5.2:446)
    at s.<anonymous> (base.min.js?v=9.5.2:446)
    at s.i.define.n.invoke (base.min.js?v=9.5.2:446)
plugin_formcreator_changeValidators @ scripts.js?v=2.12.4:2037
onchange @ form.form.php:1
trigger @ base.min.js?v=9.5.2:25
(anonymous) @ base.min.js?v=9.5.2:25
each @ base.min.js?v=9.5.2:14
each @ base.min.js?v=9.5.2:14
trigger @ base.min.js?v=9.5.2:25
i.define.n.select @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
i.define.n.invoke @ base.min.js?v=9.5.2:446
i.define.n.trigger @ base.min.js?v=9.5.2:446
i.define.s.trigger @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
i.define.n.invoke @ base.min.js?v=9.5.2:446
i.define.n.trigger @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
dispatch @ base.min.js?v=9.5.2:25
m.handle @ base.min.js?v=9.5.2:25
scripts.js?v=2.12.4:2034 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at plugin_formcreator_changeValidators (scripts.js?v=2.12.4:2034)
    at HTMLSelectElement.onchange (form.form.php:1)
    at Object.trigger (base.min.js?v=9.5.2:25)
    at HTMLSelectElement.<anonymous> (base.min.js?v=9.5.2:25)
    at Function.each (base.min.js?v=9.5.2:14)
    at jQuery.fn.init.each (base.min.js?v=9.5.2:14)
    at jQuery.fn.init.trigger (base.min.js?v=9.5.2:25)
    at n.i.define.n.select (base.min.js?v=9.5.2:446)
    at s.<anonymous> (base.min.js?v=9.5.2:446)
    at s.i.define.n.invoke (base.min.js?v=9.5.2:446)
plugin_formcreator_changeValidators @ scripts.js?v=2.12.4:2034
onchange @ form.form.php:1
trigger @ base.min.js?v=9.5.2:25
(anonymous) @ base.min.js?v=9.5.2:25
each @ base.min.js?v=9.5.2:14
each @ base.min.js?v=9.5.2:14
trigger @ base.min.js?v=9.5.2:25
i.define.n.select @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
i.define.n.invoke @ base.min.js?v=9.5.2:446
i.define.n.trigger @ base.min.js?v=9.5.2:446
i.define.s.trigger @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
i.define.n.invoke @ base.min.js?v=9.5.2:446
i.define.n.trigger @ base.min.js?v=9.5.2:446
(anonymous) @ base.min.js?v=9.5.2:446
dispatch @ base.min.js?v=9.5.2:25
m.handle @ base.min.js?v=9.5.2:25
```

**Comment by btry** [comment]
Hi

The JS error happens after an other problem. It is probably a consequence of the missing parts in the page. Is there really nothing relevant in the logs serverside ?

**Comment by killmasta93** [comment]
thanks for the reply, i was checking the server logs on GLPI it was in another location finally found it and shows this

```
root@dockers:/glpi/html/glpi/files/_log# tail -f php-errors.log
[2022-08-21 16:45:46] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Session::getNewIDORToken() in /var/www/html/glpi/plugins/formcreator/inc/form.class.php at line 559
  Backtrace :
  inc/commonglpi.class.php:627                       PluginFormcreatorForm->showForm()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
```
as soon i click on the plugin shows this log which

**Comment by btry** [comment]
Hi

OK, You need to upgrade GLPI to the latest 9.5.8 version. The problem should be solved.

**Comment by killmasta93** [comment]
thank you again going to update to 10 and postback

**Comment by btry** [comment]
HI

This issue is obsolete, I close.
