### ISSUE TITLE
Error attaching table inside description - Erro ao anexar tabela dentro de descrição 

### ISSUE THREAD

**Issue by Vinicius4** [pluginsGLPI/formcreator#2919]
**Describe the bug**
Ao adicionar uma tabela em descrição, ficamos com varios '<br>' na formatação da pagina.

When adding a table in description, we are left with several '
' in page formatting.

![image](https://user-images.githubusercontent.com/17463200/183914398-9efb4f85-9558-409c-a196-2793cedc5d32.png)

Quanto vamos em pré-visualização, dentro do inspeção de elemento observamos a mudança de layout.

When we go in preview, inside the element inspection we observe the layout change.

![image](https://user-images.githubusercontent.com/17463200/183914857-70ef39fb-1731-4cd7-b8dc-aa08b3e0cd5d.png)

Pesquisarei por uma solução, caso encontre mando aqui para voçês.

Abraços.

I'll search for a solution, if I find it I'll send it here for you.

Hugs.

**Comment by btry** [comment]
Hi

Which version of Formcreator are you using ?

**Comment by Vinicius4** [comment]
Olá, 

Capturei a falha na Versão 2.13.0-rc.2 e testei novamente hoje na 2.13.0 e continuo com o erro.

Hello,

I caught the glitch in Version 2.13.0-rc.2 and retested it today on 2.13.0 and I still get the error.

**Comment by btry** [comment]
Hi

The problem is very likely caused by CSS of GLPI. When you edit your description question, the text is in a iframe with its own CSS rules. When the description is rendered the content inherits all CSS rules from GLPI.

**Comment by btry** [comment]
Try the above fix and feedback.

**Comment by btry** [comment]
Hi

Having no feedback I asume the fix worked for you. I close this issue.
