### ISSUE TITLE
Does not collect the data person from the question in ticket target

### ISSUE THREAD

**Issue by laurixia** [pluginsGLPI/formcreator#2921]
When in a form the question asks for an email and in the destination I add this value in the requester, observer or assigned with the person field from the question, when I generate the ticket this field appears empty.

**To Reproduce**
1. Go to 'any form with a question with a email type'
2. Click on 'target ticket and define requester actors as answer from a email type question'
3. Scroll down to ' after submit the form, the ticket will be created but the requester,observer or assigned is filled blank'

**Expected behavior**
For example, the user fills the question with your email This email could be used as requester, observer or assigned when the ticket are generated by the form.

**Screenshots**
![image](https://user-images.githubusercontent.com/26741776/184112449-8c319f46-c3a4-43e9-abe1-c6db4d0ef055.png)

![image](https://user-images.githubusercontent.com/26741776/184112384-e8154186-3e4a-4b50-b885-3757bda7ba8f.png)

![image](https://user-images.githubusercontent.com/26741776/184112651-93fed112-0c47-41d0-9f7e-de4f3d80840e.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.2
- Plugins: 
	tag                  Name: Administración de etiquetas    Version: 2.9.2      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertas                        Version: 1.10.4     State: Enabled                                 
		Install Method: Marketplace
	approvalbymail       Name: Approval by mail               Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	branding             Name: Branding                       Version: 1.3.1      State: Enabled                                 
		Install Method: Marketplace
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	fields               Name: Campos adicionales             Version: 1.17.1     State: Installed / not activated               
		Install Method: Marketplace
	screenshot           Name: Captura de pantalla            Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace
	collaborativetools   Name: Collaborative tools            Version: 1.2.2      State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Contadores de impresora        Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.7      State: Installed / not activated               
		Install Method: Marketplace
	addressing           Name: Direccionamiento IP            Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.2 State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.0.1      State: Installed / not activated               
		Install Method: Marketplace
	agentconfig          Name: GLPI Agent config              Version: 1.2.0      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.3      State: Enabled                                 
		Install Method: Marketplace
	itilcategorygroups   Name: Grupos de Categorias           Version: 2.5.0      State: Installed / not activated               
		Install Method: Marketplace
	metabase             Name: metabase                       Version: 1.3.0      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Mi Dashboard                   Version: 2.0.4      State: Installed / not activated               
		Install Method: Marketplace
	oauthsso             Name: oauthsso                       Version: 1.5.2      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.1      State: Not installed                           
		Install Method: Marketplace
	releases             Name: Releases                       Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.2      State: Not installed                           
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 64 bits
 - Browser :chrome Versión 104.0.5112.79 (Build oficial) (64 bits)

**Comment by btry** [comment]
Hi

Check the recent closed issues. One of them reports the same problem. A fix is provided.

**Comment by laurixia** [comment]
> Hi
> 
> Check the recent closed issues. One of them reports the same problem. A fix is provided.

Can you tell me the fix number, I can't find it.

**Comment by btry** [comment]
This one: https://github.com/pluginsGLPI/formcreator/pull/2894

I'm waiting for your feedback.

**Comment by laurixia** [comment]
> This one: #2894
> 
> I'm waiting for your feedback.
everything is now working, that´s great. Thank you so much.

**Comment by btry** [comment]
Hi

Great, then I close.

Thank you for the feedback.
