### ISSUE TITLE
Allow create the target ticket based on the response questions

### ISSUE THREAD

**Issue by OscarLoayzaB** [pluginsGLPI/formcreator#293]
Based on the response(s) of a form, create or not ticket destination automatically without validation.
Is to set the target ticket, the values ​​defined for one or more questions, that would be the condition to create a ticket from the form.
With the values ​​that the user completes the form. The saved configuration is checked, and if these match is included or excluded to create the ticket.
For this you must define in the form one way that allows the activation of this feature. If do not has activated, its operation would be the default.
This is a suggestion.
Thanks.

**Comment by Miminoux** [comment]
:+1:

**Comment by btry** [comment]
Hi

It looks like a feature implemented in this incoming contribution https://github.com/pluginsGLPI/formcreator/issues/416#issuecomment-282483326

**Comment by etiquet** [comment]
Thanks Btry, Hi Oscar this is a feature we implemented in a future PR just for one question. Still a bug to correct but should be interested let me know. ( on branch 0.90-1.3.4 )

**Comment by btry** [comment]
Hi

formcreator supports conditions to generate targets. Comapred to the PR submitted by a contributor, the plugin supports complex conditions.

Closing.
