### ISSUE TITLE
FormCreator 2.13 install in GLPI 10.0.2

### ISSUE THREAD

**Issue by grenona** [pluginsGLPI/formcreator#2930]
Hi team
I go to Plug.in , i see the icon FormCreator

It show one Icon brown, Saying We found update but your directory permission is not writable, please download and copy to /var/www/glpi/plugin

i did it, this is not doing nothing

i copy the result again in marketplace folder over the old formcreator folder

that work, but now it give me ICON (update available) i click on it, and the message is:

Task Completed. (0 seconds)

Unknown column 'conf.entities_id' in 'where clause'

![image](https://user-images.githubusercontent.com/88557992/185632296-2e9eab9b-eee4-4e33-8444-27a7f54e81a7.png)

**Comment by btry** [comment]
Hi

> It show one Icon brown, Saying We found update but your directory permission is not writable, please download and copy to /var/www/glpi/plugin
>
> i did it, this is not doing nothing

When you install a plugin in the plugins/ directory, make sure you don't have an other copy un marketplace/ directory.

> i copy the result again in marketplace folder over the old formcreator folder

This is risky because you overwrite a version of the plugin by an other. Always move the plugin out of GLPI then copy the new one in the target folder. 

> Unknown column 'conf.entities_id' in 'where clause'

Check if you have a related backtrace in the following files of glpi/files/_logs/
- migration_to_2.13.0.log
- php-errors.log
- sql-errors.log
.
Also tell from which version you are trying to upgrade.

**Comment by grenona** [comment]
Hi

Here is the log

Thanks

**Comment by btry** [comment]
I guess something went wrong when you pasted the log. I don't see it.

**Comment by grenona** [comment]
[warning_during_migration_to_2.8.1.log](https://github.com/pluginsGLPI/formcreator/files/9384640/warning_during_migration_to_2.8.1.log)
[warning_during_migration_to_1.3.2.log](https://github.com/pluginsGLPI/formcreator/files/9384641/warning_during_migration_to_1.3.2.log)
[sql_error.log](https://github.com/pluginsGLPI/formcreator/files/9384642/sql_error.log)
[php_error.log](https://gi
[migration_to_2.12.3.log](https://github
[migration_to_1.7.3.log](https://github.com/pluginsGLPI/formcreator/files/9384647/migration_to_1.7.3.log)
.com/pluginsGLPI/formcreator/files/9384646/migration_to_2.12.3.log)
thub.com/pluginsGLPI/formcreator/files/9384644/php_error.log)

**Comment by grenona** [comment]
i email again and also copy on comment above thanks

**Comment by btry** [comment]
The files warning_during_migration contains a different version. They should match an other plugin.

Sql_errors.log is a log from mysql or mariadb server. It is not possible that you found it in glpi/files/_logs/ folder.

There is no link for php_errors.log

Migration_to_1.7.3 is probably related to an other plugin.

Migration_to_2.12.3 does not have a link, and is probably related to the upgrade to an older version of the plugin.

Just check if the files contain relevant content for the upgrade issue and copy / paste only this relevant content here, between 2 triple-backquotes for better formatting.

**Comment by grenona55** [comment]
HI  i restart the full process, 
- Before doing upgrade i get this icon over fromcreator See picture
- I delete file under /var/www/html/glpi/marketplace/formcreator
- i copy the new one downloded from git hub
- restart apache
- the form option disaper from all memu
- and the icon i get is see second picture
- after the icon in plugin show this: 
Run composer install --no-dev in the plugin directory
Run yarn install --prod in the plugin directory
I did the first line, work ok
second command did not work



![2022-08-20_10-48-22](https://user-images.githubusercontent.com/90928541/185752512-8ee61e01-ad1b-471d-b146-ccd63769d2bd.jpg)

![2022-08-20_10-16-23](https://user-images.githubusercontent.com/90928541/185752522-1befd183-8b08-4fbe-919d-f9f964f1fed9.jpg)

**Comment by grenona55** [comment]
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/9387340/php-errors.log)
[sql-errors.log](https://github.com/pluginsGLPI/formcreator/files/9387341/sql-errors.log)
[event.log](https://github.com/pluginsGLPI/formcreator/files/9387343/event.log)

**Comment by grenona55** [comment]
here is the portion i find in the php error log 

what is the command of the upgrade process ? (command line)


**2022-08-20 10:22:02] glpiphplog.WARNING:   *** PHP User Warning (512): Plugin "formcreator" version changed. It has been deactivated as its **update process has to be launched.** in /var/www/html/glpi/src/Plugin.php at line 550**
  Backtrace :
  src/Plugin.php:550                                 trigger_error()
  src/Plugin.php:466                                 Plugin->checkPluginState()
  src/Plugin.php:222                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  front/cron.php:41                                  include()
  2022-08-20 10:22:02] glpiphplog.WARNING:   *** PHP User Warning (512): Plugin "formcreator" version changed. It has been deactivated as its update process has to be launched. in /var/www/html/glpi/src/Plugin.php at line 550
  Backtrace :
  src/Plugin.php:550                                 trigger_error()
  src/Plugin.php:466                                 Plugin->checkPluginState()
  src/Plugin.php:222                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  front/cron.php:41                                  include()

**Comment by btry** [comment]
Hi

> Before doing upgrade i get this icon over fromcreator See picture

At this moment you probably have a copy of Formcreator downloaded from the source on GitHub. You shall either run the build procedure, or use the built version from the page of the release, or download from the marketplace.

It also appear you got a copy from the develop branch (2.14). Do not use it if you're not a developer.

> restart apache

This is not necessary. 

> and the icon i get is see second picture

The version is 2.13.0-alpha.3. this is not the stable version. Again, download the proper archive.  Here it is: https://github.com/pluginsGLPI/formcreator/releases/download/2.13.0/glpi-formcreator-2.13.0.tar.bz2

**Comment by grenona55** [comment]
Hi thanks

I did the process again

Now I get the Update Icon over formcreator

I click on it

I get this message

Task Completed. (0 seconds)
Unknown column 'conf.entities_id' in 'where clause'


I will send you the LOG over the git site

**Comment by grenona55** [comment]
[sql-errors.log](https://github.com/pluginsGLPI/formcreator/files/9387637/sql-errors.log)
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/9387638/php-errors.log)

**Comment by grenona55** [comment]
last upgrade message i get : 

**task Completed. (0 seconds)
Unknown column 'conf.entities_id' in 'where clause'**

**Comment by grenona55** [comment]
log SQL where Formcreator error 


SQL: INSERT INTO glpi_plugin_formcreator_entityconfigs
                  (entities_id, replace_helpdesk, default_form_list_mode, sort_order, is_kb_separated, is_search_visible, is_dashboard_visible, is_header_visible, is_search_issue_visible, tile_design)
               SELECT ent.id,
                  IF(ent.id = 0, 0, -2),
                  IF(ent.id = 0, 0, -2),
                  IF(ent.id = 0, 0, -2),
                  IF(ent.id = 0, 0, -2),
                  IF(ent.id = 0, 0, -2),
                  IF(ent.id = 0, 1, -2),
                  IF(ent.id = 0, 0, -2),
                  IF(ent.id = 0, 1, -2),
                  IF(ent.id = 0, 0, -2)
                FROM glpi_entities ent
                LEFT JOIN glpi_plugin_formcreator_entityconfigs conf
                  ON ent.id = conf.entities_id
                WHERE conf.entities_id IS NULL
  Error: Unknown column 'conf.entities_id' in 'where clause'
  Backtrace :
  marketplace/formcreator/install/install.php:361    
  marketplace/formcreator/install/install.php:208    PluginFormcreatorInstall->configureExistingEntities()
  marketplace/formcreator/hook.php:53                PluginFormcreatorInstall->upgrade()
  src/Plugin.php:779                                 plugin_formcreator_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  {"user":"2@ldap.cie1234.com"} 
2022-08-20 11:58:42 [2@ldap.cie1234.com]
Unknown column 'conf.entities_id' in 'where clause'[2022-08-20 12:00:03] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT MAX(level) AS 'maxlevel'
                  FROM glpi_entities
                  WHERE  `id` = 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3
  Backtrace :

**Comment by btry** [comment]
This error is normal because the version of the plugin changed.

You may upgrade the plugin from the UI of GLPI. If your database is big, it is better to upgrade with CLI.

Locate in glpi directory the issue the following command:

pho bin/console glpi:plugin:install formcreator -f

**Comment by grenona55** [comment]
very small DB

i try on CLI

same error


oot@ldap:/var/www/html/glpi# bin/console glpi:plugin:install formcreator -f
User to use:glpi
Processing plugin "formcreator"...
SQL Error "1054": Unknown column 'conf.entities_id' in 'where clause' in query "INSERT INTO glpi_plugin_formcreator_entityconfigs                   (entities_id, replace_helpdesk, default_form_list_mode, sort_order, is_kb_separated, is_search_visible, is_dashboard_visible, is_header_visible, is_search_issue_visible, tile_design)                SELECT ent.id,                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 1, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 1, -2),                   IF(ent.id = 0, 0, -2)                 FROM glpi_entities ent                 LEFT JOIN glpi_plugin_formcreator_entityconfigs conf                   ON ent.id = conf.entities_id                 WHERE conf.entities_id IS NULL"
Unknown column 'conf.entities_id' in 'where clause'root@ldap:/var/www/html/glpirroot@ldap:/var/www/html/glpi#

**Comment by btry** [comment]
You have a missing column entities_id in the table glpi_plugin_formcreator_entityconfigs.

I need to check the upgrade process before telling how to fix it.

**Comment by grenona55** [comment]
thanks very munch, not urgent is saturday for you also : enjoy week end

**Comment by btry** [comment]
Show the result of the SQL query. It seems  that a change on the table does not occurs.

`SHOW CREATE TABLE `glpi_plugin_formcreator_entityconfigs`;`

**Comment by grenona55** [comment]
Where should I do this command ?

***@***.***
514-919-6119

________________________________
De : btry ***@***.***>
Envoyé : Saturday, August 20, 2022 1:33:19 PM
À : pluginsGLPI/formcreator ***@***.***>
Cc : grenona55 ***@***.***>; Comment ***@***.***>
Objet : Re: [pluginsGLPI/formcreator] FormCreator 2.13 install in GLPI 10.0.2 (Issue #2930)


Show the result of the SQL query. It seems that a change on the table does not occurs.

SHOW CREATE TABLE glpi_plugin_formcreator_entityconfigs;

**Comment by btry** [comment]
In your favourite tool to explore your database.

Heidisql, the cli tool mysql, or any other

**Comment by grenona55** [comment]
That what I can pull out

***@***.***

**Comment by btry** [comment]
Hi

I see the request I gave to you, but not the its result.

**Comment by grenona** [comment]
***@***.***

**Comment by btry** [comment]
Hi

There is still nothing useful. Connect to Github and paste the result directly, instead of sending emails.

**Comment by grenona** [comment]
the re is no result 



![image](https://user-images.githubusercontent.com/88557992/186157344-fde9fa72-6a62-4500-b7d9-cbc7fe03ef7f.png)


![image](https://user-images.githubusercontent.com/88557992/186157431-85920126-138c-4f0e-a4f9-3dc2efd743fb.png)

**Comment by btry** [comment]
There is indeed a missing column in the table.

I did some cleanup in the thread for better readability. I noticed you did not answered my question about the previous version of Formcreator before your attempt to upgrade. I need this information to find the best solution.

**Comment by grenona** [comment]
very strange, i revert to my snapshot before upgrade, i get this version number in PHPAdmin

![image](https://user-images.githubusercontent.com/88557992/186166061-6dd90a22-eb76-49be-9798-be043a08dca2.png)


but i still get this warning  in PLUGIN

![image](https://user-images.githubusercontent.com/88557992/186166224-951e2f5c-37a9-4949-a023-52fe7f26ed14.png)

**Comment by btry** [comment]
the previous version is detected as 2.13.0-alpha.3 but this is wrong because you were already trying to upgrade at this moment. Do you remember the version installed before 2.13.0-alpha.3 ?

> very strange, i revert to my snapshot before upgrade, i get this version number in PHPAdmin

Then at some point a version alpha, beta or RC was installed succesfully. The problem is that the versin alpha.3 requires some manual actions to upgrade.

You should follow the instructions in the release notes of 2.13.0-rc.1: https://github.com/pluginsGLPI/formcreator/releases/tag/2.13.0-rc.1

However, maybe such efort will be a waste of time. Your GLPI instance is not for production use, right ?

**Comment by grenona** [comment]
that was the version installer before 2.13.0-alpha3

**Comment by grenona** [comment]
can you give me link for 2.12, 

i try uninstall from GUI  but icon still showing up

**Comment by btry** [comment]
To uninstall you need to click on this button

![image](https://user-images.githubusercontent.com/14139801/186172901-f3ce30f6-8a3f-4f64-bc2e-1a8d9431ae6e.png)

After that, the plugin still appears in the list because its files are still present. . This is normal. In the database there should be nothing related to the plugin. Remove the folder of the plugin, install the files of 2.13.0 then run the install process.

You will find all version of the plugin in the releases page : https://github.com/pluginsGLPI/formcreator/releases

**Comment by grenona** [comment]
i delete and reload 2.13 , data lost , but it's working now

thanks

**Comment by btry** [comment]
Hi

Good news. I close this issue.
