### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dens325** [pluginsGLPI/formcreator#2933]
![2022-08-22_10-47-52](https://user-images.githubusercontent.com/106594451/185868199-b4b1d9e4-d5f5-4186-94eb-277d63d181a0.png)
![2022-08-22_10-47-44](https://user-images.githubusercontent.com/106594451/185868203-b6e74f3d-83f6-4586-a9b0-75d70a8f04b1.png)
**Describe the bug**
When installing the plugin through the marketplace, GLPI gives the following error
 "
Задача завершена. (0 seconds)
Задача завершена. (0 seconds)
Задача завершена. (0 seconds)
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Задача завершена. (0 seconds)
Warning: Table glpi_plugin_formcreator_targetchanges_actors does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Задача завершена. (0 seconds)
Задача завершена. (0 seconds)
Warning: Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_answers`.`plugin_formcreator_formanswers_id`. in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 2025
Задача завершена. (0 seconds)
Задача завершена. (0 seconds)
Задача завершена. (0 seconds)
Warning: Usage of "utf8" charset/collation detected, should be "utf8mb4" in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1987
Warning: Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targets_actors`.`id`. in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 2025
Задача завершена. (0 seconds)
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Warning: Usage of "DATETIME" fields is discouraged, please use "TIMESTAMP" fields instead. in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 2007
Задача завершена. (1 секунд)
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Warning: Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targetchanges`.`changetemplates_id`. in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 2025
Warning: Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targettickets`.`tickettemplates_id`. in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 2025
Задача завершена. (1 секунд)
Задача завершена. (1 секунд)
Изменение структуры БД - glpi_plugin_formcreator_forms_languages (1 секунд)
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
Warning: Table glpi_plugin_formcreator_formanswers does not exists in /var/www/u1316987/data/www/it.spkmo.ru/src/DBmysql.php on line 1179
- Ошибка во время запроса базы данных: UPDATE `glpi_plugin_formcreator_formanswers` SET `requester_id` = 0 WHERE `requester_id` IS NULL - Ошибка - Table 'u1316987_its.glpi_plugin_formcreator_formanswers' doesn't exist
"

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI version GLPI 10.0.1
[](url)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Яндекс браузер 
 - Version 22

**Comment by btry** [comment]
Hi

This error usually happens if GLPI had Formcreator in the past, and its desinstallation left some tables or data. They are detected and the installation procedure tries an upgrade instead of  a fresh install.

As you said you want to install it, run the following SQL queries and show the result:
```sql
SHOW TABLES LIKE 'glpi_plugin_formcreator_%';
SELECT * FROM `glpi_configs` WHERE `context`='formcreator';
```

**Comment by dens325** [comment]
I don't really know how to use SQL, I hope I made the query correctly
![2022-08-22_11-29-11](https://user-images.githubusercontent.com/106594451/185876554-f7f0f0cf-d49e-4553-9e4b-a5f335f49d02.png)

**Comment by btry** [comment]
Each line is a SQL query. If you use phpmyadmin run them one at a time.

```sql
SHOW TABLES LIKE 'glpi_plugin_formcreator_%';
```
then 
```sql
SELECT * FROM `glpi_configs` WHERE `context`='formcreator';
```

**Comment by dens325** [comment]
Here is the result
![2022-08-22_11-40-40](https://user-images.githubusercontent.com/106594451/185878357-b08b9729-0630-4796-8bd6-ed2f189b3c43.png)
![2022-08-22_11-40-17](https://user-images.githubusercontent.com/106594451/185878361-14598f84-e60c-42d8-b028-b2215127a30c.png)

**Comment by btry** [comment]
you did not selected a database in the UI then the results are not relevant. You should learn the basics about SQL as I cannot allocate time for this. 

I recommend you get in touch with mysql community users or GLPI community users: https://forum.glpi-project.org/

**Comment by dens325** [comment]
I chose the database and made a request
![2022-08-22_11-45-22](https://user-images.githubusercontent.com/106594451/185879430-0dab7006-5f20-4906-8f44-049494ca5fdb.png)
![2022-08-22_11-45-01](https://user-images.githubusercontent.com/106594451/185879436-1e5df383-d736-424d-bd3d-e0f773d43253.png)

**Comment by btry** [comment]
There are too many tables and the version of the plugin is too recent to encounteer the problem I expected to find. 

Are you sure that you need an fresh install of the plugin ?

**Comment by dens325** [comment]
I previously installed GLPI version 10.0.2 and this plugin worked fine, but I had to switch to GLPI version 10.0.1. After that, the plugin does not start. Old data is not needed , which version should be installed to make it work ?

**Comment by btry** [comment]
Delete all tables found by the sql query, and delete the row found in glpi_configs.

Then try again to run the install process.

**Comment by dens325** [comment]
Can you tell me how to delete lines for this query?
SHOW TABLES LIKE 'glpi_plugin_formcreator_%';

**Comment by btry** [comment]
This cannot be done easily with a single line. Select all these tables in phpmyadmin and delete them with the features of its interface. This is easy : select all tables having a neme beginning with **glpi_plugin_formcreator_**

**Comment by dens325** [comment]
is it not possible to restore the plugin somehow? Since it's difficult

**Comment by btry** [comment]
No because you lost a whole table and other tables may kave relations to lost data. In such case the database is corrupted.

**Comment by btry** [comment]
Hi

Having no news, I assume your problem is solved. I close this issue.
