### ISSUE TITLE
Bug lors de la création

### ISSUE THREAD

**Issue by SkoEdi** [pluginsGLPI/formcreator#2935]
Bonjour,

Lorsque l'on clique sur le bouton send, la page ne change pas mais les tickets sont créés
Via les outils de dev, je vois l'erreur suivante quand je clique sur le bouton
![image](https://user-images.githubusercontent.com/109290859/186096980-6d3dfc63-1ba2-410c-8a85-a0d1b4e99d7c.png)

GLPI 10.0.2
        news                 Name: Alerts                         Version: 1.10.4     State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	editus               Name: Editus AzureDevOps             Version: 1.0        State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                 
		Install Method: Manual
	fpsoftware           Name: FP Software                    Version: 2.0.0      State: Enabled                                 
		Install Method: Manual

**Comment by btry** [comment]
Bonjour

Si les tickets sont créés, cela signifie que le formulaire a passé la validation des réponses. Pourtant la ligne 1399 de scripts.js correspond à un échec de soumission du formulaire, quand les réponses ne sont pas valides (un champ obligatoire resté vide par exemple).

La valeur de retour de la requte AJAX traitée dans le code est du JSON. J'ai besoin de quelques vérifications 
- Vérifiez l'état du mode debug, **sans le modifier**. Est il activé ? 
- ouvrez les outils développeur du navigateur, onglet "réseau", puis reproduisez le problème. Localisez une requête vers une URL finissant par ajax/formanswer.php. Quel est le code de réponse HTTP (onglet Entête), et quel est le body de cette réponse (onglet réponse) ?

**Comment by SkoEdi** [comment]
L'entete de réponse est HTTP/1.1 200 OK
voila le contenu de la réponse:
          <html>
          <head><title>301 Moved Permanently</title></head>
          <body>
          <center><h1>301 Moved Permanently</h1></center>
          <hr><center>nginx</center>
          </body>
          </html>
          {"redirect":"\/front\/ticket.form.php?id=12308"}

**Comment by chnateag** [comment]
Hi, we have the same issue, glpi v10.0.0, formcreator 2.13.0, updated yesterday, 
```
Uncaught TypeError: xhr.responseJSON is undefined
    submitUserForm scripts.js:1399
    jQuery 6
    <anonymous> base.js:378
    prop base.js:180
    method jQuery
    submitUserForm scripts.js:1388
    <anonymous> :1
scripts.js:1399:40
    submitUserForm scripts.js:1399
    jQuery 6
    <anonyme> base.js:378
    prop base.js:180
    method jQuery
    submitUserForm scripts.js:1388
    <anonyme> :1

```

But i can see this in answer :

```
PHP User Warning (512): getFromDBByCrit expects to get one result, 2 found in query "SELECT `id` FROM `glpi_plugin_formcreator_questionranges` WHERE `plugin_formcreator_questions_id` = '366' AND `fieldname` = 'range'". in /home/www/glpi/src/CommonDBTM.php at line 394
PHP User Warning (512): getFromDBByCrit expects to get one result, 5 found in query "SELECT `id` FROM `glpi_plugin_formcreator_questionregexes` WHERE `plugin_formcreator_questions_id` = '367' AND `fieldname` = 'regex'". in /home/www/glpi/src/CommonDBTM.php at line 394
PHP Notice (8): Undefined index: groups_id_tech in /home/www/glpi/src/NotificationTarget.php at line 1087
{"redirect":"formlist.php"}
```

and this in logs : 
```
==> /var/www/glpi/files/_log/php-errors.log <==
[2022-08-23 10:22:00] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: groups_id_tech in /home/www/glpi/src/NotificationTarget.php at line 1087
  Backtrace :
  src/NotificationTarget.php:1199                    NotificationTarget->addItemGroupTechInCharge()
  src/NotificationEventAbstract.php:93               NotificationTarget->addForTarget()
  src/NotificationEvent.php:185                      NotificationEventAbstract::raise()
  src/Ticket.php:1696                                NotificationEvent::raiseEvent()
  src/CommonDBTM.php:1667                            Ticket->post_updateItem()
  src/Item_Ticket.php:108                            CommonDBTM->update()
  src/CommonDBTM.php:1275                            Item_Ticket->post_addItem()
  plugins/formcreator/inc/targetticket.class.php:931 CommonDBTM->add()
  plugins/formcreator/inc/formanswer.class.php:871   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:1093  PluginFormcreatorFormAnswer->generateTarget()
  src/CommonDBTM.php:1275                            PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/ajax/formanswer.php:58         CommonDBTM->add()
```

**Comment by SkoEdi** [comment]
Il semble y avoir un conflit avec d'autre plugin.
Nous utilisons un plugin custom et j'ai l'erreur ci-dessous.
Si je désactive notre plugin cela fonctionne.

```
[2022-08-23 10:13:15] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $result in /var/www/glpi/plugins/nomduplugin/hook.php at line 54
  Backtrace :
  plugins/nomduplugin/hook.php:15                         CallAPI()
  src/Plugin.php:1468                                CallADO()
  src/CommonDBTM.php:1351                            Plugin::doHook()
  plugins/formcreator/inc/targetticket.class.php:920 CommonDBTM->add()
  plugins/formcreator/inc/formanswer.class.php:871   PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/formanswer.class.php:1093  PluginFormcreatorFormAnswer->generateTarget()
  src/CommonDBTM.php:1305                            PluginFormcreatorFormAnswer->post_addItem()
  plugins/formcreator/ajax/formanswer.php:58         CommonDBTM->add()
```

**Comment by btry** [comment]
@chnateag 

Excutez les 2 requêtes SQL suivantes pour voir combien de questions ont des regex et des ranges en double

```sql
select
    count(qr.id) as cpt,
    f.id as form_id,
    s.id as section_id,
    q.id as question_id,
    q.name,
    q.fieldtype,
    qr.id as qrid
from
    glpi_plugin_formcreator_questions as q
    left join glpi_plugin_formcreator_questionregexes as qr on (qr.plugin_formcreator_questions_id = q.id)
    inner join glpi_plugin_formcreator_sections as s on (q.plugin_formcreator_sections_id = s.id)
    inner join glpi_plugin_formcreator_forms as f on (s.plugin_formcreator_forms_id = f.id)
group by
    q.id
having
    cpt > 1;

select
    count(qr.id) as cpt,
    f.id as form_id,
    s.id as section_id,
    q.id as question_id,
    q.name,
    q.fieldtype,
    qr.id as qrid
from
    glpi_plugin_formcreator_questions as q
    left join glpi_plugin_formcreator_questionranges as qr on (qr.plugin_formcreator_questions_id = q.id)
    inner join glpi_plugin_formcreator_sections as s on (q.plugin_formcreator_sections_id = s.id)
    inner join glpi_plugin_formcreator_forms as f on (s.plugin_formcreator_forms_id = f.id)
group by
    q.id
having
    cpt > 1;
```

**Comment by chnateag** [comment]
j'ai ecris en anglais par reflexe 😅

```
+-----+---------+------------+-------------+------------------------------------------+------------+------+
| cpt | form_id | section_id | question_id | name                                     | fieldtype  | qrid |
+-----+---------+------------+-------------+------------------------------------------+------------+------+
|   2 |       7 |         17 |         151 | Fonction                                 | text       |   36 |
|   2 |       8 |         19 |         164 | Récupération du matériel existant        | checkboxes |   22 |
|   2 |       8 |         19 |         168 | Devis nouveau Matériel                   | checkboxes |   66 |
|   2 |       8 |         19 |         172 | Autre                                    | text       |   57 |
|   2 |       8 |         19 |         173 | téléphone Fixe Configuration             | textarea   |   11 |
|   2 |       8 |         19 |         176 | Partage DATA Dossier spécifiques   | text       |    3 |
|   2 |       8 |         19 |         178 | Partage Distant (CLOUD)                  | text       |    4 |
|   2 |       8 |         20 |         179 | Logiciels utilisés                       | checkboxes |   20 |
|   2 |       8 |         20 |         181 | Quadra Config                            | text       |   15 |
|   2 |      10 |         24 |         197 | Fonction                                 | text       |   37 |
|   2 |      10 |         26 |         220 | Commentaires                             | textarea   |   17 |
|   2 |      12 |         30 |         283 | Problème de fonctionnement Imprimante 1  | text       |  155 |
|   2 |      18 |         42 |         366 | Nom                                      | text       |   12 |
+-----+---------+------------+-------------+------------------------------------------+------------+------+
13 rows in set (0.009 sec)
```

**Comment by btry** [comment]
@chnateag 

> j'ai ecris en anglais par reflexe

ça m'arrive aussi

La requête vous donne tous les éléments pour trouver les questions ayant ce problème de doublons. Vous devez aller dans les tables glpi_plugin_formcreator_questionregexes et glpi_plugin_formcreator_questionranges pour effacer un doublon pour chaque question. 

La plupart du temps les questions n'utilisent pas de regex ou de range, les lignes doivent donc être identiques. Effacer l'une d'elles. Si vous avez des lignes non vides (colonnes regex, range_min et range_max) vous devrez choisir avec soin laquelle effacer. Vous avez l'ID des formulaires contenant les questions donc vous pouvez jeter un oeil facilement aux formulaires concernés pour chaque cas.

**Comment by btry** [comment]
@chnateag 

à propos de l'erreur

> PHP Notice (8): Undefined index: groups_id_tech in /home/www/glpi/src/NotificationTarget.php at line 1087

vous avez probablement un backtrace dans glpi/files/_logs/php-errors.log. Voyez aussi sql-errors.log si il y a quelque chose en relation. Je suggère un rapport de bug séparé pour le traiter pour la clarté de la discussion.

**Comment by btry** [comment]
@SkoEdi 

> Le mode débug n'est pas activé
L'entete de réponse est HTTP/1.1 200 OK
voila le contenu de la réponse:
> ```
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body>
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> {"redirect":"\/front\/ticket.form.php?id=12308"}
> ```

Il ne devrait pas y avoir de HTML dans le corps de la réponse. C'est à priori ajouté dynamiquement par nginx. Il faut trouver un moyen de désactiver cet ajout. Peut être que Formcreator devrait ajouter un en-tête pour spécifier le format de la réponse; j'ai besoin de me documenter pour valider cette hypothèse.

**Comment by btry** [comment]
@SkoEdi : une piste côté nginx ici: https://talk.plesk.com/threads/how-to-remove-the-html-body-of-a-301-return-of-nginx.358097/ . Vous devriez essayer.

**Comment by SkoEdi** [comment]
Avec une nouvelle version de notre plugin (toujours en test), j'ai ceci dans la réponse. Je regarde avec un de nos dev sur ce qui pourrais poser problème.
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-15442e2f9b429f5b1c7d9abc8aefd27c-72f8535568d27693-00"
}{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-74902a1c9d451410cb9d649d817fad60-3b284c9ce49b379d-00"
}{"redirect":"\/front\/ticket.form.php?id=8777"}
```

**Comment by btry** [comment]
415 Unsupported Media Type

   The 415 (Unsupported Media Type) status code indicates that the
   origin server is refusing to service the request because the payload
   is in a format not supported by this method on the target resource.
   The format problem might be due to the request's indicated
   Content-Type or Content-Encoding, or as a result of inspecting the
   data directly.

**Comment by btry** [comment]
A priori, je dois modifier la façon de soumettre le formulaire.

**Comment by btry** [comment]
@SkoEdi 

j'ai fait quelques tests. La requête HTTP envoyée par le navigateur me parait correcte. Le souci réside sûrement dans l'entête HTTP Content-Type de la requête. Il doit être de la forme

```Content-Type: multipart/mixed; boundary=gc0p4Jq0M2Yt08jU534c0p``` (boundary est une valeur générée aléatoirement et peut avoir une forme différente d'un navigateur à l'autre).

Il faut trouver pourquoi nginx n'accepte pas cet entête.

**Comment by btry** [comment]
@SkoEdi 

Essayez d'appliquer ce patch à Formcreator et dites si le problème disparait

```diff
diff --git a/js/scripts.js b/js/scripts.js
index 359580b2..feda3436 100644
--- a/js/scripts.js
+++ b/js/scripts.js
@@ -1383,12 +1383,14 @@ var plugin_formcreator = new function() {
 
    this.submitUserForm = function () {
       var form     = document.querySelector('form[data-itemtype]');
-      var data     = new FormData(form);
-      data.append('submit_formcreator', '');
+      // var data     = new FormData(form);
+      // data.append('submit_formcreator', '');
+      var data = form.serializeArray();
+      data.push({name: 'submit_formcreator', value: ''});
       $.post({
          url: formcreatorRootDoc + '/ajax/formanswer.php',
-         processData: false,
-         contentType: false,
+         // processData: false,
+         // contentType: false,
          data: data,
          dataType: 'json'
       }).done(function (data) {
```

**Comment by SkoEdi** [comment]
J'ai encore les erreurs:
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-8adef355501ca2b13cccf3cc186d22b8-e00b902d5728eff5-00"
}{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-7feaf3e349f172c5ef7f0bfe89026ee0-78efd3821677d5bc-00"
}{"redirect":"\/front\/ticket.form.php?id=8779"}
```
Pour information, je n'avais aucun problème avec la RC2. Il n'y a eu aucun changement chez nous (nginx ou plugin custom), c'est le passage sur la release qui a déclenché le problème

**Comment by btry** [comment]
Après la RC.2 la soumission des formulaires a changé pour résoudre un problème. Il fallait que j'empêche le rafraichissement de la page si les réponses ne sont pas valides, sinon les images déposées dans un textarea étaient perdues. C'est pour cela que le souci est apparu seulement maintenant.

Il y a une petite dizaine derequêtes AJAX danas le plugin qui sont susceptibles de poser votre souci. Si les autres requêtes HTTP (via ajax ou non) fonctionnent bien, je suis plutôt sûr de la solution que je propose. 

Une erreur assez fréquente peut causer l'inactin d'un patch : vous avez peut être 2 copies du plugin : une dans le dossier plugins/ (que voud avez patché) et une autre copie dans marketplace/ (parce que vous avez upgradé via ce nouvel outil). Dans ce cas il faut efacer la copie située dans plugins/. 

En parallèle je vais monter un nginx, car pour le moment je cherche un patch sans pouvoir le tester moi même.

**Comment by SkoEdi** [comment]
Suite a une modification des redirections sur nos nginx, c'est maintenant fonctionnel pour moi

**Comment by btry** [comment]
Ok, c'est donc contournable, mais ça reste un palliatif assez compliqué.

Avez vous la possibilité de tester le patch #2938 ? 

Il corrigé toutes les requêtes Ajax pouvant poser problème avec nginx.

**Comment by btry** [comment]
C'est parce qu'il y a eu une modification à proximité depuis la release. Il faut que je fasse un portage du patch.

**Comment by btry** [comment]
@SkoEdi : il y a quelque chose qui ne va pas : le patch s'applique sans conflit avec la release 2.13.0. Vous ne devriez donc pas avoir de conflit également. Votre copie du plugin contient une différence.

**Comment by SkoEdi** [comment]
Juste le patch plus haut, je n'ai pas fait d'autre modification depuis l'update
De plus, la personne en charge de nos nginx a modifié les redirections, je ne peux plus tester
Désolé

**Comment by btry** [comment]
De mo ncôté ave un nginx + PHP de base, je n'ai pas reproduit. Je ne fusionnerai donc pas le patch.
