### ISSUE TITLE
[GLPI 10.0.2 FormCreator 2.13.0-rc.2] No search fields

### ISSUE THREAD

**Issue by tdelaux** [pluginsGLPI/formcreator#2936]
Hello,
in Simplified interface, user can't search form. It is possible in the previous releases.

GLPI 9.5 + FormCreator 2.11.4 : 
![image](https://user-images.githubusercontent.com/44919953/186119792-6dfd64a2-3719-485a-98a4-f0dfa803d190.png)

GLPI 10.0.2 + FormCreator 2.13.0-rc.2 : 
No searchbar
![image](https://user-images.githubusercontent.com/44919953/186120437-25d16027-abab-475e-94c0-a7bc5cdfffb1.png)

Is it possible to add search bar to the last version ?

Thank's

**Comment by btry** [comment]
Hi 

Check the settings of Formcreator in your entity

![image](https://user-images.githubusercontent.com/14139801/186121033-f4748873-83e8-432c-914a-24878059d737.png)

**Comment by btry** [comment]
Also, consider to install the version 2.13.0 . Of course you re using the version 2.13.0-rc.2 on a testing environement, right ?

**Comment by tdelaux** [comment]
yes, testing environement.

Thank's for the solution.
