### ISSUE TITLE
Probleme de solution sur ticket

### ISSUE THREAD

**Issue by chnateag** [pluginsGLPI/formcreator#2940]
**Describe the bug**
Lors de l'ajout d'une solution à un ticket celle ci ne pré-remplie plus le champs si le ticket est créé par formcreator.

**To Reproduce**
1. Aller au ticket généré par formcreator
2. Cliquer sur réponse
3. Sélectionner une solution
4. Rien ne se passe

**Expected behavior**
Le champs devrait se préremplir

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.0
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
```
	bettermailimporter   Name: Better Mail Importer           Version: 1.0.1      State: Enabled
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled
	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.0      State: Installed / not activated
	dashboard            Name: Dashboard                      Version: 0.9.6      State: Installed / not activated
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Installed / not activated
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 10.0.0+1.1 State: Enabled
	tasklists            Name: Liste des tâches               Version: 2.0.1      State: Installed / not activated
	tec6barcode          Name: Tec6barcode                    Version: 1.0.2      State: Enabled
```

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox + Chrome

**Additional context**

![image](https://user-images.githubusercontent.com/6058178/186455077-87f711c6-c71d-466d-8d63-b10576cda20a.png)

```


==> /var/www/glpi/files/_log/php-errors.log <==
[2022-08-24 17:03:27] glpiphplog.WARNING:   *** PHP User Warning (512): PluginFormcreatorFormAnswer is not allowed for this parameter type. in /home/www/glpi/src/ContentTemplates/Parameters/AbstractParameters.php at line 75
  Backtrace :
  ...tTemplates/Parameters/AbstractParameters.php:75 trigger_error()
  ...ntTemplates/Parameters/TicketParameters.php:151 Glpi\ContentTemplates\Parameters\AbstractParameters->getValues()
  ...tTemplates/Parameters/AbstractParameters.php:79 Glpi\ContentTemplates\Parameters\TicketParameters->defineValues()
  src/ContentTemplates/TemplateManager.php:105       Glpi\ContentTemplates\Parameters\AbstractParameters->getValues()
  src/AbstractITILChildTemplate.php:140              Glpi\ContentTemplates\TemplateManager::renderContentForCommonITIL()
  ajax/solution.php:88                               AbstractITILChildTemplate->getRenderedContent()
```

**Comment by chnateag** [comment]
![fc - Copie](https://user-images.githubusercontent.com/6058178/186608271-704e8175-a82d-49f0-8b7e-111addfbe5cc.jpg)
Voici un exemple de ticket générant l'erreur

Le soucis n'est pas présent sur un ticket créé normalement, et si je duplique le ticket ci dessus tout fonctionne aussi, en ajoutant les mêmes groupes

**Comment by btry** [comment]
Bonjour

Je n'ai pas pu examiner ce problème; mais à voir le backtrace que vous avez, j'ai une idée du problème.

- vérifiez si le profil de l'utilsiateur remplissant la solution est autorisé  à associer des réponses aux formulaires à un ticket.
![image](https://user-images.githubusercontent.com/14139801/188107880-a5088a4a-3967-47d6-8adf-6bbc7e97ca73.png)
- Ajoutez ce type si nécessaire.

Puis réessayez d'e préremplir une solution.

**Comment by chnateag** [comment]
alors en effet ce n'etait pas dans  items, mais on a toujours le probleme apres application : 

```

==> /var/www/glpi/files/_log/php-errors.log <==
[2022-09-02 14:44:46] glpiphplog.WARNING:   *** PHP User Warning (512): PluginFormcreatorFormAnswer is not allowed for this parameter type. in /home/www/glpi/src/ContentTemplates/Parameters/AbstractParameters.php at line 75
  Backtrace :
  ...tTemplates/Parameters/AbstractParameters.php:75 trigger_error()
  ...ntTemplates/Parameters/TicketParameters.php:151 Glpi\ContentTemplates\Parameters\AbstractParameters->getValues()
  ...tTemplates/Parameters/AbstractParameters.php:79 Glpi\ContentTemplates\Parameters\TicketParameters->defineValues()
  src/ContentTemplates/TemplateManager.php:105       Glpi\ContentTemplates\Parameters\AbstractParameters->getValues()
  src/AbstractITILChildTemplate.php:140              Glpi\ContentTemplates\TemplateManager::renderContentForCommonITIL()
  ajax/solution.php:88                               AbstractITILChildTemplate->getRenderedContent()

```

**Comment by btry** [comment]
Alors vous pouvez retirer l'élément; c'était juste un test pour voir si le problème venait d'une vérification sur cette liste.

**Comment by chnateag** [comment]
Bien reçu

**Comment by btry** [comment]
Note : de ce que j'ai vu, le fix sera certainement à faire dans GLPI. Vous pouvez éventuellement ouvrir un ticket sur GLPI et le lier à celui-ci.

**Comment by chnateag** [comment]
Ca marche, on doit faire la maj 10.0.1 et on attend que fusioninventory soit compatible 10.0.2 ... Donc j’attends avant d'ouvrir le ticket

**Comment by btry** [comment]
Bonjour

Je n'ai pas reproduit (avec la branche 10.0/bugfixes); et j'ai un vague souvenir d'un problème semblable il ya plusieurs mois. Il y a de bonnes chances qu'il soit déjà résolu. Vous devriez utiliser une instance de test de GLPI pour upgrader vers 10.0.2 et voir si vous reproduisez toujours.

**Comment by btry** [comment]
J'ai retrouvé le patch qui devrait résoudre le souci (pour GLPI) https://github.com/glpi-project/glpi/pull/11831.

Le problème étant dans GLPI, je ferme ce ticket.
