### ISSUE TITLE
Les réponses multiples pour les boites à cocher sont affichées sans séparation

### ISSUE THREAD

**Issue by itirel-sdeau50** [pluginsGLPI/formcreator#2941]
Quand un utilisateur coche plusieurs réponses à une question à boites multiples, les réponses affichées dans le ticket cible sont concaténées sans espace, sans saut de ligne.
exemple de réponse : 
![image](https://user-images.githubusercontent.com/112075797/186629399-c8ffd17a-3a03-4df8-9f6b-b53372009361.png)

GLPI v 10.0.2
FormCreator v 2.13.0

Merci à vous !

**Comment by btry** [comment]
Bonjour,

Je n'ai pas réussi à reproduire. J'ai utilisé un ticket cible contenant la balise ##FULLFORM## (le contenu par défaut). Avez vous un contenu différent ?

**Comment by itirel-sdeau50** [comment]
Bonjour,
Quand j'utilise FullForm, je n'ai pas le problème : 
![image](https://user-images.githubusercontent.com/112075797/186636028-399fa8df-0dd8-45c2-a1a8-8e8ccf95e77b.png)
Mais dans le même ticket cible j'ai formaté comme suit : 
![image](https://user-images.githubusercontent.com/112075797/186636211-a1273d82-ee17-4dc1-b85a-dabf85c88b6f.png)

Le résultat : 
![image](https://user-images.githubusercontent.com/112075797/186636261-a57d4df3-84c4-4b6d-bcec-d2fc6799260f.png)

Ce qui est embêtant c'est qu'en testant un autre formulaire avec boîtes à cocher, j'ai une réponse correctement formatée avec une réponse par ligne.
J'ai comparé les codes sources des cibles.
Celui qui foncionne normalement : 
![image](https://user-images.githubusercontent.com/112075797/186637142-6c2162c5-4206-4192-9f91-3e00bc270000.png)

Celui qui bug : 
![image](https://user-images.githubusercontent.com/112075797/186637223-142b7365-3ee2-4bfd-889f-98275e77e5a4.png)

(Je ne m'y connait pas trop en html) j'ai remarqué le <p> présent sur celui qui ne fonctionne pas, mais cela ne change rien...

**Comment by btry** [comment]
Apparemment il y a un lien avec le gabarit du ticket cible. Editez celui qui ne fonctionne pas bien, et collez dans un fichier texte le code HTML du champ "contenu". Déposez le fichier ici. Je pense que je reproduirai en ayant un ticket avec exactement le même contenu.

**Comment by itirel-sdeau50** [comment]
J'utilise le même gabarit de ticket pour les cibles des deux formulaires qui est celui par défaut. Je peux en revanche déposer les codes sources des deux cibles..
[bug.txt](https://github.com/pluginsGLPI/formcreator/files/9424088/bug.txt)
[fonctionnel.txt](https://github.com/pluginsGLPI/formcreator/files/9424089/fonctionnel.txt)
Merci pour votre patience ;)

**Comment by btry** [comment]
J'ai repris le fichier bug.txt ; il ne m'a pas aidé à reproduire.

Essayez d'éditer le ticket cible, et de le sauvegarder sans rien modifier.

**Comment by itirel-sdeau50** [comment]
Mince. 
Malheureusement, cela n'a rien changé.
Peut être que je vais essayer de reproduire mon ticket cible sans copier-coller voire si cela règle le problème...

**Comment by btry** [comment]
J'ai tenté de copier d'un ticket cible à un autre, et là j'ai reproduit.

**Comment by itirel-sdeau50** [comment]
Ah !!
Et de mon côté j'ai refait la partie qui était buggée et le problème à disparu. 
Au besoin j'ai remis le code source du ticket cible refait, mais pas sûr que cela vous aide..
[bug-refait.txt](https://github.com/pluginsGLPI/formcreator/files/9424245/bug-refait.txt)
.

**Comment by btry** [comment]
je vais regarder; ça peut servir.

**Comment by itirel-sdeau50** [comment]
En tout cas merci !
Et pour le reste, beau boulot !!

**Comment by btry** [comment]
Bonjour

Merci, ça fait plaisir de ce plugin être utile.


Je pense avoir trouvé une solution: https://github.com/pluginsGLPI/formcreator/pull/2950

Une modification récente qui a un effet négatif dans les tableaux. les balises DIV sont effacées quand elles sont dans une balise TD.

**Comment by itirel-sdeau50** [comment]
Super, merci !

**Comment by btry** [comment]
Bonjour

Le fix est fusionné; je ferme ce ticket
