### ISSUE TITLE
Base de connaissance affichée dans la liste des formulaires

### ISSUE THREAD

**Issue by CSVPO** [pluginsGLPI/formcreator#2942]
Bonjour,

Suite au passage de la dernière version de GLPI en 10.0.2 et de FormCreator en 2.13.0 nous avons rencontré l'erreur suivante :

Certains articles (pas tous) de la base de connaissances GLPI sont également affichés dans la liste des formulaires.

Voir capture d'écran suivante : 
![Screen](https://user-images.githubusercontent.com/112167518/186877727-341cea20-0a39-4a74-ba36-3f91e1d1b079.JPG)

Comme on peut le voir avec le mode debug de GLPI, cela est lié au plugin Formcreator.

Est-ce possible de faire quelque chose pour changer cela ? ou une solution à prévoir en prochaine release ?

Ce n'est évidemment pas un problème critique, mais simplement esthétique.

Merci d'avance
Cordialement

**Comment by btry** [comment]
Bonjour

Le catalogue de service est conçu pour afficher les articles de la base de connaissance avec les formulaires depuis qu'il existe. 

Un peu plus tard un paramètre a été ajouté pour accéder aux articles de KB séparément. Peut être que ce paramètre a changé pendant la migration. Vérifiez le dans l'onglet formulaires de votre entité.

**Comment by btry** [comment]
Bonjour

N'ayant pas de retour, je considère la question comme résolue et je ferme.
