### ISSUE TITLE
Form completion error

### ISSUE THREAD

**Issue by kofe88** [pluginsGLPI/formcreator#2945]
**Describe the bug**

**To Reproduce**
1. Create a Form
2. Create a yes/no Question
3. I create Target without conditions.
4. Create a Target with the condition "Disabled unless question = Yes"
5. When filling in the "No" answer Form, an error occurs, the form is not completed, a Ticket is created for Target without conditions.

**Expected behavior**
Completing the Form and creating one Ticket.

**Screenshots**

![1](https://user-images.githubusercontent.com/16879167/187054072-e13af59c-4d36-45c1-9af5-706512896474.PNG)
![2](https://user-images.githubusercontent.com/16879167/187054078-a826748e-2f75-41fb-a21e-7c52b85dd5f3.PNG)
![5](https://user-images.githubusercontent.com/16879167/187054080-74fe69b6-0c67-4859-989d-ba28c8ad7a4c.PNG)
![3](https://user-images.githubusercontent.com/16879167/187054082-93bf6e35-5053-476e-963e-5db7124d1ee2.PNG)
![4](https://user-images.githubusercontent.com/16879167/187054084-d1df5c6a-a870-4c29-b34b-a2362e3f00fa.PNG)

**GLPI / Plugins (please complete the following information):**
GLPI 10.0.2 ( => /var/www/html/glpi)
Installation mode: TARBALL

formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                  		Install Method: Manual 	

fields               Name: Дополнительные поля    Version: 1.17.2     State: Enabled                          		        Install Method: Manual

**Desktop (please complete the following information):**
 Win 10/ Ubuntu 20.04
 - Latest Chrome, Firefox

**Comment by kofe88** [comment]
[export_formcreator_20220828_0219.zip](https://github.com/pluginsGLPI/formcreator/files/9438991/export_formcreator_20220828_0219.zip)

**Comment by btry** [comment]
Hi

It appears that your problem is in the relation between the generated tickets. They are linked each other and your design produces PHP errors which pollute a JSON string sent to the browser.

More analysis required to find how to fix the problem.

**Comment by btry** [comment]
Try the above fix, the browser side error should be solved. Check if the relation betweek tickets is still OK.

**Comment by kofe88** [comment]
> Try the above fix, the browser side error should be solved. Check if the relation betweek tickets is still OK.
> 
> EDIT:
> 
> by the way, The condition for the target ticket is not optimal. Only one line is necessary, they are the opposite each other. ![image](https://user-images.githubusercontent.com/14139801/187175589-1c0745d3-14ec-44bf-bf6c-011c4d3bc26f.png)

Hello! This fix worked for me, thanks!

I added the second condition when I tried to find out what the error was and why the form was not executed, I forgot to delete it)

**Comment by btry** [comment]
Great

Thank you for your feedback. I close this issue.
