### ISSUE TITLE
Valeur par défaut pour la question Actor non sauvé

### ISSUE THREAD

**Issue by SkoEdi** [pluginsGLPI/formcreator#2952]
**Describe the bug**
Le champ actor ne sauve plus les valeurs par défault

**To Reproduce**
ajouter une question acteur
Mettre une adresse mail et sauver
Si on rouvre la question, rien n'est visible dans les valeurs par defaut
Dans le preview, n'est pas visible non plus

**Expected behavior**
la question devrait afficher les adresses mails et les contactes mais le champs est vide

**Screenshots**
![image](https://user-images.githubusercontent.com/109290859/187888091-ecedd3db-9848-467b-bdda-08e79fda61a4.png)
![image](https://user-images.githubusercontent.com/109290859/187888130-35359d0c-3e78-4185-bbcf-6a6d7b8f8d85.png)
![image](https://user-images.githubusercontent.com/109290859/187888176-0aca57ac-09c7-4298-a85f-d1c5a34ae2ea.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version: 10.0.2
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
- news                 Name: Alerts                         Version: 1.10.4     State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	editus               Name: Editus AzureDevOps             Version: 1.0        State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                 
		Install Method: Manual
	fpsoftware           Name: FP Software                    Version: 2.0.0      State: Enabled                                 
		Install Method: Manual

**Desktop (please complete the following information):**
 - OS: windows
 - Browser [e.g. chrome, safari]: Edge + chrome
 - Version [e.g. 22]: edge: 104.0.1293.70 / chrome:104.0.5112.102

**Additional context**
Si je regarde la console du navigateur il y a une erreur à l'ouverture de la question:
![image](https://user-images.githubusercontent.com/109290859/187888975-ca5de8f1-494a-416d-b975-a92ca20cfacb.png)
Aucune autre erreur lors de la sauvegarde de la valeur

**Comment by btry** [comment]
Bonjour

Essayez le fix ci dessus.

**Comment by SkoEdi** [comment]
C'est validé sur notre env test et en prod
Merci pour la réactivité

**Comment by btry** [comment]
Merci pour le retour.
