### ISSUE TITLE
How does the "is visible" option in the form target work?

### ISSUE THREAD

**Issue by wc55** [pluginsGLPI/formcreator#2957]
**Describe the bug**
I thought the "is visible" option would be similar to the "contains" option in business rules, but I'm not sure.

**To Reproduce**
Before, i will show the targets:

![image](https://user-images.githubusercontent.com/106084399/188137959-fc072db6-bb52-4529-981b-83c845b82a2d.png)

Target configuration. The others have the same configuration.
![image](https://user-images.githubusercontent.com/106084399/188138133-15b52522-4a5f-424a-ace1-77c346c696fc.png)

Form configuration:

![image](https://user-images.githubusercontent.com/106084399/188139926-279a3b55-d378-4dc7-b23d-4b262ef04fbd.png)

1. Go to a form.
![image](https://user-images.githubusercontent.com/106084399/188138871-0aaf17c6-a8eb-4d78-b7b5-639476140184.png)

2. Answer BLUE, RED or GREEN in the field. Click on button "Send".

![image](https://user-images.githubusercontent.com/106084399/188139074-df7be4a9-eb94-492d-a9d8-ccb40eb90015.png)

3. The form created 3 tickets
![image](https://user-images.githubusercontent.com/106084399/188139391-b2314459-9650-40f2-aab5-96c4c237c46a.png)

![image](https://user-images.githubusercontent.com/106084399/188139741-66361aaa-c0f1-4b35-a205-a1ae0520fb4b.png)

4. Ticket 288

![image](https://user-images.githubusercontent.com/106084399/188143189-aaa0326a-fd85-40c6-86fb-845f11d8b7f3.png)

**Expected behavior**
I thought that only one ticket would be created, corresponding to the target with the blue answer. I inform you that the option "=" correctly creates only 1 ticket, but I tried to use "is visible" because in my environment I will have answers that would be something like "BLUE/LIGHT" or "BLUE/DARK".

**Screenshots**
Are above

**GLPI / Plugins (please complete the following information):**
<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.2 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT UNOUNIV-VFNBAD8 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="1024M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at
	200.17.210.105 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpidb
	Host info: localhost via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\xampp\htdocs\glpi
GLPI_CONFIG_DIR: C:\xampp\htdocs\glpi/config
GLPI_VAR_DIR: C:\xampp\htdocs\glpi/files
GLPI_MARKETPLACE_DIR: C:\xampp\htdocs\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\xampp\htdocs\glpi/files
GLPI_CACHE_DIR: C:\xampp\htdocs\glpi/files/_cache
GLPI_CRON_DIR: C:\xampp\htdocs\glpi/files/_cron
GLPI_DUMP_DIR: C:\xampp\htdocs\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\xampp\htdocs\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\xampp\htdocs\glpi/files/_locales
GLPI_LOCK_DIR: C:\xampp\htdocs\glpi/files/_lock
GLPI_LOG_DIR: C:\xampp\htdocs\glpi/files/_log
GLPI_PICTURE_DIR: C:\xampp\htdocs\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\xampp\htdocs\glpi/files/_plugins
GLPI_RSS_DIR: C:\xampp\htdocs\glpi/files/_rss
GLPI_SESSION_DIR: C:\xampp\htdocs\glpi/files/_sessions
GLPI_TMP_DIR: C:\xampp\htdocs\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\xampp\htdocs\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\xampp\htdocs\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\xampp\htdocs\glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.200.3.1', Port: '389', BaseDN: 'ou=people,dc=ufpr,dc=br', Connection filter: none, RootDN: none, Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Campos adicionais              Version: 1.17.2     State: Installed / not activated               
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalation                     Version: 2.8.0      State: Installed / not activated               
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.1     State: Installed / not activated               
		Install Method: Manual
	itilcategorygroups   Name: Grupos ItilCategory            Version: 2.5.0      State: Installed / not activated               
		Install Method: Manual
	stab                 Name: Split Timeline Action Buttons  Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.9.2      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Versão 104.0.5112.102 (Versão oficial) 64 bits

**Additional context**

Initially I thought the "/" character could be the problem, but apparently plain text exhibits the same behavior.

But maybe I didn't understand the functionality

**Comment by btry** [comment]
Hi

"is visible" is an operator which tests if a question is displayed or hidden. An improvement should be done to remove the last field as it seems to confuse at least one person: it is useless.

Here is a quick demo of the feature. Check the conditions of the 2nd question in the 1st section, then the condition on the 2nd section. You can use this feature to hide a whole section at once instead of hiding each question of a section with the same condition. This give better performance and more comfort for the admin.

[export_formcreator_20220902_1539.txt](https://github.com/pluginsGLPI/formcreator/files/9478289/export_formcreator_20220902_1539.txt)

**Comment by wc55** [comment]
> Hi
> 
> "is visible" is an operator which tests if a question is displayed or hidden. An improvement should be done to remove the last field as it seems to confuse at least one person: it is useless.
> 
> Here is a quick demo of the feature. Check the conditions of the 2nd question in the 1st section, then the condition on the 2nd section. You can use this feature to hide a whole section at once instead of hiding each question of a section with the same condition. This give better performance and more comfort for the admin.
> 
> [export_formcreator_20220902_1539.txt](https://github.com/pluginsGLPI/formcreator/files/9478289/export_formcreator_20220902_1539.txt)

Hi

Thanks for the answer.

Maybe I didn't express myself correctly.

Regarding hiding or showing the questions/sections I've already figured it out, and I'm already using it.

The item I'm talking about is related to the conditions to trigger a form target, where the "is visible" option also appears.

Should this functionality on targets work the same way to hide sections and questions? Because in sections and questions, I can use it normally, but the "problem" would be in the conditions of the targets.

In the second image maybe it is better to understand where is the option I mentioned

**Comment by btry** [comment]
"is visible" in a target condition will work the same way. The target will be generate an ticket (or whatever) only if the question is visible.

Again, the field on the right is not relevant with this operator, just leave it empty.

**Comment by wc55** [comment]
OK

Now, I understand how it works.

The target is activated if the question is appearing.

The suggestion for the target condition to also have the "contains" setting similar to the business rule functionality, can it be done here or does it need to be in a separate item?

Thanks

**Comment by btry** [comment]
> The suggestion for the target condition to also have the "contains" setting similar to the business rule functionality, can it be done here or does it need to be in a separate item?

The plugin does not supports such feature for targets. I'm not near the code of the project right now. If I remember well the condition using a regex is not available for targets. I have an idea to workaround : create a description question with a condition using a regex against a compatible question. A text field or a textarea field. Make the description visible under a condition, with a text like "your answers will generate a ticket for ordering a hitchikers guide to the galaxy". Then configure the target to trigger if the description is visible.

I never had to test this, but I believe it will work. You're just limited to some question types regarding to regex conditions.

**Comment by wc55** [comment]
Hi

I believe this topic can be closed if necessary.

The issue was worked around in conjunction with ticket business rules
