### ISSUE TITLE
Form does not insert attachments in ticket

### ISSUE THREAD

**Issue by acremonezi** [pluginsGLPI/formcreator#2962]
**Describe the issue**
Form does not insert attachments in ticket

**Info:** Just for reference, when I was trying to find/debug the error I found this old issue #1367 Maybe It can help anyway.

**To Reproduce**
1. Create a Form,
2. Setup the form Target to create a ticket.
3. Add a Question field to upload a file to attach into the ticket.
4. Save the form.
5. Open the form, select a simple file on your computer, upload it into the form and Submit the form.

**Expected behavior:**
A Ticket created with a file attached.

**Extra note:** After the ticket is created without the attachment, the technician is able to add attachments on the ticket via GLPI GUI. It is also possible to include attachments when create a ticket via GLPI GUI.

**GLPI / Plugins:**
- GLPI version: 10.0.2 (complete new installation)
- List of all plugins:

```
advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertas                        Version: 1.10.4     State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Campos adicionais              Version: 1.17.2     State: Not installed                           
		Install Method: Marketplace
	behaviors            Name: Comportamentos                 Version: 2.7.1      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                 
		Install Method: Marketplace
	fpwebhook            Name: FP Webhook                     Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.0      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.9.2      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.1     State: Not installed                           
		Install Method: Marketplace
	metabase             Name: metabase                       Version: 1.3.0      State: Not installed                           
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.1      State: Installed / not activated               
		Install Method: Marketplace
	dashboard            Name: Painel                         Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	singlesignon         Name: Single Sign-on                 Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	tasklists            Name: Tasks list                     Version: 2.0.1      State: Installed / not activated               
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
```

**Thanks and Best regards!**

**Comment by phamorais** [comment]
@btry Hi!

I don't know if it's related, but I'm having the same problem on a GLPI 9.5.8 and Formcreator 2.12.5

The step by step is exactly the same, however when we go to the ticket the attachment is not shown. Also no log is displayed in php-errors.log.

The permissions in the directory are correct, and the attachment can be inserted in the ticket tab after opening

**Comment by btry** [comment]
Hi

This is strange, I was sure I left an answer to @acremonezi a few days ago.

Please tell both if you use the ##fullform## tag in the target ticket. If not, check the target ticket contains the appropriate answer tag for the file question.

Files are not automatically added to tickets. The answer tag must be specified or ##fullform## must be used.

**Comment by phamorais** [comment]
@btry 
We had the following tag

<img width="986" alt="image" src="https://user-images.githubusercontent.com/35368369/189203585-64a05633-84cc-4db0-b7f1-a0ec563b18ec.png">

After adding the **##FULLFORM##** the error was resolved.

So it seems to me that there is a problem in the TAgs, correct?

<img width="993" alt="image" src="https://user-images.githubusercontent.com/35368369/189203796-07d53a18-ca23-4ba2-ad97-3440365b79a9.png">


<img width="1556" alt="image" src="https://user-images.githubusercontent.com/35368369/189203925-c7401061-9f04-4fdf-aaf9-ff42162ff94f.png">

**Comment by btry** [comment]
> So it seems to me that there is a problem in the TAgs, correct?

Not sure. In the 1st screenshot of https://github.com/pluginsGLPI/formcreator/issues/2962#issuecomment-1241108157 I cannot identify if a tag matches your file question. If this file question ##answer_<id>## is present and the file is not added to the ticket, then yes, there is a problem. If the tag is not in the content of the target ticket, then you must add it.

**Comment by acremonezi** [comment]
> Hi
> 
> This is strange, I was sure I left an answer to @acremonezi a few days ago.
> 
> Please tell both if you use the ##fullform## tag in the target ticket. If not, check the target ticket contains the appropriate answer tag for the file question.
> 
> Files are not automatically added to tickets. The answer tag must be specified or ##fullform## must be used.

Hi! @btry Thanks for your repply.

You are right! I added the tag related to the attachment tag and it works perfectly. 
My mistake, I did not pay attention on this detail. There is **no bug**. sorry for the false positive.

The test screenshot is bellow:

![image](https://user-images.githubusercontent.com/32877060/189222966-56c1cc8b-af03-4b72-badb-a65cf4bc851e.png)

Thanks and best regards.

**Comment by btry** [comment]
HI

Thank you for your feedback, I close this issue.
