### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mistereverton** [pluginsGLPI/formcreator#2975]
Hi

@wc55 @mistereverton can one of you test the above mentioned PR ?

_Originally posted by @btry in https://github.com/pluginsGLPI/formcreator/issues/2911#issuecomment-1236971486_

Hello, Yes the tests were done successfully. being triggered by Trigger.

**Comment by btry** [comment]
Hi

Thank you for your feedback. This issue is the continuation of #2911, then I close it .
