### ISSUE TITLE
Cannot update to formcreator 2.13

### ISSUE THREAD

**Issue by pzbdkp** [pluginsGLPI/formcreator#2976]
Hi,

I've did an update for GLPI to version 10.0.2 without any problems.
After the update, I downloaded the latest release for form creator and put the files in glpi/plugins/formcreator directory.

However, in GLPI I don't get the option to update the plugin. It keeps telling me version is not compatible with current version of GLPI. How can I solve this.

![image](https://user-images.githubusercontent.com/25476482/190077712-0dedfd65-ffcf-435d-b03f-f8b4c3f53587.png)

**Comment by btry** [comment]
Hi

Formcreator 2.12.5 is not the latest release. You must download the version 2.13.0.

**Comment by pzbdkp** [comment]
Hi,

As I said: I've download the latest version (glpi-formcreator-2.13.0.tar.bz2) and put it on the correct location of the webserver. But in the GUI GLPI, the new version isn't noticed and it still displays incompatible version 2.12.5.

As you can see in the screenshot, I have updated the "Behaviours" plugin in the same way: downloaded the latest version and, unzipped contents in the correct location on the webserver.
In GUI GLPI I got the possibility to upgrade to the new version and then enable the plugin.

The option for updating Form Creator isn't shown in GLPI GUI despite the new files are uploaded in the correct location.

**Comment by btry** [comment]
I see in your screenshots  that GLPI detected the version 2.12.5.

Check the folders plugins/ and marketplace/ . Do you have a subfolder "formcreator" in both ?

**Comment by pzbdkp** [comment]
Hi,

I've checked both marketplace and plugins folder, in both of them there is a subfolder "formcreator".

I am not able to use marketplace in GLPI anymore because changes made to the proxy in our internal network by sysadmin.

**Comment by btry** [comment]
Ok, here is the problem. I guess you installed Formcreator 2.12.5 using the marketplace, and you tried to upgrade to 2.13.0 bu downloading the version 2.13.0 and putting it in plugins/ folder.

Move the version in marketplace/ out of GLPI (to keep it incase of problem). If you expect your proxy problem to be solved you may want to move the copy in plugins/ directory to marketplace/ directory.

**Comment by pzbdkp** [comment]
Hi,
This solves the problem.
Thanks!
