### ISSUE TITLE
SelfService Users can't see Forms. 

### ISSUE THREAD

**Issue by fabriceverkor** [pluginsGLPI/formcreator#2984]
**Describe the bug**
Internal users with SelfService profile on Root Entity recursively can see Forms (several account tested) but  SSO Azure users can't (several account tested)

Root Entity use GLPI' Helpdesk so that SelfService users can use both forms or create ticket

I can't figure why this difference and suspect a bug

1. connect with an 'Azure SelfService user'
2. Click on 'Forms'
3. Message is  'No form found'

The same test with an 'Internal SelfService user' shows the Forms as expected

**Expected behavior**
Forms should be visible for all users using the same profile/entity/recursivity

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI version : 10
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)

Additional fields | 1.17.2
advanceddashboard | 1.4.1
Anonymize | 2.7.0
Approval by mail | 2.1.1
Barcode | 2.7.1
Branding | 1.3.1
Collaborative tools | 1.2.2
Connections | 10.0.0
Data injection | 2.11.2
Form Creator | 2.13.0
GLPI Agent config | 1.2.0
GLPI Inventory | 1.0.3
Holidays | 1.2.0
Inventory number generation | 2.8.1
IP Adressing | 3.0.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Firefox
 - Version : 104.0.2 (64-bit)

**Additional context**

**Comment by btry** [comment]
Hi

Forms are not only filtered by entity. They are also filtered by language, and maybe this filtering affects the visibility of forms for your Azure user.

Please show:
- the preferred language of the internal self service user
- the preferred language of the Azure self serviice user
- select a form which is visible for the internal self service user but is invisible for the Azure user. Which language is configured on this form ?

**Comment by fabriceverkor** [comment]
My bad. This is exactly the problem 👍 : 
The internal users have English as preferred language. The Azure ones have French
I changed the language of forms and its working fine now.

**Comment by fabriceverkor** [comment]
Its was not a bug but a misconfiguration

**Comment by btry** [comment]
Nice.

Be aware that you can use translation feature to set several languages. 

Assuming your form was set in English when your problem occured, the sections, questions were named in English. To make the form accessible for French people, just add a translation in the form, then select the new language and translate all strings. 

This way you can keep English for the form and make it  available to English and French speaking people without configuring the form for all languages.

**Comment by fabriceverkor** [comment]
Well, indeed, we are a french company but with a lot foreign workers. So the usual language is english.
Thant you again for your help. These Forms will help us to make  people love GLPI.
