### ISSUE TITLE
Formcreator 2.12.5 - Error submitting form to create tickets in selected entity.

### ISSUE THREAD

**Issue by verdanatech-marcio** [pluginsGLPI/formcreator#2986]
**Describe the bug**
When creating a ticket by form response, it did not obey the entity rule, elect in the root entity. Being created in an entity that the user does not have access to.

**To Reproduce**
1.  Create form with target for ticket creation.
2. Add a question targeting the created ticket entity.
3. Submit form response

**Expected behavior**
Create the ticket in the entity selected by the user.

**GLPI / Plugins (please complete the following information):**
- GLPI version: 9.5.8
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Formcreator 2.12.5

**Comment by btry** [comment]
Hi

Formcreator 2.12 reached its end of life. Please try GLPI 10 and Formcreator 2.13.
