### ISSUE TITLE
Be able to select Ticket additional fields in Target Ticket Properties

### ISSUE THREAD

**Issue by fabriceverkor** [pluginsGLPI/formcreator#2987]
As title says, it would be great to fill Ticket additional fields by Forms.
It requires that these additional fields appear in Target Ticket Properties.
Any way to do that ?

**Comment by btry** [comment]
Hi

I don't understand well. Do you mean the plugin additional fields ?

**Comment by fabriceverkor** [comment]
Sorry. yes, the  Ticket additional fields (dropdowns in my case) created by  plugin additional fields.

**Comment by btry** [comment]
Hi

This is already supported. I checked the documentation and unfortunately it has not been updated about the feature. There are some constraints about the additional field configuration in the zponym plugin. 

In Formcreator, use the question type additional field, then configure the target ticket to use this question. You need ##fullform## or ##answer_xxx## (xxx is the Id of the question, as found in the list of tags available on screen).

**Comment by fabriceverkor** [comment]
I think I was unclear. Yes, I could create questions using additional fields. I speaking about the "Properties" screen of target ticket that does not show additional fields created on tickets.

**Comment by btry** [comment]
The current implementation does not need any new setting in the target ticket. The additional field of the generated ticket is filled properly, based on the question of type "additional field". 

Let me find the PR of the feature, there is maybe some screenshots illustrating the result.

**Comment by btry** [comment]
There is no screenshot in the PR. I'll  complete the documentation soon. This way you will have an accurate overview of the feature. 

If you already got it but still think that something could be added to target tickets, you may describe exactly the need by describing a real use case. This may help me to understand. So far I don't see what could be added to improve the additional fields support

**Comment by fabriceverkor** [comment]
Hi
Thank your for your answers. I tried the following :
 1- I have a dropdown additionnal fields "Environment" on Tickets
 2- In the form, I have a question of Dropdown Type using the Dropdown "Addition Fields- Environment"
3- As SelftService user, when I fill the form, the possible values of the dropdown are proposed
4- But the corresponding field is empty in the created ticket.

Did I miss something ?

**Comment by fabriceverkor** [comment]
I still have the pb with GLPI  10.0.10 + FormCreator 2.13.7 + Additional Fields 1.21.4
Everything seems to work fine :
dropdown additional field can be selected in ticket :
![image](https://github.com/pluginsGLPI/formcreator/assets/104443559/4e84fe89-2135-406f-adfd-16edf38b0ad7)

dropdown additional field can be selected in form :
![image](https://github.com/pluginsGLPI/formcreator/assets/104443559/29bbc5c3-6a0c-43b0-bc1e-a31f6da2653e)

But when ticket is created, the field is not filled with question answer, which appears in ticket Description.

I works perfectly with an additional text field , which is filled by question answer and does appear in ticket Description.

**Comment by fabriceverkor** [comment]
Anyone would have an idea of what I doing wrong ?

**Comment by btry** [comment]
Hi

In the additional fields plugin, check the block is of type "Insert in the Form (before save button)"

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/76a4c6ab-f63b-476d-a745-3cdf94b12c2c)

**Comment by fabriceverkor** [comment]
Here below what I have :
![image](https://github.com/pluginsGLPI/formcreator/assets/104443559/6e4dc836-0496-4b2d-804d-d311b7ce1b5a)

**Comment by btry** [comment]
I think I got the problem. Check your previous comment : https://github.com/pluginsGLPI/formcreator/issues/2987#issuecomment-1252019028

You said the question is of type Dropdown with subtype additional field - Environment. This is wrong. You must use a question of type "Additional field" then select an available block, and a field in this block.

**Comment by fabriceverkor** [comment]
Ah yes !!!! My bad.
Thank you, it works .
