### ISSUE TITLE
Unable to modify "Limit subtree depth" value for location field

### ISSUE THREAD

**Issue by EnLef** [pluginsGLPI/formcreator#2990]
**Describe the bug**
When I try to modify the "Limit subtree depth" value in a location field, it's not saved.

**GLPI / Plugins:**
- GLPI v10.0.3
- fields               Name: Champs supplémentaires         Version: 1.17.3     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportements                  Version: 2.7.1      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                 
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.1      State: Enabled                                 
		Install Method: Manual

**Comment by btry** [comment]
Hi

The value you set is actually saved in DB, but not displayed when you re-edit the question. Here is the fix: af4096bb

**Comment by EnLef** [comment]
It's OK, thanks !
