### ISSUE TITLE
Envoi mail au valideur suivant réponse à une question dans le formulaire 

### ISSUE THREAD

**Issue by JCO946901** [pluginsGLPI/formcreator#2996]
Bonjour,

est-il possible actuellement d'envoyer un mail au valideur d'un formulaire suivant si la réponse à une question est égale à un mot spécifique ?

Bien cordialement,

**Comment by btry** [comment]
Bonjour

non, rien ne permet cela.

**Comment by JCO946901** [comment]
Merci pour votre retour
