### ISSUE TITLE
Data migration issue (&)

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#3005]
As discussed together, can you look into how "&" is handled on 2.12 -> 2.13 migration in `glpi_plugin_formcreator_questions.values` ?
It seems radio fields that contained this char didn't use encoding before 2.13, for example:
```sql
select id, name, `values` from glpi_plugin_formcreator_questions where id = 1635;
+------+--------------------+---------------------------------------------------------------------------------------------+
| id   | name               | values                                                                                      |
+------+--------------------+---------------------------------------------------------------------------------------------+
| 1635 | Sur quel domaine ? | ["Identifiant & mot de passe","Logiciel bureautique","Application métier","Matériel"]   |
+------+--------------------+---------------------------------------------------------------------------------------------+
```

After editing the question on 2.13, the value is corrected (but not during the migration):
```sql
select id, name, `values` from glpi_plugin_formcreator_questions where id = 1635;
+------+--------------------+---------------------------------------------------------------------------------------------+
| id   | name               | values                                                                                      |
+------+--------------------+---------------------------------------------------------------------------------------------+
| 1635 | Sur quel domaine ? | ["Identifiant &#38; mot de passe","Logiciel bureautique","Application métier","Matériel"]   |
+------+--------------------+---------------------------------------------------------------------------------------------+
```

I've found another question with an `&`, it seems to be an LDAP question with the following value :  
`{"ldap_auth":"5","ldap_filter":"(&(objectClass=contact))","ldap_attribute":"4"}`

However I couldn't test it so I don't know if this value should be encoded of not (there seem to be an issue on support/2.13, trying to create an LDAP question result in an error "Unable to add question").

**Comment by btry** [comment]
Formcreator does not migrate the encoding of data when swiching to GLPI 10. 

I did a test with your sample and with the branch support/2.13.0 the sample behaves properly. If I edit the question, the encoding is updated because we use Sanitize class. I don't see any problem here.

For LDAP questions, there is no problem as there is only need to escape backslashes and simple qotes.
