### ISSUE TITLE
This type of question is not compatible with public form

### ISSUE THREAD

**Issue by othye** [pluginsGLPI/formcreator#3006]
Hello, I created a public form that allows users to declare a ticket without connecting to glp, the problem that when I choose for the question category the ITIL category answer if type is incident, I have the error message : This type of question is not compatible with public forms.
Does anyone have a solution or a parameter to solve the problem?

**Comment by btry** [comment]
Bonjour

Tous les types de question qui affichent des données issues de la bdd sont interdits dans les formulaires publics, pour des raisons de sécurité.

**Comment by othye** [comment]
> 

Je te remercie , y a t il un moyen ou un paramètre pour pouvoir affichier mes catégories?

**Comment by btry** [comment]
Non : ça irait à l'encontre de la sécurité mise en place.

Vous pouvez peut être simuler les catégories en créant une question de type Select, et en créant des règles métier sur les tickets pour assigner la catégorie aux tickets générés. Fastidieux mais faisable.
