### ISSUE TITLE
Rajout de fichier joint dans un formulaire

### ISSUE THREAD

**Issue by cersyl** [pluginsGLPI/formcreator#3008]
onjour,

J'utilise au sein de mon entreprise un GLPI sur DEBIAN 11, GLPI 10.0.1 avec le plugin FORMCREATOR 2.13.1.
J'ai créé un formulaire d'assistance en accès public destiné aux utilisateurs afin qu'ils remontent leurs problèmes.
Au sein de ce formulaire je leur donne la possibilité d'insérer un fichier pour mieux expliquer leur soucis.
Ca a fonctionné jusqu'à présent, sauf que depuis un petit moment on me remonte l'impossibilité de joindre une PJ dans le ticket.

Si je teste en étant connecté au GLPI avec mon compte, pas de problème je peux bien joindre une PJ.
Si je teste en étant non connecté, lors de l'ajout de la PJ j'ai une fenêtre blanche qui apparaît avec "Information" et rien d'inscrit à l'intérieur et le bouton OK.
Certainement un problème de droit...

<img width="656" alt="Capture d’écran 2022-09-29 203849" src="https://user-images.githubusercontent.com/114693101/193115557-2615e88c-876a-4716-88c5-510e70f29f0b.png">

Je cherche en vain, mais je ne trouve pas d'où vient le problème.

J'ai également mis à jour glpi en 10.0.3 sur les conseils du forum glpi, mais pas mieux, toujours le même problème...

Debian 11 - GLPI 10.0.3 php 7.4.30 - MariaDB-0+deb11u1 - Form Creator 2.13.1

**Comment by cersyl** [comment]
Bonjour, La dernière MAJ du plugin semble m'avoir corrigé le problème d'envoi de fichier lorsque l'on est pas authentifié sur GLPI.
A voir dans le temps, mais ça semble ok.
Merci

**Comment by btry** [comment]
Bonjour

Il ne me semble pourtant pas avoir résolu ce problème. Je ne vais pas m'en plaindre ;).

Je ferme donc ce ticket. Si le problème réapparait, il faudra en ouvrir un autre avec des données actualisées.
