### ISSUE TITLE
Restore ticket confirmation toast

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#3009]
As discussed together, the "ticket confirmation toast" with the link to the newly created ticket isn't generated anymore.

**Comment by btry** [comment]
Resolved with: f43df3ebb290fdb6a8269ec0ab2e4651699c35c7 

This fix also generates a notification for other types of targets (which was not done in GLPI 9.5 : only tickets had a notificaiton.

**Comment by btry** [comment]
![image](https://user-images.githubusercontent.com/14139801/193887483-55e706f2-3711-4349-87d6-84db30ce2d6f.png)
