### ISSUE TITLE
Formcreator 2.13.1 - SLA "equal to the answer of the question" do not match

### ISSUE THREAD

**Issue by AutajonTech-LP** [pluginsGLPI/formcreator#3015]
**Describe the bug**
There is no way to assign the SLA value from a question. You've to select TTR or TTO and both list are empty. A Question which is linked to a 'service levels - SLA' or 'OLA' give the possibility to select the default value from the GLPI SLA list, this is ok., but there no way to select which type of SLA it is TTR or TTO. 

**To Reproduce**
In the Administration/Forms, select the request form,
1. Go to 'Questions' + 'Add a question'
2. Click on 'Type' and select 'Dropdown'
3. Click on 'Dropdown' and select 'Service levels - SLA'
4. Click on 'Default values' and assing on of the SLA value configured in GLPI SLA
5. See error, there's no way to select the 'Type' of SLA which must be TTR or TTO

6. Go to 'Target' + 'Add a new Target'
7. Select 'Properties'
8. Click on 'SLA' and select 'equal to the answer of the question'
9. Click on 'Question TTR/TTO'
10. See error, the list is empty with the error 'the list is empty'

**Expected behavior**
This was working fine in the previous version. Define the SLA value of the target with a value coming from a Question. The Question is linked to a GLPI SLA TTR or TTO.

**Screenshots**
In the new version, the field TTR / TTO is missing 
![354e577e-3d75-4450-87d4-cd7b12c71130](https://user-images.githubusercontent.com/115028815/193881771-deb673eb-e123-4aa3-ad26-4fe7b019159e.jpg)
- previous version : The field Type of SLA TTR or TTO is avalaible
![b5a99bd5-2b0e-4270-b555-3d51e83cea5d](https://user-images.githubusercontent.com/115028815/193881790-68a55d30-a719-42fb-9732-40f9f9b07dc5.jpg)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.3
- list of all plugins with their version
- addressing           Name: Adressage IP                   Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	financialreports     Name: Arrêtés du parc                Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	screenshot           Name: Capture d'écran                Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 10.0.1+1.0 State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.1      State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	stab                 Name: Split Timeline Action Buttons  Version: 1.1.2      State: Enabled                                 
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Browser: EDGE last version Version 105.0.1343.53

**Comment by btry** [comment]
Hi

> First bug...

> Second bug ...

Please create one issue per topic. you have 2 bugs, then you need to create 2 issues. This is required to not interlace discussions and help to resume progress if I must focus on something else then come back.

**Comment by AutajonTech-LP** [comment]
Hello. 
I've updated the bug description. This is only one bug on Question properties with an impact on the Target.

**Comment by btry** [comment]
Problem to set SLA and OLA confirmed.

**Comment by btry** [comment]
Hi

Try the above fix and feedback. I wish to include it in the next release (planned newt week).

**Comment by AutajonTech-LP** [comment]
Hi
Thanks for the fix. 
I try it and the problem is partially solved. But the problem is not solved.
The creation of a question based on a SLA is working fine and the default value can be setup from the SLA list. So this point is solved by the fix and it's ok.
But in the ticket target, when setting up the SLAs from equal to the answer to a question, the list is empty. It's not possible to select the question from the request form.

**Comment by btry** [comment]
Hi

In the target, when you select SLA from a question, 2 dropdowns appears. One is for SLA TTO and the other for SLA TTR. You must have a question of type GLPI Object / SLA in the form or none will be selectable. Depending on the type TTO or TTR of the question, it will show in the 1st or 2nd drop-down.

**Comment by btry** [comment]
Hi

Great ! I merge for the next release. Thank you for your feedback.
