### ISSUE TITLE
Added requestor can't view tickets created by formcreator in service catalog simplified interface

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/formcreator#3016]
**Describe the bug**
**Context :** 
When our users fill-up a form in the service catalog simplified interface, it usually only create 1 ticket in the IT department sub-entity.
When they want to see tickets that are currently open, they go "My requests for assistance" menu and all their tickets are listed there.
If we add a second requester to one of those ticket, the new requester can also see the ticket in the "My requests for assistance" tab of his profile.
If we click on the ticket, it links to : glpi/marketplace/formcreator/front/issue.form.php?id=XYZ&tickets_id=XYZ

**Problem :** 
Some of our forms generate 4 tickets (one in each of our sub entities for different department). Mainly HR for new staff tickets.
When one of such form is filled, it appears in the "My requests for assistance" as a form answer and links to glpi/marketplace/formcreator/front/issue.form.php?id=XYZ&plugin_formcreator_formanswers_id=XYZ
When clicking on the link, the requester can see his 4 tickets listed there.
Now if we add a second requester to one of those tickets, they won't see it in their "My requests for assistance" tab because they are added as a second requester to the ticket but not to the form answer....

Therefore, a second requester can never see the ticket in this interface....

![image](https://user-images.githubusercontent.com/38400135/193895165-099125b8-24c3-4d39-b47b-fedaa5ee433a.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version : 10.0.3
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	treeview             Name: Arborescence                   Version: 1.10.0     State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.18.0     State: Enabled                                 
		Install Method: Marketplace
	csscvinventorylabels Name: CSSCV Inventory Labels         Version: 1.0.1      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                 
		Install Method: Marketplace
	geninventorynumber   Name: Génération de numéros d'invent Version: 2.8.2      State: Enabled                                
		 Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.14.0     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Gestion des tags               Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	jamfschool           Name: JamfSchool                     Version: 1.0.1      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Marketplace
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace

**Comment by btry** [comment]
Hi

This issue may be a bit tricky to analyze and solve. Expect some delay as I have many tasks to finish first.

**Comment by btry** [comment]
I think I understood. 

When 4 tickets are created from a form, you need to add a new requester to one of those tickets. This new requester also uses the service catalog, right ?

**Comment by fralla2** [comment]
Yes that is the case. All our requesters use the service catalog interface

**Comment by btry** [comment]
Hi

I think that this PR will solve your problem. Use Formcreator 2.13.3: https://github.com/pluginsGLPI/formcreator/pull/3138

I'm waiting for your feedback.

**Comment by fralla2** [comment]
Hi @btry , Sorry for the late reply as I was away for a few weeks. I should be able to test the fix this week and come back to you.
Thanks

**Comment by fralla2** [comment]
Tested working great. Thanks

**Comment by btry** [comment]
Hi

You may migrate to Formcreator 2.13.4, the patch is already included. 

Thank you for your feedback.
