### ISSUE TITLE
upgrade from 2.13.0 Beta 3 to 2.13.1

### ISSUE THREAD

**Issue by grenona** [pluginsGLPI/formcreator#3018]
i'm getting error when upgrade

root@ldap:/var/www/html/glpi# bin/console glpi:plugin:install formcreator -f -p skip-db-check
User to use:glpi
Processing plugin "formcreator"...
SQL Error "1054": **Unknown column 'conf.entities_id**' in 'where clause' in query "INSERT INTO glpi_plugin_formcreator_entityconfigs                   (entities_id, replace_helpdesk, default_form_list_mode, sort_order, is_kb_separated, is_search_visible, is_dashboard_visible, is_header_visible, is_search_issue_visible, tile_design)                SELECT ent.id,                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 1, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 1, -2),                   IF(ent.id = 0, 0, -2)                 FROM glpi_entities ent                 LEFT JOIN glpi_plugin_formcreator_entityconfigs conf                   ON ent.id = conf.entities_id                 WHERE conf.entities_id IS NULL"
Unknown column 'conf.entities_id' in 'where clause'root@ldap:/var/www/html/glpi# 
root@ldap:/var/www/html/glpi#

**Comment by btry** [comment]
Hi

:warning: Upgrading from a Beta.3 requires specific steps described in the releases notes of 2.13.0-rc.1. See [here](https://github.com/pluginsGLPI/formcreator/releases)

The version 2.13.0-beta.3 is an untagged version. you probably used a build I shared to the community for debug and test purpose and it not a good start point for upgrades. Are you using it in production environment ?

**Comment by grenona** [comment]
HI

I have many form build that I want to keep

**Comment by grenona** [comment]
I had to force install and db check

Now I will redo my form , maybe importing them

**Comment by btry** [comment]
If you have an export of your forms, try to use a temporary instance to see if the import in 2.13.1 works well. Importing a version in an other may not work, especially because you used a beta version.

**Comment by grenona** [comment]
Hi

Import work, question are in the config, but when prompt,

Display only word Section, no filed under

Even when create a new form ,

Do you know why ?

Andre

**Comment by btry** [comment]
Hi

Is your problem solved ? 

If not, do you have errors in glpi/files/_log/php-errors.log or glpi/files/_log/sql-errors.log ?

**Comment by grenona** [comment]
All solved thanks




Andre Grenon,
Gestionnaire - Livraison Services
Service Delivery Manager

***@***.***<https://www.cortexgh.com/>




T. 514-788-7747 poste 257 | F. 514-788-7745
1255, boulevard Robert-Bourassa, bureau 900
Montréal (Québec) H3B 3W4
***@***.******@***.***>
***@***.***<https://www.facebook.com/Cortex-g%C3%A9nie-humain-100749968257594>
***@***.***<https://www.linkedin.com/company/cortex-g-nie-humain>
cortexgh.com<https://www.cortexgh.com/>





De : ***@***.***>
Envoyé le :October 13, 2022 4:43 AM
À : ***@***.***>
Cc : André ***@***.***>; ***@***.***>
Objet :Re: [pluginsGLPI/formcreator] upgrade from 2.13.0 Beta 3 to 2.13.1 (Issue #3018)


Hi

Is your problem solved ?

If not, do you have errors in glpi/files/_log/php-errors.log or glpi/files/_log/sql-errors.log ?

-

**Comment by btry** [comment]
Hi

Thank you for your feedback; I close.
