### ISSUE TITLE
FormCreator est il compatible par GLPI 9.1 ?

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#302]
La question est simple, mais coté Github/formcreator, pas d'information sur ce sujet, coté http://plugins.glpi-project.org/#/plugin/formcreator il est affiché compatible...

Le dernier numéro de version de l'application étant le suivant : 	0.90-1.3.4

Par avance, merci.

**Comment by btry** [comment]
Bonjour 

Le plugin est compatible avec GLPi 0.90 et 9.1

http://plugins.glpi-project.org/#/plugin/formcreator
