### ISSUE TITLE
section and fiel not visible

### ISSUE THREAD

**Issue by grenona** [pluginsGLPI/formcreator#3025]
when creating new or existing form after migrating from 2.13.0 to 2.13.1

no field added or present before is show in the page to enter data

![2022-10-06 08_23_57-Form Creator - 2 - GLPI](https://user-images.githubusercontent.com/88557992/194312216-7c2be937-8de0-44af-8428-6bb0f6180e8d.png)

**Comment by btry** [comment]
Hi

> no field added or present before is show in the page to enter data

Your section contains questions but since you upgraded to 2.13.1 they don't show anymore ?

**Comment by grenona** [comment]
Yes

Even if a create a brand new form from scratch




Andre Grenon,
Gestionnaire - Livraison Services
Service Delivery Manager

***@***.***<https://www.cortexgh.com/>




T. 514-788-7747 poste 257 | F. 514-788-7745
1255, boulevard Robert-Bourassa, bureau 900
Montréal (Québec) H3B 3W4
***@***.******@***.***>
***@***.***<https://www.facebook.com/Cortex-g%C3%A9nie-humain-100749968257594>
***@***.***<https://www.linkedin.com/company/cortex-g-nie-humain>
cortexgh.com<https://www.cortexgh.com/>





De : ***@***.***>
Envoyé le :October 6, 2022 8:29 AM
À : ***@***.***>
Cc : André ***@***.***>; ***@***.***>
Objet :Re: [pluginsGLPI/formcreator] section and fiel not visible (Issue #3025)


Hi

no field added or present before is show in the page to enter data

Your section contains questions but since you upgraded to 2.13.1 they don't show anymore ?

**Comment by btry** [comment]
Check the logs in glpi/files/_log . Do you ahve errors in sql-errors.log or php-errors.log ?

Also open the developer tools of the browser, then refresh the page. Do you have HTTP requests with return code 500 ?

**Comment by grenona** [comment]
***@***.***

Andre Grenon,
Gestionnaire - Livraison Services
Service Delivery Manager

***@***.***<https://www.cortexgh.com/>




T. 514-788-7747 poste 257 | F. 514-788-7745
1255, boulevard Robert-Bourassa, bureau 900
Montréal (Québec) H3B 3W4
***@***.******@***.***>
***@***.***<https://www.facebook.com/Cortex-g%C3%A9nie-humain-100749968257594>
***@***.***<https://www.linkedin.com/company/cortex-g-nie-humain>
cortexgh.com<https://www.cortexgh.com/>





De : ***@***.***>
Envoyé le :October 6, 2022 8:34 AM
À : ***@***.***>
Cc : André ***@***.***>; ***@***.***>
Objet :Re: [pluginsGLPI/formcreator] section and fiel not visible (Issue #3025)


Check the logs in glpi/files/_log . Do you ahve errors in sql-errors.log or php-errors.log ?

Also open the developer tools of the browser, then refresh the page. Do you have HTTP requests with return code 500 ?

**Comment by grenona** [comment]
i have error in the dev mode of the browser
![2022-10-06 08_54_39-SDM Template - OneNote](https://user-images.githubusercontent.com/88557992/194318109-02aa28c1-93b6-4280-9965-167315732595.png)

**Comment by grenona** [comment]
Hi

No error 500 in the browser,

I redo all the upgrade processes and same result, even in preview the field is not showing up, but in debug mode, I can see them

Andre

**Comment by grenona** [comment]
no error 500 , i redo all upgrade process from snapshot , same result, even in preview the field are not display

**Comment by grenona55** [comment]
only 1 copy

**Comment by btry** [comment]
No http error, no PHP error, no SQL error...

Try To export the form and put the JSON here.

**Comment by grenona** [comment]
i found this php log


[2022-10-06 13:28:40] glpiphplog.**CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to PluginFormcreatorAbstractField::setFormAnswer() must be an instance of PluginFormcreatorFormAnswer, null given, called in /var/www/html/glpi/marketplace/formcreator/inc/question.class.php on line 281 in /var/www/html/glpi/marketplace/formcreator/inc/abstractfield.class.php at line 62**
  Backtrace :
  marketplace/formcreator/inc/question.class.php:281 PluginFormcreatorAbstractField->setFormAnswer()
  .../twig/twig/src/Extension/CoreExtension.php:1607 PluginFormcreatorQuestion->getRenderedHtml()
  ...00f3a46bd6590290f9cccf7f31724ec80447ea8.php:200 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_7cfa97345bf27b3d081ae8316c2979aa694974d2dd888103b23f6d3401c86496->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:179      Twig\TemplateWrapper->display()
  marketplace/formcreator/inc/form.class.php:1018    Glpi\Application\View\TemplateRenderer->display()
  marketplace/formcreator/front/formdisplay.php:81   PluginFormcreatorForm->displayUserForm()

**Comment by grenona55** [comment]
Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by grenona** [comment]
{"schema_version":2.13,"forms":[{"name":"test","is_recursive":0,"icon":"fa fa-star","icon_color":"#999999","background_color":"#e7e7e7","access_rights":1,"description":"","content":"","is_active":1,"language":"en_US","helpdesk_home":0,"is_deleted":0,"validation_required":0,"is_default":0,"is_captcha_enabled":0,"show_rule":1,"formanswer_name":"test","is_visible":1,"uuid":"a474b7d7-8d9ac576-633ee1df7660b2.83158754","users":[],"groups":[],"profiles":[],"_entity":"Root Entity","_plugin_formcreator_category":"","_profiles":[],"_users":[],"_groups":[],"_sections":[{"name":"Section","order":1,"show_rule":1,"uuid":"a474b7d7-8d9ac576-633ee1df79ab55.10013309","_questions":[{"name":"test 5","fieldtype":"date","required":0,"show_empty":0,"default_values":"","itemtype":"","values":null,"description":"","row":0,"col":0,"width":4,"show_rule":1,"uuid":"a474b7d7-8d9ac576-633ee1f2191d13.02969968","_conditions":[],"_parameters":[]}],"_conditions":[]},{"name":"sec2 ","order":2,"show_rule":1,"uuid":"a474b7d7-8d9ac576-633f12d3062b74.89604004","_questions":[{"name":"zxcv","fieldtype":"date","required":0,"show_empty":0,"default_values":"","itemtype":"","values":null,"description":"","row":0,"col":0,"width":4,"show_rule":1,"uuid":"a474b7d7-8d9ac576-633f13950bbbf8.76926386","_conditions":[],"_parameters":[]}],"_conditions":[]}],"_conditions":[],"_targets":{"PluginFormcreatorTargetTicket":[{"name":"aaa","target_name":"aaa","source_rule":1,"source_question":7,"type_rule":1,"type_question":1,"content":"##FULLFORM##","due_date_rule":1,"due_date_question":0,"due_date_value":null,"due_date_period":0,"urgency_rule":1,"urgency_question":0,"validation_followup":1,"destination_entity":1,"destination_entity_value":0,"tag_type":1,"tag_questions":"","tag_specifics":"","category_rule":1,"category_question":0,"associate_rule":1,"associate_question":0,"location_rule":1,"location_question":0,"commonitil_validation_rule":1,"commonitil_validation_question":null,"show_rule":1,"sla_rule":1,"sla_question_tto":0,"sla_question_ttr":0,"ola_rule":1,"ola_question_tto":0,"ola_question_ttr":0,"uuid":"a474b7d7-8d9ac576-633f13648882a0.82363166","_tickettemplate":"","_actors":[{"itemtype":"PluginFormcreatorTargetTicket","actor_role":1,"actor_type":1,"actor_value":0,"use_notification":1,"uuid":"a474b7d7-8d9ac576-633f13648a5778.69512920"},{"itemtype":"PluginFormcreatorTargetTicket","actor_role":2,"actor_type":2,"actor_value":0,"use_notification":1,"uuid":"a474b7d7-8d9ac576-633f13648b1b11.75053442"}],"_ticket_relations":[],"_conditions":[]}],"PluginFormcreatorTargetChange":[],"PluginFormcreatorTargetProblem":[]},"_validators":[],"_translations":[{"name":"en_US","comment":"","uuid":"a474b7d7-8d9ac576-633f13779f04a1.73242002","_strings":[]}]}]}

**Comment by btry** [comment]
Hi

I tested the form, it works on my instance

![image](https://user-images.githubusercontent.com/14139801/194479773-06575ed3-1a3f-4c4d-b86e-eb5baef6908e.png)

**Comment by btry** [comment]
I see [you found a log](https://github.com/pluginsGLPI/formcreator/issues/3025#issuecomment-1270453988) (. I'll check it.

**Comment by btry** [comment]
I'm suspecting you have a bad file in the plugin. Please send here as attachment the file `inc/form.class.php`

**Comment by grenona55** [comment]
How could i verify checksum of the file ?

Envoyé à partir de Outlook<http://aka.ms/weboutlook>
From: Andre Grenon ***@***.***>
Sent: October 7, 2022 7:09 AM
To: pluginsGLPI/formcreator ***@***.***>; pluginsGLPI/formcreator ***@***.***>
Cc: Comment ***@***.***>; Andre Grenon ***@***.***>
Subject: RE: [pluginsGLPI/formcreator] section and fiel not visible (Issue #3025)

Here is the file

Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by grenona** [comment]
MD5 of the file: 1947f404604692dd5f66310b66c1682f

**Comment by grenona** [comment]
any new clue why it not working ?

**Comment by btry** [comment]
Describe your procedure to upgrde from alpha.3 to 2.13.1.

**Comment by grenona55** [comment]
I follow your link you send me , some sql delete command
Force upgrade etc….

I just find this in debug mode :

***@***.***
Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by btry** [comment]
Yes, but I want to see how you put  the files of the new version in your GLPI.

**Comment by grenona** [comment]
I clean the folder first

I copy the file new one

I force upgrade command

**Comment by btry** [comment]
It looks good. :thinking:

**Comment by grenona55** [comment]
Here is the detail

I did 3rd time the upgrade

***@***.***:/var/www/html/glpi# bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade
Processing plugin "formcreator"...
The database schema is not consistent with the installed Formcreator 2.13.1. To see the logs enable the plugin and run the command bin/console glpi:database:check_schema_integrity -p formcreator
Plugin "formcreator" has been installed and can be activated.



***@***.***:/var/www/html/glpi# bin/console glpi:plugin:install formcreator -u glpi -f -p force-upgrade
Processing plugin "formcreator"...


The database schema is not consistent with the installed Formcreator 2.13.1. To see the logs enable the plugin and run the command bin/console glpi:database:check_schema_integrity -p formcreator
Plugin "formcreator" has been installed and can be activated.


***@***.***:/var/www/html/glpi# bin/console glpi:database:check_schema_integrity -p formcreator


PHP Notice:  Undefined index: use_filter_assign_group in /var/www/html/glpi/marketplace/escalade/setup.php on line 140
The plugin "formcreator" is not found or not activated.


***@***.***:/var/www/html/glpi# php bin/console glpi:plugin:activate formcreator
Processing plugin "formcreator"...
Plugin "formcreator" has been activated.
***@***.***:/var/www/html/glpi# bin/console glpi:database:check_schema_integrity -p formcreator


PHP Notice:  Undefined index: use_filter_assign_group in /var/www/html/glpi/marketplace/escalade/setup.php on line 140
Table schema differs for table "glpi_plugin_formcreator_targetproblems".
--- Original
+++ New
@@ @@
 CREATE TABLE `glpi_plugin_formcreator_targetproblems` (
   `id` int NOT NULL AUTO_INCREMENT,
-  `category_question` int unsigned NOT NULL DEFAULT 0,
+  `category_question` int NOT NULL DEFAULT 0,
   `category_rule` int NOT NULL DEFAULT 1,
   `causecontent` text,
   `content` text,
-  `destination_entity_value` int unsigned NOT NULL DEFAULT 0,
+  `destination_entity_value` int,
   `destination_entity` int NOT NULL DEFAULT 1,
   `impactcontent` text,
   `name` varchar(255) NOT NULL DEFAULT '',
@@ @@
   `tag_specifics` varchar(255) NOT NULL DEFAULT '',
   `tag_type` int NOT NULL DEFAULT 1,
   `target_name` varchar(255) NOT NULL DEFAULT '',
-  `urgency_question` int unsigned NOT NULL DEFAULT 0,
+  `urgency_question` int NOT NULL DEFAULT 0,
   `urgency_rule` int NOT NULL DEFAULT 1,
   `uuid` varchar(255),
   PRIMARY KEY (`id`),
   KEY `problemtemplates_id` (`problemtemplates_id`)
 )
***@***.***:/var/www/html/glpi#

Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by btry** [comment]
Glpi version is ok, the inconsistencies in the database should be fixed, but are harmless. 

For now I don't see why the code fails. A null value is given instead of an instance of an object, but the code explicitly creates this instance to fill the needs of the method causing the fatal error. 

If your copy of the plugin is not modified, I don't see why it fails. A debugging session should help but I cannot do that without professional support contract.

**Comment by grenona55** [comment]
HI

I use now 10.0.2 and 2.13.1 work just fine

if I move to 10.0.3, nothing work again, but I will try to go from 10.0.2 (with 2.13.1) to 10.0.3 to see if it good or not



Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by btry** [comment]
This is unexpected. I'm running on a development version of GLPI. In short this is glpi 10.0.3 + recent bugfixes.

I'll test with the release 10.0.3, but I expect the plugin will work as expected. I'll let you know my result.

**Comment by grenona** [comment]
Ok i will also

At least it work on 10.0.2



Andre Grenon,
Gestionnaire - Livraison Services
Service Delivery Manager

***@***.***<https://www.cortexgh.com/>




T. 514-788-7747 poste 257 | F. 514-788-7745
1255, boulevard Robert-Bourassa, bureau 900
Montréal (Québec) H3B 3W4
***@***.******@***.***>
***@***.***<https://www.facebook.com/Cortex-g%C3%A9nie-humain-100749968257594>
***@***.***<https://www.linkedin.com/company/cortex-g-nie-humain>
cortexgh.com<https://www.cortexgh.com/>





De : ***@***.***>
Envoyé le :October 7, 2022 1:44 PM
À : ***@***.***>
Cc : André ***@***.***>; ***@***.***>
Objet :Re: [pluginsGLPI/formcreator] section and fiel not visible (Issue #3025)


This is unexpected. I'm running on a development version of GLPI. In short this is glpi 10.0.3 + recent bugfixes.

I'll test with the release 10.0.3, but I expect the plugin will work as expected. I'll let you know my result.

**Comment by btry** [comment]
Glpi 10.0.3 addresses security issues. Be careful if you run an older version.

**Comment by grenona55** [comment]
Final test

If i do this :
10.0.2 with 2.13.alpha3 to 10.0.3 (still work) and after do  2.13.1 (nothing work no display)

If I do

10.0.2 2.13.1 (work fine) after do 10.0.3 still working fine with 2.13.1

I’m happy 😊

Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by grenona55** [comment]
Last issue :

In chrome i’m getting this now

Undefined index: use_filter_assign_group in /var/www/html/glpi/marketplace/escalade/setup.php at line 140




Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by btry** [comment]
> In chrome i’m getting this now

Undefined index: use_filter_assign_group in /var/www/html/glpi/marketplace/escalade/setup.php at line 140

This related to escalade plugin. I saw it also in your upgrade feedback

**Comment by btry** [comment]
Hi

Showing forms with GLPI 10.0.3 works well on my side. I can't investigate further. As you choosed to stick to GLPI 10.0.2, I close.

The error related to escalade plugin should be reported in its repository.

**Comment by grenona55** [comment]
I’m using 10.0.3 and it work now


Envoyé à partir de Outlook<http://aka.ms/weboutlook>

**Comment by grenona** [comment]
No one copy only

**Comment by grenona55** [comment]
Here is the file

Envoyé à partir de Outlook<http://aka.ms/weboutlook>
