### ISSUE TITLE
Phone GLPI Object field searchable

### ISSUE THREAD

**Issue by helioguardabaxo** [pluginsGLPI/formcreator#3027]
Hi!
Currently, the field is not searchable:
![image](https://user-images.githubusercontent.com/24301085/194543074-29a25a4b-4060-4153-a97e-d3034f0e2508.png)

Would be very nice search phone in field (like computers GLPI Object):
![image](https://user-images.githubusercontent.com/24301085/194543282-3ebd11fe-7702-4a6e-a7fb-e9f43d554525.png)

Thanks!

**Comment by btry** [comment]
Hi

Dropdown and glpi object question types shoud be searchable when there are enough items to show. See if you have more items than the count configured in the screenshot below

![image](https://user-images.githubusercontent.com/14139801/194543967-b3be4e7e-53ea-4f2e-9859-143cc32aee44.png)

**Comment by helioguardabaxo** [comment]
Oh... it's really!
Thanks for your help, @btry !
