### ISSUE TITLE
Unable to install Formcreator. 

### ISSUE THREAD

**Issue by talbim** [pluginsGLPI/formcreator#3028]
Hi everyone, hope you're all doing well !!! 

I have some troubles to install Formcreator on my new upgrade environment.

I'm using GLPI 10.0.3 and when i try to install via the marketplace (and manually) and error occured ; 

"The database schema is not consistent with the installed Formcreator 2.13.1. To see the logs run the command bin/console glpi:plugin:install formcreator -f"

Everything is ok for my DB whos MariaDB. 

When i try to run the command line it ask me for a user but i don't know what is the user they refer to...

Can you please help me :)

Kind Regards 

Melvin

**Comment by btry** [comment]
Hi

Read the releases notes of Formcreator 2.13.1.

> Everything is ok for my DB whos MariaDB.

It seems not. What is the output if the CLI command ?

**Comment by talbim** [comment]
Hi btry,

First, thank for your qick response ! Apreciate it ! :) 

I did but it seems not working ... 
![Capture](https://user-images.githubusercontent.com/6168790/194861196-fde816b9-efce-4f23-b5ca-77c10728ae6f.PNG)


I upgrade from 9.5 to 10.0.3 !

**Comment by btry** [comment]
The plugin says you already have Formcreator 2.13.1. Either a previous upgade of the plugin succeeded, either there us a problem detecting the previous version of the plugin.

You should rollback to your latest backup before the 1st attempt to upgrade of Formcreator. I need this to know the state of some values in DB.

**Comment by talbim** [comment]
Re,
J'ai vu que vous étiez français est-ce possible de switcher en Francais ? 

J'ai réalisé depuis un ancien snapshot un nouvelle upgrade de GLPI.
J'ai voulu faire un upgrade depuis le marketplace mais impossible de migrer la table en question.

Voici un message d'erreur : 
2.13.1 multiple alter in glpi_plugin_formcreator_issues - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_issues` CHANGE `date_creation` `date_creation` TIMESTAMP NULL DEFAULT NULL , CHANGE `date_mod` `date_mod` TIMESTAMP NULL DEFAULT NULL , CHANGE `original_id` `items_id` INT NOT NULL DEFAULT '0' , CHANGE `sub_itemtype` `itemtype` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' , DROP INDEX `original_id_sub_itemtype` , ADD INDEX `item` (`itemtype`, `items_id`) - L'erreur est Incorrect datetime value: '1970-01-01 01:00:00' for column `glpi`.`glpi_plugin_formcreator_issues`.`date_creation` at row 6486

**Comment by btry** [comment]
Ca doit pouvoir s'arranger avec un patch. Vous devriez avoir un backtrace dans sql-errors.log correspondant à cette erreur. Pouvez vous le copier ici ?

**Comment by talbim** [comment]
En effet je trouve ça bizarre. :) 

[sql-errors.log](https://github.com/pluginsGLPI/formcreator/files/9746186/sql-errors.log)

Merci beaucoup !

**Comment by btry** [comment]
L'erreur ne s'y trouve pas. Regardez dans glpi/files/_log/migration_to_2.13.1.log . Mettez juste l'extrait correspondant à ce ticket svp.

**Comment by talbim** [comment]
Voici : 
[migration_to_2.13.1.log](https://github.com/pluginsGLPI/formcreator/files/9746212/migration_to_2.13.1.log)

**Comment by btry** [comment]
pas de backtrace ici non plus. Du coup j'en suis à deviner où est l'erreur. Votre précédente version de Formcreator est inférieure à 2.12.0 ?

**Comment by btry** [comment]
Exécutez cette requête pour voir combien de lignes ont le souci

select count(*) from glpi_plugin_formcreator_issues where date_creation < '2000-01-01 00:0:00';

**Comment by talbim** [comment]
Le resultat es "1"

**Comment by talbim** [comment]
![Capture](https://user-images.githubusercontent.com/6168790/194877001-dee824f1-e97c-4558-98d1-d77664474642.PNG)

**Comment by btry** [comment]
Je en vois pas de patch facile et sans risque pour gérer le problème. Il n'y qu'une colonne posant souci, et c'est sûrement une donnée corrompue.

Retrouvez cette colonne et montrez la valeur de la colonne date_mod.

**Comment by talbim** [comment]
Voici la valeur de la colonne dat_mod de la ligne en question : 
![Capture](https://user-images.githubusercontent.com/6168790/194877558-462ab5a6-3174-4b68-b2ce-b6dcd3ae6e9a.PNG)

**Comment by btry** [comment]
Trouvez le ticket 6496 et la valeur de sa colonne date_creation. Copiez la dans date_creation de la ligne dans glpi_plugin_formcreator_issues. Ensuite retentez l'uptgrade.

**Comment by talbim** [comment]
J'ai essayé cela n'a pas fonctionné.
Néanmoins c'était un environnement de test. 
J'ai donc supprimer le ticket qui posait problème et l'upgrade est passé :)

**Comment by btry** [comment]
OK; mais vous aurez certainement le problème lors de l'upgrade de la prod. Si vous avez besoin de garder le ticket il faudra modifier cette date.
