### ISSUE TITLE
TextArea default value field show "rn" character in response form

### ISSUE THREAD

**Issue by helioguardabaxo** [pluginsGLPI/formcreator#3030]
Hi,

When I use "default values" field in a question with TextArea type:
![image](https://user-images.githubusercontent.com/24301085/195161586-e93a6aa6-66fc-4586-8a07-918b2cbcebd5.png)

In response form "rn" is printed:
![image](https://user-images.githubusercontent.com/24301085/195161759-2e28cb81-26ec-4bef-93dd-bdaadf5ea4b7.png)

**Comment by btry** [comment]
Hi 

Try the latest revision of the branch support/2.13.0. It is possible I already fixed it. No computer near me right  now to check the commit log.

**Comment by helioguardabaxo** [comment]
I am using 2.13.0 RC1
I will update.

Thanks!
