### ISSUE TITLE
Problème de SLA

### ISSUE THREAD

**Issue by DeltatecAS** [pluginsGLPI/formcreator#3037]
Bonjour,

je suis en GLPI V10.0.3 et la dernière version de FormCreator. 

J'ai créé des règles métier qui permet d'affecter des SLA. Ces règles sont déterminées avec le catégorie, l'urgence et le type de ticket (incident, demande)

Voici les comportements étrange : 
* Lorsque je créé un ticket avec un utilisateur qui a un profil simplifié mes SLA ne s'affectent pas
* Lorsque je créé un ticket avec un utilisateur qui a un profil technicien les SLA s'affectent comme il faut
* Lorsque je créé un ticket via un formulaire de FormCreator avec un utilisateur qui a un profil simplifié mes SLA s'affectent comme il faut

Je poste donc ma question, est ce que FormCreator fait quelque chose de spécifique que GLPI ne ferait pas ? Est ce que c'est dû à une installation de FormCreator car j'ai l'impression que lors de la mise à jour vers la version 10 de GLPI je n'avais pas ce problème jusqu'à l'installation de FormCreator (qui était encore en beta)

**Comment by btry** [comment]
Bonjour

Formcreator peut manipuler les SLA, mais je pense que peu se servent de ces fonctionnalités.

Pour chercher un éventuel bug j'ai besoin que vous testiez la dernière version de GLPI ave la dernière version de Formcreator. Ensuite, si le bug persistes, il me faut un formulaire simplifié au maximum pouvant reproduire le souci. Dans votre cas il faudra aussi décrire les règles métier (si possible simplifiées aussi) et la structure de votre arborescence de catégories. Tout cela est nécessaire pour que je puisse reproduire sur on instance.

Vérifiez aussi si vous avez des erreurs php ou sql dans les logs de GLPI (dossier files/_log/ ).

**Comment by DeltatecAS** [comment]
Je vais tenter en installant les dernière versions.

Merci pour les infos.

**Comment by DeltatecAS** [comment]
Bonjour,
J'ai mis à jour Formcreator pour avoir la toute dernière version. J'ai tout de suite fait un test et ça ne fonctionne pas. Par contre j'ai réalisé quelque chose je vous explique

- J'ai affecté un profil User au compte Administrator (en plus de celui d'administrateur)
- Je me suis connecté avec le compte Administrator et j'ai changé de profil pour passer en mode user (avec la fonction debug activée. A la base c'était pour voir s'il ne me trouvait pas d'erreur)
- J'ai créé un ticket => les SLA se sont bien affecté grâce à la règle métier
- Je me suis connecté avec un compte utilisateur tout à fait basique qui a uniquement le profil User
- J'ai créé un ticket => les SLA ne se sont pas affectés

**Comment by btry** [comment]
Bonjour

> Par contre j'ai réalisé quelque chose je vous explique [...]

Quand vous créez les tickets vous utilisez un formulaire de Formcreator ?

**Comment by DeltatecAS** [comment]
Non c'est le système normal de GLPI mais si je n'ajoute pas le plugin formcreator je n'ai absolument pas ce problème.

**Comment by DeltatecAS** [comment]
J'ai trouvé le problème et c'est dû à une modification custom
