### ISSUE TITLE
Blocage du formulaire créé depuis formcreator suite au clic sur envoyer

### ISSUE THREAD

**Issue by steph915** [pluginsGLPI/formcreator#3038]
**Describe the bug**
Bonjour, 

nous sommes en version 10.0.3 de glpi et en version 2.13.1 de formcreator sous windows server
Nous avons migré depuis glpi 9.5.4 et formcreator 2.12.4 sous centos
Nous avons donné le droit à certains utilisateurs de faire des demandes via des formulaires avant migration aucun soucis que ce soit avec un compte utilisateurs ou bien un compte de technicien.

En revanche depuis la migration, les comptes utilisateurs restent bloqués après avoir cliqué sur "envoyer" alors qu'avec les comptes techniciens pas de soucis.

J'avoue ne pas savoir où faire mes recherches. J'ai déjà tenté de supprimer le plugin et le réinstaller, supprimer le formulaire et le refaire, refaire les droits glpi de l'utilisateur. Mais rien n'y change.

Si vous avez une petite idée .

Merci d'avance 

Bonne journée à vous

**Comment by btry** [comment]
Bonjour

Appliquez ce patch : https://github.com/pluginsGLPI/formcreator/commit/abed861018c4a04b3385c43223a2554eaf4dcaf7

Il ajoute un retour visuel pour confirmer que le clic a été pris en compte. Il verrouille aussi le bouton pour éviter que le demandeur clique plusieurs  fois.

Si vous êtes sous PHP 8.1, des warnings PHP peuvent perturber la redirection après le clic sur le bouton de soumission. Vous pouvez les corriger avec les 2 correctifs suivants
https://github.com/pluginsGLPI/formcreator/commit/8ff7ff91a2811937ec6ad7b4d37cd909b99373dd
https://github.com/pluginsGLPI/formcreator/commit/297fb27133851d5c9cd470c422a360b1f9ecfe90

**Comment by steph915** [comment]
J'ai tester le patch abed861, il met bien le bouton en surbrillance et il empêche de re cliquer dessus par contre il reste toujours sur la même page, nous sommes en php 8.0.20 dois je quand même passer les patchs php ?

**Comment by btry** [comment]
Vous pouvez les passer, mais ils ne résoudront pas le souci. Il seront de toute façon inclus dans la prochaine release.

Pour revenir au bug, regardez dans php-errors.log et sql-errors.log si des erreurs sont enregistrées quand vous reproduisez le problème. Je pense qu'il y aura aussi une erreur javascript dans la console des outils développeur du navigateur.

**Comment by steph915** [comment]
Merci je vais fouiller dans les logs voir si je trouve. Bon week-end

**Comment by btry** [comment]
duplicate #3035

**Comment by btry** [comment]
Bonjour 

#3056 devrait  aussi aider à résoudre les soucis si il survient à l'upload d'images dans une zone de texte.

**Comment by steph915** [comment]
Résolu avec la mise à jour du plugin
