### ISSUE TITLE
Error inserting condition in the form in the questions field

### ISSUE THREAD

**Issue by Rafaeldgs** [pluginsGLPI/formcreator#3047]
**Describe the bug**
When entering a condition in the questions field, in the browser console it shows an error

**To Reproduce**
1. Administration > Forms > Edit a form > Questions field > Condition to show the submit button
2. Clique no + para inserir condição
3. Will show the error Uncaught TypeError: plugin_formcreator.addEmptyCondition is not a function
    at HTMLButtonElement.onclick (form.form.php?id=47:1:20)

**Expected behavior**
Open new field for new condition

**Screenshots**

![2022-10-20_12-17](https://user-images.githubusercontent.com/88557932/196990606-62109077-e10c-4cf9-a6ee-f3bf12dff5e7.jpg)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.3
- Formcreator 2.13.2 DEV

**Desktop (please complete the following information):**
 - OS: Windows 2012 server
 - Browser chrome
 

**Additional context**

No error in phplog

**Comment by btry** [comment]
Hi

I don't reproduce. I tested questions sections and forms.
![Peek 20-10-2022 18-14](https://user-images.githubusercontent.com/14139801/197002679-5dfb18f1-df57-4eb7-ae1b-fb7b86308a96.gif)

**Comment by Rafaeldgs** [comment]
Following is the error
![2022-10-20 13-20-38](https://user-images.githubusercontent.com/88557932/197004744-63cc7c37-244e-4495-a2ca-f46ddd0abbd2.gif)

**Comment by btry** [comment]
in version 2.13.x the function should be plugin_formcreator_addEmptyCondition()

I sometimes move functions with prefix plugin_formcreator_ in the dedicated class, but this one is not moved yet.

I think that you have a a twig template from an other branch. Try to enable debug mode, then reproduce the bug. I expect it will disappear.

**Comment by Rafaeldgs** [comment]
Yes, in debug mode the error does not happen..

**Comment by btry** [comment]
Hi

Now disable debug mode. The error should not come back.

**Comment by Rafaeldgs** [comment]
I turned it off, but the error still occurs :(

**Comment by btry** [comment]
I'm nearly sure that there is a cache problem in template files.

Delete recursively files in glpi/files/_cache/templates/

then try again.

**Comment by Rafaeldgs** [comment]
Very good, this way cleaning the cache folder worked!
I ask, is there any impact or problem in deleting these files from the path glpi/files/_cache/templates/?

**Comment by btry** [comment]
There is no impact. GLPI will be slightly slowed down for each web page where a cache miss occurs. Nobody should notice it. The more GLPI is used the more the cach will fill reducing cache miss. After a few days I think most files will be rebuilt.
