### ISSUE TITLE
Bug a l'envoi du formulaire bouton envoyer

### ISSUE THREAD

**Issue by talbim** [pluginsGLPI/formcreator#3049]
Bonjour, 

Depuis la migration les utilisateurs self service n'arrivent pas a créer certains ticket depuis certains fomrulaire uniquement. 
En effet le bouton envoyer ne créer pas le ticket et semble juste bloquer. 
J'ai regarder j'ai vu que certains autre utilisateurs avait eu l'erreur, mais pas le même comportement.

J'ai une erreur 400 
![image](https://user-images.githubusercontent.com/6168790/197226579-e2c03795-0465-4ca4-a817-793a534095ca.png)

Le ticket ne se créer pas et rien ne se passe je peux cliquer a l'infini sur "Envoyer".

Avez-vous une idée ? 

Merci d'avance pour le travail accompli :) 

GLPI 10.0.3
Formcreator : 2.13.1

**Comment by btry** [comment]
Bonjour

Upgrades vers Formcreator 2.13.2

**Comment by talbim** [comment]
Bonjour @btry ! 

Merci pour ta réponse. J'ai réalisé l'upgrade mais toujours l'erreur.

Cette fois ci j'ai dans le bouton envoyer deux fois le texte "EnvoyerEnvoyer" quand je clique dessus et rien ne se passe.

Je remarque aussi que c'est quand je réponse a certaine question que ce bug arrive. Quand je réponse a d'autre le bug ne se produit pas.

**Comment by btry** [comment]
Bonjour

Avez vous tenté d'uploader une image dans une zone de texte ?

**Comment by talbim** [comment]
@btry,
Non en effet pas d'image. Il s'agit de question type "Boite a cocher".

**Comment by btry** [comment]
Montrez la configuration de la question correspondant. Je viens tou juste de corriger un problème avec des antislashes.

**Comment by talbim** [comment]
Cette question : 
![image](https://user-images.githubusercontent.com/6168790/197504363-431f776a-5cfd-44d1-8dbc-3318eb88bc6e.png)
Quand j'enlève le champs obligatoire et ne rentre pas cette question dans le formulaire ca passe niquel.

N'y aurait t'il pas un bug avec les "<" ">" ?

**Comment by btry** [comment]
Il peut y avoir un problème avec les symboles `>` et `<`. Si vous rendez la question obligatoire et que vous choisisez autre chose que ces 2 entrées, le formulaire se comporte bien ?

Supprimez ces symboles en attendant que je puisse chercher une solution.

**Comment by talbim** [comment]
@btry En effet j'ai remplacé le > et < par du texte.
La ca passe ni quel, je pense qu'il y a un soucis avec ce charactère

**Comment by btry** [comment]
Il semble que le fix que je viens de verser résout le souci. Essayez le

 https://github.com/pluginsGLPI/formcreator/pull/3050

**Comment by FredVH** [comment]
I have the same issue, but with the dropdown
![image](https://user-images.githubusercontent.com/45260509/198298516-ff2a79db-a6c1-41a3-8b16-5bd567b9cdf7.png)

**Comment by btry** [comment]
Hi @FredVH

I'm waiting for feedback for the patch #3050. Try it and tell if the problem is soled.

**Comment by btry** [comment]
Hi

@talbim @FredVH 

Can you feedback about the above patch ?

**Comment by rafacss** [comment]
In a public form the sub

https://user-images.githubusercontent.com/67194670/199962113-dd3badab-6429-4d5a-8ec5-8985ef38b6f0.mp4

mit button does not appear for anonymous users, only visible when authenticated when someone has a GLPI account. Problem occurring in GLPI 10.0.4 and FormCreator 2.13.2.

**Comment by btry** [comment]
Hi @rafacss I think this is not related to this issue. Please open a new one.

**Comment by rafacss** [comment]
> 

I opened a new one! thanks.

**Comment by btry** [comment]
Hi

Having no feedback, I assume the patch worked as expected. I close.
