### ISSUE TITLE
GLPI 10 Form Creator [Ticket urgency Assigment] Equals to the Answer -Not showing options

### ISSUE THREAD

**Issue by danisscenario** [pluginsGLPI/formcreator#3051]
Hi, i am creating a form to get a urgency of a ticket based on the answer but in Target Ticket i don't see my urgency options. The Questions appear to be empty . I don't know if this is a bug or i missed something. I would appreciate any form of help
![file1](https://user-images.githubusercontent.com/116552464/197489125-0903fcaa-2a0c-4867-b906-1712aad80608.jpg)
![file2](https://user-images.githubusercontent.com/116552464/197489131-1071f0cd-f574-4fc0-9a0a-9bfb49ab75ae.jpg)

**Comment by btry** [comment]
Hi

Which version of Formcreator ?

Do you have in the form at least one question of type "Urgency" ?

**Comment by danisscenario** [comment]
Form creator version is 2.13.2 

Thanks for pointing me in right direction it turns out i tried to set it up manually via Selecting from options rather than setting up The question as urgency. Thanks for the kick i needed.
