### ISSUE TITLE
FOrm Creator new version

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/formcreator#3052]
**Describe the bug**
Bonjour 
j'ai mis à jour la version ce jour de Fomrcérator 
mais au moment de l'activer il me met ce message 
"Le schéma de la base de données n'est pas conforme avec le Formcreator installé 2.13.1. Pour visualiser le journal, exécutez la commande bin/console glpi:plugin:install formcreator -f" 
le message suivant apparait "
The version of the database is not compatible with the version of the installed files. An update is necessary.
"
Pourtant j'ai un autre glpi sur le même serveur en même version et je n'ai pas eu de souci de mise à jour 

operating system: Linux 
 PHP 7.4.32 
Apache/2.4.41
Server Version: 8.0.30-0ubuntu0.20.04.2 	
 Database engine version (8.0.30) i

**Comment by btry** [comment]
Bonjour

 Autre GLPI = autre base de données avec un vécu potentiellement différent.

Alors... pour commencer la commande dans le message d'erreur est fausse. Ca mérite un fix.

La commande qui doit être affichée est **bin/console glpi:database:check_schema_integrity -p formcreator**. Elle requiert que le plugin soit activé donc je vous conseille de revenir à 2.13.1, activer le plugin et lancer la commande de vérification. 

Corrigez les anomalies  puis réessayez l'upgrade.

**Comment by btry** [comment]
Autre chose : quand GLPI 10.0.4 sera sorti il ne sera plus nécessaire d'activer le plugin pour exécuter la commande de vérification. Ca supprimera ce problème de poule et d'oeuf.

**Comment by imanou10** [comment]
ok je vais tenter de remettre l'ancienne version merci pour ce retour rapide.
je vous tiens informé

**Comment by imanou10** [comment]
je suis revenu à la version 2.13.1 mais impossible de l'activer 
Failed to check the sanity of the tables!
The database schema is not consistent with the installed Formcreator 2.13.2.

**Comment by btry** [comment]
Modifiez la version du plugin dans la table glpi_plugins. Ramenez la valeur à 2.13.1, cela va débloquer l'activation.

**Comment by imanou10** [comment]
![image](https://user-images.githubusercontent.com/36695393/197555045-36dfb0f1-c484-42b7-9626-d7a46c4ce64b.png)

je suis déjà en bonne version :(

**Comment by btry** [comment]
Passez le statut de la ligne à la  valeur 4

**Comment by imanou10** [comment]
alors c'est bon j'ai avancé 
maintenant quand j 'ai voulu l'activer il me met ce message 
UPDATE `glpi_plugin_formcreator_formanswers` SET `requester_id` = 0 WHERE `requester_id` IS NULL - L'erreur est Table 'interglpi.glpi_plugin_formcreator_formanswers' doesn't exist
et après plusieurs tests en fait il me supprimer cette table.

**Comment by btry** [comment]
Bonjour, 

Je pense que dans vos manipulations un upgrade a partir d'une version top ancienne a été effectué. N'ayant pas tous les détails, je recommanderais de repartir du backup que vous avez normalement fait avant de lancer votre tentative d'upgrade.

**Comment by imanou10** [comment]
Bonjour 
Je suis finalement reparti de 0 et reconstruit mes tables avec ma sauvegarde.
Tout est fonctionnel à présent merci de votre aide
