### ISSUE TITLE
Not Update Plugin.

### ISSUE THREAD

**Issue by JeanBuchweitz** [pluginsGLPI/formcreator#3060]
After trying to update the Plugin I am getting the error:

The database schema is not consistent with the installed Formcreator 2.13.1. To see the logs run the command bin/console glpi:plugin:install formcreator -f 

however when trying to run the command it only singles out a user. And I can't move forward

 glpihqi]# bin/console glpi:plugin:install formcreator -f
User to use:

  O nome de usuário definido pela opção --username é inválido.

glpi:plugin:install [-a|--all] [-p|--param [PARAM]] [-u|--username USERNAME] [-f                                                           |--force] [--] [<directory>...]

[root@JMBAWB glpihqi]# bin/console glpi:plugin:install formcreator -f
User to use:glpi

  O nome de usuário definido pela opção --username é inválido.

glpi:plugin:install [-a|--all] [-p|--param [PARAM]] [-u|--username USERNAME] [-f                                                           |--force] [--] [<directory>...]

**Comment by btry** [comment]
Hi

The command **bin/console glpi:plugin:install formcreator -f
** interactively asks whith which user you want to upgrade. You may specify this user wh the argument -u <username> or specify it when the command asks it.

th account **glpi** is usually used but maybe you deleted it. Choose any super admin account avainable in the DB.

**Comment by typtop21** [comment]
Hi,
I still have my GLPI account
I activated it and registered as super administrator but the same problem is there
Instalaltion : NOK
How do I roll back to the previous version?

**Comment by btry** [comment]
> I activated it and registered as super administrator but the same problem is there

If you successfully activated the plugin then no need to rollback. You must now focus on the inconsistencies found in the database. The plugin printed a diff to show where are the differences. Can you show it ?

**Comment by typtop21** [comment]
the plugin is not active

**Comment by btry** [comment]
Let me sumup your situation, correct me if I'm wrong somewhere
- You were using Formcreatore 2.13.1 and you're upgading to 2.13.2. 
- I'm not sure how you were upgrading. Probably from the UI of GLPI.
- you tried **bin/console glpi:plugin:install formcreator -f**  from CLI, and the plugin fails to upgrade

When you run **bin/console glpi:plugin:install formcreator -f** and it fails with a database inconsistency error, it show you a diff with the detected inconsistencies, like a diff file. I need to see it. 

The diff looks like this  : 

```
Table schema differs for table "glpi_plugin_formcreator_categories".
--- Expected database schema
+++ Current database schema
@@ @@
 CREATE TABLE `glpi_plugin_formcreator_categories` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `ancestors_cache` text,
+  `background_color` varchar(255),
   `comment` text,
   `completename` varchar(255),
+  `icon_color` varchar(255),
+  `icon` varchar(255),
   `knowbaseitemcategories_id` int unsigned NOT NULL DEFAULT 0,
   `level` int NOT NULL DEFAULT 1,
   `name` varchar(255) NOT NULL DEFAULT '',

Table schema differs for table "glpi_plugin_formcreator_entityconfigs".
--- Expected database schema
+++ Current database schema
@@ @@
   `default_form_list_mode` int NOT NULL DEFAULT -2,
   `entities_id` int unsigned NOT NULL DEFAULT 0,
   `header` text,
+  `home_page` int NOT NULL DEFAULT -2,
+  `is_category_visible` int NOT NULL DEFAULT -2,
   `is_dashboard_visible` int NOT NULL DEFAULT -2,
   `is_header_visible` int NOT NULL DEFAULT -2,
   `is_kb_separated` int NOT NULL DEFAULT -2,
```

**Comment by typtop21** [comment]
Upgrade by Marketplace
Today, I do not have access to my Windows server which hosts my GLPI instance
I can't do more tests.

**Comment by JeanBuchweitz** [comment]
I was only able to update by performing a drastic procedure!

1 - Backup of Plugin Forms tables.
2 - I deleted the tables.
3 - I installed version 2.13.2 as if it were the 1st time.
4 - I restored the data from the backup.

**Comment by btry** [comment]
This works only when there is no table changes between your starting and target versions.  In 2.13.3 a change in tables will occur.

The differences in the tables are still not fixed then you will get the same problem on each upgrade.

Now you upgraded the plugin, use the following command to see the diff and:
-ehtier show it here
- either you're skilled enough to decide how to fix each difference

**bin/console glpi:database:check_schema_integrity -p formcreator**

**Comment by PolSerna** [comment]
Hey,  we will have any update fixing this problem? 
Cause i can't fix it no matter what i try.  
Thx <3.

**Comment by btry** [comment]
Hi

If you use CLI to proceed the upgrade of the plugin, when inconsistencies in the tables are detected you will have output similar to what I showed [here ](https://github.com/pluginsGLPI/formcreator/issues/3060#issuecomment-1298226333). You **must** take the appropriate actions to fix these inconsistencies.

If you **really** don't want to fix them then upgrade from CLPI with the followipng command, but be aware that this is **at your own risk** : **bin/console glpi:plugin:install formcreator -f -p skip-db-check**

I gave you instructions to help you to fix the inconsistencies [here](https://github.com/pluginsGLPI/formcreator/issues/3060#issuecomment-1298442507). I can't do much more if you don't run the command and show its output.

**Comment by btry** [comment]
Hi

Having no feedback, I assume that your problem is solved. I close.
