### ISSUE TITLE
Display bug in text areas with GLPI 9.5.10/9.5.11

### ISSUE THREAD

**Issue by nsalguero** [pluginsGLPI/formcreator#3067]
**Describe the bug**
When a text area contains more than 4 lines in a form, the text area adds a grey zone at the bottom and the first lines are not visible:
![image](https://user-images.githubusercontent.com/14334161/200306650-0922e6f0-6c89-4b8f-b6ee-74b33e2a4511.png)

The issue comes from a fix for the previous version of TinyMCE that seems no more needed.  Here is a patch to solve the problem:
```
@@ -911,9 +911,9 @@ var plugin_formcreator = new function()
             questionId = parseInt(questionKey.replace('formcreator_field_', ''));
             if (!isNaN(questionId)) {
                // Workaround issue with tinymce input which may be 0px height
-               $('#form-group-field-' + questionKey + ' iframe')
+               /*$('#form-group-field-' + questionKey + ' iframe')
                   .attr('data-mce-style', 'width: 100%; height: 148px; display: block;')
-                  .attr('style', 'width: 100%; height: 148px; display: block;');
+                  .attr('style', 'width: 100%; height: 148px; display: block;');*/
                if (questionToShow[questionKey]) {
                   $('#plugin_formcreator_form.plugin_formcreator_form [data-itemtype = "PluginFormcreatorQuestion"][data-id="' + questionKey + '"]').removeAttr('hidden', '');
                } else {
```

With that patch, the text area displays normally:
![image](https://user-images.githubusercontent.com/14334161/200307262-8f8028e8-aed1-44f3-aa8a-b6637d7261db.png)

**To Reproduce**
1. Enter several lines in a text area contained in a form (either in preview mode, as a super-admin, or in real mode, as a normal user).
2. See error.

**Expected behavior**
The text area should increase its height and display all the lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/14334161/200306650-0922e6f0-6c89-4b8f-b6ee-74b33e2a4511.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.10 and 9.5.11.

**Desktop/Smartphone (please complete the following information):**
 - OS: all
 - Browser: all a priori (at least Chrome, Firefox, Webkit powered browsers)

**Comment by btry** [comment]
Hi

It makes sense : in GLPI 9.5.10, tinyMCE has been upgraded from 4 to 5, and I remember I had to do similar fix in Formcreator 2.13. 

This fix will break the plugin with older version of GLPI 9.5.x then we need something to disable those lines only with GLPI 9.5.10 or later.

**Comment by nsalguero** [comment]
Many thanks! With PR #3068, the problem is fixed.

**Comment by btry** [comment]
Great ! I merge the fix. Thank you for your feedback.
