### ISSUE TITLE
Get form anwsers using api

### ISSUE THREAD

**Issue by imagerss** [pluginsGLPI/formcreator#3069]
**Describe the bug**
Probably not a bug, but documentation never mention anything about api calls (or at least i didnt see it)

**To Reproduce**
i do simple curl call in php like this:
"https://vm-srv-glpiv2.wpwsa.local/apirest.php/PluginFormcreatorFormAnswer/".$i

**Expected behavior**
i would expect to get all form anwsers is some redable way like json
but instead i get only form name and thats it, screenshot attached

**Screenshots**
![image](https://user-images.githubusercontent.com/114244625/200328471-abc2fc86-26f7-46e7-92c0-8fecdb88a274.png)
![image](https://user-images.githubusercontent.com/114244625/200328627-3aa6e16d-158a-45dd-85db-1c16f96d580f.png)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.3
- formcreator  Version: 2.13.2

**Desktop (please complete the following information):**
 - OS: Centos 8

**Comment by btry** [comment]
Hi

If you want to get the answers given to each question by a requester you must query the itemtype PluginFormcreatorAnswer. 

FormAnswer is a relation between form and answer, with some extra properties.
