### ISSUE TITLE
Add Group option : Need Validation

### ISSUE THREAD

**Issue by gjimenezt** [pluginsGLPI/formcreator#3072]
****Is your feature request related to an Enhancement:**
I have a problem, it turns out that I need to send a request for Approval of the form but to a specific manager of a department (Location), I have a Txt : Manager (Author), where the requester places his manager. This validation must be before the action > Create ticket, if the form is Approved, the ticket is created and a validation request is also sent to a specific group.

**Describe the solution you'd like**
Add an option in the Section: Need validation? (NO - USER - GROUP - USER FROM QUESTION ANSWER

![imagen](https://user-images.githubusercontent.com/115827009/200709872-00893be6-5bc6-4344-8324-128bc3cb4cd4.png)

I explain my need: 1 - Applicant Completes the form and sends it
2- The form is sent to the Applicant's Manager or supervisor for approval.
3 - If the Form is Rejected, it will be filed and notified to the applicant.
4- If the form is Approved, the Ticket will be created and a validation request will be sent to the Validating Department (Administrative).
5 - When the ticket is validated, it is assigned to the responsible department for its solution.

NOTE: In the form I cannot select a Group to approve the form, because the person in charge of the department (Location) is placed in a Text Field within the question form.

![imagen](https://user-images.githubusercontent.com/115827009/200711247-f7466dd1-b4bf-4eda-8004-c2725ac8dfb9.png)

Thank you...

**Comment by btry** [comment]
Hi

Feature un step 2 is under tests. It will be available in a future version of Formcreator, for glpi 10.1 (somewhere in 2023).

Validation request in step 4 is not supported yet. We decided to suspend new features development to focus on reliability of the plugin. Do not expect to see this feature in short term. 

Step 5 is out of control of Formcreator. The ticket may be assigned by Formcreator when it creates the ticket, before the ticket validation step in 4.

**Comment by gjimenezt** [comment]
> Hi
> 
> Feature un step 2 is under tests. It will be available in a future version of Formcreator, for glpi 10.1 (somewhere in 2023).
> 
> Validation request in step 4 is not supported yet. We decided to suspend new features development to focus on reliability of the plugin. Do not expect to see this feature in short term.
> 
> Step 5 is out of control of Formcreator. The ticket may be assigned by Formcreator when it creates the ticket, before the ticket validation step in 4.

> 

Hello **@btry,**
**_Thank you_** for such a prompt response.

`With the feature a step 2 which is under test. which will be available in a future version of Formcreator, for glpi 10.1 (sometime in 2023). With this feature it could be solved.`

The other points can be configured in: Target ticket > Properties > Validation: Specific User or Group

This is how the flow is completed:
Approval > True > Create Ticket : Target ticket > Properties > Validation: Specific User or Group

Hopefully we can be useful for any contribution to the community, greetings to all.

Thank you

**Comment by btry** [comment]
Hi

> The other points can be configured in: Target ticket > Properties > Validation: Specific User or Group

Yes, I was unsure about that (now there are so many features that I don't remember all of them).

So you just have to wait for GLPI 10.1 and the next Formcreator.
