### ISSUE TITLE
 Call to undefined method PluginFormcreatorTranslation::getTypeName()

### ISSUE THREAD

**Issue by L019** [pluginsGLPI/formcreator#3073]
**Describe the bug**
Uncaught Exception Error: Call to undefined method PluginFormcreatorTranslation::getTypeName() in /home/MYWEBSITE/public_html/marketplace/formcreator/inc/form_language.class.php at line 348

**To Reproduce**
Create a form 
add a few questions 
add translation 
fill the files click save throws a error 400 in console 
when i refresh the page this get error

**Expected behavior**
show the translations

**Screenshots**
![image](https://user-images.githubusercontent.com/90776953/200843549-39c36f07-30f0-4248-94c9-01cef4d1a3fc.png)

**Comment by btry** [comment]
Hi

Try the following commit: 137a66047
