### ISSUE TITLE
Letter 'n' added in the description of the ticket after upgrading from 9.5.9 to 9.5.11

### ISSUE THREAD

**Issue by corzakiewicz** [pluginsGLPI/formcreator#3075]
Users create tickets using forms from FormCreator.
Since today when we upgraded GLPI from 9.5.9 to 9.5.11 (for security reason), form results are still correctly sent to create a new ticket but as the ticket is automatically created, characters are automatically added into the description of the ticket, as if the line breaks were automatically displayed

![image](https://user-images.githubusercontent.com/75740722/200889535-849a3103-5656-4a5e-bc44-00a40286fb86.png)

Characters 'rn' should not appear.

**Comment by btry** [comment]
Please read #3071

This is a duplicate

**Comment by corzakiewicz** [comment]
Thank you for your help. I am cheking #3071

**Comment by btry** [comment]
Hi
@corzakiewicz : Is the problem solved ? Can I close ?

**Comment by corzakiewicz** [comment]
Hi,

You can close, yes, the problem has been solved.
Thank you.
