### ISSUE TITLE
Information "Catégorie" saisi dans un formulaire à injecter dans le ticket GLPI

### ISSUE THREAD

**Issue by RdENIM** [pluginsGLPI/formcreator#308]
Bonjour à vous,

Sur un formulaire où nous avons pris un objet de  Type : Intitulé et 
Intitulé  : Assistance - Catégoerie de ticket, est-il possible de d'injecter cet objet directement dans la catégorie du ticket , comme cela est possible pour le titre ou la date du ticket ?

En vous remerciant d'avance de votre réponse possible, 

Cordialement,

René Danilo

**Comment by flegastelois** [comment]
Duplique #15

**Comment by RdENIM** [comment]
Bonjour à vous,

Quand vous dites dans une prochaine version majeure, avez vous une idée de la date de sortie SVP ?

En vous remerciant d'avance de votre réponse possible,

Cordialement,

René Danilo

**Comment by flegastelois** [comment]
Bonjour, 
Cela sera dans la 1.5.0, qui arrivera avant mi-janvier prochain.

**Comment by RdENIM** [comment]
Bonjour à vous,

Merci pour votre réponse,

Pour le ticket "Copier / Coller de Formulaire #307", j'ai posté une question pour savoir quand allait être prévu (si c'était prévu) une date de sortie également ? 

En vous remerciant d'avance  de votre réponse possible,

Cordialement,

René Danilo
