### ISSUE TITLE
Part of text field are invisible after new lines

### ISSUE THREAD

**Issue by luciolebrillante** [pluginsGLPI/formcreator#3083]
**Describe the bug**
When a user write a long message in a form, the new lines are hidden in Firefox (not in Chromium like navigator).

**To Reproduce**
1. go to a form with a text area
2. write text on multiple line
3. See error

**Expected behavior**
The new lines should be visible as the first one.

**Screenshots**
![Screenshot from 2022-11-16 17-14-02](https://user-images.githubusercontent.com/50231120/202234168-adde86ec-3ada-4572-8a9a-f4dcece0ed6e.png)

**GLPI / Plugins (please complete the following information):**
- GLPI 9.5.11 with [this custom fix for textfield ](https://github.com/glpi-project/glpi/pull/13226/commits/6f3d52ec84117a89e7c37d14bef72bf278c41ea1)

List of installed plugins
	news                 Name: Alertes                        Version: 1.9.1      State: Enabled
	datainjection        Name: Data Injection                 Version: 2.10.2     State: Enabled
	escalade             Name: Escalades                      Version: 2.7.2      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Enabled
	tag                  Name: Gestion des tags               Version: 2.8.3      State: Enabled
	groupcategory        Name: GroupCategory                  Version: 1.2.3      State: Enabled
	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.4.2      State: Enabled
	pdf                  Name: Impression pdf                 Version: 2.0.1      State: Enabled
	jsaddons             Name: JS Addons                      Version: 1.0.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.7.4      State: Enabled
	satisfaction         Name: Plus de satisfaction           Version: 1.5.2      State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.8      State: Enabled

**Desktop (please complete the following information):**
 - N/1
 - Firefox V 106.5

**Additional context**

**Comment by btry** [comment]
Hi
Please read https://github.com/pluginsGLPI/formcreator/issues/3071

**Comment by btry** [comment]
Keep the fixes and add this one : https://github.com/pluginsGLPI/formcreator/commit/a325a948a258a0c15ff894db9a03948c9c1d091f

**Comment by luciolebrillante** [comment]
Thank you for your help @btry 

I kept the fix about /r /n and I deploy the fix you talked about but it didn't fix it.
![Screenshot from 2022-11-17 09-25-08](https://user-images.githubusercontent.com/50231120/202394715-cdbd7287-d365-43cc-8e61-26be13fc099b.png)

**Comment by luciolebrillante** [comment]
Any new idea @btry?

This bug is annoying for my organisation :/

**Comment by btry** [comment]
Hi
For now I'm too busy to work on community issues. Sorry.

Don't forget that community support is done at best effort; and unfortunately I have a lot of work this end of year.

**Comment by luciolebrillante** [comment]
Thank you @btry for the release of the version 2.12.6 of formcreator, it just deployed it and it fixed.

**Comment by btry** [comment]
Hi

Then I guess I did not gave you all required patches. I close this issue; thank you for your feedback.
