### ISSUE TITLE
The user does not see own forms in the summary

### ISSUE THREAD

**Issue by WebGregGit** [pluginsGLPI/formcreator#3089]
**Describe the bug**
The user who submitted the form does not see them in the summary:

My 5 last forms (requester)
No form posted yet
My 5 last forms (validator)
No form waiting for validation

**To Reproduce**

1. Fill out the form as a user and send it.
2. Refresh the Forms site.

![image](https://user-images.githubusercontent.com/68922721/202921487-4cccf9d6-21a8-47b1-897a-d82284caf51d.png)

**Expected behavior**

If the statistics of forms sent by the user are displayed, then it would be good if these data were visible :)

**GLPI / Plugins (please complete the following information):**
- 10.0.4

Plugins:
	actualtime           Name: ActualTime                     Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	archisw              Name: Apps structures                Version: 2.2.14     State: Installed / not activated               
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	connections          Name: Connections                    Version: 10.0.0     State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.12.0     State: Installed / not activated               
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.12     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.12     State: Installed / not activated               
		Install Method: Marketplace
	escalade             Name: Escalation                     Version: 2.8.1      State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.2     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.0      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.1      State: Installed / not activated               
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	screenshot           Name: Screenshot                     Version: 2.0.1      State: Not installed                           
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Installed / not activated               
		Install Method: Marketplace
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.1   State: Installed / not activated               
		Install Method: Marketplace
	treeview             Name: Tree view                      Version: 1.10.0     State: Enabled                                 
		Install Method: Marketplace
	typology             Name: Typologies                     Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	webapplications      Name: Web applications               Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Zarządzanie słowami kluczowymi Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace

**Comment by btry** [comment]
Hi

Can you identify the form answer in the database (table **glpi_plugin_formcreator_formanswers**) and check the column **requester_id** ? Which value do you find ? If it is greater than 0, it must match a user id in the table **glpi_users**

**Comment by WebGregGit** [comment]
Hi @btry 

It is OK

![image](https://user-images.githubusercontent.com/68922721/204083190-5a80830a-2409-41df-90a8-c47cc9df1420.png)

![image](https://user-images.githubusercontent.com/68922721/204083451-c2cffc4a-6554-4bc3-8d93-6491ce87bcaa.png)

![image](https://user-images.githubusercontent.com/68922721/204083493-68405292-30c0-464b-9e6a-4f9be9ac03c9.png)

**Comment by btry** [comment]
Hi

In which entity is 'located the requester user when he tries to see his last forms ?

**Comment by WebGregGit** [comment]
I only use one - root

**Comment by btry** [comment]
Hi

I did a test with branch support/2.13.0. This version is 2.13.3 + all bugfixes waiting for release. Could you upgrade to 2.13.3 ans see if the problem persists ?

**Comment by btry** [comment]
Hi 

I think I found the problem. Can you answer or confirm the following questions?

- the user has no right to modify the general configuration of GLPI
- the user has one or more validation rights (validate incident or validate requests); see his profile
- the user is not a validator of the form answer (if validation is enabled in the form of this form answer)

**Comment by btry** [comment]
You may try the above fix. I'm waiting for your feedback.

**Comment by btry** [comment]
Hi

Did you test the patch; does it work for you ?

**Comment by btry** [comment]
Hi

Having no feedback, I assume the patch worked for you. I close.
