### ISSUE TITLE
LDAP Search broken in 2.12.6

### ISSUE THREAD

**Issue by OsamaDengler** [pluginsGLPI/formcreator#3094]
**Describe the bug**
After upgrade to 2.12.6 LDAP Searches don't work anymore.

Error logged:
[2022-11-24 13:11:36] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "PluginFormcreatorLdapDropdown" not found in /var/www/html/glpi/marketplace/formcreator/inc/field/ldapselectfield.class.php at line 151
  Backtrace :
  ...ace/formcreator/inc/abstractfield.class.php:102 GlpiPlugin\Formcreator\Field\LdapselectField->getRenderedHtml()
  marketplace/formcreator/inc/question.class.php:310 PluginFormcreatorAbstractField->show()
  marketplace/formcreator/inc/form.class.php:1338    PluginFormcreatorQuestion->getRenderedHtml()
  marketplace/formcreator/inc/form.class.php:773     PluginFormcreatorForm->displayUserForm()
  inc/commonglpi.class.php:637                       PluginFormcreatorForm::displayTabContentForItem()
  ajax/common.tabs.php:106                           CommonGLPI::displayStandardTab()

**To Reproduce**
1. Go to any form with a LDAP search
2. Field is not rendered
3. See error

**Expected behavior**
Dropdown with LDAP search result should be displayed

**GLPI / Plugins (please complete the following information):**
- GLPI v9.5.9
- Formcreator 2.12.6

**Additional context**
Looking at the code it appears that the class PluginFormcreatorLdapDropdown is missing in 2.12.6 while it's there in 2.13.3
Could it be a mixture between the GLPI v9 and the GLPI v10 branches?

**Comment by btry** [comment]
Hi

Yes, there is a problem : this is a new file and it was not added to the repository. I'm sorry for the inconvenience. Let me send the file here to solve your problem. I'll release a 2.12.7 soon version to fix that.

There are 2 files missing

Pick them, replace the txt extension with php and put them in formcreator. Let me know if the LDAP question works after that. The titles tell you their folder and name, relative to formcreator/ directory.

### inc/ldapdropdown.class.php
[ldapdropdown.class.txt](https://github.com/pluginsGLPI/formcreator/files/10084932/ldapdropdown.class.txt)

### ajax/getldapvalues.php
[getldapvalues.txt](https://github.com/pluginsGLPI/formcreator/files/10084943/getldapvalues.txt)

**Comment by btry** [comment]
i'm building a version 2.12.7. I'm waiting for your fedback before publishing it (to ensure I don't forget an other file for ldap dropdowns).

**Comment by OsamaDengler** [comment]
I can confirm that adding these two files fixed the problem and the LDAP queries are working.
Thanks a lot for the quick fix!

**Comment by btry** [comment]
Great !

I'll publish the release 2.12.7 with the files tomorrow morning.
