### ISSUE TITLE
Form crashes when clicking submit only if attached file, but ticket opens

### ISSUE THREAD

**Issue by To0tic** [pluginsGLPI/formcreator#3095]
Hello,

**Describe the bug**
Form crashes when clicking submit only if an attached file, but ticket opens. There is no redirection to the open ticket after error validating.
The error is : "Une erreur interne est survenue. Veuillez en informer l'adminstrateur"

The ticket is correctly opened with the attachment correctly associated

**Expected behavior**
There is no error in the sibling sql-errors.log file
The is an error in glpi/files/_log/php-errors.log file
"
[2022-11-25 14:39:34] glpiphplog.WARNING:   *** PHP User Warning (512): Document ID is mandatory in C:\xampp\htdocs\glpi\src\Document_Item.php at line 106
  Backtrace :
  src\Document_Item.php:106                          trigger_error()
  src\CommonDBTM.php:1279                            Document_Item->prepareInputForAdd()
  src\CommonITILObject.php:2591                      CommonDBTM->add()
  src\Ticket.php:2129                                CommonITILObject->post_addItem()
  src\CommonDBTM.php:1325                            Ticket->post_addItem()
  plugins\formcreator\inc\targetticket.class.php:907 CommonDBTM->add()
  plugins\formcreator\inc\formanswer.class.php:941   PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\formanswer.class.php:1171  PluginFormcreatorFormAnswer->generateTarget()
  src\CommonDBTM.php:1325                            PluginFormcreatorFormAnswer->post_addItem()
  plugins\formcreator\ajax\formanswer.php:58         CommonDBTM->add()
"
**Screenshots**
![image](https://user-images.githubusercontent.com/116352927/203998991-e44dcefc-db0b-47f1-a895-ae375085bf12.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.5
- Formcreator 2.13.3

We had the no action problem when we submit button in 2.13.1. Behind, this symptom appeared with the 2.13.2

Thank you for your help

**Comment by btry** [comment]
Hi

Apply this patch to workaround the error message. https://github.com/pluginsGLPI/formcreator/commit/e9e8da484ffd71920803ca220f4f899de12edbc0

I'll search later how to address the error found in the backtrace.

**Comment by To0tic** [comment]
Thank you. The workaround don't work.

**Comment by btry** [comment]
The document is lined to the form answer and to the ticket if needed. This is normal.

**Comment by btry** [comment]
Id ther workaround does not solved the error message, please open developer tools of the browser and reproduce. In the network tab find the HTTP request to formcreator/front.formanswer.form.php . Show the HTTP response code and the HTP response body.

**Comment by To0tic** [comment]
![image](https://user-images.githubusercontent.com/116352927/204030720-16c99498-fb4d-4a65-b5e0-319c52a72ffb.png)

![image](https://user-images.githubusercontent.com/116352927/204030754-c5fb80a3-46b7-4967-8449-0142867998cf.png)

**Comment by btry** [comment]
The trp response body should be a valid JSON string, but it is currputed by the php error you reported. The patch should address this corruption problem.

Can you confirm that your user has debug mode enabled ?

**Comment by To0tic** [comment]
Nop. I am sorry. I had not active the debug mode. Test in debug mode now : return headers http 200 OK and no content in the response.
It's seems to fix the problem

**Comment by btry** [comment]
The response must contain something, or the user will not be redirected after form submission. The response contains the URL of the page to load, depending on a server side logic.

**Comment by btry** [comment]
Hi

Please try the fix https://github.com/pluginsGLPI/formcreator/pull/3097:
-apply the fix
-upgrade the plugin from CLI with the command bin/console plugin:install formcreator -f -p force-upgrade -p skip-db-check

**Comment by To0tic** [comment]
Hello,
Unfortunately, the patch #3097 does not change the problem.

If it can help you, if I put in comment :
Document_Item.php
line 104:
/*
        if (empty($input['documents_id'])) {
            trigger_error('Document ID is mandatory', E_USER_WARNING);
            return false;
        }
*/

The form reacts normally after the submit action, the file is well dropped in the right place and 1 time in the forms response but 2 same links appear in the ticket. 
![image](https://user-images.githubusercontent.com/116352927/206388258-0ebbeb94-e19f-4494-be07-27c1aa8c7de3.png)

Hoping that it helps
Loic

**Comment by btry** [comment]
Hi I did an update to the patch . Full instructions to apply it again are in this [comment](https://github.com/pluginsGLPI/formcreator/issues/3076#issuecomment-1353528549).

Please try it and feedback. I'm waiting to solve this problem to release 2.13.4.

**Comment by btry** [comment]
Hi

The GLPI team submitted an other solution which works fine with less code. You should revert the patch and apply this one on GLPI: https://github.com/glpi-project/glpi/pull/13641

**Comment by btry** [comment]
Hi

The fix in glpi has been tested enough to be validated. The fix for Formcreator will not be included in the next release. I close this issue.
