### ISSUE TITLE
[formcreator 2.13.3] Missing tabs "forms" in profiles

### ISSUE THREAD

**Issue by athevenot** [pluginsGLPI/formcreator#3096]
**Describe the bug**
The menu to give access to formcreator to other profil is missing.
All delegations are lost since upgrade.

**To Reproduce**
1. Go to Administration -> Profile -> Any profile with Standard Interface
2. Scroll down to 'Forms' tabs
3. Wait.. You can't

**Screenshots**
![image](https://user-images.githubusercontent.com/46626767/204018421-f84b1e46-3742-478b-8f39-dc6d07e526a5.png)

**GLPI / Plugins (please complete the following information):**
- GLPI Cloud version 10.0.5
- formcreator 2.13.3

**Comment by btry** [comment]
Hi

I guess you're searching the settings to configure the entities. Go to Administration > Entities instead.

For now the plugin does not adds any tab in profiles (this will happen in 2.14.0)

**Comment by athevenot** [comment]
Hello, 

Incorrect, i'm looking for this panel to give access to the plugin for certain profiles : 
![image](https://user-images.githubusercontent.com/46626767/204024880-d03f232d-b22a-483e-b25c-f9b9a09526d9.png)

This is what I've had in GLPI 9.5.10 with formcreator 2.12.5

How am I supposed to delegate forms creation/modification ?

**Comment by btry** [comment]
I reopen an instance of GLPI 9.5 with Formcreator 2.12.5. There is no added tab in profiles with this version

![image](https://user-images.githubusercontent.com/14139801/204026324-56b015fd-467b-4a1c-84a4-ad0a6c30596b.png)

Formcreator 2.14 is on its way and contains a right to provide finer administration rights. Earlier versions do not contain specific rights. Are you sure that you did not used a version modified with a backport of that feature ?

HEre is the line which ads a tab to profiles in Formcreator 2.14: https://github.com/pluginsGLPI/formcreator/blob/support/2.14.0/setup.php#L412

and here, in Formcreator 2.12.5 the same place where the line is absent

https://github.com/pluginsGLPI/formcreator/blob/v2.12.5/setup.php#L324

**Comment by athevenot** [comment]
Ooooh, you may be right !
Sorry about that. I thought I asked TECLIB to share it with community, we've paid for custom dev that should be great to everyone.

I'd like to apologizes about the issue opening.

Have a great evening.

Best regards

**Comment by btry** [comment]
> How am I supposed to delegate forms creation/modification ?


Profiles with the right to modify entities are allowed to administrate forms. This is true until 2.13 version.

**Comment by btry** [comment]
> I thought I asked TECLIB to share it with community

Then I guess you ordered a backport but when you were using GLPI 9.5. You should get in touch to know how to port the feature in version 2.13.3. Please, get in touch with Teclib' about that.

**Comment by athevenot** [comment]
You are right ! 
Great, thanks, it is solving my issue.
