### ISSUE TITLE
Translation issue with Turing (EN)

### ISSUE THREAD

**Issue by Giudy** [pluginsGLPI/formcreator#3098]
The official sentence for when the captcha is typed wrongly is :"you failed the turing test". Even if I do like to "nerd" approach, we should admit that is not clear to normal users.
possible alternatives

- You entered an incorrect CAPTCHA
- You've entered the wrong control characters
- Your reply to the question "are you a Robot?" is wrong, maybe you have missed some character

**Comment by btry** [comment]
Hi

I will fix it in 2.14.0.

**Comment by btry** [comment]
fixed with: 03bc9e399
