### ISSUE TITLE
Actors Traget - Suppliers

### ISSUE THREAD

**Issue by udi8** [pluginsGLPI/formcreator#3100]
hi,
i'm using GLPI 10.0.0-rc3 with FormCreator 2.13.0-beta.2

i'm creating a form that will pick from a supplier list and assign it to the supplier,
for some reason it is not working.
i did implement the "fix(target_actor): import requires specific input format"
but it has not resolved the supplier assignment issue in the ticket.

**Comment by btry** [comment]
Hi

Today the latest release of GLPI is 10.0.5, and the latest release of Formcreator is 2.13.3.

Please upgrade, and if the problem persists, open a new issue.
