### ISSUE TITLE
Alert on installing it 

### ISSUE THREAD

**Issue by killmasta93** [pluginsGLPI/formcreator#3106]
**Describe the bug**
HI currently after installing on the dashboard i get 
```

1 tables use the deprecated MyISAM storage engine. Run the "php bin/console glpi:migration:myisam_to_innodb" command to migrate them.
    6 columns use the deprecated datetime field type. Run the "php bin/console glpi:migration:timestamps" command to migrate them.
    1 tables use the deprecated utf8mb3 storage charset. Run the "php bin/console glpi:migration:utf8mb4" command to migrate them.
    2 columns of primary or foreign keys use signed integers. Run the "php bin/console glpi:migration:unsigned_keys" command to migrate them.
```

**GLPI / Plugins (please complete the following information):**
- GLPI version GLPI 10.0.2
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
![image](https://user-images.githubusercontent.com/13953629/205800856-0e06b192-e77d-40b0-b0c6-9f2d28642361.png)

**Comment by btry** [comment]
Hi

Just run the commands mentionner in the error message.
