### ISSUE TITLE
Missing code in 2.12.7

### ISSUE THREAD

**Issue by OsamaDengler** [pluginsGLPI/formcreator#3109]
**Describe the bug**
I've run into another missing code problem, compareabla to issue #3094
This time a reference to PluginFormcreatorFormAccessType cannot be resolved:

[2022-12-08 14:02:13] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "PluginFormcreatorFormAccessType" not found in /var/www/html/glpi/marketplace/formcreator/inc/form.class.php at line 2841

It appears that the file containing the class "PluginFormcreatorFormAccessType" is missing in the GLPI 9.5 compatibility branch.

**To Reproduce**
1. Create form with LDAP select question
2. Open the form and click on the question to open the dropdown

**Expected behavior**
Dropdown populated with LDAP search result

**GLPI / Plugins (please complete the following information):**
- 9.5.9
- Formcreator 2.12.7

**Comment by btry** [comment]
Hi @OsamaDengler 

Did you tri the above fix ? Do you have a feedback ?

**Comment by btry** [comment]
Hi

Having no feedback, I close this issue. The patch has been validated by an other bug reporter.
