### ISSUE TITLE
[2.12.6] [2.12.7] No results found for ID number search

### ISSUE THREAD

**Issue by luisjosemachado** [pluginsGLPI/formcreator#3126]
**Describe the bug**
For 2.12.6 and 2.12.7, when I use a ticket type field (GLPI object), no result is found for the search by ID number.

**Screenshots**

v. 2.12.5
![image](https://user-images.githubusercontent.com/30940056/208259565-e976291d-75b9-46cd-b6c3-b3595bafbe75.png)

v. 2.12.6 or 1.12.7
![image](https://user-images.githubusercontent.com/30940056/208259277-88dc9eb7-bd1b-403e-9ce3-6bf275e81546.png)

.

**Comment by btry** [comment]
HI

There is a setting in GLPI or the user preferences to show or hide the ID of items in a drop-down. Check the state of the setting. If it is disabled, try to enable it and see if it helps. 

I remember I fixed the plugin quite recently to obey this setting, but I don't remember exactly when and if it affects the ability to search by Id. Investigation In code or tests are needed to get the answers.

**Comment by luisjosemachado** [comment]
It worked. Thanks.

**Comment by btry** [comment]
Great, then I close this issue.

Thank you for your feedback.
