### ISSUE TITLE
Scroll on question create or update

### ISSUE THREAD

**Issue by SilvaFernando** [pluginsGLPI/formcreator#3127]
**Describe the bug**
When I try create one question or update, scroll not working

**To Reproduce**
1. Go one form and chose question
2. Click on question
4. Try scroll
5. 
![image](https://user-images.githubusercontent.com/53239752/208699626-7c925f14-1328-4cff-b4e9-8dd2bd672b21.png)

My Forms version is 2.13.3

**Comment by btry** [comment]
Please tell the version of glpi. If you're not using the latest release, upgrade first.

I'm on vacancy, then expect at least 2 weeks of delay before I can investigate on this.

**Comment by SilvaFernando** [comment]
Hi @btry.

Can you investagate this?

BR.
Fernando Dias da Silva

**Comment by btry** [comment]
Hi
[glpi_formcreator_2.13.4-dev.zip](https://github.com/pluginsGLPI/formcreator/files/10426029/glpi_formcreator_2.13.4-dev.zip)

I don't reproduce with the latest revision of the plugin. Do you have a testing GLPI instance to try it ? In attachment : a build of the 2.13.4-dev.
[glpi_formcreator_2.13.4-dev.zip](https://github.com/pluginsGLPI/formcreator/files/10426077/glpi_formcreator_2.13.4-dev.zip)


:warning: Do **not** use it in production.

**Comment by SilvaFernando** [comment]
@btry.

I test this version on my test environment, and i have same issue, maybe, incompatibility with PHP 8.1?

Keep calm i do not use in production rsrs.

**Comment by btry** [comment]
Ok,

When I tried to reproduce I grew a textarea and reduced the browser's window to force a too big modal. The vertical scroll bar appeared on the border of the window, not the border of the modal. 

Just in case, do you reproduce with an other browser, or in private browsing mode ? You may also disable all your browser extensions to see if one of them breaks something ?

On my side I'll try with the version 2.13.3.

Pho 8.1 os compatible with Formcreator 2.13. by the way this is the version I ran for my test.

**Comment by btry** [comment]
I rechecked your screenshot, the scrollbar is in the  border of the modal. Try scrolling with the mouse wheel. Does it work ?

**Comment by SilvaFernando** [comment]
Hi @btry.
Using mouse wheel doesn't work, using keyboard keys worked.

I tried adjust this scrollbar using CSS, but i don't have success, do you have some idea?

**Comment by SilvaFernando** [comment]
Hi @btry.
I tested the formcreator in our environment and it was identified that the height of the modal in our environment is automatic and in the other environment the height was not defined, follow code:
#modal_ruiv1l > div > div{
 height: auto;
  }

**Comment by btry** [comment]
Hi

IF you have different behaviors between 2 environments, can you find and tell how they differ ?
