### ISSUE TITLE
public forms not working - plugin ActualTime 2.0.0 conflict

### ISSUE THREAD

**Issue by igormarcos** [pluginsGLPI/formcreator#3129]
**Describe the bug**

After updating from GLPI 9.5 to 10.0.5 and executing all the adjustments in the database, we reinstalled the plugins and among them the formcreator, after enabling the plugin we noticed that being logged in the GLPI the form works correctly, however for audiences that do not need to be logged in, the same return error: HTTP/1.1 403 Forbidden at address: marketplace/formcreator/ajax/showfields.php

**To Reproduce**
1. Access link of public form

**Expected behavior**
The drop menu does not work correctly, where according to the option chosen for the form it would open different fields.

**Screenshots**

![Captura de tela de 2022-12-26 14-54-20](https://user-images.githubusercontent.com/4334141/209573814-57d80b29-d538-46c9-99f8-496ee1e91bcd.png)

![Captura de tela de 2022-12-26 14-55-07](https://user-images.githubusercontent.com/4334141/209573827-385ede2c-bdd9-4b94-8a1c-ed696080f2c5.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version = 10.0.5
- formcreator plugin version = 2.13.3

**Desktop (please complete the following information):**
 - OS: Debian Linux 11
 - Browser : Firefox 102.6.0esr (64-bits)

**Additional context**
Before doing the update, the formcreator was in version 2.10 of the plugin and it worked correctly.

**Comment by btry** [comment]
Hi

Can you try the latest revision of the branch support/2.13.0, see if the problem persists and feedback.

**Comment by igormarcos** [comment]
> Hi
> 
> Can you try the latest revision of the branch support/2.13.0, see if the problem persists and feedback.

Not work, i downgrade from formcreator 2.13.3 to 2.13.0, errors in console not appear, but form not working well:

![Captura de tela de 2022-12-27 08-57-52](https://user-images.githubusercontent.com/4334141/209663438-86046bde-c040-4778-8450-830b88e132d4.png)

This access form with no login session:
![Captura de tela de 2022-12-27 08-49-42](https://user-images.githubusercontent.com/4334141/209662791-365a73a7-2a90-4e6d-b685-e4a0175c0f99.png)

This access form with login session:
![Captura de tela de 2022-12-27 08-50-28](https://user-images.githubusercontent.com/4334141/209662829-d46e0649-f2ed-4a81-abf4-53c7462ddd7f.png)

**Comment by btry** [comment]
Hi

I guess you did not understood well my request. I expected you to try the latest revision of the plugin (aka 2.13.3 + all bugfixes not yet released), but you tested the release 2.13.0.

I will provide to you an archive of the plugin for this test.

**Comment by igormarcos** [comment]
> Hi
> 
> I guess you did not understood well my request. I expected you to try the latest revision of the plugin (aka 2.13.3 + all bugfixes not yet released), but you tested the release 2.13.0.
> 
> I will provide to you an archive of the plugin for this test.

Ok, I understand now, I downloaded the support branch 2.13.0 and installed it with yarn in the repo plugin in GLPI, and the behavior was not as expected.

Print of plugin installed:
![Captura de tela de 2022-12-28 09-30-26](https://user-images.githubusercontent.com/4334141/209813098-b4bead5c-d8f4-4b96-8e74-91ae1e350512.png)

Print of console exception on access public form with out login:
![Captura de tela de 2022-12-28 09-31-40](https://user-images.githubusercontent.com/4334141/209813114-e172b16b-193d-4094-97f2-75c9b0f65976.png)

**Comment by btry** [comment]
Hi

You're probably using glpi 10.0.4 or 10.0.5. A fix is under tests to fix upload issues on public forms. Here is it's URL; apply this patch on glpi 

https://github.com/glpi-project/glpi/pull/13641

**Comment by igormarcos** [comment]
> Hi
> 
> You're probably using glpi 10.0.4 or 10.0.5. A fix is under tests to fix upload issues on public forms. Here is it's URL; apply this patch on glpi
> 
> [glpi-project/glpi#13641](https://github.com/glpi-project/glpi/pull/13641)

I applied the patch, the problem remains, but as the fix is still in testing I'll follow up on the fix, thanks a lot. I'll update here if I find anything.

**Comment by btry** [comment]
Please inspect a http request to showfields.php

Show the post data. I believe that it is incorrect ant do 't pass early sanity check in ajax/showfields.php .

**Comment by igormarcos** [comment]
Ok, I applied SSL on the website, but the behavior is the same:

I reinstalled the formcreator through the marketplace, the result was the same.

![Captura de tela 2023-01-04 202740](https://user-images.githubusercontent.com/4334141/210669116-67013c1e-3ed4-4ec9-87f4-d5502a68639b.png)

**Comment by btry** [comment]
Hi

Open developer tools of the browser and inspect the details of a request to showfields.php.

I want to check which data is sent to the server.

**Comment by igormarcos** [comment]
These are the request and response headers for the anonymous use form:

![Captura de tela de 2023-01-05 14-01-22](https://user-images.githubusercontent.com/4334141/210839931-60f18a8b-fb63-48f1-a1f7-1e0b12637d66.png)

![Captura de tela de 2023-01-05 13-51-12](https://user-images.githubusercontent.com/4334141/210839954-e900c968-a3cf-4178-9538-98cf31ac0424.png)

**Comment by btry** [comment]
Hi

I need to see the content of the tab "Request".  This is the request body and it contains the data sent to compute the visibility. Here is an example with Brave browser (tab Payload).

![image](https://user-images.githubusercontent.com/14139801/211015557-3751d8a3-001b-4102-aad6-ce9e7473ca1e.png)

**Comment by igormarcos** [comment]
![Captura de tela de 2023-01-06 13-37-31](https://user-images.githubusercontent.com/4334141/211056476-02039583-891f-4fe6-b882-624bec0f456e.png)


> Hi
> 
> I need to see the content of the tab "Request". This is the request body and it contains the data sent to compute the visibility. Here is an example with Brave browser (tab Payload).
> 
> ![image](https://user-images.githubusercontent.com/14139801/211015557-3751d8a3-001b-4102-aad6-ce9e7473ca1e.png)

**Comment by vinibr81** [comment]
We have the same behavior here.

I has the glpi 10.0.5 with my data and install fresh plugin (delete old files and tables).

The install works well, not problem of schema here.

But the error "The Action you have request is not allowed" happen here too.

We check the php-errors logs and bellow i found this

[2023-01-07 15:16:49] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiname" in /var/www/html/glpi-prod/src/Search.php at line 899
  Backtrace :
  src/Search.php:446                                 Search::constructSQL()
  src/Search.php:199                                 Search::getDatas()
  src/Search.php:176                                 Search::showList()
  marketplace/formcreator/front/formanswer.php:54    Search::show()

Important thing: The form works if the user are login on the glpi.

**Comment by vinibr81** [comment]
OK, after some tests we directory the plugin call ActualTime, its installed on my glpi, conflicts with Form Creator.

I don´t know at this moment what happen, but i suggest if they have a problem disable another plugins.

**Comment by btry** [comment]
This is interesting. But the backtrack you found does not mentions a function from actualtime. This makes harder to find how the plugin interacts with Formcreator. 

At least I'm pretty sure now your issue is not ide tical to this ticket. Please open a new one with a sump of your finding. I need to investigate to find what happens. I cannot say which plugin has a bug so far.

**Comment by igormarcos** [comment]
> This is interesting. But the backtrack you found does not mentions a function from actualtime. This makes harder to find how the plugin interacts with Formcreator.
> 
> At least I'm pretty sure now your issue is not ide tical to this ticket. Please open a new one with a sump of your finding. I need to investigate to find what happens. I cannot say which plugin has a bug so far.

I also have ActualTime plugin installed, after disabling the problem was solved. There is no more fault present.

![Captura de tela 2023-01-07 215013](https://user-images.githubusercontent.com/4334141/211175714-46de6115-e781-44da-aeef-e2692b258ef6.png)

Now try to find out what the reason for the conflict is.

**Comment by btry** [comment]
Hi

@vinibr81, acordying to the feedback of @igormarcos, now I'm sure you both have the same issue. I close the other ticket you opened; we will continue here. 

I tried to reproduce, by enabling ActualTime, but this is not sufficient. I probably need to setup something in this plugin.

**Comment by btry** [comment]
Can you check if your forms have a question of type Dropdown or GLPI Object ? This should not happen because you use a public form, but I want to be sure of that.

**Comment by vinibr81** [comment]
> Hi
> 
> @vinibr81, acordying to the feedback of @igormarcos, now I'm sure you both have the same issue. I close the other ticket you opened; we will continue here.
> 
> I tried to reproduce, by enabling ActualTime, but this is not sufficient. I probably need to setup something in this plugin.

Yes, i try to detect if the extensions using the same resources. The problem at this moment is the debug mode works only on glpi, its not possible to enable on public access. at least I don't know how

The ActualTime is not important for me, and i deleted extensions, for me, this case is solved, my goal is detected why happen.

Thanks for all

**Comment by btry** [comment]
You can enable debug mode by using a super admin account then impersonate a self service account.

I failed to reproduce so far; I think I need to have data in ActualTime, but I don't know yet how to create a timer.

By the way, which version of a ActualTime are you using ?

**Comment by vinibr81** [comment]
> You can enable debug mode by using a super admin account then impersonate a self service account.
> 
> Edit: but no way to enable it without being authenticated.
> 
> I failed to reproduce so far; I think I need to have data in ActualTime, but I don't know yet how to create a timer.
> 
> By the way, which version of a ActualTime are you using ?

The version is 2.0.0

**Comment by btry** [comment]
Hi

I successfully reproduced the bug with ActualTime 2.0.0. It looks like the develop branch of that plugin contains changes solving the issue. Then I expect the next release will no longer break Formcreator. Feel free to test the develop version to prepare an upgrade.

I think the issue may  be closed now.

**Comment by btry** [comment]
Hi

A bugfix is available in the plugin ActualTime, then this problem is solved.
