### ISSUE TITLE
Cyrillic Regexp Error

### ISSUE THREAD

**Issue by kofe88** [pluginsGLPI/formcreator#3131]
**Describe the bug**
RegExp not working with Cyrillic symbols
![image](https://user-images.githubusercontent.com/16879167/209923532-01542565-fdbc-4243-b40b-1852e3ce8f4a.png)
![image](https://user-images.githubusercontent.com/16879167/209923577-7d7ff51b-e4b7-4d14-a29c-c966ed9c8385.png)
![image](https://user-images.githubusercontent.com/16879167/209923639-a2391625-93cf-428d-ade9-a4ed395efe00.png)
![image](https://user-images.githubusercontent.com/16879167/209923691-767fa6e7-abf6-4239-abc8-e04ef02387ca.png)
Regexp is ok
![image](https://user-images.githubusercontent.com/16879167/209923782-a0f2fefe-59e7-4b92-8765-3bd02c64a541.png)

GLPI 10.0.5
Fromcreator 2.13.3

**Comment by btry** [comment]
Hi

Can you write here the regex and the test string ? I need them to reproduce locally.

**Comment by kofe88** [comment]
@btry , Hi!

regex
/^([А-Я]{1}[а-яё]{1,23}|[A-Z]{1}[a-z]{1,23})$/
test string
Иванов

https://regex101.com/r/Rs0VmP/1

**Comment by btry** [comment]
Thank you.

I'm on vacancy, I think I'll investigate next week.

**Comment by kofe88** [comment]
> Thank you.
> 
> I'm on vacancy, I think I'll investigate next week.

Ok, thank you, good holidays!

**Comment by btry** [comment]
Hi

Try this regex pattern : /(*UTF8)^([А-Я]{1}[а-яё]{1,23}|[A-Z]{1}[a-z]{1,23})$/

I'm waiting for your feedback.

**Comment by btry** [comment]
Hi

Your solution with the **u** modifier is similar to my proposal.

I don't know yet if there is a bug or not. I need to analyse the encoding of the source code of the plugin, the encoding of the webpage, and maybe the encoding of the texts in the database. A mismatch somewhere may be the root cause.

**Comment by kofe88** [comment]
@btry 

If I can help in any way, then I will be happy.
My phpmyadmin writes everywhere that the encoding is ```utf8mb4_unicode_ci```
![image](https://user-images.githubusercontent.com/16879167/211111196-45c7db21-479c-4c3b-a62f-92e900abad1e.png)
The browser also seems to write ```utf-8``` encoding of the page
![image](https://user-images.githubusercontent.com/16879167/211111388-9c9ea59f-af6f-4a9f-96fa-ada37738c4f4.png)
The regular expression in the database also looks correct.
![image](https://user-images.githubusercontent.com/16879167/211111649-5caafded-1bb7-45d2-9128-e87568de667e.png)
If there is anything else I can help, write.

**Comment by kofe88** [comment]
@btry Greetings.
I think this is quite suitable for the solution.

**Comment by btry** [comment]
Hi

Thank you fo your feedback.
