### ISSUE TITLE
Formcreator 2.13.3 - Questions - Type Dropdown - ITIL Categories

### ISSUE THREAD

**Issue by willysaurio** [pluginsGLPI/formcreator#3134]
When you use a dropdown question in a form and then select a sub-tree, from the category tree, the form shows the chosen subcategories but also shows other subcategories of the tree.
It should display only the subcategories corresponding to the chosen sub tree but it shows, additionally, other categories that are from another branch.
(En Español: Cuando usas una pregunta de tipo dropdown en un formulario y luego seleccionas un sub arbol, del arbol de categorías, el formulario muestra la subcategorias elegidas pero tambien muestra otras subcatregorias del arbol.
Debería desplegar unicamente las subcategorías correspondientes al sub arbol elegido pero muestra, adicionalmente, otras categorías  que son de otra rama.)
Question definition:
![image](https://user-images.githubusercontent.com/65296683/210228481-f9dea756-6f2b-4e25-90ab-b7cdcf849a13.png)

Preview question in form:
![image](https://user-images.githubusercontent.com/65296683/210228632-35528e29-a4fc-4cbe-be7c-1441813e1b72.png)

-GLPI / Plugins: Formcreator 2.13.3
-GLPI version 10.0.5

**Comment by btry** [comment]
Hi

I did a try with this setup

![image](https://user-images.githubusercontent.com/14139801/211031448-5c0cbb50-dc6d-44a4-b8bb-eeecb91b43bf.png)

![image](https://user-images.githubusercontent.com/14139801/211031582-916232dd-be50-48af-98a8-e4bc8f431659.png)

Here is the result : it seems ok (no scroll bar higihg items, they are all on screen)
![image](https://user-images.githubusercontent.com/14139801/211031677-66b3dcc6-5e50-447d-be1e-d76d7e464f16.png)

Then I tried the same test deeper in the tree
![image](https://user-images.githubusercontent.com/14139801/211031954-1e9ad363-d464-464a-ada9-69dbc19b2b00.png)

Here is the result: still ok  (no scroll bar higihg items, they are all on screen)
![image](https://user-images.githubusercontent.com/14139801/211032032-9fd0dfbb-46e0-4e31-93f0-3cf9d2714e26.png)

**Comment by btry** [comment]
Try to inspect thhe impacted dropdown with developer tools of the browser.  You will find a javascript block which contains a hash representing a condition
![image](https://user-images.githubusercontent.com/14139801/211034013-91ca101b-129a-4fa7-a7dd-1843c02aa34c.png)

Then open debug panel of GLPI, and inspect the session data. Find the key **glpicondition** and develop its content (clocn on the symbol **=>**
![image](https://user-images.githubusercontent.com/14139801/211034457-e2794127-6eec-441a-9cee-605ba686420c.png)

Finally find (with Ctrl+F) the condition hash in the session. You should find something like this:

![image](https://user-images.githubusercontent.com/14139801/211034889-9089e167-405c-4498-8f52-1bb8d0e6f060.png)

The  hask is a key which represents an array of ID of items allowed to show. Try to identify an ID which matches an item that should not show, and the ID ot an other item which should show.

**Comment by willysaurio** [comment]
Nice day.
I don't know if the situation is the same as what I've reported. 
My problem is with ITIL categories (and subcategories) and your answer is with locations (and sublocations).

**Comment by btry** [comment]
Hi

Actually the plugin uses the same code for all dropdowns, and very few changes when using a GLPI object. Except having  the proof of the contrary, testing any dropdown with tree hierarchy should behave the same. Don't worry about the difference of type.

**Comment by willysaurio** [comment]
Hi
I ran a test using locations and, just like in your test, it works correctly.
In my case the problem occurs with ITIL categories. In the structure of the ITIL category table something must be different in behavior with respect to the location table.
I can't play your directions in debug mode (with F12 in Chrome).

**Comment by willysaurio** [comment]
I have tried other subcategories and in some it works well.
Do you have a way to check the integrity of the table glpi_itilcategories look for problems with itilcategories_id, ancestors_cache and sons_cache?

**Comment by btry** [comment]
Hi

I don't know any tool to check the validity of the ancestors and sons cache. If you delete the content of those columns GLPI will recompute them on the fly. I would recommend to try to reproduce on a testing instance of GLPI, with a copy of your impacted database. This way you can safely experiment the deletion of the cache.

Can you tell why you could not play my instruction ? You cannot access the debug mode of GLPI or the developer tools of the browser ?

**Comment by btry** [comment]
I did a similar test with ITIL categories, and it seems to work as expected on my instance.

**Comment by willysaurio** [comment]
All done in a test environment.
-I cleaned all the columns of ancestors_cache and sons_cache and the same thing happens.
-Change the categories you didn't want to see and they appear anyway
I suppose the problem may be given by related tickets where one ticket has one category and another has another of the group that I do not want to see. 
Either way I think it could be a particular problem in my database and not general of all LPGG Users.  I'm going to close this issue. 
Anyway thank you very much.
