### ISSUE TITLE
URL isn't rewrited

### ISSUE THREAD

**Issue by tech62** [pluginsGLPI/formcreator#3142]
**Describe the bug**
When using a reverse proxy, url isn't fully rewrited

**To Reproduce**
1. Go to the GLPI on the gateway portal
2. Click GLPI App
3. See error

**Expected behavior**
This url is provided https://mydomain.reverse.net/marketplace/formcreator/front/formdisplay.php?id=9
instead of https://mydomain.reverse.net/https/internal-server/gw-1/glpi.mydomain.net/marketplace/formcreator/front/formdisplay.php?id=9

**GLPI / Plugins (please complete the following information):**
- GLPI last version
webapplications      Name: Applications Web               Version: 4.0.1      State: Enabled                                 
		Install Method: Marketplace
	badges               Name: Badges                         Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	accounts             Name: Comptes                        Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.1.4      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	archimap             Name: Diagrammes                     Version: 3.2.18     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.3     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Error / to clean                        
		Install Method: Manual
	order                Name: Gestion des commandes          Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Error / to clean                        
		Install Method: Manual
	webresources         Name: Web Resources                  Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox / Edge / Chrome
 - last Version

**Comment by btry** [comment]
Hi

Check this setting in GLPI. I believe it is misconfigured.

![image](https://user-images.githubusercontent.com/14139801/211315649-7f4da132-c404-4a4d-9448-25f9608cb754.png)

**Comment by tech62** [comment]
Hi !

The domain is correctly set.

If i use my reverse domain directly, it's ok.
If i use the Application Gateway, the url rewite works partially.

**Comment by tech62** [comment]
I confirm, the url on the left menu is correctly rewrited, the other url on the main page are incorrect

**Comment by btry** [comment]
So you have something which modifies the webpage sent by the http server ?

The URL is written twice. Once in an anchor, an other time as text visible on the page. Maybe the problem is here.

Anyway this is not a bug of the plugin. It must rely on the base URL set in glpi; and it shall not handle html alteration done after it is sent by php

**Comment by btry** [comment]
Additional note : the URL is absolute, not relative. Maybe your rewrite system needs to handle that.

**Comment by btry** [comment]
Hi

> any chance that be conflictual between plugins folder and marketplace plugin folder or a bug from glpi himself ?

No. If you carefully check the rewritten URL you can see that there is 2 occurences of http, then I guess the rewrite system does not handles properly absolute urls

**https**://mydomain.reverse.net/**https**/internal-server/gw-1/glpi.mydomain.net/marketplace/formcreator/front/formdisplay.php?id=9

**Comment by btry** [comment]
Hi

Having no feedback, I assume you solved your problem. I also believe this is not a bug in the plugin, then I close.
