### ISSUE TITLE
Question about ticket sequence

### ISSUE THREAD

**Issue by Ludo-code** [pluginsGLPI/formcreator#3146]
Hello, 

I have wanted to know if formcreator support ticket sequence?

For exemple user completed form after complet a ticket is created and when the ticket is close open another for the next task of the form for later be completed by the team.

If formcreator doesn't support ticket sequence yet it's can be possible to add it later ?

**Comment by btry** [comment]
Hi

This is not supported, and is not in the roadmap because this is out of scope of this plugin. Maybe the plugin ProcessMaker can help you.

**Comment by Ludo-code** [comment]
this one ? https://github.com/tomolimo/processmaker

If yes he currently doesn't support glpi v10

**Comment by btry** [comment]
Hi

You should consider to upgrade to GLPI 10 anyway. Support of GLPI 9.5 is about to finish.
