### ISSUE TITLE
After creating a form, adding a session and trying to create a question at the end

### ISSUE THREAD

**Issue by santiagocefa** [pluginsGLPI/formcreator#3150]
I created a form to test the customization, by creating a session and questions. However, when I go to create the questions, the modal opens, but with nothing, everything is blank.

I looked around here for someone who had gone through the same, but I couldn't find it.

GLPI Version: 10.0.5

Form Creator Version :

![image](https://user-images.githubusercontent.com/111087221/213174046-84c527ed-31a7-444f-a364-c45220f9ff59.png)

**Comment by btry** [comment]
Hi 
You used the develop branch. It is planned to be reverted to the state of suport/2.14.0 branche because of some feature additions. 

Use the official releases of the plugin if you plan tu use the plugin without contributing to its code.

https://github.com/pluginsGLPI/formcreator/releases

**Comment by santiagocefa** [comment]
Hi, thank you very much for your attention!!
Put the 2.13.3 version, however, now when I click to add a session and I'm going to save it, it doesn't record. While the question part does not appear yet.

**Comment by santiagocefa** [comment]
Hi, I am back!!
So... the error was between the chair and the table... I redid the process and now everything is fine. I appreciate your help, thank you very much.

**Comment by btry** [comment]
Hi

Great ! Then I close this issue.
