### ISSUE TITLE
Tip for formcreator plugin

### ISSUE THREAD

**Issue by willysaurio** [pluginsGLPI/formcreator#3154]
In each form created it would be useful to have an option that allows, or not, to register the "response form" that is generated and associated as an element each time an incidencident is registered from a form.

![image](https://user-images.githubusercontent.com/65296683/213443587-e0f1b776-7efd-40ce-9eed-ba641e9efcc8.png)

**Comment by btry** [comment]
Hi

Unfortunately this is not possible : the existence of the relation between an incident (a ticket) and the form answer is required for internal needs of the plugin. This relations is used to maintain the assistance requests table (glpi_plugin_formcreator_issuers).
