### ISSUE TITLE
GLPI 10.0.05 FC2.13.3 Liste ne s'affiche plus si "masqué par defaut sauf" contient < ou > 

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#3156]
**Describe the bug**
Bonjour, Testé uniquement sur objet type selection mais c'est peut etre général
Si le filtre contient le caractère < ou > alors la liste ne s'affiche plus sur GLPI 10.0.05 avec FormCeator 2.13.3 . 
Fonctionnait sur GLPI 9.x

**To Reproduce**
![inferieur](https://user-images.githubusercontent.com/78594318/214077008-54819590-3fd6-4c37-9167-4af7a35e7fa9.jpg)

**Expected behavior**

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI version
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment]
Bonjour

De quel type est la question "Atelier concerné" ? J'en ai besoin pour tenter de reproduire.

**Comment by mirda123** [comment]
Merci 
Alors c'est le type "bouton radio" celui de la question

![inferieur2](https://user-images.githubusercontent.com/78594318/214079850-b53eba3f-d026-4546-84f5-54c7b45abfa7.jpg)

**Comment by btry** [comment]
[glpi-formcreator-2.13.4-dev.zip](https://github.com/pluginsGLPI/formcreator/files/10481193/glpi-formcreator-2.13.4-dev.zip)

On dirait que le problème est déjà résolu. Essayez cette archive du plugin sur une instance de tests. C'est la révision actuelle de la branche support/2.13.0. On est très proche de la version 2.13.4 (en attente d'un fix).

**Comment by mirda123** [comment]
Alors l'erreur est toujours présente en version 2.13.4 officielle.  L'erreur est liée à la migration je pense...  j'ai réenregistré le champs en faisant une "fausse modif" et la ca refonctionne.. il faut donc re enregistrer tous les champs qui ont < ou  > 
par contre petit effet de bord dans le nommage dans le formulaire qd je réenregistre  : 
![erreur](https://user-images.githubusercontent.com/78594318/214632526-e70fdb42-69e7-4904-8b81-61dafa6ef33a.jpg)

**Comment by btry** [comment]
Bonjour,

Il y a donc un souci de migration des données d'une ancienne version. Le formulaire a t il été créé avec glpi 9.5 ou inférieur ?

**Comment by mirda123** [comment]
Alors bonne question les premiers tickets datent de janvier 2021 et la preparation des formulaires date certainement de juin 2020 sur la dernière version GLPI sortie à l'epoque qui était..  ?

**Comment by btry** [comment]
😅 je ne connais pas les dates par coeur.


Je suis quasi sûr que glpi 10 n'était pas encore publié en juin 2020. Il faut regarder la liste des releases sur le dépot de glpi. Leur date est disponible.

**Comment by mirda123** [comment]
Alors 9.4.6 Sortie le 5 mai 2020 et 9.5 le 07/07/2020
Il y a des chances que ce soit donc sur une 9.4.. bon je vais reprendre les champs concerné à la main. Je confirme par contre le bug sur 2.13.4  (peut etre faire un ticket à part) tout nouveau champ créé dans le form avec en titre < ou > en bouton radio ou liste se converti en &#60 ou &#62

**Comment by btry** [comment]
Un ticket séparé est mieux. 

D'ailleurs il se peut que rafraîchir la page fasse disparaître le problème. En effet, à la fermeture de la modale d'édition d'une question, le libellé affiché est mis à jour.

**Comment by mirda123** [comment]
exact je confirme, je ressors je reviens, l'affichage est redevenu correct...

**Comment by btry** [comment]
voilà un fix pour le < encodé à tort danas le libellé après modification: 936ccd4752a81f15abaf6699c1c99bf24040069d

**Comment by btry** [comment]
Hi

the above fix should solve the problem. It works when the plugin upgrades to 2.13.5 by searching for radios questions and update the available values.

To test it I recommend to use a testing environment

**Comment by mirda123** [comment]
it works thanks !
