### ISSUE TITLE
FormCreator 2.13.4 bug d'affichage des listes trop longues

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#3157]
**Describe the bug**
Bonjour, sur le type bouton radio ou case à cocher (à minima),  si le texte des choix est trop long, l'affichage est décalé.
Fonctionnait sur la dernière version de FC compatible GPLI 9.x
![bugFClistes](https://user-images.githubusercontent.com/78594318/215114759-981a37d6-ed4b-4173-b33f-2bb8bbd2852a.jpg)

**To Reproduce**
Créer comme sur la copie d'écran

**Expected behavior**
Affichage aligné comme sur les précédentes versions

![bugFClistes2](https://user-images.githubusercontent.com/78594318/215115029-a1ce0717-326c-4a0b-9f78-85db3c834859.jpg)

Merci de votre aide,

**GLPI / Plugins (please complete the following information):**
-GLPI 10.6 et FC 2.13.4 

**Desktop (please complete the following information):**
Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment]
Bonjour

Je pense que vous pouvez résoudre ceci en utilisant une question de type description placée au dessus de la question de type Radios, ou en utilisant directement la description existant dans la question de type Radios.

**Comment by mirda123** [comment]
Bonjour, je connais ses options effectivement qui seraient un contournement du bug  mais pas vraiment satisfaisant, car il est souhaité que le ticket réponse récupère la ligne de réponse complète parenthèse inclue pour guider le technicien.. cela fonctionne parfaitement (pas de décalage)  sur glpi 9.5 avec l'ancien plug in. S'agit -il d'une conséquence définitive de glpi 10?

**Comment by btry** [comment]
> S'agit -il d'une conséquence définitive de glpi 10?

Ça doit être un effet de bord lié aux changements faits sur le CSS du plugin pour le passage en glpi 10.

**Comment by btry** [comment]
Bonjour

Voilà un fix pour améliorer le rendu des questions de type Radios

Après aplication du patch vous devez exécuter la commande suivante pour recompiler le SCSS

php bin/console glpi:plugins:formcreator:scss

**Comment by mirda123** [comment]
Bonjour mon collègue me dit que la commande  bin/console glpi:plugins:formcreator:scss ne passe pas . 
"there are no commands defined in the "plug in : formcreator" namespace

**Comment by btry** [comment]
Bonjour

Vu, et je reproduis. Ca semble impacter toutes les commandes CLI du plugin. Je cherche une solution.

**Comment by btry** [comment]
Bonjour

Vu, et je reproduis. Ca semble impacter toutes les commandes CLI du plugin. Je cherche une solution.

**Comment by btry** [comment]
Bonjour

Il y a eu un changement dans GLPI 10.0.6 qui impacte les commandes CLI de Formcreator. Appliquez le patch suivant (qui modifie le nom des commandes)

651444a27

Ensuite, exécutez `bin/console plugins:formcreator:scss` (suppression du préfixe `glpi:`)

**Comment by btry** [comment]
Bonjour

Avez vous pu tester le patch #3158 ?

**Comment by mirda123** [comment]
Bonjour, pardon pour le retard. Alors oui ca fonctionne pour les boutons radios (tout est bien aligné désormais merci !) Mais pour info cela ne fonctionne pas pour les cases a cocher qui restent décalées de la même manière que l'étaient les boutons radios avant...

**Comment by btry** [comment]
Bonjour

Ajoutez ce commit; ça devrait résoudre le souci: f8fe93a6322bde140e21d95fe4a86a9fa2ce59cb

**Comment by btry** [comment]
Voilà le rendu que j'ai après correction.

Il faut bien penser à rebuild le css du plugin avec la commande  `/bin/console glpi:plugins:formcreator:scss` .
