### ISSUE TITLE
LDAP Search broken in 2.12.7

### ISSUE THREAD

**Issue by rafaelkuhl** [pluginsGLPI/formcreator#3161]
**Describe the bug**
After upgrade to 2.12.7 LDAP Searches don't work anymore.

**To Reproduce**

Go to any form with a LDAP search
Field is show - the results could not be loaded

**Expected behavior**
Dropdown with LDAP search result should be displayed

**Screenshots**

![1](https://user-images.githubusercontent.com/26922162/215764349-9274bf35-00cf-4ecd-bafb-a433052be5ff.JPG)
![2](https://user-images.githubusercontent.com/26922162/215764353-9e3ca3db-1415-4bfa-81f0-7f0760e7b341.JPG)
![3](https://user-images.githubusercontent.com/26922162/215764357-20d92f21-52d2-4bf6-90f5-b640a323b78b.JPG)
![4](https://user-images.githubusercontent.com/26922162/215764358-2db42c02-aef3-45ba-9dd2-167b8e75e20e.JPG)

**GLPI / Plugins (please complete the following information):**
- GLPI v9.5.12

	fields               Name: Additionnal fields             Version: 1.13.0     State: Enabled
	datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.7     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Enabled
	sccm                 Name: Interface - SCCM               Version: 2.3.1      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.7.4      State: Not installed
	oauthimap            Name: Oauth IMAP                     Version: 1.3.4      State: Enabled
	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Enabled

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge; Firefox
 - Version 109.0.1518.69; 109

**Additional context**

In the existing forms you can see the ldap connection, but in the new ones you can't select it, and it doesn't seem to be able to list the connections. 
With the superadmin role the form shows results.

**Comment by btry** [comment]
Hi

Do you have an error in glpi/files/_logs/php-errors.log or glpi/files/_logs/sql-errors.log ?

Show **only** the errors you think related to the error. Not the full files.

**Comment by rafaelkuhl** [comment]
Hi,

When I access the form and try to view the list:

2023-01-31 15:27:19] glpiphplog.WARNING:   *** PHP Warning (2): Trying to
access array offset on value of type null in
/var/www/html/glpi/plugins/formcreator/inc/ldapdropdown.class.php at line 92
  Backtrace :
  plugins/formcreator/ajax/getldapvalues.php:47
PluginFormcreatorLdapDropdown::getDropdownValue()

[2023-01-31 15:27:19] glpiphplog.WARNING:   *** PHP Warning (2): Array to
string conversion in
/var/www/html/glpi/plugins/formcreator/ajax/getldapvalues.php at line 47


LOG: php-errors.log
Best Regards,

**Comment by btry** [comment]
Hi

Can you try GLPI 10 and Formcrreator 2.13.4 ? Do the problem persist ?

**Comment by verdanatech-dev** [comment]
I had a similar problem,

The problem is that when saving the configuration it is handling the & of the condition, in the database it is saving &#38;

this is causing problem in user query

![image](https://user-images.githubusercontent.com/48805206/225988023-550d5395-e9fb-4b42-82ea-ddc59a0b1d89.png)

**Comment by btry** [comment]
Hi

@verdanatech-dev according to your screenshot, I guess that your version of Formcreator is 2.13.0 or above. If I'm right, could you open a distinct issue ? 

This issue is for version 2.12.x, which reached end of life. 

By the way, @rafaelkuhl do you have feedback with version 2.13 ? I recommend you to upgrade to GLPI 10, as version 9.5 is very close to its end of support.

**Comment by btry** [comment]
Hi

This issue is obsolete, then I close.
