### ISSUE TITLE
[glpi 10.0.6] from 2.12.3 to 2.13 error

### ISSUE THREAD

**Issue by falco2001** [pluginsGLPI/formcreator#3163]
Unable to install plug-in
I have the following errors:
since version 2.13 I have
![image](https://user-images.githubusercontent.com/31952346/216093816-db228ab8-5619-4938-8030-7a4101c03be4.png)
and 
![image](https://user-images.githubusercontent.com/31952346/216094072-246a55ba-cbd7-4be6-8ec0-6fd00790db0e.png)
 idem en 2.13.4
How do I upgrade from 2.12.3 to the latest version?
Help!!
Thank you

**Comment by btry** [comment]
Hi

show the result of the following sql

```sql
show create table glpi_plugin_formcreator_entityconfigs;
```

**Comment by btry** [comment]
Also, which is the version of the plugin before your upgrade attempt ?

**Comment by falco2001** [comment]
'glpi_plugin_formcreator_entityconfigs', 'CREATE TABLE `glpi_plugin_formcreator_entityconfigs` (\n  `id` int(11) NOT NULL,\n  `replace_helpdesk` int(11) NOT NULL DEFAULT \'-2\',\n  `sort_order` int(11) NOT NULL DEFAULT \'-2\',\n  `is_kb_separated` int(11) NOT NULL DEFAULT \'-2\',\n  `is_search_visible` int(11) NOT NULL DEFAULT \'-2\',\n  `is_header_visible` int(11) NOT NULL DEFAULT \'-2\',\n  `header` text COLLATE utf8_unicode_ci,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci'

Version 2.12.3 to 2.13 error

Thanks

**Comment by btry** [comment]
Hi

The table is consistent with the version 2.13.3. There is something wrong in the tables sanity check. The message says the check was done against the tables of the version 2.13.4 instead of 2.12.3 (the previous version).

Maybe you tried to upgrade several times and an attempt fooled the detection of the previous version ?

I tried to reproduce with an upgrade from 2.12.1 (same tables structures as 2.12.3).  No problem found.

Can you show the result of this SQL query ?

```sql
select * from glpi_configs where context='formcreator';
```

**Comment by falco2001** [comment]
'327', 'formcreator', 'previous_version', '2.13.4'
'249', 'formcreator', 'schema_version', '2.13'
Thanks

**Comment by falco2001** [comment]
I don’t understand because I just deleted the tables of glpi_plugin_formcreator_%" and imported those of in 2.12.3 .
I have the same result in update and I also have the same result of the config table. I don’t understand anything anymore

**Comment by falco2001** [comment]
bin/console glpi:plugin:install formcreator -f -p skip-db-check
User to use:toto
Traitement du plugin « formcreator »...
SQL Error "1054": Unknown column 'entities_id' in 'where clause' in query "UPDATE `glpi_plugin_formcreator_entityconfigs`                         SET `service_catalog_home` = 0 WHERE `entities_id` = 0"

In DBmysql.php line 438:

  2.13.4 set service_catalog_home in glpi_plugin_formcreator_entityconfigs - Erreur durant l'éxecution de la requête : UPDATE `glpi_plugin_formcreator_ent
  ityconfigs`
                          SET `service_catalog_home` = 0 WHERE `entities_id` = 0 - L'erreur est Unknown column 'entities_id' in 'where clause'

**Comment by falco2001** [comment]
with : 
![image](https://user-images.githubusercontent.com/31952346/216563412-813cbc1f-68de-4ab4-a91d-8dbc0e0fbb3d.png)
i am : 

> Traitement du plugin « formcreator »...
> La mise à jour depuis une version antérieure à 2.5.0 n'est plus prise en charge. Veuillez mettre à jour vers GLPI 9.5.7, mettre à jour Formcreator vers la version 2.12.5, puis mettre à jour à nouveau vers GLPI 10 ou plus récent et Formcreator 2.13 ou plus récent.L'installation du plugin « formcreator » a échoué.

**Comment by btry** [comment]
Hi

The actions you did broke the data required by Formcreaator to handle its upgrade.

You need to restore the tables of the plugin and the 2 lines in glpi_configs table from the backup you took before the first upgrade attempt (I assume you always take a backup before upgrading).

**Comment by falco2001** [comment]
Good morning,
I don’t know what happened!
I restored the glpi_configs table and all formcreator tables and restarted everything and that’s ok!!
Thank you very much
