### ISSUE TITLE
Formcreator 2.13.4 

### ISSUE THREAD

**Issue by willysaurio** [pluginsGLPI/formcreator#3167]
Again I have problems with Formcreator
I updated in a Formcreator 2.13.4 test base and it works for me. I did the same in Production and I get an error when attaching a file. Version 2.13.3 with the patch worked well for me in Production. What happened?.
![image](https://user-images.githubusercontent.com/65296683/216970813-d07b53d8-af13-438e-911e-e905f471064b.png)

in Edge if it works and in Chrome I have that error ...

**Comment by btry** [comment]
Hi

I cannot handle this issue right now. If you closed the issue, I guess you found the problem and solved it. 

Can you tell your findings: where was the problem and how you solved it?

**Comment by willysaurio** [comment]
In reality, the problem continues. I have uninstalled chrome and installed again deleting all history. When I attach a file in the public form (anonymous) the same poster still appears. In edge I work well so now I do not know what happens.
Is it possible to go back to 2.13.3 ?

**Comment by btry** [comment]
II strongly recommend you to test the rollback procedure on your testing environment by copying from your production to the testing:
- the glpi instance (all files, including the plugins)
- the database

With this copy up and running, do the following:
- install the release 2.13.3
- use the following CLI command: php bin/console plugin:install formcreator -f -p force-upgrade -p skip-db-check
- enable the plugin


### future upgrade 

When you will upgrade again to a later version in the future, you *will* have errors in the DB sanity check. You should note them and check that only those errors appear in the sanity check error.

the table **glpi_plugin_formcreator_entityconfigs** will contain an extra column **service_catalog_home**
the table **glpi_plugin_formcreator_conditions** will have the type **mediumtext**

These two errors will be harmless and can be ignored. 

any other error must be evaluated to determine the appropriate fix.

### searching the fix

I need more info to investigate. Stay tuned until I can give you instructions to collect clues.

**Comment by btry** [comment]
Hi

If I undertand well, your problem is related to file uploads in a public form.  Which version of GLPI are you using ?

**Comment by willysaurio** [comment]
Nice day. We have GLPI 10.0.05
Before upgrading to Formcreator 2.13.4 we had 2.13.3 with patch 13641.diff and it worked smoothly.

**Comment by willysaurio** [comment]
In test environment we have 10.0.6 with Fromcreator 2.13.4 and it does not work to attach files in public forms.
Using the Edge browser now also gives error.

**Comment by willysaurio** [comment]
I don't know what's happening with the released versions of Formcreator that give trouble. I will try to test back to 2.13.3 and apply the patch. If it works I will do the same in production.
Pass me the link to 2.13.3 please

**Comment by btry** [comment]
GLPI 10.0.5 contains a change which breaks uploads from public forms. It is known for several weeks, and required a deep analysis. We decided yesterday that it is necessary to drop this feature from Formcreator.

In a future version of the plugin, administrators will no longer be able to add file upload questions to public forms. Textarea questions will disallow to paste a picture in a public form.

Therefore, I recommend you to not lock yourself to old versions of the plugin and update your public forms as stated above. 

You can download Formcreator 2.13.3 from the releases history [here](https://github.com/pluginsGLPI/formcreator/releases). and upgrade later when your public forms are compliant with the incoming limitation.

**Comment by willysaurio** [comment]
I regret that in future it will not be allowed to upload files or paste images into the text of public forms. It is the most important functionality and that we use the most of formcreator. 
It allows people, (not GLPI Users) from different parts of the province, to report software errors of the computer systems we provide to all government agencies.

**Comment by willysaurio** [comment]
It will be very difficult to explain to my superiors that Users of computer systems will not be able to report errors with the corresponding images used by the development department to resolve them. We are talking about thousands of people and creating an GLPI-to-each User for them is not a viable alternative at the moment. I don't know what we're going to do about it. 

I hope that the solution is not that we return to the Redmine application for this to solve these incidents.

**Comment by btry** [comment]
> I regret that in future it will not be allowed to upload files or paste images 

I fully understand you. This was a long debate to search for an alternative. The feature might be back with GLPI 10.1 thanks to improvements in the roadmap. 

The use case you described is quite usual. If you consider giving them credentials, they will have the benefit to follow the resolution progress of their issues.

**Comment by btry** [comment]
Hi

> I reinstalled Formcreator 2.13.3, turned it on, and the file upload error in public form continues. 

This is normal. The feature broke because there is change in GLPI 10.0.5 (compared to 10.0.4).


> Then apply the patch 13641.diff with the command that you will indicate opportunely (see image) and gives 1 error

the patch fails because there is a change in document.send.php at the same place of the failed hunk. I see that this hunk should be simply ignored. In other words, keep document.send.php as it is in the official release of GLPI 10.0.6. 

A last word : the PR 13641 has  not been merged; it has been closed. Then this code does not reach quality requirements for GLPI and should not be used. I kndly recommend you to find an acceptable solution to create user accounts. This will avoid the need to use an unapproved patch, to maintain it over time (you see that it fails to apply flawlessly on the latest GLPI), and your users may be happy to follow the progress of technicians regarding their issue.

**Comment by willysaurio** [comment]
At this time I do not know how we are going to solve the impossibility of using public forms without attachments or pasted images. 
The universe of Users that we have is very varied and I think we are going to lose many records of incidents in GLPI by no longer having this functionality in formcreator. 
Surely the Users of the Computer Systems provided and supported from our address will end up reporting their problems via whatsapp groups, as many already do, and the follow-ups or solutions to them will not be registered in GLPI.
Either way I want to thank you **btry** for your willingness and deference in addressing my concerns.
Thanks a lot.
