### ISSUE TITLE
Uncaught Exception Error: Call to undefined method GlpiPlugin

### ISSUE THREAD

**Issue by otaciobarbosa** [pluginsGLPI/formcreator#3168]
**Describe the bug**
After updating to version: 9.5.12 my forms are returning the error below, how could I proceed?
Uncaught Exception Error: Call to undefined method GlpiPlugin\Formcreator\Field\SelectField::getSubItemtype() in /var/www/html/helpdesk/marketplace/formcreator/inc/targetticket.class.php at line 1035

**GLPI / Plugins (please complete the following information):** FormCreator 2.12.7
- GLPI version: 9.5.12

**Comment by btry** [comment]
Hi

I guess that a question of type GLPI Object has been used as a source to feed an associated item in a target ticket. Later the question has been edited and its type changed to a Select type. This type of question cannot be used to associate an item to a ticket.

those problems of type change will be solved in Formcreator 2.14: changing the type of a question is disabled for technical reasons and this will also avoid scenarios as described above.

Fix the associated elements settings on the target ticket(s) of the impacted form.

**Comment by NoxWorld2660** [comment]
Hello There,

@btry 
I faced the exact same issue.

Your explaination was correct in my case. I had defined 2 selection of "GLPI Object > User" and set them in target ticket properties as requesters and observers , changing these selections to "Actor" and adjusting properties with the new values did the trick.

Thank you.
