### ISSUE TITLE
Formcreator encoding html

### ISSUE THREAD

**Issue by jmarie50** [pluginsGLPI/formcreator#3171]
**Describe the bug**
After migration to GLPI v10.0.6 and Plugin Formcreator v2.13.4 **some** of the ticket titles and content create from form displays html code.

**Expected behavior**
A clear description without html code

**Screenshots**
![image](https://user-images.githubusercontent.com/36478465/217323339-db90a6c6-7729-4e83-aef5-5283a343483b.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.6
-Plugins :
news                 Name: Alertes                                     Version: 1.10.5     State: Enabled                                 
fields                 Name: Champs supplémentaires         Version: 1.20.0     State: Installed / not activated               
behaviors          Name: Comportements                       Version: 2.7.2      State: Enabled                                 
formcreator       Name: Form Creator                   Version: 2.13.4     State: Enabled                                 

Thanks for your help

**Comment by btry** [comment]
Hi

You said **some** tickets. If those tickets have In common that a picture has been pasted in a textarea question, then apply the following fix #3169 

I'm waiting for your feedback.

**Comment by jmarie50** [comment]
Thank you for your prompt response.

Some of these tickets don't have an attachment but there are help images in the question descriptions, I'll check that and let you know.

**Comment by btry** [comment]
This is interesting. I'll check if the fix must extend to description questions. If you have target tickets which don't use descriptions, then let me know if the above fix works for them. 

I'll try to give you news before the end of week.

**Comment by jmarie50** [comment]
Hi

I reproduce the problem with an image in a text area but mine seems different, finally I can't find any trace of an image in the source code of the ticket (see below)

Moreover I can't reproduce my problem after the update of GLPI and Formcreator, maybe this problem occurred during the migration

Ty for your help

_<p>&lt;div&gt;&lt;h1&gt;Données du formulaire&lt;/h1&gt;&lt;h2&gt;Informations usager&lt;/h2&gt;&lt;div&gt;&lt;b&gt;1) NOM Prénom : &lt;/b&gt;Fleury Georges&lt;/div&gt;&lt;div&gt;&lt;b&gt;2) N° de voirie : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;3) Rue / Hameau : &lt;/b&gt;route de carteret&lt;/div&gt;&lt;div&gt;&lt;b&gt;4) Commune : &lt;/b&gt;Bricquebec-en-Cotentin - Bricquebec&lt;/div&gt;&lt;div&gt;&lt;b&gt;5) Téléphone : &lt;/b&gt;0233521399&lt;/div&gt;&lt;div&gt;&lt;b&gt;6) Email : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;7) Nombre de personnes dans le foyer : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;8) Source de la demande : &lt;/b&gt;Téléphone&lt;/div&gt;&lt;h2&gt;Réclamation&lt;/h2&gt;&lt;div&gt;&lt;b&gt;9) Type de demande : &lt;/b&gt;DDMA &gt; Problème lié à la livraison des bacs 2022 - Coeur Cotentin &amp; Montebourg&lt;/div&gt;&lt;div&gt;&lt;b&gt;10) Compléments d'information : &lt;/b&gt;&lt;p&gt;Association qui demande un bac de 360 litres. &lt;/p&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;11) Date d'apparition du problème : &lt;/b&gt;19-08-2022&lt;/div&gt;&lt;div&gt;&lt;b&gt;12) Urgence : &lt;/b&gt;Moyenne&lt;/div&gt;&lt;h2&gt;Pièces jointes&lt;/h2&gt;&lt;div&gt;&lt;b&gt;13) Pièces jointes : &lt;/b&gt;Pas de document rattaché&lt;/div&gt;&lt;h2&gt;Destinataires en copie&lt;/h2&gt;&lt;div&gt;&lt;b&gt;14) Souhaitez-vous ajouter un ou des observateurs à votre demande ? : &lt;/b&gt;Non&lt;/div&gt;&lt;/div&gt;</p>_

**Comment by jmarie50** [comment]
copying and pasting the contents of the description into the "source code" of the ticket solves the problem but I can't do it for all the tickets impacted

**Comment by btry** [comment]
Hi
 
It is unclear in [this comment](https://github.com/pluginsGLPI/formcreator/issues/3171#issuecomment-1422342755) if the patch solved the problem.

It does not fix any issue with description question, I cannot investigate today. I'll let you know the result of my attempts to reproduce, and if I found a fix.

**Comment by jmarie50** [comment]
The patch solve the problem with images in textarea but my problem seems to be an other issue.

The problem appeared after the update with existing tickets but, since the update, I cannot reproduce this problem.

I checked tickets with issue, and it seems the problem appeared even without an image in the form (in text area or in question description).

Ty a lot

**Comment by jmarie50** [comment]
Bonjour Btry,

J'ai remarqué que vous parliez Français sur d'autres tickets :)

Après migration de la v9.5.9 à la v10.0.6, la description et le titre de certains tickets issus de formulaire apparaissent en html.
Tous les tickets issus du même formulaire ne présente pas le problème. Je continue à tenter de trouver un point communs aux tickets qui présente le problème.
Les nouveaux tickets créés après migration à partir deu même formulaire ne présente pas le problème.

Caractères spéciaux présents dans les contenus description et titre : > &

Merci de votre aide,

**Exemple description ticket :** 

_&lt;div&gt;&lt;h1&gt;Donn&eacute;es du formulaire&lt;/h1&gt;&lt;h2&gt;Informations usager&lt;/h2&gt;&lt;div&gt;&lt;b&gt;1) NOM Prénom : &lt;/b&gt;M. Helaine Jean François&lt;/div&gt;&lt;div&gt;&lt;b&gt;2) N° de voirie : &lt;/b&gt;42&lt;/div&gt;&lt;div&gt;&lt;b&gt;3) Rue / Hameau : &lt;/b&gt;le pied sablon&lt;/div&gt;&lt;div&gt;&lt;b&gt;4) Commune : &lt;/b&gt;Fermanville&lt;/div&gt;&lt;div&gt;&lt;b&gt;5) Téléphone : &lt;/b&gt;06 31 27 99 73&lt;/div&gt;&lt;div&gt;&lt;b&gt;6) Email : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;7) Nombre de personnes dans le foyer : &lt;/b&gt;1&lt;/div&gt;&lt;div&gt;&lt;b&gt;8) Source de la demande : &lt;/b&gt;Téléphone&lt;/div&gt;&lt;h2&gt;R&eacute;clamation&lt;/h2&gt;&lt;div&gt;&lt;b&gt;9) Type de demande : &lt;/b&gt;DDMA &gt; Problème lié à la livraison des bacs 2022 - Vallée de l'Ouve, Val de Saire & Saint Pierre Eglise&lt;/div&gt;&lt;div&gt;&lt;b&gt;10) Compléments d'information : &lt;/b&gt;&lt;p&gt;Bonjour,&lt;/p&gt;&lt;p&gt;Pouvez vous livrer cet usager en bacs svp&lt;/p&gt;&lt;p&gt;Il y a possibilité de passer les bacs par dessus la barrière pour les déposer dans la cour (elle est pas haute)&lt;/p&gt;&lt;p&gt;De plus, les rippers ne collectent pas les sacs d'OM, est ce que tu peux faire un rappel auprès de la sphère s'il te plait Guillaume.&lt;/p&gt;&lt;p&gt;Bonne journée&lt;/p&gt;&lt;p&gt; &lt;/p&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;11) Date d'apparition du problème : &lt;/b&gt;01-02-2023&lt;/div&gt;&lt;div&gt;&lt;b&gt;12) Urgence : &lt;/b&gt;Moyenne&lt;/div&gt;&lt;h2&gt;Pi&egrave;ces jointes&lt;/h2&gt;&lt;div&gt;&lt;b&gt;13) Pièces jointes : &lt;/b&gt;Pas de document rattaché&lt;/div&gt;&lt;h2&gt;Destinataires en copie&lt;/h2&gt;&lt;div&gt;&lt;b&gt;14) Souhaitez-vous ajouter un ou des observateurs à votre demande ? : &lt;/b&gt;Oui&lt;/div&gt;&lt;div&gt;&lt;b&gt;15) Observateur 1 : &lt;/b&gt;DUCHESNE Guillaume&lt;/div&gt;&lt;div&gt;&lt;b&gt;16) Observateur 2 : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;17) Observateur 3 : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;18) Observateur 4 : &lt;/b&gt;&lt;/div&gt;&lt;/div&gt;_

**Après passage dans un interprêteur html :**

_<div><h1>Données du formulaire</h1><h2>Informations usager</h2><div><b>1) NOM Prénom : </b>M. Helaine Jean François</div><div><b>2) N° de voirie : </b>42</div><div><b>3) Rue / Hameau : </b>le pied sablon</div><div><b>4) Commune : </b>Fermanville</div><div><b>5) Téléphone : </b>06 31 27 99 73</div><div><b>6) Email : </b></div><div><b>7) Nombre de personnes dans le foyer : </b>1</div><div><b>8) Source de la demande : </b>Téléphone</div><h2>Réclamation</h2><div><b>9) Type de demande : </b>DDMA > Problème lié à la livraison des bacs 2022 - Vallée de l'Ouve, Val de Saire & Saint Pierre Eglise</div><div><b>10) Compléments d'information : </b><p>Bonjour,</p><p>Pouvez vous livrer cet usager en bacs svp</p><p>Il y a possibilité de passer les bacs par dessus la barrière pour les déposer dans la cour (elle est pas haute)</p><p>De plus, les rippers ne collectent pas les sacs d'OM, est ce que tu peux faire un rappel auprès de la sphère s'il te plait Guillaume.</p><p>Bonne journée</p><p> </p></div><div><b>11) Date d'apparition du problème : </b>01-02-2023</div><div><b>12) Urgence : </b>Moyenne</div><h2>Pièces jointes</h2><div><b>13) Pièces jointes : </b>Pas de document rattaché</div><h2>Destinataires en copie</h2><div><b>14) Souhaitez-vous ajouter un ou des observateurs à votre demande ? : </b>Oui</div><div><b>15) Observateur 1 : </b>DUCHESNE Guillaume</div><div><b>16) Observateur 2 : </b></div><div><b>17) Observateur 3 : </b></div><div><b>18) Observateur 4 : </b></div></div>_

**Après second passage dans un interpreteur html :**

_Données du formulaire
Informations usager
1) NOM Prénom : XXXXXXXXXX
2) N° de voirie : 42
3) Rue / Hameau : le pied sablon
4) Commune : Fermanville
5) Téléphone : XXXXXXXXXX
6) Email :
7) Nombre de personnes dans le foyer : 1
8) Source de la demande : Téléphone
Réclamation
9) Type de demande : DDMA > Problème lié à la livraison des bacs 2022 - Vallée de l'Ouve, Val de Saire & Saint Pierre Eglise
10) Compléments d'information :

Bonjour,
Pouvez vous livrer cet usager en bacs svp
Il y a possibilité de passer les bacs par dessus la barrière pour les déposer dans la cour (elle est pas haute)
De plus, les rippers ne collectent pas les sacs d'OM, est ce que tu peux faire un rappel auprès de la sphère s'il te plait Guillaume.
Bonne journée
 
11) Date d'apparition du problème : 01-02-2023
12) Urgence : Moyenne
Pièces jointes
13) Pièces jointes : Pas de document rattaché
Destinataires en copie
14) Souhaitez-vous ajouter un ou des observateurs à votre demande ? : Oui
15) Observateur 1 : XXXXXXXXXXX
16) Observateur 2 :
17) Observateur 3 :
18) Observateur 4 :_

**Comment by jmarie50** [comment]
Github a interprété le code html (après passage dans interpreteur html).

**Comment by btry** [comment]
Bonjour

> J'ai remarqué que vous parliez Français sur d'autres tickets :)

oui, mais si nous utilisons l'anglais, les non-francophones ont l'opportunité de nous lire et trouver des solutions à leurs problèmes.

> Les nouveaux tickets créés après migration à partir du même formulaire ne présente pas le problème.

Le passage de GLPI 9.5 à 10 a révélé des problèmes d'encodage de textes riches qui étaient inconnus jusque là. Par conséquent des tickets créés via Formcreator sous GLPI 9.5 peuvent afficher des balises HTML.

Pour ces tickets vous avez 2 solutions
- finir de les traiter si nécessaire, et les laisser tel quels : une fois fermés, il y aura peu de chances de devoir revenir dessus. C'est probablement ce que font la plupart des administrateurs, vu le très faible taux de remontée du souci, comparé à ce qui est attendu.
- corriger les tickets en patchant GLPI avec [cette PR](https://github.com/glpi-project/glpi/pull/13844) puis en exécutant la commande CLI `bin/console db:fix_html` Vous devrez ajouter des arguments pour spécifier un fichier .sql de rollback. Le patch n'a pas été versé à GLPI pour les raisons évoquées dans la première solution. Soyez scrupuleux si vous voulez l'utiliser, et vérifiez les tickets modifiés. Le .sql de rollback vous aidera à identifier les tickets affectés

**Comment by jmarie50** [comment]
Bonjour,

En PJ, les modifications réalisées sur votre PR pour corriger nos erreurs d'encodage html après migration 9.5 >10.

Merci pour votre aide,
Bien cordialement,

[FixHtmlEncodingCommand.php.txt](https://github.com/pluginsGLPI/formcreator/files/10768781/FixHtmlEncodingCommand.php.txt)
