### ISSUE TITLE
Bug after send button

### ISSUE THREAD

**Issue by Rlctn01** [pluginsGLPI/formcreator#3174]
Hi, 
After upgrading to GLPI 10.0.6 and FormCreator 2.13.4, when users fill the form and click in the "Send" button, the form creates the ticket to the IT group, but nothing happens on the users screen, the user get no response as it keeps on the same screen with his form filled, if he hit the "send" button again and again, he keeps creating tickets without knowing that. 
The "Send" button is not refreshing the page or sending the  notification with his ticket number.

Many tks.

**Comment by btry** [comment]
Hi

Please go to the form, open developer tools of your browser, then reproduce the problem. See if you have JS errors or HTTP errors). 

Check the requests to formanswer.php and see the HTTP response code, the request body (tab payload) and the request response (tab response)

![image](https://user-images.githubusercontent.com/14139801/218102955-fe3e845a-cf9b-4ecc-97f1-e4ff0a903377.png)

**Comment by btry** [comment]
Check also php-errors.log and sql-errors.log in glpi/files/_logs/

**Comment by Rlctn01** [comment]
Hi, 

Tks for the reply.
No JS error:
![image](https://user-images.githubusercontent.com/125037817/218104275-4ba227db-8575-4bdb-97b2-ca5840f69742.png)

![image](https://user-images.githubusercontent.com/125037817/218104692-7dd8f4d9-372a-4874-a451-56f05a98e765.png)


![image](https://user-images.githubusercontent.com/125037817/218104740-50a6f437-7888-445b-ab7c-bf016966de42.png)


![image](https://user-images.githubusercontent.com/125037817/218104779-48ab30a7-7834-4c7e-ab87-e30bd8c4f05b.png)

**Comment by Rlctn01** [comment]
> Check also php-errors.log and sql-errors.log in glpi/files/_logs/


I just figure out with this advice, after 4 days struggling with this and finally come asking for help.

There's a plugin called "Notifications", the plugin was sendind php errors, after desabling the plugin, everthing works fine!


Here is the php error on log.

"[2023-02-10 10:38:26] glpiphplog.WARNING:   *** PHP User Warning (512): plugin_version_gdprropa-master method must be defined! in /var/www/html/helpdesk/src/Plugin.php at line 1654
  Backtrace :
  src/Plugin.php:1654                                trigger_error()
  src/Plugin.php:1692                                Plugin::getInfo()
  src/Plugin.php:722                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:516                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:496                                 Plugin->checkPluginState()
  src/Plugin.php:228                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  plugins/browsernotification/ajax/check.php:5       include()
  
[2023-02-10 10:38:27] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method DB::fetch_assoc() in /var/www/html/helpdesk/plugins/browsernotification/inc/checker.class.php at line 37
  Backtrace :
  ...s/browsernotification/inc/checker.class.php:141 PluginBrowsernotificationChecker::executeQuery()
  plugins/browsernotification/ajax/check.php:22      PluginBrowsernotificationChecker::getNewTicket()
  
"

Tks a lot!

**Comment by btry** [comment]
You should report this error to the maintainer of that plugin. DB::fetch_assoc() call must be replaced. It has been deprecated in GLPI 9.x (don't remember exactly the value of x)
