### ISSUE TITLE
Creating duplicate ticket when pressing submit button several times

### ISSUE THREAD

**Issue by lucastherondel** [pluginsGLPI/formcreator#3176]
**Describe the bug**
When a user fills a form to create a ticket, if he clicks the "submit" button again when the form is being sent, a duplicate of the first ticket will be created.

**To Reproduce**
1. Create a new ticket by clicking the button at the end of a form.
2.  Click the button again when ticket is being created 
3. See several duplicates of the first ticket

**Expected behavior**
The user must not be able to click the submit button a second time if he already clicked it.

**GLPI / Plugins (please complete the following information):**
- 10.0.6
- FormCreator 2.13.4

 - OS: Windows 10 21h1
 - Browser  : Chrome

**Comment by btry** [comment]
Hi

Show the list of your active plugins. A few days ago it has been found that a plugin contains a bug and breaks the redirection after a form submission. Please follow instructions in #3174, and check if you have the plugin **browsernotification**.
