### ISSUE TITLE
users are able to view all forms by simply changing the ID in the URL

### ISSUE THREAD

**Issue by santanaalmeida91** [pluginsGLPI/formcreator#3179]
Dear Support Team,

I am writing to report a bug that I have found in the Formcreator plugin, version 2.13.4. When using this plugin in GLPI version 10.0.6, I have discovered that users are able to view all forms by simply changing the ID in the URL.

This security issue is concerning as it allows unauthorized access to sensitive information. I have tried to reproduce the issue multiple times and can confirm that it is present consistently.

Please let me know if there is a workaround or a fix available for this issue. If any additional information is required, please let me know and I will be happy to provide it.

Thank you for your attention to this matter.

**Comment by btry** [comment]
Hi

Do the problem occur when a user wants to fill a form or when an admin wants to edit a form ?

Can you describe the restrictions applied to a form which should not be accessed, and the context of the user who successfully access the form ? (user, group membership, entity, ...)

**Comment by btry** [comment]
Hi

I guess I found your problem. I believe it ocurs on form answers, not forms.

Please apply the above fix and feedback.

**Comment by santanaalmeida91** [comment]
I made the change in the inc/formanswer.class.php file but checking here I think I wasn't very specific in the URL path, users can access all the forms just by changing the ID of that URL

/marketplace/formcreator/front/formanswer.form.php?id=178

**Comment by btry** [comment]
Hi

Let me describe the cases where a user can view a form answer. 

- the user has right to edit forms => access granted
- the user is the requester (column requester_id in the table glpi_plugin_formcreator_formanswers) => access granted
- the user is the validator of the form answer (column users_id_validator in the table glpi_plugin_formcreator_formanswers) => access granted
- the user is a member of the group validator (column groups_id_validator in the table glpi_plugin_formcreator_formanswers) => access granted
- the user is an actor of a ticket generated from the form answer (requester, watcher or assigned) => access granted

if none of the above case is true, then access is denied.

Please compare the case you believe faulty against the above conditions. Tell me if the result differs from the above rules.

**Comment by santanaalmeida91** [comment]
> Hi
> 
> The URL confirms I found the bug, and the above fix should address it. It fixes the logic used by glpi to allow / deny access to a given form answer.
> 
> I added code for tests, and I was also able to validate it with a manual test.
> 
> I'm suspecting that you changed the file manually. If yes, you should use instead the patch tool.

Excuse my ignorance but how do you do this? If I delete the formcreator folder from my system and download the latest release does it work?

**Comment by btry** [comment]
Hi

>  If I delete the formcreator folder from my system and download the latest release does it work?

The patch is applied in the latest revision, but nit yet in the latest release. If you don't know how to patch the plugin, thn I guess you won't know how to build it.

> how do you do this ? (patching the plugin)

- download the patch you want to apply
  - pick the URL of the patch, append `.diff`. For this issue, the URK of the patch is `https://github.com/pluginsGLPI/formcreator/pull/3195.diff`
  - use the command `wget` to downlaod it on the server `wget https://github.com/pluginsGLPI/formcreator/pull/3195.diff`
  - you finally have the file 3195.diff in the current directory. 
- change the current directory to the root folder of Formcreator with the command `cd` 
- test how the patch applies wih the command `patch -p1 --dry-run < path/to/3195.diff`. Adapt the path to your actual file location.
- if there is an error message, then the application of the patch will fail, you need more help. The plugin is not modified, then you're safe.
- if there is no error message then repeat the `patch` command without the argument `--dry-run`. The patch is now applied.

**Comment by btry** [comment]
[glpi_formcreator_2.13.5-dev.zip](https://github.com/pluginsGLPI/formcreator/files/10935869/glpi_formcreator_2.13.5-dev.zip)

Here is a build of the latest revision.  :warning:  Beware : it requires an upgrade of the plugin then you should use it **only** on a testing instance of GLPI!

**Comment by santanaalmeida91** [comment]
> Hi
> 
> > If I delete the formcreator folder from my system and download the latest release does it work?
> 
> The patch is applied in the latest revision, but nit yet in the latest release. If you don't know how to patch the plugin, thn I guess you won't know how to build it.
> 
> > how do you do this ? (patching the plugin)
> 
> * download the patch you want to apply
>   
>   * pick the URL of the patch, append `.diff`. For this issue, the URL of the patch is `https://github.com/pluginsGLPI/formcreator/pull/3195.diff`
>   * use the command `wget` to downlaod it on the server `wget https://github.com/pluginsGLPI/formcreator/pull/3195.diff`
>   * you finally have the file 3195.diff in the current directory.
> * change the current directory to the root folder of Formcreator with the command `cd`
> * test how the patch applies wih the command `patch -p1 --dry-run < path/to/3195.diff`. Adapt the path to your actual file location.
> * if there is an error message, then the application of the patch will fail, you need more help. The plugin is not modified, then you're safe.
> * if there is no error message then repeat the `patch` command without the argument `--dry-run`. The patch is now applied.

After following your guidance, I was able to update and the problem was fixed, thank you very much for your help and assistance.

**Comment by btry** [comment]
Hi

Great, thank you for your feedback. I close this issue.
