### ISSUE TITLE
Formcreator 2.13.4 capture d'écran

### ISSUE THREAD

**Issue by yorutech** [pluginsGLPI/formcreator#3183]
**Describe the bug**
Bonjour,
Après avoir migré notre glpi 9.5.2 vers la 10.0.5, nous rencontrons un problème lors de la création d'un ticket via l'interface simplifié.
En effet, lorsque qu'un utilisateur utilisant le profil "Self-service" créé un ticket via le formulaire de formcreator et ajoute une capture d'écran dans la zone de texte, le ticket devient illisible une fois le ticket créé.
Sur le ticket du html se rajoute.
Alors que via l'interface standard le ticket se créé correctement, sans code html lors de l'ajout d'une capture d'écran.

**To Reproduce**
1. En interface simplifié, aller dans ''demander une assistance"
2. Choisir le formulaire "demande" ou "incident"
3. Remplir les différents éléments du formulaire et dans la question "Description" ajouter une capture d'écran avec le raccourci Win+MAJ+S.
4. Retourner voir le ticket pour voir si il est devenu illisible avec du code html qui c'est rajouté.

**Expected behavior**
Le ticket créé via formcreator en interface simplifié est illisible car du code html c'est rajouté dans la description.

**Screenshots**
![image](https://user-images.githubusercontent.com/125986510/220368447-52d832d7-4cfe-4ddc-b286-715bcb3541ff.png)

![image](https://user-images.githubusercontent.com/125986510/220368603-47e3bc46-d8a6-460e-aa85-50004fc3a8d0.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version : 10.0.5
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
- 
![image](https://user-images.githubusercontent.com/125986510/220369001-58fe9ead-fb38-4b56-afac-243da55449d4.png)

**Desktop (please complete the following information):**
 - OS: windows 10 et 11 professionnel (21H2)
 - Browser : Chrome (110.0.5481.104 64 bit), edge (110.0.1587.50 64 bit)

Cordialement, 
![Capture d'écran_20230221_151200](https://user-images.githubusercontent.com/125986510/220370810-ac45f8f0-8403-4eb3-b4aa-dc5176c46fce.png)
![Capture d'écran_20230221_151108](https://user-images.githubusercontent.com/125986510/220370936-ee2c27c9-37b3-496c-9874-fc91bff933da.png)

**Additional context**

**Comment by btry** [comment]
Bonjour

Le problème a déjà été corrigé, mais le fix n'est pas encore livré. Je ne suis pas disponible pour le moment pour fournir le correctif. Merci de le retrouver dans les PR fermées et fusionnées. Faites une recherche par mots clés, en anglais, elle devrait être (je pense) dans les 2 premières pages.

**Comment by yorutech** [comment]
ok, merci je vais chercher, je reviendrai vers vous si je ne trouve pas.
Encore merci pour votre réactivité, c'est vraiment un plaisir.

**Comment by yorutech** [comment]
Bonjour, 

Est-ce que la patch sera dans une prochaine mise à jour de GLPI ?

**Comment by btry** [comment]
Bonjour, 

Oui, le patch sera dans la prochaine version. Par contre, en relisant vos screenshots je ne vois pas si votre problème touche un formulaire public. C'est un détail important, car la possibilité d'uploader des fichiers ou des images anonymement sera supprimée (c'est une décision tres récente, et ce sera normalement effectif dans la prochaine release). Cela pose trop de problèmes actuellement.

**Comment by yorutech** [comment]
Oki, super, je vais attendre ou faire des tests car j'ai du mal à comprendre comment utiliser vos patchs. (Première fois que j'utilise Github sorry)

Sinon nous n'utilisons pas les formulaires anonyme donc pas de problème de ce côté là.

**Comment by stdglpi** [comment]
Bonjour à tous,

j'ai exactement découvert le même problème lors de l'ajout d'image dans via formulaire.
Je suis venu faire un tour ici en espérant trouver un fix.

Pour ma part, ceux sont des formulaires authentifiés. (du coup non public)

Bonne soirée

**Comment by btry** [comment]
Bonjour
[formcreator_2.13.5-dev.zip](https://github.com/pluginsGLPI/formcreator/files/10896043/formcreator_2.13.5-dev.zip)

@yorutech , @stdglpi essayez cette version du plugin (en préprod !) 

Est ce que le problème persiste ?

**Comment by stdglpi** [comment]
@btry j'ai oublié de répondre mais j'ai pu utiliser votre patch en cherchant dans le backlog des issues et ça fonctionne parfaitement !

**Comment by btry** [comment]
Ok, donc le problème est résolu. Merci pour le retour.
