### ISSUE TITLE
">" encoding issue when ITIL subcategories is used to create target ticket title

### ISSUE THREAD

**Issue by jmarie50** [pluginsGLPI/formcreator#3186]
Hi,

**Describe the bug**
When an ITIL sub-category is used for answers to a question on the form and reused to create the target ticket, the ">" character is displayed as `&#62;`

**To Reproduce**
Use ITIL sub-category to set the target ticket title

**Expected behavior**
Should be ">"

**Screenshots**
![2023-02-23 14_43_06-Window](https://user-images.githubusercontent.com/36478465/220924776-538c56c0-63d2-4822-a8d0-5fb6f3d2f512.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.6 
- Plugins : Formcreator 2.13.4 ; News 1.10.5 ; Behaviors 2.7.2 ; Pdf 3.0.0

Thank you very much,

**Comment by btry** [comment]
Hi if I remember well this issue is already fixed. I cannot give you the patch now, but you may try the latest revision of the plugin in the branch support/2.13.0

**Comment by jmarie50** [comment]
Hi btry and and thank you for your quick response
I did not find the revision you are talking about but I am not familiar with github
I will wait until you are available, thank you very much

**Comment by jmarie50** [comment]
Working, thank you btry

**Comment by TR0LLL** [comment]
Good morning.

I updated the form creator plugin and started having the same problem, how did you solve it?
My version is:
GLPI: 10.0.7
FormCreator: 2.13.8
