### ISSUE TITLE
File Attached when submitting for Approval

### ISSUE THREAD

**Issue by alfredudu** [pluginsGLPI/formcreator#3187]
**Describe the bug**

I am assembling standard forms at the company, which are filled out partly by the applicant and partly by the appraiser

When the evaluator goes to check the document and edit the answers, the attachment is no longer there, and as I made this field mandatory, he needs to first download the attached document and have to attach it again, and this is causing failures in the process.

Can you sort it out please?

**GLPI / Plugins

- GLPI version

10.0.6 / 
Formcreator
![image](https://user-images.githubusercontent.com/9286827/220994545-9e0e5ee5-3b7a-48ba-b788-6b15aafd060d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest
In this part, when editing the responses, the previous attachment is not loaded

![image](https://user-images.githubusercontent.com/9286827/220994874-083d8420-e204-4be2-a5d1-147bd1dcfc47.png)

**Comment by btry** [comment]
Hi

I assume this will be easy to reproduce. But may be hard to solve. Expect some delay, and stay tuned if I need to ask you some questions.

**Comment by alfredudu** [comment]
I believe it was explained in a way that you understood, correct?

If so, I'll be waiting for your comments.

**Comment by btry** [comment]
I think I understood your issue. This will be confirmed if I reproduce the bug

**Comment by alfredudu** [comment]
Thanks!

> I think I understood your issue. This will be confirmed if I reproduce the bug

**Comment by alfredudu** [comment]
Did it work to simulate or error?

**Comment by Julia12345678901** [comment]
Hi, 
Can you help me for this upload file??
When I selected one file, nothing changement status?

**Comment by btry** [comment]
Hi

I could not investigate enough so far on this issue. Please, be 1ware that community support is done with best effort.

If you need quicker handling, you should consider to subscribe professional support https://services.glpi-network.com/ .

**Comment by btry** [comment]
Hi

Could you try this PR and feedback please ?

https://github.com/pluginsGLPI/formcreator/pull/3225

**Comment by alfredudu** [comment]
Hello,

As a workaround, I disabled the approval, because if I leave it with him I will lose the file later, and I believe that opening a ticket in glpi will not solve it...

**Comment by btry** [comment]
Hi

> As a workaround, I disabled the approval, because if I leave it with him I will lose the file later

The pr above is a fix to solve your problem if you cannot validate it works for you, then you may wait a new release containing the fix 

> and I believe that opening a ticket in glpi will not solve it...

I don't understand. I did not suggested that to solve your problem.

**Comment by btry** [comment]
Hi

I think the above PR does not fully fit your need. The following should fully address your issue.

You may try to patch GLPI with this PR: https://github.com/glpi-project/glpi/pull/14418 and patch Formcreator with this PR https://github.com/pluginsGLPI/formcreator/pull/3226

**Comment by btry** [comment]
Ok, 

Can you apply 2 patches : 
- https://github.com/glpi-project/glpi/pull/14418 on GLPI, 
- https://github.com/pluginsGLPI/formcreator/pull/3226 on Formcreator

and tell if the problem is solved ?

**Comment by btry** [comment]
Hi

Do you have feedback for the above patches ?

**Comment by alfredudu** [comment]
Patches OK. Solved

**Comment by alfredudu** [comment]
Ok
