### ISSUE TITLE
Many history entries

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#319]
Can you reduce the entries auf history ?
For one form i got history for each select but there is no sense in the entry.

ID  Date    User    Field   Update
80976   06-10-2016 10:31    user-x-z (249)  Ticket  Add a link with an item: Anforderung Hardware / Software (2331)
80970   06-10-2016 10:31    user-x-z (249)  Status  Change waiting by accepted
80870   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1339))
80869   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1338))
80868   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1337))
80867   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1336))
80866   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1335))
80865   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1334))
80864   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1333))
80863   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1332))
80862   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1331))
80861   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1330))
80860   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1329))
80859   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1328))
80858   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1327))
80857   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1326))
80856   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1325))
80855   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1324))
80854   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1323))
80853   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1322))
80852   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1321))
80851   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1320))
80850   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1319))
80849   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1318))
80848   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1317))
80847   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1316))
80846   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1315))
80845   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1314))
80844   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1313))
80843   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1312))
80842   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1311))
80841   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1310))
80840   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1309))
80839   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1308))
80838   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1307))
80837   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1306))
80836   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1305))
80835   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1304))
80834   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1303))
80833   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1302))
80832   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1301))
80831   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1300))
80830   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1299))
80829   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1298))
80828   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1297))
80827   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1296))
80826   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1295))
80825   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1294))
80824   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1293))
80823   05-10-2016 17:01    user-x-y (155)  Answer  Add an item: Answer (N/A (1292))

**Comment by btry** [comment]
Entries related to answers are useless because we see only IDs here. The above patch disables logging for answers.
