### ISSUE TITLE
Balise de texte riche dans les tickets générés depuis un fomulaire

### ISSUE THREAD

**Issue by pchauvin94** [pluginsGLPI/formcreator#3190]
Bonjour,
dans les tickets générés pas les formulaires, toutes les balises html apparaissent dans le champs description
Exemple:
 <p>Test texte riche via formulaire</p> <table style="border-collapse: collapse; width: 100.052%;" border="1"><colgroup><col style="width: 49.8829%;"><col style="width: 49.8829%;"></colgroup> <tbody> <tr> <td>Colonne 1</td> <td>Colonne 2</td> </tr> <tr> <td> </td> <td> </td> </tr> <tr> <td> </td> <td> </td> </tr> </tbody> </table> <p> </p> <p>

![Ticket](https://user-images.githubusercontent.com/123629145/221599432-fec21d45-7251-4907-8580-c01a14c0b80e.png)

GLPI 10.0.6 sur Debian 11 - Form Creator 2.13.4

**Comment by btry** [comment]
Bonjour,

Je suis en congé. Pour vous aider essayez de remplir un formulaire sans image. Si il n'y a pas de balise HTML dans le ticket, cherchez dans les PR fermées un correctif correspondant à votre problème (de mémoire un correctif existe). Il doit dater d'environ 4 semaines ou 5 semaines maximum.

**Comment by pchauvin94** [comment]
Merci de répondre malgré vos congés.

Je viens de faire le test en incluant dans le formulaire du texte + 1 tableau copié depuis Excel: pas de problème d'affichage.
Je vais essayer de retrouver ce correctif donc.

**Comment by pchauvin94** [comment]
J'ai retrouvé ce PR:
https://github.com/pluginsGLPI/formcreator/pull/3169
mais le correctif est pour une version antérieur à la 2.13.4 car je n'ai pas de dossier /tests/3-unit

**Comment by btry** [comment]
Bonjour

le dossier tests/ est absent car vous utilisez une copie de Formcreator packagée pour la production. En appliquant le correctif, vous devez simplement sauter les modifications qui portent sur les fichiers de ce dossier tests/

**Comment by pchauvin94** [comment]
Bonjour,

J’ai donc fait uniquement la modification suivante :
***@***.***

Cependant, voici ce que donne un ticket créé depuis un formulaire dans lequel une image a été insérée :
***@***.***

On retrouve toujours des balises HTML (<P> et </P>).

Y-a-t-il quelque chose que j’ai encore manqué du coup ?

Merci pour votre aide.


De : btry ***@***.***>
Envoyé : lundi 6 mars 2023 11:11
À : pluginsGLPI/formcreator ***@***.***>
Cc : CHAUVIN Philippe ***@***.***>; Author ***@***.***>
Objet : Re: [pluginsGLPI/formcreator] Balise de texte riche dans les tickets générés depuis un fomulaire (Issue #3190)


Bonjour

le dossier tests/ est absent car vous utilisez une copie de Formcreator packagée pour la production. En appliquant le correctif, vous devez simplement sauter les modifications qui portent sur les fichiers de ce dossier tests/

**Comment by btry** [comment]
Seuls les tickets créés après application du correctif sont concernés. Ls tickets déjà existants ne sont pas corrigés. Avez vous vérifié le résultat en remplissant un formulaire ?

**Comment by pchauvin94** [comment]
Oui, le résultat envoyé correspond à un ticket créé après application du correctif.
Serait-il nécessaire de redémarrer apache ou mysql pour prise en compte?

De : btry ***@***.***>
Envoyé : lundi 6 mars 2023 12:15
À : pluginsGLPI/formcreator ***@***.***>
Cc : CHAUVIN Philippe ***@***.***>; Author ***@***.***>
Objet : Re: [pluginsGLPI/formcreator] Balise de texte riche dans les tickets générés depuis un fomulaire (Issue #3190)


Seuls les tickets créés après application du correctif sont concernés. Ls tickets déjà existants ne sont pas corrigés. Avez vous vérifié le résultat en remplissant un formulaire ?

**Comment by btry** [comment]
Non, redémarrer Apache ou PHP n'aidera pas.

**Comment by btry** [comment]
On est bien d'accord que le problème n'apparaît **QUE** quand une image est déposée dans une question de type "zone de texte" et que cette zone de texte est versée dans le contenu d'un ticket ?

**Comment by pchauvin94** [comment]
Oui c’est bien ça.

Voici la zone de texte du formulaire :
***@***.***


L’intégralité du contenu du formulaire étant de toute façon déversé dans le champs description du ticket cible créé.

De : btry ***@***.***>
Envoyé : lundi 6 mars 2023 14:02
À : pluginsGLPI/formcreator ***@***.***>
Cc : CHAUVIN Philippe ***@***.***>; Author ***@***.***>
Objet : Re: [pluginsGLPI/formcreator] Balise de texte riche dans les tickets générés depuis un fomulaire (Issue #3190)


On est bien d'accord que le problème n'apparaît QUE quand une image est déposée dans une question de type "zone de texte" et que cette zone de texte est versée dans le contenu d'un ticket ?

**Comment by btry** [comment]
Les images ne sont pas récupérées par Github quand vous répondez par email.

Le fix devrait fonctionner : il a déjà été validé. Essayez de créer un formulaire qui génère un ticket, mais avec uniquement une question de type "zone de texte". Voyez si le problème est résolu avec ce formulaire de test.

**Comment by pchauvin94** [comment]
![Balises HTML dans ticket](https://user-images.githubusercontent.com/123629145/223130045-c2fdfd4b-3c0f-41f9-80f1-cfdb4f50a6cc.png)

![textareafield class php](https://user-images.githubusercontent.com/123629145/223131082-85bd9b1c-1d13-47cc-93ea-f409e7d8bf43.png)

Test effectué mais toujours le même résultat

**Comment by btry** [comment]
Un erreur courante est de patcher la mauvaise copie du plugin quand il en existe 2 copies dans plugins/ et marketplace/. Vérifiez le dossier marketplace/. Si Formcreator s'y trouve, alors vous avez patché la mauvaise copie (que je vous recommande de supprimer, en passant)

**Comment by btry** [comment]
Autre chose : il me semble que le fichier n'est pas patché correctement : 

La ligne où se trouve votre curseur, sur la capture d'écran doit être supprimée. Il y a une autre modification dans deserializeValue(...) { ... } que n'est pas affichée,

Avez vous bien utilisé l'outil patch pour appliquer le correctif ?

**Comment by pchauvin94** [comment]
Ah.
Je ne suis pas du tout familier avec l’outil patch en fait.
J’ai donc fait la modification manuellement via nano sur Debian.
Et effectivement, dans /plugin et pas /marketplace.

Y-a-t-il un tuto de l’outil patch svp ?

De : btry ***@***.***>
Envoyé : lundi 6 mars 2023 15:07
À : pluginsGLPI/formcreator ***@***.***>
Cc : CHAUVIN Philippe ***@***.***>; Author ***@***.***>
Objet : Re: [pluginsGLPI/formcreator] Balise de texte riche dans les tickets générés depuis un fomulaire (Issue #3190)


Autre chose : il me semble que le fichier n'est pas patché correctement :

La ligne où se trouve votre curseur, sur la capture d'écran doit être supprimée. Il y a une autre modification dans deserializeValue(...) { ... } que n'est pas affichée,

Avez vous bien utilisé l'outil patch pour appliquer le correctif ?

**Comment by btry** [comment]
> Et effectivement, dans /plugin et pas /marketplace.

Donc  vous avez une copie du plugin dans marketplace ?

> Y-a-t-il un tuto de l’outil patch svp ?

 téléchargez le patch en utilisant l'url de la PR (ou d'un commit) et en ajoutant .diff à la fin

https://github.com/pluginsGLPI/formcreator/pull/3169.diff

Vous aurez un fichier texte à télécharger.

placez vous dans le dossier de  formcreator, puis exécutez, en adaptant le chemin vers le fichier patch.
`patch -p1 --dry-run < path/to/patch-file.diff`

Si il n'y a pas d'erreur (ignorez celles sur le dosseir tests/) alors répétez la commande sans **--dry-run**

**Comment by pchauvin94** [comment]
Je n'ai pourtant fait aucune modification manuelle.
Que faire donc?

**Comment by pchauvin94** [comment]
J’ai bien 2 copies du plugin. Une dans /Plugin et l‘autre dans / marketplace

De : btry ***@***.***>
Envoyé : lundi 6 mars 2023 15:14
À : pluginsGLPI/formcreator ***@***.***>
Cc : CHAUVIN Philippe ***@***.***>; Author ***@***.***>
Objet : Re: [pluginsGLPI/formcreator] Balise de texte riche dans les tickets générés depuis un fomulaire (Issue #3190)


Et effectivement, dans /plugin et pas /marketplace.

Donc vous avez une copie du plugin dans marketplace ?

Y-a-t-il un tuto de l’outil patch svp ?

téléchargez le patch en utilisant l'url de la PR (ou d'un commit) et en ajoutant .diff à la fin

https://github.com/pluginsGLPI/formcreator/pull/3169.diff

Vous aurez un fichier texte à télécharger.

placez vous dans le dossier de formcreator, puis exécutez, en adaptant le chemin vers le fichier patch.
patch -p1 --dry-run < path/to/patch-file.diff

Si il n'y a pas d'erreur (ignorez celles sur le dosseir tests/) alors répétez la commande sans --dry-run

**Comment by btry** [comment]
> Je n'ai pourtant fait aucune modification manuelle.
> Que faire donc?

Je viens de faire un test. Le patch fonctionnera. C'est moi qui ai mal lu le diff de la PR.


> J’ai bien 2 copies du plugin. Une dans /Plugin et l‘autre dans / marketplace

Déplacez la copie située dans plugins/ hors de l'arborescence de votre GLPI.

**Comment by pchauvin94** [comment]
Lorsque je renomme le dossier formcreator dans /plugin en formcreatorsave, GLPI plante.

**Comment by btry** [comment]
C'est normal si vous n'avez pas déplacé le dossier hors de GLPI. Mettez-le dans /home/your-user-name/ par exemple

**Comment by pchauvin94** [comment]
Et j'ai bien déplacé le dossier formcreator de /plugin en dehors de l'arborescence glpi

**Comment by btry** [comment]
> la commande patch ne produit aucun résultat et n'a pas l'air de se terminer

Vous avez oublié le symbole  inférieur à (`<`) dans la commande. C'est pour cela qu'il ne se passe rien.

**Comment by pchauvin94** [comment]
Vraiment désolé.
Donc j'ai exécuter la commande patch. Elle ne m'a retournée aucune erreur.
Du coup je l'ai exécuté sans  --dry-run
Mais visiblement; dans le fichier textareafield.class.php du dossier marketplace, les modifications n'ont pas été apportées.

[3169.diff.txt](https://github.com/pluginsGLPI/formcreator/files/10899615/3169.diff.txt)

[textareafield.class.php.txt](https://github.com/pluginsGLPI/formcreator/files/10899623/textareafield.class.php.txt)

**Comment by pchauvin94** [comment]
Et les balises html apparaissent toujours dans le ticket

**Comment by btry** [comment]
[textareafield.class.php.txt](https://github.com/pluginsGLPI/formcreator/files/10899660/textareafield.class.php.txt)

Voici le fichier en version 2.13.4, sur lequel le patch a été appliqué.

**Comment by pchauvin94** [comment]
Impeccable! Avec cette version du fichier, les balises n'apparaissent effectivement plus.
Merci beaucoup pour votre patience et votre aide.
Longue vie au plugin FormCreator!

**Comment by btry** [comment]
Parfait; je ferme donc ce ticket.
