### ISSUE TITLE
Apporter aide utilisateur pour remplir Formulaire

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#3193]
Bonjour

j'ai réalisé un document (word, par exemple), téléchargé dans documents dans GLPI
je souhaiterais proposer une aide utilisateurs afin de remplir le formulaire.

j'ai ajouté un entete dans le formulaire : pour de l'aide cliquer ici (lien vers le document téléchargé)
Mais GLPI n'ouvre pas le document et pointe vers le document.

Comment faire pour que cette aide s'affiche ?

ou se baser sur les bases de connaissance de GLPI ?
Merci

**Comment by btry** [comment]
Bonjour

Essayez cette PR: https://github.com/pluginsGLPI/formcreator/pull/3189

**Comment by EC2311** [comment]
Bonjour
Merci

j'ai ajouté ces modifications, mais je ne vois pas ce que cela apporte niveau utilisation du formulaire. 
je pense que cela peut etre utile pour mettre de la doc lors de la **conception** du formulaire : ok

mais de mon cote c'est pour ajouter de l'aide lors de l'**utilisation** du formulaire. et là, le document chargé n'apparait pas.

**Comment by btry** [comment]
Cette PR permet d'associer des documents à un formulaire. Le fait qu'un document soit associé au formulaire doit aider GLPI pour autoriser le téléchargement du document.

**Comment by btry** [comment]
Après application de la PR, associez le document qui vous intéresse au formulaire.

**Comment by EC2311** [comment]
oui c'est ce que j'ai fait
mais je ne vois pas d'amélioration

A noter que j'ai spécifié "l'aide" dans l'entete du formulaire
![image](https://user-images.githubusercontent.com/42341169/223118695-eedc05f1-2507-46d6-a314-c3bb2d47cb0d.png)
Du coup je vois bien ce texte lors de l'utilisation du formulaire , mais quand je clique sur 'ici' : le formulaire m'envoie sur le document GLPI sans l'ouvrir.
ou alors le document est mal décrit ?

**Comment by btry** [comment]
Vérifiez le code HTML de l'entête. Il doit pointer vers document.send.php.

**Comment by EC2311** [comment]
en effet, en editant l'entete : j'avais document.**form**.php?**id**=79
en remplacant form par send, et id par docid : il demande le telechargement du doc . 
Je pense que peut etre du version glpi (9.5.5) ?

**Comment by btry** [comment]
Non. De mémoire document.send.php existe depuis très longtemps. Il faut juste bien différencier l'url qui renvoie vers le document, en tant qu'objet de GLPI, et le fichier qui est représenté oar cet objet (qui est un téléchargement). Ce lien (document.send.php) est dans la page du document (document.form.php).

**Comment by btry** [comment]
Bonjour

Il n'y a  rien de prévu pour provoquer l'ouverture directe du fichier. De plus, le plugin es tributaire de GLPI pour cela, du coup je ne peux pas modifier ce comportement. L'utilisateur doit ouvrir son fichier téléchargé lui-même.

**Comment by EC2311** [comment]
Bonjour
Merci pour vos reponses
J'ai trouvé un moyen de réaliser cette aide via GLPI. J'ai utilisé la base de connaissance, qui permet de realiser un document, puis lien dans l'entete du formulaire vers l'article de la base de connaissance.

Encore merci
