### ISSUE TITLE
Duplicidade de Formulario.

### ISSUE THREAD

**Issue by kh3v1n** [pluginsGLPI/formcreator#3198]
Olá boa tarde, estou com problema com abertura de chamado, através dos formulários, após implementar o glpi10 com o formcreator novo,  caso eu clique 5x no botao enviar, está gerando 5 chamados, no caso duplicando, quanto mais aperto mais duplica o chamado, ate abertura de 1. 
![Screenshot_1](https://user-images.githubusercontent.com/65375437/223536280-b4373b2a-0034-4dfc-8c54-0f67bd8b2257.jpg)

no caso botao enviar. cliquei 10x são chamados duplicado que ele cria.

**Comment by btry** [comment]
Hi

What is the version of Formcreator?

**Comment by kh3v1n** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/65375437/223558969-fc104a24-940a-450f-ba71-fb2d15f251c6.jpg)

Versao 2.13.4

**Comment by btry** [comment]
Hi

Open the developer tools of your browser then click the "send" button.  Find a http request to ajax/formanswer.php. Show the http response code and the http response body.

Also, check if there are errors logged in glpi/files/_log/php-errors.log and glpi/files/_log/sql-errors.log

**Comment by CalelBecassi** [comment]
Ola, estou com o mesmo problema... aqui está o que pediu acima pro outro usuário:

![php errors log](https://user-images.githubusercontent.com/55924822/227644502-f76d1b13-daa1-459b-aeb9-b68a6b92a070.png)
![response headers](https://user-images.githubusercontent.com/55924822/227644506-7a9e4f7f-bc55-4fd5-9452-7b54c7527bb1.png)
![response](https://user-images.githubusercontent.com/55924822/227644507-ab0b8a4b-1b35-4c41-966a-582c0e65bd1e.png)

**Comment by CalelBecassi** [comment]
Ja dei uma olhada na issue #3176, não temos o plugin browsernotification instalado... temos esses:

![image](https://user-images.githubusercontent.com/55924822/227644907-4cc10772-0a52-41d4-8e02-14fed6d34df3.png)

**Comment by btry** [comment]
Hi

The version 2.13.4 does not contains any mention of a variable $question in inc/question.class.php L1054 (see [here](https://github.com/pluginsGLPI/formcreator/blob/2.13.4/inc/question.class.php#L1054)). Your copy of the plugin seems different from the version 2.13.4

Your issue might be related to the error found in the logs, but I cannot investigate if your copy of the plugin is not identical to the release.

**Comment by FabianoMagalhaes** [comment]
Hello good afternoon!

I am also having the same problem!

By clicking on the "send" button several times (Submit) on the form, several tickets are created (one for each click).

I verified that the FormCreator's submit button does not deal with protection against duplication in the click, and allows the user to click several times, opening several duplicate tickets.

My environment:

GLPI - Version 10.0.7
FormCreator - 2.13.6
![config GLPI](https://github.com/pluginsGLPI/formcreator/assets/108367729/348d4f45-fa23-4f39-a721-cdb0d85c3c69)

**Comment by btry** [comment]
Hi @FabianoMagalhaes 

Please read release notes. You need to apply a patch to  glou 10.0.7 or older

**Comment by FabianoMagalhaes** [comment]
Hi @btry 

Thank you so much for your Fast answer!

I Will Read release notes. So, this patch solved this problem?  

Tks

**Comment by btry** [comment]
Of course, or I would not mention it in the release notes.

The match fixes a small error in glpi which prevents disabling the submit button. Also there will be a visual feedback to acknowledge the button has been clicked.

**Comment by FabianoMagalhaes** [comment]
Oh, Great Job!! Very good!

I'm Sorry, I don't saw this information at release notes.

But, I will update now. Thank you so much for help me.

Regards, see you.

Fabiano

**Comment by FabianoMagalhaes** [comment]
Hi, @btry Good Evening!

I applied the Patch to my GLPI 10.0.7 (#14646) and updated the plugin, but I was unsuccessful, the button did not perform the hide function and the tickets continue to duplicate.

I noticed that it only worked if I turned on Debug mode and I didn't understand why. I have already reinstalled 3x. Could you please give me a hint of what might be going on?

In normal mode (Debug mode off), it didn't work and I got the following error in the Browser inspector:

-Google Chrome 114.0.5735.110
-GLPI 10.0.7
-FormCreator 2.13.6

![image](https://github.com/pluginsGLPI/formcreator/assets/108367729/16186491-4e78-4abb-842f-265d0941d001)

**Comment by btry** [comment]
Hi

Delete glpi/js/common.min.js

Then go to a form, refresh the browser's cache with Ctrl+shift+R. It should be ok.

**Comment by FabianoMagalhaes** [comment]
Hi @btry,

Great! Very good ! It worked!

Thank you so much for all your support and congratulations for the support in the community! I'm a big fan of the GLPI Project!

Greetings,

Fabiano

**Comment by btry** [comment]
Hi

Thank you ery much for your feedback and support.

As your problem is solved, and @kh3v1n did not gave more feedback, I close this issue.
