### ISSUE TITLE
Impossible to create/modifiy question with formcreator 2.13.4 (glpi 10.0.3)

### ISSUE THREAD

**Issue by Azgar1998** [pluginsGLPI/formcreator#3199]
Hello,
I migrate GLPI 9.7 to 10.0.3. i use formcreator 2.13.4. The existing form works but we cannot modify or add questions (no reaction when clicking on the buttons "+ add a question" or "+ add a section"). It does the same thing by uninstalling and reinstalling the plugin formcreator.when I want to add a form it does the same thing: cannot add a question.
same thing to click bonton "export":  no reaction.

integrity  database: OK ("bin/console glpi:database:check_schema_integrity -p formcreator" and "bin/console glpi:database:check_schema_integrity"). 

Thanks for your help

**Comment by btry** [comment]
Hi

Did you try to refresh the browser's cache with F5 when you are on the form edition page ?

**Comment by btry** [comment]
Also, check in the browser if you have JS errors when you click on the "add section" or "add question" link

**Comment by Azgar1998** [comment]
Hello btry,

Thank you for your reply.
i refrech my browser but still not

But in my  browser console, i have js error when i click the button "+ Add section":

Uncaught ReferenceError: glpi_ajax_dialog is not defined
    showSectionForm http://glpi-address/plugins/formcreator/js/scripts.js?v=7358cf5b43f03ddd7dfa3587a10ce0063a43b37e:978
    onclick http://glpi-address/plugins/formcreator/front/form.form.php?id=1#:1

**Comment by btry** [comment]
glpi_ajax_dialog is a JS function provided by GLPI itself. 

Could you check in the developer tools  if the file glpi/js/glpi_dialog.js has been loaded ?

![image](https://user-images.githubusercontent.com/14139801/223725019-ad8856ae-fafa-4a7a-a039-3bcabc7dee2d.png)

**Comment by Azgar1998** [comment]
i think it is loaded but not for formcreator plugin
![glpi](https://user-images.githubusercontent.com/87006849/223727931-748fe4ef-28fa-46e4-84e8-28aea5c6a4ed.png)

**Comment by btry** [comment]
The file is listed here then the functions it contains should be available.

Please type in the JS console `glpi_ajax_dialog` (without parentheses). The console should return a function object.

![image](https://user-images.githubusercontent.com/14139801/223728671-11b79e78-f449-4185-b742-a04f17733688.png)

**Comment by Azgar1998** [comment]
how do you do that?

**Comment by btry** [comment]
In the developers tools of the browser. In the bottom of the browser tools you should see a console. If not, press the `ESC` key to toggle it.


![image](https://user-images.githubusercontent.com/14139801/223730337-23ce7b6d-94a5-4d92-a073-f669358026a3.png)

**Comment by Azgar1998** [comment]
I can't make changes
![glpi_ajax](https://user-images.githubusercontent.com/87006849/223732829-11505a9d-21cc-41bd-abe5-0da2f9d9e1e6.png)

**Comment by btry** [comment]
Your attempt shows that the function is indeed missing. Click on the file `glpi_diaglog.js` in the treeview. The content of the file should show on the right part of the developer tools window.

Press `Ctrl+F` then type `glpi_ajax_dialog`. It is expected that you find 1 occurrence if the function name.

![image](https://user-images.githubusercontent.com/14139801/223735843-c8e65b93-7293-46cc-9147-0cc43f993de2.png)

**Comment by btry** [comment]
I forgot 1 important thing.  Your version of the file is minified (most of spaces and new line characters are removed). You will find 2 curly braces below the rectangle of the step 2 of the above screenshot. Click on it ans the browser will restore a human readable formatting.

**Comment by Azgar1998** [comment]
I feel like it's empty
![glpi_empty](https://user-images.githubusercontent.com/87006849/223738855-3404c779-fb00-4c74-adb8-0dbd4ff4f34a.png)

**Comment by btry** [comment]
select the tab 'Réseau' then refresh the web page. You will see all HTTP requests done when loading the page. 

In the filter, type `glpi_dialog` to filter the requests.  line must still be visible in the list. Check the HTTP status of the response. It should be 200. If not, there is a problem here.
![image](https://user-images.githubusercontent.com/14139801/223739740-12a36f2b-1ac4-4c09-a318-d6cf8c30c629.png)

If the status is 200, then you should maybe check that the file is not damaged in the filesystem.

**Comment by Azgar1998** [comment]
I set up a test server (new installation) nearby, indeed "glpi_dialog..." does return code but not glpi which is in production.

**Comment by Azgar1998** [comment]
the status is 301:

![image](https://user-images.githubusercontent.com/87006849/223741580-5672f6ad-f408-48a4-94b6-e3778254790f.png)

**Comment by btry** [comment]
I'm suspecting that the file is still  cached by the browser. Notice the mention `(disk cache)`. Press F5 again to see if it helps.

**Comment by Azgar1998** [comment]
the 301 status is the redirect if I'm not mistaken.

When we changed server, the address changed from "http://glpi-adress/glpi" to "http://glpi-address/

could the problem be related? there is perhaps an element to modify in the database?

**Comment by Azgar1998** [comment]
it's still the same after f5

![image](https://user-images.githubusercontent.com/87006849/223743624-7b896a75-ad1c-4562-8fa8-918ce0d2f940.png)

**Comment by Azgar1998** [comment]
where can i look at the api url?

**Comment by btry** [comment]
My bad. The API url is in an other Tab

![image](https://user-images.githubusercontent.com/14139801/223744860-0b55b9a9-86e1-4ec8-8c7d-7de6905a96cc.png)

**Comment by Azgar1998** [comment]
I changed the address but I'm still in the same situation
![image](https://user-images.githubusercontent.com/87006849/223749496-0491be21-14d0-4e74-8fd9-042712257a0a.png)
![image](https://user-images.githubusercontent.com/87006849/223749665-6a822d46-540a-4b68-bc2b-39b0a2f4ba9f.png)

**Comment by Azgar1998** [comment]
i have new element in browser console: error syntax on glpi_dialog.min.js
![image](https://user-images.githubusercontent.com/87006849/223759708-e4a57998-3b79-412d-8d49-c9a5cb5e4a0c.png)

**Comment by btry** [comment]
It looks like a regular html page of GLPI. This file is served statically. I believe there is something specific to your http server, causing bad content. 

This is out of scope of Formcreator, then I suggest you investigate and/or get help from community, in GLPI forum.

**Comment by btry** [comment]
> i have new element in browser console: error syntax on glpi_dialog.min.js

This is normal if the browser tried to interpret JS code when the actual content is HTML.

**Comment by btry** [comment]
Hi

Having no feedback (did you get help from the community ?), I close.
