### ISSUE TITLE
Fields unicity and Plugin Additional fields

### ISSUE THREAD

**Issue by calidadcarm** [pluginsGLPI/formcreator#3216]
**Describe the solution you'd like**

Include in the Fields unicity of an object, fields of the plugin additional fields:

**Additional field on Computer:**

![imagen](https://user-images.githubusercontent.com/50906293/227496624-93891038-ea7c-46a8-b259-a16146924eb0.png)

**Fields unicity on Computer:** 

**We can't add the field 'Nombre máquina virtual' like Fields unicity.**

![imagen](https://user-images.githubusercontent.com/50906293/227496864-efb62352-409f-43d6-b860-54dda55f053d.png)

In such a way that even though these fields reside in different tables from the behavior in the GLPI interface they behave as if they were fields of the same table.

**Comment by calidadcarm** [comment]
this is not the channel to propose this idea

**Comment by btry** [comment]
no. feature request or bug report to the plugin Fields should be  submitted here: https://github.com/pluginsGLPI/fields/issues
