### ISSUE TITLE
Coud be possible add the object Domains on Fields unicity

### ISSUE THREAD

**Issue by calidadcarm** [pluginsGLPI/formcreator#3217]
**Add Domains on Fields unicity**

![imagen](https://user-images.githubusercontent.com/50906293/227500438-f642cc45-bb71-4c68-b5d2-36dcced7729a.png)

**Fields unicity can't add Domains**

![imagen](https://user-images.githubusercontent.com/50906293/227500667-c354ea8f-82bb-4d08-92c4-586980ebbd0e.png)

**Comment by btry** [comment]
Hi

This not related to Formcreator, am I right?

**Comment by calidadcarm** [comment]
this is not the channel to propose this idea

**Comment by btry** [comment]
Yes, follow the link I provided to you in the other issue you just closed.
