### ISSUE TITLE
Additional gaps between lines appeared in the "radios" form element

### ISSUE THREAD

**Issue by tovich** [pluginsGLPI/formcreator#3219]
**Describe the bug**
Additional gaps between lines appeared in the "radios" form element, they were not in the previous version.

**To Reproduce**
1. Go to 'Administration'
2. Go to 'Forms'
3. Select any forms or add new
4. Add questions 'Radios'
5. Click on 'Preview'
6. There are extra empty lines between the selection lines of the "Radios" element.

**Expected behavior**
There should be no empty lines between the selection lines of the "radios" element.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/23525927/228155950-1ad3f759-fa51-475b-85a4-60625fc9b61d.png)
![изображение](https://user-images.githubusercontent.com/23525927/228156158-be7752ab-f588-446d-9efd-d28944cbd7f8.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.6
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
Install Method: Marketplace
telegrambot          Name: TelegramBot                    Version: 3.0        State: Not installed                           
Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 111.0.1, Edge 111.0.1661.54

**Comment by btry** [comment]
Hi

This has been done to distinguish items with too long content. Look how a it looked in 2.13.4

![image](https://user-images.githubusercontent.com/14139801/228158341-1f72f914-412f-4fa2-a103-42eb8d121358.png)

It looks better in 2.13.5
![image](https://user-images.githubusercontent.com/14139801/228158542-4c3c7e6f-3588-486c-865e-d6937487c234.png)

By the way, the same change has been done for checkboxes.
