### ISSUE TITLE
schedule a form with ticket creation

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#322]
Hello,

I would like to know how to schedule a form creation with ticket creation through recurrent ticket ?

I have created a form with destination ticket 
I have created a ticket template "account deletion checklist"
I have create a recurrent ticket with date of opening and using account deletion checklist template

But when the ticket is created it is empty.

Do you have a solution please ?

Thank you for your help

**Comment by btry** [comment]
Hi

The plugin does not support recurrent form or recurrent ticket so far. As this issue is very old I close. If you still need to support recursion, please open a new issue with a use case.
