### ISSUE TITLE
User ID is shown in requester not the full name

### ISSUE THREAD

**Issue by iDazai** [pluginsGLPI/formcreator#3221]
**Describe the bug**
Maybe only a setting problem, not a bug.

After upgrading from 0.90 with Formcreator 2.4.2 to 10.0.6 with Formcreator 2.13.5 we have this minor bug that in the form directly with the url _/plugins/formcreator/front/formanswer.form.php?id=_ the name of the requester is shown with their user ID and not with their full name. Their full name is only shown on the broader overview of the forms with the url _/plugins/formcreator/front/formanswer.php_
Is it only a setting which we have to change or something in the database? The db has no inconsistencies with the formcreator tables.
This problem persisted through every GLPI version after 0.90 and the latest possible version of formcreator.

**Expected behavior**
In GLPI 0.90 with Formcreator 2.4.2 the full names were shown.

**Screenshots**
![form1](https://user-images.githubusercontent.com/50296346/228216599-31636b99-cbb2-49d7-b8f1-973d3dd686f3.png)
![form2](https://user-images.githubusercontent.com/50296346/228216608-15c859b6-7033-46a9-8a69-1a7a4584d3d5.png)

GLPI / Plugins (please complete the following information):

    GLPI version 10.0.6
    Formcreator 2.13.5

**Additional context**
Also when adding new users in a form as a validator, I only see their user ID and not their full name.

**Comment by iDazai** [comment]
bumping. Any news on that? Is that a bug or a configuration we need to do?

**Comment by iDazai** [comment]
Still happens, even in the latest Formcreator version. Checked settings but can't seem to find anything about that. No help here...

**Comment by btry** [comment]
Hi

I tried to reproduce : 
- create a new form with a question of type GLPI Object / User.
- Fill the form in preview mode then submit. A use has been selected
- Display the form answer from the tab "Form Answers"
- I have the name of the user, as expected

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/055ced7d-bccc-40d2-8968-6bbbb17c0465)

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/033ace7b-1daa-4977-81da-bd64cd255920)

Please tell me if I tried to reproduce the right way . Tell also if the user still exists in the database (ID 68 in your screenshots).

**Comment by iDazai** [comment]
Hi, thanks for your input.
So I created a new form, with a _GLPI Object_ of type _User_, filled out the form with my user in preview mode and submitted it. I'm in the _Form Answers_ section and see the User ID of myself, but not my full name.
Speaking in database coloumn names. The _name_ of the table _glpi_users_ is shown, not the _realname_, _firstname_ which was the case in our old GLPI + Formcreator setup.
Current Setup is GLPI 10.0.9 with Formcreator 2.13.7

**Comment by iDazai** [comment]
@btry Is this intended behaviour since a certain version, or is it a setting we have to change?

**Comment by btry** [comment]
Hi

There is no setting for this. The plugin shows the login (the column name in the table glpi_users). It is possible to show name + first name and last name with a patch

**Comment by iDazai** [comment]
Okay, so you could see this thread as a feature request then. I guess other users would like this feature as well. Maybe realize it as a dropdown or whatever is the best fit for that.
This feature was definitely standard when we had GLPI 0.90 and Formcreator 2.4.2

**Comment by btry** [comment]
Indeed: https://github.com/pluginsGLPI/formcreator/blob/2.4.2/inc/fields/dropdown-field.class.php#L41

**Comment by btry** [comment]
Hi

Could you try this PR and feedback ?

**Comment by btry** [comment]
Hi

You did not applied the patch properly. By replacing files like you did you may introduce other changes which may depend on other files that you did not updated. This may break the plugin and GLPI. You must use the [patch tool](https://www.man7.org/linux/man-pages/man1/patch.1.html) to apply a fix properly.

**Comment by btry** [comment]
I added tests, to confirm it works as expected. If the user does not have any name, the login is displayed. If the user has firstname and realname, then they are used for display.

**Comment by iDazai** [comment]
Sorry, I don't have time to dive into the patch tool.
If it works on your site, then it's fine by me and I'll just wait for the new version. You can deem this issue as closed if you want.

**Comment by btry** [comment]
Ok, Manual test and unit test are ok for me. The fix has been merged, I expect the next version to be released soon.
