### ISSUE TITLE
How to hide "See all"

### ISSUE THREAD

**Issue by fernandoabrito** [pluginsGLPI/formcreator#3224]
Is there any way to hide the "See all" from the simplified forms menu? Example how it is done with the search in the newest version.

![image](https://user-images.githubusercontent.com/29784835/228396411-82b352bd-bff1-492a-a797-b451aa19467c.png)

Wouldn't you put an option to configure this feature? This would be of great help in limiting basic users. Forcing them to enter the correct session and see the services available to it. This avoids launching wrong forms such as a query form that can be repeated in a few sessions. I'm sorry but I believe that this action greatly improves the end user experience and would help to receive calls correctly.

![image](https://user-images.githubusercontent.com/29784835/229115033-059bffc0-0560-4e24-9dc4-9956a5abd2a8.png)

Example:

![image](https://user-images.githubusercontent.com/29784835/229115633-c937cb70-ae80-4cc0-8ffc-9bae6770d1c7.png)

![image](https://user-images.githubusercontent.com/29784835/229116117-cf5d7cff-0599-4dba-a894-84e1924e3f19.png)

**Comment by btry** [comment]
Hi

It is not planned to add an option. You may disable this by commenting [this line](https://github.com/pluginsGLPI/formcreator/blob/support/2.13.0/inc/form.class.php#L651)

**Comment by fernandoabrito** [comment]
> Hi
> 
> It is not planned to add an option. You may disable this by commenting [this line](https://github.com/pluginsGLPI/formcreator/blob/support/2.13.0/inc/form.class.php#L651)

Wow thank you so much for your help indeed hid the menu. However, it still continues to load the "See all" screen as the loading pattern. is it possible to change it? Or leave a blank? The idea is to force the user to go to the right area to open the ticket.

![image](https://user-images.githubusercontent.com/29784835/231490545-ce4645bd-2e3c-45f2-82e6-296f031590c0.png)

**Comment by btry** [comment]
Hi

Disable the following line

https://github.com/pluginsGLPI/formcreator/blob/2.13.5/js/scripts.js#L216

**Comment by fernandoabrito** [comment]
> Hi
> 
> Disable the following line
> 
> https://github.com/pluginsGLPI/formcreator/blob/2.13.5/js/scripts.js#L216

Weirdly tried this. I commented the line and even removed it and nothing. I cleared the cache, restarted the apache service and even then it reloads "See All"

**Comment by btry** [comment]
Hi

Re enable the line and apply the following patch.

```diff
diff --git a/inc/form.class.php b/inc/form.class.php
index 1edf569ac..93e186b8c 100644
--- a/inc/form.class.php
+++ b/inc/form.class.php
@@ -687,9 +687,9 @@ PluginFormcreatorTranslatableInterface
       echo '</div>';
       echo '</div>';
       echo '</div>';
-      echo Html::scriptblock("$(function() {
-         plugin_formcreator.updateWizardFormsView();
-      });");
+      // echo Html::scriptblock("$(function() {
+      //    plugin_formcreator.updateWizardFormsView();
+      // });");
    }
 
    /**
```

**Comment by fernandoabrito** [comment]
> 

Thank you very much for your effort, but I'm bothering you again. I applied it but this way it does not load the categories now

![image](https://user-images.githubusercontent.com/29784835/232495022-5db7f72d-21f7-497a-9afe-90ec5c68bbac.png)

**Comment by fernandoabrito** [comment]
Por favor alguém poderia me ajudar a colocar essa opção que quando carregar todos formulários não aparecer todos os formulários e sim uma pagina em branco? Isso atrapalha muito o usuário a identificar o formulário correto dentro da categoria correta. Posso ter cadastros em mais uma categoria. Me mostrar uma forma melhor de estruturar isso para que evite erro do usuário em clicar no formulário errado fora da categoria.
