### ISSUE TITLE
The database schema is not consistent with the previous version of Formcreator 2.13.4

### ISSUE THREAD

**Issue by kekobrai** [pluginsGLPI/formcreator#3233]
Hi,
When I want to install formcreator I get this error:

![image](https://user-images.githubusercontent.com/55870022/229310153-f6dec222-7ce4-4c38-b41f-f9cdf4737e22.png)

I do what the message tells me and the following appears

![image](https://user-images.githubusercontent.com/55870022/229310226-d2d59e66-449e-4cba-99d8-2be5cb740ce3.png)

Then I do the skip thing and I get the following.
![image](https://user-images.githubusercontent.com/55870022/229310265-3372f062-3eb7-4cbe-b8b2-5c682d4b1c89.png)

Anyone know what might be happening?

**Comment by btry** [comment]
Hi

The plugin detected that something is wrong In your tables. You may skip the check only if you diagnosed that the errors are minor.

In your case, there is a major problem : a table is missing. This type of error may impact the upgrade process, and for sure, your plugin installation was broken before the upgrade.

You should check how are damaged / missing tables in  the backup you took before trying to upgrade (I assume you did it). Next find how to fix those problems.

Once all problems are fixed, you may try to upgrade.

Remember : the plugin implements a DB check on purpose. Don't try to skip it without a good reason and analysis of the problems.

**Comment by kekobrai** [comment]
> Hi
> 
> The plugin detected that something is wrong In your tables. You may skip the check only if you diagnosed that the errors are minor.
> 
> In your case, there is a major problem : a table is missing. This type of error may impact the upgrade process, and for sure, your plugin installation was broken before the upgrade.
> 
> You should check how are damaged / missing tables in the backup you took before trying to upgrade (I assume you did it). Next find how to fix those problems.
> 
> Once all problems are fixed, you may try to upgrade.
> 
> Remember : the plugin implements a DB check on purpose. Don't try to skip it without a good reason and analysis of the problems.

The truth is that I did not make any backup copies, since the plugin was there for months without using it, I never used it, I just tried to update it since now I wanted to use it and said error appeared. Is there a way to delete everything related to formcreator including the database and plugin and install everything from 0.?

**Comment by btry** [comment]
Backup the whole database.

Delete all tables having a name beginning with glpi_plugin_formcreator_

Next run the following query

Delete from glpi_configs where context='formcreator'

Run the installation process of the plugin. It should run smoothly.

**Comment by kekobrai** [comment]
> Backup the whole database.
> 
> Delete all tables having a name beginning with glpi_plugin_formcreator_
> 
> Next run the following query
> 
> Delete from glpi_configs where context='formcreator'
> 
> Run the installation process of the plugin. It should run smoothly.


Thank you very much for all your help, it worked. I close as solved!
