### ISSUE TITLE
Add "Public RSS feeds" and "Public reminders"

### ISSUE THREAD

**Issue by Unknoweb** [pluginsGLPI/formcreator#3239]
Hi,

we would like to switch completely to FormCreator but we use these 2 "RSS" and "Reminders" options a lot if we can have them we would completely switch to the interface (Service catalog simplified)

put them in the "My requests for assistance" menu that would be good i think

![FormCreator_Feature](https://user-images.githubusercontent.com/128051761/229606498-59323a72-b938-40c3-ac07-db186b4cd7d6.jpg)

I started with "Feature request" but no label :( sorry

**Comment by btry** [comment]
Hi

Rss and reminders seems  very rarely used (nearly no bug report of proof that anyone use them with Formcreator)

Rss is supported, I have to check about reminders.

**Comment by Unknoweb** [comment]
> Hi
> 
> Rss and reminders seems very rarely used (nearly no bug report of proof that anyone use them with Formcreator)
> 
> Rss is supported, I have to check about reminders.

I see and I understand but know that we use them a lot, we make an exception to the rule lol

Indeed the RSS is taken into account I had not seen the banner. So RSS ok is missing more than the reminders:) . If the reminders are displayed like the RSS it will do

**Comment by Unknoweb** [comment]
I added "reminder" and work fine exept is always display

in common.class.php I added this code before "RSSFeeds"

```
$reminderTable = Reminder::getTable();
      $criteria = [
         'SELECT'   => "$reminderTable.*",
         'DISTINCT' => true,
         'FROM'     => $reminderTable,
         'ORDER'    => "$reminderTable.name"
      ];
      $criteria = $criteria + Reminder::getVisibilityCriteria();
      $criteria['WHERE']["$reminderTable.users_id"] = ['<>', Session::getLoginUserID()];
      $iterator = $DB->request($criteria);
      $hasReminder = $iterator->count() > 0;

	  if (Reminder::canView() && $hasReminder) {
         $newMenu['reminders'] = [
            'default' => Plugin::getWebDir('formcreator', false) . '/front/wizardreminders.php',
            'title'   => __('Consult reminders', 'formcreator'),
            'icon'    => 'fa fa-sticky-note',
         ];
      }

```
and I create file "wizardreminders.php" with this code

```
global $CFG_GLPI;
include ("../../../inc/includes.php");

// Check if plugin is activated...
if (!(new Plugin())->isActivated('formcreator')) {
   Html::displayNotFoundError();
}

if (! plugin_formcreator_replaceHelpdesk()) {
   Html::redirect($CFG_GLPI['root_doc']."/front/helpdesk.public.php");
}

if (!Reminder::canView()) {
   Html::displayRightError();
}

if (Session::getCurrentInterface() == "helpdesk") {
   Html::helpHeader(__('Service catalog', 'formcreator'));
} else {
   Html::header(__('Service catalog', 'formcreator'));
}

Reminder::showListForCentral(false);

if (Session::getCurrentInterface() == "helpdesk") {
   Html::helpFooter();
} else {
   Html::footer();
}
```

I think I wrong in this part of code

```
$criteria = $criteria + Reminder::getVisibilityCriteria();
      $criteria['WHERE']["$reminderTable.users_id"] = ['<>', Session::getLoginUserID()];
      $iterator = $DB->request($criteria);
      $hasReminder = $iterator->count() > 0;
```

**Comment by btry** [comment]
Hi

You should create a pull request. This is more efficient to review your code and merge it.

Create a fork of the plugin, then create a branch based onto support/2.13.0. add your changes, and submit a pull request.

**Comment by Unknoweb** [comment]
> Hi
> 
> You should create a pull request. This is more efficient to review your code and merge it.
> 
> Create a fork of the plugin, then create a branch based onto support/2.13.0. add your changes, and submit a pull request.

Yes I just send PullRequest

And for my problem it's ok The code work fine. the problem came from the database

**Comment by Unknoweb** [comment]
You can close issue

**Comment by btry** [comment]
Hi, OK; I close this issue. I'll test the PR soon
