### ISSUE TITLE
Bug when translate and save

### ISSUE THREAD

**Issue by Unknoweb** [pluginsGLPI/formcreator#3243]
Bonjour,
Désolé je vais parler Français pour bien vous décrire le BUG

Lorsqu'on traduit un formulaire en Anglais par exemple et bien quand on arrive au niveau de la description donc "Zone de texte" on a ça et impossible de l'agrandir en large uniquement en hauteur donc on a pas toutes les options mais on peut enregistrer et le re-éditer et la c'est bon

![1](https://user-images.githubusercontent.com/128051761/230478398-c8b43b9a-ad09-455b-8d40-4ee2118458bb.jpg)

Ensuite quand on édite et qu'on laisse le popup ouvert comme ça et qu'on enregistre

![2](https://user-images.githubusercontent.com/128051761/230478878-4aa33363-0c15-46aa-b1c0-9b61d3063993.jpg)

Et bien on a ça lors de l'enregistrement il apparait ce n'est pas gênant il suffit de quitter et revenir mais je voulais quand même vous le signaler

![3](https://user-images.githubusercontent.com/128051761/230479118-3f90c7bf-77c6-4895-aabf-8ec5f8226bdc.jpg)

**Comment by btry** [comment]
Bonjour

Essayez le patch ci dessus; il devrait résoudre le souci au moment de créer une traduction pour une description.  Je n'ai pas  encore regardé pour le second problème; mais il est possible que patch ait un effet positif.

**Comment by Unknoweb** [comment]
Bonjour,

Premier problème résolu :) le second est toujours présent 

Comme dis ce n'est pas majeur comme le premier mais a réglé plus tard 

En tout cas merci

**Comment by btry** [comment]
Bonjour

Pour le second problème, utilisez ce fix: https://github.com/pluginsGLPI/formcreator/commit/ba97c84274df136c56ae3ae5734a7dbbb68de658

Il est déjà prêt pour la prochaine release.
