### ISSUE TITLE
BUG in edit description form with GLPI 10.0.7

### ISSUE THREAD

**Issue by Unknoweb** [pluginsGLPI/formcreator#3248]
Update GLPI 10.0.6 to 10.0.7 and look the Edit Bar is missing

![4](https://user-images.githubusercontent.com/128051761/230717358-c9908207-fa5e-4912-9ece-40b4520b31c0.jpg)

**Comment by btry** [comment]
Hi

What happens if you do a right click in the textarea? 

Show a screen of the contextual menu. Is it a menu which belongs to the navigator, or a contextual menu related to the rich editor?

**Comment by Unknoweb** [comment]
right click in the textarea

![5](https://user-images.githubusercontent.com/128051761/230720522-31b7a8a5-9c12-41b5-945c-b3405e09c017.jpg)

I use this technique to continue my forms :)

**Comment by Unknoweb** [comment]
Bon je continue en Français c'est plus simple pour moi

avant de te prendre la tête a regarder le Pourquoi je viens de tester sous xampp windows et j'ai aucun soucis avec une fresh install il fonctionne très bien

Le soucis est survenue sous linux debian 11 "fresh install" mysql 8 et php 8.2.4 donc laisse moi creuser un peut car c'est bizarre cette histoire

**Comment by btry** [comment]
Regardez les préférences utilisateur. Il y a un réglage introduit vers glpi 10.4 qui permet de choisir entre une barre d'outils ou un menu contextuel. 

Je n'ai pas en tête le comportement de GLPI concernant la valeur par défaut après une install fraîche VS la valeur qu'à d on upgrade depuis une version antérieure à l'apparition de ce réglage. Cela peut expliquer vos différences entre instances.

**Comment by Unknoweb** [comment]
oui effectivement l'option "Disposition des champs de texte riche" s'est mis sur "intégré (sans barre d'outils)" je les remis sur "classique (barre d'outils en haut)" merci de l'info tu peux clôturer l'issue
