### ISSUE TITLE
With GLPI 10.0.7 - Invalid argument at line 55

### ISSUE THREAD

**Issue by WebGregGit** [pluginsGLPI/formcreator#3251]
**Version**
GLPI:  10.0.7
Formcreator: 2.13.5

**Bug description**
When I add a new question and select the type e.g. checkboxes, multiselect I get:

PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/glpi/marketplace/formcreator/inc/field/checkboxesfield.class.php at line 55

**Steps To reproduce**
1. Enable the debug mode
2. Create the new form.
3. Add new question
4. Change the type field to checkboxes

**Related logs**
[2023-04-12 14:10:29] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/glpi/marketplace/formcreator/inc/field/checkboxesfield.class.php at line 55
  Backtrace :
  marketplace/formcreator/inc/question.class.php:744 GlpiPlugin\Formcreator\Field\CheckboxesField->showForm()
  ...etplace/formcreator/ajax/question_design.php:73 PluginFormcreatorQuestion->showForm()
  public/index.php:73                                require()

**Screenshots**
![image](https://user-images.githubusercontent.com/68922721/231505562-ea6ed50f-07d2-430c-b73d-8fa4f955c827.png)

**Comment by btry** [comment]
Fixed with: 342c39e9f
