### ISSUE TITLE
Sort as decimal from glpi_plugin_formcreator_answers table

### ISSUE THREAD

**Issue by leecheromerevilit** [pluginsGLPI/formcreator#3254]
I've added an additional column on the table view of submitted forms which is price (decimal datatype)

Since answer column on glpi_plugin_formcreator_answers table is LONGTEXT, sorting the price table will not lead to the desired result. 

Sample Result:
11
1100
2
24

Desired Result
2
11
24
1100

Is there a way I can convert string to decimal on rawSearchOptions?

**Comment by btry** [comment]
Hi

I did not find anything in GLPI (class Search) to handle decimal numbers when sorting data. I think you will need to write a patch; have a look into Search::addOrderBy

Also, if not already done, set the key 'datatype' of your search option as 'decimal' ([see here](https://glpi-developer-documentation.readthedocs.io/en/master/devapi/search.html#data-types))

**Comment by btry** [comment]
Hi

I have an other idea for you. You may store your price as an integer, by multipying the price by 100 in prepareInoutForAdd() and PrepareInputForUpdate() , then use getSpecificValueToDisplay() in the appropriate class to divide the value by 100 before displaying it. 

This way, you workaround the sorting limitation on decimal values easily.
