### ISSUE TITLE
Checkbox checked condition

### ISSUE THREAD

**Issue by sebastianSanchez23** [pluginsGLPI/formcreator#3257]
**Is your feature request related to a problem? Please describe.**
I'm just starting to use the plug in and for this form I need to check certain checkboxes if  a dropdown choice is selected, so it's more of a feature request.
**Describe the solution you'd like**
I'd like to know if it's possible to add a functionaly like condition to show the question, except for the checkboxes a section called "Condition to check the question automatically" 

Thanks for all the help ! :-)

**Comment by btry** [comment]
Hi

I think I don"t understand properly your request.

Do you want to disable conditions when some section has a specific name ?

**Comment by sebastianSanchez23** [comment]
Hi,
Oh no, actually it's more like if the user selects "option 1" on a dropdown, the checkbox A and B get checked automatically, think of it like an event in Javascript, don't know if it's more clear ?

**Comment by btry** [comment]
I understand.

The plugin does not supports the ability to modify fields when other fields are modified. Maybe you can mimic this behaviour by hiding a question of type checkboxes with pre-checked options A and B. Add on this checkboxes question a condition to show only if the question of type Dropdown has a specific value.

**Comment by sebastianSanchez23** [comment]
Great thank you very much for your time !

**Comment by btry** [comment]
Hi

You're welcome.
