### ISSUE TITLE
The form's search bar does not appear 

### ISSUE THREAD

**Issue by alekyxander** [pluginsGLPI/formcreator#3260]
The form's search bar does not appear in GLPI version 10.0.7, how can I enable it?
![image](https://user-images.githubusercontent.com/46962468/232786921-f097de65-b226-444f-a16f-066a934d4c6d.png)

![image](https://user-images.githubusercontent.com/46962468/232787499-74be991c-42cd-4af9-a3f7-bc4f48aa6440.png)

**Comment by btry** [comment]
Hi

Check the settings of your entity, tab "Formcreator".

**Comment by alekyxander** [comment]
Resolvido, Obrigado!
