### ISSUE TITLE
Maximum file size 

### ISSUE THREAD

**Issue by kekobrai** [pluginsGLPI/formcreator#3262]
Hello, I want to upload the maximum file size to 5mb in the attached files, I tried to upload the upload_max_filesize from PHP.INI but it doesn't work for me. Please can you help me

![image](https://user-images.githubusercontent.com/55870022/233680167-2e43d5c7-9c51-488b-82bc-2d72301ef5cb.png)

![image](https://user-images.githubusercontent.com/55870022/233680603-72c57a52-34d2-4e47-83d2-cffab45903b1.png)

Thanks.

**Comment by kekobrai** [comment]
> Hi
> 
> This place is dedicated to plugin maintenance. Your question is related to server configuration, then please, use the community forum https://forum.glpi-project.org/login.php

Hi, I ask the question here because I thought it could be something directly from FormCreator since when I change the php.ini in apache it does not change in formcreator, so I assimilate that it is not an apache problem but perhaps the plugin.

**Comment by btry** [comment]
Formcreator does not limits the allowed size of uploads.

**Comment by btry** [comment]
Hi

As Formcreator does not anything regarding upload size limitation, I close this issue.
