### ISSUE TITLE
Envoi de notifications impossible

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [pluginsGLPI/formcreator#3270]
**Describe the bug**
Lors de la création d'un ticket depuis le formulaire prévu, l'utilisateur ne reçoit pas de mail, alors que dans les paramètres de la cible du formulaire j'ai bien ceci : 
![image](https://user-images.githubusercontent.com/91662361/235923622-4ebe89f9-430a-4eb6-acd7-bf1c21efe264.png)

De plus dans la file d'attente des notifications de GLPI, j'ai l'ID du créateur du document qui apparait et pas son adresse mail : 
![image](https://user-images.githubusercontent.com/91662361/235923972-da43fcca-1878-4506-b735-6e276813f05f.png)

**To Reproduce**
1. Je fait une demande depuis le formulaire avec le compte de test (ID=27)
![image](https://user-images.githubusercontent.com/91662361/235925015-ff61e745-1748-4591-a8ae-1c08fd5bdfba.png)

2. Je me rends dans la file d'attente des notifications et je me rends compte que le mail est adressé non pas à une adresse mail mais à l'ID 27:
![image](https://user-images.githubusercontent.com/91662361/235925450-40517632-c307-441c-8fb1-7cec46b9f607.png)

3. Comment je peux faire pour que l'utilisateur qui crée sont ticket reçoive bien le mail de création.

Je veux que à la place du numéro 27, j'ai sont adresse mail. 

**GLPI / Plugins (please complete the following information):**
- GLPI version : 10.0.7
- list of all plugins : 
addressing           Name: Adressage IP                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertes                        Version: 1.10.6     State: Enabled                                 
		Install Method: Marketplace
	treeview             Name: Arborescence                   Version: 1.10.0     State: Enabled                                 
		Install Method: Manual
	financialreports     Name: Arrêtés du parc                Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Marketplace
	camerainput          Name: Camera Input                   Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.20.5     State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	costs                Name: Costs                          Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	mydashboard          Name: Dashboard                      Version: 2.1.4      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.0     State: Enabled                                 
		Install Method: Marketplace
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                
		 Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	gdrive               Name: GDrive                         Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	geninventorynumber   Name: Génération de numéros d'invent Version: 2.8.3      State: Enabled                                
		 Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.14.2     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.10.3     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Marketplace
	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	jsaddons             Name: JS Addons                      Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	metabase             Name: Metabase                       Version: 1.3.3      State: Enabled                                 
		Install Method: Marketplace
	onetimesecret        Name: OneTimeSecret                  Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	reports              Name: Rapports                       Version: 1.16.0     State: Enabled                                 
		Install Method: Manual
	rgpdtools            Name: Utilitaires RGPD               Version: 1.0.0      State: Enabled                                 
		Install Method: Manual
	webhook              Name: Webhooks                       Version: 1.0.12     State: Enabled                                 
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 113

**Comment by btry** [comment]
Bonjour

Le fait qu'il y ait un ID à la place d'une adresse email indique qu'il a à priori un bug.

**Comment by btry** [comment]
Bonjour

Je remarque que les notifications email impactées concernent l'ajout d'un suivi. Est ce que la validation est activée sur le formulaire ?

**Comment by btry** [comment]
Ma question n'était pas pertinente : les notifications email sont désactivées quand le formulaire doit créer un suivi après validation.

Il semble donc que la notification contenant un ID à la place d'une adresse email soit générée par l'ajout d'un suivi sur un ticket. Cela se passe hors de Formcreator.

Pouvez vous vérifier quel évènement crée la notification mail en défaut ? Est-ce une action dans Formcreator ou dans GLPI ?
