### ISSUE TITLE
quotes are escaped in field [name] of [glpi_plugin_formcreator_formanswers]

### ISSUE THREAD

**Issue by MLOcc** [pluginsGLPI/formcreator#3271]
Hi, 
The name of the form having quotes is stored with backslashes in field 'name' of  'glpi_plugin_formcreator_formanswers'

![image](https://user-images.githubusercontent.com/71837011/236185046-0f39aa24-f16f-4ab4-b001-dfc074757ba5.png)
![image](https://user-images.githubusercontent.com/71837011/236185328-9882aa7f-d775-498c-a22b-87fd73d0c112.png)

**To Reproduce**
1. Set a form with quote in his name
2. Answer the form
3. Look entry created in 'glpi_plugin_formcreator_formanswers'

- GLPI version 10.0.6
- FormCreataor 2..13.5

I solve the problem by replacing 
$input['name'] = $DB->escape($this->parseTags($form->fields['formanswer_name']));
by
$input['name'] = $this->parseTags($form->fields['formanswer_name']);
on line 831 of /inc/formanswer.class.php (prepareInputForAdd function)

**Comment by btry** [comment]
Hi

Thank you for your contribution. I validated your change and pushed the following commit e518b7de1.
