### ISSUE TITLE
Functionality hint Plugin Formcreator 

### ISSUE THREAD

**Issue by calidadcarm** [pluginsGLPI/formcreator#3275]
**Describe the solution you'd like**
¿It would be possible to copy targets as it happens in questions?

![imagen](https://user-images.githubusercontent.com/50906293/237022916-3b90aa18-7cef-40a3-b7c2-cde11c257656.png)

**Comment by btry** [comment]
Hi

The feature does not exists yet.

**Comment by calidadcarm** [comment]
One question, is this functionality planned for a future version or is it not contemplated?

**Comment by btry** [comment]
Hi

Try to apply the above patch. It should allow you to duplicate a target. It also duplicates actors and conditions applied to the object being cloned.

**Comment by calidadcarm** [comment]
Suggest they put a duplicate button on the lens to make it more intuitive.

![imagen](https://github.com/pluginsGLPI/formcreator/assets/50906293/fc707923-c9cf-4b71-b0cc-b3050cc43a13)

**Comment by calidadcarm** [comment]
Thanks very much... Yes this issue is reselve.
