### ISSUE TITLE
Many ticket while pending form registration

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#3280]
Bonjour,
Ci dessous la description d'un problème lié à la création de plusieurs tickets lorsque l'utilisateur clique plusieurs fois sur le bouton de validation du formulaire pendant son enregistrement.
Merci d'avance

**Describe the bug**
When completed a form and click on "validate", while pending the registration, it takes 2 or 3 seconds and during this time you can click many time on validate and it generate as much ticket.

**Expected behavior**
Is it possible to desactivate the button once you have click on it or manage to not create many tickets?

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.6
- list of all plugins with their version
- news                 Name: Alertes                        Version: 1.10.6     State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.20.2     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.13.0     State: Enabled                                 
		Install Method: Manual
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.6+1.1 State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Manual
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [firefox]
 - Version [113.0]

**Additional context**
PHP 7.4.33
Apache/2.4.6
10.3.13-MariaDB

**Comment by btry** [comment]
Bonjour

Un fix (#3269) est déjà fait, j'attends une vanidation par le bug reporter. Essayez-le

**Comment by eckorion** [comment]
Je viens de tester le fix mais c'est toujours pareil.

**Comment by btry** [comment]
J'ai oublié de préciser que ce fix dépend d'un autre fix pour GLPI. Le lien est dans la description du fix.

Si vous avez GLPI 10.0.7, le fix requiert de régénérer un fichier .js Pour que ce soit plus simple, le voici en PJ. Il remplace glpi/js/common.min.js
[common.min.js_1007.txt](https://github.com/pluginsGLPI/formcreator/files/11461820/common.min.js_1007.txt)

**Comment by eckorion** [comment]
Je suis en 10.0.6 mais même en appliquant le 2ème fixe le problème persiste.

**Comment by btry** [comment]
J'ai bien précisé que le fichier était pour 10.0.7. Il y a eu des changements dans ce fichier entre les 2 versions. Rempalcez le fichier par cette version, et faites F5 sur la page pour forcer le rafraîchissement du cache côté navigateur (le fichier s'y trouve, ce qui peut expliquer que ça n'a pas fonctionné)

[common.min.js_1006.txt](https://github.com/pluginsGLPI/formcreator/files/11463817/common.min.js_1006.txt)

Ces fixes fonctionnent sur mon instance et j'ai un retour positif d'une autre instance de test. Un 2e retour positif me permettra de fusionner.

**Comment by btry** [comment]
Vous utilisez surement une release de GLPI (par oppositoin à une copie de développement). Par conséquent le patch pour GLPI modifie le fichier .js du code source. Dans votre cas vous avez une  version minifiée (pour optimiser les échanges HTTP). La version minifiée porte l'extension .min.js et si elle existe sur votre instance, le fichier .js (tout court) n'est pas utilisé.

Installez le fichier que j'ai fourni (prenez un backup de l'original au cas où).

**Comment by eckorion** [comment]
J'ai bien tout revérifier et remplacé le fichier min.js mais c'est toujours pareil

**Comment by btry** [comment]
Avec votre navigateur, ouvrez les outils développeur et inspectez le code source du fichier js/common.min.js. Il tient en une seule ligne; mais vous devez avoir quelque chose en bas des outils développeur pour le formater correctement.

Dans Chrome et similaires, c'est un bouton qui représente 2 accolades {}.

Une fois fait, faites Ctrl+F pour trouver la chaine ```function blockFormSubmit```. Ci dessous un aperçu de ce fichier, reformaté.

LA flèche montre la ligne qui nous intéresse. Elle commencait initialement par ```a = a.find(```; la capture ci dessous montre la version corrigée ```a = e.find(``` (a devient e)

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/aafa8195-f913-4298-9c5b-aa28cdf4f1b9)

Est ce que vous avez bien la même chose que la capture ?

**Comment by eckorion** [comment]
Oui j'ai bien ça : {a=e.find('button[name="add"]:first, button[name="update"]:first');

**Comment by eckorion** [comment]
Bien vu! C'était bien ça. Un grand merci. Du coup je valide que ça fonctionne :)
Merci encore

**Comment by eckorion** [comment]
Merci surtout pour la disponibilité et l'implication comme à chaque fois. C'est top.

**Comment by btry** [comment]
Super, merci pour le retour. Les patches seront dans la prochaine release de glpi, et la prochaine release de Formcreator.
