### ISSUE TITLE
It's not displaying the PDUs as GLPI Objects in Formcreator.

### ISSUE THREAD

**Issue by coca-mann** [pluginsGLPI/formcreator#3284]
I'm trying to create a form to request assistance for the PDUs that I have registered. However, when I create a question and select that the type will be "GLPI Object," the PDUs are not appearing in the list. I searched on Google and found that it was resolved to add PDUs to the ticket after it's opened, and I can do that. But I need to select the PDUs in the form before opening the ticket.
Here are some screenshots to demonstrate the issue.

![image](https://github.com/pluginsGLPI/formcreator/assets/35693253/6ba2d889-29f0-411a-8b5a-2479089c453f)

![image](https://github.com/pluginsGLPI/formcreator/assets/35693253/fe5e4ab5-15c0-4a25-887d-b0dce552195a)

![image](https://github.com/pluginsGLPI/formcreator/assets/35693253/735d6fdd-b567-4be4-a354-0710a1c745c1)

It should be in the Asset list.

**Comment by btry** [comment]
Hi 

Added with commit f9f2d0bf

**Comment by coca-mann** [comment]
Thank you very much. I look forward to the next plugin update.

**Comment by btry** [comment]
A release has been done a few hours ago, it includes the patch for your need.
