### ISSUE TITLE
Bug ou donnée erronée dans fichier du plugin form ?

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#3288]
Bonjour

l'export fonctionne de maniere generale sur formulaire 

sur certains je ne parviens pas à exporter : 
![image](https://github.com/pluginsGLPI/formcreator/assets/42341169/eb063147-f2bd-431f-bf1e-282590269f74)
![image](https://github.com/pluginsGLPI/formcreator/assets/42341169/595c8237-d07d-47e0-bce5-b7f50619666d)

en mode debug : 
PHP Notice (8): Undefined index: identifier in ...\inc\massiveaction.class.php at line 262
dans php-errors.log
![image](https://github.com/pluginsGLPI/formcreator/assets/42341169/5224dc37-8ecc-4da4-99d0-acbcebb61cbd)

comme je le précise sur d'autres formulaires : pas de souci.
Merci

**Comment by EC2311** [comment]
Resolu -> suppression de lignes en double dans questionranges et questionregexes.

pourquoi des lignes en double par question ? 
comment peut on les nettoyer ?
Merci

**Comment by btry** [comment]
Bonjour

Les lignes en double pour les regex ou les contraintes de nombre d'items (check boxes) sont la conséquence d'un vieux bug qui est normalement résolu. 

Il est possible d'utiliser une requête SQL pour éliminer les lignes en trop.

**Comment by btry** [comment]
Ces requêtes devraient fonctionner; je conseille de les tester au préalable (par exemple en prenant un backup des tables avant de les exécuter). On peut aussi remplacer ```DELETE``` par ```SELECT *``` pour voir ce qui sera supprimé.

```sql
DELETE FROM glpi_plugin_formcreator_questionranges WHERE id NOT IN (
    SELECT * from (
        SELECT MIN(id)
        FROM glpi_plugin_formcreator_questionranges
        GROUP BY plugin_formcreator_questions_id
        )  tmp
    )
```

```sql
DELETE FROM glpi_plugin_formcreator_questionregexes WHERE id NOT IN (
    SELECT * from (
        SELECT MIN(id)
        FROM glpi_plugin_formcreator_questionregexes
        GROUP BY plugin_formcreator_questions_id
        )  tmp
    )
```
