### ISSUE TITLE
There are no more mandatory option in additional fields 2.13.6

### ISSUE THREAD

**Issue by Gambware** [pluginsGLPI/formcreator#3295]
**Describe the bug**
After update from 2.13.5 to 2.13.6 all fields that are from additional fields plugin is not showing Mandatory option. 

**To Reproduce**
Create a new form 
On type, choose the option "Additional Fields"
There is no mandataory option to select for this field.

**Expected behavior**
They should still showing mandatatory option

**Screenshots**
Others filed like data is showing mandatory option
![image](https://github.com/pluginsGLPI/formcreator/assets/24397740/c643473f-2f47-4bf6-8956-45b6c625978f)

But Addtional Fields no
![image](https://github.com/pluginsGLPI/formcreator/assets/24397740/5e655322-cb30-479f-aaaf-b8f84c16d071)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.7 / Formcreator 13.2.6
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
actualtime           Name: ActualTime                     Version: 2.1.0      State: Enabled                                 
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.10.6     State: Installed / not activated               
		Install Method: Marketplace
	chatcorp             Name: API Chat Corp                  Version: 1.5.6      State: Enabled                                 
		Install Method: Manual
	barcode              Name: Barcode                        Version: 2.7.1      State: Installed / not activated               
		Install Method: Marketplace
	fields               Name: Campos adicionais              Version: 1.20.6     State: Enabled                                 
		Install Method: Marketplace
	screenshot           Name: Captura de tela                Version: 2.0.2      State: Installed / not activated               
		Install Method: Marketplace
	credit               Name: Cargas de crédito              Version: 1.11.3     State: Installed / not activated               
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	accounts             Name: Contas                         Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	dividirdropdown      Name: Dividir Dropdown               Version: 1.0.0      State: Installed / not activated               
		Install Method: Manual
	escalade             Name: Escalonamento                  Version: 2.8.2      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.1     State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Importação de dados            Version: 2.13.1     State: Enabled                                 
		Install Method: Marketplace
	iframe               Name: Inline Frame                   Version: 1.1.2      State: Error / to clean                        
		Install Method: Manual
	releases             Name: Liberações                     Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.1   State: Enabled                                 
		Install Method: Marketplace
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	mailbehaviours       Name: Mail Behaviours                Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	moreticket           Name: Mais Chamados                  Version: 1.7.1      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: Mais Relatórios                Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	satisfaction         Name: Mais satisfação                Version: 1.6.1      State: Enabled                                 
		Install Method: Marketplace
	metabase             Name: Metabase                       Version: 1.3.2      State: Installed / not activated               
		Install Method: Marketplace
	mydashboard          Name: Meu Painel                     Version: 2.1.4      State: Installed / not activated               
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Manual
	dashboard            Name: Painel                         Version: 1.0.3      State: Enabled                                 
		Install Method: Manual
	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Installed / not activated               
		Install Method: Manual
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	reports              Name: Relatórios                     Version: 1.16.0     State: Enabled                                 
		Install Method: Manual
	singlesignon         Name: Single Sign-on                 Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	splitdropdown        Name: Split dropdown                 Version: 1.0.0      State: Not installed                           
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.11.1     State: Installed / not activated               
		Install Method: Marketplace
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	vip                  Name: VIP                            Version: 1.8.2      State: Installed / not activated               
		Install Method: Marketplace
	webhook              Name: Webhooks                       Version: 1.0.12     State: Enabled                                 
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Mozilla Firefox
 - Version 114.01

**Additional context**

**Comment by btry** [comment]
Hi

This option has been remobed because the plugin Additional Fields already gives you the ability to set a a field mandatory. Formcreator will use this property.

**Comment by btry** [comment]
The PR above shows the mandatory property as  read only. It helps to know its state, but does not allow you to modify it. This is informative only.

Can you test the PR and feedback ?

**Comment by Gambware** [comment]
Ok, We did some tests using the mandatory field in Additional Fields and it's working on formcreator. 
Also using the Override By status in Additional Field we keeping the field mandatory in form and not mandatory on standard ticket page.
