### ISSUE TITLE
Knowledge base articles showing under forms when marked as show in FAQ

### ISSUE THREAD

**Issue by willgl1** [pluginsGLPI/formcreator#3302]
**Describe the bug**
When knowledge base articles are listed as "Put this item in the FAQ" "YES" then it shows within FAQ tab along with Forms tab.

**To Reproduce**
1. Go to self service profile
2. Click on Forms
3. See all forms along with FAQ articles

**Expected behavior**
Before 10.0.7 and normal behaviou would be only Forms show under forms.

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.7

formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace

**Smartphone (please complete the following information):**
 - Device: Dell Laptop
 - OS: Windows 11
 - Browser Chrome
 - Version  114.0.5735.110
![FAQ Bug](https://github.com/pluginsGLPI/formcreator/assets/107202756/ec6a211a-191f-47dc-896b-d404d20ff2bc)

**Additional context**

**Comment by btry** [comment]
Hi

Check in the entity configuration the settings

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/03ef8979-5987-4c5b-a511-aecfbd21b75c)

**Comment by willgl1** [comment]
> Hi
> 
> Check in the entity configuration the settings
> 
> ![image](https://user-images.githubusercontent.com/14139801/246217959-03ef8979-5987-4c5b-a511-aecfbd21b75c.png)

Hi, thanks for this where is this menu I have checked all tabs under Administration > Entities and cnanot see this?

**Comment by btry** [comment]
Hi

I'm sorry, I did Truncated my screenshot and it does not show the tab. Use the tab **"forms"**. This tab is added by the plugin for all its entity related settings.

**Comment by willgl1** [comment]
Very helpful thanks!!
