### ISSUE TITLE
preselection not usefull for us 

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#331]
In past the radio buttons were not preselected at the branch they are selected by default the first one. Can we deactivate the preselect ?

**Comment by btry** [comment]
Hi 

Here is a patch proposal : https://github.com/btry/formcreator/tree/331_radio_without_default_value

**Comment by Armin83** [comment]
The patch works for us.

**Comment by btry** [comment]
Rework still not started, then we decided to merge the fix anyway in 2.4.1

**Comment by btry** [comment]
merged in the hotfix branch
