### ISSUE TITLE
Impossible d'attribuer à un groupe

### ISSUE THREAD

**Issue by casson974** [pluginsGLPI/formcreator#3312]
Bonjour,
Nous sommes récemment passé sur la version 10.0.7 de GLPI.
Il nous est actuellement impossible depuis un ticket ouvert de l'attribuer à un groupe.
Je précise qu'il s'agit bien d'attribuer manuellement et non par une règle métier.
Les groupes sont bien configurés pour être visibles dans un ticket :
Demandeur : Oui
Observateur : Oui
Attribué à : Oui
Tâche : Oui
Peut être notifié : Oui

Il est bien possible d'ajouter un groupe en observateur mais impossible d'attribuer.

Merci pour votre aide

**Comment by btry** [comment]
Bonjour

Quel est le rapport avec Formcreator ?

**Comment by casson974** [comment]
Bonjour,
Problème résolu.
Merci
