### ISSUE TITLE
The ticket search field does not work by ticket ID

### ISSUE THREAD

**Issue by TR0LLL** [pluginsGLPI/formcreator#3316]
Good morning,
I would like to report a BUG, after updating the form creator field to version 2.13.6, the ticket search field does not work by ticket ID, the search only works by title, which makes the search very difficult.
Can you fix or indicate how I can do this?

I'm using form creator version 2.13.6 and GLPI is 10.0.7

Thank you very much

**Comment by btry** [comment]
Hi

Please tell the URL and a screenshot of the page where you fail to search by ticket ID. I failed to locate where you observed the issue.

**Comment by TR0LLL** [comment]
Hello,

The question being used is:
![image](https://github.com/pluginsGLPI/formcreator/assets/42414051/c1655844-62c2-4970-8e01-cda1128e2c5b)

In this field, the search by ticket ID does not work, before the update it worked:
![image](https://github.com/pluginsGLPI/formcreator/assets/42414051/dcf34739-2fcb-4461-83db-4e47a0cfaf9c)

![image](https://github.com/pluginsGLPI/formcreator/assets/42414051/53d8806e-a915-4cf3-ac7c-8e6233df076e)

**Comment by btry** [comment]
Hi

Try the version 2.13.7. I checked and seems to be working. 

#duplicates https://github.com/pluginsGLPI/formcreator/issues/3335

**Comment by btry** [comment]
Hi

The other issue has been solved. The feature is implemented in the latest version of the plugin.
