### ISSUE TITLE
Liaison formcreator avec plugins

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#3317]
Bonjour

Il est possible de faire liaison entre formcreator et les plugins en ajoutant quelques lignes dans glpiselecfield.class.php

plutot que de l'ajouter manuellement, ne pourrait-on pas imaginer lors du setup de formcreator, que celui-ci scanne les plugins installés, puis demande si l'utilisateur veut les voir en tant qu'objet glpi ?

cela permettrait d'eviter cette tache (que l'on oublie des fois lors de changements de version formcreator)

qu'en pensez vous ?

**Comment by btry** [comment]
Bonjour,

Je pense que ça génère trop de complexité. L'administrateur n'a pas besoin de choisir quels types sont disponibles, pour ensuite les sélectionner pznsa t la configuration d'une question.

Je suis en congés pour le moment. De mémoire un système a déjà été mis en place pour que Formcreator puisse travailler avec un autre plugin, s'appuyant sur un mécanisme où le plugin déclare à Formcreator les types qu'il souhaite exposer dans les questions. Cela ne demande aucune intervention supplémentaire par un administrateur.
