### ISSUE TITLE
formcreator/front/wizard.php

### ISSUE THREAD

**Issue by TI-Fump** [pluginsGLPI/formcreator#3320]
When using a resolution of 1440x900, the upper bar containing new, assigned, waiting, solved and closed tickets is partially cut.
![print](https://github.com/pluginsGLPI/formcreator/assets/107057549/73ee9297-a93d-4981-868f-44553790666d)

**Comment by btry** [comment]
Hi

Try this patch and feedback: https://github.com/pluginsGLPI/formcreator/pull/3306

**Comment by btry** [comment]
Hi

I assume your problem is solved. I close.
