### ISSUE TITLE
Je ne vois pas l'objet "Applicatifs" dans Objet GLPI de mon formulaire

### ISSUE THREAD

**Issue by CecileInfanti34** [pluginsGLPI/formcreator#3321]
But final: 
Dans un formulaire, pouvoir faire choisir un nom applicatif et faire apparaitre ce nom dans la cible du ticket, mis en forme avec les ##answerXXX###

Description:
J'ai crée un formulaire avec une question: merci de sélectionner l'application concernée.
Quand je passe par le type Objet GLPI, je n'ai pas "Applicatifs", alors que j'ai bien dans Gestion, l'accès à Contrats, Fournisseurs, Documents, etc..
![image](https://github.com/pluginsGLPI/formcreator/assets/138763743/71497869-a98c-4975-bd4c-69d70f761ca4)

J'ai donc testé le type Additionnals fields. Pour ce faire, j'ai crée un bloc (champ supplémentaires) avec le plugin "Fields, que je nomme application et j'y ajoute le type Applicatifs.

A l'utilisation du formulaire, la liste des applicatifs s'affiche correctement, on sélectionne une application, tout va bien.
Le ticket se crée, et dans la cible, cela me remonte que l'ID de l'applicatif sélectionné. Je n'ai pas le nom.

Est-ce que vous auriez-vous une idée pour:
- soit utiliser le type Objet GLPI, et pouvoir utiliser l'objet Applicatif qui n'apparait pas dans la liste et pourquoi ?
- soit continuer à passer par le type Additionnal Fields, et pouvoir remonter le nom de l'applicatif dans la cible de mon formulaire et non l'ID ?

Merci pour votre aide.

- GLPI version
GLPI 10.0.3 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

- GLPI / Plugins
news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.18.1     State: Enabled                                 
		Install Method: Manual
	mydashboard          Name: Dashboard                      Version: 2.0.8      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalades                      Version: 2.8.0      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.3     State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.3+1.0 State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Impression pdf                 Version: 2.1.0      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual

**Comment by btry** [comment]
Bonjour

Cet élément est hard codé dans le plugin. Si vous avez la liste, il devrait apparaitre.

Vous cherchez bien l'objet applicatifs natif de GLPI, pas celui du plugin Appliances qui est maintenant obsolète ?

Vous utilisez des versions de GLPI et de Formcreator qui sont dépassées. Essayez de mettre à jour, au moins sur une instance de tests, et voyez si le souci persiste.

**Comment by btry** [comment]
Bonjour

N'ayant pas de retour, je suppose que le problème est résolu.
