### ISSUE TITLE
cannot edit/update after refuse answer glpi formcreator 2.13.6

### ISSUE THREAD

**Issue by iranneves** [pluginsGLPI/formcreator#3325]
**Describe the bug**
There is a problem when the user request a new form with need a validator and the answer is refuse by a validator for a correction,  the user cannot update/edit the form again to new update, this is bad because the user have to open a new form again.

**Comment by btry** [comment]
Hi

When a validator refuses a request, this is not for correction. This is a definitive rejection. Formcreator does not supports any workflow when a rejected request can be modified by the requester.

**Comment by iranneves** [comment]
> Hi
> 
> When a validator refuses a request, this is not for correction. This is a definitive rejection. Formcreator does not supports any workflow when a rejected request can be modified by the requester.

Hi,
in older versions it worked like this.

**Comment by btry** [comment]
Hi

If this worked in old version, then I'm probably wrong. I need to double check. On which version you saw the feature working ? 2.12 ?

**Comment by iranneves** [comment]
Hi,
2.8

**Comment by btry** [comment]
Hi

The problem appeared in version 2.13.0.

Here is a fix. Please test it and feedback.
