### ISSUE TITLE
Formcreator does not work to create session

### ISSUE THREAD

**Issue by furtadovitor** [pluginsGLPI/formcreator#3328]
I installed the formcreator in GLPI through the marketplace but I am not able to create sessions and questions.
When I click it, a # appears as if there is no link to it, how to fix it?

URL:
![image](https://github.com/pluginsGLPI/formcreator/assets/101369856/8696cb33-c802-49df-ae5e-7205a9d7d855)

![image](https://github.com/pluginsGLPI/formcreator/assets/101369856/886ddb82-d693-4f2c-9974-7c9050f64d90)

**Comment by btry** [comment]
Hi

Try the version 2.13.7 released yesterday. IF the problem persists, then search in the developer tools of the browser for JS errors, or errored HTTP requests.

**Comment by btry** [comment]
Hi

HAving no feedback, I assume the problem is solved.
