### ISSUE TITLE
Error i18n 

### ISSUE THREAD

**Issue by furtadovitor** [pluginsGLPI/formcreator#3330]
I installed the formcreator in GLPI through the marketplace but I am not able to create sessions and questions.
When I click it, a # appears as if there is no link to it, how to fix it?

Debugging through the browser I find several i18n errors, how to solve it?

![image](https://github.com/pluginsGLPI/formcreator/assets/101369856/15052776-2e5e-472f-8dc2-ca446bd7be69)

**Comment by btry** [comment]
Hi

Please share the URL of the impacted page. It looks like the errors occur when you're editing a configuration page.

**Comment by btry** [comment]
Hi

Having no feedback, I cannot investigate, I close.
