### ISSUE TITLE
When you click to send to create a new ticket DUPLICATES with you click twice

### ISSUE THREAD

**Issue by GOAguiar99** [pluginsGLPI/formcreator#3331]
**Describe the bug**
If you click twice in send to create a ticket, creates two tickets. If you click 3 times, creates 3 tickets.

**Expected behavior**
Doesn't allow me to create more then ONE ticket

**GLPI / Plugins (please complete the following information):**
- 10.0.7
behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.6+1.1 State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Importação de dados            Version: 2.13.2     State: Installed / not activated               
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	metabase             Name: Metabase                       Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	dashboard            Name: Painel                         Version: 1.0.3      State: Not installed                           
		Install Method: Manual

**Comment by jcervantes-sipecom** [comment]
Hi @GOAguiar99, look at these same issues:
https://github.com/pluginsGLPI/formcreator/issues/3313
https://github.com/pluginsGLPI/formcreator/issues/3198
https://github.com/pluginsGLPI/formcreator/issues/3309

**Comment by btry** [comment]
Hi

Upgrade to GLPI 10.0.9 and the problem will disappear.
