### ISSUE TITLE
[FR] Allow search Ticket by ID not just by name in GLPI Object 

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/formcreator#3335]
**Is your feature request related to a problem? Please describe.**
Sometime is required to select a Ticket in GLPI Object field, and some tickets have the same name, so it would be better to allow search the ticket by its ID as well, just as when creating a ticket you search a ticket with its ID to link it.

**Describe the solution you'd like**
The Ticket GLPI Object should also be searchable by ID:

![image](https://github.com/pluginsGLPI/formcreator/assets/56606032/5f0378a2-9f2a-4d1c-89e8-29b42bd93b0c)

**Describe alternatives you've considered**
For now nothing

**Additional context**

![image](https://github.com/pluginsGLPI/formcreator/assets/56606032/e8aabe2b-6551-4375-88ec-68a8398a5211)

This FR complement the followings: https://github.com/pluginsGLPI/formcreator/issues/3333 https://github.com/pluginsGLPI/formcreator/issues/3334

**Comment by btry** [comment]
Hi

It seems to work. Do you have the latest version (2.13.7) ?

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/2d352a0e-03d3-43ba-9880-6a5248e25d57)
