### ISSUE TITLE
Warning: Undefined array key in /glpi/src/Item_Ticket.php

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/formcreator#3336]
**Describe the bug**
When target an answer form to a ticket, or associate it manually, the column "Status of items" and "Location" have the followings errors: Warning: Undefined array key in /glpi/src/Item_Ticket.php

**To Reproduce**
1. Create a Form and target to a ticket
2. Answer the form and send
3. Go to the targeted ticket recently created
4. Go to Items associated
5. See the form answer, and the columns with error

**Expected behavior**
As the form answer didn't have Status and location, this should shown in blank.

**Screenshots**

![image](https://github.com/pluginsGLPI/formcreator/assets/56606032/5ce8e37a-d089-4b3c-922d-b6e7577c9452)

**GLPI / Plugins (please complete the following information):**
- GLPI version: 10.0.9

**Additional context**
- Plugin Version: 2.13.6

**Comment by btry** [comment]
Hi

Could you test this patch ?

https://github.com/btry/glpi/commit/71b9be6d0dd24fbdc29109f24fccba940629a5a7

**Comment by btry** [comment]
To see form answers in items of tickets, you must check your profile. Open tab assistance and ensure that the list of items associable to ticket contains form answers. If not, add it then try again.

**Comment by jcervantes-sipecom** [comment]
Ah ok @btry you where right, now it's appear again. Also as I said, I applied the patch and the Status and Location doesn't have the error again:

![image](https://github.com/pluginsGLPI/formcreator/assets/56606032/1896ca71-14c4-465c-a6f5-11f6c5052a8f)
