### ISSUE TITLE
Error update Formcreator 2.13.5 to 2.13.6

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#3338]
**Describe the bug**
Hi @btry 
When trying to update the plugin from version 2.13.5 to 2.13.6 (With GLPI 10.0.9) I get the error below

**To Reproduce**
1. Update plugin CLI Mode

**Screenshots**
![image](https://github.com/pluginsGLPI/formcreator/assets/35368369/aade7d14-acd9-49a0-94ba-f445a0ea6abb)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.9

**Desktop (please complete the following information):**
 - OS: Oracle Linux

**Comment by btry** [comment]
Hi

5his table has been replaced years ago to support conditions on more objects (sections, forms, targets)

A problem occured in a previous upgrade. 

Assuming that all forms work as expected, you can just drop this table then retry to upgrade.

Also, as you're a customer, prefer to contact us with our professional support.

**Comment by phamorais** [comment]
Hi @btry!

After your guidance I dropped the table the update went smoothly! Thank you very much!
