### ISSUE TITLE
When a user clicks the submit button multiple times in quick succession

### ISSUE THREAD

**Issue by Ouloulou69** [pluginsGLPI/formcreator#3339]
**Describe the bug**
When a user clicks several times on the submit button, multiple tickets are created. 

**To Reproduce**

Use a forms to create a ticket and click multiple times on the submit button. 

**Expected behavior**
Just create one ticket.

**Screenshots**

![Conf](https://github.com/pluginsGLPI/formcreator/assets/139245589/7b817762-1624-46d1-b704-c08dfe0f9e17)

**GLPI / Plugins (please complete the following information):**
- GLPI version : 10.0.9 
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)

 
	news                 Name: Alertes                        Version: 1.10.6     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.13.1     State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                
		 Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.2      State: Error / to clean                        
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	karastock            Name: Karastock                      Version: 1.4        State: Not installed                           
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual
	userportal           Name: UserPortal on FormCreator      Version: 1.2.6      State: Enabled                                 
		Install Method: Manual

**Desktop (please complete the following information):**
-Windows 11 : Chrome/firefox/Edge, I tried in private sessions

**Additional context**

I tried the issue on this fix : https://github.com/glpi-project/glpi/pull/14646
But it's not working. It's working on the preview of the forms but not on the users forms. 

Regards.

**Comment by btry** [comment]
Hi

With Glpi 10.0.9, this should not happen. Check if you have a JS error when you click on the submit button.

**Comment by Ouloulou69** [comment]
Hello,

I have an error : 

![image](https://github.com/pluginsGLPI/formcreator/assets/139245589/25dda1f7-c09a-4bc1-89a7-2deaad1be824)


Thanks for your help

**Comment by Ouloulou69** [comment]
Nevermind, I reverted my modification but it's why there is this error. 
With the fix, no error with super admin. 
But with a user : 

![image](https://github.com/pluginsGLPI/formcreator/assets/139245589/3c9cd8e8-0532-4d41-b9f1-bb77dbcdc4b7)

**Comment by btry** [comment]
Hi

If you're using Glpi 10.0.9 the last error, which occurred 3 times in your screenshot, should not happen. Maybe the file common.min.js is out of date in the server, or the browser's cache is out of date.

**Comment by Ouloulou69** [comment]
My bad i was on 10.0.7
