### ISSUE TITLE
Bug in public form

### ISSUE THREAD

**Issue by furtadovitor** [pluginsGLPI/formcreator#3342]
Good morning.

When creating a public form, I also downloaded the additional fields plugin, added a field with the type of object and registered 3 items within that object. But when I put it in my public form, an error appears not loading these 3 items that I registered. Follow the printns of the bugs.

![image](https://github.com/pluginsGLPI/formcreator/assets/101369856/e39c52d2-8a58-49cf-b4e9-996c22cd15c9)
![image](https://github.com/pluginsGLPI/formcreator/assets/101369856/865825f4-bd5b-45c7-82f9-c65c2fd16be6)

**Comment by btry** [comment]
Hi

Items from the database are not accessible without being logged in. The plugin forbids to create dropdowns questions because of that. 

I checked the code and you should not be able to create this type of question in a public form.

**Comment by furtadovitor** [comment]
Muito obrigado pela explicação.
