### ISSUE TITLE
Error in the counter of tickets to validate

### ISSUE THREAD

**Issue by verdanatech-marcio** [pluginsGLPI/formcreator#3349]
**Describe the bug**

Tickets created from form response and with validations created in the form target, do not appear in the simplified interface count. Only manually created validations appearing on counter

**To Reproduce**
1. Open the simplified interface homepage
2. View counters at the top of the page

**Expected behavior**
Count tickets with validation correctly

**Screenshots**

**GLPI / Plugins (please complete the following information):**
- GLPI version - 10.0.9
- Formcreator - 2.13.6

**Desktop (please complete the following information):**
 - Linux Debian 12
 - Google Chrome 

**Additional context**

**Comment by btry** [comment]
Hi

If I understand correcty, your form is configured with a validation step in Formcreator, right ?

In this case, when tue requester submits a form, a ticket is not created yet. It will  be created after approval of the form answers. The requester should see his request in the page "My requests for assistance". The row representing the answers must have an ID beginning with **f_**. Do you see it ?

**Comment by verdanatech-marcio** [comment]
No, when validations are created by glpi rules, after the creation of the ticket. The status should be waiting for validation. In the glpi it shows that it is waiting for a validation. But in the simplified interface counters it is not computed

**Comment by btry** [comment]
OK, I understand

**Comment by btry** [comment]
I reproduced

**Comment by btry** [comment]
Could you try this patch and feedback please ?

```diff
diff --git a/inc/formanswer.class.php b/inc/formanswer.class.php
index 92f5aab6..3c420635 100644
--- a/inc/formanswer.class.php
+++ b/inc/formanswer.class.php
@@ -1582,7 +1582,7 @@ class PluginFormcreatorFormAnswer extends CommonDBTM
          'items_id'           => $ticketId,
          'itemtype'           => Ticket::class,
          'name'               => $issueName,
-         'status'             => $ticket->fields['status'],
+         'status'             => PluginFormcreatorCommon::getTicketStatusForIssue($ticket),
          'date_creation'      => $ticket->fields['date'],
          'date_mod'           => $ticket->fields['date_mod'],
          'entities_id'        => $ticket->fields['entities_id'],
```

**Comment by btry** [comment]
Hi

Do you have feedback for this patch ?

**Comment by verdanatech-marcio** [comment]
Hello, after using the patch and executing sync issues, the counter was updated to the correct value. Thanks

**Comment by btry** [comment]
Hi

Thank you for your feedback; I merge the patch for the next release.
