### ISSUE TITLE
Run yarn install --prod in the plugin directory when update form creator in market place 

### ISSUE THREAD

**Issue by damien51** [pluginsGLPI/formcreator#3351]
hello,

I have an error when upgrading form creator from 2.13.6 to 2.13.7

<img width="539" alt="image" src="https://github.com/pluginsGLPI/formcreator/assets/2689495/f6826e78-7c5d-4257-b554-90c3da8417a6">

**Comment by btry** [comment]
Hi

How did you download the plugin ? Did you use the marketplace, or did you download the install manually an archive from GitHub ?

**Comment by DZbox** [comment]
Hi,
The same for me from 2.13.6 to 2.13.7
Was installed manually from Github archive

**Comment by btry** [comment]
I think I found the problem. The builds 2.13.6 and 2.13.7 are incomplete. This is surprising that noone reported it before you. Please try this archive and feedback. If it works for you I need to update the packages for both versions.

[glpi-formcreator-2.13.7.zip](https://github.com/pluginsGLPI/formcreator/files/12406881/glpi-formcreator-2.13.7.zip)

**Comment by damigr** [comment]
> I think I found the problem. The builds 2.13.6 and 2.13.7 are incomplete. This is surprising that noone reported it before you. Please try this archive and feedback. If it works for you I need to update the packages for both versions.
> 
> [glpi-formcreator-2.13.7.zip](https://github.com/pluginsGLPI/formcreator/files/12406881/glpi-formcreator-2.13.7.zip)

yes, that works !!!
thank-you !

**Comment by damien51** [comment]
Same for me thanks

**Comment by plburguet** [comment]
> I think I found the problem. The builds 2.13.6 and 2.13.7 are incomplete. This is surprising that noone reported it before you. Please try this archive and feedback. If it works for you I need to update the packages for both versions.
> 
> [glpi-formcreator-2.13.7.zip](https://github.com/pluginsGLPI/formcreator/files/12406881/glpi-formcreator-2.13.7.zip)

Hello, confirm it works (had the same error)

**Comment by btry** [comment]
The package has been updated. 

Can someone validate that an update from the marketplace leas to a working version of the plugin ?

**Comment by btry** [comment]
Version 2.13.6 has been fixed too.

**Comment by damien51** [comment]
> The package has been updated.
> 
> Can someone validate that an update from the marketplace leads to a working version of the plugin ?
> 
> I don't understand that after 9K downloads of the version 2.13.6 noone reported the issue ....

I didn't have the issue with 2.13.6

**Comment by damien51** [comment]
I tested the upgrade from marketplace on an other GLPI ( with a snapshot before this time :-) ) , it's ok.

**Comment by btry** [comment]
The issue is solved now, I close. Thank you all for your feedback.
