### ISSUE TITLE
Formcreator 2.changed as you upgraded to GLPI 10.0.9 (accordying to your last comment).

### ISSUE THREAD

**Issue by guillermohaad** [pluginsGLPI/formcreator#3352]
hi, I am upgrading from GLPI 9.5.4 and FormCreator 2.11.0 to GLPI 10.0.9 and FormCreator 2.13.6 and when I check a form ticket it shows the content like this:

![image](https://github.com/pluginsGLPI/formcreator/assets/12921805/952ab5a1-6ad2-45ec-b7e1-f9b6d6efc3a8)

**Comment by btry** [comment]
Hi

I assume this ticket has been created by Formcreator. Can you confirm that the ticket has been created when version of GLPI was 9.5.x (and Focmreator was < 2.13.0) ?

**Comment by btry** [comment]
Download this file and place it in glpi/src/Console/Database/ . If the file already exists, then backup it first to restore it the end of the procedure.

https://raw.githubusercontent.com/btry/glpi/30608131a0cf97f1b57b5863a704962bfad1bd72/src/Console/Database/FixHtmlEncodingCommand.php


Locate in GLPI's directory then run (choose a path and filename for the --dump argument)

```sh
bin/console db:fix_html --dump /path/to/backup.sql
```

The whole database will be scanned for known problems with rich text data. Inconsistent values will be backed up un the .sql file you specified then fixed.

Keey the .sql file until you're sure that everything is good. It will allow you to rollback all changes tone by this tool.

If you encounteer a fatal error (pay happen with Generic Objects, if I remember well), disable it then try again.

**Comment by btry** [comment]
Thank you very much. Glad the tool solved the issue.
