### ISSUE TITLE
Restored tickets created from a form with 2 targets aren't accessible to post-only users anymore

### ISSUE THREAD

**Issue by Zoddo** [pluginsGLPI/formcreator#3359]
**Describe the bug**
When a ticket was created using a form which contains at least 2 targets, if one of the tickets is deleted then restored, both tickets become inaccessible to users with post-only profiles ("Item not found").

**To Reproduce**
1. Create a form with at least 2 targets (you can import this one: [export_formcreator_20230828_1612.txt](https://github.com/pluginsGLPI/formcreator/files/12455289/export_formcreator_20230828_1612.txt))
2. Login as post-only and fill the form
3. Two tickets are created. Open one of them and click "Cancel my ticket"
4. As a super-admin, go to the trash bin and restore the ticket
5. As a post-only user, try to open the restored ticket: "Item not found" is displayed. The other ticket which wasn't deleted is also inaccessible.

**Expected behavior**
The deleted ticket can be accessed again by post-only users once restored.  
The non-deleted ticket should remains accessible at all times.

**GLPI / Plugins (please complete the following information):**
- GLPI version: 10.0.9
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page):
```
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled
		Install Method: Manual
```
(I have other plugins, but the issue is reproducible with all other plugins disabled)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: Google Chrome
 - Version: 115

**Additional context**
This issue happens only with tickets created from a form with 2 targets. If a ticket created directly in GLPI or from a form with a single target is deleted then restored, the ticket remain accessible.

**Comment by btry** [comment]
Hi

The CLI command deletes the whole content of issues table, then re-populate it. Its role is to fix inconsistencies and so far, there is no known bug with it. Then no known downside.

**Comment by btry** [comment]
Hi

Please try the above PR. Be careful : I added tests then the patch tool may complain that it fais to find a file to patch. Ignore any file located in tests/ directory.
