### ISSUE TITLE
Champs d'un objet GLPI selectionné

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#3374]
Bonjour

Est-il possible de 'recuperer' des champs secondaires d'une table selectionnée en tant qu'objetGLPI ?
Ex : 
on choisit glpi_users
je selectionne un utilisateur : ok

dans le ticket généré, comment afficher le champs 'name' de cette table ?

Merci

**Comment by btry** [comment]
Bonjour

Vous pouvez utiliser des tags avec la syntaxe suivante ##answer_42.property## .

Le mot property est à remplacer par le nom **en anglais** de la propriété souhaitée.  Les valeurs disponibles sont récupérables dans les critères de recherche de l'objet concerné. Si la propriété contient des espaces, il faut les remplacer par des underscores _ . La première lettre de la propriété doit être ne majuscules.

En version 2.14 il y aura une fonctionnalité pour rencre tout cela plus facile: https://github.com/pluginsGLPI/formcreator/pull/3301

**Comment by EC2311** [comment]
merci bien pour votre reponse.
cela fonctionne quelque soit les versions formcreator ?
##answer_671.Name##, sachant que cette question correspond au choix de l'utilisateur
Merci

**Comment by btry** [comment]
Cela fait pas mal de temps que la fonctionnalité existe. Je n'ai plsu en tête la date d'introduction de la fonctionnalité. Comme vous êtes forcément passé en GLPI 10 sur toutes vos instances (normalement), vous aurez forcément accès à cette syntaxe.

**Comment by EC2311** [comment]
Bonjour
Merci pour votre reponse,
est-ce que les tests (masqué sauf si, etc ) sont utilisables avec ces zones ?

**Comment by btry** [comment]
Bonjour

J'ai fait un test avec un formulaire simple dans lequel je sélectionne un utilisateur. Aucune modification du code n'a été faite. Dans le ticket cible j'ai utilisé la balise ##answer_914.Location##

La balise est bien résolue : j'obtiens le nom du lieu de l'utilisateur. Je pense que vous n'avez pas utilisé le bon nom de propriété.

En ce qui concerne l'utilisation de cette fonctionnalité dans les conditions, ce n'est pas dans la roadmap. Je pense qu'il faudrait éviter cette fonctionnalité pour pouvoir déplacer la mise à jour de la visibilité des questions côté navigateur. Actuallement c'est le serveur qui s'en charge et cela peut causer des ralentissements.

**Comment by EC2311** [comment]
j'ai installé une v10 "neuve" sans migration et uniquement le plugin formcreator : ca passe en effet sans souci.
Donc : souci avec autre plugin (je vais installer sur cette instance les autres plugins) ? ou souci lors migration (coeur glpi) ?

je continue tests

**Comment by EC2311** [comment]
j'ai ajouté ceci lors de l'appel

         $property = str_replace("_", " ", $property);
         $searchOption = $item->getSearchOptionByField("name", $property);
		 
		 **if(!isset($searchOption['id']))
		 {
			 $property=strtolower($property);
			 $searchOption = $item->getSearchOptionByField("field", $property);
		 }**

si le champs spécifié dans le formulaire n'est pas connu en tant que name, le searchOption['id'] est alors non trouvé : test avec la valeur en tant que champs de la table (field) (ex prénom, ou name etc) 

cela permet d'elargir les champs disponibles ?
De maniere générale, il faudrait peut etre prévoir le cas où la personne spécifie un champs non existant car sinon on a une belle erreur en interactif.
Qu'en pensez vous ?

**Comment by btry** [comment]
Bonjour

Vous avez spécifié la propriété Firstname,  mais dans le code de GLPI, la propriété est "First name". Quand il y a un espace, rempalcez-le par un underscore, et ça doit fonctionner sans patch.

https://github.com/glpi-project/glpi/blob/caa066572fdedc2e61b26db23d25fd366a31792f/src/User.php#L3606

**Comment by EC2311** [comment]
En effet!
méconnaissance complete de ma part pour le fonctionnement
un grand merci

**Comment by btry** [comment]
Bonjour

La question étant resolue, je ferme ce ticket.
