### ISSUE TITLE
PHP Warning when a ticket is thrown in the trash

### ISSUE THREAD

**Issue by pierrejn-git** [pluginsGLPI/formcreator#3375]
**Describe the bug**
PHP Warning pop up in red when throwing a ticket in the trash . The trace log below :
          [2023-09-26 19:37:45] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared between "glpi_computertypes" and "glpi_plugin_additionalalerts_notificationtypes" table. Target field "types_id" is not a foreign key field. in /var/www/vhosts/ecodair.services/httpdocs/glpi/src/DbUtils.php at line 2169
            Backtrace :
            src/DbUtils.php:2169                               trigger_error()
            inc/db.function.php:585                            DbUtils->getDbRelations()
            src/CommonDBTM.php:866                             getDbRelations()
            src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
            src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
            src/CommonDBTM.php:4631                            CommonDBTM->delete()
            marketplace/formcreator/hook.php:534               CommonDBTM->deleteByCriteria()
            src/Plugin.php:1665                                plugin_formcreator_hook_delete_ticket()
            src/CommonDBTM.php:2106                            Plugin::doHook()
            src/MassiveAction.php:1433                         CommonDBTM->delete()
            src/MassiveAction.php:1414                         MassiveAction::processMassiveActionsForOneItemtype()
            src/MassiveAction.php:1392                         MassiveAction->processForSeveralItemtypes()
            front/massiveaction.php:59                         MassiveAction->process()
            public/index.php:82                                require()
  
          [2023-09-26 19:37:45] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared between "glpi_documents" and "glpi_plugin_manageentities_companies" table. Target field "logo_id" is not a foreign key field. in /var/www/vhosts/ecodair.services/httpdocs/glpi/src/DbUtils.php at line 2169
            Backtrace :
            src/DbUtils.php:2169                               trigger_error()
            inc/db.function.php:585                            DbUtils->getDbRelations()
            src/CommonDBTM.php:866                             getDbRelations()
            src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
            src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
            src/CommonDBTM.php:4631                            CommonDBTM->delete()
            marketplace/formcreator/hook.php:534               CommonDBTM->deleteByCriteria()
            src/Plugin.php:1665                                plugin_formcreator_hook_delete_ticket()
            src/CommonDBTM.php:2106                            Plugin::doHook()
            src/MassiveAction.php:1433                         CommonDBTM->delete()
            src/MassiveAction.php:1414                         MassiveAction::processMassiveActionsForOneItemtype()
            src/MassiveAction.php:1392                         MassiveAction->processForSeveralItemtypes()
            front/massiveaction.php:59                         MassiveAction->process()
            public/index.php:82                                require()
            

**To Reproduce**
Create a trial ticket then throw it in the trash

**Expected behavior**
No PHP red Warning pop up

**Screenshots**
No screenshot

**GLPI / Plugins (please complete the following information):**
- GLPI version : 10..0.10
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
[plugin_glpi.pdf](https://github.com/pluginsGLPI/formcreator/files/12730788/plugin_glpi.pdf)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : CentOS

**Smartphone (please complete the following information):**

**Additional context**
When the FormCreator plugin is deactivated, there is no warning.

**Comment by stonebuzz** [comment]
Hi @pierrejn-git 

This is a warning from the additionalalerts plugin

can you open an issue to the dedicated repo 
https://github.com/InfotelGLPI/additionalalerts

Best regards
