### ISSUE TITLE
Error with form languages

### ISSUE THREAD

**Issue by Madgith** [pluginsGLPI/formcreator#3378]
Hi,

Today, I set up a translation for all my form and is working well except for the textarea. I have a textarea with a text write in the default values. This text is translated into the form languages but, when I used an English browser, all is in English except the textarea appears in french.

- Set up a textarea with a default value.
- Go to Form languages and translate your new textarea and the default value.
- Open your form with the language you want to translate and you can see the default value in the textarea is not translated, but the text of the name box is translated. Other fields I have (like email, select or multiselect) working good.

![translate_error](https://github.com/pluginsGLPI/formcreator/assets/146367297/5235cb10-96a1-491b-8518-6c082951accf)

GLPI version : 10.0.10
list of all plugins with their version : behaviors 2.7.2, formcreator 2.13.7, mreporting 1.8.2

I try with the desktop version of Chrome 117 and Firefox 118. If my English is not understandable, I can explain it in French.

Thanks in advance

**Comment by Madgith** [comment]
Hi,

Another problem related to translation, if I use a select field in my form as a condition to create a ticket, when I use a translated proposal, I receive a error and the new ticket don't created.

Steps to reproduce the behavior :

- Translate a line on a select field
- Add the translation in the targets if needed
- Test the form to create a new ticket

![image](https://github.com/pluginsGLPI/formcreator/assets/146367297/5169aab7-1aa9-40f7-9a7a-ec3ab714821d)

If I use an untranslated proposal, the ticket is created correctly.

Thanks in advance for your help.

**Comment by btry** [comment]
Hi

I think this commit will solve your problem.

https://github.com/pluginsGLPI/formcreator/commit/28b4781d8f0042aff2750dacb1662ca993e0b623

**Comment by btry** [comment]
Try also the above PR for the initial problem.

**Comment by Madgith** [comment]
Hi,

I use the PR, it solve the second issue but the first one is in the same state

**Comment by btry** [comment]
Hi

https://github.com/pluginsGLPI/formcreator/commit/28b4781d8f0042aff2750dacb1662ca993e0b623 should solve problem with a select field. It has been reported several times and reported working.

The PR #3386 addresses the untranslated problem in the default value of a text area, as you reported when you opened this issue. Then you need both to solve the 2 issues you described.
