### ISSUE TITLE
Possibility to add image on home page next to Form category

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#339]
Hello

Is it possible to image on home page next to Form category.

Target : purpose a Service Catalog to users (image is easier to find what they need

**Comment by btry** [comment]
Hi

Can you explain your thought about "to image on home page" ?

By the way, are you aware there is a service catalog incoming includiing a search engine ? (see versions 1.4-beta*)

**Comment by satyan01** [comment]
no I did not see, I am going to check

**Comment by satyan01** [comment]
1.4 beta is master version ?

**Comment by satyan01** [comment]
what is happening when I put yes to service catalog default form ?

**Comment by satyan01** [comment]
when i go to assistance form I have that

**Comment by satyan01** [comment]
Assistance form display bad

![image](https://cloud.githubusercontent.com/assets/15144026/20399641/0ddd4f5c-acf2-11e6-9d40-191aa640f47a.png)

**Comment by btry** [comment]
> 1.4  beta is master version ? 

Yes

> what is happening when I put yes to service catalog default form ?

The form is displayed if the search engine does find any form mathing the keywords

**Comment by btry** [comment]
The CSS is hugely different from previous versions. Press F5 to refrech your browser's cache and you'll get the normal  display

**Comment by satyan01** [comment]
better

![image](https://cloud.githubusercontent.com/assets/15144026/20399730/6a43672c-acf2-11e6-982d-2326d1209b5b.png)

**Comment by satyan01** [comment]
It would be great to have the possibility to add picture

example put a phone next to my blackberry 
a token next to remote access....

**Comment by satyan01** [comment]
great job !!! thank you

**Comment by btry** [comment]
Note it is not finished : there are still some bugs to solve.

**Comment by satyan01** [comment]
Good morning, just a bug with the image

![image](https://cloud.githubusercontent.com/assets/15144026/20421790/7e280486-ad66-11e6-948f-27407779279b.png)

**Comment by btry** [comment]
Hi

Can you create a distinct ticket for this, with steps to reproduce ? Also, did you used  that with previous releases (to know if this is a regression)

**Comment by satyan01** [comment]
In fact this is the case for two forms when I include an image
![image](https://cloud.githubusercontent.com/assets/15144026/20422697/38cb793a-ad6c-11e6-8577-717ddd711a5e.png)

I used last version of formcreator before the beta

**Comment by satyan01** [comment]
as well pictures are not displayed even if I refresh, for me it is ok but not for other users (IE and Chrome)

**Comment by satyan01** [comment]
for image I added <p> in the code and it is correctly above Questions

**Comment by jswytka** [comment]
Hi @satyan01 
you posted on nov, 17 a image with some categories. How do that?

![image 7](https://cloud.githubusercontent.com/assets/21204053/22205189/6590fcf8-e154-11e6-93bc-8f18c89cfabc.png)

**Comment by btry** [comment]
Hi

@jswytka : this feature is in the master branch, but not yet released. Please don't hijack issues, or it will be harder to follow them.

**Comment by satyan01** [comment]
ok no problem, thx. Actually it works correctly
