### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by lehvairo** [pluginsGLPI/formcreator#3391]
If you press submit, the form could be reset. Or is there any other solution other than Captcha. Currently, users can spam the submit button. 
What other solutions are there?

GLPI Version: 10.0.2
Form Creator Version: 2.13.7

The submit (answare) button is displayed in the picture ↓↓↓
![bywnlXAt2D](https://github.com/pluginsGLPI/formcreator/assets/147597482/6292b983-6f3c-4fa1-a111-dbe1b53ec672)

**Comment by btry** [comment]
Hi

If a user submits a form, he cannot spam the button as long the submission is not complete. There is a spinner un the button to show that the submission is being processed, and the submit button shall be disabled. After the submission, the user us redirected to a page which confirms his requests has ben saved.

There is only the captcha to prevent robots to use a public form.

I don't understand what is your issue. Is the form reinitialized at some point ? Di you seed something else than a captcha for a public form ? Do you have users who send several times the same request ?

**Comment by lehvairo** [comment]
https://youtu.be/bxpKT-V-7e8

Here is video about spamming.

**Comment by btry** [comment]
The user should  be redirected to a new page after the submission is complete. There is something wrong.

![Peek 11-10-2023 14-25](https://github.com/pluginsGLPI/formcreator/assets/14139801/42d3e6a6-d420-47aa-b663-8545ea505979)

Use browser's developer tools to submit the form via CLI and see the returned content of the request (request to ajax/formanswer.form.php)

![Peek 11-10-2023 14-27](https://github.com/pluginsGLPI/formcreator/assets/14139801/6a39a0ff-5f3f-4f05-844a-dcbaa2d86783)

You should have something like this : a JSON string containing an URL the browser will follow to do the redirection.

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/6143030b-8c17-4652-87c2-28bcd9ee007e)

**Comment by lehvairo** [comment]
It should be here. But I don't have it. Is it possible to add it manually somehow?

![image](https://github.com/pluginsGLPI/formcreator/assets/147597482/9ef9a3d8-2241-44ef-814f-6740279e8c3f)

**Comment by lehvairo** [comment]
We updated GLPI and tried to update Form Creator but it gives this error message
![chrome_lTsAR0i8oz](https://github.com/pluginsGLPI/formcreator/assets/147597482/940fb227-702d-4f10-864d-e33213aa26f7)

**Comment by lehvairo** [comment]
Currently we got to the point where GLPI version is 10.0.2 and Form creator version is 2.13.7. The form is working, but the sending part is still not working.

**Comment by btry** [comment]
Sole minor things are broken between glpi 10.0.2 and Formcreator 2.13.7. Upgrade glpi to the very latest revision.

**Comment by btry** [comment]
For the sending problem you should check php-error s.log and sql-errrors.log. maybe there is a problem which prevents to redirect properly.

**Comment by lehvairo** [comment]
![image](https://github.com/pluginsGLPI/formcreator/assets/147597482/23521f20-125a-499c-bbd2-ac70bff0e777)

GLPI update worked. How to change this text?

**Comment by btry** [comment]
You can change it in the code of the plugin. There is nothing to customize it without changing the code.

**Comment by lehvairo** [comment]
Do you know where this code is?

**Comment by lehvairo** [comment]
Where i can find the code location?
