### ISSUE TITLE
Change color in mini dashboard

### ISSUE THREAD

**Issue by damien51** [pluginsGLPI/formcreator#3394]
<img width="1492" alt="Capture d’écran 2023-10-13 à 17 32 13" src="https://github.com/pluginsGLPI/formcreator/assets/2689495/a5d86c29-3261-4598-b3ba-01a535ebbedf">

Hello, where can I edit (if it's possible) the color of the mini dashboard in self service , in other mode than self service, I can edit and change background color, but I don't figure out for self-service with service catalog.

**Comment by damien51** [comment]
I found this : https://github.com/pluginsGLPI/formcreator/pull/2765/files
but I'm not sure if it's the best way to do.

**Comment by btry** [comment]
Hi

This is the right place to change colors.

**Comment by damien51** [comment]
Thanks, if I understand correctly, I have to reinstall form creator with install.php with the new colors ?

**Comment by btry** [comment]
I forgot the fact that the colours are in the installation file. 

Then it is probably better to change them in the database.

**Comment by damien51** [comment]
Thanks for your answer.
Is it too much to ask where? , I really don't want to mess with the database.

**Comment by btry** [comment]
Hi

Check in the table glpi_dashboards_items. Search for rows related to Formcreator

```sql
SELECT * FROM glpi_dashboards_items WHERE gridstack_id LIKE 'plugin_formcreator_%';
```

**Comment by damien51** [comment]
Thanks , colours are changed.
