### ISSUE TITLE
BUG : User name anonimization on target ticket

### ISSUE THREAD

**Issue by BENAY-SD** [pluginsGLPI/formcreator#3408]
**Describe the bug**
Hi,

After upgrade our server from GLPI 9.5.6 and Formcreator 2.12.3 to GLPI 10.0.10 and Formcreator 2.13.7, we found a bug with anonymization. 
When a self-service user create a ticket for another user on forms with question type "GLPI object -> Administration - Users", target ticket display user's name anonimized. 

**To Reproduce**
1. Create a form with question (named User) : type GLPI Object -> Administration - user
2. Create a target type ticket with ##FULLFORM## tag (or juste answer of the question, same issue)
3. Configure entity to anonymize support agents (Entities -> EntityName -> Assistance -> Anonymize support agents = Replace the agent and group name with generic name)
4. Configure self-service profile to use simplified interface
5. With User A, as selft-service profile, select User B on dropdown's User and send the form
6. Look at the ticket 

There is no issue if : 
- User use standard interface 
- User A's aswers is "User A" on this question type
- Anonymize support agent turned off on entity config
- Another question type is used (like Actors)

**Expected behavior**
The expected behavior is to see User B's name on ticket.

**Screenshots**
![image](https://github.com/pluginsGLPI/formcreator/assets/59737857/5ee2038e-3062-40bb-9de3-402ae5d4d46b)

**GLPI / Plugins :**
- GLPI version : 10.0.10
- Plugins : 
![image](https://github.com/pluginsGLPI/formcreator/assets/59737857/40f2e550-ef55-4ef8-9eb8-d763f533f02e)

**Stack :**
 - Server's OS: Windows server 2016
 - Apache 2.4.57 + PHP 8.2.10
 - MariaDB 11.1.2

**Comment by btry** [comment]
Hi

this fix will solve the issue: 66bea30e0
