### ISSUE TITLE
Problem with condition on FormCreator

### ISSUE THREAD

**Issue by Olfa17** [pluginsGLPI/formcreator#3424]
Hello,

I have a problem with FormCreator since last week. My SI department update the last version of GLPI (10.0.10) and last version of FormCreator (2.13.8)
I have 5 questions on my form for an Issue and 5 for a request with conditions.

First question is:

- Type of request: Issue or Request
Condition =Always Visible

If answer is "Issue", the second question is:
Impact on Business
Condition = Hidden unless if Issue on the first question

If answer is "Request", the second question is:
processing time
Condition = Hidden unless if Request on the first question

The Issue form works corretly, i didn't have problem with it, but the second question doesn't appear when the answer of the first question is "Request".
I have 2 servers, one for Production, and second for Developpement. Both doesn't work with Request type "Request"

Do you have any idea where the problem might be coming from?

I created a new form and 3 questions, "Issue" works correctly, "Request" doesn't work

You can see on my screenshot the problem
![FormCreator - Issue](https://github.com/pluginsGLPI/formcreator/assets/152491224/523cfcac-ac4c-4892-a344-241fd0082b7f)
![FormCreator - Request](https://github.com/pluginsGLPI/formcreator/assets/152491224/7fca0309-b370-433e-a659-a100f0d383b5)

- GLPI / Plugins (please complete the following information):

GLPI version 10.0.10
Plugin FormCreator 2.13.8

- Desktop (please complete the following information):

Windows 10
Chrome or Firefox

**Comment by btry** [comment]
Hi

I think your problem is related to [this PR](https://github.com/pluginsGLPI/formcreator/pull/3388)

You probably use french words to compare the "type of request" question. Use english (GB) words instead : **Request** and **Incident**, no matter the language used to design the form.

Unfortunately, I did not find a better solution to build the fix. The solution would be to change the role of the already existing language dropdown available in the form designer.

**Comment by Olfa17** [comment]
Hi @btry 

Thank you for your reply.

Yes i used french words which work correctly before 2.13.8.
In the condition, i changed "Demande" by "Request", it works correctly now.

This bug is only on FormCreator, or for all of GLPI ?
Because I have a lot of rules for my tickets, based on their title

Thank you

**Comment by btry** [comment]
This problem belongs to Formcreator only. I created internally a SQL query to identify easily where are the questions to fix. Here it is.


```sql
(
    select
        f1.id as form_id, f1.name as form_name, f1.name as item_name, c.*
    from
        glpi_plugin_formcreator_conditions c
        inner join glpi_plugin_formcreator_forms f1 on (c.items_id = f1.id)
	inner join glpi_plugin_formcreator_questions qt1 on (c.plugin_formcreator_questions_id = qt1.id)
    where
        c.itemtype = 'PluginFormcreatorForm'
        and qt1.fieldtype = "requesttype" 
)
union
(
    select
        f2.id as form_id, f2.name as form_name, glpi_plugin_formcreator_sections.name as item_name, c.*
    from
        glpi_plugin_formcreator_conditions c
        inner join glpi_plugin_formcreator_sections on c.items_id = glpi_plugin_formcreator_sections.id
        inner join glpi_plugin_formcreator_forms f2 on (glpi_plugin_formcreator_sections.plugin_formcreator_forms_id = f2.id)
	inner join glpi_plugin_formcreator_questions qt2 on (c.plugin_formcreator_questions_id = qt2.id)
    where
        c.itemtype = 'PluginFormcreatorSection'
        and qt2.fieldtype = "requesttype" 
)
union
(
    select
        f3.id as form_id, f3.name as form_name, glpi_plugin_formcreator_questions.name as item_name, c.*
    from
        glpi_plugin_formcreator_conditions c
        inner join glpi_plugin_formcreator_questions on glpi_plugin_formcreator_questions.id = c.items_id
        inner join glpi_plugin_formcreator_sections on glpi_plugin_formcreator_questions.plugin_formcreator_sections_id = glpi_plugin_formcreator_sections.id
        inner join glpi_plugin_formcreator_forms f3 on (glpi_plugin_formcreator_sections.plugin_formcreator_forms_id = f3.id)
	inner join glpi_plugin_formcreator_questions qt3 on (c.plugin_formcreator_questions_id = qt3.id)
    where
        c.itemtype = 'PluginFormcreatorQuestion'
        and qt3.fieldtype = "requesttype" 
)
union
(
    select
        f4.id as form_id, f4.name as form_name, tt1.name as item_name, c.*
    from
        glpi_plugin_formcreator_conditions c
        inner join glpi_plugin_formcreator_forms f4 on (c.items_id = f4.id)
        inner join glpi_plugin_formcreator_targettickets tt1 on (c.items_id = tt1.id)
	inner join glpi_plugin_formcreator_questions qt4 on (c.plugin_formcreator_questions_id = qt4.id)
    where
        c.itemtype = 'PluginFormcreatorTargetTicket'
        and qt4.fieldtype = "requesttype" 
)
union
(
    select
        f5.id as form_id, f5.name as form_name, tc1.name as item_name, c.*
    from
        glpi_plugin_formcreator_conditions c
        inner join glpi_plugin_formcreator_forms f5 on (c.items_id = f5.id)
        inner join glpi_plugin_formcreator_targetchanges tc1 on (c.items_id = tc1.id)
	inner join glpi_plugin_formcreator_questions qt5 on (c.plugin_formcreator_questions_id = qt5.id)
    where
        c.itemtype = 'PluginFormcreatorTargetChange'
        and qt5.fieldtype = "requesttype" 
)
union
(
    select
        f6.id as form_id, f6.name as form_name, tp1.name as item_name, c.*
    from
        glpi_plugin_formcreator_conditions c
        inner join glpi_plugin_formcreator_forms f6 on (c.items_id = f6.id)
        inner join glpi_plugin_formcreator_targetproblems tp1 on (c.items_id = tp1.id)
	inner join glpi_plugin_formcreator_questions qt6 on (c.plugin_formcreator_questions_id = qt6.id)
    where
        c.itemtype = 'PluginFormcreatorTargetProblem'
        and qt6.fieldtype = "requesttype" 
)
```

**Comment by Olfa17** [comment]
Solved by changed "Demande" by "Request" in condition on my form
