### ISSUE TITLE
Mises à jour Formcreator 2.13.7 to 2.13.8 KO

### ISSUE THREAD

**Issue by RomOne78** [pluginsGLPI/formcreator#3428]
Hello, 

Suite à la mise à jour du plugin formcreator de version 2.13.7 à 2.13.8 le plugin ne fonctionne plus.
Mise à jour effectuée à partir de l'interface des plugins.
Tentative de suppression du plugin via Configuration > Plugin 
Désinstaller, désactiver, nettoyer .... Le plugin est toujours présent avec la version 2.13.8.

Je peux ensuite le réinstaller dans cette même version mais suite à ça, je ne peux plus importer mes formulaires avec le .json qui était sauvegardé en 2.13.7.
```
Importation du formulaire impossible, le fichier a été généré avec une autre version
``` 

J'ai tenté de supprimer le plugin dans glpi/plugins/formcreator > OK et de réinstaller le nouveau 2.13.7 mais le 2.13.8 reste persistent sur l'interface Configuration > Plugins .... 

Quelqu'un aurait-il une solution à m'apporter svp.

GLPI 10.0.10 - Ubuntu 23.10 - formcreator 2.13.8

**Comment by btry** [comment]
Bonjour

> le plugin ne fonctionne plus

Quel est le symptôme, avez vous collecté des messages d'erreur en mode debug, des backtraces dans php-errors.log et sql-errors.log ?

Vérifiez si vous avez 2 copies du plugin : une dans le dossier marketplace/ (pour les installations faites via le marketplace) et une autre dans le dossier plugins/ (installations manuelles à l'ancienne). Si oui alors la copie du dossier plugins/ est ignorée.

**Comment by RomOne78** [comment]
Pour ce qui est du plugin dans effectivement il était bien dans ce deux répertoires.
J'ai purgé les deux versions et nettoyer l'ensemble pour une réinstallation à "l'ancienne" dans plugins/

L'import du .json m'a renvoyé la même erreur.

Pour ce qui est des logs.
php-errors.log
```
[2023-12-08 12:29:39] glpiphplog.WARNING:   *** PHP User Warning (512): Plugin "formcreator" version changed. It has been deactivated as its update process has to be launched. in /var/www/html/glpi/src/Plugin.php at line 652
Backtrace :
  src/Plugin.php:652                                 trigger_error()
  src/Plugin.php:500                                 Plugin->checkPluginState()
  src/Plugin.php:245                                 Plugin->checkStates()
  inc/includes.php:95                                Plugin->init()
  front/plugin.php:36                                include()

[2023-12-08 12:31:10] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to load plugin "formcreator" information. in /var/www/html/glpi/src/Plugin.php at line 616
  Backtrace :
  src/Plugin.php:616                                 trigger_error()
  src/Plugin.php:500                                 Plugin->checkPluginState()
  front/plugin.php:43                                Plugin->checkStates()
``` 

sql-errors.log
No sql error.

**Comment by btry** [comment]
Utilisez plutôt le marketplace pour installer des plugins.

Les 2 erreurs ont eu lieu suite à quoi ? On dirait que la procédure d'upgrade n'a pas été faite pour arriver à ces erreurs.

Vous devriez envisager de restaurer le plugin et la BDD à leur état précédent votre première tentative d'upgrade, puis vérifier que le plugin est présent uniquement dans marketplace/, installer la nouvelle version depuis le marketplace et tenter la procédure d'upgrade depuis l'UI de GLPI. Prévoyez une connection au serveur avec un terminal en cas de souci d'upgrade.

**Comment by RomOne78** [comment]
La restauration de la BDD a résolue l'ensemble de mes problèmes car j'avais déjà réinstallé la version formcreator 2.13.7.
_Heureusement que j'avais mis il y a quelques jours un backup quotidien ça a limité les pertes_

Un grand merci pour tes conseils et la super réactivité des réponses.
