### ISSUE TITLE
Problèmes de redirection PHP en modifiant/répondant à un ticket

### ISSUE THREAD

**Issue by Zargui** [pluginsGLPI/formcreator#3430]
**Describe the bug**
Quand Form Creator est activé, quand on répond à un ticket ou qu'on attribue le ticket à un utilisateur, GLPI nous retourne une page blanche avec l'URL https://glpi.xxxx.net/front/itilfollowup.form.php. On reste bloqués sur cette page indéfiniment. Si on fait Retour, on revient sur la page du ticket et la réponse a pourtant bien été envoyée (ou tech attribué). Si à la place on actualise la page, le navigateur nous demande de confirmer puis on arrive sur une page GLPI nous indiquant "L'action que vous avez réalisée n'est pas autorisée.".
Nous avons testé en désactivant Form Creator, le problème disparait.

**To Reproduce**
- Installer puis activer Form Creator
- Recevoir un ticket puis soit y ajouter une réponse, soit y attribuer un technicien.
- Page blanche apparait avec l'URL php

**Expected behavior**
Fonctionnement normal de GLPI, lorsqu'on ajoute une réponse la page s'actualise avec la nouvelle réponse. Même chose si on attribue un technicien.

**Screenshots**

![image](https://github.com/pluginsGLPI/formcreator/assets/36511190/15d6ab3b-2b5d-4aca-8452-b7e3c8004918)

Quand on actualise la page :
![image](https://github.com/pluginsGLPI/formcreator/assets/36511190/a7bfcb78-df21-44fa-b9ca-60c145f7c55b)

![image](https://github.com/pluginsGLPI/formcreator/assets/36511190/a2a40c78-a0e7-442e-a52e-28d220cafa22)

**GLPI / Plugins (please complete the following information):**
- GLPI version 10.0.6
- Liste de tous les plugins installés : 
     - Cycle de vie des matériels v2.8.1
     - Form Creator v2.12.8
     - Oauth IMAP v1.4.1
     - Ticket Cleaner v4.0.2

**Desktop (please complete the following information):**
 - OS: Windows 10 60bits
 - Browser : Chrome
 - Version 120.0.6099.71

**Comment by btry** [comment]
Bonjour

Le problème vient de la page blanche. Si vous revenez en arrière et tentez de soumettre des données, c'est normal que GLPI affiche un erreur.

Quand une page blanche s'affiche, c'est en général zacause d'une erreur fatale. Elle doit être enregistrée dans php-errors.log. reproduisez la page blanche puis regardez si il y a une erreur correspondante vers la fin du fichier.

**Comment by Zargui** [comment]
Bonjour,
Les logs renvoyaient une erreur 408.
En regardant la doc de Form Creator j'ai vu que la plus ancienne version de glpi supportée était la 10.0.6 celle qui était installée sur le serveur. J'ai donc mis à jour glpi en 10.0.10 et pour le moment je ne rencontre plus le problème.

Merci pour votre réponse
