### ISSUE TITLE
[Plugin Formcreator 2.13.8][GLPI 10.0.10] visibility private data.

### ISSUE THREAD

**Issue by mchuche** [pluginsGLPI/formcreator#3431]
**Describe the bug**
In the service catalog, when you use Self-Service profil (End user) with the search tools "My requests for assistance" and select "Issues - Name" + "is", it's not your own ticket list but all issues. What's more, you can display the preview with a mouse over (information bubble).

**To Reproduce**
GLPI 10.0.10 + Formcreator 2.13.8
Self-service profile in service catalogue 
==> "My requests for assistance"
==> "Issues name" + "is"
put the cursor in right list result. 
an informative bubble appaire with private information

![bug service catalogue visiblité](https://github.com/pluginsGLPI/formcreator/assets/1767422/4cd0ce1e-fcb0-4f88-9938-4d3d7e04dc1c)

**Desktop**
Up to date : Windows 10 - Chrome or Firefoxe

**Comment by btry** [comment]
I don't finds a better solution than forbidding the operator "is". Restricting the dropdowns is really tricky.

PLease try this patch

```diff
diff --git a/inc/issue.class.php b/inc/issue.class.php
index 4b5d2e9ad..b1d6044f2 100644
--- a/inc/issue.class.php
+++ b/inc/issue.class.php
@@ -526,6 +526,10 @@ class PluginFormcreatorIssue extends CommonDBTM {
          'field'              => 'name',
          'name'               => __('Name'),
          'datatype'           => 'itemlink',
+         'searchtype'         => [
+            '0'                  => 'contains',
+            '1'                  => 'not contains',
+         ],
          'massiveaction'      => false,
          'additionalfields'   => [
             '0'                  => 'display_id'
```

**Comment by usrqmor** [comment]
Hi @btry ,
It's good with your solution, user can't use "is" with the title.

**Comment by btry** [comment]
The fix has been merged. Thank you for your feedback
