### ISSUE TITLE
Users can reserve all reservable items, not only the ones of his entities

### ISSUE THREAD

**Issue by fabriceverkor** [pluginsGLPI/formcreator#3436]
**Describe the bug**
Self-Service Users can reserve all reservable items, not only the ones of his entities.

**To Reproduce**
1. Connect on a entity with Self-Service profile
2. Go to Reservations
3. You can reserve an asset on other entities.

**Expected behavior**
User should be able to reserve assets of the entity his connected on.

**Screenshots**

**GLPI / Plugins (please complete the following information):**

    GLPI version : GLPI 10.0.10
    list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
    accounts Name: Accounts Version: 3.0.3 State: Enabled
    Install Method: Marketplace
    fields Name: Additional Fields Version: 1.20.0 State: Enabled
    Install Method: Marketplace
    badges Name: Badges Version: 3.0.0 State: Not installed
    Install Method: Marketplace
    behaviors Name: Behaviours Version: 2.7.2 State: Enabled
    Install Method: Marketplace
    connections Name: Connections Version: 10.0.0 State: Enabled
    Install Method: Marketplace
    datainjection Name: Data injection Version: 2.13.3 State: Enabled
    Install Method: Marketplace
    archimap Name: Diagrams Version: 3.3.0 State: Installed / not activated
    Install Method: Marketplace
    formcreator Name: Form Creator Version: 2.13.8 State: Enabled
    Install Method: Marketplace
    glpiinventory Name: GLPI Inventory Version: 1.2.1 State: Enabled
    Install Method: Marketplace
    geninventorynumber Name: Inventory number generation Version: 2.8.3 State: Enabled
    Install Method: Marketplace
    addressing Name: IP Adressing Version: 3.0.1 State: Enabled
    Install Method: Marketplace
    oauthimap Name: Oauth IMAP Version: 1.4.2 State: Enabled
    Install Method: Marketplace
    genericobject Name: Objects management Version: 2.14.8 State: Enabled
    Install Method: Marketplace
    screenshot Name: Screenshot Version: 2.0.2 State: Enabled
    Install Method: Marketplace
    singlesignon Name: Single Sign-on Version: 1.3.3 State: Enabled
    Install Method: Manual
    tag Name: Tag Management Version: 2.11.6 State: Enabled
    Install Method: Marketplace

**Comment by fabriceverkor** [comment]
Hi All
Has anybody noticed this problem ? Or am I doing something wrong ?
Because If we cannot isolate reservable items in their entities, we will need another tool  for reservations, which would be a pity

**Comment by btry** [comment]
Hi

Show the URL where the problem occurs, please.

**Comment by fabriceverkor** [comment]
Sorry , I think I'm not on the right place for this problem as Reservations is not a plugin.

**Comment by btry** [comment]
Indeed, this is what I wanted to check. Before opening an issue on GLPI, check the entityes of the imacted user, the entities of your asset; including recursivity flag.

**Comment by fabriceverkor** [comment]
I opened a new issue in GLPI github. 
I re-checked :
user is connected to entity A with a profile allowing reservations
He can reserve items of all entities, not only items of entity A
