### ISSUE TITLE
[Formcreator 2.13.18][GLPI 10.0.10] New forms are linked to old tickets

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/formcreator#3441]
Greetings,

I saw some time ago when a user told me he saw requests from another user so I checked.
I found that forms linked to the tickets they created but I dont know why they linked too to old tickets.

So users can see old tickets or information from other users.

**To Reproduce**
Create a form with a Self-service user
Go to the menu "My requests for assistance"
Click on one of your request then go to "Historical"

**Expected behavior**
You may see another form that the one created from another user.

**Screenshots**
![image](https://github.com/pluginsGLPI/formcreator/assets/17316903/019b63bb-1eb8-46d5-85b5-abe33ba57359)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.10
- 
	news                 Name: Alertes                        Version: 1.12.1     State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.21.6     State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.1.5      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Gestion des tags               Version: 2.11.7     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.4      State: Enabled                                 
		Install Method: Marketplace
	metademands          Name: Meta-Demandes                  Version: 3.3.7      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - Windows 10/11
 - Edge
 - Version 120.0.2210.121

Thanks for your help.
Best regards

**Comment by btry** [comment]
Hi

I remember that there was a bug, maybe 2 or 3 years ago, which caused this problem.

It has been solved, but this may persist because of data in a table of the plugin.

You may try to rebuild the assistance requests from glpi console (bin/console command).

Are you able to reproduce this problem with a ticket generated by version 2.13.8?

**Comment by usrqmor** [comment]
Hi @btry,

I apply the command php console plugins:formcreator:syncissues then create a ticket but the problem is still there. 
![image](https://github.com/pluginsGLPI/formcreator/assets/17316903/f6dba290-4786-4c01-8d6d-e11d582a09da)

It still link to ol tickets and it happens for each noew form from what I see

**Comment by usrqmor** [comment]
I don't know if its possible or not to show the menu "My tickets" instead of the menu "Request for assistance" temporary ?

**Comment by btry** [comment]
It is possible by changing the translation. 

But the words have been chosen this wak because the page doesn't shows tickets. It shows a mix of tickets and form answers, based of the technical design of the plugin

**Comment by usrqmor** [comment]
Thanks for the reply. Do you have an idea how to clean the link with the oldest tickets on the forms ? I think it's possible with a SQL query but I prefer to not use this option.
There is some form that users shouldn't see but because of this linking situation with old tickets, we have a problem with private informations on some forms that shoudn't be visible.
Thanks

**Comment by btry** [comment]
I could not investigate yet.

**Comment by usrqmor** [comment]
Hi @btry 
After asking some help from a colleague, I found why I have this problem. 
Some years ago, I couldn't properly update formcreator on my instance and had to delete all the table of the plugin (first in test, then in production after constating no issue).
But i didn't delete the line from the table items_ticket. So after reinstalling and using a lot formcreator, the id of the forms answer are double in the table.

I created 2 queries to delete the double and to delete the old line in the table items_tickets. I used them in my test instance and the problem is solved there. I didn't encounters bug so it seems fine.
But I know that using sql queries can be bad so can you tell me if its fine  ? I can share my queries if needed.

Thank you

**Comment by btry** [comment]
Hi

Based on the vents you described, your analysis is consistent. Your solution is good.

**Comment by usrqmor** [comment]
Thanks for the reply and for you help.
Have a nice day !
