### ISSUE TITLE
Error log PHP dashboard.class.php, init sesion

### ISSUE THREAD

**Issue by calidadcarm** [pluginsGLPI/formcreator#3442]
We are getting the following error in the GLPI php log:

![image](https://github.com/pluginsGLPI/formcreator/assets/50906293/69afb86b-f420-4e9f-88e8-c3691f1579c8)

After the analysis carried out on our part, it tells us that the session variables within the following section are null or do not exist:

**inc\dashboard\dashboard.class.php**

Null session variables:

-  $_SESSION['glpiactiveentities'] 
- $_SESSION['glpiprofiles'] 
- $_SESSION['glpigroups']

function **checkRights**

In the following condition that I attach indicates that the variables are empty or null, the following error must be reported to us.

![image](https://github.com/pluginsGLPI/formcreator/assets/50906293/6524ddd5-61a9-4c5e-9238-37dc868c6faf)

Simply tell them if this error has been reproduced, or if they have any way to solve the case.

Any information would be helpful to us.

We look forward.

**Comment by btry** [comment]
Hi

I don't see anything which is related to Formcreator ? Are you sure that you should report it here ?

**Comment by calidadcarm** [comment]
Hi, 

Sorry.

Thank.
