### ISSUE TITLE
[glpi 10.0.10 forms 2.13.8] glpi object not link to the problem or the ticket

### ISSUE THREAD

**Issue by jeje57** [pluginsGLPI/formcreator#3443]
To Reproduce
Accept a form with ticket or problem creation.

Expected behavior
In the ticket section "items", the elements previously selected in the form are displayed

Screenshots
http://forum.glpi-project.org/viewtopic.php?pid=348685#p348685

Desktop (please complete the following information):

OS: Windows 10
Browser chrome, firefox
Version newest
Additional context

when I create a form with a possibity to select a "glpi object", the created "problems" are not link to the glpi object selected in the form.

I've check all suggestion found on this ticket : #1014 

![image](https://github.com/pluginsGLPI/formcreator/assets/30655098/13ba2371-a317-4a7f-a280-96fd9c213482)
![image](https://github.com/pluginsGLPI/formcreator/assets/30655098/a7edccd9-d132-40e6-95ae-685bc40f2381)
![image](https://github.com/pluginsGLPI/formcreator/assets/30655098/c35a2d6b-e356-45a8-bd42-df71a7e4531f)
![image](https://github.com/pluginsGLPI/formcreator/assets/30655098/f6d2d08b-a10e-4f5e-b036-7ea66eee52ac)

**Comment by btry** [comment]
Hi

You probably not configured the target properly. You need to explictly tell that the GLPI object question must be used to fill the associated element. (Only 1 item can be associated, this is a limitation of the plugin)
![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/7542bf18-5d4a-4bc9-817a-8eeb3f1d4438)

**Comment by jeje57** [comment]
ok, that's it! thanks. 

but, is there any reason not to have this feature for the target "problem"?

**Comment by jeje57** [comment]
Thank you for the information. If we need to do this, I create a feature request.
