### ISSUE TITLE
Pregunta tipo Descripcion no se puede editar

### ISSUE THREAD

**Issue by MonteroJR** [pluginsGLPI/formcreator#3445]
**Describe the bug**
Al crear una pregunta de tipo "Descripcion" no se puede editar despues de crear.

**To Reproduce**
1. Crear pregunta tipo Descripcion
2. Hacer click para editarla
3. No hace nada

**Expected behavior**

**Screenshots**

**GLPI / Plugins: FormCreator 2.13.7
- GLPI version: 10.0.11
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment]
Hi

I don't reproduce with Formcreator 2.13.8 + unreleased bugfixes. Upgrade the plugin and feedback if you still reproduce.

**Comment by MonteroJR** [comment]
Todo bien, disculpad, actualicé el navegador y bien
