### ISSUE TITLE
Supprimer les réponses de formulaire pour alléger la base de données

### ISSUE THREAD

**Issue by paidge** [pluginsGLPI/formcreator#3450]
**Is your feature request related to a problem? Please describe.**
Les réponses de formulaires surchargent la base de données pour rien puisque nous avons des tickets cibles pour chacun de nos formulaires. J'ai voulu supprimer ces réponses mais cela m'a supprimé les tickets qui y étaient liés ! 750 tickets en cours se sont retrouvés dans la corbeille et 27000 notifications par mail étaient en attente d'être envoyées ! Ce qui a saturé le disque dur de la VM et rendu la plateforme inaccessible.

**Describe the solution you'd like**
Il serait souhaitable de pouvoir supprimer les réponses de formulaire sans pour autant que cela supprime les tickets cibles qui y sont liés

**Describe alternatives you've considered**
Une purge automatique des réponses de formulaire

**Comment by btry** [comment]
Bonjour

Pouvez-vous vérifier la configuration du profil utilsiateur utilsié au moment de supprimer les réponses ?

Je pense que les réponses aux formulaires font partie des types associables à un ticket.

**Comment by paidge** [comment]
J'ai effectué cette action avec un profil Super-Admin personnalisé. Effectivement les réponses de formulaires sont associées (associables) avec un ticket. A quel endroit je peut modifier ce comportement ?

**Comment by btry** [comment]
On ne peut pas se permetre de retirer les réponses aux formulaires de la liste, ou vous perdrez l'affichage de ce type d'élément depuis les tickets (onglet objets associés). 

Ca pourrait être fait provisoirement, le temps de supprimer les réponses; mais ce n'est pas le comportement voulu dans le plugin. Il est souhaitable de conserver les tickets.


Heureusement la solution semble simple, vous pouvez utiliser une instance de tests pour essayer le fix ci-dessus.

**Comment by paidge** [comment]
Merci. J'ai testé le fix ci-dessus sur une instance de test. J'ai supprimé la réponse à un formulaire sans que cela supprime le ticket qui y était lié. Cela a donc l'air de fonctionner. Est-ce que cette feature pourra être implémentée d'une manière ou d'une autre dans une future release ?
