### ISSUE TITLE
getDropdownValue ajax function thrown sql ambigous error with oject GLPI field

### ISSUE THREAD

**Issue by Aurely9n** [pluginsGLPI/formcreator#3452]
Hi everyone,

The "GLPI object" of the formcreator plugin field throw an sql error when a self-service user try to retrieve a ticket from.
The error only appear when a self-service user try to search a ticket. More elevated users role can acces list of tickets whitout any problem.
This field is no longer usable in this case but we need information (title and id) of a ticket in the form the self-service user want to submit.

Thx for your help.

**To Reproduce**
1. Create form with one field type "GLPI object" with formCreator plugin
2. Setup field on "tickets" (other settings no longer change the issue)
3. Save form
4. Try to fill it with self-service user, the list stay emtpy, impossible to use autocomplete search andlog/sql-error.log show error sql "id... is ambigous" thrown by DBmysql::doQuery()
5. Try to fill it with other privileges and list is ok.

**Expected behavior**

Just want to add list of tickets and ids which i can pick when using autocompletion field GLPI object

**GLPI / Plugins :**
- GLPI version 10.0.2
- Form Creator                   Version: 2.13.8     State: Enabled                                 
- FusionInventory               Version: 10.0.6+1.1 State: Enabled                                 
- Imports fabricants            Version: 3.0.5      State: Enabled                                 
- Oauth IMAP                    Version: 1.4.3      State: Enabled

**Comment by btry** [comment]
Hi

Please share the SQL error and its backtrace.

**Comment by Aurely9n** [comment]
> I see where the bug occurs in the SQL query; I think i'll have time in a few days to search the fix.

Hello there !
Did you find any solution for this issue ?
Can we hope for a patch soon (if it's possible for sure)?

Thx

**Comment by Aurely9n** [comment]
> Hi
> 
> Could you try this patch ?
> 
> Be careful, I'm not sure I choosed the right table, then check the results to see if there is no unwanted item in the list.
> 
> ```diff
> diff --git a/inc/field/dropdownfield.class.php b/inc/field/dropdownfield.class.php
> index 725de4de2..23c0e190f 100644
> --- a/inc/field/dropdownfield.class.php
> +++ b/inc/field/dropdownfield.class.php
> @@ -245,7 +245,7 @@ class DropdownField extends PluginFormcreatorAbstractField
>                    ],
>                 ]);
>                 $tickets_filter[] = [
> -                  'id' => $requestersObserversQuery,
> +                  Ticket::getTableField('id') => $requestersObserversQuery,
>                 ];
>              }
>  
> ```

Hi,
Your patch works perfectly !
It's a go for a release ;)

Thanks

**Comment by btry** [comment]
Hi

No, I won't release any new version of Formcreator : the plugin reached its end of life because forms will be avalable in GLPI 11, and this makes this plugin obsolete. 

If you use 2.13.8 and have some patches, keep them just in case. you need to rebuild your instance.

**Comment by btry** [comment]
Fix pushed in the branch

https://github.com/pluginsGLPI/formcreator/commit/3c0630554e13dff1f604faa9de5f03c04eee9efa

Thank you for your feedback

**Comment by Aurely9n** [comment]
> No, I won't release any new version of Formcreator : the plugin reached its end of life because forms will be avalable in GLPI 11, and this makes this plugin obsolete.
> 
> If you use 2.13.8 and have some patches, keep them just in case. you need to rebuild your instance.

Ok. I didn't knew that forms will be integrated to GLPI 11.

Thx for your replies and help.
