### ISSUE TITLE
Valider formulaire ne crée pas de ticket

### ISSUE THREAD

**Issue by Zargui** [pluginsGLPI/formcreator#3459]
Bonjour,

J'utilise GLPI version 10.0.12 avec FormCreator version 2.13.8.
La création de formulaires fonctionne bien, en revanche lorsque je valide le formulaire cela ne crée pas de ticket dans GLPI.
Est ce que quelqu'un saurait de quoi ça peut venir ?

Merci

**Comment by VincentLegros** [comment]
Bonjour,
Question très bete, avez vous défini une target pour votre formulaire de type ticket ?

**Comment by Zargui** [comment]
Bonjour, merci pour  votre réponse
En effet je n'avais pas rempli ce champ. C'est fait, et ça fonctionne désormais, la validation de formulaire crée bien un ticket.
Merci beaucoup
