### ISSUE TITLE
Validator see forms from other validators

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#346]
Thomas Müller can see all forms. Edit: 	0.90-1.4-beta5
![bug2-1](https://cloud.githubusercontent.com/assets/19192087/20502504/99b13da0-b03e-11e6-9e12-281e2b9a13e0.JPG)

![bug2](https://cloud.githubusercontent.com/assets/19192087/20502503/99afea4a-b03e-11e6-8bb5-a3c9a6b7fede.JPG)

![bug2-2](https://cloud.githubusercontent.com/assets/19192087/20502502/99aeb81e-b03e-11e6-8169-b07e5f782cee.JPG)

**Comment by Armin83** [comment]
The bug is still present in version 2.4.1.

**Comment by btry** [comment]
Hi

Can you use a testing environment to try the version 2.5.1 ?

I plan to release a new release within 2 ou 3 weeks, so let's work on this issue to solve it.

**Comment by Armin83** [comment]
Hi,

my failure in the post. i tested on my Testsystem 

Formulare | 2.5.1 | GPLv2 | Enabled
GLPI 9.1.5

best regards
Armin

**Comment by dcoronel1985** [comment]
To solve this problem you must do the following:

in formcreator/inc/form.class.php

change the query:

         /*$query = "SELECT fa.`id`, f.`name`, fa.`status`, fa.`request_date`
                FROM glpi_plugin_formcreator_forms f
                INNER JOIN glpi_plugin_formcreator_forms_validators fv ON fv.`plugin_formcreator_forms_id`=f.`id`
                INNER JOIN glpi_plugin_formcreator_forms_answers fa ON f.`id` = fa.`plugin_formcreator_forms_id`
                WHERE (f.`validation_required` = 1 AND fv.`items_id` = '$userId' AND fv.`itemtype` = 'User'
                   OR f.`validation_required` = 2 AND fv.`items_id` IN ($groupIdList) AND fv.`itemtype` = 'Group'
                )
                AND f.is_deleted = 0
                ORDER BY fa.`status` ASC, fa.`request_date` DESC
                LIMIT 0, 5";
         $result = $DB->query($query);*/

By the following:

 $query = "SELECT fa.`id`, f.`name`, fa.`status`, fa.`request_date`
                FROM glpi_plugin_formcreator_forms f
                INNER JOIN glpi_plugin_formcreator_forms_validators fv ON fv.`plugin_formcreator_forms_id`=f.`id`
                INNER JOIN glpi_plugin_formcreator_forms_answers fa ON f.`id` = fa.`plugin_formcreator_forms_id`
                **WHERE (f.`validation_required` = 1 AND fv.`items_id` = '$userId' AND validator_id = '$userId'**
                   OR f.`validation_required` = 2 AND fv.`items_id` IN ($groupIdList) AND fv.`itemtype` = 'Group'
                )
                AND f.is_deleted = 0
                ORDER BY fa.`status` ASC, fa.`request_date` DESC
                LIMIT 0, 5";
         $result = $DB->query($query);

I solved it that way and it works perfect.

GLPI version 9.1.4 
FormCreator version 2.5.1

Regards!

**Comment by btry** [comment]
Hi @dcoronel1985 

Indeed you found the bug, thank you for sharing.

However, I implemented it slightly differently, and extended your fix to validator group, because I think there is a similar problem here too.

@Armin83 and @dcoronel1985 can you check it works for user valdiator and group validator if possible ?

I wish to include this fix in version 2.5.2, to be released soon.

**Comment by btry** [comment]
Hi

No feedback, but the fix as I did should work for you too. Need to close to merge and release it.

**Comment by dcoronel1985** [comment]
Hello sorry for the delay, it works fine as you passed it.

Regards!

**Comment by btry** [comment]
Thank you.

The fix is in the version I released this morning.
