### ISSUE TITLE
Update ignoring customizations to files

### ISSUE THREAD

**Issue by bonnyfrances** [pluginsGLPI/formcreator#3464]
**Describe the bug**
Updated formcreator this morning to 2.13.8. It appears the update is ignoring customizations to source files. Specifically, changing the term "Forms" to "Create a ticket" that appears in the Assistance menu in inc/formlist.php and removing the giant bold "Form data" from the target ticket in inc/formanswer.class.php. These changes enhance UX for our users.

**To Reproduce**
Cannot reproduce the error like a typical bug. 

**Expected behavior**
String changes would appear in UI

**Screenshots**
![image](https://github.com/pluginsGLPI/formcreator/assets/14313832/43357ec5-b3c2-4b4a-b48a-94ae0869903f)
![image](https://github.com/pluginsGLPI/formcreator/assets/14313832/c221209c-d147-4f81-ab3e-f627fd5e6971)
![image](https://github.com/pluginsGLPI/formcreator/assets/14313832/6b86f455-1538-444b-97cc-0c14f056bf61)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.12
- fields               Name: Additional Fields              Version: 1.20.0     State: Not installed                           
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.10.5     State: Enabled                                 
		Install Method: Marketplace
	certificates         Name: Certificates                   Version: 2.3.0      State: Not installed                           
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.0     State: Installed / not activated               
		Install Method: Marketplace
	**formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Marketplace**
	ldapcomputers        Name: LDAP computers                 Version: 0.4.1      State: Not installed                           
		Install Method: Manual
	loginbyemail         Name: Login By E-mail                Version: 1.0.0      State: Not installed                           
		Install Method: Manual
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Installed / not activated               
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.3      State: Not installed                           
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.5      State: Installed / not activated               
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Installed / not activated               
		Install Method: Marketplace
	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Not installed                           
		Install Method: Manual
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	screenshot           Name: Screenshot                     Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Enabled                                 
		Install Method: Marketplace
	ticketmail           Name: Ticket Mail                    Version: 3.6.2      State: Enabled                                 
		Install Method: Manual

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 122.0.6261.57

**Additional context**

**Comment by btry** [comment]
Hi

If you change the source code, you are responsible of keeping patches and re applying them when you upgrade the plugin. this is true for GLPI, and any other plugin.
