### ISSUE TITLE
Event After ticket submission

### ISSUE THREAD

**Issue by NukerMaster** [pluginsGLPI/formcreator#3465]
**Is your feature request related to a problem? Please describe.**
The issue we are facing is that after a ticket submission users get a small notification pop up on the right side telling them the ticket has been sent. Problem is the form is still there , so they keep pressing the button twice or more and we end up with the same ticket multiple times.

**Describe the solution you'd like**
Isnt there a way to add an event after a ticket submission ? or redirect to a different confirmation page ?

**Describe alternatives you've considered**
Directly changing the source code which i think is not suitable...

**Additional context**
i've looked everywhere on forums and such and did not find any answer. no one else is getting this issue ?

Thank you
best regards

**Comment by btry** [comment]
Hi

After submission, the browser should be redirected to a new page, except if the user tested the form in preview mode.

Try to open developer tools in the browser, reproduce the issue, and check if you have JS errors. Also, check the HTTP requests sent after clicking the submit button. One of them shall return JSON data which instructs the JS code of the plugin how to redirect.

**Comment by NukerMaster** [comment]
here's what i see in console mode after submitting : 

Uncaught TypeError: Cannot read properties of null (reading 'find')
    at blockFormSubmit (common.min.js?v=6639ee217e8a256d74c62e4eda3a365e2fd099f1:33:18323)
    at Object.submitUserForm (scripts.js?v=ed36fa1d2295a3f98895323d49c72d7215b4f8bc:1397:7)
    at HTMLFormElement.onsubmit (formdisplay.php?id=9:1677:391)

**Comment by NukerMaster** [comment]
> Hi
> 
> After submission, the browser should be redirected to a new page, except if the user tested the form in preview mode.
> 
> Try to open developer tools in the browser, reproduce the issue, and check if you have JS errors. Also, check the HTTP requests sent after clicking the submit button. One of them shall return JSON data which instructs the JS code of the plugin how to redirect.

here's what i see in console mode after submitting :

Uncaught TypeError: Cannot read properties of null (reading 'find')
at blockFormSubmit (common.min.js?v=6639ee217e8a256d74c62e4eda3a365e2fd099f1:33:18323)
at Object.submitUserForm (scripts.js?v=ed36fa1d2295a3f98895323d49c72d7215b4f8bc:1397:7)
at HTMLFormElement.onsubmit (formdisplay.php?id=9:1677:391)

**Comment by btry** [comment]
Can you tel the version of Formcreator used, and the version of GLPI used ?

**Comment by NukerMaster** [comment]
> Can you tell the version of Formcreator used, and the version of GLPI used ?

GLPI 10.0.3 and FormCreator 2.13.8

**Comment by NukerMaster** [comment]
Found the issue : [https://github.com/glpi-project/glpi/commit/e68249f55590873cc72b213761041f40ad1ca6d6](url)

We gotta update
