### ISSUE TITLE
[2.13.8] : Cluster Object no more visible in glpi object ?

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/formcreator#3467]
Hello

It's not possible to choose cluster object
in 2.12.4 : 
cluster is seen in the glpi object selector -> I added the cluster type in glpiselectfield class and change type either

in 2.13.8 : 
cluster type is not in the list and change neither -> normal

but it would be good to add cluster type too 

in question.class.php
line 1236 add : 
            Cluster::class            => Cluster::getTypeName(2),

**Comment by btry** [comment]
Hi

As there will not be any  new release of the plugin, just apply your patch on 2.13.8. I'll commit the change in the branch support/2.13.0 but I don't expect to release it.

**Comment by EC2311** [comment]
just a comment : 
what do you mean by 'any new release' ? this plugin will be included in GLPI ?

**Comment by btry** [comment]
GLPI will implement forms in the next version. This is why no new feature will  be added in this plugin and (except major problem) no new release of Formcreator will be published.
