### ISSUE TITLE
Possibility to add open and close date

### ISSUE THREAD

**Issue by nuria2c** [pluginsGLPI/formcreator#3469]
It could be very usefull to add the open and the close date in the form definition as a NOT compulsory fields. 

Some forms are not available for all the time. Some of them are active only for a specific períod. Now we manage this situation changing the state of the form "Active: Yes/No" manually. 

We propose:
1. Add 2 fields in the form definition: open date / close date
2. If ther are dates defined in the form, show these dates in the forms user interface with a text like
Open from [open date] to [close date]
3. In the forms interface check these two dates. If we are in the period between the open amd theclose date, show the form as active and open. If we are out of this period, show the form but without the option to fill it.

**Comment by btry** [comment]
Hi

No new feature will be added to the plugin because forms are being implemented in GLPI. Please wait for the beta / final major release of GLPI to propose new features.

**Comment by nuria2c** [comment]
Do you have any idea when this realise will be available?
