### ISSUE TITLE
Validator can accept forms from other validators 

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#347]
Validator accept forms from other validators. 	0.90-1.4-beta5

Thomas Mueller accepted one form but he wasn't the validator.

![id1](https://cloud.githubusercontent.com/assets/19192087/20502579/f94a35f0-b03e-11e6-9b81-e74f71073a2e.jpg)
![id1-approve](https://cloud.githubusercontent.com/assets/19192087/20502578/f943091a-b03e-11e6-839a-6b5d43820fb4.jpg)

**Comment by btry** [comment]
Hi

the PR #348 should fix this issue.

Can you test it ?

Please not it does not disable display of forms as you mentionned in #346.

**Comment by Armin83** [comment]
Don't know how to install this patch fast, so i take the master.zip from git. 
On targets i get this error with debug mode / otherwise it's display "loading":
`Fatal error: Uncaught Error: Call to a member function fetch_array() on boolean in /var/www/html/glpi/inc/dbmysql.class.php:282 Stack trace: #0 /var/www/html/glpi/plugins/formcreator/inc/form_profile.class.php(68): DBmysql->fetch_array(false) #1 /var/www/html/glpi/inc/commonglpi.class.php(477): PluginFormcreatorForm_Profile::displayTabContentForItem(Object(PluginFormcreatorForm), '1', '') #2 /var/www/html/glpi/ajax/common.tabs.php(97): CommonGLPI::displayStandardTab(Object(PluginFormcreatorForm), 'PluginFormcreat...', '', Array) #3 {main} thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 282`


after that i tryed to deinstall plugin and reinstall but i got this:
Change of the database layout - glpi_plugin_formcreator_forms_profiles (0 seconds)

0.90-1.4-beta5 multiple alter in glpi_plugin_formcreator_forms_profiles - Error during the database query: ALTER TABLE `glpi_plugin_formcreator_forms_profiles` CHANGE `plugin_formcreator_profiles_id` `profiles_id` INT(11) NOT NULL DEFAULT '0' , ADD `id` INT(11) NOT NULL DEFAULT '0' , ADD PRIMARY KEY `id` (`id`) , ADD UNIQUE KEY `unicity` (`plugin_formcreator_forms_id`, `profiles_id`) , ADD `uuid` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL - Error is Duplicate entry '0' for key 'PRIMARY'

I think it's not easy to test for me.

**Comment by btry** [comment]
Hi  I had to update the patch yesterday to prepare merge into master.

Some important changes needs you upgrade the plugin.

Use CLI on your test server, go to the directory of formcreator. Then run the following

php tools/cliinstall.php 

The plugin should be up to date and the errors you encoutered no longer happen.

**Comment by btry** [comment]
FYI : the patch is now in master, this might be easier for you to test

**Comment by Armin83** [comment]
thank you, yes you are right for cliinstall i need to fill the params... ;)
Now it works correct. I hope the other problem - view foreign forms will be solved also.
