### ISSUE TITLE
La liste des catégories dans la FAQ, n'est pas classé par Ordre croissant, mais alphabétique décroissant.

### ISSUE THREAD

**Issue by glionel** [pluginsGLPI/formcreator#3488]
Boinjour.

**Describe the bug**
En mode Self-Service, quand la FAQ est dans un menu distinct, la liste des catégories de la FAQ, n'est pas classé par Ordre croissant, mais alphabétique décroissant.

![Capture d'écran 2024-04-04 133721](https://github.com/pluginsGLPI/formcreator/assets/12128907/51623d5b-bb43-4ba1-a51e-285adf831d1c)

**To Reproduce**
Activer la base de connaissance sur l'entité "**Entrée de manu distincte**"
Activer l'affiche de la base de connaissance sur le profil (ici Self-Service pour moi)
Etre en Self-Service pour voir le menu des formulaires et de la FAQ

**Expected behavior**

La liste des catégories des formulaires sont bien classés par ordre alphébétique. Mais pas la liste des catégories de la FAQ.

**Screenshots**
![Capture d'écran 2024-04-04 135311](https://github.com/pluginsGLPI/formcreator/assets/12128907/6ef5ca0b-363e-4b4a-88b3-eb601b1053b7)

**GLPI / Plugins (please complete the following information):**
- GLPI version :10.0.11
behaviors            Name: Comportements                  Version: 2.7.3      State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalades                      Version: 2.9.2      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.7     State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Not installed                           
		Install Method: Manual
	satisfaction         Name: Plus de satisfaction           Version: 1.6.2      State: Enabled                                 
		Install Method: Manual
	vip                  Name: VIP                            Version: 1.8.2      State: Enabled                                 
		Install Method: Manual

**Desktop (please complete the following information):**
 - Windows
 - EDGE / Chrome (123.0.2420.65 / 123.0.6312.105)

**Comment by glionel** [comment]
Pas solution ?

**Comment by btry** [comment]
Bonjour

Je pense que c'zest pas grand chose.

Essayez ce patch 


```diff
diff --git a/inc/knowbase.class.php b/inc/knowbase.class.php
index aa8019f1c..f872ebb25 100644
--- a/inc/knowbase.class.php
+++ b/inc/knowbase.class.php
@@ -136,7 +136,7 @@ class PluginFormcreatorKnowbase {
          'FROM' => $cat_table,
          'ORDER' => [
             KnowbaseItemCategory::getTableField('level') . ' DESC',
-            KnowbaseItemCategory::getTableField('name'),
+            KnowbaseItemCategory::getTableField('name') . ' DESC',
          ]
       ]);
 
````
