### ISSUE TITLE
Modifier la couleur du titre d'une question d'un formulaire

### ISSUE THREAD

**Issue by CecileInfanti34** [pluginsGLPI/formcreator#3493]
Bonjour, 

Je souhaiterais modifier la couleur de police de caractères d'un titre d'une question d'un formulaire. Est-ce possible ?
Par exemple, je souhaiterais afficher "Vous êtes" en rouge. 
![Capture d'écran 2024-04-16 113108](https://github.com/pluginsGLPI/formcreator/assets/138763743/7bc7c795-1995-4e88-b62b-968cd4a98519)
Merci pour votre aide.

GLPI GLPI 10.0.14 
Formcreator 2.13.9

**Comment by btry** [comment]
Bonjour

Regardez dans le CSS custom que vous pouvez configurer dans les entités. Et pour ce genre de questions, c'est le [forum communautaire](https://forum.glpi-project.org/) qui est le plus approprié. Ici c'est pour les demandes de features et les rapports de bug.

Notez qu'il n'y aura plus de feature pour le plugin, car il sera  remplacé par une implémentation native dans GLPI 11.

**Comment by CecileInfanti34** [comment]
Merci pur votre réponse, et désolée, je ne connaissais pas le forum communautaire. Je vais regarder dans le CSS custom, je cloture mon ticket, si j'ai besoin d'aide , j'en ferais un sur le forum, au bon endroit : ) Merci encore
