### ISSUE TITLE
Proposed features - Show section and Multiple conditions

### ISSUE THREAD

**Issue by J-n-s** [pluginsGLPI/formcreator#35]
- Add an "Other" option on Checkboxes and Radios that automatically adds a text field
- Add "Show section" option on Section (show this section only if fields...)
- Multiple conditions for "Show field" (ex: only if field A=0 and B=1)

Thank you and congratulations for this plugin :)

**Comment by btry** [comment]
Multiple conditions in PR #383

**Comment by btry** [comment]
Show section on condition also done.

The "other" option can be done with a text field displayed when a checkbox "other" or a radio "other" is selected, thanks to conditions. 

I think this issue can be closed.
