### ISSUE TITLE
Ao tentar instalar o formcreator na versão 10.0.15 apresentou erro :

### ISSUE THREAD

**Issue by gspgaby** [pluginsGLPI/formcreator#3509]
Ao tentar instalar o formcreator na versão 10.0.15 apresentou erro : 

O esquema do banco de dados não é consistente com a versão anterior do Formcreator 2.14.0-dev. Para ver os logs execute o comando bin/console glpi:plugin:install formcreator -f

![image](https://github.com/pluginsGLPI/formcreator/assets/61751324/e30fb84d-9746-463a-a902-05221adbb5a5)

Tentei rodar o comando solicitado porem não adiantou:

![image](https://github.com/pluginsGLPI/formcreator/assets/61751324/781555d8-63d9-4066-aa4e-7e1f8afa89fb)

**Comment by btry** [comment]
Hi

Is it a fresh install or an upgrade of  the plugin ? 

Why did you use the skip-db-check argument ? The database sanity check is here to protect your database against such problems.

**Comment by gspgaby** [comment]
It's a fresh install, I used skip-dB-check because I hadn't done it without it, so I tested it this way but I still couldn't install it

**Comment by btry** [comment]
I think  that the installation process found data from a previous installation of the plugin. For some reason it was not properly uninstalled.

Remove all tables with a name beginning with ```glpi_plugin_formcreator_```

execute the following SQL queries. The first to view the rows to be deleted by the 2nd one. (I expect 2 rows)

```sql
select * from glpi_configs where context='formcreator';
```

```sql
delete from glpi_configs where context='formcreator';
```

**Comment by gspgaby** [comment]
It worked, thanks
