### ISSUE TITLE
Modify order of forms

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#351]
Hello 

It would be useful to have the possibility to select sort of forms

Example :+1: 
I would like to have at first forms Incident and after ...

**Comment by etiquet** [comment]
Hi the option we're using is to add a number in front of the form.
ex: 
1- Form xxx
2- Form zzz

**Comment by chagasgb** [comment]
would be very useful!!

**Comment by btry** [comment]
Hi

From the requester point of view, forms are ordered alphabetically or by popularity. The default will be tunable in the entity soon. 

Ordering the forms does not makes sense as the order would be global to all forms and may be hard to manage when you have a lot of forms (some users have more than 80). I think it is better to rely on categories, and maybe I could order the forms by category in the output, if not already done (I need to check in the code).

**Comment by rpauleau** [comment]
Hi,

In the meantime to change the default order you can modify this file

line 179 of the ./js/scripts.js.php file

mostPopularSort replace with alphabeticSort

`// Initialize sort controls`
      `$('.plugin_formcreator_sort input[value=alphabeticSort]')[0].checked = true;`

**Comment by rpauleau** [comment]
Bonjour,

Je suis très intéressé par cette option aussi. Si vous connaissez le ou les fichiers à modifier pour avoir l'ordre alphabétique par défaut en attendant je suis aussi preneur

Cordialement

**Comment by btry** [comment]
Boonjour @rpauleau : La focntionnalité que vous attendiez est disponible.  Il n'y a par contre pas d'autre forme de tri disponible.

**Comment by rpauleau** [comment]
Bonjour,

D'accord merci pour l'information

**Comment by btry** [comment]
Hi

This is not posible to sort forms by type (incident or request) because forms may generate 0 to N tickets, each ticket having a different type. As alphabetical or popularity sort are available, I think we can close this issue.
