### ISSUE TITLE
Ticket de type Demande non généré

### ISSUE THREAD

**Issue by Gaelolito** [pluginsGLPI/formcreator#3512]
GLPI 10.0.05 / Formcreator 2.13.9 / Chrome

**Describe the bug**
Formulaire avec 1 seule question de type "Type de demande", avec aucune valeur par défaut.
![2024-05-31 09_05_36-Formulaires - 1 - GLPI](https://github.com/pluginsGLPI/formcreator/assets/165003634/ef9196c9-b1b4-4c95-beba-fe71dd49b20f)

2 cibles de type "Ticket cible", avec dans propriétés, Request type "Egale à la réponse à la question" / Question "Type" :
- 1 cible avec condition  "Désactivé sauf si" AND Type = "Incident"
- 1 cible avec condition  "Désactivé sauf si" AND Type = "Demande"

En testant le formulaire : 
- ticket créé lorsque réponse à la question est "Incident"
- aucun ticket créé lorsque réponse à la question est "Demande" => il y a bien une réponse au formulaire, mais pas de ticket créé

**To Reproduce**
- Autre test en mettant les conditions ID "1" pour "Incident" et "2" pour "Demande" => aucune création de ticket (Demande ou Incident) / juste réponse au formulaire
- Autre test avec dans propriétés, Request type "Incident" pour la cible avec la condition "Incident" et Request type "Demande" pour la cible avec la condition "Demande"=> même constat, pas de création de ticket de type Demande, mais création ticket de type Incident

**Expected behavior**
Souhait de pouvoir générer les types de tickets Demande et Incident depuis la question "Type de demande"

**Comment by btry** [comment]
Hi

Use English words in the conditions 
incident / request (switch your GLPI to English to check the words and case). This is specific to this question to solve an internal limitation. This is a known problem.

**Comment by Gaelolito** [comment]
Cela fonctionne.
J'avais cherché dans les closed issues sans succès : merci pour votre réactivité et votre résolution.
Have a nice day
