### ISSUE TITLE
Bug in formcreator after upgrade from GLPI 9.X to GLPI 10.0.14

### ISSUE THREAD

**Issue by breguy** [pluginsGLPI/formcreator#3514]
**Describe the bug**
When a user browse to the form list, he can see all the existing forms (that were made and worked before the update)
![image](https://github.com/pluginsGLPI/formcreator/assets/171543692/42c5ed1e-5e7a-4da4-b141-4c8be083c255)

But when clicked, the forms aren't displaying.
![image](https://github.com/pluginsGLPI/formcreator/assets/171543692/fef40651-b063-4695-9a96-c29873ec2dcf)

When an administrator tries to change an existing form, it displays the creation page.
![image](https://github.com/pluginsGLPI/formcreator/assets/171543692/1685ca15-8880-4432-b498-88e4d29e40f6)

On a test server, I tried to :
- Uninstall/Reinstall
- Clear all extension files
- Remove all data related to formcreator in the database (including backup tables)

But the same bug appears everytime !

**To Reproduce**
1. Go to http://xxxxxxx/marketplace/formcreator/front/form.php as super-admin
2. Click on any form
3. The client asks to create a new form (the url looks like http://xxxxxx/marketplace/formcreator/front/form.form.php?id=9)
4. I don't see any php or sql errors in GLPI logs.

**Expected behavior**
I exepect the form to show.

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.14
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page) : 
 	fields               Name: Additional fields              Version: 1.21.8     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.9     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Replaced                                
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	gdrive               Name: GDrive                         Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Marketplace
	metademands          Name: Meta-Demandes                  Version: 3.3.10     State: Enabled                                 
		Install Method: Marketplace

**Desktop (please complete the following information):**
 - OS: Linux/Windows
 - Browser : Chrome/firefox
 - Version : last 

**Additional context**
A SSO is enabled. It was working with it before the update.

**Comment by btry** [comment]
Hi

Can you run the following CLI command ?

```php bin/console db:check -p formcreator```

**Comment by breguy** [comment]
Hi,
it says everything's OK.
![image](https://github.com/pluginsGLPI/formcreator/assets/171543692/c95b7c76-78a8-48e9-934d-50a2af51eeec)

**Comment by breguy** [comment]
Hello,
Any news about this problem ?

**Comment by breguy** [comment]
Solution here :
https://forum.glpi-project.org/viewtopic.php?pid=511006
