### ISSUE TITLE
question: prevent plugin upgrade

### ISSUE THREAD

**Issue by ftoledo** [pluginsGLPI/formcreator#3515]
hello!
We have the plugin patched with some custom opinions and until we can publish them (if feasible).
A complete fork of it is not necessary either. Just a few simple customer-specific patches.
This would be temporary until we define what to do with those patches.

In the meantime, we want to prevent the plugin from being updated from the marketplace.
What is the best way to do this?

**Comment by btry** [comment]
Hi

If you set the permissions to read only in the folder of the plugin, recursively, I think the marketplace will  warn that the plugin cannot be upgraded and your arches will be protected against an overwrite. 

Anyway no new release is expected for Formcreator. It will be replaced by native forms in glpi 11.

**Comment by ftoledo** [comment]
> Hi
> 
> If you set the permissions to read only in the folder of the plugin, recursively, I think the marketplace will warn that the plugin cannot be upgraded and your arches will be protected against an overwrite.
> 
> Anyway no new release is expected for Formcreator. It will be replaced by native forms in glpi 11.

ok perfect, thank you very much for your response.
 Yes that was one of the options we had in mind.
Will forms be within glpi 10.1.x?

**Comment by btry** [comment]
Native forms are in active development, and the target is GLPI 10.1.
