### ISSUE TITLE
Publish a Form w/o Login

### ISSUE THREAD

**Issue by compromis909** [pluginsGLPI/formcreator#352]
I'd like to publish a Form whithout any login needed (anonymously) I am able to set it in properties to public but can not call the form. Do I do something wrong or is ist just not possible?

cheers c909

**Comment by btry** [comment]
Hi

If you give public access to the form, you need to share the URL of the form found in the tab **Targets** of this form.

Try to use this URL after you logged out (or use a private browsing session)

**Comment by compromis909** [comment]
I am not quite sure if i  do something wrong - I can't see any URL except the one in the URL bar of my browser when I am in the Targets tab.
I am using GLPI 9.1.1  whith plugin Version "0.90-1.3.4".
![glpi_forms](https://cloud.githubusercontent.com/assets/11536511/20617421/62031272-b2e9-11e6-886c-1f9a693c2647.png)
P.S. thank you for the quick reply!
cheers c909

**Comment by orthagh** [comment]
hello @compromis909 

The feature (display the link) is the next version (about to be published).
Waiting for this release, you could go to your form (in Assistance > Form), copy the url and provide it to your users.

**Comment by compromis909** [comment]
Hi orthagh,
Oh great! - As I assumed some kind of not getting your answer right! Again, thank you for the quick and great support!

cheers,
c909

**Comment by orthagh** [comment]
Some teasing: 
![image](https://cloud.githubusercontent.com/assets/418844/20618565/143b3ef0-b2f0-11e6-9b55-64fd9f93b1b9.png)
