### ISSUE TITLE
Choix accès par défaut sur Catalogue de service simplifié 

### ISSUE THREAD

**Issue by Gaelolito** [pluginsGLPI/formcreator#3538]
GLPI 10.0.16 + Formcreator 2.13.9
-------------
Default access on Simplified service catalogue 👍 
- Formcreator is set up as a simplified service catalogue.
- Users have simplified interface authorisation.
- When a user logs on to GLPI, can they access the ‘My support requests’ menu by default, rather than the ‘Request support’ menu?
-------------
Choix accès par défaut sur Catalogue de service simplifié :
- Formcreator est paramétré en catalogue de service simplifié.
- Les utilisateurs ont une habilitation sur interface simplifiée.
- Lorsqu'un utilisateur se connecte à GLPI, peut-il accéder par défaut au menu "Mes demandes d'assistance", plutôt qu'au menu "Demander une assistance" ?

![image](https://github.com/user-attachments/assets/fd348a6e-a618-49ce-871a-2f04d9162cc5)

**Comment by btry** [comment]
Hi

Check the settings of the plugin in the entity, tab "Forms". It should be what you're searching for

![image](https://github.com/user-attachments/assets/d6bf43d1-b977-432b-bdc6-7df8b3ed1052)
