### ISSUE TITLE
Ticket incident

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#359]
Hello

I have created a form of ticket incident for users, but the category in form does not modify the category in the ticket, I have to modify manually until the ticket is created.

I have created a ticket template but I cant predefined the category because it change for each ticket.

**Comment by btry** [comment]
hi

This is not implemented. The category is displayed in the description of the ticket if its placeholder is present.

**Comment by satyan01** [comment]
Will you implement this feature ?

**Comment by satyan01** [comment]
it is not possible to send a notification as on ticket to requester and technician

**Comment by btry** [comment]
Are you using the version 1.4-beta ?

**Comment by satyan01** [comment]
yes

**Comment by btry** [comment]
I fixed the opposite bug last 2 weeks. Maybe this will solve your problem. Note it is still in dev .. right now :)

**Comment by satyan01** [comment]
Hello

I have tried to update but 

Change of the database layout - glpi_plugin_formcreator_forms_profiles (1 second)

0.90-1.4-beta6 multiple alter in glpi_plugin_formcreator_forms_profiles - Error during the database query: ALTER TABLE `glpi_plugin_formcreator_forms_profiles` CHANGE `plugin_formcreator_profiles_id` `profiles_id` INT(11) NOT NULL DEFAULT '0' , ADD `id` INT(11) NOT NULL DEFAULT '0' , ADD PRIMARY KEY `id` (`id`) , ADD UNIQUE KEY `unicity` (`plugin_formcreator_forms_id`, `profiles_id`) , ADD `uuid` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL - Error is Duplicate entry '0' for key 'PRIMARY'

**Comment by btry** [comment]
I open a separate issue for this

**Comment by satyan01** [comment]
Thx

**Comment by satyan01** [comment]
problem still here after upgrade

**Comment by btry** [comment]
Lets discuss about this in #363 please

**Comment by satyan01** [comment]
problem still here after upgrade

Hello

I have created a form of ticket incident for users, but the category in form does not modify the category in the ticket, I have to modify manually until the ticket is created.

I have created a ticket template but I cant predefined the category because it change for each ticket.

**Comment by btry** [comment]
Hi

The issue should be solved now. I close this ticket. If the problem persists, please open a new ticket.
