### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#363]
@satyan01 said in #359 (looks like the resulting primary key is not auto increment, and having several entries here fails).

> Hello
> 
> I have tried to update but
> 
> Change of the database layout - glpi_plugin_formcreator_forms_profiles (1 second)
> 
> 0.90-1.4-beta6 multiple alter in glpi_plugin_formcreator_forms_profiles - Error during the database query: ALTER TABLE glpi_plugin_formcreator_forms_profiles CHANGE plugin_formcreator_profiles_id profiles_id INT(11) NOT NULL DEFAULT '0' , ADD id INT(11) NOT NULL DEFAULT '0' , ADD PRIMARY KEY id (id) , ADD UNIQUE KEY unicity (plugin_formcreator_forms_id, profiles_id) , ADD uuid VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL - Error is Duplicate entry '0' for key 'PRIMARY'

**Comment by btry** [comment]
@satyan01 : to answer to the persistence of your issue in #359 : 

if the error persists, you should have a slightly different SQL query. Can you show it please ?

**Comment by satyan01** [comment]
solved

**Comment by btry** [comment]
Can you tell what you did to solve it ?

**Comment by gregfly26** [comment]
Hello,

I have the same issue with affect the form selected category in the ticket.

Could you help me please ?

I use the last release 2.4.1 and GLPI 9.1.2

Thanks in advance for your help.

**Comment by btry** [comment]
Hi 

Please open a new ticket and provide the error message you encouteered, and logs if any.
