### ISSUE TITLE
forms ok but information in ticket missing

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#367]
We have the following error:
We don't have all information in ticket. There is some information missing but in forms view there is all information.

/var/www/glpi/files/_log nothing php-errors
I activated debug mode before.

**Comment by btry** [comment]
hi

Can you provide the following ? 

- glpi version
- plugin version
- which data are missing
- a way to reproduce if you identified it
- maybe some screenshots if you think it may help to identify the issue or how to reproduce.

**Comment by Armin83** [comment]
glpi 9.1.1
 Formulare	0.90-1.4-beta4 [production 👎 we did a mistake in past ]
 Formulare	0.90-1.4-beta6 [test system]

Data from text field is missing you can see it on the forms screenshot. We can reproduce it on our system. We have more questions

![img_019](https://cloud.githubusercontent.com/assets/19192087/20803167/937a629c-b7ee-11e6-812d-f225ad56565d.jpg)
![img_020](https://cloud.githubusercontent.com/assets/19192087/20803168/937b5792-b7ee-11e6-8c3a-2eb536aceeb2.jpg)


Could be there a problem witch special chars ?

`show_empty":0,"default_values":"Innendienst\r\nAu&szlig;endienst","values":"Innendienst\r\nAu&szlig;endienst","range_min":"","range_max":"","description":"","regex":"","order":9,"show_rule":"always",`

Later we check the setting set before.
If choose "Außendienst" we got the problem with "Inndendienst" all works finde

`"show_condition":"==","show_value":"Au&szlig;endienst","show_logic":null,"uuid":null}]},{"fieldtype":"text","name":"- Programme","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"&lt;p&gt;Bitte die ben&ouml;tigten Programme im Startcenter eintragen wie z.B. Abrufverwaltung, BMS, usw.&lt;/p&gt;","regex":"","order":19,"show_rule":"hidden","uuid":"276ccf1c-8ade0ded-583ea17b937cd8.14375892","_conditions":[{"show_field":420,"show_condition":"==","show_value":"Startcenter beantragen","show_logic":null,"uuid":"276ccf1c-8ade0ded-583ea17c0505e9.78153281"}]},`

**Comment by btry** [comment]
Hi

I found a issue with special chars for fields of type **select**. However I'm not sure this is your issue.

Can you test the following branch ? https://github.com/btry/formcreator/tree/367_html_entities_encoding_values

If it does not solve your issue, please consider using the export feature of your test system to send me your form (and only this one). I think the bug will be easier to reproduce if I use the same form as yours.

**Comment by btry** [comment]
Hi

Could you test the fix ? I updated it to match the latest revision of  the plugin version 1.4-beta .

**Comment by Armin83** [comment]
Hi,

yes the fix works for me.

best regards
Armin

**Comment by Armin83** [comment]
@btry This fix is not in the 2.4.0 release or ?
It does not work on my production system with 2.4.0 (glpi 9.1.2)

**Comment by btry** [comment]
Hi

The fix is in 2.4.0. I'll try to reproduce again.

**Comment by Armin83** [comment]
Now we have 2.4.2 and the problem don't occur again.
