### ISSUE TITLE
no requester in ticket and error message when add in

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#370]
Hello

I have this error when i want to add a requester

![image](https://cloud.githubusercontent.com/assets/15144026/20971933/8b8363c8-bc93-11e6-9da9-e3d0717e1014.png)
![image](https://cloud.githubusercontent.com/assets/15144026/20971944/962c3a34-bc93-11e6-95b4-f790de803f26.png)

2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\group_user.class.php:76                        
  inc\ruleticketcollection.class.php:115             Group_User::getUserGroups()
  inc\rulecollection.class.php:1612                  RuleTicketCollection->prepareInputDataForProcess()
  inc\rulecollection.class.php:1466                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc\ticket.class.php:1518                          RuleCollection->processAllRules()
  inc\commondbtm.class.php:815                       Ticket->prepareInputForAdd()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\group_user.class.php:76                        
  inc\ruleticketcollection.class.php:115             Group_User::getUserGroups()
  inc\rulecollection.class.php:1612                  RuleTicketCollection->prepareInputDataForProcess()
  inc\rulecollection.class.php:1466                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc\ticket.class.php:1518                          RuleCollection->processAllRules()
  inc\commondbtm.class.php:815                       Ticket->prepareInputForAdd()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\group_user.class.php:76                        
  inc\ruleticketcollection.class.php:115             Group_User::getUserGroups()
  inc\rulecollection.class.php:1612                  RuleTicketCollection->prepareInputDataForProcess()
  inc\rulecollection.class.php:1466                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc\ticket.class.php:1518                          RuleCollection->processAllRules()
  inc\commondbtm.class.php:815                       Ticket->prepareInputForAdd()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\group_user.class.php:76                        
  inc\ruleticketcollection.class.php:115             Group_User::getUserGroups()
  inc\rulecollection.class.php:1612                  RuleTicketCollection->prepareInputDataForProcess()
  inc\rulecollection.class.php:1466                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc\ticket.class.php:1518                          RuleCollection->processAllRules()
  inc\commondbtm.class.php:815                       Ticket->prepareInputForAdd()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\group_user.class.php:76                        
  inc\ruleticketcollection.class.php:115             Group_User::getUserGroups()
  inc\rulecollection.class.php:1612                  RuleTicketCollection->prepareInputDataForProcess()
  inc\rulecollection.class.php:1466                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc\ticket.class.php:1518                          RuleCollection->processAllRules()
  inc\commondbtm.class.php:815                       Ticket->prepareInputForAdd()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\group_user.class.php:76                        
  inc\ruleticketcollection.class.php:115             Group_User::getUserGroups()
  inc\rulecollection.class.php:1612                  RuleTicketCollection->prepareInputDataForProcess()
  inc\rulecollection.class.php:1466                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc\ticket.class.php:1518                          RuleCollection->processAllRules()
  inc\commondbtm.class.php:815                       Ticket->prepareInputForAdd()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\commondbtm.class.php:426                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\commondbtm.class.php:426                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  inc\commonitilobject.class.php:1383                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Warning(2): strlen() expects parameter 1 to be string, array given
  Backtrace :
  inc\commondbtm.class.php:158                       
  inc\commondbconnexity.class.php:186                CommonDBTM->getFromDB()
  inc\commondbconnexity.class.php:151                CommonDBConnexity::getItemFromArray()
  inc\commondbrelation.class.php:698                 CommonDBConnexity->getConnexityItem()
  inc\commonitilactor.class.php:360                  CommonDBRelation->post_addItem()
  inc\commondbtm.class.php:853                       CommonITILActor->post_addItem()
  inc\commonitilobject.class.php:1383                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\commondbtm.class.php:426                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  inc\commonitilobject.class.php:1391                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Warning(2): strlen() expects parameter 1 to be string, array given
  Backtrace :
  inc\commondbtm.class.php:158                       
  inc\commondbconnexity.class.php:186                CommonDBTM->getFromDB()
  inc\commondbconnexity.class.php:151                CommonDBConnexity::getItemFromArray()
  inc\commondbrelation.class.php:698                 CommonDBConnexity->getConnexityItem()
  inc\commonitilactor.class.php:360                  CommonDBRelation->post_addItem()
  inc\commondbtm.class.php:853                       CommonITILActor->post_addItem()
  inc\commonitilobject.class.php:1391                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\commondbtm.class.php:426                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  ...ns\timelineticket\inc\assigngroup.class.php:249 CommonDBTM->add()
  inc\plugin.class.php:1125                          PluginTimelineticketAssignGroup::addGroupTicket()
  inc\commondbtm.class.php:885                       Plugin::doHook()
  inc\commonitilobject.class.php:1391                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\commondbtm.class.php:426                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  inc\commonitilobject.class.php:1400                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2016-12-07 15:00:25 [@UNGSRVGVA118]
  *** PHP Warning(2): strlen() expects parameter 1 to be string, array given
  Backtrace :
  inc\commondbtm.class.php:158                       
  inc\commondbconnexity.class.php:186                CommonDBTM->getFromDB()
  inc\commondbconnexity.class.php:151                CommonDBConnexity::getItemFromArray()
  inc\commondbrelation.class.php:698                 CommonDBConnexity->getConnexityItem()
  inc\commonitilactor.class.php:360                  CommonDBRelation->post_addItem()
  inc\commondbtm.class.php:853                       CommonITILActor->post_addItem()
  inc\commonitilobject.class.php:1400                CommonDBTM->add()
  inc\ticket.class.php:1747                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:674  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:611  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1119        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()

**Comment by btry** [comment]
Hi

please give the version of GLPi and Formcreator.

**Comment by satyan01** [comment]
glpi 9.1 - Forms	0.90-1.4-beta6

**Comment by btry** [comment]
Try to upgrade to beta7

Also, tell me if GLPi is a released version. (there are 9.1.0, 9.1.1 and 9.1.2 currently in development. This is important for this specific issue.)

**Comment by satyan01** [comment]
[code]
 
GLPI 9.2 (/glpi => C:\inetpub\wwwroot\glpi)

**Comment by satyan01** [comment]
beta7 is master ?

**Comment by btry** [comment]
Yes, beta7 is master. Previous Beta versions were also master.

Although we are near of the 1.4 release, I recommend you to use all beta versions **only** for tests.

**Comment by btry** [comment]
You're using GLPi 9.2 ? Then you also need to update it too : Formcreator needs a patch added yesterday for in GLPi 9.1.2 and later. 

Note : There is backward compatibility with GLPi < 9.1.2, but the choice of legacy or modern way to add actors to a ticket is done on GLPi's version basis.

**Comment by satyan01** [comment]
I wait 9.2 official release and form creator compatible. thx

**Comment by btry** [comment]
Please, note that Formcreator version 1.4 will remain compatible with GLPI 9.1.0, thanks to the backward compatibility code. You will only have to wait for the release of Formcreator.
