### ISSUE TITLE
Possibilité de modifier un formulaire

### ISSUE THREAD

**Issue by JulienG78** [pluginsGLPI/formcreator#372]
Bonjour,

Est-il possible pour un valideur de formulaire de pouvoir modifier celui-ci avant de le valider ?

Je m'explique:
J'utilise ce plugin pour créer un workflow Ressource humaines pour les départs/arrivées de collaborateur.

Mes RH créer le formulaire et le font valider par le manager.
Le manager doit revoir tout le formulaire et pouvoir le modifier avant de la valider.

Une fois validé, celui-ci créer des tickets vers les différentes équipes.

Aujourd'hui tout fonctionne sauf que la validateur une fois qu'il a reçu le mail pour un nouveau formulaire à valider, il ne peux que ajouter un commentaire puis refuser ou valider le formulaire.
J'aimerais qu'il puisse modifier le formulaire puis le valider pour que les tickets partent.

Merci par avance !

Du super boulot ce plugin !

**Comment by JulienG78** [comment]
Bonjour,

Désolé de relancer mais est-ce que quelqu'un de la team dev a pu voir mon message et aurait un élément à me répondre ?

Merci par avance,

**Comment by btry** [comment]
Bonjour

Message vu. 

De mon point de vue, le valideur ne devrait pas modifier les réponses faites par le demandeur. 

Peut être qu'il faudrait mettre au point des questions réservées au valideur : une zone "réservée à l'administration" à l'image de certains formulaires papier qu'on peut être amené à utiliser. Les réponses à ces questions réservées pourraient ensuite servir pour la génération des tickets.

Si vous êtes prêts à financer la fonctionnalité dont vous avez besoin, contactez Teclib' : contact@teclib.com
