### ISSUE TITLE
Incapable d'ajouter une destination

### ISSUE THREAD

**Issue by T42901069** [pluginsGLPI/formcreator#374]
Bonjour, je suis incapable d'ajouter une destination. Lorsque je click sur "Ajouter une destination", j'ai un popup qui me demande un nom ainsi que le type de destination (qui est forcément un ticket) mais si je fait ajouter, le popup ferme et ma destination n’apparaît jamais.

![image](https://cloud.githubusercontent.com/assets/24526556/21104042/ffbfa4dc-c052-11e6-85fd-fbc2fac8bf84.png)

![image](https://cloud.githubusercontent.com/assets/24526556/21104059/1c207c96-c053-11e6-8f7c-9abcd64c5959.png)

![image](https://cloud.githubusercontent.com/assets/24526556/21104080/2f567e00-c053-11e6-8364-a1eba8c60e4b.png)

Merci

Voici les version : 
GLPI 0.90.1
FormCreator 0.90-1.3.4
CentOS 7.2
Apache 2.4.6
MySQL 14.14

**Comment by btry** [comment]
Bonjour

Vérifiez les logs de GLPi ainsi que ceux du serveur HTTP. Ils contiendront probablement des informations utiles pour identifier le souci.

**Comment by T42901069** [comment]
voici ce que j'ai dans les logs sql-errors

`2016-12-12 13:54:55 [23@localhost]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targettickets` (`name`,`comment`) VALUES (\'test\',\'##FULLFORM##\')
  Error: Field 'tag_questions' doesn't have a default value
  Backtrace :
  inc/commondbtm.class.php:425
  inc/commondbtm.class.php:831                       CommonDBTM->addToDB()
  plugins/formcreator/inc/target.class.php:129       CommonDBTM->add()
  inc/commondbtm.class.php:799                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins/formcreator/front/target.form.php:14       CommonDBTM->add()
2016-12-12 13:54:55 [23@localhost]
  *** MySQL query error:
  SQL: INSERT INTO glpi_plugin_formcreator_targettickets_actors
                      (`plugin_formcreator_targettickets_id`, `actor_role`, `actor_type`, `use_notification`)
                      VALUES (
                         , \'requester\', \'creator\', 1
                      ), (
                         , \'observer\', \'validator\', 1
                      );
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 'requester', 'creator', 1
                      ), (
                         ,' at line 4
  Backtrace :
  plugins/formcreator/inc/target.class.php:139
  inc/commondbtm.class.php:799                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins/formcreator/front/target.form.php:14       CommonDBTM->add()
2016-12-12 13:54:55 [23@localhost]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targets` (`name`,`itemtype`,`plugin_formcreator_forms_id`,`items_id`) VALUES (\'test\',\'PluginFormcreatorTargetTicket\',\'2\',\'\')
  Error: Incorrect integer value: '' for column 'items_id' at row 1
  Backtrace :
  inc/commondbtm.class.php:425
  inc/commondbtm.class.php:831                       CommonDBTM->addToDB()
  plugins/formcreator/front/target.form.php:14       CommonDBTM->add()`

**Comment by btry** [comment]
C'est un doublon de #235 

Si votre MySQL est en mode strict, désactivez le

**Comment by T42901069** [comment]
Ça fonctionne

Merci pour le support très rapide!
