### ISSUE TITLE
bug : no requester after creation

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#379]
hello

it happens many times when form is used for ticket creation sometimes i have no requester and writer

![image](https://cloud.githubusercontent.com/assets/15144026/21143738/19ed36d0-c148-11e6-8c6e-9c9d6bd64685.png)

**Comment by btry** [comment]
Hi

I need to know the following : 
- the version of the plugin
- the version of GLPi
- the errors which may be related to your isue in php-erros.log, sql-errors.log and your HTTP server errors log.
- if there are questions in your form which affect the actors, show their settings.

**Comment by satyan01** [comment]
glpi 9.2
Forms	0.90-1.4-beta6
no question about actor in the form

**Comment by btry** [comment]
This issue seems to be a duplicate of this one 

https://github.com/pluginsGLPI/formcreator/issues/370

Ensure GLPi 9.2 is up to date with the current develop version; and also update the plugin to 1.4-beta7. Next, check if this still occurs.

**Comment by satyan01** [comment]
Hello where can I fin 1.4-beta7 ? master version ?

**Comment by btry** [comment]
hi

any 1.4-beta X is the master branch... until the oficial release.

**Comment by btry** [comment]
Hi

Is the bug solved with the version 1.4-beta7 of the plugin?

**Comment by satyan01** [comment]
no more issue after glpi 9.2 upgrade
