### ISSUE TITLE
Better View for Validator - Feature Request

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#380]
I see this on your roadmap and i'm not sure if this match with our requirements.
```
Unplanned
    Ability to add css suffixes to form, questions and sections
```
If our validators take a look at the form they don't see easy which fields are filled.

Answer and Description of the question are similar font / size or format.
It would be better if you can change the view a little bit too see this direct.

**Comment by btry** [comment]
Hi

I  guess your suggestion would be to make answer slightly bigger, or bolder than the description ?

**Comment by Armin83** [comment]
I discussed this with my college. Can you make bolder and coloured ?

**Comment by btry** [comment]
Hi

Here is a sample of an answer as it is currently rendered.
![image](https://cloud.githubusercontent.com/assets/14139801/22013207/32ca4754-dc98-11e6-8a0d-e4ccdb8af098.png)

The first line is the title of the question, the second one is the answer, and  the third is the description.

The description is already slightly smaller than the answer, so I wonder if you actually ask to change how the *titleù is rendered. 

Making it bold might be a good idea. For now, custom CSS support is still unplanned.

**Comment by Armin83** [comment]
Yes, i know and my version is the same but it is not easy for our users.
I see the diffrent if look exactly but tablett or fast reading you must stop and show exact.
Can i change it in styles.css, which value ?
Then i can take look how bold works :)

**Comment by Armin83** [comment]
nano css/styles.css

.formcreator_form .form-group .form_field {
   width: 650px;
   display: inline-block;
   text-align: justify;
   **background: #e8d18d;**
   word-wrap: break-word;
}

But i think it could be nice for all users should i do pull request for this small change ?

Example:
![img_012](https://cloud.githubusercontent.com/assets/19192087/22643850/8b8931a2-ec60-11e6-94bc-0a3453037d0a.jpg)

**Comment by btry** [comment]
Hi

A contribution, even containing a single line is welcome. Fee free to make a PR.

**Comment by Armin83** [comment]
Not a perfect solution when completing the form the radio button selection is also marked :(

**Comment by btry** [comment]
Hi

The design changed since this issue, I close. I think that no CSS customization feature will be provided in shot or medium term. The best would be to find a good presentation, if sill needed. In such case, ipen a new issue with updated content and screenshots.
