### ISSUE TITLE
issue during ticket creation

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#382]
Hello 

this issue happened three times, no requester and impossible to assign the ticket 

![image](https://cloud.githubusercontent.com/assets/15144026/21318880/50954f20-c60b-11e6-84f8-1e83aafbc13a.png)

**Comment by btry** [comment]
Hi

This issue is duplicate of #370 and #379 you both opened. Please, let's continue investigation in #379.
