### ISSUE TITLE
First \ is not displayed in questions

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#384]
Hello

i would like to add a link to a file in a question but the first \ disappears when I save the question

In fact all \ are deleted after saving

![image](https://cloud.githubusercontent.com/assets/15144026/21345222/a63dfc26-c69f-11e6-9c0a-cab301aa20fe.png)

**Comment by btry** [comment]
hi

I think this is a duplicate of #198 (in french).

is your link a description of a question ?

**Comment by satyan01** [comment]
It is in description area
