### ISSUE TITLE
Impossible d'ajouter un destinataire dans les notifications

### ISSUE THREAD

**Issue by daeva13** [pluginsGLPI/formcreator#392]
Bonjour,
Je rencontre un pb avec les notifications.
Je ne peux pas ajouter de destinataires.
J'ai recrée les notifications pour essayer de solutionner le pb mais cela ne fonctionne pas.
Je vous remercie par avance pour votre aide, 
GLPI : 9.1.1
Formcreator : 0.90-1.4-beta7
![glpi](https://cloud.githubusercontent.com/assets/24694325/21383357/a088b46c-c765-11e6-85fc-9eae238b6835.png)

**Comment by btry** [comment]
Bonjour

Ce genre d'affichage est le symptome d'une erreur 500.

Dans ce cas, le fichier **error.log** d'Apache (ou l'équivalent selon votre serveur HTTP) doit contenir le  détail du bug ainsi qu'un backtrace. Il est également  possible que **php-errors.log** et **sql-errors.log**, tous deux dans **glpi/files/_log/**, contiennent des erreurs en lien avec le bug.

Vérifiez ces fichiers et copiez ici les extraits correspondant à votre bug.

**Comment by daeva13** [comment]
Je ne vois rien de particulier dans les 3 fichiers mentionnés.
J'ai fait une mise à jour de GLPI le lundi 19 décembre.
Je n'avais pas constaté de pb particulier sur les notifications avant ce bug mais j'avais un problème similaire avec le plugin FORMCREATOR. Je ne pouvais pas insérer des destinataire dans la partie Administrations>Formulaires>onglet destination.
La mise à jour de GLPI semble avoir solutionné ce problème mais je me retrouve avec les même symptômes d’écran blanc dans la partie destinataires des notifications.
Merci pour votre aide, 
[logs.zip](https://github.com/pluginsGLPI/formcreator/files/666419/logs.zip)

**Comment by btry** [comment]
Dans error.log, le 21 décembre à 10:35 il y a 2 erreurs 500 qui correspondent à peu près à l'heure d'ouverture de votre ticket.

Si vous avez immédiatement ouvert ce ticket suite à l'erreur, je pense qu'il y a un lien, et le backtrace indique que ce serait Generic Object qui pose souci.

Désactivez ce plugin, le temps d'une tentative pour reproduire le bug, et reportez ici le résultat.

**Comment by daeva13** [comment]
Bonjour, 
Je viens de désactiver tous mes plugins et j'ai recrée une notification 
type : formulaire saisi 
Modèle de notifications : le formulaire a été refusé
=> toujours pas possible d'ajouter des destinataires
Voici les deux lignes de log dans le fichier error : 
[Thu Dec 22 04:59:31.351374 2016] [fcgid:warn] [pid 2612:tid 192] mod_fcgid: process 4408 graceful kill fail, sending SIGKILL
[Thu Dec 22 08:10:09.368084 2016] [fcgid:warn] [pid 2612:tid 192] mod_fcgid: process 432 graceful kill fail, sending SIGKILL
Rien en date du 22 dans les fichiers sql-errors et php-errors.
je vous remercie pour votre aide,

**Comment by daeva13** [comment]
Pour info, lorsque je crée une notific
![sans titre](https://cloud.githubusercontent.com/assets/24694325/21430212/70670f10-c862-11e6-86f3-f8df283bc187.jpg)
ation, type : formulaire saisi, je n'ai pas la possibilité de choisir un 
évènement. Le menu déroulant est vide.
Mon pb est peut-être lié à ce champ "évènement" qui n'est pas renseigné...?

**Comment by btry** [comment]
Bonjour

Je ne pense pas que ce champ soit à la source de votre problème; mais il n'est pas normal qu'il soit vide. Je ferai quelques vérifications sur ce point en même temps que je tenterai de reproduire votre souci.

**Comment by btry** [comment]
Bonjour

Hé bien vous aviez raison : j'ai préparé un correctif pour résoudre le souci de votre champ évènement vide. Une fois en place, votre bug disparaît. 

Je vous invite à tester le correctif disponible ici et m'indiquer si ça fonctionne pour vous : 

https://github.com/btry/formcreator/tree/hotfix/notification

**Comment by btry** [comment]
Pouvez vous me dire si les notifications mail du plugin fonctionnaient malgré la présence du bug ?

**Comment by daeva13** [comment]
Bonjour,
Je viens de passer le patch et faire un test, tout fonctionne parfaitement :)
Merci pour votre réactivité !!

**Comment by daeva13** [comment]
Bonjour,
Je viens de passer le patch et faire un test, tout fonctionne parfaitement :)
Merci pour votre réactivité !!


----- Mail original -----
De: "btry" <notifications@github.com>
À: "pluginsGLPI/formcreator" <formcreator@noreply.github.com>
Cc: "daeva13" <aurelielariviere@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 23 Décembre 2016 09:49:35
Objet: Re: [pluginsGLPI/formcreator] Impossible d'ajouter un destinataire dans les notifications (#392)



Pouvez vous me dire si les notifications mail du plugin fonctionnaient malgré la présence du bug ?

**Comment by btry** [comment]
Merci pour votre retour, donc je verse dans la version 1.4-beta.
