### ISSUE TITLE
type from templates are not imported (type = incident)

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#395]

**Comment by btry** [comment]
I don't reproduce 

Here are my steps : 

create a ticket template with type = incident
create a ticket template with type = request

create a form with a target ticket using incident template
create a form with a target ticket using  request template

run both forms, observe generated tickets
for the incident form, the ticket is an incident
for the request form the ticket is a request

In my try to reproduce, ticket templates and forms are in the same entity.

**Comment by orthagh** [comment]
Customer report false positive for this issue, i delete labels and close
