### ISSUE TITLE
Can't create ticket with custom fields (cross plugin issue)

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/formcreator#404]
Hi, 

I don't know the problem occurs on formcreator side or fields side but I noticed that I can't create any ticket when having custom fields on my ticket (tried with Fields 1.4.1, 1.4.2 and patched version pluginsGLPI/fields#124)

![image](https://cloud.githubusercontent.com/assets/22624975/21461772/f0889fd8-c8f8-11e6-8fc7-c4ee68924ee4.png)

**Comment by btry** [comment]
Hi 

Which version of Formcreator and GLPi ?

**Comment by Lokydoki** [comment]
Tested with  [formcreator 0.90-1.3.4] and GLPI 9.1.1.
Here is the issue opened on formcreator's side which i detailed a little more: https://github.com/pluginsGLPI/fields/issues/126

**Comment by btry** [comment]
Hi

The issue on Fields looks perfect. I'll try to reproduce next week with your instructions against the incoming version 0.90+1.4 .

**Comment by btry** [comment]
issue updated in pluginsGLPI/fields#126

a fix should be possible in Fields.

**Comment by btry** [comment]
pluginsGLPI/fields#126 closed, then this one too.
