### ISSUE TITLE
slash link issue

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#412]
Hello, Happy new year for 2017 !

I installed last master version and when I add a link the result is not ok

in my form it is \\fileserver\datas$\IT\Documentation\Applications & Systems\_Procédures générales\Trigrammes.xlsm

and the result is nok

http://itsm/glpi/plugins/formcreator/front///fileserver/datas$/IT/Documentation/Applications%20&%20Systems/_Proc%C3%A9dures%20g%C3%A9n%C3%A9rales/Trigrammes.xlsm

**Comment by btry** [comment]
Hi, happy new year !

I tried to reproduce and found the following : 
![image](https://cloud.githubusercontent.com/assets/14139801/21638527/003524c0-d26c-11e6-9e61-cc6b6da69efc.png)

In the service catalog : 
![image](https://cloud.githubusercontent.com/assets/14139801/21638548/10aabb62-d26c-11e6-886c-b1adf24f5c52.png)

Does this match your issue ?

**Comment by satyan01** [comment]
no see below

![image](https://cloud.githubusercontent.com/assets/15144026/21640172/5f781462-d274-11e6-9992-22645d137757.png)

![image](https://cloud.githubusercontent.com/assets/15144026/21640186/72555554-d274-11e6-90d2-592d10e05a8b.png)


and when I click on the link 

![image](https://cloud.githubusercontent.com/assets/15144026/21640200/82bd491a-d274-11e6-8aa3-0d654459d824.png)

**Comment by btry** [comment]
I think your hyperlink does not contains a protocol. Then it is relative to the  URL of the current webpage.

You're using a windows share, then you should specify the **file://** protocol. I did a quick search about the way to specify a link to such resource and found this : http://stackoverflow.com/questions/5796215/an-url-to-a-windows-shared-folder

If the accepted answer is accurate (could not try myself) your hyperlink should be similar to the following : 

```
file://///fileserver\datas$\IT\Documentation\Applications & Systems_Procédures générales\Trigrammes.xlsm
```

Note you should try first with a resource without space, because this character may cause you an extra trouble.

**Comment by satyan01** [comment]
without space it does not start nothing

**Comment by btry** [comment]
If you simply removed spaces, your hyperlink will point to something which does not exist.

my advice was to try to point to a resource with no space in the path or in the filename. Create a resource like **//server/share/path_without_space/file_without_space.docx** to try what is described in the stackoverflow answer against a simple resource name. When you found the good syntax (especially the five slashes in  the beginning) you may try with a more complex resource name with spaces, accented or special chars to match your needs and habits.

**Comment by btry** [comment]
Hi

Can you feedback about this issue ?

**Comment by satyan01** [comment]
still issue

\\fileserver\datas$\IT\Documentation\Applications&Systems\_Procedures_generales\Trigrammes.xlsm

give 

http://itsm/glpi/plugins/formcreator/front///fileserver/datas$/IT/Documentation/Applications&Systems/_Procedures_generales/Trigrammes.xlsm

**Comment by satyan01** [comment]
above I put \\ and just one appears

**Comment by btry** [comment]
OK, then with the not up to date version, the slashes were OK, but with the latest revision of 1.4beta, slashes are lost, right ?

**Comment by satyan01** [comment]
right

**Comment by btry** [comment]
Please, edit your question. I'm expectinig you'll have to add the missing slash and save.

This is due to the recent changes about slashes problems.

**Comment by btry** [comment]
Any feedback about this one ?

**Comment by satyan01** [comment]
still issue

**Comment by satyan01** [comment]
solvedby  glpi9.2 migration
