### ISSUE TITLE
Formcreator 0.90-1.3.4 incompatible with glpi 9-1-1

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/formcreator#413]
Formcreator 0.90-1.3.4 incompatible with glpi 9-1-1
installation impossible, et je ne vois pas d'autres "releases" disponible.

Merci.

**Comment by btry** [comment]
Bonjour

Les fonctionnalités de la version 0.90+1.4 sont gelées. Des correctifs sont en cours pour les bugs connus, et la version 1.5 est également en développement.

Voyez #277 pour une des principales fonctionnalités. Notez que les captures d'écran sont un peu anciennes et que l'apparence finale a un peu évolué depuis.

**Comment by matth974** [comment]
Merci pour ce retour d'informations.
Une date de sortie pour la version 1.5 est-elle d'ores et déjà planifiée et communicable ?

Cordialement.

**Comment by btry** [comment]
J'aurais dû le préciser : la référence à l'autre ticket concerne la version 0.90+1.4, qui devrait sortir très bientôt.

Il n'y a pas de date pour la 1.5 pour le moment.
