### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#415]
A ticket generated by a form with a file upload field does not contains the files added by the requester.

**Comment by ooredroxoo** [comment]
Hello btry, 
I've tested the file upload and seems to be working, can you send the form configuration and the file details so we can look at it?

![2017-01-06_16-32-10](https://cloud.githubusercontent.com/assets/1323140/21728520/b9b37f7e-d42d-11e6-889c-b61a057ba512.gif)

**Comment by btry** [comment]
Hi

The problem is reported by a a tester of the master branch (0.90+1.4beta7).

He di not provided his form, but I think I'll easily reproduce. I planned to investigate monday.

Which  version of the plugin did you use for your attempt to reproduce ?

**Comment by ooredroxoo** [comment]
I've used 0.90-1.3.4 with GLPI 0.90.3.

**Comment by btry** [comment]
Thank you for your test, I'll take it into account when I'll work on this issue.

This is very likely a regression due to the big code cleanup in targetticket.class.php or perhaps in form_answers.class.php (master branch)

**Comment by btry** [comment]
This is a false positive. The user did not checked the ticket followups.
