### ISSUE TITLE
Select add one to the value

### ISSUE THREAD

**Issue by Darkitty** [pluginsGLPI/formcreator#419]
Hello,

When I send the form, the whole type of selection entry adds one to the current value: if choice 1, 2 shows in the form or ticket. I have looked into the code but I find nothing.

Thanks for this plugin anyway :)

GLPI version : 9.1.1 and FormCreator version : 1.3.4

**Comment by btry** [comment]
Hi

I'm trying to reproduce with the version 0.90+1.4beta7 on GLPI 9.1.1 : 

Here is the select question I created 
![image](https://cloud.githubusercontent.com/assets/14139801/21763786/f0af3ee4-d65f-11e6-8f7a-2264768656ea.png)

I use the form and answered this 

![image](https://cloud.githubusercontent.com/assets/14139801/21763808/129e4b8a-d660-11e6-9c1c-2029a8075ceb.png)

In the ticket I have 1, as expected

![image](https://cloud.githubusercontent.com/assets/14139801/21763817/242d3258-d660-11e6-8ac2-b029b075384c.png)

**Comment by Darkitty** [comment]
Where can I download this version ? I try again with a new form and attach this a ticket but I have still the bug.

The question :

![2017-01-09 11_43_28-glpi - formulaires - 6](https://cloud.githubusercontent.com/assets/7628679/21764012/317a6542-d661-11e6-8644-791d4a027c2f.png)

Fill the form :

![2017-01-09 11_43_52-glpi - formulaires - 6](https://cloud.githubusercontent.com/assets/7628679/21764016/3939985c-d661-11e6-8d0c-8bfda936c3aa.png)

And the form :

![2017-01-09 11_44_18-glpi - formcreator - 46](https://cloud.githubusercontent.com/assets/7628679/21764023/3fe9449a-d661-11e6-9967-b5a4e400a3c0.png)

And the ticket description :

![2017-01-09 11_45_08-glpi - tickets - 2017000255](https://cloud.githubusercontent.com/assets/7628679/21764018/3d0c8624-d661-11e6-91e5-22ccb610c133.png)

**Comment by btry** [comment]
The version 0.90+1.4 is still beta. We are currently fixing bugs before releasing it.

If you want to test it, please try it first on a testing environment. We appreciate feedbacks to improve it.

To download it use the green btutton "clone or download" on this page : https://github.com/pluginsGLPI/formcreator

Note : after the release if 1.4, the master branch (available with the link above) will be the latest release, at time you view it.

**Comment by Darkitty** [comment]
With the git branch, the bug is fixed. Thanks a lot for the help 👍

**Comment by btry** [comment]
Thany you for your feedback.
