### ISSUE TITLE
no group assigne

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#420]
as you see, a cross appears instead of the group of the user (same for watcher), I had to add it manually and it is not possible to remove the empty cross

![image](https://cloud.githubusercontent.com/assets/15144026/21799780/f8fbc76e-d71a-11e6-9ae1-10498a7d62b2.png)

![image](https://cloud.githubusercontent.com/assets/15144026/21799733/cb4a9dae-d71a-11e6-9a95-62c25312b5ca.png)

**Comment by btry** [comment]
Hi

with 0.90+1.4beta7 and GLPi 9.2 ?

**Comment by satyan01** [comment]
yes

**Comment by satyan01** [comment]
from rules of category

**Comment by btry** [comment]
Thank you. I'm trying to reproduce now

**Comment by btry** [comment]
I'm not sure I fully understand you about the rules of category.

Let me show you how I tried to reproduce, and tell me if this is OK : 

1 create a ticket category for the test
2 create a ticket template with category set to a test category as predefined field
3 create a group for the test (I leaft it empty)
4 create a business rule to add the group as requester if a ticket is created with the category in step 2
5 create a form with a target ticket, with ticket template in step 1
6 run the form and check the group is in the requesters of the ticket

Is it the procedure I should follow ?

Screenshots : 
![image](https://cloud.githubusercontent.com/assets/14139801/21808429/afc85ac0-d743-11e6-9716-df49e2a09e93.png)

![image](https://cloud.githubusercontent.com/assets/14139801/21808476/c8e1f50c-d743-11e6-8edd-47f10bdaba45.png)

![image](https://cloud.githubusercontent.com/assets/14139801/21808511/ec8be1e8-d743-11e6-88fd-457020db5237.png)

**Comment by satyan01** [comment]
yes perfect

**Comment by satyan01** [comment]
but the result give no group with cross

**Comment by btry** [comment]
well, not for me, this is whi I thought about a misunderstandiing. I tried with both GLPI 9.1.1 and 9.2

![image](https://cloud.githubusercontent.com/assets/14139801/21810717/332699a0-d74d-11e6-984f-92c5adaf77fd.png)

**Comment by btry** [comment]
Maybe this is a problem related to entities ? 

In my case everything is in the root entity. What about the entity of your group, the ticket, the form and the user who view the ticket ?

**Comment by satyan01** [comment]
group : root entity
ticket : root entity > geneva
user : root entity > geneva

**Comment by btry** [comment]
I still don't reproduce.

I created an entity under the root entity, 
I checked the group is not recursive and is in the root entity
I created a user with habilitation only in the sub entity (profile super admin for my convenience)
I made the form recursive

With the user, I answerred the form
The ticket is in the sub entity 
I view the ticket as the user

And the group is still visible.
![image](https://cloud.githubusercontent.com/assets/14139801/21814523/de9de35e-d759-11e6-9678-6dfe58c26ed1.png)

Just in case, can you tell the commit of your GLPI to make mine at the exact same revision ?

**Comment by satyan01** [comment]
Information about system installation and configuration
[code]
 
GLPI 9.2 (/glpi => C:\inetpub\wwwroot\glpi)

**Comment by satyan01** [comment]
I don't have the issue on super admin user, just users

**Comment by btry** [comment]
9.2 is not sufficient because this version is still in dev. It changes several times a day.

I'll try again with a normal profile

**Comment by satyan01** [comment]
where can i find the exact version ?

**Comment by satyan01** [comment]
date of files is 24.11.2016

**Comment by btry** [comment]
the best wwould  be the hash of the latest commit. You may find this hash if you know a little with GIT and you used it to download your copy of GLPI. 

If not I may rely on the date of your download. this is not perfect but probably sufficient for this issue.

**Comment by btry** [comment]
Still OK
=> with a self-service profile instead of super admin

**Comment by satyan01** [comment]
arf

**Comment by btry** [comment]
with the cross posts, I'm with an up to date version of GLPI. I'll try with an older revision

**Comment by btry** [comment]
reverted to 23-11-2016 => still ok

**Comment by satyan01** [comment]
Forms	0.90-1.4-beta7

**Comment by btry** [comment]
beta7 too

**Comment by btry** [comment]
If your user create a ticket without Form Creator, is he able to add the group ? Or if someone else add the group, Is the user able to s ee it in the ticket ?

Feel free to try other scenarios to comapre. Without a way to reproduce I can't find what's wrong. I'll also review the code to find how the cross may appear without the group name.

**Comment by satyan01** [comment]
I can't create form anymore just now, error 500 on http://itsm/glpi/plugins/formcreator/front/form.form.php

**Comment by satyan01** [comment]
I have tried to download last master version and I have the same issue

**Comment by satyan01** [comment]
nothing in php log

**Comment by btry** [comment]
Which product did you update ? GLPI or FormCreator ?

when you have an error 500 the backtrace cannot be saved in php-errors.log (the error is totally unrecoverable in PHP code). In such case, look into your HTTP server error logs.

**Comment by satyan01** [comment]
I have restarted the server and it is fixed

**Comment by satyan01** [comment]
great thx for your help, I close this issue and wait for next version

**Comment by btry** [comment]
Hi

I can reproduce with the form you shared in #426 : 

When the form you shared contains a reference to a group named **HR**. Obviously I don't have this group in my DB. The import succeeds but adds a reference to a undefined group.

If I answer the form, then the generated ticket has a group without any name, and has only a cross to supress it.

Here are the actors of the target ticket in FormCreator
![image](https://cloud.githubusercontent.com/assets/14139801/21996722/e409804c-dc2b-11e6-929e-3e99d4ccf489.png)

Note the group **N/A**

And a ticket generated with the form
![image](https://cloud.githubusercontent.com/assets/14139801/21996747/fadc2c98-dc2b-11e6-945c-568c469e3e6d.png)

I cannot delete the group.

Do you sometimes copy table contents from a GLPI to an other (for example : designing forms in a lab GLPI, t hen copy them to a production one) ?

**Comment by satyan01** [comment]
yes every day to glpi staging

**Comment by btry** [comment]
Hi

I think this is the cause of this issue, if you don't copy the whole database at once from a GLPI instance to the other.

I suggest we close (again) this issue. IF the problem occurs again, the first thing to do will be checking some relations in the database. (those related to the business rules, and the target tickets of impacted the form)

**Comment by satyan01** [comment]
you mean if I copy my database it will fails groups association ?

**Comment by btry** [comment]
If you copy all tables with their whole content, the database should be fine. 

If you copy some parts only (lets say 2 or 3 tables or few rows in a table), you may introduce foreign keys in the destination database to non existing IDs.
