### ISSUE TITLE
error 500 after send form

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#422]
(0x0) 

0 ms

Warning
58.  -MODULE_SET_RESPONSE_ERROR_STATUS 
Hello, maybe you have an idea, at each time when I send a form I have this error 500

IIS error
ModuleName
FastCgiModule 

Notification
EXECUTE_REQUEST_HANDLER 

HttpStatus
500 

HttpReason
Internal Server Error 

HttpSubStatus
0 

ErrorCode
The operation completed successfully.
 (0x0) 

ConfigExceptionInfo

**Comment by btry** [comment]
Unfortunately http error 500 does not carry any useful info. It means "Internal server error".

When you send a form there are very complex code running. Without a backtrace it is extremely difficult to find which part of code fails.
