### ISSUE TITLE
Setting Priority and Status of the Ticket

### ISSUE THREAD

**Issue by michaelschufi** [pluginsGLPI/formcreator#424]
I would like to set the initial priority and status (like Title and Description) with FormCreator. Is this somehow possible?

**Comment by btry** [comment]
Hi

Formcreator does not handle ticket priority or ticket status  But ticket templates and business rules might help you.

**Comment by btry** [comment]
link to : https://forum.glpi-project.org/viewtopic.php?pid=404352#p404352
