### ISSUE TITLE
table error

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#425]
Hello

I check my database and found this error.

![image](https://cloud.githubusercontent.com/assets/15144026/21927263/9d3484e4-d985-11e6-856b-90bb026ea179.png)

**Comment by btry** [comment]
Hi

This is not a table, this is a view to union the content of 2 tables. 

If you need the exact request, for any maintenance purpose, it is here
https://github.com/pluginsGLPI/formcreator/blob/master/inc/issue.class.php#L32

**Comment by btry** [comment]
Hi

Is there still a problem with the view, can I close this issue ?

**Comment by satyan01** [comment]
Hello

this error just appears in heidisql during database check. so I close the issue
