### ISSUE TITLE
still have issue with form and error 500

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#426]
It is just on form for account creation, still have the issue with request group assignation with cross instead of group.

Maybe it is a clue

I have these logs

2017-01-13 15:54:35 [854@UNGSRVGVA118]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc\commondbtm.class.php:426                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  inc\commonitilobject.class.php:1400                CommonDBTM->add()
  inc\ticket.class.php:1748                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:680  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:617  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1130        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()
2017-01-13 15:54:35 [854@UNGSRVGVA118]
  *** PHP Warning(2): strlen() expects parameter 1 to be string, array given
  Backtrace :
  inc\commondbtm.class.php:158                       
  inc\commondbconnexity.class.php:186                CommonDBTM->getFromDB()
  inc\commondbconnexity.class.php:151                CommonDBConnexity::getItemFromArray()
  inc\commondbrelation.class.php:698                 CommonDBConnexity->getConnexityItem()
  inc\commonitilactor.class.php:360                  CommonDBRelation->post_addItem()
  inc\commondbtm.class.php:853                       CommonITILActor->post_addItem()
  inc\commonitilobject.class.php:1400                CommonDBTM->add()
  inc\ticket.class.php:1748                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:853                       Ticket->post_addItem()
  ...ins\formcreator\inc\targetticket.class.php:1367 CommonDBTM->add()
  plugins\formcreator\inc\form_answer.class.php:680  PluginFormcreatorTargetTicket->save()
  plugins\formcreator\inc\form_answer.class.php:617  PluginFormcreatorForm_Answer->generateTarget()
  plugins\formcreator\inc\form.class.php:1130        PluginFormcreatorForm_Answer->saveAnswers()
  plugins\formcreator\front\form.form.php:69         PluginFormcreatorForm->saveForm()

**Comment by btry** [comment]
Hi

About the warnins : 
Do you have in your form one of these fields ? 
- multiselect
- checkboxes
- radios
- actor

About the HTTP error 500
Do this happen only on one form ?
Do this happen each time the form is used or do this happen sometimes with this form ?
If you try to answer the form several times (2 ou 3 is enough) with the exact same answers, do the error occurs each time ?

Finally, the latest version of the plugin has a new export feature (see the mass actions on the form).  Please consider an export to share it with me. This way I can use the exact same form as you and try to reproduce. The export does not contains any answer : only the form and question definitions.

**Comment by btry** [comment]
I remember you use an IIS server.

Would this web page help you to collect PHP logs for errors 500 ?
http://www.iis-aid.com/articles/how_to_guides/logging_php_to_windows_event_log

**Comment by satyan01** [comment]
Hello

I have checkboxes and radios and select.

It happens only on account creation form or non standard creation form.

The error occurs each time even after ctrl + f5 or close browser

Thank you for your help

**Comment by btry** [comment]
Hi

I'm trying to reproduce the error 500, without success on both GLPI 9.1.1 and 9.2.

I created a form with 3 questions : a select, a checkboxes and a multiselect.I answered the form twice
- with a value un the select, checkboxes and multiselect left empty
- with several values for checkboxes and multiselect

Maybe you have question conditions and the bug happens with them ?

Please consider at least one of the following : 
- see if the link I gave you helps you to get a backtract of the error 500
- try to build a minimal form to reproduce the bug and describe how to build it.
- export the form and share the export file with me

**Comment by satyan01** [comment]
Could you tell me how to export the form please

**Comment by btry** [comment]
View the list of forms in Administration > Forms and select one or several forms to export

![image](https://cloud.githubusercontent.com/assets/14139801/21975936/aeab286c-dbcf-11e6-97ce-b2eba5b9cb27.png)

Click on the **Actions** button, and select *Export**

![image](https://cloud.githubusercontent.com/assets/14139801/21975988/e09e6e92-dbcf-11e6-871c-33fe8cd6745b.png)

Validate and your browser will download a file. Save it, click on **Back**. Then show me the content of the file. You can open it with a text editor.

**Comment by satyan01** [comment]
{"forms":[{"is_recursive":1,"access_rights":2,"requesttype":9,"name":"Standard Account Creation","description":"Standard Account Creation","content":"&lt;p&gt;Account Form&lt;/p&gt;","is_active":1,"language":"en_GB","helpdesk_home":1,"is_deleted":0,"validation_required":0,"is_default":1,"uuid":"a86fcf15-802a1b7a-58498c5065b2f5.18090033","_plugin_formcreator_category":"&nbsp;","_sections":[{"name":"Personal Data","order":4,"uuid":"a86fcf15-802a1b7a-583d4ae59e1a40.05977988","_questions":[{"fieldtype":"text","name":"Last Name","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":1,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5587d63.87079127","_conditions":[{"show_field":null,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57a24c8.93452462"}]},{"fieldtype":"text","name":"First Name","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":2,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5589da3.27078098","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57a4471.93599877"}]},{"fieldtype":"text","name":"Usual First Name","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":3,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5697be1.18688554","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae58d3105.29598223"}]}]},{"name":"Company Information","order":5,"uuid":"a86fcf15-802a1b7a-583d4ae59e8921.16973405","_questions":[{"fieldtype":"glpiselect","name":"Same Access As","required":0,"show_empty":1,"default_values":0,"values":"User","range_min":"","range_max":"","description":"","regex":"","order":1,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae558bea2.07125265","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57a63b2.55524073"}]},{"fieldtype":"date","name":"Entry Date","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":2,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae558ddb8.16702864","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57a8269.60678910"}]},{"fieldtype":"date","name":"Official Start Date","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":3,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae558fc48.89762979","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57aa223.13351473"}]},{"fieldtype":"select","name":"Company ","required":1,"show_empty":0,"default_values":"","values":"Unigestion SA\r\nUnigestion (UK) Ltd\r\nUnigestion (US) Ltd\r\nUnigestion Asset Management (France) SA\r\nUnigestion Asia Pte. Ltd.\r\nUnigestion Holding\r\nUnigestion Holding SA\r\n\r\n","range_min":"","range_max":"","description":"","regex":"","order":4,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5591ab6.43233185","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57ac0a7.26632023"}]},{"fieldtype":"select","name":"Department","required":1,"show_empty":0,"default_values":"","values":"CAS\r\nCEO\r\nChildren action\r\nCompliance\r\nDirection &amp; administration\r\nEquities\r\nExternal\r\nFinance &amp; accounting\r\nHedge funds\r\nHR\r\nInstitutional clients\r\nIT\r\nIT- Developer\r\nIT- Infrastructure\r\nIT- Management\r\nIT- Operations\r\nIT- PMO\r\nIT- Project\r\nIT- Reporting\r\nIT- Sage\r\nIT- Service Desk\r\nLegal\r\nLogistics\r\nLogistics- Reception\r\nMarketing\r\nMarketing- Publishing\r\nOperations Middle Office\r\nOrganisation and projects\r\nOrganisation and projects- Business Analysts CRM\r\nOrganisation and projects- Dimension Support\r\nPrivate assets","range_min":"","range_max":"","description":"","regex":"","order":5,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5593908.67905926","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57adeb3.50264294"}]},{"fieldtype":"ldapselect","name":"Job Function","required":0,"show_empty":1,"default_values":"","values":"{&quot;ldap_auth&quot;:&quot;2&quot;,&quot;ldap_filter&quot;:&quot;(&amp; (samaccountname=*) (&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))&quot;,&quot;ldap_attribute&quot;:&quot;13&quot;}","range_min":"","range_max":"","description":"","regex":"","order":7,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5595899.20876941","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae58239c8.32426981"}]},{"fieldtype":"radios","name":"Internal","required":1,"show_empty":0,"default_values":"","values":"Yes\r\nNo","range_min":"","range_max":"","description":"","regex":"","order":8,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5597714.73317584","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57afca3.66726634"}]},{"fieldtype":"glpiselect","name":"Manager","required":1,"show_empty":1,"default_values":0,"values":"User","range_min":"","range_max":"","description":"","regex":"","order":11,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5599530.03552879","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57eaf64.33473308"}]},{"fieldtype":"datetime","name":"End Date","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":10,"show_rule":"hidden","uuid":"a86fcf15-802a1b7a-583d4ae55bef31.80349448","_conditions":[{"show_field":49,"show_condition":"==","show_value":"Yes","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57f6a06.87411992"}]},{"fieldtype":"textarea","name":"Comments","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":12,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae55d9cd1.96153942","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57f0e94.88008512"}]},{"fieldtype":"text","name":"Title ID","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":6,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae55dba54.29207841","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57f2d46.88641932"}]},{"fieldtype":"radios","name":"Temporary","required":0,"show_empty":0,"default_values":"","values":"Yes\r\nNo","range_min":"","range_max":"","description":"","regex":"","order":9,"show_rule":"shown","uuid":"a86fcf15-802a1b7a-583d4ae55df7d4.42385991","_conditions":[{"show_field":10,"show_condition":"==","show_value":"No","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57fc438.97281844"}]}]},{"name":"IT Materials","order":6,"uuid":"a86fcf15-802a1b7a-583d4ae59eefd2.20009483","_questions":[{"fieldtype":"glpiselect","name":"Computer / Igel","required":0,"show_empty":1,"default_values":0,"values":"Computer","range_min":"","range_max":"","description":"","regex":"","order":1,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae559b324.67032957","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57b3937.62533438"}]},{"fieldtype":"radios","name":"Blackberry","required":1,"show_empty":0,"default_values":"","values":"Yes\r\nNo\r\n","range_min":"","range_max":"","description":"","regex":"","order":2,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae559d0f1.36790484","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57f8861.04548879"}]},{"fieldtype":"radios","name":"Visit Card","required":0,"show_empty":0,"default_values":"","values":"Yes","range_min":"","range_max":"","description":"","regex":"","order":6,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae559eea4.59538226","_conditions":[]},{"fieldtype":"radios","name":"Nice Recording","required":1,"show_empty":0,"default_values":"","values":"Yes\r\nNo","range_min":"","range_max":"","description":"","regex":"","order":5,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae55dd9c5.35274891","_conditions":[{"show_field":2,"show_condition":"==","show_value":"","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57f4b92.37880371"}]},{"fieldtype":"text","name":"Blackberry Phone Number","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":3,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae55e16f0.02799843","_conditions":[{"show_field":14,"show_condition":"==","show_value":"yes","show_logic":null,"uuid":"a86fcf15-802a1b7a-583d4ae57fa660.12219288"}]},{"fieldtype":"radios","name":"Token RSA","required":0,"show_empty":0,"default_values":"","values":"Yes\r\nNo","range_min":"","range_max":"","description":"","regex":"","order":4,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae5609c02.10719321","_conditions":[]},{"fieldtype":"radios","name":"Slidebank Account","required":0,"show_empty":0,"default_values":"","values":"Yes\r\nNo","range_min":"","range_max":"","description":"","regex":"","order":7,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae560f5c8.44237503","_conditions":[]},{"fieldtype":"radios","name":"Simcorp Dimension License and Account","required":0,"show_empty":0,"default_values":"","values":"Yes\r\nNo","range_min":"","range_max":"","description":"","regex":"","order":8,"show_rule":"always","uuid":"a86fcf15-802a1b7a-583d4ae56d4906.07693231","_conditions":[]}]}],"_validators":[],"_targets":[{"itemtype":"PluginFormcreatorTargetTicket","name":"Ticket Standard / Non Standard Account Creation","uuid":"a86fcf15-802a1b7a-587742e6651434.17503984","_data":{"name":"Standard / Standard Account Creation","comment":"<p>##FULLFORM##</p>","due_date_rule":"","due_date_question":5,"due_date_value":1,"due_date_period":"minute","urgency_rule":"none","urgency_question":0,"validation_followup":1,"destination_entity":"requester","destination_entity_value":null,"tag_type":"none","tag_questions":"","tag_specifics":"","_tickettemplate":"Non Standard Account Creation","_actors":[{"actor_role":"assigned","actor_type":"group","use_notification":1,"uuid":"a86fcf15-802a1b7a-583d4ae5d3b309.02869598","_group":"IT > Service Desk"},{"actor_role":"requester","actor_type":"creator","actor_value":0,"use_notification":1,"uuid":"a86fcf15-802a1b7a-583d4ae5d40336.73696821"},{"actor_role":"observer","actor_type":"group","use_notification":1,"uuid":"a86fcf15-802a1b7a-583d4ae5d43eb1.22704218","_group":"HR"},{"actor_role":"observer","actor_type":"group","use_notification":1,"uuid":"a86fcf15-802a1b7a-583d4ae5d493b4.12800353","_group":"Logistics"}]}}],"_profiles":[{"uuid":"a86fcf15-802a1b7a-586cae984bc425.60187393","_profile":"Super-Admin"},{"uuid":"a86fcf15-802a1b7a-586cae983c9b05.62102955","_profile":"IT Human Resources"}]}]}

**Comment by satyan01** [comment]
I tried without ldap select and I have same issue

**Comment by btry** [comment]
the LDAP select is not related to the issue. Having such field in a exported form makes the export invalid. I had to repair the export data manually. And made me fill an other bug ;)

**Comment by btry** [comment]
Nice form... But I still don't reproduce. Tickets seems OK.

Did you find a way to get the backtrace ? It may give a valuable clue.

**Comment by satyan01** [comment]
unfortunately not

**Comment by satyan01** [comment]
group issue solved by a95beec

**Comment by satyan01** [comment]
I noticed form creator tables have not same engine, maybe it is a clue
![image](https://cloud.githubusercontent.com/assets/15144026/21989281/97ae3cb8-dc0a-11e6-8080-5b61c9471ff3.png)

**Comment by satyan01** [comment]
and all glpi is in utf8_general_ci except form in unicode_ci

**Comment by btry** [comment]
The commit you mentionned is for importing forms from a JSON. It does not affect the way groups are added to a ticket. 

About the type of tables : the innoDB tables seems to belong to an other plugin : https://github.com/tomolimo/formvalidation

But it would be interesting to see how your form behaves if all other plugins are disabled when you answer your form. Can you try this ?

**Comment by btry** [comment]
If the different encoding can cause issues, I think this will not lead to an HTTP 500 error. Anyway, thanks for pointing this out. A change is necessary here.
