### ISSUE TITLE
Import form broken with GLPI 9.2

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#429]
To reproduce : 

click on **Choose file**, browse for a file to import : no file uploaded

GLPI 9.1.1
![image](https://cloud.githubusercontent.com/assets/14139801/21978175/b390bf90-dbd9-11e6-8886-aabd7b1f99d0.png)

GLPI 9.2
![image](https://cloud.githubusercontent.com/assets/14139801/21978161/a391c238-dbd9-11e6-8d9f-d659cd555fdf.png)

**Comment by orthagh** [comment]
fixed by https://github.com/glpi-project/glpi/pull/1620
