### ISSUE TITLE
Add general config / profile config

### ISSUE THREAD

**Issue by pVesian** [pluginsGLPI/formcreator#433]
Hi,

It would be nice to be able to deactivate the link added in the main menu bar, either in a general config or on a profile-based level.

Thanks!

**Comment by btry** [comment]
Hi

Which link you're talking about ?

**Comment by pVesian** [comment]
Sorry, I messed up my previous sentence a bit, it's edited now. I'm talking about the link that appears in the main menu bar ("Formulaires" in FR).

**Comment by btry** [comment]
I think this is the breadcrumb here ? 

![image](https://cloud.githubusercontent.com/assets/14139801/22017604/4a83e446-dcab-11e6-8037-5692159501e1.png)

**Comment by pVesian** [comment]
No, it's the "Forms" link in the menu, not the breadcrumb. It appears for any profile (hotliner for example). The link for this link is to plugins/formcreator/front/formlist.php.
![forms_menu_link](https://cloud.githubusercontent.com/assets/3509962/22021284/93c40c2e-dcbc-11e6-91a6-b52302c4ff82.png)

**Comment by btry** [comment]
Is it displayed for profiles who don't have access to any form ?

**Comment by pVesian** [comment]
Yes it is, even when there is no form at all.

**Comment by btry** [comment]
I think it makes sense to hide the link when no forms are available.

Availability of forms is manageable on a per profile basis. If you don't already know this : edit a form, open the tab **Targets** set **Restricted access*, save the change, tick the profiles able to access the form, and save again. 

Then I suggest the plugin should simply count the number of available forms. If there is at least one form, the link is displayed, otherwise, it is hidden.

**Comment by pVesian** [comment]
It would indeed be a good solution. The count would have to be done on the list of available forms for the current user.

**Comment by davidiasass** [comment]
Help me please?

The form does not appear in the menu item.
Appears only in the user profile

**Comment by dethegeek** [comment]
Hi @davidiasass

Please open an other issue to discuss about your problem

**Comment by pVesian** [comment]
Hi @btry, is there any news on this? Thanks.

**Comment by btry** [comment]
Hi

I added the feature in version 2.5.0. 

You may want to try it on a testing environment and feedback before we release this version

**Comment by btry** [comment]
Hi

The feature is added. Having no feedback, I close this ticket.
