### ISSUE TITLE
The Formcreator plug-ins do not appear in the MENU

### ISSUE THREAD

**Issue by davidiasass** [pluginsGLPI/formcreator#437]
Help me please?

The form does not appear in the menu item.
Appears only in the user profile
![form](https://cloud.githubusercontent.com/assets/22041652/22150734/d578ec56-df01-11e6-8568-dc596bb87e12.PNG)

**Comment by btry** [comment]
Hi

Have you got at lease one form enabled ? 
![image](https://cloud.githubusercontent.com/assets/14139801/22151086/bdda5b3c-df1c-11e6-961a-6a9aee36e1b0.png)

Also, check at lease one ctive form matches the language of the user : 
![image](https://cloud.githubusercontent.com/assets/14139801/22151102/cfd96922-df1c-11e6-8015-2db66969af3b.png)

It must be the same language or **all languages**

**Comment by davidiasass** [comment]
Thank you very much.

I no longer knew what to do. rsrsrs

**Comment by EC2311** [comment]
Hello

One user shwos me that the "forms" menu was not available in the assistance menu in english, although it appears in French.

Using my superadmin profil and switching from french to english confirms that.
Version of plugin : 2.8.1
Is it a regression ?
Is there a way to solve that ?

**Comment by btry** [comment]
Hi @EC2311 

I think your problem is not the same as the problem described here. This ticket was for forms not displayed for the requesters. Your problem is about the menu entry to administrate forms. Please open a new ticket.

**Comment by btry** [comment]
@EC2311 

Maybe all your forms are set to english and no form is set to french or "any language". Try to create a dummy form set to all languages or french then check if the problem persists.

**Comment by EC2311** [comment]
@btry : you're right.
It appears now in 'assistance menu' . : solved :) 

I will do an other question about translation ;)
