### ISSUE TITLE
Group validation issue

### ISSUE THREAD

**Issue by gotanbl** [pluginsGLPI/formcreator#438]
Hello, 
I have GLPI-Formcreator 0.90-1.3.4 with Glpi 9.1.1.
In definition of form I choose to validate form request from user with group for example Mail administrators. After user created request through form, validation not goes to Mail administrators but  goes to user who have identical id as group id. I saw tables in database and in table glpi_plugin_formcreator_forms field validation_required = 2 ( ok ) but in table glpi_plugin_formcreator_formanswers field validator_id is id from user not from group id (validation go to that user, not to users exist in group)!!!
Please resolve this!

**Comment by btry** [comment]
Hi

I think the incoming version 0.90+1.4 should solve your issue. To try it, download the master branch, and install it on a GLPI dedicated to tests.

**Comment by gotanbl** [comment]
I tried as you advice and resolve problem, but now I have another!
Similar situation,  now with Target ticket and field Assigned To. If I choose Form validator, form resolve this on creating ticket the same way as in my first post. So if I have group_id = 5, form resolve this as user_id = 5, not user_id (belongs to group_id = 5) which validate request!
Also could you tell me more on Helpdesk mode -- Service catalog extended (for me I think dont work). Whatever I choose, nothing change! How this mode should look? Service catalog simplified work as expected.
Thanks for helping!

**Comment by btry** [comment]
Hi

About your issue, I'll check it soon. 

About the service catalog, it is available for profiles with simplified mode enabled. Other profiles are not affected.

It looks like this and allows the user to search in knowbase and forms at the same time.
![image](https://cloud.githubusercontent.com/assets/14139801/22204505/986f02c8-e172-11e6-9aeb-29422732a1b0.png)

**Comment by btry** [comment]
hi

I reproduced your issue, and found a fix. Can you try this branch and validate it ?
https://github.com/btry/formcreator/tree/feature/438_fix_user_group_confusion_for_validator

**Comment by gotanbl** [comment]
Not work. Now, ticket is assign to group, not to user from group who validate request!
Also, I noticed that user who send request receive two or three mails after ticket is created.
Thannks for your effort in resolving problem!

**Comment by btry** [comment]
Yes, you're right. I updated the branch, now the assigned actor is the actual validator **user**. Please validate it.

About the multiple emails, Formcreator uses 2 ways to generate tickets, depending on the version of GLPI. With GLPI < 9.1.2 it uses a legacy method. With GLPI >= 9.1.2 a new method is used and should trigger less emails. If you still g et too many emails with GLPI 9.1.2, please open a new issue.

**Comment by gotanbl** [comment]
Yes, now works as expected!
Email followup doesn't work for user who validate ticket, the assigned actor, settings in form creation is yes.

**Comment by btry** [comment]
The fix is merged, then the issue is closed.

About your email problem, please open a new one.
