### ISSUE TITLE
ticket template dropdown not accessible anymore

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#439]
Hello

I can't select template anymore

![image](https://cloud.githubusercontent.com/assets/15144026/22196613/535c054c-e14e-11e6-8860-29163f969ed9.png)

**Comment by btry** [comment]
Hi

I don't reproduce. Can you check php-errors.log and sql-errors.log ?

**Comment by satyan01** [comment]
yes nothing inside

**Comment by satyan01** [comment]
just that

2017-01-23 10:31:45 [596@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_knowbaseitems_items` WHERE `itemtype` = \'Ticket\' AND `items_id` = 2017012019
  Error: Table 'glpidb91.glpi_knowbaseitems_items' doesn't exist
  Backtrace :
  inc\dbmysql.class.php:919                          
  inc\dbmysql.class.php:543                          DBmysqlIterator->__construct()
  inc\db.function.php:317                            DBmysql->request()
  inc\knowbaseitem_item.class.php:77                 countElementsInTable()
  inc\commonglpi.class.php:207                       KnowbaseItem_Item->getTabNameForItem()
  inc\ticket.class.php:703                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:162                       Ticket->defineTabs()
  ajax\updatecurrenttab.php:51                       CommonGLPI->defineAllTabs()

**Comment by btry** [comment]
I think this error is not related to your issue : it is related to the knowbase, and it is not used in the target ticket definition of the plugin.

Try to disable all other plugins to see if the problem persists with only FormCreator enabled.

**Comment by satyan01** [comment]
same behavior when only formcreator is activated

**Comment by btry** [comment]
Go the the page with the bug, open the dev tools of your browser (Ctrl+shift+I for FF and Chrome) and refresh the web page.

Check in the dev  tools if there is a JS error.

Also, if you add a question to a form, do the **type** dropdown appear ?
![capture d ecran_2017-01-23_10-59-50](https://cloud.githubusercontent.com/assets/14139801/22199419/1c317658-e15b-11e6-8512-450f7f933246.png)

**Comment by satyan01** [comment]
VM763:4 Uncaught ReferenceError: tinyMCE is not defined
    at eval (eval at <anonymous> (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:4:4994), <anonymous>:4:1)
    at eval (<anonymous>)
    at http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:4:4994
    at Function.globalEval (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:4:5005)
    at init.domManip (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:5:28160)
    at init.append (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:5:25581)
    at init.<anonymous> (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:5:27127)
    at Function.access (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:4:6690)
    at init.html (http://itsm2/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.2:5:26701)
    at http://itsm2/glpi/lib/jquery/js/jquery-ui-1.10.4.custom.min.js?v=9.2:7:54108

**Comment by satyan01** [comment]
yes dropdown appear correctly

**Comment by btry** [comment]
Hi

As you had a cache issue last week, maybe this problem disappeared after you refreshed your cache ?

**Comment by satyan01** [comment]
the issue is the same after empty cache
