### ISSUE TITLE
Question condition dont works

### ISSUE THREAD

**Issue by jswytka** [pluginsGLPI/formcreator#442]
Visibility conditions dont works in my forms.  I tried with 'default values' and 'Values'.. 
Help please.
![image 6](https://cloud.githubusercontent.com/assets/21204053/22205324/0d5125f8-e155-11e6-995c-42cb840fab5f.png)
![image 4](https://cloud.githubusercontent.com/assets/21204053/22205332/1c03c740-e155-11e6-84a7-b34ed07969d4.png)
![image 5](https://cloud.githubusercontent.com/assets/21204053/22205345/27121ab0-e155-11e6-97a5-4a7111ad6571.png)

**Comment by btry** [comment]
Hi

Assuming you whant to show your question when the selected category is **a**, your condition should be
Hidden unless Category = a

Don't use an index, use the value exactly as you typed it in the Values field.

**Comment by jswytka** [comment]
@btry. I tried it that way, but the same behavior.

By the way, congratulations on this plugin.

**Comment by btry** [comment]
Hi

I'm checking your issue with both version 2.4.0 and development version 2.5.0 : I don't reproduce. Which version di you installed ?

Can you it Ctrl+F55 or Ctrl+R to ensure your cache is up to date ? 

If refreshing your cacne does not solve your issue, please open the developer tools of your browser, refesh the page an see if there is a JS error.

**Comment by giroli** [comment]
I've the same problem. I can't define any condition. When I save my question with display condition. I've a message "question update with success" but when I return in the question editor, I haven't any condition.
GLPI 9.1.2, formcreator 2.4.0

**Comment by btry** [comment]
@giroli : please check the php-errors.log and sql-errors.log in glpi/files/_log/

If you find relevant errors, plese show them here.

**Comment by giroli** [comment]
2017-01-30 15:12:21 [947@srv-www1]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_questions_conditions` SET
                     `plugin_formcreator_questions_id` = 10,
                     `show_field`     = 9,
                     `show_condition` = \'==\',
                     `show_value`     = \'\',
                     `uuid`           = \'fa29dbee-58c86f91-588f49c521ee20.39569453\'
  Error: Unknown column 'uuid' in 'field list'
  Backtrace :
  plugins/formcreator/inc/question.class.php:580
  plugins/formcreator/front/question.form.php:26     PluginFormcreatorQuestion->updateConditions()
2017-01-30 15:17:43 [6@srv-www1]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_questions_conditions` SET
                     `plugin_formcreator_questions_id` = 13,
                     `show_field`     = 1,
                     `show_condition` = \'==\',
                     `show_value`     = \'Lyon\',
                     `uuid`           = \'fa29dbee-58c86f91-588f4b07507341.84627412\'
  Error: Unknown column 'uuid' in 'field list'
  Backtrace :
  plugins/formcreator/inc/question.class.php:580
  plugins/formcreator/front/question.form.php:26     PluginFormcreatorQuestion->updateConditions()
root@srv-www1:/var/www/html/glpi/plugins#

**Comment by btry** [comment]
@giroli I think you upgraded the plugin without upgrading its tables. Maybe you upgraded several times from the master branch.

Find formcreator in the table glpi_plugins, set state to the value 6. Once done, GLPI will allow you to upgrade the plugin as usual. 

Don't forget to backup first.

**Comment by giroli** [comment]
Well seen :) @btry  It's ok now

**Comment by jswytka** [comment]
@btry . FC version 2.4.0. Cache empty. JS no errors
![image 001](https://cloud.githubusercontent.com/assets/21204053/22426463/19b08aa8-e6de-11e6-83dd-dfa2a9f2d159.png)
![image 002](https://cloud.githubusercontent.com/assets/21204053/22426467/1b9c2494-e6de-11e6-9c0f-fde5d5ac7b1e.png)
![image 003](https://cloud.githubusercontent.com/assets/21204053/22426468/1d00c0d8-e6de-11e6-89d0-c99e65eccb6b.png)
![image 004](https://cloud.githubusercontent.com/assets/21204053/22426471/1ed9f47e-e6de-11e6-95af-3ef73a417555.png)
![image 005](https://cloud.githubusercontent.com/assets/21204053/22426475/20842dc6-e6de-11e6-84c0-6e70f41b1490.png)
![image 008](https://cloud.githubusercontent.com/assets/21204053/22426882/d39ab8c0-e6df-11e6-8919-e9c6f202fbb0.png)
![image 009](https://cloud.githubusercontent.com/assets/21204053/22426888/d9b7fc5e-e6df-11e6-8c81-1e5e917d4f86.png)

**Comment by jswytka** [comment]
@giroli, @btry  ... 

I deleted the glpi_plugin_formcreator_questions_conditions.backup table and it worked. But check this information.  Now works fine

**Comment by jswytka** [comment]
@btry  Thanks for your support

**Comment by btry** [comment]
@jswytka it seems you had  the same problem as @giroli . The conditiosn failed to save in the database because your schema was not in sync with the code.

Do you know where does the  table **glpi_plugin_formcreator_questions_conditions.backup** come from ?

**Comment by jswytka** [comment]
I don´t know the upgrade process. Could it not have been created in this process?

In particular, I removed the table and did a new installation

**Comment by btry** [comment]
Maybe there was a problem with the dot in the table name. That said, I found nothing in the install / upgrade code which creates such backup since I started to maintain the plugin.

**Comment by matth974** [comment]
I have upgrated formcreaotor from 0.90.1-3-4 to 2-40. Since I have the same problem with FormCreator 2-4-0/ GLPI 0.90.1 and with FormCreator 2-4-0/GLPI 9-1-2.

I don't see the table glpi_plugin_formcreator_questions_conditions.backup in our databases .
I  tried also to change the status of the plugin to 6, in order to reconfigure it, but the problem is always here.

Any idea?

Thank you.

**Comment by btry** [comment]
Hi 

@matth974  Can you show the questions of the form throwing this warning ?

**Comment by btry** [comment]
I think I found the issue. 

@matth974 Please have a look on my lase comment on #423. Run the same query and give the result please.

**Comment by matth974** [comment]
> Please have a look on my lase comment on #423. Run the same query and give the result please.

See [https://github.com/pluginsGLPI/formcreator/issues/423#issuecomment-279603665](url)

**Comment by matth974** [comment]
Hi,

@btry: you asked me:

> Can you show the questions of the form throwing this warning ?

Here is an example (but all questions with conditions are concerned by this "bug"):

View :
 
![formvisu](https://cloud.githubusercontent.com/assets/10028344/22918739/300d234c-f2a5-11e6-8031-d37d2d62ca16.png)

Form Settings:
![formprm](https://cloud.githubusercontent.com/assets/10028344/22918738/300cdd6a-f2a5-11e6-8497-b81837de7c1b.png)

When i chek a case, i have an php error:
`
  *** PHP Warning(2): json_decode() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  plugins/formcreator/inc/fields.class.php:173       json_decode()
  plugins/formcreator/ajax/showfields.php:23         PluginFormcreatorFields::isVisible()`

**Comment by btry** [comment]
I fixed the warning for version 2.4.1. 

As I still cannot reproduce the issue, can you add the fix in the commit 954dee1fe116e805a267ab1da724e0d1477c547d and tell me if it solve the problem with the conditions ?

**Comment by matth974** [comment]
yeah!
it seems to be ok, now :)

Thank you for the patch.

**Comment by btry** [comment]
Do the conditions work again ?

**Comment by matth974** [comment]
yes! thank you.

**Comment by btry** [comment]
Solved for all requesters here; I close. Thank you.
