### ISSUE TITLE
Email notification problem 

### ISSUE THREAD

**Issue by gotanbl** [pluginsGLPI/formcreator#448]
Hi, 
I have formcreator 0.90-1.4-beta7 with glpi 9.1.1.
Email followup doesn't work for user (user from group) who validate ticket, no matter is he set for watcher or ticket is assigned to them, setting in form creation is Yes but in ticket is No.

**Comment by btry** [comment]
to check / fix with #456

**Comment by btry** [comment]
fix validated in #456
