### ISSUE TITLE
Migration from v1.8.1 to v0.90-1.3.4 (PHP & SQL Errors)

### ISSUE THREAD

**Issue by tabad** [pluginsGLPI/formcreator#452]
# The environment

  * Source
    * Red Hat Enterprise Linux Server release 6.3 (Santiago)
        * GLPI v0.84.8
            * Form Creator v1.8.1
  * Target
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
            * Form Creator v0.90-1.3.4

Notes

  1. The GLPI core tables (`^glpi_(?!plugin_).*$` tables) were migrated from GLPI v0.84.8 to GLPI v9.1.2 without any problem; files `php-errors.log`and `sql-errors.log` where empty after migration process.
  2. In http://plugins.glpi-project.org/#/plugin/formcreator says that Form Creator v0.90-1.3.4 is compatible with GLPI v9.1.
  
# The issues 

The migration process from *Form Creator* v1.8.1* to v0.90-1.3.4 creates entries into `php-errors.log` and `sql-errors.log` files.

The first time the `Upgrade` is pushed down, the browser screen shows these messages

```text
Installing glpi_plugin_formcreator_formanswers (0 seconds)

Work in progress...

Work in progress...
```

The upgrade process stops here and generates entries into `php-errors.log` and `sql-errors.log` files. See [forms-1.8.1-to-0.90-1.3.4-attempt1.zip](https://github.com/pluginsGLPI/formcreator/files/730443/forms-1.8.1-to-0.90-1.2.3-attempt1.zip)

I go backwards on page and push down the `Upgrade` button again. Now the plugin seems installed because the button changes from `Upgrade` to `Enable`, but there are new entries into `php-errors.log` file. See [forms-1.8.1-to-0.90-1.3.4-attempt2.zip](https://github.com/pluginsGLPI/formcreator/files/730444/forms-1.8.1-to-0.90-1.2.3-attempt2.zip)

**Comment by btry** [comment]
Hi

Please either try FormCreator 0.90-1.3.4 or wait a few days for  the definitive release of 1.4.0

**Comment by tabad** [comment]
Hello btry,

I apologize, sincerely. I don't know why but it's obvious that I took note of the version incorrectly. I should have written *v0.90-1.3.4* instead of *v0.90-1.2.3*. The description of the issue is correct now. The test was correct.

**Comment by btry** [comment]
After reading the source code, I think the bug occurs when  running the following request 
https://github.com/pluginsGLPI/formcreator/blob/0.90-1.3.4/inc/target.class.php#L198
```
SELECT t.`urgency`, t.`priority`, t.`itilcategories_id`, t.`type`, f.`entities_id`
                      FROM `glpi_plugin_formcreator_targets` t, `glpi_plugin_formcreator_forms` f
                      WHERE f.`id` = t.`plugin_formcreator_forms_id`
                      GROUP BY t.`urgency`, t.`priority`, t.`itilcategories_id`, t.`type`, f.`entities_id`
```

If I'm right, it probably returns an empty result from your database. Unfortunately, the upgrade code seems to not handle such case, and leads to the malformed query you found in sql-errors.log

Either there is an inconsistency in the data of the plugin, either the upgrade code is incomplete. I need to investigate further about the above mentioned request. 

In the mean time, try to run it and tell me if it returns a few rows or not.

**Comment by tabad** [comment]
Hello btry,

Yes, you are right, that query returns an empty result as you can see below.

```sql
MariaDB [glpi]> SELECT
    -> t.`urgency`,
    -> t.`priority`,
    -> t.`itilcategories_id`,
    -> t.`type`,
    -> f.`entities_id`
    -> FROM
    -> `glpi_plugin_formcreator_targets` t,
    -> `glpi_plugin_formcreator_forms` f
    -> WHERE
    -> f.`id` = t.`plugin_formcreator_forms_id`
    -> GROUP BY
    -> t.`urgency`,
    -> t.`priority`,
    -> t.`itilcategories_id`,
    -> t.`type`,
    -> f.`entities_id`;
Empty set (0.00 sec)
```

If I had to bet, I would bet by the second option; the upgrade code is incomplete. Form Creator v1.8.1 in GLPI v0.84.8 has the state *Installed / not activated*, and I doubt there is any form created.

**Comment by btry** [comment]
I agree  : if your DB is clean, the upgrade code is missing something.

If there is no form created before migration, I guess this is the cause of the issue. I'll try to reproduce the issue this way.

**Comment by btry** [comment]
you pointed out an old revision had the version 1.8.1. Because of  that, the incoming version will not be 1.4.0 but 2.4.0. This will prevent problems in the (near) future.

**Comment by btry** [comment]
I saw yesterday the upgrade code involved in the issue is the same until now.

I tried to upgrade a fresh isntall of FormCReator 0.90+.1.3.4 to 2.4.0. Unfortunately, having nothin in  the plugin's tables does allowed me to reproduce. Something is still missing. Anyway I'll  try with the old 1.8.1 to 2.4.0 with the necessary upgrade from GLPI 0.84.x to 9.1.2

**Comment by tabad** [comment]
Hello btry,

Perhaps this is helpful for you.

```sql
MariaDB [glpi]> SHOW TABLES FROM glpi LIKE 'glpi_plugin_formcreator_%';
+--------------------------------------------+
| Tables_in_glpi (glpi_plugin_formcreator_%) |
+--------------------------------------------+
| glpi_plugin_formcreator_cats               |
| glpi_plugin_formcreator_forms              |
| glpi_plugin_formcreator_questions          |
| glpi_plugin_formcreator_sections           |
| glpi_plugin_formcreator_targets            |
| glpi_plugin_formcreator_titles             |
+--------------------------------------------+
6 rows in set (0.01 sec)

MariaDB [glpi]> SELECT * FROM glpi_plugin_formcreator_cats;
+----+-------------+----------+
| id | name        | position |
+----+-------------+----------+
| 14 | Default cat |        0 |
+----+-------------+----------+
1 row in set (0.00 sec)

MariaDB [glpi]> SELECT * FROM glpi_plugin_formcreator_forms;
Empty set (0.00 sec)

MariaDB [glpi]> SELECT * FROM glpi_plugin_formcreator_questions;
Empty set (0.00 sec)

MariaDB [glpi]> SELECT * FROM glpi_plugin_formcreator_sections;
Empty set (0.00 sec)

MariaDB [glpi]> SELECT * FROM glpi_plugin_formcreator_targets;
Empty set (0.00 sec)

MariaDB [glpi]> SELECT * FROM glpi_plugin_formcreator_titles;
Empty set (0.01 sec)
```

I'm including the [dump](https://github.com/pluginsGLPI/formcreator/files/733392/glpi-0.84.8-forms-1.8.1-dump-tables.sql.zip) of those tables too.

**Comment by btry** [comment]
Hi 

With your dump I easily reproduce the issue. I think this PR will solve your issue : https://github.com/pluginsGLPI/formcreator/pull/459

Please try it and feedback.

**Comment by tabad** [comment]
Hello btry,

Following your indications I have tested the migration process with Form Creator [(Master branch / Commit: 37290083d3 /  Jan 30, 2017)](https://git.io/vDTDv). This is than it has happened.
```bash
[root@ilab glpi]# cat php-errors.log 
2017-01-30 10:39:49 [7@ilab.sescam.jclm.es]
  *** PHP Notice(8): Undefined variable: table_targetticket
  Backtrace :
  plugins/formcreator/inc/target.class.php:338       
  plugins/formcreator/hook.php:20                    PluginFormcreatorTarget::install()
  inc/plugin.class.php:664                           plugin_formcreator_install()
  front/plugin.form.php:49                           Plugin->install()
```

```bash
[root@ilab glpi]# cat sql-errors.log 
2017-01-30 10:39:49 [7@ilab.sescam.jclm.es]
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM ``
  Error: Incorrect table name ''
  Backtrace :
  inc/dbmysql.class.php:407                          
  inc/db.function.php:1383                           DBmysql->list_fields()
  plugins/formcreator/inc/target.class.php:338       FieldExists()
  plugins/formcreator/hook.php:20                    PluginFormcreatorTarget::install()
  inc/plugin.class.php:664                           plugin_formcreator_install()
  front/plugin.form.php:49                           Plugin->install()
```

**Comment by btry** [comment]
Indeed, there is a strong dependency between the upgrade of two classes.

see the second PR, it should fix it.

**Comment by tabad** [comment]
Hello tbry,

Again I have tested the migration process with Form Creator [(Master branch / Commit: 23a70c7184 /  Jan 30, 2017)](https://git.io/vDTDv). Now all seems be well. These are the [migration log files](https://github.com/pluginsGLPI/formcreator/files/739709/formcreator-v1.8.1-to-2.4.0-upgrade-files.zip).

A lot of thanks btry.

**Comment by btry** [comment]
Perfect ! Thank you for your feedback.
