### ISSUE TITLE
add a segmented upgrade system

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#453]
It begins to be important.
See #452 

We need to segment each update in separate files, ex
- update_0.91+1.3.4_2.4.0.php
- update_2.4.0_2.5.0.php

Maybe, it will be better to redo previous update, your thoughts ?

**Comment by trasher** [comment]
👍 for separate files, it will be much clear. I'm not sure a rewrite for old ones is really a good idea; since we may introduce regressions doing this, and it should be hard to fix.

**Comment by btry** [comment]
I'll suggest we move all current upgrade code in a single file named update_pre_2.5.0.php), and implement sometinh as near as possible as the upgrade code in GLPI.
