### ISSUE TITLE
Question : Destination obligatoire ?

### ISSUE THREAD

**Issue by Kahalisto** [pluginsGLPI/formcreator#454]
Bonjour,

J'ai remarqué que les formulaires n'ayant pas de destination (ticket) n'apparaissent pas dans la liste des formulaires proposés à l'utilisateur.
Cela est-il un comportement voulu ?
Auquel cas, il y s'agit peut être d'un bug

**Comment by btry** [comment]
Bonjour

C'est voulu. Proposer un formulaire qui ne génèrera rien me parait être un bug, d'autant plus que le demandeur voyait une confirmation de prise en compte de sa demande (Sans destination, c'est evidemment faux).

J'ai fait en sorte que les formulaires sans destination ne s'affichent plus pendant le développement de la  version 2.4.0 (anciennement 0.90-1.4.0), il y a un bon nombre de semaines.

A moins que vous voyiez un intéret à afficher de tels formulaires, je pense qu'on peut clore ce sujet.

**Comment by Kahalisto** [comment]
Merci pour cette réponse,

Je pense qu'il peut y avoir un intérêt lorsque la validation est utilisée.
Cela pourrait permettre je de faire des demandes simples avec un seul niveau de validation, sans avoir une création de ticket systématiquement après validation du formulaire. 
Qu'en pensez-vous ?

**Comment by btry** [comment]
Je ne comprends pas bien 

Si un formulaire sans destination est validé, aucun ticket ne sera créé. Comment comptez vous traiter la demande dans ces conditions ? Ce serait le valideur qui s'en chargerait ? Si oui, comment marquer comme traité (résolu ou rejeté) la demande ?

**Comment by Kahalisto** [comment]
C'est bien cela, c'est le valideur qui se charge de traiter la demande.
Quant au résultat, le champ de commentaire proposé au valideur lorsqu'il doit cliquer sur "Accepter" ou "Refuser" me semble suffisant pour apporter une quelconque précision.
Cela doit bien évidemment ne concerner que des demandes très simples.

**Comment by btry** [comment]
D'accord. Je retire la contrainte avant la release 2.4.0

**Comment by Kahalisto** [comment]
Merci beaucoup !  :)
