### ISSUE TITLE
slash instead of backslash in hyperlink

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#457]
![image](https://cloud.githubusercontent.com/assets/15144026/22377522/96ea127e-e4b2-11e6-9dae-6d8e304abfb9.png)

Look at bottom left of the page : link is with "/"
![image](https://cloud.githubusercontent.com/assets/15144026/22377531/a1ede06a-e4b2-11e6-831a-b81f7562e4e1.png)

**Comment by btry** [comment]
Hi

Can you access the file anyway ?

**Comment by satyan01** [comment]
only if I copy paste the link in windows explorer, if I click on the link directly blank page.

PS: " please could you check my tickets on glpi about task template and screenshot please, nobody has been answered"

**Comment by btry** [comment]
I can't tell you when your tickets on GLPI will be handled, they're in the queue. Community support is  best effort.

If you want quicker support contact Teclib' : contact@teclib.com

About this issue, please check the source of the page, to see if  they're backslashes or slashes.

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/22379481/d273ec00-e4b9-11e6-9b01-db649636fbd7.png)

**Comment by btry** [comment]
This pic show an other issue. Let's focus on your slash problem, and open a new one for this screenshot and its JS errors.

**Comment by satyan01** [comment]
please, how can i find js errors ?

**Comment by satyan01** [comment]
Not allowed to load local resource: file:///U:/IT/Documentation/Accounts

**Comment by btry** [comment]
Hi

I checked with 2.4.0 and 2.5.0 versions of the plugin, using Chromium

If I don't specify the protocol **file://** then the browser shows backslashes

If I slecify **file://** as protocol, the browser seems to convert backslashes into forward slashes.

In both cases, in  the backslashes are kept, unti the HTML code 

![image](https://cloud.githubusercontent.com/assets/14139801/22418730/83ce744e-e6da-11e6-8bdf-38c081bafca0.png)

Then this is not an issue related to Formcreator. Anyway, trying to link a file resource (on a share) from a web page is something very challenging.  

Maybe you could workaround by uploading your resource as a document in GLPI and link to it.

**Comment by satyan01** [comment]
Ok thx
