### ISSUE TITLE
Print feature for a saved form

### ISSUE THREAD

**Issue by Miudon** [pluginsGLPI/formcreator#458]
Hi!
Is there a possible to add print feature for a saved form?

Thanks in advance

**Comment by btry** [comment]
Hi 

The feature exists in teh development version 2.5.0. Howver you should not use it in production. You may use it to contribute, test or feedback.

**Comment by Miudon** [comment]
Hi and Thanks
I've tested developer version and the print option shows up. 
There is a possible to print the form, in the exact way that looks like at screen? Because, at moment, this feature print text only

Best regards
