### ISSUE TITLE
Impossible de trouver les lieux dans le nouveau FormCreator

### ISSUE THREAD

**Issue by Nitro76210** [pluginsGLPI/formcreator#460]
Bonjour,

Auparavant, dans les anciennes versions de FormCreator, je pouvais ajouter une question allant chercher les lieux (du menu Intitulés) déjà ajoutés (exemple : Batiment A, ....)...

Je ne retrouve plus cette fonction dans le form Creator 0.90-1.3.4 avec un glpi 0.85.4

Pouvez-vous m'aider ?

Merci

**Comment by btry** [comment]
Bonjour

La version 2.4.0 va bientôt sortir. Pouvez vous la tester et voir si votre problème persiste ?

**Comment by Nitro76210** [comment]
D'accord, je vous tiendrai informé. Merci

**Comment by btry** [comment]
Bonjour 

La version 2.4.0 est sortie; avez vous vérifié si le bug persiste pour vous ? Les corrections pour la version 2.4.1 sont en cours.

**Comment by Nitro76210** [comment]
Bonjour,


Merci bcp pour cette information que j'ai pu vérifier et tester ce matin. J'ai testé la version officielle : 2.4.0 et la version Hotfix 2.4.1


Malheureusement, la liste des lieux n'est toujours pas disponible dans les objets GLPI lors de l'ajout d'une nouvelle question.


Frederic Depreux



________________________________
De : btry <notifications@github.com>
Envoyé : dimanche 26 février 2017 22:29
À : pluginsGLPI/formcreator
Cc : Nitro76210; Author
Objet : Re: [pluginsGLPI/formcreator] Impossible de trouver les lieux dans le nouveau FormCreator (#460)


Bonjour

La version 2.4.0 est sortie; avez vous vérifié si le bug persiste pour vous ? Les corrections pour la version 2.4.1 sont en cours.

**Comment by btry** [comment]
Bonjour

Il me semble que ce dont vous avez besoin est tout simplement une question de type Intitulé (Dropdown en anglais).

![image](https://cloud.githubusercontent.com/assets/14139801/23406009/2ad73df4-fdbd-11e6-93af-5f6e1918f5ee.png)

**Comment by Nitro76210** [comment]
Bonjour et merci pour votre réponse,


Vous avez totalement raison, il ne s'agit donc pas d'un problème applicatif mais d'une méconnaissance du fonctionnement... Autant pour moi.


Merci bcp et excusez moi pour le dérangement occasionné


Frederic



________________________________
De : btry <notifications@github.com>
Envoyé : mardi 28 février 2017 13:56
À : pluginsGLPI/formcreator
Cc : Nitro76210; Author
Objet : Re: [pluginsGLPI/formcreator] Impossible de trouver les lieux dans le nouveau FormCreator (#460)


Bonjour

Il me semble que ce dont vous avez besoin est tout simplement une question de type Intitulé (Dropdown en anglais).

[image]<https://cloud.githubusercontent.com/assets/14139801/23406009/2ad73df4-fdbd-11e6-93af-5f6e1918f5ee.png>

[https://cloud.githubusercontent.com/assets/14139801/23406009/2ad73df4-fdbd-11e6-93af-5f6e1918f5ee.png]
