### ISSUE TITLE
Error: Need to be validate by a Group

### ISSUE THREAD

**Issue by Miudon** [pluginsGLPI/formcreator#464]
Hi,
This error occur on php-errors.log when I select group to validate a form.
For a test purpose, if I select "user" the process works ok.
The group has only the user mentioned on test purpose.

From PluginFormcreatorForm::displayUserForm() in /var/www/html/glpi/plugins/formcreator/inc/form.class.php line 783
  SELECT g.`id`, g.`completename`
                      FROM `glpi_groups` g
                      LEFT JOIN `glpi_plugin_formcreator_formvalidators` fv ON fv.`users_id` = g.`id`
                      WHERE fv.`forms_id` = 12

Best regards!

**Comment by Miudon** [comment]
Hi, 
I've tested development version, for other purpose, and this error does not occurs.
But when i selected Forms menu, the view looks weird, because shows up forms name and descriptions.

Thanks in advance
Best Regards

**Comment by btry** [comment]
Hi

The SQL error was fixed in october 2016.

About display problems, pressing Ctrl+R or Ctrl+F5 should solve the problem. The caching issue should disappear in next releases of GLPI.

**Comment by Miudon** [comment]
Great!
Works perfectly.
Thanks a lot
