### ISSUE TITLE
Modification des acteurs

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#468]
Bonjour,
J'utilise formcreator pour la création de demandes.
A la création de la demande, j'ai des règles qui affectent automatiquement le ticket à un groupe, mais une fois que le ticket est créé, même si le ticket est bien affecté, la liste des acteurs est vide et je ne peux donc pas modifier le technicien en charge de la demande. Si jamais le demandeur c'est trompé ou si la demande doit être transférée à un autre service, je ne peux plus changer aucun acteur.
Est-ce normal? Si oui, est-ce qu'il existe un moyen de contourner le problème?
D'avance merci
Bien Cordialement
![formcreator](https://cloud.githubusercontent.com/assets/25478777/22513685/3eea069e-e89d-11e6-994a-45e57ad1c1c6.png)

**Comment by btry** [comment]
Bonjour

Evidemment, votre souci n'est pas normal. 

Ce bug est apparu avec un autre utilisateur récemment. A défaut de retours assez précis, je ne suis pas certain de la cause. Il semble que c'était lié à un import SQL d'un GLPI à un autre portant sur les tables du plugin.

Si vous utilisez la version 0.90-1.4beta, commencez par upgrader à la dernière version de la branche master. Ne vous étonnez pas du bond en version 2.4.0. C'est un simple renommage.

Ensuite, dites 
- si le bug persiste ou non,
- si vous avez importé des morceaux de base de données, 
- si vous avez utilisé la nouvelle fonction d'export / import du plugin.

**Comment by eckorion** [comment]
Bonjour,
Merci pour tous ces éléments.
Effectivement ça semble être lié à l'import SQL.
J'ai essayé la migration en 2.4.0 et le bug était toujours présent.
Pour info je suis en GLPI 9.1
J'ai alors désinstallé le plugin et réinstallé le 2.4.0 et là ça fonctionne.
J'ai désinstallé le 2.4.0 et réinstallé 0.90-1.3.4 et là ça fonctionne également.

J'ai donc recréé mes formulaires et tout se passe bien.
Juste une petite info concernant la toute dernière version, je trouve l'affichage en 2.4.0 moins convivial pour l'usager même si les fonctionnalités ajoutées sont très intéressantes.

Merci encore pour tout ce travail et la réactivité.

Bien Cordialement

**Comment by btry** [comment]
Bonjour

Vous pouvez ouvrir des tickets pour suggérer des améliorations de l'interface utilisateur.

Pour transférer des formulaires d'un GLPI à un autre, utilisez la fonction d'export / import présente à partir de 2.4.0. 

Quelques contraintes à respecter sur l'import / export : 
Si des itemtypes de GLPI sont utilisés, et liés à un formulaire, leur ID doit être le même entre les GLPI source et destination. Notamment les utilisateurs, groupes et gabarits de tickets.

Le but est d'avoir un GLPI d'intégration pour la mise au point des formulaires. Une fois prêts ils sont exportés puis réimportés dans le GLPI de production.

L'export est une action de masse des formulaires, l'import est une icône avec une flèche vers le haut dans la barre d'outils, quand vous êtes sur la liste des formulaires.

**Comment by eckorion** [comment]
Bonjour,

Finalement ça ne fonctionne pas, après avoir pu le faire fonctionner je suis de nouveau dans l'impossibilité de faire apparaitre et de modifier les acteurs. Malgré l'installation et la désinstallation du plugin. Ca semble fonctionner de manière aléatoire.

Bien Cordialement

**Comment by btry** [comment]
Que s'est il passé entre le moment où le plugin a fonctionné et le moment où le bug est réapparu ?

De ce que j'ai pu trouver, cela peut arriver si les ID des utilisateurs ou groupes n'existent pas au moment de générer un ticket. Avez vous fait quelque chose qui pourrait avoir cassé la relation entre le ticket cible et les acteurs qui s'y trouvent ?

Je commence à penser à un point d'amélioration du plugin pour gérer ce type d'évènement.

**Comment by eckorion** [comment]
Bonjour,
Je pense avoir trouvé, il s’agissait d'un problème lié aux gabarits. Le demandeur et le technicien étaient masqués dans le gabarit de ticket par défaut de l'entité. Hors le créateur de la demande n'a pas la main puisque c'est affecté automatiquement par des règles. 
Ça ne pose pas de soucis sur les tickets sauf ceux créés par formulaire.
Ça a marché précédemment mais j'avais fait des modifications sur les gabarits justement.

**Comment by btry** [comment]
Bonjour

Parfait, donc on peut fermer ?

**Comment by eckorion** [comment]
Oui sans problème, merci pour tout.
