### ISSUE TITLE
Champs conditionnels non soumis

### ISSUE THREAD

**Issue by tlaugier** [pluginsGLPI/formcreator#469]
Bonjour,

Lorsque je remplis des champs soumis à conditions dans un formulaires ils n'apparaissent pas dans le ticket créé.

Exemple :
Une question de type "checkboxes" et une question de type "text" soumis à la condition qu'une des cases de la question précédente avec la valeur "Apache" soit cochée.
Lors de la rédaction du formulaire le champs apparaît bien mais on ne le retrouve pas dans le ticket généré.

Version de GLPI : 9.1.1
Version de formcreator : 0.90-1.3.4

**Comment by btry** [comment]
Bonjour

Quelle version du plugin ?

**Comment by btry** [comment]
Le version 2.4.0 est publiée. Votre problème ne devrait pas persister avec cette version. 

J'attends votre retour pour déterminer si il faut intervenir sur le plugin.

**Comment by tlaugier** [comment]
Bonjour,

Avec cette version les champs qui n'étaient pas soumis le sont bien.

Je vous remercie pour tout le travail sur plugin plus qu'utile !
