### ISSUE TITLE
form title width

### ISSUE THREAD

**Issue by klodnitsky** [pluginsGLPI/formcreator#471]
Hello,

Is it possible to change title width in forms? 

![bug](https://cloud.githubusercontent.com/assets/7794575/22584461/277de3cc-e9fb-11e6-9817-be6587ec1281.png)

GLPI-Formcreator 2.4.0

**Comment by jstival** [comment]
Dans le CSS, ligne 204

```
.formcreator_form .form-group > label {
     width: 300px; --> Remplace par width: 100%;
```
Ça semble corriger si je dis pas de bétises

**Comment by klodnitsky** [comment]
thx,

i replaced line 204
`width: 300px;  --> width: 650px;`
and after line 387 added
`width: 650px;`
