### ISSUE TITLE
id notification=0

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/formcreator#472]
Bonjour,
je viens d'installer la dernière version du plugin sur GLPI 9.1.2 mais lorsque je veux modifier les notifications  en cliquant sur "Une demande a été faite..." j'atterris sur la page création de modèle de notification car le lien des notifs du plugins sont  toutes à id=0
ex:
https://monglpi/front/notification.form.php?id=0

**Comment by btry** [comment]
Bonjour

Pour le moment, je ne reproduis pas.

C'est une installation fraîche du plugin ou un upgrade ?

**Comment by Riesuu** [comment]
Bonjour,
une installation toute fraiche de la semaine dernière.
Après je possède un Mysql 5.7 sur un IIS 8, est ce que cela peut en être la
cause?

Cordialement,
Lyes BRIK.

2017-02-06 17:47 GMT+01:00 btry <notifications@github.com>:

**Comment by btry** [comment]
Je ne pense pas que votre choix d'infrastructure soit la cause du souci.

Regardez du côté des logs de votre installation si il y a des erreurs : 

glpi/files/_logs/php-errors.log
glpi/files/_logs/sql-errors.log

**Comment by Riesuu** [comment]
Bonjour,
je ne vois absolument rien dans les logs, je viens de
déinstaller/nettoyer/résintaller le plugin, les log php et sql n'ont pas
bougés.
Le seule fichier qui a été remplis est "migration to 2.4.log"


0 seconde for "Installing glpi_plugin_formcreator_answers" @ 2017-02-03
16:30:33 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_entityconfigs" @
2017-02-03 16:30:34 [12@monserveurglpi]
1 seconde for "Configuration of existing entities" @ 2017-02-03 16:30:34
[12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_forms" @ 2017-02-03
16:30:34 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_forms_answers" @
2017-02-03 16:30:34 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_questions" @ 2017-02-03
16:30:34 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_sections" @ 2017-02-07
09:34:21 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_answers" @ 2017-02-07
09:34:21 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_entityconfigs" @
2017-02-07 09:34:21 [12@monserveurglpi]
0 seconde for "Configuration of existing entities" @ 2017-02-07 09:34:21
[12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_forms" @ 2017-02-07
09:34:22 [12@monserveurglpi]
1 seconde for "Installing glpi_plugin_formcreator_forms_answers" @
2017-02-07 09:34:22 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_questions" @ 2017-02-07
09:34:22 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_sections" @ 2017-02-07
09:38:45 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_answers" @ 2017-02-07
09:38:45 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_entityconfigs" @
2017-02-07 09:38:45 [12@monserveurglpi]
0 seconde for "Configuration of existing entities" @ 2017-02-07 09:38:45
[12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_forms" @ 2017-02-07
09:38:45 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_forms_answers" @
2017-02-07 09:38:45 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_questions" @ 2017-02-07
09:38:45 [12@monserveurglpi]
0 seconde for "Installing glpi_plugin_formcreator_sections" @

Cordialement,
Lyes BRIK.

2017-02-06 17:57 GMT+01:00 btry <notifications@github.com>:

**Comment by btry** [comment]
Bonjour

Je ne vois pas comment votre bug peut arriver. Dans la table glpi_notifications de votre base de données, vous devriez avoir une ligne pour la notification **The form has been created** (en anglais). Est elle présente ?

Si oui, cette ligne porte normalement un ID supérieur à 0. Est bien le cas ?

**Comment by Riesuu** [comment]
Bonjour,
j'ai bien la ligne demandé qui concerne votre plugin (en tout 5), mais l'id
es à 0

Cordialement,
Lyes BRIK.

**Comment by btry** [comment]
Désinstallez le plugin, puis vérifiez que toutes ses notifications sont bien supprimées de GLPI. Les notifications doivent être supprimées, et les modèles de ces notifications également.

Si il reste quelque des notifications ou des modèles, essayez de les supprimer avec l'interface de GLPI.

Ensuite installez le plugin de nouveau, et vérifiez les ID des notifications créées.

**Comment by Riesuu** [comment]
Je viens de trouver...
Dans ma BDD glpi_notification j'avais un id à "0" "Request Unlock Items".
J'ai donc supprimé complétement ma table glpi_notification.
Réimporter une BDD vide et importer mes données en mettant un "id" à ce
"Request unlock items". Ensuite j'ai réinstallé le plugin et je récupère
enfin des id.

Encore désolé du dérangement et merci pour tout.

Cordialement,
Lyes BRIK.

**Comment by btry** [comment]
A mon avis, votre manipulation a peut être introduit une incohérence qui pourrait casser le bon fonctionnement de la notification Request Unlock Item.

Dans la table glpi_notificationtargets la colonne notifications_id est une clé étrangère vers la table glpi_notifications. Il y a donc probablement une ligne avec un 0 qui devrait être changé en l'ID que vous avez choisi.

Quand vous dites "Réimporté une BDD vide", je ne sais pas exactement quelle manipulation vous avez faite, mais cela me parait dangereux à cause de la relation que j'ai pointé ci dessus.

Vous auriez peut être meilleur compte de restaurer la table si vous avez fait une sauvegarde et procéder d'une manière moins globale, seulement sur la ligne avec l'ID à 0.

**Comment by Riesuu** [comment]
Effectivement...
Malheureusement sur mes sauvegardes l'id de "Request" est toujours à 0.
Dans glpi_notificationtargets les informations pour votre plugin ont toutes
un id à 0,
Puis j'ai encore 4 id à 0 qui correspondent au notification des contrats .

Cordialement,
Lyes BRIK.

**Comment by btry** [comment]
Il a dû se passer quelque chose dans la vie de votre base de données. En principe les tables de notifications ne sont pas soumises à beaucoup de changements.

C'est un souci qui sort du cadre du plugin, qui me parait plus général. Je pense qu'on peut clore ce ticket car vous avez réussi à résoudre le problème par rapport au plugin. 

Il me semble que ce problème d'ID à 0 est un signal fort qui devait vous inciter à vérifier en profondeur l'intégrité de vos tables touchant aux notifications. Selon ce que vous trouvez, et selon l'historique de votre GLPI, peut être que vous devriez étendre les vérifications à plus de tables. 

Surveillez aussi attentivement pendant quelques temps le fonctionnement des notifications par mail (utilsiateurs qui n'en reçoivent pas ou qui ont des messages incohérents). Ce sera un indicateur sur la fiabilité des notifications que vous utilisez et donc la cohérence des tables qui les concernent.

Si vous trouvez des anomalies, et si leur gravité le justifie, n'hésitez pas à sollicitez de l'aide sur le forum de GLPI, IRC ou à contacter votre prestataire spécialiste GLPI. Si vous n'en avez pas, vous pouvez vous rapprocher de Teclib' : contact@teclib.com .

**Comment by Riesuu** [comment]
Merci pour les conseils je vais regarder ça attentivement, jusqu'à
aujourd'hui je n'avais recensé aucun problème sur cette base alors que sur
la base glpi_entité oui.
Je vous souhaite une bonne continuation et je vais me replonger dans tout
ça ainsi que l'élaboration de mes formulaires.

Cordialement,
Lyes BRIK.
