### ISSUE TITLE
Impossible d'importer un formulaire exporté

### ISSUE THREAD

**Issue by jstival** [pluginsGLPI/formcreator#473]
J'ai créé un formulaire dans l'ancienne version du plugin (il est en 2.4.0 maintenant) sur une plateforme 9.1.2, je tente de l'importer sur une autre instance de GLPI mais je reçois le message : "Type de fichier non autorisé".

Quand j'exporte le formulaire, il est en extension .json

**Comment by btry** [comment]
Bonjour

Le format JSON n'est pas autorisé par défaut dans les types de fichier uploadables. Ajoutez ce format et vous pourrez faire l'import.

**Comment by jstival** [comment]
Effectivement, en allant dans la gestion des types de documents et en ajoutant le type : json, cela fonctionne parfaitement. Encore merci :)
