### ISSUE TITLE
Ajouter/modifier l'image des formulaires

### ISSUE THREAD

**Issue by jstival** [pluginsGLPI/formcreator#474]
Sera-il possible de modifier les images (soit à partir d'une liste pré établie, soit en upload) pour qualifier au mieux les formulaires ?

![image](https://cloud.githubusercontent.com/assets/21370534/22607943/96780f8e-ea30-11e6-93c7-b8e7e790f376.png)

Un formulaire pour créer un nouvel arrivant sera avec l'icone d'un bonhomme
Un formulaire pour commander un nouveau PC avec l'icone d'un PC, etc...

Merci

Ps : Plus j'utilise et découvre ce plugin, plus je l'aime !! Félicitation pour le boulot !! Merci !!!

**Comment by btry** [comment]
Bonjour,

L'objectif de cette icône est de différencier les formulaires et les éléments de la FAQ (voir la base de connaissance).

Avoir une icône distincte par formulaire n'est pas prévu pour l'instant, utilisez plutôt le système de catégories en arborescence et le moteur de recherche.

**Comment by btry** [comment]
Bonjour

Il est maintenant possible de personnaliser la couleur de l'icone, le symbole de l'icone (pioché dans Font Awesome) et la couleur d'arrière plan.

Certains demandent de prendre en charge une image personalisée, mais cela n'est pas encore fait.

Pour le moment je ferme ce ticket; réagissez à l'autre demande pour être notifiée des améliorations. Je vous laisse le soin de la rechercher parmi les demandes ouvertes.
