### ISSUE TITLE
Form Destination - Requester - Allow insert an e-mail from a Anonymous Users 

### ISSUE THREAD

**Issue by Gambware** [pluginsGLPI/formcreator#475]
In my organization, we allow tickets are open by e-mail from anonymous users. (filtering the email domains in Email Collector Rules)

So, when we created Public forms to allow that the users open their tickets on GLPI, the tickets are opened without a requester and the form doesn't have the option to select Ex. e-mail field on the form to be placed as Requester.

**Comment by Gambware** [comment]
![image](https://cloud.githubusercontent.com/assets/24397740/22610712/59b00204-ea2c-11e6-9792-c87b6d39af43.png)

**Comment by btry** [comment]
Hi 

Use the field type **Actor**. In the target ticket, add a requester from an actor question.

The anonymous requester should add his own email adress in the field to appear in requesters.

This feature is available from 2.4.0.

I would like to hear feedbacks about this new feature.

**Comment by Gambware** [comment]
Hi, Thanks for the answer !! 

I changed the field e-mail to Actor on form, but now, when I put the e-mail address on this field he try to search the e-mail and don't find any e-mail even the e-mails that already registered on GLPI Users and the same to e-mails from anonymous users (That aren't registered on GLPI DB). When I move to another field the E-mail (Actor) field back to blank. So I can't insert e-mail address on this field. 

![image](https://cloud.githubusercontent.com/assets/24397740/22652641/d40d3356-ec4c-11e6-8343-879ae6422174.png)

![image](https://cloud.githubusercontent.com/assets/24397740/22652659/e6637272-ec4c-11e6-9df6-fd40a4f765e4.png)

**Comment by btry** [comment]
Hi

This is simply a misunderstanding about the way this field works. The docuymentation is not yet up to date with new version.

Searches doone by the adctor field is done against the name of the users (in other words : their login). The field allows typing email addresses to handle anonymous users. When you type an email address, just ignore the fact the search fails to find any user. This the expected behavior.

When you type a user, you shall either type it until his last char, or choose it in the search results. Aasuming you choose to type all chars of the user login (or anonymous user's email), press the Enter key to validate it.

Example: typing glpi
![image](https://cloud.githubusercontent.com/assets/14139801/22655743/63ab26c8-ec91-11e6-896c-f4bf741cd22f.png)


After choosiing the user glpi in the drpodown **OR** fully type it then hit ENTER : 
![image](https://cloud.githubusercontent.com/assets/14139801/22655781/82c18d0e-ec91-11e6-9538-72f778e61302.png)

The same while typing an email address :
![image](https://cloud.githubusercontent.com/assets/14139801/22655804/9817f85a-ec91-11e6-8b81-4b38aa025e00.png)

When I finished to type the email address, I hit ENTER and the field becomes 
![image](https://cloud.githubusercontent.com/assets/14139801/22655839/b72f64da-ec91-11e6-8168-2843d8fb6500.png)

**Comment by Gambware** [comment]
Ok, I'm trying to Hit Enter and Tab but the field isn't filled. He back to blank
I'm trying on Google Chrome / Mozilla / MS Edge. 
All are showing the same behavior.

**Comment by Gambware** [comment]
My GLPI version is 9.1.1

**Comment by btry** [comment]
If 3 different browsers are imapcrted, I assume this is browser independant. Pick your preferred, and check its developers tools for any JS error while typing something in the field.

Check also : 
- glpi/files/_logs/php-èerrors.log 
- glpi/files/_logs/sql-errors.log

It should run from GLPI 0.90.x to 9.1.2.

**Comment by gotanbl** [comment]
Is it possible that the Actor is automatically user who is requester, or user who is logged on system?

**Comment by btry** [comment]
@gotanbl : yes of course ! Just have a lok on the default actors when you create a new target ticket 
![image](https://cloud.githubusercontent.com/assets/14139801/22665565/7b28154e-ecb5-11e6-9ed1-2784cd9958a4.png)

There is the form requester in ... the requesters :) . However, it is impossible to determine who is the requester if the form is used anonymously. That's whi @Gambware needs the requester fill hos own email address.

**Comment by Gambware** [comment]
I checked all logs (php and sql) but nothing related with the form is logging. 
Also I perhaps that the form works perfectly when you are logged on GLPI, but when you open the form without login on glpi the field Actor not work properly he just show "Searching" and dont allow you put any information because when you write a text and hit enter or tab the field backs to blank

**Comment by btry** [comment]
Hi

Your idea makes sense. I'll investigate in this direction.

**Comment by gotanbl** [comment]
@btry : I know for that. Another question: Is it possible to use Form requester in Ticket title as Macro like Answers and Question. (##Form requester##).
If form is needed to validate I dont know from which user request is, unless I create question in Form where I ask user for that!

**Comment by btry** [comment]
@gotanbl : Currently, there is nothing to put the requester in the title of a ticket. You should request this feature by creating a new ticket.

**Comment by endlessterror** [comment]
@btry I am requesting support of this feature in ticket #741.

**Comment by btry** [comment]
Hi @castorsenior 

This is normal : when you are not authenticated, you are not granted to read anything in the database, and showing available entries requires to read data from users. 

The incoming version 2.7.0 will no longer allow to add such fields to anonymous forms. Existing forms will not be modified by the upgrade process. It is up to the form designer to determine how to modify his forms.

**Comment by castorsenior** [comment]
Thank you very much @btry for your quick answer :-) :-) :-) 
So, I understand that the policy of the developpers is to close the possibility for anonymous users to give their mail. Right ? But what about the issue #741, which is actually in your to do list ? My need is to give possibility to anonymous users to fill a form, to leave their mail adress, and this mail adress to be automatically copied in the field "Requester" of the generated ticket.

**Comment by btry** [comment]
> So, I understand that the policy of the developers is to close the possibility for anonymous users to give their mail. Right ?

This is not the purpose of this change. So I created a fix to allow use of the email field instead. This is not as powerful as actors field because email field allows only one email address. If needed, set several fields. See this patch https://github.com/pluginsGLPI/formcreator/pull/1266

**Comment by btry** [comment]
![image](https://user-images.githubusercontent.com/14139801/51400411-a026bf80-1b48-11e9-8184-fbf32b5fffcc.png)

![image](https://user-images.githubusercontent.com/14139801/51400369-86857800-1b48-11e9-95f8-ca232b0201e0.png)


![image](https://user-images.githubusercontent.com/14139801/51400350-766d9880-1b48-11e9-9307-cb83f70aa2da.png)

**Comment by castorsenior** [comment]
Thank you very very much @btry for such detailled explanations. We managed to let it work :-)

**Comment by btry** [comment]
Great, Then I close. The feature is ready for 2.7.0
