### ISSUE TITLE
during update to 2.4.0

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#478]
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''F:\' WHERE `id` = 5813' at line 2

**Comment by btry** [comment]
Hi

Please provide the full error entry as you can find it in sql-errors.log 
- the error message
- the backtrace
- the full SQL query

**Comment by satyan01** [comment]
the error message is above
no backtrace
no log

nothing appears in form anymore, the plugin is activated and database filled

**Comment by btry** [comment]
Ok, then this is a "raw" query in the upgrade process.

Have a look into the tables glpi_plugin_formcreator_*  and tell me which ones have a row with ID = 5813.

**Comment by satyan01** [comment]
answer f:\

**Comment by satyan01** [comment]
I have deleted the line on staging server, removed form database on prod, copy form database from staging, upgrade the plugin to 2.4.0, and it will fixed.

**Comment by btry** [comment]
The procedure you described is a workaround, but the bug is still there. I must reopen

**Comment by btry** [comment]
Hi

I guess the faulty query is in the upgrade of **answer** itemtype. I need a proof of this.

In the branch hotfix/2.4.1 I added a feature to save the backtrace of an unrecoverable error during an upgrade. 

Could you backoup your integration environment and try to upgrade to version 2.4.1 without trying to workaround ? The bug should occur, and should be logged in **glpi/files/_log/migration_to_2.4.1.log**

**Comment by btry** [comment]
no feedback, cannot reproduce
