### ISSUE TITLE
Add the Target Ticket - Destination entity - by the domain e-mail Actor Requester In case of Anonymous Users

### ISSUE THREAD

**Issue by Gambware** [pluginsGLPI/formcreator#481]
This can be very useful when you allow tickets to be opened by anonymous users. 

Imagine that you give support to several companies in different countries and you don't register all Requester on your GLPI Database. 

You can create one form for each language and based on the domain e-mail of each requester the ticket will be opened direct on the correct Entity.

![image](https://cloud.githubusercontent.com/assets/24397740/22709562/dbe678dc-ed3f-11e6-93f1-1d993f2ed22a.png)

**Comment by btry** [comment]
Hi

I assume this field **Mail domain surrogates entity** is the one you want to use for matching.

![image](https://cloud.githubusercontent.com/assets/14139801/22710792/00fe6500-ed7f-11e6-84f6-ad91e8c5697d.png)

**Comment by Gambware** [comment]
Yes, Exactly. 

But I'm not sure if "Mail domain surrogates entity" will support multi email domains

**Comment by btry** [comment]
Hi

No, this field is for a single domain.

Le 7 février 2017 22:51:13 GMT+01:00, Gambware <notifications@github.com> a écrit :
>Yes, Exactly. 
>
>But I'm not sure if "Mail domain surrogates entity" will support multi
>email domains
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pluginsGLPI/formcreator/issues/481#issuecomment-278152226

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Gambware** [comment]
So, I think this will not work very well, Sometimes we can have more than one e-mail domain per entity. 
Maybe if the GLPI Rules allowed you create a rule where you can move the ticket entity based on tickets field like the "Mail Requester" but currently isn't possible. 

Currently I'm doing this with a Shell Script direct on the GLPI DB (Cron to run each 1 min)

mysql -u glpiuser -ppassword -D GLPI_DB_NAME -e "UPDATE glpi_tickets INNER JOIN  glpi_tickets_users ON glpi_tickets.id = glpi_tickets_users.tickets_id **SET glpi_tickets.entities_id = 14** where **glpi_tickets.entities_id = 7** AND **glpi_tickets_users.alternative_email LIKE '%emaildomain.com%'**;"

This is the Default Entity where formcreator create tickets to Clients from Spain: glpi_tickets.entities_id = 7

This is the e-mail domain from the client that probably will open a ticket glpi_tickets_users.alternative_email LIKE '%emaildomain.es%'

And this is the entity that I want to move e-mails from emaildomain.es SET glpi_tickets.entities_id = 14

I have several lines on this script one for each client in Spain, Panama, Brasil and United States.

**Comment by btry** [comment]
Would it be acceptable to divide a customer into sub entities, one per domain ?

**Comment by Gambware** [comment]
That's works thanks !
