### ISSUE TITLE
Missing indexes

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#483]
While testing current version (2.5.0 - develop) with real data, i encounter some missing indexes on theses tables (foreign keys):
- glpi_plugin_formcreator_answers
- glpi_plugin_formcreator_forms_answers

For theses 2 tables, its important, we have execrable performances in form > Form answer tab.

But i think a review of all table is necessary, i detected more missing index for foreign keys (entities_id for example) in a lot of formcreator tables 

Maybe to do after #480 merge (or in the same time)

**Comment by orthagh** [comment]
I targeted 2.4.1 finally  as a customer says the service catalogue has bad performance, but both versions need this work, i think.

**Comment by btry** [comment]
this is #450

**Comment by orthagh** [comment]
Here is the priority :

```sql
ALTER TABLE `glpi_plugin_formcreator_answers`
   ADD INDEX `plugin_formcreator_forms_answers_id` (`plugin_formcreator_forms_answers_id`);
ALTER TABLE `glpi_plugin_formcreator_forms_answers`
   ADD INDEX `plugin_formcreator_forms_id` (`plugin_formcreator_forms_id`);
```

**Comment by btry** [comment]
Also added in PR for installer rewrite

**Comment by btry** [comment]
All index are added in both 2.4.1 and 2.5.0.
