### ISSUE TITLE
Enable json filetype and forms import

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#484]
Following an internal discussion, i reopen the subject of importing form and the acceptation of json filetype by glpi upload.

Previously, we stated we don't want to update silently this filetype but it 's a little confuse for users on import form.

So Here is the proposal:
On the import form, it json extension is not enabled, we could diplay a (strongly visible) message alerting the user and ask for enabling the extension.
And a button, which permits the autorisation in one click.

**Comment by btry** [comment]
Hi

this looks good to me. However, I guess a user able to upload a file may not have the right to enable JSON file extension. 

I think this could be added in milestone 2.4.1.

**Comment by btry** [comment]
done in 4afede3cd83834779fd3e33dd202ee5592474ec6
