### ISSUE TITLE
display requester in ticket's title

### ISSUE THREAD

**Issue by gotanbl** [pluginsGLPI/formcreator#485]
I think that is very usefull to put macro in ticket title for Form requester like ##form_requester##. 
Similar like ##anser## and ##question##!
Now we need to ask user about his/her name and with macro ##anser_no## and use in ticket tile.
If need to validate form if dont ask user for name we dont know who is requester!
For me is useless to ask user about name after he/she is logged in. 
It will be very usefull to devolop this in future release!
Thanks!

**Comment by btry** [comment]
Hi

If you're a validator and show a list of forms to validate you can see the requester.

show your forms
![image](https://cloud.githubusercontent.com/assets/14139801/22930634/8821f2e4-f2c1-11e6-8e54-fc756ab72552.png)

click **All my forms (validator)**
![image](https://cloud.githubusercontent.com/assets/14139801/22930653/a0948de6-f2c1-11e6-8fd3-d0da0b9720fa.png)

there is a column **requester**. Can it satisfy your need.

**Comment by gotanbl** [comment]
Yes, I satisfied!
I overlooked this.
Thanks anyway. 
This macro is usefull but not indispensable.

**Comment by btry** [comment]
great; I close.

**Comment by flo1994** [comment]
I would like to insert an information field into a form. This field is intended to represent the requester of a form. Are there possibilities?

Unfortunately, the following attempt was not successful:

![requester](https://cloud.githubusercontent.com/assets/20795317/26402772/e229a9cc-408b-11e7-9fac-632bff4f0ef4.JPG)

**Comment by btry** [comment]
Hi @flo1994 

Please open a new issue for your need.
