### ISSUE TITLE
Export/Import Forms

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/formcreator#486]
I see a function "import forms" in FC 2-4-0. 
How use it ?
 I don't see an Export function for download existing forms.
 I can't also duplicate forms from a server to another one (i.e, duplicate forms created for test on a production server).

Thank you.

**Comment by btry** [comment]
Hi

The export feature is in the mass actions of a form. Using it let you download a JSON file containing the definition of the previously selected forms.

To import it (in an other server for example) you must first enable json file extension in the GLPI. 

A caveat with the export / import feature : if your exported form is linked to objects belonging to GLPI itself (i.e. users, groups, tickets templates) you must have the same IDs existing in the GLPI instance you import into. 

The feature was designed to satisfy your need : copy forms from test server to production server.

**Comment by matth974** [comment]
Hi,

Thank you! 
I'll try it soon.

Best regards.
