### ISSUE TITLE
Affichage utilisateur LDAP

### ISSUE THREAD

**Issue by Azga** [pluginsGLPI/formcreator#490]
Bonjour, 

Je m'y prend peut-être mal mais j'ai créé un formulaire qui possède une question sur le choix d'un utilisateur et qui se sert de la fonction LDAP avec comme filtre
(& (samaccountname=*) (&(objectCategory=Person)(sAMAccountName=*)(memberOf=cn=fooUsers,ou=foobar,ou=barfoobar,dc=foobarfoo,dc=net)))

Lorsque j'utilise mon formulaire, je n'ai pas de souci, la combobox m'affiche bien la liste des utilisateurs avec le bon filtre et me permet bien d'en sélectionner un.
Par contre une fois le formulaire validé et que se soit dans le ticket ou dans la lecture du formulaire l'affichage de l'utilisateur est vide.

J'ai testé avec plusieurs filtres fonctionnels (Au cas ou) mais rien  n'y fait.

Une idée, un bug ?

GLPI 9.1.2
Formcreator 2.4.0

Merci de votre retour.

Cordialement.

**Comment by btry** [comment]
Bonjour

Ca peut être un bug en effet. Avez-vous cherché dans la table glpi_plugin_formcreator_answers si il y a une donnée cohérente une fois le formulaire rempli et validé ?

**Comment by Azga** [comment]
Bonjour, 

J'ai bien une entrée dans la table et elle correspond bien au bon ID de la variable de réponse
La variable n'est pas reprise à l'affichage du formulaire ni dans le ticket.

Après plusieurs essais j'ai compris d'ou vient le souci....
Lorsque que le nom dans la base LDAP possède un caractère spécial (é ë, ...) la valeur ne s'affiche pas.

Par contre je ne sais pas quoi modifier pour corriger ce souci.

**Comment by btry** [comment]
Alors il y a probablemnt un souci avec l'échappement de ces caractères.

**Comment by Azga** [comment]
A la création du formulaire j'ai bien tous les noms LDAP d'affichés et sélectionnables.
Dans la base j'ai bien le bon nom sélectionné qui est inscrit (Caractère spéciaux ou non)
C'est juste à l'affichage du formulaire ou du ticket une fois la form validée que le problème se pose.

**Comment by btry** [comment]
Regardez dans les logs php-errors.log si il y a des erreurs. Vérifiez aussi sql-errors.log (même si à mon avis il n'y auira rien de lié à ce bug).

**Comment by Azga** [comment]
Je n'ai que ce genre d'erreur dans la log php-errors.log et qui correspond aux checkbox (Dès que l'on coche ou décoche ces lignes apparaissent). 
Rien concernant le problème initial. 

 *** PHP Warning(2): json_decode() expects parameter 1 to be string, array given
  Backtrace :
  :
  plugins/formcreator/inc/fields.class.php:173       json_decode()
  plugins/formcreator/ajax/showfields.php:23         PluginFormcreatorFields::isVisible()
2017-02-15 07:57:39 [xxx@#######]
  *** PHP Warning(2): json_decode() expects parameter 1 to be string, array given
  Backtrace :
  :
  plugins/formcreator/inc/fields.class.php:173       json_decode()
  plugins/formcreator/ajax/showfields.php:23         PluginFormcreatorFields::isVisible()

Et comme prévu rien dans le sql-errors.log

**Comment by btry** [comment]
Pour l'erreur trouvée dans php-errors.log j'ai déjà un correctif. Appliquez-le.

https://github.com/pluginsGLPI/formcreator/commit/954dee1fe116e805a267ab1da724e0d1477c547d

Il est miraculeux: il résout plein de tickets alors que ça me semblait sans relation. Voyons si son bénéfice va jusqu'à résoudre votre bug.

**Comment by Azga** [comment]
Cela corrige effectivement bien le souci des checkbox mais pas mon souci initial.
Dommage j'aurais bien cru au miracle ;)

**Comment by Azga** [comment]
Pas de news sur ce souci ?

**Comment by btry** [comment]
Bonjour

Rien de nouveau pour le moment

**Comment by Azga** [comment]
Bonjour, 
J'ai essayé de chercher à corriger ce souci mais avec mes maigres connaissances je ne suis pas arrivé à grand chose.
Ce que je peux dire, si ça permet de faire avancer, est que le problème ne se présente que sur LDAP.
En effet, dans mon formulaire j'ai une selectbox qui m'affiche tous les utilisateurs d'un groupe Active Directory.
Comme dit plus haut lors de la saisie dans le formulaire tout se passe bien, je vois bien ma liste d'utilisateur avec les caractères spéciaux (é, ë, ...).
Lorsque je valide le formulaire et que je regarde les entrées dans la DB tout est bien affiché également (J'ai même forcé la collation à utf8_unicode_ci, mais pas mieux)

C'est lors de l'affichage du formulaire en mode "page web" ou dans le ticket que le contenu sélectionné dans la selectbox est à blanc (Rien ne s'affiche)
J'ai fait un test avec une textbox, pas de souci, les caractères spéciaux s'affichent correctement.

Pour info, Active Directory stock les données en UTF8 (Donc normalement pas de souci avec GLPI qui est full UTF8 si j'ai tout compris).

J'ai plus l'impression que c'est une souci avec un json_encode ou decode de trop ou mal placé qqpart dans le code.
D'après mes recherches, 2 solutions reviennent souvent : 
- Soit forcer un encodage de la valeur avec  utf8_encode
- Soit forcer un SET NAMES utf8 sur la query DB

Il y a aussi la possibilité de placer un json_last_error au bon endroit pour voir ce que ca retourne.

Pour finir, Il y a à priori également des petit soucis entre l'interprétation de l'UTF8 sous Windows (Donc mon AD) et PHP/linux

En espérant que tout cela vous aidera à faire avancer le schmilblick pour mon plus grand bonheur :)

**Comment by btry** [comment]
Bonjour,

Savoir que l'info est bien enregistrée en BDD me rend service. Pouvez-vous montrer un exemple d'une donnée qui n'est pas restituée? Il se peut en effet que l'encodage JSON soit en cause, vu que j'ai corrigé d'autres problèmes. Essayez la version 2.4.1, peut-être que c'est déjà corrigé (et la release est en cours)

**Comment by Azga** [comment]
Bonjour, 

Je suis passé sur la branch hotfix/2.4.1 et toujours le même souci.

Affichage dans un ticket : 
![tickets_display](https://cloud.githubusercontent.com/assets/9134248/24502806/a2ec55c8-154f-11e7-9fdf-3815ba6060f9.jpg)

Affichage sur la visu WEB du formulaire:
![web page_display](https://cloud.githubusercontent.com/assets/9134248/24502807/a50fa2ce-154f-11e7-88b3-ac68fd532fe4.jpg)

Par contre je remarque que pour ce qui est récupéré de LDAP "Raphaël" on retrouve la même écriture dans la DB
![database_selectbox ldap](https://cloud.githubusercontent.com/assets/9134248/24502809/a6bef246-154f-11e7-8a5c-06d0d2db2b52.jpg)

A contrario, j'ai saisi un nom avec un caractère spécial (un é) dans une textbox et celui-ci est encodé dans la DB
![database_textbox](https://cloud.githubusercontent.com/assets/9134248/24502813/abee1ec2-154f-11e7-964d-c9f3df14188f.jpg)

En espérant que ca aide.

Cordialement.

**Comment by btry** [comment]
Bonjour

J'ai réussi à  reproduire, et à corriger.

J'ai fait un patch basé sur la version 2.4.2 du plugin.
https://github.com/btry/formcreator/tree/feature/490_ldapfield_not_rendered

Pouvez-vous l'essayer ? Si il est concluant, je le verserai dans la version 2.5.0.

**Comment by btry** [comment]
A défaut de retour, et mes  tests semblant concluants, je ferme. Si el problème persiste, merci d'ouvrir un nouveau ticket.

**Comment by Azga** [comment]
Bonjour, 

Désolé pour la réponse tardive.
Je valide le patch est fonctionnel.

Merci.

**Comment by btry** [comment]
Bonjour

Parfait. Le patch sera disponible dans la prochaine release.
