### ISSUE TITLE
Button send on Public Forms (Users that aren't logged in GLPI) is not Translated.

### ISSUE THREAD

**Issue by Gambware** [pluginsGLPI/formcreator#494]
The language of this form is in Español but if the users aren't logged in GLPI, the button show in English (that is my default langue of GLPI).

NOTE: Just in public forms and with users that aren't logged in. If user is logged in GLPI, the button will show in Default User Language.

![image](https://cloud.githubusercontent.com/assets/24397740/22887706/b1b96a8c-f1c8-11e6-97c3-bdb9e6df2fe5.png)

**Comment by btry** [comment]
Hi

GLPI sets the locales from the user's preferences. If the user is anonymous GLPI cannot guess the language and uses the default one.

Maybe Formcreator might set itself a language in such case from something else. We may use a HTTP header sent by the browser.

**Comment by btry** [comment]
Hi

Formcreator 2.12.0 supports form translations. For anonymous users, a langauge is choosen from available translations. This issue should be solved.
