### ISSUE TITLE
Form not displaying after migration

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#496]
I have recently migrated from 0.90.5 to 9.1.2 with the plugin at its latest version 2.4.0. After the migration the questions in the forms do not appear, only the sections
![capture](https://cloud.githubusercontent.com/assets/9021998/22918519/6077b932-f293-11e6-9846-98120d7442c6.PNG)
. See attached image. Is there any way to repair this? This behaviour is repeated even if I create a new form.

**Comment by btry** [comment]
Hi

First check your browser's cache is up to date : press Ctrl+F5, Ctrl+R or Ctrl+Shift+R

If this does not solve your issue, please tell me if some or all questions have conditions.

**Comment by grego1981** [comment]
I tried your suggestions, even used a PC never accessed GLPI after cleaning its cache. I then created a new form with a single text question and nothing more, to no avail.

**Comment by btry** [comment]
Can you apply this patch https://github.com/pluginsGLPI/formcreator/commit/954dee1fe116e805a267ab1da724e0d1477c547d and tell if this helps ?

**Comment by grego1981** [comment]
Yes it works! After applying the patch my forms work as they supposed to!

Thank you!

**Comment by btry** [comment]
Great. This patch is included in 2.4.1.
