### ISSUE TITLE
Bug at installation

### ISSUE THREAD

**Issue by chris-pb** [pluginsGLPI/formcreator#498]
Hi, trying to install the 2.4.0 version on glpi 9.1.2 and got the following error : Illegal mix of collations for operation 'UNION'

Here's the SQL log : 

         SELECT DISTINCT
            CONCAT(\'f_\',`fanswer`.`id`)    AS `id`,
            `fanswer`.`id`                 AS `original_id`,
            \'PluginFormcreatorForm_Answer\' AS `sub_itemtype`,
            `f`.`name`                     AS `name`,
            `fanswer`.`status`             AS `status`,
            `fanswer`.`request_date`       AS `date_creation`,
            `fanswer`.`request_date`       AS `date_mod`,
            `fanswer`.`entities_id`        AS `entities_id`,
            `fanswer`.`is_recursive`       AS `is_recursive`,
            `fanswer`.`requester_id`       AS `requester_id`,
            `fanswer`.`validator_id`       AS `validator_id`,
            `fanswer`.`comment`            AS `comment`
         FROM `glpi_plugin_formcreator_forms_answers` AS `fanswer`
         LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
            ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
         LEFT JOIN `glpi_items_tickets` AS `itic`
            ON `itic`.`items_id` = `fanswer`.`id`
            AND `itic`.`itemtype` = \'PluginFormcreatorForm_Answer\'
         GROUP BY `original_id`
         HAVING COUNT(`itic`.`tickets_id`) != 1

         UNION

         SELECT DISTINCT
            CONCAT(\'t_\',`tic`.`id`)       AS `id`,
            `tic`.`id`                    AS `original_id`,
            \'Ticket\'                      AS `sub_itemtype`,
            `tic`.`name`                  AS `name`,
            `tic`.`status`                AS `status`,
            `tic`.`date`                  AS `date_creation`,
            `tic`.`date_mod`              AS `date_mod`,
            `tic`.`entities_id`           AS `entities_id`,
            0                             AS `is_recursive`,
            `tic`.`users_id_recipient`    AS `requester_id`,
            \'\'                            AS `validator_id`,
            `tic`.`content`               AS `comment`
         FROM `glpi_tickets` AS `tic`
         LEFT JOIN `glpi_items_tickets` AS `itic`
            ON `itic`.`tickets_id` = `tic`.`id`
            AND `itic`.`itemtype` = \'PluginFormcreatorForm_Answer\'
         WHERE `tic`.`is_deleted` = 0
         GROUP BY `original_id`
         HAVING COUNT(`itic`.`items_id`) <= 1

  Error: Illegal mix of collations for operation 'UNION'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:78
  plugins/formcreator/hook.php:20                    PluginFormcreatorIssue::install()
  inc/plugin.class.php:664                           plugin_formcreator_install()
  :                                                  Plugin->install()
  front/plugin.form.php:49                           call_user_func()

Environment
PHP FPM 5.6.20
mysql  Ver 15.1 Distrib 5.5.49-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by btry** [comment]
Hi

It is a duplicate of #330.

I need to be sure : are you installing or upgrading the plugin ?

**Comment by chris-pb** [comment]
It's an installation of the plugin

**Comment by btry** [comment]
Can you check the collation of all your tables 

All your tables should use collation utf8_unicode_ci (except glpi_notimportedemails, charset latin1)

**Comment by chris-pb** [comment]
I changed the collation of the tables that where in latin1 but the problem remains the same.

**Comment by btry** [comment]
Can you tell which tables you changed ?

You should not change glpi_notimportedemails : it is absolutely not related to the plugin.

**Comment by chris-pb** [comment]
Here's the liste of the tables changed

- glpi_plugin_addressing_configs
- glpi_plugin_centreon_config
- glpi_plugin_centreon_host
- glpi_plugin_centreon_profiles
- glpi_plugin_centreon_service
- glpi_plugin_centreon_users
- glpi_plugin_dashboard_config
- glpi_plugin_dashboard_map
- glpi_plugin_mobile_options
- glpi_plugin_mobile_profiles
- glpi_plugin_mreporting_profiles
- glpi_plugin_treeview_display
- glpi_plugin_treeview_preference
- glpi_plugin_treeview_profiles

glpi_notimportedemails was not changed and is still in latin1

**Comment by btry** [comment]
None of these tables belong (or are related) to FormCreator. That said, it would be a good idea to report an issue to maintainers of plugins treeview, mreporting, mobile, centreon and addressing.

About FormCreator, I need to investigate to find other other things.

As the message does not contains more detail to find the tables or columns responsible of the error, and I cannot reproduce (already tried for #330) I think you should try to create the view several times, removing a column in the 2 parts of the union, until the CREATE VIEW succeeds. This way I think we will find which column causes the issue.

**Comment by chris-pb** [comment]
ok, i've done this and the the query is working without the 2 columns **name** and **comment**

**Comment by btry** [comment]
Hi

I assume adding only one of these two colums make the query fail again ?

**Comment by chris-pb** [comment]
Hi, 
Right. The query works only if the 2 columns are removed

**Comment by btry** [comment]
Hi

To solve a performance issue I had to drop the view and use a real table. I think it will also solve your problem. 

Feel free to test the branch hotfix/2.4.1 and feedback if your issue disappears.

**Comment by chris-pb** [comment]
Hi, i downloaded and installed successfully the branch hotfix/2.4.1
Your modification solved the problem !
The plugin is now fully functional

**Comment by btry** [comment]
Thank you for yiur feedback.

Dont forget this branch is still un dev. It will become the official 2.4.1 release soon.
