### ISSUE TITLE
Valideur du formulaire devient demandeur du ticket target

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/formcreator#50]
Le valideur du formulaire devient le demandeur du ticket créé.
Il faut que le demandeur initial qui a rempli le formulaire soit toujours le demandeur du ticket.

**Comment by Zpard** [comment]
Bonjour, 
Je me permet de rajouter une note sur ce bug car nous rencontrons le problème aujourd'hui. 
Notre version de GLPI : 9.3.2
Version du Plugin 2.8.2

Lorsqu'on met un formulaire avec le valideur voici le comportement que nous avons :
- Le ticket côté Gestionnaire affiche le bon demandeur. En revanche, dans l'onglet "traitement du ticket" c'est le valideur qui apparaît. 
- Côté demandeur, le "demandeur" du ticket est modifié dès la validation du formulaire. Le demandeur vois alors le valideur à sa place dans le ticket que ça soit dans l'onglet "Ticket" ou "Traitement du ticket".
D'avance merci pour votre support. 

Zpard

**Comment by btry** [comment]
Bonjour

Il se peut que cette PR (inachevée pour le moment) aide à résoudre le souci

https://github.com/pluginsGLPI/formcreator/pull/1391

**Comment by Zpard** [comment]
Bonjour,
Merci pour votre réponse. 
Après avoir appliqué le patch, cela semble fonctionné côté "Demandeur". Il n'y a que dans la partie "Traitement du ticket" ou le demandeur reste le valideur. 
Est-ce qu'il y a d'autre chose à modifier ? 
D'avance merci,

**Comment by btry** [comment]
Bonjour
  
Oui il y a encore deds choses à modifier, puisque je n'ai pas encore terminé le patch. JE ne sais pas encore quand je pourrai reprendre cette tâche. 

Mettez un emoticone ou quelque chose sur la PR du patch pour être informé des futurs changements.
