### ISSUE TITLE
Answer form: Result for dropdown itens

### ISSUE THREAD

**Issue by jswytka** [pluginsGLPI/formcreator#500]
After submit form with Dropdown selector. Show field condition in 'Answer form' not working. But works when fill out the form.

![image](https://cloud.githubusercontent.com/assets/21204053/22930956/7279fc54-f2a1-11e6-9cde-068d50a495c6.png)

**Comment by btry** [comment]
I reproduce

**Comment by btry** [comment]
I guess your question is tested agains a number (the ID of your item **Additional Fields - Equipoe** ?

**Comment by jswytka** [comment]
@btry Yes. 
I even tested with glpi core itens (dropdown) and show same behavior .

**Comment by btry** [comment]
I tried myself with a core item. 

Here is what I found : 
When a user fills a form, the visibility is updated depending on the actions of the user, if a visibility is computed depending on a dropdown, the value of the dropdown used for the compputation is the ID of the choosen item. Then in the conditions you need to use this ID.

When a user shows a previously filled form, the visibility if a dropdown-dependant question is no longer compputed against the ID of the selected item, but the displayed value if t he dropdown. 

To not break behavior between 2.4.0 and 2.4.1 I shall fix this to always use the ID.

**Comment by btry** [comment]
I created a quick fix. Please try to add the commit https://github.com/pluginsGLPI/formcreator/commit/05153eaf939f8b4449c6a39dbf7a80add3ce6a5f

Also if you have some other forms with conditions, check if this fix introduce an other bug. Fields are a tricky part in this plugin and need rewrite.

**Comment by jswytka** [comment]
@btry  Works fine !!! Thnx !!

**Comment by btry** [comment]
Great ! I close.
