### ISSUE TITLE
All my forms (validator) don't work 

### ISSUE THREAD

**Issue by gotanbl** [pluginsGLPI/formcreator#503]
Btry, 
As you described in closed ticket #485 to view All my forms (validator) click on link for that.
But for me this does not work.
![image](https://cloud.githubusercontent.com/assets/24296903/23023661/e649568c-f456-11e6-9b43-a08edf72f2e6.png)
![image](https://cloud.githubusercontent.com/assets/24296903/23023691/0020e160-f457-11e6-9ca5-2c27536d6e6f.png)
![image](https://cloud.githubusercontent.com/assets/24296903/23023708/11a7158a-f457-11e6-9b17-8c0d52a760c7.png)
I didn't test it, before, until now.
On picture that you uploaded seems that it work, but for me don't.
I have glpi 9.1.2 and formcreator 2.4.0.
Thanks

**Comment by btry** [comment]
Hi

I thought this is a bug.. but not yet. 

Have a look on your seond screenshot : your list is filtered by the status **waiting**.  Remove this filter and let me know if you got all your forms.

**Comment by gotanbl** [comment]
Yes, I got all forms.

**Comment by btry** [comment]
Hi

The plugin is designed to show only the waiting forms by default. If you got all the expected forms when removing the status filter, I think we can close.

**Comment by gotanbl** [comment]
Second picture above is after I  click on All my forms (validator),so I  think that this link doesn't work as expected. 
Do you test it?
Third picture is after I click on button for forms waiting for validation.
And this work as you design it. 
Maybe I didn't be clear what is problem for me.

**Comment by dcoronel1985** [comment]
To solve this problem you must do the following:

in formcreator/inc/form.class.php (line 775-785)

change the query:

     /*$query = "SELECT fa.`id`, f.`name`, fa.`status`, fa.`request_date`
            FROM glpi_plugin_formcreator_forms f
            INNER JOIN glpi_plugin_formcreator_forms_validators fv ON fv.`plugin_formcreator_forms_id`=f.`id`
            INNER JOIN glpi_plugin_formcreator_forms_answers fa ON f.`id` = fa.`plugin_formcreator_forms_id`
            WHERE (f.`validation_required` = 1 AND fv.`items_id` = '$userId' AND fv.`itemtype` = 'User'
               OR f.`validation_required` = 2 AND fv.`items_id` IN ($groupIdList) AND fv.`itemtype` = 'Group'
            )
            AND f.is_deleted = 0
            ORDER BY fa.`status` ASC, fa.`request_date` DESC
            LIMIT 0, 5";
     $result = $DB->query($query);*/
By the following:

$query = "SELECT fa.id, f.name, fa.status, fa.request_date
FROM glpi_plugin_formcreator_forms f
INNER JOIN glpi_plugin_formcreator_forms_validators fv ON fv.plugin_formcreator_forms_id=f.id
INNER JOIN glpi_plugin_formcreator_forms_answers fa ON f.id = fa.plugin_formcreator_forms_id
WHERE (f.validation_required = 1 AND fv.items_id = '$userId' AND validator_id = '$userId'
OR f.validation_required = 2 AND fv.items_id IN ($groupIdList) AND fv.itemtype = 'Group'
)
AND f.is_deleted = 0
ORDER BY fa.status ASC, fa.request_date DESC
LIMIT 0, 5";
$result = $DB->query($query);

I solved it that way and it works perfect.

GLPI version 9.1.4
FormCreator version 2.5.1

Regards!

**Comment by btry** [comment]
Hi Tis issue is old, and probably obsolete. 

Your suggestion cannot work as it ignores an itemtype check which is required.
