### ISSUE TITLE
Regex in additional validation field non-ascii characters

### ISSUE THREAD

**Issue by gotanbl** [pluginsGLPI/formcreator#506]
I need to regex some non-ascii characters like čćžđš (bosnian|serbian|croatian special characters) .
For example:
 /[\x{0161}\x{0160}\x{017d}a-z]+/u
\x{0161} represent š
\x{0160} represent Š
\x{017d} represent Ž
stream above represent [šŠŽa-z]+.
After I put it in text field for additional validation and save it, formcreator saved it as
/[x{0161}x{0160}x{017d}a-z]+/u$/
And this not work!
Error in php_errors.log:
*** PHP Warning(2): preg_match(): Unknown modifier '$'
  Backtrace :
  :                                                  
  .../formcreator/inc/fields/text-field.class.php:21 preg_match()
  plugins/formcreator/inc/form.class.php:1088        textField->isValid()
  plugins/formcreator/front/form.form.php:74         PluginFormcreatorForm->saveForm()

**Comment by btry** [comment]
In the source code, the regex is forced to begin with **/^** and to finish with **$/**

Because  your regex terminates with **u**, **$/ is appended. I think you want to use UTF-8 ( http://php.net/manual/fr/reference.pcre.pattern.modifiers.php ) . Can you find a workaround to not use any modifier ?

**Comment by gotanbl** [comment]
Yes, I want to use UTF-8. 
I am not find any other solution, yet. 
I will try to find, but I am not shure is it possible.

**Comment by gotanbl** [comment]
It is possible with \p{L}+      matches any kind of letter from any language.
But also do not work! No errors in php_errors.log.

**Comment by btry** [comment]
Then I think I'll have to modify (maybe drop ?) the checks on regex to allow modifiers.

**Comment by btry** [comment]
Hi

Please have a look on this PR

https://github.com/pluginsGLPI/formcreator/pull/701/files

This would help you by giving you the fill responsibility (and power) on the regex validation.

**Comment by btry** [comment]
Hi 

The PR i submitted to you is merged. I hope it will satisfy your need. If not, please open a new issue.
