### ISSUE TITLE
question -> multiple choice, bad encoding

### ISSUE THREAD

**Issue by Co0ker** [pluginsGLPI/formcreator#508]
Hi. I found a bug.
If set answer on question of type = multiple choice, formcreator records in the database, bad encoding symbol.
locale = ru_RU
Example:
answer = Переместить в отдел ИТ
in db = u041fu0435u0440u0435u043cu0435u0441u0442u0438u0442u044c u0432 u043eu0442u0434u0435u043b u0418u0422
Help pls, and sorry for the English :)

**Comment by btry** [comment]
Hi

I had a doubt about the type of your field. I guessed the type you called **Multiple choice** is actually **Multiselect**.

Assuming I'm right, I did a patch which seems to work. In the database, the russian text is now saved in a readable way, and it also solved the lack of answer when viewing the answers.

The patch is here, based on 2.4.0. Please, test it and feedback

https://github.com/btry/formcreator/tree/feature/fix_for_russian_and_non_latin_strings

**Comment by Co0ker** [comment]
Many thanks
After the patch, the problem disappeared
