### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by NoK80** [pluginsGLPI/formcreator#509]
Bonjour,
J'ai créé un formulaire avec le plugin formcreator. quand je clic sur envoyer j'ai l'erreur
 "the server is currently unable to handle this request HTTP ERROR 500" 
quand je referchi la page j'ai bien le message "Votre ticket a bien été enregistré, son traitement est en cours." 
Sanchant que depuis le premier clic sur envoyer, le formulaire est enregistré et le ticket est créé. 

version GLPI 0.85.2 ,  version formcreator 0.90 - 1.3.4
Je ne peux pas faire un upgrade de GLPI pour le moment à cause d'autre plugin.

Merci de me donner une solution.

**Comment by btry** [comment]
Bonjour

Vérifiez les logs du serveur HTTP : il devrait y avoir un backtrace qui aidera à comprendre ce qu'il s'est passé.

**Comment by NoK80** [comment]
Merci pour votre réponse.
Voici le log
[Tue Feb 21 10:18:45 2017] [error] [client x.x.x.35] PHP Fatal error:  Class 'Item_Ticket' not found in /usr/share/glpi/plugins/formcreator/inc/targetticket.class.php on line 1199, referer: http://x.x.x.x/glpi/plugins/formcreator/front/formdisplay.php?id=7
[Tue Feb 21 10:25:04 2017] [error] [client x.x.x.x] PHP Fatal error:  Class 'Item_Ticket' not found in /usr/share/glpi/plugins/formcreator/inc/targetticket.class.php on line 1199, referer: http://x.x.x.x/glpi/plugins/formcreator/front/formdisplay.php?id=7
[Tue Feb 21 10:38:40 2017] [notice] Graceful restart requested, doing restart
[Tue Feb 21 10:38:41 2017] [notice] Digest: generating secret for digest authentication ...
[Tue Feb 21 10:38:41 2017] [notice] Digest: done
[Tue Feb 21 10:38:41 2017] [notice] SSL FIPS mode disabled
[Tue Feb 21 10:38:41 2017] [notice] Apache/2.2.17 (Unix) DAV/2 PHP/5.3.8 mod_ssl/2.2.17 OpenSSL/1.0.0e-fips mod_perl/2.0.4 Perl/v5.12.4 configured -- resuming normal operations
[Tue Feb 21 10:38:41 2017] [error] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Tue Feb 21 10:40:58 2017] [error] [client x.x.x.x] PHP Fatal error:  Class 'Item_Ticket' not found in /usr/share/glpi/plugins/formcreator/inc/targetticket.class.php on line 1199, referer: http://x.x.x.x/glpi/plugins/formcreator/front/formdisplay.php?id=7

**Comment by btry** [comment]
La classe non trouvée appartient à GLPI.

Vérifiez que vous pouvez créer un ticket et associer un ordinateur à ce ticket. Si ça plante, il y a un souci dans votre GLPI.

**Comment by NoK80** [comment]
On n'a pas de souci par rapport à la creation de ticket ni l'associer un ordi

**Comment by btry** [comment]
Une fonctionnalité a été introduite dans GLPI au milieu des releases de bugfix, permettant d'associer plusieurs objets à un ticket. Les versions précédentes ne permettant qu'une seule association.

Je viens de vérifier, la fonctionnalité est apparue avec GLPI 0.85.3. Son implémentation a requis l'apparition de la classe Item_Ticket qu'il vous manque.

Donc la solution serait d'upgrader GLPI en 0.85.3, ce qui devrait être tout à fait envisageable dans votre cas. Faites un essai sur une plateforme de test; formcreator ne rencontrera plus ce bug.

**Comment by btry** [comment]
Note : Vous avez pris un petit risque tout de même : FormCreator 0.90-1.3.4 est officiellement comaptible avec GLPI 0.90 et supérieurs, ce qui exclut GLPI 0.85.

**Comment by btry** [comment]
Bonjour

Je me permets de clore ce ticket car le problème est une incompatibilité entre la version de GLPI et la version du plugin, connue et choisie au moment du développement de la version de FormCreator que vous utilisez.

**Comment by nafoufa** [comment]
bonjour tous
besoin d'aide
j'utilise glpi version 0-84-5 sous redhat enterprise et j'ai un petit soucis c que en attribuant un ticket a un technicien il me donne erreur 500.
merci d'avance

**Comment by btry** [comment]
Bonjour

Les versions du plugin pour GLPI 0.84.x ne sont plus maintenues. Je vous invite à considérer l'upgrade de votre GLPI vers une version 9.1.6 au minimum.

De plus, créez plutôt un nouveau ticket, au lieu de commenter un ticket fermé. Vous pouvez, si besoin, faire une référence à un autre ticket en mentionnant son numéro précédé d'un dièze.

**Comment by nafoufa** [comment]
merci pour votre reponse ..
maintenant j'ai un autre soucis en attribuant un ticket au groupe de
technicien faite par admin glpi, la réception des email au groupe sa prend
du temps comment je peut reduire ce temps pour que a chaque attribution de
ticket au technicien ces techniciens reçoivent automatiquement les email ..
merci d'avance

**Comment by btry** [comment]
Merci de créer un nouveau ticket car votre question n'est pas liée à celui-ci.

**Comment by nafoufa** [comment]
ok merci

2017-08-14 14:56 GMT+02:00 btry <notifications@github.com>:
