### ISSUE TITLE
Added the "Associated items" field in the target ticket.

### ISSUE THREAD

**Issue by jfg** [pluginsGLPI/formcreator#512]
--------------------- EN ------------------------
Hello and first thank you for this plugin today in version 0.90-1.3.4 on my GLPI DEV!

I expose my problem:

When creating a ticket via a form, it is possible to display a selection list linked to my software fleet. What I have surely done.

However after selection, I can not use the response value to fill in the "Associated items" value of my final ticket!

Do you have a solution to my problem?

Thank you in advance for your return.

--------------------- FR ------------------------
Bonjour et tout d'abord merci pour ce plugin aujourd'hui en version 0.90-1.3.4 sur mon GLPI de DEV !

J'expose mon problème  : 

Lors de la création d'un ticket via un formulaire, il est possible d'afficher une liste de sélection lié à mon parc logiciel. Ce que j'ai bien sure fait.

Cependant après sélection, je ne peux pas utiliser la valeur de réponse pour renseigner la valeur "Éléments associés" de mon ticket final !

Avez vous une solution à ma problématique ?

Merci d'avance pour votre retour.

**Comment by btry** [comment]
Hi

The plugin does not associate assets to the generated tickets because this is not implemented. Your request duplicates #232

**Comment by btry** [comment]
As this issue duplicates an older one, I close

**Comment by btry** [comment]
Hi

Feature implemented
