### ISSUE TITLE
Error during migration

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/formcreator#522]
From 084.2.1.5 to 2.4.0

*** MySQL query error:
  SQL: ALTER TABLE `$table` ADD `name` VARCHAR(255) NOT NULL AFTER `id`;
  Error: Table 'glpi91.$table' doesn't exist
  Backtrace :
  plugins/formcreator/inc/form_answer.class.php:885

**Comment by btry** [comment]
Fixed, thank you
