### ISSUE TITLE
Message after migration

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/formcreator#524]
![capture-13](https://cloud.githubusercontent.com/assets/12936722/23666312/eef21752-035a-11e7-82a9-3e775292bfab.png)

**Comment by yllen** [comment]
Plugin is just migrfated from 084.2.1.5 to 2.4.0 and not yet activated

**Comment by btry** [comment]
Note : @flegastelois had the same issue upgrading from 2.4.0 to 2.4.1 in development

**Comment by btry** [comment]
Hi

Please check the tables glpi_plugin_formcreator_sections and glpi_plugin_formcreator_questions

If the row uuid of these tables onnly contains NULL then I think the following patch will help you

https://github.com/btry/formcreator/tree/feature/524_fix_upgrade_issue

Please note it is based on the hotfix/2.4.1 branch.
