### ISSUE TITLE
Display of the euro sign (€)

### ISSUE THREAD

**Issue by flo1994** [pluginsGLPI/formcreator#531]
After updating to the latest version, the euro character is no longer displayed correctly. The character is displayed correctly within the form:
https://abload.de/img/1szla8.jpg

Once the form has been sent and created, it is displayed as follows:
https://abload.de/img/2lpziz.jpg

Our forms contain a lot of rules for which the euro sign is used.

**Comment by btry** [comment]
Hi

Can you try this fix ? I'm expecting it will also work  for your problem.
https://github.com/btry/formcreator/commit/e7b72635e2c4c1e73d9eceb7347a1b60ffd1acf5

If this works, the fix will be available in the next release 2.4.1

**Comment by flo1994** [comment]
Thanks! That works for me :-)

**Comment by btry** [comment]
Thank you for your feedback. The fix is already merged in 2.4.1 then your issue will disappear in the nexwt release.
