### ISSUE TITLE
no image anymore in forms

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#542]
Hello

I don't know why, but I don't see image anymore in forms, I have checked rights on files folder everyone has the rights on it. images are saved in documents as png image 

![image](https://cloud.githubusercontent.com/assets/15144026/24107337/be00b75e-0d8a-11e7-810f-6cac299b12c5.png)

source code of the form header

<div class="contenu"><img style="float: left;" src="http://itsm/glpi/front/document.send.php?
docid=3703" width="150" height="200" />
<div class="contenu"><em>With Blackberry, mobile professionals get effortless access to their important information and communications while on the road and IT departments get centralized administration in a secure solution. Blackberry is a totally integrated package that includes hardware, software and service, providing a complete end-to-end solution.</em></div>
<div class="contenu"> </div>
<h3 class="contenu">Service Level Agreement :</h3>
<div class="contenu">
<p><strong>Availibility :</strong> 24x7x365 with the exception of scheduled maintenance</p>
<p><strong>Support Coverage : </strong>IT service desk opening hours</p>
</div>
</div>

**Comment by btry** [comment]
Hi

Check the path to your image in the HTML soruce code. Is it correct ? You may copy paste the path in a new tab to see if you get a HTTP error.

**Comment by satyan01** [comment]
If I open the image in another tab in chrome the image is displayed correctly

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/24108419/d1d2768e-0d8d-11e7-8ece-d3739c51d8e2.png)
![image](https://cloud.githubusercontent.com/assets/15144026/24108436/db194a06-0d8d-11e7-91ef-4297af8f3ebb.png)

**Comment by btry** [comment]
I'm not sure about the way you checked the resource.

Anyway I understand your image iin saved as a document in GLPI. 

Can you show the HTML code of the header of this form ?

I did a try and did not reproduces your issue. Note my test used ab absolute URI.

**Comment by satyan01** [comment]
the code is above

source code of the form header

<div class="contenu"><img style="float: left;" src="http://itsm/glpi/front/document.send.php?
docid=3703" width="150" height="200" />
<div class="contenu"><em>With Blackberry, mobile professionals get effortless access to their important information and communications while on the road and IT departments get centralized administration in a secure solution. Blackberry is a totally integrated package that includes hardware, software and service, providing a complete end-to-end solution.</em></div>
<div class="contenu"> </div>
<h3 class="contenu">Service Level Agreement :</h3>
<div class="contenu">
<p><strong>Availibility :</strong> 24x7x365 with the exception of scheduled maintenance</p>
<p><strong>Support Coverage : </strong>IT service desk opening hours</p>
</div>
</div>

**Comment by btry** [comment]
I used your HTML code to build a form header, and it works file for me. Is the user authenticated when he uses the form ?

**Comment by satyan01** [comment]
yes, and in super admin it is the same

**Comment by btry** [comment]
Hi

The only way to reproduce for me is to access the form anonymously (public access mode). In this cas this is normal.

By the way, if you want to prevent overflow of the picture on the blue section bar, append the following in your header HTML code

```
<p style="clear: both;"></p>
```

**Comment by satyan01** [comment]
Hello I found that in logs

2017-03-22 09:12:48 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc\item_ticket.class.php:563                      
  inc\commonglpi.class.php:206                       Item_Ticket->getTabNameForItem()
  inc\ticket.class.php:706                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:161                       Ticket->defineTabs()
  ajax\updatecurrenttab.php:50                       CommonGLPI->defineAllTabs()

**Comment by satyan01** [comment]
same result for me 
![image](https://cloud.githubusercontent.com/assets/15144026/24188190/b85fa196-0ee0-11e7-960b-7d255de566fc.png)

**Comment by btry** [comment]
Can you show the cotnent of the **preview** and **response** tabs ?

**Comment by satyan01** [comment]
please what is response tab ?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/24188436/aab13b80-0ee1-11e7-9344-9117a18ed529.png)

**Comment by btry** [comment]
The tabs are in t he dev tools, here is your screenshot where I highlighted them for you

![selection_002](https://cloud.githubusercontent.com/assets/14139801/24188964/890b17b0-0ee3-11e7-9018-3b4d29a5708e.png)

**Comment by satyan01** [comment]
this request has no preview available
this request has no rseponse available

**Comment by btry** [comment]
Show in the **headers** tab the section **response headers**

![selection_003](https://cloud.githubusercontent.com/assets/14139801/24189679/3e9295f2-0ee6-11e7-9dfc-592e2837907e.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/24189900/15d187e4-0ee7-11e7-8508-7a8b22d3c169.png)

**Comment by btry** [comment]
If I compare with the headers of my screenshot, I notice there is no header related to a file download. 

Are you really sure there is nothing in the **Response** tab ? The headers tells there is 257 bytes of content, and this is HTML code.

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/24191650/b45588de-0eec-11e7-8863-d8fc261fe75e.png)

**Comment by satyan01** [comment]
oh my god !!! solved by ctrl F5, after I tried on ie, it works, so I get chrome and works.

Sorry for the time that you passed on my issue.
