### ISSUE TITLE
service catalog simplified and extended for self service

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#547]
Hello, (glpi 9.1 - form creator 2.4.0)

I test this interface for user, when I want to book an asset and click on search after selecting a period I obtain the message : The action you have requested is not allowed.

in phplog I have just this error

2017-03-22 08:05:02 [@UNGSRVGVA218]
  *** PHP Notice(8): Undefined index: glpiactiveentities_string
  Backtrace :
  inc\db.function.php:1720                           
  inc\link.class.php:612                             getEntitiesRestrictRequest()
  inc\commondbtm.class.php:3258                      Link::getSearchOptionsToAddNew()
  inc\search.class.php:5426                          CommonDBTM::getSearchOptionsToAdd()
  inc\log.class.php:124                              Search::getOptions()
  inc\commondbtm.class.php:381                       Log::constructHistory()
  inc\commondbtm.class.php:1146                      CommonDBTM->updateInDB()
  inc\auth.class.php:765                             CommonDBTM->update()
  front\login.php:78                                 Auth->Login()

**Comment by btry** [comment]
Hi

I don't reproduce. However this feature reuses as much as possible the code from GLPI (because this is only an alternate display). It sould be interesting to see if the issue also occurs in GLPI.

Unfortunately the backtrace you show here is not related. The warning occured when someone authenticates in GLPI.

**Comment by satyan01** [comment]
Hello 

solved with 2.4.1
