### ISSUE TITLE
Notification Mail Ticket 

### ISSUE THREAD

**Issue by SebCvo** [pluginsGLPI/formcreator#550]
Bonjour,

Actuellement nous utilisons la version GLPI 9.1.2 et la version 2.4.0 de formcreator.

nous avons actuellement un problème concernant les notification automatique par mail concernant les acteurs du ticket généré par le formulaire.

Nous souhaitons l'activer par défaut, or lorsque le valideur  valide le formulaire, il y a création du ticket mais les notifications par mail des trois acteurs sont en "Non"

![image](https://cloud.githubusercontent.com/assets/26623913/24245391/f81d31da-0fc2-11e7-9518-b09390913b6c.png)

Comment faire pour les activer par défauts ?

En vous remerciant, cordialement Sébastien.

Vérification faites 
- au niveau de la destination /ticket cible
![image](https://cloud.githubusercontent.com/assets/26623913/24245450/35c44988-0fc3-11e7-805a-041f6164225b.png)
- au niveau de l'entité 
![image](https://cloud.githubusercontent.com/assets/26623913/24245503/64ed7d38-0fc3-11e7-93e4-a89a43880fec.png)

**Comment by btry** [comment]
Bonjour

La version 2.4.1 en cours de développement contient une grande quantité de corrections. Pouvez-vous l'essayer en environnement de test ? Il y a des chances pour que votre problème soit déjà résolu.

**Comment by btry** [comment]
Bonjour

Avez vous essayé les versions 2.4.1 ou 2.4.2 du plugin ?

**Comment by btry** [comment]
Bonjour

Je ferme ce ticket devenu obsolète. Si votre problème se reproduit avec la version 2.5.0 du plugin, merci de faire un nouveau ticket.
