### ISSUE TITLE
Form duplication empty

### ISSUE THREAD

**Issue by boscorelly** [pluginsGLPI/formcreator#551]
When i duplicate a form, it is empty.

All questions are deleted.

**Comment by btry** [comment]
Hi

Which version of the plugin ?

**Comment by boscorelly** [comment]
hi,

2.4.1 as i have tested the fix for conditon field (and that's not working)

**Comment by btry** [comment]
Hi,

Do you have accented characters or non latin characters in the value of your conditions ?

**Comment by btry** [comment]
Closing. If you got some information to reproduce then feel free to reopen.
