### ISSUE TITLE
Error message appearing on non debug-mode in english

### ISSUE THREAD

**Issue by CCoruble** [pluginsGLPI/formcreator#552]
Bonjour,
Je suis actuellement en train d'essayer tous les types de question possible et j'ai remarqué un bug mineur / anomalie.
Dans un formulaire si l'on ajoute une question de type "intitulé" de base le champ "Valeur par défaut" est vide, on ne peut pas le remplir. Si l'on choisis un intutilé, par exemple un lieu, le champ "Valeur par défaut" apparait bien et on peut le remplir. Néanmoins si l'on selectionne "rien", c'est à dire "---" ,dans le champ type d'intitulé (ici cela remplacera "Lieux") un message d'erreur en anglais s'affiche :
![2017-03-24 11_43_11-glpi - formulaires - 1](https://cloud.githubusercontent.com/assets/24699373/24291056/a820f4b2-1087-11e7-9cf2-8c04dd55a4f4.png)

Ce message s'affiche même si l'on est pas en mode debug et si notre langue choisis est autre que l'anglais.
_PS: Je sais que c'est un problème mineur, je ne fais que du feedback sur la verison actuel du plugin pour que la suivante soit niquel !_

**Comment by btry** [comment]
Bonjour

Pouvez vous préciser la version du plugin et de GLPI qeu vous utilisez ?

PS : ça reste une contribution, et bien que le bug soit (peut être ?) mineur; il faut le corriger :). Merci pour votre retour.

**Comment by CCoruble** [comment]
Bonjour,
merci pour la réponse rapide !
Je suis en dernière version de GLPI (9.1.2) et de votre plugin (2.4.0) !

**Comment by btry** [comment]
Bug résolu, la correction sera dans la version 2.4.1.
