### ISSUE TITLE
Import impossible de fichier .json après export de ce dernier

### ISSUE THREAD

**Issue by CCoruble** [pluginsGLPI/formcreator#554]
Bonjour,
après avoir créer un formulaire, j'ai exporter ce dernier de façon à l'importer plus tard.
Le fichier généré par l'import est un .json, j'utilise la fonction "Action" pour importer mes formulaires n'ayant pas trouvé d'autres moyens pour le faire (je suis peut-être aveugle :/ ...).
Le fichier se télécharge bien, mais lors de l'import de ce même fichier, 3 secondes après l'avoir téléchargé, il est inscrit que ce type de fichier n'est pas supporté.
![2017-03-24 16_03_37-glpi - formulaires](https://cloud.githubusercontent.com/assets/24699373/24300113/a812a4d8-10ab-11e7-8b9b-65d6ec522fff.png)

![2017-03-24 16_04_51-glpi - formulaires](https://cloud.githubusercontent.com/assets/24699373/24300115/aafbb9fa-10ab-11e7-8e65-b2122c312160.png)

J'ai ré-essayer plusieurs fois mais sans succès je suppose donc que ce soit être un bug.
_PS: Je m'excuse d'avance si cela n'était pas un bug mais moi qui ne faisait pas la bonne manipulation!_

**Comment by btry** [comment]
Bonjour

L'upload des fichiers .json n'est pas autorisé par défaut dans GLPI. Il faut ajouter ce type de fichiers.

![image](https://cloud.githubusercontent.com/assets/14139801/24300482/e5095098-10ac-11e7-82b4-4ea260fdf10e.png)

Dans la version 2.4.1, si nécessaire et si les droits le permettent, la fonction d'import proposera un bouton pour faire la configuration automatiquement.

**Comment by CCoruble** [comment]
Bonjour,
comme toujours merci pour la réponse rapide !
Pour être honnête j'avoue qu'il serait préférable d'avoir un bouton import/export.
C'est plus instinctif et si l'on à plein de fichier / formulaires cela rendrait la chose plus ergonomique, bien que je me doute que ce soit beaucoup de travail !

Cordialement

**Comment by btry** [comment]
Par tradition dans GLPI, quand on veut faire une action portant sur plusieurs objets d'une liste, il faut passer par le bouton **Actions**. Il est donc logique que le plugin adhère à ce principe, pour la cohérence générale de l'interface.

Le bouton **Actions ** ne permet que des actions sur des objets existant. L'import se fait donc dans la barre d'outils où se trouve le bouton de création de formulaire. 

Il y a deux choses : 

1 - GLPI donne un cadre assez strict sur la présentation, ce qui est plutôt une bonne chose pour la cohérence globale de l'interface utilisateur. En contrepartie, les plugins ont assez peu de libertés à ce niveau. Cela dit jetez un oeil au catalogue de service, qui montre qu'avec quelques efforts on peut faire des choses bien sympathiques.

2 - vous semblez découvrir le plugin (qui de plus, devient très riche) mais malheureusement la documentation n'est pas encore à jour sur tout ce qu'apporte la version 2.4 du plugin par rapport à la version précédente. Il y aura un travail sur la documentation, mais il faut finir de corriger les bugs de la version 2.4.0 d'abord.

**Comment by btry** [comment]
Le problème étant résolu, je clos.
