### ISSUE TITLE
[Curiosity] What is this image?

### ISSUE THREAD

**Issue by magaiverpr** [pluginsGLPI/formcreator#555]
I see this image in the description of this plugin.

This is a MOD for GLPI? Never see anything like this.

![screenshot_2](https://cloud.githubusercontent.com/assets/10533823/24304414/0055251c-1098-11e7-8541-cd98fce0439b.png)

**Comment by btry** [comment]
Hi

This is a feature introduced in FormCreator 2.4.0 : the service catalog. It replaces the simplified interface. The service catalog may be enabled or disabled per entity with inheritance between entities.

It allows the user to search in a single engine both forms and FAQ entries of  the KB. If you fill the KB you may avoid a few tickets if a solution does not requires the intervention of a technician and the user finds it.

Note that this interface does *not* requires patching GLPI. It is 100% implemented in FormCreator and the plugin still installs and uninstalls like any regular plugin.

If you want to test it, use a testing environment and check out directly the branch hotfix/2.4.1. It already contains a lot of bugfixed and I think it will be ready in a few weeks.

**Comment by magaiverpr** [comment]
Seriously, this view is so awesome and user-friendly that can be a stand-alone plugin and I anyone can use this.

If I can open tickets in this screen it will be realy cool. 

Please think this.

**Comment by btry** [comment]
To create a ticket from the service catalog, just choose a form and fill it. As long as the form is designed to generate a ticket, the ticket will appear in **My requests for assistance**.

**Comment by zeriqueh** [comment]
Up - accompanying

**Comment by btry** [comment]
Hi

It seems there are no new questions, then I close.
