### ISSUE TITLE
Affichage de champs

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#556]
Bonjour,

Il est actuellement possible de conditionner l'affichage de certains champs à une réponse précédente, mais il ne me semble pas possible d'effectuer des tests sur plusieurs question ex: j'affiche la question 3 si oui à la question 1 et non à la question 2.
Est-ce qu'il est possible de réaliser cette fonction, ou est-il prévu que ce soit implémenté?

Merci beaucoup

**Comment by btry** [comment]
Bonjour

C'est implémenté dans la version 2.5.0 (branche develop). Vous pouvez l'essayer en environnement de test, mais ne l'utilisez pas en production pour le moment.
