### ISSUE TITLE
[Question / amélioration] Formulaire à plusieurs

### ISSUE THREAD

**Issue by CCoruble** [pluginsGLPI/formcreator#558]
Bonjour,
malgré mes recherches je ne trouve pas de moyen pour un formulaire d'être envoyer à quelqu'un lorsque qu'une partie est remplie (j'en déduis que ce n'est pas possible). 

Planifiez vous dans le futur que des formulaires puissent être remplies par deux personnes ? 
Exemple (bidon): 
Une personne rencontre un problème sur sa machine à laver.
Il remplie son nom / prénom / adresse.
Le formulaire est envoyer à une personne du SAV qui remplit le reste du formulaire ( N* de série de la machine et la date d'acquisition)  grâce aux info qui sont déjà présente dans le formulaire.
Le formulaire ainsi compléter avec les info du client et de la personne du SAV est envoyer, cela créera un ticket et les personnes du service technique recevront un mail.

En plus court ;
Inviter une personne à terminer un formulaire dans lequel se trouve des informations que l'on a nous même renseigné.

**Comment by btry** [comment]
Bonjour

C'est une fonctionnalité qui a été demandée dans un autre ticket (queje dois retrouver). Ce n'est pas planifié pour le moment.

**Comment by btry** [comment]
Duplicates #372 and #444

**Comment by JulienG78** [comment]
Hello, j'ai poussé cette demande mais qui n'a pas été retenue, le développeur m'a répondu que le plugin n'a pas été développé pour cet usage.
