### ISSUE TITLE
I can not view / download documents in glpi form plugin.

### ISSUE THREAD

**Issue by virginiacorrea** [pluginsGLPI/formcreator#561]
Hello
A form validator or approver can not download the attached document on the form.

The validator / approver uses helpdesk interface.

![image](https://cloud.githubusercontent.com/assets/16838689/24369611/30c374a2-12ea-11e7-9d1d-b095a0727cb7.png)

If someone can give me an orientation or definitely know that this works this way.

**Comment by virginiacorrea** [comment]
To clarify the documents as validator I see them (I see their names) but the link is not enabled for download / visualization of the document

**Comment by btry** [comment]
Hi

Can you tell the version of GLPI and the version of the plugin, please ?

**Comment by virginiacorrea** [comment]
Hi.
GLPI v 0.90.1
Plugin Form v. 0.90-1.3.4

Thanks!

**Comment by btry** [comment]
Hi

You are 2 releases late (2.4.1 out today). Can you test the version 2.4.1 on a testing environment and feedback ?

**Comment by virginiacorrea** [comment]
Hi
Tested in the same version 090.1 with 2.4.1 and the drawback continues

![image](https://cloud.githubusercontent.com/assets/16838689/24633573/e1eda2b2-188e-11e7-8583-629629d70516.png)

**Comment by virginiacorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/16838689/24633653/3577e636-188f-11e7-8051-a1f90543d3e7.png)

**Comment by virginiacorrea** [comment]
I think the drawback is with the version of glpi 090.1 since with version 9.1.1 and 2.4.1 it works correctly.

I think that even though I have to wait to make the change, this would be the solution to my problem

Thank you.

**Comment by btry** [comment]
Hi

About your first screenshot, this is a known problem. Your browser maintains in its cache the CSS of your old version of the plugin. Just hit CTRL+R to refresh the page, and it will dispàlay correctly. See README.md.

I agree with your last comment: I could not reproduce with GLPI 9.1 or GLPI 0.90.5. 

Can you build a GLPI 0.90.5 testing environment with your data, and see if the problem still occurs ? Upgrading to this version is maybe an option as it contains only bugfixes comapred to 0.90.1.

**Comment by virginiacorrea** [comment]
Thank you very much
I think I'll wait and do both updates for an effort that involves me.

Thank you so much for your help.

Good day.
