### ISSUE TITLE
FC 2-4-1: les conditions ne s'affichent pas si la réponse contient des accents

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/formcreator#565]
Bonjour,

Suite au test de FormCreator 2-4-1, les questions conditionnées ne s'affichent pas si la condition contient des caractères accentués.

J'ai par exemple la question:

> Avez-vous des commandes à passer pour que le titulaire soit opérationnel ? *
>  
>  Téléphone portable
>  Matériel, logiciel, équipement informatique
>  Mobilier, matériel, équipement de bureau
>  Véhicule de services
>   Autres

En fonction des réponses cochées, des questions supplémentaires apparaissent.
Sauf que je constate que pour que cela fonctionne en 2-4-1, il faut que j'enlève les accents dans les réponses et conditions.

Or jusqu'à maintenant les accents ne posaient pas de problème, en apparence, du moins, puisque l'affichage fonctionnait après application du patch donné dans le post #442.

Est-ce possible de faire quelque chose pour que les conditions liées à des choix de réponses avec accents soient de nouveau tolérés?

S'il est plus simple d'enlever les accents, il sera difficile d'avoir un rendu impeccable pour un formulaire en français et à destination d'un grand nombre d'utilisateurs.

En vous remerciant

**Comment by btry** [comment]
Bonjour

Pouvez-vous essayer le correctif en #566 ?

**Comment by matth974** [comment]
Pardon de mon retour, qui peut paraître un peu bête, mais:

le correctif #566 fait apparaitre des modifications sur le fichier plugins/formcreator/inc/fields.class.php aux lignes 238 et 243, mais le fichier présent sur notre serveur, ne comporte que 226 lignes.

Ai-je loupé quelque chose ?

**Comment by btry** [comment]
Bonjour,

Utilisez-vous la version releasée ce lundi ? Et comment appliquez-vous le patch ?

Pour les besoins des tests j'ai déplace du code d'un autre ficher vers inc/fields.class.php. cela représente plus que deux lignes et un seul "bloc" de code. C'est d'ailleurs ce code déplacé qui a subi un changement. Voyez l'onglet changes de la PR pour avoir un aperçu.

**Comment by matth974** [comment]
ok, je viens de comprendre , je m'étais basé sur l'onglet commits au lieu de l'onglet files changed.
je teste ça et je reviens vers vous.

**Comment by matth974** [comment]
Patch appliqué. Ok pour moi.
Merci.

Note pour mémoire: les numéros de lignes sur l'affichage github ne correspondent pas toujours aux numéros de lignes figurant dans N++. Pour appliquer le correctif, j'ai faire une recherche sur le texte et non par rapport aux numéros de lignes

**Comment by btry** [comment]
Je pense que vous n'êtes pas sur la version releasée, mais quelques révisions en retard, ce qui expliquerait la différence de numérotation. Git sait gérer cela, vous devriez essayer sur une copie de travail si je vous soumet un autre patch à l'avenir. Ca réduit aussi les risques d'erreur humaine lors de l'application d'un diff.
