### ISSUE TITLE
Add multiple features

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/formcreator#568]
Hi,

GOAL : 
- Add several levels of validations
- Add a rights profiles to the plugin
- Possibility of changing the validator. (Example: the validator is vacant, it must be possible to reassign the validation to another validator)
- Add the export of the form in pdf
- Add an automatic action with sending notification for forms awaiting validation
- When a ticket is created from a form, add form validations to ticket validation as accepted.

The client requested several features for the plugin.
Are you agree with this feature?

**Comment by amma35** [comment]
No reviews for features?

**Comment by btry** [comment]
Hi

Sorry for the delay.

First, all new features must be based on the crurent developpement branch (future 2.5 version). Create one branch per feature, each having its unit tests. Each branch name should be prefixed with "feature/" (see git flow model).

About features related to validation or profile, I need more details. Maybe one ticket per feature with one or several use case(s) would help me to fully understand the needs and discuss how to implement it when necessary. If you already know how you plan to implement the features, please describe it. 

The database model of the validation feature is not perfect un my opinion. I expect you will need to improve it, and maybe create new itemtypes or relations. If I'm right, then you must handle the migration process from older versions of the plugin.

Simpler features like pdf export are ok. Be aware that the version 2.5 allows to print a form.

About the automatic action, we probably need the ability to enable or disable it.

**Comment by amma35** [comment]
Hi, 

Ok, thanks for the return.
At the customer's agreement, I will do a issue/PR by functionality.

Thank you.

**Comment by amma35** [comment]
I'm closing for the moment, we haven't heard from the client.
