### ISSUE TITLE
Affichage des questions sur plusieurs lignes

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/formcreator#569]
Bonjour,

Je remarque depuis la 2-4-0, une petite régression au niveau de l'affichage des questions sur les formulaires.

Les questions lorsqu'elles dépassent un certain nombre de caractères sont affichées sur plusieurs lignes, mais la découpe donne un étrange rendu (d'autant plus qu'il y a encore de la place sur la ligne):

Quelques exemples (en 2-4-1):

![image](https://cloud.githubusercontent.com/assets/10028344/24694707/05d67f76-19f4-11e7-8d60-1245a9b36c03.png)

![image](https://cloud.githubusercontent.com/assets/10028344/24694769/3ffe683a-19f4-11e7-985a-9d724958c9b1.png)

La différence en version 0.90-1.3.3:

![image](https://cloud.githubusercontent.com/assets/10028344/24694933/dab19352-19f4-11e7-99a7-28c5f034049c.png)

![image](https://cloud.githubusercontent.com/assets/10028344/24694987/198a2ed6-19f5-11e7-9b9c-f006864911c5.png)

Visuellement, on a un meilleur rendu sous la 0.90-1.3.3.

Serait-il possible d'améliorer le rendu visuel que l'on a en 2-4-0 et 2-4-1 ?

Cordialement.

**Comment by btry** [comment]
Bonjour

Il semble que le bug a été résolu : j'ai  testé la version 2.4.2 et la  version 2.5.0 sans reproduire

2.4.2
![image](https://cloud.githubusercontent.com/assets/14139801/25858791/eb693b48-34dc-11e7-9b0c-936b88a7a054.png)

2.5.0 
![image](https://cloud.githubusercontent.com/assets/14139801/25858834/0c25b492-34dd-11e7-8449-ef6f07db2d27.png)

**Comment by matth974** [comment]
Effectivement en 2.4.2, c'est ok.
Merci bien.
