### ISSUE TITLE
issue to affect form category in ticket

### ISSUE THREAD

**Issue by gregfly26** [pluginsGLPI/formcreator#570]
Hello,

I have an issue to affect the form selected category in the ticket (like in issue 363).

I added on the form a field link to GLPI categories.
When I filled the form, I selected a category but this category was not in the ticket.

Could you help me please ?

I use the last release 2.4.1 and GLPI 9.1.2 (I never use a previous plugin version)
I have no error message.

Thanks in advance for your help.

**Comment by btry** [comment]
Hi

With FormCreator 2.4.1, when you use ticket categories as a field in the form, the category will appear in the description of the ticket only. The plugin does not affects the actual category of the generated ticket.

This feature is implemented in FormCreator 2.5.0 which is still in development. A target ticket allows the form designer to choose a category, or use a question to let the requester pick a category for his request.

**Comment by gregfly26** [comment]
Ok !
Do you have a plan date for 2.5.0 release ?

**Comment by btry** [comment]
There is no date planned yet for this version.

**Comment by btry** [comment]
Hi

Version 2.5.x is there so the feature you asked for is available. I close.
