### ISSUE TITLE
Assignation d'un ticket : technicien

### ISSUE THREAD

**Issue by Darkitty** [pluginsGLPI/formcreator#574]
Bonjour,

Lors de la validation d'un formulaire, le ticket généré n'est pas attribué au technicien défini dans le formulaire. Quand on regarde l'historique de ce ticket, on obtient ceci :

```
928904	07-04-2017 15:26	xxxxxx (yyy)	Utilisateur	Supprimer un lien avec un élément : xxxxxx (yyy)
928903	07-04-2017 15:26	xxxxxx (yyy)	Statut		Changement de En cours (Attribué) à Nouveau
928902	07-04-2017 15:26	xxxxxx (yyy)	Utilisateur	Ajout d'un lien avec un élément : xxxxxx (yyy)
```

J'ai essayé en supprimant le technicien du formulaire et en en remettant un autre, mais le soucis reste le même. Ce qui semble étrange, c'est la suppression du lien alors que celui-ci est bien créé juste avant avec le bon technicien.

La version de GLPI est 9.1.1 et la version du plugin formcreator la dernière en date (2.4.1). L'ensemble tourne sur une Debian 8 avec Apache et php5.

Merci d'avance et merci pour ce plugin qui nous ai bien pratique 👍

**Comment by btry** [comment]
Bonjour

Comme il n'y a rien dans FormCreator qui supprime explicitement des acteurs, la suppression a peut être lieu ailleurs. Avez vous des règles métiers pour les tickets ou d'autrers plugins ?

**Comment by Darkitty** [comment]
Il y aucune règle métier d'utiliser et voici l'ensemble des autres plugins utilisés actuellement :

```
Alertes			1.3.2.4
Champs supplémentaires	1.4.3
Comportements		1.2
Compteurs Imprimantes	1.3.0
Custom			0.90-1.0.1
Escalades		2.1.0
Gestion de baies	1.7.0
Gestion de cartes SIM	1.4.2
Liste des tâches	1.1.0
OCS Inventory NG	1.3.2
Plus de rapports	1.3.1
Réservation		1.3.5
Salles			3.0.4b2
Tableau de bord		0.7.9
VIP			1.0.1
```

**Comment by btry** [comment]
Désactivez Escalade et Comportements, et voyez si le problème persiste. 

Ces deux plugins sont de bons candidats à une interférence. 

Si le problème disparait, essayez de nouveau un seul de ces plugins désactivé, chacun son tour.

**Comment by Darkitty** [comment]
En effet, le soucis vient du plugin Escalade. Merci. Je vais voir si il y a une mise à jour ou le désactiver complètement si celui-ci pose encore soucis si c'est possible.
Merci 👍

**Comment by btry** [comment]
Je marque je ticket comme bug: il va peut être falloir que les deux plugins communiquent entre eux pour résoudre le souci.

**Comment by Darkitty** [comment]
D'accord. Est-ce que j'ouvre également une issue sur leur dépôt ?

**Comment by btry** [comment]
oui, cela vous permettra d'être tenu au courant si seul Escalade a besoin d'une mise à jour.

**Comment by btry** [comment]
Le bug doit être résolu. Je ferme.
