### ISSUE TITLE
Création de ticket dans la mauvaise entité

### ISSUE THREAD

**Issue by Kahji** [pluginsGLPI/formcreator#582]
Bonjour,

Depuis la dernière version, lorsque je créé un ticket via formulaire, tout les tickets sont créés dans Root Entity.
J'ai pourtant essayé avec les champs "**Entité Active**" ou "**Entité par défaut du demandeur**", mais aucun des deux ne fonctionnent. De ce fait je suis obligé de passer sur "Entité Spécifique" et de dupliquer mes formulaires... ce qui n'est pas très pratique.

Avez-vous déjà recensé ce problème ? Je n'ai rien trouvé à ce sujet pour l'instant.
Merci par avance pour les retours et bon courage à tous !

Version GLPI : 9.1.1
Version FormCreator : 2.4.1

**Comment by btry** [comment]
Bonjour,

Je n'ai pas eu de remontée d'un tel problème. Puisque vous avez vu le problème après un upgrade, pouvez vous dire quelle était la version précédente du plugin ?

J'ai aussi besoin de connaître la version de GLPI.

**Comment by Kahji** [comment]
Il me semble que la version d'avant été la **0.90-1.3.4**. (Ou 2.4.0 mais j'ai un gros doute la dessus)
Version de GLPI 9.1.1.

Dans la version d'avant je n'avais pas configuré ce champ (je ne suis pas sur qu'il était disponible d'ailleurs) et les tickets étaient dans l'entité active du demandeur. Si cela peut aider.

**Comment by btry** [comment]
J'ai besoin d'être sûr. La 1.3.4 est assez ancienne alors que la 2.4.0 est sortie en début de cette année (février de mémoire). Avez vous déjà upgradé le plugin ces derniers mois ? Si oui je pense que vous étiez en 2.4.0. Comparez avec les dates de release affichées sur github. Je pense qua ça vous aidera.

**Comment by Kahji** [comment]
Il s'agit bien de la **0.90-1.3.4** après vérification. Je n'avais pas fait la mise à jour vers la 2.4.0 par manque de temps en début d'année.

**Comment by btry** [comment]
Bonjour

Je tente de reproduire le bug, sans succès. 

J'ai testé le plugin en 2.4.2 et en 2.5.0 (en développement) avec un formulaire créé dans l'entité  racine. Je me positionne dans une sous entité pour remplir le formulaire et générer des tickets. Les tickets sont bien  générés dans l'entité attendue. Je pr écise que le ticket cible est configuré en **entité active**.

Avez vous quelque chose hors du plugin susceptible d'impacter l'entité du ticket généré ?

**Comment by Kahji** [comment]
Bonjour,

J'ai essayé en désactivant tout les plugins actif et pas de changement. J'ai contourné le problème en modifiant mes formulaires et en les attribuants manuellement. Je pense que je vais attendre la prochaine mise à jour de FormCreator et en profiter pour mettre à jour GLPI vers la 9.1.2 à la même période. 
Il y a une date prévue pour la sortie de la 2.5 ? 

Merci pour les retours :+1:

**Comment by btry** [comment]
Nous comptons sortir la version 2.5.0 dans quelques semaines. J'espère fin mai / début juin.

Comme vous avez contourné en modifiant vos formulaires, créez un nouveau formulaire dédié à al recherche du bug. Mettez-y une section et une question, et ajoutez un ticket destination avec les  réglages permettant de reproduire le bug.

Vérifiez que le bug se produit toujours, puis ouvrez la table **glpi_plugin_formcreator_targettickets** dans la base de données.

Trouvez la ligne correspondant à votre ticket destination, en vous basant sur la colonne **name**. Quelles valeurs se trouvent dans les colonnes **destination_entity** et **destination_entity_value** ?

**Comment by btry** [comment]
Bonjour 

A défaut de retour, je ferme le  ticket. Si le problème réapparait avec une version 2.4.2 ou 2.5.0, ouvrez un nouveau ticket.
