### ISSUE TITLE
DropDown loading fail

### ISSUE THREAD

**Issue by LeFournG** [pluginsGLPI/formcreator#587]
![formcreatorbug2](https://cloud.githubusercontent.com/assets/25687914/25423499/37b99308-2a65-11e7-984b-fa38e11ef64b.png)

![formcreatorbug](https://cloud.githubusercontent.com/assets/25687914/25423500/37bb2a1a-2a65-11e7-9db3-e3816234785b.png)

When i am logged in glpi i have access to the list, but when i'm not logged i have the error message "loading failed."
I really need the list for non logged people

**Comment by btry** [comment]
Hi

If you're not logged in you don't have any profile. Without a profile, GLPI cannot grant read access to dropdown content.

Giving read access to dropdowns might be a solution, but I must consider first how this affects security.

**Comment by LeFournG** [comment]
I think that's the best idea. 
For security problem our users can only access to the form after being logged into our intranet so i think grant read access to dropdowns ins't that risky

**Comment by btry** [comment]
Yes, but this is specific to your context. I must consider other possible contexts, especially a GLPI available from anywhere.

**Comment by LeFournG** [comment]
The strange thing is that the dropdown was available for non logged people before , i just upgrade to glpi 9.1.1 and download the last version of formcreator and now it doesn't work.
That mean the guy who put formcreator in the first place knew how to grant access but he didn't let guide or something so

**Comment by btry** [comment]
Could you try to stick to the previous version of GLPI you used and upgrade only the plugin ?

The reverse case (upgrading GLPI and keep the previous version of the plugin) may be useful too to find the problem.

Also please tell the previous versions of GLPI and FormCreator (I guess you upgraded to 2.4.2).

**Comment by LeFournG** [comment]
I'm on 9.1.1 glpi and 2.4.1 formcreator
And i had the same issue when glpi was in 9.1. 
I think i just miss a single configuration like : give access to dropdown to everyone somewhere i don't know i'll try to find the guy guide if he did one

**Comment by btry** [comment]
If you upgraded from 9.1 to 9.1.1 your upgrade covers only bugfixes in GLPI. Then this is maybe a regression in  the plugin. 

Can you test GLPI 9.1 and your previous version of FormCreator (which version by the way ?), upgrade to 2.4.1 and test again ?

**Comment by LeFournG** [comment]
I don't even know the last version of form, i just arrived upgrade glpi, upgrade all the plugins and install some new. 
Everything work except this Dropdown problem, i think i just removed form and install it from nothing so i lost configuration from the previous one that's why

**Comment by btry** [comment]
I noticed this contribution in GLPI which may help to solve this issue:
https://github.com/glpi-project/glpi/pull/2269/commits/7f86dad7d57b9c5d2db7b3a2890d62ab467658f9

**Comment by SoporteBH** [comment]
Hi, the same thing happens to me as @LeFournG.

It shows me that the load only failed from public access, which is what I need.
I ask for help please !!!! Since I consider it really necessary because I call the form from another system and it is not practical to enter another user.

(Before writing, I tried different versions of GLPI and the plugin even with a new installation but I did not succeed).

**Comment by btry** [comment]
Hi

There is a constraint from GLPI. Reading data from databases to populate dropdowns requires computation on entities and user profiles. I need to find a solution which does not expose data in dropdowns in a insecure way when no user is logged in.

**Comment by andreasmalta** [comment]
> I noticed this contribution in GLPI which may help to solve this issue:
> [glpi-project/glpi@7f86dad](https://github.com/glpi-project/glpi/commit/7f86dad7d57b9c5d2db7b3a2890d62ab467658f9)

any idea how to use the above link to make dropdowns available to public users?

**Comment by btry** [comment]
Hi

Drodpowns and other question types are disabled for anonymouse forms. There is no good solution to disclose contents of such questions without introducing a security problem.

I close this issue.
