### ISSUE TITLE
Comment remplir les intitulés du ticket ? 

### ISSUE THREAD

**Issue by LeFournG** [pluginsGLPI/formcreator#588]
Lorsque je rempli le formulaire en y renseignant, via les intitulés, certains informations, elle ne sont ensuite pas reporté sur le ticket.

![bug](https://cloud.githubusercontent.com/assets/25687914/25435115/4cb19a60-2a8f-11e7-967e-e06a8f81636e.png)

Ayant pourtant dans le formulaire renseigner via intitulé le lieux et la catégorie, le colonnes reste vide et rien n'est renseigné dans le ticket.
Les colonnes lieu et catégorie

**Comment by btry** [comment]
Bonjour

Je pense que votre problème n'est qu'un problème d'utilisation. La priorité est calculée à partir de l'urgence et l'impact du ticket.

Essayez ce qui suit : 

Modifiez l'urgence de votre ticket destination. Notez que vous pouvez utiliser une question de type **Urgence** pour proposer le choix au demandeur.

![image](https://cloud.githubusercontent.com/assets/14139801/25435618/dc060826-2a90-11e7-9d46-5db6a532c8da.png)

L'urgence affectera le calcul de la priorité selon la matrice définie dans la configuration générale de GLPI

![image](https://cloud.githubusercontent.com/assets/14139801/25435702/38769a30-2a91-11e7-86bf-bd6a12c7d23a.png)

**Comment by LeFournG** [comment]
Je ne voit pas le rapport avec mon problème.
Mon formulaire demande des informations sur le lieu et le problème 

![bug2](https://cloud.githubusercontent.com/assets/25687914/25435924/009e4aee-2a92-11e7-80e9-6d2b8ed7b9d7.png)

Malgré le fait qu'ils soit remplis le ticket ne les prends pas en compte : 

![bug](https://cloud.githubusercontent.com/assets/25687914/25435941/1388056e-2a92-11e7-83d8-c37de9cbe8f3.png)
![bug3](https://cloud.githubusercontent.com/assets/25687914/25435975/2881ee1c-2a92-11e7-863f-0feeee69123f.png)

J'aimerais juste savoir comment je peut lié la réponse aux question du formulaire aux zones lié dans la création du ticket

**Comment by btry** [comment]
Au  temps pour moi, j'ai focalisé sur le jaune de la priorité, et la couleur étant apparement personnélisée j'ai pensé à une mise en valeur pour montrer le problème.

Pour que la catégorie soit reportée dans le ticket il faut (là aussi) personnaliser le  ticket destination.
Dans la capture ci dessous j'ai créé uen question nommée **cat** représentant l'intitulé **catégories de ticket**.
![image](https://cloud.githubusercontent.com/assets/14139801/25436270/1ba323cc-2a93-11e7-8515-a3390435b696.png)

Je pense que vous n'avez pas fait ce réglage. Cette fonction est disponible dans la version 2.4 du plugin.

**Comment by LeFournG** [comment]
Pour la destination ticket je n'ai que cette interface

![Uploading bug4.png…]()

**Comment by btry** [comment]
Vous avez quelle version du plugin ?

**Comment by LeFournG** [comment]
2.4.1

**Comment by btry** [comment]
Décidément... La fonctionnalité est dans la version 2.5, pas 2.4. Cette version est en cours de développement; donc il vous faudra patienter.  La date de livraison n'est ps encore fixée, mais nous cherchons à adopter un rythme de releases plus soutenu.

**Comment by LeFournG** [comment]
Une idée du temps avant le release ? 1semaine ? 1 mois ?

**Comment by btry** [comment]
Je pense autour de 1 mois. Si je dois ajouter des fonctionnalités pour la version 2.5, ça peut être plus long.

**Comment by btry** [comment]
Bonjour

Je ferme le ticket étant donné que votre besoin sera couvert avec la release 2.5.0.
