### ISSUE TITLE
Liste objet GLPI plus spécifique

### ISSUE THREAD

**Issue by Kahji** [pluginsGLPI/formcreator#591]
Bonjour,

Je suis en train de réorganiser mes formulaires pour m'adapter au mieux aux besoins de l'entreprise.
J'ai donc une entité spécifique à l'une de nos entreprises et dans Parc>Ordinateur on y retrouve les postes internes ainsi que les serveurs.
Je souhaiterais utiliser, dans certain formulaire, l'Objet GLPI >> Ordinateur, puis spécifier un type et/ou un statut afin d'être plus précis dans la demande. (Et surtout, pour ne pas voir les ordinateurs du parc et laisser apparaître uniquement les serveurs)

Je ne trouve pas la possibilité. J'imagine que c'est logique, vu que d'après GLPI il faudrait une entité pour les postes internes et une autre pour les serveurs, mais dans mon cas c'est difficilement faisable...

Est-ce faisable ? Cette fonctionnalité a-t-elle déjà était demandé ?

Merci par avance pour le retour.

**Comment by btry** [comment]
Bonjour

Si je comprends bien vous voulez que la liste des ordinateurs puisse se restreindre par leur statut ou leur type à partir d'un second ou troisième champ de formulaire.

La fonction n'existe pas dans FormCreator; à ma connaissance vous êtes le premier à demander cela.

Créer des dépendances fonctionnelles entre champs d'un formulaire me parait être une fonctionnalité assez lourde à implémenter.

Il me semble plus simple de configurer ce filtrage à la conception du formulaire. Cela a aussi l'avantage de ne pas alourdir la saisie par le demandeur.

**Comment by Kahji** [comment]
Bonjour,

En gros, rajouter un champ "Type : _xyz_" en dessous de "Afficher une valeur vide : ".
_xyz_ serait la liste des Type d'ordinateurs qu'on a créé dans GLPI.

Je ne sais pas du tout à quel point cela peut être compliqué à rajouter, mais je pense que cela peut être utile à d'autres personnes afin de simplifier certains formulaires.

Bonne journée.

**Comment by btry** [comment]
Bonjour

Vous pouvez soit attendre que la fonctionnalité soit développée de manière communautaire, soit demander son développement en contactant Teclib : contact@teclib.com

**Comment by etiquet** [comment]
Bonjour, nous avions envisagé cette fonctionnalité pour un fonctionnement similaire (différentiation application d'entreprise vs logiciel sur le poste de travail). Mais cela revient à ajouter des conditions d'affichage d'un champs dans le formulaire et donc surtout devoir personnaliser la partie paramétrage du formulaire. Pour rester générique nous avons abandonné cette piste. 
Si vous avez un peu de compétence en base de données, vous pourriez vous appuyer sur le PR que nous avons soumis dans lequel vous pouvez gérer un autre objet GLPI + effecter une copie select / join de la table glpi_computers vers l'objet GLPI cible (avec un cron ou une tâche dans le séquenceur). Le PR permet beaucoup plus mais cela répondra à votre besoin.

**Comment by nqb** [comment]
La fonctionnalité demandée nous intéresse également afin de présenter aux utilisateurs uniquement le matériel en production. Il y a peu d'intérêt à présenter le matériel en stock ou au rebut.

De quelle façon peut-on contourner le problème en attendant le développement de la fonctionnalité ?

**Comment by btry** [comment]
Bonjour

Peut être que vous pouvez contourner en travaillant sur la répartition dans des entités des utilisateurs et matériels.

**Comment by dgsn** [comment]
Bonjour,
suggestion...
Et si on pouvait référencer une recherche sauvegardée liée à l'objet GLPI sélectionné ?
On pourrait à ce moment créer des recherches sauvegardées spécifiques pour une utilisation FormCreator ou utiliser des recherches existantes. 
Vraisemblablement il faudra limiter le choix des recherches sauvegardées à celles qui dépendent directement de l'objet et qui sont public.
Bien cordialement.

**Comment by btry** [comment]
In progress: https://github.com/pluginsGLPI/formcreator/pull/2978

big up to the sponsor

**Comment by btry** [comment]
Hi

The feature will be available in Formcreator 2.14.0
