### ISSUE TITLE
Génération ticket dans entité spécifique: non prise en compte des règles métiers et pas de notification pour groupe de techniciens

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/formcreator#595]
Bonjour,

Nous constatons que  lorsqu'un formulaire est saisi sur une entité A mais que nous forçons la génération du ticket dans une entité B, les règles métiers utilisées pour la catégorisation de ces tickets ne sont pas prise en compte.

La génération du ticket néanmoins s'effectue bien dans l'entité B.

Nous constatons par ailleurs, toujours dans le cas d'un ticket généré dans l'entité B à partir d'un formulaire accessible sur une entité A, que si nous définissons le(s) groupe(s) de technicien(s) dans l'onglet "destination" du formulaire,  ce(s) dernier(s) ne n'est (sont) pas notifiés , bien que le ticket lui (leur) soient correctement affectés et les alertes mails correctement activées. 

Reproduisez-vous ces problèmes?

En vous remerciant.

Cordialement,
 
----------------
Version FormCreator utilisée: 2-4-2

**Comment by btry** [comment]
Bonjour

- Quelle est la version de GLPI utilisée ? 
- Est-ce une régression par rapport à une version précédente du plugin (si oui, laquelle) ?

**Comment by matth974** [comment]
Bonjour,

Je ne sais pas si l'on peut parler de régression car nous utilisons ce mécanisme de genération de tickets dans une autre entité depuis l'arrivée de la version 2-4-2.
Pour ce qui est de la version de GLPI, nous fonctionnons avec la 0.90.1 en production.
J'aurais souhaité vérifié le fonctionnement en 9-1-2 avant de répondre, mais notre environnement de tests m'est pour l'heure inaccessible.

**Comment by btry** [comment]
Avec GLPI < 9.1.2 le plugin crée le ticket avec le demandeur puis ajoute les autres acteurs. Je pense que ça peut impacter ces règles métier en les empêchant d'accéder à certaines informations du ticket.

GLPI 9.1.2 a levé une limitation interne pour que FormCreator puisse ajouter tous les acteurs dès la création du ticket. Ce changement pourrait résoudre à la fois résoudre le souci de règle et le souci de notification.

Il me semble intéressant de tester avec GLPI 9.1.2. Je vais patienter jusqu'à ce que vous puissiez faire un essai.

**Comment by matth974** [comment]
Bonjour,

J'ai pu tester ce jour la situation décrite sous GLPI 9-1-2 en démo.
Il semble que cela fonctionne bien.

Les règles métiers sont bien prises en compte, et je vois bien les notifications associées en file d'attente.

Il m'est impossible de confirmer si l'on reçoit bien les mails car ils restent en file d'attente, mais je suppose que cela ne vient pas de formcreator, mais d'une erreur de paramétrage dans la configuration des mails en démo.

Cordialement.

**Comment by btry** [comment]
Bonjour

Merci pour ce retour.

Si tous les emails attendus arrivent en file d'attente c'est bon.  Si ils y restent c'est très probablement parce que vous n'avez pas configuré de tâche cron pour les actions automatiques.

Voyez ce sujet sur le forum, vous êtes probablement dans la même situation: http://forum.glpi-project.org/viewtopic.php?id=157647

**Comment by btry** [comment]
Bonjour

Avez vous des retours à fournir sur ce ticket ? Si vous n'en avez pas, je ferme. Si le bug persiste avec la dernière versoin il faudra refaire un nouveau ticket. pour se center sur le code de la dernière version .

**Comment by matth974** [comment]
Bonjour,

Désolé pour la réponse tardive. Nous n'avons pas de nouveaux retours à formuler,merci beaucoup.
