### ISSUE TITLE
Impossible to upgrade

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#600]
glpi9.1.2 formcreator 2.4.0

PHP Warning: fopen(C:\inetpub\wwwroot\glpi\plugins\formcreator\install/mysql/plugin_formcreator_empty.sql): failed to open stream: No such file or directory in C:\inetpub\wwwroot\glpi\inc\dbmysql.class.php at line 477

**Comment by btry** [comment]
Hi

This file is introduced in version 2.5.0. How can you have this error with 2.4.0 ?

**Comment by satyan01** [comment]
I have solved the issue, when a form answer contains \ the installation is stopped with error

**Comment by btry** [comment]
I advice you to upgrade to version 2.4.2 : there were some fixes for this kind of issues.

Also, if you still find upgrade errors or bad behavior related to backslashes, or special chars, it is nice you report them, but don't close the issues if you workaround them. Instead, if you can, reproduce on a testing environment and let's discuss together to find how the bug occurs. This is necessary to remove the bug in the code. Every user of the plugin will benefit the fix, and I guess you're happy to not think avoiding some chars when adding data in your DB. Such bug must be closed when we cannot reproduce again after a fix.
