### ISSUE TITLE
[AMELIORATION] Titres formulaire dynamique

### ISSUE THREAD

**Issue by JulienG78** [pluginsGLPI/formcreator#601]
Bonjour,

Serait-il envisageable de pouvoir personnaliser le titre des formulaires générés ?

Je m'explique :

- Aujourd'hui j'ai créé un formulaire pour les RH pour déclarer un nouvel arrivant. Quand le formulaire est créé celui-ci garde le titre du template de formulaire soit "arrivée ressource". Quand on a plusieurs fois le même formulaire c'est juste impossible de s'y retrouver.

Je suis conscient que ma demande peut paraitre spécifique mais je pense sincérement que ma question va toucher à tout les types de besoins en formulaire. Il devient vite ingérable de traiter plusieurs formulaires qui ont tous le même nom.

D'où mon idée, car quand on définie une cible sous forme de ticket on a les hashtags qui renvoit vers les réponses du formulaire afin de personnaliser le ticket. Il faudrait pouvoir ajouter cette option dans les paramètres du formulaire, dans l'onglet général par exemple. De pouvoir rendre dynamique le titre du formulaire en fonction d'une réponse à une question du formulaire.

Je pense que ça aiderais énormément de monde !

Merci par avance,

**Comment by btry** [comment]
Bonjour

C'est déjà possible

Modifiez le ticket destination et utilisez les réponses pour "forger" le titre de vos tickets générés 

Vous voudrez sans doute quelque chose similaire à ceci : 
Demande RH: nom ##answer_NN##

![image](https://cloud.githubusercontent.com/assets/14139801/26000054/b943c3f2-3727-11e7-9926-5407ff21e25c.png)
Vous avez en bas du formulaire la liste des tags utilisables: les noms des champs, et les réponses, entourés par deux # 

![image](https://cloud.githubusercontent.com/assets/14139801/26000090/d7f7d98c-3727-11e7-8767-fcd6e516ea74.png)

**Comment by JulienG78** [comment]
Bonjour, je ne parle pas du ticket.
Je parle du formulaire en lui même.
Lorsque le formulaire est créé le formulaire garde le nom du template de formulaire.

Du coup si je créer un nouveau formulaire qui s'apelle "Arrivée", dans ce cas tout les formulaires créés se nomment tous "Arrivée", ce qui est ingérable.

Comme indiqué dans mon message je ne parle pas du des tickets qui eux sont personnalisables je le sais.
Je parle du titre du formulaire.

**Comment by btry** [comment]
Je vois. On peut peut être imaginer le même mécanisme que le titre des tickets générés. pour avoir la même souplesse.

**Comment by JulienG78** [comment]
Voila car la quand on voit ça dans ssa liste de formulaire c'est assez difficil.

Du coup vu que vous avez déjà créé ça pour les tickets, j'imagine que ça semble envisageable de l'appliquer au titre du formulaire qui est généré.

![12-05-2017 15-50-03](https://cloud.githubusercontent.com/assets/24435635/26000904/e2947186-372a-11e7-97c0-002bc4ba0f6a.png)

**Comment by JulienG78** [comment]
Ce serait vraiment top en tout cas.
Mais quoi qu'il arrive je tiens à vous remercier pour votre travail remarquable !!
Pour information nous avons comparé votre solution à d'autres outils payants, et franchement le boulot fait pour ce plugin est vraiment super !

Bravo à vous !

**Comment by btry** [comment]
Techniquement c'est envisageable. Par contre la largeur de la zone étant faible, les titres longs seront soit tronqués, soir sur plusieurs lignes, cassant la lisibilité.

Je note qu'il faudrait peut être prévoir aussi une infobulle

**Comment by btry** [comment]
Nous sommes ravis de votre satisfaction vis à vis de ce plugin.

**Comment by JulienG78** [comment]
Bonjour,

Votre nouvelle version semble très intéressante. Par contre sauf erreur de ma part je n'ai pas vu cette amélioration. J'imagine que vous l'avez prévu pour une prochaine release ?
c'est juste pour savoir :)

Merci

**Comment by btry** [comment]
Bonjour

Non, la feature n'est pas encore implémentée. Le développement  communautaire est en best-effort, et il me semble qu'il à a des parties du plugin à revoir de manière prioritaire, vu les derniers rapports de bugs.

**Comment by JulienG78** [comment]
Pas de soucis je comprends tout à fait :)
Bon courage en tout cas pour votre super boulot.
