### ISSUE TITLE
Liste des formulaires

### ISSUE THREAD

**Issue by JulienG78** [pluginsGLPI/formcreator#602]
Bonjour,
J'ai un besoin qui je pense peut être résolu par quelque chose qui existe déjà mais qui ne semble pas fonctionner.

Voila j'aimerais pouvoir voir un résumé des tickets d'un formulaire depuis la liste des formulaires.

Quand je suis dans la liste, si je veux paramétrer les colonnes qui s'affichent je peux ajouter la colonne "nombre de tickets", mais hélas celle-ci ne s'affiche pas :( du coup je ne sais pas ce que ça fait et si ça peut répondre à mon besoin.

Une idée ? Merci

**Comment by btry** [comment]
Bonjour

Je reproduis; c'est un bug.

**Comment by btry** [comment]
Bonjour

Il semble que sur la future version 2.5.0 la colonne "Nombre de tickets" fonctionne. Pouvez-vous faire un essai ? 

![image](https://cloud.githubusercontent.com/assets/14139801/26359354/890f08e8-3fd5-11e7-9e2d-897fbe4636f8.png)

**Comment by JulienG78** [comment]
Je dois avoir un soucis car ça ne fonctionne toujours pas de mon coté.
Par ailleurs lorsque je tente de changer l'ordre des colonnes ça ne fonctionne pas.
J'ai rajouté la colonne "date de création", et celle-ci s'est placé à la dernière colonne malgré mes tentatives de la mettre ailleurs, elle reste à la fin.

Je suis en 2.5.0 et sur GLPI 9.1.4.
![19-06-2017 11-37-55](https://user-images.githubusercontent.com/24435635/27279122-f7dbbb40-54e3-11e7-8871-2e7fdfd9d978.png)

**Comment by JulienG78** [comment]
J'ai trouvé, enfait dans le réglage de la vue il fallait que j'aille dans l'onglet VUE PERSONNELLE, c'était lui qui apparement était affiché de base et qui n'avait pas la colonne Vue des tickets.

Parcontre quand je clic sur le nombre de ticket dans cette colonne j'arrive sur un filtre de recherche bizarre qui ne m'envoit sur rien du tout.
Sur ma capture j'obtiens cette page en cliquant sur le chiffre 2 qui correspont au nombre de tickets inclus dans un formulaire issue de la liste des formulaires. Je pensais qu'en cliquant sur le nombre de tickets cela m'afficherait la liste des tickets mais à la place je reçois ça
![23-06-2017 16-14-37](https://user-images.githubusercontent.com/24435635/27485946-31294266-582f-11e7-8f46-5dee02ef9f8c.png)
 :

**Comment by btry** [comment]
Bonjour

Donc le travail portera sur la correction du filtre défini sur cette page.

**Comment by btry** [comment]
Le problème semble porter sur les ID des search options de l'itemtype form_answer.

l'ID 1 devrait être correspondre à la colonne **name** et elle correspond pour le moment à **status**

**Comment by btry** [comment]
Bonjour

J'ai un correctif à vous faire tester. Attention, il va modifier les préférences d'affichage des listes. A tester en pré-production uniquement. Si le patch est appliqué puis retiré, l'affichage de certaines listes dans GLPI pourrait casser. Il faut donc bien sauvegarder avant de le metre à l'épreuve.

**Comment by btry** [comment]
Le  correctif a été validé. il sera dans la prochaine release.

**Comment by JulienG78** [comment]
Merci beaucoup ! je vais tester ça de ce pas.
