### ISSUE TITLE
Perte des dépendances de questions apres mise à jour plugin FormCreator

### ISSUE THREAD

**Issue by Nitro76210** [pluginsGLPI/formcreator#603]
Bonjour à tous,

Lorsque je mets à jour GLPI et le plugin FormCreator, mes formulaires perdent les dépendances entre les questions.

J'ai essayé de mettre à jour mes différentes applications GLPI :

GLPI 0.83.7 et FormCreator 1.4.2 vers 9.1.2 et formCreator 2.4.2=> Problème ci-dessus constaté
GLPI 0.84.5 et FormCreator 0.84-2.1.6 vers 9.1.2 et formCreator 2.4.2 => Problème ci-dessus constaté
GLPI 0.84.8 et FormCreator 0.84-2.1.6 vers 9.1.2 et formCreator 2.4.2 => Problème ci-dessus constaté
GLPI 0.85.4 et FormCreator 0.90-1.2.5 vers 9.1.2 et formCreator 2.4.2 => Pas de problème

J'ai biensur essayé une étape intermédiaire en migrant préalablement mes premieres applications en 0.85.4 mais j'ai toujours le problème.

A noter que : 

- Pas de problème pendant la migration de GLPI vers la 9.1.2. 
- Par contre, lorsque je veux mettre à jour le plugin formcreator, j'obtiens le message d'erreur : 

Installing glpi_plugin_formcreator_forms_answers (0 seconde)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Ã©tude / chiffrage Demande de modification MaÃ§onnerie / GÃ©nie civil / Vrd A' at line 3
Please, check migration log

Puis lorsque je relance la mise à jour du plugin, ca semble passer mais un message en bas a droite dans une fenetre rouge m'indique : 
Erreur
close
L'intitulé est obligatoire
L'intitulé est obligatoire

Avez-vous une solution ou devrais-je reconfigurer toutes les dépendances de mes formulaires ?

Merci d'avance,

Frederic

**Comment by Nitro76210** [comment]
Personne n'a une idée ? Avez-vous besoin d'une sauvegarde ?

**Comment by btry** [comment]
Bonjour

Il me semblait avoir répondu le jour même, en disant que ça ressemble à un autre bug déjà résolu.

Je vais tenter de reproduire cette fin de semaine, il est possible que j'aie quelques question à vous poser pour arriver à reproduire.

**Comment by Nitro76210** [comment]
Bonjour et merci pour votre réponse rapide...

Non je ne m'en rappelle pas mais ca n'est pas grave.

N'hésitez pas si vous avez d'informations complémentaires,

Merci pour votre aide,

**Comment by btry** [comment]
Je viens d'éditer mon message (mais vous avez été plus raipde). 

Et si ma réponse initiale n'est pas là c'est qu'il s'est passé quelque chose sur mon interface chaise / clavier ;)

**Comment by Nitro76210** [comment]
Foutue interface...  :-)

**Comment by btry** [comment]
Bonjour

Avez-vous pu vérifier le fichier journal de migration ? Il me permettra de localiser l'erreur SQL que  vous avez signalé.

**Comment by Nitro76210** [comment]
Bonjour,

Je suis désolé si la question est redondante mais j'ai fait des recherches sur le forum mais rien trouvé : Ou se trouve ce fichier journal de migration ?

Merci d'avance,

**Comment by btry** [comment]
C'est ce que j'ai ajouté dans mon premier message de ce ticket : 

> EDIT: le message d'erreur vous invite à vérifier le journal de migration. Il doit y avoir un backtrace dedans. Le fichier e trouve dans glpi/files/_log et son nom commence par migration suivi de versions du plugin.

Un exemple **migration_to_2.5.0.log**

**Comment by Nitro76210** [comment]
Autant pour moi, je n'étais pas revenu sur votre précédent post...

Ayant bcp de fichier commencant par "migration", je vous ai joint le dossier complet compressé : 

[https://1drv.ms/u/s!ApiDa4aXlGsUlfFtp7Yix35oYpBs2A](url)

**Comment by btry** [comment]
L'archive contient bien des fichiers de migratioin, mais ils concernent tous un upgrade de GLPI.

Reproduisez le bug, et immédiatement après, voyez si vous avez un fichier **migration_to_2.4.2.log** (à supposer que vous upgradez vers la version 2.4.2 du plugin).

**Comment by Nitro76210** [comment]
Ce fichier ci ira peut-être mieux : 

[https://1drv.ms/u/s!ApiDa4aXlGsUlfFvWoVdEOkHLpbt6A](url)

**Comment by btry** [comment]
Oui  c'est le bon. Mais il n'y a pas de backtrace. En revanche la  dernière ligne est incomplète, donc c'est par là qu'a lieu le plantage.

Il doit y a voir un endroit où la gestion d'erreur est incomplète. Ca donne quelques indices.

Pouvez-vous dire à quoi correspond l'extrait de texte dans l'erreur SQL (nom de catégorie, titre de formulaire, ...) ?

> Ã©tude / chiffrage Demande de modification MaÃ§onnerie / GÃ©nie civil / Vrd A

Ca finira de cibler le code fautif.

**Comment by Nitro76210** [comment]
A des valeurs d'une liste d
![capture](https://cloud.githubusercontent.com/assets/25430105/26253194/c53c490a-3cb2-11e7-91d3-b80997af0ab6.JPG)
éroulante du formulaire :

**Comment by btry** [comment]
Parfait: je pense que j'ai tout ce qu'il me faut. Merci.

Je vous ferai tester un correctif pour la 2.4.2 pour vous débloquer et valider la solution. En revanche, le fix sera appliqué certainement dans la version 2.5.0. Il n'y a pas de 2.4.3 prévue.

**Comment by btry** [comment]
Bonjour

Je tente de reproduire avec GLPI 0.84.5 et FormCreator 084-2.1 ou 0.84-2.1.6, sans succès. La migration se passe bien. L'erreur que vous rencontrez ne doit pas arriver car le code prévoit ce cas.

Je pense que je ne cherche pas au bon endroit. Il faut vraiment avoir le backtrace situé dans le log.

Pouvez-vous reproduire sur GLPI 0.84.8 + FormCreator 0.84-2.1.6 en upgrade vers GLPI 9.1.3 + FormCreator 2.4.2 ?

J'ai vérifié la gestion d'erreur. Si vous avez le message "check migration log" vous devez avoir les détails dans le fichier de migration. Il n'y a pas d'exception possible.

Si vraiment il n'y a rien dans le fichier de migration, alors vous pouvez modifier setup.php du plugin

A la fin du fichier vous verrez : 
```
function plugin_formcrerator_upgrade_error(Migration $migration) {
   global $DB;

   $error = $DB->error();
   $migration->log($error . "\n" . Toolbox::backtrace(false, '', array('Toolbox::backtrace()')), false);
   die($error . "<br><br> Please, check migration log");
}
```
avant la ligne die(), insérez la ligne suivante:

```
echo Toolbox::backtrace(false, '', array('Toolbox::backtrace()'))
```

Le backtrace dont j'ai besoin doit apparaître à l'écran quand l'erreur survient.

**Comment by Nitro76210** [comment]
Bonjour,

Merci bcp pour votre aide et le temps que vous y passer... je vais essayer d'être le plus précis possible dans mes explications et d'apporter des éléments importants : 

Comme vous le suggériez ci-dessus, j'ai activé le backtrace dans le fichier setup.php et j'ai d'abord migré mon application GLPI de 0.84.5 et formcreator 0.84-2.1.6 vers GLPI 0.84.8 et  formcreator 0.84-2.1.6 et là, surprise, le problème est déjà présent.

Vous trouverez dans le lien ci-dessous les logs de migration, ainsi qu'un exemple de question qui ne passe pas avant migration et apres migration. A noter que ces questions sont, de base, paramétré : 
- en "Obligatoire : premier choix ne sera pas séléctionnable" => option non presente dans la MAJ
- avec une 1ere valeur nulle qui est supprimée apres migration

https://1drv.ms/u/s!ApiDa4aXlGsUlfFwkwlEp8aWddsbCA

Je reste à votre disposition pour tout renseignement complémentaire,

Frederic

**Comment by Nitro76210** [comment]
Juste une autre question, les opérateurs de condition, pour l'affichage ou non des questions, ne sera pas qu'en version 2.50 de formcreator ? il n'est pas déjà présent en 2.42 ?
https://github.com/pluginsGLPI/formcreator/pull/383

**Comment by btry** [comment]
Les conditions existent depuis longtemps. Elles sont simples jusqu'en 2.4.2, et seront multiples à partir de 2.5.0. C'est à dire qu'on pourra composer des expressions avec plusieurs critères, connectés avec des opérateurs booléens.

**Comment by btry** [comment]
> migré mon application GLPI de 0.84.5 et formcreator 0.84-2.1.6 vers GLPI 0.84.8 et formcreator 0.84-2.1.6 

Il y a quelque chose que je ne comprends pas bien. Dans vos logs je vois un fichier **migration_to_0.84-2.1.5.log** Ca indique que vous migrez **vers** une très ancienne version qui serait la même qu'au début de votre essai. 

Du coup je ne vois pas l'intérêt de modifier setup.php car à cette époque il n'y avait rien pour enregistrer sur disque les erreurs de migration (j'ai ajouté cela trés récemment pour des cas comme le vôtre).

Ce qui expliquerait pourquoi vous n'avez pas relevé un éventuel message détaille affiché à l'écran (que j'attendais à défaut d'avoir une trace dans les fichiers de log). Le code que je vous ai montré est appelé en cas d'erreur SQL, et enregistre sur disque le backtrace (depuis la version 2.4.1).  L'ajout que je vous ai fait faire permet d'afficher le backtrace à l'écran en plus de l'enregistrer sur disque.

- Faites l'upgrade de GLPI à votre convenance, l'important est que vous montiez à 9.1.x. 
- Remplacez le plugin par sa version 2.4.2, 
- Faites la modification dans glpi/plugins/formcreator/setup.php 
- Lancez son upgrade depuis GLPI. Vous devez avoir dans migration_to_2.5.0.log le backtrace qui s'affichera aussi à l'écran.

En parallèle je reprendrai vos captures d'écran pour voir si elles me donnent une piste supplémentaire

**Comment by Nitro76210** [comment]
D'accord merci pour les conditions. Je vais avoir besoin de cette évolution. Pour quelle date est prévue la 2.50 ?

Pour la migration, à la base, je fais bien une migration d'une version GLPI 0.84.5 et Formcreator 0.84-2.1.6 VERS GLPI 9.1.2 et formcreator 2.4.2 mais comme vous me posiez la question suivante : 
"Pouvez-vous reproduire sur GLPI 0.84.8 + FormCreator 0.84-2.1.6 en upgrade vers GLPI 9.1.3 + FormCreator 2.4.2 ?"
j'ai pensé que vous vouliez que je migre en 2 fois en passant par une version GLPI 0.84.8 + FormCreator 0.84-2.1.6....

Mais avant cela, je migrais bien une version GLPI 0.84.5 et Formcreator 0.84-2.1.6 VERS GLPI 9.1.2 et formcreator 2.4.2.

Pour revenir à mon constat, en migrant préalablement par la version GLPI 0.84.8 + FormCreator 0.84-2.1.6, j'ai pu constaté que les questions avaient déjà perdues leurs valeurs nulles ainsi que leurs dépendances aux autres questions (afficher le champs uniquement si...) 

J'ai refais la migration GLPI 0.84.5 et Formcreator 0.84-2.1.6 VERS GLPI 9.1.2 et formcreator 2.4.2 en ayant activé le"echo Toolbox" à la fin du fichier setup.php mais aucun message n'apparait à l'écran à part celui-ci : https://1drv.ms/i/s!ApiDa4aXlGsUlfJD2BU1njLfxnqI1g

**Comment by btry** [comment]
Bonjour

> "Pouvez-vous reproduire sur GLPI 0.84.8 + FormCreator 0.84-2.1.6 en upgrade vers GLPI 9.1.3 + FormCreator 2.4.2 ?"

Il faut faire l'upgrade du plugin sans passer par une version intermédiaire dudit plugin. 

Simplifiez les étapes d'upgrade:
Sur un GLPI où l'erreur SQL survient, upgradez vers GLPI 9.1.2, sans upgrader le plugin. Sauvegardez votre BDD (si on veut faire d'autres essais, ça ira plus vite de restaurer un snapshot).

Ensuite, upgradez le code, et uniquement le code de FormCreator vers la version 2.4.2 et appliquez ce patch :
https://github.com/pluginsGLPI/formcreator/compare/master...btry:feature/fix_603_try_1?expand=1

Ensuite, lancez la procédure d'upgrade du plugin. J'espère qu'avec ce correctif l'upgrade passera sans plantage. 

Si l'upgrade réussit, vérifiez que vos formulaires n'ont rien perdu. J'attends votre retour.

**Comment by Nitro76210** [comment]
Bonjour et merci bcp pour votre aide.

J'ai donc : 
-effectué une sauvegarde de GLPI après migration en 9.1.2
- remplacé les lignes 798 et 799 du fichier inc/question.class.php
- effectué la migration de formcreator vers 2.4.2

Résultat : même problème constaté, les dépendances entre questions sont perdues... Les questions, qui devraient apparaitre uniquement selon une certaine valeur d'une autre question, sont en "Toujours visible"

**Comment by btry** [comment]
D'accord, mais avez vous eu une erreur SQL  comme décrit dans votre premier message ? C'est d'abord cela que je veux éliminer. Ensuite, si ce bug est corrigé, il faut voir si il y a un impact positif sur les conditions. (et sinon, trouver un second fix)

**Comment by Nitro76210** [comment]
Ah pardon je n'avais pas compris votre besoin...

En ayant activé les logs dans setup.php :

- Depuis une application en GLPI 0.84.5 et formcreator 0.84-2.1.6 => pas de message d'erreur SQL mais dépendances entre questions perdues

- Depuis une application en GLPI 0.83.7 et formcreator 1.4.2 => pas de message d'erreur SQL (alors que j'en avais un avant) mais dépendances entre questions perdues

**Comment by Nitro76210** [comment]
Bonjour,

Avez-vous besoin d'autre chose pour investiguer sur le pb de dépendances ?

A votre disposition dans ca cas,

Merci d'avance,

Frederic

**Comment by btry** [comment]
Bonjour

J'ai commencé à étudier le système d'upgrade sur ce point et il apparait que avec la version 1.4.2 l'upgrade ne soit pas fait correctement. Ce serait intéressant que vous me confirmiez que cette version 1.4.2 est bien celle qui provient de la forge de GLPI (https://forge.glpi-project.org/projects/formcreator). Je dois continuer à investiguer pour confirmer cette hypothèse.

Si le même souci survient avec la version 0.84-2.1.6  je pense qu'il  faudrait réparer ce cas en premier. Une fois fait, il faut voir si ça résout l'upgrade depuis une version encore plus ancienne (autrement dit la 1.4.2)

Je dois me concentrer sur un autre projet dans les jours à venir, donc je serai silencieux pendant une petite quinzaine de jours. Cela n'empêche pas, si vous trouvez quelque chose d'intéressant, de continuer à poster ici. 

Je n'ai pas répondu à propos de la sortie de la v2.5.0. Pour les mêmes raisons, la release sera repoussée à la seconde quinzaine de juin, peut être juillet. Cette version contient de nouvelles features, une contribution. Je voudrais résoudre quelques bugs ennuyeux pour cette occasion, dont le vôtre.

**Comment by Nitro76210** [comment]
Bonjour,

Je vous confirme que la version 1.4.2 dont je dispose provient bien de la forge : https://forge.glpi-project.org/projects/formcreator

D'accord pour les 15 jours, ce problème n'est pas bloquant pour moi dans ma migration car je peux re-créer les dépendances post-migration mais cela me demande environ 1 heure par formulaire...

**Comment by btry** [comment]
Bonjour

J'ai repris un FormCreator 1.4.2 et je n'y vois pas quoi que ce soit qui constitue une dépendance entre des questions. Le plugin en étant à ses débuts. J'ai créé quelques formulaires puis réalisé un upgrade vers 2.5.0. Il semble que ça se soit bien passé. Les formulaires ont leurs sections et leurs questions.

**Comment by Nitro76210** [comment]
Bonjour et merci pour votre retour...

Comme je vous l'avais spécifié dans mon message qui date de 14 jours : 

"Pour revenir à mon constat, en migrant préalablement par la version GLPI 0.84.8 + FormCreator 0.84-2.1.6, j'ai pu constaté que les questions avaient déjà perdues leurs valeurs nulles ainsi que leurs dépendances aux autres questions (afficher le champs uniquement si...)"

C'est pour cela que je me demande si le problème n'est pas du côté de GLPI (et non de formcreator) ou que le plugin ne gère pas l'ancienne méthode de gestion des dépendances (Select Questions on change)

Si je suis le seul utilisateur dans ce cas, ne passez pas trop de temps sur ce problème... Je vais recréer toutes les dépendances... cela demande du travail... mais le problème n'est pas bloquant

**Comment by btry** [comment]
Bonjour

Non, le problème est clairement dans le plugin; mais remonter aussi loin dans le temps rend l'exercice assez compliqué. 

De toute façon, ce problème est le dernier que je compte traiter pour releaser la version 2.5.0. Comme vous avez un contournement, je pense qu'il est effectivement plus sage de laisser ce bug de côté vu la faible fréquence et la complexité à le résoudre.

**Comment by Nitro76210** [comment]
Bonsoir,


Je suis d'accord, vous pouvez cloturer le ticket.


Merci pour le temps passé et pour votre aide


Frederic


________________________________
De : btry <notifications@github.com>
Envoyé : mardi 6 juin 2017 18:31
À : pluginsGLPI/formcreator
Cc : Nitro76210; Author
Objet : Re: [pluginsGLPI/formcreator] Perte des dépendances de questions apres mise à jour plugin FormCreator (#603)


Bonjour

Non, le problème est clairement dans le plugin; mais remonter aussi loin dans le temps rend l'exercice assez compliqué.

De toute façon, ce problème est le dernier que je compte traiter pour releaser la version 2.5.0. Comme vous avez un contournement, je pense qu'il est effectivement plus sage de laisser ce bug de côté vu la faible fréquence et la complexité à le résoudre.
