### ISSUE TITLE
affichage de champ

### ISSUE THREAD

**Issue by NoK80** [pluginsGLPI/formcreator#604]
Bonjour,
Mon formulaire contient par exemple question 1: liste de 20 valeurs (0,1,2,3 ---->20)
et question 2
Je voudrais afficher question 2 juste dans le cas ou question 1 égale (0 ou 2 ou 4 ).
Est-ce cela est possible en utilisant le champ "masqué par défaut sauf"? (ça vaut dire tester plusieurs valeurs au lieu de tester qu'un seul valeur)

Merci,

**Comment by btry** [comment]
Bonjour

Jusqu'à la version 2.4.x les conditions ne sont pas assez sophistiquées pour cela. Votre besoin est couvert dans la version 2.5.0 mais est encore en développement, et devrai sortir bientôt.

Si vous en avez la possibilité, essayez la sur un environnement de test. Les remontées de bugs sont les bienvenues.
Je clos le ticket étant donné que votre besoin est déjà implémenté.

**Comment by NoK80** [comment]
Où je peux trouver la version 2.5.0 pour la tester? merci

**Comment by btry** [comment]
(répondu en #605)
