### ISSUE TITLE
Envoi de mail à un Observateur & technicien suite à la création d'un ticket

### ISSUE THREAD

**Issue by TarekDB7** [pluginsGLPI/formcreator#606]
Bonjour,

Sur la version 9.1.3 de GLPI et 2.4.2 de Formcreator, je ne parviens pas à effectuer une notification par mail à un observateur et un technicien suite à la création d'un ticket généré par Formcreator.

**Comment by btry** [comment]
Lien du sujet sur le forum: http://forum.glpi-project.org/viewtopic.php?pid=333891

**Comment by btry** [comment]
Bonjour

Pouvez vous exporter en JSON et poster ici votre formulaire (ou mieux: un formulaire qui reproduit le bug, mais réduit au minimum) ?

**Comment by TarekDB7** [comment]
Pour l'instant je n'ai pas vraiment la possibilité de l'exporter, j'ai testé sur plusieurs formulaires le résultat est le même.

**Comment by btry** [comment]
Dans la version 2.4.2 il y a une fonction d'export destinée à passer des formulaires entre 2 GLPI (prod / intégration par exemple). Ca évite de recopier à la main un formulaire  testé sur une instance séparée de GLPI. 

Comme certains bugs peuvent être liés à une conception particulière, la fonction est pratique pour me transmettre un formulaire présentant un bug en vue de le reproduire.

Choiisissez le formulaire le plus petit parmi ceux qui buguent, et faites une action de masse dessus pour l'exporter. Ca se fait en quelques clics.

![image](https://cloud.githubusercontent.com/assets/14139801/26313225/7871bcc2-3f0a-11e7-9b42-bf4ee72b1608.png)

**Comment by Gambware** [comment]
J'ai le même problème.


[export_formcreator_20170522_1541.zip](https://github.com/pluginsGLPI/formcreator/files/1020198/export_formcreator_20170522_1541.zip)

**Comment by btry** [comment]
Bonjour

Merci @Gambware pour le formulaire exemple. 

J'ai fait des essais et je n'arrive pas à reproduire le bug. En revanche, si je désactive la notification **Update Ticket** (Configuration > Notifications > Notifications), les mails ne sont plus générés. 

@TarekDB7 @Gambware pouvez vous vérifier si la notification Update Ticket est activée ?

**Comment by TarekDB7** [comment]
Bonjour,

Ce type de notification est bien active sur mon serveur.

**Comment by btry** [comment]
@TarekDB7 

Quelle version de GLPI utilisez-vous ? 
Sur le ticket généré, votre technicien est bien ajouté, et ses notifications sont bien actives ?

![image](https://cloud.githubusercontent.com/assets/14139801/26356977/2f16f988-3fce-11e7-9933-591f6a63c16f.png)

**Comment by TarekDB7** [comment]
Je fais actuellement des test sur la version 9.1.3, mais le problème est le même sur la version 9.1.1.
Mon technicien est bien ajouté et ses notifications sont bien actives, d'ailleurs il n'ont pas de problèmes particuliers lors de la génération de tickets hors Formcreator.

**Comment by btry** [comment]
@TarekDB7 : Le plugin n'exécute pas le même code pour générer les tickets sur GLPI 9.1.1 comparé à GLPI 9.1.2 ou supérieur. Du coup, il vaudrait mieux ouvrir un ticket différent car les bugs seraient différents (et le fix aussi)

**Comment by TarekDB7** [comment]
Pour le moment, je souhaiterais élucider ce bug en version 9.1.3 car on peut toujours envisager de monter en version.

**Comment by btry** [comment]
tout à fait d'accord, car si tout se passe comme prévu, le support de GLPI < 9.1.2 sera supprimé (la PR est déjà prête)

**Comment by TarekDB7** [comment]
@btry Cela fonctionne de votre côté si j'ai bien compris ?

**Comment by btry** [comment]
Oui, et d'après le ticket #595 ça fonctionne mieux avec GLPI 9.1.2+ que les versions d'avant. Je ne vois pour le moment pas ce qui peut vous causer ce souci.

Si vous pouvez partager votre formulaire comme l'a fait @Gambware ça me donnera peut être une piste.

**Comment by Gambware** [comment]
Ce problème est déjà arrivé avec moi sur la version 9.1.1
J'ai déjà essayé d'activer / Désactiver la notification de mise à jour et même si le formulaire n'émet aucun courrier électronique à Technician and Watchers. J'ai été mis à jour vers la version 9.1.2 et 9.1.3 et ne fonctionnait pas.

**Comment by TarekDB7** [comment]
[export_formcreator_testgit.zip](https://github.com/pluginsGLPI/formcreator/files/1024821/export_formcreator_testgit.zip)

**Comment by Gambware** [comment]
Des commentaires à ce sujet?

**Comment by btry** [comment]
Pas pour le moment. Peut être mardi, si j'ai du nouveau.

**Comment by Gambware** [comment]
Nous avons mis à jour le plugin vers 2.5.0, mais continuez de ne pas envoyer d'e-mail (New Ticket) à l'utilisateur "affecté à" comme image ci-dessous

![image](https://user-images.githubusercontent.com/24397740/27044386-010edba6-4f63-11e7-9d88-007e957ef602.png)

**Comment by btry** [comment]
Bonjour

@Gambware: je viens de refaire un essai. J'ai créé un formulaire et ai assigné  une personne spécifique au ticket destination. Si je réponds au formulaire, j'ai 2 emails générés: un pour le demandeur, et un pour l'utilisateur assigné.

En GLPI 9.1.2+, le plugin crée le ticket et ajoute les acteurs en une seule opération. Si l'utilsiateur est ajouté, et que le drapeau "notification" est bien activé (ce qui est le cas selon votre capture d'écran), c'est la preuve que le plugin a donné les informations attendues à GLPI. C'est GLPI qui se charge de produire les notifications, sur la base de sa configuration et le drapeau "notifications". Je pense qu'il y a un souci de configuration hors du plugin.

Si vous créez un ticket via GLPI en assignant le même utilisateur, la notification est-elle générée ?

**Comment by btry** [comment]
Bonjour

C'est un détail intéressant. Je tenterai de reproduire de cette manière.

**Comment by btry** [comment]
Je n'en ai pas encore la certitude.

**Comment by btry** [comment]
Bonjour

D'après mes essais, peu importe que l’utilisateur soit authentifié ou non. Je reproduis si la notification **New Ticket** est configurée comme suit (aucun destinataire)

![image](https://user-images.githubusercontent.com/14139801/27784458-60970c2e-5fda-11e7-9dd0-15a52cfff7f0.png)

Du moment que j'ajoute le  technicien en charge du ticket à la notification, l'email à destination du technicien est bien créé et mis en file d'attente, y compris avec un formulaire public. Est ce que votre souci ne serait pas simplement là ?
![image](https://user-images.githubusercontent.com/14139801/27784444-527d03d2-5fda-11e7-8e25-a4cfcc8bc56f.png)

**Comment by Gambware** [comment]
Oui, cela a résolu le problème.
Nous n'avions pas compris cela, parce que les techniciens ont toujours reçu les courriels, seulement et exactement quand il n'était pas authentifié, le technicien n'a pas reçu.

Merci beaucoup pour l'aide.

**Comment by btry** [comment]
Bonjour

Par défaut la notification est configurée comme ceci :
* Profile: Admin
* Administrator
* Requester
* Watcher

Les techniciens n'étant pas dans la liste ils ne doivent pas recevoir de notification; sauf si vous changez ce paramétrage, ou si un plugin altère le comportement de cette notification.

Si dans certains cas la notification a fonctionné avec les techniciens, quelque chose a dû le faire pour vous. Un autre plugin peut être ? Pouvez-vous montrer la liste de vos plugins actifs ?

**Comment by btry** [comment]
Bonjour 

Etant donné que le souci n'est qu'un problème de configuration, et n'ayant pas de retour pour trouver pourquoi ça fonctionnait auparavant, je ferme.
