### ISSUE TITLE
Can't add "Actors from the question" - Forms Destination

### ISSUE THREAD

**Issue by Gambware** [pluginsGLPI/formcreator#609]
When I try to add an "Actor from the question" in a form, the list appears empty. 

![image](https://cloud.githubusercontent.com/assets/24397740/26373330/bb0b2cbe-3fc6-11e7-96ce-c62aca218f78.png)

GLPI Version 9.1.3 
FormCreator 2.4.2 

The forms that already had "Actors from the question" (before the update) still working, but doesn't allow to add more.

**Comment by btry** [comment]
Hi

I checked, it seems to be working. 

Are you sure your previously created a question of type **actor** in this form ?

**Comment by Gambware** [comment]
Ok, I understand, I was trying to use an E-mail question to put as an Actor. 
But, I see that I can do that modifying the the table "glpi_plugin_formcreator_targettickets_actors"

So I basically change the Columns 

actor_type = question_actors
and 
actor_value = (I insert the number of the question that I want to put in this field)

![image](https://cloud.githubusercontent.com/assets/24397740/26378014/55427da8-3fd8-11e7-8b13-519fac3cd8e6.png)

And works for me !!! 

I think this could be very useful to use the forms with Anonimous Users. Allow to user as actor the field e-mail.

Thanks

**Comment by Gambware** [comment]
Look that.

![image](https://cloud.githubusercontent.com/assets/24397740/26378119/bab25fa0-3fd8-11e7-929d-602e3eb6bab9.png)

**Comment by btry** [comment]
Hi

The actors field allows the reqester to input an email address. I think you don't need to hack the plugin. Can you try it ?

**Comment by Gambware** [comment]
I try it, 

In my scenario I create a form with public access. The users don't logged in GLPI can open this form and fill it. When I add an actor field in this form, users that aren't logged on GLPI can't use this field. See the image below.

![image](https://cloud.githubusercontent.com/assets/24397740/26407065/b46a90f4-405f-11e7-9d5f-63d5298b9a0e.png)

When the user press TAB or go to another field, the actor field (test) back to empty.

**Comment by btry** [comment]
Indeed, then you're in the same case as found in #587.

Then the your question is solved, but if you want to not hack your DB as described here, you need a solution for #587. You should subscribe to it to receive followups.

As the original problem is solved, I close this one.
