### ISSUE TITLE
accès direct au formulaire via leur url

### ISSUE THREAD

**Issue by ericeric227** [pluginsGLPI/formcreator#612]
Bonjour,

J'ai paramétré le catalogue de service comme indiqué ici : http://forum.glpi-project.org/viewtopic.php?id=157613

Et le catalogue de service est très convivial, j'en suis content.

Mais nous avons un site intranet qui permet d'authentifier les utilisateurs via un SSO.

Et lorsque les utilisateurs "cliquent" sur les liens qui pointent vers les formulaires, lors du premier clic, il sont redirigés vers wizard.php au  d'accéder au formulaire.

J'ai vérifié que  les formulaires concernées soient directement accessibles, mais rien y fait.

En désactivant l'authentification les formulaires sont directement accessibles, sans redirection.

Par avance,

Merci de votre aide,

glpi : 9.1.2.
formcreator : 2.4.2.

**Comment by btry** [comment]
Bonjour

Pouvez vous vérifier si le problème est toujours d'actualité avec la version 2.12.0 ?
