### ISSUE TITLE
Notifications non fonctionnelles

### ISSUE THREAD

**Issue by philippeplatiau** [pluginsGLPI/formcreator#613]
Bonjour, 
Avec la version GLPI 0.90.5, et FormCreator 2.4.2 (ou 2.4.1, même comportement), j'ai quelques soucis avec les notifications. 

Contexte: 

J'ai créé un formulaire que les commerciaux remplissent. 
Une fois soumis, un ticket est créé. Je suis assigné comme technicien et j'avais mis comme "Watcher group", un groupe de personnes qui doivent également être notifiées. 
Le "watcher group" n'est plus notifié. Uniquement moi. 
J'ai même testé avec un "watcher" simple, ou même un technician group ou un autre technicien... rien n'y fait... Je vois bien le groupe ou la personne qui sont rajoutés dans le ticket mais le mail ne leur est pas envoyé. Par contre, quand je rédige un follow-up dans le ticket, là, ils le reçoivent bien 

Je me demandais donc si l' événement appelé lors de la création du formulaire était bien un "New Ticket" et pas autre chose. 

Dans l'Event "New ticket", j'ai le technicien, le watch group, le watcher, l'auteur, et le technician group... Cela fonctionne parfaitement quand je crée manuellement un ticket. 

Une idée ? Avez-vous besoin d'autres informations ? 

Cordialement, 

Philippe

**Comment by btry** [comment]
Bonjour

Le support avec GLPI 0.90.x devrait cesser avec la release 2.5.0 de FormCreator. Pouvez-vous tester avec GLPI 9.1.2 ou supérieur ? Profitez-en pour considérer un upgrade de votre GLPI i vous voulez profiter des prochains bugfixes et des prochaines features.

**Comment by philippeplatiau** [comment]
Merci pour votre réponse rapide... 
Oui, c'était ma question suivante, la migration vers la dernière version et voir si le comportement était toujours là. 
J'ai quelques soupçons quant à la DB. Peut-être qu'elle est corrompue... Avant, il me semble qu'il y avait une faute de frappe dans le nom des tables et que cela avait changé par la suite (j'ai dû adapter mes scripts également car je me sers aussi des formulaires pour envoyer des SMS avec un GSM connecté sur le serveur et le script en php ne trouvait plus la table "formanwers") 

Je vous tiens au courant (ce ne sera pas tout de suite, je dois d'abord tester les autres plugins et voir s'ils existent tous pour GLPI 9.1.2 ou supérieur.)

Merci et bon weekend !

**Comment by philippeplatiau** [comment]
Bonsoir, 

Comme promis, je vous tiens au courant et c'est effectivement une bonne nouvelle. Je viens de passer de la version 0.90.5 vers la 9.1.3 avec mise-à-jour de tous les autres plugins et tout fonctionne correctement. Mon problème de notifications semble résolu puisque lorsque je vérifie dans le "mail.log", il envoie correctement vers les personnes prévues dans le ticket lors de sa création après soumission du formulaire. 

Merci pour votre support et je vous souhaite une excellente continuation ! 

Philippe

**Comment by btry** [comment]
Bonsoir 

Merci pour votre retour; on peut donc fermer ce ticket.
