### ISSUE TITLE
Problem with select field into generated ticket

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/formcreator#618]
Use select field with values by example admin & Direction.

The ticket don't display the selected value.

into inc/fields/select-field.class.php
```
 public function getAnswer()
   {
      $values = $this->getAvailableValues();
      $value  = $this->getValue();
      return in_array(Html::entities_deep($value), $values) ? $value : $this->fields['default_values'];
   }
```
```
$values = Array
  (
      [0] => admin &gt; Direction
)
$value = admin &gt; Direction
```
so the test Html::entities_deep($value), $values) cannot work

**Comment by amma35** [comment]
It seems to me that we should use "plugin_formcreator_encode" instead of "Html::entities_deep"

**Comment by btry** [comment]
Hi

I prefer an other solution: plugin_formcreator_encode() is a method I wish to completely remove because I think its content is ugly.

**Comment by btry** [comment]
hi

I can reproduce in 2.4.2. However I don't reproduce in the develop branch.
