### ISSUE TITLE
[UPGRADE] Erreur lors de l'installation de la version 2.5.0

### ISSUE THREAD

**Issue by TarekDB7** [pluginsGLPI/formcreator#620]
Bonjour,

J'ai tenté d'installer la version 2.5.0 de Formcreator et j'obtiens l'erreur suivante : 

Upgrade glpi_plugin_formcreator_targetchanges (1 seconde)

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/glpi/plugins/formcreator/inc/targetchange.class.php on line 41

**Comment by btry** [comment]
Bonjour

Je viens de vérifier le fichier inc/targetchange.class.php et de le solliciter en créant une destination de type **Changment** sur un formulaire. Tout va bien.

Comment avez vous téléchargé le plugin ?

**Comment by btry** [comment]
vous pouvez aussi comparer la ligne 41 de vitre fichier avec le code https://github.com/pluginsGLPI/formcreator/blob/2.5.0/inc/targetchange.class.php

**Comment by TarekDB7** [comment]
Je l'ai téléchargé à partir du lien suivant en mode graphique : 

https://github.com/pluginsGLPI/formcreator/releases/download/2.5.0/glpi-formcreator-2.5.0.tar.bz2

Puis j'ai effectué un scp du fichier tar.bz2 depuis ma machine vers le serveur de test.

**Comment by btry** [comment]
J'ai pris l'archive, et l'ai installée. J'ai créé un formulaire à l'identique que précédement, et ça fonctionne toujours.

Avez vous comparé le fichier avec ce qui est sur github ? (lien ci dessus)

**Comment by TarekDB7** [comment]
La ligne est exactement la même.

**Comment by btry** [comment]
Et les quelques lignes avant ?

Essayez tout de même de ré-uploader le fichier, quelque chose a dû le corrompre; je ne vois que ça pour le moment.

**Comment by TarekDB7** [comment]
Quelle méthode de décompression avez-vous utilisé ?

J'ai utilisé la commande tar xfvj.

**Comment by btry** [comment]
j'ai utilisé tar xf <fichier.tar.bz2> . Votre commande doit faire exactement la même chose.

**Comment by TarekDB7** [comment]
Je retrouve désormais la même erreur lorsque je veux effectuer un backup sur la version 2.4.2.

**Comment by btry** [comment]
J'aurais dû y penser plus tôt: c'est certainement votre version de PHP qui est trop ancienne. Qulle version avez-vous ?

**Comment by TarekDB7** [comment]
php 5.4

**Comment by btry** [comment]
C'est effectivement trop ancien.

Supprimez le plugin FormCreator dans glpi/plugins, et restaurez la version précédente. Cela vous permettra de faire votre backup si vous utilisez la fonction de GLPI. 

Ensuite, considérez l'upgrade de votre PHP, et et finalement vous pourrez upgrader le plugin.

Je vais ajouter une vérification de la version de PHP en 2.5.1.

**Comment by btry** [comment]
Pour information, GLPI 9.1.3 requiert PHP 5.6: Utiliser une version plus ancienne vous expose potentiellement à des bugs.

**Comment by Nexoz** [comment]
Bonjour,

J'ai aussi la même erreur lors de l'installation du plugin.
Cependant, je ne peux pas mettre à jour de manière officielle la version de PHP, vu la distribution que j'utilise sur mon serveur de production (CentOS 7.3.1611).
Or dans le README de la version 9.1.3 de GLPI, il est spécifié que la version requise de PHP est la 5.4 ou au dessus.
Êtes-vous sûr qu'il est donc nécessaire d'avoir la version 5.6 de PHP pour cette version de GLPI ?

Cordialement.

**Comment by btry** [comment]
Je vais vérifier pour la version minimale de GLPI. 

le code fautif dans le plugin est l'expression MaClasse::class . Ca ne fonctionne qu'à partir de PHP 5.5.

Si effectivement GLPI 9.1.x requiert PHP 5.4 je devrai changer la syntaxe. Si il requiert PHP 5.5, il serait préférable pour vous d'upgrader. Je vais faire un patch pour vous débloquer, et selon les retours sur GLPI, je fusionnerai ou pas avec la  version 2.5.1

**Comment by TarekDB7** [comment]
Je testerai demain avec une version PHP en 5.6.

**Comment by btry** [comment]
Voilà une version qui doit rétablir la compatibilité avec PHP 5.4

https://github.com/btry/formcreator/tree/feature/php_5_4_compatibility

**Comment by Teva86** [comment]
Bonjour,
Comment utiliser votre fix pour la version 5.4 ?
Merci d'avance
Cordialement

**Comment by btry** [comment]
Bonjour

Un moyen simple est de télécharger les fichiers **inc/targetchange.class.php** et **inc/targetticket.class.php** en mode brut (raw)  à partir des URL suivantes et de les installer à la palce des fichiers de même nom. dans le dossier du plugin.

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/targetchange.class.php

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/targetticket.class.php

**Comment by Teva86** [comment]
Merci ça marche nickel ! :)

**Comment by btry** [comment]
Bonjour

GLPI 9.1 est comaptible jusqu'à PHP 5.4. Donc je vais intégrer les correctifs.

**Comment by btry** [comment]
Bonjour

Je viens de releaser la version 2.5.1 destinée à rétablir la compatibilité avec PHP 5.4
