### ISSUE TITLE
Version 2.5.0 - Impression des formulaires

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#621]
Bonjour,
J'ai procédé à l'installation de la dernière version 2.5.0 en partant de  zéro sur une mise à jour de GLPI en 9.1.3 depuis une 9.1.1
Je n'ai rencontré aucun problème à l'installation et toutes les fonctionnalités que j'utilisais semblent fonctionner.
Seul soucis rencontré pour l'instant : l'impression de formulaires.
J'ai testé avec chrome et firefox, l'impression directe et l'enregistrement en PDF, j'obtiens une page vide la plupart du temps et parfois juste la réponse à une ou 2 questions.
Je continue mes tests, en touts cas, merci pour tout ce travail.
Bonne journée

**Comment by btry** [comment]
Bonjour

Votre problème est aléatoire avec une seule réponse à une formulaire ou cela dépend des réponses que vous voulez imprimer ?

De plus, il y a peut être des informations utiles dans glpi/files/_log/*-errors.php. Si il y a des erreurs en lien avec ce problème, merci de les partager.

**Comment by eckorion** [comment]
Non, c'est suivant que j'imprime lors de la saisie du formulaire ou lorsque le formulaire est enregistré.
En pièces jointes les documents correspondants aux deux cas.
Sur la saisie, on voit en haut à gauche la donnée qui figure normalement sur le champs "centre de responsabilité budgétaire". De plus les cases "radio" sont vides alors qu'elles sont cochées sur le formulaire.
Aucune erreur dans les log.
[GLPI - Formcreator - enregistré.pdf](https://github.com/pluginsGLPI/formcreator/files/1071336/GLPI.-.Formcreator.-.enregistre.pdf)
[GLPI - Formcreator - saisie.pdf](https://github.com/pluginsGLPI/formcreator/files/1071337/GLPI.-.Formcreator.-.saisie.pdf)

**Comment by eckorion** [comment]
De plus l'impression en mode prévisualisation lors de la construction du formulaire renvoie une page blanche s'il n'y a pas de saisie, si on saisi plusieurs élément, un seul champs apparaît en haut à gauche sans rien d'autre.
[GLPI - Formulaires - prévisualisation.pdf](https://github.com/pluginsGLPI/formcreator/files/1071370/GLPI.-.Formulaires.-.previsualisation.pdf)

**Comment by satyan01** [comment]
Bonjour

Meme resultat pour moi

**Comment by Erdnax** [comment]
Boujour,
C'est pareil pour moi aussi ...
J'ai regardé aux niveaux des .css mais rien de plus ...

**Comment by popoix** [comment]
Bonjour,

même problème, rien ne s'affiche, peut importe le formulaire.
 Je n'ai rien trouvé dans les logs php.

**Comment by btry** [comment]
Hi I switch to english for the user who opened #634 

Please try the fix in #646 and feedback

**Comment by grego1981** [comment]
Tried the fix, it prints the page but on the startof the page on the backgrounf I get a list of all the users.

**Comment by btry** [comment]
Can you tell me all fields types you have on your form ?

**Comment by grego1981** [comment]
I have text, date, select, checkboxes and textarea

**Comment by btry** [comment]
I updated the fix : forms printing and answers printing needs different process.

I also removed floating things in top left corner. I think it should solve your problem.

Please test it and feedback.

**Comment by grego1981** [comment]
For me it works just fine!

**Comment by btry** [comment]
Thank you, I'll merge this for 2.5.2

**Comment by popoix** [comment]
It works for me too!

**Comment by btry** [comment]
merged, waiting to the new release now. Thanks for your feedbacks.

**Comment by eckorion** [comment]
Hi, I tried the fix, it's much better but I find 2 little problem in preview mode when you're building a form.
When I print, I don't see if the radio buttons are checked.
And the "select" fields are empty.
Except that, the over kind of fields seem to be ok.

**Comment by btry** [comment]
then we need a new ticket for that. It is a slightly different problem. 

By the way , I'm not sure yet we should display the ticks: it depends if you want to print the forms to fill them on paper, if this is only for preview and discuss the design with other persons.

**Comment by eckorion** [comment]
No, I don't need, but as I noticed, I made you a feedback, actually, everything I need is working fine.
Thanx

**Comment by btry** [comment]
OK, I'll open a ticket myself to think about this later.
