### ISSUE TITLE
display descripton on homepages

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#623]
Can i display forms description on homepage ?

We use this setting "Direct access on homepage". We want to see also the description.
We use entity setting GLPI Helpdesk.

**Comment by btry** [comment]
Hi 

You should have a display similar to this
![image](https://user-images.githubusercontent.com/14139801/27093387-c2c7bc5a-5066-11e7-94cd-ceb19477be57.png)

click the **+** on the left of the titles
![image](https://user-images.githubusercontent.com/14139801/27093380-bbc64782-5066-11e7-8557-67d4d37e04f6.png)

In this screenshot only one form has a description.

**Comment by Armin83** [comment]
ohh, i did not see it. Can i expand by default ? (I think not but perhaps it is possible.)

**Comment by btry** [comment]
There is no feature to expand them by default. You may consider using the service catalog instead: forms are displayed with their description.

**Comment by Armin83** [comment]
thanks for fast answer
