### ISSUE TITLE
Ticket category - Answer is name and not ID

### ISSUE THREAD

**Issue by Teva86** [pluginsGLPI/formcreator#626]
Hi,
I've installed the version 2.5.0 and it is great to now be able to list the categories directly in the form.
Thanks for this enhancement !

One question tough : 
As we can use the answer of this question in the title or description of the ticket, can the answer be the name of the category instead of the ID ?

Regards

**Comment by btry** [comment]
Hi

This is a useful improvement.

**Comment by btry** [comment]
Hi

A category is now resolved as its name, not its ID. This issue can be closed.
