### ISSUE TITLE
Version 2.5.0 - Problèmes de compatibilité avec PHP 5.4

### ISSUE THREAD

**Issue by Nexoz** [pluginsGLPI/formcreator#627]
Bonjour,

En plus de ce qui est référencé dans l'Issue #620, j'ai trouvé des erreurs liées à la version 5.4 de PHP dans la méthode `showForForm` de la classe FormAnswer.
En effet  `$item = new Self;` à la ligne 247 est inconnu, et la méthode `array_filter` ne prend qu'un troisième paramètre qu'à partir de la version 5.6.

Cordialement.

**Comment by btry** [comment]
Merci pour ce retour. Je complète la branche https://github.com/btry/formcreator/tree/feature/php_5_4_compatibility

Il faut donc mettre à jour 

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/targetchange.class.php

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/targetticket.class.php

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/form_answer.class.php

**Comment by btry** [comment]
Bonjour 

Je viens de releaser la version 2.5.1 destinée à rétablir la comaptibilité avec PHP 5.4.
