### ISSUE TITLE
actors inserts id instead of name

### ISSUE THREAD

**Issue by magheinz** [pluginsGLPI/formcreator#631]
before my last "git pull" formcreater inserted username in fields with type actor.
Now it iserts the userids.

is this a bug or a feature?

**Comment by btry** [comment]
Hi

This is a bug.

**Comment by flagan06** [comment]
I suppose this is the same issue with ticket category, priority, and observer : 
Here is what I get in my ticket description using tags : 
"Catégorie ticket	3
Urgence	4
Observateur (facultatif)	,2921
Description (facultatif)	zazazazaza"

**Comment by btry** [comment]
@flagan06 
You're right.

**Comment by msizec** [comment]
Have the same problem here

**Comment by btry** [comment]
Hi

Please can you try this fix and feedback ? (thank you @flegastelois for taking time to find a fix)

https://github.com/pluginsGLPI/formcreator/pull/643/files

**Comment by flagan06** [comment]
yes, it works fine for me. Thanks

**Comment by btry** [comment]
@magheinz and @msizec, is this fix ok for you too ?

**Comment by flagan06** [comment]
There is an issue, I am trying to get the ticket category as title for the ticket.
But I hide it in the form (I set a default value, and hide it). First it works fine, but then when I change the default value of the category, I dont have the ticket category in the title anymore but my form description.
It looks like the tag numbers are shiffted (+1) in the form destination.
Trying to be clear, but not sure I am ... Let me know  if you need more explanation...

**Comment by btry** [comment]
@flagan06 this is a different issue. Please open a new ticket.

**Comment by btry** [comment]
Missing feedback from 2 users; closing as it worked at least for me and one user.

**Comment by magheinz** [comment]
sorry for my late reply,

i can't test it at the moment, i changed my script an inserted a subroutine to resolve the name via api.

**Comment by btry** [comment]
Hi

I'm confident the fix will work for you. When  you have time to test it, if you see it does not work for you, just feedback here and I'll repoen the issue. By the way, notice I already merged it.

**Comment by nqb** [comment]
Fix works (tested in 9.1.5). I have try with three GLPI objects : 
- computers
- networks devices
- users

In each case, I get name in place of ID.

**Comment by btry** [comment]
Thank you for your feedback :+1:
