### ISSUE TITLE
Observer not added to the destination ticket (2.5)

### ISSUE THREAD

**Issue by flagan06** [pluginsGLPI/formcreator#632]
Hi,
I added a watcher (actor from a form question) to the destination ticket but it is not working.
Do you have the same problem ?
Thanks.

**Comment by msizec** [comment]
I have the same problem. I don't see the watchers in the created ticket.

This is the configuration of the destination : 
![image](https://user-images.githubusercontent.com/29256398/27373085-2af08ed2-5667-11e7-8f19-397722b44f6c.png)

The ticket gabarit used in this destination is correctly set, observers are not masked.

This is what the ticket looks like : 
![image](https://user-images.githubusercontent.com/29256398/27373367-4ce60606-5668-11e7-9719-8892ce529ec2.png)

**Comment by btry** [comment]
Do you use the plugin Behaviors ? If yes, do this plugin adds the missing observers ?

**Comment by msizec** [comment]
Yes !

So I do have to add it in the notification for ticket creation ?

 



  _____  


Description : C:\Users\ms\AppData\Roaming\Microsoft\Signatures\signature_fichiers\logo_petit_maximo.png

Mathieu Sizec 
Responsable bureautique 
Tél : 03.26.79.33.36 - Fax : 03.26.79.32.99 
Mail : mathieu.sizec@maximo.fr 

MAXIMO - ZA Parc du Château - 51500 TAISSY 
 <http://www.maximo.fr/> www.maximo.fr 




  _____  



Avant d’imprimer cet email, réfléchissez à l’impact sur l’environnement. 

Description : C:\Users\ms\AppData\Roaming\Microsoft\Signatures\signature_fichiers\tree.jpg

 

 

De : btry [mailto:notifications@github.com] 
Envoyé : mercredi 21 juin 2017 10:07
À : pluginsGLPI/formcreator
Cc : msizec; Comment
Objet : Re: [pluginsGLPI/formcreator] Observer not added to the destination ticket (2.5) (#632)

 

Do you use the plugin Behaviors ? If yes, do this plugin adds the missing observers ?

**Comment by btry** [comment]
It seems the Formcreator and Behavior don't work well together (see #629). Can you disable Behaviors and see if observers are correctly added ?

**Comment by msizec** [comment]
Ok it works !

 

Are you French ?

 



  _____  


Description : C:\Users\ms\AppData\Roaming\Microsoft\Signatures\signature_fichiers\logo_petit_maximo.png

Mathieu Sizec 
Responsable bureautique 
Tél : 03.26.79.33.36 - Fax : 03.26.79.32.99 
Mail : mathieu.sizec@maximo.fr 

MAXIMO - ZA Parc du Château - 51500 TAISSY 
 <http://www.maximo.fr/> www.maximo.fr 




  _____  



Avant d’imprimer cet email, réfléchissez à l’impact sur l’environnement. 

Description : C:\Users\ms\AppData\Roaming\Microsoft\Signatures\signature_fichiers\tree.jpg

 

 

De : btry [mailto:notifications@github.com] 
Envoyé : mercredi 21 juin 2017 10:07
À : pluginsGLPI/formcreator
Cc : msizec; Comment
Objet : Re: [pluginsGLPI/formcreator] Observer not added to the destination ticket (2.5) (#632)

 

Do you use the plugin Behaviors ? If yes, do this plugin adds the missing observers ?

**Comment by btry** [comment]
yes I'm french

**Comment by msizec** [comment]
Ok, donc j'ai ajouté manuellement 'observateur' dans les destinataires de ma notification 'creation de ticket' ... il n'y était pas avant.
Behaviors permet d'y avoir accès mais on ne l'avais jamais configuré ... my bad

**Comment by btry** [comment]
OK, then for you this is a  configiration problem in your notifications.

@flagan06 : can you check also the settings of your notification ?

**Comment by flagan06** [comment]
The problem is not at the notification level (yet), but at the ticket creation, I have no observer added to the ticket, I amnot using behavour plugin... I don't get it... Do I need to do something with the ticket template ?

**Comment by btry** [comment]
@flagan06 : You don't need to use a ticket template. If you add observers in the target, it is expected you find them in the generated ticket.

**Comment by flagan06** [comment]
Ok, merci, thanks

**Comment by btry** [comment]
Hi @flagan06 

I'm trying to reproduce your issue, without success with the development version

Can you tell me which version of FormCreator you're using, and if it is 2.5.0 or later, export your form in JSON and send it to me ?

**Comment by btry** [comment]
Hi

No feedback then I close. If  the issue persists with the version 2.6.0 or later, please open a new issue.
