### ISSUE TITLE
Blank page when using printing

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#634]
Hello I have upgraded to the latest version, 2.5.1 using glpi 9.1.4. I can no longer print the forms, when pressing the printer icon I get a blank page on preview and on printer instead of the form.

**Comment by btry** [comment]
Hi

This usse was found starting from 2.5.0. I'll try to fix it in 2.5.2

**Comment by grego1981** [comment]
Thank you! I don't know if it helps, but when trying it from firefox I get a page with all the users... while from chrome I get the blank page

**Comment by btry** [comment]
As this issue duplicates #621 I close this one. Please follow #621, try the fix I submitted here, and feedback.
