### ISSUE TITLE
Bugs liés à la validation d'un formulaire par un Groupe

### ISSUE THREAD

**Issue by Nexoz** [pluginsGLPI/formcreator#635]
Bonjour,

Je possède un formulaire Test DAA comme suivant :
![formulairedaa](https://user-images.githubusercontent.com/16245319/27334420-8dac60f8-55c9-11e7-8993-d496eb8fdfaa.png)

Il est soumis à la validation d'un groupe, Validation DAA auquel j'appartient. Sur ma vue globale des formulaires, ils apparaissent bien en tant que formulaire que je peux valider : 
![derniersformsvalideurs](https://user-images.githubusercontent.com/16245319/27334489-c21b399a-55c9-11e7-9a68-2834df2b2e73.png)

Mais cependant lors que je clique sur "Tous mes formulaires (Valideurs)", j'obtiens aucun élément : 
![tousmesformsvalideurs](https://user-images.githubusercontent.com/16245319/27334541-e82d8d04-55c9-11e7-8a5e-077e298473dd.png)
Peut-être est-ce que au fait que le filtre se fait par rapport à mon nom, et non pas à mes groupes.

De plus, lorsque je supprime ce filtre, le nom du Validateur est erroné : 
![screenformulaires](https://user-images.githubusercontent.com/16245319/27334612-26d875b4-55ca-11e7-8849-533421b78553.png)
L'utilisateur Frank est ici affiché car l'id de cet utilisateur est le même que celui de mon groupe (78).

J'utilise la version 2.5.1 du plugin avec GLPI 9.1.3.

Merci pour tout votre travail sur ce plugin.

**Comment by btry** [comment]
Bonjour

Je pense qu'il faut repenser le plugin sur cette partie. Cela va passer par un changement de schéma, ce qui impose une planification pour la version 2.6.0

**Comment by btry** [comment]
Bonjour
Si vous en avez la possibilité, vous pouvez tester ce correctif sur un environnement de test (le plugin passera en v2.6.0-dev).

#657
