### ISSUE TITLE
HTML en RichText : format perdu

### ISSUE THREAD

**Issue by nicolas62** [pluginsGLPI/formcreator#636]
Bonjour à tous,

Je m'explique, je viens d'installer Formcreator 2.5.1 sur GLPI 9.1.2.
J'ai un problème lors de la génération de ticket depuis un formulaire ayant un champ Zone de Texte.
Le formatage HTML disparait et l'affichage est en texte brut.

Le format texte enrichit est pourtant bien activé.

Avez-vous une solution ?

**Comment by btry** [comment]
Bonjour

La cause est dans le plugin, la fonction **plugin_formcreator_encode**, qui purifie le texte avant sauvegarde en BDD.

Il faut que j'améliore l'implémentation de tous les types de questions pour faire cela convenablement.

**Comment by btry** [comment]
Bonjour

Quelques changements ont eu lieu dans la future version 2.6.0. Il est possible qu'ils contribuent à résoudre votre bug. Pouvez-vous réessayer ? (Il faut GLPI 9.2 avec à partir  de 2.6.0)

**Comment by nicolas62** [comment]
Bonjour

Je vais faire le test dès que possible et vous ferez un retour.

**Comment by nicolas62** [comment]
Bonjour,

Je viens de tester, et la mise en page lors de la complétion d'un champ texte est bien conservé à la création d'un ticket.

Ce bug est donc pour moi corrigé en version 2.6.0 dev.

Merci beaucoup.

**Comment by btry** [comment]
Bonjour

Merci pour votre retour.
