### ISSUE TITLE
Value 0 after reopen and accept already rejected form

### ISSUE THREAD

**Issue by flo1994** [pluginsGLPI/formcreator#637]
A form is rejected.
Shortly after, this form will be sent again for review.
Now the form is approved.

The value in the fields with the "Checkbox" type now has the value 0.

I think this is a bug.
![glpi](https://user-images.githubusercontent.com/20795317/27339669-ae9e1f22-55d8-11e7-9c9e-d4c7fd1c0c65.JPG)

**Comment by btry** [comment]
Hi

I reproduce and found a fix (see#653)

Please test it and feedback.

**Comment by flo1994** [comment]
That fix works for me!

**Comment by btry** [comment]
Nice ! Thank you for your feedback

**Comment by btry** [comment]
fix merged into develop
