### ISSUE TITLE
Formulaire n'apparait plus sur page d'acceuil

### ISSUE THREAD

**Issue by ChristopheG77** [pluginsGLPI/formcreator#644]
Bonjour

Depuis la dernière maj du plugin mes formulaires on disparu de la page d’accueil alors que ceux ci sont bien paramétré pour s'y afficher
Je suis sous GLPI 9.1.4 + Formulaire 2.5.1
Merci de votre aide

**Comment by ChristopheG77** [comment]
Je rencontre ce problème sur les 2 interfaces

**Comment by btry** [comment]
Bonjour

Rafraichissez le cache de votre navigateur avec Ctrl+F5 ou Ctrl+MAJ+R selon votre navigateur.

Si cela ne fonctionne pas, voyez si il y a des erreurs PHP dans php-errors.log et sql-errors.log. Enfin, cherchez une éventuelle erreur fatale dans les logs de votre serveur HTTP.

**Comment by ChristopheG77** [comment]
J'ai essayé, rien n'y fait
J'ai vérifié tous mes fichiers Logs et aucune erreur

**Comment by btry** [comment]
Bonjour

La régression a eu lieu avec la release 2.5.0.

Voilà le correctif: https://github.com/pluginsGLPI/formcreator/pull/659

**Comment by btry** [comment]
Bonjour

A défaut de retour, je ferme le ticket. Si le problème persiste, demandez sa réouverture.

**Comment by ChristopheG77** [comment]
Ok pas de souci
