### ISSUE TITLE
Ticket category / tags in destination

### ISSUE THREAD

**Issue by flagan06** [pluginsGLPI/formcreator#645]
There is an issue, I am trying to get the ticket category as title for the ticket.
But I hide it in the form (I set a default value, and hide it). First it works fine, but then when I change the default value of the category, I dont have the ticket category in the title anymore but my form description.
It looks like the tag numbers are shiffted (+1) in the form destination.
Trying to be clear, but not sure I am ... Let me know if you need more explanation...

**Comment by btry** [comment]
Hi

When a field is hidden it is not evaluated to populate placeholders in the destinations.

If the field is hidden and has a default value, why not write the category directly in the title of the destination ticket ?

![image](https://user-images.githubusercontent.com/14139801/28324662-35f51016-6bdc-11e7-8a46-5889ef5480e0.png)

**Comment by btry** [comment]
Hi

No answer to my proposal; then I close.
