### ISSUE TITLE
[BUG] Notifs bloquées en file d'attente

### ISSUE THREAD

**Issue by JulienG78** [pluginsGLPI/formcreator#649]
Bonjour,

Je rencontre un problème avec les notifications mails issues du plugin FormCreator.

Après avoir créé un formulaire celui-ci envoi une notification mail pour la création et la demande de validation du formulaire.

Sauf que les mails restent bloqués dans la file d'attente GLPI et ne partent jamais sauf si je lance manuellement la tache queuedmail.
Cette anomalie ne se produit qu'avec les notifications du plugin formcreator, pour les tickets et autres les mails partent bien en accord avec ma crontask et ma tache queuedmail configuré en CLI.

Sur le mail.log de glpi je vois bien la mise en attente des notifications formcreator mais elles ne partent pas. Dans le fichier log cron.log je vois les exécutions de la tache mais ne fait pas partir mes notifications.

J'ai pourtant vérifié les différentes notifications de formulaires, elles sont bien activées, avec notification courriel, configuré comme par défaut, mais ça ne part pas, que ce soit avec la dernière version de formcreator ou celles d'avant ça ne part pas.

Auriez-vous une idée ?

Merci par avance,

PS, voici des screenshots de mon mail.log et cron.log
![26-06-2017 13-49-38](https://user-images.githubusercontent.com/24435635/27538074-ad610da2-5a76-11e7-8cca-65a100195c0b.png)
![26-06-2017 13-51-21](https://user-images.githubusercontent.com/24435635/27538073-ad211f80-5a76-11e7-942a-574d398a1d0c.png)

**Comment by btry** [comment]
Bonjour

Du moment que FormCReator a généré les mails et qu'ils sont déposés dans QueuedMail, sa part de travail est faite. 

Je pense qu'il y a quelque chose de mal configuré dans votre GLPI. 

Votre extrait de mail.log est un peu court pour me faire une idée; mais est ce que les mails retenus en file d'attente ne seraient pas exclusivement ceux propres au plugin (messages de formulaire en attente de validation, formulaire sauvegardé, formulaire validé...) ?

**Comment by JulienG78** [comment]
Oui ce ne sont que ces mails qui restent bloqués.
Comme expliqué plus haut tous les autres mails venant de tickets, changement, etc... partent correctement.

Seuls les mails du plugin restent bloqués en file d'attente.

**Comment by btry** [comment]
Pouvez-vous préciser la version de GLPI et du plugin ?

**Comment by JulienG78** [comment]
Bonjour,

Je suis en 9.1.4 et plugin 2.5.1.
parcontre bizarrement depuis hier soir les notifications partent.

Je ne comprends pas car je n'ai rien fait et ça ne fonctionnait plus depuis des semaines :(
Ca s'est résolu tout seul on dirait.

Du coup désolé vous pouvez cloturer le ticket ^^

Bonne journée

**Comment by btry** [comment]
Bonjour

Merci pour ce retour. 

Cela dit, votre souci m'a paru très étrange, ce serait intéressant de regarder dans les logs de votre serveur mail, ou peut être la table glpi_queuedmails si il y a des traces d'échec d'envoi.
