### ISSUE TITLE
Multiple valeur dans "Affichage du champ"

### ISSUE THREAD

**Issue by bdrayer** [pluginsGLPI/formcreator#655]
Bonjour, lorsque l'on crée une règle d'affichage du champ je n'ai pas trouvé comment mettre plusieurs valeur.

Pour exemple je désire proposer un champ en fonction du département. Si le champ département est "Direction" ou "Finance", je voudrais afficher ce champ, sinon pas. Avec soit l'un, soit l'autre ça fonctionne très bien mais par contre je n'ai pas trouvé le séparateur qui permet d'en prendre 2 en compte.

si ce n'est pas possible, il serait peut-être intéressant de mettre en place un système de règle plus complexe ou il est possible de mettre plusieurs règles différentes

Merci encore pour ce plugin

**Comment by btry** [comment]
Bonjour 

Quelle  version du plugin ?

**Comment by bdrayer** [comment]
2.4.2

**Comment by bdrayer** [comment]
J'avais pas vu qu'il y'avait pleins de mises à jour depuis que je l'ai installé il y'a un mois :-)

**Comment by bdrayer** [comment]
C'est parfait avec la dernière version :-) Merci bien
