### ISSUE TITLE
Targets: Location (enhancement)

### ISSUE THREAD

**Issue by supraman7m89** [pluginsGLPI/formcreator#656]
First of all, I want to say I love the FormCreator plugin!

The one thing I use it for that I cannot target is the location. The latest rev added the ticket category which has pretty much gotten rid of the need for the ticket template. 

Like due date, if you could add Location equals the answer to the question.  Mostly everything else I can see can be accomplished with business rules and templates. 

Thanks for the consideration!

**Comment by btry** [comment]
Hi

I'll add the ability to set the location like we already do for categories in version 2.6.0

**Comment by iPaulis** [comment]
Hi, first of all thanks for developing this plugin, it is incredibly handy.
Regarding enhancements in the Target section, I would like to ask if it is possible to add the "Opening Date equals to the answer", the same way that we have Due Date now. 
Right now the Opening Date of the ticket is the moment when the ticket is created, which is the same as the form is saved. It would be very helpful for my workflow if I could set it up equal to an answer, so I could set a future or past Opening Date if I need to.

Thank you in advance.

**Comment by btry** [comment]
Hi 

The feature is in the version 2.6.0 (in development). Please try it and feedback. This version requires GLPI 9.2.

**Comment by btry** [comment]
Release candidate 1 of Formcreator 2.6.0 is published. The feature is included, so I close. Now time to hunt the remaining bugs.
