### ISSUE TITLE
GLPI object does not contains genericobject

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/formcreator#660]
Hello,

We have notice a bug to link objects created by genericobject when selecting `Type : GLPI object`
in a question with GLPI 9.1.4 and FormCreator 2.5.1. Generic objects are not present under `Assets`.

However, if you choose `Type : Dropdown`, you have a section called `Objects Management` with all generic dropdowns listed. 

This behavior is incoherent.

Steps to reproduce : 
- Install genericobject plugin (version 2.4.0)
- Create a new type of object with new fields
- Create objects (based on new type of object) in Assets
- Create a form with a question that use `Type : GLPI Object`
- Try to find your new type of object in `GLPI Object`

=> You can't find it.

**Comment by btry** [comment]
Generic Object ne popule pas systématiquement $CFG_GLPI['asset_types']. Cela dépend des comportments des itemtypes de la page suivante 

![image](https://user-images.githubusercontent.com/14139801/28323268-90933e34-6bd8-11e7-9b8f-1a1e755479eb.png)

LEs itemtypes de G eenric Object est disponible dans $_SESSION['glpimenu']['asset']['content'] mais les itemtypes sont listés en minuscules, ce qui pose problème lors de la génération de tickets (conversion itemtype name => table name sensible à la casse).

Ce ticket a besoin de plus d'investigation, très probablement un développement côté Generic Object.

**Comment by nqb** [comment]
Thanks for your feedback @btry. Could you open an issue on genericobject project ?

**Comment by LordBat** [comment]
Hi! Any update about this?  thanks!

**Comment by btry** [comment]
Hi

No news yet. I began to investigate myself on both plugins, but I'm lacking time to continue this task for now.

**Comment by nqb** [comment]
@cedric-anne : do you plan to work on this feature soon ? I see you are working on pluginsGLPI/genericobject

**Comment by cedric-anne** [comment]
@nqb I do not know when I will be able to work on this issue.

**Comment by mohierf** [comment]
👍

**Comment by btry** [comment]
Hi

Feature implemented in Formcreator 2.11.4, requires Generic Objects 2.11.0

**Comment by nqb** [comment]
🍾 

Thanks for your work!  

@dvinouze and @ASLLR will be happy.
