### ISSUE TITLE
drop down loading failed

### ISSUE THREAD

**Issue by krutikakombe** [pluginsGLPI/formcreator#661]
Hi,
Expected: When I select any value from drop down, then it should open another drop down field. On loading value in parent drop down, child drop down should appear.
Actual: Now, when I am selecting value in parent drop down, it is successfully selecting correct value but not loading child drop down.
After selecting value in parent drop down:![image](https://user-images.githubusercontent.com/29305067/27906194-2f498286-6260-11e7-9c91-af1ad06b4996.png)
Before selecting value:
![image](https://user-images.githubusercontent.com/29305067/27906222-4c7345ae-6260-11e7-82fa-450fa17dc831.png)

My code:
`Utility.SelectDropdown(driver, "//div[3]/div/div/select", "CMT Desigo CC");
		Utility.SelectDropdown(driver, "//div[2]/div/div/div[3]/div/div/select", "Hardware");`
Could anyone suggest me correct way of doing this.
Thanks.

**Comment by btry** [comment]
Hi

Question, is this issue related to Formcreator plugin for GLPI ? The UI seems different.

**Comment by btry** [comment]
No feedback. Closing.
