### ISSUE TITLE
multiple file uploads with a single file field type

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#662]
We need to allow users to upload several files without creating several file questions. This way, we ensure the user does not reach a limit, for example he wants to upload 4 files but there are only 3 file questions.

**Comment by kedson42** [comment]
Hello!
Is there any update on this?

We need to use one question to upload more than one file, the same way we can do using the File field that comes with native on GLPI.

**Comment by btry** [comment]
Hi 

No update on this issue yet. This is a community request and community issues are processed at best effort.

If you want to speedup development of this feature, contact us at contact@teclib.com

**Comment by kedson42** [comment]
Ah okay.

We'll try to ajust here and update the code for approval. If you're willing to give any basic instruction on what needs to be adjusted, we'll be very grateful.

Thanks

**Comment by btry** [comment]
You're welcome to contribute. I don't have in mind the requirements to complete this feature, but I think reading the code in GLPI where you observe the wanted behaviour will be useful.

This issue is a feature. This means you must target the next version of Formcreator. Use the current develop branch as a base for you contribution. 

Feel free to ask if you're stuck somewhere.

**Comment by kedson42** [comment]
Hi @btry , we've managed to develop this feature here.

Now the file field from formscreator gets multiple files and attach it to a ticket, also adding the files as a follow-up, the same way GLPI does natively.

We'll push the code in order to get your approval.
Thanks!

**Comment by btry** [comment]
Hi

Great. I'll plan to merge it in the 2.7.0 version.

Thank you for your contribution.

**Comment by lbteles** [comment]
Finally :)
https://github.com/pluginsGLPI/formcreator/pull/941

**Comment by kedson42** [comment]
Awesome! 
Thanks @btry for always helpnig the community.

@lbteles , é nóis.

**Comment by alyssontkd** [comment]
Great job, @lbteles !

I was in need of this functionality. Implemented here and it worked perfectly.

Thank you so much!

**Comment by btry** [comment]
@alyssontkd If you open a form answer with multiple files, can you show how  this is rendered ?

By reading the code, I think we may see only the last upload. I expect the PR still needs an improvement.

**Comment by kedson42** [comment]
Here how it works in our environment:

![image](https://user-images.githubusercontent.com/34751754/37767863-586ee456-2daa-11e8-922a-1d5b5d71b025.png)

![image](https://user-images.githubusercontent.com/34751754/37767886-687a00a6-2daa-11e8-9d12-2555b88ed938.png)

![image](https://user-images.githubusercontent.com/34751754/37767898-6e2baad6-2daa-11e8-8d41-2df1135a591c.png)

![image](https://user-images.githubusercontent.com/34751754/37767900-714d0f48-2daa-11e8-8d35-4591ad235081.png)

**Comment by btry** [comment]
well, it looks good. Maybe handle singular / plural and this PR will be ready. Thank you for your feedback

**Comment by lbteles** [comment]
@kedson42, tamo junto brother!

**Comment by btry** [comment]
Hi

Feature implemented, closing.
