### ISSUE TITLE
Error 500 when users send a forms

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/formcreator#663]
Hello,
Since we have update Formcreator to latest version, when a user send a forms, an error 500 is display.

BackTrace : 

  *** MySQL query error:
  SQL: SELECT q.`id`, q.`fieldtype`, q.`name`, a.`id` as answer_id
                FROM glpi_plugin_formcreator_questions q
                LEFT JOIN glpi_plugin_formcreator_sections s
                  ON s.`id` = q.`plugin_formcreator_sections_id`
                LEFT JOIN `glpi_plugin_formcreator_answers` AS a
                  ON a.`plugin_formcreator_formanwers_id` = -1
                  AND a.`plugin_formcreator_question_id` = q.`id`
                WHERE s.`plugin_formcreator_forms_id` = 2
  Error: Unknown column 'a.plugin_formcreator_formanwers_id' in 'on clause'
  Backtrace :
  plugins/formcreator/inc/formanswer.class.php:423
  plugins/formcreator/inc/form.class.php:978         PluginFormcreatorFormanswer->saveAnswers()
  plugins/formcreator/front/form.form.php:50         PluginFormcreatorForm->saveForm()

Formcreator Version 2.5.1
GLPI version 9.1.3

**Comment by btry** [comment]
Bonjour

Il doit y avoir un problème dans votre installation. Cela fait longtemps qu'il n'y a plus de fichier inc/formanswer.class.php. Il a été renommé en inc/form_answer.class.php (notez l'underscore).

J'ai l'impression que la version du code que vous utilisez n'est pas la 2.5.1 mais une version beaucoup plus ancienne.

Vérifiez votre installation par rapport à l'archive de la version 2.5.1 ou par rapport au tag v2.5.1 de ce dépôt.

**Comment by SylvainGuibert** [comment]
Hi,

You'r right. I had setup an old version instead of upgrade to 2.5.1...

Thanks for your help...

I Close this thread...
