### ISSUE TITLE
[2.5.1] + GLPI 9.1 requester can change filter in list view to see all forms

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#671]
requester can change filter in list view to see all forms. We use forms to organize payable requirements for our various profit centers. They should not see the requested or approved forms from other profit centers.

A single requester should only see its one requests.

**Comment by btry** [comment]
Hi

This is a bug. The plugin is designed to function as you expected, but is seems there is an issue in GLPI 9.1.x breaking this feature.

This is fixed in GLPI 9.2. 

I keep this issue for now. if the fix is backported, then I'll add the diff here for you.

**Comment by ladenree76000** [comment]
GLPI[9.1.6]+formcreator [2.5.2]
any user can see all tickets . 
tickets count on header also counts all tickets (it should count active user tickets)
 I dont know if it's the same issue
glpi/plugins/formcreator/front/issue.php?criteria[0][field]=4&criteria[0][searchtype]=equals&criteria[0][value]=notold&reset=reset

**Comment by btry** [comment]
Hi

Is the issue fixed with GLPI 9.2.0 and Formcreator 2.6.0, or GLPI 9.2.1 and Formcreator 2.6.1 ?

**Comment by btry** [comment]
Hi 

@ladenree76000 if you upgraded to GLPI 9.2.x, can you feedback about this issue ?

**Comment by ladenree76000** [comment]
glpi9.2.2(upgraded) + formcreator 2.6.2 (fresh install): 
user only sees his own tickets : OK

**Comment by btry** [comment]
Thank you ! Then I close.
