### ISSUE TITLE
création d'un menu sous GLPI

### ISSUE THREAD

**Issue by amartisara** [pluginsGLPI/formcreator#677]
bonsoir tout le monde est ce possible la création d'un menu et de ses sous menu sur GLPI si oui avec quel plugin on le  fait

**Comment by btry** [comment]
Bonjour

Si votre question ne concerne pas un bug ou une demande de fonctionnalité de formCreator, posez votre question sur le forum de GLPI, section dédiée aux plugins

http://forum.glpi-project.org/

Sinon, si il s'agit de créer des menus déroulants supplémentaires avec FormCreator, le plugin ne le permet pas pour le moment.
