### ISSUE TITLE
Liste formulaires saisis

### ISSUE THREAD

**Issue by popoix** [pluginsGLPI/formcreator#682]
Bonjour,

depuis la màj en 2.5.2 je n'ai plus la liste des formulaires saisis. J'ai bien le nombre de formulaires mais quand je clique sur l'onglet c'est blanc.

![formcreator_liste](https://user-images.githubusercontent.com/29449252/28772002-25d73eda-75e5-11e7-9641-644469dcb6a9.PNG)

**Comment by btry** [comment]
Bonjour

Vérifiez  les logs de votre serveur HTTP. Il y a probablement une erreur 500.

Vérifiez aussi php-errors.log et sql-errors.log; il pourrait y avoir des erreurs survenant avant le crash de l'onglet.

**Comment by btry** [comment]
Question, cela arrive t il avec tous vos formulaires? JE viens de tester avec un des miens et ça fonctionne.

**Comment by popoix** [comment]
En effet, cela se produit avec un formulaire en particulier. Je vais regarder dans les logs.

Merci

**Comment by btry** [comment]
Ne fermez pas le ticket; il y a probablement un bug dans les sources à corriger.

**Comment by popoix** [comment]
Je ne vois pas d'erreurs dans mes logs php et mysql. Ce qui est étrange, c'est qu'n passant par "linterface" utilisateur, (assistance > formulaires), quand je clique sur "tous mes formulaires" ils s'affichent bien, même quand je retire le filtre demandeur, je vois bien tous les formulaires remplis.

Je continue mes recherches.

**Comment by btry** [comment]
Vu la  capture d'écran vous avez certainement une erreur HTTP 500 au chargement de l'onglet.

Utilisez les outils développeur de votre navigateur, puis rendez vous sur le formulaire, et l'onglet en défaut. 

Les outils développeur vont historiser toutels les requêtes HTTP que vous emettez. A coup sûr vous en  verrez une avec le code 500. Ces erreurs ne peuvent pas être logguées dans php-errors.log. Elle devraient se trouver dans les logs du serveur HTTP.

Sous un système linux (débian ou dérivé) avec Apache, vous trouverez un backtrace dans /var/log/apache2/errors.log.

C'est ce backtrace dont j'ai besoin pour commencer la recherche d'un correctif, puisque je ne reproduis pas encore.

**Comment by popoix** [comment]
Voila mon fichier de log, je ne sais pas si ca peut vous aider. 

GLPI:/var/log/apache2# tail -f error.log
[Mon Jul 31 11:05:35.053517 2017] [:error] [pid 9849] [client 192.168.17.124:61963] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:05:35.278578 2017] [:error] [pid 10313] [client 192.168.0.169:55313] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:05:55.498124 2017] [:error] [pid 8098] [client 192.168.0.180:61044] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:05:58.308376 2017] [:error] [pid 8099] [client 192.168.9.66:60946] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:06:01.015685 2017] [:error] [pid 9853] [client 192.168.0.29:52190] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:06:15.402472 2017] [:error] [pid 10313] [client 192.168.0.169:55341] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24, referer: http://helpdesk.residalya.org/front/central.php
[Mon Jul 31 11:06:26.982315 2017] [:error] [pid 8098] [client 192.168.0.169:55352] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24, referer: http://helpdesk.residalya.org/front/plugin.php
[Mon Jul 31 11:06:36.799942 2017] [:error] [pid 9881] [client 192.168.5.3:4153] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:06:39.896484 2017] [:error] [pid 9853] [client 192.168.0.178:58132] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24
[Mon Jul 31 11:06:40.553818 2017] [:error] [pid 9880] [client 192.168.34.152:1095] PHP Fatal error:  Cannot redeclare plugin_version_formcreator() (previously declared in /var/www/helpdesk.residalya.org/plugins/formcreator/setup.php:24) in /var/www/helpdesk.residalya.org/plugins/formcreator.2.5.1/setup.php on line 24

**Comment by btry** [comment]
Ce type d'erreur est de nature à mettre tout votre GLPI en panne. Je doute qu'elle soit à la source de votre problème. Cela dit il faut la résoudre.

Pour l'obtenir, je pense que vous avez deux copies du même plugin dans le dossier glpi/plugins. Vous avez peut être sauvegardé l'ancienne version du plugin puis installé la nouvelle.

Assurez-vous qu'il n'y a qu'une version du plugin présente dans glpi/plugins. Ouvrez les outils développeur de votre navigateur, puis tentez de reproduire votre bug. Enfin, voyez l'historique des requêtes dans les outils de développeur. Il ne doit pas y avoir que des réponses HTTP 200. Si ce n'est pas le cas, montrez une capture d'écran de l'historique, en affichant les détails de la première requète suspecte.

**Comment by popoix** [comment]
Oui c'est quand j'ai fait la màj du plugin, j'avais laissé l'ancienne version renommée dans le meme folder.
 
Je ne vois rien de suspect dans l'historique.

![image](https://user-images.githubusercontent.com/29449252/28781839-b5633614-760b-11e7-82b5-292053f325ab.png)

**Comment by btry** [comment]
Votre capture montre l'onglet **Console**. Vous y trouverez des messages du moteur JS. Regardez plutôt l'onglet **Réseau**

**Comment by popoix** [comment]
Désolé. Voila. Les 2 dernières lignes sont apparues dès que j'ai cliqué sur formulaires saisis: 

![image](https://user-images.githubusercontent.com/29449252/28782501-8edb2c98-760d-11e7-9479-a5f8282555b6.png)

**Comment by btry** [comment]
Il n'y a pas l'erreur HTTP 500 que j'attendais. Donc il se passe clairement autre chose.

Je remarque que les 2 dernières requêtes n'ont renvoyé aucun octet. Ca explique l'onglet vide.

**Comment by btry** [comment]
Bonjour

En lisant le code, je pense que votre problème a lieu dans la méthode Form_Answer::showForForm()

Le plugin utilise le moteur de recherche de GLPI pour afficher la liste des réponses au formulaire. Il doit y avoir un problème dans les paramètres qui lui sont passés. 

https://github.com/pluginsGLPI/formcreator/blob/master/inc/form_answer.class.php#L261

Il faut examiner ce qu'il se passe dans les trois appels Search::*() ainsi que le contenu de la variable **$data**.

**Comment by btry** [comment]
Bonjour

Je tombe par hasard sur quelque chose qui ressemble à votre bug.

Je pense que vous avez dans sql-errors.log une erreur de ce type
```
SELECT \'glpi\' AS currentuser,
                        `glpi_plugin_formcreator_forms_answers`.`entities_id`, `glpi_plugin_formcreator_forms_answers`.`is_recursive`, `glpi_plugin_formcreator_forms_answers`.`status` AS `ITEM_0`,   `glpi_plugin_formcreator_forms_answers`.`id` AS `ITEM_1`,
                        `glpi_plugin_formcreator_forms_answers`.`id` AS `ITEM_1_id`,
                         `glpi_users_requester_id`.`name` AS `ITEM_2`,
                        `glpi_users_requester_id`.`realname` AS `ITEM_2_realname`,
                        `glpi_users_requester_id`.`id`  AS `ITEM_2_id`,
                        `glpi_users_requester_id`.`firstname` AS `ITEM_2_firstname`,
                         `glpi_users_validator_id`.`name` AS `ITEM_3`,
                        `glpi_users_validator_id`.`realname` AS `ITEM_3_realname`,
                        `glpi_users_validator_id`.`id`  AS `ITEM_3_id`,
                        `glpi_users_validator_id`.`firstname` AS `ITEM_3_firstname`,
                        `glpi_plugin_formcreator_forms_answers`.`request_date` AS `ITEM_4`,  `glpi_plugin_formcreator_forms_answers`.`id` AS id  FROM `glpi_plugin_formcreator_forms_answers`LEFT JOIN `glpi_users`  AS `glpi_users_requester_id`
                                          ON (`glpi_plugin_formcreator_forms_answers`.`requester_id` = `glpi_users_requester_id`.`id`
                                              )LEFT JOIN `glpi_users`  AS `glpi_users_validator_id`
                                          ON (`glpi_plugin_formcreator_forms_answers`.`validator_id` = `glpi_users_validator_id`.`id`
                                              ) WHERE  `glpi_plugin_formcreator_forms_answers`.`is_deleted` = \'0\'  ORDER BY ITEM_0 ASC  LIMIT 0, 20
  Error: Unknown column 'glpi_plugin_formcreator_forms_answers.validator_id' in 'on clause'
  Backtrace :
  inc/search.class.php:921                           
  plugins/formcreator/inc/form_answer.class.php:264  Search::constructDatas()
  plugins/formcreator/inc/form_answer.class.php:207  PluginFormcreatorForm_Answer::showForForm()
  inc/commonglpi.class.php:483                       PluginFormcreatorForm_Answer::displayTabContentForItem()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
```

**Comment by btry** [comment]
Fausse alerte: ma BDD avait un changement lié à un développement en cours.

**Comment by btry** [comment]
Bonjour

@popoix 
Auriez vous la possibilité de voir avec GLPI 9.2 et la branche develop de Formcreator (future 2.6.0) si le problème a disparu ?

**Comment by popoix** [comment]
Bonjour,

je n'ai pas le problème avec la version 2.6 du plugin sur la 9.2 de GLPI.
Mais je suis sur une bécane de test donc pas à périmètre égal.
En revanche, quand je duplique un formulaire, ca me le copie mais sans les
questions. Quel est l'intérêt?

Cordialement,

2017-10-03 17:46 GMT+02:00 btry <notifications@github.com>:

**Comment by btry** [comment]
Bonjour

Merci pour votre retour. Donc à priori, je bug pourrait être résolu. J'attends votre retour sur une situation plus proche de votre instance de production.

Concernant la duplication de formulaire, un bug a été identifié cette semaine et corrigé. Il y a aussi des soucis de duplication quand un formulaire contient un changement cible. Le correctif est prêt et attend sa revue.

Si vous n'avez pas de changement dans les cibles de vos formulaires, vous pouvez essayer la branche develop du plugin pour résoudre les soucis de duplication.

**Comment by btry** [comment]
Correction: le correctif en attente vient d'être fusionné :)

**Comment by btry** [comment]
Bonjour 

A défaut de retour je clos. D'autant plus que d'autres points évoqués ici sont résolus. Si besoin, ouvrez un nouveau ticket.
