### ISSUE TITLE
form answers

### ISSUE THREAD

**Issue by Smiley-k** [pluginsGLPI/formcreator#683]
Hi,

install update version 2.5.2,
![2017-07-31 15 33 35](https://user-images.githubusercontent.com/11009787/28777931-cac93900-7605-11e7-8014-d809ece3d9b8.png)

See this small bug. 
Previously, it was possible to open or view the completed form, now this form is disclosed immediately and stretched across the screen

**Comment by btry** [comment]
Hi

I cannot read russian text, this is annoying to fully understand what happens. I guess some columns on your screenshot have the name of some fields in some forms. 

Open your display preferences and check you have all the columns you want to display. If you got more, then consider removing them from your preferences.

Don't forget the personal view takes precedence over the global view.

**Comment by Smiley-k** [comment]
And the problem is not in the Russian language. You also see this form? before I thought it was neat

**Comment by btry** [comment]
Hi

The russian text caused me trouble because I wanted to check it the columns are fields of the form. Anyway, other clues led me to this conclusion.

i can reproduce, and the fix is easy.

https://github.com/pluginsGLPI/formcreator/pull/686/files

Please try it and feedback.

**Comment by Smiley-k** [comment]
Yeah, great, it solves the problem

**Comment by btry** [comment]
Thank you

It wil lbe available in the next release.
