### ISSUE TITLE
Perte historique formulaire 0.90-1.3.1 > 2.5.2

### ISSUE THREAD

**Issue by Lau65rent** [pluginsGLPI/formcreator#696]
Bonjour,

j'ai migré mon serveur GLPI 0.90.1 en 9.1.6 puis j'ai mis à jour le plugins formcreator en version 2.5.2.
Le plugin a bien retrouvé mes formulaires, par contre j'ai perdu tout l'historique, les formulaires en attentes de validation disparu et le compteur ID est reparti à 11.

Aucun problème lors de la création des nouveaux formulaires avec la création des tickets.

Avez-vous des idées de comment récupérer les formulaires?

**Comment by btry** [comment]
Bonjour

On a remonté un cas très semblable sur le forum. A priori il y a un souci de migration quand on upgrade depuis une version 1.3.x.

Il a été possible de contourner en upgradant en plusieurs étapes, comme décrit sur ce fil : http://forum.glpi-project.org/viewtopic.php?id=158555

**Comment by Lau65rent** [comment]
Merci pour votre rapidité, effectivement c'est le même problème.
