### ISSUE TITLE
glpi

### ISSUE THREAD

**Issue by nafoufa** [pluginsGLPI/formcreator#697]
bonjour,
 j'ai un soucis en attribuant un ticket au groupe de technicien faite par admin glpi, la réception des email au groupe sa prend du temps comment je peut réduire ce temps pour que a chaque attribution de ticket au technicien ces techniciens reçoivent automatiquement les email ..
merci d'avance

**Comment by btry** [comment]
Bonjour

Combien de temps faut-il pour que l'email arrive ?

**Comment by nafoufa** [comment]
bonjour
sa prend presque 20 mn et aussi l email n'arrive pas a tout les techniciens

2017-08-14 15:04 GMT+02:00 btry <notifications@github.com>:

**Comment by btry** [comment]
Vérifiez l'action automatique **queuedmail**. Elle doit être configurée en mode d'exécution **CLI** et vous devez avoir configuré une tâche cron (linux) ou le planificateur de tâches (windows) pour lancer les actions automatiques chaque minute.
![image](https://user-images.githubusercontent.com/14139801/29273528-dceb55b4-8104-11e7-88b3-9beb5413fe7e.png)

http://glpi-user-documentation.readthedocs.io/fr/latest/config/config_crontaskcli.html?highlight=cron (dernière section **Automatisation sous Linux**)

**Comment by nafoufa** [comment]
bonjour
mais lors de l'attribution de ticket a un groupe de technicien, l'email
n'arrive pas a tout les membre pourquoi ? et c quoi la solution ?
et merci pour votre aide

**Comment by btry** [comment]
Résolvons d'abord le délai d'envoi des emails. Ensuite voyons pourquoi des techniciens ne reçoivent pas de notification.

Le problème de délai est il résolu ?

**Comment by nafoufa** [comment]
oui c resolus

2017-08-14 16:38 GMT+00:00 btry <notifications@github.com>:

**Comment by nafoufa** [comment]
bonjour
mais lors de l'attribution de ticket a un groupe de technicien, l'email
n'arrive pas a tout les membre pourquoi ? et c quoi la solution ?
et merci pour votre aide


Le 14 août 2017 à 18:20, Nafissa Filali <nafissa.filali1991@gmail.com> a
écrit :

**Comment by nafoufa** [comment]
bonjour
comment je peut faire un cron qui tourne chaque munite pour l'action
automatique pour le mailgate et queuedmail parce que je ne reçoit pas l
email  que si j'execute l'action  automatique
et merci d'avance

Le 15 août 2017 à 09:59, Nafissa Filali <nafissa.filali1991@gmail.com> a
écrit :

**Comment by nafoufa** [comment]
bonjour 
comment je peut faire un cron qui tourne chaque munite pour l'action automatique pour le mailgate et queuedmail parce que je ne reçoit pas l email  que si j'execute l'action  automatique 
et merci d'avance

**Comment by btry** [comment]
Bonjour

Voyez cette documentation: http://glpi-user-documentation.readthedocs.io/fr/latest/config/config_crontaskcli.html

(dernière section **Automatisation sous Linux**)

J'en déduis que le problème de délai d'envoi des emails n'est pas résolu.

**Comment by nafoufa** [comment]
bonjour
oui c vrai j'ai toujours le probléme de delai

**Comment by nafoufa** [comment]
bonjour
j'ai essayé de faire l'automatisation sous linux situé dans le lien que
vous avez envoyé mais sa marche pas ...
moi j'utilise redhat enterprise 7

Le 15 août 2017 à 17:35, Nafissa Filali <nafissa.filali1991@gmail.com> a
écrit :

> bonjour
> oui c vrai j'ai toujours le probléme de delai
>

**Comment by btry** [comment]
Etant donné que je suis orienté Debian et que je n'ai pas assez d'expérience avec Red Hat, je vous invite à chercher sur le forum de GLPI, et éventuellement créer un sujet.

http://forum.glpi-project.org/

Pensez aussi à lire la documentation en ligne de Red Hat:
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/ch-Automating_System_Tasks.html

* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Deployment_Guide/ch-autotasks.html#s1-autotasks-cron

**Comment by nafoufa** [comment]
merci infiniment

**Comment by btry** [comment]
Non plus.

**Comment by nafoufa** [comment]
bonjour
est ce que pouvez vous me dire comment je peut regler le delai de temps
pask apres l'envoi de ticket elle reste dans le file d'attente jusqu'a
force l'action automatique ...
une solution pour ça svp

2017-08-16 7:16 GMT+00:00 btry <notifications@github.com>:

**Comment by btry** [comment]
Tant que vous ne configurerez pas une tâche cron pour les actions automatiques (programmée pour s'exécuter chaque minute) les emails ne pourront pas partir rapidement.

Les emails sont libérés de la file d'attente par le lancement des actions automatiques. Cela a lieu quand des personnes naviguent dans GLPI (mode d'exécution GLPI) et quand la tâche cron est configurée (mode d'exécution CLI). 

Vous *devez* configurer le mode d'exécution CLI et créer une tâche cron pour lancer les actions automatiques de manière régulière. L'action automatique que vous lancez manuellement sera lancée automatiquement et enverra les emails.

**Comment by nafoufa** [comment]
et comment je peut configurer une tache cron pour que l'execution de la
tache soit automatique

**Comment by btry** [comment]
Ouvrez un sujet sur le forum (lien donné sur ce fil), cette problématique concerne la configuration de GLPI.
