### ISSUE TITLE
Bug liste déroulante (selection)

### ISSUE THREAD

**Issue by juveboss** [pluginsGLPI/formcreator#699]
Bonjour,

J'ai un champs (selection) ou j'ai mis des nom d'agence avec un champs vide au départ : 
![image](https://user-images.githubusercontent.com/31047406/29332908-fb4f0476-8201-11e7-9885-e5f517aa2060.png)

Lors de l'utilisation du formulaire de nouvel arrivant par un utilisateur, il remplit le champs agence qui est un champs obligatoire mais lorsque le technicien visualise le ticket le champs agence est vide.

Je pense que ceci est un bug... car si je sélectionne séléction multiple le résultat est bien présent pour le technicien. Donc provisoirement j'ai mis la selection multiple mais ce n'est pas pratique.

Merci d'avance

**Comment by btry** [comment]
Bonjour

Quelle version de GLPI et du plugin ?

**Comment by juveboss** [comment]
GLPI 9.1.6
Plugin : Formulaires | 2.5.2 | GPLv2 | Activé | Teclib'

**Comment by juveboss** [comment]
Des idées ? Avez vous le même problème ?

**Comment by btry** [comment]
Je n'ai pas encore commencé; je vous donne des nouvelles dès que j'ai réussi à reproduire (ou pas, auquel cas pour d'autres questions)

**Comment by btry** [comment]
Bonjour

Je ne reproduis pas.

Avez vous créé le formulaire avec une version précédente du plugin puis upgradé ?

Regardez aussi dans glpi/files/_log/php-errors.log et sql.errors.log. Si il y a des erreurs au moment de g générer une ticket cible, ça peut me donner uen piste.

**Comment by juveboss** [comment]
Bonsoir,

J'ai trouvé le problème.... bon j'ai passé 1h à faire des tests...
Et j'ai remarqué que les valeurs dans mon champs "agence" il y avait un espace "Paris " et non "Paris" , cela doit créer un bug d'affichage..
Et vu que je reprenais les valeurs de ce champs pour mes autres formulaires, je reportais le problème ailleurs..

Si sa peut aider :)
Merci en tout cas

**Comment by btry** [comment]
En effet, cela met clairement sur la voie. Merci pour la recherche.

**Comment by btry** [comment]
Bonjour

Je viens de réaliser un correctif pour votre bug. Il impacte également les valeurs par défaut.

Pouvez-vous faire un test sur un GLPI 9.2 ?

**Comment by btry** [comment]
Bonjour

A défaut de retour, je ferme. Si le problème persiste, merci de créer un nouveau ticket.
