### ISSUE TITLE
Filter actors

### ISSUE THREAD

**Issue by magheinz** [pluginsGLPI/formcreator#700]
It would be very usefull to filter in multiselect-fields so you can be sure there are only actors or groups with names like 'admin*' or 'user*' or something like that.

**Comment by btry** [comment]
Hi

Multiselect field don't support objects from GLPI; only raw values,  then it seems to me useless to implement a filter feature here. I assume you meant questions of type GLPI Object. 

In version 2.14.0 you will be able to use filters to restrict the list available to user.

![image](https://user-images.githubusercontent.com/14139801/233646873-6cea0243-e913-479c-ab16-70f1e949ff2f.png)
