### ISSUE TITLE
[Feature Request] Priviledge management or possibility for Admin role to create/edit forms and see all answers 

### ISSUE THREAD

**Issue by iPaulis** [pluginsGLPI/formcreator#708]
Hi, I've searched if there is a similar issue or any solution, but I think I haven't found anything, so I hope this request is OK, or maybe you can help me with a workaround or something.

We use GLPI v9.1.2 and Formcreator v2.5.2. Right now, only super-admin role is able to create/edit forms and see all the answers in the new "All answers" view. This new view is a very interesting and straightforward way to see all the results, for example, for our administrative department, which should not have super-admin role. In our case, we would like the admin role to also be able to access this live data, but I could not find the possibility to change permissions in "Administration > Profiles" or in any other place.

Am I looking in the wrong place? is there a way to change privileges for a certain role? or is there any way I can make another role to have the same privileges for this plugin as super-admin?

If there is a way to do it, I would really appreciate your help. Otherwise, I would kindly suggest to add the possibility as a feature for a future version.

Thank you very much in advance.

**Comment by btry** [comment]
Hi 

A user should be able to manage forms as long he has the UPDATE right on entities. Can you try and feedback if this satisfies your need ?

**Comment by iPaulis** [comment]
It works!! It is exactly what I needed, thank you.

**Comment by btry** [comment]
Great ! Thank you for your feedback.
