### ISSUE TITLE
[2.5.2]+GLPI  9.1.6 :  service catalog very slow

### ISSUE THREAD

**Issue by ladenree76000** [pluginsGLPI/formcreator#709]
really looks like this
https://github.com/pluginsGLPI/formcreator/issues/450
i'm preparing migration to GLPI 9.1.6 with form creator 2.5.2.
with standard interface (tech or admin profile) it works fast (less than 0.5 second).
with simplified interface (post only profile) and entity set to 'service calalog'  it takes more than 15 seconds.

I have no problem with glpi90.5+formcreator 2.4.2 : it works fast whatever the profile, whatever simplified iterface or standard

**Comment by btry** [comment]
Hi

Please enable slow queries, and set a trigger to 5 seconds to see if a SQL query is responsible of your problem.

**Comment by btry** [comment]
About #450 : A hard work was done to solve this issue, and it seems it was successful for this user.

In 2.4.x the table ```glpi_plugin_formcreator_issues``` was actually a view. To solve the issue you mentionned, I did not find more efficient than converting it into a table (duplicating data available in other itemtypes).

If the view is not converted into a table, the plugin should work, but will run slowly when there is a lot of tickets in the database. Check that  ```glpi_plugin_formcreator_issues``` is actually a table, and not a view.

**Comment by ladenree76000** [comment]
glpi_plugin_formcreator_issues is not a view but a table ( with 51 000 records ) i also have 51000 tickets ! 
only 100 tickets where created with formcreator.

**Comment by btry** [comment]
It is normal that the count of issues matches the count of tickets. Don't worry about that.

Compare the CREATE TABLE request in install/mysql/plugin_formcreator_empty.sql with the actual table. Are all indexes found in the .sql file actually created in your table ?

If yes, then it is time to search the slow queries as I described earlier.

**Comment by ladenree76000** [comment]
slow query (allways the same) : 
```
# Time: 170829 17:15:27
# User@Host: ocs[ocs] @ localhost []
# Thread_id: 1229  Schema: glpi  QC_hit: No
# Query_time: 5.781735  Lock_time: 0.000266  Rows_sent: 49923  Rows_examined: 353525
# Full_scan: Yes  Full_join: No  Tmp_table: Yes  Tmp_table_on_disk: Yes
# Filesort: Yes  Filesort_on_disk: No  Merge_passes: 1  Priority_queue: No
SET timestamp=1504019727;
SELECT 'user' AS currentuser,
                        `glpi_plugin_formcreator_issues`.`sub_itemtype`, `glpi_plugin_formcreator_issues`.`entities_id`, `glpi_plugin_formcreator_issues`.`is_recursive`,  GROUP_CONCAT(DISTINCT CONCAT(`glpi_plugin_formcreator_issues`.`name`, '$#$' ,
                                                        `glpi_plugin_formcreator_issues`.`id`)
                                        SEPARATOR '$$##$$') AS `ITEM_0`,
                           
                            IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_formcreator_issues`.`display_id`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_plugin_formcreator_issues`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_0_display_id`, `glpi_plugin_formcreator_issues`.`display_id` AS `ITEM_1`,  `glpi_plugin_formcreator_issues`.`status` AS `ITEM_2`,  `glpi_plugin_formcreator_issues`.`date_creation` AS `ITEM_3`,  `glpi_plugin_formcreator_issues`.`date_mod` AS `ITEM_4`,  `glpi_entities`.`completename` AS `ITEM_5`,   `glpi_users_requester_id`.`name` AS `ITEM_6`,
                        `glpi_users_requester_id`.`realname` AS `ITEM_6_realname`,
                        `glpi_users_requester_id`.`id`  AS `ITEM_6_id`,
                        `glpi_users_requester_id`.`firstname` AS `ITEM_6_firstname`,
                        `glpi_plugin_formcreator_issues`.`id` AS id  FROM `glpi_plugin_formcreator_issues` LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_a900a61824c3906cc82f90407e525192`
                                             ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`tickets_id`
                                                 AND `glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`type`
                                                                 = 1 ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_9201eed6268ba42a969f0541adcd73d9`
                                             ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_9201eed6268ba42a969f0541adcd73d9`.`tickets_id`
                                                 AND `glpi_tickets_users_9201eed6268ba42a969f0541adcd73d9`.`type`
                                                                   = 3 ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`
                                             ON (`glpi_plugin_formcreator_issues`.`original_id` = `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`tickets_id`
                                                 AND `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`type`
                                                                  = 2 )LEFT JOIN `glpi_entities` 
                                          ON (`glpi_plugin_formcreator_issues`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_users`  AS `glpi_users_requester_id`
                                          ON (`glpi_plugin_formcreator_issues`.`requester_id` = `glpi_users_requester_id`.`id`
                                              ) WHERE   ( `glpi_plugin_formcreator_issues`.`entities_id` IN ('2', '3', '6', '4')  OR (`glpi_plugin_formcreator_issues`.`is_recursive`='1' AND `glpi_plugin_formcreator_issues`.`entities_id` IN ('0')) )  AND (   `glpi_plugin_formcreator_issues`.`status` IN ('5','6') ) GROUP BY `glpi_plugin_formcreator_issues`.`id` ORDER BY ITEM_0 ASC;
```

**Comment by ladenree76000** [comment]
here my indexes :

 Type | Unique | Compressé | Colonne | Cardinalité | Interclassement | Null | Commentaire
BTREE | Oui | Non | id | 50375 | A | Non |  
 BTREE | Non | Non | original_id | 50375 | A | Non |  sub_itemtype | 50375 | A | Non
BTREE | Non | Non | entities_id | 5 | A | Non |  
 BTREE | Non | Non | requester_id | 53 | A | Non |  
 BTREE | Non | Non | validator_id | 1 | A | Non |  
 
and the indexes in empty.sql 
  PRIMARY KEY (`id`),
  INDEX `original_id_sub_itemtype` (`original_id`, `sub_itemtype`),
  INDEX `entities_id` (`entities_id`),
  INDEX `requester_id` (`requester_id`),
  INDEX `validator_id` (`validator_id`)

it matches...

**Comment by btry** [comment]
Yes, it matches, and the query you reported seems to be created by the sarch engine. I think your problem is not the same as #450. It is related to the four big numbers you can see in the service catalog on the top of the page.

**Comment by btry** [comment]
An additional note:

now the request is identified, you should run EXPLAIN on it. I think this will provide more information on how to solve the issue.

**Comment by ladenree76000** [comment]
table and indexes are the same in 2.4.2 and 2.5.2  but in one case I have 36 lines and another case 51000 lines.
in both cases i have 51000 tickets.

**Comment by ladenree76000** [comment]
"you should run EXPLAIN on it"  => I don't know how to do it.  (i'll google for it...)

**Comment by btry** [comment]
just use your favourite SQL tool and copy paste the query. Prepend it with EXPLAIN to ask your DBMS to explain how it will run the query. You'll find some info on internet to learn how to read the answer.

**Comment by ladenree76000** [comment]
here's explain results.
I don't see any clue....
`

id | select_type | table | type | possible_keys | key | key_len | ref | rows | Extra |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | glpi_plugin_formcreator_issues | ALL | entities_id | NULL | NULL | NULL | 50375 | Using where; Using temporary; Using filesort
1 | SIMPLE | glpi_tickets_users_a900a61824c3906cc82f90407e525192 | ref | unicity | unicity | 8 | glpi.glpi_plugin_formcreator_issues.original_id,const | 1 | Using index
1 | SIMPLE | glpi_tickets_users_9201eed6268ba42a969f0541adcd73d9 | ref | unicity | unicity | 8 | glpi.glpi_plugin_formcreator_issues.original_id,const | 1 | Using index
1 | SIMPLE | glpi_tickets_users_74690f2626744a37ace4c70dd87cea83 | ref | unicity | unicity | 8 | glpi.glpi_plugin_formcreator_issues.original_id,const | 1 | Using index
1 | SIMPLE | glpi_entities | eq_ref | PRIMARY | PRIMARY | 4 | glpi.glpi_plugin_formcreator_issues.entities_id | 1 |  
1 | SIMPLE | glpi_users_requester_id | eq_ref | PRIMARY | PRIMARY | 4 | glpi.glpi_plugin_formcreator_issues.requester_id | 1 |  

`

**Comment by ladenree76000** [comment]
what is strange in this query is that there is no where clause on glpi_ticket_users.users_id= "$myuserid"

**Comment by ladenree76000** [comment]
i made it faster by adding a filter to see only my forms/tickets :+1: 

              ```
                ['field' => 8,
                              'searchtype' => 'equals',
                              'value'      => 'process',
			      'value'      => $_SESSION[glpiID],
                              'link'       => 'AND'],
```

 in issues.class.php 
so i can see only My ticket/forms  in the numbers a the top 



`
   static function getIncomingCriteria() {
      return ['criteria' => [['field' => 4,
                              'searchtype' => 'equals',
                              'value'      => 'process',
                              'value'      => 'notold'],
			    ['field' => 8,
                              'searchtype' => 'equals',
                              'value'      => 'process',
			      'value'      => $_SESSION[glpiID],
                              'link'       => 'AND']],
              'reset'    => 'reset'];
   }

   static function getWaitingCriteria() {
      return ['criteria' => [['field' => 4,
                              'searchtype' => 'equals',
                              'value'      => 'process',
                              'value'      => Ticket::WAITING],
			    ['field' => 8,
                              'searchtype' => 'equals',
                              'value'      => 'process',
			     'value'      => $_SESSION[glpiID],
                              'link'       => 'AND']],
              'reset'    => 'reset'];
   }

   static function getValidateCriteria() {
      return ['criteria' => [['field' => 4,
                              'searchtype' => 'equals',
                              'value'      => 'process',
                              'value'      => 'notclosed',
                              'link'       => 'AND'],
			    ['field' => 8,
                              'searchtype' => 'equals',
                              'value'      => 'process',
			      'value'      => $_SESSION[glpiID],
                              'link'       => 'AND'],
                             ['field' => 9,
                              'searchtype' => 'equals',
                              'value'      => 'process',
                              'value'      => $_SESSION['glpiID'],
                              'link'       => 'AND'],
                             ['field' => 4,
                              'searchtype' => 'equals',
                              'value'      => 'process',
                              'value'      => 'notclosed',
                              'link'       => 'OR'],
			    ['field' => 8,
                              'searchtype' => 'equals',
                              'value'      => 'process',
			      'value'      => $_SESSION[glpiID],

                              'link'       => 'AND'],
                             ['field' => 11,
                              'searchtype' => 'equals',
                              'value'      => 'process',
                              'value'      => $_SESSION['glpiID'],
                              'link'       => 'AND']],
              'reset'    => 'reset'];
   }

   static function getSolvedCriteria() {
      return ['criteria' => [['field' => 4,
                              'searchtype' => 'equals',
                              'value'      => 'old'],
			    ['field' => 8,
                              'searchtype' => 'equals',
                              'value'      => 'process',
			     'value'      => $_SESSION[glpiID],
                              'link'       => 'AND']],
              'reset'    => 'reset'];
   }

`

but see "my requests" allways shows all tickets

**Comment by btry** [comment]
Hi

Thank you for sharing your results. If these changes solve at least a part of the problem, you may submit your fix in a pull request.

**Comment by ladenree76000** [comment]
this is a workaround not a real fix.  :  whatever the user rights ( with simplified interface) he only can see his tickets. : that's what I want. Is it the aim of the project ?  perhaps it should manage userrights ( see my tickets, see groups tickets, see all tikets) depending of the profile ? 

moreover, post only user still can see all the tickets in ticket list , i have to find a solution for it.

PS i'm not familar with Github and I don't kwow how to pull request.

**Comment by btry** [comment]
Hi

If you know how to use git, fork this repo grom your GH account, clone the fork in your work station, do changes, commit them in a branch and push it to your fork. Next from GH you can submit your branch for review and inclusion to the official repository.

I'll investigate issue #711 first, as it is more urgent.

**Comment by btry** [comment]
Hi

In #711 you said the fix solves the performace problem. Can I close this issue to ?

**Comment by ladenree76000** [comment]
yes, you can close.
Thanks

**Comment by btry** [comment]
Thank you for your feedback
