### ISSUE TITLE
Problème affichage questions

### ISSUE THREAD

**Issue by nicolas62** [pluginsGLPI/formcreator#714]
Bonjour,

Je me permets de vous reporter ce qui semble être un BUG sur la version 2.5.2.
Je ne pense pas qu'il ait déjà été soumis.

Nous avons créer un formulaire avec de multiples questions.
Ces dernières ne sont affichés qu'en fonction de réponse à d'autres questions préalables sur ce schéma : 
![image](https://user-images.githubusercontent.com/25502814/30151438-b271580c-93af-11e7-9019-607e597c79b5.png)

On ajoute ensuite une nouvelle question, elle apparait tout en bas de la liste par défaut.
Si on veut la déplacer plus haut dans le formulaire, toutes les questions qui sont alors déplacé vers le bas change de paramétrage.
![image](https://user-images.githubusercontent.com/25502814/30151523-12d80510-93b0-11e7-9256-ac8e19c4d281.png)
Le champ surligné passe alors en "Toujours Visible" et il faut refaire tout le paramétrage car toutes les questions deviennent visible..

Est-ce un BUG du plugin ou un problème de mon coté ?
Je suis en version 9.1.6 de GLPI.

Merci par avance,
Nicolas

**Comment by btry** [comment]
Bonjour

Au vu de votre souci, je pense qu'il s'agit d'un bug.

Je tente de reproduire la semaine prochaine.

**Comment by btry** [comment]
Bonjour

Je vous invite à tester le correctif ci dessus et me faire un retour.

**Comment by nicolas62** [comment]
Bonjour,

C'est validé pour moi, merci.

**Comment by btry** [comment]
Bonjour

Merci pour votre retour.
