### ISSUE TITLE
[Translate] Service Catalog  some words are not translated.

### ISSUE THREAD

**Issue by LordBat** [pluginsGLPI/formcreator#715]
Hi, i use Spanish (Argentina) language but some words are not translated. See Image.

![image](https://user-images.githubusercontent.com/19165739/30174172-893db392-93d0-11e7-92f8-fc2f5c6e33f0.png)

Thanks and Regards!

**Comment by btry** [comment]
Hi

Translations are done by the community. I noticed this week that support for some languages is almost complete (>70%), and yours is among them.

I suggest that you contribute by translating the last strings. You'll be able to retrieve your work for yourself, and I'll include your contribution in the incoming 2.6.0 release for GLPI 9.2.

**Comment by LordBat** [comment]
Hi btry! Thanks for the fast response!

Yes i do almost all the es_AR language on transifex, but i dont know why these word can't was translated. By the way that words are not in the FormCreator language, i think is the core GLPI language?.


Regards!

**Comment by btry** [comment]
Some strings have singular and plural versions. Maybe you did not noticed a small blue button to switch between the versions. If you translate only one of them you canot save it. I had this annoyance the first time used the online service.

I confirm the plugin uses strings from the core when this is possible. If you give me an example of such string I can check if it is actually provided by the core or the plugin. I don't know the status of Spanish for Argentina for the core, but the translations are also handled by transifex. You can also contribute if some strings are missing.

**Comment by LordBat** [comment]
I found my issue, i put the new po - mo files but i forgot to put the read permissions to be translated. Now is working flawless.


Thanks for your time!

Regards!

**Comment by btry** [comment]
Great!  Then I close.
