### ISSUE TITLE
[Ticket category Assigment] Equals to the Answer -Not showing options

### ISSUE THREAD

**Issue by LordBat** [pluginsGLPI/formcreator#716]
Hi, i am creating a form to get a category based on the answer but in Target Ticket i don't see my category options. I don't know if this is a bug or i missed something.

See Image:

![image](https://user-images.githubusercontent.com/19165739/30210481-37e31df4-9473-11e7-9742-cb041164f949.png)

Im using the latest version of Formcreator (2.5.2) on GLPI 9.1.4.

Thanks and Regards!

**Comment by btry** [comment]
Hi

You need to have in your form a question displaying the ticket categories, like the following screenshot
![image](https://user-images.githubusercontent.com/14139801/30211254-8c28e07e-94a0-11e7-935b-009c8088346b.png)

The features in the target ticket you highlighted don't affect the list of available tags. Actually the cargetory selected by the requester wil lbe saved in the category field of a generated ticket: 

![image](https://user-images.githubusercontent.com/14139801/30211328-d500c9ec-94a0-11e7-9079-94c1f683e851.png)

**Comment by LordBat** [comment]
Hi btry, thanks again for the fast answer.

i am testing that and works BUT in question displaying the ticket categories i see all categories (i separate the categories between request and incident) and i need only the incident categories available. i dont know if this could be possible now or can be a nice future feature.


Regards!

**Comment by btry** [comment]
In the development version 2.6.0 I recently added a feature to filter ticket categories and allow only request, or incidents or both. You will also be able to limit the tree to a specified deep level.

Unfortunately this version is compatible with GLPI 9.2 only. You're welcome to test it with the latest revision of GLPI 9.2, despite it is not ready for production yet. I do my best to make this plugin ready as soon as GLPI 9.2 is released.

**Comment by LordBat** [comment]
Sure! i will test and wait with joy the new glpi 9.2! and the new features of this amazing plugin.

Thanks again for all your efforts and fast support response.

Regards!

**Comment by btry** [comment]
Thank you.

There are some other new features planned in the version 2.6.0. I'll build and share a release candidate prior the final release. If you find bugs with this develomment version, I'll be glad to get your feedbacks.

**Comment by bugos** [comment]
Hello,
would it be possible to list only the subcategories below a certain category in the form. For example I have a ticket category "Internal Apps" with Subcategories "App1", "App2" etc. 
Can I display only "App1", "App2" etc in the dropdown and have the ticket category assigned automatically?

**Comment by btry** [comment]
Hi @bugos 
please create a new issue : your question is not related to this one.
