### ISSUE TITLE
[9.2]Item_Ticket tabs display nothing

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/formcreator#732]
but with a correct count into the tab title

![image](https://user-images.githubusercontent.com/418844/30695081-01fef294-9ed7-11e7-99d7-2db42b838d77.png)

**Comment by btry** [comment]
ni item_ticket.class.php::showForTicket()

```php
if (in_array($itemtype, $_SESSION["glpiactiveprofile"]["helpdesk_item_type"])) {
```

This test fails and prevent displaying the item. If we manually add in the current profile the itemtype for form answers, the item show.

**Comment by btry** [comment]
I'm unsure about the right way to fix it.

When installing the plugin, we cannot add the itemtype to helpdesk_item_types for all profiles as this is probably generally not wanted. We cannot add it only to the profile isntalling the plugin (mostly super-admin) as this is often useless. 

I think adding the type must be done by the admin of GLPI, depending on the specific needs.

Thus maybe GLPI should filter the items in relation to a ticket by available itemtypes while counting the items.

**Comment by btry** [comment]
as we discussed: this is more an issue in GLPI than in the plugin. 

https://github.com/glpi-project/glpi/issues/2813

**Comment by btry** [comment]
Issue in GLPI solved, so this one too.
