### ISSUE TITLE
Errors in 9.2 php logs

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#744]
Hello I get the following error every second in the php-errors.log:

2017-09-29 08:05:40 [7@]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/formcreator/inc/form.class.php:1405        TableExists()
  plugins/formcreator/setup.php:132                  PluginFormcreatorForm::countAvailableForm()
  inc/plugin.class.php:145                           plugin_init_formcreator()
  inc/includes.php:118                               Plugin::load()
  front/plugin.form.php:38                           include()

Is there something I can do?

Thank you

**Comment by btry** [comment]
Hi

I guess you're using Formcreator 2.5.2 ?

**Comment by grego1981** [comment]
Yes I use the 2.5.2 release.

**Comment by btry** [comment]
Then you hacked the version check in the plugin.

The version 2.5.2 is not compatible with GLPI 9.2. 

I'm preparing right now the pre-release 2.6.0-rc1 which is needed for GLPI 9.2 (I know I'm late, sorry). I strongly encourage you to download the develop version or the imminent pre-release and test it on a testing isntance of GLPI 9.2.

Your feedbacks are welcome.

**Comment by btry** [comment]
Here is the pre-release you need. don't forget to feedback (even if it works perfectly for you)

https://github.com/pluginsGLPI/formcreator/releases/tag/v2.6.0-rc1

**Comment by grego1981** [comment]
Yes indeed I've done that during testing and forgot! I'll download the release you're working on and give any feedback I can!

**Comment by btry** [comment]
Great, thank you ! I close this ticket as it is not relevant for version 2.6.x.
