### ISSUE TITLE
Correspondance Suivi / Ticket

### ISSUE THREAD

**Issue by LrtLand** [pluginsGLPI/formcreator#749]
Bonjour.

Actuellement en GLPI 9.1.6 et FormCreator 2.5.2 je rencontre une anomalie dans la consultation des tickets lorsque GLPI (au niveau d'une entité) est configuré en mode Catalogue de service simplifié.
Lorsque certains utilisateurs souhaitent consulter leurs tickets ouverts, ils obtiennent bien la liste de leurs ticket dans "Mes demandes d'assistance" mais lorsqu'ils éditent leurs tickets, quelques uns affichent le contenu d'un ticket d'un autre ticket.

J'ai tenté d'analyser au mieux et, sauf erreur d'interprétation de ma part, voici ce que j'ai relevé :
- Création de tickets depuis les formulaire = affichage des tickets et de leurs contenus OK.
- Suppression d'un ticket GLPI seul.
- Création d'un nouveau ticket depuis un formulaire sans avoir supprimé le formulaire lié au ticket précédemment supprimé (formulaire devenu orphelin) = affichage des contenus des nouveaux tickets créés non corrects. Un décalage se créé entre l'ID du ticket listé et l'ID du ticket affiché lors de son édition. Les tickets créés avant la suppression de l'un d'eux restent conforme à l'affichage.
- Suppression du formulaire orphelin.
- Création d'un nouveau ticket depuis un formulaire = affichage de ces nouveaux tickets OK ! Tous les tickets créés entre la suppression d'un ticket et la suppression de son formulaire restent néanmoins en erreur d'affichage.

En revanche, en interface standard, aucune anomalie d'affichage n'est constaté.

En résumé, sous le mode Catalogue de service simplifié, un décalage s'opère à l'affichage du contenu d'un ticket d'autant qu'il puisse y avoir des formulaires orphelins (si j'ai 3 formulaires orphelins, j'aurai un décalage du contenu de ticket de 3 par rapport à l'ID du ticket). 
Une fois ces formulaires orphelins supprimés à leurs tours, les nouveaux tickets s'affichent normalement. Ceux en décalage restent décalés.
Je ne sais pas si c'est considéré comme un bug mais je suis à tout le moins preneur d'une solution pour pouvoir identifier les tickets concernés et éliminer leurs décalages d'affichage (au niveau de la BD ?).

Cdt.

**Comment by btry** [comment]
Bonjour

Quand un utilisateur utilise le catalogue de service en interface simplifiée il voit les données d'une table en BDD contenant des infos de ticket mais aussi de réponses à des formulaires.

Cette partie a été assez complexe à faire fonctionner dans sacrifier les performances. Les résultats de vos tests pourraient être perturbés (donc falsifiés) par une action automatique de Formcreator visant à rétablir la cohérence des données provenant des réponses aux formulaires et des tickets si nécessaire

Pouvez-vous désactiver l'action automatique "SyncIssues" avant de refaire votre test ?

De plus une anomalie dans GLPI 9.1.6 impacte le catalogue de service, mais sa correction en GLPI 9.2 introduit un autre problème qui vient de m'être remonté. Pour bien faire les choses, il faudrait que vous testiez GLPI 9.2 avec Formcreator 2.6.0-rc1 (livrée aujourd'hui). Formcreator 2.5.2 et en fin de vie et il est préférable de se concentrer sur la branche 2.6.x .

**Comment by btry** [comment]
Je tente de reproduire, mais quelques points ambigus font que je ne suis peut être pas la bonne procédure. De plus je teste avec Formcreator 2.6.0-rc1, mais il n'y a pas eu de changement sur cette partie qui pourrait influer sur le problème.

Je crée un formulaire dédié au traitement de ce sujet. Il contient une question, et génère un ticket (pas de validation pour simplifier).

Je fais les étapes 1 et 2. (ID de ticket génénré = 145 pour moi)

Etape 3 : 
* je dois prendre le même formulaire qu'en étape 1, un autre, ou cela n'a pas d'importance ?
* ID de ticket = 146 (pour moi c'est normal)
* j'affiche la liste des demandes d'assistance, je vois bien une ligne t_146 (id du ticket). J'ouvre le ticket à partir de la demande d'assistance, et ça ouvre bien le ticket ID=146.

* Etape 4 : suppression du formulaire orphelin. Je suppose que le formulaire est orphelin parce que le ticket généré n'existe plus. Dans ce cas ce qui est orphelin serait la demande d'assistance qui a été créée en  répondant à un formulaire pendant étape 1. C'est bien ça ?

* Etape 5 : les  tickets créés entre la  suppression d'un ticket et la suppression de son formulaire (ou demande d'assistance ?)  sont créés par GLPI ou par le plugin ?

**Comment by btry** [comment]
Bonjour

Ce ticket est obsolète. Si le problème persiste avec la version 2.6.2, ouvrez un nouveau  ticket.
