### ISSUE TITLE
Destination: specific entity [9.2]

### ISSUE THREAD

**Issue by grvy** [pluginsGLPI/formcreator#754]
No additional dropdown is loaded, using GLPI 9.2 and the RC release of FormCreator. 

In the old version you would get a addtional dropdown where you could specify extra information.
I can see it not working for the specific entity but I think there's more.. the plugin is acting odd.

**Comment by btry** [comment]
Hi

Where do you observe such behavior ? When you design a form ?

**Comment by grvy** [comment]
When desiging a form, you have the destination tab. Select specific entity there, but you get no option to specify anything.

**Comment by btry** [comment]
Indeed, there is something wrong here. The appearance if the dropdowns of this page is not good. PRobably a JS issue.

![image](https://user-images.githubusercontent.com/14139801/31049353-9e723d0a-a631-11e7-85cd-1dbfec37601f.png)

the

**Comment by grvy** [comment]
Do you need further assistance? and also while im asking; could you explain to me the difference between the extended service catalog and the simplified? i dont see any changes?

**Comment by btry** [comment]
It seems pressing F5 to refresh workarounds the issue.

In the mean time, I confirm there is a JS error remated to tinymce

![image](https://user-images.githubusercontent.com/14139801/31049371-060fd030-a632-11e7-9b7c-c1c8f914e10b.png)

**Comment by grvy** [comment]
Not entirely, unable to save. If you click save it goes back blank.

**Comment by btry** [comment]
The difference between simplified and extended service catalogs is when you display an issue.

The extended mode shows tabs of the generated ticket (if any). The simplified does not shows these  tabs 

# Extended
![image](https://user-images.githubusercontent.com/14139801/31049415-b8282fce-a632-11e7-8ac0-98fdfb10ac23.png)

# simplified 

![image](https://user-images.githubusercontent.com/14139801/31049417-c69d3a54-a632-11e7-882a-c9b3006ffbea.png)

**Comment by btry** [comment]
> It seems pressing F5 to refresh workarounds the issue.
>> Not entirely, unable to save. If you click save it goes back blank.

On my site it seems I'm able to save. I'll focus on the initial problem :/

**Comment by btry** [comment]
Note:  it seems it does not happen if rich text mode is disabled in GLPI.

**Comment by grvy** [comment]
Ah, it doesnt happen if you make a new form but it does not save if you use a old form. 
WOrkaround is to DUplicate the form I guess so it's new. I will test further, 

If I cant fix it, ill log a new issue for it. If its just buggy becuz of the upgrade path thats fine.

**Comment by btry** [comment]
@grvy 

Can you try this patch ?
https://github.com/btry/formcreator/commit/e0c807237faa19e1103983982bd5a97c982e8ec7

**Comment by grvy** [comment]
@btry tested. It works! awesome.

**Comment by btry** [comment]
Thanks for your feedback ! Of course it will be added in the next RC or final release.
