### ISSUE TITLE
Impossible de montrer /cacher un champ 

### ISSUE THREAD

**Issue by msizec** [pluginsGLPI/formcreator#760]
J'ai 2 champs. Le premier est de type 'intitulé'.
Je ne peux pas montrer/cacher le second champ en utilisant la condition que le champ de type intitulé est vide. 
Mettre en condition "affiché si différent de -----" ne fonctionne pas. et  "affiché si différent de " non plus.

**Comment by btry** [comment]
Bonjour

En effet, je reproduis.

**Comment by btry** [comment]
finir #666 et intégrer le fix

A priori  le test if (empty...)) {...} est cause du bug, en plus d'être inutile
```php
            case '==' :
               if (empty($condition['value'])) {
                  $value = false;
               } else {
                  if (is_array($values[$condition['field']])) {
                     $decodedConditionField = null;
                  } else {
                     $decodedConditionField = json_decode($values[$condition['field']]);
                  }
                  if (is_array($values[$condition['field']])) {
                     $value = in_array($condition['value'], $values[$condition['field']]);
                  } else if ($decodedConditionField !== null && $decodedConditionField != $values[$condition['field']]) {
                     $value = in_array($condition['value'], $decodedConditionField);
                  } else {
                     $value = $condition['value'] == $values[$condition['field']];
                  }
               }
               break;
```

**Comment by btry** [comment]
Bonjour voyez le correctif pour #877

Il devrait corriger votre bug.

**Comment by btry** [comment]
Bonjour

Je ne reproduis plus avec la branche develop (2.7.0-beta.1 + quelques correctifs).

Il faut que la valeur de la condition soit vide : 
![image](https://user-images.githubusercontent.com/14139801/50562997-7e8ca200-0d19-11e9-895c-a490c45607ff.png)


Pouvez-vous essayer et faire un retour ?

**Comment by btry** [comment]
Bonjour

à défaut de retour, je ferme ce ticket.
