### ISSUE TITLE
Pas d'affichage des formulaires avec l'interface simplifiée

### ISSUE THREAD

**Issue by DooBio** [pluginsGLPI/formcreator#770]
Bonjour

Premièrement merci pour votre plugin que j'utilise quotidiennement et qui simplifie grandement la création de demande d'intervention pour mes utilisateurs ;).

Suite à la mise à jour en Glpi 9.2 et donc en FormCretaor 2.6.0 Rc1 j'ai un problème d'affichage des formulaire en mode interface simplifié pour mes utilisateurs qui sont dans le profil Self Service. 
Les catégories et les formulaires n'apparaissent plus : 

![image](https://user-images.githubusercontent.com/32511461/31170980-7c0ee90a-a8fe-11e7-9aa3-d059ea0b4915.png)

![image](https://user-images.githubusercontent.com/32511461/31170996-8844a214-a8fe-11e7-9561-789a120f4923.png)

Par contre avec l'interface standard pas de problème

![image](https://user-images.githubusercontent.com/32511461/31171024-ae1d1cdc-a8fe-11e7-95a8-81535398314c.png)

![image](https://user-images.githubusercontent.com/32511461/31171041-b84ea00e-a8fe-11e7-8a81-b661044898e9.png)

D'avance merci

**Comment by btry** [comment]
Bonjour

J'ai eu une remontée identique, et c'est lié à la présence de deux plugins chacun ayant un petit souci de compatibilité : 
* News https://github.com/pluginsGLPI/news/pull/43
* Data injection https://github.com/pluginsGLPI/datainjection/issues/32

Voyez si vous avez ces deux plugins, et si oui, vérifiez que vous avez les patchs que j'ai indiqué pour chacun d'entre eux.

Si vous avez suivi la recommandation de la version 2.6.0-rc1 vous n'êtes pas encore en production. Dans ce cas vous êtes invités à mettre le plugin à jour avec la branche develop pour bénéficier d'une collection de correctifs faits depuis fin de semaine dernière.

Je suis à l'écoute des retours pour faire les corrections nécessaires avant la sortie de al version finale. Je  compte faire la release d'ici une semaine ou deux maximum.

**Comment by DooBio** [comment]
Merci pour la réactivité effectivement ça vient bien du Plugin "News".

Encore merci pour le travail effectué 

Bonne continuation

**Comment by btry** [comment]
Merci pour votre retour; je ferme.
