### ISSUE TITLE
Bouton formulaire invisible avec le plugin Alertes

### ISSUE THREAD

**Issue by thiasou** [pluginsGLPI/formcreator#771]
Bonjour,

Lorsque le plugin Alertes est activé, le bouton formulaire n'apparait pas dans le profil utilisateur.

Cordialement,

Mathias

**Comment by btry** [comment]
Bonjour

Le bouton formulaire ? 

Pouvez vous me montrer de quoi il s'agit ? 

Précisez aussi la version du plugin, et voyez si la solution du ticket #770 résout votre souci.

**Comment by btry** [comment]
Ok, j'ai compris: vous êtes la personne qui a ouvert ce sujet sur le forum: http://forum.glpi-project.org/viewtopic.php?id=159173

Si je me souviens bien l'entrée de menu Formulaires est créée par du code JS. Si vous n'avez pas le patch que j'ai fait pour le plugin Alertes, je ne suis pas étonné que le menu disparaisse.

J'attends votre retour pour confirmer cela.

**Comment by thiasou** [comment]
Bonjour,

Merci de votre réponse.

C'est ou j'ai pas compris ou ça ne fonctionne pas:

J'ai remplacé le contenu de news/js/news.js par:

> $(document).ready(function() {
>    var ajax_baseurl = '../plugins/news/ajax';
>    var path = document.location.pathname;
>    // construct url for plugin pages
>    if (path.indexOf('plugins/') !== -1) {
>       var plugin_path = path.substring(path.indexOf('plugins'));
>       var nb_directory = (plugin_path.match(/\//g) || []).length + 1;
>       var ajax_baseurl = Array(nb_directory).join("../") + 'plugins/news/ajax';
>    }
> });
> 
> pluginNewsCloseAlerts = function() {
>    $(document).on("click", "a.plugin_news_alert-close",function() {
>       var alert = $(this).parent(".plugin_news_alert");
>       var id    = alert.attr('data-id');
>       $.post(ajax_baseurl+"/hide_alert.php", {'id' : id})
>          .done(function() {
>             alert.remove();
>          });
>    });
> };
> 
> pluginNewsToggleAlerts = function() {
>    $(document).on("click", ".plugin_news_alert-toggle",function() {
>       var alert = $(this).parent(".plugin_news_alert");
>       alert.toggleClass('expanded');
>    });
> }

et:

>      $PLUGIN_HOOKS['add_css']['news'] = 'css/styles.css';
>      $PLUGIN_HOOKS['add_javascript']['news'][] = "js/news.js";

**Comment by btry** [comment]
Bonjour

Le correctif résout une erreur JS fatale. Vos modifications ont l'air bonnes, mais peut être que vous faites face à un autre souci.

De mon côté, je confirme que le menu est bien créé par du code JS. Ouvrez les outils développeur de votre navigateur, et rendez-vous sur la page où le menu n’apparaît pas.

Vérifiez q'il n'y a pas d'erreur JS une fois cette page chargée. 

Autre chose à vérifier: le menu ne doit apparaître qu'à la condition que l’utilisateur peut utiliser au moins un formulaire. Il faut donc vérifier que vos formulaires sont bien activés, non supprimés, utilisables dans l'entité de l’utilisateur et accessibles par cet utilisateur..

**Comment by thiasou** [comment]
Déjà j'ai cette erreur en mode debug:

PHP Notice: Undefined index: entities_id in /var/www/glpi/plugins/news/inc/alert.class.php at line 498

**Comment by thiasou** [comment]
J'ai bien un profil qui permet d'y accéder (et ça fonctionne quand le plugin news n'est pas activé)
En mode debug le menu apparait.

J'ai sur l'outil developpeur IE11 des problèmes JS.

[https://img11.hostingpics.net/pics/230188Capture.png](url)

**Comment by btry** [comment]
L'erreur PHP est à priori relative au plugin News. Je vous invite à ouvrir un ticket sur son dépôt en précisant sa version et le backtrace de l'erreur dans php-errors.log.

**Comment by thiasou** [comment]
Pour vous le problème peut venir de ça?

**Comment by btry** [comment]
A mon avis, non. 

Je ne peux pas étudier aujourd'hui le backtrace que vous avez relevé dans votre navigateur. Je vous tiens au courant. En attendant, si vous ne voyez pas l'effet du correctif, enlevez  le patch, voyez ce qu'il se passe dans le catalogue de service en interface simplifié avec le plugin News activé. Vous devriez observer que les catégories et les formulaires n'apparaissent pas. Si vous rétablissez le patch, ça doit fonctionner correctement. Auquel cas je vous recommande de garder le patch.

**Comment by thiasou** [comment]
Je ne devrai avoir aucune catégorie?

**Comment by btry** [comment]
Vu #770, c'est possible. Mais focalisons sur votre souci initial de menu. Entre les correctifs pour News, Datainjection il y a plusieurs mois et ceux de Formcreator de cette semaine, il y a pas mal de soucis cosmetiques et fonctionnels résolus.

Je travaillerai sur le backtrace la semaine prochaine. Savoir que News est lié au souci va m'aider.

**Comment by thiasou** [comment]
Pas de problème merci pour votre aide.

**Comment by btry** [comment]
Bonjour

Au vu du backtrace, je dirais que ni GLPI ni Formcreator n'ont de problème. Ca semble être un problème de javascript embarqué dans la DLL des outils développeur du navigateur.

**Comment by thiasou** [comment]
Bonjour et merci pour votre retour,

Quelle solution il y a pour faire fonctionner correctement les plugins ensemble?

**Comment by btry** [comment]
Commencez par mettre à jour Formcreator avec la version RC1 + les correctifs faits depuis: 

https://github.com/pluginsGLPI/formcreator/archive/develop.zip

Vérifiez que vous avez toujours le correctif pour le plugin News, et voyez si ça suffit à résoudre votre problème.

**Comment by thiasou** [comment]
Bonjour,

J'ai bien fais la MAJ et vérifié le correctif et ça me fait toujours la même chose...

**Comment by btry** [comment]
Un autre souci a été identifié sur le plugin Alertes. Dès que le correctif est disponible je vous inviterai à le tester. Il se peut qu'il aide à résoudre votre souci.

**Comment by btry** [comment]
Bonjour

Je pense que vous devriez essayer la dernière révision du plugin News, Il se peut que je souci soit résolu.

**Comment by thiasou** [comment]
Bonjour,

Avec la nouvelle version ça fonctionne à nouveau.

**Comment by btry** [comment]
Merci, alors je clos ce ticket ! Joyeuses fêtes !
