### ISSUE TITLE
affichage suivant un objet GLPI

### ISSUE THREAD

**Issue by judzk** [pluginsGLPI/formcreator#772]
Hello, je découvre le plugin et GLPI et j'aimerais filtrer l'affichage d'une question suivant le choix d'un groupe GLPI dans une question précédente.
![image](https://user-images.githubusercontent.com/26792639/31277753-bffe3968-aaa2-11e7-8921-db16861bdef8.png)

![image](https://user-images.githubusercontent.com/26792639/31277768-d5a81004-aaa2-11e7-81f8-a2648973745e.png)

Ca fonctionne niquel avec un bouton radio, mais impossible comme ca. Je me sers aussi du groupe pour envoyer le ticket au bon destinataire par la suite
Merci d'avance

**Comment by btry** [comment]
Bonjour

Merci de préciser la version de GLPI et la version du plugin.

Il y a peut être un souci dans un cas comme le vôtre. Pouvez-vous essayer de mettre l'ID du groupe dans votre condition, à la place se son nom ? Si ça fonctionne, vous aurez un contournement jusqu'à ce que je puisse corriger. Bien sûr, n'oubliez pas de rapporter le résultat du test.

**Comment by judzk** [comment]
Désolé pour le manque d'info.
GLPI 9.1.6
formulaire 2.5.2
PHP 5.6.31

Pour le test cela fonctionne très bien avec le numéro de groupe.
Merci pour la réactivité ;)

**Comment by btry** [comment]
Donc pour moi c'est un bug. les concepteurs de formulaires trouveront plus ptarique d'utiliser le nom de groupe.

Note pour moi même: voir si les arrangements de la version 2.6.0 corrigent le bug.

**Comment by btry** [comment]
Bonjour

Avec la version 2.7.0-veta.1 + les derniers bugixes, ça fonctionne.

Pouvez-vous faire un essai en environnement de test ? (branche develop)

**Comment by btry** [comment]
Bonjour,

à défaut de retour, je ferme le ticket
