### ISSUE TITLE
Entity not shown correctly

### ISSUE THREAD

**Issue by grvy** [pluginsGLPI/formcreator#773]
When using the self service catalog the entity is shown like this: 

![afbeelding](https://user-images.githubusercontent.com/5603820/31295577-563e26b8-aadf-11e7-8b8c-994d1dc33956.png)

I doubt this is correct? also is there a way I could contribute to the look of the SSP? I have some ideas to improve the flow.

**Comment by btry** [comment]
Hi

The dropdown is not an entity selector, but a profile selector. This is normal.

If you got ideas to improbe the service catalog, first open an issue to submit them. Once your aideas are validated, you can freely contribute and submmit a PR. Thank you for your interest to contribute.

**Comment by grvy** [comment]
@btry my point was not the self service profile. but the highlighted "Information Technology" below it. (that is our entity) its white on a light gray background which is why you cant see it withjout highlighting it. but its not shown correctly I assume.

**Comment by btry** [comment]
Indeed I understand better, and I reproduce. You're right this is an issue.

**Comment by btry** [comment]
Hi

Can you try this fix and feedback ?

**Comment by btry** [comment]
merged. 

Don't hesitate to submit your suggestions to improve the plugin; your contributions are welcome.
