### ISSUE TITLE
[Feature] Hover in the self service portal

### ISSUE THREAD

**Issue by grvy** [pluginsGLPI/formcreator#780]
When hovering over the links in the self service portal its not clear they are links unless you go over the image. Please give it a hover effect so users understand they can click there. Make it 'light up' or something. 

Also rename "Request for Assistance" as this shows the tickets you should rename this to Tickets or Assistance but the sentence is too long.

**Comment by btry** [comment]
Hi

After a check, in self service all links show a hand with straight index  when hovering anchors.  think this issue is solved.
