### ISSUE TITLE
[Translate] Dutch

### ISSUE THREAD

**Issue by grvy** [pluginsGLPI/formcreator#783]
Hello I was working on the dutch translations, but I dont know how I can test it.. also sometimes I cant save a translation.. 

Is there a way I can test it or?

**Comment by btry** [comment]
Hi

### If you're comfortable with composer
I'll add soon some enhancements to the build tools to help you (see #788). To use it you need composer, robo.li (will be installed by composer) and msgfmt.

### if you prefer msgfmt
install msgfmt on your system

go to your locales directory and run
```msgfmt nl_NL.po -o nl_NL.mo```
or
```msgfmt nl_BE.po -o nl_BE.mo```
depending on the variant of the langauge you want to translate.

Once compiled, the translation will be available in your GLPI instance

### Notes
I checked status of Dutch language in Transifex. There are two variants: Belgium and Netherland created. They're empty for now. Please consider pushing your contribution to Transifex

**Comment by grvy** [comment]
Hello, @btry i made the adjustments on Transifex itself? what do you mean with empty?

**Comment by btry** [comment]
> @btry i made the adjustments on Transifex itself? 
No: I think the two variants of dutch I found were created long ago, there a several languages in this case.

> what do you mean with empty?
I mean no strig is translated yet.

I think I can help you, but first, I need you describe how you began to translate the plugin. Tell me which files you modified, which command you ran to do any related task or any other useful information.

**Comment by grvy** [comment]
@btry I translated on transifex. In the language there.. i got a few strings, and translated them.. and submitted it.

**Comment by btry** [comment]
OK, I checked deeper the language and I see that some strings are indeed yours.

I still need to know where you translated the strings. 
- from the web interface of Transifex ?
- in the file **locales/nl_NL.po** if the plugin ?

**Comment by grvy** [comment]
On the web interface, I stopped after like 10 strings? becuz I didnt know where some strings where used in the interface and depending on usage the translation will change.

**Comment by btry** [comment]
OK.

In short you need to download your strings to your instance of Formcreator with the Transifex command line tool, then compile them into a .mo file. Once done you can see them in action.

To install the tool, follow the instructions on these pages

https://docs.transifex.com/client/installing-the-client
https://docs.transifex.com/client/init
https://docs.transifex.com/client/client-configuration

You also need msgfmt tool. For a debian-like linux run ```apt-get install gettext```

go to the folder of Formcreator and run the following commands
```tx pull -a``` (this will download translations for all languages available)
```msgfmt locales/nl_NL.po -o locales/nl_NL.mo``` (this will compile Dutch for netherlands)

The translations are ready, you can use the plugin to see your strings in action.

If you're comfortable with PHP, have a look into **locales/glpi.pot** this template contains comments which may help you to know where in the source code is a localazable string. Reading the source may help you to identify the context of a string.

**Comment by grvy** [comment]
Hello @btry i did my best and I think I translated everything I could. I'm not sure if its 100% accurate. But yeah. I just did it on the transifex interface. Feel free to review. I will use your method to see them in action and verify/change the strings when needed.

**Comment by btry** [comment]
well... you did it fast !

I don't speak Dutch so I'm unable to review your strings. We need an other contributor speaking this language to make a good review. 

I successfully imported and compiled your contribution. I let you try the commands I gave to you, to ensure you're able to do it yourself (and when you want). 

If you have problems with these commands, I can share the result of your contribution to make easier for you to test it. Just ask.

Thank you for you contribution !

**Comment by grvy** [comment]
Hello @btry after I use sgfmt locales/nl_NL.po -o locales/nl_NL.mo it doesnt give any feedback. Should something happen? according to tx pull -a I have the files as when I run that as econd time it says its skipping the languages

**Comment by btry** [comment]
msgfmt does give any feedback. If you want to make it more verbose, add ```-v``` argument. It will  tell you the number of translated strings.

As the command did not output anything, check you ahvea new file **locales/nl_NL.mo**. This is the compiled version of your contribution. Having this file present (and populated) is sufficient to have translations in Formcreator.

**Comment by grvy** [comment]
@btry it does have that file. With date of today.  How do I see what version it is?>

**Comment by grvy** [comment]
Reboot helped. awesome.

**Comment by btry** [comment]
Great ! Thank you for your contribution.

Do you think the translation could also be used for Dutch for Belgium ?

Also I think I may close this issue now.

**Comment by grvy** [comment]
@btry it should be fine for Belgium aswell, may not be 100% accurate for them but good enough.

**Comment by btry** [comment]
Thank you, I pushed your contribution on nl_NL to nl_BE to duplicate it.

I close this issue, as you know how to use the translation tools.
