### ISSUE TITLE
[Feature] Search Box (Categories)

### ISSUE THREAD

**Issue by grvy** [pluginsGLPI/formcreator#791]
Hello, 

Im sorry for all the suggestions, but I have many and I wish I could code so I could help you out,  but I can only translate and maybe help with some UI design. If you need me to, I can. Just say the word. 

However I had a suggestion to make a search box with a 'categories' include from the KB, so you can filter your search for knowledgebase articles in the searchbox. 

Kinda like this example I found on google while trying to see how I could help improve the look of the self service portal. As you can see the searchbox has this "All" dropdown. 

http://22cr523khewwd4m82vloko13.wpengine.netdna-cdn.com/wp-content/uploads/2016/07/Homepage-Self-Service.jpg

**Comment by btry** [comment]
Hi

> Im sorry for all the suggestions, but I have many and I wish I could code so I could help you out, but I can only translate and maybe help with some UI design. If you need me to, I can. Just say the word.

You're welcome to suggest ideas. The soruces are available so you can fork the project, do some changes freely, and create a Pull Request (PR) to ask for review and merge into the mainstream repository (here).

> However I had a suggestion to make a search box with a 'categories' include from the KB, so you can filter your search for knowledgebase articles in the searchbox.

I think your idea is already implemented. Have a look into the dropdowns of GLPI to create / edit form categories of this plugin. You can link a form  category to a KB category.

![image](https://user-images.githubusercontent.com/14139801/31583054-95a99d36-b193-11e7-9f72-a89d5671fbee.png)

Doing this will allow the service catalog to search the KB and show results matching the current category and keywords.

![image](https://user-images.githubusercontent.com/14139801/31583059-b8b82d06-b193-11e7-926e-87ad465ff15e.png)

Currently the icon of each result is not customizable, and the search is always done in forms and KB items (if categories are linked).

**Comment by grvy** [comment]
@btry I know this, but I want to be able to filter the search in the service catalog by category aswell.

**Comment by btry** [comment]
You probably can build similar trees in KB categories and form categories in order ti easily link them one by one.

Is is not sufficient to browse for a category on the left side and optionnaly add keywords in the search box?

The result is filtered by these two criterias.

**Comment by grvy** [comment]
Hello @btry I tested this, it is indeed filtered by the categories aswell. I didnt realize this. You can close this, as that is indeed sufficient.

**Comment by btry** [comment]
Hi,

Thank you for your feedback I close.
