### ISSUE TITLE
Validation case

### ISSUE THREAD

**Issue by ELCHERGUI** [pluginsGLPI/formcreator#792]
Salam, 
Hi All,
I have a proposition, can you add new type of validation in the forme creation.
Exemple: whene an user wanna require a service, validation case will be filled automaticaly by his manager N+1 the choose a validator or group validator

**Comment by btry** [comment]
Hi

In  version 2.14.0 yo uwill be able to set a supervisor to your users, then use "requester supervisor" as validator. See the screenshot below.

![image](https://user-images.githubusercontent.com/14139801/233645390-18b14b30-50fb-4e63-91c2-3dced7427b14.png)
