### ISSUE TITLE
Message d'erreur lors de l'upgrade

### ISSUE THREAD

**Issue by Mosa276** [pluginsGLPI/formcreator#794]
Bonjour,

j'ai un message d'erreur lors de l'upgrade de la version 2.5.2 en 2.6.0 sur un GLPI 9.2

`Changement de la structure de la base de données - glpi_plugin_formcreator_answers (0 seconde)
2.5.2 multiple alter in glpi_plugin_formcreator_answers - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_answers` ADD INDEX `plugin_formcreator_question_id` (`plugin_formcreator_question_id`) - L'erreur est La clé 'plugin_formcreator_question_id' n'existe pas dans la table`

**Comment by btry** [comment]
Bonjour

Avez vous lancé plusieurs fois l'upgrade pour uen raison quelconque ?

Il doit y avoir un backtrace de l'erreur dans glpi/files/_log/migration_to_2.6.0.log. Pouvez-vous le joindre ici ?

**Comment by btry** [comment]
Le bug a été reproduit en situation réelle d'upgrade, mais je ne le reproduis toujours pas pour investigation.

Du fait que le plugin n'initie pas lui même un changement d'index tel que décrit dans l'erreur SQL, il se peut que la requête fautive soit générée par la classe Migration. Cela expliquerait aussi l'absence constatée de backtrace dans le fichier de migration.

**Comment by btry** [comment]
Bonjour

Un autre doublon de votre souci a été créé. Il 'ma permis de trouver la solution. Veuillez vous référer à #816  pour vérifier mon hypothèse.
