### ISSUE TITLE
Bug Location error on form opening

### ISSUE THREAD

**Issue by kleverson4g** [pluginsGLPI/formcreator#795]
Every time the user opens a call through the form, it ignores the existing location reprieve in glpi and does not inform the called which location of the user, this test was performed in version 9.1.6 of glpi and in the latest version of plugin formcreator.

**Comment by btry** [comment]
Hi

To be sure I understand: do you mean you expect the location of a user to be assigned to a generated ticket ?

![image](https://user-images.githubusercontent.com/14139801/31684964-be8013c6-b381-11e7-93ea-e799aabbcfc1.png)

![image](https://user-images.githubusercontent.com/14139801/31684969-c24c44a2-b381-11e7-9d1f-70cc13080548.png)

**Comment by btry** [comment]
An encoding issue was solved recently in the future 2.6.1 version of the plugin, which impacted the rules engine in similar cases.

Please consider testing GLPI 9.2 with the develop branch of the plugin to check if the issue still occurs.

Versions of the plugin for GLPI < 9.2 reached end of life and are no longer maintained (actually you're probably using the last version of the plugin which is compatible with your instance of GLPI: it is version 2.5.2, and it is no longer the lastest as 2.6.0 is out).

**Comment by kleverson4g** [comment]
This has already been tested, so I'm still not sure how to migrate to version 9.2, I would like to continue using 9.1.6, can you correct for this version?
Thank you and understand that it is not only I who suffer from this and yes several users.
Thank you very much

**Comment by btry** [comment]
Hi

I think I got the issue. Please try the patch in #802 and feedback. I worked successfully for me.

**Comment by btry** [comment]
Also, please note this will work only of the generated ticket has only one requester. If there are several requesters, the location will not be copied from any requester. 

This is by choice because I cannot guess which requester should be userd as "source". Using the first requester is an option but this introduces a special meaning for him which seems in my opinion a source of headache for users.

**Comment by btry** [comment]
A final note as you answered while I was searching for your bug.

Currently there is no plan to release a new version of 2.5.x, but the code causing you trouble did not changed (or very few) between version 2.5.x and 2.6.0. This makes the patch easily backportable to versions 2.5.x. 

Feel free to keep a patched version of the plugin, the best would be by forking the repository and cherry-pick the commits of the patch.

**Comment by kleverson4g** [comment]
I can not change it! if possible
Can you please send me this edited file by email?
kleverson4g@gmail.com

**Comment by btry** [comment]
Please confirm you use the release 2.5.2 and I'll send you the patched file.

**Comment by kleverson4g** [comment]
Yes, I'm in this version.
thank you

**Comment by btry** [comment]
You can download the patches file from this link.

https://raw.githubusercontent.com/btry/formcreator/feature/795_for_2-5-2/inc/targetticket.class.php

Replace the file with the patched one, test and feedback.

**Comment by kleverson4g** [comment]
Many thanks worked out perfectly
God bless.

**Comment by btry** [comment]
Thank you for your feedback. Please keep carefully a copy of the plugin with the patch. From time to time I cleanup obsolete data in my fork, and the download URL will die.

I heavily recommend you to consider update to GLPI 9.2. You said you unsure about how to migrate to GLPI 9.2. If you need help you may : 
- ask to the community with the forum ( http://forum.glpi-project.org/ ) or irc ( #glpi on freenode)
- request for paid support to Teclib' ( contact@teclib.com ) or a partner ( http://glpi-project.org/spip.php?article300 )

**Comment by mrcssilvasouza** [comment]
Dear,

I use GLPI 9.1.3 and plugin 2.5.2 and it did not work with this change. Utlizo or GLPI 9.1.3 for being the only stable version.
