### ISSUE TITLE
Error to assign applicant location.

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/formcreator#796]
Dear,

All 2.4.x versions are having trouble assigning the location of the call by copying the user's location. The rule works perfectly for calling, but either creating a form does not work. For now I have to use version 0.90.1.3.4. Can someone help me?

**Comment by btry** [comment]
Hi

I guess you have a business rule to copy the user's location to the generated ticket ? 

![image](https://user-images.githubusercontent.com/14139801/31690359-cb97b954-b392-11e7-8d35-874ea976b932.png)

Please consider trying GLPI 9.2 with the release 2.6.0 , or better, the develop branch of the plugin (because there are a lot of bugfixes ready for the future release 2.6.1). Versions < 2.6.0 are no longer maintained, and versions 2.6.x are compatible with GLPI 9.2 only.

**Comment by mrcssilvasouza** [comment]
Hi,

the problem is that version 9.2 continued with the errors in the header of the call, as I mentioned in the link https://github.com/pluginsGLPI/formcreator/issues/797. So for now I'm using version 9.1.3 (more stable).

**Comment by btry** [comment]
Hi,

I don't see the point with Formcreator. How the plugin interacts with this use case ?

**Comment by mrcssilvasouza** [comment]
I did not understand your question? I have a form created for an entity. I fill in the form, and this one becomes a ticket. The ticket location from user rule should work, but it does not work. The location of the applicant is not copied to the ticket, but if you open a direct ticket it works. In version 0.90.1.3.4 is ok, any other top does not work.

**Comment by btry** [comment]
Hi

I'm sorry: my last comment was for #797. I reposted in the good place.

This issue seems to duplicate #795. Can you check #795 and confirm ?

**Comment by btry** [comment]
Please have a look on patch #802 if your issue is the same as #795.

**Comment by btry** [comment]
Hi

seeing the posts you just sent elsewhere, I'm suspecting an other plugin to affect the behavior of Formcreator. Can you show me the list of active plugins in your GLPI ?

**Comment by mrcssilvasouza** [comment]
Follow.

![print pdf](https://user-images.githubusercontent.com/30185683/31778850-10896c84-b4c8-11e7-8e28-346342a797ed.jpg)

**Comment by btry** [comment]
Keep  the patch for #795 in Formcreator

for each plugin:
* disable it
* try to  reproduce the issue

if the issue disappears after disabling a plugin, re enable all **others** disabled plugins and try again to see if Formcreator still works as expected. 

You may begin by disabling Behaviors which is known to introduce an issue in Formcreator when generating tickets.

Let me know the results.

**Comment by mrcssilvasouza** [comment]
Dear,

I uninstalled everything and reinstalled the Formcreator plugin and it did not work.

![print 2](https://user-images.githubusercontent.com/30185683/31828988-5530d82a-b592-11e7-8d80-bda572a7adf5.jpg)

![print 3](https://user-images.githubusercontent.com/30185683/31829184-edc810da-b592-11e7-8bc7-07881c9597be.jpg)

**Comment by btry** [comment]
Hi

Show me the settings of the target ticket.

**Comment by mrcssilvasouza** [comment]
Not bored, are you referring to the profile or rule?

**Comment by btry** [comment]
Hi

None of these. Go to Administration > Forms > (your form) > tab Targets >  (your target). You'll see a page like this:

![image](https://user-images.githubusercontent.com/14139801/31859155-2d97b276-b708-11e7-9a34-75f7c87c7710.png)

You can also show your rule now. I planned to ask later if needed.

**Comment by btry** [comment]
So your target ticket did not had any requester ? 

When you create a new target ticket the target ticket description shall contain "Form requester". This is by default.

Also note that if you got several requesters the patch will fail (this is by design) because the plugin cannot determine which user will be the "source" for the correct location.

**Comment by mrcssilvasouza** [comment]
Actually, when using 0.90.x version, I did not need to inform, but even adding the requester to the form, only worked after changing the code, because I tested it in another environment and it did not work. Thank you.
