### ISSUE TITLE
Editable fields in the call header even after assigned.

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/formcreator#797]
Dear,

I made several analyzes of GLPI and can be used to use versions 9.1.4 to the current one, since the call opening user can edit the category, urgency, impact, title and description, even after it has been assigned. This can be resolved by removing the save button in the header for those profiles. Has anyone got a solution? They recommended using the escalade plugin, but the locks do not work.

The most stable version is 9.1.3. Note that the description field is editable, but the save button does not appear, so the requester can not further change the information. That's right.

In version 9.2 several fields are editable and with the save button. Validated all and fields and urgency and category, impact, title and description allow to change, even after assigned.

**Comment by btry** [comment]
Hi

This issue is related to tickets in GLPI, am I right ?

**Comment by mrcssilvasouza** [comment]
Yes. 

Is the community already checking this? From 9.1.4 to 9.2 is showing these faults. It is not feasible to use it that way.

**Comment by btry** [comment]
Hi,

I don't see the point with Formcreator. How the plugin interacts with this use case ?

**Comment by mrcssilvasouza** [comment]
Excuse me,

Open the ticket without realizing it was inside the page for the formcreator. In fact this is a problem with the GLPI versions. How do I migrate this discussion? Will I have to open again?

**Comment by mrcssilvasouza** [comment]
Sorry,

Open the ticket without realizing it was inside the page for the formcreator. In fact this is a problem with the GLPI versions. How do I migrate this discussion? Will I have to open again?

**Comment by btry** [comment]
You have to create a new issue here https://github.com/glpi-project/glpi/issues 

To make bugs easy to reproduce consider providing a step by step guide to reproduce your issue. This will help to handle issues better and quicker (also with less questions to the bug reporter). 

Please note also I'm suspecting that the feature you want was actually a bug. I remember about an issue close to the behavior you actually want.
