### ISSUE TITLE
[GLPI 9.2] Self-service wizard view : Table 'glpi.glpi_bookmarks' doesn't exist

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/formcreator#799]
>   Error: Table 'glpi.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins/formcreator/inc/wizard.class.php:114       
  plugins/formcreator/front/issue.php:12             PluginFormcreatorWizard::header()

**Comment by btry** [comment]
indeed: see pr #800

**Comment by btry** [comment]
fix merged
