### ISSUE TITLE
Probleme compteur depuis réinstallation du plugin

### ISSUE THREAD

**Issue by bouboufatal** [pluginsGLPI/formcreator#805]
Bonjour,

tout d'abord merci aux personnes qui maintiennent ce plugin, surtout avec l'arrivée du catalogue de service simplifié.

J'ai voulu faire une réinstallation du plugin, et depuis en mode catalogue simplifié, les compteurs sont à 0 et ne s'affiche plus l'ensemble des tickets ouverts mais seulement les tickets générés via les formulaires...

Ai je raté qq chose ?

Je suis en 2.6 pour le plugin et 9.2 pour GLPI.

Merci...!

**Comment by btry** [comment]
Bonjour

Les compteurs sont calculés à partir d'une table dont le contenu est une copie des tickets et des réponses aux formulaires. C'est un mauvais design, malheureusement imposé par une limitation du SGBD. La bonne solution nécessite un SGBD pouvant gérer des index dans une vue.

Il y a une action automatique qui reconstruit le contenu de la table si une incohérence est détectée. Cherchez les actions automatiques ayant le mot **formcreator**. Il y aura un résultat. Exécutez la manuellement et les compteurs devraient être restaurés.

![image](https://user-images.githubusercontent.com/14139801/31908168-518edda6-b836-11e7-94ec-4aca70a9a22e.png)

Veillez à ce que les actions automatiques soient lancées par une tâche cron (linux) ou du planificateur de tâches (windows).

**Comment by bouboufatal** [comment]
Merci pour la réponse rapide !
Je ne trouve pas la tache auto Syncissues, rien en recherchant avec Formcreator...
Puis je la recrééer cette tâche auto d'une certaine manière ?

Merci

**Comment by btry** [comment]
La tâche est créé à l'installation du plugin. 

Vous ne pouvez pas recréer la  tâche manuellement sans modifier directement la base de données. Avant d'en arriver à une telle solution il faudrait voir pourquoi la tâche n'est pas créée.

Pouvez vous dire la procédure exacte que vous avez suivie pour réinstaller le plugin ?

**Comment by btry** [comment]
En mettant au point un test unitaire pour l'action automatique j'ai trouvé  un bug touchant une installation fraîche et faisant que l'action automatique n'est pas créée. Je pense que votre souci vient de là

https://github.com/pluginsGLPI/formcreator/pull/807

**Comment by bouboufatal** [comment]
Merci pour votre efficacité..!
Pour corriger le probleme de mon côté en attendant la 2.6.1, vous me confirmez que je dois désinstaller le plugin, pour le réinstaller avec les fichiers corrigés?

**Comment by bouboufatal** [comment]
Bonjour,

Super, tout est rentré dans l'ordre :

**Comment by btry** [comment]
Bonjour,

Merci pour votre retour; je ferme.
