### ISSUE TITLE
Dynamic allocation according to a question answer 

### ISSUE THREAD

**Issue by Geeskill** [pluginsGLPI/formcreator#812]
Hello,

I would like to know how to assign a form to a specific group according to the answer to a question?

Thanks.

**Comment by btry** [comment]
Hi

I guess you added a target ticket to your form. Edit this  target ticket. Near of the bottom of the page you see all actors ( requesters, observers and assignees). You can add / delete them, and specify how to use questions to populate the actors

![image](https://user-images.githubusercontent.com/14139801/32097774-e81bab10-bb0a-11e7-9d45-e1a5a31a66d8.png)

![image](https://user-images.githubusercontent.com/14139801/32097823-133ec39a-bb0b-11e7-9169-f973cf019baf.png)
