### ISSUE TITLE
problème d'accent sur un select

### ISSUE THREAD

**Issue by tatoun59** [pluginsGLPI/formcreator#814]
Lorsque dans un select, on a des mots avec des accents, on perd la donnée dans le formulaire.

**Comment by btry** [comment]
Bonjour

Pouvez vous préciser la version de GLPI et la version du plugin ? J'ai aussi besoin de savoir exactement dans quel champ se trouve le problème d'accent. Coté conception de  formulaire  (champs valeur ou valeur par défaut) ou coté utilisateur au moment de remplir un formulaire ?

**Comment by flobidon** [comment]
Bonjour,
Même problème. Côté conception et création du ticket utilisateur, aucun soucis.
Le select permet bien le choix et les accents sont visibles.
C'est une fois que l'on ouvre le ticket (côté user ou assistance) que le soucis se présente: la réponse à la question est vierge si il y a un accent dans la réponse.

**Comment by btry** [comment]
Bonjour,

Même réponse : j'ai besoin de la version du plugin et de GLPI.

Si vous pouvez, essayez la version en développement pour vérifier si le bug est corrigé. Des correctifs déjà faits pourraient influer sur ce bug.

**Comment by flobidon** [comment]
Formcreator 2.6.0
GLPI 9.2

Je vais voir si je peux passer sur la version en cours de dev.

**Comment by btry** [comment]
Bonjour

Je pense que le bug  est identifié et concerne plusieurs types de champ. Voyez la PR #826

**Comment by btry** [comment]
La PR est fusionnée dans la branche de développement. 

@flobidon @tatoun59 je vous invite à tester et m'informer si le bug est corrigé.

**Comment by mickaelambrosini** [comment]
Bonjour,
Après des essais avec la version 9.2.1 de GLPI, le bug est toujours présent.
Pour information, la version de form creator : 2.6.0
A votre disposition pour des essais.

**Comment by btry** [comment]
Bonjour

Avez vous bien utilisé la branche de développement (elle sera marquée 2.6.0, mais ce n'est pas la release) ?
https://github.com/pluginsGLPI/formcreator/tree/develop

**Comment by mickaelambrosini** [comment]
Bonjour,
Je viens effectivement de passer sur la version de développement, mais le bug est toujours présent.
Je viens de tester le select et multiselect.

**Comment by mickaelambrosini** [comment]
Bonjour,
Avez-vous des nouvelles ?
J'ai testé avec la dernière version de dev.
Merci beaucoup d'avance.

**Comment by flobidon** [comment]
Bonjour,
Pour ma part, depuis la 9.2.1, je constate plus le problème dû aux accents. Par contre il est toujours présent si une valeur contient un apostrophe.

**Comment by btry** [comment]
Bonjour

@flobidon regardez le fichier sql-errors.log. il y a certainement un UPDATE ou un INSERT qui échoue à cause de l'apostrophe.

**Comment by btry** [comment]
Bonjour

@flobidon de ce que j'ai pu reproduire, uen apostrophe provoque une troncature de la valeur à enregistrer. Le texte qui précède l'apostrophe est bien savegardé. De ce que j'ai trouvé c 'est un bug côté GLPI.
https://github.com/glpi-project/glpi/issues/3308
https://github.com/glpi-project/glpi/pull/3309

Je mets en place un contournement jusqu'à la version 9.2.2.

@tatoun59 @mickaelambrosini 
Avec la version de développement et GLPI 9.2.1 je n'ai pas reproduit de souci d'accent. les tickets générés contiennent bien la valeur attendue.

**Comment by flobidon** [comment]
Exact le UPDATE passe en erreur. Je testerai le contournement quand il sortira.

**Comment by btry** [comment]
Le contournement est fusionné dans la branche de développement, vous pouvez l'essayer.

Chose étrange, e n'ai pas eu d'erreur dans les logs au moment de reproduire. Je suis preneur de votre backtrace, pour mémo.

**Comment by flobidon** [comment]
voici l'erreur qui m'avait été remontée sur le INSERT : 

*** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_questions_conditions` (`plugin_formcreator_questions_id`,`show_field`,`show_condition`,`show_value`,`show_logic`,`order`,`uuid`) VALUES (\'168\',\'7\',\'==\',\'Compte utilisateur / Droits d\'acces\',\'AND\',\'1\',\'0fbb86e2-8ade0ded-5a2920fea689a7.11515797\')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'acces','AND','1','0fbb86e2-8ade0ded-5a2920fea689a7.11515797')' at line 2
  Backtrace :
  inc/commondbtm.class.php:504                       
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  plugins/formcreator/inc/question.class.php:1180    CommonDBTM->add()
  plugins/formcreator/front/question.form.php:42     PluginFormcreatorQuestion->duplicate()

**Comment by btry** [comment]
Merci, donc c'est bien un souci d'apostrophe.

Avez vous testé le fix pour GLPI ? Fonctionne-t-il ?

**Comment by flobidon** [comment]
J'obtiens une erreur lorsque je veux mettre a jour le plugin:

Changement de la structure de la base de données - glpi_plugin_formcreator_answers (0 seconde)

2.6.0-dev multiple alter in glpi_plugin_formcreator_answers - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_answers` ADD INDEX `plugin_formcreator_question_id` (`plugin_formcreator_question_id`) - L'erreur est Key column 'plugin_formcreator_question_id' doesn't exist in table

quel est le meilleur moyen pour tester le fix? pour ma part, j'ai juste ajouté un fichier update_dev.php et modifié le setup.php

**Comment by btry** [comment]
Quand on fait une installation fraiche de Formcreator 2.6.0, le plugin n'enregistre pas correctemetn sa version de schema, et sans cettte information, un upgrade va tenter d'upgrader depuis une versio nantérieure à la 2.5.0.

Le souci a été corrigé la semaine dernière. 
https://github.com/pluginsGLPI/formcreator/commit/decaafe5bd85ef01438ccbb3064aba9061475ade

Avez-vous mis à jour le plugin à partir d'un ZIP de la branche de développement  (ou l'outil GIT directement) ?

Je viens de re-tester une installation fraiche du plugin dans sa release .6.0 puis un upgrade vers 2.6.0-dev et ça fonctionne.

Quelle a été la première version installée du plugin ?

**Comment by flobidon** [comment]
la version 2.6.0

J'ai manuellement ajouté un fichier update_dev.php et modifié le setup. 
Je vais télécharger le ZIP de la branche de dev dans ce cas.

**Comment by btry** [comment]
oui, c'est ce qu'il faut faire. Attention, à bien utilsier un environnement de  test !

**Comment by flobidon** [comment]
Je viens de testé (au passage, c'est bon pour la mise à jour après la modification du install.php)
J'ai toujours l'erreur concernant l'apostrophe.
Cependant, rien dans les logs concernant cette erreur.

Mon test est simple. Je créer un nouveau formulaire
Question 1 : Type sélection avec 2 réponses / Valeur 1: Droits d'accès / Valeur 2 : Peu importe
Question 2 : Text Area, ne s'affiche que si la réponse à la question 1 est : Droits d'accès
Question 3 : Text Area, ne s'affiche que si la réponse à la question 1 est : Peu importe

Si je choisis la valeur 1, rien ne s'affiche, contrairement au choix de la valeur 2 qui affiche bien la question 3

**Comment by flobidon** [comment]
Finalement, j'ai bien une erreur dans les logs:

2017-12-27 16:50:47 [6@futglpi]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_questions_conditions` (`plugin_formcreator_questions_id`,`show_field`,`show_condition`,`show_value`,`show_logic`,`order`,`uuid`) VALUES ('189','186','==','Droits d'accès utilisateurs','AND','1','0fbb86e2-8ade0ded-5a43c157eb4648.59081824')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'accès utilisateurs','AND','1','0fbb86e2-8ade0ded-5a43c157eb4648.59081824')' at line 2
  Backtrace :
  inc/commondbtm.class.php:504                       
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  plugins/formcreator/inc/question.class.php:1185    CommonDBTM->add()
  plugins/formcreator/front/question.form.php:42     PluginFormcreatorQuestion->duplicate()

**Comment by btry** [comment]
Si je relis le premier post de ce ticket, le problème ne porte pas sur le fonctionnement des l'afichage conditionnel des champs. Ou alors j'ai perdu un épisode en route.

En tout cas je reproduis; je tâche de faire un fix dans la semaine.

**Comment by flobidon** [comment]
J'utilise l'affiche conditionnel afin de faire un test simple.
Mais pour être dans la ligné du premier post: si mon utilisateur répond au formulaire et choisis la valeur contenant l'apostrophe, la réponse ne s'affiche pas dans la description.

**Comment by btry** [comment]
C'est un problème dans ce plugin: je travaille depuis longtemps à supprimer l'abus d'échappement en tous genre. Il ne faut pas se fier à l'affichage conditionnel pour tester le rendu dans les tickets. 

Cela dit ça révèle un autre bug :). Je vais re-vérifier le patch.

**Comment by flobidon** [comment]
C'est pour ça que j'ai pousser mon test depuis une demande utilisateur pour valider le problème avant ma dernière réponse.
Je suis dispo si besoin pour tester le futur patch.

**Comment by btry** [comment]
Bonjour 

Avec la version 2.6.1, je ne rencontre pas de problème : les caractères accentiés et les apostrophes sont bien gérés. Le test a porté sur un champ de type **select**.

**Comment by flobidon** [comment]
Bonjour,

Je confirme, plus de problème avec la v2.6.1
Mes tests ont portés pour l'instant sur un select/multiselect.

Beau boulot

**Comment by btry** [comment]
Merci pour le retour, je ferme.
