### ISSUE TITLE
Perte mise en forme 'Description'

### ISSUE THREAD

**Issue by flobidon** [pluginsGLPI/formcreator#817]
Bonjour,
Je rencontre un problème de mise en forme pour le champ description:
une fois le ticket créé, la description affiche bien le ##FULLFORM## lors du traitement.
Mais si je qualifie la catégorie, change le niveau d'urgence ou l’attribution du ticket ... et que je sauvegarde les modifications ->le champ description remplace les 'enter' par 'rn' et affiche les balises les une après les autres sans tenir compte de la mise en forme initiale.

GLPI 9.2
Formcreator 2.6.0

**Comment by btry** [comment]
Bonjour 

Je suis sur une autre partie du plugin en ce moment, mais j'aimerais savoir tout de même pourquoi vous fermez le ticket (test de la version de dev, fausse alerte, contournement ?). Ca m'évitera de chercher pour rien si le bug n'existe pas/plus.

**Comment by sigin** [comment]
Bonjour,

This issue is also happening to me. I have the same versions as flobidon.

**Comment by btry** [comment]
Hi @sigin 

Then I reopen the issue. I'm still on an other part of the plugin.

**Comment by sigin** [comment]
@btry , 
Now that I've changed the "Use rich text for helpdesk" to "yes" this issue isn't happening anymore. So it seems it's only happening to anyone that prefers to not use rich text.

**Comment by btry** [comment]
Thank you this is very helpful to know which lines of code cause the issue. I'll let you know as soon as I find the fix.

**Comment by flobidon** [comment]
j'ai fermer le ticket car ce n'est pas un bug formcreator mais GLPI 9.2.

https://github.com/glpi-project/glpi/issues/2870

avec une modif du code et l'utilisation du rich text, le problème semble être résolu en partie (un décalage des infos se génère sur une partie de la description).

**Comment by btry** [comment]
D'accord, c'est une bonne nouvelle. Merci pour le test.

@sigin: @flobidon said the fix for GLPI he mentioned solved the issue. I suggest you test and validate it too. The fix is merged then it will be available in GLPI 9.2.1 (very soon).

@flobidon: if you think the shift you observed is an issue in the plugin then open a new ticket for it. I expect to deliver a version 2.7.0 beta of the plugin soon with a bit code refactor + a pending contribution. Once done I'll continue bugfixes, and release a final 2.7.0.

**Comment by btry** [comment]
Note: #840 may affect this issue. Need to validate it for merge before finding a patch.

**Comment by flobidon** [comment]
Depuis MAJ en GLPI 9.2.1
2 issues : 
-Si le rich text est activé, tout est OK (plus de décalage des informations non plus)
-Si le rich text n'est pas activé, GLPI remplace les 'enter' par des 'n' (sans même avoir à qualifier la catégorie, ou l'urgence comme indiqué dans mon premier post)

**Comment by btry** [comment]
Bonjour

Je vous inviterai à tester la version de développement du plugin une fois le correctif #840 fusionné, pour vérifier si le souci évolue.

**Comment by btry** [comment]
Hi 

I merged the patch #840. With the other patches in the development branch, the plugin should run better. Can you try it ?

**Comment by flobidon** [comment]
Yes, I test it as soon is possible

**Comment by btry** [comment]
Hi

@flobidon Any feedback with Formcreator 2.6.1 or the patch ?

**Comment by flobidon** [comment]
Bonjour, 
depuis la v2.6.1, les résultats des tests sont quelques peu différents de mon précédent post:
2 issues :
-Si le rich text est activé, tout est OK (plus de décalage des informations non plus)
-Si le rich text n'est pas activé, GLPI remplace les 'enter' par des 'n' (sans même avoir à qualifier la catégorie, ou l'urgence comme indiqué dans mon premier post) donc un paragraphe sur plusieurs lignes se retrouvera sur une seule ligne (seul les espaces restent).
Cependant, pour cette seconde issue, si je qualifie mon ticket (catégorie, urgence ...) la mise en forme globale du ticket reste la bonne (càd les 'enter' entre les sections et les numéros de question).

J'espère être assez clair.

**Comment by btry** [comment]
Je pense avoir compris. Je tente de reproduire bientôt.

**Comment by btry** [comment]
Bonjour 

le patch #905 devrait résoudre les soucis de rendu des champs dans les tickets et changements générés.

Vu qu'i la fallu refactorer le code touchant à tous les champs, si vous le pouvez, essayez un maximum de types de champs, aussi bien en mode  txte riche qu'en mode normal.

Pour ma part, j'ai corrigé tout ce que j'ai pu trouver.

Je souiate intégrer le correctif dans la version 2.6.2, et je souhaite releaser très rapidement.

**Comment by btry** [comment]
Fix released in 2.6.2. Some feedbacks, all positive.

If the issue persists, please open a new ticket.
