### ISSUE TITLE
Version 2.6.0  Not saving specific category

### ISSUE THREAD

**Issue by carlosbmc** [pluginsGLPI/formcreator#822]
In Target ticket:

I'm selecting "ticket category" ->> "specific category"  and then selecting the category

but after "save" (->> Item successfully updated )  the "Ticket category" returns to "Category from template or none"

**Comment by btry** [comment]
Hi,

Two possibilities:
- the value is not saved in DB
- or the value is not retrieved when displaying the form

I'm working hard on something else in the  plugin then please be patient.

**Comment by btry** [comment]
Also please tell if you're using the release version or the develop version

**Comment by carlosbmc** [comment]
I think the value is not saved in database.
Release version 2.6.0
https://github.com/pluginsGLPI/formcreator/releases/download/2.6.0/glpi-formcreator-2.6.0.tar.bz2
Thank you

**Comment by btry** [comment]
Hi
I don't reproduce with the release 2.6.0, not with the current development branch.

Can you reproduce it again, and see if there is something relevant in sql-errors.log and php-errors.log ?

**Comment by carlosbmc** [comment]
No errors in sql-errors.log and php-errors.log 
But impossible to assign category

**Comment by carlosbmc** [comment]
Same error after upgradin 9.2.1 
https://drive.google.com/open?id=1WoCIS0aF_TP5Y_4VP1bgLrlu3FE4TWIc

**Comment by btry** [comment]
Hi

Please identify in your database the target ticket of your issue, (or create a new target ticket and check the highest ID of target tickets in your DB).

Reproduce the issue and check the columns **category_rule** and category_question**. 

FYI: the table containing the target tickets is **glpi_plugin_formcreator_targettickets**

**Comment by carlosbmc** [comment]
For "Sistemas Hardware" category_rule="", and  category_question =41

"4","Sistemas Hardware","1","<p>##answer_2##
</p>",,"0","-30","minute","none","0","none","0","1","specific","2","none",,,,"41"
"3","Comercial","1","<p>##FULLFORM##</p>",,"0","-30","minute","none","0","none","0","1","current",NULL,"none",,,,"78"
"5","##answer_4##","9","<p>##answer_5##</p>",,"0","-30","minute","none","0","none","0","1","specific","11","none",,,,"71"
"6","JHGHJG","0","<p>##FULLFORM##</p>",,"0","-30","minute","none","0","none","0","1","form",NULL,"none",,,,"78"

**Comment by kedson42** [comment]
Hi guys, I'm having the same problem with GLPI 9.2 and Formscreator 2.6.0.

Have you found any solutions yet?

**Comment by btry** [comment]
Hi 

I think your began to use the plugin starting from version 2.6.0. I found an inconsistency when creating the schema, making a column missing. I sucessfully reproduced.

Please try this fix and feedback. To use it:
- update the files of Formcreator including the fix
- edit glpi_plugins, find the row for Formcreatir and change the state to the value 6
- un GLPI UI the plugin should be marked "Upgrade". Upgrade it
- check you can save a specific  category

https://github.com/pluginsGLPI/formcreator/pull/867

**Comment by omesquita** [comment]
Hi people! I had same issue. To solve the problem by following fix #867.
Great Job.

Tank's!!!

**Comment by kedson42** [comment]
Hi guys.
We managed to solve the problem by following the fix #867.

Thanks a lot.
