### ISSUE TITLE
Cloture du ticket direct

### ISSUE THREAD

**Issue by wolfyinkbane** [pluginsGLPI/formcreator#823]
Bonjour,
Visiblement par défaut, lorsqu'une solution est donnée au ticket, il arrive dans cloturer directement.
Je préfererai qu'il soit dans résolu, pour que le demandeur cloture lui meme le ticket via la notification email par exemple (sinon a quoi sert la ligne résolu ?)
Sinon, si c'est cloturé, il ne semble pas possible de relancer le ticket en ajoutant un suivi par exemple, il n'y a plus d'action possible une fois clos.
Merci par avance pour votre retour

**Comment by btry** [comment]
Bonjour

Un ticket clos peut être réouvert. Voyez le bouton à côté du statut.

![image](https://user-images.githubusercontent.com/14139801/32567071-63290d8a-c4ba-11e7-954b-b5ac4244ff4d.png)

Pour qu'un ticket soit résolu (mais non clos) au moment d'apporter une solution changez la  configuration de votre entité (onglet Assistance). Par défaut un ticket résolu est clôture immédiatement. Choisissez **Jamais** ou un délai qui vous convient pour maintenir la clôture automatique.

![image](https://user-images.githubusercontent.com/14139801/32567237-fb430bca-c4ba-11e7-99d4-b709121ed917.png)

Ces questions concernent GLPI, il ne me semble pas y avoir de lien avec Formcreator.

**Comment by btry** [comment]
Je clos ce ticket car il n'y a pas de lien avec le plugin, et il semble que vous n'avez plus de question.
