### ISSUE TITLE
Required condition ignored

### ISSUE THREAD

**Issue by andreseliseo** [pluginsGLPI/formcreator#829]
Hi.
GLPI = 9.1.2
Forms = 2.5.2

When creating a question of:
Type: Select
Required: Yes
Show empty: Yes
Default values:
Values: *List of my values*
Description: *My description*
Hidden Unless: *Some condition*

User of the form can avoid to select some value of *List of my values*. He just left the Select field as "-----" and the required condition gets violated.

**Comment by btry** [comment]
Hi 

do you have an opportinuty to check if the bug still occurs with the develop branch of the plugin (requires GLPI 9.2)

**Comment by andreseliseo** [comment]
Hi. Thanks for the quick answer. We are currently generating a lab environment for testing this. We will post the result later.

**Comment by andreseliseo** [comment]
Hi. Me again. The lab environment was created with success. GLPI was updated to v9.2 (be aware of php requiremets for thoose who try this!) and Forms was updated to the actual branch. The issue is still present at this versions. Will preserve this lab for further testing.

**Comment by btry** [comment]
Hi

Yes, please keep this lab. Once I investigated enough, I'll ask you for further information or to test a fix.

**Comment by andreseliseo** [comment]
Hi. Did you have any opportunity to investigate this?

**Comment by btry** [comment]
No: i'm working full time on an other project the whole week. Please be patient.

**Comment by andreseliseo** [comment]
Hi btry! Did you have any oportunity to go through this issue?

**Comment by btry** [comment]
Hi

only a gap to prepare a form to try to reproduce.

**Comment by sebelk** [comment]
Hi @btry I have the same problem that @andreseliseo , your fix will be very welcome, otherwise it's a pain to enforce a support policy.

Thanks in advance

**Comment by btry** [comment]
Hi

Please test the above patch and feedback

**Comment by sebelk** [comment]
Thanks @btry  ! It works

One caveat:

When it results in error, in order to it works again, the page must be refreshed, otherwise menu options does not load options that depend on other items

HTH
SB

**Comment by btry** [comment]
Hi

Yes I noticed the same behavior, but this is an other bug, and it should happen no matter this one occurs or not.
