### ISSUE TITLE
Ajout Workflow

### ISSUE THREAD

**Issue by ITraz** [pluginsGLPI/formcreator#830]
Idée d'ajout dans le plugin
Ajouter un workflow qui permettrais, lorsqu'il y a plusieurs cible à un formulaire, d'attendre qu'un ou plusieurs ticket cible soit clôturer avant d'ouvrir et d'envoyer la notification aux autres cibles.

Exemple: 
Je rempli mon formulaire, 5 cibles sont définis: Service 1, 2, 3, 4 et 5.
Il faudrait que le ticket destiné aux services 3, 4 et 5 ne soit ouvert que lorsque les services 1 et 2 ont clôturé le leur.

**Comment by vinz38500** [comment]
Bonjour
En fait, il faut 1seul ticket et raisonner avec des taches
Nous le faisons avec ProcessMaker qui peut nous gerer des taches parallèles et séquentielles dans un ticket glpi.

**Comment by btry** [comment]
Bonjour

La gestion de workflow sort du cadre du plugin. Je vous invite à étudier ce plugin 
http://plugins.glpi-project.org/#/plugin/processmaker
