### ISSUE TITLE
Errors in change ticket

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/formcreator#837]
Hi,

When the form is destined for change type, the following errors occur:
1. It does not transfer the information from the form to the change ticket description box.
2. The destination name is modified to "formcreator".

In use: GLPI 9.2.1 and Formcreator 2.6.0

**Comment by btry** [comment]
Hi

1. I found that the description is sent to the title of the change. Fixed in the develop version.
2. I think I don't understand this point, I did not noticed anything wrong. Send a screenshot to help me to locate this issue.

**Comment by pedroluisvsousa** [comment]
Hi,
I will treat in this post only the first reported error.

1. Follow the created and filled form that will be sent.
![tela01_formulario](https://user-images.githubusercontent.com/26510405/33932462-c2e31f22-dfd1-11e7-9247-4be131de6ae5.png)

2. Below the change ticket destination setting.
![tela02_configuracao_destino_2](https://user-images.githubusercontent.com/26510405/33932529-ebee8104-dfd1-11e7-9d78-9b44faf4fa70.png)

3. The screens below show the change ticket information created from the form.
![tela03_change_ticket_2](https://user-images.githubusercontent.com/26510405/33932555-fbd05fd4-dfd1-11e7-8dae-b168ade91b4c.png)
![tela04_impacts](https://user-images.githubusercontent.com/26510405/33932577-094b6e2e-dfd2-11e7-9ce1-fa684b0e61e5.png)

Error Description:

Check that the ## FULLFORM ## tag is set for the "Description" and "Impacts" fields (lables 1 and 2). However, the form data is only transferred to the "Impacts" field (label 4) and the "Description" field is empty (label 3).

**Comment by pedroluisvsousa** [comment]
Now the second question.

The below is a destination change ticket for a form. The assigned title is "Change Test" (label 1).
![erro_2-1](https://user-images.githubusercontent.com/26510405/33983582-75fa4f74-e093-11e7-8035-7ab903a5fd7b.png)

After being saved, the name is changed to "formcreator" (labels 2 and 3).
![erro2-2](https://user-images.githubusercontent.com/26510405/33983581-75e2e302-e093-11e7-8b13-85765c8c3a6a.png)
![erro_2-3](https://user-images.githubusercontent.com/26510405/33983580-75ca8af0-e093-11e7-92a3-cec9b7d4c9b2.png)

I believe the correct thing was to preserve the name assigned to the destination of the form. Right?

**Comment by btry** [comment]
I checked, the destination name issue is already fixed in the development branch. 

I'll focus on the 1st issue.

**Comment by btry** [comment]
Hi

The 1st issue seems already fixed too in the development version.

![image](https://user-images.githubusercontent.com/14139801/34357879-05e55334-ea4b-11e7-8d47-49a0fd20ee93.png)

Can you check and feedback, please ?

**Comment by pedroluisvsousa** [comment]
Hi, 
that's ok for this two reported issues on the development version.

Thank you.

**Comment by btry** [comment]
hi

Great, then I close.

Thank you for your feedback.
