### ISSUE TITLE
Pb d'affichage des formulaires

### ISSUE THREAD

**Issue by Quifilius** [pluginsGLPI/formcreator#839]
Bonjour,

j'espère vraiment que vous allez pouvoir m'aider,
J'ai un problème concernant l'affichage des formulaires sur le dashboard dans le menu /Assistance/Formulaire/

j'ai le message d'erreur : "An error occured while querying forms"

[Erreur](http://www.hostingpics.net/viewer.php?id=562492firefox20171207182327.png)

je précise que j'ai cette erreur depuis que j'ai mis à jour le GLPI (9.2.1) et le plugin Formcreator (2.6.0).

D'avance merci pour votre aide.

EDIT : Je précise les versions : 
ubuntu0.16.04.1
PHP 7.0.22-0
Apache/2.4.18
Mysql 5.7.20-0

**Comment by btry** [comment]
Bonjour

Pouvez-vous montrer le contenu de  **glpi/files/_logs/sql-errors.log** ? Il doit y avoir quelques entrées en relation avec votre problème.

**Comment by Quifilius** [comment]
Bonjour,

j'ai aucun logs générés dans le fichier sql-errors.log (l'option "traceurs dans fichiers" pour SQL est bien activé dans les options GLPI)

Et si j’active le mod debug sur la page, j'ai les requêtes suivantes : 

[Requêtes 1, 2, 3, 4, 5](http://hpics.li/e741fcc)
[Requêtes 6, 7](http://hpics.li/44d64f9)
[Requêtes 8, 9](http://hpics.li/473c4ba)

Je test les requêtes une par une et aucune ne me donne la liste des formulaires ...

Merci.

**Comment by btry** [comment]
A priori, si vous n'avez rien dals sql-errors.log, c'est que vous n'avez pas d'erreur SQL.

Au vu du code, je pense qu'une requête HTTP échoue. Ouvrez les outils de développeur du navigateur, et tentez de reproduire le bug. Relevez le code de retour HTTP des requêtes à destination de **/plugins/formcreator/ajax/homepage_wizard.php**

**Comment by Quifilius** [comment]
Bonjour,

pour information concernant ce bug, la version dev semble corrigé le problème.
