### ISSUE TITLE
Formulaire avec 2 fichiers et 2 cibles : Configuration non disponible de l'affectation des fichiers

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/formcreator#84]
Impossible dans le cas d'un Formulaire avec 2 champs 'File' et 2 cibles que le premier fichier soit uniquement pour le premier ticket et le second uniquement pour le 2ème fichier.

Attendu : Pouvoir configurer pour chaque cible si le fichier 1 sera joint, si le fichier 2 sera joint, etc.

Actuellement : Aucune configuration disponible, ce qui pose un éventuel problème de confidentialité des données (certaines informations n'ont pas à être visible par certaines personnes).

**Comment by btry** [comment]
Feature was implemented, but is broken. Fix : 753b423d
