### ISSUE TITLE
La question "urgence" ne fonctionne pas

### ISSUE THREAD

**Issue by DaFuQprod** [pluginsGLPI/formcreator#842]
Bonjour, 

J'ai un problème quand j'insère le type de question "urgence".
La question apparaît bien mais lors de la création du ticket, le champs urgence n'est pas modifié.

Pouvez vous m'aider ?

**Comment by btry** [comment]
Bonjour

Précisez la versin de GLPI et du plugin. Vérifiez aussi sql-errors.log et php-errors.log.

**Comment by DaFuQprod** [comment]
La version GLPI est la 9.2.1
Désolé je ne suis pas un pro... Où se trouve les deux log ? (j'héberge glpi sur OVH)

**Comment by vinz38500** [comment]
Bonjour @DaFuQprod 
Dans ton install tu dois avoir un dossier files et dedans un dossier _log

**Comment by btry** [comment]
Merci @vinz38500 

@DaFuQprod : attention à bien sélectioinner le ou les messages pouvant avoir un lien avec votre souci. Ces fichiers contiennent une trace de toutes les erreurs qui ont pu avoir lieu dans la vie de votre instance de GLPI.

**Comment by DaFuQprod** [comment]
Merci @vinz38500 , je vous envoie ça !
[sql-errors.log](https://github.com/pluginsGLPI/formcreator/files/1551131/sql-errors.log)
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/1551132/php-errors.log)

**Comment by btry** [comment]
De ce que je vois, il n'y a apparement pas d'erreur en lien avec un provlème d'urgence pas enregistrée.

Par contre vous avez un sérieux souci de perte de connexion à MySQL. JE pense que c'est à régler en priorité.

Si vous avez une instance de GLPI pour mener des  tests je vous invite à essayer la version en développement du plugin. Il y a beaucoup de correctifs versés.

**Comment by DaFuQprod** [comment]
D'accord... merci ^^
J'installe ça et je reviens vers vous !
Merci beaucoup

**Comment by DaFuQprod** [comment]
Rebonjour,

J'ai installer la dernière version de développement avec wamp et la version 2.6.0 du plugin et j'ai toujours le même problème !

Voulez vous les logs ?

**Comment by btry** [comment]
Vu qu'il n'y a rien eu de notable dans les logs précédents, je pense qu'il serait plus intéressant de faire fonctionner le formulaire moi même. Pouvez vous l'exporter et déposer le fichier ici ?

Pour exporter: affichez la liste des formulaires, cochez le formulaire en défaut, et cliquez sur le bouton **Actions**. Choisissez l'option Exporter. Vous serez invités à  télécharger un fichier. Il contient un export du formulaire.

Précisez aussi la ou les valeurs de l'urgence que vous avez tenté d'utiliser (au cas où).

**Comment by DaFuQprod** [comment]
Voilà : 
[formulaire.zip](https://github.com/pluginsGLPI/formcreator/files/1551629/formulaire.zip)

J'ai essayé avec toutes les valeurs d'urgence possible (très haute, haute, moyenne, basse, très basse)

**Comment by btry** [comment]
Bonjour

Vous avez mis une question pour choisir une urgence, mais vous ne l'avez pas utilisée dans la définition du ticket cible.
![image](https://user-images.githubusercontent.com/14139801/33888641-f43eab06-df4d-11e7-98c8-52d906885415.png)

Modifiez votre ticket comme décrit ci-dessous et ça devrait fonctionner
![image](https://user-images.githubusercontent.com/14139801/33888676-132c3e5c-df4e-11e7-89df-e770bfc229dc.png)

**Comment by DaFuQprod** [comment]
SUPER ! Ça fonctionne, merci beaucoup !
Et beau boulot pour ce plugin soit dit en passant ;)

Bonne journée ^^
