### ISSUE TITLE
QUESTION : Imprimer automatiquement le formulaire

### ISSUE THREAD

**Issue by DaFuQprod** [pluginsGLPI/formcreator#845]
Bonjour !

Y'a t-il un moyen d'imprimer automatiquement un formulaire lorsqu'on le créé ?
Ou imprimer le ticket généré ?

Cordialement

**Comment by btry** [comment]
Bonjour

Il n'y a pas de fonction pour imprimer _automatiquement_ un formulaire. Par contre vous pouvez imprimer _manuellement_ les réponses faites à un formulaire; le plugin offrant la fonctionnalité.

Je vous invite à chercher / demande sur le forum, pour les questions orientée utilisation de GLPI et plugins (impression du ticket généré). Il faut réserver les ticket Github pour les bugs et demandes de fonctionnalités dans la mesure du possible.

Lien vers le forum: http://forum.glpi-project.org/

**Comment by DaFuQprod** [comment]
Merci infiniment et bon courage !
