### ISSUE TITLE
disorganized information

### ISSUE THREAD

**Issue by leandrotenorio** [pluginsGLPI/formcreator#847]
Hello People,

When I open a ticket by means of formcreator the disorganized information. 

I am problem with formcreator, can someone help me? 

follows the attachment
![screenshot_10](https://user-images.githubusercontent.com/8218579/34001105-41be650e-e0d6-11e7-81a4-a80b8503dda2.png)
![screenshot_9](https://user-images.githubusercontent.com/8218579/34001106-41e6a80c-e0d6-11e7-8e0b-e170cb548644.png)

**Comment by btry** [comment]
Ho

Please tell the version of GLPI and the version of the plugin

Note also there are some fixes in t he development version which solve some ticket generation issues and one more incoming in the PR #840 

If you have a testing instance of GLPI (9.2.1 preferred), please test the development version, add the diff of the PR #840 and feedback.

I want to release a version 2.6.1 before the end of the year, so you still encounter issues with the development version, it may be worth to fix it *before*  the next release.

**Comment by leandrotenorio** [comment]
My version GLPI 9.2.1 the FormCreator 2.6.0. 

Regards

Leandro Tenorio

**Comment by leandrotenorio** [comment]
Other doubt, when configuration format the letter, color, general fonts in formcreator, it isnt keeping  the fortmatting in ticket GLPI and e-mail. 

Regards.

Leandro Tenorio

**Comment by btry** [comment]
with or without the patch #840 ?

**Comment by leandrotenorio** [comment]
How do I see this?

**Comment by btry** [comment]
If you don't know, t hen you did not used it. As I advised you to test the latest development + this patch, I thought you gave it a try. 

I suggest you test GLPI 9.2.1 + Formcreator development branch after I merge #840

**Comment by btry** [comment]
Hi

The patch is merged in the development version. Can you try it and feedback ?

**Comment by leandrotenorio** [comment]
Hello, 

I am sorry

**Comment by leandrotenorio** [comment]
I am sorry for I delay in to answer. I tested the version For mCreator Develop, the problem continue, at least in my server.

**Comment by leandrotenorio** [comment]
I'm in the mood if you need anything else.

**Comment by btry** [comment]
@leandrotenorio please tell me if you're in rich text mode.

The setting is in GLPI:  Configuration > General > Assistance

**Comment by leandrotenorio** [comment]
Thanks,  it functioned!!!

**Comment by leandrotenorio** [comment]
Other question, only a doubt.
There´s possibility of a form creator to open a template of project and/or tasks project  in future?

**Comment by btry** [comment]
First, I just wanted you to tell me the state of the rich text mode. The plugin is expected to work no matter the state of this setting. So, what was its state before you switched it ?

There is no plan yet to use projects or tasks. If you're want this feature, please contact us: contact@teclib.com .

**Comment by btry** [comment]
Well, 

By observing carefully the screenshot on your first post, I guess it was disabled.

**Comment by btry** [comment]
Hi

Please test the following patch and feedback. It should solve your issue.

https://github.com/pluginsGLPI/formcreator/pull/865/files
