### ISSUE TITLE
Problem with Greek characters glpi_plugin_formcreator_forms table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#848]
Values saved in glpi_plugin_formcreator_forms in columns 'name' and 'description' appear in html entities in the database.
![1](https://user-images.githubusercontent.com/9021998/34036612-7325889e-e18e-11e7-9fc3-b003bc3890fa.PNG)

**Comment by btry** [comment]
Hi

This issue is solved with 2.7.0-beta.1. Closing
