### ISSUE TITLE
Problem with Greek characters glpi_plugin_formcreator_forms_answers table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#849]
Values saved in glpi_plugin_formcreator_forms_answers in columns 'name' appear in html entities in the database.
![1](https://user-images.githubusercontent.com/9021998/34036689-bfe0df8a-e18e-11e7-8348-ee83c21d5e8e.PNG)

**Comment by btry** [comment]
Hi

This issue is solved with 2.7.0-beta.1. Closing
