### ISSUE TITLE
Problem with Greek characters glpi_plugin_formcreator_issues table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#850]
Values saved in glpi_plugin_formcreator_issues in columns 'name' appear in html entities in the database.
![1](https://user-images.githubusercontent.com/9021998/34036803-16fe4992-e18f-11e7-9df0-4914c16a6595.PNG)

**Comment by btry** [comment]
Hi @grego1981 

I think the issues table should no longer contain any HTML entity now. Can yo uconfirm please ?

**Comment by grego1981** [comment]
I can confirm it works as it should!
Thank you!

**Comment by btry** [comment]
Thank you again, I close
