### ISSUE TITLE
Problem with Greek characters glpi_plugin_formcreator_questions table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#851]
Values saved in glpi_plugin_formcreator_questions in columns 'name' and 'description' appear in html entities in the database.
![1](https://user-images.githubusercontent.com/9021998/34037625-35b43c68-e192-11e7-90f3-7190da613589.PNG)

**Comment by btry** [comment]
Note: fix for the column name already done in #856

**Comment by btry** [comment]
Hi

This issue should be solved now, like all others you reported. If such problem still occurs with latest versions, feel free to open a new ticket.
