### ISSUE TITLE
Problem with Greek characters glpi_plugin_formcreator_sections table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#852]
Values saved in glpi_plugin_formcreator_sections in columns 'name' appear in html entities in the database.
![1](https://user-images.githubusercontent.com/9021998/34037733-8d78b924-e192-11e7-8f86-bb8dedb1d0d8.PNG)

**Comment by btry** [comment]
Note: fix for the column name already done in #856

**Comment by btry** [comment]
#856 was obsoleted. #940 found, and related to the encoding problem. Fix #950 should solve both issues

**Comment by btry** [comment]
Hi 

Can you try the PR #950 and  feedback ?

**Comment by grego1981** [comment]
Hi I'm using 2.6.2 the PR #950 does not match the line numbers.. Do you need me to use the latest development files?

**Comment by btry** [comment]
It is better to apply the patch on the release 2.6.2.

The line numbers don't match but the patch should apply successfully if you use the patch tool.

Which method do you use to apply the patch ?

**Comment by grego1981** [comment]
I usually use linux patch tool, I'll give a try and post here

**Comment by btry** [comment]
Good, this is the right way.

**Comment by grego1981** [comment]
Works as it should, both in the DB and in displayed form.

![capture](https://user-images.githubusercontent.com/9021998/38238169-bad7d72a-3731-11e8-8857-e1465d68b363.PNG)

**Comment by btry** [comment]
Great ! I can close 2 issues :)

Thank you for the feedback.

I still plan the other similar issues you reported for version 2.7.0, except if someone discovers a functional impact.
