### ISSUE TITLE
Problem with Greek characters glpi_plugin_formcreator_targets table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#853]
Values saved in glpi_plugin_formcreator_targets in columns 'name' appear in html entities in the database.
![1](https://user-images.githubusercontent.com/9021998/34037796-c3d75b2e-e192-11e7-93ce-3115fc4038ef.PNG)

**Comment by btry** [comment]
Hi @grego1981

In the re lease 2.6.3 I removed HTML entities in the name column of targets. Then I think this issue is solved now.

Can you confirm please ?

**Comment by grego1981** [comment]
I can confirm it works as it should!
Thank you!

**Comment by btry** [comment]
And here again, thanks !
