### ISSUE TITLE
Problem with Greek glpi_plugin_formcreator_targettickets table

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#854]
Values saved in glpi_plugin_formcreator_targettickets in columns 'name' appear in html entities in the database.

![1](https://user-images.githubusercontent.com/9021998/34037993-63ea954a-e193-11e7-97c3-4e4c23b6ac9f.PNG)

**Comment by btry** [comment]
Hi @grego1981 

In the re lease 2.6.3 I removed HTML entities in the name column of  target tickets. Then I think this issue is solved now.

Can you confirm please ?

**Comment by grego1981** [comment]
I can confirm it works as it should!
Thank you!

**Comment by btry** [comment]
Thank you for jour feedback, I close the issue
