### ISSUE TITLE
Notification formcreator pour un formulaire en attente de validation

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#871]
Bonjour,

J'ai créé un formulaire en précisant un groupe comme valideur.
J'ai également créé une notification avec comme évènement "Formulaire en attente de validation" et comme destinataire "Valideur".
Néanmoins, lorsque le formulaire est créé aucune notification n'est envoyé aux membres du groupe (fichier mail.log non renseigné). Cependant, les personnes faisant partie de ce groupe ont bien le droit de valider ou non le formulaire lorsqu'elles sont connectés sur GLPI.
Alors que si je met un utilisateur simple comme valideur, celui-ci reçoit bien les notifications.

Version de FormCreator : 2.6.0
Version de GLPI : 9.2.1

**Comment by btry** [comment]
Bonjour

A première vue, je pense que la notification échoue à convertir un groupe en une liste d'utilsaiteurs.

**Comment by lolokai** [comment]
Petite précision : sur la version précédente de formcreator cela fonctionnait parfaitement bien.

**Comment by btry** [comment]
Pouvez-vous préciser la version exacte ?

**Comment by lolokai** [comment]
Oui il s'agissait de la version 2.5.2

**Comment by lolokai** [comment]
Avec GLPI 9.1.6

**Comment by btry** [comment]
Merci. Je regarderai après la release de la 2.6.1. Cela fait trop longtemps que repousse sa release.

Vérifiez les logs SQL et PHP au cas où il y aurait une erreur en lien avec le bug.

**Comment by lolokai** [comment]
Pour info : Pas d'informations ni dans les fichiers SQL / ni PHP

Bonne année ;)

**Comment by hiscorebob** [comment]
Bonjour,

J'ai exactement le même comportement décrit par lolokai. Je confirme cette regression introduit par la version 2.6.0 
Cordialement,

**Comment by btry** [comment]
Bonjour

Quelle est al dernière version qui a fonctionné correctement pour vous ?

Ca peut m'aider à identifier le code fautif.

**Comment by lolokai** [comment]
Comme indiqué : la version 2.5.2 fonctionnait bien

**Comment by btry** [comment]
Je pense que ce correctif fera l'affaire. 

Pouvez-vous me faire un retour ?

**Comment by hiscorebob** [comment]
Le correctif fonctionne. Les notifications des formulaires en attente sont bien envoyés maintenant.

**Comment by btry** [comment]
Merci pour le retour. La correction sera disponble à la prochaine release.

**Comment by lolokai** [comment]
@hiscorebob : tu utilises la version 2.6.0 ou la 2.6.1 ? Sur la 2.6.1 cela ne semble pas fonctionner

**Comment by hiscorebob** [comment]
J'ai fait la modification sur la 2.6.0

**Comment by lolokai** [comment]
@btry tu peux jeter un oeil ?

**Comment by btry** [comment]
J'ai fait le correctif à partir de la version de développement de ce jour. C'est la version 2.6.1 + un premier patch pour la prochaine version.

Le patch doit fonctionner aussi bien pour 2.6.0 que 2.6.1, et en faisant une session de debug, l'erreur m'a paru bien claire, sans aucun doute possible.

@lolokai si vous avez les connaissances suffisantes en PHP, je vous invite à provoquer l'envoi de mails à un groupe et capturer le contenu de la variable $query dans la méthode concernée par le patch.

En la jouant avec un outil comme phpmyadmin vous pourrez voir le résultat de la requête. Une requête fautive va avoir une clause WHERE groups_id = 0.

**Comment by lolokai** [comment]
Ok je jète un oeil et je vous tiens au courant.

Merci ;)

**Comment by btry** [comment]
Voilà un exemple de requête sans le patch

```sql
SELECT DISTINCT `glpi_users`.`id` AS users_id,
 `glpi_users`.`language` AS LANGUAGE
FROM `glpi_groups_users`
INNER JOIN `glpi_users` 
ON (`glpi_groups_users`.`users_id` = `glpi_users`.`id`)
INNER JOIN `glpi_profiles_users` 
ON (`glpi_profiles_users`.`users_id` = `glpi_users`.`id` AND (`glpi_profiles_users`.`entities_id` = '0'))
INNER JOIN `glpi_groups` 
ON (`glpi_groups_users`.`groups_id` = `glpi_groups`.`id`)
WHERE `glpi_groups_users`.`groups_id` = '0' AND `glpi_groups`.`is_notify`
```

**Comment by lolokai** [comment]
Après revérification je confirme que ça fonctionne bien.

Sujet à clore donc ;)

**Comment by btry** [comment]
Parfait; merci pour le retour.
