### ISSUE TITLE
Some keys in translation doesn't work

### ISSUE THREAD

**Issue by hotdesc** [pluginsGLPI/formcreator#873]
doesn't work:
`__('Form category')`

work: 
`_n('Form category', 'Form categories', 2, 'formcreator')`

Example -> 

file: form.class.php

```
$tab[] = [
         'id'                 => '10',
         'table'              => 'glpi_plugin_formcreator_categories',
         'field'              => 'name',
         'name'               => _n('Form category', 'Form categories', 2, 'formcreator'),//__('Form category'),
         'datatype'           => 'dropdown',
         'massiveaction'      => true
      ];
```

**Comment by hotdesc** [comment]
`__('Homepage', 'formcreator')`

**Comment by btry** [comment]
Hi

I think singular is better because a form can be linked to one category only.

https://github.com/pluginsGLPI/formcreator/pull/874/files
