### ISSUE TITLE
mise en page du ticket destinataire

### ISSUE THREAD

**Issue by jc-j** [pluginsGLPI/formcreator#877]
Bonjour,
Ayant fait les mises-à-jour de glpi en 9.2.1 et installer la version 2.6.0 avant noël j'ai eu plein de problèmes de mise en page des tickets créés par les formulaires.
La version 2.6.1 a résolu la majorité des soucis mais un champ "boites à cocher" ne se met toujours pas correctement en page. Il y a des n entre chaque options des boites à cocher.
Je précise que tout cela fonctionnait "avant" avec Formulaires 2.4.0, par contre je ne me rappelle plus exactement quelle version de glpi j'avais. Les mises à jours se sont passées sans problèmes apparents.
Merci

**Comment by btry** [comment]
Bonjour

Vous décrivez deux bugs. Pouvez vous créer un second ticket pour votre 2e bug, et éditer celui-ci pour ne laisser que le premier ?

**Comment by btry** [comment]
Bonjour

De ce que j'ai trouvé il n'y a pas que les boites à cocher qui connaissent un souci de formatage.

Essayez ce correctif, et n'hésitez pas à tester tous les types de champs, avec ou sans mode  texte riche.

#905

J'ai fait pas mal d'essais et il me semble bon

**Comment by btry** [comment]
This issue duplicated #817
