### ISSUE TITLE
Limiter la liste des sujets non pas par profondeur mais par parent

### ISSUE THREAD

**Issue by PlowRaiser** [pluginsGLPI/formcreator#878]
Est il possible de filtrer une liste 
Par exemple mon catalogue d'application se compose comme suit : 

Demande de service > Application
Demande de service > Communiquer collaborer
Demande de service > Droits d'accès et sécurité

Lorsque je clique suis dans un formulaire pour saisir une demande Communiquer et collaborer je voudrais afficher uniquement les sujets de demande dont le parent est Droits d'accès et sécurité

![image](https://user-images.githubusercontent.com/13099470/34529513-95ac6f54-f0ac-11e7-8589-1879f1be9f93.png)

**Comment by btry** [comment]
Bonjour

La fonctionnalité n'existe pas pour le moment. Vous pouvez nous contacter à l'adresse suivante si vous voulez la sponsoriser : contact@teclib.com

**Comment by btry** [comment]
Bonjour

Il est maintenant possible pour l'ensemble des intitulés et objets arborescents de resteindre les éléments profondeur et par Une racine de sous-arbre. Je pense que ce sujet est donc résolu.
