### ISSUE TITLE
Changer le type de ticket

### ISSUE THREAD

**Issue by gregfly26** [pluginsGLPI/formcreator#879]
Bonjour,
Je suis en GLPI 9.2.1 et FromCreator 2.6.1
Est-il possible d'ajouter lors de la destination "ticket", la possibilité de fixer si c'est une demande ou un incident ?
Car j'utilise des catégories différentes dans GLPI suivant le type, et là, le formulaire se convertit en ticket d'incident, avec une catégorie qui n'existe que dans demandes ...
Merci d'avance.

**Comment by ladenree76000** [comment]
pour l'instant il faut utiliser un gabarit de ticket "demande"

**Comment by gregfly26** [comment]
Bonjour,
Effectivement, cela fonctionne !
Merci pour votre aide.
