### ISSUE TITLE
Champs "Masqué par défaut, sauf si" n'apparait jamais dans le ticket

### ISSUE THREAD

**Issue by jc-j** [pluginsGLPI/formcreator#880]
Bonjour,
Un champ ayant la propriété "Masqué par défaut, sauf si" ne s'affichera jamais dans le ticket même si le "sauf si" est valide.
Je précise que tout cela fonctionnait "avant" avec Formulaires 2.4.0, par contre je ne me rappelle plus exactement quelle version de glpi j'avais. Les mises à jours se sont passées sans problèmes apparents.
Merci

**Comment by btry** [comment]
Bonjour

Vous observez ce comportement avec des types de champs particuliers et/ou des valeurs particulières, ou bien pour vous cela ne fonctionne pas du tout ?

**Comment by jc-j** [comment]
Bonjour
Cela ne fonctionne pas du tout.
Je décris : J'ai un premier champ (bouton radio avec 4 possibilités). Suivant ce qui est coché, cela fait apparaitre les champs suivants. Pour cela, les champs suivants ont la propriété "Masqué par défaut, sauf si" et la condition dépend du premier champ (bouton radio) et de ce qui est coché.
Merci

**Comment by btry** [comment]
bonjour 

Je viens de faire un essai avec un formularie simple: des boutons radio avec les choix a b c et d et un champ de texte. Pour moi ça fonctinne avec la version 2.6.1 + mes premiers patchs.

Soit le bug est déjà résolu, soit les valeurs de vos boutons radio ont des particularités  (apostrophes, caractères accentués).

Pouvez-vous me montrer les valeurs de vous boutons radio, pour que je tente de reproduire avec les elles ?

**Comment by andreseliseo** [comment]
Hi,
We have the same issue with GLPI 9.2 and forms 2.6.1 last commit. This kind of questions (with option "hidden unless") does not get a number in description of ticket ##FULLFORM##. The only questions getting numbers 1), 2), 3) are those with option "Always displayed". 
This didn't happen on version 2.5.2 and GLPI 9.1

**Comment by btry** [comment]
Hi

Thanks, I think this will be helpful to find what happens.

**Comment by eckorion** [comment]
Bonjour,

Je reproduit un dysfonctionnement similaire voilà comment:
question 1 choix : 1,2,3
question 2  choix : 1,2,3
question 3 choix : 1,2,3 masquée sauf si q2 = 3
question 4 masquée sauf si q1 = 1 ou  q2 = 1 ou q3 =1

En fait la question 4 n'est visible que lorsque la question 3 est visible et = 1 même si q1 ou q2 sont = 1

Voilà, j'espère que ça peut vous aider.

Bonne journée

**Comment by flobidon** [comment]
Bonjour,

Même problème pour moi depuis que je suis passé sous la v2.6.1 (GLPI 9.2.1).
Tous mes formulaires qui comportent une zone de texte qui sont masqué sauf si la réponse à une question est définie, ne renvoient plus les réponses dans le fullform.
Si je passe cette zone en 'toujours visible', plus de problème.
Assez contraignant sachant que pour certains formulaire, la zone de texte est le descriptif du problème utilisateur, donc rien n’apparaît pour les techniciens.

Dispo pour test

**Comment by btry** [comment]
Hi

 Please test the above patch and feedback

**Comment by flobidon** [comment]
Hi,

I confirm, the patch fix the problem.

Thanks

**Comment by eckorion** [comment]
Bonjour,
En ce qui me concerne, une partie du problème est toujours présente, il est nécessaire que toutes les questions entrant dans la condition soient "visibles". Si l'une d'entre elle ne l'est pas, le test ne fonctionne pas.
Cordialement

**Comment by btry** [comment]
Donc le patch fonctionne pour un cas simple (2 questions dont une est masquée selon l'autre), mais votre cas, plus complexe, échoue toujours. C'est cela ?

**Comment by flobidon** [comment]
effectivement de mon côté, je n'ai que des cas simple d'utilisation tel que décrit par btry.
Je vois si je peux faire un test.

**Comment by btry** [comment]
Si un scénario à 3 questions plante, il peut être utile. Moins il y a de questions plus ce sera facile à examiner.

**Comment by flobidon** [comment]
je viens de tester avec 3 questions.
Q2 s'affiche que si Q1 = R2
Q3 s'affiche que si Q1 = R2 et Q2 = R3

Effectivement, dans la description n’apparaît que la réponse à Q1 (manque la réponse à Q2 & Q3)

**Comment by eckorion** [comment]
Bonjour,
Voici les questions testées:
![image](https://user-images.githubusercontent.com/25478777/35721522-c3056192-07f2-11e8-9292-5113a8d78561.png)
![image](https://user-images.githubusercontent.com/25478777/35721527-c9579376-07f2-11e8-9316-4573935613ae.png)
![image](https://user-images.githubusercontent.com/25478777/35721531-cf46e35e-07f2-11e8-9db7-cd8e93d581eb.png)
Et le résultat lorsqu'on coche R3 dans Q1
![image](https://user-images.githubusercontent.com/25478777/35721553-e28e3ebc-07f2-11e8-94a5-0855e38f0bbf.png)
Q3 n'apparait pas.

Cordialement

**Comment by eckorion** [comment]
Seule la réponse à Q2 permet d'afficher Q3
![image](https://user-images.githubusercontent.com/25478777/35721635-3a6fb9bc-07f3-11e8-9979-33f329761bff.png)

**Comment by btry** [comment]
Bonjour

Je reproduis le scénario. JE remarque que sélectionner la éponse R3 dans Q2 ne fait pas non plus apparaitre Q3.

Par contre, je remarque que Q3 apparait à partir du moment où les deux questions ont un élément sélectionné, et que Q1 ou Q2 vaut R3.

Il me semble que Q3 n'apparait pas car une des questions n'a aucune valeur sélectionnée.

**Comment by btry** [comment]
@eckorion 

Essayez le patch #902; il devrait résoudre votre souci. N'oubliez pas de me faire un retour.

**Comment by eckorion** [comment]
Je viens de faire le test, j'ai toujours la même erreur.

**Comment by btry** [comment]
Etrange. J'ai fait ceci, et j'ai reproduit

![image](https://user-images.githubusercontent.com/14139801/35735644-cd7076e8-0825-11e8-8225-a36e50b8f2a1.png)

![image](https://user-images.githubusercontent.com/14139801/35735628-bbcbab24-0825-11e8-9bf5-1e28af6693ac.png)

![image](https://user-images.githubusercontent.com/14139801/35735630-c0a00d7a-0825-11e8-980c-4d11200b15dc.png)

![image](https://user-images.githubusercontent.com/14139801/35735638-c7793626-0825-11e8-95d1-27b4ad70aac2.png)

A tout hasard, avez vous bien créé q3 **après** q1 et q2 ? J'ai remarqué fin 2017 que les conditions pouvaient ne pas fonctionner si une question Q2 dépendant de Q1 est créée avant Q1. Le fix n'est pas dans 2.6.x mais dans la future 2.7.0.

**Comment by btry** [comment]
Prévisu:

![image](https://user-images.githubusercontent.com/14139801/35735762-20dc122e-0826-11e8-8072-3e1da81782df.png)

![image](https://user-images.githubusercontent.com/14139801/35735765-248bacb8-0826-11e8-8525-cb7e52cf55ee.png)

![image](https://user-images.githubusercontent.com/14139801/35735773-2a981ace-0826-11e8-913c-20441d3728f6.png)

![image](https://user-images.githubusercontent.com/14139801/35735783-2f826f58-0826-11e8-8c82-7f7e7ea609f2.png)

**Comment by eckorion** [comment]
Je pense que c'est parce que vous avez Q2 "toujours visible" s'il y a une condition sur Q2 ça ne fonctionne plus exemple Q2 "masqué par défaut sauf si Q1 = 2"

**Comment by btry** [comment]
ah, oui, j'ai raté ceci. Cela dit ca m'a fait cibler un autre souci.

**Comment by andreseliseo** [comment]
Hi all,
We test the first patch and, in our case, the patch fix the issue. But we only have simple cases. Let us know when the more complex scenario gets solved. And thanks for the patches.

Testing various scenarios, we discover another issue. New line in every "Textarea" box, appears as "n" characters and there is no newline at all. This does not occur in previous commits. Don't know exactly where the issue appears. Is there an open issue for this???

**Comment by btry** [comment]
Hi

> New line in every "Textarea" box, appears as "n" characters and there is no newline at all. 

I think there is already an issue. I remember qomzoke talked about this one or two weeks ago.

I'll work on a other patch soon.

**Comment by btry** [comment]
Hi

The PR #902 should fix all problems related to conditions reported in this issue.

Please feedback.

**Comment by eckorion** [comment]
Hi, 
Great job, it works fine for me!
Best regards

**Comment by btry** [comment]
Great ! Waiting for other feedbacks, and once the PR merged I plan to release the version 2.6.2.

**Comment by flobidon** [comment]
J'ai tester le patch, cela fonctionne pour moi également.

**Comment by btry** [comment]
Good news ! Thank you for your feedback !
