### ISSUE TITLE
Redirection aprés validation du formulaire

### ISSUE THREAD

**Issue by datskill** [pluginsGLPI/formcreator#885]
Bonjour, est-il possible (dans les fichiers du plugins) de modifier la redirection lors de la validation du formulaire ? Actuellement, lors de la validation la redirection est basé sur la liste des formulaires, cependant je préfèrerais une redirection sur les tickets ou la page d'accueil. Merci.

**Comment by btry** [comment]
Bonjour

Tout dépend du contexte. Si Formcreator est configuré pour remplacer l'interface simplifiée, c'est la liste de formulaires qui fait office de page d'accueil. Il est donc normal d'y revenir après saisie d'un formulaire.

En interface normale, l'utilisateur rejoint la liste des formulaires puis en remplit un. Il me parait normal également de revenir sur la liste. 

Revenir sur la liste des tickets va un peu à l'encontre du principe du plugin. Son but étant de faire l'intermédiaire avec les tickets en fournissant des formulaires personnalisables.

Je ne peux pas lancer une telle modification pour un seul utilisateur, car à ce jour tout le monde semble satisfait du comportement actuel. Je vous suggère de modifier le plugin et de conserver le patch.

Une amélioration envisageable serait d'enrichir les options que le plugin affiche dans les entités pour proposer divers choix tels que ce que vous avez demandé.

**Comment by datskill** [comment]
D'accord, pas de soucis et merci

**Comment by btry** [comment]
Bonjour

C'est ici: https://github.com/pluginsGLPI/formcreator/blob/master/front/form.form.php#L97

**Comment by datskill** [comment]
Merci, ça marche niquel !

**Comment by btry** [comment]
Merci, alors je clos.
