### ISSUE TITLE
Accès direct FAQ via interface Catalogue de service / Catalogue de service étendu

### ISSUE THREAD

**Issue by PlowRaiser** [pluginsGLPI/formcreator#886]
Existe il une possibilité pour donner un accès direct à la FAQ depuis l'interface Catalogue de service ?

**Comment by btry** [comment]
Bonjour

Oui, depuis que le catalogue de services existe.

Modifiez vos catégories de formulaires. Vous trouverez un chap qui permet de rattacher une catégorie de FAQ à la catégorie en cours d'édition. 

construisez vos associations, et le catalogue de service affichera les entrées de FAQ et les formulaires disponibles, dnas la même interface.

**Comment by PlowRaiser** [comment]
Très bien j'ai pu voir comment c'était lié mais on est obligé d'arriver sur "Voir tout" à l'ouverture du catalogue de service ? 

Parce que dans notre cas ça fait un sacré paquet d'info sur la page d'accueil le but étant d'optimiser la navigation pour l'utilisateur lambda.

**Comment by PlowRaiser** [comment]
Tous les formulaires ne sont pas encore prêt pour la mise en production mais en tout nous avons 61 demandes de services distinctes.

Ce n'est pas vraiment une limite du plugin c'est plutôt l'orientation, comme vous le dites pour vous l'utilisateur doit principalement utiliser la recherche alors que dans notre vision le mieux est de naviguer dans les catégorie jusqu'à atteindre la demande souhaitée.

Mettre la priorité sur la fonction de recherche peut être envisager à l'ouverture du portail pour les utilisateurs. 

Merci pour votre réponse.
