### ISSUE TITLE
Les sous catégories ne s'affichent pas

### ISSUE THREAD

**Issue by PlowRaiser** [pluginsGLPI/formcreator#887]
Bonjour, lorsque je gère les intitulés de catégories de formulaire mes sous catégories n'apparaissent pas :

(j'ai pu voir que les sous catégories fonctionne sous la forme décrit dans le ticket https://github.com/pluginsGLPI/formcreator/issues/398 )

![image](https://user-images.githubusercontent.com/13099470/35098900-436f48a0-fc56-11e7-9719-2c0360bc28a0.png)

Ici on voit que j'ai la catégorie application avec comme enfant Gestion de compte applicatif qui a lui même comme enfant Demande d'accès aux applications Citrix.

Voici l'affichage en interface Catalogue de service étendu : 

![image](https://user-images.githubusercontent.com/13099470/35098969-77cb0904-fc56-11e7-8e27-646a1154a5ac.png)

Authentification unique SSOX est bien un enfant direct de applications
test est dans la catégorie Gestion de compte applicatif (je l'ai ajouté pour être sur que la sous catégorie ne soit pas ignorée du fait qu'elle ne comprends pas de formulaire)
Demande d'accès aux applications Citrix est enfant de Gestion de compte applicatif 

Ici on a l'impression que ces trois formulaires se trouvent directement en dessous de Applications.

Navigateur utilisé : Internet Explorer 11 & Chrome Version 63.0.3239.132 (Build officiel) (64 bits)

**Comment by btry** [comment]
Bonjour
Si une catégorie n'apparait pas, c'est parce qu'il n'y a aucun formulaire accessible par l'utilsiateur dans son sous-arbre.

La requête SQL qui gère cela n'est pas parfaite et parfois, peut laisser apparaitre une catégorie sans formulaire accessible. Par cotnre l'inverse n'a pas été observé à ma connaissance.

Je vous invite donc à vérifier qu'il y a au mopins un formulaire **actif et utilsiable** par l'utilsiateur concerné.

**Comment by btry** [comment]
Essayez pour commencer de vider les colonnes sons_cache et ancestors_cache de la table **glpi_plugin_formcreator_categories**

Si le cache ne reflète pas bien la réalité, il peut y avoir un impact. Vider le cache permet de le recalculer quand il est sollicité, au moment de parcourir l'arborescence.

**Comment by ladenree76000** [comment]
j'ai le même comportement mais à mon avis c'est le comportement souhaité  : 
à la racine(niveau 0) on voit tous les formulaires, 
au niveau I  on voit tous les formulaires niveau I et aussi ceux de niveau inférieur
plus on descend plus la liste s'affine.

**Comment by btry** [comment]
@ladenree76000 a raison, c'est bien le comportement voulu. 

Mais il me semble que le problème exposé ici montre qu'un formulaire d'une catégorie parent pourrait apparaitre dans certains cas. Et cela n'est pas souhaité.

**Comment by PlowRaiser** [comment]
Est ce qu'il faut qu'il y a un formulaire accessible dans chaque niveau ? 

Exemple j'ai les catégorie 1 2 3 et les formulaire A et B

Si l'utilisateur à accès au formulaire A qui est au niveau 1 et au formulaire B qui est au niveau 3 mais que le niveau 2 n'a aucun formulaire associé cela est sensé fonctionner ?

**Comment by btry** [comment]
Oui, c'est censé fonctionner.

**Comment by PlowRaiser** [comment]
Déjà la flèche qui permet de comprendre qu'il y a des sous catégorie comme on peut voir dans le ticket auquel je fais référence n’apparaît pas et même après remise à NULL des colonnes cité le fonctionnement attendu ne se produit pas.

**Comment by PlowRaiser** [comment]
![image](https://user-images.githubusercontent.com/13099470/35107493-637c9466-fc71-11e7-97c4-d84955a4ae96.png)
pourtant quand on inspecte le code la liste est bien présente niveau HTML

**Comment by PlowRaiser** [comment]
après avoir remis à neuf depuis le master les dossier front et inc la fonctionnalité semble fonctionner un fichier devait donc être corrompu par ma faute.

Désolé pour le temps consommé.
Cordialement.

**Comment by btry** [comment]
Merci pour le retour.

Au cas où, je vous conseille d'upgrader un plugin en déplacant l'ancienne version hors de l'arborescence de GLPI, puis d'isntaller la nouvelle version dans le dossier plugins. C'est peut être de là que venait votre problème.
