### ISSUE TITLE
Critère d'affichage des questions

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#889]
Bonjour,
J'ai constaté, il y a quelques versions déjà que lorsqu'on déplace une question dans un formulaire, le critère d'affichage de la question repasse à "toujours visible" quelque soit le valeur de ce champs.
Pour info, je suis actuellement en GLPI 9.1.4 et en Formcreator 2.5.2
Bonne journée
Cordialement

**Comment by btry** [comment]
Bonjour

Je me souviens avoir trouvé et corrigé ce bug. Considérez un upgrade vers Formcreator 2.6.1. Il requiert GLPI 9.2.1.

**Comment by eckorion** [comment]
Merci beaucoup,
Bonne jornée
