### ISSUE TITLE
 resize screen Chrome and IE

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#890]
when using forms with IE or Chrome, the screen has poor visualization, does anyone know how to solve? There are no problems in MOZILA.

Form Version: 2.6.1
![save1](https://user-images.githubusercontent.com/35368369/35276138-7dd630d6-0029-11e8-83e5-c4056bf6fbca.PNG)

**Comment by btry** [comment]
Hi

I'm suspecting an issue with the length of a localized string. Can you switch to English and see how the page is rendered ?

**Comment by ralporto** [comment]
I have this same issue here, when i use at Brazilian Portuguese, but when i set to english everything got fine.

**Comment by btry** [comment]
Hi

Then the problem is the length of the string. I already gave more room long ago, I think we need to find a better solution now. Do you think a shorter translation is possible ?

**Comment by ralporto** [comment]
Hi,

Yes, there is a short translation that would be better. I think that we can use just "Solicitações de suporte" instead "minhas requisições de suporte". What do you think?

**Comment by btry** [comment]
Well I understand only english, french and a few from german :) I must trust you. The best would be the approval from someone else who knows your language.

You may give a try with your proposal by updating yourself the locales. If it is OK, then you may update the locales on Transifex.

**Comment by ralporto** [comment]
Just to explain, in my proposal of a new translation i only abandone the word my (minhas in português) and change the word requisições (requests) to a synonymous (solicitações).

Can you tell me how to update the locales by my self?

Thanks so mutch!

**Comment by btry** [comment]
To update the locales you need the CLI tool msgfmt 

First update the locale in the file **formcreator/locales/bt_BR.po**
```shell
cd formcreator/locales
msgfmt pt_BR.po -o pt_BR.mo
```

Once done, navigate to the page where the locale is used (or refresh). It should be updated.

**Comment by ralporto** [comment]
Thank you! Its working greate now!
![4](https://user-images.githubusercontent.com/33453857/35582361-c2519596-05d5-11e8-981b-59fc2c970d69.JPG)

**Comment by phamorais** [comment]
Guys, I solved my problem by changing the font of css styles
