### ISSUE TITLE
Catégorie spécifique dans destination du ticket non fonctionnelle

### ISSUE THREAD

**Issue by PlowRaiser** [pluginsGLPI/formcreator#892]
Bonjour, lorsque je test de créer une destination de formulaire qui pointe vers une catégorie spécifique : 

![image](https://user-images.githubusercontent.com/13099470/35339809-d3a4ed42-0121-11e8-8fa6-c482f803a139.png)

Une fois que je clique sur enregistrer l'élément est marqué comme modifié avec succès mais voici l'affichage : 

![image](https://user-images.githubusercontent.com/13099470/35339845-ef39db80-0121-11e8-8960-ef891e3ac6cb.png)

En base dans la table Targettickets les colonnes category_rule et category_question : 
![image](https://user-images.githubusercontent.com/13099470/35339887-08a2a50c-0122-11e8-9bcd-004792babf0e.png)

J'ai bien le numéro de catégorie qui corresponds à celle que je veux attribuer 
![image](https://user-images.githubusercontent.com/13099470/35339941-2c1a8f22-0122-11e8-9782-bb1db2f92e47.png)

Cependant quand je créer un ticket celui-ci n'a pas de catégorie d'affectée.

**Comment by btry** [comment]
Bonjour

Ca ne ressemblerait pas à ce bug ? https://github.com/pluginsGLPI/formcreator/issues/822

**Comment by PlowRaiser** [comment]
Effectivement c'est bien ce bug cependant lorsque je mets les nouveaux fichiers et que je fais l'update j'ai l'erreur : 

![image](https://user-images.githubusercontent.com/13099470/35340953-c168cc72-0124-11e8-918d-622e38426aed.png)

**Comment by btry** [comment]
Vous avez rempalce les fichiers concernés par le patch complètement mis à jour le plugin en  version 2.6.1 ?

**Comment by PlowRaiser** [comment]
Je sais pas pourquoi j'ai tenter une deuxième fois avec les mêmes fichiers et cela a fonctionner.

**Comment by btry** [comment]
Il y avait deux bugs dans le code d'install / upgrade qui affectaient le comportement de l'upgrade. Votre souci est typique de ces deux bugs.

Le plugin a décidé d'upgrader depuis une versio nantérieure à 2.5.0 alros que vous étiens (je pense) en 2.6.0.

C'est surprenant que la 2e tentative réussisse, car le plugin ne devrait pas retomber sur ses pieds après un upgrade interrompu. Surveillez vos logs php-errors.log et sql-errors.log pendant quelques temps, pour être sûr que vous n'avez pas d'erreur en lien avec les tables du plugin.
