### ISSUE TITLE
Created ticket error

### ISSUE THREAD

**Issue by Tamalou** [pluginsGLPI/formcreator#893]
Hello,
I'm with Glpi 9.2.1 and Formcreator 2.6.0
I have created a form and when I validate it, I have an error Http500 on this URL : http://XXX/glpi/plugins/formcreator/front/form.form.php
The form was been created but not the ticket.

Could you help me, please ?

**Comment by btry** [comment]
Please check the logs of your HTTP server. You should find a abcktrace. 

Also, you may try Formcreator 2.6.1. It contains a lot of fixes (see the changelog)

**Comment by Tamalou** [comment]
Ok, I'm going to do the update.
I must just copy the file on the folder of the plugin ?

**Comment by btry** [comment]
You must move the folder **formcreator* out of your GLPI, then install the usual way the new version. Next, login as super admin in GLPI, and run the upgrade.

Do not forget to **backup** your database before doing any update.

**Comment by Tamalou** [comment]
It works !!!
Thank you for your help

**Comment by btry** [comment]
Thank you for your feedback; I close this issue.
