### ISSUE TITLE
Format date dans le ticket

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/formcreator#894]
Bonjour,

Je voulais savoir s'il était possible de modifier le format de date dans les tickets en format jj-mm-aaaa au lieu de aaaa-mm-jj ?
![image](https://user-images.githubusercontent.com/17316903/35432373-25826d9c-0280-11e8-89fc-68d36a78afd7.png)

Ma version de formecreator est le 2.6.
j'ai modifié le format par défaut en jj-mm-aaaa mais ca n'a rien changé (y compris après redémarrage d'apache/serveur).

Est-ce que c'est modifiable ?
Merci d'avance pour votre aide.

**Comment by btry** [comment]
Bonjour

Le plugin ne prend pas en compte les préférences de format de date. C'est effectivement un point à améliorer.

**Comment by usrqmor** [comment]
Merci pour le retour @btry . Je m'en doutais mais je voulais juste confirmer ça.

Bonne journée.

**Comment by benjaminEORIS** [comment]
Bonjour, 

Nous avons le même besoin, une question demandant une date et toujours au format anglais dans la question et dans le ticket.

Nous aimerions avoir la date au format français. Est-il envisageable de prendre en compte les préférences générales de GLPI pour la question et la date renseignée sur le ticket ?

![image](https://user-images.githubusercontent.com/50371086/66192352-8d312c80-e690-11e9-805f-8a23ebfac8bb.png)

![image](https://user-images.githubusercontent.com/50371086/66192369-96ba9480-e690-11e9-9f91-2bfc29605431.png)

**Comment by btry** [comment]
Bonjour

Pour passer le champ en un format français il faut aller dans les préférences de votre compte 

![image](https://user-images.githubusercontent.com/14139801/66222070-9a6e0b80-e6d0-11e9-8e35-3d8224e1ec89.png)

**Comment by btry** [comment]
Une précision par rapport à la demande originale : quand le ticket est généré so ncontenu est d'une certaine manière définitif. Une date écrite dans le contenu ne peut pas s'adapter à une pférérence de format car la date est devenue un morceau de texte.

Je pense du coup qu'il va falloir clore ce vieux ticket à défaut d'avoir une solution.

En revanche pour l'afichagfe des champs, la réponse ci dessus devrait résoudre votre souci.

**Comment by benjaminEORIS** [comment]
Dans la deuxième capture d'écran fourni vous pouvez constater que la personnalisation est bien en place mais que la question du formulaire ne s'est pas adaptée à la configuration en question. Configuration en place MM-JJ-AAAA.

Mise en forme dans le questionnaire : AAAA-MM-JJ

**Comment by btry** [comment]
Bonjour

Le problème doit être résolu avec les dernières versions du plugin

Exemple : un champ datetime affiché dans un formulaire en cours de saisie.

![image](https://user-images.githubusercontent.com/14139801/69065743-7ff1b680-0a20-11ea-84ab-cb0087eacc69.png)
