### ISSUE TITLE
Wrong display of approval form in formcreator interface

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/formcreator#896]
When an approval cycle is set up from the technical interface, it is not possible with the service-desk profile (and therefore the formcreator interface) to accept or reject the approval request.

In the timeline of the ticket I find the notion of approval

![image](https://user-images.githubusercontent.com/7335054/35562537-f9a2a2e6-05b3-11e8-870b-ac666698eb73.png)

But if I click on the pen to display the form of acceptance or refusal, nothing is displayed.

![image](https://user-images.githubusercontent.com/7335054/35562543-fe55ac2a-05b3-11e8-83b2-6b7376a4c7b0.png)

GLPi version -> 9.2
Tested with formcreator  2.6.0 and 2.6.1

**Comment by btry** [comment]
Hi

@stonebuzz You investigated about this issue, can you tell about what you found ? I could not reproduce.
