### ISSUE TITLE
Hidden text fields are not show at ticket description

### ISSUE THREAD

**Issue by ralporto** [pluginsGLPI/formcreator#897]
When i use a hidden text field at a form to open a ticket, the text entered are not show at de description of the ticket even if i select full form to be show.

I´m using GLPI 9.2.1 and formcreator 2.6.1 in Brazilian portuguese.

![1](https://user-images.githubusercontent.com/33453857/35567682-03b741ee-05ad-11e8-85b2-bef85254e851.JPG)
![2](https://user-images.githubusercontent.com/33453857/35567683-03ddd43a-05ad-11e8-896b-14d09f966bee.JPG)
![3](https://user-images.githubusercontent.com/33453857/35567684-0403d96e-05ad-11e8-9885-457adc39b001.JPG)

**Comment by flobidon** [comment]
Hi, try the fix #901

**Comment by ralporto** [comment]
Thanks, this fix works perfectly.

**Comment by btry** [comment]
Grerat ! thank you for your feedback. I close this issue, the related one will close with the next release.
