### ISSUE TITLE
Gestion des lieux

### ISSUE THREAD

**Issue by JeromeW57** [pluginsGLPI/formcreator#899]
Bonjour,

Je souhaitais savoir s'il existe une façon de lier le lieu choisi par l'utilisateur dans la saisie du formulaire à l'objet lieu lors de la création du ticket ? Je n'ai rien trouvé de tel dans la création de la demande. 

Merci d'avance pour les informations que vous saurez me donner.

Jérôme.

**Comment by btry** [comment]
Bonjour

C'est dans la définition d'un ticket cible. Modifiez ce paramètre pour prendre le lieu à partir d'une question (de type intitulé / lieux)

![image](https://user-images.githubusercontent.com/14139801/35627212-8673f0dc-0698-11e8-9d28-2809522c4280.png)

**Comment by JeromeW57** [comment]
Merci pour votre retour très rapide. Nous allons donc mettre à jour noter version du plugin afin d'avoir cette possibilité.

Bonne journée.

**Comment by btry** [comment]
Pour info, la version 2.6.1 est sortie, pour GLPI 9.2.1 minimum.
