### ISSUE TITLE
Formatage du texte lors de l'attribution d'un ticket à une personne 

### ISSUE THREAD

**Issue by Geeskill** [pluginsGLPI/formcreator#911]
Bonjour,

Lors de l'attribution d'un ticket à une personne, le champ description se formate pour devenir presque illisible.

Avant attribution :
![formulaire ticket](https://user-images.githubusercontent.com/32699631/36144119-5c64220c-10ad-11e8-91ae-e8bb4c61813a.PNG)

Après attribution :
![formulaire ticket 2](https://user-images.githubusercontent.com/32699631/36144139-6faf5dfe-10ad-11e8-8897-ee4f3027eb35.PNG)

J'utilise ##FullForm## dans la rubrique Destination Glpi 9.2 et FormCréator 2.6.0 

Merci d'avance.

**Comment by btry** [comment]
Bonjour

Essayez Formcreator 2.6.2 sur une plate forme de test. Cette révision contient un correctif pour résoudre divers soucis de formatage.

**Comment by Geeskill** [comment]
J'ai bien effectué la mise à jour glpi 9.2.1 et formcréator 2.6.2 sur une plateforme de test mais mon formulaire ne fonctionne plus. Plusieurs conditions de masquage disparaissent. et en utilisant ##FullForm##  cela ne rempli plus le champ description de mon ticket.

**Comment by btry** [comment]
Il ya bien eu des bugfixes sur le masquage des questions, mais les retours que j'au eu étaient positifs.

Exportez le formulaire dans un fichier et déposez-le ici pour que je tente de reproduire.

**Comment by Geeskill** [comment]
[export_formcreator_20180213_1126.txt](https://github.com/pluginsGLPI/formcreator/files/1719517/export_formcreator_20180213_1126.txt)

**Comment by btry** [comment]
Bonjour

Je remarque que l'entête de votre formulaire contient quelque chose qui ressemble à une tentative d'injection de code.

```
<!--?php echo 'Bonjour'?-->
```
Dans quel but ?

**Comment by btry** [comment]
J'ai fait focntionner votre formulaire, et le ticket généré est  tout à fait corect.

Il est possible que le fait d'importer le plugin dans mon instance ait un effet, à cause des changements  d'encodage des textes en BDD que je mène depuis longtemps.

Pouvez-vous me montrer un exemple de réponses au formulaire, qui pose problème pour que ej remplisse de la même manière, et observe la géénration de ticket ?

De la même manière, montrez aussi comment vous remplissez le formulaire pour révéler un souci de masquage de champs se comportant d'une manière non désirée. Je n'ai rien vu d'anormal pour le moment.

**Comment by Geeskill** [comment]
Bonjour, 

pour le :  

 C'était un test que je n'ai pas enlevé mais rien de particulier. 

Voici ce que FormCreator renseigne dans le ticket :

Données du formulaire
=================

Identité
---------------------------------
1) Demande pour un tiers ? : 

2) Service : : service test

3) Ordinateur concerné : : UCTEST

4) Numéro de téléphone de contact : : 0606060606

Demande
---------------------------------
5) Votre demande concerne : : Messagerie

6) Messagerie : Calendrier partagé

Service en charge de la demande 
---------------------------------
7) Service Postes : DSI > POSTES

Informations complémentaires
---------------------------------
8) Vous pouvez noter ici toutes informations complémentaires : : message test

9) Ajouter une capture d'écran : Document joint


Voici ce que ça donne si je l'attribut à une personne :

Données du formulairern=================rnrnIdentitérn---------------------------------rn1) Demande pour un tiers ? : rnrn2) Service : : service testrnrn3) Ordinateur concerné : : UCTESTrnrn4) Numéro de téléphone de contact : : 0606060606rnrnDemandern---------------------------------rn5) Votre demande concerne : : Messageriernrn6) Messagerie : Calendrier partagérnrnService en charge de la demande rn---------------------------------rn7) Service Postes : DSI > POSTESrnrnInformations complémentairesrn---------------------------------rn8) Vous pouvez noter ici toutes informations complémentaires : : message testrnrn9) Ajouter une capture d'écran : Document joint

**Comment by btry** [comment]
Bonjour

Avec les dernières versions du plugin, il ne devrait plus y avoir de problème de ce type. 

Je ferme.
