### ISSUE TITLE
formcreator 0.90-1.3.3 to 2.6.2 upgrade error

### ISSUE THREAD

**Issue by Ph1eG** [pluginsGLPI/formcreator#912]
Hi all,
After upgrade of GLPI 0.90.3 to 9.2.1, during upgrade of formcreator 0.90-1.3.3 to 2.6.2 version i have :
- in my browser
> 2.6.2 multiple alter in glpi_plugin_formcreator_targettickets - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_formcreator_targettickets` ADD `location_rule` ENUM('none', 'specific', 'answer') NOT NULL DEFAULT 'none' AFTER `category_question` , ADD `location_question` INT(11) NOT NULL DEFAULT '0' AFTER `location_rule` , ADD `uuid` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL AFTER `category_question` - L'erreur est Unknown column 'category_question' in 'glpi_plugin_formcreator_targettickets'

- in file /var/www/glpi/files/_log/migration_to_2.6.2.log
> 2018-02-13 15:55:45 [6825@white]
0 seconde for "create database schema" @ 2018-02-13 15:55:45 [6825@white]
0 seconde for "Upgrade to schema version 2.5" @ 2018-02-13 15:55:45 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_answers" @ 2018-02-13 15:55:45 [6825@white]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_answers" @ 2018-02-13 15:55:45 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_categories" @ 2018-02-13 15:55:45 [6825@white]
0 seconde for "Changement de la structure de la base de données - glpi_plugin_formcreator_categories" @ 2018-02-13 15:55:46 [6825@white]
Unknown column 'validator_id' in 'field list'
  Backtrace :
  plugins/formcreator/install/update_0.0_2.5.php:166 plugin_formcreator_upgrade_error()
  plugins/formcreator/install/update_0.0_2.5.php:15  plugin_formcreator_updateForm_Answer_2_5()
  plugins/formcreator/install/install.php:47         plugin_formcreator_update_2_5()
  plugins/formcreator/hook.php:17                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:730                           plugin_formcreator_install()
  :                                                  Plugin->install()
  front/plugin.form.php:48                           call_user_func()
 @ 2018-02-13 15:56:01 [6825@white]
0 seconde for "create database schema" @ 2018-02-13 15:56:01 [6825@white]
0 seconde for "Upgrade to schema version 2.6" @ 2018-02-13 15:56:01 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2018-02-13 15:56:01 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_questions" @ 2018-02-13 15:56:01 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2018-02-13 15:56:25 [6825@white]
0 seconde for "create database schema" @ 2018-02-13 15:56:25 [6825@white]
0 seconde for "Upgrade to schema version 2.6" @ 2018-02-13 15:56:25 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2018-02-13 15:56:25 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_questions" @ 2018-02-13 15:56:25 [6825@white]
0 seconde for "Upgrade glpi_plugin_formcreator_forms_answers" @

Any ideas ?

**Comment by btry** [comment]
I think you should upgrade with intermediate steps.

Use a lab environment with a snapshot of your production database.

Upgrade to Formcreator 2.4.0, then 2.5.0 then 2.6.2. You will have to upgrade GLPI with intermediate steps too due to the compatibility restrictions of the plugin.

**Comment by Ph1eG** [comment]
Thank you very much for your answer.
I'm already in a dev' environnement with multiples snapshots.
I'll come back then to bring the results of my different tests.

Phi

**Comment by Ph1eG** [comment]
i confirm that upgrading with intermediate steps resolves this issue.
Many thanks !

**Comment by btry** [comment]
Great ! then I'll not investigate to fix this upgrade issue. The bug is workaround able and I prefer not to modify the old upgrade code (too many risks).
