### ISSUE TITLE
import email

### ISSUE THREAD

**Issue by nafoufa** [pluginsGLPI/formcreator#914]
Hello everybody
how i can import email from a specific user to glpi like ticket.
And thank you in advance

**Comment by btry** [comment]
Hi

I'm unsure I understand correctly your question. Do you want to create a ticket containing a requester whose the email does not belongs to a known user ?

**Comment by nafoufa** [comment]
what I want is to import emails from an account to glpi to be consulted

**Comment by btry** [comment]
This is out of scope. The purpose of Formcreator is to generate tickets or changes. I guess you need the plugin DataInjection.

**Comment by nafoufa** [comment]
thanks for the answer first.
now how can I do to use the plugin DataInjection.

**Comment by nafoufa** [comment]
and apparently the data injection is compatible only with the last version and I use the previous version

**Comment by btry** [comment]
If you use an older version of GLPI, you should consider upgrading it to the latest version.

To learn how to use DataInjection, ask on the forum. Unfortunately there is no official documentation yet for this plugin.

forum.glpi-project.org

**Comment by nafoufa** [comment]
OK THANKS A LOT
