### ISSUE TITLE
Champs "Masqué par défaut, sauf si" n'apparait pas dans le formulaire saisi

### ISSUE THREAD

**Issue by cemoimarc** [pluginsGLPI/formcreator#918]
Bonjour,
Un champ ayant la propriété "Masqué par défaut, sauf si" ne s'affiche pas le résumé du formulaire saisi même si le "sauf si" est valide.
Je précise que les valeurs s'affichent maintenant dans les tickets mais pas dans le formulaire
Test effectué:
Emploi à temps complet (bouton radio) = Oui, Non
Si emploi à temps complet = Non alors Journées travaillées (boîtes à cocher) s'affiche et on choisit les valeurs

Captures écrans
**Ticket généré par le formulaire**
![image](https://user-images.githubusercontent.com/36709162/36498224-a7764950-170b-11e8-81e3-b7a2b5ff0b6d.png)

**Formulaire saisi**
![image](https://user-images.githubusercontent.com/36709162/36498321-f2c78306-170b-11e8-80b2-50a5fa223557.png)

Merci

**Comment by btry** [comment]
hi

The issue seems fixed in the develop branch.

Waiting for feedback from you with this development version

**Comment by btry** [comment]
fix validated by requester
