### ISSUE TITLE
Problème notification en cas d'ajout d'une cible Acteur

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#919]
Bonjour,

Nous avons configuré une notification de cette manière :

Type : Formulaire de saisie
Evènement : Un formulaire est en attente de validation
Cible : Auteur

Nous avons configuré une seconde notification (même événement mais cible différente)

Type : Formulaire de saisie
Evènement : Un formulaire est en attente de validation
Cible : Valideur

Le groupe de valideurs reçoit bien la notification. L'acteur ne reçoit pas la notification configurée (malgré le fait que Notifications pour mes changements soit à Oui).

Versions : 
GLPI : 9.2.1
Formcreator : 2.6.2

**Comment by btry** [comment]
Bonjour

Pourquoi vous n'ajoutez pas les cibles auteur et valideur dans la meme notification ?

![image](https://user-images.githubusercontent.com/14139801/36594304-e1b21264-189d-11e8-94d0-c33b936d2448.png)

**Comment by lolokai** [comment]
Car le message de notification est différent :)

**Comment by btry** [comment]
D'accord, donc ça semble bien être un bug.

**Comment by lolokai** [comment]
Avez-vous eu le temps de travailler sur cette issue ?

**Comment by lolokai** [comment]
Des nouvelles de ce soucis ?

**Comment by btry** [comment]
Bonjour

J'ai  créé des notifications:

![image](https://user-images.githubusercontent.com/14139801/37959279-105fc1dc-31b3-11e8-87db-c318936ea3ee.png)

![image](https://user-images.githubusercontent.com/14139801/37959288-1459b040-31b3-11e8-95d2-22b5409454a3.png)

chacune ayant un modèle
![image](https://user-images.githubusercontent.com/14139801/37959315-25ac28fa-31b3-11e8-950c-df715035407a.png)

![image](https://user-images.githubusercontent.com/14139801/37959330-2c01b44a-31b3-11e8-8649-a896a8d2bdf4.png)

et chaque modèle ayant une traduction par défaut

![image](https://user-images.githubusercontent.com/14139801/37959368-410b763c-31b3-11e8-8c01-7de8483e7922.png)


![image](https://user-images.githubusercontent.com/14139801/37959350-39e6715e-31b3-11e8-86c6-aa9c4247db29.png)

Enfin, un formulaire avec validation

![image](https://user-images.githubusercontent.com/14139801/37959400-4ed1eef4-31b3-11e8-838e-9d97d8c76115.png)

Je remplis le formulaire avec le compte ```glpi``` et le fais valider par ```normal```

j'ai bien les notifications en file d'attente (glpi et normal ont uen adresse email)
![image](https://user-images.githubusercontent.com/14139801/37959446-66f6f196-31b3-11e8-8f12-cc0e338fbe46.png)

Je tente d'améliorer mon scénario en utilsiant un groupe valideur...

**Comment by lolokai** [comment]
Effectivement mais nous avons également mis en place un groupe valideur.
Je vais tâcher d'investiguer également de mon côté d'ici ce vendredi

**Comment by lolokai** [comment]
Je confirme que cela fonctionne bien mais dans notre cas, nous avions utilisé le même utilisateur comme valideur et demandeur c'est pour cela que ça ne fonctionne pas.
En utilisant 2 users distincts  : un valideur et un demandeur différent ça fonctionne.

**Comment by btry** [comment]
Bonjour

Oui, ça peut jouer car dans le moteur de notifications je me souviens avoir vu qu'on ne peut pas mettre plusieurs notifications en attente pour le même utilsiateur + objet lié.

Du coup, avoir le même utilisateur comme demander ET valideur me semble un cas absurde qui ne devrait pas arriver. J'aurais tendance à dire qu'il n'y pas bug. 

Et si il est vraiment décidé d'apporter une correction, je ne vois pas mieux que créer un modèle de notification spécifique à ce cas.

**Comment by lolokai** [comment]
Impec pour moi ;)
Merci pour votre temps

**Comment by btry** [comment]
Bonjour je ferme ce ticket car la solution proposée semble convenir.
