### ISSUE TITLE
Hide answers after Form creation 

### ISSUE THREAD

**Issue by BradacKamil** [pluginsGLPI/formcreator#920]
GLPI 9.2.1
Form 2.6.2

After filing form, filed questions with Condition are hide and invisible for Approver 

![during form filling](https://user-images.githubusercontent.com/36759517/36596564-06ae8fde-189e-11e8-94da-9dad8fd1dee9.JPG)

Created form

![created form](https://user-images.githubusercontent.com/36759517/36596730-9176fc28-189e-11e8-9b67-95e30eac9d31.JPG)

Thanks for help

**Comment by btry** [comment]
Hi

In this form do you have 2 fields with conditions, or more ?

**Comment by BradacKamil** [comment]
Hi 

+- 8 fields with conditions, if I filing form all working well but after creation all fields with conditions are hide

**Comment by btry** [comment]
Ok, then they all fail. Thank you.

**Comment by BradacKamil** [comment]
Do you have any idea why?

**Comment by btry** [comment]
Yes I got one. I'm curently working on something else. I'll investigate in 10 days. Earlier if I got free time.

**Comment by btry** [comment]
Hi

I reproduce with version 2.6.2, but no longer with develop branch (some fixes done on conditions).

Please use your testing environment to validate the development version and feedback.

**Comment by btry** [comment]
Seems to be a duplicate of #918

**Comment by btry** [comment]
Hi

No feedback, I assume the issue is solved.
