### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by OtavioCapila** [pluginsGLPI/formcreator#921]
I'm using the latest version of the plugin(2.6.2),when someone attach an file,appears that the file was sent correctly,but when you view the form, it does not appear.

**Comment by vismarluiz** [comment]
This problem only happens when there is no user logging into the GLPI. When the form is public.

**Comment by btry** [comment]
Hi

Many field types cannot work  correctly with public form, due to restrictions of GLPI. 

I already told on some other issues I'm considering to forbid these fields in public forms. I don't see any better solution, to not introduce security issues.

I think I'll implement this restriction in version 2.7.0.

**Comment by castorsenior** [comment]
Hello, 
I'm using Formcreator 2.6.3.
You write : "...when someone attach an file,appears that the file was sent correctly,but when you view the form, it does not appear".  <<====== I have the same problem for a user which is logged into GLPI.
It is a bug ? Make it sense for me to spend time looking for the solution ?
Thank you for your answer.
With best regards

**Comment by castorsenior** [comment]
*for a user who is logged into GLPI.

**Comment by btry** [comment]
I'll resume development of 2.7.0 as soon I released the version 2.6.4. If  the fix for this issue is easy I may consider to release it for 2.6.4 (in progress).

**Comment by castorsenior** [comment]
Thank you very much @btry for your labors and for rapid answer :-)

**Comment by castorsenior** [comment]
It works today for a logged user :-)))
(I didn't test for anonymous).
We had "queuednotification" desactivated... maybe that was the cause of the problem...

**Comment by btry** [comment]
Formcreator uses the notifications system provided by GLPI. Indeed, if notifications are disabled, the plugin cannot send any notification.

**Comment by btry** [comment]
Hi 

some fixes were done in 2.6.4 for file uploads. Can you feedback with this version ?

**Comment by castorsenior** [comment]
Hi @btry 

Thank you very much. I'll do it as soon as possible.

With best regards

**Comment by castorsenior** [comment]
@btry  PS : is it possible to install 2.6.4 on GLPI 9.2.4 ? I fear it is not possible.

**Comment by castorsenior** [comment]
Hello@btry
The paste of an image in the field "Description" (rich text), for example a screenshot, still not works in 2.6.4 either... 
Thank you for your attention, your help, and your labors

**Comment by btry** [comment]
Hi

I began investigation to implement paste of an image in a rich text area. Unfortunately it appears to be tricky to achieve. Please be patient

**Comment by thiagoifsc** [comment]
Hi, anyone has an update or solution to this issue?

I'm using the last version of GLPI (9.4.3) and the form creator plugin (2.8.5).
The problem only appears to me when i use windows(10 in this case). 
If i try to reproduce it in arch linux, i can paste an image inside rich text area without problems(it don't create an attachment, or at least it didn't show me an attachment is created) and the image appears in the ticket after submit.

I noticed that when i paste an image outside the plugin(in the default ticket opening page of the glpi) it didn't happen, and an attachment is created with the pasted image (both in windows and in linux).

Thanks in advance for the attention.

**Comment by thiagoifsc** [comment]
I forgot to say that the form in question are not public and i tried it with both admin and non-admin users.

**Comment by btry** [comment]
Hi

The field in DB which contains the answers to questions is too short to store an image with a reasonnable size. Please try this fix (not released yet) It may also work with anonymous forms.

https://github.com/pluginsGLPI/formcreator/commit/84e9c68532d1f0068e8963e7f522490007204246

related to https://github.com/pluginsGLPI/formcreator/issues/1455

**Comment by btry** [comment]
Hi 

This thread is getting old. If you still have issues with pasted documents in a text area consider to try the branch support/2.9.0 + the patch #1573 (not merged at time of writing this comment).

Please follow #1568
