### ISSUE TITLE
[2.6.2] Regression : use tags in ticket title

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/formcreator#922]
Hello,

In 2.6.2, you can't use tags in ticket title. If you downgrade in 2.6.1, you can.

Steps to reproduce : 
1. Create a form "Test" with a section and a question (type = text)
2. Define a destination called "MyDestination"
3. Set "Ticket title" to `##answer_X##` with X, ID of your **answer**
4. Save your form

When you save you form, "Ticket title" reverts to "MyDestination".

Same behavior when you edits an existing form.

No errors in logs or debug mode.

**Comment by nqb** [comment]
@btry : do you plan to fix this issue soon ?

**Comment by btry** [comment]
Hi

I think this issue matches the patch #917. Try it, and feedback.

**Comment by nqb** [comment]
It works with your patch.

I notice that when ##answer_X## is, for example, `Router doesn't work`, Ticket title is `Router doesn\'t work`.

**Comment by btry** [comment]
Thank you for  your  feedback.

Can you open a new issue for this backslash problem ?
