### ISSUE TITLE
Amélioration choix valideur

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#924]
Bonjour,

Il serait pratique d'avoir le choix du valideur automatiquement saisie lorsqu’il n'y a qu'un seul valideur ou groupe de valideur ?

**Comment by btry** [comment]
Bonjour

On pourrait aller encore plus loin, et afficher le valideur sans possibilité de modification.

**Comment by lolokai** [comment]
Je suis entièrement d'accord :)

**Comment by btry** [comment]
Bonjour,

Je priorise la resolution des soucis de compatibilité avec GLPI 9.3. Ensuite je continuerai le développement de la version 2.7.0 qui ne prendra plus en charge GLPI 9.2. Stabilisation de la version suite au code refactor, fin de résolution des bugs liés à l'encodage des saisies dans ma BDD, features sponsorisées. Les demandes communautaires sont en n'est effort.

Ce ticket étant une nouvelle feature il fait l'implémenter en 2.x.0.

**Comment by btry** [comment]
Bonjour

Pour le moment, non. J'ai beacuoup à faire sur les tests unitaires du plugin et la résolution des derniers soucis d'échappement de quote ou de caractères spéciaux/accentués.

Je tente de placer ça en 2.7.0 (le éveloppement est en cours)

**Comment by btry** [comment]
Bonjour
la fonctionnalité est réalisée.
