### ISSUE TITLE
Attachments. If the user is not logged in to GLPI the attachment does not go up.

### ISSUE THREAD

**Issue by vismarluiz** [pluginsGLPI/formcreator#925]
We're having trouble with the form attachments. If the user is not logged in to GLPI the attachment does not go up.

Version 2.6.2

**Comment by btry** [comment]
Hi 

there are several field types which don't work with a anonymous form (there are one or 2 other issues about that). 

Unfortunately, I don't have any solution, and I planned to introduce soon a check to forbid usage of these fields with an anonymous form.

**Comment by btry** [comment]
This may be linked to #679

**Comment by btry** [comment]
The issue might be related to the entity where the file is being saved. investigation will begin soon.
