### ISSUE TITLE
Type of the Ticket

### ISSUE THREAD

**Issue by vlemos** [pluginsGLPI/formcreator#929]
All Tickets are created as Incident´s Type. We don´t have option to create it as Request or Incident as ITIL´s metodology.

**Comment by btry** [comment]
Hi

Indeed, and not time yet to enhance this. Create a  ticket template, set it as a request type. Use this  template in your target ticket. Your generated tickets should be requests now.

**Comment by btry** [comment]
Hi

Some enhancements were done. You can nom set the ticket type (incident / request) by using a ticket template, associated to the target ticket.
