### ISSUE TITLE
v2.6.2 - bug: problem with multiple attachments in a form.

### ISSUE THREAD

**Issue by niloultimate** [pluginsGLPI/formcreator#937]
Problem with multiple attachments in a form.
if two attach fields are required, an error occurs while opening the call.

**Comment by btry** [comment]
Hi

Please provide more details : 
php-errors.log
sql-errors.log
screenshot if you consider this is useful
exact procedure to  reproduce (with a the most simple form aas possible, or export your form)

**Comment by niloultimate** [comment]
![forms 1](https://user-images.githubusercontent.com/24455891/37672507-e4645824-2c4c-11e8-88ef-c1db00f8e98d.png)
![forms 2](https://user-images.githubusercontent.com/24455891/37672526-ee43034a-2c4c-11e8-961f-359bc81d7cd0.png)

**Comment by niloultimate** [comment]
O
![forms 3](https://user-images.githubusercontent.com/24455891/37672859-8fb6f8a8-2c4d-11e8-8587-41362a0b3b3e.png)
r with the required field
![forms 4](https://user-images.githubusercontent.com/24455891/37672870-96d43510-2c4d-11e8-8182-dbd6ccb86103.png)

**Comment by matth974** [comment]
Hi,

I have the same problem.

Thanks

**Comment by niloultimate** [comment]
*Meu problema foi solucionado com a solução abaixo:
*My problem was solved with the solution below:

"multiple file upload lbteles #943"
https://github.com/pluginsGLPI/formcreator/pull/943/commits/7dfb008c2e9613fe642020b5cb572b15964c4597#diff-f47bf3ddb21dc2be496ec6a45d8532ad

**Comment by niloultimate** [comment]
0 - Após a alteração.
0 - After the change.

    1 - Eu encontrei outro problema, ao anexar ou finalizar o chamado o arquivo "showfields.php", não recebe o parâmetro que define o campo como  requezitos atendidos.
    1 - I found another problem, when appending or finalizing the called the file "showfields.php", does not receive the parameter that defines the field as answered requesitos.

2 - "JSON" enviado para  "showfields.php"
2 - "JSON" sent to "showfields.php"

{
4191: true,
 4192: true,
 4193: true,
 4194: 0,
 4195: true,
 4198: true,
 4199: 0,
 4200: true,
 4201: true,
 formcreator_field_4193:true
formcreator_field_4195:true
formcreator_field_4198:true
}

![teste](https://user-images.githubusercontent.com/24455891/38318414-a57622fe-3805-11e8-8dd7-7b7157af0195.png)

**Comment by btry** [comment]
Hi @niloultimate if you find an other problem, then this is an other bug or issue. Please open an other ticket. This is important for an efficient bug tracking.

**Comment by niloultimate** [comment]
I open a new ticket.
 https://github.com/pluginsGLPI/formcreator/issues/961

Thanks @btry.

**Comment by btry** [comment]
Hi

Please test the above fix. It should solve the issue. I wish to put it in 2.6.3 to be released today or tomorrow.

**Comment by matth974** [comment]
Thank you.
We can't test it today but tomorrow it will be possible.

**Comment by matth974** [comment]
Hi,

I try this fix: https://github.com/btry/formcreator/commit/34b7342582f94edc808179de19e5cc3ed9cae36b
and the problem is always here, for me.

**Comment by niloultimate** [comment]
I'm going to test in the afternoon.

**Comment by btry** [comment]
@matth974 can you share the form where you still observe the issue ?

**Comment by niloultimate** [comment]
1 - Ingles:
I also tested: [https://github.com/btry/formcreator/commit/34b7342582f94edc808179de19e5cc3ed9cae36b]
The required error persists.

2 - Portugues:
Eu tambem testei: [https://github.com/btry/formcreator/commit/34b7342582f94edc808179de19e5cc3ed9cae36b]
O erro de obrigatório persiste.

**Comment by matth974** [comment]
Hi,

See attachement, please.
[export_formcreator_20180425_0737.zip](https://github.com/pluginsGLPI/formcreator/files/1945393/export_formcreator_20180425_0737.zip)

**Comment by btry** [comment]
Hi

I improved the fix. Please remove the patch you added and apply this PR to test and feedback

https://github.com/pluginsGLPI/formcreator/pull/974

**Comment by matth974** [comment]
Hi btry,

Thanks you, it's OK for me. But the files are strangely renamed:
![nomfic_arallonge](https://user-images.githubusercontent.com/10028344/39236359-b88a2a0e-4889-11e8-95e0-f0f1253191d8.png)

**Comment by btry** [comment]
Hi

The patch does not impacts the filenames. This would be nice to keep the original filenames. This requires investigation to ensure this is possible (an other issue to open).

**Comment by matth974** [comment]
OK thanks. I'll open an other issue (in french).

**Comment by niloultimate** [comment]
Thanks guys, I've reissued the changes.

The attachment worked fine and its name is also correct.

![sem titulo](https://user-images.githubusercontent.com/24455891/39247157-02747e8c-486f-11e8-9680-9019aa6f2d52.png)

**Comment by btry** [comment]
@niloultimate It seems you have a different behavior comapred to @matth974 and me.

You're using GLPI 9.2.1, right ?

**Comment by niloultimate** [comment]
ops...
Sorry, I did not pay attention.
Yes is 9.2.1

**Comment by niloultimate** [comment]
Sorry again.

Ticket: [https://github.com/pluginsGLPI/formcreator/issues/976](url)

Thanks @btry

**Comment by niloultimate** [comment]
@matth974 , you're still experiencing the problem in your attachments ?

**Comment by matth974** [comment]
@niloultimate : i have not this problem (glpi-9-2-1).

**Comment by niloultimate** [comment]
@matth974 : in version 9.2.2 I had no problem with the name only with multiple attachments in the same field and the problem of recharging the screen when (Ticket: https://github.com/pluginsGLPI/formcreator/issues/976).

On my last screen I used version 9.2.2 of GLPI. Is it the same as you're using correct?
