### ISSUE TITLE
Problème apostrophe sur les noms de sections

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#940]
Si un nom de section contient une apostrophe la génération du ticket n'est pas possible

**Comment by btry** [comment]
Bonjour

Il devrait y avoir une erreur dans php-errors.log et / ou sql-errors.log.

**Comment by lolokai** [comment]
Oui dans le fichier sql-errors on a ça : 

2018-03-21 14:21:04 [2@glpi02]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_tickets` (`requesttypes_id`,`type`,`name`,`content`,`entities_id`,`itilcategories_id`,`locations_id`,`status`,`urgency`,`impact`,`priority`,`users_id_lastupdater`,`users_id_recipient`,`date`,`global_validation`,`date_creation`,`date_mod`) VALUES ('9','1','Ticket','Données du formulaire\n=================\n\n\nInformations générales\n---------------------------------\n1) Lieu : Tous &gt; Réunion &gt; Ouest\n\n2) Type d\'incident : Enseigne &gt; Décrochée\n\n\nNature de l'incident\n---------------------------------\n3) Commentaire : Mon enseigne est décrochée\n\n4) Photos : \n\n','10','105','9','2','3','3','2','2','2','2018-03-21 14:21:04','1','2018-03-21 14:21:04','2018-03-21 14:21:04')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'incident\n---------------------------------\n3) Commentaire : Mon enseigne est d' at line 2
  Backtrace :
  inc/commondbtm.class.php:504
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  ...ins/formcreator/inc/targetticket.class.php:1205 CommonDBTM->add()
  plugins/formcreator/inc/form_answer.class.php:967  PluginFormcreatorTargetTicket->save()
  plugins/formcreator/inc/form_answer.class.php:703  PluginFormcreatorForm_Answer->generateTarget()
  plugins/formcreator/inc/form.class.php:1174        PluginFormcreatorForm_Answer->saveAnswers()
  plugins/formcreator/front/form.form.php:91         PluginFormcreatorForm->saveForm()


Ici "Nature de l'incident" est une section

**Comment by btry** [comment]
J'ai f ait un test rapide:
GLPI 9.2.2-bugfixes (future 9.2.3)
Formcreator en développement (future 2.6.3).

quelles sont vos versions ?

**Comment by lolokai** [comment]
Bisarre on est en GLPI 9.2.2 et FormCreator : 2.6.2

**Comment by btry** [comment]
Je vais me baser sur le backtrace que vous avez fourni pour chercher le fix.

**Comment by btry** [comment]
Je reproduis : il faut que le mode texte riche soit désactivé. Je pousse un correctif.

Pouvez vous le valiuder  sur un environneemnt de test ?
- installez le correctlf
- sauvegardez la base de données (mise à jour du plugin nécessaire, altérant des données existantes)
- lancez le script CLI de mise à jour ```php scripts/cliinstall.php``` depuis le dossier du plugin
- testez

(problème qui résout partiellement #858)

**Comment by btry** [comment]
positive feedback in #852
