### ISSUE TITLE
Gabarit de tickets non appliqué

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/formcreator#945]
Lorsque nous créons un ticket à partir d'une réponse à un formulaire si nous appliquons un gabarit de tickets au ticket de destination et qu'au sein de ce gabarit nous masquons des champs.
Les champs ne sont pas masqués dans le ticket créé (par exemple : Urgence et Impact)

**Comment by btry** [comment]
Bonjour

Avec GLPI 9.2.2 et FormCreator : 2.6.2 (en me basant sur votre précédent ticket) ?

**Comment by lolokai** [comment]
Oui c'est bien cela

**Comment by btry** [comment]
Bonjour

Ce n'est pas un bug.

GLPI masque les champs d'un ticket en fonction de la catégorie du ticket, sa nature (requête ou incident) et le gabarit associé.

Donc pour masquer des champs dans les tickets générés vous devez faire en sorte que Formcreator applique une catégorie à votre ticket généré qui est rattachée à votre gabarit, sans oublier de prendre en compte la nature du ticket.

J'ai pu reproduire le comportement que vous voulez de la manière que je viens de décrire.

![image](https://user-images.githubusercontent.com/14139801/37913494-46efce16-3115-11e8-9b55-d2861c8124fe.png)
![image](https://user-images.githubusercontent.com/14139801/37913521-567e02d0-3115-11e8-9b7b-73d100c3d56b.png)
