### ISSUE TITLE
probleme modification aprés création

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/formcreator#946]
Bonjour je suis sous GLPI 9.2.1 avec Formcreator 2.6.2.
Après création de mon formulaire je ne peux plus modifier mon ticket Cible. 
en effet j'effectue mes modifications mais dés que clique sur enregistrer cela revient à l'état "avant modification".
Merci pour votre aide

**Comment by btry** [comment]
Bonjour

Regardez le contenu de **php-errors.log** et **sql-errros.log** dans **glpi/files/_log/**

**Comment by imanou10** [comment]
Bonjour 
il n'y a rien de spécifique .

**Comment by btry** [comment]
Montrez par capture d'écran votre ticket cible tel qu'il apparait à l'écran, puis modifiez le **sans sauvegarder** et faites une nouvelle capture d'écran. Je voudrais voir l'état initial et les changements que vous faites.

Enregistrez ensuite les changements, juste pour vérifier que vos captures sont bonnes pour reproduire le souci de mon côté.

**Comment by imanou10** [comment]
![avant](https://user-images.githubusercontent.com/36695393/37893804-9e74d4d2-30cb-11e8-8660-9d2315dbbd5e.JPG)
![apres](https://user-images.githubusercontent.com/36695393/37893805-9e9bb2dc-30cb-11e8-9cad-8489ac18b14f.JPG)
voici le avant après exemple la j'ai juste modifié le titre

**Comment by btry** [comment]
Ca ressemble à un bug déjà corrigé

https://github.com/pluginsGLPI/formcreator/pull/917

Le correctif sera dans la prochaine version 2.6.3

**Comment by imanou10** [comment]
Ah génial merci :)
Bonne fin de journée

**Comment by btry** [comment]
Merci, à vous aussi.

**Comment by btry** [comment]
Duplicates #922
