### ISSUE TITLE
probleme d'attachement de plusieurs pièces jointes en même temps + champ sourcer

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/formcreator#949]
bonjour 
J'ai deux petites questions : 
1- Peut-on attacher plusieurs documents sur un formulaire car lorsque je le fait seul le premier document est rattaché au ticket ?
2- Peut-on ajouter le champ source dans la destination du ticket ?
en vous remerciant

**Comment by btry** [comment]
Je pense que j'ai mal interprété votre première question. En fait ce serait plus une limitation qu'un bug. En totu cas, un contributeur a soumis le patch suivant, que je compte merger dans la version 2.7.0

https://github.com/pluginsGLPI/formcreator/pull/943

**Comment by btry** [comment]
Bonjour

Il y a effectivement un souci quand on met deux champs de type fichier sur un formulaire. Seul le premier est pris en compte.

Correctif: https://github.com/pluginsGLPI/formcreator/pull/974

Combiné avec la contribution (que je prévois en 2.7.0 car je considère que c'est une nouvelle fonctionnalité) les fichiers doivent fonctionner beaucoup mieux.

**Comment by btry** [comment]
Bonjour

à défaut de retour, et vu qu'il y a eu des correctifs, je ferme ce ticket.
