### ISSUE TITLE
[2.6.2] Doesn't show created forms for Self-Service

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/formcreator#953]
Hello!
I've a problem with setting the Formcreator plugin.
Doesn't show forms for all Self-service users. What do I need to enable to show forms?
GLPI 9.2.2
Formcreator plugin 2.6.2

For instance:

![image](https://user-images.githubusercontent.com/17082164/38078070-c91045b2-3343-11e8-8b76-37e499942ffe.png)

Forms settings:

![image](https://user-images.githubusercontent.com/17082164/38078148-043a5952-3344-11e8-831f-b2e7077e84a6.png)

**Comment by btry** [comment]
I notice that one screenshot uses russian and the other uses english.
Have a look on the following field when you design a form:

![image](https://user-images.githubusercontent.com/14139801/38079144-80aea304-333e-11e8-96e7-fb08f6e52709.png)

this field is compared against the current language of a user. If the language does not match, the user will not see the form.

I guess you configured your forms with Russian. Then when you are in the simplified interface you should use russian. If this conflicts with your needs, you may change the language field to **All languages**.

**Comment by tresheron** [comment]
Here is an example where the language is the same, the same, the forms are not displayed
![1](https://user-images.githubusercontent.com/37867500/38080257-9f46cd22-3349-11e8-8c08-cff76861b71f.PNG)
![default](https://user-images.githubusercontent.com/37867500/38080258-9f66c0e6-3349-11e8-9725-dcc2fe378061.PNG)

**Comment by btry** [comment]
Show the main tab of one of these forms please ?

I tried to reproduce with the development version, it works well for me.

**Comment by tresheron** [comment]
![image](https://user-images.githubusercontent.com/37867500/38081423-b495fd8a-334c-11e8-9c02-ff061d1e5f58.png)

**Comment by tresheron** [comment]
If you set All languages, it also does not appear

**Comment by tresheron** [comment]
![image](https://user-images.githubusercontent.com/37867500/38081587-0def8392-334d-11e8-833a-a34a8842fd6e.png)
![image](https://user-images.githubusercontent.com/37867500/38081653-3786c058-334d-11e8-9592-792a500055e3.png)

**Comment by btry** [comment]
Check sql-errors.log and php-erors.log

Also, open the dev tools of your browser when you're on the simplified interface, refresh the page and find the request beginning with 
**GET homepage_wizard.php?wizard=forms**
show me the HTTP response code. It should be 200 (succcess)

**Comment by btry** [comment]
show also the response body of this request. This is a JSON string

**Comment by AircraftRu** [comment]
@btry 
sql-errors.log:
```
2018-03-29 10:57:33 [7@glpi]
  *** MySQL query error:
  SQL: SELECT `glpi_bookmarks`.*,
                       `glpi_bookmarks_users`.`id` AS IS_DEFAULT
                FROM `glpi_bookmarks`
                LEFT JOIN `glpi_bookmarks_users`
                  ON (`glpi_bookmarks`.`itemtype` = `glpi_bookmarks_users`.`itemtype`
                      AND `glpi_bookmarks`.`id` = `glpi_bookmarks_users`.`bookmarks_id`
                      AND `glpi_bookmarks_users`.`users_id` = '7')
                WHERE `glpi_bookmarks`.`is_private`='1'
                  AND `glpi_bookmarks`.`users_id`='7'
                  OR `glpi_bookmarks`.`is_private`='0' AND ( `glpi_bookmarks`.`entities_id` IN ('4')  OR (`glpi_bookmarks`.`is_recursive`='1' AND `glpi_bookmarks`.`entities_id` IN ('0')) ) 
  Error: Table 'glpi922.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins/formcreator/inc/wizard.class.php:114       
  plugins/formcreator/front/issue.php:12             PluginFormcreatorWizard::header()
2018-03-29 10:57:35 [7@glpi]
  *** MySQL query error:
  SQL: SELECT `glpi_bookmarks`.*,
                       `glpi_bookmarks_users`.`id` AS IS_DEFAULT
                FROM `glpi_bookmarks`
                LEFT JOIN `glpi_bookmarks_users`
                  ON (`glpi_bookmarks`.`itemtype` = `glpi_bookmarks_users`.`itemtype`
                      AND `glpi_bookmarks`.`id` = `glpi_bookmarks_users`.`bookmarks_id`
                      AND `glpi_bookmarks_users`.`users_id` = '7')
                WHERE `glpi_bookmarks`.`is_private`='1'
                  AND `glpi_bookmarks`.`users_id`='7'
                  OR `glpi_bookmarks`.`is_private`='0' AND ( `glpi_bookmarks`.`entities_id` IN ('4')  OR (`glpi_bookmarks`.`is_recursive`='1' AND `glpi_bookmarks`.`entities_id` IN ('0')) ) 
  Error: Table 'glpi922.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins/formcreator/inc/wizard.class.php:114       
  plugins/formcreator/front/wizard.php:14            PluginFormcreatorWizard::header()
2018-03-29 10:57:54 [7@glpi]
  *** MySQL query error:
  SQL: SELECT `glpi_bookmarks`.*,
                       `glpi_bookmarks_users`.`id` AS IS_DEFAULT
                FROM `glpi_bookmarks`
                LEFT JOIN `glpi_bookmarks_users`
                  ON (`glpi_bookmarks`.`itemtype` = `glpi_bookmarks_users`.`itemtype`
                      AND `glpi_bookmarks`.`id` = `glpi_bookmarks_users`.`bookmarks_id`
                      AND `glpi_bookmarks_users`.`users_id` = '7')
                WHERE `glpi_bookmarks`.`is_private`='1'
                  AND `glpi_bookmarks`.`users_id`='7'
                  OR `glpi_bookmarks`.`is_private`='0' AND ( `glpi_bookmarks`.`entities_id` IN ('4')  OR (`glpi_bookmarks`.`is_recursive`='1' AND `glpi_bookmarks`.`entities_id` IN ('0')) ) 
  Error: Table 'glpi922.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins/formcreator/inc/wizard.class.php:114       
  plugins/formcreator/front/issue.php:12             PluginFormcreatorWizard::header()
```
No errors associeted with the formcreator plugin in php-errors.log

**Comment by btry** [comment]
Which version of GLPI are you using ?

**Comment by AircraftRu** [comment]
GLPI 9.2.2

**Comment by btry** [comment]
If I  remember correctly bookmarks were redesigned in GLPI 9.2 and are now named saved searches. The table in the DB glpi_bookmarks does not exists anymore.

Line 114 of inc/wizard.php does not directly queries on this table. https://github.com/pluginsGLPI/formcreator/blob/2.6.2/inc/wizard.class.php#L114

Try to disable all other plugins and see if this still occurs. 

Also how can you have saved searches in the simplified interface ?

**Comment by AircraftRu** [comment]
Yes, GLPI 9.2 has bookmarks redesigned.

I can save searches here:

![image](https://user-images.githubusercontent.com/17082164/38083332-ee565fe2-3351-11e8-9201-bc0d177e3561.png)

I've saved a search and I don't have these errors in sql-errors.log anymore.

**Comment by AircraftRu** [comment]
Is it the bug?

**Comment by btry** [comment]
I need to investigate because the backtrace in the sql errors seems strange. I'll try to reproduce next week (I'm working on an other project for the remaining of this week).

In the mean time, please check the result of the HTTP request as I asked. This might be helpful to see if  there is a relation between the SQL errors and the missing forms. Do you know how to use developer tools in a browser ?

**Comment by AircraftRu** [comment]
See previous post. I've wrong with SQL errors. For 2.6.2 it's not actualy.

**Comment by AircraftRu** [comment]
Hi, did you find reasons of the bug? We can't to start to use this plugin.

**Comment by btry** [comment]
Hi 

Not yet. Did you checked the HTP requests with the developer tools of your browser ? This would be helpful to know if there is a crash when getting the forms of if this is only a parameter problem.

**Comment by AircraftRu** [comment]
Is it? 
Google Chrome Console:
```
Uncaught ReferenceError: pluginNewsCloseAlerts is not defined
    at HTMLDocument.<anonymous> (wizard.php:131)
    at c (jquery-1.10.2.min.js:4)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js:4)
    at Function.ready (jquery-1.10.2.min.js:4)
    at HTMLDocument.q (jquery-1.10.2.min.js:4)
```

**Comment by btry** [comment]
This is not what I was searching for, but this is interesting. Disable the plugin Alerts and see if the bug persists.

**Comment by AircraftRu** [comment]
It depends on Alert plugin. I've disabled it and FormCreator plugin start to work as needed.
Thank you! But I have 1.3.2.5 version of Alert plugin, and I need it, latest version of the plugin don't work correctly on GLPI 9.2.2. Nobody support Alert plugin now.

**Comment by btry** [comment]
A few months ago some patches were pushed on  the development version of the Alert plugin to fix issues with Formcreator.

**Comment by AircraftRu** [comment]
Is this https://github.com/pluginsGLPI/news/commit/5dda82ad669c4234dd54510d1380c6c07991cc4c ?

**Comment by btry** [comment]
I think yes, but I believe there are one or 2 other fixes more.

I noticed t here are 3 commits more in the branch develop compared to the branch master. I think you should pick all of them.

**Comment by AircraftRu** [comment]
I've fixed js\news.js and setup.php in my the news plugin, and all is ok. Thank you!

**Comment by AircraftRu** [comment]
It's solved.
