### ISSUE TITLE
[2.6.2] Some bugs

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/formcreator#954]
Hello
Text is shifed on main page user if setted Russian.

![image](https://user-images.githubusercontent.com/17082164/38082826-85245fac-3350-11e8-8f0e-f96f274f131c.png)

**Comment by btry** [comment]
Hi

This issue was already found for an other language. The problem comes from the length of the string.

I considered to make the left pane lager, but I think increasing it again would be too much. The solution we found was to find a shorter translation. As I don't read Russian, I cannot change this myself. Could you contribute and propose a shorter string ?

**Comment by AircraftRu** [comment]
This is my translation. But unfortunately it can't be done shorter. It's normal by Russian.

**Comment by btry** [comment]
Then I'll try to find a way to make the width of the left panel automatic, with a minimal value.

**Comment by AircraftRu** [comment]
Don't forget about hiding doesn't work on first tab.

**Comment by AircraftRu** [comment]
@btry Hi
And I've a problem with translating words: "Form categories", "Forms" and etc. on Transifex website:

![image](https://user-images.githubusercontent.com/17082164/38127052-0c1bff2c-33fd-11e8-9424-337f9a69cb96.png)

Thank you!

**Comment by btry** [comment]
OK, going to Transifex to see if I can "un-review" the whole language

**Comment by btry** [comment]
Done, try again !

**Comment by btry** [comment]
Really ? Look what I see on Transifex.

![image](https://user-images.githubusercontent.com/14139801/38128163-b6424bb8-33f9-11e8-9906-ab4f83bc5333.png)

You may also update the .po file in the locales/ folder, then regenerate the .mo with gettext. (old fashion, scripts available in the plugin simcards)

If you so it, send me the updated russian .po file and I'll update Transifex from it.

**Comment by btry** [comment]
Yes I saw the issue for Form categories, but how an untranslated string can be reviewed ? I'll send a message to the Transifex team.

**Comment by AircraftRu** [comment]
I've translated it.

[ru_RU.zip](https://github.com/pluginsGLPI/formcreator/files/1863185/ru_RU.zip)

**Comment by AircraftRu** [comment]
And some words don't have translation: "Ticket approver" isn't at Transifex, "Form approver".

![image](https://user-images.githubusercontent.com/17082164/38133376-9b16661c-3417-11e8-8bf4-ad30bf54af51.png)

**Comment by btry** [comment]
Ok, I'll check  that

**Comment by btry** [comment]
I found the not missing translations. Transifex is updated, with them, and your .po  file

**Comment by AircraftRu** [comment]
It's strange, I don't see any changes.

**Comment by btry** [comment]
Hi

Indeed, the update seems to fail because the remote translation was more recent than the file you sent to me. I choosed to force the update as the comparison of the old transaltion against yours seems to show some errors. It seems the old translation did not translated correctly plural, am I right ?

Only the string "Ticket approver" needs a translation now.

**Comment by AircraftRu** [comment]
Yes, all right.

**Comment by AircraftRu** [comment]
I'm else waiting for you tell me how to fix it:

![image](https://user-images.githubusercontent.com/17082164/38082826-85245fac-3350-11e8-8f0e-f96f274f131c.png)

**Comment by AircraftRu** [comment]
"Tags" doesn't have translation:

![image](https://user-images.githubusercontent.com/17082164/38198632-4a71c93c-3696-11e8-816d-410ec48b2280.png)

**Comment by btry** [comment]
Is  the Tags plugin installed ?

**Comment by AircraftRu** [comment]
No

**Comment by btry** [comment]
if the plugin Tags is not installed, this type of field should not appear. the plugin is designed  to re-use the translation provided by the Tags plugin.

Try this patch please: https://github.com/pluginsGLPI/formcreator/pull/957

**Comment by AircraftRu** [comment]
I got it, This solusion doesn't work.

**Comment by btry** [comment]
Indeed, I left a typo. I fixed it and in my development instance it works better. The PR is up to date.

**Comment by AircraftRu** [comment]
Yes, it works! Thank you!

I'm else waiting for you tell me how to fix it:

![image](https://user-images.githubusercontent.com/17082164/38082826-85245fac-3350-11e8-8f0e-f96f274f131c.png)

**Comment by AircraftRu** [comment]
Hello @btry, how to make word wrap? Which CSS file do I need?

**Comment by btry** [comment]
hi

you need to edit this file: https://github.com/pluginsGLPI/formcreator/blob/master/css/styles.css

**Comment by AircraftRu** [comment]
Thanks, I removed 
```
#c_menu li label {
   display: inline-block;
```
I don't know how to fix it.

**Comment by btry** [comment]
Hi @AircraftRu I'm fixing last issues before relasing the version 2.6.3 (today or tomorrow).

I decided to give more room to the left panel (+50 pixels). Can you try the fix and tell me if this is sufficient ?

**Comment by btry** [comment]
Hi @AircraftRu 

Can you feedback please ?

**Comment by btry** [comment]
Hi @AircraftRu 

I'm working on versioin 2.7.0, can you validate this change please ?

**Comment by btry** [comment]
Hi 

Having no feedback, I close this issue. Feel free to request if the fix still needed.
