### ISSUE TITLE
Impossible d'ajouter une destination (nouveau 31/03/2018)

### ISSUE THREAD

**Issue by MichelKarwatka** [pluginsGLPI/formcreator#955]
Bonjour,
j'ai installé Formcreator (version 2.4.1) dans mon GLPI (version 0.90.5 tournant avec MySQL) sur mon serveur de test. Tout fonctionne correctement.
Je souhaite maintenant installer FormCreator (2.4.1) dans mon GLPI de production (même version que le test). Je rencontre un problème quand je veux définir la destination : je remplis le champ destination, je sélectionne l'option "ticket" et je clique sur le bout on "Ajouter". Aucune destination n'est créée.

J'ai appliqué les recommandations déjà données dans ce forum por résoudre ce même problème : 

- désactiver le mode strict dans MySQL
- ajouter default '' dans le fichier targetticket.class.php dans les lignes : 
+                     `tag_questions` VARCHAR(255) NOT NULL DEFAULT '',
+                     `tag_specifics` VARCHAR(255) NOT NULL DEFAULT ''

Malgré ces deux actions mon problème reste toujours d'actualité.

Voici ce que je trouve dans le logfile de MySQL : 

2018-03-31 09:38:41 [2@BEJEMGLP02]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targettickets` (`name`,`comment`) VALUES (\'TEST\',\'##FULLFORM##\')
  Error: Field 'tag_questions' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:428                       
  inc\commondbtm.class.php:834                       CommonDBTM->addToDB()
  plugins\formcreator\inc\target.class.php:134       CommonDBTM->add()
  inc\commondbtm.class.php:802                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins\formcreator\front\target.form.php:14       CommonDBTM->add()
2018-03-31 09:38:41 [2@BEJEMGLP02]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targettickets_actors` (`plugin_formcreator_targettickets_id`,`actor_role`,`actor_type`,`use_notification`,`uuid`) VALUES (\'\',\'requester\',\'creator\',\'1\',\'2a43ee55-5b62d400-5abf3b01794573.79517721\')
  Error: Incorrect integer value: '' for column 'plugin_formcreator_targettickets_id' at row 1
  Backtrace :
  inc\commondbtm.class.php:428                       
  inc\commondbtm.class.php:834                       CommonDBTM->addToDB()
  plugins\formcreator\inc\target.class.php:145       CommonDBTM->add()
  inc\commondbtm.class.php:802                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins\formcreator\front\target.form.php:14       CommonDBTM->add()
2018-03-31 09:38:41 [2@BEJEMGLP02]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targettickets_actors` (`plugin_formcreator_targettickets_id`,`actor_role`,`actor_type`,`use_notification`,`uuid`) VALUES (\'\',\'observer\',\'validator\',\'1\',\'2a43ee55-5b62d400-5abf3b0179c675.04289011\')
  Error: Incorrect integer value: '' for column 'plugin_formcreator_targettickets_id' at row 1
  Backtrace :
  inc\commondbtm.class.php:428                       
  inc\commondbtm.class.php:834                       CommonDBTM->addToDB()
  plugins\formcreator\inc\target.class.php:152       CommonDBTM->add()
  inc\commondbtm.class.php:802                       PluginFormcreatorTarget->prepareInputForAdd()
  plugins\formcreator\front\target.form.php:14       CommonDBTM->add()
2018-03-31 09:38:41 [2@BEJEMGLP02]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_formcreator_targets` (`name`,`itemtype`,`plugin_formcreator_forms_id`,`items_id`,`uuid`) VALUES (\'TEST\',\'PluginFormcreatorTargetTicket\',\'1\',\'\',\'2a43ee55-5b62d400-5abf3b0179e051.99790162\')
  Error: Incorrect integer value: '' for column 'items_id' at row 1
  Backtrace :
  inc\commondbtm.class.php:428                       
  inc\commondbtm.class.php:834                       CommonDBTM->addToDB()
  plugins\formcreator\front\target.form.php:14       CommonDBTM->add()

Auriez-vous une idée de la cause du problème ?

Merci d'avance pour votre réponse.

**Comment by btry** [comment]
Bonjour

La modification que vous avez  faite dans targetticket.class.php ne s'appliquera qu'à l'installation du plugin.

Comme le plugin est déjà installé, modifiez la table corespondante en mettant une valeur par défaut (chane vide). Cela doit résoudre le souci.

Il n'y aura pas de correctif sur uen version aussi ancienne. Je vous recommande d'envisager l'upgrade de votre GLPI en 9.2.2 pour profiter de la dernière version du plugin.

**Comment by btry** [comment]
Bonjour

Peut on clore ce ticket ?

**Comment by MichelKarwatka** [comment]
Oui le ticket peut être clôturé.
Nous allons envisager le passage à la version 9.2.2 de GLPI.
Merci pour votre réponse.

**Comment by MichelKarwatka** [comment]
Oui le ticket peut être clôturé.
Nous allons envisager le passage à la version 9.2.2 de GLPI.
Merci pour votre réponse.
