### ISSUE TITLE
Opened Date in blank when Form make a Ticket

### ISSUE THREAD

**Issue by allancarlosvr** [pluginsGLPI/formcreator#960]
After I complete my form with full requisitions. He show me a error, with open date ticket.

I need so much a help, please
![abertura](https://user-images.githubusercontent.com/36505009/38276676-270c3ed8-376c-11e8-995a-0b7c3df0fe52.PNG)

**Comment by btry** [comment]
Hi

Please translate into english the messages, I don't read this language.

**Comment by btry** [comment]
Hi

Think this matches other reports done later, and this was solved. I close this issue. It it still ocurs, please open a new ticket, and use english.
