### ISSUE TITLE
bug: multiple attachments in one form - Multiple required

### ISSUE THREAD

**Issue by niloultimate** [pluginsGLPI/formcreator#961]
0 - Após a alteração.
0 - After the change.

"multiple file upload lbteles #943"
https://github.com/pluginsGLPI/formcreator/commit/7dfb008c2e9613fe642020b5cb572b15964c4597#diff-f47bf3ddb21dc2be496ec6a45d8532ad

1 - Eu encontrei outro problema, ao anexar ou finalizar o chamado o arquivo "showfields.php", não recebe o parâmetro que define o campo como requezitos atendidos.
1 - I found another problem, when appending or finalizing the called the file "showfields.php", does not receive the parameter that defines the field as answered requesitos.

2 - "JSON" enviado para "showfields.php"
2 - "JSON" sent to "showfields.php"

{
4191: true,
4192: true,
4193: true,
4194: 0,
4195: true,
4198: true,
4199: 0,
4200: true,
4201: true,
formcreator_field_4193:true
formcreator_field_4195:true
formcreator_field_4198:true
}

![teste](https://user-images.githubusercontent.com/24455891/38324449-ba527f90-3816-11e8-8878-d5d3b0a79bb5.png)

**Comment by btry** [comment]
Hi

This problem should be solved now. Closing.
