### ISSUE TITLE
Problème d'affichage des champs conditionnés dans les formulaires

### ISSUE THREAD

**Issue by cemoimarc** [pluginsGLPI/formcreator#962]
Les éléments qui sont dépendant d'une valeur dans les formulaires ( Si X = Oui ou X=Non alors visible ), ne sont pas retraités et restent cachés si le formulaire est remplis avec erreur.
**Avant la soumission du formulaire**
![image](https://user-images.githubusercontent.com/36709162/38368021-32dcc7cc-38b2-11e8-9ef6-394ad468d4cf.png)

**Après la soumission du formulaire qui comprend des erreurs**
![image](https://user-images.githubusercontent.com/36709162/38368206-b0315026-38b2-11e8-90ba-bbffeb25ca14.png)

Avez-vous une solution à ce problème. 
Merci de votre aide

**Comment by btry** [comment]
Bonjour

J'ai remarqué que certains types de questions nécessitent de perdre le focus pour que le formulaire recalcule les conditions. Il me semble que les boutons radio en font partie.

**Comment by btry** [comment]
Bonjour

J'utilise la branche develop telle qu'elle est à ce jour.

Il semble que le problème ne soit pas (ou plus) reproductible. J'ai créé le formulaire suivant
question 1 : champ  radio avec les valeurs A et B, B étant par défaut
question 2 : champ de type texte, caché sauf si question 1 == B
question 3 : champ texte obligatoire

Si je fais fonctionner le formulaire, que je choisis sur al question 1 le choix B et que je valide, la page se rafraichit, un message d'erreur apparait (question 3 vide) et la question 2 apparait.

Pouvez vous vérifier avec la même version ?

**Comment by btry** [comment]
Bonjour
@cemoimarc Pouvez-vous vérifier que le bug a bin disparu avec la release 2.6.3 du plugin ? Je reste en at tente de retour de votre part.

**Comment by cemoimarc** [comment]
Les champs de **type description** ne sont pas traités

**Comment by btry** [comment]
Bonjour,

Vous voulez afficher / cacher des descriptions selon des conditions ?

**Comment by cemoimarc** [comment]
Bonjour,
Oui

**Comment by btry** [comment]
Je fournirait un patch mercredi
