### ISSUE TITLE
Validation Bug

### ISSUE THREAD

**Issue by dibbo-kotatsu** [pluginsGLPI/formcreator#964]
Hi,
I did a form with validation step by specific group. An user creates a request via form and the form is available to a member of specific group who can click on "Accept" or "Refuse" Button. However, when he click on a button, there is no effect.

GLPI Version: 9.2.2
FormCreator Versione: 2.6.2

Here main steps:

1. Creation Request by Form with group "Dirigenti" selected to validate request:

![creation_form](https://user-images.githubusercontent.com/28952486/38423314-de16fbde-39ad-11e8-83b6-2fa3eec5e1d1.jpg)

2. Request is available to member of group "Dirigenti" for validation without effects when he click on buttons:

![accept_form](https://user-images.githubusercontent.com/28952486/38423416-26d349ae-39ae-11e8-8721-3ffa0b4c6097.jpg)
![refuse_form2](https://user-images.githubusercontent.com/28952486/38423422-2c6127d8-39ae-11e8-955b-e377aba79725.jpg)
![refuse_form](https://user-images.githubusercontent.com/28952486/38423428-30a1804a-39ae-11e8-9d07-268a2c1b0a09.jpg)

3. Nobody in list of approver:

![form_approver](https://user-images.githubusercontent.com/28952486/38423486-5aba1270-39ae-11e8-897d-6b52ae2cd528.jpg)

I attach export of my form here:

[export_formcreator_20180406_1454.zip](https://github.com/pluginsGLPI/formcreator/files/1884113/export_formcreator_20180406_1454.zip)

Thanks

Dibbo

**Comment by dibbo-kotatsu** [comment]
Hi,
news for this issue?
Thanks

Giovanni

**Comment by btry** [comment]
Hi

Not yet. This issue is a community issue, then it will be solved at best effort. If you need a quicker resolution, contact us : contact@teclib.com

**Comment by btry** [comment]
Hi

The validator is empty because it does not contains the user who actually validates the form. 

There are two fields
- form validator
- form validator group

### form validator
this field is populated if the form is designed to be validated by a validator user. The value is the validator selected by the requester.

### form validator group
this field is populated if the form is desigend to be validated by a member of a group. The value is the validator group selected by the requester. When a member of the group validates the form, it is NOT added ti the form validator column.

You may show the form validator group by editing the display preferences.

**Comment by dibbo-kotatsu** [comment]
Hi,
thank you, but tha main problem is that the member of group can't validate form, as the screenshot show.
Clicking buttons hasn't effects.

**Comment by btry** [comment]
I tested before answering, and for me it works fine.

Is the user a member of a group itself or a member of a sub-group ?

**Comment by dibbo-kotatsu** [comment]
member of a group itself.

Strange behaviour. I do not know what prevents validation. Thanks anyway

**Comment by btry** [comment]
Can you check with the develop branch if this still happens ?

**Comment by dibbo-kotatsu** [comment]
Ok I will try.

Thank you

**Comment by dibbo-kotatsu** [comment]
Hi,
a member of group validator with Super-Admin profile can validate Form. Members with other profiles can't. What privileges users need to validate forms?

Dibbo

**Comment by btry** [comment]
Hi

There are no specific right needed to validate a a filled form. The plugin only checks that the current user is an eligible validator (in your case, he must be a member of the validator group).

The buttons to accept or refuse the form are displayed only if the user can validate the form. If you see the buttons, then the plugin considers you can validate the form.

If you click on "accept" or "refuse", do your browser refresh the page ?

Please check php-errors.log, sql-errors.log. You may also open  the developer tools of your browser and check if there are javascript errors before and after clicking a validation button.

**Comment by dibbo-kotatsu** [comment]
Hi,
finally I found a mandatory user rights to validate forms on my instance of FormCreator.
The profile "Dirigente" needs "Update Entity" on Administration Function to validate forms.
But this means that menu Administration-Forms appears to users with that profile and they can create and update all forms in the their entity.

Dibbo

**Comment by btry** [comment]
By reading the code the updat entity right shall not be needed. I'll check the rights of the **normal** user who validated  the forms when I tested your use case.

**Comment by dibbo-kotatsu** [comment]
I regret don't use validation with normal user. Normal user can modify forms configurations (menu "Administration->Forms" is showed to him).

Dibbo

**Comment by btry** [comment]
Hi

This issue is stalled sonce 3 years. Closing. If the problem still occurs, the open a new issue with up to date context.
