### ISSUE TITLE
Transifex Czech - unable to edit strings marked as reviewed

### ISSUE THREAD

**Issue by p-bo** [pluginsGLPI/formcreator#965]
Hi,

in Czech translation of Formcreator - completed missing translations,
but unable to edit rest - may I ask you to remove review flags or make
me reviewer (pavelb) please?

Thanks a lot :)
Pavel

**Comment by btry** [comment]
Hi

I removed  the reviewed flag on all language strings. You should be able to update freely this language.

**Comment by btry** [comment]
I changed your role to reviewer

**Comment by btry** [comment]
Hi

Can I close your issue ?

**Comment by p-bo** [comment]
Yes please - many thanks :)

**Comment by btry** [comment]
You're welcome. Thank you for your contribution !
