### ISSUE TITLE
Add file destination

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/formcreator#966]
Hello,

Currently in Formcreator, we can create two destinations : Ticket and Change.

Having a file destination that create files in `GLPI_ROOT/files/_plugins/formcreator` in a customizable manner will be a great enhancement.
Our idea : parsing that files to automate some tasks based on answers.

**Comment by btry** [comment]
Hi

Do you plan to read the file with some software and do some process ?

Why not directly use the REST API of GLPI ?

**Comment by nqb** [comment]
> Do you plan to read the file with some software and do some process ?

Yes, exactly.

> Why not directly use the REST API of GLPI ?

If it we can already access filled forms from REST API, you can close that issue.

**Comment by btry** [comment]
The API should work : GLPI exposes the itemtypes of plugins the same way its own itemtypes.

Give a try and feedback. If you succeed, then I'll close this issue.

**Comment by btry** [comment]
Hi

Having no feedback on the suggestion, I close this ticket.
