### ISSUE TITLE
Anonymous form do not load correctly . 

### ISSUE THREAD

**Issue by lucioaquino** [pluginsGLPI/formcreator#968]
I am using the form creator plugin to permit to users open a ticket for a creation of a account . The form is public but do not load correctly ,  only if i do a f5 reload 

--> Before 
![image](https://user-images.githubusercontent.com/18651504/38782783-e56efbd4-40ce-11e8-918d-f25ef16d383d.png)

--> After 

![image](https://user-images.githubusercontent.com/18651504/38782811-381bdb04-40cf-11e8-8aaa-1dafc6963a9d.png)

**Comment by btry** [comment]
Hi

A contributor did a fix for this recently.

https://github.com/pluginsGLPI/formcreator/pull/928

You may try it. The fix is ready for the next release.

**Comment by lucioaquino** [comment]
Thank you , it´s working perfectly . 

Mercy , Ça marche !
