### ISSUE TITLE
Gestion des plages horaires et jours fériés dates d'échéance

### ISSUE THREAD

**Issue by osfrance** [pluginsGLPI/formcreator#97]
Bonjour,
Est-il possible d'ajouter une prise en charge des plages horaires et des jours fériés à l'ajout d'une date d'échéance ?
Merci d'avance,
Cordialement,

**Comment by neeftarah** [comment]
Bonjour,

C'est effectivement possible, en ajoutant la prise en charge des calendriers.
Ceci est toutefois une évolution demandant un peu de temps et je n'aurais pas le temps de m'en chargé à court terme.
