### ISSUE TITLE
v.2-6-2- Nom des fichiers joints

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/formcreator#975]
Suite #937, l'ajout de fichiers multiples fonctionne désormais.

J'ai constaté qu'à la génération du ticket, le nom des fichiers est préfixé d'une chaîne alpha numérique:

![nomfic_arallonge](https://user-images.githubusercontent.com/10028344/39238112-7828a1a2-488e-11e8-949e-0fbc2ae3e5e4.png)

Sur l'exemple, le nom original de mes fichiers étaient:
- SepC128GEN - Copie.pdf
- SepC128GEN.pdf

Ce renommage de fichier est-il "normal" ?

Merci

**Comment by btry** [comment]
Bonjour

Ce renommage est normal. Cependant,  il est peut être possible de récupérer le nom de fichier original. A étudier niveau faisabilité.

**Comment by matth974** [comment]
J'ai oublié de préciser que ce test est effectué en 9-2-1. Je vois dans un autre post qu'en 9-2-2 ce problème n'apparait pas et que les noms de fichiers sont corrects. A confirmer donc.
