### ISSUE TITLE
Request : ticket title

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/formcreator#977]
Hello

Is it possible to change the ticket title from a form answer ?

I tried by adding ##answer50## in ticket title but it disappears after saving

THanks for your answer

by the way, is it possible to add a question from plugin fields ?

**Comment by btry** [comment]
hi

> I tried by adding ##answer50## in ticket title but it disappears after saving

This is a bug and it is fixed in the develop branch. I wanted to release this week the version 2.6.3 but I'm still waiting for some feedbacks to add a few more fixes.

**Comment by btry** [comment]
Here is  the fix: https://github.com/pluginsGLPI/formcreator/pull/917
