### ISSUE TITLE
Bug.  Multiple file in same field

### ISSUE THREAD

**Issue by niloultimate** [pluginsGLPI/formcreator#979]
Problem with multiple files in the same field.
![1](https://user-images.githubusercontent.com/24455891/39429570-9c904636-4c61-11e8-9345-57a8d478506f.png)
![2](https://user-images.githubusercontent.com/24455891/39429571-9cba5174-4c61-11e8-9fb2-4c84892ae7ba.png)
[export_formcreator_20180430_1030.zip](https://github.com/pluginsGLPI/formcreator/files/1960705/export_formcreator_20180430_1030.zip)

**Comment by btry** [comment]
Hi

This is not supported yet.

**Comment by btry** [comment]
Hi

It is now possible to upload several files in the same file question type.
