### ISSUE TITLE
Community profile 

### ISSUE THREAD

**Issue by ajsb85** [pluginsGLPI/formcreator#983]
Hi, @Naylin15 

Please, create these files in this repository

- [x] README
- [x] Code of conduct
- [x] Contributing
- [x] License
- [x] Issue template and pull request template
- [x] GitHub App Settings
- [x] Project Site
- [x] Project Board
- [x] Milestones

Thank you.

**Comment by ajsb85** [comment]
@Naylin15 the branch is ready to use

**Comment by Naylin15** [comment]
Merci !
