### ISSUE TITLE
[2.6.3] hidden unless condition do not work anymore if type description

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/formcreator#988]
Hidden unless condition don't work anymore with the type Description 2.6.3 (2.5.2 before it works)
![img_003](https://user-images.githubusercontent.com/19192087/39706786-c73aa38e-5212-11e8-9e44-e281b93acd11.jpg)

result: the description is always displayed

**Comment by btry** [comment]
Hi 

If I remember correctly, descriptions are not conditionally displayed.  I'll check and allow it.

**Comment by Armin83** [comment]
GLPI 9.1.2
Formcreator 2.5.2
![img_004 - kopie](https://user-images.githubusercontent.com/19192087/39739361-cd474f2e-5290-11e8-8fc4-bd2e25cb05fb.jpg)
![img_007](https://user-images.githubusercontent.com/19192087/39739418-113fa79e-5291-11e8-8e62-b9cb47407ff5.jpg)
![img_006 - kopie](https://user-images.githubusercontent.com/19192087/39739358-cd1084e4-5290-11e8-8a6e-6096fe8dfbab.jpg)

`{"forms":[{"is_recursive":0,"access_rights":1,"requesttype":7,"name":"Reservierung von EDV-Ger&auml;ten f&uuml;r Besprechungen","description":"Hier k&ouml;nnen Sie Notebooks, Beamer und Zubeh&ouml;r f&uuml;r Besprechungen reservieren.","content":"","is_active":1,"language":"de_DE","helpdesk_home":1,"is_deleted":0,"validation_required":0,"is_default":0,"uuid":"4ec7f24b-8ade0ded-5ace04df0afa84.94598105","_plugin_formcreator_category":"&nbsp;","_sections":[{"uuid":"4ec7f24b-8ade0ded-5a950c82122252.29597108","name":"Reservierungen","order":1,"_questions":[{"uuid":"4ec7f24b-8ade0ded-5ace04a778f7f6.75528906","fieldtype":"select","name":"Notebooks","required":0,"show_empty":0,"default_values":"Kein Notebook ben&ouml;tigt","values":"Kein Notebook ben&ouml;tigt\r\n1 Notebook reservieren\r\n2 Notebooks reservieren\r\n3 Notebooks reservieren\r\n4 Notebooks reservieren\r\n","range_min":"","range_max":"","description":"","regex":"","order":8,"show_rule":"always","_conditions":[]},{"uuid":"4ec7f24b-8ade0ded-5ace04a6caec37.28049343","fieldtype":"checkboxes","name":"Beamer","required":0,"show_empty":0,"default_values":"","values":"Beamer reservieren","range_min":"","range_max":"","description":"","regex":"","order":9,"show_rule":"always","_conditions":[]},{"uuid":"4ec7f24b-8ade0ded-5ace04a5f25a44.16831938","fieldtype":"textarea","name":"Bemerkungen","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"&lt;p&gt;Sollten sonstiges Zubeh&ouml;r ben&ouml;tigt werden, oder Sie m&ouml;chten uns noch zus&auml;tzlich etwas mitteilen, dies bitte in dieses Textfeld eintragen&lt;/p&gt;","regex":"","order":10,"show_rule":"always","_conditions":[]},{"uuid":"4ec7f24b-8ade0ded-5ace04a8db57b3.97917260","fieldtype":"datetime","name":"Startzeit","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":6,"show_rule":"always","_conditions":[]},{"uuid":"4ec7f24b-8ade0ded-5ace04a81f4105.02043262","fieldtype":"datetime","name":"Endzeit","required":1,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"","regex":"","order":7,"show_rule":"always","_conditions":[]},{"uuid":"4ec7f24b-8ade0ded-5aa0e9a9d6ad18.21735906","fieldtype":"select","name":"Besprechungsort","required":1,"show_empty":1,"default_values":"","values":"EDV Schulungsraum\r\nEnergiekompetenzzentrum\r\nHaus Bergwald\r\nKonferenzraum\r\nExtern","range_min":"","range_max":"","description":"","regex":"","order":1,"show_rule":"always","_conditions":[]},{"uuid":"4ec7f24b-8ade0ded-5ace03bd5689d4.56871497","fieldtype":"description","name":"Vorhandene Hardware","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"&lt;p&gt;&lt;strong&gt;Es ist ein Fernseher und ein Laptop in diesem Raum vorhanden&lt;/strong&gt;&lt;/p&gt;","regex":"","order":2,"show_rule":"hidden","_conditions":[{"uuid":"4ec7f24b-8ade0ded-5ad729f71aba63.07519271","show_field":"4ec7f24b-8ade0ded-5aa0e9a9d6ad18.21735906","show_condition":"==","show_value":"EDV Schulungsraum","show_logic":"AND","order":1}]},{"uuid":"4ec7f24b-8ade0ded-5ace043a469813.89743645","fieldtype":"description","name":"Vorhandene Hardware","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"&lt;p&gt;&lt;strong&gt;Es ist ein Beamer in diesem Raum vorhanden&lt;/strong&gt;&lt;/p&gt;","regex":"","order":3,"show_rule":"hidden","_conditions":[{"uuid":"4ec7f24b-8ade0ded-5ad729fbd92728.61009511","show_field":"4ec7f24b-8ade0ded-5aa0e9a9d6ad18.21735906","show_condition":"==","show_value":"Energiekompetenzzentrum","show_logic":"AND","order":1}]},{"uuid":"4ec7f24b-8ade0ded-5ace046c22ff04.99494044","fieldtype":"description","name":"Vorhandene Hardware","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"&lt;p&gt;&lt;strong&gt;Es ist ein Beamer in diesem Raum vorhanden&lt;/strong&gt;&lt;/p&gt;","regex":"","order":4,"show_rule":"hidden","_conditions":[{"uuid":"4ec7f24b-8ade0ded-5ad72a0015c8b4.34983610","show_field":"4ec7f24b-8ade0ded-5aa0e9a9d6ad18.21735906","show_condition":"==","show_value":"Haus Bergwald","show_logic":"AND","order":1}]},{"uuid":"4ec7f24b-8ade0ded-5ace04a8db1954.14426977","fieldtype":"description","name":"Vorhandene Hardware","required":0,"show_empty":0,"default_values":"","values":"","range_min":"","range_max":"","description":"&lt;p&gt;&lt;strong&gt;Es ist ein Beamer in diesem Raum vorhanden&lt;/strong&gt;&lt;/p&gt;","regex":"","order":5,"show_rule":"hidden","_conditions":[{"uuid":"4ec7f24b-8ade0ded-5ad72a0445b128.14786291","show_field":"4ec7f24b-8ade0ded-5aa0e9a9d6ad18.21735906","show_condition":"==","show_value":"Konferenzraum","show_logic":"AND","order":1}]}]}],"_validators":[],"_targets":[{"uuid":"4ec7f24b-8ade0ded-5ae2c989063645.48214660","itemtype":"PluginFormcreatorTargetTicket","name":"Reservierung - EDV-Ger&auml;te","_data":{"name":"Reservierung - EDV-Ger&auml;te","comment":"<p>##FULLFORM##</p>","due_date_rule":"","due_date_question":0,"due_date_value":-30,"due_date_period":"minute","urgency_rule":"none","urgency_question":0,"validation_followup":1,"destination_entity":"requester","destination_entity_value":null,"tag_type":"none","tag_questions":"","tag_specifics":"","category_rule":"specific","category_question":40,"_tickettemplate":"Formular","_actors":[{"uuid":"4ec7f24b-8ade0ded-5a95537bf06c32.75396990","actor_role":"requester","actor_type":"creator","actor_value":null,"use_notification":1}]}}],"_profiles":[]}]}`
