### ISSUE TITLE
Issue to add a GLPI object in a form

### ISSUE THREAD

**Issue by chichtacos** [pluginsGLPI/formcreator#998]
Hi everyone,

To replace paper demands for account creations in my company, I'm creating a form under GLPI.

I would like to insert a GLPI object which show all the locations existing in GLPI. But they don't appears on the  dropdown choices : 
![image](https://user-images.githubusercontent.com/36413379/40108943-93a3ef44-58fc-11e8-9ec2-c0dddbd11dfc.png)

Is it possible to do that ? Or it's a future improvment of the plugin ?
I don't know if I'm clear enough..

My config : 
GLPI : 9.2.3
Formulaires plugin : 2.6.2

Thx a lot !

**Comment by btry** [comment]
Hi

You need to setup a question like this:

![image](https://user-images.githubusercontent.com/14139801/40109323-5eb13a34-58fd-11e8-9008-0b5c60006e71.png)

**Comment by chichtacos** [comment]
Perfect !!
I completly skipped the "intitulé" type...

I close this case then

Thx a lot :) :) :) :
